### ISSUE TITLE
Clearly label C vs C++ headers

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#1]
**Issue by [Delwin9999](https://github.com/Delwin9999) (MIGRATED)**
_Friday May 06, 2016 at 13:27 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/499_

----

Some of this repository is in C, other parts are in C++.  There are different headers necessary (inttypes.h vs. cinttypes) depending on what language you are compiling to.

Source files are already labels (_.c vs *.cpp).  I suggest that headers likewise be labelled (_.h vs. *.hpp) whereas currently all headers are *.h.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/lentinem"><img src="https://avatars3.githubusercontent.com/u/9709345?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lentinem](https://github.com/lentinem) (MIGRATED)**
_Friday May 06, 2016 at 14:42 GMT_

----

I'm not a fan of the h/hpp separation but I would like to pretty much uniformly make everything C++ over time so keeping this open to track that.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/jon-lunarg"><img src="https://avatars2.githubusercontent.com/u/6935198?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jon-lunarg](https://github.com/jon-lunarg) (MIGRATED)**
_Tuesday Jun 14, 2016 at 20:12 GMT_

----

If the loader and the layers no longer share any header files (except vk_layer.h) then we could more easily resolve this issue.

**Comment by mark-lunarg** [comment]
Since this issue was created, the loader-related files have been moved into a separate repository.  This should minimize, if not eliminate, uncertainty about the compilation target type.
