### ISSUE TITLE
Using the same attachment as a color & input attachment for a subpass triggers questionable warnings

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#10]
**Issue by [DominikWitczakAMD](https://github.com/DominikWitczakAMD) (MIGRATED)**
_Friday Oct 21, 2016 at 12:08 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1080_

----

Consider an app which uses a renderpass attachment X both as a color & an input attachment in the same subpass. This triggers the following warnings:

![image](https://cloud.githubusercontent.com/assets/17761066/19597860/80637d0a-9797-11e6-83ba-e975253d429d.png)

![image](https://cloud.githubusercontent.com/assets/17761066/19597891/aa5b07ae-9797-11e6-9766-00cdfbb7e6b2.png)

However:
- The attachment cannot be in COLOR_ATTACHMENT_OPTIMAL layout because that's illegal as per spec.
- The attachment cannot be in READ_ONLY_OPTIMAL layout because of the same reason.
- The attachment cannot be in two layouts at once :)

**Comment by karl-lunarg** [comment]
<a href="https://github.com/chrisforbes"><img src="https://avatars1.githubusercontent.com/u/128877?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Tuesday Oct 25, 2016 at 08:09 GMT_

----

Yep, that's pretty awful. To do this properly we need to combine all the constraints on the layout, rather than making a fuss about each constraint individually.

**Comment by locke-lunarg** [comment]
According to VkLayerTest.InvalidImageLayout, the issue should be solved.
