### ISSUE TITLE
How can I correlate object IDs with object addresses in tracing when using VK_LAYER_KHRONOS_validation?

### ISSUE THREAD

**Issue by StrayLightning** [KhronosGroup/Vulkan-ValidationLayers#1003]
When using the old VK_LAYER_LUNARG_standard_validation meta-layer, VK_LAYER_GOOGLE_unique_objects would get in the way of obtaining address references in tracing.  For example:

@[Validation]:  [ UNASSIGNED-vkCmdExecuteCommands-commandBuffer-00001 ] Object: 0x1306678f6e0 (Type = 6) | vkCmdExecuteCommands():: Executed secondary command buffer using image 0x73 (subresource: aspectMask 0x1 array layer 0, mip level 0) which expects layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL--instead, image current layout is VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL.

The problem is identifying what "image 0x73" corresponds to.  One option was to enable information level output from the validation layers, and tie up the object IDs with messages such as the following which were emitted after the objects are created:

INFO: @[ObjectTracker]: OBJ[0x72] : CREATE RenderPass object 0x65

However, commit 18bf5c637cb9ee403994003b63ea8d39558d7307 removed the information messages for tracked objects for performance reasons.

Another option was to replace VK_LAYER_LUNARG_standard_validation with the corresponding component layers but remove VK_LAYER_GOOGLE_unique_objects, which results in the object address being emitted in the tracing instead of its ID -- at the cost of some loss of validation.

With VK_LAYER_KHRONOS_validation my understanding (which admittedly might well be faulty) is that this is not a meta-layer, in which case I cannot replace it with a subset of its constituent layers.

When using VK_LAYER_KHRONOS_validation, how do I tie up object IDs to the corresponding object addresses in the tracing?

**Comment by mark-lunarg** [comment]
@StrayLightning, sorry that the changes have caused you trouble.  The easiest option here is to disable the handle-wrapping functionality that was previously provided by the unique_objects layer.  You can do this in a few ways, and maybe the [Layers Overview and Configuration doc](https://vulkan.lunarg.com/doc/sdk/1.1.108.0/windows/layer_configuration.html) might help.  To summarize, you can disable handle wrapping like so:

- Use the `VK_EXT_validation_features `extension, and set the `VK_VALIDATION_FEATURE_DISABLE_UNIQUE_HANDLES_EXT `flag
- Use the `vk_layer_settings.txt` file, setting the `khronos_validation.disables` flag to `VK_VALIDATION_FEATURE_DISABLE_UNIQUE_HANDLES_EXT `
- Use the `VK_LAYER_DISABLES `environment variable, setting it to `VK_VALIDATION_FEATURE_DISABLE_UNIQUE_HANDLES_EXT `

If having the information messages connecting the wrapped handles to the unwrapped handle values is extremely useful to you, please let us know and we'll consider a way to optionally supply them in the future (for instance, is this the main use-case for those messages?).  Thanks!

**Comment by StrayLightning** [comment]
Thanks, Mark.  Sorry, I had completely missed that feature.

It would be very useful to be able to map from IDs to addresses without otherwise influencing the tracing.  I don't know how feasible it is to add to the tracing for vkCreate* entrypoints to emit the wrapped handles.

**Comment by mark-lunarg** [comment]
@StrayLightning -- no problem at all.  The powers-that-be here have just reminded me of a fourth method, which is to use the **VkConfig** utility included in the Vulkan SDKs. We should be increasingly relying on this in the future.
