### ISSUE TITLE
Segmentation fault in latest validation layers

### ISSUE THREAD

**Issue by termhn** [KhronosGroup/Vulkan-ValidationLayers#1011]
With the latest release of the vulkan SDK/validation layers, we get a segfault originating in the validation layers on queue submit in [Amethyst](https://github.com/amethyst/amethyst). Reproduction is simple:

* Install latest vulkan SDK
* Install Rust
* Clone Amethyst
* Do `cargo run --example pong --features vulkan`

**Comment by mark-lunarg** [comment]
Can you share the validation errors received before the segfault, if any? It is sometimes the case that a condition reported as a validation error is unrecoverable and will eventually cause a crash in the layers or the driver.

**Comment by termhn** [comment]
Yeah, there were no validation errors received. Here's a full log and stack backtrace: https://gist.github.com/patrick-o-harrison/e37f6410032c2c517e48e29ba6f4c7a0

**Comment by mark-lunarg** [comment]
Thanks for the info! We'll take a look.

**Comment by mark-lunarg** [comment]
@termhn, I've not previously used Rust nor Amethyst.  Followed steps above, got past (?) an issue with 'fulltype', and now my terminal is staring at me like so:

```
mark@Maersk:~/dev/xgl/amethyst$ cargo run --example pong --features vulkan
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
    Updating registry `https://github.com/rust-lang/crates.io-index`
```

What is supposed to happen?  Any additional repro tips?  

Also, didn't see in the Amethyst repo where the validation layers were specified or referenced -- is this baked into some other component?  One thing at a time, I guess...

**Comment by termhn** [comment]
@mark-lunarg thanks for taking a look :) Those errors mean you probably have an outdated version of cargo/rustc installed (maybe from your distro's package manager?) I recommend installing it from https://rustup.rs/ which will get you the latest stable version.

The validation layers aren't directly referenced in the Amethyst repo, they're actually a couple dependencies deep :P Amethyst uses [rendy](https://github.com/amethyst/rendy) which is a framegraph + memory allocator + more stuff over top of [gfx-hal](https://github.com/gfx-rs/gfx) which is pretty much just a Rust-ification of the Vulkan API, and also has a translation layer to other backends (VKPI). 

But when using the Vulkan backend (which you are specifying with `--features vulkan`), it loads the validation layers here: https://github.com/gfx-rs/gfx/blob/129da5cb3b778ba399a02155246cb7d9bb96d83f/src/backend/vulkan/src/lib.rs#L352-L415 

and the layers that get requested is defined here: https://github.com/gfx-rs/gfx/blob/129da5cb3b778ba399a02155246cb7d9bb96d83f/src/backend/vulkan/src/lib.rs#L70-L82

**Comment by mark-lunarg** [comment]
Ah, I guess I *had* used rust, since my install was from 2017.  Updated, and you were absolutely right, it was simple -- I see that the layers are loaded correctly but are crashing.  May have more questions later!

**Comment by termhn** [comment]
Sure thing, ask away :D

**Comment by mark-lunarg** [comment]
@termhn, it *looks like* the crash happens with or without the layers.  You can try this by setting the following environment variable:

`export VK_LAYER_PATH=ANY_OLD_GARBAGE`

and then run the command line you supplied. This env var tells the loader to use that location for the layers, and if they aren't there they won't be loaded.  I also tried with the 1.1.106 SDK and see the same behavior.

While it doesn't appear related to the layers, it might stem from a [known loader issue](https://github.com/KhronosGroup/Vulkan-Loader/issues/116).  I can see from the API Dump that the last call completed looks to be `vkGetPhysicalDeviceSurfacePresentModesKHR`.  If the next call is one of the device-level DebugUtils functions, that could explain things.

**Comment by termhn** [comment]
Hm, interesting... for me (and others who have had this issue with Amethyst), downgrading to 1.1.106 SDK has solved the issue.

**Comment by mark-lunarg** [comment]
@termhn, were you able to determine if amethyst is calling a device-level extension function related to DebugUtils after the GetPhysicalDeviceSurfacePresentModes call?

**Comment by termhn** [comment]
Haven’t had a chance to look yet

**Comment by jaynus** [comment]
Hi, I'm another developer on the Amethyst project with @termhn 

Using the provided environmental variable, I do *not* receive a crash when disabling the validation layers.

- `VK_LAYER_PATH=asdf cargo run --example pong --features vulkan` Runs successfully for me with no crash.

- `cargo run --example pong --features vulkan` crashes inside `libVkLayer_khronos_validation`

So it appears its definitely only with the validation layers, somehow with our usage and the layers.

There doesn't appear  to be any calls to any DebugUtil functionality aftert

In my segfault, I do not have a crash after `vkGetPhysicalDeviceSurfacePresentModesKHR`, my crash is always after submitting a frame and after `vkEndCommandBuffer`. `vkGetPhysicalDeviceSurfacePresentModesKHR` is always followed by `vkGetPhysicalDeviceSurfaceSupportKHR` then `vkCreateImage`. I think your test environment may not be matching ours for behavior. 

I've uploaded a full API trace here (this was with VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_api_dump)
https://gist.github.com/jaynus/b86cb8945a3f5e901fcc3804650eee8a

**Comment by jaynus** [comment]
After further debugging, I can tell you the crash definitely only occurs in `VK_LAYER_LUNARG_core_validation`.

All other layers operate fine.
```
export VK_INSTANCE_LAYERS=VK_LAYER_GOOGLE_threading:VK_LAYER_LUNARG_parameter_validation:VK_LAYER_LUNARG_device_limits:VK_LAYER_LUNARG_object_tracker:VK_LAYER_LUNARG_image:VK_LAYER_LUNARG_swapchain:VK_LAYER_GOOGLE_unique_objects 
export CARGO_MANIFEST_DIR=/home/jaynus/dev/amethyst/ 

target/release/examples/pong
```
Executes successfully. Adding `VK_LAYER_LUNARG_core_validation` crashes.

**Comment by mark-lunarg** [comment]
@jaynus, thanks, this is extremely helpful.  Obviously, my dev env is set up incorrectly.  To get the SDK, I just downloaded the gzip, unzipped it into a local directory, and ran the `setup-env.sh` script.  I have the `1.37.0-nightly` version of rustc installed, `58c1053c5d `of the Master branch of amethyst, and the Nvidia 415.22.06 driver installed.  Any suggestions?

**Comment by mark-lunarg** [comment]
Also, just for grins, where did you get the swapchain and dev_limits layers?

**Comment by jaynus** [comment]
> @jaynus, thanks, this is extremely helpful. Obviously, my dev env is set up incorrectly. To get the SDK, I just downloaded the gzip, unzipped it into a local directory, and ran the `setup-env.sh` script. I have the `1.37.0-nightly` version of rustc installed, `58c1053c5d `of the Master branch of amethyst, and the Nvidia 415.22.06 driver installed. Any suggestions? All this is on Ubuntu 16.04.

My nightly was a bit old, so I just upgraded my nightly to match `rustc 1.37.0-nightly (d3e2cec29 2019-06-26)` and tested, it still occurs. 

You may need to `cargo clean` to make sure everything gets rebuilt again with the new toolchain. I confirm `58c1053c5d` is definitely still exhibiting the bug for us. 


If not, here are some reproducible steps. 
First, make sure you have git lfs installed. This might be the issue, as you need to `git lfs pull` our repo as well.  Instructions for your distro here: https://github.com/git-lfs/git-lfs/wiki/Installation
```sh
rm -rf ~/.cargo && rm -rf ~/.rustup
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    Press 2, enter, Type nightly, enter.
    Press 1, enter
git clone --depth 1 https://github.com/amethyst/amethyst.git
cd amethyst
git lfs pull
```
At this point, you can `cargo run --example pong --features "vulkan"` which should segfault. 

As an FYI, this builds our debug target, which is in `target/debug/examples/pong`. gfx-hal by default, for debug builds, enables the validation layers. 

> Also, just for grins, where did you get the swapchain and dev_limits layers?

Google returned an ancient version of the docs I used real quick to see: https://vulkan.lunarg.com/doc/view/1.0.13.0/windows/layers.html was my first google result :P Since you ask, I just repeated with the latest docs. 
I had to remove `VK_LAYER_KHRONOS_validation` and `VK_LAYER_LUNARG_core_validation` to get things to execute correctly.

**Comment by termhn** [comment]
I have a new hint/lead on this from this issue https://github.com/amethyst/rendy/issues/171

This segfault only occurs when using rendy's `PresentNode`, which is a node that does an image copy from an intermediate image into a swapchain image and then presents the swapchain image to the screen. The rendy `triangle` example does not use this node and instead renders directly into the swapchain image, and evidently does not cause this bug. Perhaps that is helpful in trying to narrow down what's going on...

**Comment by mark-lunarg** [comment]
@termhn, @jzulauf-lunarg, @jeremy-lunarg, and I root-caused the issue today, and there'll be a PR tomorrow. Turned out to be related to the image layout tracking in secondary command buffers. Thanks again for the outstanding repro-case help!

**Comment by termhn** [comment]
@mark-lunarg Awesome! Thank you for the great communication & quick response :D
