### ISSUE TITLE
Assert or abort (at least optionally) on undefined behavior.

### ISSUE THREAD

**Issue by reduz** [KhronosGroup/Vulkan-ValidationLayers#1012]
Today I found out that forgetting a vkEndCommandBuffer before vkQueueSubmit hard-crashes 
Ubuntu Linux running RADV driver to the point I can't even ssh from the outside. 

Asking around, I found that this is fine, given it's undefined behavior.

This is a very simple error that I'm sure the validation layer was catching, but I could never read.  

I think it would be very useful to abort (or at least making it to optionally abort) on undefined behavior, after displaying the error.

**Comment by reduz** [comment]
Even if the validation layer would not abort, at least finding out that something is undefined behavior could be useful, so I can abort myself.

**Comment by reduz** [comment]
I realize now i could just abort on any error and would be able to work around this, so not quite sure if there is any way to tell which errors have the potential to crash a driver, I may be asking for too much I guess.

**Comment by mark-lunarg** [comment]
@reduz, yes, if you received a validation error, you could intercept it in your callback and take appropriate action.  In fact, **any** validation error  places the application in 'undefined behavior' territory. We have medium-term plans to stop/short-circuit validation upon encountering certain kinds of errors, which should help to avoid some crashes and to place more focus on critical errors.

**Comment by mark-lunarg** [comment]
I'm going to close this issue for now -- if you find that you did NOT get any validation errors before the hard-crash, please reopen this issue and we'll try to get a repro ASAP.  Thanks!
