### ISSUE TITLE
Validation layers print errors when creating a device using supported device features from extensions

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#102]
**Issue by [Whenning42](https://github.com/Whenning42) (MIGRATED)**
_Friday May 11, 2018 at 16:42 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2670_

----

Creating a device with supported physical device features added by extensions prints errors. It looks like the validation layers are currently only tracking physical device features returned from a call to vkGetPhysicalDeviceFeatures, and so the layers think any physical device features added by extensions are unsupported.

An example of this is that running the following code using the testing framework:
```c++
ASSERT_NO_FATAL_FAILURE(InitFramework(myDbgFunc, m_errorMonitor));
auto indexingFeatures = lvl_init_struct<VkPhysicalDeviceDescriptorIndexingFeaturesEXT>();
auto features2 = lvl_init_struct<VkPhysicalDeviceFeatures2KHR>(&indexingFeatures);
vkGetPhysicalDeviceFeatures2(gpu(), &features2);
ASSERT_NO_FATAL_FAILURE(InitState(nullptr, &features2));
```

prints the following errors:
```
Unexpected: Object: VK_NULL_HANDLE (Type = 2) | While calling vkCreateDevice(), requesting feature 'textureCompressionETC2' in VkPhysicalDeviceFeatures struct, which is not available on this device.
Unexpected: Object: VK_NULL_HANDLE (Type = 2) | While calling vkCreateDevice(), requesting feature 'textureCompressionASTC_LDR' in VkPhysicalDeviceFeatures struct, which is not available on this device.
Unexpected: Object: VK_NULL_HANDLE (Type = 2) | You requested features that are unavailable on this device. You should first query feature availability by calling vkGetPhysicalDeviceFeatures().
```

**Comment by karl-lunarg** [comment]
@tobine Can this (and the LVL issue KhronosGroup/Vulkan-LoaderAndValidationLayers#2670) issue be closed?  Pull Request KhronosGroup/Vulkan-LoaderAndValidationLayers#2673 was submitted.  But I can't tell if that PR completely addresses the issue.

**Comment by mark-lunarg** [comment]
This looks to have been fixed.
