### ISSUE TITLE
ImageLayoutMap might have order issue in CoreChecks::ValidateCmdBufImageLayouts

### ISSUE THREAD

**Issue by locke-lunarg** [KhronosGroup/Vulkan-ValidationLayers#1020]
[PR #1018 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1018)

CoreChecks saves imageLayout in map. (`CoreChecks::SetLayout`) But the index of data in map doesn't follow when it adds, so when it runs the whole ImageLayoutMap in `CoreChecks::ValidateCmdBufImageLayouts`, the data order might be different with the command order.

For example: I add command `vkCmdPipelineBarrier`, and then add `vkCmdCopyImage`. But sometimes, in `CoreChecks::ValidateCmdBufImageLayouts`, it runs `vkCmdCopyImage` first, and then runs `vkCmdPipelineBarrier`.

**Comment by mark-lunarg** [comment]
Fixed by PR #1018.

**Comment by locke-lunarg** [comment]
The description is not correct. The real problem is about memory aliasing.
