### ISSUE TITLE
The viewportCount and scissorCount members of VkPipelineViewportStateCreateInfo aren't validated

### ISSUE THREAD

**Issue by JoergArm** [KhronosGroup/Vulkan-ValidationLayers#1032]
The specification states that those members must be within [1;VkPhysicalDeviceLimits::maxViewports].
We hit at least one case in the Conformance tests where 0 (for the scissorCount member) was supplied, internal CTS issue #1857.
Is it possible to add the appropriate validation?

**Comment by mark-lunarg** [comment]
@JoergArm, validation for the two implicit VUs ("`VUID-VkPipelineViewportStateCreateInfo-viewportCount-arraylength`" and "`VUID-VkPipelineViewportStateCreateInfo-scissorCount-arraylength`") is implemented, along with checks for "`VUID-VkPipelineViewportStateCreateInfo-scissorCount-01216`" through 01219, along with validation tests.  Can you point me to one or more of the CTS tests that were failing so I can investigate the discrepancy?  Thanks!

**Comment by JoergArm** [comment]
Thanks for pointing out the specific commit - cross-checked, and indeed the validation happens after that revision.
