### ISSUE TITLE
stateless\parameter validation is not resistant to `nullptr`

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-ValidationLayers#1039]
Stateless\parameter validation is not resistant to `nullptr` required parameters. PR #1038 to demonstrate.

The main problem is "manual" checks are performed before the automatic checks. And the manual checks (rightly?) do not worry about `nullptr` arguments.

Should perhaps the order of checks be reversed?

**Comment by mark-lunarg** [comment]
@krOoze, this is a great idea.  Will get on it directly.

**Comment by krOoze** [comment]
Hmm, there is also a somewhat minor problem that this is untestable. If it crashes test count it as fail, even if the error mesage was produced earlier.

Perhaps it should be spread in two sublayers of `parameter_implicit` and `parameter_manual`?
