### ISSUE TITLE
Race condition in vkCreateDevice()+vkDestroyDevice()+vkGetDeviceProcAddr()

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-ValidationLayers#1044]
Say we have N threads living in the same process that call the three functions. They may be referring to any valid logical device, possibly using different Vulkan instances.

vkCreateDevice() and vkDestroyDevice() require external synchronization but vkGetDeviceProcAddr() does not. Furthermore, external synchronization only refers to the device instance in question, not to all logical devices spawned by the process.

I'm seeing a crash in the loader when a random thread calls vkGetDeviceProcAddr(). Here's some screenshots:

![image](https://user-images.githubusercontent.com/17761066/60895783-82b7f000-a265-11e9-8dab-dc96da9c97fa.png)

![image](https://user-images.githubusercontent.com/17761066/60895813-92cfcf80-a265-11e9-98af-e17d408c0a9a.png)

![image](https://user-images.githubusercontent.com/17761066/60895836-9d8a6480-a265-11e9-911c-f32b0e1ac605.png)

![image](https://user-images.githubusercontent.com/17761066/60895860-a8dd9000-a265-11e9-8044-8238fa88c639.png)

![image](https://user-images.githubusercontent.com/17761066/60895891-aed37100-a265-11e9-9259-6036a93c83d7.png)

From the above, the only logical conclusion is that either dev->icd_device or dev->chain_device is nullified while loader_get_dispatch() is being called, which suggests a race condition.

Wrapping a global lock around all invocations of vkCreateDevice(), vkDestroyDevice() and vkGetDeviceProcAddr() functions in the said process , while something I'd prefer not to be doing, appears to fix the problem.

**Comment by mark-lunarg** [comment]
Hey @DominikWitczakAMD, I can't see much of the call stack, but i'm *guessing* that the layers aren't loaded, or at the very least, that they're not required to observe the race condition?  If that is the case, I'd respectfully ask that a corresponding issue be opened in the [Vulkan-Loader repository](https://github.com/KhronosGroup/Vulkan-Loader). Thanks!

**Comment by DominikWitczakAMD** [comment]
Apologies, you're right. I guess it was late when I was opening this ticket. Moving the ticket now.

**Comment by DominikWitczakAMD** [comment]
Opened https://github.com/KhronosGroup/Vulkan-Loader/issues/200 .

**Comment by mark-lunarg** [comment]
No worries, and thanks.  I've already spoken with @lenny-lunarg about the issue.
