### ISSUE TITLE
VS project dependency is incorrect

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-ValidationLayers#1045]
Project dependency in the generated VS solution is incorrect.
E.g. the tests should imo depend on the layers, otherwise it accidentaly tests the unmodified (old) build of layers and lead to serious head scratching.

PS: it is also bit annoying some things (re)build even when there're no changes.

**Comment by mark-lunarg** [comment]
I think the PR has a sufficient remedy for this issue.  As for the unnecessary rebuilds, we will address those items after the pre-baked codegen and legacy layer deprecation land.
