### ISSUE TITLE
Crash in SHADER_MODULE_STATE::BuildDefIndex

### ISSUE THREAD

**Issue by joey-sketchup** [KhronosGroup/Vulkan-ValidationLayers#1060]
Hey guys :)

I'm running pretty basic test shaders and debugging creation of shader modules when I ran into a crash in vkCreateShaderModule. Building with the tip of master of Vulkan-ValidationLayers I found it crashed at line 68 of shader_validation.cpp in SHADER_MODULE_STATE::BuildDefIndex(). Looks like the crash is due to the iterator going off of the end of the data.

Right before the crash the following validation error was emitted:
`UNASSIGNED-CoreValidation-Shader-InconsistentSpirv(ERROR / SPEC): msgNum: 0 - SPIR-V module not valid: End of input reached while decoding OpCompositeExtract starting at word 438: missing result ID operand at word offset 2.
    Objects: 1
        [0] 0, type: 0, name: NULL`

-- Edit: Irrelevent info removed --

SDK Version: 1.1.108.0

**Comment by joey-sketchup** [comment]
Commenting out line 111 in shader_validation.h in SHADER_MODULE_STATE::PreprocessShaderBinary, which prevents that iterator from terminating when it finds the first "OpFunction" I see the same crash.

So it seems the crash is with the spirv_inst_iter itself, and I notice it's incrementing the iterator based on the upper 16 bits of the current word... and looking at the SPIR-V spec this makes sense.

So is this code not meant to be idiot proof? The spirv_inst_iter is trusting that the data is formatted sanely. Not sure if it fits within the philosophy of the validation layers to add some sort of check before running the iterators to see if the flow of the SPIR-V instructions makes sense and report and error otherwise.

**Comment by jeremy-lunarg** [comment]
Validation layer behavior is undefined after detection/reporting of validation errors.

Also, use spirv-val to validate spirv. glslangValidator does not validate spirv.
