### ISSUE TITLE
Strange error and crash with wrongly reported bound descriptor

### ISSUE THREAD

**Issue by reduz** [KhronosGroup/Vulkan-ValidationLayers#1070]
I am getting this error:

```
ERROR: _debug_messenger_callback: ERROR : VALIDATION - Message Id Number: 0 | Message Id Name: UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotBound
	VkPipeline 0x259 uses set #1 but that set is not bound.

	Objects - 1
		Object[0] - VK_OBJECT_TYPE_COMMAND_BUFFER, Handle 0x76a45e0

```

And subsequently a crash in the validation layers.

I checked a thousand times and the set #1 _is_ bound. 

Running my code without validation layers works fine, and when running under RenderDoc, it shows that set #1 is perfectly bound, so it appears to me that this is a bug in the validation layer.

I have no idea how to reproduce this for you to test. Is a RenderDoc capture good enough?

EDIT: Here is a renderdoc capture that crashes the validation layer. You can observe that set #1 _is_ actually bound.
[ssc.zip](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/3413855/ssc.zip)

**Comment by reduz** [comment]
This issue is extremely annoying, any help figuring out what is going one is very welcome.

**Comment by jeffbolznv** [comment]
My only thought is that maybe the descriptor set was bound to the wrong pipeline bind point?

I'm unable to load the renderdoc because it's incompatible with my system (win10, NVIDIA RTX 2070). If you could capture the failure on a config like that I can take a look.

**Comment by reduz** [comment]
I wish I had hardware like that :wink:. Is there a better way I could do some capture that will run on that hardware? 

I tried to use  vktrace, but It's really difficult to compile in Ubuntu without replacing all my system headers and break my install (wish Khronos could work on that.. and make it easier to distribute), so RenderDoc is all I have. Codebase is far too complex to make a simple test (it's an entire game engine).

**Comment by jeffbolznv** [comment]
Do you have a win10 system you can capture on with any NVIDIA GPU? I should be able to match the GPU closely enough.

**Comment by KarenGhavam-lunarG** [comment]
Yes, we saw your issue about [building vktrace on ubuntu 19.04](https://github.com/LunarG/VulkanTools/issues/856) and responded with a suggestion. Builds do not modify system files and you may need to be following the steps in the build.md.

**Comment by reduz** [comment]
@jeffbolznv I have a notebook with a 1060, if that's enough will try tomorrow.

**Comment by jeffbolznv** [comment]
I think it should be.

**Comment by reduz** [comment]
To update on this, it seems the pipeline layouts were actually not correct (due to a strange issue I have with GLSLang, will try to report there afterwards), generating a different descriptor set that could not be bound.

The issue is then, shouldn't the validation layer be able to easily recognize this situation? Something is bound, then at draw time a check is done so that the descriptor set layout is different and warns about this, instead of just reporting that it was not bound. This was very confusing for me, as I thought I wasn't setting anything when it actually was, but was wrong.

**Comment by reduz** [comment]
OK, nevermind, I finally understood what is going on.. 
* I thought I was using compatible pipeline layouts for the previous sets from the one I'm trying to bind because they have the same uniforms
* However, I don't use some of these (in code) in some shader versions and GLSlang gets rid of them when compiling to SPIR-V.
* As a result, the lower sets were being unbound... I see it can be difficult to show a warning about this, but I still wish it was the case.

I still believe, if possible to modify this validator warning and add the extra information that the set was unbound because of using a different pipeline layout on lower layers), that would be very appreciated (it would definitely had saved me a huge amount of time).

**Comment by mark-lunarg** [comment]
@jzulauf-lunarg, any ideas for connecting these two occurrences (pipeline incompatibility/unbound descriptor set checks)?

**Comment by jzulauf-lunarg** [comment]
@mark-lunarg potentially we could track an "unbound by command" record when the the bound set is invalidated similar to the way we track some of "image layout need by command" information for image layout mismatch messages.  I wouldn't wan't to create "yet another special case", but probably we should think about some general way to store causal information for these and other "deferred validation" situations.

**Comment by mark-lunarg** [comment]
@reduz, thanks for running this down.  We'll add saving some metadata for deferred validation checks to our internal design list.

**Comment by reduz** [comment]
Thanks to you guys!
