### ISSUE TITLE
Missing validations related to fragmentDensityMap features

### ISSUE THREAD

**Issue by ByumjinConffx** [KhronosGroup/Vulkan-ValidationLayers#1097]
Hello,

I have checked the validation codes related to fragmentDensityMap.
It seems like several validations, even if they are already mentioned in Vulkan document, are not implemented.
For example, like

>"VUID-VkRenderPassFragmentDensityMapCreateInfoEXT-sType-sType",
"VUID-VkFramebufferCreateInfo-flags-03194",
"VUID-VkRenderPassFragmentDensityMapCreateInfoEXT-fragmentDensityMapAttachment-02547",
>

These are already registered in `vk_validation_error_messages.h` but I could not find the codes to validate these.

If it is true and no one have a plan to work for this, I would like to help to add the missing validation codes.

**Comment by mark-lunarg** [comment]
@ByumjinConffx, you are correct, and any progress you can make on these 'incomplete' VUs would be greatly appreciated by the community. Please give the [CONTRIBUTING.md document](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/CONTRIBUTING.md) a quick look, and if you have any questions you can post them here or contact me directly at mark@lunarg.com.  Thanks!
