### ISSUE TITLE
Validation for render passes could be more specific

### ISSUE THREAD

**Issue by nickyc95** [KhronosGroup/Vulkan-ValidationLayers#1102]
When using a render pass with an initial layout that is not `VK_IMAGE_LAYOUT_UNDEFINED` and where the actual image layout is not what was specified in initialLayout, it would be nice to get a better error message.

Currently if you do this you will get:
 ` Submitted command buffer expects image 0x25 (subresource: aspectMask 0x2 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL--instead, image 0x25's current layout is VK_IMAGE_LAYOUT_UNDEFINED.`

It would be nice if it was a bit more specific and pointed you towards the render pass, instead of the generic error.

Cheers! 👍

**Comment by krOoze** [comment]
I think it is probably duplicate of #466.

**Comment by nickyc95** [comment]
> I think it is probably duplicate of #466.

It looks like you are correct... I'll close this issue.

Thanks

**Comment by mark-lunarg** [comment]
Thank you @krOoze!  Beat me to it.  Thanks @nickyc95 for the report.  I'll bump the priority there.
