### ISSUE TITLE
coverity scan results for 1.1.114 SDK tag

### ISSUE THREAD

**Issue by airlied** [KhronosGroup/Vulkan-ValidationLayers#1106]
[scan-results.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/3479564/scan-results.txt)

I recently packaged 1.1.114 and it got ran through our coverity scanner, I've attached the results here, there are a bunch of uninitialised C++ constructor problems and some deadcode ones, there might be a bunch of actual bugs in here as well, I'd appreciate if someone had a chance to look over it.

**Comment by tobine** [comment]
Whoa, thanks, @airlied. Definitely some low-hanging fruit here that needs to be fixed and lots more cleanup and potential issues. Huge bulk of safe-struct issues that can potentially be fixed en masse as that code is generated.
Looks like @krOoze has already jumped on some fixes (thanks!). I encourage any other enterprising devs who want to help out to do the same.
If you don't mind, @airlied, you could post an updated scan now that @krOoze's fixes have landed, and as any more fixes come in.

**Comment by krOoze** [comment]
I will just piggyback to this issue, that there are ~25 static analysis warnings in VS2019.

**Comment by airlied** [comment]
Our coverity instance is also unfortunately quite far down the production line, so to test master I'd have to bring in master of a bunch of other packages, which I can only really do easily on sdk rebases. I could probably backport some of the fixes into my 1.1.114 tree and check them.

**Comment by krOoze** [comment]
@airlied Nobody cared thus far; I guess there's no harm now waiting for next SDK release. 
So far I crossed off only `DEADCODE`, `DIVIDE_BY_ZERO, and some `FORWARD_NULL`. Rest should still be the same.

**Comment by krOoze** [comment]
I think I covered all the actionable items in previous or outstanding PRs...

**Comment by mark-lunarg** [comment]
Closing for now, thanks a bunch guys!

**Comment by krOoze** [comment]
@airlied BTW: new SDK is out if you feel like rescanning this...
