### ISSUE TITLE
Remove mem_info->bound_ranges tracking?

### ISSUE THREAD

**Issue by jeffbolznv** [KhronosGroup/Vulkan-ValidationLayers#1109]
I'm running the validation layers with a recently released game where the layers introduce a stall for about 30 seconds at level load time, with all the time spent in ValidationStateTracker::RangesIntersect. This app binds thousands of VkBuffers to a VkDeviceMemory, and the range intersection tracking is O(N^2).

All this alias tracking is only used to generate a warning about behavior that is actually legal, albeit maybe uncommon (aliasing linear and non-linear memory). This warning is pretty similar to the warning that was recently removed in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1006, and I wonder if we can just remove the bound_ranges tracking entirely.

If folks agree that it's OK to remove, I'm happy to make a PR for it.

**Comment by mark-lunarg** [comment]
@jeffbolznv, I added a ref to the [assistant layer](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/24) for the warning, and we all agree here that you can kill it with fire.

**Comment by mark-lunarg** [comment]
Fixed in #1119.
