### ISSUE TITLE
Safe structs need to initialize pNext in default constructors

### ISSUE THREAD

**Issue by jmacnak-nv** [KhronosGroup/Vulkan-ValidationLayers#1113]
Currently, layers/generated/vk_safe_struct.cpp has

safe_VkAccelerationStructureInfoNV::safe_VkAccelerationStructureInfoNV() :
    pGeometries(nullptr)
{}

which doesn't initialize the 

const void* pNext

which causes issues on destruction.

**Comment by mark-lunarg** [comment]
Fixed by #1114.
