### ISSUE TITLE
Shader validation seems to not be integrated correctly

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/Vulkan-ValidationLayers#112]
When trying to feed an invalid SPIRV into vkCreateShaderModule with validation layers active and debug callback set up, I get the following behavior on 1.1.73 on Windows:

During vkCreateShaderModule, the following message is printed to debug output:
> Validation (ERROR): msg_code: 5: Object: VK_NULL_HANDLE (Type = 0) | SPIR-V module not valid: End of input reached while decoding OpCompositeConstruct starting at word 1467: missing ID operand at word offset 3.

The message does *not* go through the debug callback I've registered - it seems to be some hardwired mechanism.
Additionally, vkCreateShaderModule does *not* fail in this case - presumably, the driver (NVidia in this case) doesn't validate SPIRV at this time.

This makes these issues harder to diagnose. It would be nice if the error was routed through debug callback, *and* vkCreateShaderModule failed in this case.

**Comment by zeux** [comment]
Yeah - other messages *are* coming through callback, it's only these that don't. I'm registering the callback by using EXT_debug_report and chaining the struct to instance info:

		debugReportCallbackCreateInfo.sType = VK_STRUCTURE_TYPE_DEBUG_REPORT_CREATE_INFO_EXT;
		debugReportCallbackCreateInfo.flags = VK_DEBUG_REPORT_ERROR_BIT_EXT | VK_DEBUG_REPORT_WARNING_BIT_EXT | VK_DEBUG_REPORT_PERFORMANCE_WARNING_BIT_EXT;
		debugReportCallbackCreateInfo.pfnCallback = &debugReportCallback;

		instanceInfo.pNext = &debugReportCallbackCreateInfo;

Not sure if this is related... I'll try to make a repro case.

**Comment by courtney-g** [comment]
Spec:
To capture events that occur while creating or destroying an instance an application can link a VkDebugReportCallbackCreateInfoEXT structure to the pNext element of the VkInstanceCreateInfo structure given to vkCreateInstance. **This callback is only valid for the duration of the vkCreateInstance** and the vkDestroyInstance call. Use vkCreateDebugReportCallbackEXT to create persistent callback objects.

There is no way to destroy a debug report callback chained at CreateInstance time so we limit it's lifetime to just that call.

**Comment by zeux** [comment]
Gotcha, thanks! Then this is just the confusion on my part, sorry about that.

I was assuming that chaining VkDebugReportCallbackCreateInfoEXT is just a simpler way to register a callback and that it persists for the duration of the instance. I don't quite understand why the callback is valid for the duration of vkCreate/vkDestroy but *not* the interval between them, but I'm happy to change the code back to an explicit callback creation.
