### ISSUE TITLE
Would it be an issue to complexify VUID tag names a bit?

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-ValidationLayers#1130]
We have some internal script changes queued up that may result in implicit VUID names like

> VUID-vkAllocateCommandBuffers-pAllocateInfo::commandBufferCount-arraylength

Will this be a problem for the validation layers' consumption of them through validusage.json, or however else you might get at them? I want to be precise in the style guide about what can go in the components of VUID tags - it's unspecified today - and at least for now, limit it to [A-Za-z0-9:]+ .

**Comment by KarenGhavam-lunarG** [comment]
Notifying @shannon-lunarg and @mikes-lunarg

**Comment by mikes-lunarg** [comment]
Most of the validation code that deals with VUIDs treats them as arbitrary strings so it shouldn't matter if we allow more non-alphanumeric characters.

If any current VUIDs are *changing* there will obviously be some work to move existing automated and manually written code over to the new naming scheme.

**Comment by krOoze** [comment]
Shouldn't be so hard.
Why though? Isn't point of VUID to be somewhat permanent identifier?
It is bit of a transitional problem, as links in the error msgs would have dead link into the spec. Unless spec and SDK release is synchronized.

**Comment by oddhack** [comment]
There are not significant changes in existing VUIDs. Maybe one or two. Thanks @mikes-lunarg .
