### ISSUE TITLE
Update validation of VK_KHR_shader_float_controls

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-ValidationLayers#1133]
Note that VK_KHR_shader_float_controls was updated in [v4](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/chap44.html#VK_KHR_shader_controls_v4_incompatibility) to remove separateDenormSettings & separateRoundingModeSettings bools.
This will cause issues with the next header roll as shader\_validation layer is using those bools. Please update VK\_KHR\_shader\_float\_controls support in validation layers to comply with the latest version of the extension so that headers can be updated without error.

**Comment by critsec** [comment]
Turns out @jekstrand already created PR #1096 to fix this, but it's been held up on other issues.

**Comment by tobine** [comment]
This was fixed in the 1.1.119 Header [merge](https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/3cc90bcf8cfef52366a93c62d66ec8eef09b7059)

**Comment by locke-lunarg** [comment]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1144
