### ISSUE TITLE
Stateless Validation does not track VkPhysicalDeviceFeatures2

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-ValidationLayers#1147]
Stateless Validation does not support VkPhysicalDeviceFeatures2.
Tracking it in its state could facilitate validation of further (extension) VUIDs.

**Comment by jeffbolznv** [comment]
@mark-lunarg @jzulauf-lunarg or others, is there any rule against capturing enabled features in stateless validation? I'm going to implement VK_EXT_line_rasterization validation very soon and this affects where I would put most of it.

**Comment by krOoze** [comment]
Enabled features are already tracked. Just not the extension\1.1 `Features2` variant.
