### ISSUE TITLE
Buffer <-> Image copy VU checks don't adjust subresource extents for compressed formats

### ISSUE THREAD

**Issue by peterfsat** [KhronosGroup/Vulkan-ValidationLayers#1155]
Both buffer -> image and image -> buffer copy pre-call validation routines call `ValidateBufferImageCopyData` as the first step, where the image extents are checked against the "adjusted" image extents as calculated by `GetImageSubresourceExtent`.

However, for compressed formats, the "adjusted" extents should be at least the size of the texel block - this is accounted for in `ValidateImageBounds`, for example.

**Comment by daveh-lunarg** [comment]
I can't spot an error in the validation code here. `GetImageSubresourceExtent` (which could possibly be better named) calculates the available extent _in texels_ for an image's specified mip level, which is independent of image format. Then (for compressed formats only) the copy region is checked against the available extent according to the compressed-block constraint VUs, e.g. 
```
If the calling command’s VkImage parameter is a compressed image, or a single-plane, “
_422” image format, imageExtent.width must be a multiple of the compressed texel block
width or (imageExtent.width + imageOffset.x) must equal the image subresource width.
```

If you can provide a specific example that produces an erroneous validation, that would be helpful to understand the exact issue being reported.

**Comment by peterfsat** [comment]
You're very right Dave, I've got this the other way around.

Apologies for the invalid issue.

**Comment by daveh-lunarg** [comment]
No worries.
