### ISSUE TITLE
Please keep deleting old branches

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-ValidationLayers#1161]
Please keep deleting old branches.

Especially merged ones have no reason to exist. So I would also recommend to add setting that does that automatically:
https://help.github.com/en/articles/managing-the-automatic-deletion-of-branches

**Comment by mark-lunarg** [comment]
Done, thanks for the great suggestion.

**Comment by krOoze** [comment]
That applies to any future branches, I think. Old branches still need to be deleted manually.

**Comment by mark-lunarg** [comment]
Did some cleaning up there as well.
