### ISSUE TITLE
GpuValidationArrayOOBRayTracingShaders crashes

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-ValidationLayers#1162]
`GpuValidationArrayOOBRayTracingShaders` test crashes at:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/22a1c99af4c696e78f41cb38874b7491903e8825/tests/vklayertests_descriptor_renderpass_framebuffer.cpp#L1291

Deleting `main` body of ray generation shader makes it stop crashing, but cause the test to fail.

Also I see some invalid use:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/22a1c99af4c696e78f41cb38874b7491903e8825/tests/vklayertests_descriptor_renderpass_framebuffer.cpp#L1267-L1272

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/22a1c99af4c696e78f41cb38874b7491903e8825/tests/vklayertests_descriptor_renderpass_framebuffer.cpp#L1274-L1276

**Comment by Tony-LunarG** [comment]
Is this a new crash?  Was it working before?  What is your system configuration?

When we were testing #1052 we had to update our driver to avoid an access violation in the Nvidia driver.  425.88 is working for us here with this morning's master. Could the driver be your problem?

I would agree that those are both invalid usages and are not checked for in current validation code.  @jmacnak-nv would the fix be as simple as setting the offending shaders to UNUSED?

**Comment by krOoze** [comment]
I have been ignoring it for a while. I think it is crashing for at least two weeks.

Crashes on NV GTX 1060 6 GB 431.60 DCH Game-optimized, Win 10 1903. Crashes inside driver dlls.

**Comment by jeffbolznv** [comment]
Eric tested this internally and said the crash in the driver is resolved in the next driver release, but it sounds like there may be some invalid usage here to resolve nonetheless.

**Comment by krOoze** [comment]
Indeed, new driver works.
