### ISSUE TITLE
MockICD: Double free of physical_device handle with > 1 concurrent instance

### ISSUE THREAD

**Issue by jzulauf-lunarg** [KhronosGroup/Vulkan-ValidationLayers#117]
vk_loader_validation_test case EnumeratePhysicalDevices.MatchOneAndTwoCallNumbers with mock icd

There is heap corruption causing program termination. Valgrind pointed to DestroyInstance call of 

DestroyDispObjHandle((void*)physical_device);

Physical_device is a file scope static, and   MatchOneAndTwo creates two instances at the same time and then deletes them. The pointer physical_device is thus double freed since it isn't NULL'd after free -- corrupting the heap, with program termination happening at a later free(). 

Nulling the pointer after free would avoid the corruption, but result in the surviving instance having a NULL physical_device

Use of a shared pointer and/or unique_ptr, would seem advised (along with mutex or std::call_once on initialization).

**Comment by mark-lunarg** [comment]
Mock ICD is in Vulkan-Tools Repo.

**Comment by tobine** [comment]
Issue [10](https://github.com/KhronosGroup/Vulkan-Tools/issues/10) in Vulkan-Tools Repo
