### ISSUE TITLE
Create a deprecation layer?

### ISSUE THREAD

**Issue by Tobski** [KhronosGroup/Vulkan-ValidationLayers#1184]
Hi, something that I've been thinking for a while would be useful to have is a layer that gives warnings about functionality in use that is deprecated by other features that an application is relying on.

Right now, the Vulkan specification has a set of extensions that are listed as deprecated/promoted/obsoleted by Vulkan 1.1, or by other extensions, and to start with it could be useful to be able to have a deprecation layer be able to identify when you're enabling these extensions alongside other extensions, or in a version where it's no longer needed. This should help applications identify and upgrade parts of their codebase where newer functionality is available.

Ideally such a layer would also be able to identify specific features such as when a "v2" of a function is added to the spec (e.g. vkGetPhysicalDeviceProperties2), but this might be a "phase 2" since that sort of thing can't be trivially generated from the xml at the moment.

One key workflow issue here will be that applications would likely only want deprecation warnings against their min-spec, rather than against every single feature they enable on a given run. Use of the DevSim layer to describe your min spec and run your application against that and the deprecation layer might be a way to get this precisely.

**Comment by Tobski** [comment]
P.S. Hopefully this is the right place to file this issue, there's not a generic place to tag new layer ideas - I can move this if necessary!

**Comment by mark-lunarg** [comment]
This is the right place ☑️

**Comment by Jasper-Bekkers** [comment]
I would love to see this as a way to properly enforce the deprecation model, and as something we can hopefully lean on in the future to more aggressively deprecate things.

**Comment by krOoze** [comment]
@Jasper-Bekkers My not so old phone is stuck on 1.0.20 with zero extensions. How's that for min-spec :D

> warnings about functionality in use that is deprecated by other features that an application is relying on

Seems reasonable. I am nominating it for #24.

**Comment by Ralith** [comment]
> Ideally such a layer would also be able to identify specific features such as when a "v2" of a function is added to the spec (e.g. vkGetPhysicalDeviceProperties2)

Are the originals of these functions considered deprecated? If not, this might be unpleasantly noisy for applications which don't need extensions on those interfaces.

**Comment by Tobski** [comment]
> Are the originals of these functions considered deprecated? If not, this might be unpleasantly noisy for applications which don't need extensions on those interfaces.

Pretty much, but this is why the ability to have a min spec is important - if you require e.g. VK_KHR_get_physical_device_properties2, then using v1 of that function is kind of pointless. But if you don’t, then you shouldn’t get that warning. Similarly you’d presumably still be able to filter messages via debug callbacks if you were deliberately using deprecated functionality.

**Comment by mark-lunarg** [comment]
Moving this to the [Best Practices tracking issue](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/1184).  Updates/additions/requests can still be added in this issue, or tacked onto the tracking issue.  Thanks!
