### ISSUE TITLE
Layers build ninja crashing on Android with DebugUtils

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-ValidationLayers#1187]
I'm attempting to run the latest validation layers on Android using the Ninja build and they are immediately crashing in the layers when attempting to call vkCreateDebugUtilsMessengerEXT().
However, if I switch to using the older vkCreateDebugReportCallbackEXT() the layers work fine.

Posting this here in case someone else can verify and point to any potential changes in the layers of the last couple months that may be missing in Ninja build. @mikes-lunarg or @mark-lunarg any ideas?

**Comment by mark-lunarg** [comment]
Coupla new files, `best_practices.*` and `vklayertests_imageless_framebuffer.cpp`, but I don't know what either would have to do with that extension.

**Comment by mikes-lunarg** [comment]
Does VK_EXT_debug_utils require loader support? I see a loader terminator for vkCreateDebugUtilsMessengerEXT on desktop.

**Comment by tobine** [comment]
That's a good thought @mikes-lunarg. I just tried to dynamically load entrypoint and still seeing crash, though, so potentially loader not the issue. I do see that the layer_test still use vkCreateDebugReportCallback() for everything except VkLayerTest.DebugUtilsNameTest() in vklayertests_others.cpp. That test appears to be running and passing in our farm, though.
Still not sure what to make of this. Will keep issue open for a bit as I test some things on my end.
Not high priority, but if you have any ideas or test anything on your end let me know.

**Comment by mark-lunarg** [comment]
@tobine, does this behavior persist?

**Comment by mark-lunarg** [comment]
Also, does it work on the non-ninja Android builds?  From the Android loader source code we have seen, it doesn't look like the utils extension is supported in the same way that the debug report extension is.
