### ISSUE TITLE
WSI Swapchain interframe dependency tracking

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#12]
**Issue by [szdarkhack](https://github.com/szdarkhack) (MIGRATED)**
_Friday Dec 02, 2016 at 13:29 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1225_

----

In the current implementation of core validation, when a WSI fence is retired it is not associated with any queue and thus does not retire any work, leading to incorrect errors about resources being in use when in fact they are not. It should be the case that when an acquire fence is waited upon for a particular image index, all previous work for which the respective presentation submission waited should in turn be retired. For instance:

render loop
    acquire image and wait on fence
    submit work that signals a semaphore
    queue present that waits upon that semaphore
end render loop

It should be the case that when the acquire fence is signaled the presentation must have finished, and as such the work submitted prior to the presentation (to the same image index) must also have finished. Therefore, resources used by that submission should be marked as not being in flight (command buffers etc).

**Comment by karl-lunarg** [comment]
<a href="https://github.com/mark-lunarg"><img src="https://avatars2.githubusercontent.com/u/7252958?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mark-lunarg](https://github.com/mark-lunarg) (MIGRATED)**
_Friday Dec 02, 2016 at 14:41 GMT_

----

Maybe @chrisforbes might have a go at this one?

**Comment by karl-lunarg** [comment]
<a href="https://github.com/chrisforbes"><img src="https://avatars1.githubusercontent.com/u/128877?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Wednesday Dec 07, 2016 at 18:41 GMT_

----

@mark-lunarg Yes, I'll take care of this.

**Comment by mark-lunarg** [comment]
Waiting on the acquire fence is not a guarantee that the submitted work has been completed, even on the same image index.  The only way to guarantee this is to wait on the signaled fence from the `QueueSubmit()`.

**Comment by kvark** [comment]
@mark-lunarg so this resolution comes in conflict with the original assumption by @karl-lunarg 👍 > It should be the case that when the acquire fence is signaled the presentation must have finished, and as such the work submitted prior to the presentation (to the same image index) must also have finished. Therefore, resources used by that submission should be marked as not being in flight (command buffers etc).

Can you share a bit more background on why this decision was made? Perhaps, there are examples of work by the driver that could assist in a more intuitive understanding of the issue. What does it mean now that the fence for `acquire_image` is ready?

**Comment by mark-lunarg** [comment]
The original assumption wasn't by Mr. Schultz, but by a user of the validation layers who had a question soon after Vulkan was initially released. @jzulauf-lunarg is the Vulkan synchronization expert, whom I relied upon for the short update above.  John, might you be able to add a bit more detail to my thin comment above?

**Comment by kvark** [comment]
Reading https://github.com/KhronosGroup/Vulkan-Docs/issues/117 now, there is a lot of interesting detail on how the fence is different from the semaphore in the wait. It also mentions that the spec has this text fixed in 1.0.9.
Going back to the original post by @karl-lunarg it would be great to get a definite resolution on whether this is a valid render loop pseudo-code or not.

**Comment by nickkuk** [comment]
Somewhat related question: when one could reuse binary `Semaphore` that signaled in `vkQueueSubmit` and waited in `vkQueuePresentKHR`?

One could
1. wait for `Fence` or timeline `Semaphore` that signaled in `vkQueueSubmit`;
2. wait for `vkAcquireNextImageKHR` to return the same image index, which was used in `vkQueuePresentKHR` before;
3. even more: wait for `Fence` or timeline `Semaphore` that signaled in `vkQueueSubmit` for next iteration of the same image index;
4. etc.

@kvark, have you encountered such an issue in `gfx` or `wgpu`?

**Comment by nickkuk** [comment]
I've always used timeline `Semaphore`s instead of `Fence`s, so I've missed another option:

3-ε. wait for `Fence` from vkAcquireNextImageKHR that return the same image index, which was used in vkQueuePresentKHR before.

In the world without `Fence`s ε approaches to zero and 3-ε becomes 3.

Note that in 2 I meant just `vkAcquireNextImageKHR` function call without `Fence` waiting.

**Comment by artem-lunarg** [comment]
Added test case the reproduces the scenario: https://github.com/artem-lunarg/Vulkan-ValidationLayers/commit/808eba0a7ebbae2d89ec2efadbe18a5f1b80a3b9
