### ISSUE TITLE
Guard C++ specific functions in vk_enum_string_helper.h code-generation script to regain 'C' compatibility.

### ISSUE THREAD

**Issue by jzulauf-lunarg** [KhronosGroup/Vulkan-ValidationLayers#1211]
Guard the utilities that compose a multi-bit flag word into a string joining all the bit stringifications into a single returned std::string, for example string_VkFenceCreateFlags.

These (and the header includes) should be guarded by:

#ifdef __cplusplus

in the auto-generation script.  

From LunarXchange -- https://vulkan.lunarg.com/issue/view/5d4b09b5b736866d88e7e89d

**Comment by krOoze** [comment]
This header does not seem to be part of the SDK on Windows... so perhaps this is a packaging error?

**Comment by mark-lunarg** [comment]
After this imminent SDK, we'll be combing through the files included in the Source directory and removing unneeded ones.  Closing this issue as the layer support files in this repository are targeted at CPP.

**Comment by juan-lunarg** [comment]
vk_enum_string_helper.h is now C compatible and lives in the https://github.com/KhronosGroup/Vulkan-Utility-Libraries
