### ISSUE TITLE
Validation Layer keep reporting widelines feature disabled

### ISSUE THREAD

**Issue by harokyang** [KhronosGroup/Vulkan-ValidationLayers#1217]
vulkaninfo report widelines = 1, lineWidthRange is [1.0-64.0]

Everything works fine with static or dynamic line width pipeline setup
But validation layer keep reporting VkPhysicalDeviceFeatures::wideLines is disabled

Vulkan SDK 1.1.114.0, Windows 10 64bit, GTX 1060

**Comment by harokyang** [comment]
More information,

Error report on static line width:

ERROR: [Validation] Code 0 :  [ VUID-VkGraphicsPipelineCreateInfo-pDynamicStates-00749 ] Object: VK_NULL_HANDLE (Type = 19) | The line width state is static (pCreateInfos[0].pDynamicState->pDynamicStates does not contain VK_DYNAMIC_STATE_LINE_WIDTH) and VkPhysicalDeviceFeatures::wideLines is disabled, but pCreateInfos[0].pRasterizationState->lineWidth (=4.000000) is not 1.0. The Vulkan spec states: If the wide lines feature is not enabled, and no element of the pDynamicStates member of pDynamicState is VK_DYNAMIC_STATE_LINE_WIDTH, the lineWidth member of pRasterizationState must be 1.0 (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-pDynamicStates-00749)

Error report on dynamic line width:

ERROR: [Validation] Code 0 :  [ VUID-vkCmdSetLineWidth-lineWidth-00788 ] Object: 0x555557b440c0 (Type = 6) | VkPhysicalDeviceFeatures::wideLines is disabled, but lineWidth (=4.000000) is not 1.0. The Vulkan spec states: If the wide lines feature is not enabled, lineWidth must be 1.0 (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdSetLineWidth-lineWidth-00788)

This issue only happened when using VK_LAYER_KHRONOS_validation layer
The VK_LAYER_LUNARG_core_validation layer behave correctly

**Comment by mark-lunarg** [comment]
@harokyang, can you confirm that you have enabled the WideLines feature in VkPhysicalDeviceFeatures as described in chapter 35 of the Vulkan Specification?

**Comment by harokyang** [comment]
Thanks for the remind
I forgot to enable it on device creation
The old validation layer say nothing about it, I thought it was enabled by default
