### ISSUE TITLE
GPU assisted validation and usage of the nonuniformEXT qualifier

### ISSUE THREAD

**Issue by Avopeac** [KhronosGroup/Vulkan-ValidationLayers#1226]
When using the GPU assisted validation feature (in SDK 1.1.114.0) I'm getting a nullptr access in the instrumentation process when creating shader modules. This happens when using the nonuniformEXT qualifier to index a texture array. Stripping all the nonuniformEXT usage from the shader makes the validation feature work as intended. Is the qualifier supposed to be supported with the validation feature?

Callstack looks like this:

`>	VkLayer_khronos_validation.dll!spvtools::opt::InstBindlessCheckPass::AnalyzeDescriptorReference(spvtools::opt::Instruction * ref_inst, spvtools::opt::InstBindlessCheckPass::ref_analysis * ref) Line 212	C++
 	VkLayer_khronos_validation.dll!spvtools::opt::InstBindlessCheckPass::GenInitCheckCode(spvtools::opt::InstructionList::iterator ref_inst_itr, spvtools::opt::UptrVectorIterator<spvtools::opt::BasicBlock,0> ref_block_itr, unsigned int stage_idx, std::vector<std::unique_ptr<spvtools::opt::BasicBlock,std::default_delete<spvtools::opt::BasicBlock> >,std::allocator<std::unique_ptr<spvtools::opt::BasicBlock,std::default_delete<spvtools::opt::BasicBlock> > > > * new_blocks) Line 371	C++
`

It prints this:

Exception thrown: read access violation.
**spvtools::opt::analysis::DefUseManager::GetDef**(...) returned nullptr.

**Comment by greg-lunarg** [comment]
Can you please supply the SPIR-V or the shader source and compilation command line?

**Comment by Avopeac** [comment]
So I reduced the amount of shader code to reproduce the issue:

#version 450 core
#extension GL_EXT_nonuniform_qualifier : enable

layout( location = 0 ) in vec2 inTexcoord;
layout( location = 0 ) out vec4 outColor;

layout( set = 0, binding = 0 ) uniform Uniforms {
	vec2 var0;
} uniforms;


layout( set = 0, binding = 1 ) uniform sampler uniformSampler;
layout( set = 0, binding = 2 ) uniform texture2D uniformTex;
layout( set = 0, binding = 3 ) uniform texture2D uniformTexArr[8];

void main() {
	int index = 0;
	float x = texture( sampler2D( uniformTexArr[ nonuniformEXT( index ) ], uniformSampler ), inTexcoord.xy ).x;
	float y = texture( sampler2D( uniformTex, uniformSampler ), inTexcoord.xy * uniforms.var0.xy ).x;
	outColor = vec4( 0.0 );
}

The compilation command I used is:

glslangValidator.exe -V --target-env vulkan1.1 descriptor_indexing.frag -o descriptor_indexing.fspv

If it helps the VkDeviceCreateInfo pNext is pointing to a VkPhysicalDeviceFeatures2 with "shaderSampledImageArrayDynamicIndexing" set to true, the pNext of the VkPhysicalDeviceFeatures2 is pointing to a VkPhysicalDeviceDescriptorIndexingFeaturesEXT with "shaderSampledImageArrayNonUniformIndexing" set to true. The only enabled device extension is "VK_EXT_descriptor_indexing".

"VK_LAYER_KHRONOS_validation" is the only enabled instance layer and "VK_EXT_debug_utils" is the only instance extension.

It appears the instrumentation succeeds if either I don't multiply with "uniforms.var0.xy" or don't use the nonuniformEXT qualifier.

**Comment by greg-lunarg** [comment]
Thanks! Will take a look.

**Comment by greg-lunarg** [comment]
My apologies. This slipped off my stack. Am looking now.

**Comment by Tony-LunarG** [comment]
Fixed
