### ISSUE TITLE
Question: How are ClipDistance and CullDistance validated?

### ISSUE THREAD

**Issue by chaoticbob** [KhronosGroup/Vulkan-ValidationLayers#125]
Hi,

I know that Vulkan requires ClipDistance and CullDistance to be arrays of floats and the validation checks for this. Was wondering if the check is robust enough to handle the case where these are two dimension arrays? 

Thanks!

**Comment by chrisforbes** [comment]
=> SPIRV-Tools. We don't touch ClipDistance/CullDistance in validation layers.
