### ISSUE TITLE
Layers validate basePipelineHandle object unconditionally

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-ValidationLayers#1257]
The `basePipelineHandle` member in `VkGraphicsPipelineCreateInfo` and `VkComputePipelineCreateInfo` doesn't always have to be valid, but it's always checked in the object_tracker layer:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/be102ad6730ddc70d1e5b950ea7edc68063c5cad/layers/generated/object_tracker.cpp#L1087-L1092

In particular it only needs to be valid if flags contain `VK_PIPELINE_CREATE_DERIVATIVE_BIT` and `basePipelineIndex` is `-1`, otherwise it's ignored.

**Comment by mark-lunarg** [comment]
@baldurk, this should have been addressed by #1265, please let me know right away if the problem persists.  Thanks!
