### ISSUE TITLE
Dedicated Allocation Aliasing (VkBindTextureMemory)

### ISSUE THREAD

**Issue by jonslayer0** [KhronosGroup/Vulkan-ValidationLayers#1266]
Hello,

I'm sorry in advance if my problem has already been addressed and/or resolved.

I'm getting a validation layer error when calling vkBindTextureMemory (I'm using VMA and VulkanSDK 1.1.114.0).

Like the title says, I started by creating a vkImage, with preferred dedicated allocation (the VMA get memory requirements function returned the flag as true), then I'm creating a second vkImage and using the allocation of the first image to bind it. These images are used by Render Targets and have the same extent.

My problem is, in the documentation it states that either the second image must be equal to the first one OR equal to an "image that was created using the same parameters in VkImageCreateInfo" ([(https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#vkBindImageMemory)]). 

But when I look at the test that checks that requirement (at the end of CoreChecks::ValidateBindImageMemory()), I see that it only verifies if the images are equal (and that the offset is 0).

The aliasing seems to work, since VMA goes on and binds it and I do not get any other layer errors (and everything seems to be displayed correctly).

Regards,
Jonathan Siret

**Comment by jeffbolznv** [comment]
The "or an image that was created using the same parameters in sname:VkImageCreateInfo..." language is part of the VK_NV_dedicated_allocation_image_aliasing extension, and I don't think this was ever added to the validation layers. I'll fix this.

**Comment by jonslayer0** [comment]
Thank you for the quick answer. For now, our callback function will ignore that message. 

Regards,
Jonathan Siret
