### ISSUE TITLE
vkCreateDevice "best practices" check is testing the wrong state

### ISSUE THREAD

**Issue by cdwfs** [KhronosGroup/Vulkan-ValidationLayers#1272]
The check for `kVUID_BestPractices_CreateDevice_PDFeaturesNotCalled` in `best_practices.cpp` claims to be checking whether `vkGetPhysicalDeviceFeatures()` has been called before `vkCreateDevice()`. However, it's checking `vkGetPhysicalDeviceSurfaceCapabilitiesKHRState`, not `vkGetPhysicalDeviceFeaturesState`.

I started working on a PR for what I assumed would be a simple one-line change, but then I discovered that `vkGetPhysicalDeviceFeaturesState` is never actually being set. I've been out of the validation layer game for a year or so; can I get a little help with this one? :)

**Comment by mark-lunarg** [comment]
Sure @cdwfs, we'll take a look.  Thanks for finding it!

**Comment by mark-lunarg** [comment]
Hey, it's all yours!

**Comment by mark-lunarg** [comment]
You *may* need the change from #1273.
