### ISSUE TITLE
Memory poisoning linting tool

### ISSUE THREAD

**Issue by Plagman** [KhronosGroup/Vulkan-ValidationLayers#1279]
Apps using uninitialized memory and not realizing it because current Windows drivers happen to zero-initialize it is a common issue. Could the validation layers have a mode that initializes memory with garbage to uncover these sorts of cases?

**Comment by mark-lunarg** [comment]
Sure, that could be an opt-in enable in the khronos layer.

**Comment by mark-lunarg** [comment]
This issue has been rolled into the [Validation Layer Enhancements Project Page](https://github.com/KhronosGroup/Vulkan-ValidationLayers/projects/4).
