### ISSUE TITLE
vkGetPhysicalDeviceWin32PresentationSupportKHR not recognized by layers

### ISSUE THREAD

**Issue by Rainer4** [KhronosGroup/Vulkan-ValidationLayers#1282]
It seems like the Khronos validation layers do not recognize vkGetPhysicalDeviceWin32PresentationSupportKHR, since the message "vkQueuePresentKHR: Presenting image without calling vkGetPhysicalDeviceSurfaceSupportKHR" is sent whenever presenting, when using vkGetPhysicalDeviceWin32PresentationSupportKHR instead of vkGetPhysicalDeviceSurfaceSupportKHR.

**Comment by Rainer4** [comment]
Solved: Platform-specific versions of the present-support function do not check for surface compatibility, hence the warning. https://vulkan.lunarg.com/doc/view/1.0.33.0/linux/vkspec.chunked/ch29s04.html:  "Not all physical devices will include WSI support. Within a physical device, not all queue families will support presentation. WSI support and compatibility can be determined in a platform-neutral manner (which determines support for presentation to a particular surface object) and additionally may be determined in platform-specific manners (which determine support for presentation on the specified physical device but do not guarantee support for presentation to a particular surface object)."

**Comment by mark-lunarg** [comment]
Wow!  Thanks for the clarification and update -- we very much appreciate the follow-through. 👍
