### ISSUE TITLE
Threading validation error when using vkResetEvent()/vkCreateEvent() with vkCmdFillBuffer()/vkCmdWriteBufferMarkerAMD() on different threads

### ISSUE THREAD

**Issue by unrealqloc** [KhronosGroup/Vulkan-ValidationLayers#1283]
I have thread validation error Vulkan SDK 1.1.121: 
THREADING ERROR : object of type VkCommandPool is simultaneously used in thread 0x6e08 and thread 0x14a0..
It's related to calling of vkResetEvent()/vkCreateEvent()/vkSetDebugUtilsObjectNameEXT() and (vkCmdFillBuffer() and vkCmdWriteBufferMarkerAMD()) on different threads. Am I doing something wrong or there is an issue with threading validation? vkResetEvent()/vkCreateEvent() calls use device only? How can I pinpoint what is an issue here?

**Comment by jeffbolznv** [comment]
vkResetEvent/vkCreateEvent don't count as using a command pool, so they shouldn't be relevant (though vk*Cmd*ResetEvent does use a command pool). Is it possible for you to set a breakpoint on that error being logged and maybe find the offending commands in the call stacks of the two threads?

Note that there was a pretty big rewrite of the ThreadSafety layer in the most recent SDK. It's possible there are bugs in it, but it also has the effect of locking less which may make the layer more easily able to find these sorts of app bugs than in previous versions.

**Comment by mark-lunarg** [comment]
@unrealqloc, as @jeffbolznv mentioned, it is possible there is an issue with the validation.  However, we are unaware of any other like reports.  The best way to proceed is to have a repro case -- can you share a code snippet or test case that exhibits the problem?  If not, can you share an API dump of the app while running the validation layers?  Thanks!

**Comment by unrealqloc** [comment]
Sorry for late reply, I didn't notice follow ups. I've managed to fix this issue, but validation layers wasn't helpful. Firstly I've put mutexes everywhere around all command buffer / pool accesses to quiet validation layers, but after that I've got random crashes inside vkCmdWriteBufferMarkerAMD() / vkCmdFillBuffer() functions (inside AMD driver). 
In the end I've removed all mutexes (adding them was very radical ;-)) and I've made sure that buffer marker ranges (which are assigned to given command buffer "context") cannot be touched by other command buffer until given command buffer has been submitted / finished execution, so it turned out that it was application side problem. 
In general we have several types of command buffer pools (graphics / compute / copy / copyasync), each pool has contigous host visible marker buffer, which can hold several "breadcrumb contexts" of fixed size. Each of this contexts was assigned for given command buffer for breadcrumb writes (which are reused and can be grabbed from different threads) and should be released after given command buffer has been submitted and finished work.     
I cannot share code snippets, because I would have to share whole engine which is under NDA (alot of things is going on at once).  
I have one suggestion, could you promote buffer marker functionality to standard extension? Currently there are three variants with different behaviour / interfaces (for example vkCmdWriteBufferMarkerAMD has additional parameter and can be used outside render pass, fallback vkCmdFillBuffer() cannot be used inside render pass, Nvidia VK_NV_device_diagnostic_checkpoints has different interface ). So in general application developer has to implement / test three different variants for different hardware vendors.

**Comment by mark-lunarg** [comment]
@unrealqloc, I would strongly suggest opening an issue in [Vulkan-Docs](https://github.com/KhronosGroup/Vulkan-Docs) with this request, and thanks for your detailed follow up!
