### ISSUE TITLE
Receiving 'VUID-vkBindImageMemory-memory-01509' error messages when VK_NV_dedicated_allocation_image_aliasing extension is used

### ISSUE THREAD

**Issue by mboucha1** [KhronosGroup/Vulkan-ValidationLayers#1291]
Based on the following documentation:
https://github.com/KhronosGroup/Vulkan-Docs/blob/master/appendices/VK_NV_dedicated_allocation_image_aliasing.txt 

This extension allows user to alias different VkImage on dedicated allocations with these restrictions:
"the extent and the number of layers in the image   being aliased must be smaller than or equal to those of the original image   for which the allocation was created, and every other image parameter must match."

Even if these restrictions are followed, we are still receiving 'VUID-vkBindImageMemory-memory-01509' errors.

**Comment by jeffbolznv** [comment]
I fixed this recently, see https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/82f854d3c711f1469df1711b8f04f0e90f1557d6. It's not in the 1.1.123.0 SDK release. Are you using a newer commit than that? If so, did you enable the dedicatedAllocationImageAliasing feature?

**Comment by mboucha1** [comment]
We currently use Vulkan SDK version 1.1.114.0 with the dedicatedAllocationImageAliasing feature.

Which SDK should have the fix?

**Comment by jeffbolznv** [comment]
It would be in the next official release, which I'd guess is at least a few weeks away since the .121 SDK was pretty recent. Or you could build the layers from source...

**Comment by mark-lunarg** [comment]
In addition to building layers from source, you can download the Windows build-artifacts including validation layer binaries from @jeffbolznv's fix from appveyor [here](https://ci.appveyor.com/project/Khronoswebmaster/vulkan-validationlayers/builds/27483688/job/n0t4wg35jvwlglxj/artifacts).   Closing this issue for now, if you are able to verify that it persists using the referenced binaries or later in the next SDK, please reopen this issue.  Thanks!
