### ISSUE TITLE
Unintended copy of output fields in VkPipelineCreationFeedbackCreateInfoEXT?

### ISSUE THREAD

**Issue by hysw** [KhronosGroup/Vulkan-ValidationLayers#1295]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/9b00efde64668c1748a82e6ee879ac667099475d/layers/generated/layer_chassis_dispatch.cpp#L253

The memory region pointed to by
VkPipelineCreationFeedbackCreateInfoEXT::pPipelineCreationFeedback
and
VkPipelineCreationFeedbackCreateInfoEXT::pPipelineStageCreationFeedbacks
are suppose to be used for returning data from the icd/driver to the application.
However in layers/generated/vk_safe_struct.cpp (referenced by generated/layer_chassis_dispatch.cpp) those fields are copied and returned data are not passed back to the application.

**Comment by hysw** [comment]
Partial stack trace:
#1  ... in DispatchCreateGraphicsPipelines (device=0x7fffc41de010, pipelineCache=0xdc0060, createInfoCount=1, 
    pCreateInfos=0xdbff90, pAllocator=0x0, pPipelines=0x7fffffffe3d0)
    at layers/layer_chassis_dispatch.cpp:253
#2  ... in vulkan_layer_chassis::CreateGraphicsPipelines (device=0x7fffc41de010, pipelineCache=0x1c000000001c, 
    createInfoCount=1, pCreateInfos=0xdbff90, pAllocator=0x0, pPipelines=0x7fffffffe3d0)
    at layers/chassis.cpp:689

**Comment by mark-lunarg** [comment]
First attempt doesn't account for a createinfo count > 1.

**Comment by mark-lunarg** [comment]
This should be fixed by #1318.   Thanks!
