### ISSUE TITLE
Smoketest with validation spews errors on resize (NVIDIA, Linux)

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#13]
**Issue by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Friday Dec 09, 2016 at 22:57 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1250_

----

**Comment by Tony-LunarG** [comment]
Smoketest has been removed from this repository and the Hologram sample it was derived from does not spew validation errors apart from the known errors here: 

https://github.com/LunarG/VulkanSamples/issues/178

Tested resize of Hologram Ubuntu 18.04, Nvidia driver 418.56.

Closing this issue
