### ISSUE TITLE
core: skip chassis locking for methods that aren't implemented

### ISSUE THREAD

**Issue by jeffbolznv** [KhronosGroup/Vulkan-ValidationLayers#1310]
The core layer currently takes a lock around each PreCallValidate, PreCallRecord, and PostCallRecord method, even if the method doesn't do anything. And one of the two Record functions is empty the vast majority of the time. I see a decent improvement in multithreaded scaling by skipping the unnecessary locks.

I'd like to discuss options for how to deal with this. A couple ideas:

(1) Push the locking down into the layer. i.e. each method is responsible for its own locking, and the write_lock method is overridden to use defer_lock.

(2) Consolidate the core/statetracker layers to only use one or the other of PreCallRecord/PostCallRecord, give the chassis separate locking methods for those, and nop one of them for the core layer.

Any other ideas? I think (1) is probably a better option than (2), particularly if we want to move to any kind of finer-grained locking in the future.

**Comment by jeffbolznv** [comment]
ping @jzulauf-lunarg @mark-lunarg for their thoughts.

**Comment by mark-lunarg** [comment]
Moved to the validation layer performance tracking issue.

**Comment by mark-lunarg** [comment]
Implemented for non-overloaded Device APIs by PR #2529.
