### ISSUE TITLE
update_deps.py issue on Python 3.6.8 with Ubuntu 18.04

### ISSUE THREAD

**Issue by JDeuce** [KhronosGroup/Vulkan-ValidationLayers#1314]
The script doesn't seem to run with this version of python 3 

```
# python3 ./scripts/update_deps.py
Traceback (most recent call last):
  File "./scripts/update_deps.py", line 245, in <module>
    import distutils.dir_util
ModuleNotFoundError: No module named 'distutils.dir_util'
```

Workaround for now is to edit _update_external_sources_android.sh_ to run with python2

```
--- a/build-android/update_external_sources_android.sh
+++ b/build-android/update_external_sources_android.sh
@@ -89,7 +89,7 @@ function build_shaderc () {

 # Pull down or update external dependencies
 echo "Update external dependencies based on the $ANDROIDBUILDDIR/known_good.json file"
-python3 ../scripts/update_deps.py --no-build --dir $BASEDIR --known_good_dir $BUILDDIR
+python ../scripts/update_deps.py --no-build --dir $BASEDIR --known_good_dir $BUILDDIR

 if [[ -z $nobuild ]]
 then
```

**Comment by mark-lunarg** [comment]
@JDeuce, your issue does not manifest in either the internal test farm nor in [Github CI](https://travis-ci.org/KhronosGroup/Vulkan-ValidationLayers).  Can you provide information related to your build environment, python versions, etc?  And when did this issue begin to occur, for instance, is this a recent issue?  Thanks!

**Comment by JDeuce** [comment]
I just setup a new Ubuntu 18.04 VM to compile it, following these instructions https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/BUILD.md#building-on-linux.

So it's not something that just recently started happening.

Looking at the travis config the build seems to be using Ubuntu Xenial (16.04 w/ python 3.5 as default) while I was using Bionic (18.04 w/ python 3.6 as default).

Also I just tested running `apt install python3-distutils` and it seemed to fix python3 on the script... so maybe this is just a missing step in the doc.
