### ISSUE TITLE
issue in spirv-tools: amd_ext_to_khr.cpp tries to include spv-amd-shader-ballot.insts.inc and fails

### ISSUE THREAD

**Issue by JDeuce** [KhronosGroup/Vulkan-ValidationLayers#1315]
One more minor issue I encountered when building latest.

Ran into a similar error to this one https://github.com/google/amber/issues/648
```
[arm64-v8a] Compile++      : SPIRV-Tools-opt <= amd_ext_to_khr.cpp
amd_ext_to_khr.cpp:22:10: fatal error: 
      'spv-amd-shader-ballot.insts.inc' file not found
#include "spv-amd-shader-ballot.insts.inc"
```

Had to apply this patch from spirv-tools to _build-android/third_party/shaderc/third_party/spirv-tools/Android.mk_ to add the extra dependency on that inc file before it would compile:

https://github.com/KhronosGroup/SPIRV-Tools/pull/2883/commits/0bda2bf5c1847ea6b6045aa7d241dd270b41b739

**Comment by mark-lunarg** [comment]
@JDeuce, can you please supply the commit IDs you are using for glslang and spirv-tools?  Thanks!

**Comment by JDeuce** [comment]
I didn't try to figure out the proper way to update the dependency, only that the version I had was missing those 2 lines in Android.mk. I just manually patched those in to get my build to succeed.

**Comment by mark-lunarg** [comment]
This repository is only vetted to work with the versions set in the `known_good.json` file, specifically to avoid incompatibilities such as this -- thanks for the heads-up, we'll make sure the fix for this is included in the next known-good update.
