### ISSUE TITLE
unexpected error messages when reading queries without "wait" as well as VK_EXT_query_host_reset

### ISSUE THREAD

**Issue by pixeljetstream** [KhronosGroup/Vulkan-ValidationLayers#1349]
SDK 1.1.114.0
https://drive.google.com/file/d/1eYxJT6AXZX89AU-2zYYz3P6yZFzaNx7I/view?usp=sharing
binaries here (msvc 2017-x64 debug)

The use of wait for fences ensures that the queries are not in-flight, yet the validation layer complains “query may return no data”, only if I enforce the WAIT BIT on query read that message goes away.

When the scene regeneration is activated in the ui, some queries are reset via VK_EXT_query_host_reset and that also creates errors that imo shouldn’t exist.

**Comment by pixeljetstream** [comment]
SDK 1.1.126.0 does not reproduce these problems anymore, closing

**Comment by mark-lunarg** [comment]
Thanks for retesting this and closing, @pixeljetstream.
