### ISSUE TITLE
Validation of KHR_timeline_semaphore is missing

### ISSUE THREAD

**Issue by HansKristian-Work** [KhronosGroup/Vulkan-ValidationLayers#1360]
I tried buliding from git, but it seems that KHR_timeline_semaphore validation is not implemented. There seems to be some basic checks about having the KHR extension enabled when calling certain entry points, but that's about it.

**Comment by mark-lunarg** [comment]
@HansKristian-Work, someone has been assigned to the [Gitlab issue](https://gitlab.khronos.org/vulkan/Vulkan-ValidationLayers/issues/5), and status will be tracked there.  Once it gets through the approval process it'll be brought over and merged.  Thanks!

**Comment by mikew-lunarg** [comment]
PR https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1394 is merged to master
