### ISSUE TITLE
vkCmdResetQueryPool + vkCmdBeginQuery/vkCmdWriteTimestamp false positive

### ISSUE THREAD

**Issue by jareksocha** [KhronosGroup/Vulkan-ValidationLayers#1364]
Hello,

I have encountered a problem with vkCmdResetQueryPool and vkCmdBeginQuery/vkCmdWriteTimestamp validation. 
I'm getting messages:

vkCmdBeginQuery(): VkQueryPool 0x4655610000000064[] and query 99: query not reset. After query pool creation, each query must be reset before it is used. Queries must also be reset between uses.

But the problem is that vkCmdResetQueryPool is executed in different command buffer than buffer that is executing vkCmdBeginQuery and validation layer is not recording query reset state between command buffers.

I have traced it down to ValidateCommandBuffersForSubmit and this function is not tracking query state proper.

Thanks,
Jarek

SDK 1.1.126.0

**Comment by mark-lunarg** [comment]
@jareksocha, I put together a test case and it seems to work correctly, which probably means I need additional information.  Can you provide the contents of the two command buffers, at least related to queries?  Are they in the same or separate submit calls?  Actually, an api_dump would be best, but we'll take what you have handy.  Thanks!

**Comment by jareksocha** [comment]
Hello,

@mark-lunarg I will try to get you API_DUMP today. I think they are in a same submit calls.
Thanks, Jarek.

**Comment by jareksocha** [comment]
Hello,

@mark-lunarg 
I'm attaching a dump file, unfortunately its rather large.

[dump.zip](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/3840081/dump.zip)

**Comment by jareksocha** [comment]
I think the problem might be in vkQueueSubmit having multiple Submits.

**Comment by mark-lunarg** [comment]
Thank you very much @jareksocha!  We'll take a look at this today.
