### ISSUE TITLE
Expose VUID stats in build artifacts

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-ValidationLayers#1368]
Expose VUID stats in build artifacts. Similar to `https://vulkan.lunarg.com/doc/sdk/1.1.126.0/windows/validation_error_database.html.

Bonus points for linking to it for a `master` branch.

**Comment by mark-lunarg** [comment]
Do you mean the AppVeyor build artifacts?  That would be workable, as would an optional MSVC build target (a la VulkanVL_generate_source).  Or did you have something else in mind?

**Comment by krOoze** [comment]
Yea, those. I thought that would be the most straightforward path.

The local repo basically breaks everytime headers are updated. I think it also requires the generated stuff to be compiled. Seems more convenient to have the coverage report build somewhere, rather than asking people to run the script.
