### ISSUE TITLE
Warn if vkAcquireNextImageKHR too many images

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-ValidationLayers#1389]
Warn on attempt to acquire too many images via vkAcquireNextImageKHR when timeout is not `UINT32_MAX` (otherwise that is not Valid Usage).

This is a recommendation of the specification:

> If the number of currently acquired images is greater than this, `vkAcquireNextImageKHR` **should** not be called;

**Comment by mark-lunarg** [comment]
Anybody think that statement is strong enough to warrant an error?

**Comment by krOoze** [comment]
Well, "should" is well defined in the specification.  The user can do it, if he really really wants for some reason.

BTW it was an error in layers before PR #1373

**Comment by mark-lunarg** [comment]
Ah, there it is, then -- thanks for the definitive answer.

**Comment by mark-lunarg** [comment]
Added to the [BP tracking issue](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/24)!
