### ISSUE TITLE
Dangling pointer bug when shader module does not exist

### ISSUE THREAD

**Issue by jaebaek** [KhronosGroup/Vulkan-ValidationLayers#139]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/shader_validation.cpp#L1442

will cause a segfault when `module` is NULL.

Under some environment setting, users cannot realize what are problems because the validation layer also fails without any problem report.

**Comment by mark-lunarg** [comment]
Did the object tracker layer or standard_validation issue an error before the segfault?

**Comment by mark-lunarg** [comment]
This issue would be properly reported by the object-lifetime validation code.
