### ISSUE TITLE
"Fix constness of shared_ptrs" commit causes access violation in CTS

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-ValidationLayers#1395]
PR #1324 causes the CTS test dEQP-VK.binding_model.shader_access.primary_cmd_buf.with_push.sampler_immutable.no_access.single_descriptor.1d (with Khronos_validation) to get an access violation in descriptor_sets.cpp line597: 

descriptors_.emplace_back(new SamplerDescriptor(state_data, immut_sampler + di));

when state_data is null. @jeffbolznv could you take a look?

**Comment by jeffbolznv** [comment]
I don't have the cycles to work on this at the moment. This must be one of the "proxy" descriptor sets made for push descriptors. There's a comment suggesting a possible path to avoid this mess, but I don't know what all is involved in fixing it:

```
                    // Create an empty proxy in order to use the existing descriptor set update validation
                    // TODO move the validation (like this) that doesn't need descriptor set state to the DSL object so we
                    // don't have to do this.
```

Alternately, we might just need to skip looking up the immutable sampler when state_data is null, as a more local fix.
