### ISSUE TITLE
Want better message for unrecognized instruction

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/Vulkan-ValidationLayers#1396]
A customer was using HLSL-based shaders compiled with -fhlsl_functionality1
This injected OpDecorateString instructions (formerly OpDecorateStringGOOGLE), with opocode 5632.

The shader was used in a driver that doesn't support VK_GOOGLE_hlsl_functionality1, so the instruction was unrecognized.
The validation layers gave a message similar to "i don't recognize this instruction"

The customer requested a more informative message.  For example, the layer could use an opcode-based lookup to see if the instruction is enabled by an extension or by a later version of SPIR-V, beyond what is supported by the driver.
E.g. "Driver does not recognize opcode 5632 from extension SPV_GOOGLE_hlsl_functionality1"

**Comment by jeremy-lunarg** [comment]
I tried reproducing this using the VK_GOOGLE_hlsl_functionality1 extension. Can you tell me where you were seeing the error message? Thanks.

**Comment by KarenGhavam-lunarG** [comment]
@dneto0 Were wondering if you could help move this issue along by providing some more information as requested by @jeremy-lunarg 

Thanks!

**Comment by jeremy-lunarg** [comment]
@dneto0
