### ISSUE TITLE
Fence wait should be optional with timeline semaphores

### ISSUE THREAD

**Issue by kennyalive** [KhronosGroup/Vulkan-ValidationLayers#1410]
With the introduction of timeline semaphores it's fine to call vkQueueSubmit without a fence (and subsequent vkWaitForFences), instead we can wait on the host using vkWaitSemaphoresKHR. 

The latest validation layer code as of  Nov 28, 2019 still requires to use VkFence in vkQueueSubmit and then wait on it, otherwise,  ValidationStateTracker::RetireWorkOnQueue won't be called and in my case I get false-positive validation error that resource is being deleted that is still in use by the command buffer.

Are there plans to provide support for use case when synchronization implemented without fences and vkWaitSemaphoresKHR is used to wait on the host?

**Comment by mark-lunarg** [comment]
@jasuarez, hopefully you can cover these cases as the validation is filled out.  @kennyalive, yes, the timeline semaphore validation implementation was added to the spec before the validation was complete and it is being actively worked on now.  Thanks!

**Comment by aejsmith** [comment]
FWIW this is also an issue for me right now, since when I'm using timeline semaphores, that fully replaces use of binary semaphores and fences. vkWaitSemaphoresKHR is used to wait for command buffer completion before destroying resources, and currently I get false positive errors for destruction while in use.

**Comment by kennyalive** [comment]
@aejsmith  if you are interested in a dirty workaround one option is to build layers manually with this hack (definitely not a proper fix):
![image](https://user-images.githubusercontent.com/4964024/70428935-dbd7ba00-1a77-11ea-8912-935cf0b37024.png)

**Comment by mark-lunarg** [comment]
@jasuarez, if you approve, I could add the above workaround until the complete validation lands.  Please let us know.

**Comment by jasuarez** [comment]
@mark-lunarg yeah, go ahead

**Comment by mark-lunarg** [comment]
Running through the farm now.

**Comment by jasuarez** [comment]
I think this has been covered by https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1511
