### ISSUE TITLE
CreateGraphicsPipelines crash if shader module hande is invalid.

### ISSUE THREAD

**Issue by dor666** [KhronosGroup/Vulkan-ValidationLayers#1417]
Issue was found when trying GPU_Caps_Viewer_1.43.1.0 with vk_phong_lighting2 demo and attached khronos_validation from SDK 1.1.126.0.

CapsViewer is a 32bit app and chops upper 32bits of shader handle.

While this is an app issue, I don't think it should cause a validation layer crash.
It would be nice to print an error.

```
void ValidationStateTracker::RecordPipelineShaderStage(VkPipelineShaderStageCreateInfo const *pStage, PIPELINE_STATE *pipeline,
                                                       PIPELINE_STATE::StageState *stage_state) const {
    // Validation shouldn't rely on anything in stage state being valid if the spirv isn't
    auto module = GetShaderModuleState(pStage->module);
    if (!module->has_valid_spirv) return; // <- nullptr pointer dereference.
```

Command line to reproduce:
`GPU_Caps_Viewer.exe /run_gxl_demo=vk_phong_lighting2`

**Comment by mark-lunarg** [comment]
If the module handle is the handle returned from CreateShaderModule, there's little we can do.  The object-lifetimes validation will verify that any handle used is one that was properly created, and if it is not we'll print a message.  We don't have any way to know if a handle returned from a driver is valid or invalid (obviously), and it is our policy to allow object-lifetimes checks to be the first line of defense for the rest of the validation.  As far as the specification is concerned, this is a valid handle.

**Comment by dor666** [comment]
Hi Mark.
I think you misunderstood me.
App zeroes upper 32bits of handle so it is not valid anymore (never returned by CreateShaderModule).
I see no message from object-lifetimes. I just see crash.
Do I need to enable object-lifetimes checks somehow in new khronos_validation layer?
Maybe this crash is before actual object-lifetimes check..

**Comment by mark-lunarg** [comment]
Ah, so in this case, the correct 64-bit handle is returned from CreateShaderModule, but the app mangles the handle when it creates and passes in the CreateGraphicsPipelineData?  If this is the case you're right -- the lifetime stuff should throw an error before the layers give up.  Lemme know and I'll take a look at it!

**Comment by mark-lunarg** [comment]
@dor666, thanks for the simple repro case.  I was able to reproduce the crash in Visual Studio and see this in the output window:

```
VUID-VkPipelineShaderStageCreateInfo-module-parameter(ERROR / SPEC): msgNum: 0 - Invalid VkShaderModule Object 0x40. The Vulkan spec states: module must be a valid VkShaderModule handle (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkPipelineShaderStageCreateInfo-module-parameter)
    Objects: 1
       [0]  0x40, type: 15, name: NULL
VUID-VkPipelineShaderStageCreateInfo-module-parameter(ERROR / SPEC): msgNum: 0 - Invalid VkShaderModule Object 0x41. The Vulkan spec states: module must be a valid VkShaderModule handle (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkPipelineShaderStageCreateInfo-module-parameter)
    Objects: 1
       [0]  0x41, type: 15, name: NULL
Exception thrown: read access violation.
**module** was nullptr.
```

At least in the configuration I have here, things seem to be working as intended.

**Comment by dor666** [comment]
@mark-lunarg 
Your're right Mark, I just tried it on two machines and everything works fine, two messages printed before crash.
I must have configured something wrong with debug output earlier.

I'm sorry for having bothered you. You can close this issue.

**Comment by mark-lunarg** [comment]
@dor666, no bother at all.  Thanks for your time!
