### ISSUE TITLE
Heads Up: 1.1.130 validusage.json contains some significant textual, but non-semantic changes

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-ValidationLayers#1421]
We accepted in MR in the 1.1.130 spec update that changes the markup used on most structure names in VU statements, so there are many, many diffs of the form

```
-<p><a id="VUID-vkCreateInstance-pInstance-parameter"></a> <code>pInstance</code> <strong class="purple">must</strong> be a valid pointer to a <code>VkInstance</code> handle</p>  
+<p><a id="VUID-vkCreateInstance-pInstance-parameter"></a> <code>pInstance</code> <strong class="purple">must</strong> be a valid pointer to a <a href="#VkInstance">VkInstance</a> handle</p>
```

in the new validusage.json, relative to 1.1.129. I don't know if this affects how you do a VL update, but wanted to make sure you folks had some notice. There are a few meaningful changes and new VU amidst the sea of markup, unfortunately.

**Comment by oddhack** [comment]
Feel free to close once the right people have seen it, there's no direct action called for though it may have implications for your process.

**Comment by mark-lunarg** [comment]
Thanks @oddhack for the heads-up -- updated in pr #1424.
