### ISSUE TITLE
Add support for VK_EXT_tooling_info

### ISSUE THREAD

**Issue by Tobski** [KhronosGroup/Vulkan-ValidationLayers#1422]
The Vulkan specification recently added the VK_EXT_tooling_info extension which adds queries to Vulkan about the tools that are currently active on a system, allowing developers to find out more information about the system environment, potentially saving many headaches. It would be great if the layers could add support for this extension to provide additional information about what is actually active.

**Comment by Tobski** [comment]
Addendum: By support here, I mean the layers should report themselves via this extension and whitelist it, there's no manual validation work to do AFAIK as it's just a query.

**Comment by mark-lunarg** [comment]
Addressed by PR #1430.
