### ISSUE TITLE
vkQueuePresentKHR validation bug

### ISSUE THREAD

**Issue by daemyung** [KhronosGroup/Vulkan-ValidationLayers#1423]
Normally presenting a swapchain image steps are like below.

1. Submit command buffers.
2. Present a swapchain image.

Both steps are synchronized by a semaphore.

Now I'm trying to little bit differently.

1. Present a swapchain image
2. Submit command buffers.

Also it's synchronized by a semaphore. Detail is below.

VkPresentInfoKHR present_info {};

present_info.waitSemaphoreCount = 1;
present_info.pWaitSemaphores = &render_semaphore;

vkQueuePresentKHR(queue_, &present_info);

VkSubmitInfo submit_info {};

submit_info.signalSemaphoreCount = 1;
submit_info.pSignalSemaphores = &render_semaphore;

vkQueueSubmit(queue_, 1, &submit_info, VK_NULL_HANDLE);

I think vkQueuePresentKHR will be pending until render_semaphore is signaled and this semaphore is signaled when a submitted command buffer is processed. So I think that I don't have to keep the calling function orders. Isn't it?

But validation layer reports below error messages.

UNASSIGNED-CoreValidation-DrawState-QueueForwardProgress(ERROR / SPEC): msgNum: 0 - VkQueue 0x102714e18[] is waiting on VkSemaphore 0xd000000000d[] that has no way to be signaled.
    Objects: 1
        [0] 0, type: 6, name: NULL
VUID-VkPresentInfoKHR-pImageIndices-01296(ERROR / SPEC): msgNum: 0 - Images passed to present must be in layout VK_IMAGE_LAYOUT_PRESENT_SRC_KHR or VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR but is in VK_IMAGE_LAYOUT_UNDEFINED. The Vulkan spec states: Each element of pImageIndices must be the index of a presentable image acquired from the swapchain specified by the corresponding element of the pSwapchains array, and the presented image subresource must be in the VK_IMAGE_LAYOUT_PRESENT_SRC_KHR layout at the time the operation is executed on a VkDevice (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkPresentInfoKHR-pImageIndices-01296)
    Objects: 1
        [0] 0x102714e18, type: 4, name: NULL

If I change the calling function order then it's find but my way looks good. Also I can't find any spec documentation about this.

**Comment by Tony-LunarG** [comment]
In section 32.9 of the spec, in the valid usage for vkQueuePresentKHR, it says:

**All elements of the pWaitSemaphores member of pPresentInfo must be semaphores that are signaled, or have semaphore signal operations previously submitted for execution.**

So you cannot submit the work that signals the semaphore after work waiting on the semaphore.

**Comment by daemyung** [comment]
Ok thanks...

But "**have semaphore signal operations previously submitted for execution**" looks wired. It looks like that even I use semaphores I need to care about submitting command buffers in order.

**A semaphore can be signaled after execution of a queue operation is completed, and a queue operation can wait for a semaphore to become signaled before it begins execution.**" https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkSemaphore.html

I try to synchronize between Graphics Queue and Present Queue. Before submit a command buffer to Graphics Queue, submitting a present command to Present Queue is not a problem as I think.  A present command will wait until pWaitSemaphores are signaled. After a command buffer which is submitted to Graphics Queue is processed and pWaitSemaphores are signaled. Then Present Queue can execute a present command. Isn't it make sense? There is no limitation about submitting command buffers so I think the spec documentation is wrong.

**Comment by mark-lunarg** [comment]
#daemyung, for spec questions, bugs, or interpretations, the best place to raise an issue is in the [Vulkan-Docs repo ](https://github.com/KhronosGroup/Vulkan-Docs/issues)-- it is there that these questions will get answered or addressed.  This repo is targeted at enforcing the existing spec, even in cases of incorrect or unclear valid usage.

**Comment by Tony-LunarG** [comment]
Actually, your vkQueueSubmit should be waiting for the semaphore you supplied to vkAcquireNextImageKHR.  See this Khronos synchronization example for the canonical way to acquire and present swapchain images.
https://github.com/KhronosGroup/Vulkan-Docs/wiki/Synchronization-Examples#swapchain-image-acquire-and-present

**Comment by daemyung** [comment]
@Tony-LunarG That's not my concern. My concern is that present a swapchain image after rendering is done. So vkQueuePresentKHR should be waiting for the semaphore I supplied to vkQueueSubmit. And the current issue is that validation layers report error messages depends on API call order. It's NOT considering the semaphore.

**Comment by daemyung** [comment]
@mark-lunarg I raise up an issue at https://github.com/KhronosGroup/Vulkan-Docs/issues/1139. How can I handle this issue?

**Comment by mark-lunarg** [comment]
As there's nothing for us to due until the spec language is clarified, we'll close.
