### ISSUE TITLE
Allow using Vulkan-Headers installed on the system

### ISSUE THREAD

**Issue by sarnex** [KhronosGroup/Vulkan-ValidationLayers#144]
Hi, 

I am a maintainer for Gentoo. We cannot have Vulkan-Headers as a submoduble as it currently is, so it is packaged separately. Right now, there only way to use the system version of Vulkan-Headers is to manually modify the source, as I have done below for Vulkan-Loader:

https://raw.githubusercontent.com/gentoo/gentoo/master/media-libs/vulkan-loader/files/vulkan-loader-9999-Use-usr-for-vulkan-headers.patch

Please allow a way to use the system Vulkan-Headers install, perhaps with a -DVULKAN_HEADERS_INSTALL_DIR variable.

Thanks,
Sarnex

**Comment by krOoze** [comment]
`-DVULKAN_HEADERS_INSTALL_DIR` has been added today...

**Comment by sarnex** [comment]
Fixed in https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/cd83f4cb83aad4b279642beb9e9d6bd988b66338
