### ISSUE TITLE
VkPhysicalDeviceFloatControlsPropertiesKHR is never queried

### ISSUE THREAD

**Issue by ReinUsesLisp** [KhronosGroup/Vulkan-ValidationLayers#1448]
`VkPhysicalDeviceFloatControlsPropertiesKHR float_controls_props` is declared and read but it's never loaded, resulting in false errors on SPIR-V shaders using `SPV_KHR_float_controls`.

We can see in [state_tracker.h](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/state_tracker.h#L1097) it's declared, but then in [state_tracker.cpp](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/state_tracker.cpp#L1160-L1194) it's never loaded to the `pNext` chain.

**Comment by mark-lunarg** [comment]
Updated statetracker with commit e4a2b7f227824917f252bb8f5fde8580eacc5c38 to initialize the properties -- please retry and see if this addresses your issue.
