### ISSUE TITLE
Add support for VK_KHR_draw_indirect_count

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-ValidationLayers#145]
New extension [VK_KHR_draw_indirect_count](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_KHR_draw_indirect_count) is a modified version of [VK_AMD_draw_indirect_count](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_AMD_draw_indirect_count).
When this lands with next header release, need to update validation to support functions for new extensions, which should be able to use same core functionality from AMD extension.
Note that this will fix the issue @SaschaWillems points out in this [tweet](https://twitter.com/SaschaWillems2/status/1000718698032844800?s=19).

**Comment by pdaniell-nv** [comment]
See https://github.com/KhronosGroup/Vulkan-Docs/issues/719.

**Comment by tobine** [comment]
A few general points to bring up here.
Khronos now has a requirement for new extensions to include at least basic validation support so should see support land very near release.
Note that vulkan header updates in Validation repo typically lag the header update by ~1 week which limits the earliest point at which validation layers will support a new extension.
In many of these crash situations the layer that causes the crash is the unique_objects layer, which is on the bottom of the layer stack (call just before driver) and remaps handles so if you're on the bleeding-edge you may still be able to run with validation layers without crash by just disabling the unique_objects layer.

**Comment by pdaniell-nv** [comment]
Validation implementing pending review and approval is here: https://gitlab.khronos.org/vulkan/Vulkan-ValidationLayers/merge_requests/2

**Comment by pdaniell-nv** [comment]
Now here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/188

**Comment by mark-lunarg** [comment]
This was merged as part of #188.
