### ISSUE TITLE
Reduce overzealous warning spam for suboptimal swapchains

### ISSUE THREAD

**Issue by haasn** [KhronosGroup/Vulkan-ValidationLayers#1450]
In #1101 you added a perf warning for queueing images to a suboptimal swapchain. However, I think this warning is currently overzealous - and, ironically, might even be misleading / damaging for performance. A single presentation to a suboptimal swapchain is not only completely fine, but also expected if the user is resizing the window with the mouse.

Trying to suppress this by immediately recreating the swapchain all the time actually *decreases* smoothness / performance during live window resizes in my testing - the best thing to do is to continue rendering and presenting the suboptimal frame and then recreate the swapchain afterwards. (In fact, that's the whole reason VK_SUBOPTIMAL_KHR even exists - to allow handling continuous resizes gracefully, possibly with the compositor blitting/scaling the contents to make up for the mismatch)

I do agree that a performance warning like this makes sense, but I would like to add the condition that you should only warn if the user seems to be *persistently* presenting to suboptimal swapchains. My simple suggestion would be to use some sort of internal counter, and only emit the warning once this counter surpasses a threshold number of queued presentations. The counter should be reset if the user recreates the swapchain. (Which I guess would imply moving it from stateless to stateful validation)

**Comment by mark-lunarg** [comment]
@tobine, these are the warnings added at your request, is moving them to Best Practices OK with you?  @camden-lunarg, can you please move these warnings to the BP object if @tobine signs off on it?

**Comment by camden-lunarg** [comment]
@mark-lunarg Is this warning good to be moved to BP? I never saw a sign off fro @tobine

**Comment by mark-lunarg** [comment]
Yeah, let's do it.
