### ISSUE TITLE
VK_IMAGE_VIEW_TYPE_2D_ARRAY is not compatible with image type VK_IMAGE_TYPE_3D

### ISSUE THREAD

**Issue by wumo** [KhronosGroup/Vulkan-ValidationLayers#1451]
The [vulkan-specs](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkImageViewCreateInfo.html) lists the Image and image view parameter compatibility requirements as :
<img width="716" alt="table" src="https://user-images.githubusercontent.com/7351935/71440049-f75ce900-2736-11ea-8d05-50814da1de18.png">
This allows ` VK_IMAGE_TYPE_3D` created with `VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT` to have `VK_IMAGE_VIEW_TYPE_2D_ARRAY` view and `layerCount` be the same as `extent.depth`.

But validation layer reports error for this:
```
validation layer: vkCreateImageView(): pCreateInfo->viewType VK_IMAGE_VIEW_TYPE_2D_ARRAY is not compatible with image ty
pe VK_IMAGE_TYPE_3D. The Vulkan spec states: subresourceRange and viewType must be compatible with the image, as describ
ed in the compatibility table (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkImag
eViewCreateInfo-subResourceRange-01021)
```
and 
```
validation layer: vkCreateImageView: pCreateInfo->subresourceRange.baseArrayLayer + .layerCount (= 0 + 32 = 32) is great
er than the arrayLayers of the image when it was created (i.e. greater than 1). The Vulkan spec states: If subresourceRa
nge.layerCount is not VK_REMAINING_ARRAY_LAYERS, subresourceRange.baseArrayLayer + subresourceRange.layerCount must be l
ess than or equal to the arrayLayers specified in VkImageCreateInfo when image was created (https://www.khronos.org/regi
stry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkImageViewCreateInfo-subresourceRange-01719)
```

**Comment by krOoze** [comment]
Seems to be implemented.

Either `VK_KHR_maintenance1` has to be enabled or `VkApplicationInfo::apiVersion` and `VkPhysicalDeviceProperties::apiVersion` must both be >= 1.1. Did you do that?

**Comment by mark-lunarg** [comment]
Pinging @wumo...

**Comment by mark-lunarg** [comment]
There are existing tests for these validation checks, `VkLayerTest.CreateImageViewBreaksParameterCompatibilityRequirements` and `VkLayerTest.CreateImageViewInvalidSubresourceRange`.  If your app has met the conditions @krOoze has specified and still feel that the validation is in error, please respond and we will reopen this issue.  Thanks!
