### ISSUE TITLE
Warn for bad uses of VK_ACCESS_MEMORY_* and *_OF_PIPE

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-ValidationLayers#1453]
#24 

1) Warn when using `VK_ACCESS_MEMORY_*` with only `*_OF_PIPE_BIT`.

2) Warn when using `VK_ACCESS_MEMORY_WRITE` with only read-only stages (and vice-versa)

3) Warn when using `*_OF_PIPE_BIT` where user semantically meant `VK_PIPELINE_STAGE_ALL_COMMANDS_BIT`

**Comment by mark-lunarg** [comment]
Moved into Tracking Issue #24!  Thanks Petr.
