### ISSUE TITLE
`CompatForSet` compairs pointers, and there's unused `PipelineLayoutCompatDef::operator==`?

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-ValidationLayers#1459]
I got a validation layer error that I'm not quite understanding, and I traced it to this:

```C++
if (pPipe->active_slots.size() > 0 && !CompatForSet(pPipe->max_active_slot, state, pipeline_layout->compat_for_set)) {
    result |= log_msg(report_data, VK_DEBUG_REPORT_ERROR_BIT_EXT, VK_DEBUG_REPORT_OBJECT_TYPE_PIPELINE_EXT,
                      HandleToUint64(pPipe->pipeline), string_VuidNotCompatibleForSet(cmd_type),
                      "%s(): %s defined with %s is not compatible for maximum set statically used %" PRIu32
                      " with bound descriptor sets, last bound with %s",
                      command_name_list[cmd_type], report_data->FormatHandle(pPipe->pipeline).c_str(),
                      report_data->FormatHandle(pipeline_layout->layout).c_str(), pPipe->max_active_slot,
                      report_data->FormatHandle(state.pipeline_layout).c_str());
}
```

I noticed in `CompatForSet`, there's a comparison of `compat_id_for_set`, of type `PipelineLayoutCompatId = PipelineLayoutCompatDict::Id = std::shared_ptr<const PipelineLayoutCompatDef>`. I also noticed that `PipelineLayoutCompatDef` has an `operator ==`. However, the type being `std::shared_ptr`, only a pointer comparison is made.

Is that intentional? Adding logs in `PipelineLayoutCompatDef::operator==`, I don't see it called, at least not in a few basic tests.

**Comment by ShabbyX** [comment]
For what it's worth, I learned that the validation error was indeed legitimate and that the application was reusing a descriptor set that was bound to slot N, where the layout of slot M<N was changed.

So, I'm not questioning the validation error itself. You may still want to double check the code here to see if the pointer comparison is intentional.

**Comment by jzulauf-lunarg** [comment]
@ShabbyX -- the PipelineLayoutCompatId are in fact pointers to entries in the canonical forms dictionary for layout compatible-ness.  The == operator is used in the with the PipelineLayoutCompatDict dictionary that stores the canonical forms.

So I believe this is "as designed".  Happy to hear we caught your layout compat issue.
