### ISSUE TITLE
vkDebugUtilsMessengerCallbackEXT not respecting all flags

### ISSUE THREAD

**Issue by RCalocaO** [KhronosGroup/Vulkan-ValidationLayers#146]
On SDK 1.1.73.0
Using
VkDebugUtilsMessengerCreateInfoEXT CreateInfo;
[...]
messageSeverity = 4352;
messageType = 3;
(so NOT VK_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT)

I do get callbacks like:
 MsgType = 6
pMessage = 0x0000026165934bf0 "vertex shader writes to output location 0.0 which is not consumed by fragment shader" 

which is a performance warning.

**Comment by MarkY-LunarG** [comment]
Thanks for catching this.  It should be resolved now.
