### ISSUE TITLE
Links to the spec should point to the chunked spec

### ISSUE THREAD

**Issue by DethRaid** [KhronosGroup/Vulkan-ValidationLayers#1462]
Links to the spec in error messages, such as "ERROR: [Validation] [Validation]  Objects: Command Buffer (1b2ef6de1d0)  vkCmdPipelineBarrier(): pImageMemBarriers[0].srcAccessMask (0x800) is not supported by srcStageMask (0x1). The Vulkan spec states: Each element of pMemoryBarriers, pBufferMemoryBarriers and pImageMemoryBarriers must not have any access flag included in its srcAccessMask member if that bit is not supported by any of the pipeline stages in srcStageMask, as specified in the table of supported access types. (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdPipelineBarrier-pMemoryBarriers-01184)", include a link to the part of the spec that the use has violated, but they link to the single-html-file version of the spec. This version takes a while to load and the VUIDs don't seem to work very well. Instead, I'd like for the spec links in validation messages to link to the chunked version of the Vulkan specm

**Comment by mark-lunarg** [comment]
If the VUIDs were explicitly included in the spec as tags _and_ text, specifically in the PDF version which loads much faster, this would be straightforward.  However, implementing this change in the layers would require that the three HTML versions of the specification be parsed, which we wish to avoid.
This might be raised as an issue in the [Vulkan-Docs repo](https://github.com/KhronosGroup/Vulkan-Docs) -- we have long pushed for the VUIDs to be visible in the specification.

**Comment by krOoze** [comment]
With https://github.com/KhronosGroup/Vulkan-Docs/pull/1285 this should be possible. So I am soliciting feedback for that.

Additionally, I think it would be nice to also request a permanent `khr.io` shortlink?

**Comment by mark-lunarg** [comment]
Yes, this would be a much better solution.  We thought that using the PDF version would help quite a bit, but ran into platform consistency/reliability issues with it and had to go back to linking to the full spec.  Good luck!
