### ISSUE TITLE
regression in vkGetInstanceProcAddr() with commit 9086e801366f2c5c888a80de1ad6f60f26f0dea7

### ISSUE THREAD

**Issue by brianpaul** [KhronosGroup/Vulkan-ValidationLayers#1469]
My application calls vkGetInstanceProcAddr() for the transform feedback extension functions ("vkBindTransformFeedbackBuffersEXT" for example).

Prior to commit 9086e801366f2c5c888a80de1ad6f60f26f0dea7 there was no issue.  But now the pointer returned from vkGetInstanceProcAddr("vkBindTransformFeedbackBuffersEXT") points to 0x7fffef2c208e <vkPhysDevExtTramp3> and when execution jumps there we wind up in vulkan_layer_chassis::CreateFramebuffer() and crash soon after.

The same issue seems to happen with the VK_EXT_conditional_rendering extension.

**Comment by mark-lunarg** [comment]
Are there any validation errors or messages that appear before your crash?  
Is it possible that could you provide a simple repro case?  When I try this (with `vk`**Cmd**`BindTransformFeedbackBuffersEXT`), it works as expected.  Neither of these extensions or entrypoints is apparently affected by the changes in this commit, which is simply adding the `vkGetPhysicalDeviceProcAddr()` entrypoint.

**Comment by brianpaul** [comment]
Hi Mark,

I don't have a small, open repro case to share here, but I can share my
test app with you.  I'll send it to your email asap.

-Brian

**Comment by mark-lunarg** [comment]
A quick update -- @brianpaul was kind enough to provide a simple repro case, but the issue does not appear to manifest on our test systems.  We are still pursuing the discrepancies offline.

**Comment by mark-lunarg** [comment]
Closing for now, please reopen or comment if additional information comes to light.  Thanks!
