### ISSUE TITLE
DebugUtilsMessenger not working in SDK 130

### ISSUE THREAD

**Issue by Zingam** [KhronosGroup/Vulkan-ValidationLayers#1471]
I have tested my code on a laptop with Intel HD620 and I believe SDK 106. Debug messages are printed out through the DebugUtilsMessanger callback.
When the same code is run on a laptop with Intel HD630/NVIDIA GeForce and SDK 130 the callback is not called, so there is no output. However I made a small test with `vkSubmitDebugUtilsMessageEXT` and in that case the callback is called with my message as expected.

I checked VIA, Vulkan Cube, Vulkan Configurator and everything seems fine to me. I googled for solutions or similar issues but there doesn't seem to be any.

**Comment by mark-lunarg** [comment]
@Zingam, I'm guessing this is on Windows -- do you have a repro case you can share here or privately?  Also, are you able to build and use the layers from this repo, or maybe more recent layers available in the [appveyor build artifacts](https://ci.appveyor.com/project/Khronoswebmaster/vulkan-validationlayers/builds/29930931/job/6a3nifp53vl88m96/artifacts)?  Our internal/external windows tests seem to be passing, so any additional data we have will be most helpful.

**Comment by Zingam** [comment]
Sorry about that! I am on the latest version of Windows 10 with nearly the latest drivers.
I decided to try third party samples also.
I copied the appveyor files to the SDK folder and I cloned: 
https://github.com/SaschaWillems/Vulkan
I enabled the validation and I opened the project in VS2019 and run the "triangle.exe" sample. I still got no validation info.
Then I modified the sample to use `vkSubmitDebugUtilsMessageEXT` and I still got the previously described result:
```
		void setupDebugging(VkInstance instance, VkDebugReportFlagsEXT flags, VkDebugReportCallbackEXT callBack)
		{

			vkCreateDebugUtilsMessengerEXT = reinterpret_cast<PFN_vkCreateDebugUtilsMessengerEXT>(vkGetInstanceProcAddr(instance, "vkCreateDebugUtilsMessengerEXT"));
			vkDestroyDebugUtilsMessengerEXT = reinterpret_cast<PFN_vkDestroyDebugUtilsMessengerEXT>(vkGetInstanceProcAddr(instance, "vkDestroyDebugUtilsMessengerEXT"));

			VkDebugUtilsMessengerCreateInfoEXT debugUtilsMessengerCI{};
			debugUtilsMessengerCI.sType = VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT;
			debugUtilsMessengerCI.messageSeverity = VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT | VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT;
			debugUtilsMessengerCI.messageType = VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT | VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT;
			debugUtilsMessengerCI.pfnUserCallback = debugUtilsMessengerCallback;
			VkResult result = vkCreateDebugUtilsMessengerEXT(instance, &debugUtilsMessengerCI, nullptr, &debugUtilsMessenger);
			assert(result == VK_SUCCESS);

			using namespace std::string_literals;

			std::vector<std::pair<VkDebugUtilsMessageSeverityFlagBitsEXT, std::string>>
				messageSeverityFlags{
				  { VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT, "Verbose"s },
				  { VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT, "Info"s },
				  { VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT, "Warning"s },
				  { VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT, "Error"s }
			};
			std::vector<std::pair<VkDebugUtilsMessageTypeFlagBitsEXT, std::string>>
				messageTypeFlags{
				  { VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT, "General"s },
				  { VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT, "Validation"s },
				  { VK_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT, "Performance"s }
			};
			for (auto const messageSeverity : messageSeverityFlags) {
				for (auto const messageType : messageTypeFlags) {
					std::string message{ "Callback Test: severity - "s +
										 messageSeverity.second + ", type - "s +
										 messageType.second };

					VkDebugUtilsMessengerCallbackDataEXT callbackData{};
					callbackData.sType =
						VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CALLBACK_DATA_EXT;
					callbackData.pNext = nullptr;
					callbackData.flags = 0u;
					callbackData.pMessageIdName = "Debug Message";
					callbackData.messageIdNumber = 1;
					callbackData.pMessage = message.c_str();
					callbackData.queueLabelCount = 0;
					callbackData.pQueueLabels = nullptr;
					callbackData.cmdBufLabelCount = 0;
					callbackData.pCmdBufLabels = nullptr;
					callbackData.objectCount = 0;
					callbackData.pObjects = nullptr;

					auto vkSubmitDebugUtilsMessage =
						reinterpret_cast<PFN_vkSubmitDebugUtilsMessageEXT>(
							vkGetInstanceProcAddr(instance, "vkSubmitDebugUtilsMessageEXT"));
					assert(
						(nullptr != vkSubmitDebugUtilsMessage) &&
						"VK_EXT_debug_utils extension is not present!");

					vkSubmitDebugUtilsMessage(
						instance, messageSeverity.first, messageType.first, &callbackData);
				}
			}
		}
```

![image](https://user-images.githubusercontent.com/3337419/72105522-5c6b2e00-3336-11ea-86ee-a845a38ac260.png)

**Comment by mark-lunarg** [comment]
@Zingam, if there are no errors, there should be no output.  1.1.106 is pretty old, and my hunch is that you were used to getting a bunch of object-related informational output which has since been removed.  You might try to deliberately induce an error to prove that things are working as expected -- pass in zero for a command buffer or something like that.

**Comment by Zingam** [comment]
So I should not get any output about creating and destroying a vulkan surface?

**Comment by Zingam** [comment]
@mark-lunarg Thank you! You appear to be right and the information on the internet outdated:
![image](https://user-images.githubusercontent.com/3337419/72108089-71968b80-333b-11ea-9cc4-5cf8602043f2.png)

**Comment by mark-lunarg** [comment]
Much effort has been put into reducing unnecessary spew -- we try very hard not to complain if you are doing something right.  The error database will tell you which VUIDs are checked, if that's what you mean by output.

**Comment by Zingam** [comment]
@mark-lunarg Thank you for clarifying the situation. Maybe it is my omission but these changes should be documented more clearly in light of the outdated examples out there. Perhaps a simple "Hello world"-type message could be issued once the messenger is registered. Also the database https://vulkan.lunarg.com/doc/sdk/1.1.130.0/windows/validation_error_database.html should be linked to the TOC of the documentation: https://vulkan.lunarg.com/doc/sdk/1.1.130.0/windows/getting_started.html
After all who reads the README files.

**Comment by mark-lunarg** [comment]
@Zingam, I've had such a PR on my machine for three years now, but we have overwhelmingly heard back from folks that they want ZERO informational messages from the layers -- for instance, installations where many hundreds of applications are tested would have to deal with the extra noise.  OTOH, point me to any out-of-date documentation and I'll do what I can to get them updated!  Thanks again!

**Comment by Zingam** [comment]
@mark-lunarg I talk about third party tutorials and books that contain outdated information. But maybe you could add samples, more notes about the current situation, maybe even a tool, how to test that the layers are workings as expected, which for me isn't a big deal any longer
In that context I think that enumerating the device extensions produces info messages of the sort:

> "! Validation ! [Vulkan] - [Layer] :    Device Extension: VK_EXT_pipeline_creation_feedback (C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_d6a74c40738c4b56\.\igvk64.dll) version 0.0.1"

Which I think are purely informational and are not covered by what is described in the database. Is this intentional?

**Comment by mark-lunarg** [comment]
I believe those messages might be coming from the Vulkan Loader, I don't think the layers output anything.  Thanks for all the good feedback!
