### ISSUE TITLE
Pipeline statistics query sporadically returns 0xFFFFFFFFFFFFFFFF in all fields

### ISSUE THREAD

**Issue by DiligentGraphics** [KhronosGroup/Vulkan-ValidationLayers#1475]
We face the following problem that is only reproducible when validation layers are enabled: pipeline statistics query sometimes indicates that the data is available and returns `0xFFFFFFFFFFFFFFFF` in all fields.
We use the following commands to get the query data:
- `vkCmdResetQueryPool`
- `vkCmdBeginQuery`
- `vkCmdEndQuery`
- Check the fence to wait until all commands are executed by the GPU
- `vkGetQueryPoolResults(VK_QUERY_RESULT_64_BIT | VK_QUERY_RESULT_WITH_AVAILABILITY_BIT)`

This works almost all the time, however sporadically the data in all fields is set to `0xFFFFFFFFFFFFFFFF`, while the last element in the array is set to `1`, which indicates that the data is available.

The spec says that `vkGetQueryPoolResults` should either write `1` as the availability flag and write correct data, or write `0` and leave the rest fields unchanged. The behavior when it writes `1` and `0xFFFFFFFFFFFFFFFF` is not described.

We tested with 1.1.130.0 SDK.

Update: the issue seems to be reproducible without validation layer as well, but maybe you can still suggest what might be the problem here.

**Comment by mark-lunarg** [comment]
@DiligentGraphics, the layers do not change, copy, or even examine the data returned from the driver.  If this issue occurs with _AND_ without any layers present, circumstances strongly point to the display driver.  It might be that differences in the frequency of occurrence between the two scenarios could be attributed to the difference in timing.  Which graphics hardware has this manifested on?  Does it happen for all hardware and all drivers?

**Comment by DiligentGraphics** [comment]
Sorry about the noise. This was a driver issue. Updating the driver fixed the problem.
