### ISSUE TITLE
vkCmdCopyImage missing VUID 122 and 123 for YUV planes

### ISSUE THREAD

**Issue by tambry** [KhronosGroup/Vulkan-ValidationLayers#1499]
From the spec:
* The source region specified by each element of `pRegions` [...] must be a region that is contained within the plane being copied if the `srcImage`’s VkFormat is a multi-planar format (VUID 122)
* The destination region specified by each element of `pRegions` [...] must be a region that is contained within the plane being copied to if the `dstImage`’s VkFormat is a multi-planar format (VUID 123)

Sample (source code and compiled Linux executable):
[copy.zip](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/4107345/copy.zip)

Running the sample on AMD RX 5700 with the RADV driver causes a GPU hang. The computer needs to be forcefully reset.  
The GPU hang made this problem really hard to trace down and debug in my application. Took multiple days.

**Comment by sfricke-samsung** [comment]
Hey @tambry I will be happy to cover this as I am currently trying to add more general YUV support. I realize part of the issue here is related to the [Vulkan Spec](https://github.com/KhronosGroup/Vulkan-Docs/blob/master/chapters/copies.txt#L340). The spec has the ability to generate various variations with the `ifdef` and `endif` statements, but currently there isn't support to do it in the middle of the VUID. I realized I never caught this VUID because it didn't show up when I ran the vk_validation_stats.py script

I will make a change for this in the Vulkan Spec to have it get properly sorted out. This is done by adding 2 VUID for each 00122 and 00123 to cover the case when the spec contains `VK_KHR_sampler_ycbcr_conversion` or version 1.1

My idea is to keep the non YUV as the original 00122 and 00123 as they are implemented already. @mark-lunarg What is your thought if I added a UNASSIGNED VUID for the time being for these 2 cases and just updated the VUID when the fixed spec get into a head downstream?

**Comment by tambry** [comment]
@sfricke-samsung Thank you for your work on the YUV VUIDs. Due to missing coverage in validation layers developing an application that uses YUV samplers took me way longer than it should've.

**Comment by sfricke-samsung** [comment]
agreed as the Vulkan YUV documentation/support as a whole feel through (its not a topic is as familiar with in graphics), also there is now a [section in the Vulkan Guide](https://github.com/KhronosGroup/Vulkan-Guide/blob/master/chapters/extensions/VK_KHR_sampler_ycbcr_conversion.md) to also help aid with this.

**Comment by sfricke-samsung** [comment]
@tambry So looking even MORE into this, I tried your app and curious what version of the Validation Layers you used to test. The `VUID-VkImageCopy-srcOffset-00144` and `VUID-VkImageCopy-dstOffset-00150` should have caught the issue you had (It did when I ran your test copy application).

I actually think the new answer is not what I stated above, but instead remove 00122 and 00123 as "a region that is contained" is not defined well anywhere, but the series of 00144, 00145, 00147 and 00150, 00151, 00153 cover the cases in detail with regards to if it is src or depth and also if it is the x, y, z extent that exceeded.

**Comment by tambry** [comment]
@sfricke-samsung I think I used 1.1.126.0, as that was what was available on Debian at the time. I'll try again with validation layers from the master branch once I'm at the office on Monday.

**Comment by tambry** [comment]
@sfricke-samsung With validation layers from the master branch, I'm still seeing a GPU hang when running the copy executable. As far as I can tell, if validation layers caught it, the call would be skipped and I wouldn't be seeing a hang.

I tried `export VK_LOADER_DEBUG=all; export VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_api_dump:VK_LAYER_KHRONOS_validation`. I see plenty of loader debug output regarding device extensions and seems `VK_LAYER_KRHONOS_validation` is also loaded.  
Any ideas as to what I should try?

For reference, I'm using AMD RX 5700 on Debian Unstable with Mesa 20.0.

**Comment by sfricke-samsung** [comment]
This is what i get when I run it on Ubuntu with Mock ICD driver and ToT validation
```
$ cmake --build .
[100%] Built target copy
$ ./copy 
[VUID-VkImageSubresourceLayers-aspectMask-parameter] [ VUID-VkImageSubresourceLayers-aspectMask-parameter ] Object: 0x2631dc0 (Type = 3) | vkCmdCopyImage() parameter, VkImageAspect pRegions->srcSubresource.aspectMask, is an unrecognized enumerator. The Vulkan spec states: aspectMask must be a valid combination of VkImageAspectFlagBits values (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkImageSubresourceLayers-aspectMask-parameter)
[VUID-VkImageSubresourceLayers-aspectMask-parameter] [ VUID-VkImageSubresourceLayers-aspectMask-parameter ] Object: 0x2631dc0 (Type = 3) | vkCmdCopyImage() parameter, VkImageAspect pRegions->dstSubresource.aspectMask, is an unrecognized enumerator. The Vulkan spec states: aspectMask must be a valid combination of VkImageAspectFlagBits values (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkImageSubresourceLayers-aspectMask-parameter)
[VUID-vkCmdCopyImage-pRegions-00122] [ VUID-vkCmdCopyImage-pRegions-00122 ] Object: 0x255e5e0 (Type = 6) | vkCmdCopyImage(): Source pRegion[0] with mipLevel [ 0 ], offset [ 0, 0, 0 ], extent [ 128, 128, 1 ] exceeds the source image dimensions. The Vulkan spec states: The source region specified by each element of pRegions must be a region that is contained within srcImage (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdCopyImage-pRegions-00122)
[VUID-vkCmdCopyImage-pRegions-00123] [ VUID-vkCmdCopyImage-pRegions-00123 ] Object: 0x255e5e0 (Type = 6) | vkCmdCopyImage(): Dest pRegion[0] with mipLevel [ 0 ], offset [ 0, 0, 0 ], extent [ 128, 128, 1 ] exceeds the destination image dimensions. The Vulkan spec states: The destination region specified by each element of pRegions must be a region that is contained within dstImage (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdCopyImage-pRegions-00123)
[VUID-VkImageCopy-srcOffset-00144] [ VUID-VkImageCopy-srcOffset-00144 ] Object: 0x255e5e0 (Type = 6) | vkCmdCopyImage(): Source image pRegion 0 x-dimension offset [0] + extent [128] exceeds subResource width [64]. The Vulkan spec states: srcOffset.x and (extent.width + srcOffset.x) must both be greater than or equal to 0 and less than or equal to the source image subresource width (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkImageCopy-srcOffset-00144)
[VUID-VkImageCopy-srcOffset-00145] [ VUID-VkImageCopy-srcOffset-00145 ] Object: 0x255e5e0 (Type = 6) | vkCmdCopyImage(): Source image pRegion 0 y-dimension offset [0] + extent [128] exceeds subResource height [64]. The Vulkan spec states: srcOffset.y and (extent.height + srcOffset.y) must both be greater than or equal to 0 and less than or equal to the source image subresource height (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkImageCopy-srcOffset-00145)
[VUID-VkImageCopy-dstOffset-00150] [ VUID-VkImageCopy-dstOffset-00150 ] Object: 0x255e5e0 (Type = 6) | vkCmdCopyImage(): Dest image pRegion 0 x-dimension offset [0] + extent [128] exceeds subResource width [64]. The Vulkan spec states: dstOffset.x and (extent.width + dstOffset.x) must both be greater than or equal to 0 and less than or equal to the destination image subresource width (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkImageCopy-dstOffset-00150)
[VUID-VkImageCopy-dstOffset-00151] [ VUID-VkImageCopy-dstOffset-00151 ] Object: 0x255e5e0 (Type = 6) | vkCmdCopyImage(): Dest image pRegion 0 y-dimension offset [0] + extent [128] exceeds subResource height [64]. The Vulkan spec states: dstOffset.y and (extent.height + dstOffset.y) must both be greater than or equal to 0 and less than or equal to the destination image subresource height (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkImageCopy-dstOffset-00151)
```

**Comment by sfricke-samsung** [comment]
@tambry 2 questions

1. Have you varified the layers are being loaded, try setting something obvious that would trigger a error. I know silly question, but I have had issues in past because didn't realize layers weren't set
```
$ export VK_LAYER_PATH=$VULKAN_SDK/lib/vulkan/layers
$ export LD_LIBRARY_PATH=$VULKAN_SDK/lib:$VULKAN_SDK/lib/vulkan/layers
$ export VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation
```

2. I added some Tests to validation layers in PR linked to issue, they seem to mock the same style of copy your example had

**Comment by tambry** [comment]
@sfricke-samsung I'm using validation layers built from the master branch and have `ninja install`-ed them for the user. `vulkaninfo` shows validation layers 1.2.133 validation layers existing, so they must be getting loaded.

For example setting `VkCommandPoolCreateInfo::flags` to 0x8 does result in a validation error. But still no errors related to the out-of-bounds image copy.  
Since this works for you, this can probably be closed. Something about my installation must be borked.

I'm unable to run validation layer tests either, as half-way through I get "Floating point exception". Will open a separate issue for that.
