### ISSUE TITLE
Scrub semaphore validation

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#15]
**Issue by [tobine](https://github.com/tobine) (MIGRATED)**
_Monday Dec 19, 2016 at 15:52 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1285_

----

With recent updates to spec synchronization, need to scrub semaphore validation to make sure that all valid usage cases are covered and correct. Also, while scrubbing, can make sure that unique error ids are in place for all semaphore checks.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/tobine"><img src="https://avatars0.githubusercontent.com/u/7526739?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tobine](https://github.com/tobine) (MIGRATED)**
_Tuesday Mar 21, 2017 at 15:09 GMT_

----

Also want to add hazard detection for things like WaW cases without proper synchronization. Not certain if this will go in validation layers or a potential separate layer but adding here for now for tracking purposes and will spin off into a separate issue if/when appropriate.

**Comment by jzulauf-lunarg** [comment]
Triage notes: This is part of a larger effort for greatly improving synchronization validation

@jzulauf-lunarg consolidate this into an overarching sync issue.

**Comment by mark-lunarg** [comment]
Added this issue to the main Synchronization Tracking Issue, #72.
