### ISSUE TITLE
False positive for "InconsistentSpirv" when VK_EXT_scalar_block_layout is used.

### ISSUE THREAD

**Issue by tomilov** [KhronosGroup/Vulkan-ValidationLayers#1500]
To be short: initially problem faced when I deal with `spirv-opt`. Corresponding ticket is [here](https://github.com/KhronosGroup/SPIRV-Tools/issues/3153).

**Comment by tomilov** [comment]
Seems I missed to add `vk::PhysicalDeviceScalarBlockLayoutFeatures` with `scalarBlockLayout = VK_TRUE;` to `vk::StructureChain` of `vk::CreateDeviceInfo`. Maybe warning message just shoud suggest this.

**Comment by jeremy-lunarg** [comment]
We don't have enough information to detect that you intended to enable that feature. There's nothing trivially identifiable in the SPIR-V. In fact, we'd need query that feature to validate the module during shader validation.
