### ISSUE TITLE
vkWaitSemaphores not enough to revert Command Buffers from Pending state, fence still needed

### ISSUE THREAD

**Issue by farnoy** [KhronosGroup/Vulkan-ValidationLayers#1502]
I realized that it's not enough to wait on the host with `vkWaitSemaphores` before cleaning up the submission data (namely the command buffer), that a `vkFence` still needs to be used with `vkQueueSubmit`.

I think this is a limitation of the validation layers, and my understanding of the spec is that this approach is sufficient and a Fence is not needed.

1. 5.5 in the spec, under `vkQueueSubmit`:
    > fence is an optional handle to a fence to be signaled once all submitted command buffers have completed execution. If fence is not VK_NULL_HANDLE, it defines a fence signal operation.
2. 5.5 in the spec, under `VkSubmitInfo`:
    > pSignalSemaphores is a pointer to an array of VkSemaphore handles which will be signaled when the command buffers for this batch have completed execution. If semaphores to be signaled are provided, they define a semaphore signal operation.

Sounds like they should be equivalent. But validation layers log an error when I'm not using a fence:

> ERROR:  [ VUID-vkFreeCommandBuffers-pCommandBuffers-00047 ] Object: 0x563cdd244cf0 (Type = 6) | Attempt to free VkCommandBuffer 0x563cdd244cf0[] which is in use. The Vulkan spec states: All elements of pCommandBuffers must not be in the pending state (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkFreeCommandBuffers-pCommandBuffers-00047) (code 0x00000000 from Validation at CommandBuffer:0)

I have modified one of the CTS tests to trigger this: https://github.com/KhronosGroup/VK-GL-CTS/compare/master...farnoy:timeline-semaphore-free-command-buffer?expand=1#diff-9fc6b33e64367b80bddbf7650d6cf11eR155-R165

I have the same error message on RADV x64 Linux 19.3.2 and on two recent proprietary AMD drivers on Windows 10 x64. My app, where I first encountered this, uses Vulkan 1.1. I'm not sure how the CTS is initialized, but in all my test cases the highest version of vk is 1.1.130, I haven't tested it on a 1.2 driver.

Is it a problem with validation layers, or am I misunderstanding the spec? Does "command buffers for this batch have completed execution" imply that these command buffers *must* revert to executable/invalid at the same time as the fence/semaphore signal?

If this is a problem with validation layers, I think it similarly also affects `vkUpdateDescriptorSets`. The `in_use` lifetime/state tracking might not be aware of timeline semaphores.

**Comment by Karutoh** [comment]
I have a similar issue when using Timeline Semaphores to load resources. When waiting on a semaphore to finish loading resources. It does not wait long enough for it all to finish executing. My errors are different.

```
Log - [Vulkan] <Warning> VkCreateSemaphore: timelineSemaphore feature is not enabled, can not create timeline semaphores The Vulkan spec states: If the timelineSemaphore feature is not enabled, semaphoreType must not equal VK_SEMAPHORE_TYPE_TIMELINE (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkSemaphoreTypeCreateInfo-timelineSemaphore-03252)
Log - [Vulkan] <Warning> Cannot call vkDestroySemaphore on VkSemaphore 0x8f32de000000003b[] that is currently in use by a command buffer. The Vulkan spec states: All submitted batches that refer to semaphore must have completed execution (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkDestroySemaphore-semaphore-01137)
Log - [Vulkan] <Warning> Attempt to free VkCommandBuffer 0x1d6a4389db0[] which is in use. The Vulkan spec states: All elements of pCommandBuffers must not be in the pending state (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkFreeCommandBuffers-pCommandBuffers-00047)
```

**Comment by jasuarez** [comment]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1511 has been merged, and a new https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1622 has been created to cover more cases

**Comment by jasuarez** [comment]
@farnoy is still this issue valid, after merging #1511 and #1622?

**Comment by HansKristian-Work** [comment]
I tried building validation layers from master and I still have this issue.

I also exclusively use vkWaitSemaphores instead of fences when timeline semaphores are enabled, and I get these false positives:

```
[ERROR]: [Vulkan]: Validation Error: Validation Error: [ VUID-vkResetCommandPool-commandPool-00040 ] Object 0: handle = 0x55555710fd30, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xb53e2331 | Attempt to reset command pool with VkCommandBuffer 0x55555710fd30[] which is in use. The Vulkan spec states: All VkCommandBuffer objects allocated from commandPool must not be in the pending state (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkResetCommandPool-commandPool-00040)
[ERROR]: [Vulkan]: Validation Error: Validation Error: [ VUID-vkResetCommandPool-commandPool-00040 ] Object 0: handle = 0x5555571c57a0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xb53e2331 | Attempt to reset command pool with VkCommandBuffer 0x5555571c57a0[] which is in use. The Vulkan spec states: All VkCommandBuffer objects allocated from commandPool must not be in the pending state (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkResetCommandPool-commandPool-00040)
[ERROR]: [Vulkan]: Validation Error: Validation Error: [ VUID-vkResetCommandPool-commandPool-00040 ] Object 0: handle = 0x5555572fbd00, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xb53e2331 | Attempt to reset command pool with VkCommandBuffer 0x5555572fbd00[] which is in use. The Vulkan spec states: All VkCommandBuffer objects allocated from commandPool must not be in the pending state (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkResetCommandPool-commandPool-00040)
[ERROR]: [Vulkan]: Validation Error: Validation Error: [ VUID-vkResetCommandPool-commandPool-00040 ] Object 0: handle = 0x555557139e40, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xb53e2331 | Attempt to reset command pool with VkCommandBuffer 0x555557139e40[] which is in use. The Vulkan spec states: All VkCommandBuffer objects allocated from commandPool must not be in the pending state (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkResetCommandPool-commandPool-00040)
[ERROR]: [Vulkan]: Validation Error: Validation Error: [ VUID-vkResetCommandPool-commandPool-00040 ] Object 0: handle = 0x55555713cd10, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xb53e2331 | Attempt to reset command pool with VkCommandBuffer 0x55555713cd10[] which is in use. The Vulkan spec states: All VkCommandBuffer objects allocated from commandPool must not be in the pending state (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkResetCommandPool-commandPool-00040)
[ERROR]: [Vulkan]: Validation Error: Validation Error: [ VUID-vkResetCommandPool-commandPool-00040 ] Object 0: handle = 0x5555571754b0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xb53e2331 | Attempt to reset command pool with VkCommandBuffer 0x5555571754b0[] which is in use. The Vulkan spec states: All VkCommandBuffer objects allocated from commandPool must not be in the pending state (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkResetCommandPool-commandPool-00040)
```

I'm hitting this issue in Granite and vkd3d currently. For a simple repro case with Granite:

```
git clone git://github.com/Themaister/Granite
cd Granite
git submodule update --init
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Debug
make -j$(nproc) triangle-test
GRANITE_VULKAN_FORCE_TIMELINE_SEMAPHORE=1 ./tests/triangle-test
```

With the env variable set to 0, the legacy fence path is used and I do not get any validation errors.

**Comment by jzulauf-lunarg** [comment]
Great repro case.  PR for fix @ https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1719

**Comment by HansKristian-Work** [comment]
Error is gone in Granite now and vkd3d as far as I can tell, thanks!

**Comment by jzulauf-lunarg** [comment]
@HansKristian-Work  -- a simple clear repro case is "a joy forever".

**Comment by rygo6** [comment]
So, I feel resurrecting this thread is appropriate as I believe I have run into the same exact bug EXCEPT it only pops up after calling vkGetSemaphoreWin32HandleKHR on an external timeline semaphore.

Did whatever conditions that got merged in to fix this also take into account it being an external timeline semaphore and its handle having been retrieved via vkGetSemaphoreWin32HandleKHR?
