### ISSUE TITLE
VkCommandBuffer not retaining it's object name after being recorded multiple times.

### ISSUE THREAD

**Issue by Didgy74** [KhronosGroup/Vulkan-ValidationLayers#1504]
This issue has been experienced on the SDK v1.1.130.0.

A `VkCommandBuffer` will lose it's object-name given to it through `vkSetDebugUtilsObjectNameEXT`
after recording to the command buffer 2 or more times. If you record to the command buffer only once, the object-name remains, record to it again and the name disappears.

The `VkCommandPool` owning the `VkCommandBuffer` was created with only the `VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT` flag enabled and no other options set.

The `VkCommandPool` was named using `vkSetDebugUtilsObjectNameEXT` before allocating the command buffer.

The `VkCommandBuffer` was created with only the `VK_COMMAND_BUFFER_LEVEL_PRIMARY` flag enabled and no other options set.

**Comment by mark-lunarg** [comment]
@Didgy74, modified `VkLayerTest.DebugUtilsNameTest` in `vklayertest_others.cpp` as indicated, but the naming appears to work as expected.  Might you have the time modify that test-case to reproduce the problem  (or provide a simple repro case) so we can get it fixed as quickly as possible?  Thanks!

**Comment by Didgy74** [comment]
I'm closing this issue. Turns out the behavior did not apply to the validation layers after some testing. It's the intended behavior of RenderDoc to forget the debug-utils name whenever you reset a command buffer.

**Comment by mark-lunarg** [comment]
Thanks @Didgy74 for following up, I was unaware of the RenderDoc behavior.
