### ISSUE TITLE
Timeline semaphores don't appear to support out-of-order submission

### ISSUE THREAD

**Issue by kspagnoli** [KhronosGroup/Vulkan-ValidationLayers#1514]
The validation layers don't appear to support out-of-order submission of timeline semaphores.

Looking at the layer source, it appears the payload signal value is instantly updated at submission time and the layers will warn if any future submit will signal a lower value. However, this is a _potentially_ a false warning if the first submit was blocked.

e.g.

submit #1 -- wait 10 signal 100 (blocked)
submit #2 -- wait 0 signal 10 (unblocks submit #1)

This usage pattern is legal and highlighted in a recent blog post: https://www.khronos.org/blog/vulkan-timeline-semaphores

Implementation wise the layer could possibly detect if the submit is blocked and ignore this warning. As an additional check, the layer could ask for the counter value in this via vkGetSemaphoreCounterValue to see if the current value is greater than the future signal which is illegal.

**Comment by jasuarez** [comment]
This should be covered by https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1622

**Comment by jasuarez** [comment]
@kspagnoli can you check if this is still a valid issue after #1622?
