### ISSUE TITLE
Extra image create flag added on swapchain images

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-ValidationLayers#1516]
In `ValidationStateTracker::PostCallRecordGetSwapchainImagesKHR`: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/e85fe4c3cc9f6c12d887d2ef912241241e0f5ffa/layers/state_tracker.cpp#L4901

and

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/e85fe4c3cc9f6c12d887d2ef912241241e0f5ffa/layers/state_tracker.cpp#L4919-L4924

There's `VK_IMAGE_CREATE_ALIAS_BIT` added implicitly to the image create flags on top of all the conditionals, but the vulkan spec says for swapchain images:

> `VK_IMAGE_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT` is set if `VK_SWAPCHAIN_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT_KHR` is set
>
> `VK_IMAGE_CREATE_PROTECTED_BIT` is set if `VK_SWAPCHAIN_CREATE_PROTECTED_BIT_KHR` is set
>
> `VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT` and `VK_IMAGE_CREATE_EXTENDED_USAGE_BIT_KHR` are both set if `VK_SWAPCHAIN_CREATE_MUTABLE_FORMAT_BIT_KHR` is set
>
> **all other bits are unset**.

This means that if using imageless framebuffers with the swapchain, it complains that `VK_IMAGE_CREATE_ALIAS_BIT` isn't set on the `VkFramebufferAttachmentImageInfoKHR.flags`.

**Comment by Tony-LunarG** [comment]
But can't you create images and bind swapchain image memory to them?  To me, that implies that the theoretical VkImageCreateInfo.flags _should_ contain VK_IMAGE_CREATE_ALIAS_BIT rather than forbid it from being set.  Isn't the functionality the same as with two non-swapchain images aliasing memory, and requiring VK_IMAGE_CREATE_ALIAS_BIT?

**Comment by baldurk** [comment]
I'm not aware of any way to do that, I thought the swapchain's memory was entirely opaque and unavailable to the application to do any aliasing with. Maybe I'm forgetting an extension somewhere, maybe one of the external memory ones?

**Comment by jeffbolznv** [comment]
The device group extension allows binding swapchain memory to images, so you can create peer mappings, for example. See VkBindImageMemorySwapchainInfoKHR.

**Comment by baldurk** [comment]
Ah right yeh I see. Annoyingly it doesn't look like we know at swapchain time whether that will be done or not (I don't see any pNext struct needed to be chained onto the swapchain) or else we could add that into the swapchain image equivalent table.

Either way, either the spec needs to be updated to say that `VK_IMAGE_CREATE_ALIAS_BIT` is always set for swapchain image equivalent info - which I don't think we can do as it's backwards compatibility breaking - or the layers need to treat the swapchain images as alias-able, but not require `VK_IMAGE_CREATE_ALIAS_BIT` for the imageless framebuffer image flags.

**Comment by Tony-LunarG** [comment]
Fixed in #1561
