### ISSUE TITLE
Duplicate header file entries in BUILD.gn

### ISSUE THREAD

**Issue by randomascii** [KhronosGroup/Vulkan-ValidationLayers#1526]
layers/state_tracker.h ends up being listed twice in a list of source files. This is ignored by gn but when VS project files are created it causes them to fail to load with this message:

Cannot load project with duplicated project items:
    ... vulkan-validation-layers/src/layers/state_tracker.h is included
    as 'None' and as 'None' item types.

PR being created.

**Comment by mikes-lunarg** [comment]
Fixed in #1528
