### ISSUE TITLE
Removal of non-API range enums from Vulkan headers

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-ValidationLayers#1532]
The Vulkan WG is looking at removing the BEGIN_RANGE, END_RANGE, and RANGE_SIZE enums from the Vulkan headers and XML going forward. These tokens have always been defined as not being part of the Vulkan API. As a first step, we'd like to be sure that the validation layers are not using these tokens.

Can you verify that the validation layers project has no objection to removing these tokens from the published XML/headers, or if there is a problem, undertake to remove all such usage? Thanks.

**Comment by mark-lunarg** [comment]
@oddhack, yes, they are used in the layers and we have a bit of work to do to remove them.

**Comment by oddhack** [comment]
Thanks for the quick turnaround!
