### ISSUE TITLE
Validate resource binding to external memory

### ISSUE THREAD

**Issue by jeffbolznv** [KhronosGroup/Vulkan-ValidationLayers#1533]
We got a bug report from a developer recently, where the app was binding an image to external memory without using VkExternalMemoryImageCreateInfo. This would have been caught by VUID-vkBindImageMemory-memory-02728. 

Please implement VUIDs 02726 through 02729 and 02791 through 02794. These are Bind{Buffer,Image}Memory(2) versions of this check for exportable and imported memory.

**Comment by mark-lunarg** [comment]
These were completed by @sfricke-samsung in commits 8a45d7399 and e9f3b5dad.

**Comment by sfricke-samsung** [comment]
also #1965 fixes this too
