### ISSUE TITLE
fase warning in vkUpdateDescriptorSets() call on some machines

### ISSUE THREAD

**Issue by thenegativehunter** [KhronosGroup/Vulkan-ValidationLayers#1548]
the specification states that :
**If sampler is used** and the VkFormat of the image is a multi-planar format, the image must have been created with VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT, and the aspectMask of the imageView must be VK_IMAGE_ASPECT_PLANE_0_BIT, VK_IMAGE_ASPECT_PLANE_1_BIT or (for three-plane formats only) VK_IMAGE_ASPECT_PLANE_2_BIT

in case of a immutable sampler which uses a multi planar image for sampling, sampler is not used(and also ignored if used) and VK_IMAGE_ASPECT_COLOR_BIT will be used with no plane specified.
although it doesn't prevent my software from running, the false warning will be generated as follows : 

"vkUpdateDescriptorSets() failed write update validation for VkDescriptorSet 0x5c000000005c[] with error: Write update to VkDescriptorSet VkDescriptorSet 0x5c000000005c[] allocated with VkDescriptorSetLayout VkDescriptorSetLayout 0x490000000049[] binding #1 failed with error message: image 50577534877742 combined image sampler is a multi-planar format and was not was not created with the VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT. The Vulkan spec states: If sampler is used and the VkFormat of the image is a multi-planar format, the image must have been created with VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT, and the aspectMask of the imageView must be VK_IMAGE_ASPECT_PLANE_0_BIT, VK_IMAGE_ASPECT_PLANE_1_BIT or (for three-plane formats only) VK_IMAGE_ASPECT_PLANE_2_BIT (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkDescriptorImageInfo-sampler-01564)"
or something like that with different numbers.

**Comment by mark-lunarg** [comment]
@thenegativehunter, the conditions in which you're getting this error are a bit cloudy to us here, can you get us a simple repro case, or maybe an API dump of a program running up to and including the error?  That'd help us to address this much more quickly -- thanks!

**Comment by thenegativehunter** [comment]
@mark-lunarg 
i was trying to implement a api dump, i changed my machine, and didn't get the error anymore. so i wouldn't be able to provide it without a lot of hassle.
but i realize where the problem is. i was using the latest vulkan sdk but setting the used api to 1.1 instead of 1.2
this time, i installed 1.1.130 on my machine instead and didn't get the error at all.
i searched in the source codes to realize the difference, in 1.1.130 the error code `VUID-VkDescriptorImageInfo-sampler-01564` has been defined but never referenced. but it is referenced in 1.2.131 and the master branch it is referenced.
so this probably not some deep bug rather a quick and incomplete definition of the api check. so probably by adding a sampler check to "CoreChecks::VerifyWriteUpdateContents" it can be resolved. i'm not very familiar with the code, but in the if statements you need to add a check where it makes sure the sampler argument is not VK_NULL_HANDLE (aka 0).

for further explanation, a ycbcr sampler should be used as a immutable sampler. so originally if the **sampler** argument is used, it the value will be ignored, but since the specification clearly states, if it is used it is against the spec or smth

**Comment by mark-lunarg** [comment]
@thenegativehunter, we pushed a commit (3ca937b323e7ec) which should take care of your issue, assuming we understood it correctly.  Please build and retry with your application and respond when you have the time.  Thanks!
