### ISSUE TITLE
pWaitDstStageMask should be checked against null pointer

### ISSUE THREAD

**Issue by tntljc** [KhronosGroup/Vulkan-ValidationLayers#1559]
App with pWaitDstStageMask set to null but using wait semaphore will crash in VkQueueSubmit with validation layer enabled, user will have no idea of the reason, either there is any message.

Looking at the code in the ValidateSemaphoresForSubmit() core_validation.cpp, it directly access pWaitDstStageMask's elements without any null-checking. I think it would be better if validation could report such error instead of crash.

**Comment by mark-lunarg** [comment]
@tntljc, there is existing validation for passing a null `pWaitDstStageMask `pointer.  Specifically, in `StatelessValidation::PerCallValidateQueueSubmit()`, in the `validate_flags_array()` call.  The following message is output if this parameter is NULL:

`[ VUID_Undefined ] Object: 0x23f823d4050 (Type = 3) | vkQueueSubmit: required parameter pSubmits[0].pWaitDstStageMask specified as NULL.`

I've added a test for this specific VUID, and the debug callback is called correctly before execution continues.  Thanks!

**Comment by tntljc** [comment]
Thanks @mark-lunarg ! My mistake that didn’t find this sentence. Close the issue.

**Comment by mark-lunarg** [comment]
@tntljc, no problem at all.  When you do inevitably run across something that's missing, let us know!
