### ISSUE TITLE
Implement VkSamplerCreateInfo-unnormalizedCoordinates-*

### ISSUE THREAD

**Issue by critsec** [KhronosGroup/Vulkan-ValidationLayers#156]
These VUIDs aren't implemented according to the database, and would have saved us a fair amount of time (and stress, due to deadlines) recently.

* If unnormalizedCoordinates is VK_TRUE, minFilter and magFilter must be equal
* If unnormalizedCoordinates is VK_TRUE, mipmapMode must be VK_SAMPLER_MIPMAP_MODE_NEAREST
* If unnormalizedCoordinates is VK_TRUE, minLod and maxLod must be zero
* If unnormalizedCoordinates is VK_TRUE, addressModeU and addressModeV must each be either VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE or VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER
* If unnormalizedCoordinates is VK_TRUE, anisotropyEnable must be VK_FALSE
* If unnormalizedCoordinates is VK_TRUE, compareEnable must be VK_FALSE

Since this looks really easy, I may try to use it as a Hello Validation Layers project for myself this weekend.

**Comment by daveh-lunarg** [comment]
Hi @critsec! As we plug away on improving validation layer coverage (or sometimes just trying to keep up as new validation language appears), it's really helpful when devs take the time to report their issues - it helps us prioritize where to focus next.

That said, the _only thing better_ than hearing "Here's an issue I found" is hearing "Here's an issue, and I think I can fix it." Thanks for jumping in!
