### ISSUE TITLE
Improve documentation in GitHub

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-ValidationLayers#1560]
Following internal discussion and reviewing repo, I believe we're deficient in documentation in the GitHub repo itself to give into on using the validation layers apart from the SDK and a basic background of the layer functionality.

If I put on my new user hat, I come to the main page in GitHub and then find ["How to Build and Run"](https://github.com/KhronosGroup/Vulkan-ValidationLayers#how-to-build-and-run) section in main readme.

When I click on that if I choose to bypass the [Vulkan Configurator Tool](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/LAYER_CONFIGURATION.md#vulkan-configurator-tool) then it immediately jumps into Activating layers on various platforms with no real info on what the validation layers are.

I'm thinking it would be nice to have a **Validation Layer Overview** section after Vulkan Configurator Tool and before the Activating Layers on Windows section. That section should explain that all Vulkan validation checks are unified into the single VK\_LAYER\_KHRONOS\_validation layer. It doesn't need to get into specifics, but can reference the [docs](https://github.com/KhronosGroup/Vulkan-ValidationLayers/tree/master/docs) dir for more info.

The other info that was brought to my attention and I'd like input on is potentially including a little historical background on the layers. This would primarily be for the benefit of people coming into Vulkan development who may be updating existing code with VK\_LAYER\_LUNARG\_standard\_validation and/or explicit individual layers. A few sentences could explain the history of those pieces and that they're now deprecated and all validation should be merged into the unified VK\_LAYER\_KHRONOS\_validation layer.

I was originally against this idea as it brings up deprecated items, but I do agree that it could be useful for devs dealing in older code who have no idea what's going on with those old layers.

**Comment by hevrard** [comment]
That sounds good, happy to help with drafting/reviewing some documentation on these points.

**Comment by mark-lunarg** [comment]
@hevrard, if you'd like to have a go, I think that'd be helpful to everyone in that an outside viewpoint is hard to come by.  We'll need to make sure any changes are applicable for both the repo and SDK, but that shouldn't be hard.

**Comment by hevrard** [comment]
OK, I'll try to get something ready next week.

**Comment by mark-lunarg** [comment]
@tobine, @hevrard, went ahead and created  #1607, please take a look and share edits/suggestions!
