### ISSUE TITLE
Imageless framebuffers and renderpass image layout transitions

### ISSUE THREAD

**Issue by billeter** [KhronosGroup/Vulkan-ValidationLayers#1563]
I'm using an imageless framebuffer (`VK_KHR_imageless_framebuffer`) to render to swap chain images (views bound when calling `vkCmdBeginRenderpass` via `VkRenderPassAttachmentBeginInfoKHR`). The associated render pass is set up to transition the corresponding color attachment from `VK_LAYOUT_UNDEFINED` to `VK_LAYOUT_PRESENT_SRC_KHR`. 

At present time, the validations layers are reporting an error about mismatching image layouts:
> [ VUID-VkPresentInfoKHR-pImageIndices-01296 ] Images passed to present must be in layout `VK_IMAGE_LAYOUT_PRESENT_SRC_KHR` or `VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR` but is in `VK_IMAGE_LAYOUT_UNDEFINED`. [...]

From briefly wading through the code, it seems that image layout transitions from render passes are not tracked for imageless framebuffers (e.g., `TransitionBeginRenderPassLayouts()` and related calls use `GetAttachmentImageViewState()` which returns a `nullptr` for imageless framebuffers).

**Comment by Tony-LunarG** [comment]
Fixed via #1594
