### ISSUE TITLE
Boundary checks for srcSubpass and dstSubpass

### ISSUE THREAD

**Issue by tuxerr** [KhronosGroup/Vulkan-ValidationLayers#1566]
One of my developers had mistakenly sent a VkRenderPassCreateInfo with 2 VkSubpassDependency where the 2nd dependency had uninitialized values for srcSubpass and dstSubpass, which was crashing his application in the vulkan driver (obviously). 

Unfortunately this also crashes the validation layers, as multiple places seem to use src/dstSubpass to index in subpass arrays, such as 
                self_dependencies[dependency.srcSubpass].push_back(i);
or 
                pCreateInfo->pSubpasses[dependency.srcSubpass].viewMask > 1

without checking that srcSubpass/dstSubpass are in [0, subpassCount[

**Comment by mark-lunarg** [comment]
Missing checks for these cases should be checked in stateless validation, and are:
```
• VUID-VkRenderPassCreateInfo-srcSubpass-02517
The srcSubpass member of each element of pDependencies must be less than subpassCount
• VUID-VkRenderPassCreateInfo-dstSubpass-02518
The dstSubpass member of each element of pDependencies must be less than subpassCount
```
