### ISSUE TITLE
No checks that vkCmdCopyQueryPoolResults is writing into a big enough buffer

### ISSUE THREAD

**Issue by tuxerr** [KhronosGroup/Vulkan-ValidationLayers#1567]
bool CoreChecks::PreCallValidateCmdCopyQueryPoolResults doesn't check that the buffer that the function writes to is big enough : the size should be at least as bit as dstOffset + queryCount*stride.

**Comment by mark-lunarg** [comment]
```
VUID-vkCmdCopyQueryPoolResults-dstOffset-00819
VUID-vkCmdCopyQueryPoolResults-firstQuery-00820
VUID-vkCmdCopyQueryPoolResults-firstQuery-00821
```

**Comment by tuxerr** [comment]
(it seems that to be complete, [[VUID-vkCmdCopyQueryPoolResults-dstBuffer-00824]] would also be necessary)

**Comment by jorgep31415** [comment]
@mark-lunarg  Similarly, to issue 1568 my pull request #2086 fully addressed this issue and so I think it can now be closed.

**Comment by mark-lunarg** [comment]
Thanks @jorgep31415, this is a big help!
