### ISSUE TITLE
Lack of renderpass compatibility testing in graphics pipelines

### ISSUE THREAD

**Issue by tuxerr** [KhronosGroup/Vulkan-ValidationLayers#1568]
We recently hit 2 issues, both having to do with the renderpass currently used ( after a vkCmdBeginRenderPass ) being incompatible with the renderpass in the graphics pipeline under the renderpass compatibility rules in https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#renderpass-compatibility. 

In the first case, the renderpass in use was using a fragment density map (vk_ext_fragment density map) and therefore had the FDM pNext and an FDM in the list of attachments. The graphics pipeline however didn't have either the pNext or the attachment. 

In the 2nd case, similarly, the renderpass in use was multiview (VkRenderPassMultiviewCreateInfo in the VkRenderPassCreateInfo pNext) but the graphics pipeline one wasn't (no pNext). 

Neither of those were caught by the validation layers.

**Comment by jorgep31415** [comment]
Unless the most recently mentioned pull request is somehow related which it doesn't seem like it is, my pull request #2080 fully addressed this issue and so I think this can now be closed.

**Comment by mark-lunarg** [comment]
Couldn't be happier.  Thanks.
