### ISSUE TITLE
Validate buffer sizes when recording drawcalls

### ISSUE THREAD

**Issue by DethRaid** [KhronosGroup/Vulkan-ValidationLayers#1570]
I've noticed that I've gotten `VK_ERROR_DEVICE_LOST` from when I try to record a drawcall where I've told Vulkan that either the index buffer or the vertex buffer is the wrong size. I don't exactly know how I misusing Vulkan because I changed a few things when fixing the error, but I'm 95% certain it's something related to buffer sizes or number of indices

**Comment by mark-lunarg** [comment]
@DethRaid, can you provide some additional detail?  Maybe some pseudo-code or repro circumstances, and maybe which valid usage checks are missing?  It'd help us get a good handle on things.

**Comment by DethRaid** [comment]
I can try to get a minimal repro case, but like I said I changed a few things while fixing the error so it may take a while to make

**Comment by mark-lunarg** [comment]
@DethRaid, this area has received a good bit of attention in the last 4-6 weeks.  To proceed we'd need either some VUIDs to target or a repro case we can use to get them. These checks should be straightforward to implement and we are more than willing to do the work, just need a bit more guidance...

**Comment by mark-lunarg** [comment]
These checks have been implemented as part of the security VUIDs effort.  Thanks!
