### ISSUE TITLE
Warn if pipeline with disabled rasterization has dynamic state

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-ValidationLayers#1571]
to #24
from https://github.com/KhronosGroup/Vulkan-Docs/issues/1184

Warn if pipeline with disabled rasterization has dynamic state that is appropriate only if rasterization is enabled.

Plus perhaps warn if it has a fragment shader.

Plus if it links extensions in `pNext` that depend solely on rasterization.

**Comment by mark-lunarg** [comment]
Thanks Petr, added this to the tracking issue!
