### ISSUE TITLE
Validate pipeline layout against maxPerStageDescriptorSamplers

### ISSUE THREAD

**Issue by scyganINTEL** [KhronosGroup/Vulkan-ValidationLayers#1575]
The purpose of this issue is to verify if layers check for number of samplers used per stage and validate that against the `maxPerStageDescriptorSamplers` limit advertised by the driver. 

I am not seeing `maxPerStageDescriptorSamplers` anywhere in layers code, so I guess it is not checked.

**Comment by mark-lunarg** [comment]
Perhaps you have an older version of the source?  There's [this section]([url](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/aeb43fc03baef19f1bb618c534bee0cf4182d897/layers/core_validation.cpp#L3978)) of **maxPerStageDescriptorSamplers**-related checks in core validation, and tests for them in `VkLayerTest.CreatePipelineLayoutExcessPerStageDescriptors` in `vklayertests_pipeline_shader.cpp`.  If you're still seeing errors get through or false positives with these checks active, then we'll add those missing checks to our Incomplete list.

**Comment by scyganINTEL** [comment]
@mark-lunarg Agree, thanks! 

I was looking for the error check  in VkDescriptorSetLayout create, while indeed it is catched in VkPipelineLayout creation - exactly where spec wants it. 

The bug is now closed.

**Comment by mark-lunarg** [comment]
@scyganINTEL -- thanks very much for your time!
