### ISSUE TITLE
Shader validation should pass correct Vulkan version to spvValidate()

### ISSUE THREAD

**Issue by daveh-lunarg** [KhronosGroup/Vulkan-ValidationLayers#158]
PreCallValidateCreateShaderModule() passes an SPV_ENV_VULKAN_1_0 environment to spvValidate() unconditionally.  This should be changed to match the actual Vulkan version.

SPIRV-Tools doesn't yet have support for checking shader capabilities using an SPV_ENV_VULKAN_1_1 environment, so all capabilities are considered allowed by default. Once issue https://github.com/KhronosGroup/SPIRV-Tools/issues/1597 is resolved, shader_validation can be updated to do the Right Thing.

**Comment by farnoy** [comment]
I believe this is related to #74 and #101

**Comment by daveh-lunarg** [comment]
The dependent issue in SPIRV-Tools was recently fixed, but pushing the layer fix immediately is as likely to cause as many problems for those not at the tip of that repo as would be solved. The combined fixes to validation layers and SPIRV-Tools will be put in before the next SDK drop.
