### ISSUE TITLE
Wrong VU for vkCmdExecuteCommands

### ISSUE THREAD

**Issue by martty** [KhronosGroup/Vulkan-ValidationLayers#159]
`Object: 0x1eedc5ce820 (Type = 6) | vkCmdExecuteCommands() cannot be called in a subpass using inline commands. The spec valid usage text states 'Each of fence, semaphore, and swapchain that are valid handles must have been created, allocated, or retrieved from the same VkInstance' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VUID-VkAcquireNextImageInfoKHR-commonparent)`

The error is good, but the VU seems unrelated.

**Comment by daveh-lunarg** [comment]
Yes, these are partially converted but there are still a few of the old enums hanging around. I'll take this.
