### ISSUE TITLE
Improve error messages for descriptor mis-matches

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#16]
**Issue by [tobine](https://github.com/tobine) (MIGRATED)**
_Tuesday Jan 24, 2017 at 23:36 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1404_

----

Received feedback that the error messages for incompatibility between descriptor layout and pipeline layout could be clearer. Need to make sure which components come from pipeline layout are clearly distinguished from the separate descriptor layout in the error message.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/punkUser"><img src="https://avatars2.githubusercontent.com/u/3095784?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [punkUser](https://github.com/punkUser) (MIGRATED)**
_Thursday Mar 23, 2017 at 16:57 GMT_

----

Just want to add that we definitely would like to see improvements to these descriptor type error messages as well. In particular, the ones that say things like:

Type mismatch on descriptor slot 0.1 (used as type `ptr to const uniform image(dim=5, sampled=2)`) but descriptor of type VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER

It would be super-useful to know what type of descriptor (enum) it is actually expecting here, as "ptr to const uniform image(dim=5, sampled=2))" is perhaps less useful than you would think :)

**Comment by karl-lunarg** [comment]
<a href="https://github.com/tobine"><img src="https://avatars0.githubusercontent.com/u/7526739?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tobine](https://github.com/tobine) (MIGRATED)**
_Friday Jul 07, 2017 at 15:54 GMT_

----

#1934 addresses my initial concern. I looked at the follow-on request from @punkUser which is a bit trickier. @chrisforbes can you take a look? One possibility I was looking at was to refactor descriptor_type_match() in shader_validation.cpp to use a utility function that would return a vector of acceptable VkDescriptorType values to compare descriptor_type against. The utility function could then also be used to print the acceptable VkDescriptorTypes in the error message. This was a bit messy, though, and I wanted to see if you had a better idea.

**Comment by tobine** [comment]
This is done including the follow-on request.
