### ISSUE TITLE
Remove clang compiler warnings when building

### ISSUE THREAD

**Issue by sfricke-samsung** [KhronosGroup/Vulkan-ValidationLayers#1608]
I have had it a few times now where I get a build error/warning that is important but it was suppressed in the noise of warnings I get currently

I normally build with clang 6, but checked a gcc 7 build and see that doesn't spit warnings so these seems to be clang warnings

Basically to sum up all the warnings:

Unused functions clang can't resolve
```
vk_extension_helper.h:53:13: warning: unused function 'IsExtEnabled' [-Wunused-function]

state_tracker.h:222:68: warning: unused function 'GetDslFromPipelineLayout' [-Wunused-function]

core_validation_types.h:522:13: warning: unused function 'ImageLayoutMatches' [-Wunused-function]
```

unused const variables clang can't resolve
```
parameter_validation.cpp:47:28: warning: unused variable 'AllVkFormatFeatureFlagBits' [-Wunused-const-variable]
```

Not sure why `noexcept` is causing this
```
vktestbinding.cpp:242:9: warning: function previously declared with an explicit exception specification redeclared with an implicit exception
      specification [-Wimplicit-exception-spec-mismatch]
Device::~Device() {
        ^
vktestbinding.h:195:5: note: previous declaration is here
    ~Device() NOEXCEPT;
     ^
```

My main question is what of the 3 possible options would we want to take:
- set `-Wno-unused-function -Wno-unused-const-variable -Wno-implicit-exception-spec-mismatch` in cmake
- add pragamas for clang to ignore these
- acknowledge this is just how it is and that if you are building for clang it is in your best interest to set those `-Wno` manually

**Comment by mark-lunarg** [comment]
Heh.  Just learned a few minutes ago that there are a slew of warnings on Ubuntu 19.04 (GCC 8.3?) also.  We'll get these cleared up, and thanks for the notice.

**Comment by null77** [comment]
Mark: is there any interest in making the VVL use warnings-as-error? The potential benefits are there. You can end up catching real errors and code inefficiencies.

FYI I'm looking at fixing a couple warnings-as-errors that popped up in the roller into ANGLE.

**Comment by mark-lunarg** [comment]
@null77, the specified compiler is GCC, but we do 'support' clang.  It's in our Github CI builds, but we  have not turned on warning-as-errors for this compiler.  Warnings there (especially the number we have now!) are a real impediment to productivity, so I'll see what the temperature is in the group for extending W-A-E to clang.

**Comment by null77** [comment]
OK. FWIW Chrome sees probably hundreds of commits a day and enjoys a very high level of productivity despite warnings-as-errors. They can have benefits to productivity too. The compiler could catch a bug that a developer otherwise might spend time debugging.

**Comment by mark-lunarg** [comment]
@null77, yeah, I'd prefer it this way as well, but there's only a very small proportion of VVL developers using Clang, so it's always a surprise.  Makes compete sense to me, and I'll see what I can do.
