### ISSUE TITLE
CI needs to be updated for new Vulkan-Loaders build

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-ValidationLayers#162]
Recent change to Vulkan-Loaders build process has broken the Validation Layer CI.
The configs need to be updated to support the Loader build w/o Vulkan-Headers as a submodule.
See CI output for [PR160](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/160) for an example of current error.

**Comment by karl-lunarg** [comment]
I've just pushed branch `karl-gh161` to fix this.

How is this different from issue #161 ?

**Comment by tobine** [comment]
#161 is for a permanent solution to prevent breaks like this from ever happening again.

**Comment by karl-lunarg** [comment]
Okay, I'll re-word #161 a bit to remove confusing references to unrelated issues.  I have some questions, so I hope you'll answer there.

**Comment by karl-lunarg** [comment]
Fixed via #163
