### ISSUE TITLE
Change all variable names that are "requires"

### ISSUE THREAD

**Issue by DadSchoorse** [KhronosGroup/Vulkan-ValidationLayers#1634]
`requires` is a keyword in c++20, but it gets used as a variable name, for example here:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/c46b6f74a8d5ef2c3a3b7af32d64c1aae52b223e/layers/generated/vk_extension_helper.h#L109
I'm using that file in my project, so I would be thankful if it could get changed.

**Comment by mark-lunarg** [comment]
Pushed fix to Master.
