### ISSUE TITLE
CoreChecks::ValidateImageFormatFeatureFlags and general format feature support

### ISSUE THREAD

**Issue by sfricke-samsung** [KhronosGroup/Vulkan-ValidationLayers#1636]
Example of current use of `ValidateImageFormatFeatureFlags`

```
skip |= ValidateImageFormatFeatureFlags(dst_image_state, VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT, "vkCmdResolveImage()",
                                                "VUID-vkCmdResolveImage-dstImage-02003", "VUID-vkCmdResolveImage-dstImage-02003");
```

`VUID-vkCmdResolveImage-dstImage-02003` is
> The format features of dstImage must contain VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT.

----

I realized while working on other VUID related to format features that `CoreChecks::ValidateImageFormatFeatureFlags` is only checking for Linear and Optimal formats. I then realize there is just a general lack of greater format feature checking in the VVL.

The tiling could be `VK_IMAGE_TILING_DRM_FORMAT_MODIFIER_EXT` or if its an external image it would need to check `VkAndroidHardwareBufferFormatPropertiesANDROID::formatFeatures` instead of anything

----

So a few things I am proposing (happy to do some as I am running into this anyway, just want to get 2nd opinion before I do any work)

- All cases of `ValidateImageFormatFeatureFlags` have the same linear and optimal VUID so I would first get rid of passing it in twice
- I would just save the `VkFormatFeatureFlags` for an image in the `IMAGE_STATE` so various other places can just grab it there (ex `ValidateImageFormatFeatureFlags`)
- I would also save the `VkFormatFeatureFlags` for an image in the `IMAGE_VIEW_STATE` so VUID such as `VUID-vkCmdDraw-None-02690` that need the "Image View's format feature " can grab it as well

----

The external image is a nasty twist, basically if `VkImageCreateInfo::format` is `VK_FORMAT_UNDEFINED` then you don't query from the type of tiling, but the `VkAndroidHardwareBufferFormatPropertiesANDROID::formatFeatures` found by calling `vkGetAndroidHardwareBufferPropertiesANDROID` on the Android hardware buffer that was imported to the `VkDeviceMemory` to which the image is bound.

**Comment by mark-lunarg** [comment]
@sfricke-samsung, this all sounds great...  I put your name on it -- thanks!
