### ISSUE TITLE
VK_LAYER_KHRONOS_validation VK_KHR_ray_tracing Segfault

### ISSUE THREAD

**Issue by x3DCoder** [KhronosGroup/Vulkan-ValidationLayers#1647]
tags/v1.2.135
VK_LAYER_KHRONOS_validation
VK_KHR_ray_tracing
This bug is very simple to explain and reproduce. 
Segfault on vkCmdBuildAccelerationStructureKHR when building multiple bottom level acceleration structures in one build command. 
With VK_LAYER_KHRONOS_validation Off, everything works perfectly. 
Splitting builds in multiple commands also solves it.

**Comment by x3DCoder** [comment]
Repro app (not minimal app, but minimal scene) : 
https://drive.google.com/open?id=11GLwMV24ru586YJiNVqt8fIJMCU_3Jnc

./incubator (linux build with the reproducible segfault)
incubator.exe (windows build, unsure if the issue also happens on windows since I didn't install the new validation layers on my windows machine yet). 

Also, Here's a piece of code that I was testing with to confirm that the issue was only happening when building multiple blas in the same cmd.

```
// Individual calls (always works, but commented out in current repro app)
for (int i = 0; i < geomInfos.size(); ++i) 
	device->CmdBuildAccelerationStructureKHR(commandBuffer, 1, &geomInfos[i], &offsetInfos[i]);

// Multiple builds in the same cmd (current repro app, only works with validation layers off, otherwise segfault)
device->CmdBuildAccelerationStructureKHR(commandBuffer, geomInfos.size(), geomInfos.data(), offsetInfos.data());
```
geomInfos is a std::vector<VkAccelerationStructureBuildGeometryInfoKHR>
offsetInfos is a std::vector<VkAccelerationStructureBuildOffsetInfoKHR*>

My ppGeometries for each VkAccelerationStructureBuildGeometryInfoKHR is a pointer to an array containing exactly one geometry information, and geometryCount = 1

Also, validation layers are not complaining of anything when building individual blas, and I no complaints from address sanitizer either.

**Comment by jeffbolznv** [comment]
I have a repro and see the problem. safe_VkDeviceOrHostAddressKHR is a struct instead of a union, so safe_VkAccelerationStructureBuildGeometryInfoKHR is the wrong size. I'll see if I can fix the scripts to use a union here.
