### ISSUE TITLE
Handle validation of secondary command buffers with their own renderpass information

### ISSUE THREAD

**Issue by MarkY-LunarG** [KhronosGroup/Vulkan-ValidationLayers#165]
This is to keep the items brought up in the previous repo discussion https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/516/#discussion_r63013756.

It likely requires both spec and layer updates.

Content follows in case that ever goes away:

![old_pr516_discuss](https://user-images.githubusercontent.com/16328578/40945586-be1fe1be-6816-11e8-9cf7-2e2efc19e550.png)

**Comment by tobine** [comment]
It appears that spec and validation have both been updated for this.
