### ISSUE TITLE
Setting `VkApplicationInfo::apiVersion` to random values has no effect

### ISSUE THREAD

**Issue by dictoon** [KhronosGroup/Vulkan-ValidationLayers#1665]
The following code does not produce any error or validation error:

    VkApplicationInfo app_info = {};
    app_info.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO;
    app_info.pApplicationName = "ApplicationName";
    app_info.applicationVersion = VK_MAKE_VERSION(1, 0, 0);
    app_info.pEngineName = "EngineName";
    app_info.engineVersion = VK_MAKE_VERSION(1, 0, 0);
    app_info.apiVersion = VK_MAKE_VERSION(42, 72, 0);  // <-- some ways in the future

    VkInstanceCreateInfo create_info = {};
    create_info.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
    create_info.pApplicationInfo = &app_info;
    ...
    if (vkCreateInstance(&create_info, nullptr, &m_instance) != VK_SUCCESS)
        throw std::runtime_error("Failed to create Vulkan instance");

Is it to be expected?

I'm using LunarG's Vulkan SDK version 1.2.131.2 on Windows 10 and an NVIDIA GeForce RTX 2080 Ti with game ready drivers 445.75 (the latest at the time of writing).

I'm currently using the `VK_LAYER_LUNARG_standard_validation` validation layer.

**Comment by mark-lunarg** [comment]
@dictoon, can you point us to the valid usage statements  in the specification that you'd expect to see called out?  I did see this:

`Vulkan 1.0 implementations were required to return VK_ERROR_INCOMPATIBLE_DRIVER if apiVersion was larger than 1.0.`

But for other versions, it looks like anything might be valid.

**Comment by dictoon** [comment]
The spec doesn't mention anything about it. It was simply suggested by someone on the KhronosDevs Slack that "I would hope validation would have at least a sanity check there.  Maybe file a validation bug?", so I did.

It would seem helpful for the validation layers to check that an app isn't passing random version values but as you pointed out, according to the spec it appears to be legal.

**Comment by mark-lunarg** [comment]
The validation layers, by default, can and should only enforce the spec.  However, it 's a good idea, and I've added this to the best-practices layer tracking issue #24, which is a great place for stuff like this.  Thanks for the suggestion!

**Comment by dictoon** [comment]
Thank you!
