### ISSUE TITLE
VUID-VkImageCreateInfo-samples-02257 doesn't check for DRM_FORMAT_MOD_LINEAR

### ISSUE THREAD

**Issue by sfricke-samsung** [KhronosGroup/Vulkan-ValidationLayers#1670]
`VUID-VkImageCreateInfo-samples-02257` checks only `pCreateInfo->tiling != VK_IMAGE_TILING_OPTIMAL` but according to the spec

> If tiling is VK_IMAGE_TILING_DRM_FORMAT_MODIFIER_EXT, then imageCreateMaybeLinear_ is true if and only if imageCreateDrmFormatModifiers contains DRM_FORMAT_MOD_LINEAR.

so there should be a test where `VK_EXT_image_drm_format_modifier` is on and there is no `DRM_FORMAT_MOD_LINEAR` and the tiling set to `OPTIMAL` and try to trip VUID 02257

----

While a bug, the plumbing in #1636 should hopefully be able to fix this, but making note know incase someone runs into bug as well

**Comment by mark-lunarg** [comment]
Looks like this VUID check is unchanged.  Perhaps there should be an ImageCreateMaybeLinear() function that we could use for those half-dozen spots.  Shall I assign this one to you Spencer?

**Comment by sfricke-samsung** [comment]
Yes I forgot about this... happy to fix it up, only issue is no way to test it as I can't find any implementation with DRM_FORMAT support... if that isn't a huge issue it should be a trivial fix in layer but idk how to test it... your call

**Comment by mark-lunarg** [comment]
Seems like we could set the DRM bit in the ImageTiling of an ImageCreateInfo structure, call CreateImage, and catch it that way?  Might be a mess of other unexpecteds but it could work...

**Comment by mark-lunarg** [comment]
Or I might have my bits backwards.  Anyhow.

**Comment by sfricke-samsung** [comment]
ok, re-looking at the spec, I see this something that is passed in `VkImageDrmFormatModifierListCreateInfoEXT` so you can write a test as you said... I don't mind doing it, but more pressing issues I rather take care of first, also hate not being able to test it and just blindly think it should work

**Comment by mark-lunarg** [comment]
Taking care of this one AWA 02259.
