### ISSUE TITLE
Review of ErrorMonitor constructor in tests

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-ValidationLayers#1674]
I am not sure why ErrorMonitor constructor locks and unlocks its mutex in its constructor. Does not make sense to me. Who else would use the object if it is not even constructed yet?

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/dbd073615280f0b737e96017c355ca75835abc1e/tests/vkrenderframework.cpp#L29-L34

On the other hand the `ErrorMonitor::Reset()` method does not have locking, while technically a modifying function.

Not sure generally what the locking is useful for. Most (all?) of the tests are single-threaded.

**Comment by mark-lunarg** [comment]
As I understand it, this is completely unnecessary.
