### ISSUE TITLE
Creating multiple instances without destroy in between crashes tests

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-ValidationLayers#1677]
This code (PR #1676 for demonstration purposes) crashes:

```
TEST_F(VkPositiveLayerTest, TwoInstances) {
    TEST_DESCRIPTION("Create two instances before destroy");

    ASSERT_NO_FATAL_FAILURE(InitFramework(m_errorMonitor));

    VkInstance i1, i2, i3;

    VkInstanceCreateInfo ici = {};
    ici.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
    ici.enabledLayerCount = m_instance_layer_names.size();
    ici.ppEnabledLayerNames = m_instance_layer_names.data();

    vk::CreateInstance(&ici, nullptr, &i1);

    vk::CreateInstance(&ici, nullptr, &i2);
    vk::DestroyInstance(i2, nullptr);

    vk::CreateInstance(&ici, nullptr, &i3);
    vk::DestroyInstance(i3, nullptr);  // crash

    vk::DestroyInstance(i1, nullptr);
}
```

The conditions are MockICD, and two layers: Validation + Device Profile (default of the test framework).

**Comment by mark-lunarg** [comment]
@krOoze, this is due to a bug in the mock ICD.  It creates a single physical device handle, passes it back to everybody, always, but destroys it on the first DestroyInstance() call, ruining the party for everyone.  I think I can just make a static handle, and not delete it, then we're all cool (the test passed when I skipped the PDev delete in the debugger).  DevSim is uninvolved.

**Comment by krOoze** [comment]
Hm, though it worked for me if Device Profile layer was not among the enabled layers...

**Comment by mark-lunarg** [comment]
Ah, yeah, I'm always getting device_simulation and device_profile mixed up.  The DeviceProfile layer **is** loaded in my debugging scenario -- it is responsible for some of the EnumeratePhysicalDevices calls, so maybe those mask the problem?  Either way, I'll do some more digging and get it sorted.

**Comment by mark-lunarg** [comment]
Without the MockICD fix, it failed for me with or without DevProf.  With the fix, it passes either way.  Here's the [PR on Vulkan-Tools](https://github.com/KhronosGroup/Vulkan-Tools/pull/365).

**Comment by krOoze** [comment]
This particular case seems to work now. There is similar problem in `VkPositiveLayerTest.SwapchainImageLayout` though.

**Comment by mark-lunarg** [comment]
This was pushed to Master -- thanks Petr!
