### ISSUE TITLE
Debug enabled by env does not validate vkCreateInstance

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-ValidationLayers#1678]
I have tested debug enabled by env (`VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation`). It does not seem to catch `vkCreateInstance` errors. My code:

```
#include <vulkan/vulkan.h>

int main(){
	VkInstance i1, i2, i3;

	// Test known good validation
	const VkInstanceCreateInfo ici = {VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO};
	vkCreateInstance(&ici, nullptr, &i1);
	uint32_t pdc = 1;
	VkPhysicalDevice pd;
	vkEnumeratePhysicalDevices(i1, &pdc, &pd);
	vkGetPhysicalDeviceProperties(pd, nullptr); // works as it should

	// Test known good instance validation -- bad sType
	const VkInstanceCreateInfo bad_ici = {VK_STRUCTURE_TYPE_APPLICATION_INFO};
	vkCreateInstance(&bad_ici, nullptr, &i2); // no diagnostic

	// Test nullptr return instance
	vkCreateInstance(&ici, nullptr, nullptr); // crashes with no diagnostic

	// Test nullptr create info
	vkCreateInstance(nullptr, nullptr, &i3); // crashes with no diagnostic
}
```

I know the second case should work, because I tested it in #810 with explicit validation.

**Comment by mark-lunarg** [comment]
Hey @krOoze, I just tried this, and I seem to be hitting the correct LogError messages for these failures (using a real driver, anyway).  Is this just with MockICD, or has this been covered somehow?

**Comment by krOoze** [comment]
@mark-lunarg I still have the same result. Either mock or NV on Windows.

```
VK_ICD_FILENAMES=C:\Dev\_GitHub\Vulkan-Tools\build\icd\Debug\VkICD_mock_icd.json
VK_LAYER_PATH=C:\Dev\_GitHub\Vulkan-ValidationLayers\build\layers\Debug
VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation
```

Loader 1.1.126 from NV driver.

`vkCreateInstance(&bad_ici, nullptr, &i2);` exits with 0, and issues no error

This one is tested with VkLayerTest.InstanceBadStype, so should otherwisely work.

**Comment by mark-lunarg** [comment]
I had created a new app for your code fragment, did you test this inside the test framework?  Just remove loading of the layers from the framework and use the env var?

**Comment by krOoze** [comment]
No, I have created new app as well. The above code is verbatim plus-minus commenting the cases as necessary (i.e, commenting the first case, which is just a control).

**Comment by mark-lunarg** [comment]
Just tried this again in the layertests.  Commented out loading Khronos validation and devsim, added KHRONOS to VK_INSTANCE_LAYERS, set mockicd and layer path, `InstanceBadStype ` worked fine.

**Comment by krOoze** [comment]
I still get nothing. Even with master head loader and layers.

**Comment by mark-lunarg** [comment]
@krOoze, I modified the vk_layer_validation_tests to do this and it seemed to work just fine, did you use a standalone app?  If so, can you share it?

**Comment by krOoze** [comment]
@mark-lunarg Yes, standalone app. It is in the OP. The `vkGetPhysicalDeviceProperties` validation works, so I know the setup should be correct. The rest of the cases issue no error. The bad `sType` is even tested, so definitely should be working, but doesn't.

**Comment by mark-lunarg** [comment]
It seems to make no difference if the layers are loaded through the environment variable or programmatically.  The issue here is that a default callback isn't installed (by the layer) until the instance is created.  Your app could create a temp messenger through the pNext chain and that'll work fine, but I think we really need to install a default one if none has been passed in.  It only needs to be active until the real ones are installed after the instance is created.  Good catch!

**Comment by mark-lunarg** [comment]
@krOoze, pushed a fix that should take care of this.  Default callbacks are now set up *before* the chassis makes the `PreCallValidate `calls.  Note that this only applies to situations where the application has not installed any default callbacks.  Thanks!

**Comment by krOoze** [comment]
Yup, that seems to do the trick.
