### ISSUE TITLE
Build script update_deps.py not building for Win32 correctly

### ISSUE THREAD

**Issue by samwalls-arm** [KhronosGroup/Vulkan-ValidationLayers#1681]
Also see the discussion towards the end of [this PR](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1621).

The instructions which I found from `BUILD.md` didn't quite work on my windows machine for some reason.

e.g.
```
mkdir build
cd build
../scripts/update_deps.py --arch Win32
cmake -A Win32 -C helper.cmake ..
cmake --build .
```
or
```
scripts/update_deps.py --arch Win32 --dir external --config Debug
mkdir build
cd build
cmake -A Win32 -C ../helper.cmake ..
cmake --build .
```

Kept giving me errors regarding glslang dependencies:
```
SPIRV-Tools-optd.lib(optimizer.obj) : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86' [C:\Users\sam\w\Vulkan-ValidationLayers\build\layers\VkLayer_khronos_validation.vcxproj]
```

After working with it a bit, I found that I had to go into the glslang project created by `update_deps.py`, and re-build the 32-bit target manually with `-A Win32`. This is with Visual Studio 2019 Professional installed, cmake 3.17.0-rc3, and python 3.7.3.

Is this expected behaviour? If so, `BUILD.md` might not reflect it.

**Comment by mark-lunarg** [comment]
@samwalls-arm, is the note above sufficient?  If you feel more is needed, please feel free to add onto the PR.  Thanks!

**Comment by samwalls-arm** [comment]
It might not be. I tried again with a completely fresh clone of the repository, just in case, and the commands I wrote here still produce the error.

**Comment by mark-lunarg** [comment]
@samwalls-arm, thanks for checking, I will either fix it or change the blurb!

**Comment by mark-lunarg** [comment]
Updates (and fixes) pushed to Master.  Thanks for the nudge!
