### ISSUE TITLE
Feature request: silent mode

### ISSUE THREAD

**Issue by 741g** [KhronosGroup/Vulkan-ValidationLayers#1691]
Hi,

I'm on Android GPU virtualization efforts at Google and we're interested in using VVL to prevent undefined/invalid behavior triggered from a Vulkan guest. In the course of this, one feature that we'd be interested in is 'silent mode'; i.e., when the layers are linked in, they do validation and return error codes and don't exercise the host driver on validation failure (like they do now), except that the printouts are skipped.

What do you think?

Frank

**Comment by mark-lunarg** [comment]
@741g, you can create a debug callback and eat the messages, they'll never show up.  I'm guessing this won't work for you?

**Comment by 741g** [comment]
@mark-lunarg ah that's right, I can do that instead! Would there be any extra noticeable overhead from having trivial debug callbacks? If not, feel free to close.

**Comment by mark-lunarg** [comment]
I would really like to understand your use case a bit better -- but if you create a debug callback, the layers will use yours instead of setting up their own default callbacks, so there _shouldn't_ be any noticeable overhead.

**Comment by 741g** [comment]
The use case: security. this would be for using attached validation layers as a way to prevent malformed Vulkan structs/API calls from causing undefined behavior on the host. Each instance/device created by the guest would have the validation layers added on top. As such, we'd want validation to happen, but would also want a minimal amount of overhead (for performance).

**Comment by mark-lunarg** [comment]
Ah, that helps.  For this use case, you may wish to disable the thread-safety checks and possibly even the unique_handles portions of the default validation types.  This should speed things up a good bit if it becomes necessary.  In your use-case, the callback shouldn't affect things at all.  Lemme know if you want/need any additional info, glad to help.

**Comment by 741g** [comment]
Thanks Mark! Will re-open once I run into issues needing additional help :)

It's possible we do unique_handles already due to stuff that is required as part of virtualization (keeping guest/host handles in separate spaces), though we might want to keep the thread safety checks, and that might be something that is more uhh interesting to make superfast :)
