### ISSUE TITLE
Names for objects in validation layer, take 2

### ISSUE THREAD

**Issue by Jasper-Bekkers** [KhronosGroup/Vulkan-ValidationLayers#1695]
I've file this issue way back in 2017 in the other repository (https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1880) but it looks like this still isn't addressed?

It looks like this may have gotten stuck on https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/2475 but it's a real shame, having to jump through hoops for years to get names on objects.

> "Validation Error: [ VUID-VkWriteDescriptorSet-descriptorType-00331 ] Object 0: handle = 0x767e510000000789, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0xde8c9ed7 | vkUpdateDescriptorSets() failed write update validation for VkDescriptorSet 0x767e510000000789[] with error: Write update to VkDescriptorSet VkDescriptorSet 0x767e510000000789[] allocated with VkDescriptorSetLayout VkDescriptorSetLayout 0x8c7a9600000000f3[] binding #1 failed with error message: Attempted write update to buffer descriptor failed due to: Buffer (51B3510000000014) with usage mask 0x13 being used for a descriptor update of type VK_DESCRIPTOR_TYPE_STORAGE_BUFFER does not have VK_BUFFER_USAGE_STORAGE_BUFFER_BIT set.. The Vulkan spec states: If descriptorType is VK_DESCRIPTOR_TYPE_STORAGE_BUFFER or VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC, the buffer member of each element of pBufferInfo must have been created with VK_BUFFER_USAGE_STORAGE_BUFFER_BIT set (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkWriteDescriptorSet-descriptorType-00331)" 

I've named the buffer appropriately though the debug_utils extension yet it still shows up as some hex number here.

@mark-lunarg

**Comment by mark-lunarg** [comment]
@Jasper-Bekkers, the infrastructure for this has been in place for some time and a scrub was made a few weeks ago to pick up most of the multi-object output cases, but a whole bunch of messages in `descriptor_sets.cpp` were missed.  I fixed all I could find there (in #1704), if you run across any other spots let us know and they'll be addressed quickly.
