### ISSUE TITLE
Unjustified VUID-vkAcquireNextImageKHR-swapchain-01802 (Application has already previously acquired X images from swapchain)

### ISSUE THREAD

**Issue by cjay** [KhronosGroup/Vulkan-ValidationLayers#1696]
The following kind of validation error can occur unjustified:

> VUID-vkAcquireNextImageKHR-swapchain-01802(ERROR / SPEC): msgNum: 1050126472 - Validation Error: [ VUID-vkAcquireNextImageKHR-swapchain-01802 ] Object 0: h
andle = 0x2a000000002a, type = VK_OBJECT_TYPE_SWAPCHAIN_KHR; | MessageID = 0x3e97a888 | **vkAcquireNextImageKHR: Application has already previously acquired
2 images from swapchain. Only 2 are available to be acquired using a timeout of UINT64_MAX** (given the swapchain has 3, and VkSurfaceCapabilitiesKHR::minIma
geCount is 2). The Vulkan spec states: If the number of currently acquired images is greater than the difference between the number of images in swapchain
and the value of VkSurfaceCapabilitiesKHR::minImageCount as returned by a call to vkGetPhysicalDeviceSurfaceCapabilities2KHR with the surface used to creat
e swapchain, timeout must not be UINT64_MAX (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-swapc
hain-01802)

This can happen in the following situation: Assume the maximum "allowed" swapchain images had already been acquired (length of swapchain - VkSurfaceCapabilitiesKHR::minImageCount + 1) before a call to `vkQueuePresentKHR` that had an unsuccessful return code, usually being `VK_ERROR_OUT_OF_DATE_KHR`. Now, calling `vkAcquireNextImageKHR` will cause the validation error despite respecting the limits.

The reason is combination of two things.
`ValidationStateTracker::PostCallRecordQueuePresentKHR` checks the return code of the actual `vkQueuePresentKHR` and skips over the remaining state updates, which would have marked one of the swapchain images as not acquired:
```
if (local_result != VK_SUCCESS && local_result != VK_SUBOPTIMAL_KHR) continue;
...
image_state->acquired = false;
```

`CoreChecks::ValidateAcquireNextImage` then counts all swapchain images that have `acquired == true`, without checking beforehand if the swapchain is out of date.

**Comment by krOoze** [comment]
It sounds like an Issue for Vulkan-Docs. The VU says nothing about caring whether swapchain is out of date or not.

**Comment by cjay** [comment]
No, the issue is that the validation complains about legitimate API use. A call to `vkQueuePresentKHR` followed by a call to `vkAcquireNextImageKHR` should never result in a validation error that complains about trying to acquire too many swapchain images.
I mentioned out of date swapchain only as part of the example situation where this happens.

**Comment by krOoze** [comment]
Ok, give me an example that does not violate:

> The Vulkan spec states: If the number of currently acquired images is greater than the difference between the number of images in swapchain
and the value of VkSurfaceCapabilitiesKHR::minImageCount as returned by a call to vkGetPhysicalDeviceSurfaceCapabilities2KHR with the surface used to creat
e swapchain, timeout must not be UINT64_MAX

yet shows the error.

**Comment by cjay** [comment]
> give me an example without VK_ERROR

Why do you want that? A `VK_ERROR_OUT_OF_DATE_KHR` is part of normal operation. Sure, it's suboptimal to call `vkAcquireNextImageKHR` after `vkQueuePresentKHR` returned an error, but it's not disallowed, is it? And if it is, the validation layer should complain about that instead.

Personally, I triggered the issue because I had `vkQueuePresentKHR` in a different thread (using a mutex for swapchain access of cause), and decided to check for `VK_ERROR_OUT_OF_DATE_KHR` in only one of the calls for now, to avoid having to signal the return code to the other thread. The validation error definitely caused me some confusion.

**Comment by krOoze** [comment]
I want it, because you said the problem does not rely on out-of-date.

Traditionally an VK_ERROR means the command is unwinded, so the image is still acquired.

It could be argued out-of-date will just fail any subsequent command on the swapchain, so the validation error is pointless, but the spec says nothing about that.

The spec also says that for specific errors the semaphore gets polluted, but nothing about how it changes the acquireness.

I would say it does not, because it says the presentation is "rejected" .

Either way if the spec makes a guy overthink or argue about its interpretation, then that is an issue of the specification.

**Comment by cjay** [comment]
I agree that the spec is lacking when it comes to acquiredness.

I have only observed the issue with `VK_ERROR_OUT_OF_DATE_KHR`, but I'm pretty sure any non-success return code is sufficient. So yes, some error is needed. Any non-success return code causes the update to the `acquired` flag to be skipped: `if (local_result != VK_SUCCESS && local_result != VK_SUBOPTIMAL_KHR) continue;`. I see 6 possible non-success return codes for `vkQueuePresentKHR` in the spec. Though I'm not entirely sure if the circumstances that are necessary to cause each of these codes allow the counting code in `CoreChecks::ValidateAcquireNextImage` to be reached, my understanding of how the validation code is structured is very limited.

**Comment by krOoze** [comment]
> I have only observed the issue with `VK_ERROR_OUT_OF_DATE_KHR`, but I'm pretty sure any non-success return code is sufficient. So yes, some error is needed. 

Right. Well, for `OUT_OF_MEMORY` the spec outright says it shouldn't change anything. So we are definitely at least correct there.

As for the others, we should not really invent in layers what drivers should and shouldn't behave like. That is what the spec is for. Seeing that you are reluctant to do so, I made an Issue for you: https://github.com/KhronosGroup/Vulkan-Docs/issues/1242.

**Comment by cjay** [comment]
Thanks. Apologies if I was unhelpful. I misunderstood you when you wrote "It sounds like an Issue for Vulkan-Docs.". I interpreted that as "only the docs need a change", but it has become clear that such a change would then probably be reflected in the validation code.

**Comment by krOoze** [comment]
Nah, keep up the good work. Exposing spec bugs is extremely important. Spec is the only contract you have with the driver, so do not hesitate to report things of this sort there.

> I interpreted that as "only the docs need a change", but it has become clear that such a change would then probably be reflected in the validation code.

Well, depends on what change they make. Might be that your usage would be considered invalid after all. Of course, the layers will always reflect what the spec says.
