### ISSUE TITLE
Deprecated extension warning for future Vulkan version

### ISSUE THREAD

**Issue by pezcode** [KhronosGroup/Vulkan-ValidationLayers#1720]
I'm getting the following warning with a Vulkan 1.1 instance and best practices validation enabled:

> Validation Warning: [ UNASSIGNED-BestPractices-vkCreateDevice-deprecated-extension ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xad32db6 | CreateDevice(): Attempting to enable deprecated extension VK_EXT_descriptor_indexing, but this extension has been promoted to VK_VERSION_1_2.

I feel like I shouldn't be getting warnings for using extensions that are only deprecated in a *later* Vulkan version. Is this intended or a bug?

**Comment by mark-lunarg** [comment]
Nah, you're right -- you shouldn't be!

**Comment by krOoze** [comment]
I recently had to modify relevant tests for unrelated reasons. But I was gonna mention the coverage of the tests is low, and this might happen. Also should test if extension is deprecated due to another extension, and if extension is just obsoleted (`VK_NV_glsl_shader`).

**Comment by mark-lunarg** [comment]
@pezcode, we just pushed a fix for a related issue, can you let us know if this fixes the problem you encountered as well?

**Comment by pezcode** [comment]
Thanks for the heads-up. I'll have to find some time to figure out how to compile the layers from source and report back.

**Comment by mark-lunarg** [comment]
If you're using Windows, you can get build artifacts from [appveyor through Github CI](https://ci.appveyor.com/project/Khronoswebmaster/vulkan-validationlayers/builds/32887626/job/e8i1bbsyf8m8t1wg/artifacts).

**Comment by pezcode** [comment]
> 
> 
> If you're using Windows, you can get build artifacts from [appveyor through Github CI](https://ci.appveyor.com/project/Khronoswebmaster/vulkan-validationlayers/builds/32887626/job/e8i1bbsyf8m8t1wg/artifacts).

Oh, perfect. I can confirm that the issue is fixed for me on that change id, compared to 1.2.135.0

Closing, and thanks for the fix!
