### ISSUE TITLE
[Request] Validation for properly matching VkImageLayouts for VkDescriptorImageInfo

### ISSUE THREAD

**Issue by starbucksDave** [KhronosGroup/Vulkan-ValidationLayers#1723]
I've been debugging a Vulkan application on Intel hardware for the past couple of days, and found out that the validation layer is missing some crucial validation that could've saved me multiple days of debugging..

We were binding a `VkImage` with `VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL` to a binding in a descriptor set, however in the `VkDescriptorImageInfo` we always specified `VK_IMAGE_LAYOUT_GENERAL`... 

NVIDIA and AMD totally don't care whatever is in the `VkDescriptorImageInfo::imageLayout`, but Intel does. 

To my surprise, the validation layers did not catch this bug, so I would like to report this to the maintainers.

FYI I was using the latest Vulkan SDK available at this moment, i.e. 1.2.135.0. 

Related Vulkan spec info: 
- https://renderdoc.org/vkspec_chunked/chap13.html#VkDescriptorImageInfo
- https://renderdoc.org/vkspec_chunked/chap11.html#resources-image-layouts-matching-rule

**Comment by mark-lunarg** [comment]
@Tony-LunarG, someday, when all the promised spare time falls into your lap, maybe you could throw together a test for this, and then either fix it or tell me what to do to fix it?  If not, just assign it back to me.

**Comment by Tony-LunarG** [comment]
First, apologies for it taking us so long to get to this
I modified the validation layer test ImageDescriptorLayoutMismatch to match the issue description by changing the first call to do_test to:

do_test(&image, &view, VK_IMAGE_ASPECT_COLOR_BIT, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
                VK_IMAGE_LAYOUT_GENERAL, /* positive */ false);

which does an UpdateDescriptorSets using an image view created from said image and specifying VkImageLayout = VK_IMAGE_LAYOUT_GENERAL.
It then records a command buffer that does an pipeline barrier setting the image's layout to VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
binds the descriptor set, and does a CmdDraw.  Validation reports VUID-VkDescriptorImageInfo-imageLayout-00344 at draw time:

Validation Error: [ VUID-VkDescriptorImageInfo-imageLayout-00344 ] Object 0: handle = 0x25043b85058, 
type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xde55a405 | vkCmdDraw(): Cannot use VkImage 0xe81828000000000d[] (layer=0 mip=0) with specific layout VK_IMAGE_LAYOUT_GENERAL 
that doesn't match the previous known layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL. The Vulkan spec states: imageLayout must match the actual VkImageLayout of each subresource accessible from imageView at the time this descriptor is accessed as defined by the image layout matching rules

The test then records and submits a command buffer with a barrier setting the image's layout to VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL
records another command buffer that binds the descriptor set and does a CmdDraw, and then when the command buffer is submitted to QueueSubmit, validation reports:

Validation Error: [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object 0: handle = 0x25043b85058, 
type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x4dae5635 | Submitted command buffer expects VkImage 0xe81828000000000d[] (subresource: aspectMask 0x1 array layer 0, mip level 0) 
to be in layout VK_IMAGE_LAYOUT_GENERAL--instead, current layout is VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL.

So I think that in both the case where the image layout can be known at draw time and the case where it cannot, the image layout / descriptor layout mismatch is reported.

@starbucksDave is there something that your code is doing that  ImageDescriptorLayoutMismatch is not that is causing you not to see one of these errors?  Do you still see the problem with the latest SDK?

**Comment by Tony-LunarG** [comment]
Assuming my experiments show that validation is happening, I'll close this issue.  Feel free to re-open or re-submit if you are still seeing a problem here.
