### ISSUE TITLE
Add validation coverage for TransformFeedback API

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-ValidationLayers#1724]
Currently most of the VUIDs related to vkCmdBeginTransformFeedback() and vkCmdEndTransformFeedback() are reported as not covered in the error [database](https://vulkan.lunarg.com/doc/sdk/1.2.131.2/windows/validation_error_database.html). It appears to be about 25 missing checks total with most of them being explicit.

This is a tracking bug to add validation coverage for those checks along with tests to verify the checks are correct.

**Comment by null77** [comment]
For context, we're implementing GL transform feedback in ANGLE and aren't sure if we're calling the APIs correctly. See http://anglebug.com/3206

**Comment by null77** [comment]
This came up again in ANGLE: http://anglebug.com/4533

**Comment by jeremy-lunarg** [comment]
The majority of the VUIDs have been added by #1861. There is still a hole that is part of a larger coverage effort that is logged in #135.

**Comment by null77** [comment]
That's great! Will be a big help in proving ANGLE's transform feedback correctness.
