### ISSUE TITLE
Cleanup Tests on Android (mostly for CI)

### ISSUE THREAD

**Issue by sfricke-samsung** [KhronosGroup/Vulkan-ValidationLayers#1726]
Some Android Hardware Buffer tests are [being blacklisted](https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/f84b766cc4368ed5b6af4edcc09670575ffe7a01) and this issue is to track progress on all things related to getting AHB tests fully cleaned up.

----

Notes for anyone who wants to know

apply patch to [build-android/jni/Application.mk](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/build-android/jni/Application.mk)
```
diff --git a/build-android/jni/Application.mk b/build-android/jni/Application.mk
index 243c2853..7cf48a20 100644
--- a/build-android/jni/Application.mk
+++ b/build-android/jni/Application.mk
@@ -19,3 +19,4 @@ APP_PLATFORM := android-26
 APP_STL := c++_static
 NDK_TOOLCHAIN_VERSION := clang
 NDK_MODULE_PATH := .
+APP_OPTIM := debug
\ No newline at end of file
```
In order to show `asserts()`

If you get an adb log crash dump, use `ndk-stack -i crashdump.txt -sym build-android/obj/local/arm64-v8a` and it will turn the backtrace into something useful such as
```
#00 0x0000000000553e30
CoreChecks::PreCallValidateCmdBindPipeline(VkCommandBuffer_T*, VkPipelineBindPoint, VkPipeline_T*) const
Vulkan-ValidationLayers/build-android/jni/../../layers/core_validation.cpp:4700:0
```

**Comment by sfricke-samsung** [comment]
So I have ran into some tests such as `VkPositiveLayerTest.CreatePipelineAttachmentUnused` that crash my Galaxy S9 Mali Device

```
Bakctrace:
#00 0x000000000078efb8 /vendor/lib64/egl/libGLES_mali.so
#01 0x000000000078dfe8 /vendor/lib64/egl/libGLES_mali.so (vkCreateGraphicsPipelines+488)
#02 0x000000000085d868 /lib/arm64/libVkLayer_khronos_validation.so
DispatchCreateGraphicsPipelines(VkDevice_T*, VkPipelineCache_T*, unsigned int, VkGraphicsPipelineCreateInfo const*, VkAllocationCallbacks const*, VkPipeline_T**)
layer_chassis_dispatch.cpp:245:23
#03 0x0000000000899514 /lib/arm64/libVkLayer_khronos_validation.so
vulkan_layer_chassis::CreateGraphicsPipelines(VkDevice_T*, VkPipelineCache_T*, unsigned int, VkGraphicsPipelineCreateInfo const*, VkAllocationCallbacks const*, VkPipeline_T**)
chassis.cpp:705:23
#04 0x0000000000011fe0 /system/lib64/libvulkan.so 
(_ZN6vulkan3api12_GLOBAL__N_123CreateGraphicsPipelinesEP10VkDevice_TP17VkPipelineCache_TjPK28VkGraphicsPipelineCreateInfoPK21VkAllocationCallbacksPP12VkPipeline_T+224)
#05 0x00000000004b5008 /lib/arm64/libVulkanLayerValidationTests.so
CreatePipelineHelper::CreateGraphicsPipeline(bool, bool)
```

So I have no way around the test other then to black list it locally

**Comment by mark-lunarg** [comment]
@sfricke-samsung, so this crash is due to a driver bug de-referencing a structure pointer that it should be ignoring, yes?  So when @Tony-LunarG adds the ability for each test to detect the current platform and skip if necessary, we should add this GPU to that list?

**Comment by mark-lunarg** [comment]
Another note for Tony.  Currently the test framework has a function, DeviceIsMockICD().  This should get folded into whatever GPU ID function ends up getting implemented (assuming it's even possible!) and go away.

**Comment by sfricke-samsung** [comment]
@mark-lunarg I have found crashes were happening from 2 main causes

1. The test assumed the driver compiled the shader, but when it didn't it hits the assert() from not having the `PIPELINE_STATE`. This is easy to fix in tests as just need to check for pipeline being created where a test crashes a device
2. In the case of  `VkPositiveLayerTest.CreatePipelineAttachmentUnused` if you look at the backtrace, it crashed in the driver as this case it was unable to handle a shader that didn't reference the input attachment. This is a driver bug and nothing that can be done by blacklist the test from the device

**Comment by mark-lunarg** [comment]
@sfricke-samsung, #1729 is pushed, do you wish to leave this issue open?

**Comment by sfricke-samsung** [comment]
For now, I have a few things I still want to investigate

**Comment by sfricke-samsung** [comment]
I feel #1785 does a good job handling this as a blacklist now that can be controlled from my end now so happy to close this. Thanks again for the PR
