### ISSUE TITLE
BestPractices::PreCallRecordCreateInstance assumes pApplicationInfo is non-NULL

### ISSUE THREAD

**Issue by janharaldfredriksen-arm** [KhronosGroup/Vulkan-ValidationLayers#1739]
The last line of this function crashes if pApplicationInfo is NULL (which it's allowed to be):
```
void BestPractices::PreCallRecordCreateInstance(const VkInstanceCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator,
                                                VkInstance* pInstance) {
    ValidationStateTracker::PreCallRecordCreateInstance(pCreateInfo, pAllocator, pInstance);
    instance_api_version = pCreateInfo->pApplicationInfo->apiVersion;
}
```

The fix probably needs to disable the check that uses instance_api_version (?).

**Comment by samwalls-arm** [comment]
Hey, since I've been working on this most recently, I'll try to look into this soon and bundle a fix along with other checks. Unless @mark-lunarg would prefer that a fix for this is self-contained in a PR?
