### ISSUE TITLE
Validation layer doesn't warn if a shader uses `GL_EXT_multiview ` but no `VkRenderPassMultiviewCreateInfo` has been specified for the render pass.

### ISSUE THREAD

**Issue by VZout** [KhronosGroup/Vulkan-ValidationLayers#1749]
If you have a shader which makes use of `GL_EXT_multiview` and you create a pipeline with a render pass that didn't specify `VkRenderPassMultiviewCreateInfo` the validation layer doesn't give a error or warning.

It would be nice if the validation layer could give a hint to developers about this since it can cause issues on some hardware.

**Comment by mark-lunarg** [comment]
@VZout, I was unable to find any valid usage related to this relationship, could you point us to the spec language we could use for validation?

**Comment by mark-lunarg** [comment]
@VZout, bump.

**Comment by spencer-lunarg** [comment]
I think this is a valid request to validate, but should get a VUID, will raise a request to add one to the spec (or get a CTS showing this would work)

**Comment by VZout** [comment]
Sorry I didn't reply 2 years ago 😓 but thanks @spencer-lunarg

**Comment by spencer-lunarg** [comment]
better late than never, will help get this into the spec and coded up in the Validation Layers to save the next developer who does the same thing!

**Comment by oddhack** [comment]
@spencer-lunarg this should be fixed in the 1.3.234 spec update, just pushed.

**Comment by spencer-lunarg** [comment]
Thanks Jon! The following are now the missing VUs that need to be added

- [ ] VUID-VkGraphicsPipelineCreateInfo-renderPass-06048
- [ ] VUID-VkGraphicsPipelineCreateInfo-renderPass-06049
- [ ] VUID-VkGraphicsPipelineCreateInfo-renderPass-06050
  - VUID-VkGraphicsPipelineCreateInfo-renderPass-06059 is done but for dynamic rendering
- [ ] VUID-VkGraphicsPipelineCreateInfo-renderPass-07717
- [ ] VUID-VkGraphicsPipelineCreateInfo-renderPass-07718
- [ ] VUID-VkGraphicsPipelineCreateInfo-renderPass-07719
- [ ] VUID-VkGraphicsPipelineCreateInfo-renderPass-07720
