### ISSUE TITLE
Unable to build with recent Vulkan-Headers

### ISSUE THREAD

**Issue by dj2** [KhronosGroup/Vulkan-ValidationLayers#1752]
If you have the latest Vulkan-Headers and you use it by adding the headers subdirectory first the configure step will fail. This is due to https://github.com/KhronosGroup/Vulkan-Headers/commit/382bf3de06fc8c8961055afc37957fe65846c33b which changed the `target_include_directories` command to have the `BUILD_INTERFACE` and `INSTALL_INTERFACE`.

From my searching around those get evaluated at non-configure time, so when the layers tries to do the `FILE` command later to determine the headers version we end up with a `VulkanHeader_INCLUDE_DIRS` with something like:

```
"/Users/dsinclair/Development/vulkan-validationlayers/$<BUILD_INTERFACE:/Users/dsinclair/Development/vulkan-validationlayers/external/Vulkan-Headers/include>;$<INSTALL_INTERFACE:include>/vulkan/vulkan_core.h"
```

which doesn't work so well

**Comment by dj2** [comment]
@mikew-lunarg  @rbsheth

**Comment by mark-lunarg** [comment]
@jd2, at first glance it seems this would need to be fixed in the headers repo, unless your evidence points to some mismanagement in the VVL cmake files, is that your conclusion?

**Comment by dj2** [comment]
Yea, I just came to the same conclusion and was coming to add that comment, heh. Should I move this over?

**Comment by mark-lunarg** [comment]
Yeah, that would be preferable since, at the moment, there's nothing for us to do here.  If it blows back and errors need to be fixed on our side, you can comment here and I'll reopen it.  I just KNEW that PR was going to bite us!

**Comment by dj2** [comment]
Moved to https://github.com/KhronosGroup/Vulkan-Headers/issues/111

**Comment by dj2** [comment]
Done, thanks.
