### ISSUE TITLE
std::bad_alloc when pSpecializationInfo is not declaired.

### ISSUE THREAD

**Issue by Root3287** [KhronosGroup/Vulkan-ValidationLayers#1763]
I had a bug in my program where it was throwing a std::bad_alloc while creating the pipeline. I found out that in the `VkPipelineShaderStageCreateInfo` you need to set the `pSpecializationInfo` to be a nullptr. The validation layers didn't pick that up or warned about it.

**Comment by mark-lunarg** [comment]
@Root3287, the Vulkan specification for this particular case says `pSpecializationInfo is a pointer to a VkSpecializationInfo structure, as described in Specialization Constants, or NULL`.

**Comment by mark-lunarg** [comment]
Closing this issue for now, please comment again if you feel it was closed prematurely.
