### ISSUE TITLE
Format Features of Swapchain Image?

### ISSUE THREAD

**Issue by danielmaciel** [KhronosGroup/Vulkan-ValidationLayers#1764]
Hi, I just cloned the latest validation layers.
I have noticed a new validation error:
`
Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-blendEnable-02023 ] Object 0: handle = 0xb3deb0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x1991022a | vkCreateGraphicsPipelines(): pipeline.pColorBlendState.pAttachments[0].blendEnable is VK_TRUE but format VkImage 0x40000000004[] associated with this attached image (VK_FORMAT_B8G8R8A8_SRGB) does not support VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT. The Vulkan spec states: If rasterization is not disabled and the subpass uses color attachments, then for each color attachment in the subpass the blendEnable member of the corresponding element of the pAttachment member of pColorBlendState must be VK_FALSE if the attached image's format features does not contain VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-blendEnable-02023)
`
The image it is complaining about is a Swapchain Image. I checked the spec and it doesn't seem to say anything about format features of a Swapchain Image. Are you taking format features of Swapchain Images in consideration here? Is this a spec bug, a validation bug or a driver bug?
If I disable `blendEnable` for that image, I lose blending. It works perfectly without the validation layer.
NVIDIA drivers 4.40 on Ubuntu 20.04. I also had the same problem on 19.04, 4.35 driver.

**Comment by krOoze** [comment]
Hm, what does `vkGetPhysicalDeviceFormatProperties(pd, VK_FORMAT_B8G8R8A8_SRGB, &props)` actually return for you?

**Comment by danielmaciel** [comment]
`props.optimalTilingFeatures` contains `BLEND` bit
`(VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT | VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT | VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT | VK_FORMAT_FEATURE_BLIT_SRC_BIT | VK_FORMAT_FEATURE_BLIT_DST_BIT | VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT | VK_FORMAT_FEATURE_TRANSFER_SRC_BIT | VK_FORMAT_FEATURE_TRANSFER_DST_BIT | VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_MINMAX_BIT) (122241)
`
`props.lineartilingFeatures` does not
(VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT | VK_FORMAT_FEATURE_BLIT_SRC_BIT | VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT | VK_FORMAT_FEATURE_TRANSFER_SRC_BIT | VK_FORMAT_FEATURE_TRANSFER_DST_BIT | VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_MINMAX_BIT) (119809)

@krOoze good that you found a potential root cause

**Comment by krOoze** [comment]
@danielmaciel well, I also fixed it

**Comment by danielmaciel** [comment]
Awesome! Thanks! Will try it out later
