### ISSUE TITLE
Thank you for removing VK_LAYER_LUNARG_standard_validation and replacing it with VK_LAYER_KHRONOS_validation!

### ISSUE THREAD

**Issue by procedural** [KhronosGroup/Vulkan-ValidationLayers#1781]
Thank you very much for removing VK_LAYER_LUNARG_standard_validation and replacing it with VK_LAYER_KHRONOS_validation! I think we should do this more often. Say, once a year.

**Comment by mark-lunarg** [comment]
Always happy to take PRs!
