### ISSUE TITLE
Generated source not re-generated if headers are changed.

### ISSUE THREAD

**Issue by dj2** [KhronosGroup/Vulkan-ValidationLayers#1782]
In my build I updated to the newest vulkan-headers and rebuilt the layers and they did not rebuild the generated files, they used the version which is committed. The committed version does not work with the latest headers if re-generated.

The generated files should be configured to re-build if the vulkan header files have changed.

**Comment by mark-lunarg** [comment]
The generate source script to build sources runs from the command line:

`python scripts\generate_source.py path/to/your/Vulkan-Headers/registry`

It is designed to be run during header updates, or if changes are being made to one of the source code generators.  All code generated by the script is checked into the repo, so in normal usage there is no need to run the generator during builds.

**Comment by dj2** [comment]
There is a cmake target which can be executed with `ninja VulkanVL_generated_source` which I was expecting to run when the headers changed.

It would be nice if that target could be setup with the registry as a dependency so if it changes it auto-generates.

**Comment by mark-lunarg** [comment]
@dj2, talked to @mikes-lunarg and we're considering adding a cmake dependency on `vk.xml `for running `generate_source.py`, and this would be behind a cmake variable or developer option that you would set.  It's on the list but may take awhile.  And PRs are welcome!

**Comment by dj2** [comment]
When you say behind a flag, do you mean the dependency would be behind the option or the target `VulkanVL_generated_source` would move behind the flag and the dependency would always be set?

**Comment by mark-lunarg** [comment]
We'd prefer that the dependency and everything be protected by a cmake variable, which would need to be set when running cmake and generate the source if the dependencies called for it.  So if the var is not explicitly set, behavior is identical to present operation regardless of what's in the Vulkan-Headers repo.

**Comment by mark-lunarg** [comment]
We believe the solution is to move the functionality of this script back into cmake, and it's on the list.

**Comment by mark-lunarg** [comment]
This issue has been rolled into the [Validation Layer Enhancements Project Page](https://github.com/KhronosGroup/Vulkan-ValidationLayers/projects/4).
