### ISSUE TITLE
Generated files do not work with latest Vulkan-Headers

### ISSUE THREAD

**Issue by dj2** [KhronosGroup/Vulkan-ValidationLayers#1783]
I updated to the latest vulkan headers (https://github.com/KhronosGroup/Vulkan-Headers/commit/4c19ae6b95e44c821d5306adf94842defa57ba21) and re-generated the generated files and the build fails:

```
../../third_party/vulkan-validationlayers/layers/object_tracker_utils.cpp:341:23: error: out-of-line definition of 'PreCallRecordDestroyInstance' does not match any declaration in 'ObjectLifetimes'; did you mean 'PostCallRecordDestroyInstance'?
void ObjectLifetimes::PreCallRecordDestroyInstance(VkInstance instance, const VkAllocationCallbacks *pAllocator) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                      PostCallRecordDestroyInstance
../../third_party/vulkan-validationlayers/layers/generated/object_tracker.h:2606:6: note: 'PostCallRecordDestroyInstance' declared here
void PostCallRecordDestroyInstance(VkInstance instance, const VkAllocationCallbacks *pAllocator);
     ^
1 error generated.
```

**Comment by dj2** [comment]
(Sorry, this is in https://github.com/google/vkb where I ran the tests)

**Comment by mark-lunarg** [comment]
Yes, it is unlikely that the validation layers will compile with header version newer than the commit specified in the `known_good.json` (which is why it exists).  There is a 2-5 day process that takes place after Vulkan-Headers is updated, where the downstream repos are modified to work with the new header changes, and their `known_good.json` commit IDs are updated.

**Comment by dj2** [comment]
K, we have internal processes which roll all these things automatically. Wanted to make sure the breakage was on your radar, and will use this bug as a way to know when we can update internally.

**Comment by dj2** [comment]
Issue https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/1782 is the more interesting one in this case. My VKB build passed because the files were not re-generated and I expected they would be.

**Comment by mark-lunarg** [comment]
Using the update_deps script to build this repo should always work.  Building TOT vulkan-headers and TOT downstream repos is likely to fail or produce undefined results more than half of the time.

**Comment by dj2** [comment]
We've had pretty good success with rolling tip-of-tree. When we run into issues we file bugs, to get things worked out. We aren't using the deps as specified by update_deps in most cases, we typically don't work with installed dependencies but have the build system handle them.

**Comment by mark-lunarg** [comment]
I'm astonished, that's great to hear!  So maybe we can help out with the generate_source script -- is there anything more to be done as part of this issue? If you want, I guess I can assign it to @shannon-lunarg and have her notify you through this issue that this repo has been updated to use the new Vulkan-Headers.

**Comment by dj2** [comment]
Yea, if we can keep it open for when the update is done, that would be awesome.  I can then kick off the internal updates.

**Comment by mark-lunarg** [comment]
@shannon-lunarg, will you update this issue and close it when the 139 header update is done please?

**Comment by KarenGhavam-lunarG** [comment]
@mark-lunarg Is this a one time activity, for the 139 header update? Or something Shannon needs to do with each header update (ugh)?

**Comment by dj2** [comment]
I'm just looking for when the 139 update is done. Thanks.

**Comment by mark-lunarg** [comment]
Closing this for @shannon-lunarg.
