### ISSUE TITLE
CoreChecks::VerifyQueryIsReset logs an error for performance query with multiple pass 

### ISSUE THREAD

**Issue by bcmet** [KhronosGroup/Vulkan-ValidationLayers#1795]
Performance queries can have multiple pass and the query should not be reset between passes.

CoreChecks::VerifyQueryIsReset checks that the status of the query is QUERYSTATE_RESET when the command cmdBeginQuery is submitted.  After a command cmdBeginQuery, the query status is changed to QUERYSTATE_RUNNING.

This works for the first pass as the query has been reset but for the next pass, the query has not been reset (should not be reset between passes), its status is still QUERYSTATE_RUNNING and an error is logged.

For performance query, CoreChecks::VerifyQueryIsReset should probably only log an error if it is the first pass for that query.

**Comment by Tony-LunarG** [comment]
Performance query validation was reworked here #1682  @bcmet do you know if that rework addresses your false positive?

**Comment by mark-lunarg** [comment]
After review, we are calculating that this issue is covered by the changes in #1682.  If this is incorrect, please reopen this issue or create a new one.  Thanks for the report!
