### ISSUE TITLE
rendering to subresource(layer=1) of an image3d expects subresource(layer=0) to be in VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL

### ISSUE THREAD

**Issue by ansicode** [KhronosGroup/Vulkan-ValidationLayers#1799]
Vulkan SDK version 1.1.126
When I tried to initialize an 3D image by following steps:

> img3d  = vkCreateImage(VK_IMAGE_TYPE_3D and size(w,h,2)) // no mipmaps
view0  = vkCreateImageView(img3d, subresource(layer=0))
view1 = vkCreateImageView(img3d, subresource(layer=1))
pass0 = vkCreateRenderPass(initialLayout=undefined, layout=color_attachment finalLayout=shader_read_optimal)
pass1 = vkCreateRenderPass(initialLayout=undefined, layout=color_attachment, finalLayout=shader_read_optimal)
framebuffer0 = vkCreateFramebuffer(view0, pass0)
framebuffer1 = vkCreateFramebuffer(view1, pass1)
cmd0 = VkAllocateCommandBuffer()
vkCmdBeginRenderPass(cmd0, framebuffer0, pass0)
//draw sth
vkCmdEndRenderPass(cmd0)
cmd1 = VkAllocateCommandBuffer()
vkCmdBeginRenderPass(cmd1, framebuffer1, pass1)
//draw sth
vkCmdEndRenderPass(cmd1)
vkQueueSubmit({cmd0, cmd1})

I got an InvalidImageLayout error:
>Submitted command buffer(cmd1) expects VkImage [img3d] (subresource: aspectMask 0x1 array layer 0, mip level 0) to be in layout VK_IMAGE_COLOR_ATTACHMENT_OPTIMAL--instead, current layout is VK_IMAGE_LAYOUT_SHADER_READ_OPTIMAL

Seems cmd0 passed the validation and transfer view0 to be in layout VK_IMAGE_LAYOUT_SHADER_READ_OPTIMAL, this is correct.
Question is,
Why cmd1 would expect view0 to be in layout VK_IMAGE_COLOR_ATTACHMENT_OPTIMAL when it's rendering to view1?

**Comment by mark-lunarg** [comment]
Maybe it's just an artifact of the pseudo-code, but when I try to create an image view of a 3D image and set the baseArrayLayer to 1, I do get an error as 3D images only have a single layer, so I assume you're setting the 2D compatible bit, etc?   If you could possibly share a repro-case or api dump, that'd speed things up considerably.

**Comment by ansicode** [comment]
sorry for the artifacts. yes it's created with the 2D compatible bit.
we update our SDK to the latest version 1.2.135.0.
now it works without validation errors.
thanks for your time.
