### ISSUE TITLE
Refactor MapMemory

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#18]
**Issue by [tobine](https://github.com/tobine) (MIGRATED)**
_Monday Mar 06, 2017 at 20:13 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1534_

----

Refactor vkMapMemory() to follow the pre/post pattern where validation takes place during pre & state updates occur down post path.

**Comment by mark-lunarg** [comment]
Tracked in issue #77.
