### ISSUE TITLE
Does SPIRV_HEADERS_INCLUDE_DIR have to be set manually?

### ISSUE THREAD

**Issue by jeffbolznv** [KhronosGroup/Vulkan-ValidationLayers#1829]
BUILD.md still suggests this for the Windows build instructions:

```
cmake -A x64 -DVULKAN_HEADERS_INSTALL_DIR=absolute_path_to_install_dir \
             -DGLSLANG_INSTALL_DIR=absolute_path_to_install_dir ..
```

After the change to use SPIRV-Headers to get spirv.hpp, I also need `-DSPIRV_HEADERS_INCLUDE_DIR=abolute_path_to_install_dir` to build successfully. Should the build instructions be updated?

(FWIW, I don't understand why I need any of these manual options, given that I'm using update_deps.py to install all of these).

**Comment by mark-lunarg** [comment]
@jeffbolznv, yes, it's on my plate to do this -- now that there's an issue I guess I'll have to get to it sooner(!) -- thanks for the reminder.  

Lot's of folks can't/won't use `update_deps`, so this still has to work, even though it's nearly unmanageable.
