### ISSUE TITLE
Validation layer crash after reporting that descriptor set is not bound.

### ISSUE THREAD

**Issue by kennyalive** [KhronosGroup/Vulkan-ValidationLayers#184]
I have a use case when descriptor set is not bound and I get a deserved validation error:

> VkPipeline 0x2347 uses set #2 but that set is not bound.

After that core_validation.cpp layer crashes in `UpdateDrawState `function due to:

```
cvdescriptorset::DescriptorSet *descriptor_set = state.boundDescriptorSets[setIndex];
if (!descriptor_set->IsPushDescriptor()) {
...
```

This code tries to access a descriptor that previously was reported as unbound (the retrieved descriptor_set is null). I assume the validation error should not cause a crash of the layer.

**Comment by daveh-lunarg** [comment]
After some discussion I'm convinced that the current crash during UpdateDrawState() is the best (aka the least bad) option available to the validation layer. At the time of the crash the error condition has already been logged, and the known-corrupt Draw command has been sent to the driver. At that point the driver hasn't (yet) crashed, but both driver and the validation layer are in unknown states and no further validation can be relied upon.

Avoiding the null dereference in UpdateDrawState may just lead to another crash at some point more distant from the actual error, or a spew of unreliable error messages. Allowing the layer crash isn't ideal but it appears the best option of those available.

**Comment by kennyalive** [comment]
I agree in the case when it leads to driver crash it might be the best option.
My situation is a bit different. In our case it could not lead to driver crash since shader has logic that resource is not used if descriptor set was not bound by c++ code (regular condition based on the value of uniform variable). So it seems it should not violate vulkan spec - at runtime shader does not use unbound resource.
Of course the guarantee of correctness for such usage scenario is completely described by app logic and potential usage of unbound resource can not be determined by static spriv analysis. We fixed the issue on our side by using dummy resource for initialization but it's rather a patch to make validation layers happy.
