### ISSUE TITLE
VK_LAYER_KHRONOS_validation SEGV when creating an image view

### ISSUE THREAD

**Issue by io7m** [KhronosGroup/Vulkan-ValidationLayers#1847]
Hello!

I'm seeing a segmentation fault in code that was previously working. The fault appears to be inside the validation layer `.so`. I don't see any validation errors logged, but the program crashes inside the validation for `vkCreateImageView`:

```
Stack: [0x00007facd1a48000,0x00007facd1b49000],  sp=0x00007facd1b47090,  free space=1020k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libVkLayer_khronos_validation.so+0x827436]
C  [libVkLayer_khronos_validation.so+0x7cc457]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.lwjgl.system.JNI.callPPPPI(JJJJ[J)I+0
j  org.lwjgl.vulkan.VK10.vkCreateImageView(Lorg/lwjgl/vulkan/VkDevice;Lorg/lwjgl/vulkan/VkImageViewCreateInfo;Lorg/lwjgl/vulkan/VkAllocationCallbacks;[J)I+46
j  com.io7m.jcoronado.lwjgl.VulkanLWJGLLogicalDevice.createImageView(Lcom/io7m/jcoronado/api/VulkanImageViewCreateInfo;)Lcom/io7m/jcoronado/api/VulkanImageViewType;+60
j  com.io7m.jcoronado.examples.HelloVulkanWithVMA.createTexture(Lcom/io7m/jmulticlose/core/CloseableCollectionType;Lcom/io7m/jcoronado/api/VulkanLogicalDeviceType;Lcom/io7m/jcoronado/vma/VMAAllocatorType;Lcom/io7m/jcoronado/api/VulkanQueueType;Lcom/io7m/jcoronado/api/VulkanCommandPoolType;)Lcom/io7m/jcoronado/examples/HelloVulkanWithVMA$Texture;+173
j  com.io7m.jcoronado.examples.HelloVulkanWithVMA.main([Ljava/lang/String;)V+1153
v  ~StubRoutines::call_stub
```

If I turn off the validation layer, the program runs correctly.

I'm calling Vulkan from Java, but I'm going through the machine-generated LWJGL bindings and I trust their correctness. I trust my usage of them less so, but I'd at least expect validation errors in that case, rather than an outright crash.

My code is here: https://github.com/io7m/jcoronado/blob/develop/com.io7m.jcoronado.examples/src/main/java/com/io7m/jcoronado/examples/HelloVulkanWithVMA.java

It's an extremely thin layer over the standard Vulkan API, but I appreciate that, as Vulkan developers, you're probably not going to want to go picking through a load of Java code. I've attached a `vktrace` of the program, although I think it may not be too illuminating as it obviously won't contain the final crashing call.

[vktrace_out.zip](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/4638592/vktrace_out.zip)

My system is:

```
Linux sunflower.int.arc7.info 5.6.13-arch1-1 #1 SMP PREEMPT Thu, 14 May 2020 06:52:53 +0000 x86_64 GNU/Linux
```

I've attached the output of `vulkaninfo` in case that's important, and I'm using my distribution's (unpatched) layers package:

```
vulkan-extra-layers 1.2.135.0+10638+909f5297d-1
vulkan-headers 1:1.2.140-1
vulkan-html-docs 1:1.2.140-1
vulkan-icd-loader 1.2.140-1
vulkan-mesa-layer 20.0.7-2
vulkan-radeon 20.0.7-2
vulkan-tools 1.2.137-1
vulkan-trace 1.2.135.0+10638+909f5297d-1
vulkan-validation-layers 1.2.137-1
```

[vulkaninfo.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/4638594/vulkaninfo.txt)

Please let me know if there's any other info I can provide.

**Comment by mark-lunarg** [comment]
@io7m, thanks for the detailed report!  After a quick glance I don't see anything unusual in your source (I also don't know java from a hole in the ground).  Also, can you expand on "...previously working..." -- that might be a clue.

To tackle this expeditiously, We'd either need a binary that'd run on an Ubuntu box, or some super-detailed build instructions, or some more involved assistance from you if you wouldn't mind.  The easiest option there is to load up the API-Dump layer before the validation layers, and share the output up to and including the crash.  Alternatively, building a debug version of the Khronos layer and using that to find the offending layer code would also get us much closer.  I'm happy to help out if you have questions and look forward to hearing from you.

**Comment by io7m** [comment]
Hello!

>  Also, can you expand on "...previously working..." -- that might be a clue.

I'm using my distro's validation layers package (Arch Linux). I think they upgraded to a new version at some point within the last few months, and upon resuming work on Vulkan yesterday after being away from it for some time, I find my code no longer works. :wink:

Unfortunately, I don't know what version I was on when things were working. It'll take some bisection (which I'm willing to do!).

> To tackle this expeditiously, We'd either need a binary that'd run on an Ubuntu box, or some super-detailed build instructions, or some more involved assistance from you if you wouldn't mind.

There are multiple options here, so firstly here's a jar file you can run on any JDK newer than or equal to Java 11:

https://ataxia.io7m.com/2020/05/17/com.io7m.jcoronado.examples-0.0.1-SNAPSHOT-main.jar
https://ataxia.io7m.com/2020/05/17/com.io7m.jcoronado.examples-0.0.1-SNAPSHOT-main.jar.asc (PGP signature)

You can run it like this:

```
$ java -jar com.io7m.jcoronado.examples-0.0.1-SNAPSHOT-main.jar
```

You'll likely see a window open, logging output, and then a large "A fatal error has been detected by the Java Runtime Environment:" message.

You can obviously run it under `gdb` like this:

```
$ gdb --args java -jar com.io7m.jcoronado.examples-0.0.1-SNAPSHOT-main.jar
```

The stack information probably won't be a great deal of use until execution reaches a version of the validation layers that you've compiled with debug symbols present. You'll reach Vulkan through several layers of native code (the JVM itself), and interpreted and/or jit-compiled code (my code, and LWJGL), so the stack trace entries before you reach Vulkan can be pretty raw and probably not too useful.

Alternatively, if you want to build the Java code yourself, you'll need JDK 11 or above (Ubuntu almost certainly includes JDK 11 or above) and also Apache Maven 3.6.2 or better. Once those are installed, you should be able to do:

```
$ git clone --recursive https://github.com/io7m/jcoronado/
$ cd jcoronado
$ mvn -DskipTests=true clean package
```

That'll compile all of the code and generate the `jar` file I attached above in `com.io7m.jcoronado.examples/target/com.io7m.jcoronado.examples-0.0.1-SNAPSHOT-main.jar`.

I'm going to take a shot at building a debug version of the Khronos layer. I'm also going to take a shot at the API-Dump layer, as I'm actually quite curious as to the sort of output it produces!

**Comment by io7m** [comment]
API dump: 
[api_dump.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/4640956/api_dump.txt)

**Comment by io7m** [comment]
I did some bisection, and it looks like this one is my fault! It appears that at some point the default memory allocator changed and was causing an uninitialized `pNext` pointer to be non-zero.

Sorry for the noise!

**Comment by io7m** [comment]
I should point out that I only found this because I compiled the layers in debug mode. That meant there were symbols in the `libVkLayer_khronos_validation.so` shared library, and it was pretty clear even just looking at the stack trace alone that `pNext` was at fault.

Is there some reason the release binaries are stripped? I could see myself essentially never using the stripped binaries.

**Comment by KarenGhavam-lunarG** [comment]
> Is there some reason the release binaries are stripped? I could see myself essentially never using the stripped binaries.

Do you mean the validation layers delivered with an SDK? If so, they are built with debug info (not full debug). There is also a .pdb file for the validation layers included in the SDK.

**Comment by mark-lunarg** [comment]
After consulting with some guys who are familiar with the details, as I understand it each Distro enforces a policy for their packages and packaging.  For SDK releases, we build Ubuntu packages, and the policy there is to provide stripped release binaries, and a companion `-dbg` package containing the matching symbolic information.  I'm not sure about Arch, but the package maintainers there are the ones who build those packages, using their policies.  But I'm with you, I use debug builds 99% of the time.  And thanks for the detailed bug report -- I wish they were all like this!

**Comment by io7m** [comment]
Thanks! I'll raise the issue downstream and see if I can find out why they're stripping them.
