### ISSUE TITLE
Possible copy paste bug with VK_FORMAT_FEATURE_TRANSFER_SRC_BIT in vklayertests_buffer_image_memory_sampler.cpp

### ISSUE THREAD

**Issue by qarmin** [KhronosGroup/Vulkan-ValidationLayers#1848]
`VK_FORMAT_FEATURE_TRANSFER_SRC_BIT` is used twice in expression, probably by mistake

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/3a10b92381299c537be363bf3ed191127b6bf7a3/tests/vklayertests_buffer_image_memory_sampler.cpp#L9535

**Comment by mark-lunarg** [comment]
@sfricke-samsung, is it safe to merely remove the duplicate, or was your intention otherwise?

**Comment by sfricke-samsung** [comment]
looking at it seems like a copy and paste error, only need single `VK_IMAGE_USAGE_TRANSFER_SRC_BIT`  to match

```
image_create_info.usage = VK_IMAGE_USAGE_TRANSFER_SRC_BIT;
```

Can make a quick PR fix, this @qarmin for catching this!
