### ISSUE TITLE
Output bug in the error message 0x6287944f

### ISSUE THREAD

**Issue by x3DCoder** [KhronosGroup/Vulkan-ValidationLayers#1864]
```
[ VUID-VkSubpassDescription-loadOp-00846 ] Object 0: handle = 0x555555c9e788, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6287944f | ValidateCreateRenderPass(): attachment 4 is first used as an input attachment in subpass 4 with loadOp=CLEAR.
```
it says `subpass 4` but it's actually subpass 1 (I only have two subpasses here..) looks like a mistake in the generated output message..

**Comment by mark-lunarg** [comment]
Pushed a fix to Master.  Please let me know if this doesn't resolve the issue you found, and thanks for the report!
