### ISSUE TITLE
Timeline semaphore usage breaks state tracking

### ISSUE THREAD

**Issue by Nimanf** [KhronosGroup/Vulkan-ValidationLayers#1886]
Timeline semaphores (VK_KHR_timeline_semaphore) incorrectly breaks state tracking of command buffers and other objects.

It seems tracking of command buffer **in_use** state is done with “RetireQueuWrork()” through only a few APIs such as “waitForFences”, “QueueWaitIdle” and some cases in submissions.

PostCall in vkWaitSemaphoresKHR() API is not doing anything to remove in_use status of command lists. Therefore, the following code breaks all the state tracking.
```
vkQueueSubmit() with VkTimelineSemaphoreSubmitInfoKHR.
vkWaitSemaphoresKHR()
vkResetCommandPool()
```
Reset of command pool can’t figure out that we already waited correctly and displays the following spam. It seems it also causes state tracking for other related objects to go wrong as well.

`VUID-vkResetCommandPool-commandPool-00040,message: Attempt to reset command pool 
with VkCommandBuffer 0xABC[] which is in use`

Vulkan SDK **1.2.131.1** and **1.2.135.0**

**Comment by Nimanf** [comment]
is that because only PostCallRecordWaitSemaphores() is implemented and PostCallRecordWaitSemaphoresKHR (and other KHR versions) are forgotten to be implemented?

**Comment by Nimanf** [comment]
It is fixed in SDK 141. Closing this.

**Comment by mark-lunarg** [comment]
Sweet!  Thanks @Nimanf...
