### ISSUE TITLE
Reverse "divisibility" logic on VkSampleLocationsInfoEXT::sampleLocationGridSize

### ISSUE THREAD

**Issue by csmartdalton86** [KhronosGroup/Vulkan-ValidationLayers#1887]
For setting custom sample locations, the spec states:

> sampleLocationsInfo.sampleLocationGridSize.height must evenly **divide** VkMultisamplePropertiesEXT::sampleLocationGridSize.height

(https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VkGraphicsPipelineCreateInfo)

However, we are getting a validation error that says:

> VkPipelineSampleLocationsStateCreateInfoEXT::sampleLocationsInfo::sampleLocationGridSize.height (1) **must be be a multiple of** VkMultisamplePropertiesEXT::sampleLocationGridSize.height (2) ...

It appears that validation layers are swapping which value is the divisor and which is the dividend.

**Comment by mark-lunarg** [comment]
Spencer, can you address this? If you can't get it it quickly please let me know.

**Comment by sfricke-samsung** [comment]
ugh, so the spec phrases VUs everywhere else as "must be a multiple of" while this one uses "evenly divide" randomly which is something they would be nice to fix to match the other VUs, but I digress

Yes, I messed up here and the logic is flipped and [the code](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1807/files#diff-617ec4ceb169e2ba63e3b5ba46ef3647R1457)

```
if ((grid_size.height % max_grid_size.height) != 0) {
```

should be flipped around to properly match this. @mark-lunarg I can get to this later today as I want to make sure the added tests are correct as well, so if that isn't fast enough please assign back the issue

**Comment by mark-lunarg** [comment]
No, of course that's fine.  It *is* unusual phrasing -- these are the only two spots it's used in the entire spec.  Thanks Spencer!

**Comment by sfricke-samsung** [comment]
sounds good... just noting down the VUIDs that need fixing

VUID-VkGraphicsPipelineCreateInfo-pDynamicStates-01521
VUID-VkGraphicsPipelineCreateInfo-pDynamicStates-01522

**Comment by egdaniel** [comment]
Sad to see this didn't make it into sdk-1.2.141.0 by what looks like a couple hours and will be breaking our tests till next release or require manual layer building :(

**Comment by mark-lunarg** [comment]
You might filter out those messages in your debug callback, use a `vk_layer_settings.txt` file and the `khronos_validation.message_id_filter` setting to suppress the message(s), or the `VK_LAYER_MESSAGE_ID_FILTER `environment variable to do the same.
