### ISSUE TITLE
Broken layer_configuration.md link

### ISSUE THREAD

**Issue by christophe-lunarg** [KhronosGroup/Vulkan-ValidationLayers#1902]
Hi,

In https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/docs/khronos_validation_layer.md there is a link to 
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/docs/layer_configuration.md

However, the file doesn't exist anymore resulting in a broken link.

Thanks,
Christophe

**Comment by mark-lunarg** [comment]
Pull requests are welcomed!

**Comment by KarenGhavam-lunarG** [comment]
The link is incorrect. Is pointing into the docs directory, but should be up one level. This is the file it should be pointing to: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/LAYER_CONFIGURATION.md

**Comment by christophe-lunarg** [comment]
Working on it

**Comment by mark-lunarg** [comment]
Fixed by outstanding PR #1902.
