### ISSUE TITLE
Crash in BestPractices::PreCallValidateCreateInstance() when not setting pApplicationInfo

### ISSUE THREAD

**Issue by cforfang** [KhronosGroup/Vulkan-ValidationLayers#1906]
[The following line](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/500f77901f6d8d077dc268dfe18cc5266ab27bf2/layers/best_practices_utils.cpp#L143) in `BestPractices::PreCallValidateCreateInstance()` always dereferences `VkInstanceCreateInfo.pApplicationInfo`, however `pApplicationInfo` is not required to be non-`NULL`. 

I encountered this when enabling the best-practices functionality, as my app does in fact not use `pApplicationInfo`.

**Comment by mark-lunarg** [comment]
@cforfang, thanks!  This was also discovered and partially addressed by @samwalls-arm as part of PR #1898, and a fix was pushed to master yesterday (below).  It was also cherry-picked over to SDK branch and will be in the soon-to-be-released SDK.  Thanks!

```
commit 17d8dc682c9443e4272cc3572e86f484dc13de4d
Author: Mark Lobodzinski <mark@lunarg.com>
Date:   Wed Jun 3 08:48:58 2020 -0600
    practices: Avoid null pApplicationInfo deref
```
