### ISSUE TITLE
Released Validation Layers v1.2.141.0 built in Debug configuration?

### ISSUE THREAD

**Issue by Valakor** [KhronosGroup/Vulkan-ValidationLayers#1911]
I updated to the latest MacOS SDK 1.2.141.0 and when enabling validation I see the following warning issued to my debug callback:
`VALIDATION LAYERS WARNING: Using debug builds of the validation layers *will* adversely affect performance.`

I have not tested on Windows yet.

**Comment by mark-lunarg** [comment]
This was an issue specific to the MacOS SDK, which will undoubtedly get re-spun shortly.  A similar SDK issue was created in [LunarXchange](https://vulkan.lunarg.com/issue/view/5edb053d670a05242fdccc67), and will be tracked there (LunarXchange is the recommended place for SDK issues).  Thanks!
