### ISSUE TITLE
vkCmdCopyQueryPoolResults() doesn't warn about incorrect flags

### ISSUE THREAD

**Issue by mickbeaver** [KhronosGroup/Vulkan-ValidationLayers#1927]
Hello,

I found that `vkCmdCopyQueryPoolResults()` didn't warn me when I used the `VK_QUERY_RESULT_PARTIAL_BIT` when copying values from a pool that was created with `VK_QUERY_TYPE_TIMESTAMP`.

My flags value was `VK_QUERY_RESULT_64_BIT | VK_QUERY_RESULT_PARTIAL_BIT`. According to the docs at https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdCopyQueryPoolResults.html :

`VK_QUERY_RESULT_PARTIAL_BIT` must not be used if the pool’s `queryType` is `VK_QUERY_TYPE_TIMESTAMP`.

**Comment by sfricke-samsung** [comment]
This is `VUID-vkCmdCopyQueryPoolResults-queryType-00827` (for noting purpose) and it has not been implemented yet it seems. 

I added a few query related items recently and I actually remember seeing this one, apparently missed adding it, will have a PR up today to cover this case!

**Comment by mickbeaver** [comment]
Thank you for looking into this!
