### ISSUE TITLE
Add optimalBufferCopyOffsetAlignment and  optimalBufferCopyRowPitchAlignment to BP

### ISSUE THREAD

**Issue by sfricke-samsung** [KhronosGroup/Vulkan-ValidationLayers#1930]
The `optimalBufferCopyOffsetAlignment` and `optimalBufferCopyRowPitchAlignment` values in `VkPhysicalDeviceLimits` are good candidates to add to the Best Practice Layers to warn apps that they have sub-par alignment

**Comment by mark-lunarg** [comment]
Moved to BP tracking issue #24.  This is great, thanks Spencer.
