### ISSUE TITLE
Missing validation for VkExternalMemoryImageCreateInfo with valid externalFormat

### ISSUE THREAD

**Issue by courtney-g** [KhronosGroup/Vulkan-ValidationLayers#1934]
While adding support to ANGLE for importing external images I ran into validation errors that I don't think are errors.

In particular, I was getting complaints about an invalid VkFormat of VK_FORMAT_UNDEFINED. While it's generally true that having a VkFormat of VK_FORMAT_UNDEFINED is not valid, there are cases when using the VK_KHR_external_memory extension where it's required.

**Comment by courtney-g** [comment]
Reference CL can be found here: https://github.com/courtney-g/Vulkan-ValidationLayers/commit/40e10b60c587cb417fd46ae29431aa005f4f84f7

That's not final or complete, just what I changed to get validation happy. I'll leave it to LunarG to provide production code.

**Comment by sfricke-samsung** [comment]
So this was an issue I already have caught and made the internal spec fixes a few weeks ago, but the change is in the 1.x.143 headers which are currently being pulled in (also left a [comment explaining this exact issue](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1926#issuecomment-642404579) yesterday)

So if you don't mind waiting, once the #1926 gets pulled in, I have a change to fix the whole `VK_FORMAT_UNDEFINED` format issue here!

**Comment by courtney-g** [comment]
Awesome, that sounds great!

**Comment by mark-lunarg** [comment]
@spencer, I'm hoping this is unblocked now, yes?

**Comment by sfricke-samsung** [comment]
no, waiting on #1952 to merge now since #1926 worked moved there
