### ISSUE TITLE
Add command buffer/command causing layout updates to global layout check

### ISSUE THREAD

**Issue by Tobski** [KhronosGroup/Vulkan-ValidationLayers#1936]
An ISV has been hitting an validation error originating in the CoreChecks::ValidateCmdBufImageLayouts function. Debugging the cause of this error has been fraught though -  the error message doesn't indicate where the error occurred beyond the current command buffer being submitted, when really we want to know what specific commands are interacting.

It would be extremely helpful if this check could include point-of-origin checks to indicate:

- Which command buffer set the layout last
- Which command in that command buffer set that layout
- Which command in the new command buffer expects a different layout

The error output in question is here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/9506ae485ab4d5650296c9c53fe63738405c1ccf/layers/buffer_validation.cpp#L3606

I imagine this will require changes to the GlobalImageLayoutMap in some fashion, to carry this extra information.

**Comment by mark-lunarg** [comment]
Moving to the tracking issue for these types of enhancements, #679.
