### ISSUE TITLE
Q: can layers track undefined memory reads from HOST?

### ISSUE THREAD

**Issue by scyganINTEL** [KhronosGroup/Vulkan-ValidationLayers#1954]
This is a question, rather than issue: 

Is there any way to make layers warn on accessing undefined memory contents from HOST?

Consider this pseudocode:
```
vkCmdCopyImageToBuffer() -> writes some contents from device to the memory range
-- a barrier from device write access to host read access is missing here --
vkEndCommandBuffer()

vkQueueSubmit()
vkWaitFences()

vkInvalidateMappedMemoryRanges()
```

Is there any way to make Layers warn in vkInvalidateMappedMemoryRanges(), that the memory range invalidated on host was not 'flushed' on device, as there was no barrier transitioning the memory to `VK_ACCESS_HOST_READ_BIT` access?

Do layers track device memory writes anywhere, so we could implement that check?

**Comment by jzulauf-lunarg** [comment]
Currently there is no support for this. We are working to add synchronization checks to the validation layers, but host/device interactions will not be part of the first deliverable.

**Comment by scyganINTEL** [comment]
Thansk for the info!
