### ISSUE TITLE
Segmentation Fault During vkAcquireNextImageKHR while using VK_LAYER_KHRONOS_validation

### ISSUE THREAD

**Issue by Moggers** [KhronosGroup/Vulkan-ValidationLayers#1955]
If I call vkGetSwapchainImagesKHR to fetch the number of images, and then make no subsequent call to fetch the images into an array, when I then go to call vkAcquireNextImageKHR later on, a segfault is caused inside core_validation.cpp (looks to be https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/core_validation.cpp#L11131-L11133), where it is trying to iterate over the swapchain images. 

Inspecting the swapchain in gdb at the place the exception is thrown, shows the following in the unhappy path:
```
(gdb) p swapchain_data->images
$2 = std::vector of length 3, capacity 3 = {{image = 0x0, bound_images = std::unordered_set with 0 elements}, {image = 0x0,
    bound_images = std::unordered_set with 0 elements}, {image = 0x0, bound_images = std::unordered_set with 0 elements}}
```

If removing both calls, swapchain_data contains the following:
```
(gdb) p swapchain_data->images
$3 = std::vector of length 0, capacity 0
```

If calling twice, once to get length and then to populate an array:
```
(gdb) p swapchain_data->images
$1 = std::vector of length 3, capacity 3 = {{image = 0xd000000000d, bound_images = std::unordered_set with 1 element = {[0] = 0xd000000000d}}, {image = 0xe000000000e,
    bound_images = std::unordered_set with 1 element = {[0] = 0xe000000000e}}, {image = 0xf000000000f, bound_images = std::unordered_set with 1 element = {
      [0] = 0xf000000000f}}}
```

API dump and AddressSanitizer bailout:
https://gist.github.com/Moggers/14d0f5cf9542ade502bd4d26883bdbdb
If a minimal reproduction is required, I can hack one together.

**Comment by mark-lunarg** [comment]
Reproduced easily.  Currently there is a check for this specifically that should spit out a warning, but it was AFTER the checks that crash.  I'll move it up so that the message is received before any crashes, and am looking to see if it is suitable to become a Real Live Error -- right now I don't see any VUs for it.
