### ISSUE TITLE
Unexpected validation errors regarding xChromaOffset and yChromaOffset

### ISSUE THREAD

**Issue by rg3igalia** [KhronosGroup/Vulkan-ValidationLayers#1971]
The Vulkan spec is a bit confusing regarding two valid usage requirements when using VkSamplerYcbcrConversionCreateInfo. On the one hand it says:

> xChromaOffset describes the sample location associated with downsampled chroma channels in the x dimension. **xChromaOffset has no effect for formats in which chroma channels are the same resolution as the luma channel**.

(Emphasis mine)

And the same for yChromaOffset. But, in the valid usage section below it mentions:

> If the potential format features of the sampler Y′CBCR conversion do not support VK_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT, xChromaOffset and yChromaOffset must not be VK_CHROMA_LOCATION_COSITED_EVEN

And the same for VK_CHROMA_LOCATION_MIDPOINT.

VK-GL-CTS tests using YcbCr conversions do not check the format feature to be available when the format is not chroma-subsampled in the X or Y axis, following the comment in the first paragraph because the offset is not needed in those cases and those fields should have no effect and values should not matter. However, the layers are interpreting the validation rule strictly without looking at the conversion format.

I think VK-GL-CTS is behaving correctly in this case and I will also file a spec bug for this to improve the validation rule wording.

**Comment by sfricke-samsung** [comment]
So I agree with this issue/fix, When I wrote these Validation I followed the VUs as stated. I am **assuming** that the x/yChromaOffsets can be ignored when the format is correct, but this really needs update in the VUID of the spec itself to say that the offsets can be anything depending on the format. The Validation Layers are doing the same assumption with other parts of the spec where parameters are "ignored" as well
