### ISSUE TITLE
Double update of requested descriptor count in StateTracker

### ISSUE THREAD

**Issue by citron0xa9** [KhronosGroup/Vulkan-ValidationLayers#1981]
When using core validation and best practice validation in my vulkan application, the requested descriptor count (tracked by `cvdescriptorset::AllocateDescriptorSetsData`) of a `vkAllocateDescriptorSets` call is calculated to be double of the actual requested count.
Concretely `CoreChecks::PreCallValidateAllocateDescriptorSets` calls `ValidationStateTracker::PreCallValidateAllocateDescriptorSets` which in turn calls `UpdateAllocateDescriptorSetsData` and increases the `required_descriptors_by_type` according to the descriptor set layout.
Afterwards `BestPractices::PreCallValidateAllocateDescriptorSets` also calls `ValidationStateTracker::PreCallValidateAllocateDescriptorSets` which results in the required descriptors to be increased once again. As a result `required_descriptors_by_type` contains twice the amount of required descriptors for a given type and the state of the descriptor pool is wrongly updated later on.

If someone could give a hint on how to fix that (remove one call, reset required_descriptors_by_type to 0 before update, ...) I would also try to create a PR.

**Comment by mark-lunarg** [comment]
After a quick look, I believe this is a scope issue.  No data should be shared between the StateTracker instantiations used by BestPractices and CoreChecks.  It was not intended that BP and CoreChecks should be run at the same time for performance reasons but it is supposed to work correctly.
