### ISSUE TITLE
Validation error during compaction contradicts the specs, VkAccelerationStructureCreateInfoKHR::maxGeometryCount.

### ISSUE THREAD

**Issue by PatrikTegelberg** [KhronosGroup/Vulkan-ValidationLayers#1982]
If compaction is enabled in the Nvidia ray tracing tutorial, https://nvpro-samples.github.io/vk_raytracing_tutorial_KHR/, a validation error occurs:
"The Vulkan spec states: maxGeometryCount must be greater than 0"
But the spec says:
"If compactedSize is not 0 then maxGeometryCount must be 0"
The compaction appears to work.
This validation error seems to contradict the specs.

**Comment by mark-lunarg** [comment]
@souravpNV, @jeffbolznv, this result seems to contradict the spec/stateless source code -- is it possible for y'all to have a quick look?

**Comment by souravpNV** [comment]
@PatrikTegelberg  : Do you know what is the error VUID?

I do see the right error VUID VUID-VkAccelerationStructureCreateInfoKHR-compactedSize-03490, but checking the src code briefly I didn't see any VUID that would correspond to the error mentioned.


KHR: VUID VUID-VkAccelerationStructureCreateInfoKHR-compactedSize-03490,
For NV:
    {"VUID-VkAccelerationStructureCreateInfoNV-compactedSize-02421", "If compactedSize is not 0 then both info.geometryCount and info.instanceCount must be 0", "1.2-extensions"},


I think the error is generated from PreCallValidateCreateAccelerationStructureKHR  when it calls validate_array
 if (countRequired && (count == 0)) {
            skip_call |= LogError(device, count_required_vuid, "%s: parameter %s must be greater than 0.", apiName,
                                  countName.get_name().c_str());
        }

but countRequired passed is false so this shall not happen, so probably will have to step through

**Comment by PatrikTegelberg** [comment]
Hi Souravp and Mark
The full validation error in the Nvidia tutorial (downloaded about a month ago) is:

ERROR: VUID-VkAccelerationStructureCreateInfoKHR-maxGeometryCount-arraylength
 --> Validation Error: [ VUID-VkAccelerationStructureCreateInfoKHR-maxGeometryCount-arraylength ] Object 0: handle = 0x16410bc2128, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xec7e9464 | vkCreateAccelerationStructureKHR: parameter pCreateInfo->maxGeometryCount must be greater than 0. The Vulkan spec states: maxGeometryCount must be greater than 0 (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkAccelerationStructureCreateInfoKHR-maxGeometryCount-arraylength)
 Object[0] - Type Device, Value 0000016410BC2128, Name "(null)"

Which does not look like the one you are getting.

The full error message in my application is:

VUID-VkAccelerationStructureCreateInfoKHR-maxGeometryCount-arraylength(ERROR / SPEC): msgNum: -327248796 - Validation Error: [ VUID-VkAccelerationStructureCreateInfoKHR-maxGeometryCount-arraylength ] Object 0: handle = 0x170663c5978, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xec7e9464 | vkCreateAccelerationStructureKHR: parameter pCreateInfo->maxGeometryCount must be greater than 0. The Vulkan spec states: maxGeometryCount must be greater than 0 (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkAccelerationStructureCreateInfoKHR-maxGeometryCount-arraylength)
    Objects: 1
        [0] 0x170663c5978, type: 3, name: NULL

I am using VK_LAYER_KHRONOS_validation and VulkanSDK\1.2.135.0

Thank you.

**Comment by souravpNV** [comment]
Thanks, Patrik, ok so this should be fixed in 1.2.2, I was checking this error message and it is not a valid VUID as per latest changes, I can see it in my local tracking sheet (about 3 months old), this particular code should be autogenerated and based on latest spec changes it should be fixed in next SDK, you can also try to the validation layers locally if you want the latest changes.

This is what I had in my tracking sheet.
VUID-VkAccelerationStructureCreateInfoKHR-maxGeometryCount-arraylength: 

maxGeometryCount   must be greater than 0   (https	//www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkAccelerationStructureCreateInfoKHR-maxGeometryCount-arraylength)
--

**Comment by PatrikTegelberg** [comment]
I don't know what " try to the validation layers locally" means, but I am OK waiting for 1.2.2.

Thank you for the answer.

**Comment by souravpNV** [comment]
Ah sorry for the confusion and the horrific bold font above.
> try to (*build)  the validation layers locally 
 I meant that if it is urgent you can build the updated validation dll's by using the top of the tree validation code.

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/BUILD.md

**Comment by mark-lunarg** [comment]
@PatrikTegelberg, you also have the option of pulling the Windows binaries from the Appveyor build artifacts, [here](https://ci.appveyor.com/project/Khronoswebmaster/vulkan-validationlayers/builds/33852215/job/mokt8lvwpa88dify/artifacts).  I realize that building this repo is loads of fun, but you might just want to get stuff done!

**Comment by mark-lunarg** [comment]
Guys, might this already be addressed in the 1.2.141.2 SDK release?

**Comment by mark-lunarg** [comment]
@PatrikTegelberg, gonna assume @souravpNV is correct and that this has been addressed in the [latest 1.2.148 SDK Release](https://vulkan.lunarg.com/sdk/home).  If you find this not to be the case, please comment here and I'll reopen this issue.  Thanks!
