### ISSUE TITLE
Failure to instrument shaders on vulkan 1.2

### ISSUE THREAD

**Issue by haasn** [KhronosGroup/Vulkan-ValidationLayers#1991]
Trying to compile even a basic shader on vulkan 1.2 with the best practices GPU-assisted validation feature enabled results in the following errors:

```
debug: Sub-allocating slice 0 + 4096 from slab with size 1048576
debug: vertex shader source:
debug: [  1] #version 410                               
debug: [  2] layout(location=0) in vec2 vertex_pos;     
debug: [  3] layout(location=1) in vec3 vertex_color;   
debug: [  4] layout(location=0) out vec3 frag_color;    
debug: [  5] void main() {                              
debug: [  6]     gl_Position = vec4(vertex_pos, 0, 1);  
debug: [  7]     frag_color = vertex_color;             
debug: [  8] }
debug: shaderc compile status 'success' (0 errors, 0 warnings)
debug: fragment shader source:
debug: [  1] #version 410                               
debug: [  2] layout(location=0) in vec3 frag_color;     
debug: [  3] layout(location=0) out vec4 out_color;     
debug: [  4] void main() {                              
debug: [  5]     out_color = vec4(frag_color, 1.0);     
debug: [  6] }
debug: shaderc compile status 'success' (0 errors, 0 warnings)
error: vk Validation Error: [ UNASSIGNED-GPU-Assisted Validation Error.  ] Object 0: handle = 0x55b0703e7ae0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xf697542c | Detail: (Failure to instrument shader.  Proceeding with non-instrumented shader.)
error:     using VkDevice: anon (0x55b0703e7ae0)
error: vk Validation Error: [ UNASSIGNED-GPU-Assisted Validation Error.  ] Object 0: handle = 0x55b0703e7ae0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xf697542c | Detail: (Failure to instrument shader.  Proceeding with non-instrumented shader.)
error:     using VkDevice: anon (0x55b0703e7ae0)
debug: Pass statistics: size 3392, SPIR-V: vert 756 frag 432 comp 0
```

It seems to me as though the source of this issue is the [hard-coded SPIR-V version in `layers/gpu_validation.cpp`](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/gpu_validation.cpp#L1149).

Simply changing this constant to `SPV_ENV_VULKAN_1_2` makes it work for me. I suspect that this layer should either be choosing the SPIR-V version automatically based on the target environment, or based on the SPIR-V version of the shader being instrumented.

While researching this bug I noticed that a number of other places in the code have hard-coded SPIR-V versions, or lack support for vulkan 1.2, leading to [similar such bugs in the past](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1520/commits/cc7e5431fcc3d9ea2ac393c4195df5f404e4e8dc).

I think the proper solution here might be to move all of these 'choose SPIR-V version'-type branches to a common helper function that can be reused everywhere it's needed.

**Comment by Tony-LunarG** [comment]
Fixed with #1992
