### ISSUE TITLE
Add Protected Memory Validation Support

### ISSUE THREAD

**Issue by sfricke-samsung** [KhronosGroup/Vulkan-ValidationLayers#1996]
Currently left to implement:
- VUID-vkCmdDispatch-commandBuffer-02713
- VUID-vkCmdDraw-commandBuffer-02713
- VUID-vkCmdDrawIndexed-commandBuffer-02713
- VUID-vkCmdTraceRaysKHR-commandBuffer-02713
- VUID-vkCmdTraceRaysNV-commandBuffer-02713

----

Added in PR #2269:
- VUID-VkMemoryAllocateInfo-memoryTypeIndex-01872
- VUID-vkCmdDispatch-commandBuffer-02712
- VUID-vkCmdDraw-commandBuffer-02712
- VUID-vkCmdDrawIndexed-commandBuffer-02712
- VUID-vkCmdTraceRaysKHR-commandBuffer-02712
- VUID-vkCmdTraceRaysNV-commandBuffer-02712
- VUID-vkCmdDispatch-commandBuffer-02707
- VUID-vkCmdDispatchBase-commandBuffer-02707
- VUID-vkCmdDispatchIndirect-commandBuffer-02707
- VUID-vkCmdDraw-commandBuffer-02707
- VUID-vkCmdDrawIndexed-commandBuffer-02707
- VUID-vkCmdDrawIndexedIndirect-commandBuffer-02707
- VUID-vkCmdDrawIndexedIndirectCount-commandBuffer-02707
- VUID-vkCmdDrawIndirect-commandBuffer-02707
- VUID-vkCmdDrawIndirectCount-commandBuffer-02707
- VUID-vkCmdDrawIndirectByteCountEXT-commandBuffer-02707
- VUID-vkCmdDrawMeshTasksIndirectCountNV-commandBuffer-02707
- VUID-vkCmdDrawMeshTasksIndirectNV-commandBuffer-02707
- VUID-vkCmdExecuteGeneratedCommandsNV-commandBuffer-02707
- VUID-vkCmdDrawMeshTasksNV-commandBuffer-02707
- VUID-vkCmdTraceRaysIndirectKHR-commandBuffer-02707
- VUID-vkCmdTraceRaysKHR-commandBuffer-02707
- VUID-vkCmdTraceRaysNV-commandBuffer-02707

Added in PR #2134:
- VUID-VkProtectedSubmitInfo-protectedSubmit-01816
- VUID-VkProtectedSubmitInfo-protectedSubmit-01817
- VUID-VkSubmitInfo-pNext-04120
- VUID-VkSubmitInfo-pNext-04148

Added in PR #2090:
- VUID-vkCmdClearAttachments-commandBuffer-02504
- VUID-vkCmdClearAttachments-commandBuffer-02505

Added in PR #2071:
- VUID-vkCmdBlitImage-commandBuffer-01834
- VUID-vkCmdBlitImage-commandBuffer-01835
- VUID-vkCmdBlitImage-commandBuffer-01836
- VUID-vkCmdClearColorImage-commandBuffer-01805
- VUID-vkCmdClearColorImage-commandBuffer-01806
- VUID-vkCmdClearDepthStencilImage-commandBuffer-01807
- VUID-vkCmdClearDepthStencilImage-commandBuffer-01808
- VUID-vkCmdCopyBuffer-commandBuffer-01822
- VUID-vkCmdCopyBuffer-commandBuffer-01823
- VUID-vkCmdCopyBuffer-commandBuffer-01824
- VUID-vkCmdCopyBufferToImage-commandBuffer-01828
- VUID-vkCmdCopyBufferToImage-commandBuffer-01829
- VUID-vkCmdCopyBufferToImage-commandBuffer-01830
- VUID-vkCmdCopyImage-commandBuffer-01825
- VUID-vkCmdCopyImage-commandBuffer-01826
- VUID-vkCmdCopyImage-commandBuffer-01827
- VUID-vkCmdCopyImageToBuffer-commandBuffer-01831
- VUID-vkCmdCopyImageToBuffer-commandBuffer-01832
- VUID-vkCmdCopyImageToBuffer-commandBuffer-01833
- VUID-vkCmdExecuteCommands-commandBuffer-01820
- VUID-vkCmdExecuteCommands-commandBuffer-01821
- VUID-vkCmdFillBuffer-commandBuffer-01811
- VUID-vkCmdFillBuffer-commandBuffer-01812
- VUID-vkCmdResolveImage-commandBuffer-01837
- VUID-vkCmdResolveImage-commandBuffer-01838
- VUID-vkCmdResolveImage-commandBuffer-01839
- VUID-vkCmdUpdateBuffer-commandBuffer-01813
- VUID-vkCmdUpdateBuffer-commandBuffer-01814

Added in PR #2070:
- VUID-vkCmdBeginQuery-commandBuffer-01885
- VUID-vkCmdBeginQueryIndexedEXT-commandBuffer-01885
- VUID-vkCmdEndQuery-commandBuffer-01886
- VUID-vkCmdEndQueryIndexedEXT-commandBuffer-02344

Added in PR #2010:
- VUID-VkBufferCreateInfo-flags-01887
- VUID-VkCommandPoolCreateInfo-flags-02860
- VUID-VkImageCreateInfo-flags-01890
- VUID-VkBufferCreateInfo-None-01888
- VUID-VkImageCreateInfo-None-01891
- VUID-vkBindBufferMemory-None-01898
- VUID-vkBindBufferMemory-None-01899
- VUID-vkBindImageMemory-None-01901
- VUID-vkBindImageMemory-None-01902

Added in PR #1994: 
- VUID-vkCmdDrawIndirect-commandBuffer-02711
- VUID-vkCmdDispatchIndirect-commandBuffer-02711
- VUID-vkCmdDrawIndexedIndirect-commandBuffer-02711
- VUID-vkCmdDrawIndirectCount-commandBuffer-02711
- VUID-vkCmdDrawIndexedIndirectCount-commandBuffer-02711
- VUID-vkCmdTraceRaysIndirectKHR-commandBuffer-02711
- VUID-vkCmdDrawMeshTasksIndirectCountNV-commandBuffer-02711
- VUID-vkCmdDrawMeshTasksIndirectNV-commandBuffer-02711

**Comment by sfricke-samsung** [comment]
Update: Only VUIDs left are the `02712`, `02713` and `02707`

All of these are draw/dispatch command VUs that are based on checking the pipeline doesn't write to any resource with mixing protected bits set.

**Comment by ncesario-lunarg** [comment]
Added remaining VUIDs to #2746.
