### ISSUE TITLE
vkGetSemaphoreCounterValue appears to crash on access violation

### ISSUE THREAD

**Issue by fheavr** [KhronosGroup/Vulkan-ValidationLayers#1997]
any and all uses of vkGetSemaphoreCounterValue appear to crash with an access violation. Debug layer is not reporting anything prior to crash. The device is clearly valid, since the semaphore creation works (amongst all the other things using it). I can't come up with anything else locally that could be the culprit beyond maybe improperly loading the timeline semaphore extension, but that appears to work as well.

Vulkan version 1.2.141.2

```
// ensured timeline semaphores are supported in hardware,
VkPhysicalDeviceVulkan12Features features = {};
features.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_FEATURES;
features.timelineSemaphore = true;

deviceInfo.pNext = &features;

vr = vkCreateDevice(m_hardware, &deviceInfo, nullptr, &m_device);
VV_ASSERT(vr == VK_SUCCESS);

...

// create the timeline semaphore, appears to work fine
VkSemaphoreTypeCreateInfo timelineCreateInfo;
timelineCreateInfo.sType = VK_STRUCTURE_TYPE_SEMAPHORE_TYPE_CREATE_INFO;
timelineCreateInfo.pNext = NULL;
timelineCreateInfo.semaphoreType = VK_SEMAPHORE_TYPE_TIMELINE;
timelineCreateInfo.initialValue = 0;

VkSemaphoreCreateInfo semInfo;
semInfo.sType = VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO;
semInfo.pNext = &timelineCreateInfo;
semInfo.flags = 0x0;

vr = vkCreateSemaphore(m_device, &semInfo, nullptr, &m_queueSemaphore);
VV_ASSERT(vr == VK_SUCCESS);

...

VkPipelineStageFlags pipe_stage_flags = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;

// this resolves to 1, as m_endOfWorkValue is initialized at 0, same as the semaphore
uint64_t signalValue = ++m_endOfWorkValue; 

VkTimelineSemaphoreSubmitInfo timelineInfo;
timelineInfo.sType = VK_STRUCTURE_TYPE_TIMELINE_SEMAPHORE_SUBMIT_INFO;
timelineInfo.pNext = NULL;
timelineInfo.waitSemaphoreValueCount = 0;
timelineInfo.pWaitSemaphoreValues = nullptr;
timelineInfo.signalSemaphoreValueCount = 1;
timelineInfo.pSignalSemaphoreValues = &signalValue;

VkSubmitInfo info = {};
info.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
info.pNext = &timelineInfo;
info.commandBufferCount = 1;
info.pCommandBuffers = &cmdBuffer;
info.waitSemaphoreCount = waitSemaphoreCount;
info.pWaitSemaphores = (waitSemaphoreCount > 0) ? waitSemaphores : nullptr;
info.pWaitDstStageMask = &pipe_stage_flags;
info.signalSemaphoreCount = 1;
info.pSignalSemaphores = &m_queueSemaphore;

// inserted check here to validate the semaphore and hard crash
// I wanted to validate the semaphore due to QueueSubmit throwing validation layer errors about 
// " value exceeds limit regarding current semaphore VkSemaphore payload"
uint64_t value;
VkResult vr2 = vkGetSemaphoreCounterValue(m_device, m_queueSemaphore, &value);

VkResult vr = vkQueueSubmit(m_queue, 1, &info, VK_NULL_HANDLE);
```

**Comment by fheavr** [comment]
vkSignalSemaphore seems to have similar behavior. Disabling the validation layer results in the functions working as expected.

**Comment by kikijiki** [comment]
I can confirm, having the same problem.

**Comment by kikijiki** [comment]
I'm not familiar with the code but in `chassis.cpp` -> `GetDeviceProcAddr` if I skip the check `if (!ApiParentExtensionEnabled(funcName, &layer_data->device_extensions))` it seems not to crash anymore.

**Comment by mark-lunarg** [comment]
@kikijiki, @fheavr, been doing some testing here, and I can replicate this behavior if I end up with a device context < version 1.2.  Can you share what APIVersion you are requesting and what you get when your physical device is queried?  If it is less than 1.2, you'd need to use the extension version of this command.  This all seems to work using a 1.2 context.

**Comment by fheavr** [comment]
Yup, I was requesting a vulkan 1_1 in my VkApplicationInfo. Updating that version number resolved the problem for me.

**Comment by kikijiki** [comment]
Oh crap you're right, I updated the version I check against before creating the device but not the one that I actually pass in the struct /facepalm.
Sorry for the trouble!

**Comment by mark-lunarg** [comment]
No trouble at all.  Thanks for your patience.
