### ISSUE TITLE
Need stagemask validation for subpass' self dependency.

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#2]
**Issue by [ratchetfreak](https://github.com/ratchetfreak) (MIGRATED)**
_Saturday Jul 02, 2016 at 13:13 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/723_

----

https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/tests/layer_validation_tests.cpp#L3135

This test (RenderPassSubpassZeroTransitionsApplied) violates the following sentence of the spec:

> Self-dependencies must only include pipeline stage bits that are graphics stages.

ALL_COMMANDS is not a graphics stage (or at least includes more than just graphics stages). Not to mention the created dependency includes all stages on both sides of the dependency which violates:

> Self-dependencies must not have any earlier pipeline stages depend on any later pipeline stages. More precisely, this means that whatever is the last pipeline stage in srcStageMask must be no later than whatever is the first pipeline stage in dstStageMask (the latest source stage can be equal to the earliest destination stage).

This would also mean that ALL_GRAPHICS is not allowed because there is no way to make a sensible dependency with it.

Proposals for failing tests, 
1. using a non-graphics stage in the masks like transfer or compute 
2. using srcStageMask = Fragment and dst = Vertex (violating the order constraint)

**Comment by karl-lunarg** [comment]
<a href="https://github.com/chrisforbes"><img src="https://avatars1.githubusercontent.com/u/128877?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Saturday Jul 02, 2016 at 20:35 GMT_

----

Yes, this test is subtly wrong. Sounds like a good idea.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/chrisforbes"><img src="https://avatars1.githubusercontent.com/u/128877?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Thursday Jul 07, 2016 at 21:08 GMT_

----

Issue in RenderPassSubpassZeroTransitionsApplied now resolved; validation work to catch this is not yet done.

**Comment by krOoze** [comment]
I started spec Issue https://github.com/KhronosGroup/Vulkan-Docs/issues/1020 that should be relevant to this.

**Comment by mark-lunarg** [comment]
@krOoze, do you happen to know if this has been straightened out in the layers?

**Comment by krOoze** [comment]
@mark-lunarg Currently, the `ALL_COMMANDS` fails, but `ALL_GRAPHICS` passes. Plus spec still seems to be bit ambiguous about it.

**Comment by mark-lunarg** [comment]
This seems pretty close to my interpretation of what we should be doing -- is the remaining point that validation should not be using ALL_GRAPHICS, but instead be splitting it up into the individual stages and checking for the first/last dependency?

**Comment by krOoze** [comment]
TBH, we are doing too much interpreting. The spec should just say exactly. If it is not clear in spec, we must assume _some_ driver handles it wrong (resp. differently from us).

IDK, even if we ignore the spec, `ALL_GRAPHICS` smells bit of a code rot in a self-dependency. How should one read it? It sorta kinda makes sense if it is on both sides, as it means "allow me to do everything". What it means if it is only on one side, in the light of [VUID-VkSubpassDependency-srcSubpass-00867](https://www.khronos.org/registry/vulkan/specs/1.2/html/vkspec.html#VUID-VkSubpassDependency-srcSubpass-00867)? When it is used, how should the "subset" in [VUID-vkCmdPipelineBarrier-pDependencies-02285](https://www.khronos.org/registry/vulkan/specs/1.2/html/vkspec.html#VUID-vkCmdPipelineBarrier-pDependencies-02285) be interpreted?

And if `ALL_GRAPHICS` is allowed, then I don't see why not allow `ALL_COMMANDS`.

**Comment by mark-lunarg** [comment]
Both 00867 and 02285 are covered in the layers, sounds like there is still some work to be done here, but nothing which is straightforward.
