### ISSUE TITLE
Descriptor type validation doesn't handle OpGroupDecorate

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#20]
**Issue by [phaulos](https://github.com/phaulos) (MIGRATED)**
_Thursday Mar 09, 2017 at 22:22 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1549_

----

`dEQP-VK.spirv_assembly.instruction.compute.decoration_group.all` is failing with:

```
ERROR: Type mismatch on descriptor slot 0.0 (used as type `ptr to uniform struct of (oddtype)`) but descriptor of type VK_DESCRIPTOR_TYPE_STORAGE_BUFFER (code 0x0000000d from SC at Unknown:2631)
...
```

Looking at the SPIR-V `BufferBlock` decoration is applied to `0.0` through `OpGroupDecorate`. This is not something glslang does so it might be that validation simply doesn't handle it.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/chrisforbes"><img src="https://avatars1.githubusercontent.com/u/128877?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Friday Mar 10, 2017 at 03:58 GMT_

----

Indeed, SC has no idea about group decorations at all. This is going to take a bit of work.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/chrisforbes"><img src="https://avatars1.githubusercontent.com/u/128877?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Friday Mar 24, 2017 at 04:53 GMT_

----

Working out with spirv-tools side how best to deal with this.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/gwihlidal"><img src="https://avatars1.githubusercontent.com/u/564042?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gwihlidal](https://github.com/gwihlidal) (MIGRATED)**
_Wednesday May 17, 2017 at 00:10 GMT_

----

Any update on this? We're hitting this error in many of our shaders.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/mark-lunarg"><img src="https://avatars2.githubusercontent.com/u/7252958?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mark-lunarg](https://github.com/mark-lunarg) (MIGRATED)**
_Thursday Mar 01, 2018 at 21:40 GMT_

----

@chrisforbes, any update? Still applicable?

**Comment by chrisforbes** [comment]
Yes, still needed.
