### ISSUE TITLE
VUID 02690 is not covering case of non-combined image samplers

### ISSUE THREAD

**Issue by sfricke-samsung** [KhronosGroup/Vulkan-ValidationLayers#2012]
I added my extra tests in #2011 I wrote for this VU and see it is failing one test from the changes ported in #1769 (cc @jeremyk-lunarg)

VUID 02690

> If a VkImageView is sampled with VK_FILTER_LINEAR as a result of this command, then the image view’s format features must contain VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT

The issue it the current layers assume that descriptor is a `VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER` but I wrote a test case where there is a `VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE` and `VK_DESCRIPTOR_TYPE_SAMPLER` being used.

To my knowledge as expressed in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/135#issuecomment-576282999, is you actually need to parse out the SPIR-V as you need to know the sampler that the image is applied too in the case of not using `VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER`

**Comment by Tony-LunarG** [comment]
This is also the case for VUID-VkSamplerCustomBorderColorCreateInfoEXT-format-04015 and likely the same parsing code could be used for both.  The task is on our list but hasn't risen high enough to get started.

**Comment by sfricke-samsung** [comment]
That is fair, but I guess I wanted to make an issue because from the naked-eye view of the summary script/table, it looks like this validation is "done" but it is only partially done

**Comment by mark-lunarg** [comment]
The `*-None-02690` VUIDs have been renamed `*-magFilter-04553`.

**Comment by sfricke-samsung** [comment]
@locke-lunarg actually fixed in #2182 so :tada: 

My extra tests are re-uploaded to #2442
