### ISSUE TITLE
no error/warning for invalid stride in GetQueryPoolResults

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-ValidationLayers#2029]
According to spec:

`If more than one query is retrieved and stride is not at least as large as the size of the array of values corresponding to a single query, the values written to memory are undefined.`

This seems like something that should have some sort of message. For example:
* a pipeline statistics query has completed with 2 bits set in `pipelineStatistics`
* the query pool has 2 result sets available
* `VK_QUERY_RESULT_64_BIT` is set
* GetQueryPoolResults is called with stride = `sizeof(uint64_t)`

In this case, I'd expect at least a warning since each query will return a 2x64 array, meaning the stride must be `2 * sizeof(uint64_t)`, but there is no message.

**Comment by mark-lunarg** [comment]
#1567 is related.
