### ISSUE TITLE
centos 7 compiling error: vulkan/layers/generated/chassis.cpp

### ISSUE THREAD

**Issue by joelelrocker** [KhronosGroup/Vulkan-ValidationLayers#2032]
Hi,
I'm attempting on building this into a CentOS 7 docker container and receiving this error: 

/opt/vulkan/layers/generated/chassis.cpp: In function 'VkResult vulkan_layer_chassis::CreateGraphicsPipelines(VkDevice, VkPipelineCache, uint32_t, const VkGraphicsPipelineCreateInfo*, const VkAllocationCallbacks*, VkPipeline_T**)':
/opt/vulkan/layers/generated/chassis.cpp:795:75: internal compiler error: in gimplify_init_constructor, at gimplify.c:4271
     create_graphics_pipeline_api_state cgpl_state[LayerObjectTypeMaxEnum]{}

Have you seen this before? It appears on multiple version, I'm currently checking out sdk-1.2.141. 

I'm happy to share my dockerfile if that helps

**Comment by mark-lunarg** [comment]
@joelelrocker, several versions of GCC are supported, as well Clang.  In addition, we run interna/external builds on Windows and Android, but have not seen this error or (AFAICT) any related warnings.  If you can come up with a simple workaround that makes those compilers happy, we'll gladly take a PR!

**Comment by joelelrocker** [comment]
Thanks Mark, I'll keep digging for a workaround and if I get anywhere I'll share :)

**Comment by mark-lunarg** [comment]
@joelelrocker, I'm going to close this for now, but you can always comment on this issue or open a new one (or hopefully, a new PR!).  Thanks and good luck...
