### ISSUE TITLE
VK_EXT_debug_utils is an instance extension and should not be used as a device extension

### ISSUE THREAD

**Issue by sugoi1** [KhronosGroup/Vulkan-ValidationLayers#2049]
According to the spec (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_debug_utils.html), VK_EXT_debug_utils is an instance extension.

If we look at the source code for the Vulkan Layers, like here:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/45c73d999ed8cc46f62754649cd78c3a917575c5/scripts/layer_chassis_dispatch_generator.py#L978
the Vulkan Layers attempt to call VK_EXT_debug_utils commands using the device_dispatch_table (list of device function pointers) instead of using the instance_dispatch_table (list of instance function pointers). Every function defined within VK_EXT_debug_utils should be part of instance_dispatch_table and not device_dispatch_table.

Regarding extensions, according to the Vulkan spec, vkGetInstanceProcAddr can return "enabled instance extension commands for instance" or "available device extension commands for instance", but vkGetDeviceProcAddr can only return "enabled extension device-level commands".

**Comment by mark-lunarg** [comment]
The `VK_EXT_debug_utils `extension is an instance extension, unfortunately, it is one of those instance extensions that also contains device-level commands:

> Device-Level Command
> Any command that is dispatched from a logical device, or from a child object of a logical device

As you can see, the debug-utils APIs in the device dispatch table are indeed dispatched at the device-level, either through a `VkDevice `object, a `VkQueue `object.  or a `VkCommandBuffer `object.  So it is expected that the device-level function pointers would be retrieved by either `GetInstanceProcAddr `or `GetDeviceProcAddr`.

**Comment by sugoi1** [comment]
Cool, good to know! I question though:
The device should only expose these function pointers if the instance exposes VK_EXT_debug_utils, right?
I didn't see an active check for that, but I may have missed it.

**Comment by mark-lunarg** [comment]
Yeah, that check is part of `GetDeviceProcAddr() `-- see `ApiParentExtensionEnabled()` in `vk_dispatch_table_helper.h `and `chassis.cpp`.

**Comment by sugoi1** [comment]
Great, I'll close this issue. Thanks for all the info!
