### ISSUE TITLE
Missing validation unit on `vkGetBufferMemoryRequirements`

### ISSUE THREAD

**Issue by haasn** [KhronosGroup/Vulkan-ValidationLayers#2050]
These validation messages are a bit special because they're not listed under any "Valid Usage" section, but instead referenced as part of the [text describing VkMemoryRequirements](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VkMemoryRequirements)

> The implementation guarantees certain properties about the memory requirements returned by vkGetBufferMemoryRequirements2, vkGetImageMemoryRequirements2, vkGetBufferMemoryRequirements and vkGetImageMemoryRequirements:
> ...

In particular, I noticed that the very first line, "The memoryTypeBits member always contains at least one bit set.", is not validated. I ran into an ICD (AMDVLK) which violates this on some types of VkBuffers - that is, it returns `memoryTypeBits = 0x0`.

I would expect the layers to catch this.

**Comment by jeffbolznv** [comment]
In general, validation is only supposed to check for application bugs, not implementation bugs. The conformance tests should check for implementation bugs. I think this is covered by the tests in https://github.com/KhronosGroup/VK-GL-CTS/blob/master/external/vulkancts/modules/vulkan/memory/vktMemoryRequirementsTests.cpp, but I'm not very familiar with those particular tests.

**Comment by mark-lunarg** [comment]
@haasn -- I would interpret this as saying that these things are guaranteed, and as such you can assume them to be true.  The validation layers do not validate anything returned by the driver -- this should be ideally be covered by Vulkan CTS, and would be a driver bug.

**Comment by haasn** [comment]
Oh, I see. I thought the layers were supposed to catch both. Alright, I guess that makes this a limitation in the CTS for failing to catch this particular reproduction case.

**Comment by mark-lunarg** [comment]
Thanks @jeffbolznv.  Good luck @haasn...

**Comment by haasn** [comment]
(Just for the record, this is the reproducing VkBuffer:)

```c
VkBuffer buffer = VK_NULL_HANDLE;
VkMemoryRequirement reqs = {0};

VkExternalMemoryBufferCreateInfoKHR ext_buf_info = {
    .sType = VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO_KHR,
    .handleTypes = VK_EXTERNAL_MEMORY_HANDLE_TYPE_HOST_ALLOCATION_BIT_EXT,
};

VkBufferCreateInfo binfo = {
    .sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,
    .pNext = &ext_buf_info,
    .size = 2097152,
    .usage = VK_BUFFER_USAGE_TRANSFER_SRC_BIT |
             VK_BUFFER_USAGE_TRANSFER_DST_BIT
    .sharingMode = VK_SHARING_MODE_CONCURRENT,
    .queueFamilyIndexCount = 3,
    .pQueueFamilyIndices = &(uint32[]){ 0, 1, 2},
};

vkCreateBuffer(vk->dev, &binfo, NULL, &buffer);
vkGetBufferMemoryRequirements(vk->dev, buffer, &reqs);
```
