### ISSUE TITLE
Difficulties Enabling Best Practices + Potential Bug in Config File Parsing

### ISSUE THREAD

**Issue by samwalls-arm** [KhronosGroup/Vulkan-ValidationLayers#2057]
Hey there,

I've been trying to enable best practices on Linux using `vk_layer_settings.txt` and appropriate environment variables, but something doesn't seem to line up. Feel free to shoot this down if there's something obvious I'm doing wrong.

Here's `vk_layer_settings.txt`:
```
# Basic configuration file for enabling best practices validation warnings

khronos_validation.debug_action = VK_DBG_LAYER_ACTION_LOG_MSG;

# have also tried just "perf" on its own here...
khronos_validation.report_flags = info, warn, perf, error;

khronos_validation.log_filename = stdout;

khronos_validation.enables = VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT, VALIDATION_CHECK_ENABLE_VENDOR_SPECIFIC_ARM;
```

`VK_INSTANCE_LAYERS` is set to `VK_LAYER_LUNARG_api_dump:VK_LAYER_KHRONOS_validation`. I'm also using the latest build of Vulkan-ValidationLayers' master branch as the location of my `VK_LAYER_PATH` environment variable. Additionally, `VK_LAYER_SETTINGS_PATH` points to the directory that the config file is in, and I can confirm that it finds the config file, by observing the output of vulkan applications I run, when I set/unset the variable.

What I'd expect to find:
- best practices enabled
- Arm best practices enabled
- warning output + performance warning output enabled

What I find:
- best practices enabled
- Arm best practices are _disabled_
- warning output is enabled, however performance warning output is _disabled_ (I tried adding a `LogPerformanceWarning(...)` statement unconditionally on some API hook, but it does not get emitted). I also tried just having `perf` on its own in the `report_flags` field - same behaviour except there's no error output at all.

I think there may be an issue with the parsing of the file, as I tried changing the value of `khronos_validation.enables`, swapping the order of the two flags there. It might be only enabling the first flag(?).

In any case, if I don't use the config file, and instead add `VK_LAYER_ENABLES=VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT:VALIDATION_CHECK_ENABLE_VENDOR_SPECIFIC_ARM` to my environment, it has the effect I want. While this is functional, I'm not sure what's wrong with the config file, have I missed something [in the documentation](https://vulkan.lunarg.com/doc/view/1.2.131.2/windows/layer_configuration.html)?

Finally, is there an environment variable, similar to `VK_LAYER_ENABLES`, which corresponds to the `report_flags` field, at the moment? I still can't enable performance warning output.

For example, I've tested out a small change to the validation layer hooks. I have:
```cpp
    std::cout << "scanning index buffer with Arm check..." << std::endl;

    LogPerformanceWarning(device, "test-uuid", "test message");
```
And, I get the print output, but not the performance warning.

If anyone has any insight into why this is happening, and/or how to enable performance warnings, I would be very grateful!

Thanks,
Sam Walls

**Comment by samwalls-arm** [comment]
After a lot of digging around, I've found that the semicolons in the config file were causing issues. I've removed them, and I'm seeing more of the expected config values internally. However, still no performance warning output! I'll keep looking into this.

**Comment by mark-lunarg** [comment]
@samwalls-arm, tried this with some of Sascha's examples (texturearray.exe, in particular) and it seemed to work as expected:

Are you using the layer validation tests or your own application?

...snip...

> UNASSIGNED-BestPractices-vkAllocateMemory-small-allocation(WARN / PERF): msgNum: -602362517 - Validation Performance Warning: [ UNASSIGNED-BestPractices-vkAllocateMemory-small-allocation ] Object 0: handle = 0x24de4d1c268, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xdc18ad6b | vkAllocateMemory(): Allocating a VkDeviceMemory of size 256. This is a very small allocation (current threshold is 262144 bytes). You should make large allocations and sub-allocate from one large VkDeviceMemory.
>     Objects: 1
>         [0] 0x24de4d1c268, type: 3, name: NULL
> UNASSIGNED-BestPractices-vkAllocateMemory-small-allocation(WARN / PERF): msgNum: -602362517 - Validation Performance Warning: [ UNASSIGNED-BestPractices-vkAllocateMemory-small-allocation ] Object 0: handle = 0x24de4d1c268, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xdc18ad6b | vkAllocateMemory(): Allocating a VkDeviceMemory of size 256. This is a very small allocation (current threshold is 262144 bytes). You should make large allocations and sub-allocate from one large VkDeviceMemory.
>     Objects: 1
>         [0] 0x24de4d1c268, type: 3, name: NULL

...

Here's the good part of my settings file:

> khronos_validation.debug_action = VK_DBG_LAYER_ACTION_LOG_MSG
khronos_validation.report_flags = info, perf
khronos_validation.log_filename = stdout
khronos_validation.enables=VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT, VALIDATION_CHECK_ENABLE_VENDOR_SPECIFIC_ARM

**Comment by samwalls-arm** [comment]
Hey @mark-lunarg, I'm testing this against [vulkan samples](https://github.com/KhronosGroup/Vulkan-Samples).

As described in the last message, removing the semicolons in the settings file seemed to make some settings come through in the code (I've added log lines all over the place in VL to try and understand what's happening). However, there still seem to be problems with using the settings file.

The only way I can enable best practices + arm best practices is by using the `VK_LAYER_ENABLES` environment variable. Without the environment variable, and copying the line directly from your settings there, best practices are enabled, however Arm best practices are still not enabled for me. Similarly, I am getting info + warning messages, but nothing for performance warnings.

I haven't had the time to look into this more deeply. However, looking at the logging output, it seems like almost all the logic agrees there should be a performance warning, however something's blocking it from being emitted.

**Comment by mark-lunarg** [comment]
@samwalls-arm, settings file requires all commas, sorry for the trouble there.  Since this seems to work on Windows, I tried it on Linux and still see it working, but did notice that at least some of the settings are intolerant to having a space after the comma.  We're in the midst of refactoring the setting/parsing stuff with the intention of making it a bit more friendly towards separators. 

I plan to keep looking but can you try those settings lines without any spaces and see if it makes a difference?

**Comment by samwalls-arm** [comment]
@mark-lunarg removing all the spaces from the config file, I find that it picks up on the Arm best practices enablement flag. Thanks for that!

Looking at the logging output I mentioned, it looks like performance warning enablement is also picked up from the config file correctly, however the layer still doesn't seem to be _outputting_ performance warnings.

I've narrowed the problem down to `debug_log_msg` in `layers/vk_layer_logging.h` - starting [roughly here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/vk_layer_logging.h#L429).

Here's some of the log placements I made in the function so one can get an idea what's going on:
```cpp
    std::ostringstream oss;
    std::cout << "attempting to log warning '" << text_vuid << "' with msg flags: " << msg_flags << std::endl;
    if (msg_flags & kErrorBit) {
        oss << "Validation Error: ";
    } else if (msg_flags & kWarningBit) {
        oss << "Validation Warning: ";
    } else if (msg_flags & kPerformanceWarningBit) {
        std::cout << "selecting performance warning message type..." << std::endl;
        oss << "Validation Performance Warning: ";
    } else if (msg_flags & kInformationBit) {
        oss << "Validation Information: ";
    } else if (msg_flags & kDebugBit) {
        oss << "DEBUG: ";
    }
    if (text_vuid != nullptr) {
        oss << "[ " << text_vuid << " ] ";
    }
```

There's a section at the end of the function which composites the warning message + all the string formatting, then decides which debug callback to use:
```cpp
    oss << "| MessageID = 0x" << std::hex << location << " | " << message;
    std::string composite = oss.str();

    const auto callback_list = &debug_data->debug_callback_list;
    // We only output to default callbacks if there are no non-default callbacks
    bool use_default_callbacks = true;
    for (auto current_callback : *callback_list) {
        use_default_callbacks &= current_callback.IsDefault();
    }

    for (auto current_callback : *callback_list) {
        // Skip callback if it's a default callback and there are non-default callbacks present
        if (current_callback.IsDefault() && !use_default_callbacks) continue;

        // VK_EXT_debug_utils callback
        if (current_callback.IsUtils() && (current_callback.debug_utils_msg_flags & severity) &&
            (current_callback.debug_utils_msg_type & types)) {
            callback_data.pMessage = composite.c_str();
            std::cout << "outputting message '" << callback_data.pMessage << " with type " << types << std::endl;
            if (current_callback.debug_utils_callback_function_ptr(static_cast<VkDebugUtilsMessageSeverityFlagBitsEXT>(severity),
                                                                   types, &callback_data, current_callback.pUserData)) {
                bail = true;
            }
        } else if (!current_callback.IsUtils() && (current_callback.debug_report_msg_flags & msg_flags)) {
            // VK_EXT_debug_report callback (deprecated)
            std::cout << "outputting message '" << callback_data.pMessage << " with type " << types << std::endl;
            if (current_callback.debug_report_callback_function_ptr(
                    msg_flags, convertCoreObjectToDebugReportObject(object_name_info[0].objectType),
                    object_name_info[0].objectHandle, location, 0, layer_prefix, composite.c_str(), current_callback.pUserData)) {
                bail = true;
            }
        }
    }
    return bail;
```

Neither of the two log lines ("outputting message"...) appear to be reached.

Here's an example of the whole log output when I run compute_nbody from vulkan samples (no performance warnings are output).
```
scanning index buffer with Arm check...
validation layers code attempting to emit the following warning:
UNASSIGNED-BestPractices-vkCmdDrawIndexed-sparse-index-buffer | %s The indices which were specified for the draw call only utilise approximately %.02f%% of index buffer value range. Arm Mali architectures before G71 do not have IDVS (Index-Driven Vertex Shading), meaning all vertices corresponding to indices between the minimum and maximum would be loaded, and possibly shaded, whether or not they are used.
message severity matches performance warning: 1
message type matches performance warning: 1
report data active type flags: 7
not ignoring warning...
attempting to log warning 'UNASSIGNED-BestPractices-vkCmdDrawIndexed-sparse-index-buffer' with msg flags: 4
selecting performance warning message type...
```

Whereas, for a normal warning type (not a performance warning), I'm seeing the following (see the warning output at the end):
```
attempting to log warning 'UNASSIGNED-BestPractices-pipeline-stage-flags' with msg flags: 2
outputting message 'Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x5654f5e18800, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
 with type 2
[warning] 1218486124 - UNASSIGNED-BestPractices-pipeline-stage-flags: Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x5654f5e18800, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
```
All the preceding logic agrees that it's a performance warning, however, something about the callback seems to disagree.

I can't allocate much more time to this right now, I might find some spare at some point over the week, I hope this might shed light on what's going on, or what I'm doing wrong.

**Comment by mark-lunarg** [comment]
@samwalls-arm, looks like there might be an issue with using the default callbacks and the perf-warning output level.  I'll run this to ground today.  Thanks for your patience!

**Comment by mark-lunarg** [comment]
@samwalls-arm, Vulkan-Samples is installing its own debug callback.  The debug_report callback they set up only allows ERROR and WARNING messages. After modifying that project to accept PERFORMANCE_WARNING messages, they were again output properly.

Here's the change I made to get `hello_triangle `to work:

```
diff --git a/samples/api/hello_triangle/hello_triangle.cpp b/samples/api/hello_triangle/hello_triangle.cpp
index cc82e3f..50a45d2 100644
--- a/samples/api/hello_triangle/hello_triangle.cpp
+++ b/samples/api/hello_triangle/hello_triangle.cpp
@@ -239,7 +239,7 @@ void HelloTriangle::init_instance(Context &                        context,

 #if defined(VKB_DEBUG) || defined(VKB_VALIDATION_LAYERS)
        VkDebugReportCallbackCreateInfoEXT debug_report_create_info = {VK_STRUCTURE_TYPE_DEBUG_REPORT_CREATE_INFO_EXT};
-       debug_report_create_info.flags                              = VK_DEBUG_REPORT_ERROR_BIT_EXT | VK_DEBUG_REPORT_WARNING_BIT_EXT;
+       debug_report_create_info.flags                              = VK_DEBUG_REPORT_ERROR_BIT_EXT | VK_DEBUG_REPORT_WARNING_BIT_EXT | VK_DEBUG_REPORT_PERFORMANCE_WARNING_BIT_EXT | VK_DEBUG_REPORT_INFORMATION_BIT_EXT;
        debug_report_create_info.pfnCallback                        = debug_callback;
        instance_info.pNext = &debug_report_create_info;
```
