### ISSUE TITLE
Best Practices: Warn on nonsense combinations of layouts / access masks in ImageMemoryBarriers

### ISSUE THREAD

**Issue by TomOlson** [KhronosGroup/Vulkan-ValidationLayers#2063]
The Vulkan Specification description of image memory barriers permits combinations of layouts and access flags that don't have any conceivable use. Because the combinatorics make for a large design space, it is easy to get things wrong and end up with synchronization that doesn't actually do anything. But because the flag combinations are valid, the validation layers don't complain. 

It would be helpful if the Best Practices layer could warn on use of layout / access combinations that seem likely to be programmer errors. The Vulkan working group is in the process of documenting what combinations of layouts and access flags are potentially meaningful - we'll comment on the issue when we have something that could be implemented as Best Practices layer checks.

**Comment by mark-lunarg** [comment]
Updated issue #24.  Thanks!
