### ISSUE TITLE
Best Practices need to warn when duplicate VkSubpassDependency happens

### ISSUE THREAD

**Issue by locke-lunarg** [KhronosGroup/Vulkan-ValidationLayers#2079]
When pDependencies in VkRenderPassCreateInfo has duplicate VkSubpassDependency, it causes massive recursions for synchronization validation in NextSubpass or EndRenderpass.

Added in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/24

**Comment by mark-lunarg** [comment]
Thanks @locke-lunarg!
