### ISSUE TITLE
Validation should warn against empty acceleration structures

### ISSUE THREAD

**Issue by Tobski** [KhronosGroup/Vulkan-ValidationLayers#2081]
As per https://github.com/KhronosGroup/Vulkan-Docs/issues/1328, there are a number of ways to create empty acceleration structures which can't be hit in the ray tracing extension. In some cases these are going to crop up occasionally and should be completely innocuous, but there's certainly also danger that application developers didn't intend it. Adding warnings to these cases would aid in developer bring up with the ray tracing extensions.

Specifically, the cases that matter are: `VkAccelerationStructureBuildGeometryInfoKHR::geometryCount` is 0,  `VkAccelerationStructureBuildOffsetInfoKHR::primitiveCount` is 0, and cases where all primitives are inactive (see spec for how triangles are determined as active or otherwise - but this is a harder to detect case which is also likely rarer).

cc @dgkoch

**Comment by mark-lunarg** [comment]
Added to the best-practices tracking issue, #24.
