### ISSUE TITLE
Validation Layers cause crash in vkSetPrivateDataEXT

### ISSUE THREAD

**Issue by DadSchoorse** [KhronosGroup/Vulkan-ValidationLayers#2082]
Validation Layers Version: `1.2.146`

The Validation Layers seem to cause a crash in `vkSetPrivateDataEXT` with some objects. I was able to reproduce it on `VkSwapchainKHR` and `VkSampler`, `VkDevice` was fine. My guess would be that the layer wraps these object and doesn't unwrap them for `VK_EXT_private_data`.

Test to reproduce:
[private_data_test.c.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/5003951/private_data_test.c.txt)
It runs fine but crashes with `VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation`.
(Please don't mind the slightly messy code, I hacked my wine test to work standalone)

**Comment by mark-lunarg** [comment]
Ugh.  @DadSchoorse, yeah, we are not unwrapping those handles before letting them through to the driver.  EXT extensions are just the best!  In the meantime, you can disable handle wrapping to avoid the crashes.  If you need/want info for that, lemme know.
