### ISSUE TITLE
syncval: Multiple subpass dependencies EXTERNAL->0 are ignored.

### ISSUE THREAD

**Issue by HildarTheDorf** [KhronosGroup/Vulkan-ValidationLayers#2088]
From my reading of the spec it's allowed to have multiple subpass dependencies for the same (srcSubpass, dstSubpass) tuple.

The new synch validation feature in KHRONOS_validation does not seem to support my use of multiple (VK_SUBPASS_EXTERNAL, 0) dependencies.

Valid Code:
```c++
    std::array<vk::SubpassDependency, 2> subpassDependencies;
    // Sync depth buffer usage with the last renderpass
    subpassDependencies[0].srcSubpass = VK_SUBPASS_EXTERNAL;
    subpassDependencies[0].dstSubpass = 0;
    // Technically only Late->Early stages need to be specified, but it doesn't hurt to specify both.
    subpassDependencies[0].srcStageMask = vk::PipelineStageFlagBits::eEarlyFragmentTests | vk::PipelineStageFlagBits::eLateFragmentTests;
    subpassDependencies[0].dstStageMask = vk::PipelineStageFlagBits::eEarlyFragmentTests | vk::PipelineStageFlagBits::eLateFragmentTests;
    subpassDependencies[0].srcAccessMask = vk::AccessFlagBits();
    subpassDependencies[0].dstAccessMask = vk::AccessFlagBits::eDepthStencilAttachmentRead | vk::AccessFlagBits::eDepthStencilAttachmentWrite;
    subpassDependencies[0].dependencyFlags = vk::DependencyFlagBits();
    // Sync color writes with the acquire and/or last frame's MSAA buffer
    subpassDependencies[1].srcSubpass = VK_SUBPASS_EXTERNAL;
    subpassDependencies[1].dstSubpass = 0;
    subpassDependencies[1].srcStageMask = vk::PipelineStageFlagBits::eColorAttachmentOutput;
    subpassDependencies[1].dstStageMask = vk::PipelineStageFlagBits::eColorAttachmentOutput;
    subpassDependencies[1].srcAccessMask = vk::AccessFlagBits();
    subpassDependencies[1].dstAccessMask = vk::AccessFlagBits::eColorAttachmentRead | vk::AccessFlagBits::eColorAttachmentWrite;
    subpassDependencies[1].dependencyFlags = vk::DependencyFlagBits::eByRegion;
```

```c++
    renderPassCreateInfo.dependencyCount = subpassDependencies.size();
    renderPassCreateInfo.pDependencies = subpassDependencies.data();
```

Error recieved:
```
SYNC-HAZARD-NONE(ERROR / SPEC): msgNum: 105717438 - Validation Error: [ SYNC-HAZARD-NONE ] Object 0: handle = 0x109fd40, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x64d1ebe | vkCmdBeginRenderPass: Hazard WRITE_AFTER_WRITE vs. layout transition in subpass 0 for attachment 1 aspect depth during load with loadOp VK_ATTACHMENT_LOAD_OP_CLEAR.
    Objects: 1
        [0] 0x109fd40, type: 18, name: NULL
```

Reversing the order of the subpass dependencies gives the following error instead:

```
SYNC-HAZARD-NONE(ERROR / SPEC): msgNum: 105717438 - Validation Error: [ SYNC-HAZARD-NONE ] Object 0: handle = 0x28ac780, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x64d1ebe | vkCmdBeginRenderPass: Hazard WRITE_AFTER_WRITE vs. layout transition in subpass 0 for attachment 0 aspect color during load with loadOp VK_ATTACHMENT_LOAD_OP_CLEAR.
    Objects: 1
        [0] 0x28ac780, type: 18, name: NULL
```

Combing all flags into one combined dependency works fine, but shouldn't be necessary.

I'm certainly no expert when it comes to vulkan sync, so happy to be corrected if any of the above is in error!

**Comment by jzulauf-lunarg** [comment]
It's likely that no multiple dependencies are being merged in this.  While it isn't proscribed by the spec (AFAICT), I also don't see any definition of how these *should* be merged.   Specifically, is the union of the memory dependencies done based on the union of the stage masks with the union of the access masks, or based on the the union of the valid state/access pairs arising from each dependency individually.

It likely needs to be clarified in the spec, and then the sync validation updated to reflect it.

**Comment by jzulauf-lunarg** [comment]
@HildarTheDorf  -- in any case, I'll add this to my "known limitations" list for those working with SyncVal alpha.  

Also, the fact you're seeing a log message with "HAZARD-NONE" also appears to be a bug.  NONE is the *no-hazard* state and shouldn't ever show up...  can you send a small repro case?

**Comment by HildarTheDorf** [comment]
My reading of the spec is that multiple dependencies is fine, and combining them by just taking the union of stages and union of access masks would result in overzealous (i.e. slow), but correct, dependencies.

**Comment by HildarTheDorf** [comment]
https://github.com/HildarTheDorf/VulkanTutorial

I made a commit here that demonstrates the HAZARD-NONE behaviour (that's about as minimal as I can make it). Can be compiled with "clang++ --std=c++17 code/15_hello_triangle_badsync.cpp -o badsync -lglfw -lvulkan" or equivlent.

**Comment by jzulauf-lunarg** [comment]
@locke-lunarg  -- can you look at the commit above to debug the HAZARD-NONE report behavior?

**Comment by jzulauf-lunarg** [comment]
The incorrect "HAZARD-NONE" should be fixed by https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2092 (merged)

**Comment by jzulauf-lunarg** [comment]
only partially fixed... reopening unless we want to put the known limitations in a tracking issue.

**Comment by mark-lunarg** [comment]
Sorry!  @jzulauf-lunarg, we already have [a tracking issue](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/72).  If these start to pile up we can move them there, or create a new one.

**Comment by martty** [comment]
> It's likely that no multiple dependencies are being merged in this release of sync validation. While it isn't proscribed by the spec (AFAICT), I also don't see any definition of how these _should_ be merged. Specifically, is the union of the memory dependencies done based on the union of the stage masks with the union of the access masks, or based on the the union of the valid state/access pairs arising from each dependency individually.
> 
> It likely needs to be clarified in the spec, and then the sync validation updated to reflect it.

Sorry for butting into this thread, I too have multiple dependencies and interested in the developments. Was a bug filed against the spec?

**Comment by jzulauf-lunarg** [comment]
@martty -- it has.  I'm working it actively.

**Comment by jzulauf-lunarg** [comment]
@HildarTheDorf -- PR above has near term fix.  Can you verify?

**Comment by jzulauf-lunarg** [comment]
Fixed, with no issue author feedback.
