### ISSUE TITLE
Settings not working (vkconfig admin/IsHighIntegrity)

### ISSUE THREAD

**Issue by dor666** [KhronosGroup/Vulkan-ValidationLayers#2094]
When running vkconfig and tested application as admin, settings are not picked up by ValidationLayers

Details:

vkconfig tool in SDK v1.2.148 writes path to settings file to HKEY_LOCAL_MACHINE or HKEY_CURRENT_USER windows registry.
Former is used when launched as admin :

```
void Configurator::AddRegistryEntriesForLayers(QString qsJSONFile, QString qsSettingsFile) {
    // Layer override json file
    HKEY key;
    HKEY userKey = (_running_as_administrator) ? HKEY_LOCAL_MACHINE : HKEY_CURRENT_USER;
```

Topic in VulkanTools LunarG/VulkanTools#935
Topic in Loader KhronosGroup/Vulkan-Loader#266

But ValidationLayers always use HKEY_CURRENT_USER:

```
string ConfigFile::FindSettings() {
    struct stat info;

#if defined(WIN32)
    // Look for VkConfig-specific settings location specified in the windows registry
    HKEY hive;
    LSTATUS err = RegOpenKeyEx(HKEY_CURRENT_USER, "Software\\Khronos\\Vulkan\\Settings", 0, KEY_READ, &hive);
    if (err == ERROR_SUCCESS) {
```

ValidationLayers should use the same logic as vkconfig to read settings from registry.

**Comment by richard-lunarg** [comment]
@mark-lunarg Why is this a vkconfig issue? When run as administrator, should we set the file paths for both keys then (HKEY_LOCAL_MACHINE and HKEY_CURRENT_USER) so that the validation layer code can pick it up?

**Comment by mark-lunarg** [comment]
No, you're right, it sounds like the layers need to be changed.  Looking forward to the PR!

**Comment by dor666** [comment]
Just a side question: Is apidump layer using the same files for settings lookup?
