### ISSUE TITLE
False positive for VkAccelerationStructureBuildGeometryInfoKHR-update-03538

### ISSUE THREAD

**Issue by JayEff87** [KhronosGroup/Vulkan-ValidationLayers#2096]
Hello,
I believe I've found a false positive for the titular check, specifically:

Upon calling `vkCmdBuildAccelerationStructureKHR` with `VkAccelerationStructureBuildGeometryInfoKHR::update` being true, I get the error
>`vkCmdBuildAccelerationStructureKHR(): If update is VK_TRUE, srcAccelerationStructure must havebeen built before with VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_UPDATE_BIT_KHR setin VkAccelerationStructureBuildGeometryInfoKHR flags` 

However, I have confirmed that the flag is set correctly. Furthermore, the update does appear to go through, the visible geometry changes as I would expect. Indeed, if I don't set the flag upon creation of the acceleration structure, the scratch memory allocation for the update fails, as the allocationSize returned by `vkGetAccelerationStructureMemoryRequirementsKHR` is 0, as expected.

As an easy to find example of the bug in action, I can confirm it occurs in NVIDIA's implementation, found [here](https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR) (see the ray_tracing_animation example).

My version of the VulkanSDK is 1.2.141.0 in case this is relevant.

**Comment by mark-lunarg** [comment]
@souravpNV, @jeffbolznv, can you please advise?

**Comment by souravpNV** [comment]
@mark-lunarg : I believe this is the same issue that was fixed in 
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1923
build info  flags were not updated in postcallrecord method, so even if app sets it the data was NULL at validation layers.
They should not be seeing this at TOT build

**Comment by mark-lunarg** [comment]
Thanks for the quick response @souravpNV!  @JayEff87, can you confirm by trying out the [newest SDK](https://vulkan.lunarg.com/sdk/home)?

**Comment by JayEff87** [comment]
Thanks for the quick help, I can confirm that version 1.2.148.0 did not produce the error.
