### ISSUE TITLE
Missing coverage for "VUID-VkSwapchainCreateInfoKHR-physicalDeviceCount-01429"

### ISSUE THREAD

**Issue by pdaniell-nv** [KhronosGroup/Vulkan-ValidationLayers#2098]
A developer in the field accidentally set the pCreateInfo->flags value in the call to vkCreateSwapchainKHR() to VK_SWAPCHAIN_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT_KHR. This caused an unexpected and unexplained failure with their application. The developer was using validation with the VK_LAYER_KHRONOS_validation layer.

It appears there is no validation code for the follow VUID:
```
  * [[VUID-VkSwapchainCreateInfoKHR-physicalDeviceCount-01429]]
    If the logical device was created with
    slink:VkDeviceGroupDeviceCreateInfo::pname:physicalDeviceCount equal to
    1, pname:flags must: not contain
    ename:VK_SWAPCHAIN_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT_KHR
```

Can this be added since it has affected at least one real developer.

**Comment by Tony-LunarG** [comment]
Fixed with #2104
