### ISSUE TITLE
Build and test failures with latest Android toolchain

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#21]
**Issue by [cnorthrop](https://github.com/cnorthrop) (MIGRATED)**
_Thursday Mar 09, 2017 at 23:07 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1551_

----

The latest releases of the Android NDK (r14) and SDK Tools (25.3.1) are causing problems with our builds and tests.

If you've already upgraded, please roll back until we get them straightened out.  I'll update this issue when things are working again with latest tools, either through source changes or tool updates.

Links to working versions below:

Android SDK Tools:
Windows - https://dl.google.com/android/repository/tools_r25.2.3-windows.zip
Linux - https://dl.google.com/android/repository/tools_r25.2.5-linux.zip
OSX - https://dl.google.com/android/repository/tools_r25.2.3-macosx.zip

Android NDK (13b known to work):
http://developer.android.com/ndk/downloads/older_releases.html

**Comment by karl-lunarg** [comment]
<a href="https://github.com/cnorthrop"><img src="https://avatars1.githubusercontent.com/u/6932500?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cnorthrop](https://github.com/cnorthrop) (MIGRATED)**
_Saturday Mar 11, 2017 at 00:17 GMT_

----

PR #1562 works around the NDK problem, so Android NDK r14 should work now.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/cnorthrop"><img src="https://avatars1.githubusercontent.com/u/6932500?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cnorthrop](https://github.com/cnorthrop) (MIGRATED)**
_Wednesday Apr 19, 2017 at 16:09 GMT_

----

PR #1673 fixes the packaging problem for Linux and OSX.  Still need to update Windows scripts.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/mark-lunarg"><img src="https://avatars2.githubusercontent.com/u/7252958?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mark-lunarg](https://github.com/mark-lunarg) (MIGRATED)**
_Friday Mar 09, 2018 at 17:53 GMT_

----

@cnorthrop, is this still an issue?

**Comment by karl-lunarg** [comment]
<a href="https://github.com/cnorthrop"><img src="https://avatars1.githubusercontent.com/u/6932500?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cnorthrop](https://github.com/cnorthrop) (MIGRATED)**
_Friday Mar 09, 2018 at 18:22 GMT_

----

Yes, still an issue for Windows.  Probably will remain an issue until we get everything migrated over to python scripts.

**Comment by mark-lunarg** [comment]
This issue may also interact with Vulkan-Tools.

**Comment by mark-lunarg** [comment]
@cnorthrop, I think we're past this with the known-good?  Correct me if this isn't true.  Thanks!

**Comment by cnorthrop** [comment]
I *think* this issue was about removal of the "android" script and "ant" from the SDK.  It means you cannot create VulkanLayerValidationTests.apk on Windows.  I don't think anyone has complained about it, or provided a way to do it, so I think you can keep this closed.
