### ISSUE TITLE
Vulkan 1.1 is not properly detected for the shader validation layer

### ISSUE THREAD

**Issue by MaikKlein** [KhronosGroup/Vulkan-ValidationLayers#210]
It seems even when an 1.1 instance is created, the vulkan validation layer will trigger for 1.1 features. For example:

>"Object: VK_NULL_HANDLE (Type = 0) | SPIR-V module not valid: Invalid SPIR-V binary version 1.3 for target environment SPIR-V 1.0 (under Vulkan 1.0 semantics)."

With this header

>; SPIR-V
; Version: 1.3
; Generator: Google rspirv; 0
; Bound: 62
; Schema: 0

It seems that only the 1.0 context is checked.

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/9d1ac3171762514b39ec405e8bc12e464b360963/layers/shader_validation.cpp#L1710

If I don't set the version to 1.3 I get other validation errors like 

> Object: VK_NULL_HANDLE (Type = 0) | SPIR-V module not valid: 2nd operand of TypePointer: operand 12 requires one of these extensions: SPV_KHR_storage_buffer_storage_class SPV_KHR_variable_pointers

Although I am not 100% certain if the `VK_KHR_storage_buffer_storage_class` has to be enabled in a vulkan 1.1 context. I assume it doesn't have to because it is core.

**Comment by daveh-lunarg** [comment]
Already recorded as issue #158.  Fix is pending.
