### ISSUE TITLE
validation to-add: vkCmdCopyBufferToImage must be on graphics queue, for depth-stencil format (also vkCmdCopyImageToBuffer)

### ISSUE THREAD

**Issue by mccaffrey-jonathan** [KhronosGroup/Vulkan-ValidationLayers#2113]
The VkBufferImageCopy argument for vkCmdCopyBufferToImage and vkCmdCopyImageToBuffer specifies restriction 

> Because depth or stencil aspect buffer to image copies may require format conversions on some implementations, they are not supported on queues that do not support graphics.

However, this specification is not in the Valid Usage block, and the validation layers also don't enforce it.  There is a queue flags check in validation layers for vkCmdCopyBufferToImage/vkCmdCopyImageToBuffer , should this additionally check that for depth-stencil format images,  queue bit VK_QUEUE_GRAPHICS_BIT is set ?
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/c1c43b026f9350e67eff6dbc7f25013ec1e39fa0/layers/buffer_validation.cpp#L5813

**Comment by sfricke-samsung** [comment]
So I agree there should be a VU to check that the command buffer being used was allocated from a command pool tied to a queue that has `VK_QUEUE_GRAPHICS_BIT` set

So there are 2 items for these cases

1. Fix in the Vulkan spec at https://github.com/KhronosGroup/Vulkan-Docs  but for this, I can handle making the internal fix to add this as a proper Valid Usage statement
2. The Validation Layers need to add the logic and then label it once the VUID shows up in a header

@mark-lunarg feel free to assign this to me as this is a trivial enough of a fix I can see it through from spec fix to validation PR

**Comment by mark-lunarg** [comment]
Thank you Spencer!
