### ISSUE TITLE
A potential validation layer bug with Dual Source Blending.

### ISSUE THREAD

**Issue by vikram-jadhav** [KhronosGroup/Vulkan-ValidationLayers#2115]
Hi, 
         We are getting the following validation warning for a unit-test we have set up for Dual Source Blending with Vulkan SDK 1.1.126 on win64

 VALIDATION: Validation Warning: [ UNASSIGNED-CoreValidation-Shader-OutputNotConsumed ] Object 0: handle = 0xee1e29000000002c, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x609a13b | fragment shader writes to output location 1 with no matching attachment

In the case of Dual Source Blending, the shader writes to 2 output locations, but the locations are used as two sources for blending to 1 destination. Therefore, the above warning doesn't make sense, unless I am missing some setup step.

**Comment by mark-lunarg** [comment]
An issue like this (#766) was fixed right around the time this old SDK came out.  Can you please retry with the latest [SDK](https://vulkan.lunarg.com/sdk/home)?

**Comment by mark-lunarg** [comment]
@vikram-jadhav, were these results using the latest SDK? If it is, please let us know what the specific Android device was (we have half-a-dozen in our test farm) and maybe provide us with a simple test case?  That'd help a lot, thanks!

**Comment by vikram-jadhav** [comment]
- The crash on Android was with Vulkan SDK 1.1.126 and without enabling the Validation layer. 
- The device was Pixel 3 XL with Android 10.  
- The unit-test was simple, but I am not sure sharing the code will help as it's written in our rendering API which acts as a backend abstraction layer. 
- Here's how it's setup. A pixel shader writes to 2 color outputs. The render-pass only has one attachment-description, but the sub-pass has 2 attachment-references where the 2nd attachment index is VK_ATTACHMENT_UNUSED.  One of the blend factors that the graphics pipeline uses is VK_BLEND_FACTOR_SRC1_COLOR. In the end, we read back the value written to frame-buffer and compare it to the expected output.

**Comment by mark-lunarg** [comment]
If the crash is occuring without the layers I believe you are correct.  Is there validation output for the Pixel 3XL before the crash? Also, just for fun, the latest Android layer binaries are [available here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/releases)).

**Comment by mark-lunarg** [comment]
@vikram-jadhav, closing for now as there seems to be no further work for the layers here.  If you find otherwise, please comment here and I'll reopen, or create a new issue.  Thanks!

**Comment by vikram-jadhav** [comment]
Thank you for the link to Android layer binaries. Yes, I think you can close this as it's fixed for PC. Android isn't an immediate priority for us. It may take me a while to share the validation output on Android as integrating Validation layers with our current setup is a bit of work.
