### ISSUE TITLE
Should VkDisplayModeKHR objects be created in PostCallRecordGetDisplayModePropertiesKHR?

### ISSUE THREAD

**Issue by bcmet** [KhronosGroup/Vulkan-ValidationLayers#2116]
The issue occurs when PreCallRecordGetDisplayPlaneCapabilitiesKHR (layers/generated/thread_safety.cpp) is called and the VkDisplayModeKHR object is not found in the map.

The application is calling the following functions:
vkGetDisplayModePropertiesKHR
...
vkGetDisplayPlaneCapabilitiesKHR

The only place where the VkDisplayModeKHR objects are created (and added to the map) is when VkCreateDisplayModeKHR is called which I believe is optional.

My question is: should the VkDisplayModeKHR objects be also created when vkGetDisplayModePropertiesKHR is called and return an array of VkDisplayModePropertiesKHR?

See the attached file to see what I have in mind.

Thanks
[commit-f31883d.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/5090495/commit-f31883d.txt)

**Comment by mark-lunarg** [comment]
We made a sweep to cover these issues in commit eb3a42af33, which should have been included in the [1.2.148 SDK](https://vulkan.lunarg.com/sdk/home).  Are these issues still manifesting in the latest SDK or in TOT?

**Comment by bcmet** [comment]
It is working fine with this commit. Thanks

**Comment by mark-lunarg** [comment]
Glad to hear it, thank you!
