### ISSUE TITLE
make install does not produce vk_layer_dispatch_table.h

### ISSUE THREAD

**Issue by jengelh** [KhronosGroup/Vulkan-ValidationLayers#2118]
Version: 1.2.148
When building the ValidationLayers tree and running `make install`, no .h files are placed into /usr/include.
It would seem to me that this is because `BUILD_LAYER_SUPPORT_FILES` defaults to `OFF`.

This is contraty to `BUILD.md` which states that “Controls whether or not layer support files are built if the layers are not built.”

**Comment by mark-lunarg** [comment]
Would “Controls whether or not layer support files are installed.” be a better description?

**Comment by jengelh** [comment]
Absolutely.

**Comment by mark-lunarg** [comment]
Changed and pushed to Master -- thanks for the report!

**Comment by jengelh** [comment]
But why does the flag exist/off by default anyway? If these files are not meant to be used outside of vulkan-validationlayers, shouldn't they be removed from make install at all?

**Comment by mark-lunarg** [comment]
These files are used by other Khronos and non-Khronos repositories which build layers.  As you noted they are not installed by default, but It is advantageous to have the ability to share these files without having to build the repository and all its dependencies.
