### ISSUE TITLE
[Feature Request] Get notified when a texture layout changes

### ISSUE THREAD

**Issue by darksylinc** [KhronosGroup/Vulkan-ValidationLayers#2123]
Hi!

I just spend a couple hours finding a rogue/stray layout change in my code, which came from an incorrectly setup VkRenderPass.

I actually found the problem doing "by hand" what this feature suggests. I noticed the relevant code seems to be in
`CoreChecks::SetImageLayout` from source/Vulkan-ValidationLayers/layers/buffer_validation.cpp

I just waited with breakpoints until layout and image_state.image were the ones I was expecting; and walked up the stack.

It would be cool if there was an official way to do this, like registering a listener so we get:

 - old layout
 - new layout
 - image ptr
 - name (if vkDebugMarkerSetObjectNameEXT was called on it)

**Comment by mark-lunarg** [comment]
@darksylinc, that sounds pretty cool, but might be slightly outside the purview of the default set of work done in the Validation Layers.  I will add it to the [Best Practices tracking issue](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/24) (though it doesn't quite fit that either) just so it doesn't get lost.  This might be something better suited to [GfxReconstruct ](https://github.com/LunarG/gfxreconstruct) or [RenderDoc ](https://github.com/baldurk/renderdoc) maybe?

**Comment by darksylinc** [comment]
RenderDoc may be able to do it, but is not very well suited for this; as the goal is to break and evaluate the C++ state whenever that rogue transition changes.

Conceptually speaking, what I am proposing is very similar to [_crtBreakAlloc](https://support.microsoft.com/en-us/help/151585/how-to-use-crtbreakalloc-to-debug-a-memory-allocation)
