### ISSUE TITLE
How to go about scanning SPIR-V Tools for VUIDs

### ISSUE THREAD

**Issue by sfricke-samsung** [KhronosGroup/Vulkan-ValidationLayers#2141]
The 1.2.152 headers add almost 300 VUs for Built-ins, most (if not all) of which I assume should be implemented in `spirv-val`

I created an [initial PR](https://github.com/KhronosGroup/SPIRV-Tools/pull/3756) to label all the current VUs in effort to know where to add effort in the battle for more complete Vulkan targeted SPIR-V validation

This issue is to address `vk_validation_stats.py` as I am willing to add the logic, but there a few a ways to go about it and wanted 2nd thoughts before I go off and create a PR as I realize there might be some internal flows I don't want to break on people.

1. Getting SPIR-V tools to scan source
    - One thought is that the script could attempt to clone the source ToT, only cloning the master branch in effort to reduce overhead
    - Another idea is just like the `validusage.json` to pass the path to a SPIR-V tools
    - Regardless, I feel this should work even if a user of the script
2. Marking where it the VU is implemented
    - Main issue is the VUID itself doesn't describe if it will be implemented in SPIR-V Tools or VVL until found in source
    - I imagine in the `-summary` it would be nice to show how many Explicit VUIDs of the total checked/tested are in SPIR-V tools repo
    - For the `-html`,`-cvs`, `-text` option it would be worth adding a column to describe if it is implemented in the Validation Layers or SPIR-V Tools
3. vk_validation_error_messages.h
    - There was some extra logic that was added to the ruby scripts in Vulkan-Doc to handle the fact these VUIDs belong to non-enum/commands/structs. I imagine there will need to be some extra logic for this file as well

Overall, I don't think this is too invasive of a change as it is all additive in nature

**Comment by mark-lunarg** [comment]
@sfricke-samsung, for #1, I'd prefer the second option, and would make it optional -- if no Spirv-tools path is passed in, it works just like it does today. 

Perhaps there could be a `vk_validation_stats.py` counterpart in the spirv-tools repo.  Then the VVL script could call the Spirv-tools script and combine the outputs.  I'm mostly worried about having to maintain a list of Spriv-tools source files in the VVL script, but it's not a deal breaker if it turns out to be necessary.

#2 seems straightforward, and for #3, `vk_validation_error_messages.h `is generated directly from the `validusage.json` file, so I'm hoping that we'll be somewhat insulated from the Vulkan-Docs changes.

**Comment by sfricke-samsung** [comment]
for `1`

I thought about putting some logic in SPIR-V Tools, but I guess was trying to keep everything in one point and need as little dependency on sync up info between repos (also since this is the only script that cares about the VUID strings in spirv-tools, feel like easier to make changes here)

I also haven't looked into it closely (figure its due to time to run script), but curious why the script list files instead of directories as this could be simply just

```
spirv_val_dir = [ "test/val/*", "source/val/* ]
```

----

For `3` - good to know, makes life easier!

**Comment by sfricke-samsung** [comment]
Also, for `1`, as [per request from SPIR-V Tool folks](https://github.com/KhronosGroup/SPIRV-Tools/pull/3756#discussion_r479278960) all the VUID strings will be in a single switch case, so makes maintaining the file location easy :smile:
