### ISSUE TITLE
Push constant validation issues

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-ValidationLayers#2148]
We hit a validation error in ANGLE related to the following VVL change de8975779. Oddly enough, this validation error manifests on Nvidia driver 440.10 on Ubuntu 18.04 with a GTX 1660, but not on a more recent driver on Ubuntu 20.04 with a GTX 970.

That said, I believe there are two potential issues here.

First, the push constant resulting in error is:

```
layout(push_constant) uniform PushConstants {
    // Number of levels to generate mipmaps for.
    uint levelCount;
    // Inverse extents of src image for uv calculation.
    vec2 invSrcExtent;
} params;
```

Note that there's an (accidental) implicit padding between the two variables. The validation error is:

```
DebugUtilsMessenger(338): [ UNASSIGNED-CoreValidation-Shader-PushConstantOutOfRange ] Validation Error: [ UNASSIGNED-CoreValidation-Shader-PushConstantOutOfRange ] Object 0: handle = 0x1ad9dfa50050, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x650ba96a | Shader push-constant buffer member 1 at offset 8 is not declared in pipeline layout
                            Object: 0x1ad9dfa50050 (type = Device(3))
```

However, the pipeline correctly does declare 16 bytes of push constants. This seems like a VVL bug.

---

Additionally, I tried to add some debug output to the code that generates this validation error, and I noticed that in `ValidatePushConstantBlockAgainstPipeline`, where the validation happens:

```
if ((range.offset <= offset) && ((range.offset + range.size) >= (offset + size)) &&
    (range.stageFlags & stage)) {
```

for the vec2 field, the calculated size is `6` but should be `8`! That's not causing a failure, but it's definitely a bug.

**Comment by locke-lunarg** [comment]
The change have been undo, so the issue should be gone.
