### ISSUE TITLE
Validation task to add check for binding range

### ISSUE THREAD

**Issue by usamamahboob-AMD** [KhronosGroup/Vulkan-ValidationLayers#2151]
need to add validation check for the following VU:

when you bind the descriptor, if you set the dynamic offset to anything other than 0, you’ll be violating this VU:

 

For each dynamic uniform or storage buffer binding in pDescriptorSets, the sum of the effective offset, as defined above, and the range of the binding must be less than or equal to the size of the buffer
 

That comes from vkCmdBindDescriptorSets.

**Comment by mark-lunarg** [comment]
VUID-vkCmdBindDescriptorSets-pDescriptorSets-01979

> For each dynamic uniform or storage buffer binding in pDescriptorSets, the sum of the effective offset, as defined above, and the range of the binding must be less than or equal to the size of the buffer

**Comment by ncesario-lunarg** [comment]
It looks like [this](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/descriptor_sets.cpp#L822) code is checking for this?

@sfricke-samsung would you happen to have any insight into this VUID? I'm pretty sure I'm missing something here, especially with respect to "if you set the dynamic offset to anything other than 0."

**Comment by sfricke-samsung** [comment]
So this the set of Draw VUs for ` VUID-vkCmdDraw-None-02699`. I think @locke-lunarg put these together (I didn't)

The main difference is that code is checked at draw time from what the descriptor was set as, while VUID `01979` is at `vkCmdBindDescriptorSets` itself.

**Comment by ncesario-lunarg** [comment]
Thanks for the quick response @sfricke-samsung! My mistake, I'll follow up with @locke-lunarg.

**Comment by locke-lunarg** [comment]
Thanks @sfricke-samsung . My mistake to set a wrong VUID.

**Comment by spencer-lunarg** [comment]
I am pretty sure this was fixed in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2540 , closing
