### ISSUE TITLE
Synchronisation validation fails on some buffers with VK_WHOLE_SIZE range

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-ValidationLayers#2166]
I have a test case where I removed some necessary barriers to trigger the synchronisation validation and it didn't print anything. Tracking the issue down I found that here where the range is added to the buffer's base address:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/c876c6eba742a082d7580090946b284d4c712fde/layers/synchronization_validation.cpp#L955-L959

If the range comes from a descriptor where size is `VK_WHOLE_SIZE` the range addition overflows and so you end up with a range something like `begin=12345, end=12344` which will never match anything.

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/c876c6eba742a082d7580090946b284d4c712fde/layers/range_vector.h#L75

The test case is in [RenderDoc's demos project](https://github.com/baldurk/renderdoc/tree/v1.x/util/test), in particular in VK_Indirect I removed [this barrier](https://github.com/baldurk/renderdoc/blob/v1.x/util/test/demos/vk/vk_indirect.cpp#L303-L305) between a dispatch writing some indirect parameters and an indirect dispatch that uses them.

**Comment by jzulauf-lunarg** [comment]
@baldurk  --the linked PR fixes the range computation but spawns new sync validation messages which seems to be reporting insufficient access mask bits.

**Comment by baldurk** [comment]
Yes that works for me. With the new messages it looks like there were a couple of cases where I had `TRANSFER_WRITE` but I meant `SHADER_WRITE`, probably a copy-paste error. There are another couple of messages that are technically accurate but the dispatch in question is indirect which dispatches 0,0,0 so it would require GPU-based validation to know if shader writes actually happen.

**Comment by jzulauf-lunarg** [comment]
@baldurk -- thanks.
