### ISSUE TITLE
subpass #n, input attachment #n is not used in fragment shader. (Either not supposed to be invalid usage or does not point to the correct rule in the documentation). 

### ISSUE THREAD

**Issue by x3DCoder** [KhronosGroup/Vulkan-ValidationLayers#2171]
I am having new validation errors after updating the vulkan validation layers. 

My subpasses have input attachments that are correctly bound via descriptor sets but not always all used in some shaders. 
This should not be invalid in my opinion, but the new version of validation layers seem to think it is invalid. 

I am getting the following validation errors : 

```
[ VUID-vkCmdDrawIndexed-None-02686 ] Object 0: handle = 0x5555573c0f18, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0xfc00000000fc, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0xe91b58a0 | vkCmdDrawIndexed(): VkRenderPass 0xfc00000000fc[], subpass #1, input attachment #3 is not used in fragment shader. The Vulkan spec states: Every input attachment used by the current subpass must be bound to the pipeline via a descriptor set (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdDrawIndexed-None-02686)
```

It seems to be pointing to the rule saying that input attachments must be bound to the pipeline via a descriptor set, which makes a lot of sense, but they are correctly bound in my case, just not used in every fragment shader code, even tho always declared as input attachments and correctly bound. 

Is this an error ? 
I cannot find any rule that actually says that all fragment shaders must actually USE all input attachments bound in the subpass... 

If so, then the validation message is certainly not pointing to the correct rule, otherwise there is an error in the way the validation layers interpret what is happening.

**Comment by egdaniel** [comment]
I am seeing the same issue. Input attachment is bound to a descriptor set, but not used in a specific draw in the render pass.

**Comment by samwalls-arm** [comment]
I was finding this behaviour earlier today as well. With:
- SDK `1.2.135`
- graphics: Intel UHD 620 (driver: `27.20.100.8476`)

 Many of the vulkan samples (not all) seem to be spitting out these errors. The `subpasses` sample might be a good example.

**Comment by locke-lunarg** [comment]
@x3DCoder, @egdaniel, @samwalls-arm, can you please try PR 2223 and see if it fixes the issues you were seeing?

**Comment by x3DCoder** [comment]
@locke-lunarg  I have just tested it, works fine now, no more validation errors! 
Thanks!

**Comment by ARNAB5671** [comment]
Vulkan error [Validation]: code: 0: vkCreateGraphicsPipelines(): pCreateInfos[0].pStages[0].sType must be VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO.
The Vulkan spec states: sType must be VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO (https://vulkan.lunarg.com/doc/view/1.4.313.1/windows/antora/spec/latest/chapters/pipelines.html#VUID-VkPipelineShaderStageCreateInfo-sType-sType)
C:\Users\arnab.1d\skia1\skia\tools\gpu\vk\VkTestUtils.cpp(141): fatal error: "Vulkan debug layer error"


Can anyone explain what is the issue here?
