### ISSUE TITLE
GetDescriptorSetLayoutSupport should null check pImmutableSamplers in the generated object_tracker layer

### ISSUE THREAD

**Issue by alexanderyshi** [KhronosGroup/Vulkan-ValidationLayers#218]
Using the Vulkan 1.1.73 SDK

From Vulkan spec _13.2.1 Descriptor Set Layout_, it seems that there is a valid use case for a VkDescriptorSetLayoutBinding object to be passed to vkGetDescriptorSetLayoutSupport(...) with **const VkSampler* pImmutableSamplers** set as NULL. 

> If pImmutableSamplers is NULL, then the sampler slots are dynamic and sampler handles must be bound into descriptor sets using this layout.

Within **GetDescriptorSetLayoutSupport(...)** in the generated object_tracker.cpp, the validation layer tries to index pImmutableSamplers without doing a null check first, leading to a crash when this is passed as null.

**Comment by daveh-lunarg** [comment]
Looked at this a little bit with @Tony-LunarG and @mikes-lunarg yesterday.  It appears pImmutableSamplers is correctly labeled in the vk.xml file but the 'optional' is lost during codegen?

**Comment by mark-lunarg** [comment]
This has been fixed!
