### ISSUE TITLE
pBeginInfo->pInheritanceInfo should not be read when command buffer is primary

### ISSUE THREAD

**Issue by hevrard** [KhronosGroup/Vulkan-ValidationLayers#2195]
In `StatelessValidation::manual_PreCallValidateBeginCommandBuffer()`, pBeginInfo->pInheritanceInfo is dereferenced (if it is non-null) to check sType, even if the command buffer is primary:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/db992e60cc7ad13b0894ac92366cf09690e5bb28/layers/parameter_validation_utils.cpp#L3260-L3268

Yet, the [spec for VkCommandBufferBeginInfo](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkCommandBufferBeginInfo.html) says:

> pInheritanceInfo is a pointer to a VkCommandBufferInheritanceInfo structure, used if commandBuffer is a secondary command buffer. **If this is a primary command buffer, then this value is ignored.**

So it sounds like the implicit VU (for pInheritanceInfo to be a valid pointer) is overridden by this remark, such that the validation layer should not read it unless the command buffer is known to be secondary.

(This issue leads to possible replay crashes in AGI, see discussion at: https://github.com/google/agi/pull/475)

**Comment by mark-lunarg** [comment]
Ugh.  This is an ugly spec corner-case where information is required from a different API (`vkAllocateCommandBuffers`) to know whether to wrap handles in `vkBeginCommandBuffer`, hosing the dispatcher and safe_struct.  The stateless validation call will need to move to corechecks and some handle-wrapping rework will be needed to address the larger issues.

**Comment by mark-lunarg** [comment]
Pushed a fix for the layer chassis dispatcher, a fix for the stateless validation error is in flight.  This scenario seems to be improperly handled on all the devices we have available for testing -- wondering if there is a CTS test case for this.  @rg3igalia?

**Comment by rg3igalia** [comment]
I've taken a look at the command buffer tests and it looks like CTS lacks a specific test for this case. This one should be interesting, so I'll create a test for that.

**Comment by rg3igalia** [comment]
CTS tests submitted for review.
