### ISSUE TITLE
Specialization Constant as array size causes validation error

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#22]
**Issue by [wobakj](https://github.com/wobakj) (MIGRATED)**
_Tuesday Mar 14, 2017 at 22:08 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1580_

----

On drawing, the following error is triggered: `Descriptor in binding #0 at global descriptor index 1 is being used in draw but has not been updated` 
The error appears regardless of the actual value of the constant. No error is triggered when using a "normal" constant variable with identical value instead. This behaviour appears at least for sampler, texture and buffer arrays.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/wobakj"><img src="https://avatars3.githubusercontent.com/u/6664953?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [wobakj](https://github.com/wobakj) (MIGRATED)**
_Thursday Jun 08, 2017 at 21:38 GMT_

----

This issue can be closed. I now realized that it was caused by an incorrect automated building of the DescriptorSets in my application.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/chrisforbes"><img src="https://avatars1.githubusercontent.com/u/128877?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Friday Jun 09, 2017 at 01:24 GMT_

----

You may have had another issue with your code, but we're still doing the wrong thing in validation with specialization. This is still on my plate.

**Comment by mark-lunarg** [comment]
@chrisforbes, can you add some context about what needs to be done here?

**Comment by chrisforbes** [comment]
Right -- the remaining work here is to apply the SPIRV-Tools specialization passes before doing any analysis.

**Comment by jeremy-lunarg** [comment]
This is now covered by PR #1166.

**Comment by jeremy-lunarg** [comment]
Fixed by #1344.

The SPIR-V optimizer (#2927) has been patched to handle existing extended types, and I've updated the patch in #1344 to log errors when future unrecognized/extended types are encountered.
