### ISSUE TITLE
CreateImageView bug with VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT_KHR

### ISSUE THREAD

**Issue by mark-lunarg** [KhronosGroup/Vulkan-ValidationLayers#2203]
From an external bug report:

We found a bug that is falsely asserting VUID-VkImageViewCreateInfo-image-01761 on us.  In the 1.2.148 buffer_validation.cpp:4634, we see:

`                if ((!(image_flags & VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT_KHR)) || (!FormatIsMultiplane(image_format))) {`

The || should be an &&

The spec says,

> If image was created with the VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT flag, but without the VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT flag, and if the format of the image is not a multi-planar format, format must be compatible...

We are setting  VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT so we are good to go.  With an ||, it's saying you also have to be multiplanar which isn't true.

**Comment by mark-lunarg** [comment]
In` PreCallValidateCreateImageView()`.

**Comment by ncesario-lunarg** [comment]
Fixed with https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2214.
