### ISSUE TITLE
VkDebugUtilsMessageSeverityFlagBitsEXT == 4096

### ISSUE THREAD

**Issue by ak-1** [KhronosGroup/Vulkan-ValidationLayers#2204]
I have the following DebugUtilsMessenger callback:
```
static VKAPI_ATTR VkBool32 VKAPI_CALL debugUtilsMessengerCallbackFn(
    VkDebugUtilsMessageSeverityFlagBitsEXT messageSeverity,
    VkDebugUtilsMessageTypeFlagsEXT messageType,
    const VkDebugUtilsMessengerCallbackDataEXT* pCallbackData,
    void* pUserData)
{
    printf("[debugUtilsMessenger:%d:%d] %s\n", messageSeverity, messageType, pCallbackData->pMessage);
    return VK_FALSE;
}
```
which produces the following output:
```
[debugUtilsMessenger:4096:1] /usr/lib32/libvulkan_radeon.so: wrong ELF class: ELFCLASS32
```
4096 does not seems to be a valid value: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkDebugUtilsMessageSeverityFlagBitsEXT.html

**Comment by mark-lunarg** [comment]
Does this message appear without the validation layers loaded?  It appears that this message is coming from your AMD Linux driver, likely indicating that a 32-bit component was encountered when a 64-bit one was expected.

**Comment by ak-1** [comment]
The message appears only when the validation layers are enabled:
```
[ak@can:~/my/dev/vulkan/mandelbrot]$ cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ak/my/dev/vulkan/mandelbrot/build
[ak@can:~/my/dev/vulkan/mandelbrot]$ cmake --build build
[ 33%] Building CXX object CMakeFiles/vulkan_minimal_compute.dir/src/main.cpp.o
[ 66%] Building CXX object CMakeFiles/vulkan_minimal_compute.dir/lib/lodepng.cpp.o
[100%] Linking CXX executable vulkan_minimal_compute
[100%] Built target vulkan_minimal_compute
[ak@can:~/my/dev/vulkan/mandelbrot]$ ./build/vulkan_minimal_compute 
enableValidationLayers
[debugUtilsMessenger:4096:1] /usr/lib32/libvulkan_radeon.so: wrong ELF class: ELFCLASS32
[debugUtilsMessenger:4096:1] /usr/lib32/libvulkan_intel.so: wrong ELF class: ELFCLASS32
done
[ak@can:~/my/dev/vulkan/mandelbrot]$ cmake -DCMAKE_BUILD_TYPE=Release -S . -B build
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ak/my/dev/vulkan/mandelbrot/build
[ak@can:~/my/dev/vulkan/mandelbrot]$ cmake --build build
[ 33%] Building CXX object CMakeFiles/vulkan_minimal_compute.dir/src/main.cpp.o
[ 66%] Building CXX object CMakeFiles/vulkan_minimal_compute.dir/lib/lodepng.cpp.o
[100%] Linking CXX executable vulkan_minimal_compute
[100%] Built target vulkan_minimal_compute
[ak@can:~/my/dev/vulkan/mandelbrot]$ ./build/vulkan_minimal_compute 
done
```
I have both 32 and 64 bit libs installed:
```
[ak@can:~]$ locate libvulkan_radeon.so
/usr/lib/libvulkan_radeon.so
/usr/lib32/libvulkan_radeon.so
```
The program works fine so I think this is just an informational message that this particular library is not compatible. I am not so much concerned about the message itself. I was just wondering why the messageSeverity is 4096 when it should be between 1, 2, 4 or 8.

**Comment by mark-lunarg** [comment]
As you noted, the spec says:

> // Provided by VK_EXT_debug_utils
> typedef enum VkDebugUtilsMessageSeverityFlagBitsEXT {
>   VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT = 0x00000001,
>   VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT = 0x00000010,
>   VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT = 0x00000100,
>   VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT = **0x00001000**,
> } VkDebugUtilsMessageSeverityFlagBitsEXT;

**0x00001000 == 4096**

**Comment by ak-1** [comment]
Gosh of course. Sorry to waste your time.
