### ISSUE TITLE
dynamic descriptor offset validation

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-ValidationLayers#2205]
If I specify `0` as a dynamic offset in my offset array, I get a validation error, but the spec doesn't explicitly prohibit this as far as I can tell. Typically if I'm using a dynamic buffer, I start with data at the beginning of the buffer and then increase the offset as I go without creating a new pipeline just for that first use.

**Comment by zmike** [comment]
Oops, disregard, this works fine :)

**Comment by mark-lunarg** [comment]
@zmike, these are the _best_ kinds of issues!

**Comment by zmike** [comment]
Happy to provide them!
