### ISSUE TITLE
ValidationStateTracker::PreCallRecordDestroyFence() crashes with fence created by vkRegisterDisplayEventEXT()

### ISSUE THREAD

**Issue by timo-suoranta-varjo** [KhronosGroup/Vulkan-ValidationLayers#2221]
`ValidationStateTracker::PreCallRecordDestroyFence()` crashes with fence created by `vkRegisterDisplayEventEXT()`.

```
    auto fence_state = GetFenceState(fence);
    fence_state->destroyed = true;
```

`GetFenceState()` returns `nullptr` so assignment crashes.

**Comment by timo-suoranta-varjo** [comment]
The code runs as expected without issues when validation layers are not enabled.

**Comment by nces** [comment]
Hi @timo-suoranta-varjo, do you know if there are any validation errors printed before the crash?

**Comment by timo-suoranta-varjo** [comment]
> Hi @timo-suoranta-varjo, do you know if there are any validation errors printed before the crash?

See #2222 - no other validation issues.

**Comment by mark-lunarg** [comment]
This may also depend on information requested in #2222.

**Comment by timo-suoranta-varjo** [comment]
I added comment with more information to #2222.
