### ISSUE TITLE
Incorrect error when using VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT_EXT

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-ValidationLayers#2224]
When creating a pipeline with `VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT_EXT` (and correspondingly with `VK_DYNAMIC_STATE_SCISSOR_WITH_COUNT_EXT`) the `viewportCount` and `scissorCount` in the pipeline create info must be set to 0:

> `VUID-VkGraphicsPipelineCreateInfo-pDynamicStates-03379`
> If VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT_EXT is included in the pDynamicStates array then viewportCount must be zero
>
> `VUID-VkGraphicsPipelineCreateInfo-pDynamicStates-03380`
> If VK_DYNAMIC_STATE_SCISSOR_WITH_COUNT_EXT is included in the pDynamicStates array then scissorCount must be zero

But when doing that I get an error from this code:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/9d4b40ae645e092bb5550cbaf73b6bfd5a3ce52a/layers/parameter_validation_utils.cpp#L2006-L2021

which is checking for non-1 when multiView is not enabled. I believe this needs an additional check to only print this error when `!has_dynamic_viewport_with_count` or `!has_dynamic_scissor_with_count`.

**Comment by mark-lunarg** [comment]
@pdaniell-nv, do you agree with @baldurk?

**Comment by pdaniell-nv** [comment]
> @pdaniell-nv, do you agree with @baldurk?

Yes, there should be extra checks for !has_dynamic_viewport_with_count or !has_dynamic_scissor_with_count. I suspect I missed this because this is for the !multiViewport case which our implementation doesn't have. @mark-lunarg are you planning to fix this?

**Comment by baldurk** [comment]
FWIW this is checking what features are enabled, not which ones are available. You can still hit this even if the driver supports multiViewport as long as the application doesn't enable it (and a good vulkan application shouldn't enable features it doesn't use).

**Comment by mark-lunarg** [comment]
> @mark-lunarg are you planning to fix this?

Sure, I'll give it a shot.

**Comment by mark-lunarg** [comment]
@baldurk, please lemme know right away if this doesn't cover the issue you discovered, or if you run into anything else.  Thanks!
