### ISSUE TITLE
Update known-good files for 1.2.157 header

### ISSUE THREAD

**Issue by y-novikov** [KhronosGroup/Vulkan-ValidationLayers#2227]
This blocks rolling 1.2.157 headers into ANGLE.
https://chromium-review.googlesource.com/c/angle/angle/+/2465051
 ../../third_party/angle/third_party/vulkan-validation-layers/src/layers/generated/vk_enum_string_helper.h:363:14: error: use of undeclared identifier 'VK_STRUCTURE_TYPE_DRM_FORMAT_MODIFIER_PROPERTIES_EXT'; did you mean 'VK_STRUCTURE_TYPE_DRM_FORMAT_MODIFIER_PROPERTIES_LIST_EXT'?

I could probably run generate_source.py myself, but I don't know if I can just update known-good files without any testing.

@shannon-lunarg took care of all previous updates.

**Comment by shannon-lunarg** [comment]
I have a header update in the works if that is what you're looking for. #2228 
It will be merged upon passing internal testing and approval.

**Comment by y-novikov** [comment]
Cool, thanks!

**Comment by y-novikov** [comment]
Fixed by #2228 

Roll into ANGLE passed https://chromium-review.googlesource.com/c/angle/angle/+/2477443
