### ISSUE TITLE
Identically defined descriptor sets ordering of sets

### ISSUE THREAD

**Issue by FilippoLeon** [KhronosGroup/Vulkan-ValidationLayers#2233]
So, in a mild abuse of the vulkan specs I have stretched the meaning of "identically defined" descriptor set layouts to mean same bindings of same type but in any order. So I just defined a descriptor set layout with 2 buffers at binding 3 and 4 and flipped the bindings around when creating the pipeline.

This used to work with no validation error, until I used MoltenVK:
https://github.com/KhronosGroup/MoltenVK/issues/1107

I think (by just very quickly glancing through the comments in descriptor_sets.h) that the ValidationLayers are interpreting this as I originally did, and thus emit no error.

Does the Validation interpret it this way? If so, and it turns out this interpretation is indeed incorrect, it would be nice to either add a validation error.

**Comment by mark-lunarg** [comment]
@jzulauf-lunarg, could you please comment on what the pipeline layout compatibility validation accepts and what it doesn't (or, what it'd do if it encountered the same bindings but in a different order)?

**Comment by jzulauf-lunarg** [comment]
I don't believe the declaration order in the descriptor sets is supposed to matter.  If Molten is relying on this, it may be a bug there.  I don't see anything in the text the implies that order matters, in fact the treatment of bindings as indices to a sparsely filled array is strongly implied.

> The above layout definition allows the descriptor bindings to be specified sparsely such that not all binding numbers between 0 and the maximum binding number need to be specified in the pBindings array. Bindings that are not specified have a descriptorCount and stageFlags of zero, and the value of descriptorType is undefined. However, all binding numbers between 0 and the maximum binding number in the VkDescriptorSetLayoutCreateInfo::pBindings array may consume memory in the descriptor set layout even if not all descriptor bindings are used, though it should not consume additional memory from the descriptor pool.

If the VkDescriptorSetLayoutBinding*    pBindings contains the same VkDescriptorSetLayoutBinding entries in whatever order, I believe they should be considered identical.

**Comment by FilippoLeon** [comment]
Thank you for chiming in. I'd like this to be maybe clarified in the Specs (additionally to being fixed in Molten): should I open an issue on Vulkan-Docs and close this one (or do you have it from here on)? (Wouldn't hurt for the Validation to issue a warning, in the meantime...)

**Comment by jzulauf-lunarg** [comment]
@mark-lunarg  -- the warning would be a moltenvk specific best practices, yes?

**Comment by jzulauf-lunarg** [comment]
@FilippoLeon -- I don't think the spec is particularly unclear on this point.  The preferred workflow is for whoever wants a clarification to propose a spec edit.

**Comment by mark-lunarg** [comment]
If this can be fixed in MoltenVK, that's the preferred solution.  If not, it might be applicable to the new Portability extension (VK_KHR_portability_subset).

**Comment by jzulauf-lunarg** [comment]
@mark-lunarg @FilippoLeon  -- if I'm correct and this is a Molten issue, it should be fixed there.  As this is bookkeeping issue, implementations supported by portability should be able to support it, as it's independent of the underlying implementation.

**Comment by mark-lunarg** [comment]
Updated the MoltenVK issue above with findings, closing this for now.  Will reopen if any action on the part of the VL is needed.  Thanks!
