### ISSUE TITLE
Remove redundant copy command implicit VU checks in non-generated StatelessValidation

### ISSUE THREAD

**Issue by sfricke-samsung** [KhronosGroup/Vulkan-ValidationLayers#2235]
From https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2209#discussion_r502051631

(@jackohound let me know if you plan to apply a PR fix, otherwise I am happy to fix this all up! Just don't want to have us overlap work if you started)

There are various `VkImageAspectFlags` checks in `parameter_validation_utils.cpp` and `buffer_validation.cpp` that shouldn't be there check. The spec has 2 implicit VUs

> aspectMask must be a valid combination of VkImageAspectFlagBits values
>
> aspectMask must not be 0

And this is already checked in `parameter_validation.cpp` via `validate_flags`, so these shouldn't be attempted else where as if a new `VkImageAspectFlags` came out tomorrow, there would be a lot of bugs and headaches with the current flow

So my purposed actions are

1. ~~Remove the checks in `parameter_validation.cpp`~~ COMPLETE
- ~~manual_PreCallValidateCmdCopyImage~~
- ~~manual_PreCallValidateCmdBlitImage~~
- ~~manual_PreCallValidateCmdCopyBufferToImage~~
- ~~manual_PreCallValidateCmdCopyImageToBuffer~~

2. ~~Remove the checks in `buffer_validation.cpp`~~ COMPLETE
- `VUID-VkClearAttachment-aspectMask-parameter`
- `VUID-VkClearAttachment-aspectMask-requiredbitmask` 

3. ~~(Bonus/related)~~ DEFER, Comment below
Due to nature of the spec, `VUID-VkSubpassDescription2-attachment-02799` and `VUID-VkSubpassDescription2-attachment-02800` were made as explicit VUs and not implicit VUs, but are still stateless, just can't be generated. These two VUs should be moved out of `core_validation.cpp` and put into `parameter_validation_utils.cpp` and call `validate_flag`

4. (Bonus/related) Add missing `aspectMask` VUs as these are trivial to add next to the other VUs already (most were added from `VK_EXT_image_drm_format_modifier`)
~~- `VUID-VkBufferImageCopy2KHR-aspectMask-00212`~~
- `VUID-VkImageSubresourceRange-aspectMask-01670`
- `VUID-vkCmdClearAttachments-aspectMask-02502`
- `VUID-vkCmdClearAttachments-aspectMask-02503`

related to `VK_IMAGE_ASPECT_MEMORY_PLANE_i_BIT_EXT`
- `VUID-VkClearAttachment-aspectMask-02246`
- `VUID-VkImageSubresourceLayers-aspectMask-02247`
- `VUID-VkImageSubresourceRange-aspectMask-02278`
- `VUID-VkInputAttachmentAspectReference-aspectMask-02250`

Need adjust `ValidateBufferImageCopyData` to handle `{imageparam}` from spec
- `VUID-VkCopyBufferToImageInfo2KHR-aspectMask-00211`
- `VUID-VkCopyBufferToImageInfo2KHR-aspectMask-01560`
- `VUID-VkCopyImageToBufferInfo2KHR-aspectMask-00211`
- `VUID-VkCopyImageToBufferInfo2KHR-aspectMask-01560`
- `VUID-vkCmdCopyImageToBuffer-aspectMask-00211`
- `VUID-vkCmdCopyImageToBuffer-aspectMask-01560`

**Comment by jackohound** [comment]
#2236 is the follow-up to #2209, and should address (1) from above.

**Comment by sfricke-samsung** [comment]
@jackohound Awesome! Sounds good, will take on 2, 3 and 4

**Comment by sfricke-samsung** [comment]
Note: Currently `3` is not possible due to not being able to grab `AllVkImageAspectFlagBits` from `parameter_validation_utils.cpp` or `stateless_validation.h` so I feel for now it should just be fine
