### ISSUE TITLE
Validation layers don't validate descriptor updates against variable descriptor counts

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-ValidationLayers#2238]
If a descriptor set layout is created with `VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT_EXT` for a binding, it should have a `VkDescriptorSetVariableDescriptorCountAllocateInfo` struct passed along at create time.

This is processed currently and stored in `cvdescriptorset::DescriptorSet::variable_count_` but this only seems to be used for e.g. limiting the amount of validation that happens at draw time in `ValidateDescriptorSetBindingData`.

In particular it doesn't validate that descriptor updates happen within the allocated range. If a write happens to a descriptor binding which is past the end of the variable count but before the size declared in the layout, there won't be an error. This is particularly important if the `VkDescriptorSetVariableDescriptorCountAllocateInfo` struct is omitted, because then the variable count becomes 0.

I think in the `cvdescriptorset::DescriptorSet` constructor the variable count should be applied to limit the bindings created - though I don't know off hand how many places check the *layout* descriptorCount and how many check the *descriptor set* allocated count. If not for this variable alloc feature it's easy to interchange the two as they should be equal.

Note this would also help in cases where the layout declares a very large upper bound but each descriptor set allocated has a significantly smaller variable allocation count. In that case currently the validation layers overallocate heavily on descriptor storage leading to a lot of CPU memory overhead (and wasted processing during alloc).

**Comment by Tony-LunarG** [comment]
Fixed with #2270
