### ISSUE TITLE
Bug in input attachment validation

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-ValidationLayers#2243]
A recent [roll into ANGLE][1] is exposing a VVL bug that says:

```
[ VUID-vkCmdDraw-None-02686 ] Validation Error: [ VUID-vkCmdDraw-None-02686 ] Object 0: handle = 0x555ebb092460, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0x6a000000006a, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x242cb6b8 | vkCmdDraw(): Fragment Shader's input attachment index #0 doesn't exist or VK_ATTACHMENT_UNUSED in VkRenderPass 0x6a000000006a[], subpass #0. The Vulkan spec states: Every input attachment used by the current subpass must be bound to the pipeline via a descriptor set (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdDraw-None-02686)
```

To repro, apply [this change][2] to ANGLE, build and run:

```
$ ./angle_end2end_tests --gtest_filter=MultisampledRenderToTextureTest.2DColorAttachmentMultisampleDrawTest/ES3_Vulkan
```

In the above test, there's a single color attachment / resolve attachment pair. In the second render pass, there are two subpasses. The first of the two subpasses uses the resolve attachment as input attachment and renders into the color attachment. Subpass' `pInputAttachments` is not `VK_ATTACHMENT_UNUSED`, and the draw call binds the input attachment at set 0 binding 0 correctly. I verified these with RenderDoc.

[1]: https://chromium.googlesource.com/external/github.com/KhronosGroup/Vulkan-ValidationLayers.git/+log/7d11021098f2..8c5a10d952f4
[2]: https://chromium-review.googlesource.com/c/angle/angle/+/2484732

**Comment by snowman791** [comment]
I have a similar problem:

Validation Error: [ VUID-vkCmdDraw-None-02686 ] Object 0: handle = 0x26956baba10, name = CommandBuffer: 0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0x9c93ec00000001c2, name = Render Pass: result, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x242cb6b8 | vkCmdDraw(): VkRenderPass 0x9c93ec00000001c2[Render Pass: result], subpass #0, input attachment #1 is not used in fragment shader.  Every input attachment used by the current subpass must be bound to the pipeline via a descriptor set

in the fragment shader the input is defined as array if  subpassInputs, and not separated:

layout (input_attachment_index = 0, set = 0, binding = 0) uniform subpassInput inputColor[3];

**Comment by jonahryandavis** [comment]
This issue is still happening even with the above fix.
Examples documented here: https://bugs.chromium.org/p/angleproject/issues/detail?id=5228

**Comment by ShabbyX** [comment]
Wrong bug Jonah! This comment should have been on #2148.

**Comment by locke-lunarg** [comment]
@jonahryandavis  @ShabbyX 

I'm confused. Why is the error message is VkNonDispatchableHandle? It should have been VkPipelineLayout.

**Comment by ShabbyX** [comment]
@locke-lunarg it may be a false alarm. I had a change that fixes a pipeline-binding bug which was probably the cause of this validation error.

**Comment by ShabbyX** [comment]
@locke-lunarg Confirmed that the warning was actually due to an ANGLE bug.
