### ISSUE TITLE
No validation error on vkCmdBuildAccelerationStructureNV called twice on top level VkAccelerationStructureKHR without VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_UPDATE_BIT_NV

### ISSUE THREAD

**Issue by obhi-d** [KhronosGroup/Vulkan-ValidationLayers#2253]
Hello,

I notice that vkCmdBuildAccelerationStructureNV called on a top level VkAccelerationStructureKHR without the VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_UPDATE_BIT_NV flag a second time (after updating the instance buffer again) do not throw any validation error. The result is undefined behaviour as I discovered though a very hard to find bug, which caused a random driver crash. It might be useful to add this check in validation layer.
The workflow that resulted in the bug was:
->Create a TLAS and Build it (without VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_UPDATE_BIT_NV)
->Use it for few frames
->Compact all BLAS, after a few frames delay
->Rebuild the TLAS with the compacted BLAS (keep the original TLAS, just update the instance buffer and call build)
->Random crash when this TLAS is used by a DescriptorSet.
Expected:
->Validation error when second build is called.

Thanks,
-obhi

**Comment by mark-lunarg** [comment]
@jmacnak, @souravpNV, there doesn't seem to be a VUID for this particular case.

**Comment by souravpNV** [comment]
@mark-lunarg, I will check internally for this.

**Comment by mark-lunarg** [comment]
@souravpNV, is there any new information?

**Comment by souravpNV** [comment]
Sorry, I lost track of this, I checked with Eric and there is some confusion, as per Eric If the “Rebuild the TLAS” doesn’t have the update flag set, then it sounds like that should be legal, but I can’t tell either way from what he’s saying.
Adding @ewerness-nv  here directly

**Comment by obhi-d** [comment]
I wanted to add that, in Nsight, the AccelerationStructure appears invalid in this case. Which is why I tried to recreate the TLAS, and it seemed to be working after that.

**Comment by spencer-lunarg** [comment]
sorry this has got stale, between the fact that `VK_KHR_ray_tracing_pipeline` was added since this issue as well as `VK_NV_ray_tracing_validation` and the fact there has been a LOT of refactoring in the last year alone for the CPU side ray tracing checks, I am going to close this.

If there is still a reproducible issue, happy to take a look in a new issue, but this has sat around and probably won't get addressed in its current state
