### ISSUE TITLE
error: ‘OpAtomicFAddEXT’ is not a member of ‘spv’

### ISSUE THREAD

**Issue by kyrios123** [KhronosGroup/Vulkan-ValidationLayers#2254]
Hello,

Since commit 25b6c3575f3816ff8268d4269d274b808830b642 I get the following error when building Vulkan-ValidationLayers. What did I miss ?
```
../layers/shader_validation.cpp: In function ‘bool AtomicOperation(uint32_t)’:
../layers/shader_validation.cpp:853:19: error: ‘OpAtomicFAddEXT’ is not a member of ‘spv’; did you mean ‘OpAtomicIAdd’?
  853 |         case spv::OpAtomicFAddEXT:
      |                   ^~~~~~~~~~~~~~~
      |                   OpAtomicIAdd
```

**Comment by mark-lunarg** [comment]
can you try rerunning `update_deps.py` or updating your `glslang/SPIRV-Headers` dependencies?

**Comment by kyrios123** [comment]
I updated `glslang` to [SDK-candidate-26-Jul-2020](https://github.com/KhronosGroup/glslang/releases/tag/SDK-candidate-26-Jul-2020) instead of [stable release April 27, 2020](https://github.com/KhronosGroup/glslang/releases/tag/8.13.3743) and it works.

It would be nice to have a consistent toolchain. The sdk-1.2.154.0 is a stable version so it shouldn't rely on release candidate/unreleased glslang. At least for the SDK versions of Vulkan, SPIRV/glslang release should be tagged if needed !
Just my 2 cents.

**Comment by mark-lunarg** [comment]
You are right, and there are efforts in progress to reduce these frustrations but it is a complex issue and we are sorry for any confusion.
