### ISSUE TITLE
AHardwareBuffer_describe symbol missing in latest release

### ISSUE THREAD

**Issue by Izhido** [KhronosGroup/Vulkan-ValidationLayers#2287]
Attempting to include the validation layers in the latest release, in a project that targets Android 25, generates the following message:

E/vulkan: failed to load layer library '/data/app/com.blablabla.myapp/lib/arm64/libVkLayer_khronos_validation.so': dlopen failed: cannot locate symbol "AHardwareBuffer_describe" referenced by "/data/app/com.blablabla.myapp/lib/arm64/libVkLayer_khronos_validation.so"...

Interestingly enough, this error also happens with the validation layers that are included in the latest Android SDK - the main reason I went to look for the latest release of the layers was precisely this error message.

**Comment by mark-lunarg** [comment]
@Izhido, in the past, issues like this have been because a version of Android was used that was not current enough (I believe this symbol was added in Android 'O', or Oreo).  Android 25 should be fine however.  Can you enumerate the NDK version you are using?  Thanks!

**Comment by Izhido** [comment]
Sure. I'm currently on NDK 21.3.6528147, which incidentally is the version (I believe) the latest release was compiled against.

Being stuck in Android 25 in my device has given me no small grief - Android Studio offers a fully featured native code profiler which I'd love to use for my app - problem is, the "native code" part of it is enabled for Android 26 and later :(

**Comment by mark-lunarg** [comment]
@Izhido, i'm certainly not an Android expert, but am confident that the validation layers (and the latest Android and Android SDK versions) support this symbol.  The only other thing I can think of might be the setting of APP_PLATFORM in your Application.mk file -- what might that be?

**Comment by Izhido** [comment]
Interesting point. My project **does not** include APP_PLATFORM in its own Application.mk. However, there is one Application.mk at root level in the Oculus Mobile SDK, which includes the following:

```
# NOTE: These properties are ignored for any libraries or applications
# using the externalNativeBuild path. This file can go away, once
# remaining usage can be stripped from test libraries and applications.

# This needs to be defined to get the right header directories for egl / etc
# NOTE: this is ignored from here now, and must be specified in build.gradle!
APP_PLATFORM := android-24
```

**Comment by mark-lunarg** [comment]
@Izhido, I would think that android-24 should be sufficient.  I'm sorry but I don't think we can be of much more help with application issues.  The layers included in the latest Android SDK have been tested and cleared by the Android folks, so they are not seeing this issue.  Likewise, have seen no issues with our Android testing including AHardwareBuffer-specific tests.

**Comment by mark-lunarg** [comment]
@Izhido, just heard from the Android folks.  I (as I suspected) was wrong, AHardwareBuffer was not [introduced until Android 26](https://en.wikipedia.org/wiki/Android_version_history#Android_8.0_Oreo_(API_26)
) (Oreo), so to use any layers built since that time you'd need to target a newer API level.

**Comment by sfricke-samsung** [comment]
So the issue is the Validation Layers need to be built without using AHB just like when its built for Windows/Linux.

in [android_ndk_types.h](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/android_ndk_types.h) we should have wrapping around so if you set the [APP_PLATFORM](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/build-android/jni/Application.mk#L18) to `android-25` it "should" build the Validation Layers without any of the AHardwareBuffer checks, but I see it fails to build, mainly cause no one has really seemed to ask for this (my guess).

I think the proper/simple solution is the to update the AHB areas from

```cpp
#ifdef VK_USE_PLATFORM_ANDROID_KHR
```

to 

```cpp
#if defined(VK_USE_PLATFORM_ANDROID_KHR) && !defined(__ANDROID_API_N__)
```

It would allow you change `APP_PLATFORM` and then build the Validation Layers for Android 24 (which would work for Android-25 as well)

**Comment by mark-lunarg** [comment]
@sfricke-samsung, thanks, this explains a lot.  I think we could update the build to work correctly as you suggest.  I don't see new releases being made for the old Android versions, but they could still be built if needed.

**Comment by sfricke-samsung** [comment]
@mark-lunarg did you want me to make the PR for the macros then (happy to do so)? 

As for adding a build to CI or release, it actually easy as you should be able to just append `APP_PLATFORM=android-24`to the [ndk-build](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/build-android/build_all.sh#L63) command to build it for "pre-AHB" 

Note: Android 24 is the first version that supports Vulkan so its the true minimal

**Comment by mark-lunarg** [comment]
The repo is required to have the latest version (matching the SDK-release) available on Github for the Android binary releases. I'd still prefer updating the docs for users who need the the pre-AHB versions (@Izhido is the second person in four years AFACT!).  A PR would be GREATLY appreciated!  The AHB stuff was all added before hardware was available, so it's a bit shaky as you have noticed.

**Comment by sfricke-samsung** [comment]
Sounds good to me. I should have a PR up tomorrow with both the fixes the way to build it in the BUILD.md

The we can have @Izhido test it to confirm it satisfies this issue

**Comment by mark-lunarg** [comment]
This is super -- you guys are great!

**Comment by Izhido** [comment]
Concur. Let me know when to start testing.

I guess the intersection of the Venn diagram of “people who do Vulkan” vs “people who code for Oculus Quest” vs “people who use validation layers” is pretty small...

**Comment by Izhido** [comment]
Just tested the new build generated from the PR above, successfully. The validation layer lib works now as expected!
