### ISSUE TITLE
RPCS3 emulator Vulkan error: CHECK_RESULT for vkCreateDevice VK_ERROR_FEATURE_NOT_PRESENT 

### ISSUE THREAD

**Issue by birdcat87** [KhronosGroup/Vulkan-ValidationLayers#2289]
This error has occurred for the last several months of RPCS3 software releases, and the same line of code creates the problems every time.  So when I try to play Demon Souls using Vulkan (the problem doesn't occur in OpenGL), I get:

RPCS3 Error Page:
(https://user-images.githubusercontent.com/73905602/98024987-06093780-1e01-11eb-967a-251f73e25b9a.png)

The line of code referenced is (used to be line 1001 in prior releases of RPCS3):
https://github.com/RPCS3/rpcs3/blob/088931525d0dbdf0cce92608dacc6448c0ede2a8/rpcs3/Emu/RSX/VK/VKHelpers.h#L1017

Which reads out: CHECK_RESULT(vkCreateDevice(*pgpu, &device, nullptr, &dev));

My vulkaninfo:
[vulkaninfo2.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/5483245/vulkaninfo2.txt)

Thus it seems the issue isn't with the RPCS3 software itself, but my driver not supporting features of Vulkan, thus being within the scope of this repository.  If you could help me narrow down the exact features that aren't supported that are causing this issue and help me find a solution, I would be very grateful.  If sending this type of support request isn't allowed in this Github repository due to not being a legitimate bug within the ValidationLayers itself, then if you could redirect me to a better place to ask these questions, than I would also appreciate it.

**Comment by mark-lunarg** [comment]
@birdcat87, Vulkan provides API support to query hardware platforms for supported extensions, features, and limits.  Attempting to create a device object with invalid combinations of them would certainly produce a result such as you are seeing.

Are the validation layers loaded when the application generates this error?  If so, could you include the output from the layers before encountering this error?  If you are not running with the validation layers, it is likely they would tell you what the problem is.

**Comment by birdcat87** [comment]
Thank you, @mark-lunarg for responding so quickly and helpfully! 

I have version 1.2.154.0 of vulkan-validation-layers installed on my Linux computer, but unfortunately I don't know how to actually run or get the output from the validation layers.  I have some command line experience (I can use cat to get the output of a file, then pipe it to grep to search for a word) but I have no real experience with working with Vulkan other than as a end user having an application run it and the internet research I did to try to figure out this problem.  

Sorry for posting this to here when I lack developer knowledge of Vulkan, @mark-lunarg. I just wanted to figure out the root of this problem.  

 If you could explain how to load and read the output of the validation layers step by step (or if it has a log file, tell me the folder path to it), or link to a tutorial that does so, that would be very helpful.

**Comment by mark-lunarg** [comment]
@birdcat87, as we are desperately short of bandwidth I am only able to point you to the [Vulkan SDK Documentation](https://vulkan.lunarg.com/doc/sdk/1.2.154.1/windows/layer_configuration.html), which has information about configuring and using the layers.  Perhaps Reddit or maybe the Vulkan Slack channel might be of help, but I am confident that once you fix the issues discovered by validation you have a clear path forward.
