### ISSUE TITLE
Render pass area is not inherited to secondary command buffers

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#23]
**Issue by [phaulos](https://github.com/phaulos) (MIGRATED)**
_Monday Mar 20, 2017 at 16:45 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1601_

----

CTS test `dEQP-VK.api.command_buffers.render_pass_continue` is failing with:

```
ERROR: vkCmdClearAttachments(): The area defined by pRects[0] is not contained in the area of the current render pass instance. For more information refer to Vulkan Spec Section '17.2. Clearing Images Inside A Render Pass Instance' which states 'The rectangular region specified by a given element of pRects must be contained within the render area of the current render pass instance' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#vkCmdClearAttachments) (code 0x0000045b from DS at Unknown:1475)
```

It seems that the issue is that render area is not inherited from primary command buffer to the secondary buffer where `vkCmdClearAttachments` is issued.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/chrisforbes"><img src="https://avatars1.githubusercontent.com/u/128877?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Tuesday Mar 21, 2017 at 22:53 GMT_

----

Difficult to do a good job here -- render area isn't included in VkCommandBufferInheritanceInfo, so we're never going to know it in a secondary command buffer at recording time.

Have to defer either to CmdExecuteCommands, or QueueSubmit, like some other recently adjusted checks.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/karl-lunarg"><img src="https://avatars2.githubusercontent.com/u/16430219?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [karl-lunarg](https://github.com/karl-lunarg) (MIGRATED)**
_Wednesday Mar 22, 2017 at 18:00 GMT_

----

There's a similar issue in LunarG's LunarXchange ([654](https://vulkan.lunarg.com/issue/view/58b4083666315130fe3c2d78)).  Probably exactly the same.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/phaulos"><img src="https://avatars2.githubusercontent.com/u/295496?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [phaulos](https://github.com/phaulos) (MIGRATED)**
_Wednesday Mar 22, 2017 at 18:01 GMT_

----

If possible it would be best to do the check in vkCmdExecuteCommands(). At
that point the primary command buffer has seen vkCmdBeginRenderPass() and
knows the render area. That is also off the critical path, unlike
vkQueueSubmit().

**Comment by jzulauf-lunarg** [comment]
Triage notes: see discussion above.  First step would be to verify the bug still exists vs. the CTS test case.

**Comment by locke-lunarg** [comment]
The error doesn't happen in `dEQP-VK.api.command_buffers.render_pass_continue` of CTS with `Vulkan SDK 1.1.101.0`, and `VkPositiveLayerTest.ConfirmNoVLErrorWhenVkCmdClearAttachmentsCalledInSecondaryCB` passes. So could we close the issue?

**Comment by jzulauf-lunarg** [comment]
@phaulos -- this appears to be resolved, ok to close?

**Comment by krOoze** [comment]
@mark-lunarg fixed, per the test?
