### ISSUE TITLE
Crash and false reports when using push constants.

### ISSUE THREAD

**Issue by Facundo961** [KhronosGroup/Vulkan-ValidationLayers#2313]
I've recently encountered an error when using push constants.

I have several pipeline layouts describing different sets and bindings and everything works fine, but when I try to add a push constant to the first pipeline layout (or anyone of them for that matter) the validation layers crash at vkCmdDrawIndexed() time while de-referencing a descriptorSet pointer and reports an error through debug utils saying one or two of my descriptor sets are not bound (when they actually are, I checked by not using push constants)
I then disabled the validation layers and tested the code (with push constants) which worked as expected and did not cause any problems.

I'm running on Windows10 64-bit, NVIDIA Beta Vulkan Driver v.457.17, LunarG SDK v.1.2.154.1

**Comment by mark-lunarg** [comment]
@Facundo961, this validation is currently passing tests and we're unaware of other outstanding reports.  Could you please share a repro case along with the shaders in question?

**Comment by Facundo961** [comment]
**Vertex Shader:**
```
#version 460

layout(std140, row_major) uniform;
layout(std140, row_major) buffer;

layout(set = 0, binding = 0) uniform sampler2D img[];

//set = 1, render pass data

layout(set = 2, binding = 0) buffer StaticMeshRenderGroupData
{
	mat4 MVP[];
} renderGroupData;

layout(push_constant) uniform InvocationInfo
{
	uint Pass;
	uint RenderGroup;
	uint Material;
	uint Object;
} invocationInfo;

layout(location = 0) in vec3 vertexPosition;
layout(location = 1) in vec3 vertexNormal;
layout(location = 2) in vec3 vertexTangent;
layout(location = 3) in vec3 vertexBiTangent;
layout(location = 4) in vec2 vertexTextureCoords;

layout(location = 0) out vertexShaderOut
{
	vec2 texCoords;
} vertexOut;

void main()
{
	gl_Position = renderGroupData.MVP[invocationInfo.Object] * vec4(vertexPosition, 1.0);
	vertexOut.texCoords = vertexTextureCoords;
}
```

**Fragment Shader:**
```
#version 460

#extension GL_EXT_nonuniform_qualifier : enable

layout(std140, row_major) uniform;
layout(std140, row_major) buffer;

layout(set = 0, binding = 0) uniform sampler2D img[];

//set = 1, render pass data

layout(set = 2, binding = 0) buffer StaticMeshRenderGroupData
{
	mat4 MVP[];
} renderGroupData;

layout(set = 3, binding = 0) buffer StaticMaterialData
{
	uint Albedo;
} staticMaterialData;

//layout(set = 3, binding = 0) uniform DynamicMaterialData
//{
//	vec4 Color;
//} materialData;

layout(location = 0) out vec4 fragmentColor;

layout(location = 0) in vertexShaderOut
{
	vec2 texCoords;
} vertexIn;

void main()
{
	fragmentColor = texture(img[nonuniformEXT(staticMaterialData.Albedo)], vertexIn.texCoords);
	//fragmentColor = vec4(float(staticMaterialData.Albedo));
}
```

Those are the shaders. And I'm sorry I'm still quite new to this but what do you mean by a repro case? Thanks!

**Comment by mark-lunarg** [comment]
Sorry about that, it'd be a simple test case that we could compile and run to reproduce the issue and find the errors.

**Comment by Facundo961** [comment]
Ok. Would a generated CPP from a frame capture suffice? Because the application is part of an engine that is not quite ready to be built on another machine. Or would an executable for the final app be ok?

**Comment by mark-lunarg** [comment]
@Facundo961, the CPP-framecap (maybe with buildtips) would be great, or the exe, as long as it'll run on Win10/VS2019 -- either would be a huge help!

**Comment by Facundo961** [comment]
I've finished prepping up the [executable](https://drive.google.com/file/d/1VtKEp0GJIACigHUWKCnegDLWcEnzb6lZ/view?usp=sharing). Please tell me if that works. In the Debug-x64 folder, you'll find a setings.ini file. You can toggle validation on and off with the debug parameter, and you can toggle push constant use or dynamic buffer use with the "usePushConstants" setting. If needed you can find last run's logs in the log.txt file. You can also check out the shaders inside the resources folder, the shaders being used are the HydrantMat.vs/fs and TvMat.vs/fs. (VS = vertex shader, FS = fragment shader)

Make sure to ask for anything else you might need!

**Comment by Facundo961** [comment]
Also, runtime crashes inside this function.

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/d0de1f88d802f42d911cf4e77fb85e4cca5cbac9/layers/synchronization_validation.cpp#L1519

**Comment by mark-lunarg** [comment]
@Facundo961, this is greatly helpful, thanks.  A couple more questions please:  Can you include the error message, and from the crash location it sounds like you also have synchronization validation enabled?

**Comment by Facundo961** [comment]
These are the errors:

```
Counter: 134, Thread: 3, [Date: 16/11/2020][Time: 12:47:11]RenderSystem: Validation Error: [ UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotBound ] Object 0: handle = 0x2da1fb40498, name = Graphics command buffer. Frame: 1, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xcde11083 | VkPipeline 0xaf4278000000005d[Raster pipeline. Material: 11946071746173283494] uses set #2 but that set is not bound.
Counter: 135, Thread: 3, [Date: 16/11/2020][Time: 12:47:11]RenderSystem: Validation Error: [ UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotBound ] Object 0: handle = 0x2da1fb40498, name = Graphics command buffer. Frame: 1, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xcde11083 | VkPipeline 0xaf4278000000005d[Raster pipeline. Material: 11946071746173283494] uses set #0 but that set is not bound.
```


> @Facundo961, this is greatly helpful, thanks. A couple more questions please: Can you include the error message, and from the crash location it sounds like you also have synchronization validation enabled?

That's also strange I have recently enabled synchronization validation and that's what that app shipped with, but the error also appeared before I included sync validation.

Also, [here's](https://github.com/Game-Tek/Byte-Engine/blob/bef5e785d0e9de80e9f6ac528dd1cf1fdbdf6cdd/ByteEngine/src/ByteEngine/Render/RenderOrchestrator.cpp#L789) the main rendering function if you'd like to look at it.

**Comment by locke-lunarg** [comment]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/state_tracker.cpp#L3913

You can look at this code. I guess when you bind different descriptor sets, you use different pipeline layouts. Plus, those pipeline layouts have different pPushConstantRanges, so they are not compatibility, as a result, the validation layers clean the other descriptor sets to cause null and crash and UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotBound.

https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#descriptorsets-binding
`Each of the pDescriptorSets must be compatible with the pipeline layout specified by layout. The layout used to program the bindings must also be compatible with the pipeline used in subsequent bound pipeline commands with that pipeline type, as defined in the Pipeline Layout Compatibility section.`

**Comment by mark-lunarg** [comment]
@Facundo961, can you take a look and see if the new information can help you with the issue?

**Comment by Facundo961** [comment]
@locke-lunarg You are absolutely right, that's what was happening. Only some of the pipeline layouts were compatible in regards to the push constant ranges. Thank you guys. I'm sorry I opened the issue but I would have never realized that myself.

**Comment by mark-lunarg** [comment]
@Facundo961, added [an item](https://github.com/KhronosGroup/Vulkan-ValidationLayers/projects/1#card-49642560) to the best practices project which might help to provide the info you'd have needed to track down the source of the unbound descriptorSets.
