### ISSUE TITLE
syncval: is it possible to validate host read after shader write?

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-ValidationLayers#2329]
Take the following scenario:

1. A host-visible buffer is created and bound
2. A compute shader writes to this buffer
3. `vkInvalidateMappedMemoryRanges` is called
4. The host reads back from the buffer

Between steps 2 and 3, there should be a pipeline barrier from (COMPUTE_SHADER,SHADER_WRITE) -> (HOST,HOST_READ). Is there a way syncval can validate this?

**Comment by jzulauf-lunarg** [comment]
@ShabbyX -- host synchronization after multi-command buffer on the plan.

**Comment by jzulauf-lunarg** [comment]
Added to https://github.com/KhronosGroup/Vulkan-ValidationLayers/projects/5#card-48793604
