### ISSUE TITLE
Installing copies non-SDK files to installation directory

### ISSUE THREAD

**Issue by danielmaciel** [KhronosGroup/Vulkan-ValidationLayers#233]
Installing now is copying *source code* into the install directory. Source code that is not going to be used by an end user at all.

To make matters worse, it copies them inside the root 'include' directory. I am really confused as to why is this happening, but it sure has been added deliberately.

I would recommend making this step optional if this is something needed by other repos. It certainly is not in the interest of anyone using the validation layer binaries.

This is what is causing the issue, inside layers/CMakeLists.txt ...

```
# Configure installation of source files that are dependencies of other repos.
set(LAYER_UTIL_FILES
   hash_util.h
   hash_vk_types.h
   vk_format_utils.h
   vk_format_utils.cpp
   vk_layer_config.h
   vk_layer_config.cpp
   vk_layer_data.h
   vk_layer_extension_utils.h
   vk_layer_extension_utils.cpp
   vk_layer_logging.h
   vk_layer_utils.h
   vk_layer_utils.cpp
   vk_loader_layer.h
   vk_loader_platform.h
   vk_validation_error_messages.h
   ${PROJECT_BINARY_DIR}/vk_layer_dispatch_table.h
   ${PROJECT_BINARY_DIR}/vk_dispatch_table_helper.h
   ${PROJECT_BINARY_DIR}/vk_safe_struct.h
   ${PROJECT_BINARY_DIR}/vk_safe_struct.cpp
   ${PROJECT_BINARY_DIR}/vk_enum_string_helper.h
   ${PROJECT_BINARY_DIR}/vk_object_types.h
   ${PROJECT_BINARY_DIR}/vk_extension_helper.h
   ${PROJECT_BINARY_DIR}/vk_typemap_helper.h
   )
install(FILES ${LAYER_UTIL_FILES} DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
```

**Comment by jeremy-lunarg** [comment]
This is an artifact of recent repo restructuring. I'll make it an option but I won't get to it right away.

**Comment by jengelh** [comment]
Installation still copies `libVkLayer_utils.a`, but which is probably useless now that there is no more header files installed by default to get at the function declarations.
