### ISSUE TITLE
syncval bug w.r.t depth/stencil attachments that use storeOp=DONT_CARE

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-ValidationLayers#2333]
To reproduce:

- Take ANGLE and apply the following patches:
  * An optimization to avoid storeOp=STORE (if not landed): https://chromium-review.googlesource.com/c/angle/angle/+/2548319
  * Enable syncval: https://chromium-review.googlesource.com/c/angle/angle/+/2297884
- Run `./angle_deqp_gles3_tests --deqp-case=dEQP-GLES3.functional.fbo.blit.default_framebuffer.r8`
- Observe validation errors

The above test produces this trace [1]:

- RP with depth/stencil attachment X with loadOp=DONT_CARE, storeOp=DONT_CARE
  * X uses `VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL`
  * There's a draw call in this RP, but has depth/stencil disabled
- Unrelated RP
- Another RP with X with loadOp=DONT_CARE, storeOp=DONT_CARE
  * X uses `VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL`
  * There's a draw call in this RP, but has depth/stencil disabled
- An image layout transition from `DEPTH_STENCIL_READ_ONLY` to `DEPTH_STENCIL_ATTACHMENT`
  * src and dst stages include both early and late fragment tests
  * src access is 0
  * dst access includes `DEPTH_STENCIL_ATTACHMENT_READ/WRITE`

There's a syncval validation in the above image layout transition:

```
[ SYNC-HAZARD-WRITE_AFTER_WRITE ] Validation Error: [ SYNC-HAZARD-WRITE_AFTER_WRITE ] Object 0: handle = 0x120000000012, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0xfdf9f5e1 | vkCmdPipelineBarrier: Hazard WRITE_AFTER_WRITE for image barrier 0 VkImage 0x120000000012[]. Access info (usage: SYNC_IMAGE_LAYOUT_TRANSITION, prior_usage: SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE, write_barriers: 0, command: vkCmdEndRenderPass, seq_no: 12, reset_no: 1).
```

I believe this to be an error. There was never a write to D/S in this test.

**Environment:**
 - OS: Linux
 - GPU: Nvidia

**Comment by ShabbyX** [comment]
[1]: RenderDoc capture: https://drive.google.com/file/d/1ERMNFR8STZPXx6b8E-ZUA823TBzJhkHZ/view

**Comment by jzulauf-lunarg** [comment]
@ShabbyX  -- 

Note the difference between DONT_CARE and the vendor specific NONE extension.  It's not guaranteed that store will or won't happen, and validation cannot depend on implementation dependent behavior.  NONE guarantees NONE, but is not supported in SyncVal at this time.  If you think this is incorrect, I recommend a spec issue to clarify.

> VK_ATTACHMENT_STORE_OP_DONT_CARE specifies the contents within the render area are not needed after rendering, and *may* be discarded; the contents of the attachment will be undefined inside the render area. For attachments with a depth/stencil format, this uses the access type VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT. For attachments with a color format, this uses the access type VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT.

> VK_ATTACHMENT_STORE_OP_NONE_QCOM specifies that the contents within the render area were not written during rendering, and may not be written to memory. If the attachment was written to during the renderpass, the contents of the attachment will be undefined inside the render area.

**Comment by ShabbyX** [comment]
@jzulauf-lunarg Thank you, I had missed that!

This is somewhat related, and maybe you can shed light on it too. Take the following situation:

- Transition D/S image to DEPTH_STENCIL_READ_ONLY
- Start render pass with D/S storeOp = DONT_CARE
- Draw, with D/S test enabled, but write disabled
- Draw, with D/S test disabled, but D/S image is sampled from in the shader
- End render pass

The above generates a READ-AFTER-WRITE (read from shader, write to attachment) error in syncval, and if I understand it correctly it's because of the two draw calls where syncval assumes the first draw call is writing to D/S because of storeOp=DONT_CARE, while in reality D/S write is disabled (and the layout is read-only anyway). Is that per spec or a bug?

**Comment by jzulauf-lunarg** [comment]
@ShabbyX   It's possible we aren't tracking the d/s read/write enables correctly ... can you open this as a separate issue?

Note that the image layout transition and the store op will still be treated as writes, so there may need to be dstAccessMask to protect the store from the transition.

**Comment by ShabbyX** [comment]
Will do.
