### ISSUE TITLE
Is it useful to warn about VK_ERROR_OUT_OF_DATE_KHR being returned from vkQueuePresentKHR?

### ISSUE THREAD

**Issue by expipiplus1** [KhronosGroup/Vulkan-ValidationLayers#2335]
**Describe the Issue**

When I resize the window which holds the surface to which my application is presenting `vkQueuePresentKHR` returns `VK_ERROR_OUT_OF_DATE_KHR` as expected, and the validation layer prints:

`Validation: Validation Warning: [ UNASSIGNED-BestPractices-Error-Result ] Object 0: handle = 0x120e3b0, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x5f379b89 | vkQueuePresentKHR(): Returned error VK_ERROR_OUT_OF_DATE_KHR.`

On the one hand this is an error, however it's not due to misuse of the API, it's a quite normal part of program operation.

Similarly for: return codes `VK_ERROR_SURFACE_LOST_KHR` and `VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT` and any other swapchain command

**Valid Usage ID**

`UNASSIGNED-BestPractices-Error-Result`

**Environment:**
 - OS: Linux 5.4.77
 - GPU: 2080 Ti, nvidia-455.38
 - SDK or header version if building from repo: `sdk-1.2.141.0`
 - Options enabled (synchronization, best practices, etc.): `VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT`

**Comment by mark-lunarg** [comment]
@expipiplus1, you are absolutely right, this is normal usage and operation.  This is why the check is outside the standard validation and part of Best Practices validation.  The point of BP is to warn of API usage that is technically valid but may be inefficient, unnecessary, or unintended.  It is common for developers to fail to check return codes and this layer warns on all non-success return codes for this reason.  You can disable BP and still get Real™️ validation errors, or you can use **VkConfig** or the `message_id_filter` option to suppress noisy or unwanted messages.  Hope this helps!

**Comment by expipiplus1** [comment]
Thank you for the useful reply

> may be inefficient, unnecessary, or unintended

Do the cases above fit into any of these categories though?

> or you can use **VkConfig** or the `message_id_filter` option to suppress noisy or unwanted messages

Yeah, setting `khronos_validation.message_id_filter=UNASSIGNED-BestPractices-Error-Result` in `vk_layer_settings.txt` does suppress this message. In my case this is fine as I'm definitely checking everything, however it does seem like a large hammer, i.e. it's disabling cases where I might really want to know about errors.

Perhaps the validation layer should think about two categories of errors separately, ones which are part of normal operation and ones which do represent exceptional cases which a typical application isn't expected to explicitly case about.

An alternative would be being able to disable Error-Result messages specifically for combinations of commands and result values.

**Comment by mark-lunarg** [comment]
@expipiplus1, those are both great suggestions, and your issue generated a lot of sympathy in our team. I will add [both](https://github.com/KhronosGroup/Vulkan-ValidationLayers/projects/1#card-49789238) [items](https://github.com/KhronosGroup/Vulkan-ValidationLayers/projects/1#card-49789341) to the Best Practices project page in the hopes we can get to them in the near future.  Thanks!

**Comment by expipiplus1** [comment]
Thanks! And thanks for the hard work on such a useful tool!
