### ISSUE TITLE
ThreadSafety::...DeviceWaitIdle should treat all queues as being written to

### ISSUE THREAD

**Issue by jeffbolznv** [KhronosGroup/Vulkan-ValidationLayers#2336]
**Describe the situation in which you encountered the missing validation**
We got a bug report from a developer about a driver crash, which ended up being due to calling vkDeviceWaitIdle and vkQueueSubmit for one of that device's queues at the same time. ThreadSafety::{Pre,Post}CallRecordDeviceWaitIdle should call {Start,Finish}WriteObject on all queues belonging to the device.

**Valid Usage IDs requested**
UNASSIGNED-Threading-MultipleThreads

**Additional Context**
None

**Comment by ziga-lunarg** [comment]
@mark-lunarg This issue was fixed and can be closed correct?

**Comment by spencer-lunarg** [comment]
closing as https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2345 should have fixed this as stated
