### ISSUE TITLE
Message filtering via an env var

### ISSUE THREAD

**Issue by Joshua-Ashton** [KhronosGroup/Vulkan-ValidationLayers#2344]
Support for filtering message ids via an env var would be very useful.

**Comment by mark-lunarg** [comment]
Dude, try `VK_LAYER_MESSAGE_ID_FILTER`. Lemme know if it doesn't work for you.

**Comment by KarenGhavam-lunarG** [comment]
The Vulkan Configurator (vkconfig) included with the Vulkan SDK also enables message filtering.

**Comment by Joshua-Ashton** [comment]
I have tried this before and I thought it didn't work, but it turns out it's only filtering out the first one I have specified.

(I am doing `set VK_LAYER_MESSAGE_ID_FILTER=0x682a878a,0x99fb7dfd`, I have tried both with and without quotes)

The Vulkan Configurator's message filtering option and layer injection doesn't work at all on my machine, even with applications I start through it's own launcher.

**Comment by KarenGhavam-lunarG** [comment]
> The Vulkan Configurator's message filtering option and layer injection doesn't work at all on my machine, even with applications I start through it's own launcher.

It's best for us to resolve this. Can you submit an issue to LunarG/VulkanTools detailing more about your usage so that we can resolve it?

**Comment by Joshua-Ashton** [comment]
I will try this later today before ensuring it wasn't a PEBKAC

**Comment by mark-lunarg** [comment]
@Joshua-Ashton, I'm guessing you're on Windows?  Please lemme know and I'll check into it right away.

**Comment by Joshua-Ashton** [comment]
Yes, I am using Windows right now on the latest Vulkan SDK

**Comment by Joshua-Ashton** [comment]
It also occurs with `vulkan-validation-layers 1.2.158-1` on Arch.

**Comment by mark-lunarg** [comment]
@Joshua-Ashton, confirmed the issue here, thanks so much for the report.  Working on this now.

**Comment by mark-lunarg** [comment]
@Joshua-Ashton, in the environment variable cases, the traditional validation layer delimiter is the **semicolon**, not a comma.  On Linux, it's a `colon`. It is on our [list of upcoming layer enhancements](https://github.com/KhronosGroup/Vulkan-ValidationLayers/projects/4#card-50002507) to expand the usable list of delimiter characters.  Please try the semicolons -- hopefully it'll get you going and I apologize for the confusion this has caused.

**Comment by Joshua-Ashton** [comment]
The documentation says to use `,`s and the examples have `,` delimiters.

```
 This is a comma-delineated list of VUIDs
    or VUID identifers which are to be IGNORED by the layers. These can be in
    any combination of the normal VUID string form,
```

**Comment by mark-lunarg** [comment]
@Joshua-Ashton, it is confusing -- that's actually for using the layer settings file and you're right, the differences between the various option-setting methods have been an ongoing issue.

**Comment by Joshua-Ashton** [comment]
Did this get fixed?

**Comment by mark-lunarg** [comment]
@Joshua-Ashton, right now it's working as designed and we have an open issue in the projects page to change the design.  The commas are for the layer settings file, and the colons and semicolons are for environment variables.  If we missed some environment variable documentation that indicates commas, please point us to it and we can fix it immediately.
