### ISSUE TITLE
Descriptor indexing with VARIABLE_DESCRIPTOR_COUNT triggers false positive without maintenance1.

### ISSUE THREAD

**Issue by HansKristian-Work** [KhronosGroup/Vulkan-ValidationLayers#2350]
**Describe the Issue**

When using descriptor indexing, and VARIABLE_DESCRIPTOR_COUNT_BIT, validation layer does not use the variable count when validating if the descriptor pool is filled.

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/descriptor_sets.cpp#L2825.
VARIABLE_COUNT is only considered down below:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/descriptor_sets.cpp#L2841

This only triggers if maintenance1 is not enabled.

**Valid Usage ID**

VUID-VkDescriptorSetAllocateInfo-descriptorPool-00307: Validation Error: [ VUID-VkDescriptorSetAllocateInfo-descriptorPool-00307 ] Object 0: handle = 0x380000000038, type = VK_OBJECT_TYPE_DESCRIPTOR_POOL; | MessageID = 0x21859338 | Unable to allocate 1048576 descriptors of type VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE from VkDescriptorPool 0x380000000038[]. This pool only has 262144 descriptors of this type remaining. The Vulkan spec states: descriptorPool must have enough free descriptor capacity remaining to allocate the descriptor sets of the specified layouts (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkDescriptorSetAllocateInfo-descriptorPool-00307)

**Environment:**
 - OS: Linux
 - GPU: NVIDIA GTX 1660Ti
 - SDK or header version if building from repo: master
 - Options enabled (synchronization, best practices, etc.): None

**Additional context**

**Comment by ziga-lunarg** [comment]
I don't think this is a bug, the spec says: 

> For the purposes of counting against limits such as maxDescriptorSet* and maxPerStageDescriptor*, the full value of descriptorCount is counted, except for descriptor bindings with a descriptor type of VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK ...

**Comment by ncesario-lunarg** [comment]
@HansKristian-Work does @ziga-lunarg's comment make sense, or do you think this validation is still incorrect?

**Comment by HansKristian-Work** [comment]
That is the maxDescriptorSet/maxPerStateDescriptor limit. Is the reading here that "such as" also includes descriptor count in maintenance1? That would seem unintentional to me.

**Comment by HansKristian-Work** [comment]
Then again, this is like behavior against ancient, pre-cambrian era Vulkan, so probably not worth spending time on resolving this.

**Comment by ncesario-lunarg** [comment]
After re-reading the spec and the validation code, I'm not sure the validation code is correct as-is. I think it _is_ operating according to the spec if maintenance1 is not enabled. That said, the possibility of descriptor_indexing + !maintenance1 doesn't seem to be accounted for in this particular area of the spec. If `descriptor_indexing` required maintenance1, then I suppose this wouldn't be an issue, but it only depends on maintenance3; unless the presence of maintenance3 implies the presence of maintenance1, but I don't think it does.
