### ISSUE TITLE
layers: Add finer VkFormat size information for VUID 04466

### ISSUE THREAD

**Issue by ncesario-lunarg** [KhronosGroup/Vulkan-ValidationLayers#2361]
**Add more detailed size information to vk_format_utils**
VUID 04466 requires bit-per-channel information which is currently not present in the `VULKAN_FORMAT_INFO` struct. This information should probably be generated by the python scripts.

**Valid Usage ID**
- VUID-VkImageViewCreateInfo-imageViewFormatReinterpretation-04466

This is part of #2208.

FYI @mark-lunarg.

**Comment by ncesario-lunarg** [comment]
@sfricke-samsung has [started work](https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/4787/) to get this information into `vk.xml`; once that change gets merged, automation should be updated to generate `vk_fomat_utils.cpp`.

**Comment by Rua** [comment]
What would be the number of bits per component in the case of block-compressed formats? Is that even well-defined?

**Comment by sfricke-samsung** [comment]
I "**think**" with block-compressed formats its not, but at same time, the issue about is where Image and ImageView have different formats, so in that case, if block-compressed, it would have to just be the same format

**Comment by Rua** [comment]
What if the image was created with `VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT`, and the image view has an uncompressed format?
