### ISSUE TITLE
Invalid report of raytracing geometry.transformData->deviceAddress misalignment

### ISSUE THREAD

**Issue by llatta** [KhronosGroup/Vulkan-ValidationLayers#2362]
**Describe the Issue**
I'm getting this validation error when invoking vkCmdBuildAccelerationStructuresKHR with a geometry.transformData->deviceAddress of 0, which should be exempted from the mentioned alignment requirement.

Validation Error: [ VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03810 ] Object 0: handle = 0xee2ddf28, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x4f220e0c | vkCmdBuildAccelerationStructuresKHR:For any element of pInfos[i].pGeometries with a geometryType of VK_GEOMETRY_TYPE_TRIANGLES_KHR, geometry.transformData->deviceAddress must be aligned to 16 bytes. The Vulkan spec states: For any element of pInfos[i].pGeometries or pInfos[i].ppGeometries with a geometryType of VK_GEOMETRY_TYPE_TRIANGLES_KHR, if geometry.triangles.transformData.deviceAddress is not 0, it must be aligned to 16 bytes (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03810)

**Valid Usage ID**
VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03810

**Environment:**
 - OS: Windows
 - GPU: Quadro RTX 800
 - SDK or header version if building from repo: latest AppVeyor build 5809 (commit 05ae438c)
 - Options enabled (synchronization, best practices, etc.): only Khronos validation

**Additional context**

**Comment by rg3igalia** [comment]
I can reproduce the problem, so I'll provide a pull request with the fix.
