### ISSUE TITLE
False positive on updating descriptor sets for top level acceleration structure

### ISSUE THREAD

**Issue by x3DCoder** [KhronosGroup/Vulkan-ValidationLayers#2368]
**Describe the Issue**
I have a validation error upon vkUpdateDescriptorSets() for a top-level acceleration structure. 
I have confirmed that I am correctly vkCreateAccelerationStructureKHR() with the correct type (as mentioned in the error) BEFORE updating descriptor sets. 
However, I am not building the top level acceleration structure yet, but as far as I understand this should not be necessary until we actually use it in a shader. 
Though the validation layer seems to want to validate that the top level acceleration structure is also BUILT before updating descriptor sets. 

**Valid Usage ID**
[ VUID-VkWriteDescriptorSetAccelerationStructureKHR-pAccelerationStructures-03579 ] Object 0: handle = 0x8f000000008f, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0x8cf1bb17 | vkUpdateDescriptorSets(): Each acceleration structure in pAccelerationStructures must have been created with VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_KHR or VK_ACCELERATION_STRUCTURE_TYPE_GENERIC_KHR and built with VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_KHR. The Vulkan spec states: Each acceleration structure in pAccelerationStructures must have been created with VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_KHR or VK_ACCELERATION_STRUCTURE_TYPE_GENERIC_KHR and built with VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_KHR

**Environment:**
 - OS: Linux 64bit 5.8.16-2-MANJARO
 - GPU: RTX 2060
 - SDK or header version if building from repo: Vulkan Headers 162

**Comment by mark-lunarg** [comment]
@dgkoch, will you please take a look at @x3DCoder's issue?

**Comment by dgkoch** [comment]
Oh that's fun. I think we'll need a spec change to actually make that legal, but I think what we meant that VU to be would more like: 

Each acceleration structure in pAccelerationStructures must have been created with VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_KHR; or created with VK_ACCELERATION_STRUCTURE_TYPE_GENERIC_KHR and built with VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_KHR.

**Comment by dgkoch** [comment]
Discussing more internally, we probably want to allow either type to be used "non-built", so @souravpNV will remove that part of the check while we figure out how to spec this correctly.

**Comment by dgkoch** [comment]
See https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2371

**Comment by dgkoch** [comment]
Assigning myself as I still need to deal with spec side of this.

**Comment by dgkoch** [comment]
Created spec issue https://gitlab.khronos.org/vulkan/vulkan/-/issues/2466

**Comment by dgkoch** [comment]
VU was updated in the 1.2.166 spec update. 

VU text was fixed to match in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2434

**Comment by mark-lunarg** [comment]
Thanks Daniel!
