### ISSUE TITLE
vkCmdBindVertexBuffers2EXT stride validation doesn't handle null param

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-ValidationLayers#2376]
**Describe the Issue**
Passing NULL for `pStrides` in this function erroneously throws errors as though an array of 0 was passed.

**Valid Usage ID**
```
VUID-vkCmdBindVertexBuffers2EXT-pStrides-03363(ERROR / SPEC): msgNum: -2012710471 - Validation Error: [ VUID-vkCmdBindVertexBuffers2EXT-pStrides-03363 ] Object 0: handle = 0x281d940, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x880879b9 | The pStrides[1] (0) parameter in the last call to vkCmdBindVertexBuffers2EXT is less than the extent of the binding for attribute 3 (16). The Vulkan spec states: If pStrides is not NULL each element of pStrides must be greater than or equal to the maximum extent of of all vertex input attributes fetched from the corresponding binding, where the extent is calculated as the VkVertexInputAttributeDescription::offset plus VkVertexInputAttributeDescription::format size (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdBindVertexBuffers2EXT-pStrides-03363)
```

**Environment:**
 - OS: linux
 - GPU: intel
 - SDK or header version if building from repo: 154
 - Options enabled (synchronization, best practices, etc.):

**Additional context**

**Comment by zmike** [comment]
Disregard, Monday is hitting hard this week :/

**Comment by mark-lunarg** [comment]
Hit me too, I couldn't figure out WHAT was going on!  Thanks, and we hope to hear from you again.

**Comment by zmike** [comment]
Alright, then having considered this further, I'm back.

The correct error in this case would be to inform the user that they can't pass NULL with `VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE_EXT` in their pipeline creation flags, so this is still a valid issue.

**Comment by mark-lunarg** [comment]
I think that's probably this missing check:

> • VUID-vkCmdBindVertexBuffers2EXT-pStrides-03361
> If the bound pipeline state object was created with the
> VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE_EXT dynamic state enabled then pStrides
> must not be NULL, otherwise pStrides must be NULL

**Comment by zmike** [comment]
Right, that's the one :+1:

**Comment by baryluk** [comment]
@mark-lunarg Thanks for improving this!
