### ISSUE TITLE
dEQP-VK.subgroups.partitioned.graphics.subgroupadd_int8_t assert with validation enabled

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-ValidationLayers#2383]
**Describe the Issue**
As of #2299 the test in the title gets an assert "Can't dereference out of range vector iterator" 

**Environment:**
 - OS: Windows 10 x64
 - GPU: GeForce RTX 2080
 - SDK or header version if building from repo: 0065ce08 layers: Generate SPIR-V Capability/Extension
 - Options enabled (synchronization, best practices, etc.): No options

**Additional context**
shader_validation.h 48: uint32_t opcode() { return *it & 0x0ffffu; } 
it = 0xcdcdcdcd
from shader_validation.cpp 2187:  if ((scope_id.opcode() == spv::OpSpecConstant) || (scope_id.opcode() == spv::OpConstant)) {
scope_id.it = 0xcdcdcdcd
CTS branch vulkan-cts-1.2.5
Preceded by validation error "The SPIR-V Extension (SPV_NV_shader_subgroup_partitioned) was declared, but none of the requirements were met to use it."

Let me know if you need more info / anything else

**Comment by jeffbolznv** [comment]
I bet this is happening because OpGroupNonUniformPartitionNV doesn't have a scope operand, and validation is assuming it does. This is a mistake in the spec (my bad), but not something that's fixable without a whole new replacement opcode.

**Comment by sfricke-samsung** [comment]
Ok, that would 100% be the issue... Happy to just add a 

```
if (inst.opcode() == spv::OpGroupNonUniformPartitionNV)
```

I remember looking at all the other group operations and noticed the scope operand and yes, it is making the assumption

**Comment by sfricke-samsung** [comment]
@jeffbolznv does one just assume the `OpGroupNonUniformPartitionNV` is always in `Subgroup` scope for validation?

**Comment by jeffbolznv** [comment]
Yeah, best to just assume `Subgroup`.
