### ISSUE TITLE
Validation calling vkGetPhysicalDeviceProperties2KHR without enabling VK_KHR_get_physical_device_properties2

### ISSUE THREAD

**Issue by mikes-lunarg** [KhronosGroup/Vulkan-ValidationLayers#2390]
`GetPhysicalDeviceExtProperties` in state_tracker.h is unconditionally calling the "KHR" version of `vkGetPhysicalDeviceProperties2`, even when the VK_KHR_get_physical_device_properties2 extension is not enabled. This does appear to be working (possibly due to loader magic in the `pfnNextGetInstanceProcAddr` provided to the layer) but is causing some warnings when using gfxreconstruct to replay a file that was captured with validation enabled.

After talking over with @mark-lunarg, we think the layer should be selecting between the KHR/non-KHR version based on what is enabled, or perhaps just the requested api version.

**Comment by mark-lunarg** [comment]
Confirmed fixed by #2392.
