### ISSUE TITLE
Control flow integrity error in CoreChecks::VerifyWriteUpdateContents

### ISSUE THREAD

**Issue by sugoi1** [KhronosGroup/Vulkan-ValidationLayers#2391]
Running CFI (Control flow integrity) checks on Vulkan Validation Layers picks up the following error:
```
runtime error: control flow integrity check for type 'cvdescriptorset::SamplerDescriptor' failed during base-to-derived cast (vtable address 0x7f1e36fed740)
0x7f1e36fed740: note: vtable is of type 'cvdescriptorset::ImageSamplerDescriptor'
```

The CFI run can be found here:
https://ci.chromium.org/ui/p/chromium/builders/try/linux_chromium_cfi_rel_ng/1458/steps

The error happens on this line:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/28168c539d5960ec9e2f52e346875524ef24b389/layers/descriptor_sets.cpp#L3302
Which contains the following code:
`SamplerDescriptor *desc = (SamplerDescriptor *)dest_set->GetDescriptorFromGlobalIndex(index + di);`

This attempts to cast an object created as an ImageSamplerDescriptor into a SamplerDescriptor, which should never happen.

**Comment by null77** [comment]
For context we caught this when we enabled the SwiftShader + ANGLE using the VVL on a CFI-enabled config. The bug is currently blocking us from enabling this path in Chrome. http://crbug.com/1061151 

@mark-lunarg fyi

**Comment by ncesario-lunarg** [comment]
I believe something like the following will fix this (i.e., just cast to the base type)?
```diff
diff --git a/layers/descriptor_sets.cpp b/layers/descriptor_sets.cpp
index 5d082b32..c24310b5 100644
--- a/layers/descriptor_sets.cpp
+++ b/layers/descriptor_sets.cpp
@@ -3205,7 +3205,7 @@ bool CoreChecks::ValidateWriteUpdate(const DescriptorSet *dest_set, const VkWrit
 bool CoreChecks::VerifyWriteUpdateContents(const DescriptorSet *dest_set, const VkWriteDescriptorSet *update, const uint32_t index,
                                            const char *func_name, std::string *error_code, std::string *error_msg) const {
     using ImageSamplerDescriptor = cvdescriptorset::ImageSamplerDescriptor;
-    using SamplerDescriptor = cvdescriptorset::SamplerDescriptor;
+    using Descriptor = cvdescriptorset::Descriptor;
 
     switch (update->descriptorType) {
         case VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER: {
@@ -3299,7 +3299,7 @@ bool CoreChecks::VerifyWriteUpdateContents(const DescriptorSet *dest_set, const
         // Fall through
         case VK_DESCRIPTOR_TYPE_SAMPLER: {
             for (uint32_t di = 0; di < update->descriptorCount; ++di) {
-                SamplerDescriptor *desc = (SamplerDescriptor *)dest_set->GetDescriptorFromGlobalIndex(index + di);
+                const Descriptor *desc = (const Descriptor*)dest_set->GetDescriptorFromGlobalIndex(index + di);
                 if (!desc->IsImmutableSampler()) {
                     if (!ValidateSampler(update->pImageInfo[di].sampler)) {
                         *error_code = "VUID-VkWriteDescriptorSet-descriptorType-00325";
```

If this looks right I can make a PR, though I'm not setup to reproduce this error.

**Comment by sugoi1** [comment]
I tested this locally and it works, so yes, I would appreciate if this could be fixed.

Based on your change, it looks like this line:
`ImageSamplerDescriptor *desc = (ImageSamplerDescriptor *)dest_set->GetDescriptorFromGlobalIndex(index + di);`
can also be changed to:
`const ImageSamplerDescriptor *desc = (const ImageSamplerDescriptor *)dest_set->GetDescriptorFromGlobalIndex(index + di);`
so you might want to add this to your PR.

In any case, this works, so thanks for the fix!

**Comment by ncesario-lunarg** [comment]
@sugoi1 closing this issue as the fix is merged. Let me know if you're still having errors with it!
