### ISSUE TITLE
Fragment shader rate validated on incorrect pipeline type

### ISSUE THREAD

**Issue by archimedus** [KhronosGroup/Vulkan-ValidationLayers#2397]
I have crashes in compute pipeline using SDK 1.2.162.0 running CTS stating:
```
Exception thrown: read access violation.

pipeline->graphicsPipelineCI.pViewportState was nullptr.
```

I suppose  Pipeline Fragment Shading Rate is applicable only for graphics pipeline, thus following line should be guarded:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/6663c9bccb4b13355eefa354c00c6e9989761468/layers/shader_validation.cpp#L3687

Even more I suppose it should be checked only if rasterization is enabled (i.e. fragment shader stage present in pipeline).

@Tobski 

Could you please take a look?

**Comment by Tobski** [comment]
> I suppose Pipeline Fragment Shading Rate is applicable only for graphics pipeline, thus following line should be guarded:

Ack, yep that should be guarded. I'm rather surprised this didn't show up in any of the existing validation layer tests 🤔 

> Even more I suppose it should be checked only if rasterization is enabled (i.e. fragment shader stage present in pipeline).

That interaction isn't called out the spec, so that would need a correction first, but I think I agree.

**Comment by archimedus** [comment]
EDIT: Changed pViewState to pViewportState.

> so that would need a correction first

I think it's already in the spec:

>  pViewportState is a pointer to a VkPipelineViewportStateCreateInfo structure, and is ignored if the pipeline has rasterization disabled.

i.e. when rasterization is disabled this pointer can be NULL and lead validator to crash. Or hangups (for example dead loop via pNext pointing to it selves) if the pointer just invalid.

**Comment by Tobski** [comment]
> I think it's already in the spec:

Ah I missed that - thanks. I shall look into providing fixes for both of these.

**Comment by ziga-lunarg** [comment]
This has been fixed.
