### ISSUE TITLE
Incorrect validation in vkCmdPipelineBarrier for ray tracing

### ISSUE THREAD

**Issue by azhirnov** [KhronosGroup/Vulkan-ValidationLayers#2405]
**Describe the Issue**
I get validation error:
`MessageID = 0x69c8467d | vkCmdPipelineBarrier(): pBufferMemBarriers[0].dstAccessMask (0x20) is not supported by dstStageMask (0x2000000).`
where dstAccessMask is VK_ACCESS_SHADER_READ_BIT, dstStageMask is VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR, which is allowed: 
https://vulkan.lunarg.com/doc/view/1.2.162.0/windows/1.2-extensions/vkspec.html#synchronization-access-types-supported

**Valid Usage ID**
VUID-vkCmdPipelineBarrier-srcAccessMask-02815
VUID-vkCmdPipelineBarrier-dstAccessMask-02816

**Environment:**
 - OS: windows
 - GPU: RTX 2080
 - SDK or header version if building from repo: 1.2.162 release
 - Options enabled (synchronization, best practices, etc.): default

**Comment by mark-lunarg** [comment]
@souravpNV, can you please have a look?

**Comment by souravpNV** [comment]
Sure will have a look

**Comment by souravpNV** [comment]
@mark-lunarg  fix for review https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2408

**Comment by mark-lunarg** [comment]
Fixed by #2408.  Thanks Gentlemen!
