### ISSUE TITLE
vkQueuePresentKHR():  Image Layout Comparison Error(?) for Image -> Present  (VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR)

### ISSUE THREAD

**Issue by Ay-Aitch** [KhronosGroup/Vulkan-ValidationLayers#2424]
I'm rendering onto images in VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR layout.   

These images are then blitted at each frame onto SC images.   

I get this validation error per vkQueuePresentKHR() :
_(Note that the required image layout is already set as per the validation message)_

> UID-VkPresentInfoKHR-pImageIndices-01296(ERROR / SPEC): msgNum: 0 - Images passed to present must be in layout VK_IMAGE_LAYOUT_PRESENT_SRC_KHR or VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR but is in VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR. ...

**Comment by mark-lunarg** [comment]
Were there any other validation error messages which occurred prior to this one, maybe an error when calling `GetSwapchainStatusKHR()`?  It looks as if you don't have the `VK_KHR_shared_presentable_image `device extension enabled.

**Comment by Ay-Aitch** [comment]
No other validation error messages.  I get the desired effect, images are rendered how they should be.

But you're right, there isn't a `VK_KHR_shared_presentable_image` device extension.  Apologies for this spurious bug report.

(JIC others arrive here searching a similar issue; the specification - v1.0 in my case - doesn't state whether layouts, flags, and other parameters, are guaranteed features or require specific device extensions)
