### ISSUE TITLE
vkCmdWriteAccelerationStructuresPropertiesNV reports error on legal queryType

### ISSUE THREAD

**Issue by pixeljetstream** [KhronosGroup/Vulkan-ValidationLayers#2448]
**Describe the Issue**
vkCmdWriteAccelerationStructuresPropertiesNV reports errors on the NV enums used for queryType which have different values than the KHR enums. The NV function was called with VK_QUERY_TYPE_ACCELERATION_STRUCTURE_COMPACTED_SIZE_NV

**Valid Usage ID**
Validation Error: [ VUID-vkCmdWriteAccelerationStructuresPropertiesNV-queryType-03432 ] Object 0: handle = 0x1eb14914ee8, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xb9d6de38 | vkCmdWriteAccelerationStructuresPropertiesNV: queryType must be VK_QUERY_TYPE_ACCELERATION_STRUCTURE_COMPACTED_SIZE_KHR or VK_QUERY_TYPE_ACCELERATION_STRUCTURE_SERIALIZATION_SIZE_KHR. The Vulkan spec states: queryType must be VK_QUERY_TYPE_ACCELERATION_STRUCTURE_COMPACTED_SIZE_KHR or VK_QUERY_TYPE_ACCELERATION_STRUCTURE_SERIALIZATION_SIZE_KHR (https://vulkan.lunarg.com/doc/view/1.2.162.0/windows/1.2-extensions/vkspec.html#VUID-vkCmdWriteAccelerationStructuresPropertiesNV-queryType-03432)

**Environment:**
 - OS:  win10-64
 - GPU: quadro rtx 6000
 - SDK or header version if building from repo: 1.2.162.0
 - Options enabled (synchronization, best practices, etc.):

**Additional context**

**Comment by mark-lunarg** [comment]
@pixeljetstream, the validation is technically accurate according to the spec:

> • VUID-vkCmdWriteAccelerationStructuresPropertiesNV-queryType-03432
> queryType must be VK_QUERY_TYPE_ACCELERATION_STRUCTURE_COMPACTED_SIZE_KHR or
> VK_QUERY_TYPE_ACCELERATION_STRUCTURE_SERIALIZATION_SIZE_KHR

My hunch is that this is a vuid typo -- could you, @souravpNV or @dgkoch confirm this?

**Comment by souravpNV** [comment]
I too think this is VUID typo, and will need spec update, for NV the queryType should be replaced by VK_QUERY_TYPE_ACCELERATION_STRUCTURE_COMPACTED_SIZE_NV or VK_QUERY_TYPE_ACCELERATION_STRUCTURE_SERIALIZATION_SIZE_NV

**Comment by mark-lunarg** [comment]
@souravpNV, this was the complication for me -- there is not an NV flavor of `VK_QUERY_TYPE_ACCELERATION_STRUCTURE_SERIALIZATION_SIZE_KHR`.

**Comment by souravpNV** [comment]
@mark-lunarg Thanks for the correction, yes it should be COMPACTED_SIZE_NV and SERIALIZATION_SIZE_KHR.

**Comment by dgkoch** [comment]
There was a point when those were all aliased and were the same, but then we changed it, so yes will need a spec fix. 
BTW SERIALIZATION_SIZE isn't supported for the NV extension.

**Comment by dgkoch** [comment]
Spec fix in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/4310

**Comment by mark-lunarg** [comment]
Thanks Daniel.

**Comment by mark-lunarg** [comment]
**NOTE:** This will require a VVL PR when the headers containing the fix have been updated.

**Comment by dgkoch** [comment]
> NOTE: This will require a VVL PR when the headers containing the fix have been updated.

Yes. Spec change is approved and should be in next spec update. 
Do we need to wait for the spec to be published, or can we just go ahead and fix it now?

@souravpNV can you implement this?

Relevant modified VUs are: 

  * [[VUID-vkCmdWriteAccelerationStructuresPropertiesNV-accelerationStructures-03431]]
    All acceleration structures in pname:pAccelerationStructures must: have
    been built with
    ename:VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_COMPACTION_BIT_KHR if
    pname:queryType is
    ename:VK_QUERY_TYPE_ACCELERATION_STRUCTURE_COMPACTED_SIZE_NV
  * [[VUID-vkCmdWriteAccelerationStructuresPropertiesNV-queryType-03432]]
    pname:queryType must: be
    ename:VK_QUERY_TYPE_ACCELERATION_STRUCTURE_COMPACTED_SIZE_NV

**Comment by mark-lunarg** [comment]
@dgkoch, we usually wait for the spec to change, but if you're OK with it I am.  And I can make the change here, it'll be faster.

**Comment by dgkoch** [comment]
> @dgkoch, we usually wait for the spec to change, but if you're OK with it I am. And I can make the change here, it'll be faster.

Go for it!
