### ISSUE TITLE
VUID-VkSamplerYcbcrConversionCreateInfo-format-04060 incorrectly fails a UNorm check

### ISSUE THREAD

**Issue by kspagnoli** [KhronosGroup/Vulkan-ValidationLayers#2449]
**Describe the Issue**
Seeing false positives for format that is failing a check in `FormatIsUNorm`. Doing a quick audit, it looks like a handful of formats are missing. Specifically, I'm seeing this in vkCreateSamplerYcbcrConversion for the VK_FORMAT_R12X4G12X4_UNORM_2PACK16 format but I'm guessing this'll manifest in some other false positives as well.

**Valid Usage ID**
Validation Error: [ VUID-VkSamplerYcbcrConversionCreateInfo-format-04060 ] Object 0: handle = 0x13edf9d3e48, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x27d1d397 | vkCreateSamplerYcbcrConversion(): CreateInfo format (VK_FORMAT_R12X4G12X4_UNORM_2PACK16) is not an UNORM format and there is no external format conversion being created. The Vulkan spec states: format must represent unsigned normalized values (i.e. the format must be a UNORM format)

**Comment by mark-lunarg** [comment]
@kspagnoli, updated the FormatIsUNorm() format list, please let us know if this doesn't resolve your issue.  And thank you very much for bringing this to our attention!
