### ISSUE TITLE
SPV_KHR_multiview incompatibility between validation layers and glslangvalidator. 

### ISSUE THREAD

**Issue by tuxerr** [KhronosGroup/Vulkan-ValidationLayers#2456]
When using master validation layers on a multiview application (UE4/Vulkan on Oculus Quest 2 in my case) I'm getting this error:
`
LogVulkanRHI: Warning: *** [Error:Validation(VUID-VkShaderModuleCreateInfo-pCode-04146)] Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-04146 ] Object 0: handle = 0x79f8241eb0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xd80a42ae | vkCreateShaderModule(): A SPIR-V Extension (SPV_KHR_multiview) was declared that is not supported by Vulkan. The Vulkan spec states: pCode must not declare any SPIR-V extension that is not supported by the API, as described by the Extension section of the SPIR-V Environment appendix (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-04146)`
`

Looking at https://github.com/KhronosGroup/glslang/blob/master/SPIRV/GlslangToSpv.cpp, any use of ViewIndex will add to the SPIRV code:

`
        builder.addIncorporatedExtension(spv::E_SPV_KHR_multiview, spv::Spv_1_3);
`

however in the latest vk.xml of validation layers, SPV_KHR_multiview isn't a valid spirvextension anymore as multiview is now a core capability.

 
        <spirvcapability name="MultiView">
            <enable struct="VkPhysicalDeviceVulkan11Features" feature="multiview" requires="VK_VERSION_1_1,VK_KHR_multiview"/>
        </spirvcapability>
        
I'm not sure what the solution is in this case, either remove the extension from glslangvalidator, force-add it to validation layers, or change the VK spec?

**Comment by sfricke-samsung** [comment]
So recently there was code added to the Validation Layers that generates the error you see

The issue, as you pointed out, is there is no 
```
        <spirvextension name="SPV_KHR_multiview">
            <enable extension="VK_KHR_multiview"/>
        </spirvextension>
```
which is 100% a Vulkan Spec bug.

I will get a fix into the [Vulkan-Docs](https://github.com/KhronosGroup/Vulkan-Docs) repo so this can get properly generated in the Validation Layer

**Comment by tuxerr** [comment]
Perfect, thanks! I'll re-generate my validation layers when that's done :)

**Comment by mark-lunarg** [comment]
Fix bubbling through the pipeline at https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/4314.

**Comment by sfricke-samsung** [comment]
Should be fixe now with 1.2.169 headers merged in
