### ISSUE TITLE
Potentially incorrect requirement to enable VK_KHR_external_fence_capabilities to use VkPhysicalDeviceIDProperties

### ISSUE THREAD

**Issue by tuxerr** [KhronosGroup/Vulkan-ValidationLayers#2457]
I'm getting a validation error (parameter_validation.cpp, line 836 on case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ID_PROPERTIES) when having a VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ID_PROPERTIES pNext while not enabling the parent extension VK_KHR_external_fence_capabilities. However, I did enable VK_KHR_external_memory_capabilities, and looking at the man page in https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPhysicalDeviceIDProperties.html, it seems that this structure is provided by either external_fence or external_memory or external_semaphore. 

Should the validation layer in line 837 of parameter_validation.cpp check for one of those 3 extensions instead of only vk_khr_external_fence_capabilities? If so I'm happy to make the change, just want to be sure.

**Comment by mark-lunarg** [comment]
@tuxerr, no, I think you are correct.  We had long operated under the assumption that a struct should be owned by a single extension and this is no longer true.  It's fiddly but we'll get it fixed.  Thanks!

```
        // Validation code for VkPhysicalDeviceIDProperties structure members
        case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ID_PROPERTIES: { // Covers VUID-VkPhysicalDeviceIDProperties-sType-sType
            if (!instance_extensions.vk_khr_external_fence_capabilities) {
                skip |= LogError(
                           instance, pnext_vuid,
                           "%s: Includes a pNext pointer (%s) to a VkStructureType (VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ID_PROPERTIES), but its parent extension "
                           "VK_KHR_external_fence_capabilities has not been enabled.",
                           api_name, parameter_name.get_name().c_str());
            }
        } break;
```

And in the xml, `VkPhysicalDeviceIDPropertiesKHR `is included in the `VK_KHR_external_fence_capabilities`, `VK_KHR_external_memory_capabilities `and the `VK_KHR_external_semaphore_capabilities `extensions.  Sweet.  Problem is related to 

`                        ext_name_define = self.extension_names[ver_info]`

which returns an extension but should probably return a list.

**Comment by ncesario-lunarg** [comment]
Was just about to tag @mark-lunarg and ask if [this](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/scripts/parameter_validation_generator.py#L386) should get converted to a list :D

**Comment by tuxerr** [comment]
Thanks!

**Comment by mikes-lunarg** [comment]
This also seems to affect extensions which get promoted to from Vendor to EXT:
```
        case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MUTABLE_DESCRIPTOR_TYPE_FEATURES_EXT: { // Covers VUID-VkPhysicalDeviceMutableDescriptorTypeFeaturesEXT-sType-sType
            if (is_const_param) {
                if ((is_physdev_api && !SupportedByPdev(physical_device, VK_VALVE_MUTABLE_DESCRIPTOR_TYPE_EXTENSION_NAME)) || (!is_physdev_api && !IsExtEnabled(device_extensions.vk_valve_mutable_descriptor_type))) {
                        skip |= LogError(
                               instance, pnext_vuid,
                               "%s: Includes a pNext pointer (%s) to a VkStructureType (VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MUTABLE_DESCRIPTOR_TYPE_FEATURES_EXT), but its parent extension "
                               "VK_VALVE_mutable_descriptor_type has not been enabled.",
                               api_name, parameter_name.get_name().c_str());
                }
            }
```
and EXT to KHR
```
        case VK_STRUCTURE_TYPE_DEVICE_QUEUE_GLOBAL_PRIORITY_CREATE_INFO_KHR: { // Covers VUID-VkDeviceQueueGlobalPriorityCreateInfoKHR-sType-sType
            if (is_const_param) {
                if ((is_physdev_api && !SupportedByPdev(physical_device, VK_EXT_GLOBAL_PRIORITY_EXTENSION_NAME)) || (!is_physdev_api && !IsExtEnabled(device_extensions.vk_ext_global_priority))) {
                        skip |= LogError(
                               instance, pnext_vuid,
                               "%s: Includes a pNext pointer (%s) to a VkStructureType (VK_STRUCTURE_TYPE_DEVICE_QUEUE_GLOBAL_PRIORITY_CREATE_INFO_KHR), but its parent extension "
                               "VK_EXT_global_priority has not been enabled.",
                               api_name, parameter_name.get_name().c_str());
                }
            }
```

**Comment by spencer-lunarg** [comment]
Update, we had this suppressed and now un-suppressed in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6806

goal now is to finally (once and for all hopefully)  have the "when things are enabled" logic correct

**Comment by krOoze** [comment]
@spencer-lunarg I am getting this exact error now with SDK 1.3.283. Have this bug resurfaced?

**Comment by spencer-lunarg** [comment]
@krOoze we added a test to prevent this regression

```c++
TEST_F(VkPositiveLayerTest, DeviceIDPropertiesExtensions) {
    TEST_DESCRIPTION("VkPhysicalDeviceIDProperties can be enabled from 1 of 3 extensions");

    SetTargetApiVersion(VK_API_VERSION_1_0);
    AddRequiredExtensions(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
    AddRequiredExtensions(VK_KHR_EXTERNAL_MEMORY_CAPABILITIES_EXTENSION_NAME);
    RETURN_IF_SKIP(InitFramework());

    if (DeviceValidationVersion() != VK_API_VERSION_1_0) {
        GTEST_SKIP() << "Tests for 1.0 only";
    }

    VkPhysicalDeviceIDProperties id_props =  vku::InitStructHelper();
    VkPhysicalDeviceFeatures2 features2 = vku::InitStructHelper(&id_props);
    vk::GetPhysicalDeviceFeatures2KHR(gpu(), &features2);
}
```

What is your example doing differently?

**Comment by krOoze** [comment]
@spencer-lunarg The test seem defective and should generate an error. `VkPhysicalDeviceIDProperties` extends Props, not Features struct.

Given that, the layers should probably test whether `returnedonly` structs are properly validated too.

**Comment by spencer-lunarg** [comment]
> VkPhysicalDeviceIDProperties extends Props, not Features struct.

wow, good catch, fixed those in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8025 

but VVL are working as expected still, so still curious what your example was doing that hit the original False Positive from this issue

> Given that, should probably also test whether returnedonly structs are properly validated too.

Not sure what you mean, the `returnedonly` in the XML just removes all the implicit VUs from `VkPhysicalDeviceIDProperties` as we don't need to check those fields

**Comment by krOoze** [comment]
What I mean is the test as you have posted it previously should have failed (because of the wrong pnext struct), but apparently didn't.

---

In the PR you invalidated the purpose of the test by changing the enabled extension. Me and OP refer to `VK_KHR_external_memory_capabilities` as the problem-causing one. Be careful to conform code to pass tests, and not conform tests to pass the code (cc: @artem-lunarg as the PR reviewer). I just verified the test fails when reverted to `VK_KHR_external_memory_capabilities`.

**Comment by krOoze** [comment]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/48b38b33245c8c4835e4fcbdad4ea2b5f23b13f8/scripts/generators/stateless_validation_helper_generator.py#L1021 seems to assume singular extension, hence the layer bug.

**Comment by spencer-lunarg** [comment]
sorry, didn't see this before

![image](https://github.com/KhronosGroup/Vulkan-ValidationLayers/assets/115671160/fc82b553-aede-4f51-93c8-49ac2fbd49ad)

will take another stab at this Monday

**Comment by krOoze** [comment]
Original test not producing validation error is likely due to https://github.com/KhronosGroup/Vulkan-Docs/issues/2257

**Comment by krOoze** [comment]
As for immediate issue, already stabbed at PR #8036
