### ISSUE TITLE
Crash in vkQuake with enabled anti aliasing

### ISSUE THREAD

**Issue by Novum** [KhronosGroup/Vulkan-ValidationLayers#2463]
Crash in code validating attachment image views when running vkQuake with multi/super sampling loading into any level. No message, just crashes

 - OS: Windows 10
 - GPU: NVIDIA GeForce RTX 3080
 - SDK or header version if building from repo: 1.2.162.0
 - Options enabled (synchronization, best practices, etc.): Default options

This was not happening with earlier validation layers. I can't rule out a problem on my end, but it seems unlikely and it shouldn't crash but report an error ideally if something is wrong.

Quake shareware data can be obtained here: https://community.pcgamingwiki.com/files/file/411-quake-shareware-pak/
Then just copy the latest vkQuake release binaries into the folder and run it.

On Linux you can probably get it through the distro package manager including the shareware data, but I haven't tried. I believe this would crash in older vkQuake versions too because the code setting up the render passes hasn't changed in a while.

**Comment by locke-lunarg** [comment]
When anti aliasing is enabled, the attachment is 2 in vulkan_globals.main_render_pass.
https://github.com/Novum/vkQuake/blob/master/Quake/gl_vidsdl.c#L1054

But framebuffer_create_info.attachmentCount is 2 to trigger the assert.
https://github.com/Novum/vkQuake/blob/master/Quake/gl_vidsdl.c#L1823

A weird thing it is rendering ui.
https://github.com/Novum/vkQuake/blob/master/Quake/gl_draw.c#L1025
But the renderpass is main_render_pass, not ui_render_pass.
https://github.com/Novum/vkQuake/blob/master/Quake/gl_rmisc.c#L1571

@mark-lunarg We might need a validation for this case.

**Comment by mark-lunarg** [comment]
@Novum, there doesn't appear to be valid usage preventing this particular situation, do you feel that there should be?  We are leaning towards changing the assert into a validation error, but it'd be helpful to know what you'd prefer from the developer-side of things.

**Comment by Novum** [comment]
The asserts in optimized code are useless for most people. I have no idea what it means because I don't know the code. And the SDK doesn't even ship the sources so you have to dig them up from github. That's not explained anywhere either.

So yes, never assert or crash if possible. It should return validation errors instead.

**Comment by Novum** [comment]
@locke-lunarg That's not the frame buffer that is used for the first sub pass. It's this one: https://github.com/Novum/vkQuake/blob/master/Quake/gl_vidsdl.c#L1802

Are you sure there isn't some problem with sub passes in this validation step?

**Comment by Novum** [comment]
Considering the cause of this: It would be nice if the validation layer would verify that the render pass of the pipeline matches the active one?

**Comment by mark-lunarg** [comment]
Yeah, that's what I was _trying_ to ask -- do you think it should be declared in the spec that these two things must match?  We are planning to add a check either way, but we are on more solid ground if I can take this back to the Vulkan group and get their approval as well.

**Comment by Novum** [comment]
Well, the spec allows for compatible render passes. I guess the validator would need to check if the render pass provided in the pipeline is compatible with the active render pass.

The render pass compatibility thing is important for creating pipelines at startup without actual rendering yet.

**Comment by spencer-lunarg** [comment]
@Novum sorry this hasn't been looked at for awhile, but there has been a lot of code changes in the last 2 years, can you try to reproduce this to see if it still an issue?
