### ISSUE TITLE
Validator hangs in vkCreateShaderModule

### ISSUE THREAD

**Issue by seanbaxter** [KhronosGroup/Vulkan-ValidationLayers#2465]
/usr/lib/x86_64-linux-gnu/libVkLayer_khronos_validation.so enters an infinite loop or something inside vkCreateShaderModule.

This is the module:
https://gist.github.com/seanbaxter/5ab783bac4e2293865e8fc71b8e7cd0c

It passes spirv-val. It's no great surprise that it gives the validator a problem, because this is pretty bleeding edge. It uses physical storage buffers in a way that is much different from GLSL buffer_reference. I do a C++ lambda closure to bake the pointer into the push constant.

This is my first Vulkan program so I may not have the extensions set up correctly.

The branch that hangs is here:
https://github.com/seanbaxter/vulkan_compute/tree/hang

The code I'm concerned about doesn't even get executed, since it stalls at loading the module.

All I'm doing is using Vma to allocate a vec3 array and launching a compute grid to initialize the values:
https://github.com/seanbaxter/vulkan_compute/blob/hang/compute.cxx

**Comment by mark-lunarg** [comment]
@seanbaxter, can you share the validation message output before the hang if there was any?  That should tell you if you do not have the extensions set correctly.  @ncesario-lunarg, a hang in CSM is often caused by a malformed shader, but it's disturbing that it passes spirv-val(?).  Can you have a quick look, perhaps after we hear back from Sean?  Thanks!

**Comment by seanbaxter** [comment]
There are no validation messages, just the hang. This code was generated with my own compiler. The SPIR-V differs from glslang's considerably.

**Comment by ncesario-lunarg** [comment]
@seanbaxter I'm trying to reproduce this, but unfortunately I'm not able to build the project (e.g., not sure what is producing SPIR-v code via this [-shader](https://github.com/seanbaxter/vulkan_compute/blob/hang/CMakeLists.txt#L12) flag). Could you point me to the SPIR-v compiler you're using? Also, are there any other requirements for running this (e.g., OS/GPU/etc)? Thanks!

**Comment by seanbaxter** [comment]
I wrote the compiler and the version that generates this particular module isn't ready for public. Just load the module into any Vk project. You don't have to run it. It hangs immediately in vkCreateShaderModule. The validation layer must be interpreting the SPIR-V incorrectly and getting itself stuck.

**Comment by ncesario-lunarg** [comment]
Thanks @seanbaxter, I created a test case that creates a compute pipeline to try to reproduce this, and I'm seeing `vkCreateShaderModule` fail first, then the following validation errors. I'm not able to reproduce the hang, though.
```
Expected to succeed but got error: Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x1e08c8fb060, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: OpEntryPoint interfaces must be OpVariables with Storage Class of Input(1) or Output(3). Found Storage Class 9 for Entry Point id 1.
  %_Z11shader_pushI16transform_push_tIZ4mainEUliE_EE = OpVariable %_ptr_PushConstant__struct_7 PushConstant
```
The setup I used was based off of [this](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/f5dea94f6f1507f637c0500b01a818d9217be1fe/tests/vkpositivelayertests.cpp#L1632) test:
```cpp
...
app_info_.apiVersion = VK_VERSION_1_2; // Use Vulkan 1.2

// Add extensions mentioned at https://github.com/seanbaxter/vulkan_compute/blob/88db4f19e96ec114fbbbfdbe10b923563fb0c444/context.cxx#L32
m_device_extension_names.push_back("VK_KHR_buffer_device_address");
m_device_extension_names.push_back("VK_KHR_shader_non_semantic_info");
...
const std::string spv_source = R"(
  <your SPIR-v assembly>
)";

VkPushConstantRange push_constant_ranges[1]{{VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(float) * 16}};

VkPipelineLayoutCreateInfo const pipeline_layout_info{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO, nullptr, 0, 0, nullptr, 1, push_constant_ranges};

CreateComputePipelineHelper pipe(*this);
pipe.InitInfo();

// This calls vkCreateShaderModule
pipe.cs_.reset(new VkShaderObj(m_device, spv_source, VK_SHADER_STAGE_COMPUTE_BIT, this));

pipe.InitState();
m_errorMonitor->ExpectSuccess();
pipe.CreateComputePipeline();
m_errorMonitor->VerifyNotFound();
```

For reference this is on Windows 10 + nvidia gtx 1650. 

Would you be able to share any of the following?
- Platform your are running on
- Stack trace of where the app is hung (e.g., `ctrl + c` while a debugger is attached during the hang)
- The binary that hangs (either Windows or Linux executable)

**Comment by ncesario-lunarg** [comment]
Just noticed that it looks like the result of [vkCreateShaderModule](https://github.com/seanbaxter/vulkan_compute/blob/hang/context.cxx#L184) is not being checked? Is that call succeeding on your platform?

**Comment by jeffbolznv** [comment]
> SPIR-V module not valid: OpEntryPoint interfaces must be OpVariables with Storage Class of Input(1) or Output(3)

This was changed in SPIR-V 1.4. Is your test using too old of a SPIR-V or Vulkan version?

**Comment by seanbaxter** [comment]
vkCreateShaderModule doesn't return. It hangs, so it can't be checked.

But it looks like your repro case shows the problem. Why does vkCreateShaderModule fail in your test? It's a valid module. The diagnostic that it's printing is wrong.

```
Expected to succeed but got error: Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x1e08c8fb060, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: OpEntryPoint interfaces must be OpVariables with Storage Class of Input(1) or Output(3). Found Storage Class 9 for Entry Point id 1.
```

From the SPIR-V spec for OpEntryPoint:
```
Starting with version 1.4, the interface’s storage classes are all storage classes used in declaring all global variables referenced by the entry point’s call tree.
```

I'm less concerned with the hang than the fact that on both of our systems the validation layer is failing to accept a valid module.

**Comment by mark-lunarg** [comment]
@seanbaxter, the failure is saying that it is not a valid module.  That particular check means that the spirv-validator has failed (the layers call it directly).  We are just passing through the error from the validator.  Perhaps there's an issue with [spirv-tools](https://github.com/KhronosGroup/SPIRV-Tools/tree/master/tools/val)?

**Comment by seanbaxter** [comment]
> @seanbaxter, the failure is saying that it is not a valid module. That particular check means that the spirv-validator has failed (the layers call it directly). We are just passing through the error from the validator. Perhaps there's an issue with [spirv-tools](https://github.com/KhronosGroup/SPIRV-Tools/tree/master/tools/val)?

It passes spirv-val. This is my version of that: SPIRV-Tools v2020.7-dev v2020.6-15-g1bb80d27

**Comment by ncesario-lunarg** [comment]
Ah, typo on my part (`VK_VERSION_1_2` -> `VK_API_VERSION_1_2` when setting up the instance). Thanks @jeffbolznv as I thought I had the versions setup correctly!

This is hitting an assert in [shader_validation.cpp](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/f5dea94f6f1507f637c0500b01a818d9217be1fe/layers/shader_validation.cpp#L1260). Don't know why yet, but this is in the same area as a different issue I was looking at involving push constants and `VK_KHR_buffer_device_address`, so maybe they are related.

**Comment by seanbaxter** [comment]
> Ah, typo on my part (`VK_VERSION_1_2` -> `VK_API_VERSION_1_2` when setting up the instance). Thanks @jeffbolznv as I thought I had the versions setup correctly!

While you're at it, file a bug that VK_VERSION_1_2 ought to be the same as VK_API_VERSION_1_2. Someone is likely to get stung by that.

**Comment by seanbaxter** [comment]
How do I turn off shader module validation and keep the other layers on? I'm flying blind without it and don't know Vulkan.

**Comment by ncesario-lunarg** [comment]
Hi @seanbaxter, I don't think there is a way to turn off _only_ shader validation (@mark-lunarg @jeremy-lunarg?). You can see a list of "features" you can enable/disable in the **VK_LAYER_KHRONOS_validation** layer [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/docs/khronos_validation_layer.md#validationfeatures).

It looks like the hang is happening because the type pointed to by the push constant address is expected to be a struct in the VVL, but is actually a vector type. I'll see if I can get a change up that avoids the hang in the short, but it will probably take a bit longer to get something that works properly.

**Comment by ncesario-lunarg** [comment]
@seanbaxter if you're able to build the ValidationLayers, #2497 should fix the hang you were seeing, though you will likely get an additional error about `OpExtension` using a non-SPV extension now. Please re-open if you are still seeing this issue.
