### ISSUE TITLE
kInstErrorBindlessBuffOOB removed from spirv

### ISSUE THREAD

**Issue by ravensiris** [KhronosGroup/Vulkan-ValidationLayers#2466]
https://github.com/KhronosGroup/SPIRV-Tools/commit/c32277c0ba0df26c8661a7daadc8743dc5a10bd3

Won't compile with newest spirv-tools.

error: ‘kInstErrorBindlessBuffOOB’ was not declared in this scope
 1269 |         case kInstErrorBindlessBuffOOB: {

**Comment by Tony-LunarG** [comment]
Yes, those changes are in support of better GPU-AV error reporting.  The validation layers will be updated to use the kInstErrorBuffOOB* codes with the next revision of glslang, which will pull in the new spirv-tools.

**Comment by mark-lunarg** [comment]
@ravensiris, this repo has a mechanism in place to manage the numerous upstream repo dependencies, concentrated in the [scripts/known_good.json](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/scripts/known_good.json) file. 
The repo is only guaranteed to build correctly with that specific combination of dependencies.  The `known_good.json` file is typically updated about a week after a new header release, so the `spirv-tools` changes you are looking for will make their way to this repo after the other upstream components have been updated and the repo header update has been performed.
