### ISSUE TITLE
Scrub dispatch calls from CreateInstance hooks

### ISSUE THREAD

**Issue by ncesario-lunarg** [KhronosGroup/Vulkan-ValidationLayers#2468]
See https://github.com/KhronosGroup/Vulkan-Loader/issues/537 for more details.

In short, `CreateInstance` is more of a "constructor" than a "hook," and dispatch calls should not be made from inside CreateInstance. This issue is to track finding and removing dispatch calls from within CreateInstance hooks.

FYI @lenny-lunarg @jeremyk-lunarg @mikes-lunarg @mark-lunarg

**Comment by mark-lunarg** [comment]
Didn't notice any after a quick scan. Hopefully this won't be a big deal.  Thanks Loader!

**Comment by spencer-lunarg** [comment]
Not sure what is still needed to be done here (cc @charles-lunarg)

**Comment by charles-lunarg** [comment]
After a quick look at https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/d5426ea20669a4d8de34dd3b89685fba73a21c4f/layers/generated/chassis.cpp#L261 and noting that the loader has 'fixed' layers making calls during create instance, I will close the issue as I do not believe there is any thing left to do.
