### ISSUE TITLE
debugPrintfEXT issues with ray tracing shaders

### ISSUE THREAD

**Issue by UHFT** [KhronosGroup/Vulkan-ValidationLayers#2469]
**Describe the Issue**

I'm using 'debugPrintfEXT' to trace the flow and debug some values. 

It works fine for *.vert, .frag files(passthrough.vert,frag_shader.frag,vert_shader.vert,post.frag)
but somehow it does not work on raytrace. (raytrace.rgen, raytrace.rchit etcs). 
Please check NVPro example (https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR, especially ray_tracing__simple ) with debugPrintfEXT.

It is very frustrating that I cannot use 'debugPrintfEXT' on ray tracing shaders.

Do you have any ideas or suggestions on how to resolve this issue?

**Valid Usage ID**
If applicable, please include the validation messages encountered leading up to the issue

**Environment:**
 - OS: Windows 10
 - GPU: GTX 2080Ti
 - SDK or header version if building from repo: SDK version 1.2.162 
 - Options enabled (synchronization, best practices, etc.):

**Comment by Tony-LunarG** [comment]
@UHFT #2472 should fix this problem

**Comment by UHFT** [comment]
What procedure I have to follow to test whether it works?

**Comment by Tony-LunarG** [comment]
You can build the validation layers from this repository and use them with your ray tracing tutorial build that has debug printfs in the shaders, or wait for the next SDK.

**Comment by Tony-LunarG** [comment]
Or if you are using Windows, https://ci.appveyor.com/project/Khronoswebmaster/vulkan-validationlayers/builds/37253285/job/mio9orlqplk3oho8/artifacts would have the layer executables that you can use.
