### ISSUE TITLE
vkCreateComputePipelines crash when VK_KHR_FRAGMENT_SHADING_RATE is enabled

### ISSUE THREAD

**Issue by turanszkij** [KhronosGroup/Vulkan-ValidationLayers#2473]
Calling vkCreateComputePipelines results in crash when the fragment shading rate extension is used and validation layers enabled. The crash reason is:
```
pipeline->graphicsPipelineCI.pViewportState was nullptr.
```
The compute pipeline doesn't have viewport state, but for some reason the call crashes on it.

**Valid Usage ID**
There are no validation layer messages using DebugUtilsMessenger callback

**Environment:**
 - OS: Windows 10 (19042.746)
 - GPU: Nvidia RTX 2060
 - SDK or header version if building from repo: SDK 1.2.162.1
 - Options enabled (synchronization, best practices, etc.): VK_EXT_DEBUG_UTILS extension enabled, VK_LAYER_KHRONOS_validation enabled
 
**Additional context**
The issue can be reproduced in the following github repo: https://github.com/turanszkij/WickedEngine
I am happy to provide additional details if required.

**Comment by turanszkij** [comment]
Additionally, I include the call stack from the crash:

```
 	VkLayer_khronos_validation.dll!CoreChecks::ValidatePrimitiveRateShaderState(const PIPELINE_STATE * pipeline, const SHADER_MODULE_STATE * src, spirv_inst_iter entrypoint, VkShaderStageFlagBits stage) Line 3561	C++
 	VkLayer_khronos_validation.dll!CoreChecks::ValidatePipelineShaderStage(const VkPipelineShaderStageCreateInfo * pStage, const PIPELINE_STATE * pipeline, const PIPELINE_STATE::StageState & stage_state, const SHADER_MODULE_STATE * module, const spirv_inst_iter & entrypoint, bool check_point_size) Line 3687	C++
 	VkLayer_khronos_validation.dll!CoreChecks::ValidateComputePipelineShaderState(PIPELINE_STATE * pipeline) Line 3996	C++
 	VkLayer_khronos_validation.dll!CoreChecks::PreCallValidateCreateComputePipelines(VkDevice_T * device, VkPipelineCache_T * pipelineCache, unsigned int count, const VkComputePipelineCreateInfo * pCreateInfos, const VkAllocationCallbacks * pAllocator, VkPipeline_T * * pPipelines, void * ccpl_state_data) Line 4855	C++
 	VkLayer_khronos_validation.dll!vulkan_layer_chassis::CreateComputePipelines(VkDevice_T * device, VkPipelineCache_T * pipelineCache, unsigned int createInfoCount, const VkComputePipelineCreateInfo * pCreateInfos, const VkAllocationCallbacks * pAllocator, VkPipeline_T * * pPipelines) Line 597	C++

```

**Comment by pdaniell-nv** [comment]
Since Vulkan CTS enables all extensions, this crash happens for all compute tests. It would be nice if this was fixed asap.

**Comment by Tony-LunarG** [comment]
Fixed with #2490

**Comment by pdaniell-nv** [comment]
Is there an ETA for when this will land in an updated SDK? I know this issue is blocking some folks. Thanks.

**Comment by Tony-LunarG** [comment]
The next SDK is scheduled to be available 3/1
