### ISSUE TITLE
Update vk_safe_struct wrappers to correctly handle pNext chains

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-ValidationLayers#248]
Currently generated safe_* struct wrappers in vk_safe_struct.h/cpp simply copy any pNext pointer values. Safe structs should be making their own complete copy of whatever is pointed to, so for pNext chains they should be replicating the whole chain so that any destruction of the original data doesn't break the safe_* struct wrapper.

**Comment by jzulauf-lunarg** [comment]
For "known" pNext structures this is possible, but for privately defined extensions it isn't.  Either the unknown types would have to be dropped or replaced with a placeholder.
