### ISSUE TITLE
descriptor image layout check should happen at submit-time instead of record-time

### ISSUE THREAD

**Issue by YunHsiao** [KhronosGroup/Vulkan-ValidationLayers#2487]
**Describe the Issue**
Descriptor image layout checks now happen as soon as any vkCmdDraw* is called, which can lead to false positives when the layout transitions are recorded into a separate command buffer afterward but being submitted first.

**Valid Usage ID**
VUID-VkDescriptorImageInfo-imageLayout-00344: Validation Error: [ VUID-VkDescriptorImageInfo-imageLayout-00344 ] Object 0: handle = 0x146fdeb0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xde55a405 | vkCmdDraw(): Cannot use VkNonDispatchableHandle 0x37d77e000000007b[] (layer=0 mip=0) with specific layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL that doesn't match the previous known layout VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL. The Vulkan spec states: imageLayout must match the actual VkImageLayout of each subresource accessible from imageView at the time this descriptor is accessed as defined by the image layout matching rules (https://vulkan.lunarg.com/doc/view/1.2.162.1/windows/1.2-extensions/vkspec.html#VUID-VkDescriptorImageInfo-imageLayout-00344)

**Environment:**
 - OS: Windows 10 20H2
 - GPU: Radeon RX550/550 Series
 - SDK or header version if building from repo: 1.2.162
 - Options enabled (synchronization, best practices, etc.):

**Additional context**

**Comment by YunHsiao** [comment]
Sorry, the false positive is my bad. The vkCmdCopyBuffer stuff was mistakenly put in the second command buffer. After correcting this the error was gone. But still, I wonder whether the current approach would give false negatives though, for there is just no way to tell what the image layout was before the current command buffer.

**Comment by mark-lunarg** [comment]
Thanks very much for the update @YunHsiao.  We have somebody currently looking at this from our side to see if action is needed, and appreciate you bringing this to our attention.  Looking forward to hearing from you in the future!

**Comment by jzulauf-lunarg** [comment]
@YunHsiao  -- there are both record time and submit time checks.  Effectively we track the *first* use of a given resource and check that against the global (submit) image layout at submit time.  Additionally "update after bind" is validated at queue submit time... though there is an open issue against the current handling of that case.

**Comment by YunHsiao** [comment]
Alright, although arguably not ideal that sounds good enough for my case, so closing this.
