### ISSUE TITLE
Validation for descriptor pool over-allocation turned off too completely

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-ValidationLayers#2488]
**Describe the Issue**
When KHR_maintenance1 is enabled either explicitly or implicitly by using vulkan 1.1+, the validation layers omit validation for descriptor sets being allocated from descriptor pools that don't have enough space reserved.

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/ab73ad6376066d73c6f592aca91cb423c8abfc63/layers/descriptor_sets.cpp#L2904-L2927

This was removed in 64b5bb7c40322b, perhaps because the expectation is that the driver will return `VK_ERROR_OUT_OF_POOL_MEMORY` in this case. However the wording of the spec is slightly less strict than that - it only requires that **if** the driver fails to allocate, it should return that error message instead of a more general OOM error. It doesn't require the error if the driver is able to over-allocate or doesn't care about one of the limits.

The effect of this is that applications can have a bug - allocating too many descriptors of a type or sets out of a pool - and have it work on one GPU/driver without any validation errors, and then have it fail on another GPU/driver. This is a particular problem because it's a common misunderstanding that the pool descriptor type sizes specified are total across all descriptor sets.

Perhaps instead of being completely muted the error could be demoted to a warning?

CC @pdaniell-nv 

**Valid Usage ID**
This particularly applies to VUID-VkDescriptorSetAllocateInfo-descriptorSetCount-00306 and VUID-VkDescriptorSetAllocateInfo-descriptorPool-00307, but I don't know off the top of my head if there are other VUIDs in this area.

**Environment:**
 - OS: Windows 10
 - GPU: NV 2080 & AMD RX 480
 - SDK or header version if building from repo: 1.2.166
 - Options enabled (synchronization, best practices, etc.): Default options only, no extras.

**Comment by mark-lunarg** [comment]
@baldurk, you're right, and without a change to the spec our best option will be to add these checks (without the 1.0 context limits) to the best-practices validation.  Maybe these VUs could be added back into the spec?

**Comment by baldurk** [comment]
I think if nothing else then it should be added somewhere, but my concern with adding this to the best practices validation is that not everyone is going to run with that enabled so it would be easy to miss this check. Also it's not really a best practice to correctly size pools, but indeed it's also not technically invalid and I'm not sure what's a better alternative.

Arguably applications should be checking return codes properly, but in the case of a developer who misunderstands the limits it's hard for them to go from an opaque error return code to realising _why_ the pool is out of space. The user who reported this to me originally was under the impression that only `maxSets` mattered and that the pool could not be running out of space until that many sets had been allocated.

Looking at the history of this (gitlab vulkan issue 686) this originated because of libraries/middleware using an unknown pool, they checked the return code of `vkAllocateDescriptorSets` to know when a new pool was needed. The layers of course can't differentiate between the intent so either you have messages in that case which would be ignored, or you don't have messages in this case :(. I'm not sure what the best solution is.
