### ISSUE TITLE
GPU-AV check index buffer out-of-bounds

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/Vulkan-ValidationLayers#2492]
We recently had a GPU hang that GPU Assisted Validation was unable to catch.  We were running with robustBufferAccess disabled and had a -1 in our index buffer.  The draw with the index buffer was dispatched from an indirect draw command.  It would be a nice feature addition if GPUAV could check this case since we couldn't catch it with validation or GPUAV.

@Tony-LunarG @greg-lunarg

**Comment by greg-lunarg** [comment]
@Tony-LunarG I think the technique we chatted about the other day where we insert a compute pipeline to check buffers before they are consumed by the API might be the ticket here. This is another case that would help justify the infrastructure investment.
