### ISSUE TITLE
Incorrect validation error claiming pipeline subpass and render pass subpass index mismatches

### ISSUE THREAD

**Issue by Duttenheim** [KhronosGroup/Vulkan-ValidationLayers#2498]
**Describe the Issue**
I get a seemingly incorrect validation error for every render pass which uses more than 1 subpass, claiming the pipeline is built for another subpass index. I can reproduce the error 100% and present a RenderDoc capture illustrating this issue. It seems to me that the subpass index validation is off by one if a render pass has more than one subpass; Pipeline was built for subpass 1 but used in subpass 0, Pipeline was built for subpass 2 but used in subpass 1, etc are the messages I am getting.

**Valid Usage ID**
24337 API High Miscellaneous 951775942

**Environment:**
 - OS: Windows 10
 - GPU: Radeon RX 480
 - SDK or header version if building from repo: 
 - Options enabled (synchronization, best practices, etc.):

I am generating subpass data in secondary command buffers before I record the primary command buffer which begins and ends render passes, as well as progresses to the next subpass.

![image](https://user-images.githubusercontent.com/6490176/105783635-3cc19a80-5f77-11eb-81a9-bc9f692656c5.png)

In this image, the error on the right is highlighted, and in the left we can clearly see that a call to vkCmdNextSubpass is performed.

**Comment by ziga-lunarg** [comment]
@Duttenheim Are you still receiving this error?

**Comment by Duttenheim** [comment]
I think this turned out to be correctly reported, but for whatever reason my PSO wasn't correctly setup with the next subpass, even if it appeared so in the capture. 

Sorry for not getting back about this earlier. You can close this one :)

**Comment by ziga-lunarg** [comment]
@Duttenheim Thanks for letting us know!
