### ISSUE TITLE
nullDescriptor crash for acceleration structures with VK_NV_RAY_TRACING

### ISSUE THREAD

**Issue by Nimanf** [KhronosGroup/Vulkan-ValidationLayers#2520]
**Describe the Issue**
Spec is updated to allow "**nullDescriptor**" (**VK_EXT_robustness2**) to be used with both **VK_NV_RAY_TRACING** and the new official VK_KHR extensions (on latest drivers and SDK 1.2.162.1), so a null descriptor is interpreted as a miss shader.

However, there are bugs in validation layers in which those acceleration structure descriptors are being accessed to retrieve some state tracking, even though VK_EXT_robustness2 is enabled. Therefore such nullDescriptor will cause a crash with VK_NV_XXX but it works correctly with VK_KHR_XXX.

**Environment:**
 - OS: Windows 10, 1909
 - GPU: RTX 2080 TI
 - SDK or header version if building from repo: SDK 1.2.162.1

**Comment by ziga-lunarg** [comment]
Any chance you can provide a code sample for this? @Nimanf

**Comment by ncesario-lunarg** [comment]
Looks like this was supposed to be resolved by https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/3f145ae?

**Comment by ziga-lunarg** [comment]
Looks like it, I assume we should close this issue?

**Comment by ncesario-lunarg** [comment]
Looks like that fix was included in the 1.2.162 SDK.

@Nimanf any chance you could try this on the latest SDK? I vaguely remember another change related to `nullDescriptor`s that I think went in after 1.2.162, but having difficulty finding it at the moment.

**Comment by Nimanf** [comment]
That commit is for the same old SDK I initially reported for 1.2.162 SDK.
I tried the latest 1.2.182 SDK, and got a crash using nullDescriptor (Note that KHR + nullDescriptor works correctly):

The crash is in `ValidateMemoryIsBoundToAccelerationStructure `when it is called by `ValidateAccelerationStructureUpdate()` for `VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV` case in descriptor_sets.cpp.

I might be able to provide a binary app with Vulkan debug functionality later, if that helps.
Thanks

**Comment by ncesario-lunarg** [comment]
A binary or a gfxreconstruct trace (which would be even better :)) would definitely help.

"KHR + nullDescriptor," means using the KHR ray tracing extensions as opposed to the NV ones?

**Comment by Nimanf** [comment]
Yes, KHR raytracing extensions has no issue with nullDescriptor, only crashes with NV_ray_tracing
