### ISSUE TITLE
Performance optimization suggestions

### ISSUE THREAD

**Issue by Novum** [KhronosGroup/Vulkan-ValidationLayers#2537]
Context: I've been looking at validation layer perf a bit and those are my findings. I have been profiling with our use case (Doom Eternal) and on Windows 10 with MS compiler and STL. Disclaimer: I don't completely understand the code and I might have unknowingly broken things.

1. Consider using a better hash map than std::unordered_map. I've been doing experiments with robin hood hashing (https://github.com/martinus/robin-hood-hashing). To actually gain performance I had to remove the small map optimizations here, because they are detrimental with the faster map:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/669dfd5ce67f3c818e963f5a729a2335b098d7ff/layers/vk_layer_data.h#L551
And just replace it with `class small_unordered_map : public robin_hood::unordered_map< Key, T >`. Note: If for some reason the values need to be immovable (I don't think so) you need to specifically use `robin_hood::unordered_node_map`.
Maybe there are even better options, I didn't try other ones.

2. Use try_emplace and remove additional pointer indirection for GlobalImageLayoutMap/CommandBufferImageLayoutMap. The additional indirection via std::unique_ptr isn't useful because the maps already allocate individual nodes for each value. The entire code at https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/buffer_validation.cpp#L4171 can then just be `auto inserted = map.try_emplace(image_state.image, image_state.subresource_encoder.SubresourceCount())` constructing the GlobalImageLayoutRangeMap in place or returning the existing one. This avoids the double lookup. Same pattern for the CommandBufferImageLayoutMap code.

3. Alias the memory for the small and big maps in https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/subresource_adapter.h#L536 & only construct and destruct the one actually used. At least with the MS STL just calling the BigMap constructor will cause a memory allocation for the root node of the std::set which wastes a lot of perf. I used `std::aligned_storage<std::max(sizeof(SmallMap), sizeof(BigMap)), std::max(sizeof(SmallMap), sizeof(BigMap))> storage` for this which guarantees that everything is aligned properly etc. Then just do e.g. `(*static_cast<BigMap*>(&storage)).~BigMap()` when in big map mode etc.

Together those saved ~100ms in the main menu for us, down from ~450 to ~350 on a Ryzen 3700X. Still slow, but it's something.

**Comment by jeremyg-lunarg** [comment]
Since #2581 and #2618 have merged, we've addressed the specific suggestions given in this Issue. Thank you very much for the feedback. However, closing this does not mean we are done optimizing against Doom Eternal.
