### ISSUE TITLE
vkCmdBindVertexBuffers2EXT() should accept VK_NULL_HANDLE if nullDescriptor is enabled

### ISSUE THREAD

**Issue by mosra** [KhronosGroup/Vulkan-ValidationLayers#2541]
**Describe the Issue**

While `vkCmdBindVertexBuffers()` accepts null `pBuffers` entries when the `nullDescriptor` feature from `VK_EXT_robustness2` is enabled, `vkCmdBindVertexBuffers2EXT()` does not. I checed the spec, and [it's allowed in this command as well](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdBindVertexBuffers2EXT.html), so I think it's a validation layer bug. 

The former got reported and fixed in #2309 and #2310 and I thought about opening a PR to fix this case too, unfortunately I wasn't able to find the exact place where this check is done, sorry :)

**Valid Usage ID**

I get the following when calling `vkCmdBindVertexBuffers2EXT()` with a null `pBuffers` entry and the `nullDescriptor` feature enabled:

```
UNASSIGNED-GeneralParameterError-RequiredParameter(ERROR / SPEC): msgNum: -1711571459 - Validation Error: [ UNASSIGNED-GeneralParameterError-RequiredParameter ] Object 0: handle = 0x560747358740, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x99fb7dfd | vkCmdBindVertexBuffers2EXT: required parameter pBuffers[0] specified as VK_NULL_HANDLE
    Objects: 1
        [0] 0x560747358740, type: 3, name: NULL
VUID-vkCmdBindVertexBuffers2EXT-pBuffers-parameter(ERROR / SPEC): msgNum: 1747617674 - Validation Error: [ VUID-vkCmdBindVertexBuffers2EXT-pBuffers-parameter ] Object 0: handle = 0x560746c56f80, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x682a878a | Invalid VkBuffer Object 0x0. The Vulkan spec states: pBuffers must be a valid pointer to an array of bindingCount valid VkBuffer handles (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdBindVertexBuffers2EXT-pBuffers-parameter)
    Objects: 1
        [0] 0x560746c56f80, type: 1, name: NUL
```

I get no validation messages when using `vkCmdBindVertexBuffers()` instead. In both cases the driver seems to do the correct thing, supplying zeros for given attribute.

**Environment:**
 - OS: ArchLinux
 - GPU: Intel, Mesa 20.3.4
 - SDK or header version if building from repo: [`vulkan-validation-layers`](https://archlinux.org/packages/extra/x86_64/vulkan-validation-layers/) 1.2.166
 - Options enabled (synchronization, best practices, etc.): just the `VK_LAYER_KHRONOS_validation` layer

**Additional context**

**Comment by Joshua-Ashton** [comment]
Please fix this. It makes validation unusable for us in DXVK and VKD3D-Proton.

**Comment by ncesario-lunarg** [comment]
It looks like there is a change needed for vk.xml to fix this. I created an internal issue to get this changed upstream (assuming this is what needs to be done).

If you are blocked by this, you might be able to either use the `khronos_layer.message_id_filter` [layer setting](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/vk_layer_settings.txt) or the environment variable `VK_LAYER_MESSAGE_ID_FILTER` to filter out this particular message in the short term.

**Comment by ncesario-lunarg** [comment]
#2648 works with the xml change I believe is necessary. Assuming this is the correct course, I will merge that PR once we pick up the xml change from upstream.
