### ISSUE TITLE
XFB stage is removed as valid for XFB_COUNTER_READ as part of refactor

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-ValidationLayers#2542]
@jeremyg-lunarg [This change](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2519) effectively undoes my fix in [this change](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2506)

Could you please rectify this?

**Comment by ShabbyX** [comment]
I suspect it's sufficient to update the spec snippet in `scripts/sync_val_gen.py` according to [this MR](https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/4355/diffs), but I'm not able to run `scripts/helper_file_generator.py` (errs on `from generator import *`).

**Comment by jeremyg-lunarg** [comment]
Doh! Good catch. I'll get a fix up shortly.

**Comment by jeremyg-lunarg** [comment]
This should still be fixed even after syhcnronization2 is closed.  Please let us know if you find otherwise.
