### ISSUE TITLE
glslang should only be required if BUILD_TESTS ON

### ISSUE THREAD

**Issue by SpaceIm** [KhronosGroup/Vulkan-ValidationLayers#2548]
**Describe the Issue**

Looking at source code, `glslang` is only used in tests (included in `tests/vktestframework.h`).
Currently, CMakeLists requires `glslang` if `BUILD_TESTS OR BUILD_LAYERS`, and `glslang` is linked into `VkLayer_${target}` targets (`VkLayer_khronos_validation`) while it's not used at all.

**Additional context**

I've tested building `Vulkan_Utils` and `VkLayer_khronos_validation` 1.2.154.0 without glslang + BUILD_TESTS OFF + a fake glslang interface target to make CMakeLists happy, and it works.

**Comment by mark-lunarg** [comment]
@ncesario-lunarg, this may be true now -- we used to rely on glslang for the spirv-tools it included and they might now be discrete components as far as the build goes.

**Comment by ncesario-lunarg** [comment]
I believe this should be resolved with #3076 and  #3120.

**Comment by SpaceIm** [comment]
I think also.

There is still a reference to glslang include dir in VkLayer_khronos_validation: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/52dbd08362270a1f7819a981995916248734df33/layers/CMakeLists.txt#L294

But at least it doesn't hurt (it's just misleading).

**Comment by ncesario-lunarg** [comment]
Yep, that is incorrect; nice catch! For the short term, that shouldn't affect builds with `-DBUILD_TESTS=OFF`, but let me know if you're seeing different results. I will remove that in an upcoming change.
