### ISSUE TITLE
Warning waiting/testing unsubmitted fences

### ISSUE THREAD

**Issue by jzulauf-lunarg** [KhronosGroup/Vulkan-ValidationLayers#255]
From [LunarXchange 785](https://vulkan.lunarg.com/issue/view/5b5f09b366315148d1e447df) 

> If I call vkGetFenceStatus for fence in unsignalled state I get the following error in LunarG validation layers. I think that it is normall to call vkGetFenceStatus for fences in any state, because vkGetFenceStatus is used to determine state.
> 
> "vkGetFenceStatus called for fence 0x9 which has not been submitted on a Queue or during acquire next image"
> 
> I can call vkGetFenceStatus immidiately after fence was resetted and I also get the same error.
> 
> The similar issue is with vkWaitForFences (if it is used only to determine state, it means that it is called with timeout value equals zero)

The cause is that since the fence hasn't been submitted and thus can't possibly be done, core validation thinks this is unusual enough to warn about.

Should this be subject to the general reduction of warnings and eliminated? Is there another layer where this warning might be apropos to keep (and a tracking issue for warnings to be implemented after elimination from core validation)?

@mark-lunarg @mikes-lunarg @tobine

**Comment by tobine** [comment]
After a bit of thought I think the warning can just be killed. The warning would be more useful if it was actually valid based on what it reports, meaning that the fence had not really ever been submitted. However, the warning is flagged for any "UNSIGNALED" fence which means that the fence may very well have been submitted and/or reset, in which case the warning is just wrong.

So, I vote kill it.

**Comment by jzulauf-lunarg** [comment]
@tobine -- i believe unsignalled transitions to "IN_FLIGHT" for unsignalled but submitted a "Shroedinger's Cat" state where it's not possible to know the state until somebody opens the box.  So I think it's correct as is.

So assuming it's correct, still kill it?

**Comment by tobine** [comment]
@jzulauf-lunarg if a fence is submitted and then reset it goes back to UNSIGNALED state. For that case the warning is just wrong. I think the warning is useful, but if we want to keep it, it should be reworded. An obvious rewording wasn't apparent to me so I voted kill.
