### ISSUE TITLE
Question for windows build: install folder and symbols export

### ISSUE THREAD

**Issue by SpaceIm** [KhronosGroup/Vulkan-ValidationLayers#2550]
**Describe the Issue**

I don't know if it's the good place to ask. Maybe I miss something, but:
- why `VkLayer_khronos_validation` is built as `SHARED` and not `MODULE`, and why its symbols are exported? I thought that it was not supposed to be linked, but dynamically loaded by `vulkan-loader`. AFAIR, import lib is not even provided in Vulkan SDK. Moreover `-fvisibility=hidden` is passed to GNU compilers: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/f9eec56cc82f4b3c268caac39be736105a209282/CMakeLists.txt#L124
- why `VkLayer_khronos_validation.dll` and its jsonfile are not installed in bin folder? It's usually where runtime (dll/exe) are installed on Windows (and vulkan sdk of LunarG puts all its validation layers -including this one- in bin folder).

**Comment by juan-lunarg** [comment]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4803 addresses the first half of this PR.

The second half of this PR is valid but is covered by https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2861 which I'll use to track that issue instead.

**Comment by juan-lunarg** [comment]
@SpaceIm see the following 2 issues, you are pointing out valid problems. The main issue is back-compat.
- https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4804
- https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4805
