### ISSUE TITLE
vkCmdDrawIndexed validation does not respect VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT

### ISSUE THREAD

**Issue by danielmaciel** [KhronosGroup/Vulkan-ValidationLayers#2565]
The following validation does not respect VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT when using statically used descriptors:
```
Validation Error: [ VUID-vkCmdDrawIndexed-None-02699 ] Object 0: handle = 0x150000000015, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0xa44449d4 | VkDescriptorSet 0x150000000015[] encountered the following validation error at vkCmdDrawIndexed() time: Descriptor in binding #1 index 1 is being used in draw but has never been updated via vkUpdateDescriptorSets() or a similar call. The Vulkan spec states: Descriptors in each bound descriptor set, specified via vkCmdBindDescriptorSets, must be valid if they are statically used by the VkPipeline bound to the pipeline bind point used by this command (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdDrawIndexed-None-02699)
```

The spec states that:
For descriptor set bindings created with the VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT bit set, all descriptors in that binding that are dynamically used must have been populated before the descriptor set is consumed.

For descriptor set bindings created *without the VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT bit set*, all descriptors in that binding that are *statically used* must have been populated before the descriptor set is consumed.

**Comment by Tony-LunarG** [comment]
I've written a test in #2580 that shows a descriptor that hasn't been updated doesn't get an error if the PARTIALLY_BOUND flag is set in its binding flags, and it does get 02699 if it isn't.  @danielmaciel could you describe what in your use case is different from the simple test that is triggering the error where the test does not?

**Comment by danielmaciel** [comment]
This is what my uniforms look like in my shader:
```glsl
layout(set = 1, binding = 0) uniform sampler TextureSamplers[2];
layout(set = 1, binding = 1) uniform texture_2d Textures2D[];
layout(set = 1, binding = 2) uniform texture_3d Textures3D[];
layout(set = 1, binding = 3) uniform texture_cube TexturesCube[];
```
The error is about the second binding which is not fully updated (some items of the array are not updated).
Let me know if you need further input.

**Comment by Tony-LunarG** [comment]
Ok, I pushed a change to the test's shader to look like:

layout(set = 0, binding = 0) uniform foo_0 { int val; } doit;
layout(set = 0, binding = 1) uniform sampler TextureSamplers[2];
layout(set = 0, binding = 2) uniform texture2D Textures2D[];

I didn't update the samplers or textures and I still get no false positives from validation.
@danielmaciel could you provide a small program to reproduce what you are seeing, or modify the test in #2580 to match you use case?  Or a gfxreconstruct trace would work as well.

**Comment by danielmaciel** [comment]
Hi Tony,

About this phrase
```
Descriptor in binding #1 index 1 is being used in draw but has never been updated via vkUpdateDescriptorSets() or a similar call.
```
Does that mean that the binding 1 array index 1 is being used but never updated?
So that would mean that on your test you need to update the first element of the array but not the second, and then try using the second element.

Kind regards,
Daniel

**Comment by danielmaciel** [comment]
Okay I tested updating the second element of the array, and now it says:
```
Descriptor in binding #1 index 2 is being used in draw but has never been updated via vkUpdateDescriptorSets() or a similar call.
```
So there's that.

**Comment by Tony-LunarG** [comment]
Ok, I updated the first element of the array and used the second, and received no validation errors.  
What does your call to CreateDescriptorSetLayout look like, and what is in the pNext of the CreateInfo?

**Comment by danielmaciel** [comment]
```C
      {
          VkDescriptorSetLayoutBinding SamplerLayoutBinding = {};
          SamplerLayoutBinding.binding = 0;
          SamplerLayoutBinding.descriptorType = VK_DESCRIPTOR_TYPE_SAMPLER;
          SamplerLayoutBinding.descriptorCount = 2;
          SamplerLayoutBinding.stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;

          VkDescriptorSetLayoutBinding TexturesLayoutBinding2D = {};
          TexturesLayoutBinding2D.binding = 1;
          TexturesLayoutBinding2D.descriptorType = VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE;
          TexturesLayoutBinding2D.descriptorCount = RenderPath->MaxTextureCount;
          TexturesLayoutBinding2D.stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;

          VkDescriptorSetLayoutBinding TexturesLayoutBinding3D = {};
          TexturesLayoutBinding3D.binding = 2;
          TexturesLayoutBinding3D.descriptorType = VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE;
          TexturesLayoutBinding3D.descriptorCount = RenderPath->MaxTextureCount;
          TexturesLayoutBinding3D.stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;

          VkDescriptorSetLayoutBinding TexturesLayoutBindingCube = {};
          TexturesLayoutBindingCube.binding = 3;
          TexturesLayoutBindingCube.descriptorType = VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE;
          TexturesLayoutBindingCube.descriptorCount = RenderPath->MaxTextureCount;
          TexturesLayoutBindingCube.stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;

          VkDescriptorSetLayoutBinding LayoutBindings[] = {
              SamplerLayoutBinding,
              TexturesLayoutBinding2D,
              TexturesLayoutBinding3D,
              TexturesLayoutBindingCube,
          };

          VkDescriptorBindingFlags BindingFlags = VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT;
          // TODO: Use 'VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT'. We can only use it with the last binding.
          VkDescriptorBindingFlags LayoutBindingFlags[] = {
              0,
              BindingFlags,
              BindingFlags,
              BindingFlags,
          };
          Assert(ArrayCount(LayoutBindingFlags) == ArrayCount(LayoutBindings));

          VkDescriptorSetLayoutBindingFlagsCreateInfo BindingFlagsInfo = {};
          BindingFlagsInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_BINDING_FLAGS_CREATE_INFO;
          BindingFlagsInfo.bindingCount = ArrayCount(LayoutBindings);
          BindingFlagsInfo.pBindingFlags = &BindingFlags;

          VkDescriptorSetLayoutCreateInfo LayoutCreateInfo = {};
          LayoutCreateInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
          LayoutCreateInfo.bindingCount = ArrayCount(LayoutBindings);
          LayoutCreateInfo.pBindings = LayoutBindings;
          LayoutCreateInfo.pNext = &BindingFlagsInfo;

          VkResult Result = vkCreateDescriptorSetLayout(RenderPath->Device, &LayoutCreateInfo, RenderPath->Allocator,
                                                        &RenderPath->TextureDescriptorSetLayout);
          Assert(Result == VK_SUCCESS);
      }
```
The `ArrayCount(...)` function returns the number of elements on a given array.
The only major difference I see is I am using Vulkan 1.2 where you are using 1.1 plus extensions. Is that something I should watch for? Maybe if I am not declaring a specific extension or something...

**Comment by Tony-LunarG** [comment]
That all looks good.  Vulkan 1.2 made descriptor indexing core, so you shouldn't need the extension.
Is the "used but not updated" error the very first validation error that you get?  And are you getting it from your call to vkCmdDrawIndexed and not from vkQueueSubmit?

**Comment by danielmaciel** [comment]
> Is the "used but not updated" error the very first validation error that you get?
Yes.
> And are you getting it from your call to vkCmdDrawIndexed and not from vkQueueSubmit?
`vkCmdDrawIndexed` yes.
I'll see if I can get this `gfxreconstruct` thing you asked about.
Thanks,
Daniel

**Comment by Tony-LunarG** [comment]
We'll also need to know what graphics card you are using, hopefully something we have here.

**Comment by Tony-LunarG** [comment]
And if you are getting validation layers from an SDK, what SDK version you're using

**Comment by danielmaciel** [comment]
Radeon 6800 XT, using RADV on Linux
I am using validation layers from git, compiling it myself, master branch (clean clone + build from a couple of days ago).

**Comment by Tony-LunarG** [comment]
I have an RX 5700 running on RADV on Linux.  I think there's at least a chance a gfxreconstruct trace would play across devices.  If that's the way you want to go.  Output from VK_LAYER_LUNARG_api_dump might help too.

**Comment by Tony-LunarG** [comment]
I've provided an example #2580 showing that, at least in the test case I wrote, validation does respect VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT.  Closing, but please open another issue if you get a reproduction case you can share.  Thanks.

**Comment by danielmaciel** [comment]
Hi @Tony-LunarG  I discovered my problem. The line `BindingFlagsInfo.pBindingFlags = &BindingFlags;` should have been `BindingFlagsInfo.pBindingFlags = LayoutBindingFlags` instead. It was my mistake. Thanks for your help.
