### ISSUE TITLE
Investigate cause of trace crash in 

### ISSUE THREAD

**Issue by ncesario-lunarg** [KhronosGroup/Vulkan-ValidationLayers#2576]
See https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2564 for context, specifically [this](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2564/files#r579391706) comment.

In short the type check on https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2564/files#diff-031322650ec7e38a7158e5f2aa110b3b4f07ff124fd75b039cd46dc1bb67e91dR878 should not be necessary, but without it we will crash in some cases since a BufferDescriptor is being tracked instead of a SamplerDescriptor https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/9ce7c8e67684d4a9448d8d909931cd443c361eb7/layers/state_tracker.cpp#L3784.

FYI @locke-lunarg.

**Comment by spencer-lunarg** [comment]
@ncesario-lunarg can this be closed?

**Comment by ncesario-lunarg** [comment]
I'd have to revisit the original crash to see if this was fixed, but I don't think it was. This is something I'm hoping will get resolved as part of a wider "shader validation cleanup," but needs to be verified.

**Comment by spencer-lunarg** [comment]
Closing for now, please reopen if we reproduce it
