### ISSUE TITLE
Feature request: Layer for simulating errors (especially device loss)

### ISSUE THREAD

**Issue by haasn** [KhronosGroup/Vulkan-ValidationLayers#2577]
It can be difficult to test failure paths, especially for device loss, without a good way of artificially triggering those types of errors. It would be very useful to have a layer that can insert errors into vulkan calls that allow them.

In particular, I'm interested in simulating a device loss. This means that the layer should be capable of randomly/programmatically inserting device loss errors - and ideally, once a device is lost, it should remain that way until the device is recreated. (To simulate what happens for real implementations)

This is not entirely trivial because not all vulkan commands are allowed to return `VK_ERROR_DEVICE_LOST`.

Another type of error that would be useful to test is simulating device OOM / host OOM.

**Comment by ncesario-lunarg** [comment]
This sounds like a great idea @haasn. As you mentioned this would most likely not be a trivial effort, and we don't have anything like that planned that I'm aware of.

I don't think this is necessarily a "_validation_ layer" project/issue, but I'm also not sure where the best place would be to track this.

**Comment by ncesario-lunarg** [comment]
Tracking via project card [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/projects/4#card-55704840).
