### ISSUE TITLE
VK_EXT_debug_utils crashes with vkCmdBeginDebugUtilsLabelEXT and vkCmdEndDebugUtilsLabelEXT 

### ISSUE THREAD

**Issue by Nimanf** [KhronosGroup/Vulkan-ValidationLayers#258]
We are getting crashes with vkCmdBeginDebugUtilsLabelEXT and vkCmdEndDebugUtilsLabelEXT .

Despite we get valid function pointers from vkInstance, segmentation fault happens on above two methods.

- enumerations of this extension shows it is supported
- We successfully receive pointers for all other methods (such as vkCreateDebugUtilsMessengerEXT) and they work correctly
- we are using VK_KHR_SWAPCHAIN and VK_KHR_SURFACE.
- Can be reproduced on both Windows and Linux with SDK 1.1.77
- happens with both debug layer (VK_LAYER_LUNARG_standard_validation), and without any debug layer.

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
Program terminated with signal SIGSEGV, Segmentation fault.
```

**Comment by MarkY-LunarG** [comment]
And validation layers are or are not enabled?  Can you provide a full call-stack too?  Or is it returning `NULL` from `vkGetInstanceProcAddr()`?

**Comment by Nimanf** [comment]
vkGetInstanceProcAddr returns valid pointers correctly for all the functions. However, once I call vkCmdBeginDebugUtilsLabelEXT/vkCmdEndDebugUtilsLabelEXT, it seems inside  CmdBeginDebugUtilsLabelEXT() it is getting NULL for dispatch key/table from commandBuffder. 

My crash is with VK_LAYER_LUNARG_standard_validation enabled or disabled. Also got the same crash when I disabled the entire validation layer.

`info = {sType = VK_STRUCTURE_TYPE_DEBUG_UTILS_LABEL_EXT, pNext = 0x0, pLabelName = 0x40aedf "Clear", color = {1, 0, 0, 1}}`
Sorry can't provide further stack call in public

**Comment by MarkY-LunarG** [comment]
No worries, based on your description I'm wondering if this is a loader bug.  I'll look into it and try to reproduce it.

**Comment by farnoy** [comment]
I am also getting this on 1.1.82.0. If I run my application under RenderDoc, it works fine. Maybe we're missing a default handler for this function when no external tool is hooked in?

**Comment by TiemoJung** [comment]
Just stumbled over this too while porting from debug_report and debug_marker to debug_utils.
Call stack:

> [Inline Frame] VkLayer_core_validation.dll!std::_Deallocate(void * _Ptr, unsigned __int64) Line 103	C++
> [Inline Frame] VkLayer_core_validation.dll!std::allocator<char>::deallocate(char *) Line 720	C++
> [Inline Frame] VkLayer_core_validation.dll!std::_Wrap_alloc<std::allocator<char> >::deallocate(char * _Count, unsigned __int64) Line 987	C++
> [Inline Frame] VkLayer_core_validation.dll!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy(bool) Line 2258	C++
> VkLayer_core_validation.dll!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::~basic_string<char,std::char_traits<char>,std::allocator<char> >() Line 1017	C++
> VkLayer_core_validation.dll!core_validation::PostCallRecordCmdEndDebugUtilsLabelEXT(core_validation::layer_data * dev_data, VkCommandBuffer_T * commandBuffer) Line 12619	C++
> VkLayer_core_validation.dll!core_validation::CmdEndDebugUtilsLabelEXT(VkCommandBuffer_T * commandBuffer) Line 12628	C++
> VkLayer_object_tracker.dll!object_tracker::CmdEndDebugUtilsLabelEXT(VkCommandBuffer_T * commandBuffer) Line 735	C++
> VkLayer_parameter_validation.dll!parameter_validation::vkCmdEndDebugUtilsLabelEXT(VkCommandBuffer_T * commandBuffer) Line 12688	C++
> VkLayer_threading.dll!threading::CmdEndDebugUtilsLabelEXT(VkCommandBuffer_T * commandBuffer) Line 5898	C++
> vulkan-1.dll!00007ffce9983cba()	Unknown

**Comment by MarkY-LunarG** [comment]
@lenny-lunarg is assigned this, now.  I believe it's a loader bug, but he should verify.  It would need to migrate over to KhronosGroup/Vulkan-Loaders.

**Comment by mark-lunarg** [comment]
We believe this issue has been fixed.  If any issues still manifest, please reopen this issue or file a new one.  Thanks!

**Comment by Reon90** [comment]
Have the same issue in 1.1.126.0
