### ISSUE TITLE
Threading layer doesn't report the API entry points during a threading error.

### ISSUE THREAD

**Issue by jzulauf-lunarg** [KhronosGroup/Vulkan-ValidationLayers#259]
Based on user experience in [LunarXchange 786](https://vulkan.lunarg.com/issue/view/5b602dcb66315148d1e44815), the threading layer reporting should included the API calls involved in the thread conflict (at least the current one, and one of the conflicting ones).

If 786 the developer was given an error while calling a function that did not have "external synchronization" requirements, but that conflicted with a call that *did*.  This led the developer to believe this was a false positive in the layer.  Listing the conflicting entry points would all direct search of the spec for the external synchronization requirements, improving the usability of the error message.

**Comment by mark-lunarg** [comment]
Dup of issue #47.
