### ISSUE TITLE
Commit source for vulkan_wrapper generator

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#26]
**Issue by [tobine](https://github.com/tobine) (MIGRATED)**
_Tuesday Apr 25, 2017 at 16:41 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1697_

----

This stems from a [Pull request](https://github.com/googlesamples/android-vulkan-tutorials/pull/7) in android-vulkan-tutorials repo. @alessandroborges wants to update vulkan_wrapper, but changes really need to be made in the source generator which is not currently public.

This is a tracking issue to commit the vulkan_wrapper generator to this repo.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/ggfan"><img src="https://avatars3.githubusercontent.com/u/10564521?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ggfan](https://github.com/ggfan) (MIGRATED)**
_Tuesday Apr 25, 2017 at 17:21 GMT_

----

adding @AlessandroBorges to this conversation.

**Comment by mark-lunarg** [comment]
This script is checked in as of 5/2018, though it now resides in the Vulkan-Tools repository.
