### ISSUE TITLE
VK_KHR_xlib_surface and VK_LAYER_LUNARG_standard_validation are not compatible

### ISSUE THREAD

**Issue by ProgramMax** [KhronosGroup/Vulkan-ValidationLayers#260]
Attempting to use a VkSurfaceKHR object created via VK_KHR_xlib_surface will cause errors in validation. For example:

(null)(ERROR / SPEC): msgNum: -1 - Instance Extension VK_KHR_xlib_surface is not supported by this layer.  Using this extension may adversely affect validation results and/or produce undefined behavior.

[152346:152346:0515/174651.640546:343954747360:ERROR:vulkan_instance.cc(24)] Object: 0x1ff962de8a20 (Type = 26) | Invalid SurfaceKHR Object 0x1ff962de8a20. The spec valid usage text states 'surface must be a valid VkSurfaceKHR handle' (https://www.khronos.org/registry/vu$
kan/specs/1.0-extensions/html/vkspec.html#VUID-vkGetPhysicalDeviceSurfaceSupportKHR-surface-parameter)

This came up when adding Vulkan support to Chromium. The bug for that is here: https://bugs.chromium.org/p/chromium/issues/detail?id=843346

**Comment by mark-lunarg** [comment]
@ProgramMax, I modified the cube demo in Vulkan-Tools to run with Xlib and it works as expected, running with no validation errors.  Can you ensure that the **BUILD_WSI_XLIB_SUPPORT** build option is defined?  It would appear that the only way to generate the errors you are seeing is if the validation layers were built without this option.

**Comment by mark-lunarg** [comment]
The **BUILD_WSI_XLIB_SUPPORT** option is enabled by the CMake system whenever **CMAKE_SYSTEM_NAME** is "Linux".  CMake should fail if this is enabled and X11 isn't installed.  Android uses a different build procedure which is partially CMake-based, and is completely separate from the main build system (see the **build-android** directory).  Each display server uses platform-specific objects, so each is protected by conditional compilation.

**Comment by ProgramMax** [comment]
I haven't been able to try it yet. I will be returning to the office next week. Sorry for the delay.
I'll try it as soon as I can and let you know.

**Comment by mark-lunarg** [comment]
@ProgramMax, no problem at all, thanks!

**Comment by mark-lunarg** [comment]
@ProgramMax, Ping!

**Comment by ProgramMax** [comment]
Sorry I didn't respond earlier.
I still haven't been able to get to this task. It is now on my short list.
I know I previously said "soon" but seriously this time, soon. :D

**Comment by ProgramMax** [comment]
I have begun looking into this again. I tried getting the latest Vulkan-validation-layers and testing locally. Everything seemed fine.

I am trying to get this landed in Chrome before I completely give the OK. But I've run into a bit of red tape. The copy of the library we were using was moved into a dependency of ANGLE where we don't have easy access to it from Chrome.

I'll keep pushing on this. But I wanted to give an update. It seems so far that everything is fixed. Final OK coming soon. :)

**Comment by mark-lunarg** [comment]
Thanks a bunch for the update @ProgramMax.  We'll hop on this right away if you run into anything...

**Comment by mark-lunarg** [comment]
@ProgramMax, any chance we can close this one?

**Comment by mark-lunarg** [comment]
Closing this issue -- please reopen of there are are any additional questions or if action needs to be taken in the repository.  Thanks!
