### ISSUE TITLE
CTS crashing due to #2540

### ISSUE THREAD

**Issue by ncesario-lunarg** [KhronosGroup/Vulkan-ValidationLayers#2600]
CTS is crashing due to #2540.

From @Tony-LunarG: the issue can be reproduced with `dEQP-VK.binding_model.shader_access.primary_cmd_buf.uniform_buffer_dynamic.no_access.multiple_discontiguous_descriptors.offset_view_zero_dynamic_nonzero`. At https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/476f5e2a9f6525143ee9cc48f4c4c8108d00f22a/layers/core_validation.cpp#L6972 the returned `descriptor` is null.

@sfricke-samsung Let me know if there's a particular way you'd like to proceed with this. Thanks!

**Comment by sfricke-samsung** [comment]
I have CTS locally, will look into this sometime later today... hopefully, its nothing too fun to fix 😄

**Comment by Tony-LunarG** [comment]
Now dEQP-VK.binding_model.descriptorset_random.sets4.noarray.ubolimitlow.sbolimitlow.sampledimglow.outimgonly.noiub.nouab.frag.ialimitlow.1 is crashing (after getting validation errors) .  Starts crashing at #2540 and crashes despite #2601.  Crash is at 
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/a4cb494beecaddd8e84661b662ae363f76696c3e/layers/core_validation.cpp#L6974
Where descriptor comes back null.  @sfricke-samsung want to take a look?

**Comment by Tony-LunarG** [comment]
Now dEQP-VK.binding_model.descriptorset_random.sets4.noarray.ubolimitlow.sbolimitlow.sampledimglow.outimgonly.noiub.nouab.frag.ialimitlow.1 is crashing (after getting validation errors) .  Starts crashing at #2540 and crashes despite #2601.  Crash is at 
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/a4cb494beecaddd8e84661b662ae363f76696c3e/layers/core_validation.cpp#L6974
Where descriptor comes back null.  @sfricke-samsung want to take a look?

**Comment by sfricke-samsung** [comment]
@Tony-LunarG yes I can take a look later today, sorry for the hassle, the `descriptor_sets.cpp` is my favorite file in the repo

**Comment by ncesario-lunarg** [comment]
Thanks @Tony-LunarG @sfricke-samsung!
