### ISSUE TITLE
BP shouldn't warn if present mode is VK_PRESENT_MODE_FIFO_KHR

### ISSUE THREAD

**Issue by tambry** [KhronosGroup/Vulkan-ValidationLayers#2602]
**Describe the Issue**
Currently best practices warns about creating a swapchain before retrieving available present modes. I think it'd be better if it didn't if the present mode is `VK_PRESENT_MODE_FIFO_KHR` as it's guaranteed to be always supported per the spec.

**Valid Usage ID**
`UNASSIGNED-BestPractices-vkCreateSwapchainKHR-surface-not-retrieved`

**Environment:**
 - OS: Debian Unstable
 - GPU: AMD RX 5700XT
 - SDK or header version if building from repo: 1.2.170 tag
 - Options enabled (synchronization, best practices, etc.): best practices

**Comment by ncesario-lunarg** [comment]
Thanks for the issue @tambry! This sounds like a good idea to me. I think this should be pretty easy to add by checking the presentMode here https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/79f0658e9fbaf419e75607fda57785cbb7a17863/layers/best_practices_utils.cpp#L298
