### ISSUE TITLE
syncval: No hazard detection of swapchain images causing false negatives

### ISSUE THREAD

**Issue by jeremyg-lunarg** [KhronosGroup/Vulkan-ValidationLayers#2603]
** Former Title ** 
syncval: different output for color vs. depth stencil renderpass attachments

**Describe the Issue**
See https://www.reddit.com/r/vulkan/comments/lvkr35/writeafterwrite_hazard_for_a_simple_programs/

The program here https://github.com/vblanco20-1/vulkan-guide/blob/c7cb7ae7fdbcfb3153f224e8abbe584ed371cb53/chapter-3/vk_engine.cpp#L400  produces WaW errors for the depth / stencil attachment, because its subpass dependency only covers the color buffer pipeline stages and access masks (both color and depth/stencil have layout transitions):
```
	VkSubpassDependency dependency = {};
	dependency.srcSubpass = VK_SUBPASS_EXTERNAL;
	dependency.dstSubpass = 0;
	dependency.srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
	dependency.srcAccessMask = 0;
	dependency.dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
	dependency.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;

```

 If the subpass dependency is changed to:

```
const VkSubpassDependency in_dependency{
    .srcSubpass = VK_SUBPASS_EXTERNAL,
    .dstSubpass = 0,
    .srcStageMask = VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
    .dstStageMask = VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT,
    .srcAccessMask = 0,
    .dstAccessMask = VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT
};
```
There are NOT errors for the color buffer.  Should there be errors for this?  Or are the errors for depth/stencil false positives.

**Valid Usage ID**
If applicable, please include the validation messages encountered leading up to the issue

**Environment:**
 - OS:  Linux
 - GPU: Nvidia 
 - SDK or header version if building from repo: 1.2.170
 - Options enabled (synchronization, best practices, etc.):

**Additional context**

**Comment by jzulauf-lunarg** [comment]
I believe the WAW is correct.  The render pass instance is performing a `VkAttachmentDescription::stencilLoadOp` `VK_ATTACHMENT_LOAD_OP_CLEAR` defined @ [line 328](https://github.com/vblanco20-1/vulkan-guide/blob/c7cb7ae7fdbcfb3153f224e8abbe584ed371cb53/chapter-3/vk_engine.cpp#L382) after image-layout-transition, which occurs as a stage/access not covered by the `VkSubpassDependency` @ [line 400](https://github.com/vblanco20-1/vulkan-guide/blob/c7cb7ae7fdbcfb3153f224e8abbe584ed371cb53/chapter-3/vk_engine.cpp#L400)

> Load operations for attachments with a depth/stencil format execute in the `VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT` pipeline stage.

>`VK_ATTACHMENT_LOAD_OP_CLEAR` specifies that the contents within the render area will be cleared to a uniform value, which is specified when a render pass instance is begun. For attachments with a depth/stencil format, this uses the access type `VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT`.

**Comment by jeremyg-lunarg** [comment]
Should there be a similar error if the subpass dependency is changed to not cover the COLOR_ATTACHMENT_OUTPUT pipeline stage / access mask? (there isn't)

**Comment by jzulauf-lunarg** [comment]
I'm more worried about the reported missing WAW when the `VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT` / `VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT` are removed from the `VkSubpassDependency`

**Comment by jzulauf-lunarg** [comment]
This is a known gap.  Currently we aren't validating acquired swapchain images as they don't have VkDeviceMemory associated and thus aren't considered "Simple" bindings.

Looking at closing that gap, as it's causing confusion IRL.

**Comment by jzulauf-lunarg** [comment]
Branch available for test above ^^^.
