### ISSUE TITLE
VUID-VkRenderPassBeginInfo-framebuffer-03212 false positive

### ISSUE THREAD

**Issue by Ralith** [KhronosGroup/Vulkan-ValidationLayers#2607]
When beginning a render pass using an imageless framebuffer, the layers complain e.g.:

> Validation Error: [ VUID-VkRenderPassBeginInfo-framebuffer-03212 ] Object 0: handle = 0x30000000003, name = main, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0xd883b436 | vkCmdBeginRenderPass(): Image view #0 created from an image subresource with height set as 896, but image info #0 used to create the framebuffer had height set as 1008 The Vulkan spec states: If framebuffer was created with a VkFramebufferCreateInfo::flags value that included VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT, each element of the pAttachments member of a VkRenderPassAttachmentBeginInfo structure included in the pNext chain must be a VkImageView with a height equal to the height member of the corresponding element of VkFramebufferAttachmentsCreateInfo::pAttachmentImageInfos used to create framebuffer (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkRenderPassBeginInfo-framebuffer-03212) id=VUID-VkRenderPassBeginInfo-framebuffer-03212 number=-662457290 queue_labels= cmd_labels= objects=RENDER_PASS 30000000003 VUID-VkRenderPassBeginInfo-framebuffer-03212

However, the image view in question (indeed, every attachment image view in my process) has a *width* of 896, and a height of 1008. The error is reported for every single attachment, for every single render pass. Are the validation layers getting their axes swapped somewhere?

**Environment:**
 - OS: NixOS
 - GPU: Intel(R) UHD Graphics 620 (KBL GT2) (Vulkan 1.2, driver 5001004)
 - SDK or header version if building from repo: 1.2.170
 - Options enabled (synchronization, best practices, etc.): Defaults

**Comment by sfricke-samsung** [comment]
This was caught 2 weeks ago, idk if it missed getting into the 1.2.170 SDK or not 
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2571

**Comment by jeremyg-lunarg** [comment]
This change is in the  sdk-1.2.170 branch

https://github.com/KhronosGroup/Vulkan-ValidationLayers/commits/sdk-1.2.170
 commit 9ce7c8e67684d4a9448d8d909931cd443c361eb7

**Comment by ncesario-lunarg** [comment]
I'll see if I can reproduce this locally. @Ralith, can you please confirm where you got the SDK? e.g., was it from https://www.lunarg.com/vulkan-sdk/, your repo's package manager, etc.?

**Comment by Ralith** [comment]
Thanks! I built it myself from the v1.2.170 tag, which doesn't seem to have the fix, so that explains the issue. It's confusing that the tag and the published version differ.

**Comment by jeremyg-lunarg** [comment]
The v1.2.170 refers to where we picked up the corresponding version of Vulkan-Headers, the sdk-1.2.170.0 is what was used to build the SDK.

**Comment by Ralith** [comment]
That's confusing. sdk-1.2.170.0 works, anyway.
