### ISSUE TITLE
timeline_semaphore ValidationStateTracker::PostCallRecordQueueSubmit error

### ISSUE THREAD

**Issue by mklefrancois** [KhronosGroup/Vulkan-ValidationLayers#2616]
The test in `ValidationStateTracker::PostCallRecordQueueSubmit` is incorrect, as it can access the array of signal or wait semaphore without checking its size. I hit the issue while I have a binary semaphore for wait and timeline semaphore in signal. 

The second issue, it is accessing the timeline semaphore info index, from the global semaphore index. Meaning that if you have a mix of semaphores binary/timeline, the index will be incorrect.

This seems new from 
 - SDK 1.2.170.0

Here is a suggested fix for `ValidationStateTracker::PostCallRecordQueueSubmit()`
See modification in the two for-loop.

```
void ValidationStateTracker::PostCallRecordQueueSubmit(VkQueue queue, uint32_t submitCount, const VkSubmitInfo *pSubmits,
                                                       VkFence fence, VkResult result) {
    if (result != VK_SUCCESS) return;
    auto queue_state = GetQueueState(queue);

    uint64_t early_retire_seq = RecordSubmitFence(queue_state, fence, submitCount);

    // Now process each individual submit
    for (uint32_t submit_idx = 0; submit_idx < submitCount; submit_idx++) {
        CB_SUBMISSION submission;
        const VkSubmitInfo *submit = &pSubmits[submit_idx];
        const uint64_t next_seq = queue_state->seq + queue_state->submissions.size() + 1;
        auto *timeline_semaphore_submit = LvlFindInChain<VkTimelineSemaphoreSubmitInfo>(submit->pNext);
        for (uint32_t i = 0; i < submit->waitSemaphoreCount; ++i) {
            uint64_t w_idx = 0;
            uint64_t value = timeline_semaphore_submit && timeline_semaphore_submit->waitSemaphoreValueCount > w_idx
                                 ? timeline_semaphore_submit->pWaitSemaphoreValues[w_idx]
                                 : 0;
            if (GetSemaphoreState(submit->pWaitSemaphores[i])->type == VK_SEMAPHORE_TYPE_TIMELINE) w_idx++;
            RecordSubmitWaitSemaphore(submission, queue, submit->pWaitSemaphores[i], value, next_seq);
        }

        bool retire_early = false;
        for (uint32_t i = 0; i < submit->signalSemaphoreCount; ++i) {
            uint64_t s_idx = 0;
            uint64_t value = timeline_semaphore_submit && timeline_semaphore_submit->signalSemaphoreValueCount > s_idx
                                 ? timeline_semaphore_submit->pSignalSemaphoreValues[s_idx]
                                 : 0;
            if (GetSemaphoreState(submit->pWaitSemaphores[i])->type == VK_SEMAPHORE_TYPE_TIMELINE) s_idx++;
            retire_early |= RecordSubmitSignalSemaphore(submission, queue, submit->pSignalSemaphores[i], value, next_seq);
        }
        if (retire_early) {
            early_retire_seq = std::max(early_retire_seq, next_seq);
        }

        const auto perf_submit = LvlFindInChain<VkPerformanceQuerySubmitInfoKHR>(submit->pNext);
        submission.perf_submit_pass = perf_submit ? perf_submit->counterPassIndex : 0;

        for (uint32_t i = 0; i < submit->commandBufferCount; i++) {
            RecordSubmitCommandBuffer(submission, submit->pCommandBuffers[i]);
        }
        submission.fence = submit_idx == (submitCount - 1) ? fence : VK_NULL_HANDLE;
        queue_state->submissions.emplace_back(std::move(submission));
    }

    if (early_retire_seq) {
        RetireWorkOnQueue(queue_state, early_retire_seq);
    }
}
```

**Comment by jeremyg-lunarg** [comment]
Thank you for reporting this and including a proposed fix!  Unfortunately I do not think this fix is required. Please see  the paragraph describing VkTimelineSemaphoreSubmitInfo (right above this [VUID tag](https://vulkan.lunarg.com/doc/view/1.2.170.0/windows/chunked_spec/chap7.html#VUID-VkTimelineSemaphoreSubmitInfo-sType-sType)):

> If the semaphore in VkSubmitInfo::pWaitSemaphores or VkSubmitInfo::pSignalSemaphores corresponding to an entry in pWaitSemaphoreValues or pSignalSemaphoreValues respectively was not created with a VkSemaphoreType of VK_SEMAPHORE_TYPE_TIMELINE, the implementation must ignore the value in the pWaitSemaphoreValues or pSignalSemaphoreValues entry.

Also, while this part of the code did change a great deal in sdk-1.2.170, it looks to me like the indexing of the semaphores arrays is the same as the [older code](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/sdk-1.2.162/layers/state_tracker.cpp#L2241).

In both the old and new code pWaitSemaphores and pWaitSemaphoreValues are indexed by i. Here's the relevant section of the old code, the signal loop is roughly the same.

```
        for (uint32_t i = 0; i < submit->waitSemaphoreCount; ++i) {
            VkSemaphore semaphore = submit->pWaitSemaphores[i];   // NOTE: indexed by i
            auto pSemaphore = GetSemaphoreState(semaphore);
            if (pSemaphore) {
                if (pSemaphore->scope == kSyncScopeInternal) {
                    SEMAPHORE_WAIT wait;
                    wait.semaphore = semaphore;
                    wait.type = pSemaphore->type;
                    if (pSemaphore->type == VK_SEMAPHORE_TYPE_BINARY_KHR) {
                       ...
                    } else if (pSemaphore->payload < timeline_semaphore_submit->pWaitSemaphoreValues[i]) {
                        wait.queue = queue;
                        wait.seq = next_seq;
                        **wait.payload = timeline_semaphore_submit->pWaitSemaphoreValues[i]; //NOTE: indexed by i
                        semaphore_waits.push_back(wait);
                        pSemaphore->in_use.fetch_add(1);
                    }
                } else {
                     ...
                }
            }
       }
```

Please let me know if I'm misunderstanding something about this problem, and I can take another look.

**Comment by mklefrancois** [comment]
Thanks @jeremy-lunarg for looking into the issue. I see the issue with the change, and I will try to give more explanations.

Lets assume a `vkQueueSubmit` with the following semaphores:
* A wait binary semaphore to wait for the frame
* A signal timeline semaphore to signal something external.

The `VkSubmitInfo` will be initialize with the following information
```
  submitInfo.waitSemaphoreCount   = 1;
  submitInfo.pWaitSemaphores      = &waitFrameSemaphore;
  submitInfo.signalSemaphoreCount = 1;
  submitInfo.pSignalSemaphores    = &signalTimelineSemaphore;
```

Since there is a timeline semaphore, we also need to provide the `VkTimelineSemaphoreSubmitInfo` to the pNext chain of `VkSubmitInfo`.

The structure will be filled like this. Note that there are no wait timeline semaphore and we are setting `pWaitSemaphoreValues` to NULL.
```
  VkTimelineSemaphoreSubmitInfo tl{};
  tl.sType                     = VK_STRUCTURE_TYPE_TIMELINE_SEMAPHORE_SUBMIT_INFO;
  tl.pNext                     = nullptr;
  tl.signalSemaphoreValueCount = 1;
  tl.pSignalSemaphoreValues    = &fenceValue;
  tl.waitSemaphoreValueCount   = 0;
  tl.pWaitSemaphoreValues      = nullptr;
```

**Issue 1**

The problem with the current code, it loops over the wait semaphores and access pWaitSemaphoreValues even if it is NULL.
In the case described above, timeline_semaphore_submit will not be NULL since it has information for the signal semaphore, but the TL wait count is 0 and pWaitSemaphoreValues is NULL.  This will crash if the submit info contains the information as previously showed.

```
        auto *timeline_semaphore_submit = LvlFindInChain<VkTimelineSemaphoreSubmitInfo>(submit->pNext);
        for (uint32_t i = 0; i < submit->waitSemaphoreCount; ++i) {
               uint64_t value = timeline_semaphore_submit ? timeline_semaphore_submit->pWaitSemaphoreValues[i]
                                 : 0;
            RecordSubmitWaitSemaphore(submission, queue, submit->pWaitSemaphores[i], value, next_seq);
        }
```

**Issue 2** 

If we have 2 wait semaphores, one binary wait for the frame and one timeline, in that order.

```
  submitInfo.waitSemaphoreCount   = 2;
  submitInfo.pWaitSemaphores      = &waitFrameSemaphores[0]; // 0:frame, 1:TL
...
...
  tl.waitSemaphoreValueCount   = 1;
  tl.pWaitSemaphoreValues      = &waitValue;
```

If we are looking again at the for-loop in `ValidationStateTracker::PostCallRecordQueueSubmit`, 
waitSemaphoreCount will be equal to 2. With i==0 it will pass but not using the right semaphore, but but i==1, `pWaitSemaphoreValues` will be out of bounds.

```
        auto *timeline_semaphore_submit = LvlFindInChain<VkTimelineSemaphoreSubmitInfo>(submit->pNext);
        for (uint32_t i = 0; i < submit->waitSemaphoreCount; ++i) {
               uint64_t value = timeline_semaphore_submit ? timeline_semaphore_submit->pWaitSemaphoreValues[i]
                                 : 0;
            RecordSubmitWaitSemaphore(submission, queue, submit->pWaitSemaphores[i], value, next_seq);
        }
```

I hope I was able to expose the issues correctly and I don't think there is anything in the specification that forbids to mix binary and timeline semaphores.

I'm not sure how it should work if we have a longer mix of binary and timeline semaphores (0:frame, 1:TL, 2:frame, 3:TL, ...), but my fix recommendation is trying to address both issues and to some extend, this uncommon case.

Best
-mkl

**Comment by jeremyg-lunarg** [comment]
Thank you for the clarification @mklefrancois , those definitely are regressions from my change. I will get a fix ready for them. 

I agree that there's nothing that forbids mixing timeline and binary semaphores in the specification, the section I quoted about "must ignore the value in the pWaitSemaphoreValues or pSignalSemaphoreValues" is trying to address how this case should work.  But it isn't very clear.  I think what it is trying to say is that the pXSemaphoreValues array must be long enough to hold a value for the last timeline semaphore in the pXSemaphores array. 

If we had a sequence of semaphores like the one you describe:
0: binary, 1: TL, 2: binary, 3: TL, 4, 5, 6, 7, etc.. all binary 
Then the "pXSemaphoreValues" array would need a length of at least 4. BUT, the implementation (and validation) should only look at entries 1 and 3 in that array, since those are the only timeline semaphores. BTW, this is a good reason to check out the VK_KHR_synchronization2 extension. :)  Since there's only 1  array each for the wait and signal semaphores, these confusing array mismatches are no longer relevant.

**Comment by jeremyg-lunarg** [comment]
After further reviewing the code, my comment above is not quite correct.  There are 2 VUIDs that are relevant here:

> VUID-VkSubmitInfo-pNext-03240
> If the pNext chain of this structure includes a VkTimelineSemaphoreSubmitInfo structure and any element of pWaitSemaphores was created with a VkSemaphoreType of VK_SEMAPHORE_TYPE_TIMELINE, then its waitSemaphoreValueCount member must equal waitSemaphoreCount
> 
> VUID-VkSubmitInfo-pNext-03241
> If the pNext chain of this structure includes a VkTimelineSemaphoreSubmitInfo structure and any element of pSignalSemaphores was created with a VkSemaphoreType of VK_SEMAPHORE_TYPE_TIMELINE, then its signalSemaphoreValueCount member must equal signalSemaphoreCount

To restate the example correctly:
If we had a sequence of semaphores like the one you describe:
0: binary, 1: TL, 2: binary, 3: TL, 4, 5, 6, 7 all binary
Then the "pXSemaphoreValues" array would need a length of exactly 8. BUT, the implementation (and validation) should only look at entries 1 and 3 in that array, since those are the only timeline semaphores. 

But validation shouldn't crash and that definitely needs to be fixed.

**Comment by jeremyg-lunarg** [comment]
Note: PR 2621 isn't relevant to this issue, but I mistakenly referenced it when creating that pull request.

**Comment by mklefrancois** [comment]
Thanks @jeremy-lunarg for looking into this issue.. 

Note, I saw in the change, the following test:
```
i < timeline_semaphore_submit->pWaitSemaphoreValues[i]
```

Shouldn't be instead like this, just to be sure?
```
i < timeline_semaphore_submit->waitSemaphoreValueCount
```

I will definitively look into [VK_KHR_synchronization2](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_synchronization2.html), seems less confusing. ;-)

**Comment by jeremyg-lunarg** [comment]
> Thanks @jeremy-lunarg for looking into this issue..
> 
> Note, I saw in the change, the following test:
> 
> ```
> i < timeline_semaphore_submit->pWaitSemaphoreValues[i]
> ```
> 
> Shouldn't be instead like this, just to be sure?
> 
> ```
> i < timeline_semaphore_submit->waitSemaphoreValueCount
> ```

Yes! Thank you for catching this.
