### ISSUE TITLE
ExtensionNotEnabled test is broken

### ISSUE THREAD

**Issue by Whenning42** [KhronosGroup/Vulkan-ValidationLayers#262]
A bug in this test was exposed by the change made GetProcAddr return nullptr for API functions without their parent extensions enabled. The test is now guaranteed to skip on any config. Is there anyway to still hit the test's expected error or is that validation message now dead code?

**Comment by jzulauf-lunarg** [comment]
The code can be reached if the object_tracker layer isn't enabled, but as we don't CI in that environment, there's not point in retaining the test AFAICT.

Comments, @mark-lunarg @Whenning42

**Comment by mark-lunarg** [comment]
This check is in parameter validation.  The test can be modified to select an API that requires multiple extensions, choosing an API for an extension that IS enabled but for which an additional extension is also required.  For example, vkCreateSharedSwapchainsKHR is part of the Display_Swapchain extension, which can be enabled (and you'd get a non-null pointer back when calling GDPA), but it also requires KHR_DISPLAY and KHR_SWAPCHAIN, either of which you might NOT enable and then get this error, validating the check.
