### ISSUE TITLE
Confusion about ALL_COMMANDS_BIT and VUID-00838: spec wording vs validation

### ISSUE THREAD

**Issue by s9w** [KhronosGroup/Vulkan-ValidationLayers#2624]
When speccing stage masks for a `VkSubpassDependency`, there are two very special values: `VK_PIPELINE_STAGE_ALL_COMMANDS_BIT` and `VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT`. What those mean is a bit unclear to me. The graphics_bit is described as a "logical OR" of an impressive list. If I would actually bool-OR them together, things go wrong. For example because that list contains a `GEOMETRY_SHADER_BIT` which might not be activated. But since it's also described in the text as `all graphics pipeline stages`, a benevolent interpretation will cut that down to a valid set and all is good.

But: It's another story for the `ALL_COMMANDS_BIT` - I think. It "specifies all operations performed by all commands supported on the queue". I think that mostly refers to table 3. That is quite a lot and again includes things that are illegal for a graphics pipeline because my graphics queue supports stages my graphics pipeline does not. This is - among others - safeguarded by VUID-00838. Interestingly, the sync validation actually complains about that if you use the `ALL_COMMANDS_BIT`. Even more interestingly, the actual implicit dependency as listed in the spec violates that if you actually copy-paste it.

So: What's going in here? Is the spec wrong/unprecise about `ALL_COMMANDS_BIT`? Am I interpreting it wrong? Is it correct that the sync validation complains about its use - even with the **textbook example** of a dependency?

**Comment by jeremyg-lunarg** [comment]
@s9w You are correct that ALL_COMMANDS_BIT does refer to all pipeline stages supported by a queue, as specified in Table 3, excluding pipeline stages related to features that were not enabled when creating the VkDevice associated with the queue.

With the information you've given, I'm unable to tell you what is going wrong.

What version of the validation code are you running? Much of this code has changed recently due to the introduction of VK_KHR_synchronization2.

What settings are you using with the Validation layer? You mention  VUID-00838, which is not part of[ synchronization validation](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/docs/synchronization.md).  For the most part, synchronization  validation produces errors that begin with "SYNC_".

If you can supply the exact error messages you're getting that would help too. Even better would be an api dump or some example code. In many cases, interactions with prior commands can be the source of errors like this.

Thanks!
Jeremy

**Comment by s9w** [comment]
I'm on SDK version 1.2.162.1. And okay not sure if this is what you call sync validation - sorry if I sent anyone on a wrong path there. The VUID is [straight from the Vulkan spec](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkRenderPassCreateInfo-pDependencies-00838).

The exact error message is
```
[ERROR: Validation]
Validation Error: [ VUID-VkRenderPassCreateInfo-pDependencies-00838 ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0xb2225bf1 | vkCreateRenderPass: Dependency pDependencies[0] specifies a dstStageMask that contains stages (VK_PIPELINE_STAGE_ALL_COMMANDS_BIT) that are not part of the Graphics pipeline, as specified by the dstSubpass (= 0) in pipelineBindPoint. The Vulkan spec states: For any element of pDependencies, if the dstSubpass is not VK_SUBPASS_EXTERNAL, all stage flags included in the dstStageMask member of that dependency must be a pipeline stage supported by the pipeline identified by the pipelineBindPoint member of the destination subpass (https://vulkan.lunarg.com/doc/view/1.2.162.1/windows/1.2-extensions/vkspec.html#VUID-VkRenderPassCreateInfo-pDependencies-00838)
```

The subpass dependency that triggers it is as following. Note that this is an exact copy-paste from the spec, minus that I replaced the VK_PIPELINE_STAGE_NONE_KHR  with VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT.

```c++
   constexpr VkSubpassDependency in_dependency = {
    .srcSubpass = VK_SUBPASS_EXTERNAL,
    .dstSubpass = 0,
    .srcStageMask = VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, // without sync2, so I replaced VK_PIPELINE_STAGE_NONE_KHR with top of pipe
    .dstStageMask = VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,
    .srcAccessMask = 0,
    .dstAccessMask = VK_ACCESS_INPUT_ATTACHMENT_READ_BIT |
                     VK_ACCESS_COLOR_ATTACHMENT_READ_BIT |
                     VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT |
                     VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT |
                     VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT,
    .dependencyFlags = 0
   };
```

My program is pretty simple and runs perfectly and without any warnings with a correct dependency. The only reason I tried this in the first place was a discord discussion about what ALL_COMMANDS_BIT actually means - and was surprised that the validation also seems (?) to interpret that in a very all-encompassing manner and marks it as a mistake.

**Comment by jeremyg-lunarg** [comment]
Thank you for the clarification. After looking into VUID 00838 further, I agree that *something* is wrong here. Given that these dependencies have been in the spec since 1.0 it seems to me that validation should change. Several open source drivers, such as the [radv driver](https://gitlab.freedesktop.org/mesa/mesa/-/blob/master/src/amd/vulkan/radv_pass.c#L89), use these exact dependencies in their implementation, as does [synchronization validation](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/state_tracker.cpp#L4589).  We didn't have any unit tests that used these dependencies, so I added them.

**Comment by s9w** [comment]
So okay this is a validation bug then. But I'm still somewhat confused. Let's say I have a perfectly valid dependency and randomly add `VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT` to either or both stageMasks. I don't know what fragment density is, at least I'm pretty sure I don't use it. So it shouldn't go through validation since it's not part of the pipeline, right? There's VUID-00838/00837. In this particular case, there's also

```
VUID-vkCmdSetEvent-stageMask-04093
If the fragment density map feature is not enabled, stageMask must not contain VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT
```

But my validation doesn't seem to care.

I tried with all available flags and the following *do* trigger an error when used, as expected:
- VK_PIPELINE_STAGE_TASK_SHADER_BIT_NV
- VK_PIPELINE_STAGE_MESH_SHADER_BIT_NV
- VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT
- VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT
- VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT

Yet the following flags did not, but should, at least I think. They're either not part of the graphics pipeline, weren't enabled by me and some of them are explicitly guarded by a VUID
- VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT
- VK_PIPELINE_STAGE_TRANSFER_BIT
- VK_PIPELINE_STAGE_HOST_BIT
- VK_PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT // VUID-vkCmdSetEvent-stageMask-04092
- VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT // VUID-vkCmdSetEvent-stageMask-04093
- VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR
- VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR
- VK_PIPELINE_STAGE_SHADING_RATE_IMAGE_BIT_NV // VUID-vkCmdSetEvent-stageMask-04097
- VK_PIPELINE_STAGE_COMMAND_PREPROCESS_BIT_NV

I'm really not sure which part is me misunderstanding the spec and which could be validation issues.

**Comment by mark-lunarg** [comment]
There may be some additional context in this existing [Vulkan spec issue](https://github.com/KhronosGroup/Vulkan-Docs/issues/1020).

**Comment by jeremyg-lunarg** [comment]
Thanks Mark. I should have thought to check for history on this. Based on reading the spec issue, it looks like my patch is not supported by the replies from @Tobski , although I'm not 100% certain about that :confused: 

@s9w, some of the stages you listed are not checked by validation until 1.2.170 and some of them still aren't checked. The current code for managing feature to pipeline stage inclusion is [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/sync_utils.cpp#L30). The 1.2.162 code is [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/sdk-1.2.162/layers/core_validation.cpp#L2561). Though that doesn't explain the HOST, TRANSFER, or COMPUTE stages. I'll have to dig into this further. I apologize for the continued confusion.

**Comment by spencer-lunarg** [comment]
sorry this has not been replied to in a long time.

Between the spec updates and code change this should be able to be closed now. @s9w if you are still hitting this issue please feel free to reopen the issue
