### ISSUE TITLE
Can the robin hood dependency be optional?

### ISSUE THREAD

**Issue by ben-clayton** [KhronosGroup/Vulkan-ValidationLayers#2639]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/3e54036acdd1e56217aeb714eda9ab7db0d14287 introduced a new third_party dependency on github.com/martinus/robin-hood-hashing.
The Vulkan Validation Layers are in use within Chromium and the internal Google codebase. In both cases, we currently would prefer not to add `robin_hood` as a new transitive dependency.

Assuming 3e54036 is the only place that uses `robin_hood`, [it appears fairly simple](https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/3e54036acdd1e56217aeb714eda9ab7db0d14287#diff-2b95ba5f9301e60bd8a46f548002117402176bff98adc954aa89bbd4b8e47739) to conditionally switch between this custom library and the regular STL.

Would it be possible for VVL to make this dependency optional, say via a `-DUSE_ROBIN_HOOD_HASH=1`?
If so, we'd probably like to revert the changes to `BUILD.gn`, as this is currently blocking rolls of the VVL into Chromium.

Many thanks,
Ben

**Comment by ncesario-lunarg** [comment]
@ben-clayton I agree it shouldn't be too difficult to make this optional. However, this change gives us a significant performance boost. Is this a build issue we could fix (e.g., would checking the header directly into the repo help), or is there a different reason you would rather not use the robin-hood-hashing library?

FYI @jeremyg-lunarg.

**Comment by ben-clayton** [comment]
> However, this change gives us a significant performance boost.

Both internal-google and Chromium have their own fast-container implementations (the latter being [Abseil](https://github.com/abseil/abseil-cpp)), which we would prefer to use than adding another dependency that offers very similar functionality. Every additional dependency requires an initial security review, integration work, and then continual integration maintenance. For something that's pure-optimization like this, and something we already have alternatives for, we'd strongly like to avoid it if possible.

> Is this a build issue we could fix (e.g., would checking the header directly into the repo help)

I'm afraid embedding dependencies like this is only further complicating the licensing side of things.

> is there a different reason you would rather not use the robin-hood-hashing library

Just the reasons listed above. I'm sure the library is great :)

Many thanks,
Ben

**Comment by ncesario-lunarg** [comment]
Thanks for the clarification @ben-clayton! I'm trying out a change now that will remove this from the GN build. Is there any other build (e.g., cmake, Android) that would also be affected, or just the GN build?

**Comment by ben-clayton** [comment]
I've asked the Android team, and am waiting on a response. I strongly anticipate they'd respond with wanting this removed for the Android build files too.

Thank you.

**Comment by ncesario-lunarg** [comment]
@ben-clayton, please re-open this if you're still having issues with the GN build after #2640.

**Comment by ben-clayton** [comment]
Thank you ever so much for the extremely rapid fix!
