### ISSUE TITLE
vkCmdBindVertexBuffers2EXT validation doesn't work with null descriptors

### ISSUE THREAD

**Issue by Joshua-Ashton** [KhronosGroup/Vulkan-ValidationLayers#2642]
**Describe the Issue**

When using vkCmdBindVertexBuffers2EXT with null descriptors I get garbage validation spam.

**Valid Usage ID**

VUID-vkCmdBindVertexBuffers2EXT-pBuffers-parameter(ERROR / SPEC): msgNum: 1747617674 - Validation Error: [ VUID-vkCmdBindVertexBuffers2EXT-pBuffers-parameter ] Object 0: handle = 0x7f041d10, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x682a878a | Invalid VkBuffer Object 0x0. The Vulkan spec states: pBuffers must be a valid pointer to an array of bindingCount valid VkBuffer handles (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdBindVertexBuffers2EXT-pBuffers-parameter)
    Objects: 1
        [0] 0x7f041d10, type: 1, name: NULL
UNASSIGNED-GeneralParameterError-RequiredParameter(ERROR / SPEC): msgNum: -1711571459 - Validation Error: [ UNASSIGNED-GeneralParameterError-RequiredParameter ] Object 0: handle = 0x7f22f330, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x99fb7dfd | vkCmdBindVertexBuffers2EXT: required parameter pBuffers[1] specified as VK_NULL_HANDLE
    Objects: 1
        [0] 0x7f22f330, type: 3, name: NULL

**Environment:**
 - OS: Arch Linux
 - GPU: AMD Radeon VII
 - SDK or header version if building from repo: vulkan-validation-layers 1.2.172-1 
 - Options enabled (synchronization, best practices, etc.): None

**Additional context**

**Comment by Joshua-Ashton** [comment]
Ah, this is a dupe of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2541

**Comment by ncesario-lunarg** [comment]
Thanks @Joshua-Ashton, we'll try to move #2541 up in the priority queue.
