### ISSUE TITLE
VUID-vkCmdPipelineBarrier-dstAccessMask-02816: Pipeline barrier with dstStage=VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR and dstAccessMask = VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR

### ISSUE THREAD

**Issue by httpdigest** [KhronosGroup/Vulkan-ValidationLayers#2645]
**Describe the Issue**
I am getting a validation error for the following pipeline barrier (syntax is Java, but it should be clear what's being done here):
```java
// Insert barrier to let tracing wait for the TLAS build
vkCmdPipelineBarrier(cmdBuf,
        VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR,
        VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR,
        0, // <- no dependency flags
        VkMemoryBarrier.callocStack(1, stack)
            .sType(VK_STRUCTURE_TYPE_MEMORY_BARRIER)
            .srcAccessMask(VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR |
                           VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR)
            .dstAccessMask(VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR),
        null,
        null);
```
So, I want a pipeline barrier that syncs the build of a TLAS with the trace command in a ray tracing pipeline.
Apart from me not having seen anything that _mandates_ this barrier (neither the Nvidia Vulkan Ray Tracing Samples do such a barrier (they simply do a queueWaitIdle nor Sascha Willems examples), apart from the mandate of synchronizing access to the SBT in the paragraph:
> Accesses to the shader binding table from ray tracing pipelines must be synchronized with the VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR pipeline stage and an access type of VK_ACCESS_SHADER_READ_BIT.

That barrier shouldn't however throw a `VUID-vkCmdPipelineBarrier-dstAccessMask-02816` validation warning, because in the table of valid pipeline stages and access masks, the combination `VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR` and `VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR` _is_ allowed, as mentioned in the table on https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkAccessFlagBits.html .

So, my actual questions are probably two-fold:
- is a memory barrier needed between the build of a TLAS and the tracing?
- is the mentioned reported validation error correct?

**Valid Usage ID**
`Validation Error: [ VUID-vkCmdPipelineBarrier-dstAccessMask-02816 ] Object 0: handle = 0x22b2e126c08, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x69c8467d | vkCmdPipelineBarrier(): pMemoryBarriers[0].dstAccessMask bit VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR is not supported by stage mask (VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR). The Vulkan spec states: The dstAccessMask member of each element of pMemoryBarriers must only include access flags that are supported by one or more of the pipeline stages in dstStageMask, as specified in the table of supported access types (https://vulkan.lunarg.com/doc/view/1.2.170.0/windows/1.2-extensions/vkspec.html#VUID-vkCmdPipelineBarrier-dstAccessMask-02816)`

**Environment:**
 - OS: Windows 10 x64 20H2
 - GPU: Nvidia GeForce RTX 2080 Ti (driver version 461.92, 466.27)
 - SDK or header version if building from repo: 1.2.170.0 and 1.2.176.1
 - Options enabled (synchronization, best practices, etc.): none (left installation default)

**Comment by jeremyg-lunarg** [comment]
This validation error does not look correct to me. I'll fix it.

I haven't been able to find an exact example of a barrier for shader binding table.

https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdBuildAccelerationStructuresKHR.html describes barriers needed to access other data.  And  [CTS](https://github.com/KhronosGroup/VK-GL-CTS/tree/master/external/vulkancts/modules/vulkan/ray_tracing) has several examples of these barriers.

**Comment by jeremyg-lunarg** [comment]
This validation error does not look correct to me. I'll fix it.

I haven't been able to find an exact example of a barrier for shader binding table.

https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdBuildAccelerationStructuresKHR.html describes barriers needed to access other data.  And  [CTS](https://github.com/KhronosGroup/VK-GL-CTS/tree/master/external/vulkancts/modules/vulkan/ray_tracing) has several examples of these barriers.

**Comment by httpdigest** [comment]
@jeremy-lunarg thanks for pointing me to the CTS repo. I'll have a look.

So, to confirm: Given that https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdBuildAccelerationStructuresKHR.html says

> Accesses to the acceleration structure scratch buffers as identified by the VkAccelerationStructureBuildGeometryInfoKHR→scratchData buffer device addresses must be synchronized with the VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR pipeline stage and an access type of VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR or VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR. **Similarly for accesses to each VkAccelerationStructureBuildGeometryInfoKHR→srcAccelerationStructure and VkAccelerationStructureBuildGeometryInfoKHR→dstAccelerationStructure.**

i take it that the source of the pipeline barrier must be VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR/VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR. However, I am still not clear what the destination of the barrier should be (for the actual tracing/read access to the acceleration structure), since https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdTraceRaysKHR.html also makes no statement about it. I _assumed_ that it would be VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR / VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR but I cannot find a normative statement about that being so.

**Comment by jeremyg-lunarg** [comment]
@httpdigest I agree about the source bits for the barrier. And that the destination seems right to me, but you do have to infer by piecing together multiple parts of the spec. We may need this part of your issue to become a https://github.com/KhronosGroup/Vulkan-Docs issue to get the attention of spec authors.

**Comment by httpdigest** [comment]
Thank you!
Okay, then I guess this issue here only is about the issued validation error `VUID-vkCmdPipelineBarrier-dstAccessMask-02816` and should only track its fixing in the validation layer.

**Comment by johannesugb** [comment]
Just ran into the same issue. The validation layer's message
```
.pMemoryBarriers[0].dstAccessMask bit VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR is not supported by stage mask (VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR)
```
must be a false positive, because it clearly contradicts the information in [Table 4](https://vulkan.lunarg.com/doc/view/1.2.176.1/windows/1.2-extensions/vkspec.html#synchronization-access-types-supported) from the specification.

SDK: 1.2.176.1 (Windows 10)
