### ISSUE TITLE
license on docs/images/sync_diagram_source.txt

### ISSUE THREAD

**Issue by airlied** [KhronosGroup/Vulkan-ValidationLayers#2652]
We have a license scanner that scans for open source compatible licenses in the source code of packages we distribute via Fedora/RHEL. Since we ship the source rpms which contain these tarballs we have to try and keep them open source only.

Our recent scan flagged this file as having a CC-BY-ND-4.0 which isn't open-source.

This leaves us with the task of having to add a pre-step to out tarball packaging to remove the file and retar it.

Can we get this file removed or relicensed under Apache 2.0 or MIT?

**Comment by ncesario-lunarg** [comment]
@jzulauf-lunarg not sure what exactly needs to change here. Can you please take a look?

**Comment by karolherbst** [comment]
If the author still wants to use the CC license then the "ND" part has to go away.

**Comment by jzulauf-lunarg** [comment]
@airlied  -- everything *else* in docs appears to have CC-BY-ND-4.0 -- why does this file need to be different?\

**Comment by airlied** [comment]
Where is the CC-BY-ND-4.0 for the rest of the docs?

The license file says "
The majority of files in this project use the Apache 2.0 License.
There are a few exceptions and their license can be found in the source.
Any license deviations from Apache 2.0 are "more permissive" licenses."

I can find no mention that other docs are covered by anything by Apache 2.0.

Also CC-BY-ND-4.0 isn't more permissive than Apache 2.0

If the docs are not under a permissive license then that should be fixed for all the documents, please relicense them.

**Comment by jzulauf-lunarg** [comment]
All of:
```
best_practices.md
core_checks.md
debug_printf.md
gpu_validation.md
handle_wrapping.md
images/sync_diagram_source.txt
khronos_validation_layer.md
object_lifetimes.md
stateless_validation.md
synchronization.md
synchronization_usage.md
thread_safety.md
```
Cite `'https://creativecommons.org/licenses/by-nd/4.0/` and use the `https://i.creativecommons.org/l/by-nd/4.0/88x31.png` badge to denote license.

@ncesario-lunarg -- given this is a docs global issue I'm going to push it back to you.

**Comment by airlied** [comment]
I've updated the title. The document needs to be licensed under an open source license, I believe Lunarg/Khronos probably hold all the copyrights here, so someone just needs to enable it. Apache 2.0 should be fine for these docs.

**Comment by ncesario-lunarg** [comment]
Sorry @airlied, I'm still confused here. As @jzulauf-lunarg pointed out, don't the other text files under docs have the same CC license? What is different about this file? If this file were converted to a markdown file and used the same CC header the other markdown files under docs use (e.g., https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/docs/best_practices.md), would that be sufficient? If not, why does this file need to have a different license?
