### ISSUE TITLE
False-positive with validation of srcStageMask on VkSubpassDependency2

### ISSUE THREAD

**Issue by KolyaNaichuk** [KhronosGroup/Vulkan-ValidationLayers#2661]
**Describe the Issue**
I am using VkSubpassDependency2 with VkMemoryBarrier2KHR extension. I specify srcStageMask, srcAccessMask, dstStageMask, dstAccessMask on VkMemoryBarrier2KHR and keep srcStageMask, srcAccessMask, dstStageMask, dstAccessMask uninitialised on VkSubpassDependency2. According to the [specification](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkSubpassDependency2.html) if we include the extension VkMemoryBarrier2KHR, stage masks and access masks should be ignored on VkSubpassDependency2. This does not seem  to be the case for the validation layer as it throws this error while calling vkCreateRenderPass2.
 
"[ VUID-VkSubpassDependency2-srcStageMask-parameter ] Object 0: handle = 0x19a3847a268, name = Renderer::m_DeviceHandle, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xe5ee6532 | vkCreateRenderPass2: value of pCreateInfo->pDependencies[0].srcStageMask contains flag bits that are not recognized members of VkPipelineStageFlagBits The Vulkan spec states: srcStageMask must be a valid combination of VkPipelineStageFlagBits values"

**Valid Usage ID**

**Environment:**
 - OS: Windows 10 Home (19042.867)
 - GPU: GTX 1070 (458.06)
 - SDK or header version if building from repo: 1.2.170.0
 - Options enabled (synchronization, best practices, etc.):

**Additional context**

**Comment by ncesario-lunarg** [comment]
Thanks for pointing this out @KolyaNaichuk, it looks like we don't currently have a way of ignoring these as this validation is currently generated (see `layers/generated/parameter_validation.cpp` around line 7051). It might take a bit of effort in the generation scripts to get this resolved.

**Comment by KolyaNaichuk** [comment]
Alright! No worries I am able to workaround the issue by initialising the masks to 0 on VkSubpassDependency2.
