### ISSUE TITLE
Segfault in StateTracker::PostCallRecordQueueSubmit

### ISSUE THREAD

**Issue by farnoy** [KhronosGroup/Vulkan-ValidationLayers#2662]
Hey @mark-lunarg & @jeremyg-lunarg

I believe a regression was introduced in timeline semaphore validations.

The code in [`PostCallRecordQueueSubmit`](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/4fdcd0eebfed3505732720fc6fd98293e847d697/layers/state_tracker.cpp#L2424) assumes that `LvlFindInChain<VkTimelineSemaphoreSubmitInfo>(submit->pNext)` being truthy implies safe dereferencing into `pWaitSemaphoreValues` and `pSignalSemaphoreValues`, but my understanding is that the standard is more lenient as long as all of the semaphores in wait/signal buckets are binary.

> VUID-VkSubmitInfo-pNext-03240
If the pNext chain of this structure includes a VkTimelineSemaphoreSubmitInfo structure **and any element of pWaitSemaphores was created with a VkSemaphoreType of VK_SEMAPHORE_TYPE_TIMELINE**, then its waitSemaphoreValueCount member must equal waitSemaphoreCount

> VUID-VkSubmitInfo-pNext-03241
If the pNext chain of this structure includes a VkTimelineSemaphoreSubmitInfo structure **and any element of pSignalSemaphores was created with a VkSemaphoreType of VK_SEMAPHORE_TYPE_TIMELINE**, then its signalSemaphoreValueCount member must equal signalSemaphoreCount

(emphasis mine)

I've reported a similar issue in the past, in #1786

**Comment by jeremyg-lunarg** [comment]
@farnoy, what version of the Vulkan-ValidationLayers repository are you using? A similar segfault was reported and fixed a couple of weeks ago (see: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2616).  Do you have that fix already?

**Comment by farnoy** [comment]
Good call, I forgot to check what the latest code there looks like. I think it got fixed indeed. I am using 1.2.170.0 from the binary distribution. Your merge commit e53e4e5f0cdcda471a425cceba778a0a154d233c appeared in the 1.2.173.0 tag first, so I don't have it yet.

I'm closing this and will re-test when the next version gets included in a binary SDK release.
