### ISSUE TITLE
syncval WRITE-AFTER-WRITE error with DS input attachment

### ISSUE THREAD

**Issue by congyue1977** [KhronosGroup/Vulkan-ValidationLayers#2663]
**Describe the Issue**
1. Begin RP with 2 sub passes with a DS attachment, and RP's final layout is DEPTH_READ_ONLY_OPTIMAL.
2. Subpass 0 write DS, and DS reference layout is DEPTH_ATTACHMENT_OPTIMAL.
3. Subpass 1 read DS as input attachment, and DS reference layout is DEPTH_READ_ONLY_OPTIMAL.
4. End RP.
5. Dispatch compute shader, read the DS and image memory barrier's old layout is DEPTH_READ_ONLY_OPTIMAL, new layout is SHADER_READ_ONLY_OPTIMAL.

**Valid Usage ID**
`Validation Error: [ SYNC-HAZARD-WRITE_AFTER_WRITE ] Object 0: handle = 0x20229f54c58, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0xfdf9f5e1 | vkCmdPipelineBarrier: Hazard WRITE_AFTER_WRITE for image barrier 0 VkImage 0x20229f54c58[]. Access info (usage: SYNC_IMAGE_LAYOUT_TRANSITION, prior_usage: SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE, write_barriers: 0, command: vkCmdEndRenderPass`

**Environment:**
 - OS: Windows 10
 - GPU: Nvidia 2070s
 - SDK or header version if building from repo: Vulkan SDK 1.2.170.0
 - Options enabled (synchronization, best practices, etc.):synchronization

**Comment by jeremyg-lunarg** [comment]
@congyue1977, it looks like you may be getting errors from the [store operation](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkAttachmentStoreOp.html) of your attachment, but it is hard to be sure without knowing the subpass dependencies of your renderpass and the parameters you're giving to ckCmdPipelineBarrier(). Usually in cases like this you are better off using a subpass dependency with dstSubpass = VK_SUBPASS_EXTERNAL instead of a separate pipeline barrier. Then you should be able to set your attachment's final layout to SHADER_READ_ONLY_OPTIMAL, and use the pipeline stages and access masks from your barrier command.

**Comment by congyue1977** [comment]
@jeremyg-lunarg Thanks for your reply！
The RP subpass dependencies setting as follows:
```
srcSubpass = 0;
dstSubpass = 1;
srcStageMask = COLOR_ATTACHMENT_OUTPUT | EARLY_FRAGMENT_TESTS | LATE_FRAGMENT_TESTS;
dstStageMask = FRAGMENT_SHADER | EARLY_FRAGMENT_TESTS;
srcAccessMask = COLOR_ATTACHMENT_WRITE | DEPTH_STENCIL_ATTACHMENT_WRITE;
dstAccessMask = INPUT_ATTACHMENT_READ | DEPTH_STENCIL_ATTACHMENT_READ;
dependencyFlags = BY_REGION_BIT;
```
The barrier is:
```
srcStageMask = LATE_FRAGMENT_TESTS;
dstStageMask = COMPUTE_SHADER;
srcAccessMask = 0;
dstAccessMask = SHADER_READ;
oldLayout = DEPTH_STENCIL_ATTACHMENT_READ;
newLayout  = SHADER_READ_ONLY_OPTIMAL;
```

And I also tried the method you said, unfortunately, I got another WAW error:
`Validation Error: [ SYNC-HAZARD-WRITE_AFTER_WRITE ] Object 0: handle = 0x184115fd3d8, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0xfdf9f5e1 | vkCmdEndRenderPass: Hazard WRITE_AFTER_WRITE with last use subpass 1 for attachment 1 final image layout transition (old_layout: VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL, new_layout: VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL). Access info (usage: SYNC_IMAGE_LAYOUT_TRANSITION, prior_usage: SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE, write_barriers: 0, command: Command_Undefined, seq_no: 4294967295, subcmd: 4294967295, reset_no: 1.`

**Comment by jeremyg-lunarg** [comment]
it looks to me like your barrier should have srcAccessMask = DEPTH_STENCIL_ATTACHMENT_WRITE

**Comment by congyue1977** [comment]
@jeremyg-lunarg Thank you very much! Problem solved.

But I still have doubts. In another case, I set the barrier's srcAccessMask = 0 but there is no WAW error.
Another case is:
- Begin the first RP with 2 sub passes with a DS attachment, and RP's final layout is DEPTH_READ_ONLY_OPTIMAL.
- subpass 0 write DS, and DS reference layout is DEPTH_ATTACHMENT_OPTIMAL.
- subpass 1 read DS as input attachment, and DS reference layout is DEPTH_READ_ONLY_OPTIMAL.
- End the first RP.
- Set one image memory barrier.
- Begin the second RP with the DS attachment, LOAD Op is Load, RP's init layout is DEPTH_READ_ONLY_OPTIMAL
- End the second RP.

The first RP subpass dependencies setting as follows:

```
srcSubpass = 0;
dstSubpass = 1;
srcStageMask = COLOR_ATTACHMENT_OUTPUT | EARLY_FRAGMENT_TESTS | LATE_FRAGMENT_TESTS;
dstStageMask = FRAGMENT_SHADER | EARLY_FRAGMENT_TESTS;
srcAccessMask = COLOR_ATTACHMENT_WRITE | DEPTH_STENCIL_ATTACHMENT_WRITE;
dstAccessMask = INPUT_ATTACHMENT_READ | DEPTH_STENCIL_ATTACHMENT_READ;
dependencyFlags = BY_REGION_BIT;
```

The barrier' setting before the second RP is:

```
srcStageMask = LATE_FRAGMENT_TESTS;
dstStageMask = EARLY_FRAGMENT_TESTS | LATE_FRAGMENT_TESTS;
srcAccessMask = 0;
dstAccessMask = DEPTH_STENCIL_ATTACHMENT_READ;
oldLayout = DEPTH_READ_ONLY_OPTIMAL;
newLayout  = DEPTH_READ_ONLY_OPTIMAL;
```

**Comment by jeremyg-lunarg** [comment]
In this case, I think your code is relying on the implicit subpass dependencies that are added to each renderpass if there is a layout transition (from the [renderpass chapter](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap8.html#renderpass-creation))

> If there is no subpass dependency from VK_SUBPASS_EXTERNAL to the first subpass that uses an attachment, then an implicit subpass dependency exists from VK_SUBPASS_EXTERNAL to the first subpass it is used in. The implicit subpass dependency only exists if there exists an automatic layout transition away from initialLayout. The subpass dependency operates as if defined with the following parameters:
> 
> VkSubpassDependency implicitDependency = {
>     .srcSubpass = VK_SUBPASS_EXTERNAL;
>     .dstSubpass = firstSubpass; // First subpass attachment is used in
>     .srcStageMask = VK_PIPELINE_STAGE_NONE_KHR;
>     .dstStageMask = VK_PIPELINE_STAGE_ALL_COMMANDS_BIT;
>     .srcAccessMask = 0;
>     .dstAccessMask = VK_ACCESS_INPUT_ATTACHMENT_READ_BIT |
>                      VK_ACCESS_COLOR_ATTACHMENT_READ_BIT |
>                      VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT |
>                      VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT |
>                      VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT;
>     .dependencyFlags = 0;
> };
> Similarly, if there is no subpass dependency from the last subpass that uses an attachment to VK_SUBPASS_EXTERNAL, then an implicit subpass dependency exists from the last subpass it is used in to VK_SUBPASS_EXTERNAL. The implicit subpass dependency only exists if there exists an automatic layout transition into finalLayout. The subpass dependency operates as if defined with the following parameters:
> 
> VkSubpassDependency implicitDependency = {
>     .srcSubpass = lastSubpass; // Last subpass attachment is used in
>     .dstSubpass = VK_SUBPASS_EXTERNAL;
>     .srcStageMask = VK_PIPELINE_STAGE_ALL_COMMANDS_BIT;
>     .dstStageMask = VK_PIPELINE_STAGE_NONE_KHR;
>     .srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT |
>                      VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT;
>     .dstAccessMask = 0;
>     .dependencyFlags = 0;
> };

It these dependencies are getting added, your barrier may be partially or completely redundant. Also, the dependency you specify between subpasses won't ensure that the layout transition is synchronized at the end of the renderpass.

In the [synchronization examples](https://github.com/KhronosGroup/Vulkan-Docs/wiki/Synchronization-Example
) wiki, the "First render-pass writes to a depth attachment. Second render-pass re-uses the same depth attachment." example seems very close to what you're doing and shows how to synchronize with an external subpass dependency.  Using this method has the advantage removing the need for barrier commands and avoiding the implicit subpass dependencies (which I find to often be confusing).

**Comment by congyue1977** [comment]
@jeremyg-lunarg I appreciate your kind reply to my question!

> It these dependencies are getting added, your barrier may be partially or completely redundant. Also, the dependency you specify between subpasses won't ensure that the layout transition is synchronized at the end of the renderpass.

It's a bit complicated. 

First, If I remove the barrier, I'll get a WAW error. This is why a barrier is added here.

Secondly, the only difference between the first case and the second case is that after the first RP in the first case, dispatch a Compute shader that reads the DS Attachment, and the other parts are exactly the same.

So I am more confused about what you said:
`Also, the dependency you specify between subpasses won't ensure that the layout transition is synchronized at the end of the renderpass.`
Is this the reason why I got the WAW error after removing the barrier?

**Comment by congyue1977** [comment]
I found this description in the Vulkan documentation:

> For attachments however, subpass dependencies work more like a VkImageMemoryBarrier defined similarly to the VkMemoryBarrier above, the queue family indices set to VK_QUEUE_FAMILY_IGNORED, and layouts as follows:
> 
> The equivalent to oldLayout is the attachment’s layout according to the subpass description for srcSubpass.
> The equivalent to newLayout is the attachment’s layout according to the subpass description for dstSubpass.

My understanding is that attachment subpass dependency is equivalent to VkImageMemoryBarrier , which guarantees synchronization.But whether this is contradictory with what you said?

> Also, the dependency you specify between subpasses won't ensure that the layout transition is synchronized at the end of the renderpass.

**Comment by jeremyg-lunarg** [comment]
subpass dependencies are mostly equivalent to a pipeline barrier before or after the renderpass, if either the src or dst subpass is VK_SUBPASS_EXTERNAL, otherwise they only synchronize between the 2 subpasses of the renderpass. Here is the relevant section of the spec:

> If srcSubpass is equal to VK_SUBPASS_EXTERNAL, the first synchronization scope includes commands that occur earlier in submission order than the vkCmdBeginRenderPass used to begin the render pass instance. Otherwise, the first set of commands includes all commands submitted as part of the subpass instance identified by srcSubpass and any load, store or multisample resolve operations on attachments used in srcSubpass. In either case, the first synchronization scope is limited to operations on the pipeline stages determined by the source stage mask specified by srcStageMask.
> 
> If dstSubpass is equal to VK_SUBPASS_EXTERNAL, the second synchronization scope includes commands that occur later in submission order than the vkCmdEndRenderPass used to end the render pass instance. Otherwise, the second set of commands includes all commands submitted as part of the subpass instance identified by dstSubpass and any load, store or multisample resolve operations on attachments used in dstSubpass. In either case, the second synchronization scope is limited to operations on the pipeline stages determined by the destination stage mask specified by dstStageMask.

Notice that the 'Otherwise' sentence of each paragraph only mentions commands that are part of the source and destination subpasses, not any commands submitted before or after the renderpass. The initial layout transition occur as part of vkCmdBeginRenderPass() and the store as part of vkCmdEndRenderPass().  This is why implicit subpass dependencies get inserted if you don't provide them. Unfortunately because they use VK_PIPELINE_STAGE_NONE_KHR as either their src or dst StageMask,  it is very hard to create a pipeline command barrier that will synchronize correctly with an implicit subpass dependency, unless you use VK_PIPELINE_STAGE_ALL_COMMANDS_BIT which waits for all stages to be idle.

**Comment by congyue1977** [comment]
Thank you very much for your patient guidance! I fully understand the cause of the problem.
Synchronization in Vulkan is very complicated and often confusing. The recently launched VK_KHR_synchronization2 has further improvements, but I hope that new improvements will be introduced in the future to make it easier for developers to understand and use. Thank you again for your reply!
