### ISSUE TITLE
validation layer tests get vulkan versioning test wrong

### ISSUE THREAD

**Issue by airlied** [KhronosGroup/Vulkan-ValidationLayers#2666]
At the moment, lavapipe driver reports as a Vulkan 1.0 driver, but with a new enough loader you can get cases where you have a 1.2 instance.

The correct way to determine supported versioning for features is to do a vkGetPhysicalDeviceProperties get the support version for the physical device and use the minimum of this and the instance version.

VkLayerTest.ValidateExtendedDynamicStateDisabled demonstrates this as it tries to use vkGetPhysicalDeviceFeatures2 on a 1.2 instance with a 1.0 physical device which isn't legal.

**Comment by sfricke-samsung** [comment]
> The correct way to determine supported versioning for features is to do a vkGetPhysicalDeviceProperties 

So I guess this depends "what" you are looking for support for, if it something like `vkGetPhysicalDeviceFeatures2` (from `VK_KHR_get_physical_device_properties2`) is an [instance extension](https://github.com/KhronosGroup/Vulkan-Guide/blob/master/chapters/enabling_extensions.md#two-types-of-extensions), therefore the instance version matters here

Also there is a `DeviceValidationVersion` tests can use if they actually want to check for the device version for Device Extensions

Also note that CI should be running with [devsim and mock icd](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/docs/creating_tests.md#running-tests-on-devsim-and-mockicd) which only runs at Vulkan Device level 1.0 (and even uses a [1.0.18 old android profile](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/tests/device_profiles/mobile_chip.json#L119)) and it doesn't have these issues

**Comment by airlied** [comment]
If you look at the MR linked I fixed tests to use the DeviceValidatuonVersion

My guess is those tests in CI are only exposing a 1.0 instance as wrl

**Comment by spencer-lunarg** [comment]
Between https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4140 and other PR, all the tests should now correctly be checking for versions
