### ISSUE TITLE
test VkLayerTest.ResolveImageFormatMismatch assumes 2 sample image will be supported

### ISSUE THREAD

**Issue by airlied** [KhronosGroup/Vulkan-ValidationLayers#2669]
This test never validates that it is legal to create a 2 sample image. This will get the wrong VU if that happens.

**Comment by sfricke-samsung** [comment]
I think a simple fix would just be using `VK_SAMPLE_COUNT_4_BIT` as `sampledImageColorSampleCounts` limit in Vulkan requires `4_BIT` to be supported for `VK_FORMAT_R8G8B8A8_UNORM`.
