### ISSUE TITLE
Duplicate pNext chain structure types reported incorrectly when using multiple VkDebugUtilsMessengerCreateInfoEXT structures

### ISSUE THREAD

**Issue by rumblehhh** [KhronosGroup/Vulkan-ValidationLayers#2671]
In https://github.com/KhronosGroup/Vulkan-Docs/issues/1329 VkDebugUtilsMessengerCreateInfoEXT structures were made exceptions to the "each struct in the pNext chain must be unique" rule from 1.2.150 spec onwards however when using multiple VkDebugUtilsMessengerCreateInfoEXT structures in the pNext chain the validation layers report a validation layer error as is shown below. It seems the validation layers do not take into account this exception made to unique pNext chain structures.

**Valid Usage ID**
Validation Error: [ VUID-VkInstanceCreateInfo-sType-unique ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x3cf04b78 | vkCreateInstance: pCreateInfo->pNext chain contains duplicate structure types: VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT appears multiple times. The Vulkan spec states: The sType value of each struct in the pNext chain must be unique, with the exception of structures of type VkDebugUtilsMessengerCreateInfoEXT (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkInstanceCreateInfo-sType-unique)

**Environment:**
 - OS: Windows
 - GPU: NVidia RTX 2060
 - SDK or header version if building from repo: Known good build using https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/4e0a32a45607dda04a121c1d4561826ef5351b45. Issue also present using VulkanSDK 1.2.170.

**Comment by ncesario-lunarg** [comment]
I was thinking this would be a quick fix, but looks like it's going to require a bit more time. I don't think this will be particularly difficult, more a question of how to implement it.

**Comment by ncesario-lunarg** [comment]
@rumblehhh do the changes in #2676 fix your issue?

**Comment by rumblehhh** [comment]
These changes look perfect. Thanks for making the changes!

**Comment by ncesario-lunarg** [comment]
Thanks for reporting the issue!
