### ISSUE TITLE
Incorrect validation of completion of events with respect to vkGetQueryPoolResults?

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/Vulkan-ValidationLayers#269]
We are seeing the following validation error when calling vkGetQueryPoolResults:

VK ERROR Validation 0:-1: [ UNASSIGNED-CoreValidation-DrawState-InvalidQuery ] Object: VK_NULL_HANDLE (Type = 12) | Cannot get query results on queryPool 0x2969b90 with index 0 as data has not been collected for this index.

The application follows a pattern something like this (pseudocode):

```
vkBeginCommandBuffer( m_pCurrentVkCommandBuffer );
vkCmdResetQueryPool( m_pCurrentVkCommandBuffer, timestamp.m_pQueryPool, 0, 1 );
vkCmdWriteTimestamp( m_pCurrentVkCommandBuffer, VK_PIPELINE_STAGE_ALL_COMMANDS_BIT, timestamp.m_pQueryPool, 0 );
vkResetEvent( m_pVkDevice, pEventQuery->pEvent );
vkCmdSetEvent( m_pCurrentVkCommandBuffer, pEventQuery->pEvent, VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT );
vkEndCommandBuffer( m_pCurrentVkCommandBuffer );

vkQueueSubmit(...) <- submits m_pCommandBuffer

```
It then waits for the event to be set by doing something like the following on the CPU:

```
while( vkGetEventStatus( m_pVkDevice, pEventQuery->pEvent ) != VK_EVENT_SET ) {}
```
Once the event becomes set, it calls:

```
vkGetQueryPoolResults( m_pVkDevice, timestamp.m_pQueryPool, 0, nCount + 1,
						   sizeof( queryResults ), queryResults, sizeof( uint64_t ),
						   VK_QUERY_RESULT_64_BIT | VK_QUERY_RESULT_WAIT_BIT );
```

This leads to the following validation error:
 [ UNASSIGNED-CoreValidation-DrawState-InvalidQuery ] Object: VK_NULL_HANDLE (Type = 12) | Cannot get query results on queryPool 0x2969b90 with index 0 as data has not been collected for this index.

If I stick a vkDeviceWaitIdle in before calling vkGetQueryPoolResults then the error goes away.  However, since the VkEvent follows the timestamp writes, I believe it should be valid to query for the pool results at this time.  

It seems maybe the event isn't being tracked in validation, at least to the extent necessary to know that it has completed?

**Comment by jzulauf-lunarg** [comment]
There isn't any mechanism to track progress (and dependency) at less than command buffer granularity.  vkGetEventStatus could be used to retire pending work on a queue, but only up to the *previous* command buffer, since while we could know that the command buffer containing the SetEvent has gotten *past* the set event, we couldn't know that the *whole* command buffer had completed, thus we can't retire *any* work from it.

This is a case I'm going to need to integrate into the overall "synchronization" validation planning, but there isn't a straight forward near term fix.

I'm pretty sure that using fences, validation would give correct results -- though fences are limited to per submit granularity.

**Comment by jzulauf-lunarg** [comment]
@danginsburg  -- "A query is considered finished when the final results of the query are ready to be retrieved by vkGetQueryPoolResults and vkCmdCopyQueryPoolResults, and this is when the query’s status is set to available."

Discussed this with @tobine -- these checks actually appear to not be supported by the spec.  Based on the quote above (and surrounding context)  -- you can ask for results anytime you like, and the call will tell you whether or not they're ready, without requirement of *knowing* that they have been submitted or completed. 

Plan of attack is to remove these extra-spec validation checks.

**Comment by zeux** [comment]
We're hitting this as well. Would be great to fix this. We submit a command buffer that writes to the query pool, and then use vkGetQueryPoolResults to check availability before waiting on the fence associated with the pool - I believe this is valid as per spec.

**Comment by jzulauf-lunarg** [comment]
@danginsburg -- referenced PR above has a fix for the issue
