### ISSUE TITLE
core_validation layer gives obscure layer names

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#27]
**Issue by [krOoze](https://github.com/krOoze) (MIGRATED)**
_Monday May 01, 2017 at 21:43 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1724_

----

core_validation layer uses obscure `pLayerPrefix` names like "DS", "DL", "MEM", ...

A) Does anybody know what these mean?

B) `README.md` where I looked for answer links to `layers/vk_validation_layer_details.md`. That document is non-existent.

C) It should be changed to something obvious. And it should at least contain the name of the source layer.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/tobine"><img src="https://avatars0.githubusercontent.com/u/7526739?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tobine](https://github.com/tobine) (MIGRATED)**
_Tuesday May 02, 2017 at 13:49 GMT_

----

Yes, these are a bit outdated and come from the time when all layers were separate.
DS = Draw State
DL = Device Limits
MEM = Memory

We'll soon have string-based unique IDs that may make sense here in addition to unique enum. Those may make sense in this field.

I'll discuss this with LunarG and we'll work out something more sane.

**Comment by mark-lunarg** [comment]
This was fixed by the log_msg rework.
