### ISSUE TITLE
Compile error after headers roll

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-ValidationLayers#2707]
The Vulkan-Headers repository has changed the definition of `VK_NULL_HANDLE`:

```
#ifndef VK_DEFINE_NON_DISPATCHABLE_HANDLE
    #if (VK_USE_64_BIT_PTR_DEFINES==1)
        #if __cplusplus >= 201103L
            #define VK_NULL_HANDLE nullptr
        #else
            #define VK_NULL_HANDLE ((void*)0)
        #endif
    #else
        #define VK_NULL_HANDLE 0ULL
    #endif
#endif
#ifndef VK_NULL_HANDLE
    #define VK_NULL_HANDLE 0
#endif
```

VVL uses `uint64_t` for handles, causing compile error. For example:

```
layers/generated/vk_object_types.h:844:9: error: cannot initialize a member subobject of type 'uint64_t' (aka 'unsigned long') with an rvalue of type 'nullptr_t'
        handle(VK_NULL_HANDLE),
```

Context of the above failure:

```
struct VulkanTypedHandle {
    uint64_t handle;
    ...
        VulkanTypedHandle() :
        handle(VK_NULL_HANDLE),
        ...
```

**Comment by mark-lunarg** [comment]
Yeah, this is a headers issue, [see here.](https://github.com/KhronosGroup/Vulkan-Headers/issues/197#issuecomment-819356229)

**Comment by ShabbyX** [comment]
That seems to be specific to MSVC. The above is a clang failure, so it _may_ not be entirely resolved by the fix for that issue.

**Comment by pdaniell-nv** [comment]
It's probably not safe for the app to assume that a "uint64_t" can interoperate with Vulkan handles. If it wants to use a "uint64_t" as a handle then it probably shouldn't use VK_NULL_HANDLE, which is designed for handles, not uint64_t.

Having said that it does suck when regressions occur...

**Comment by mark-lunarg** [comment]
Yikes.

**Comment by ShabbyX** [comment]
That's my feeling as well, that this is not entirely a Vulkan-Headers issue. VVL shouldn't be using `uint64_t`, but it also looks like there's no defined type-that-matches-non-dispatchable-objects.

**Comment by pdaniell-nv** [comment]
The Vulkan header allows you to define your own VK_DEFINE_NON_DISPATCHABLE_HANDLE, which is what we do to get around this issue, and we can interoperate with uint64_t without trouble.

**Comment by ncesario-lunarg** [comment]
From a validation layers perspective, could/would it make sense to use something like [HandleToUint64](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/675fbfaee4e7ecb34602d5bb20c35b73d0f85ace/layers/vk_layer_logging.h#L127) to store off VK_NULL_HANDLE to a static constant, then compare against that constant rather than VK_NULL_HANDLE in VVL code?

**Comment by oddhack** [comment]
@ShabbyX I did post a candidate header fix attached to https://github.com/KhronosGroup/Vulkan-Docs/issues/1502#issuecomment-820831500 . That may not affect this issue, though - give it a try and let us know if it's better with this header?

**Comment by ShabbyX** [comment]
@oddhack Ben's change to VVL fixes the issue. I didn't get a chance to try your change, sorry.
