### ISSUE TITLE
Warn user when attempting to destroy a presentable vkImage

### ISSUE THREAD

**Issue by wilkesreid** [KhronosGroup/Vulkan-ValidationLayers#2718]
**Describe the situation in which you encountered the missing validation**
Attempting to call `vkDestroySwapchainKHR` on a swapchain that has images which have been destroyed by the application via `vkDestroyImage` can result in a bad memory access. Validation layers currently don't catch this. The documentation is clear that applications should never call `vkDestroyImage` on a presentable image as the lifetime of presentable images is implementation-defined, so validation should warn against it. In practice, the bad memory access error can be misleading, as it appears to the application that the address of the swapchain resource itself is somehow wrong.

**Comment by mark-lunarg** [comment]
@wilkesreid, is there a VUID for this, or can you share the spec location where this is qualified?  It'll help us a lot...

**Comment by wilkesreid** [comment]
@mark-lunarg There doesn't seem to be a strict VUID in the spec, but the following is stated under `vkGetSwapchainImagesKHR` [here](https://renderdoc.org/vkspec_chunked/chap34.html#vkGetSwapchainImagesKHR):

> Further, the lifetime of presentable images is controlled by the implementation, so applications must not destroy a presentable image. See vkDestroySwapchainKHR for further details on the lifetime of presentable images.

It's a bit hard to say exactly where the VUID would go for this since it isn't really defining a valid usage of a particular method. It seems ways to refactor that documented requirement into the spec itself as a VUID could be something like adding "All presentable images acquired from `swapchain` **must not** have been destroyed" to `vkDestroySwapchainKHR`.

If a proposal for a new VUID is beyond the scope of this repo, or if there is in general a more appropriate place to put this issue since it may involve adding to the spec, I'm happy to cooperate. I think in the mean time it would still be helpful for the validation layer to provide a warning for this case.

**Comment by mark-lunarg** [comment]
Great info from both of you!  @wilkesreid, we do have a way of adding VUIDs that don't have spec-assigned identifiers, and we can surely do this -- sounds like Nate already has a good line on it.  This is a good find, thank you for the report.

**Comment by wilkesreid** [comment]
Well due credit to @charles-lunarg who made me aware on the Vulkan discord server that this was an issue-worthy situation. I'm a beginner at Vulkan and had no idea what was going on, haha.

**Comment by sfricke-samsung** [comment]
From spec under `vkGetSwapchainImagesKHR`

> Further, the lifetime of presentable images is controlled by the implementation, so applications must not destroy a presentable image. See vkDestroySwapchainKHR for further details on the lifetime of presentable images.

So agree that it is illegal and the validation layers should track it, but also think the spec needs an explicit VU so I will raise an internal issue to get an explicit VU for `vkDestroyImage`

**Comment by sfricke-samsung** [comment]
Follow-up, spec change was approved this morning so good to go with PR (in terms of WG agreed it was missing and the issue raised was a valid issue)
