### ISSUE TITLE
Non-generated implicit VU that are not stateless

### ISSUE THREAD

**Issue by sfricke-samsung** [KhronosGroup/Vulkan-ValidationLayers#2720]
**Describe the situation in which you encountered the missing validation**
Issue description:

There is an implicit VU `*-cmdpool` for all `vkCmd` calls, but are currently being manually check, an example:

```
bool skip = ValidateCmdQueueFlags(cb_state, "vkCmdBindPipeline()", VK_QUEUE_GRAPHICS_BIT | VK_QUEUE_COMPUTE_BIT, "VUID-vkCmdBindPipeline-commandBuffer-cmdpool");
```

but the XML has `queues="graphics,compute" ` and it would be very easy to generate this logic

The issue is these are not stateless and ideally any generated code could just use `CoreChecks::ValidateCmdQueueFlags` to not copy logic

The issue I have is how to add generated code for `CoreChecks`... I didn't want to create another internal layer/ValidationObject just to handle this single implicit VU. I also didn't want to just go adding an extra jump before every `CoreChecks::PreCallValidate*` call.

Not sure of a good solution, but for now, outside this implicit VU, I don't know of anything else that would really make use of a generated per-function CoreCheck section

**Valid Usage IDs requested**
Please include the valid usage IDs for the checks you are requesting:

- VUID-vkCmdBeginConditionalRenderingEXT-commandBuffer-cmdpool
- VUID-vkCmdBeginDebugUtilsLabelEXT-commandBuffer-cmdpool
- VUID-vkCmdBeginTransformFeedbackEXT-commandBuffer-cmdpool
- VUID-vkCmdBindPipelineShaderGroupNV-commandBuffer-cmdpool
- VUID-vkCmdBindTransformFeedbackBuffersEXT-commandBuffer-cmdpool
- VUID-vkCmdDebugMarkerBeginEXT-commandBuffer-cmdpool
- VUID-vkCmdDebugMarkerEndEXT-commandBuffer-cmdpool
- VUID-vkCmdDebugMarkerInsertEXT-commandBuffer-cmdpool
- VUID-vkCmdEndConditionalRenderingEXT-commandBuffer-cmdpool
- VUID-vkCmdEndDebugUtilsLabelEXT-commandBuffer-cmdpool
- VUID-vkCmdEndTransformFeedbackEXT-commandBuffer-cmdpool
- VUID-vkCmdExecuteGeneratedCommandsNV-commandBuffer-cmdpool
- VUID-vkCmdInsertDebugUtilsLabelEXT-commandBuffer-cmdpool
- VUID-vkCmdPipelineBarrier2KHR-commandBuffer-cmdpool
- VUID-vkCmdPreprocessGeneratedCommandsNV-commandBuffer-cmdpool
- VUID-vkCmdPushDescriptorSetWithTemplateKHR-commandBuffer-cmdpool
- VUID-vkCmdSetCoarseSampleOrderNV-commandBuffer-cmdpool
- VUID-vkCmdSetDeviceMask-commandBuffer-cmdpool
- VUID-vkCmdSetDiscardRectangleEXT-commandBuffer-cmdpool
- VUID-vkCmdSetFragmentShadingRateEnumNV-commandBuffer-cmdpool
- VUID-vkCmdSetPerformanceMarkerINTEL-commandBuffer-cmdpool
- VUID-vkCmdSetPerformanceOverrideINTEL-commandBuffer-cmdpool
- VUID-vkCmdSetPerformanceStreamMarkerINTEL-commandBuffer-cmdpool
- VUID-vkCmdSetSampleLocationsEXT-commandBuffer-cmdpool
- VUID-vkCmdWaitEvents2KHR-commandBuffer-cmdpool
- VUID-vkCmdWriteBufferMarker2AMD-commandBuffer-cmdpool
- VUID-vkCmdWriteBufferMarkerAMD-commandBuffer-cmdpool

**Comment by sfricke-samsung** [comment]
Ok, so `*-renderpass` would be another use case as the following are missing

- VUID-vkCmdBeginTransformFeedbackEXT-renderpass
- VUID-vkCmdCopyImageToBuffer2KHR-renderpass
- VUID-vkCmdEndTransformFeedbackEXT-renderpass
- VUID-vkCmdExecuteGeneratedCommandsNV-renderpass
- VUID-vkCmdPreprocessGeneratedCommandsNV-renderpass

but could call `CoreChecks::InsideRenderPass` or `CoreChecks::OutsideRenderPass` from the XML's `renderpass="inside"` information automatically if generated

**Comment by sfricke-samsung** [comment]
So sorry for talking to myself outloud but realized from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2721 that `ValidateCmd(` is probably the best option here, since every `vkCmd` will have it (or at least pretty maintainable to do that manually) 

(using the `*-recording` example) I guess maybe the real issue for a better way to track the strings for `vk_validation_stats.py`, currently they are in `vk_validation_error_message.h` but seems to then be copied over to `core_validation.cpp` to be tracked, which is not sustainable without constant manual checking

**Comment by mark-lunarg** [comment]
Spencer, another thing to at least have a _look_ at is the CommandCounter helper stuff.  Right now it's only enabled if performance queries are enabled, but we could just enable it all the time to get some autogenerated CmdXxx-related stuff in the main execution path.  (see 'command_counter_helper.*' in the generated files, and 'CoreChecks::InitDeviceValidationObject()'.
