### ISSUE TITLE
VkMemoryDedicatedAllocateInfo::image at time of vkBindImageMemory

### ISSUE THREAD

**Issue by nanokatze** [KhronosGroup/Vulkan-ValidationLayers#2730]
It is unclear whether the image provided in VkMemoryDedicatedAllocateInfo::image at time of vkAllocateMemory needs to remain live at the time of vkBindImageMemory. With dedicatedAllocationImageAliasing feature, I want to "dedicate" the allocation to a worst case _dummy image_ that will be used to vkAllocateMemory, but I will not bind this memory to that image. Instead, new images, smaller or equal in extent to the dummy one, will be created and bound to that memory. This made me think the _dummy image_ could be destroyed immediately after vkAllocateMemory, given that it will not be used any more, but then validation layers report this as violation of VUID-VkBindImageMemoryInfo-memory-02629 when vkBindImageMemory is done. Citing the VUID (emphasis added):
>  If the dedicated allocation image aliasing feature is enabled, and the VkMemoryAllocateInfo provided when memory was allocated included a VkMemoryDedicatedAllocateInfo structure in its pNext chain, and VkMemoryDedicatedAllocateInfo::image was not VK_NULL_HANDLE, then memoryOffset must be zero, and image must be either equal to VkMemoryDedicatedAllocateInfo::image **or an image that was created using the same parameters in VkImageCreateInfo, with the exception that extent and arrayLayers may differ subject to the following restrictions: every dimension in the extent parameter of the image being bound must be equal to or smaller than the original image for which the allocation was created; and the arrayLayers parameter of the image being bound must be equal to or smaller than the original image for which the allocation was created**

I was unable to find any wording in the specification that would suggest that image the allocation was dedicated to has to be kept alive during vkBindMemory which leads me to think doing so is not violation of the above VUID and leaves me confused.

**Comment by pdaniell-nv** [comment]
@ncesario-lunarg @Tony-LunarG is there someone that can pick up this validation bug?
