### ISSUE TITLE
Android settings behavior

### ISSUE THREAD

**Issue by ncesario-lunarg** [KhronosGroup/Vulkan-ValidationLayers#2742]
@sfricke-samsung brought up some topics that could use some resolution regarding how settings are managed on Android [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2736#issuecomment-825450313).

## 1. Using a C/C++ API over the `getprop` command  (_Resolved_)

I'm in favor of using an API over a command if it's "reliably available." It looks like the currently recommended way to do this is via [GetProperty](https://android.googlesource.com/platform/system/core/+/android-8.0.0_r2/base/include/android-base/properties.h#35) from android-base/properties.h, but I'm not sure how to use that without access to AOSP. I agree that whatever we use, we should use it consistently across the ecosystem.

**Resolution**: no action at this time; continue to use the `getprop` process.

## 2. Use something along the lines of `debug.vvl.settings_path` vs `VK_LAYER_SETTINGS_PATH` for property names

This sounds like a good idea, but might require some investigation on how disruptive it would be. I don't think it would be too disruptive code-wise, but there may be documentation that relies on Android using the same names as desktop environment variables.

FYI @lunarpapillo @johnzupin @jeremyg-lunarg.

**Comment by mark-lunarg** [comment]
For 2, we absolutely want to keep the text the same for the individual settings, though we _could_ add a `vvl` sandbox for all the settings, it's just a slightly harder story to tell in some already challenging settings documentation.  I had some branches which added Android settings support but never pushed them due to lack of interest -- I vaguely remember significant issues with `GetProperty` and that the current solution was the reliable one.

**Comment by ncesario-lunarg** [comment]
Thanks @mark-lunarg. I was also thinking that perhaps just prefixing all the env vars with `debug.vvl` might work, but again, not sure how disruptive this would be in practice.

Strangely, based on the small amount of searching I've done, the `getprop` command (i.e., our current implementation) seems to be the most popular, and I'm guessing that's for a good reason. Unfortunate we need to launch a process to access that information, but looks like that's the thing to do.

**Comment by mark-lunarg** [comment]
This is probably obvious to everybody, but for these settings the `debug.` prefix for the properties is required -- the `vvl.` part would be a new piece.

**Comment by sfricke-samsung** [comment]
the `vvl` was an arbitrary suggestion I made before https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2651#discussion_r601405171 

I pointed out in the PR api dump uses naming convention `setprop debug.apidump_log_filename` and validation could use `setprop debug.khronos_validation_report_flags` to be consistent with the SDK's `vk_layer_settings.txt` file

**Comment by ncesario-lunarg** [comment]
I'm marking the first topic as resolved, as I don't see a reason to change this in the short term.

I'll do some further investigation on (2). I need to get more familiar with the settings code.

**Comment by ncesario-lunarg** [comment]
This was resolved by https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5864 and https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6043.
