### ISSUE TITLE
thread_safety assertion failed with vkRegisterDisplayEventEXT

### ISSUE THREAD

**Issue by qxsnap** [KhronosGroup/Vulkan-ValidationLayers#2743]
Using vk_khr_display and VK_EXT_display_control, I'm getting a FindObject assertion failure on the VkDisplayKHR handle during thread safety validation.  This appears similar to #1569 and #1987.

```
main.app: /build/Vulkan-ValidationLayers/layers/generated/thread_safety.h:143: std::shared_ptr<ObjectUseData> counter<T>::FindObject(T) [with T = VkDisplayKHR_T*]: Assertion `object_table.contains(object)' failed.
Aborted (core dumped)
```

Using SDK 1.2.174 on aarch64.   The VK_EXT_display_control extension performs correctly when validation layers are disabled.

It appears that `display` is never added to `layer_data` for `device` by any Vulkan command in layer_chassis_dispatch.cpp.  Rather `display` is added to `layer_data` for `physicalDevice` by `DispatchGetPhysicalDeviceDisplayPropertiesKHR`.  

Because `vkRegisterDisplayEventEXT` doesn't have `physicalDevice` as an argument, there is no direct way for `DispatchRegisterDisplayEventEXT` to correctly unwrap `display`.   Somehow the `physicalDevice` would need to be derived from the `device`.

A workaround is to bypass threading checks on `display` in thread_safety.cpp:
```
void ThreadSafety::PreCallRecordRegisterDisplayEventEXT(
    VkDevice                                    device,
    VkDisplayKHR                                display,
    const VkDisplayEventInfoEXT*                pDisplayEventInfo,
    const VkAllocationCallbacks*                pAllocator,
    VkFence*                                    pFence) {
    StartReadObjectParentInstance(device, "vkRegisterDisplayEventEXT");
    //StartReadObject(display, "vkRegisterDisplayEventEXT");
}

void ThreadSafety::PostCallRecordRegisterDisplayEventEXT(
    VkDevice                                    device,
    VkDisplayKHR                                display,
    const VkDisplayEventInfoEXT*                pDisplayEventInfo,
    const VkAllocationCallbacks*                pAllocator,
    VkFence*                                    pFence,
    VkResult                                    result) {
    FinishReadObjectParentInstance(device, "vkRegisterDisplayEventEXT");
    //FinishReadObject(display, "vkRegisterDisplayEventEXT");
```

However then another failure occurs in vkWaitForFences waiting on the VkFence created by `vkRegisterDisplayEventEXT`:
```
main.app: /build/Vulkan-ValidationLayers/layers/generated/thread_safety.h:143: std::shared_ptr<ObjectUseData> counter<T>::FindObject(T) [with T = VkFence_T*]: Assertion `object_table.contains(object)' failed.
Aborted (core dumped)
```

For some reason the VkFence created by vkRegisterDisplayEventEXT isn't known to the layers.  It's not yet clear to me where the problem is, since `DispatchRegisterDisplayEventEXT` seems to do the same wrapping that `DispatchCreateFence` does.

**Comment by ChristophHaag** [comment]
Bumping because we want to use this in Monado and ran into the same issues.

It affects Valve's SteamVR vrcompositor on linux too. You can run it like this to see it:

`VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation LD_LIBRARY_PATH=~/.steam/steam/steamapps/common/SteamVR/bin/linux64 ~/.steam/steam/steamapps/common/SteamVR/bin/linux64/vrcompositor --keepalive`

**Comment by jeremyg-lunarg** [comment]
@ChristophHaag  I haven't been able to reproduce this crash yet,  but I think the code in #3566 *might* fix it. If you have a chance to give it a try please let us know, otherwise we can try to reproduce it again next week. Thanks!

**Comment by ChristophHaag** [comment]
#3566 indeed fixes both issues, thanks.
