### ISSUE TITLE
Security-related VUIDs Missing

### ISSUE THREAD

**Issue by ncesario-lunarg** [KhronosGroup/Vulkan-ValidationLayers#2746]
The following VUIDs have been identified as related to security and validation for them is currently missing.

- [ ] `VUID-vkCmdCopyBufferToImage-pRegions-00173`
- [ ] `VUID-vkCmdCopyImageToBuffer-pRegions-00184`
- [x] `VUID-vkCmdBlitImage-pRegions-00217`
- [x] `VUID-*-commandBuffer-02712`
- [x] `VUID-*-commandBuffer-02707`

FYI @Tony-LunarG.

**Comment by arno-lunarg** [comment]
Closing in favor of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3993
