### ISSUE TITLE
vk_extension_helper.h:972:14: error: 'VK_QCOM_render_pass_store_ops_EXTENSION_NAME' was not declared in this scope;

### ISSUE THREAD

**Issue by shoober420** [KhronosGroup/Vulkan-ValidationLayers#2751]
Building from git master as of https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/27193c3c3005af8f2d89dd51259a645fa388726e, I get this compile error.

vk_extension_helper.h:972:14: error: 'VK_QCOM_render_pass_store_ops_EXTENSION_NAME' was not declared in this scope; did you mean 'VK_QCOM_render_pass_store_ops'?

I have Robin Hood hashing disabled using -DUSE_ROBIN_HOOD_HASHING=OFF.

**Environment:**
 - OS: Gentoo Linux
 - GPU: AMD Radeon RX 5500 XT
 - SDK or header version if building from repo: https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-util/vulkan-headers/vulkan-headers-9999.ebuild
 - Options enabled (synchronization, best practices, etc.): https://github.com/shoober420/shoober420-overlay/blob/main/media-libs/vulkan-layers/vulkan-layers-9999.ebuild

Here is the log.
[vulkan-layers-9999norobinhood.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/6386832/vulkan-layers-9999norobinhood.txt)

**Comment by ncesario-lunarg** [comment]
Thanks @shoober420, would you happen to be using headers 1.2.177? From @mikes-lunarg: 
> VK_QCOM_render_pass_store_ops_EXTENSION_NAME changed to VK_QCOM_RENDER_PASS_STORE_OPS_EXTENSION_NAME in 177

VVL has not been updated to 1.2.177 yet.

**Comment by shoober420** [comment]
@ncesario-lunarg 
I'm using the vulkan-headers-9999.ebuild, which builds directly from git master.

https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-util/vulkan-headers/vulkan-headers-9999.ebuild

**Comment by ncesario-lunarg** [comment]
Right, looks like that that is pulling from the Vulkan-Headers master branch, which is expected to not work. You can view which Vulkan-Headers version will work in [known_good.json](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/27193c3c3005af8f2d89dd51259a645fa388726e/scripts/known_good.json#L23) (which is currently set to the `v1.2.176` tag).

Closing as this is expected. Please re-open if you feel there is still an issue.
