### ISSUE TITLE
Add support for `VK_EXT_provoking_vertex`

### ISSUE THREAD

**Issue by hevrard** [KhronosGroup/Vulkan-ValidationLayers#2755]
**Describe the situation in which you encountered the missing validation**

The VVL seems unaware of the `VK_EXT_provoking_vertex` extension, I get validation errors like:

```
VUID-VkDeviceCreateInfo-pNext-pNext(ERROR / SPEC): msgNum: -1876993556 - Validation Error: [ VUID-VkDeviceCreateInfo-pNext-pNext ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x901f59ec | vkCreateDevice: pCreateInfo->pNext chain includes a structure with unknown VkStructureType (1000254000)
```

And looking in Vulkan headers:

```
VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROVOKING_VERTEX_FEATURES_EXT = 1000254000
```

**Valid Usage IDs requested**
Please include the valid usage IDs for the checks you are requesting:

All the VUID related to this extension.

**Comment by KarenGhavam-lunarG** [comment]
Once the 1.2.177 header is propagated to this repository, there will be a merge request to add the validation layer support from @locke-lunarg

**Comment by hevrard** [comment]
Sounds good! Thanks for the prompt clarification.

**Comment by ncesario-lunarg** [comment]
@locke-lunarg, could you please link this to your PR when 1.2.177 gets merged and you have a chance to create it?
