### ISSUE TITLE
vkCreateRayTracingPipelinesKHR with Deferred Operations 

### ISSUE THREAD

**Issue by amhagan** [KhronosGroup/Vulkan-ValidationLayers#2767]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/884579ec2928a26cffac0573101f48efe82d87de/layers/generated/layer_chassis_dispatch.cpp#L2269-L2271

If result of vkCreateRayTracingPipelinesKHR is a VK_OPERATION_DEFERRED_KHR the pCreateInfos need to be available in memory until the deferred operation is complete. 

> 
> 3.6. Threading Behavior
> if an application is using deferred host operations in a command, and that operation is successfully deferred, object parameters and application-owned memory passed to that command may be accessed at any time until the deferred operation is complete.
>

**Comment by ncesario-lunarg** [comment]
Thanks for the issue @amhagan! Would you be able to provide some sample code that reproduces the issue you're seeing?

Also, I'm assuming this is referring to the `DispatchCreateRayTracingPipelinesKHR` rather than the  `DispatchCreateComputePipelines` code? https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/884579ec2928a26cffac0573101f48efe82d87de/layers/generated/layer_chassis_dispatch.cpp#L9008

**Comment by amhagan** [comment]
> [Vulkan-ValidationLayers/layers/generated/layer_chassis_dispatch.cpp](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/884579ec2928a26cffac0573101f48efe82d87de/layers/generated/layer_chassis_dispatch.cpp#L9008)

Yes.. sorry.. DispatchCreateRayTracingPipelinesKHR not DispatchCreateComputePipelines 

I will get a repo case together..

**Comment by AaronHaganAMD** [comment]
To repro this issue you can use the https://github.com/AaronHaganAMD/VK-GL-CTS repository with the RayTracingDeferredPipelines branch.

Command line arguments:
--deqp-validation=enable  -n dEQP-VK.ray_tracing_pipeline.large_shader_set.gpu.64

**Comment by AaronHaganAMD** [comment]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/884579ec2928a26cffac0573101f48efe82d87de/layers/generated/layer_chassis_dispatch.cpp#L9012-L9015

I think its invalid to wrap the pipeline handle here if the operation is VK_OPERATION_DEFERRED_KHR.
The pipeline value is non-deterministic and unreadable until the deferred operation completes.

**Comment by souravpNV** [comment]
@AaronHaganAMD I tried locally with your deferred pipeline builds commit,   I  see few validation warnings but no errors, I am using the latest public SDK.

I used  deqp-vk.exe --deqp-validation=enable --deqp-case=dEQP-VK.ray_tracing_pipeline.large_shader_set.gpu.64

**Comment by AaronHaganAMD** [comment]
> @AaronHaganAMD I tried locally with your deferred pipeline builds commit, I see few validation warnings but no errors, I am using the latest public SDK.
> 
> I used deqp-vk.exe --deqp-validation=enable --deqp-case=dEQP-VK.ray_tracing_pipeline.large_shader_set.gpu.64

What implementation did you try this on? This currently doesn't work on AMD's implementation as this violates the spec by reading pipeline values before the deferred operation is complete.

**Comment by FrancoisBeaune** [comment]
Hi,

As a data point, we (Adobe) would really like to see this bug fixed. Let me know if we can be in any help to reproduce the issue.

Thanks for the great work everyone.

**Comment by AaronHaganAMD** [comment]
> Hi,
> 
> As a data point, we (Adobe) would really like to see this bug fixed. Let me know if we can be in any help to reproduce the issue.
> 
> Thanks for the great work everyone

I have an updated change set that I believe I can put up for review in the next couple days. Thanks.

**Comment by jeremyg-lunarg** [comment]
There's several other ray tracing host commands that use deferred operations:

- vkBuildAccelerationStructuresKHR()
- vkCopyAccelerationStructureKHR()
- vkCopyAccelerationStructureToMemoryKHR()
- vkCopyMemoryToAccelerationStructureKHR()
- vkWriteAccelerationStructuresPropertiesKHR()

Will these have the same problem?

**Comment by larsivarsimonsen-arm** [comment]
Hi,

I've made a more generic fix in #3592 that should fix both vkCreateRayTracingPipelinesKHR and the host acceleration structure functions.

Please have a look at it at your convenience.

**Comment by ncesario-lunarg** [comment]
Re-opening as #3592 is not a complete fix.

**Comment by ncesario-lunarg** [comment]
@larsivarsimonsen-arm please let me know if you are unable to make the changes @AaronHaganAMD [mentioned](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3592#issuecomment-990123429) and we will assign someone. Thanks!

**Comment by jeremyg-lunarg** [comment]
> Re-opening as #3592 is not a complete fix.

That change fixed the dispatch layer code, but we need to do something similar in the state tracker and derived classes. Anything that has a PostCallRecordCreateRayTracingPipelinesKHR() will need to not run it until the deferred operation completes. Maybe it can happen in chassis.cpp.

@AaronHaganAMD  is going to post a PR with a test case that shows the whole problem.

**Comment by larsivarsimonsen-arm** [comment]
@ncesario-lunarg As mentioned in #3592 I currently don't have access to a device to test this on, so I won't be able to verify the fix.
If someone is available to pick this up, I think that would be better.

**Comment by ncesario-lunarg** [comment]
Sounds good @larsivarsimonsen-arm, and thanks for the getting the other fixes in!

**Comment by ncesario-lunarg** [comment]
@stu-s I don't think so. The issue JeremyG [mentioned](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2767#issuecomment-990260116) is still outstanding.

**Comment by aitor-lunarg** [comment]
Remaining issue is fixed with #3793.

**Comment by FrancoisBeaune** [comment]
Awesome, thanks everyone for the great work!
