### ISSUE TITLE
Validation layers with handle wrapping on cause a segfault on Swapchain creation

### ISSUE THREAD

**Issue by SunGrow** [KhronosGroup/Vulkan-ValidationLayers#2773]
**Describe the Issue**
Validation layers with handle wrapping on cause a segfault on Swapchain creation. No validation error (when validation is on) precede the segfault. Everything works perfectly fine, with 'handle wrapping' turned off

**Valid Usage ID**
[apidumpout.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/6420427/apidumpout.txt)

**Environment:**
 - OS: Linux 5.11.16-arch1-1
 - GPU: AMD Radeon(TM) Vega 8 Graphics
 - SDK or header version if building from repo: 
 Headers: 1.2.177-1
 Loader: 1.2.177
 Physical Device: 1.2.174
 - Options enabled (synchronization, best practices, etc.): Handle Wrapping

**Additional context**
Issue does not occur on GTX 1060 6G with Vulkan 1.2.155, Vulkan loader 1.2.162 and sdk 1.2.154.1

**Comment by ncesario-lunarg** [comment]
Thanks for the issue @SunGrow! Do you have a sample reproduction case? Unfortunately, there are known issue when running AMD mesa drivers with `VK_LAYER_KHRONOS_validation`, with handle wrapping being one of them. Running the test suite gives somewhat of a good idea where some of the problems are (many tests either fail or crash in the driver), but some of the tests that are passing do call vkCreateSwapchain.

**Comment by SunGrow** [comment]
Yeah... The error appears to be on the driver side (crashes in amdvlk64.so). But, since it may be a known issue, I am not sure, if I should report it to the amdvlk repo... And what exactly to report... Let's hope I will have some free time for that in the future... 
Either way, just in case, here is a validation test output:
[testout.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/6429654/testout.txt)
Thread backtrace:
```* thread #1, name = 'demoapp', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
  * frame #0: 0x00007ffff7bed59a libc.so.6`__memmove_avx_unaligned_erms + 154
    frame #1: 0x00007ffff3ca941c amdvlk64.so`___lldb_unnamed_symbol4385$$amdvlk64.so + 1868
    frame #2: 0x00007ffff74754fd libvulkan.so.1`___lldb_unnamed_symbol403$$libvulkan.so.1 + 237
    frame #3: 0x00007ffff2c1455b libVkLayer_khronos_validation.so`DispatchCreateSwapchainKHR(VkDevice_T*, VkSwapchainCreateInfoKHR const*, VkAllocationCallbacks const*, VkSwapchainKHR_T**) at layer_chassis_dispatch.cpp:350:75
    frame #4: 0x00007ffff2bb5192 libVkLayer_khronos_validation.so`vulkan_layer_chassis::CreateSwapchainKHR(VkDevice_T*, VkSwapchainCreateInfoKHR const*, VkAllocationCallbacks const*, VkSwapchainKHR_T**) at chassis.cpp:4789:49
    frame #5: 0x000055555557ef7b demoapp`createVkSwapchain(pApp=0x00005555556610a0, oldswapchain=0x0000000000000000, pSwapchain=0x0000555556195400) at sg_material.c:161:6
    frame #6: 0x000055555557f04e demoapp`sgCreateSwapchain(pApp=0x00005555556610a0, pCreateInfo=0x00007fffffffdea0, pSwapchain=0x0000555556195400) at sg_material.c:177:2
    frame #7: 0x000055555557fa37 demoapp`sgCreateMaterialMap(pApp=0x00005555556610a0, pCreateInfo=0x00007fffffffe020, ppMaterialMap=0x00007fffffffdf90) at sg_material.c:326:2
    frame #8: 0x000055555555c45b demoapp`main at main.c:386:2
    frame #9: 0x00007ffff7ab0b25 libc.so.6`__libc_start_main + 213
    frame #10: 0x000055555555b68e demoapp`_start + 46
```
If a portable sample reproduction case is needed, please let me know and I will try to make one.
But in the meantime, I have this issue appearing in my ~~janky forever todo~~ sungrow/sage project, if that's of any help
