### ISSUE TITLE
sdk-1.2.176.0: build fails

### ISSUE THREAD

**Issue by kloczek** [KhronosGroup/Vulkan-ValidationLayers#2775]
spirv-headers from git master (still no release of those headers as regular release).
vulkan-loader sdk-1.2.176
```console
[tkloczko@barrel x86_64-redhat-linux-gnu]$ make
/usr/bin/cmake -S/home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0 -B/home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0/x86_64-redhat-linux-gnu --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0/x86_64-redhat-linux-gnu/CMakeFiles /home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0/x86_64-redhat-linux-gnu//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0/x86_64-redhat-linux-gnu'
make  -f CMakeFiles/VkLayer_utils.dir/build.make CMakeFiles/VkLayer_utils.dir/depend
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0/x86_64-redhat-linux-gnu'
cd /home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0/x86_64-redhat-linux-gnu && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0 /home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0 /home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0/x86_64-redhat-linux-gnu /home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0/x86_64-redhat-linux-gnu /home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0/x86_64-redhat-linux-gnu/CMakeFiles/VkLayer_utils.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0/x86_64-redhat-linux-gnu'
make  -f CMakeFiles/VkLayer_utils.dir/build.make CMakeFiles/VkLayer_utils.dir/build
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0/x86_64-redhat-linux-gnu'
[  2%] Building CXX object CMakeFiles/VkLayer_utils.dir/layers/vk_layer_config.cpp.o
/usr/bin/g++ -DAPI_NAME=\"Vulkan\" -DUSE_ROBIN_HOOD_HASHING -DVK_ENABLE_BETA_EXTENSIONS -DVkLayer_utils_EXPORTS -I/home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0/layers -I/home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0/layers/generated -I/home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0/x86_64-redhat-linux-gnu -I/home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0/x86_64-redhat-linux-gnu/layers -I/src/include -I/home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0/PATH -I"/home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0/Path to robin-hood-hashing/include" -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -DNDEBUG -fPIC -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -fvisibility=hidden -Wimplicit-fallthrough=0 -std=gnu++11 -o CMakeFiles/VkLayer_utils.dir/layers/vk_layer_config.cpp.o -c /home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0/layers/vk_layer_config.cpp
In file included from /home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0/layers/vk_layer_config.h:27,
                 from /home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0/layers/vk_layer_config.cpp:25:
/home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0/layers/vk_layer_data.h:37:10: fatal error: robin_hood.h: No such file or directory
   37 | #include "robin_hood.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/VkLayer_utils.dir/build.make:85: CMakeFiles/VkLayer_utils.dir/layers/vk_layer_config.cpp.o] Error 1
```

**Comment by akeley98NV** [comment]
You need to run `scripts/update_deps.py` to fetch the new hashtable dependency.

**Comment by kloczek** [comment]
```console
+ /usr/bin/python3 scripts/update_deps.py
Starting builds in /home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0
Checking out glslang in /home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0/glslang
Cloning glslang into /home/tkloczko/rpmbuild/BUILD/Vulkan-ValidationLayers-sdk-1.2.176.0/glslang
```
Are you kidding?
This **will not work** on builders on most of the Linux distributions whic are intentionally cut off any access to network eccept localhost.
Why you are fetching those trees instead just relly on system installed version of the components like spirv-headers or glslang?
So glslang needs to be updated?
If yes why did you not coordinate that with glslang maintainetr to ask to make new glslang release before sdk release of the Vulkan-ValidationLayers?

**Comment by kloczek** [comment]
spirv-headers or glslang are maintained under common github organisation https://github.com/KhronosGroup
Why it is so poor communication inside that organisation before making exact releases?
SPIRV-Headers is not reacting at all on my monits about new release
https://github.com/KhronosGroup/SPIRV-Headers/issues/199
Did you try to contact SPIRV-Headers and glslang maintainers before make new sdk release of the Vulkan-ValidationLayers?

**Comment by kloczek** [comment]
I just updated my glslang rpm package to 11.4.0 which has been released only 12 days ago and Vulkan-ValidationLayers build still fails.

Really please taka as accusation or attack but please oh please better coordinate own release with releases all components which Vulkan-ValidationLayers is using because releasing own code as new version which is basing on unreleased code of other components it is not how it suppose to work :(

I see that glslang does not offer pkgconfig file to allow other components detect other software in exact versions.
Will try to submit to spirv-headers and glslang patches to generate and install pkgconfig files.
Really .. relaying on cloning git trees ins not acceptable. It is IMO nothing more than asking for troubles :(

Again please do not take what I wrote as accusation or attack but that build dependencies should be really resolved over pkgconfig.
As I wrote will try to help on provide such description an use it as well.

**Comment by jeremyg-lunarg** [comment]
As far as your original problem goes, the source of robin_hood.h is described here  https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/BUILD.md#robin-hood-hashing  and here https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/scripts/known_good.json#L34 .  Our you can build without it by setting the cmake variable USE_ROBIN_HOOD_HASHING to FALSE

**Comment by kloczek** [comment]
Thx will try that ASP 😀
Nevertheless will try to help with provide and use pkgconfig 😋

**Comment by ncesario-lunarg** [comment]
Thanks for the issue @kloczek! [known_good.json](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/scripts/known_good.json) (which `update_deps.py` makes use of) has been the mechanism for fetching VVL dependencies for a few years, and other repos in the Vulkan ecosystem (e.g., [glslang](https://github.com/KhronosGroup/glslang/blob/master/known_good.json)) use a similar mechanism. Using pkgconfig for describing dependencies is less desirable due to the fact that this code must be built on multiple platforms (e.g., Windows) and other repos we depend on don't necessarily use pkgconfig. I definitely understand the frustration here, but unfortunately this is not something we can change in the near future. That said, if you know of a good way to make our code "pkgconfig-compatible," PRs are always welcome :)

As the documentation @jeremyg-lunarg pointed to, please keep in mind there is a significant performance penalty when _not_ using Robin Hood Hashing.

**Comment by kloczek** [comment]
FYI `USE_ROBIN_HOOD_HASHING=OFF` fixed build issue. Thx 😀

If may I have two questions ..
- I've managed to build Vulkan-ValidationLayers with `-fno-exceptions` which is good however I see that RTTIs (`-fno-rtti`) are massively used. Q: is it not would be good to try to avoiduise RTTI? (as long ter target)
- what is the impact of  `USE_ROBIN_HOOD_HASHING=OFF`?🤔

**Comment by jeremyg-lunarg** [comment]
> FYI `USE_ROBIN_HOOD_HASHING=OFF` fixed build issue. Thx 
> 
> If may I have two questions ..
> 
> * I've managed to build Vulkan-ValidationLayers with `-fno-exceptions` which is good however I see that RTTIs (`-fno-rtti`) are massively used. Q: is it not would be good to try to avoiduise RTTI? (as long ter target)

Not easily... we're using RTTI to avoid calling default no-op virtual methods, which saves 5% of CPU time in multithreaded applications.  See; https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/generated/chassis_dispatch_helper.h#L27

> * what is the impact of  `USE_ROBIN_HOOD_HASHING=OFF`?thinking

That switches back to using std::unordered_map and std::unordered_set instead of the robin_hood:: versions.  The std:: versions are much slower. This will cost 10-25% CPU time in most applications.
See: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/vk_layer_data.h#L87

**Comment by kloczek** [comment]
FYI I made PR to provide pkgconfig file by SPIRV-Headers https://github.com/KhronosGroup/SPIRV-Headers/pull/209
When this PR will be commited will try to create PR for Vulkan-ValidationLayers to use that.
