### ISSUE TITLE
Get Windows mock ICD tests working in CI

### ISSUE THREAD

**Issue by ncesario-lunarg** [KhronosGroup/Vulkan-ValidationLayers#2784]
The `scripts/github_ci_win_linux.py` script does not work on Windows in its current form. This needs to be fixed so that mock ICD tests also run on Windows. Once `scripts/github_ci_win_linux.py` works properly on Windows, remove `scripts/github_ci_win.py` as it will no longer be necessary.

@mikes-lunarg was able to get this script working on Windows.

**Comment by spencer-lunarg** [comment]
@ncesario-lunarg I don't see `github_ci_win.py` anymore, this done?

**Comment by ncesario-lunarg** [comment]
No, CI still doesn't run on Windows in github actions, but I think we established that this isn't a big deal. I'll close for now and can reopen if someone has strong feelings about this.
