### ISSUE TITLE
Debug printf should support standard C format string for 64-bit integers

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-ValidationLayers#2786]
**Describe the Issue**
Currently the [docs](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/docs/debug_printf.md) list `%ul` as the way to print a 64-bit integer, but this is backwards from the standard printf strings used everywhere else where it would be `%lu` (though that confusingly just means long i.e 32-bit so it would be `%llu` more likely, though this is not completely portable). This also leads to potential ambiguities such as it being impossible to print a 32-bit integer immediately followed by a lowercase L with no space in between. Perhaps unlikely but a limitation that doesn't normally exist otherwise because the parsing of normal printf strings is unambiguous.

With shaders likely having shipped relying on `%ul` I don't think it can be removed, but if a different format specifier is necessary it would be nice to support the C standard `%llu` or just `%lu`. I'm not sure quite why this is needed though since SPIR-V gives all the type information necessary compared to normal C varargs and length specifiers aren't used elsewhere for other types.

This would also mean that `%lu` could be printed as decimal 64-bit integers and `%lx` for hex.

**Environment:**
 - OS: Windows
 - GPU: NV 1080 Ti
 - SDK version: 1.2.176.1
 - Options enabled (synchronization, best practices, etc.): debug printf

**Comment by Tony-LunarG** [comment]
Fixed in #2802
