### ISSUE TITLE
Messy tagging.

### ISSUE THREAD

**Issue by kloczek** [KhronosGroup/Vulkan-ValidationLayers#2790]
Up to now where used two git tag patters `<version>` and `sdk-<version>`
Today have been introduced `sdk.<version>-TAG`
Is it possible to stick with old patters?

**Comment by ncesario-lunarg** [comment]
@johnzupin, does this have something to do with the branch/tag name conflict you encountered?

**Comment by KarenGhavam-lunarG** [comment]
Due to required workflows for SDK releases, SDK tags moving forward will have a -TAG added to their name.
