### ISSUE TITLE
BestPractices::ManualPostCallRecordAllocateMemory references vkReleaseFullScreenExclusiveModeEXT rather than vkAllocateMemory

### ISSUE THREAD

**Issue by rumblehhh** [KhronosGroup/Vulkan-ValidationLayers#2794]
BestPractices::ManualPostCallRecordAllocateMemory references vkReleaseFullScreenExclusiveModeEXT rather than vkAllocateMemory which I believe should instead be referenced. 
Line linked here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/20678fff2a19946fe8d5f3ee5300af1c3228268a/layers/best_practices_utils.cpp#L573

**Comment by ncesario-lunarg** [comment]
Yep, that makes sense :)
