### ISSUE TITLE
Housekeeping: split up layer_validation_tests.cpp

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#28]
**Issue by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Wednesday May 10, 2017 at 17:33 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1754_

----

**Comment by karl-lunarg** [comment]
<a href="https://github.com/jeremy-lunarg"><img src="https://avatars0.githubusercontent.com/u/6943397?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jeremy-lunarg](https://github.com/jeremy-lunarg) (MIGRATED)**
_Wednesday May 10, 2017 at 17:37 GMT_

----

Any thoughts/opinions on the dissection?

**Comment by karl-lunarg** [comment]
<a href="https://github.com/chrisforbes"><img src="https://avatars1.githubusercontent.com/u/128877?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Wednesday May 10, 2017 at 20:02 GMT_

----

I was going to start with:

- ErrorMonitor on its own.
- CreatePipeline* (all the SC checks) together in their own file

**Comment by karl-lunarg** [comment]
<a href="https://github.com/krOoze"><img src="https://avatars1.githubusercontent.com/u/3791331?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [krOoze](https://github.com/krOoze) (MIGRATED)**
_Sunday Nov 26, 2017 at 16:59 GMT_

----

Since VUs are per-command, I propose splitting to one file per tested command (or rationaly multiple related ones). Structures that can be used independently by multiple commands can be a separate header.

Aditionally this could lead to ~two tests per file (small number of positive and negative tests). Each test setup takes over half second. Aggregating some tests shouldn't break things for the case the subtests succeed, and it could greatly improve testing time.

I think e.g. `vkCmdSet*` commands could be tested together, and so in single file.

And of course utils and whatever should be in separate file(s).

Thoughts?

**Comment by mark-lunarg** [comment]
This is being tracked and handled in issue #427.
