### ISSUE TITLE
Invalid UTF-8 character in `layers/gpu_validation.cpp`

### ISSUE THREAD

**Issue by timvpGoogle** [KhronosGroup/Vulkan-ValidationLayers#2804]
**Describe the Issue**
Commit f0d4e2bc438e281f5e271568a932a4adb520f10d (gpu: More info in draw indirect count message) introduced an invalid UTF-8 character:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/6da4ac2df971af6b2b697d94dd1e2e38c4bcd8fa/layers/gpu_validation.cpp#L1345

The "×" character cannot be encoded as UTF-8.   Opening the file in an IDE (e.g., CLion) will also generate an error indicating that the file has invalid UTF-8 encoding due to the character.

This causes compilation failures in ANGLE:
https://chromium-review.googlesource.com/c/angle/angle/+/2894300

```
 ../../third_party/vulkan-deps/vulkan-validation-layers/src/layers/gpu_validation.cpp(985): error C2220: the following warning is treated as an error
 ../../third_party/vulkan-deps/vulkan-validation-layers/src/layers/gpu_validation.cpp(985): warning C4828: The file contains a character starting at offset 0x13e69 that is illegal in the current source character set (codepage 65001).
```

**Comment by timvpGoogle** [comment]
Pull request:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2805

**Comment by timvpGoogle** [comment]
I don't know how to use GitHub I can't find good documentation, so here's a new PR:

Pull request:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2806

**Comment by ncesario-lunarg** [comment]
👍 thanks! In the future, amending the commit and doing a force push to the branch should get the job done if that works for you.
