### ISSUE TITLE
`vkCreateDevice` doesn't check features against enabled extensions

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-ValidationLayers#2818]
**Describe the situation in which you encountered the missing validation**
With `VK_KHR_get_physical_device_properties2` enabled, I include features structs in the `pNext` chain of `vkGetPhysicalDeviceFeatures2`, that require an extension to be supported on the given Vulkan `apiVersion`. For example, with the instance's `apiVersion` set to 1.0, I can include e.g. `VkPhysicalDevice16BitStorageFeaturesKHR` in the chain, and the implementation will set the `storagePushConstant16` member to `VK_TRUE`. I think this is expected, because when quering features support for a physical device, there is no logical device yet, and therefore the needed extensions could not have been enabled. (I suppose it's possible that the device still needs to _support_ the extension in order to include its features struct in the chain, or maybe it's just meant to skip any structs it doesn't recognise.)

When I move on to creating the logical device, I pass on the same chain of structs that was used to query the features, in the `pNext` chain of `VkDeviceCreateInfo`. But I don't enable any device extensions, which means that `storagePushConstant16` is going to be enabled on a Vulkan 1.0 device, but the required extension is not. The validation layers don't report any error in this case.

**Valid Usage IDs requested**
I can't find anything in the specs that explicitly says that this is allowed or disallowed. In the case of extensions, you generally can't use anything provided by the extension without enabling it, so that suggests that this is a validation error.

**Comment by ncesario-lunarg** [comment]
Thanks for the issue @Rua! I also don't see anything in the spec that says you _must_ enable the extension to use a feature. If you're querying for feature support, and the implementation reports that the feature is supported, that is what really matters from my understanding of the spec. Closing this for now as it's not clear to me that there is a spec violation here; might be worth bringing this topic up in Vulkan-Docs for clarification.

**Comment by Rua** [comment]
[This part of the spec](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap3.html#fundamentals-validusage-extensions) states:
> Physical-device-level functionality or behavior added by a device extension to the API __must__ not be used unless the conditions described in [Extending Physical Device Core Functionality](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap4.html#initialization-phys-dev-extensions) are met.
> Device functionality or behavior added by a device extension to the API __must__ not be used unless that extension is supported by the device as determined by vkEnumerateDeviceExtensionProperties, and that extension is enabled in VkDeviceCreateInfo.

I would consider the `VkPhysicalDevice16BitStorageFeaturesKHR` struct to fall under "(physical) device functionality or behavior added by a device extension". However, two paragraphs before, the spec states:
> Any component of the implementation (the loader, any enabled layers, and drivers) __must__ skip over, without processing (other than reading the `sType` and `pNext` members) any extending structures in the chain not defined by core versions or extensions supported by that component.

This seems like a potential conflict in the specification, or at least unclear. The implementation is supposed to silently ignore structures it doesn't recognise, which suggests that the application __can__ include structures that require non-enabled extensions in a `pNext` chain.
