### ISSUE TITLE
VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR is not validated

### ISSUE THREAD

**Issue by danielmaciel** [KhronosGroup/Vulkan-ValidationLayers#2831]
Spec says:

VUID-vkCmdBuildAccelerationStructuresKHR-geometry-03673
The buffers from which the buffer device addresses for all of the geometry.triangles.vertexData, geometry.triangles.indexData, geometry.triangles.transformData, geometry.aabbs.data, and geometry.instances.data members of all pInfos[i].pGeometries and pInfos[i].ppGeometries are queried must have been created with the VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR usage flag

I can create buffers without that flag and the validation layer will not complain.

I expect it to complain if I don't set that flag on my buffers.

**Comment by ncesario-lunarg** [comment]
Thanks @danielmaciel, indeed there is no check for this VUID currently. Looks like this will need to be added to https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/00cc43d56498abd14a7f5dc18278e06b1ad0b5fa/layers/core_validation.cpp#L6395.
