### ISSUE TITLE
Wrong validation of VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR vs VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR

### ISSUE THREAD

**Issue by danielmaciel** [KhronosGroup/Vulkan-ValidationLayers#2832]
This validation is wrong:

Validation Error: [ VUID-vkCmdPipelineBarrier-dstAccessMask-02816 ] Object 0: handle = 0x2113620, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x69c8467d | vkCmdPipelineBarrier(): .pMemoryBarriers[0].dstAccessMask bit VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR is not supported by stage mask (VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR). The Vulkan spec states: The dstAccessMask member of each element of pMemoryBarriers must only include access flags that are supported by one or more of the pipeline stages in dstStageMask, as specified in the table of supported access types (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdPipelineBarrier-dstAccessMask-02816)

According to the spec, VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR is supported by VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR

See https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#synchronization-access-types-supported

![image](https://user-images.githubusercontent.com/2924812/119255020-c269f580-bbb9-11eb-8987-0a9b2a7dabff.png)

**Comment by jeremyg-lunarg** [comment]
This should be fixed by https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2824 once it merges.

**Comment by jeremyg-lunarg** [comment]
#2824 is now merged

**Comment by JoseEmilio-ARM** [comment]
Hi @jeremy-lunarg , I'm using the layers from SDK 1.2.182.0 which should include this fix, however I am seeing a similar issue, in my case with the combination of `VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR` and `VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT` which seems to be supported in the spec as shown above:

> VUID-vkCmdPipelineBarrier-dstAccessMask-02816: Validation Error: [ VUID-vkCmdPipelineBarrier-dstAccessMask-02816 ] Object 0: handle = 0x1dfea0ccc88, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x69c8467d | vkCmdPipelineBarrier(): .pMemoryBarriers[0].dstAccessMask bit VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR is not supported by stage mask (VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT). The Vulkan spec states: The dstAccessMask member of each element of pMemoryBarriers must only include access flags that are supported by one or more of the pipeline stages in dstStageMask, as specified in the table of supported access types (https://vulkan.lunarg.com/doc/view/1.2.182.0/windows/1.2-extensions/vkspec.html#VUID-vkCmdPipelineBarrier-dstAccessMask-02816)

**Comment by jeremyg-lunarg** [comment]
@JoseEmilio-ARM, sorry about that. It looks like this is a problem with how 03927 is written:
```
VUID-VkImageMemoryBarrier2KHR-srcAccessMask-03927
If srcAccessMask includes VK_ACCESS_2_ACCELERATION_STRUCTURE_READ_BIT_KHR, srcStageMask must include VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_BUILD_BIT_KHR, VK_PIPELINE_STAGE_2_RAY_TRACING_SHADER_BIT_KHR, or VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT_KHR
```
We are using these VUIDs to generate tables of allowed access mask / pipeline stage combinations which are used even when synchronization2 isn't enabled.  I'll file an issue with the working group about the mismatch and then this should get fixed by new code generation.

**Comment by jeremyg-lunarg** [comment]
@JoseEmilio-ARM  you might also want to check out other parts of the [spec](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#synchronization-access-types) that mention ACCELERATION_STRUCTURE_READ_BIT. I can only find text that indicates that it is used with the stages listed in VUID 03927.

> VK_ACCESS_2_ACCELERATION_STRUCTURE_READ_BIT_KHR specifies read access to an acceleration structure as part of a trace, build, or copy command, or to an acceleration structure scratch buffer as part of a build command. Such access occurs in the VK_PIPELINE_STAGE_2_RAY_TRACING_SHADER_BIT_KHR pipeline stage or VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_BUILD_BIT_KHR pipeline stage.

vkCmdBuildAccelerationStructureNV():
> Accesses to dst, src, and scratch must be synchronized with the VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR pipeline stage and an access type of VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR or VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR.

etc...  I'd *guess* that means the VUID and validation are correct and the table is wrong. I just filed a working group issue about this and I'm reopening this one so that I remember to ping you when I hear back.

**Comment by jeremyg-lunarg** [comment]
@arno-lunarg  this is another one I think you just fixed.

**Comment by arno-lunarg** [comment]
@jeremy-lunarg Yes, with https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4976 a validation error will be outputed in this case, but I think only if using `vkCmdPipelineBarrier2` (and not if using `vkCmdPipelineBarrier`? Not sure about that...)
