### ISSUE TITLE
Would validation layers be impacted by removing 'pipeline' attributes from vk.xml?

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-ValidationLayers#2834]
The Vulkan WG is hoping to remove the 'pipeline' attributes from vk.xml, and the corresponding 'Pipeline Types' column from the specification. Would this impact your use of the XML? Easiest way to tell is probably by substituting the [attached proposed vk.xml](https://github.com/KhronosGroup/VK-GL-CTS/files/6536053/vk.zip) in your build and see if it makes a difference. I believe @sfricke-samsung volunteered to do that.

**Comment by sfricke-samsung** [comment]
Took ToT (which has 1.2.179 headers) and the `vk.xml` from internal Vulkan MR 4594 and reran `python3 scripts/generate_source.py path/to/Vulkan-Headers/registry/` with it and nothing has changed confirming my confidence the VVL were not using it neither

**Comment by oddhack** [comment]
Thanks!
