### ISSUE TITLE
Validate PSOs follow maxFragmentInputComponents et. al.

### ISSUE THREAD

**Issue by darksylinc** [KhronosGroup/Vulkan-ValidationLayers#2835]
**Describe the situation in which you encountered the missing validation**
Issue description:

I [found this issue](https://gitlab.freedesktop.org/mesa/mesa/-/issues/4524) by accident:

Overflowing number of varyings passed to pixel shader results in GPU crash

The following VS and PS will cause a GPU hang when using RADV. In OpenGL it correctly refuses to link this shader citing that the 'array is too large':

```
// VS
layout( location = 0 ) in float4 inputVsPos;

layout( location = 0 ) out block
{
float4 a0;float4 a1;float4 a2;float4 a3;float4 a4;float4 a5;float4 a6;float4 a7;float4 a8;float4 a9;float4 a10;
float4 a11;float4 a12;float4 a13;float4 a14;float4 a15;float4 a16;float4 a17;float4 a18;float4 a19;float4 a20;
float4 a21;float4 a22;float4 a23;float4 a24;float4 a25;float4 a26;float4 a27;float4 a28;float4 a29;float4 a30;
float4 a31;float4 a32;float4 a33;float4 a34;float4 a35;float4 a36;float4 a37;float4 a38;float4 a39;float4 a40;
float4 a41;float4 a42;float4 a43;float4 a44;float4 a45;float4 a46;float4 a47;float4 a48;float4 a49;
} outVs;

void main()
{
	gl_Position.xyzw = inputVsPos;
	outVs.a0 = inputVsPos; outVs.a1 = inputVsPos; outVs.a2 = inputVsPos; outVs.a3 = inputVsPos; outVs.a4 = inputVsPos; outVs.a5 = inputVsPos;
	outVs.a6 = inputVsPos; outVs.a7 = inputVsPos; outVs.a8 = inputVsPos; outVs.a9 = inputVsPos; outVs.a10 = inputVsPos;
	outVs.a11 = inputVsPos; outVs.a12 = inputVsPos; outVs.a13 = inputVsPos; outVs.a14 = inputVsPos; outVs.a15 = inputVsPos;
	outVs.a16 = inputVsPos; outVs.a17 = inputVsPos; outVs.a18 = inputVsPos; outVs.a19 = inputVsPos; outVs.a20 = inputVsPos;
	outVs.a21 = inputVsPos; outVs.a22 = inputVsPos; outVs.a23 = inputVsPos; outVs.a24 = inputVsPos; outVs.a25 = inputVsPos;
	outVs.a26 = inputVsPos; outVs.a27 = inputVsPos; outVs.a28 = inputVsPos; outVs.a29 = inputVsPos; outVs.a30 = inputVsPos;
	outVs.a31 = inputVsPos; outVs.a32 = inputVsPos; outVs.a33 = inputVsPos; outVs.a34 = inputVsPos; outVs.a35 = inputVsPos;
	outVs.a36 = inputVsPos; outVs.a37 = inputVsPos; outVs.a38 = inputVsPos; outVs.a39 = inputVsPos; outVs.a40 = inputVsPos;
	outVs.a41 = inputVsPos; outVs.a42 = inputVsPos; outVs.a43 = inputVsPos; outVs.a44 = inputVsPos; outVs.a45 = inputVsPos;
	outVs.a46 = inputVsPos; outVs.a47 = inputVsPos; outVs.a48 = inputVsPos; outVs.a49 = inputVsPos;
}
```

```
// PS
layout( location = 0 ) in block
{
float4 a0;float4 a1;float4 a2;float4 a3;float4 a4;float4 a5;float4 a6;float4 a7;float4 a8;float4 a9;float4 a10;
float4 a11;float4 a12;float4 a13;float4 a14;float4 a15;float4 a16;float4 a17;float4 a18;float4 a19;float4 a20;
float4 a21;float4 a22;float4 a23;float4 a24;float4 a25;float4 a26;float4 a27;float4 a28;float4 a29;float4 a30;
float4 a31;float4 a32;float4 a33;float4 a34;float4 a35;float4 a36;float4 a37;float4 a38;float4 a39;float4 a40;
float4 a41;float4 a42;float4 a43;float4 a44;float4 a45;float4 a46;float4 a47;float4 a48;float4 a49;
} inPs;

float4 main()
{
	float4 outCol = float4(0,0,0,0);

	outCol += inPs.a0; outCol += inPs.a1; outCol += inPs.a2; outCol += inPs.a3; outCol += inPs.a4;
	outCol += inPs.a5; outCol += inPs.a6; outCol += inPs.a7; outCol += inPs.a8; outCol += inPs.a9;
	outCol += inPs.a10; outCol += inPs.a11; outCol += inPs.a12; outCol += inPs.a13; outCol += inPs.a14;
	outCol += inPs.a15; outCol += inPs.a16; outCol += inPs.a17; outCol += inPs.a18; outCol += inPs.a19;
	outCol += inPs.a20; outCol += inPs.a21; outCol += inPs.a22; outCol += inPs.a23; outCol += inPs.a24;
	outCol += inPs.a25; outCol += inPs.a26; outCol += inPs.a27; outCol += inPs.a28; outCol += inPs.a29;
	outCol += inPs.a30; outCol += inPs.a31; outCol += inPs.a32; outCol += inPs.a33; outCol += inPs.a34;
	outCol += inPs.a35; outCol += inPs.a36; outCol += inPs.a37; outCol += inPs.a38; outCol += inPs.a39;
	outCol += inPs.a40; outCol += inPs.a41; outCol += inPs.a42; outCol += inPs.a43; outCol += inPs.a44;
	outCol += inPs.a45; outCol += inPs.a46; outCol += inPs.a47; outCol += inPs.a48; outCol += inPs.a49;

	return outCol;
}
```

**Valid Usage IDs requested**

I don't think there is a VUID for this, although the [VkPhysicalDeviceLimits page](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPhysicalDeviceLimits.html) does mention maxGeometryInputComponents/maxGeometryOutputComponents/maxFragmentInputComponents/etc

Section [15.1.4. Location Assignment](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#interfaces-iointerfaces-locations) also expands on these limits.

**Additional Context**
Any additional information:

This error limit is hard to hit, and I was aware of the problem because OpenGL hit it first, so I was immediately informed by the driver what the problem was. But looking into the future, this issue could happen again and it won't be so obvious without validation.

At least on Mesa RADV, exceeding this limit causes the GPU to hang and X11 restarts (semi-equivalent of Windows' TDR), which makes the problem hard to diagnose without proper validation.

I ran into this problem by accident because a client was running into a severe edge case and asked me to extend Ogre 2.1+ to support his edge case.

**Comment by AllianceDarkSylinc** [comment]
vulkainfo dump:
[vulkaninfo.txt.zip](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/6563499/vulkaninfo.txt.zip)

Given that this issue is supposedly tested by the validator, let me check again (can't do it ASAP though) to avoid wasting time.

Perhaps I was on an old validation layer, or it wasn't enabled when I tested when I thought it was, or the layer warned but the GPU still crashed and thus I missed it.

**Comment by sfricke-samsung** [comment]
I plan to look into this very soon, so happy to give a first stab at it. Thanks for the vulkaninfo dump, will see if I can spot a bug in the current validation layers with it

**Comment by sfricke-samsung** [comment]
So @AllianceDarkSylinc I added a test in #2853 to confirm the case above is being validated.

So my bet is your GPU hangs at `vkCreateShaderModule` time? The validation is done at pipeline creation time, so if you can confirm your crash/issue is at shader module time (instead of pipeline creation time), then the issue is not the validation coverage is missing, but rather "when" it is being covered is wrong

(I know this has been an issue before, can't find specific issue number right now)

**Comment by spencer-lunarg** [comment]
Update: I looked into this, I would like to move more checks to `CreateShaderModule` time if possible

Taking notes: There is this `create_shader_module_api_state` object because it seems GPU-VA modifies the shaders between `PreCallValidateCreateShaderModule` and `PostCallRecordCreateShaderModule`
