### ISSUE TITLE
UNASSIGNED-CoreValidation-Shader-OutputNotConsumed

### ISSUE THREAD

**Issue by Desperado17** [KhronosGroup/Vulkan-ValidationLayers#2837]
Greetings, I'm new to vulkan and get the following error message:

vkDebug: Validation: 0: Validation Performance Warning: [ UNASSIGNED-CoreValidation-Shader-OutputNotConsumed ] Object 0: handle = 0x2cf63000002cf63, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x609a13b | Vertex attribute at location 3 not consumed by vertex shader

I cannot explain this as vertex attribute 3 is definitivly consumed in vertex shader:

#version 310 es
precision highp float;
precision highp int;
layout( std140, push_constant ) uniform PushConstants {
<...>
};
layout(location = 0) in vec2 a_pos;
layout(location = 7) in vec2 a_displace;
layout(location = 3) in float a_tex;
layout(location = 4) in int a_tex1;
layout(location = 0)  out vec2 v_tex;

void main()
{
    <...>
    v_tex = vec2( a_tex * u_somevariable, float ( a_tex1 ) );
}

Do I interpret the message wrong?

**Comment by Desperado17** [comment]
Nevermind, there were attributes in my description that were optimized out by the GLSL compiler.

**Comment by ncesario-lunarg** [comment]
No worries @Desperado17, glad it's resolved for you!
