### ISSUE TITLE
Image transfer ownership causes core validation layer to incorrectly update its internal per-subresource layout info cache.

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-ValidationLayers#286]
1. Let X and Y be (separate) images. X is in TRANSFER_DST layout and Y uses TRANSFER_SRC layout.
2. In cmd buffer 1:
* Do a bunch of Y->X copy ops.
* Issue an image memory barrier as per below:

![image](https://user-images.githubusercontent.com/17761066/44258880-4c6a2000-a210-11e8-9bfe-14b874dfc740.png)

Note the different queue family indices - the described problem does not repro if the two fields match.

3. In cmd buffer 2:
* Do an X->buffer copy op.
* Observe the following incorrect error being reported by core validation layer:

![image](https://user-images.githubusercontent.com/17761066/44258958-83403600-a210-11e8-972e-1d63ec296dc0.png)

This error is seen being reported with core validation layer snapshot built from this morning's source code.
The error does not reproduce if image ownership is not transferred to a different queue family.

**Comment by jzulauf-lunarg** [comment]
@DominikWitczakAMD  -- you're doing a queue family ownership release operation. Operations on the original queue family are undefined after the release.  From a validation perspective, we don't log the image layout change until the acquire (that's a bookkeeping trick to avoid doubly recording the image layout).

If command buffer 2 is submitted on the *same* queue family, this is an undefined operation after a release (AFAIK), if command buffer 2 is submitted on a *different* queue family -- the contents of the buffer are not defined without a release operation.

The specific error may be incorrect, but from your description, I think the *code* is also incorrect at the level you've described it.

**Comment by DominikWitczakAMD** [comment]
Apologies, you are indeed correct. This is an app-side issue.
