### ISSUE TITLE
[Improvement] Warn if the application sets wait/signal semaphore pointers but the respective count is zero in VkSubmitInfo

### ISSUE THREAD

**Issue by samuelig** [KhronosGroup/Vulkan-ValidationLayers#2867]
**Describe the situation in which you encountered the missing validation**
Issue description:

On CTS, we have found a tests that [was setting the wait semaphore pointer but wrongly setting its count value to zero](https://github.com/KhronosGroup/VK-GL-CTS/blob/c25238228ea42bbe9f508da1a765dbe224fb775c/external/vulkancts/modules/vulkan/synchronization/vktSynchronizationOperationSingleQueueTests.cpp#L283) (fixed already in internal gitlab repo).

Copied the code here for reference:

```
		VkSemaphoreSubmitInfoKHR		signalSemaphoreSubmitInfo =
			makeCommonSemaphoreSubmitInfo(*semaphore, 0u, VK_PIPELINE_STAGE_2_BOTTOM_OF_PIPE_BIT_KHR);
		VkSemaphoreSubmitInfoKHR		waitSemaphoreSubmitInfo =
			makeCommonSemaphoreSubmitInfo(*semaphore, 0u, VK_PIPELINE_STAGE_2_TOP_OF_PIPE_BIT_KHR);
		VkCommandBufferSubmitInfoKHR	commandBufferSubmitInfo[]
		{
			makeCommonCommandBufferSubmitInfo(cmdBuffers[WRITE]),
			makeCommonCommandBufferSubmitInfo(cmdBuffers[READ])
		};

		synchronizationWrapper->addSubmitInfo(
			0u,
			DE_NULL,
			1u,
			&commandBufferSubmitInfo[WRITE],
			1u,
			&signalSemaphoreSubmitInfo
		);
		synchronizationWrapper->addSubmitInfo(
			0u,
			&waitSemaphoreSubmitInfo,
			1u,
			&commandBufferSubmitInfo[READ],
			0u,
			DE_NULL
		);
```
It could be nice to detect that in the validation layer and print out a warning to notify the application developer that it might be doing something wrong. Similarly, we can do the same in the future for similar arguments in other Vulkan functions.

**Valid Usage IDs requested**
Please include the valid usage IDs for the checks you are requesting:

https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkSubmitInfo-pWaitSemaphores-parameter
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkSubmitInfo-pWaitDstStageMask-parameter

Or more VUIDs if we generalize it to cover similar cases in other functions.

**Additional Context**
Any additional information:

**Comment by ncesario-lunarg** [comment]
Thanks @samuelig, I'm wondering if this maybe belongs as a "best practice," as it looks like having the count == 0 with a non-null pointer _is_ valid according to the spec?

@Tony-LunarG @jeremyg-lunarg any thoughts?

**Comment by Tony-LunarG** [comment]
I'd agree with Best Practices - we try not to put warnings or things that aren't specifically VUID violations into validation.  Also, it could be valid, intentional usage if the code wants to leave the pointers in place for future use, but wants the implementation to ignore them on one particular call.

**Comment by jeremyg-lunarg** [comment]
Yeah that seems like the best approach to me too.

**Comment by ncesario-lunarg** [comment]
Thanks guys, I'll leave this open for now and aim to add it to best practices.

**Comment by samuelig** [comment]
Yeah, Best Practices seems like a right place to me. Thanks everybody!

**Comment by juan-lunarg** [comment]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5699
