### ISSUE TITLE
OpImageRead validation error: Expected Result Type to have 4 components

### ISSUE THREAD

**Issue by llyzs** [KhronosGroup/Vulkan-ValidationLayers#2871]
According to OpImageRead section in the SPIR-V spec: "Result Type must be a scalar or vector of floating-point type or integer type. It must be a scalar or vector with component type the same as Sampled Type of the OpTypeImage (unless that Sampled Type is OpTypeVoid)." which means OpImageRead can read a single scalar uint or float.

Following is a simplified sample shader, the bound image being read has format R32_UINT. OpImageRead reads scalar uint directly and it works without issue, but recently the validation requires the read must be a vector of 4 uints.

Please check if this is validation layer issue.

```
; SPIR-V
; Version: 1.3
; Generator: Khronos; 0
; Bound: 37
; Schema: 0
               OpCapability Shader
               OpCapability ImageBuffer
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %2 "main" %9 %13
               OpDecorate %9 BuiltIn VertexIndex
               OpDecorate %13 Location 0
               OpDecorate %18 DescriptorSet 3
               OpDecorate %18 Binding 1
          %3 = OpTypeVoid
          %4 = OpTypeFunction %3
          %7 = OpTypeInt 32 0
          %8 = OpTypePointer Input %7
          %9 = OpVariable %8 Input
         %10 = OpTypeFloat 32
         %11 = OpTypeVector %10 4
         %12 = OpTypePointer Output %11
         %13 = OpVariable %12 Output
         %15 = OpConstant %7 0
         %16 = OpTypeImage %7 Buffer 0 0 0 2 R32ui
         %17 = OpTypePointer UniformConstant %16
         %18 = OpVariable %17 UniformConstant
         %21 = OpConstant %7 16
         %24 = OpConstant %7 2
         %27 = OpConstant %7 1
         %32 = OpConstant %7 3
         %35 = OpTypeVector %7 4
          %2 = OpFunction %3 None %4
          %5 = OpLabel
         %14 = OpLoad %7 %9
         %19 = OpLoad %16 %18
         %20 = OpIMul %7 %14 %21
         %22 = OpIAdd %7 %20 %15
         %23 = OpShiftRightLogical %7 %22 %24
         %25 = OpImageRead %7 %19 %23
         %26 = OpIAdd %7 %23 %27
         %28 = OpImageRead %7 %19 %26
         %29 = OpIAdd %7 %23 %24
         %30 = OpImageRead %7 %19 %29
         %31 = OpIAdd %7 %23 %32
         %33 = OpImageRead %7 %19 %31
         %34 = OpCompositeConstruct %35 %25 %28 %30 %33
         %36 = OpBitcast %11 %34
               OpStore %13 %36
               OpReturn
               OpFunctionEnd

Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x55f56dd42558, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Expected Result Type to have 4 components
  %25 = OpImageRead %uint %19 %23
```

**Comment by sfricke-samsung** [comment]
This is a `spirv-val` error https://github.com/KhronosGroup/SPIRV-Tools/blob/f0c96f40c79d03e42688aae48642a4759a5e376f/source/val/validate_image.cpp#L1492

The validation layers just run `spirv-val` here (probably could be labeled better that is what is doing)

**Comment by sfricke-samsung** [comment]
So seems this is a recent change to `spirv-val` in the 1.2.62.0 SDK doesn't throw the error. Regradless, this should be moved to a SPIRV-Tools issue

**Comment by sfricke-samsung** [comment]
Sorry, this is not actually an issue

>  VUID-StandaloneSpirv-Result-04780
The Result Type operand of any OpImageRead or OpImageSparseRead instruction must be a vector of four components

This is a Vulkan restriction on top of SPIR-V and I recently added the validation in `spirv-val` (but the system to pipe the VUID through is not set up)

**Comment by ncesario-lunarg** [comment]
Thanks for the clarification @sfricke-samsung! Closing as it looks like this is not a validation layer issue.
