### ISSUE TITLE
Crash on VkRenderPassBeginInfo when and pClearValues is nullptr.

### ISSUE THREAD

**Issue by smokesugar** [KhronosGroup/Vulkan-ValidationLayers#2876]
**Issue**
When VkRenderPassBeginInfo::pClearValues is nullptr, the validation layer will throw an exception even if the load op is VK_ATTACHMENT_LOAD_OP_DONT_CARE .

**Valid Usage ID**
No validation messages posted.

**Environment:**
 - OS: Windows 10 x64
 - GPU: NVIDIA GTX 1060 3GB
 - SDK or header version if building from repo: 1.2.176.1

**Comment by ncesario-lunarg** [comment]
Thanks for the issue @smokesugar. Can you please point to where in the spec this is stated? The only thing I'm seeing is that there _should_ (_must_? The spec doesn't seem clear) be a [clear value for every attachment](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap8.html#VkRenderPassBeginInfo), but I don't see anything stating that pClearValues can be null.

**Comment by sfricke-samsung** [comment]
By chance what is your `clearValueCount` because even if you `pClearValues` of `nullptr` most layers/drivers will still loop `clearValueCount` 

granted the spec seems to be lacking the implicit VU text saying 

> If clearValueCount is not 0, pClearValues must be a valid pointer to an array of clearValueCount VkClearValue structures

**Comment by smokesugar** [comment]
I must be mistaken, I assumed the clear values were irrelevant if the load op was not VK_ATTACHMENT_LOAD_OP_CLEAR.

**Comment by ncesario-lunarg** [comment]
Going to close this for now as it's not clear to me that a change is needed for the validation layers, though perhaps some updated language in the spec might help here.
