### ISSUE TITLE
Invalid validation error reported when querying video queue family properties using vkGetPhysicalDeviceQueueFamilyProperties2KHR() 

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-ValidationLayers#2878]
Consider VkQueueFamilyProperties2 struct, to which VkVideoQueueFamilyProperties2KHR struct has been chained. The latter's videoCodecOperations field is set to 0, because we're expecting the implementation to fill the said struct with data at vkGetPhysicalDeviceQueueFamilyProperties2KHR() call time.

However, when calling vkGetPhysicalDeviceQueueFamilyProperties2KHR(), VL taken from SDK 1.2.176 report:

>VkVideoQueueFamilyProperties2KHR: value of videoCodecOperations must not be 0. The Vulkan spec states: videoCodecOperations must not be 0 (https://vulkan.lunarg.com/doc/view/1.2.176.1/windows/1.2-extensions/vkspec.html#VUID-VkVideoQueueFamilyProperties2KHR-videoCodecOperations-requiredbitmask)

I don't believe this error should be generated when passing the struct to a getter entrypoint.

**Comment by mark-lunarg** [comment]
This looks to be an implicit VUID (auto-generated from the Vulkan registry/XML) so unless there's a problem with the VVL codegen it may need to instead be addressed in the [Khronos Vulkan private repo](https://gitlab.khronos.org/vulkan/vulkan) or the [Khronos Vulkan-Docs public repo](https://github.com/KhronosGroup/Vulkan-Docs).

**Comment by ncesario-lunarg** [comment]
Yep, thanks for @mark-lunarg!

I agree this doesn't make sense for a query API like `vkGet*Properties`; though, I think the VL are technically following the "letter of the law here."

My guess is that the `returnedonly` attribute needs to be added to the `VkVideoQueueFamilyProperties2KHR` struct in [vk.xml](https://github.com/KhronosGroup/Vulkan-Docs/blob/main/xml/vk.xml):
```xml
<type category="struct" name="VkVideoQueueFamilyProperties2KHR" structextends="VkQueueFamilyProperties2">
```
_IF_ that is indeed the intended use.

**Comment by ncesario-lunarg** [comment]
Closing this for now as this looks like a spec change is needed rather than a change to the validation layers. @DominikWitczakAMD please re-open if you feel otherwise.
