### ISSUE TITLE
Vulkan-ValidationLayers doesn't check the device argument of vkCreateSwapchainKHR

### ISSUE THREAD

**Issue by Clyybber** [KhronosGroup/Vulkan-ValidationLayers#288]
It doesn't check wether the user incorrectly passes a physicalDevice for example instead of a logical device.

**Comment by jzulauf-lunarg** [comment]
@Clyybber  -- After discussion with the loader team, it is unlikely that an invalid physical device handle will ever reach the validation layers, without first crashing inside the loader when the handle is cast and used as if it was the correct type.

Vulkan-Loader [Issue 64](https://github.com/KhronosGroup/Vulkan-Loader/issues/64)  has been opened to track an enhancement request to do this validation.  The check would have a meaningful performance impact and would be optional even when implemented.

**Comment by jzulauf-lunarg** [comment]
@cnorthrop  -- just in case this was something you wanted to track w.r.t. the non-desktop loader/layers

**Comment by Clyybber** [comment]
1: No warnings/Errors as far as I remember
2: Warning and Error

>@Clyybber -- After discussion with the loader team, it is unlikely that an invalid physical device handle will ever reach the validation layers, without first crashing inside the loader when the handle is cast and used as if it was the correct type.

Hmm, yes I don't see a way to prevent this either.

**Comment by jzulauf-lunarg** [comment]
@Clyybber  -- you can follow-up on Vulkan-Loader [Issue 64](https://github.com/KhronosGroup/Vulkan-Loader/issues/64)
