### ISSUE TITLE
Core validation layer claims usubpassinput input attachment variable must not be associated with R32_UINT image view

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-ValidationLayers#289]
Consider the following FS:

```
#version 450

#extension GL_EXT_nonuniform_qualifier : require
 
layout(location = 0) flat in uint in_point_id;
  
  #if 1
      layout(set = 0, binding = 0, input_attachment_index = 0) uniform usubpassInput tested_array[];
  #endif
  
  layout(set = 1, binding = 4, std430) writeonly buffer outputBufferType
  {
      int result[];
  };
  
  void main()
  {
      uint n_invocation = in_point_id;
      int temp = 2;
  
      for (int n_array = 0; n_array < 8; n_array += 2)
      {
          if (subpassLoad(tested_array[n_array]).x != (n_array + 1) )
          {
              temp = 4;
  
              break;
          }
      }
  
      result[n_invocation] = temp;
  }
```

Input attachment binding is paired with a R32_UINT image view. However, at vkCreateGraphicsPipelines() call time, the following VU triggers:

![image](https://user-images.githubusercontent.com/17761066/44332568-a0714080-a46c-11e8-99d5-2cb187096544.png)

![image](https://user-images.githubusercontent.com/17761066/44332629-c39bf000-a46c-11e8-8e80-4b9e38be4410.png)

**Comment by jzulauf-lunarg** [comment]
Looks like VVL doesn't recognized the type in the SPIRV parser. ("oddtype" is how it formats unknown types).

@chrisforbes you have time to look at this?

**Comment by chrisforbes** [comment]
VL doesn't understand `OpTypeRuntimeArray` there. This support should have been added with  `EXT_descriptor_indexing`.

**Comment by jzulauf-lunarg** [comment]
@DominikWitczakAMD  -- possible to test versus PR above?  Thanks.

**Comment by DominikWitczakAMD** [comment]
@jzulauf-lunarg : Works like a charm now! Thanks for the swift reaction, much appreciated.

**Comment by jzulauf-lunarg** [comment]
Kudos @chrisforbes !
