### ISSUE TITLE
Housekeeping: Fold CV DRAW_DATA tracking into CB bound objects mechanism

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#29]
**Issue by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Friday May 19, 2017 at 16:57 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1788_

----

Currently we have parallel mechanisms here.

**Comment by mark-lunarg** [comment]
Index buffers also have their own scheme, outside of object_bindings *and* draw_data.
