### ISSUE TITLE
No error on recording & submitting command buffers with freed VkDeviceMemory

### ISSUE THREAD

**Issue by nyorain** [KhronosGroup/Vulkan-ValidationLayers#2900]
When destroying VkDeviceMemory, all command buffers using resources bound to that memory are moved to invalid state, as specified in section 3.3.1 of the Vulkan spec. The validation layer (tested version 1.2.170, windows) does not report an error if we continue to record or even submit a command buffer using such resources. 

The tested case: performing a vkCmdPipelineBarrier with a VkImageMemoryBarrier for an image that is bound to a freed VkDeviceMemory object. The special case here is that the image itself was kept alive and just the underlying VkDeviceMemory object was freed.

Expected behavior: The validation layer should issue an error as soon as further commands are recorded into a command buffer (including vkEndCommandBuffer) referencing resources bound to a freed VkDeviceMemory object. It should also output an error when submitting such a command buffer.

**Comment by jeremyg-lunarg** [comment]
It looks like we're not adding images or buffers into CMD_BUFFER_STATE::object_binding for barrier commands. This should be pretty easy to fix.
