### ISSUE TITLE
Error in the tracking for VUID_Core_DrawState_InvalidImageLayout

### ISSUE THREAD

**Issue by Kangz** [KhronosGroup/Vulkan-ValidationLayers#2910]
I think there's an issue in the tracking of the required image layout. CC @jeremy-lunarg since this is similar to #2793 (and is part of the same [Dawn issue](https://bugs.chromium.org/p/dawn/issues/detail?id=785), we just didn't finish fixing it previously).

**Environment:**
 - OS: macOS (doesn't matter)
 - GPU: Swiftshader
 - SDK or header version if building from repo: f12691a7fca240719ae0be8c6186cf90cca94265
 - Options enabled (synchronization, best practices, etc.): VVL with synchronization validation enabled.

Running the command below with this [Dawn commit](https://dawn-review.googlesource.com/c/dawn/+/55780) causes an incorrect (as far as I can tell) warning to be produced:

`./out/Debug/dawn_end2end_tests --gtest_filter=ShaderTests.A/Vulkan_SwiftShader_Device_Subzero --enable-backend-validation`

The invalid warning is:

> [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object 0: handle = 0x1400df470, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x4dae5635 | Submitted command buffer expects VkImage 0x40000000004[] (subresource: aspectMask 0x1 array layer 0, mip level 1) to be in layout VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL--instead, current layout is VK_IMAGE_LAYOUT_UNDEFINED.

I think it is invalid because the code uses only mip level 0 as an attachment, not mip level 1. The test is [here](https://dawn-review.googlesource.com/c/dawn/+/55780/3/src/tests/end2end/ShaderTests.cpp) and reads like Vulkan-lite with implicit zero-initialization of resources. Roughly what it does is the following:

 - Create a texture with two mip levels.
 - Make a barrier for mip level 0 going from `UNDEFINED` to `OUTPUT_ATTACHMENT_OPTIMAL`.
 - "Discard" mip level 0.
 - Make two barriers to transition mip level 0 (resp. 1) from `OUTPUT_ATTACHMENT_OPTIMAL` (resp. `UNDEFINED`) to `TRANSFER_DST_OPTIMAL`.
 - Copy from a buffer to both mips.
 - Transition mip level 0-1 from `TRANSFER_DST_OPTIMAL` to `SHADER_READ_ONLY_OPTIMAL`.
 - Run a trivial dispatch that uses a descriptor set that uses mip level 0-1.

**Comment by jeremyg-lunarg** [comment]
I can reproduce this with the dawn unit test, working on a fix.

**Comment by Kangz** [comment]
Thank you for taking the time to look at building the unittest!

**Comment by jeremyg-lunarg** [comment]
Sorry for the delay on this issue, the fix I have up right now causes problems with sync validation. I think I've figured that out now and should hopefully have a fixed fix up soon.

**Comment by Kangz** [comment]
No rush, we ignore this VVL warning for now. Once the PR is landed I'll let you know what the next issue is :) (or will let you know that everything is A-OK)
