### ISSUE TITLE
[Best Practices] Validate invalid access/layout combinations for VkImageMemoryBarrier{2KHR}

### ISSUE THREAD

**Issue by Tobski** [KhronosGroup/Vulkan-ValidationLayers#2918]
**Describe the situation in which you encountered the missing validation**
There are a number of situations in which the set of access flags in the source/destination mask make no sense with an old/new layout in an image memory barrier. While these are not invalid by the spec, it would be helpful to check that the access mask matches up with the specified layout and issue a warning if they don't match.

The following table lists the set of "expected" access flags for a given image layout - anything outside of this should issue a warning.

| Layout | "Valid" access bits |
| ------ | ------ |
| UNDEFINED | Any (can be 0) |
| GENERAL | Any (must not be 0) |
| COLOR_ATTACHMENT_OPTIMAL | COLOR_ATTACHMENT_READ_BIT<br>COLOR_ATTACHMENT_WRITE_BIT<br>COLOR_ATTACHMENT_READ_NONCOHERENT_BIT_EXT |
| DEPTH_STENCIL_ATTACHMENT_OPTIMAL | DEPTH_STENCIL_ATTACHMENT_READ_BIT<br>DEPTH_STENCIL_ATTACHMENT_WRITE_BIT |
| DEPTH_STENCIL_READ_ONLY_OPTIMAL | SHADER_READ_BIT<br>DEPTH_STENCIL_ATTACHMENT_READ_BIT |
| SHADER_READ_ONLY_OPTIMAL | INPUT_ATTACHMENT_READ_BIT<br>SHADER_READ_BIT |
| TRANSFER_SRC_OPTIMAL | TRANSFER_READ_BIT |
| TRANSFER_DST_OPTIMAL | TRANSFER_WRITE_BIT |
| PREINITIALIZED | HOST_WRITE_BIT |
| DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL | Depth Aspect:<br>SHADER_READ_BIT<br>DEPTH_STENCIL_ATTACHMENT_READ_BIT<br><br>Stencil Aspect:<br>DEPTH_STENCIL_ATTACHMENT_READ_BIT<br>DEPTH_STENCIL_ATTACHMENT_WRITE_BIT |
| DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL | Depth Aspect:<br>DEPTH_STENCIL_ATTACHMENT_READ_BIT<br>DEPTH_STENCIL_ATTACHMENT_WRITE_BIT<br><br>Stencil Aspect:<br>SHADER_READ_BIT<br>DEPTH_STENCIL_ATTACHMENT_READ_BIT |
| DEPTH_ATTACHMENT_OPTIMAL | DEPTH_STENCIL_ATTACHMENT_READ_BIT<br>DEPTH_STENCIL_ATTACHMENT_WRITE_BIT |
| DEPTH_READ_ONLY_OPTIMAL | SHADER_READ_BIT<br>DEPTH_STENCIL_ATTACHMENT_READ_BIT |
| STENCIL_ATTACHMENT_OPTIMAL | DEPTH_STENCIL_ATTACHMENT_READ_BIT<br>DEPTH_STENCIL_ATTACHMENT_WRITE_BIT |
| STENCIL_READ_ONLY_OPTIMAL | SHADER_READ_BIT<br>DEPTH_STENCIL_ATTACHMENT_READ_BIT |
| PRESENT_SRC_KHR | Must be 0 |
| SHARED_PRESENT_KHR | Any (can be 0) |
| SHADING_RATE_OPTIMAL_NV | SHADING_RATE_IMAGE_READ_BIT_NV |
| FRAGMENT_DENSITY_MAP_OPTIMAL_EXT | FRAGMENT_DENSITY_MAP_READ_BIT_EXT |

**Valid Usage IDs requested**
N/A - These are best practices only, so no VUIDs

**Comment by jeremyg-lunarg** [comment]
@Tobski, is this table from the Vulkan specification or some other document?

**Comment by Tobski** [comment]
I manually constructed it based on usage information noted in the descriptions of each [image layout](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImageLayout.html.). We could add it to the spec but it'd take some serious reworking...
