### ISSUE TITLE
Missing validation that integer varyings must be decorated with "flat" in SPIR-V.

### ISSUE THREAD

**Issue by Kangz** [KhronosGroup/Vulkan-ValidationLayers#2922]
**Describe the situation in which you encountered the missing validation**
Running some of the WebGPU CTS that use integer "varyings". Our SPIR-V was missing the Flat decoration for the variables.

**Valid Usage IDs requested**
No VUID but it is this excerpt from the Vulkan spec:

> 9.11. Interpolation Decorations
> ...
> Fragment shader inputs that are signed or unsigned integers, integer vectors, or any double-precision floating-point type must be decorated with Flat.

**Comment by sfricke-samsung** [comment]
> No VUID

It is, ` VUID-StandaloneSpirv-Flat-04744`

Also there is already a PR for this https://github.com/KhronosGroup/SPIRV-Tools/pull/4293

There is an internal GLSL/Glslang blocking it, but the logic in `spirv-val` is there handling this

**Comment by Kangz** [comment]
Thanks, feel free to close this issue.
