### ISSUE TITLE
Request for build update to header 1.2.183

### ISSUE THREAD

**Issue by sarahM0** [KhronosGroup/Vulkan-ValidationLayers#2925]
**Describe the Issue**
This layers name is changed in the new version of vulkan-headers and causes a compilation error:
from: VK_STRUCTURE_TYPE_SUBPASSS_SHADING_PIPELINE_CREATE_INFO_HUAWEI
to: VK_STRUCTURE_TYPE_SUBPASS_SHADING_PIPELINE_CREATE_INFO_HUAWEI

this is causing a compilation errors when the top of tree of all vulkan dependencies is pulled.
Please update to the new version of vulkan-headers v1.2.183

**Comment by null77** [comment]
+1 , causing compile errors when integrating with ANGLE as well.

**Comment by ncesario-lunarg** [comment]
There are some problems with updating to 1.2.183 and synchronization validation. Tentatively assigning @jeremyg-lunarg (for the synchronization issues) and @mikes-lunarg (for general header update issue) for now.

**Comment by mikes-lunarg** [comment]
@jeremyg-lunarg I've got a workaround for the header update. I'll create a separate issue with more details on the sync problem and tag you.
