### ISSUE TITLE
VK_PRESENT_MODE_FIFO_RELAXED_KHR vs UNASSIGNED-BestPractices-vkCreateSwapchainKHR-suboptimal-swapchain-image-count

### ISSUE THREAD

**Issue by nym9** [KhronosGroup/Vulkan-ValidationLayers#2927]
**Describe the Issue**
VK_PRESENT_MODE_FIFO_RELAXED_KHR doc says:
>If a vertical blanking period has already passed since the last update of the current image then the presentation engine does not wait for another vertical blanking period for the update

But while using FIFO_RELAXED with two images a warning is emitted:
>Using double buffering and vsync locks rendering to an integer fraction of the vsync rate. In turn, reducing the performance of the application if rendering is slower than vsync

Isn't there a contradiction?

**Valid Usage ID**
UNASSIGNED-BestPractices-vkCreateSwapchainKHR-suboptimal-swapchain-image-count(WARN / PERF): msgNum: 1698912437 - Validation Performance Warning: [ UNASSIGNED-BestPractices-vkCreateSwapchainKHR-suboptimal-swapchain-image-count ] Object 0: handle = 0x17f18e03b48, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x654358b5 | Warning: A Swapchain is being created with minImageCount set to 2, which means double buffering is going to be used. Using double buffering and vsync locks rendering to an integer fraction of the vsync rate. In turn, reducing the performance of the application if rendering is slower than vsync. Consider setting minImageCount to 3 to use triple buffering to maximize performance in such cases.
    Objects: 1
        [0] 0x17f18e03b48, type: 3, name: NULL

**Environment:**
 - OS: Windows 10
 - GPU: NVIDIA GeForce GTX 950
 - SDK or header version if building from repo: 1.2.176.1
 - Options enabled (synchronization, best practices, etc.): BEST_PRACTICES_EXT, SYNCHRONIZATION_VALIDATION_EXT

**Additional context**

**Comment by ziga-lunarg** [comment]
@ncesario-lunarg Does your commit already close this issue?

**Comment by ncesario-lunarg** [comment]
I think so @ziga-lunarg; not sure why this issue didn't close when that change merged.

@nym9 is this issue resolved with the latest VVL?

**Comment by nym9** [comment]
This message is still there with vulkan sdk 1.2.189.2
