### ISSUE TITLE
Warn if attachment STORE_OP_DONT_CARE is followed by LOAD_OP_LOAD

### ISSUE THREAD

**Issue by dor666** [KhronosGroup/Vulkan-ValidationLayers#293]
Issue was found in third party game. It could be traced with validation layer.

Game uses same attachment in first render pass with STORE_OP_DONT_CARE and later in another pass it tries to use it with LOAD_OP_LOAD.

On some gfx vendors it works, on some corruptions are visible.

Edit:
Validation layers could print some warning :)

**Comment by jzulauf-lunarg** [comment]
Warnings and best practices reporting is being moved to the "assistant layer" tracked by issue #24 . Added this issue to the feature request list .
