### ISSUE TITLE
No error reported when attempting to map multi-instance mem allocation to process space

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-ValidationLayers#294]
Consider the following use case:

1. vkAllocateMemory() is called with device mask set to include more than one device and with *flags* set to VK_MEMORY_ALLOCATE_DEVICE_MASK_BIT. This makes the allocation multi-instance., even if the memory comes from host-visible heap.
2. vkMapMemory() is called against the memory block.

According to one of the VUs specified for vkMapMemory, *memory* must not have been allocated with multiple instances. However, no error is reported by the validation layers.

**Comment by jzulauf-lunarg** [comment]
VUID-vkMapMemory-memory-00683

Multiinstance detection:

> If VK_MEMORY_ALLOCATE_DEVICE_MASK_BIT is not set, the number of instances allocated depends on whether VK_MEMORY_HEAP_MULTI_INSTANCE_BIT is set in the memory heap. If VK_MEMORY_HEAP_MULTI_INSTANCE_BIT is set, then memory is allocated for every physical device in the logical device (as if deviceMask has bits set for all device indices).

**Comment by jeremyk-lunarg** [comment]
In the case that VkMemoryAllocateFlagsInfo.flags has VK_MEMORY_ALLOCATE_DEVICE_MASK_BIT set, things should be rather simple.  VkMemoryAllocateFlagsInfo is linked along the pNext chain of a VkMemoryAllocateInfo structure which is referred to in the DEVICE_MEM_INFO structure defined in core_validation_types.h.  From here we can grab deviceMask from VkMemoryAllocateFlagsInfo and count the number of bits set.

In the case that VkMemoryAllocateFlagsInfo.flags does not have VK_MEMORY_ALLOCATE_DEVICE_MASK_BIT set, things become a bit more complicated.  In this case, we have to check whether VK_MEMORY_HEAP_MULTI_INSTANCE_BIT is set in the memory heap.  The VkMemoryAllocateInfo structure provides an index to the type of memory, listed in VkPhysicalDeviceMemoryProperties, it wishes to allocate which in turn provides an index to the heap memory that is of that type.  To solve this would require a method to get a VkPhysicalDeviceMemoryProperties structure.  Possible ways to do this could be storing a copy of the VkPhysicalDeviceMemoryProperties to be referred to later by the layers or making a call to vkGetPhysicalDeviceMemoryProperties during validation.
