### ISSUE TITLE
Image Operand Offset can't be used with OpImageFetch

### ISSUE THREAD

**Issue by TLaviron** [KhronosGroup/Vulkan-ValidationLayers#2942]
I am getting this vaildation error after upgrading the SDK:

Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x2ad1122c048, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: [VUID-StandaloneSpirv-Offset-04663] Image Operand Offset can only be used with OpImage*Gather operations
  %140 = OpImageFetch %v4float %127 %136 Offset|Sample %139 %int_0

I had a look at the [relevant section in the SPIR-V spec](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#_a_id_image_operands_a_image_operands), it seems that the ConstOffsets operand can only be used with OpImageGather and OpImageDrefGather, but no such restriction is listed for the Offset operand.

**Comment by sfricke-samsung** [comment]
This was added in `spirv-val` https://github.com/KhronosGroup/SPIRV-Tools/pull/4118

> I had a look at the relevant section in the SPIR-V spec,

So correct, the SPIR-V spec doesn't restrict this, but the Vulkan spec does

> VUID-StandaloneSpirv-Offset-04663
> 
> Image operand Offset must only be used with OpImage*Gather instructions

Which is where this error is coming from

**Comment by ncesario-lunarg** [comment]
Thanks for the clarification @sfricke-samsung. I'm going to close this as it looks like VVL was working as expected here.
