### ISSUE TITLE
Label (and possibly add) new image view VUIDs

### ISSUE THREAD

**Issue by sfricke-samsung** [KhronosGroup/Vulkan-ValidationLayers#2945]
**Describe the situation in which you encountered the missing validation**
Issue description:
New Image View VUID were added in 1.2.184
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2944/files?file-filters%5B%5D=.h#r664891877
Most should be done, just need proper labeling

**Valid Usage IDs requested**
Please include the valid usage IDs for the checks you are requesting:
~~VUID-VkImageViewCreateInfo-imageViewType-04969~~ (getting removed, was just VUID 01021)

#2965
~~VUID-VkImageViewCreateInfo-imageViewType-04973~~
~~VUID-VkImageViewCreateInfo-imageViewType-04974~~

#2976
~~VUID-VkImageViewCreateInfo-image-04970~~
~~VUID-VkImageViewCreateInfo-image-04971~~

VUID-VkImageViewCreateInfo-image-04972

**Additional Context**
Any additional information:
I plan to do this (so feel free to assign to me)

**Comment by ncesario-lunarg** [comment]
Thanks @sfricke-samsung!
