### ISSUE TITLE
Confusing interpretation of vkCmdDrawIndexed spec

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-ValidationLayers#2947]
**Describe the Issue**

I got the message below when attempting a `vkCmdDrawIndexed` with no index buffer bound. While it makes obvious sense that an error occurs, the message itself quotes a VUID from the spec that I would not interpret in this way. Specifically, it mentions dynamic state required by the bound `VkPipeline`.

Nothing related to an index buffer is specified when creating a pipeline, so when I think of dynamic pipeline state, I think of state that was specified up front to be dynamic. See also the [section on dynamic state](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap10.html#pipelines-dynamic-state) in the spec. An indexed draw call seems very different, and requires an index buffer because of the nature of the draw call, not because of any requirement in the pipeline. So if this VUID is supposed to be interpreted as referring to index buffers as well, then it might be better if it said so explicitly.

**Valid Usage ID**

VUID-vkCmdDrawIndexed-commandBuffer-02701(ERROR / SPEC): msgNum: -1468188274 - Validation Error: [ VUID-vkCmdDrawIndexed-commandBuffer-02701 ] Object 0: handle = 0x55b8c69acae0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xa87d398e | VkCommandBuffer 0x55b8c69acae0[]: Index buffer object not bound to this command buffer when Indexed Draw attempted. The Vulkan spec states: If the VkPipeline object bound to the pipeline bind point used by this command requires any dynamic state, that state must have been set (https://vulkan.lunarg.com/doc/view/1.2.182.0/linux/1.2-extensions/vkspec.html#VUID-vkCmdDrawIndexed-commandBuffer-02701)

**Environment:**
 - OS: Linux Mint 20.1
 - GPU: AMD Radeon RX 580
 - SDK or header version if building from repo: 1.2.182.0~rc2-1lunarg20.04-1
 - Options enabled (synchronization, best practices, etc.): Core

**Comment by ncesario-lunarg** [comment]
Thanks for the issue @Rua, my understanding is that there is no specific VUID for making sure there is an index buffer bound at `vkCmdDrawIndexed` time (I could be wrong; might be worth asking on Vulkan-Docs). However, there _is_ a VUID for checking whether or not the appropriate dynamic state has been set. It sounds like in your case there is no dynamic state set _and_ no index buffer bound; while the Vulkan spec is a bit confusing for this specific scenario, the VL attempts to give you a more relevant message, which is where the `Index buffer object not bound to this command buffer when Indexed Draw attempted` comes from (and it sounds like that is indeed what was happening here).

I'm going to close this as it's not clear to me there is a VL issue here. Please re-open if you feel a change to the validation layers should be made.
