### ISSUE TITLE
safe_VkFramebufferCreateInfo::initialize erroneously reads pAttachments

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-ValidationLayers#2953]
According to the vk spec:

> pAttachments is a pointer to an array of VkImageView handles, each of which will be used as the corresponding attachment in a render pass instance. If flags includes VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT, this parameter is ignored.

Despite this, safe_VkFramebufferCreateInfo::initialize ignores VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT and will attempt to index into and copy pAttachments based on the conditional `if (attachmentCount && in_struct->pAttachments)`, which can crash if the struct has not been zero-initialized.

**Environment:**
 - OS: Linux
 - GPU: Any
 - SDK or header version if building from repo: latest master
 - Options enabled (synchronization, best practices, etc.): default

**Comment by vuchien000** [comment]
safe_VkFramebufferCreateInfo :: khởi tạo đọc sai pAttachments # 2953

**Comment by Tony-LunarG** [comment]
Fixed in #2954

**Comment by zmike** [comment]
Thanks!

**Comment by vuchien000** [comment]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2954
