### ISSUE TITLE
"... contains flag bits that are not recognized members of VkPipelineStageFlagBits" occurs in a strange way.

### ISSUE THREAD

**Issue by Xeais** [KhronosGroup/Vulkan-ValidationLayers#2968]
### Describe the Issue
```cpp
const VkSemaphore waitSemaphores[]
{
  acquireSemaphore,
  renderer.GetChunkRenderList().GetSemaphoreGraphics(),
  renderer.GetShadowRenderList().GetSemaphoreGraphics()
};

//Code that initializes the second and third semaphore.
inline VkHandle<VkSemaphore> CreateVkSemaphore() noexcept
{
  VkSemaphore semaphore;
    
  VkSemaphoreCreateInfo createInfo {VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO};
  CheckResult(vkCreateSemaphore(vulkan.device, &createInfo, nullptr, &semaphore));
    
  return semaphore;
}

const VkPipelineStageFlags waitStage {VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT};

const VkCommandBuffer commandBuffers[]
{
  renderer.GetCommandBuffer(),
  postProcessor.GetCommandBuffer(),
  uiGraphicsContext.GetCommandBuffer()
};

const VkSubmitInfo submitInfo
{
  VK_STRUCTURE_TYPE_SUBMIT_INFO,                     
  nullptr,                                            
  static_cast<uint32_t>(ArrayLength(waitSemaphores)), //=| Hardcode the size (3) does not resolve the issue. |=\\
  waitSemaphores,                                   
  &waitStage,  //pWaitDstStageMask                                      
  static_cast<uint32_t>(ArrayLength(commandBuffers)),  
  commandBuffers,                                
  1,                                            
  &*frame.m_signalSemaphore                      
};
```
With only one semaphore (`acquireSemaphore`) there is no error, but with all three it seems to corrupt the following struct entry (`pWaitDstStageMask`) for the validation layers; C++ does not seem to have a problem with it.
### Valid Usage ID
> Validation[0]: Validation Error: [ UNASSIGNED-GeneralParameterError-UnrecognizedValue ] Object 0: handle = 0x184f1ea95c8, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xbe6eff91 | vkQueueSubmit: value of pSubmits[0].pWaitDstStageMask[1] contains flag bits that are not recognized members of VkPipelineStageFlagBits
Validation[0]: Validation Error: [ UNASSIGNED-GeneralParameterError-UnrecognizedValue ] Object 0: handle = 0x1fb71a82418, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xbe6eff91 | vkQueueSubmit: value of pSubmits[0].pWaitDstStageMask[2] contains flag bits that are not recognized members of VkPipelineStageFlagBits

### Environment:
 - OS: Windows 10
 - GPU: GTX 980M
 - SDK or header version if building from repo: **1.2.182.0**
 - Options enabled (synchronization, best practices, etc.): Nothing that should matter for this case.

### Additional context
[`VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT`](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPipelineStageFlagBits.html) is definitely a valid flag bit.

**Comment by jeremyg-lunarg** [comment]
pWaitDstStageMask needs to be an array with the same length as waitSemaphoreCount.  Try changing this:

`const VkPipelineStageFlags waitStage {VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT};
`
to this:
`const VkPipelineStageFlags waitStage[3] {VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT, VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT, VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT};
`

**Comment by Xeais** [comment]
@jeremyg-lunarg | Now that you're saying this ... yes, of course, thank you!

But the message by the validation layers is not really good. It's quite better in the specification: 
> `pWaitDstStageMask` is a pointer to an array of pipeline stages at which each corresponding semaphore wait will occur.

Yours is even better:
> `pWaitDstStageMask` needs to be an array with the same length as `waitSemaphoreCount`.

The validation layers reliably point out deviations from the specification (great job!), yet the messages that come with it range from excellent to problematic. In my opinion, the validation layers would benefit greatly from more consistency in this regard.

Nevertheless, I could/should have spotted this on my own: I could no longer see the forest for the trees.

You LunarG-people are by far the best Vulkan problem solvers I know of! It's awesome, thank you, again.

**Comment by jeremyg-lunarg** [comment]
Thanks for the kind words!   As far as the error message, the validation code cannot really tell the difference between going off the end of an 'array' like in your example, or a correctly sized array that just contains bad values. In this case I noticed that the error message was for `pSubmits[0].pWaitDstStageMask[1]  and [2]` which aren't valid memory in your code. To detect this sort of thing automatically you'd need to use something like [ASan](https://en.wikipedia.org/wiki/AddressSanitizer).  Closing this, unless you have something else.

**Comment by Xeais** [comment]
> Thanks for the kind words! As far as the error message, the validation code cannot really tell the difference between going off the end of an 'array' like in your example, or a correctly sized array that just contains bad values. In this case I noticed that the error message was for `pSubmits[0].pWaitDstStageMask[1] and [2]` which aren't valid memory in your code. To detect this sort of thing automatically you'd need to use something like [ASan](https://en.wikipedia.org/wiki/AddressSanitizer). Closing this, unless you have something else.

You're welcome!

This is just one example and yes, I am totally aware of the difficulties that can arise from more precise messages. If the work that comes with such an undertaking is out of scale, no one (I hope) will criticize you for a more general message. Though, there are possibly some cases where it can be done without too much effort?

**Comment by Xeais** [comment]
@jeremyg-lunarg | As I remember, you are the Vulkan synchronization specialist, what is ideal as I have a short, rather general, question in this regard:
```cpp
//Graphics command to release buffers:
m_allocation.ReleaseFrom(commandBuffer, QueueFamOwnershipTransf::Graphics);
//Acquire barrier:
m_allocation.PrepareForRendering(commandBuffer);
m_allocation.MarkUsed();
commandBuffer.End();

//Graphics submission with commands to release and acquire buffers:
VkHandle<VkFence> fenceGraphics {CreateVkFence()};
VkSubmitInfo graphicsSubmitInfo {VK_STRUCTURE_TYPE_SUBMIT_INFO};;
graphicsSubmitInfo.commandBufferCount = 1;
graphicsSubmitInfo.pCommandBuffers = &commandBuffer.GetVkCommandBuffer();
vulkan.queues[QUEUE_FAMILY_GRAPHICS]->Submit(1, &graphicsSubmitInfo, *fenceGraphics);
WaitForFence(*fenceGraphics);

...
```
The validation layers report the following error: "... no matching release barrier queued for execution."

Can this be caused by a lack of synchronisation of this submission (signal a semaphore here) with the next following (wait for it there)? Yes, the question is related to this issue.

**Comment by jeremyg-lunarg** [comment]
Possibly... Without a semaphore between the 2 queues, there is probably not anything to prevent the acquire barrier from executing before the release barrier, no matter which order they are submitted in. Also, the validation layer code does not record state of calls where an error is detected so with your original you could get additional errors like this one.

**Comment by Xeais** [comment]
@jeremyg-lunarg | Is there a way to synchronize this with only one submission? Performance-wise, one would be preferable.

> Without a semaphore between the 2 queues, there is probably not anything to prevent the acquire barrier from executing before the release barrier, no matter which order they are submitted in.

In this regard is single-threaded CPU-coding so much easier! 😭😉😁

**Comment by Xeais** [comment]
@jeremyg-lunarg | The question can't be that hard to answer ... 😁

**Comment by ncesario-lunarg** [comment]
> The question can't be that hard to answer

Unfortunately these questions do take time, especially as Vulkan synchronization is not exactly straightforward :) Combine that with a growing list of VVL issues, and it might take a while before we get back to this. We will get to this when we can, but you might get a much quicker answer via posting on something like the vulkan reddit or discord.

Sadly, there is only one Jeremy :cry:

**Comment by Xeais** [comment]
> Unfortunately these questions do take time, especially as Vulkan synchronization is not exactly straightforward :) Combine that with a growing list of VVL issues, and it might take a while before we get back to this.

Totally okay, I just wrote because I wasn't sure if poor me has been forgotten. 😃 
Thank you for the clarifying answer

> We will get to this when we can, but you might get a much quicker answer via posting on something like the vulkan reddit or discord.

I am not really into reddit and let's say, I made other experiences with Vulkan Discord.

> Sadly, there is only one Jeremy

In contrast to Vulkan synchronization, this problem is not hard to dispel: Just clone him a few times. If it works for sheep, it _must_ work for Jeremy. 😉😁

**Comment by jeremyg-lunarg** [comment]
Sorry, I have been distracted on a different problem the last couple of days...   If you are doing work on 2 different queues you are going to need at least 2 submissions, one on each queue.  You should be able to include the barriers and semaphore as part of the submissions that are doing the other work on those queues. The best you can probably get is something like this:

Submission on Queue 1:
* Wait for semaphore 1
*  Acquire barrier
* Do work
*  Release barrier
* Signal semaphore 2

Submission on Queue 2:
* Wait for semaphore 2
* Acquire barrier
* Do more work
* Release barrier
* Signal semaphore 1

There's a [complete example ](https://github.com/KhronosGroup/Vulkan-Samples/blob/master/samples/api/compute_nbody/compute_nbody.cpp) in Vulkan-Samples that might be clearer.
