### ISSUE TITLE
Setting VK_ICD_FILENAMES causes environment variable path test failure

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#30]
**Issue by [jeremy-lunarg](https://github.com/jeremy-lunarg) (MIGRATED)**
_Friday May 19, 2017 at 20:34 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1793_

----

If I set `VK_ICD_FILENAMES` (e.g. `/etc/vulkan/icd.d/nvidia_icd.json`), then the Environment Variable Path Test in `run_loader_tests.sh` will fail. I don't believe this is intended behavior, but I may be mistaken.

**Comment by mark-lunarg** [comment]
This issue should be migrated to the Vulkan-Loader repo.

**Comment by karl-lunarg** [comment]
Remigrated to KhronosGroup/Vulkan-Loader#11
