### ISSUE TITLE
Layer warns about swapchain having 0 images if vkGetSwapchainImagesKHR hasn't been called

### ISSUE THREAD

**Issue by ghost** [KhronosGroup/Vulkan-ValidationLayers#3012]
**Describe the Issue**

When you issue an API call, which involves checking count of swapchain's images (ex. `vkQueuePresentKHR`) before `vkGetSwapchainImagesKHR` has been called on the swapchain, the validation layer will warn about swapchain having 0 images.
<br/>
If you called `vkGetSwapchainImagesKHR` on the swapchain before without once providing a non-null `pSwapchainImages` parameter, validation layer will trigger a page fault on calls, which involve checking swapchain images (ex. `vkQueuePresentKHR`).
<br/>
**Possible reason of the bug**: internal structures of the layer are initialized on `vkGetSwapchainImagesKHR` and not on `vkCreateSwapchainKHR`, so even if valid swapchain object is passed to the layer, it doesn't have valid information about the swapchain.

**Environment:**
 - OS: Windows
 - GPU: NVidia RTX 2060
 - SDK version: 1.2.154.1

**Comment by ncesario-lunarg** [comment]
@Vironacorus is this scenario what you are referring to?
```cpp
vk::GetSwapchainImagesKHR(device(), m_swapchain, &swapchain_images_count, nullptr);
// allocate array
//vk::GetSwapchainImagesKHR(device(), m_swapchain, &swapchain_images_count, swapchain_images.data()); <- _NOT_ doing this causes the crash on QueuePresentKHR?

vk::QueuePresentKHR(m_device->m_queue, &present);
```

If so, I'm not able to reproduce this locally. Are you able to try this on a newer version of the SDK? There have been a few releases since 1.2.154.1.

**Comment by Vironacorus** [comment]
@ncesario-lunarg 
I was able to reproduce the exact same error on the newest version of the SDK. 

```c
	vkCreateSwapchainKHR(Device, &Swapchain_info, NULL, &Swapchain);

	const uint32_t Image_index = 0;
	VkPresentInfoKHR Present_info = { VK_STRUCTURE_TYPE_PRESENT_INFO_KHR };
	Present_info.pImageIndices = &Image_index;
	Present_info.pSwapchains = Swapchain;
	Present_info.swapchainCount = 1;
	vkQueuePresentKHR(Present_queue, &Present_info);
```

Bug appears even if I call `vkQueuePresentKHR` instantly after swapchain is created
