### ISSUE TITLE
crash on descriptor binding

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-ValidationLayers#3014]
Binding a descriptor set containing dynamic buffer descriptors where the buffer is null but the dynamic offset is nonzero causes a crash.

**Environment:**
 - OS: Linux
 - GPU: Any
 - SDK or header version if building from repo:  f4fb2a0b00d10942997e3ff7b93c40b1409a8b2b
 - Options enabled (synchronization, best practices, etc.): Default

This is a bit of a weird one according to spec since it doesn't seem to be explicitly covered, but based on my reading, it appears the validation for the dynamic offset should occur after determining whether the descriptor is null instead of only considering whether the descriptor may be null if the dynamic offset is zero.

**Comment by jeremyg-lunarg** [comment]
I reproduced the crash by hacking VkPositiveLayerTest.DynamicOffsetWithInactiveBinding. Will work on a separate test case and figuring out what we should do in this case, besides not crashing.
