### ISSUE TITLE
Writing to gl_Layer with invalid framebuffer layers

### ISSUE THREAD

**Issue by batcholi** [KhronosGroup/Vulkan-ValidationLayers#3019]
Issue description:
I am writing to gl_Layer from within a geometry shader to draw points in a cubemap, while my framebuffers were configured with 1 layer instead of 6. 

It was working flawlessly on an AMD GPU, but was only outputting on a single layer (0) on an NVIDIA GPU. 
Changing the framebuffer to use 6 layers fixed it on the NVIDIA. 

I think this should have given off a validation error.

**Comment by spencer-lunarg** [comment]
>  If the Layer value is less than 0 or greater than or equal to the number of layers in the framebuffer, then primitives may still be rasterized, fragment shaders may be executed, and the framebuffer values for all layers are undefined

So this is not **invalid** (undefined behavior) to write outside the Framebuffer range.

We should add this to the Best Practice to warn the user (such in this case) there might be some un-expected values
