### ISSUE TITLE
Validation layers don't check core version availbility for 1.1 functions

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-ValidationLayers#304]
In `vkGetDeviceProcAddr` the validation layers check for extensions being enabled, and return `NULL` for the corresponding functions if the extension isn't enabled. This is good, but I think it needs to be extended for 1.1 core functions - if a 1.1 context isn't available then `NULL` should be returned for functions promoted to core like `GetBufferMemoryRequirements2`.

To test this, you'll need either a 1.0 driver with `VK_KHR_get_memory_requirements_2` or you can hack the validation layers in `vk_dispatch_table_helper.h` to force `NULL` instead of `gpa(device, "vkGetBufferMemoryRequirements2");` which is what I did.

Then run cube.c with this diff:

```diff
diff --git a/cube.c b/cube_mod.c
index 8edbd65..74d44d4 100644
--- a/cube.c
+++ b/cube_mod.c
@@ -3175,6 +3175,8 @@ static void demo_init_vk(struct demo *demo) {
         free(device_extensions);
     }

+    demo->extension_names[demo->enabled_extension_count++] = VK_KHR_GET_MEMORY_REQUIREMENTS_2_EXTENSION_NAME;
+
     if (!swapchainExtFound) {
         ERR_EXIT("vkEnumerateDeviceExtensionProperties failed to find the " VK_KHR_SWAPCHAIN_EXTENSION_NAME
                  " extension.\n\nDo you have a compatible Vulkan installable client driver (ICD) installed?\n"
@@ -3241,6 +3243,8 @@ static void demo_init_vk(struct demo *demo) {
 }

 static void demo_create_device(struct demo *demo) {
+    VkBufferMemoryRequirementsInfo2 buf_req;
+    VkBufferCreateInfo buf_info;
     VkResult U_ASSERT_ONLY err;
     float queue_priorities[1] = {0.0};
     VkDeviceQueueCreateInfo queues[2];
@@ -3273,6 +3277,32 @@ static void demo_create_device(struct demo *demo) {
     }
     err = vkCreateDevice(demo->gpu, &device, NULL, &demo->device);
     assert(!err);
+
+    memset(&buf_info, 0, sizeof(buf_info));
+    buf_info.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
+    buf_info.usage = VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT;
+    buf_info.size = 1024;
+
+    memset(&buf_req, 0, sizeof(buf_req));
+    buf_req.sType = VK_STRUCTURE_TYPE_BUFFER_MEMORY_REQUIREMENTS_INFO_2;
+    vkCreateBuffer(demo->device, &buf_info, NULL, &buf_req.buffer);
+
+    PFN_vkGetBufferMemoryRequirements2KHR khr_variant =
+      (PFN_vkGetBufferMemoryRequirements2KHR)vkGetDeviceProcAddr(demo->device, "vkGetBufferMemoryRequirements2KHR");
+
+    VkMemoryRequirements2 reqs;
+    memset(&reqs, 0, sizeof(reqs));
+    reqs.sType = VK_STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2_KHR;
+
+    khr_variant(demo->device, &buf_req, &reqs);
+
+    PFN_vkGetBufferMemoryRequirements2 core_variant =
+      (PFN_vkGetBufferMemoryRequirements2)vkGetDeviceProcAddr(demo->device, "vkGetBufferMemoryRequirements2");
+
+    memset(&reqs, 0, sizeof(reqs));
+    reqs.sType = VK_STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2;
+
+    core_variant(demo->device, &buf_req, &reqs);
 }

 static void demo_init_vk_swapchain(struct demo *demo) {
```

Which will call both KHR and non-KHR variants - the non-KHR variant returns non-NULL but then eventually crashes at the end of the validation layer chain with nowhere in the driver to call forward to.

I'm not sure how this extends to instance-level functionality exactly. I tried testing with an instance function promoted to core in 1.1 like `vkGetPhysicalDeviceProperties2` but think the loader started emulating the 1.1 core function on top of the KHR function (which is probably fine and doesn't lead to crashes). Maybe it also happens version checking, I'm not actually sure.

**Comment by jzulauf-lunarg** [comment]
@lenny-lunarg -- can you review if this is correctly classified as a layers or loader issue?

**Comment by jzulauf-lunarg** [comment]
@baldurk -- should be fixed at TOT master
