### ISSUE TITLE
UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout

### ISSUE THREAD

**Issue by Desperado17** [KhronosGroup/Vulkan-ValidationLayers#3059]
This is question as I didn't find a method to submit one otherwise. Sorry.

I get a validation error of type UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout.

Is there a way to find out which command caused the error?

Regards

**Comment by sfricke-samsung** [comment]
It is a draw time error, which means it won't be detected until you call `vkQueueSubmit`

The issue is a command buffer in the submission has an image with an invalid layout

(I do agree the error message currently doesn't display the `vkQueueSubmit` like it should)

**Comment by Desperado17** [comment]
Yes, but what in the command buffer found the image in the wrong format? A drawcall that found the wrong imageLayout in the descriptor? Or something else? That would be nice to know.

**Comment by sfricke-samsung** [comment]
@Desperado17 Can you put the entire Validation Layer error message in this issue, can see if I can help decipher it for you (and if I can't, add more details to the error message)
