### ISSUE TITLE
No warning / error is reported if a dispatch / draw call is issued without assigning data to pipeline's push constant ranges beforehand.

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-ValidationLayers#306]
It's an easy catch, especially in more complex apps.

**Comment by mark-lunarg** [comment]
This VUID has been updated to:

> VUID-vkCmdDraw-None-02698
> For each push constant that is statically used by the VkPipeline bound to the pipeline bind point used by this command, a push constant value must have been set for the same pipeline bind point, with a VkPipelineLayout that is compatible for push constants, with the VkPipelineLayout used to create the current VkPipeline, as described in Pipeline Layout Compatibility
