### ISSUE TITLE
GPU-Assisted Validation on Mobile

### ISSUE THREAD

**Issue by byumjin** [KhronosGroup/Vulkan-ValidationLayers#3072]
Hi, I'm trying to use `VK_EXT_validation_features` extenstion to fix my out of bounds issues on my android device (Samsung galaxy S21). I found that `vkEnumerateInstanceExtensionProperties` only can get two debug instance extensions `VK_EXT_debug_report`, `VK_EXT_debug_utils`. (I'm using NDK r22b)

I wonder that `VK_EXT_validation_features` is included in the current available NDK or the latest `libVkLayer_khronos_validation.so`

If not, is there a way to use the extension on Android?

**Comment by mark-lunarg** [comment]
@byumjin, can you share how you queried the available instance extensions?  `VK_EXT_validation_features` in this case is an extension supported by the layer, meaning one would need to query the extensions supported specifically by `VK_LAYER_KHRONOS_validation` -- it should show up there.  If you enable the extension, your CreateInstance call should succeed and the extension functionality should be available.

**Comment by byumjin** [comment]
Hi @mark-lunarg,

I queried VK_LAYER_KHRONOS_validation layer and the debug instance extension like this.
I could check that PC platform has `VK_EXT_validation_features`, but with my Android device, it only has other debug extensions such as debug_report, debug_utils, but **not** `VK_EXT_validation_features`

```
const char *khronosValidation = "VK_LAYER_KHRONOS_validation";

	// Wanted Layers
	const char *wantedLayers[MAX_LAYERS] = {};
	size_t nlayers = 0;

	if ( Dconst_GetInt( r_deviceDebug ) >= DEBUG_LAYER_KHRONOS )
	{
		wantedLayers[nlayers++] = khronosValidation;
	}

uint32_t availableLayerCount = 0;
	VKCALL( vkEnumerateInstanceLayerProperties( &availableLayerCount, NULL ) );
	VkLayerProperties *availableLayers = (VkLayerProperties *)malloc( sizeof( VkLayerProperties ) * availableLayerCount );
	VKCALL( vkEnumerateInstanceLayerProperties( &availableLayerCount, availableLayers ) );


    uint32_t availableDebugInstanceExtensionCount = 0;
	VKCALL( vkEnumerateInstanceExtensionProperties( khronosValidation, &availableDebugInstanceExtensionCount, NULL ) );
	VkExtensionProperties *availableDebugInstanceExtensions = (VkExtensionProperties *)malloc( sizeof( VkExtensionProperties ) * availableDebugInstanceExtensionCount );
	VKCALL( vkEnumerateInstanceExtensionProperties( khronosValidation, &availableDebugInstanceExtensionCount, availableDebugInstanceExtensions ) );

    -------------------------------------


    // Collect layers to pass to instance creation
	for ( uint32_t i = 0; i < availableLayerCount; ++i )
	{
		if ( I_streq( availableLayers[i].layerName, "VK_LAYER_RENDERDOC_Capture" ) )
		{
			g_vk.renderDoc = true;
		}

		for ( uint32_t w = 0; w < nlayers; ++w )
		{
			if ( I_streq( availableLayers[i].layerName, wantedLayers[w] ) )
			{
				wantedLayers[w] = "";
				finalLayers[finalLayerCount++] = availableLayers[i].layerName;
				break;
			}
		}
	}

	VkValidationFeaturesEXT validationFeaturesExt = { VK_STRUCTURE_TYPE_VALIDATION_FEATURES_EXT };
	VkValidationFeatureEnableEXT enabledValidationFeatures[] =
	{
		VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXT,
	};
	validationFeaturesExt.enabledValidationFeatureCount = 1;
	validationFeaturesExt.pEnabledValidationFeatures = enabledValidationFeatures;

	VkInstanceCreateInfo instanceCreateInfo = {};
	instanceCreateInfo.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
	instanceCreateInfo.enabledExtensionCount = finalInstanceExtensionCount;
	instanceCreateInfo.enabledLayerCount = finalLayerCount;
	instanceCreateInfo.flags = 0;
	instanceCreateInfo.pApplicationInfo = &appInfo;
	instanceCreateInfo.pNext = &validationFeaturesExt;
	instanceCreateInfo.ppEnabledExtensionNames = finalInstanceExtensions;
	instanceCreateInfo.ppEnabledLayerNames = finalLayers;
	VKCALL( vkCreateInstance( &instanceCreateInfo, R_VK_AllocationCallbacks(), &g_vk.instance ) );
```

**Comment by byumjin** [comment]
FYI, if I force to use validationFeaturesExt even if my device can't find the `VK_EXT_validation_features`, the app prints the error below whenever it creates shaders

`[ UNASSIGNED-GPU-Assisted Validation Error.  ] Object: VK_NULL_HANDLE (Type = 15) | Detail: (Failure to instrument shader.  Proceeding with non-instrumented shader.) (0)`

**Comment by Tony-LunarG** [comment]
The extension reporting could be an issue.  We run GPU-AV tests on Android but they always assume the extension is there and enable GPU-AV.  I'll investigate.
As for your failure to instrument, are you saying that the same shader is successfully instrumented and run with GPU-AV on a deskstop setup (using what version of layers?), but you get failure to instrument running on Android?  Is anything printed before this error?
Does your app enable a descriptor indexing extension?  A buffer device address extension?  Does the shader pass glslangValidator?  Is the shader source something you can share here?

**Comment by byumjin** [comment]
> As for your failure to instrument, are you saying that the same shader is successfully instrumented and run with GPU-AV on a deskstop setup (using what version of layers?)

Yes, desktop looks fine but Android only has this issue. For desktop setup, I used `1.2.162.1` and `1.2.182.0` SDK versions and both worked. 

> but you get failure to instrument running on Android? Is anything printed before this error?

No, I couldn't see any related errors before `Failure to instrument shader` error.

> Does your app enable a descriptor indexing extension? A buffer device address extension?

No, my app does not use the features.

> Does the shader pass glslangValidator?

I use DXC to convert HLSL shaders to GLSL shaders for Vulkan platforms. At the moment, I use `-fspv-target-env=vulkan1.1` to set Vulkan target environment. But, I don't think I use glslangValidator.

> Is the shader source something you can share here?

I think it is difficult to share any shader source but, this `Failure to instrument shader` error happens on every shader on Android, It does not happen on Desktop.

**Comment by byumjin** [comment]
@Tony-LunarG, I investigated it more and checked the error message below after I used `VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT` extension.

GPU-Assisted validation requires `fragmentStoresAndAtomics` and `vertexPipelineStoresAndAtomics`. GPU-Assisted Validation disabled.

It seems like my device only support `fragmentStoresAndAtomics` but not `vertexPipelineStoresAndAtomics`.

Do you think, does it explain the current situation that the app cannot instrument shaders?

**Comment by byumjin** [comment]
I have another question, after I made the app use GPU assisted validation without `vertexPipelineStoresAndAtomics`, it seemed to instrument the shaders correctly. But, the app runs **SUPER** slowly with Vulkan Validation layers, I already disabled `VK_VALIDATION_FEATURE_DISABLE_SHADERS_EXT, VK_VALIDATION_FEATURE_DISABLE_THREAD_SAFETY_EXT, 	VK_VALIDATION_FEATURE_DISABLE_API_PARAMETERS_EXT, VK_VALIDATION_FEATURE_DISABLE_OBJECT_LIFETIMES_EXT,		VK_VALIDATION_FEATURE_DISABLE_UNIQUE_HANDLES_EXT`. But, enabling GPU assisted validation seemed to make the app slow like this.

It is enough if I can find out of bounds errors only from the validation.

Do you have any suggestion?

**Comment by Tony-LunarG** [comment]
This is a bit confusing, because the GPU-AV code checks at vkCreateDevice time for both fragmentStoresAndAtomics and vertexPipelineStoresAndAtomics and if either is not supported, GPU-AV should report:
GPU-Assisted validation requires fragmentStoresAndAtomics and vertexPipelineStoresAndAtomics.  GPU-Assisted Validation disabled.
and then no more GPU-AV functionality should be called.  This would include the code to instrument the shader.  Instrumentation should not even be attempted, let alone fail.
If you hve disabled all other validation and if you are not using descriptor indexing, and are not using buffer device address, you have turned off nearly everything that can be turned off and still perform out of bounds checking.  If you are willing to forego buffer OOB checking, you may set khronos_validation.gpuav_buffer_oob to false in a layer_validation_settings.txt file and that will turn off buffer OOB checking, leaving just checking for out-of-bounds descriptor array indexing for image/texel descriptor types.
One reason that GPU-AV may be slow is that it does a QueueWaitIdle on every QueueSubmit, which can be costly in terms of performance.  It does this because it needs to collect errors from the GPU from all of the command buffers and they need to be done executing to be able to collect the errors.

**Comment by Tony-LunarG** [comment]
#3136 should fix the visibility of the validation feature extensions.  @byumjin are you still seeing issues with GPU-AV?

**Comment by byumjin** [comment]
@Tony-LunarG thanks tony. I think it is fine to close this issue :)
