### ISSUE TITLE
VK_NV_device_generated_commands vkCreateGraphicsPipelines crash

### ISSUE THREAD

**Issue by zmarlon** [KhronosGroup/Vulkan-ValidationLayers#3091]
**Describe the Issue**
When calling vkCreateGraphicsPipelines with VK_NV_device_generated_commands structure in pNext chain, it crashes with an access violation. After disabling validation layers, everything works fine. 

My pipeline creation code:
https://pastebin.com/KpgWxPVN

**Valid Usage ID**
The application crashes at vkCreateGraphicsPipelines, so there is no Valid Usage ID

**Environment:**
 - OS: Windows 10 / Linux 
 - GPU: NVIDIA GeForce RTX 3080 
 - SDK or header version if building from repo: 1.2.182.0
 - Options enabled (synchronization, best practices, etc.):

**Additional context**

**Comment by ziga-lunarg** [comment]
I have some information on this issue that I never wrote down, creating a copy of `VkShaderModule` in `VkGraphicsShaderGroupCreateInfoNV->pStages` fixes this issue, but I'm not sure why.
