### ISSUE TITLE
Tests: make spirv assembler available

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#31]
**Issue by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Thursday May 25, 2017 at 17:20 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1817_

----

There are a number of interesting spirv cases which glslang doesn't generate, but other toolchains can be expected to. We need to be able to write some tests in spirv assembly to exercise these.

**Comment by mark-lunarg** [comment]
Validation tests now accept raw SPIRV.
