### ISSUE TITLE
Bug in "Validate creating pipeline with read-only depth/stencil"

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-ValidationLayers#3115]
A change (2eafdd8607e80b1c2477082a4d2212b74c9a7d27) to validate that pipelines don't write to depth if the layout is read-only is flakily asserting in ANGLE. For example, the following test produces a validation error once every few runs. The test itself is fine (i.e. there is no error in the Vulkan stream generated):

```bash
./angle_white_box_tests --gtest_filter=VulkanPerformanceCounterTest.ReadOnlyDepthStencilFeedbackLoopUsesSingleRenderPass/ES3_Vulkan
```

Running the test through `valgrind` didn't show anything interesting.

The above failing test does the following:

- Start render pass with `DEPTH_STENCIL_ATTACHMENT` layout + a draw call that writes to depth
- Start render pass with `READ_ONLY_DEPTH_STENCIL` layout + 6 draw calls that only do depth testing but no write
- Start render pass with `DEPTH_STENCIL_ATTACHMENT` layout + a draw call that writes to depth

The validation error happens when recording the second render pass. It almost seems like the value `pPipeline->graphicsPipelineCI.pDepthStencilState->depthWriteEnable` being tested is stale, though unclear why that is flaky.

**Comment by ShabbyX** [comment]
Could we revert this change until it's fixed? @ziga-lunarg

**Comment by ncesario-lunarg** [comment]
@ShabbyX this should be reverted with https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/592ea4ecb1c8c2838135dd46219ad50ea02ac719.

**Comment by ShabbyX** [comment]
Thank you. Let me know if you need help reproducing the issue with ANGLE.

**Comment by ziga-lunarg** [comment]
@ShabbyX Could you possibly run the linked PR with the test that failed before? I believe it should pass now.

**Comment by ShabbyX** [comment]
Ran the test a couple of times, seemed to work fine!
