### ISSUE TITLE
Add Validation for attempting to clear a renderpass attachment without VK_ATTACHMENT_LOAD_OP_CLEAR

### ISSUE THREAD

**Issue by rtryan98** [KhronosGroup/Vulkan-ValidationLayers#3123]
When beginning a renderpass and attempting to clear it via `pClearValues` the there is no validation check for the case that the renderpass itself uses `VK_ATTACHMENT_LOAD_OP_DONT_CARE` for example. Is this intended behavior? There is nothing in the specification about this being invalid but it may be a candidate for a best practice validation error.

In case such a validation check already exists, I'm also using imageless framebuffers which may be a factor here.

**Comment by sfricke-samsung** [comment]
According the spec

> pClearValues is a pointer to an array of clearValueCount VkClearValue structures that contains clear values for each attachment, if the attachment uses a loadOp value of VK_ATTACHMENT_LOAD_OP_CLEAR or if the attachment has a depth/stencil format and uses a stencilLoadOp value of VK_ATTACHMENT_LOAD_OP_CLEAR. The array is indexed by attachment number. **Only elements corresponding to cleared attachments are used. Other elements of pClearValues are ignored**.

so there is nothing invalid here, the driver should be just ignoring the `pClearValues` values

As for best practices, I guess I could see this being there as a "are you sure you intended this?" type warning

**Comment by ncesario-lunarg** [comment]
I don't have a sense of how this would effect app developers. e.g., it seems like this aspect of the spec _could_ be purposely used, but maybe not.

Thoughts @Tony-LunarG @jeremyg-lunarg @ziga-lunarg on making this a best practice warning?

**Comment by ziga-lunarg** [comment]
I don't think this can be a warning. If you have 2 attachments and first is `VK_ATTACHMENT_LOAD_OP_DONT_CARE` and the second `VK_ATTACHMENT_LOAD_OP_CLEAR`, you have to specify `clearValueCount` 2, but the first one would emit a warning with no way around it.
