### ISSUE TITLE
Core validation: No support for vkAcquireNextImage2KHR()

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-ValidationLayers#315]
Core validation layer does not intercept vkAcquireNextImage2KHR() calls. Amongst other uses, these are fundamental for AFR rendering. 

In the use case I'm seeing, this leads to invalid errors being reported when doing the following:

0. Let D be a logical device built of phys devices P0 and P1.
1. Acquire a swapchain image for physical device P1. Specify a sem S to be set upon acquisition.
2. Do a dummy cmd buffer submission with wait sem set to S.

At step 2 I'm seeing the layer report a problem with S not being set which is not true.

**Comment by tobine** [comment]
Also need a test for vkAcquireNextImage2KHR

**Comment by DominikWitczakAMD** [comment]
Thanks for the swift turn-over. I'll verify the newly added support works as expected when I get back to the office from the f2f on Monday next week.

**Comment by mark-lunarg** [comment]
Basic support has been added, and there are least some devicemask tests for AcuireNextImage2KHR.
