### ISSUE TITLE
External images with VK_SHARING_MODE_CONCURRENT false validation error?

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/Vulkan-ValidationLayers#317]
I've hit a bit of a corner case with external images created with VK_SHARING_MODE_CONCURRENT.  In process 1, the external image gets created with VK_SHARING_MODE_CONRURRENT and the VkImageCreateInfo.queueFamilyIndexCount = 2 and pQueueFamilyIndices = { 0, 1}.  The device in process 1 is created with queues from these two families.

In process 2, we import the external image.  On this process, the device was created with a single queueFamilyIndexCount, but we need to create the image with the same parameters and indicate to the driver that it's CONCURRENT.  So again the image gets created with queueFamilyIndexCount=2, and pQueueFamilyIndices = { 0, 1 }.  Validation in process 2 gives this error:

VK ERROR ParameterValidation 166:1: Object: 0x560313c15d10 | vkCreateImage: pCreateInfo->pQueueFamilyIndices[1] (= 1) is not one of the queue families given via VkDeviceQueueCreateInfo structures when the device was created. 

This seems like a solid check to be making generally, but the actual VU for vkCreateImage says:

> * If sharingMode is VK_SHARING_MODE_CONCURRENT, queueFamilyIndexCount must be greater than 1
> 
>  * If sharingMode is VK_SHARING_MODE_CONCURRENT, each element of pQueueFamilyIndices must be unique and must be less than pQueueFamilyPropertyCount returned by either vkGetPhysicalDeviceQueueFamilyProperties or vkGetPhysicalDeviceQueueFamilyProperties2 for the physicalDevice that was used to create device
> 

I don't see anywhere where it says that pQueueFamilyIndices[] must match the actual queue families the device was created for.  I therefore think this check is too aggressive.

Agree?

**Comment by danginsburg** [comment]
> So my guess would be that the correct thing to do in the process with only a single queue family would be to create the image as EXCLUSIVE in that instance. 

Actually, that's what we were doing originally, but the RADV driver enables DCC for images that have only a single queue family index.  That was causing a mismatch between the two processes. leading to a GPU VM Fault.  I'd need to go dig out the language in the spec, but talking this over with some folks I had the impression that the spec required external images to be created with the same parameters in both processes.  @BNieuwenhuizen care to comment?

**Comment by BNieuwenhuizen** [comment]
So the way I read the spec, it is just aliased images on a shared memory buffer so all creation parameters need to match, including the coherent/exclusive bits.

EXCLUSIVE could be valid, if and only if you create the image as EXCLUSIVE on both sides. I think the issue here is that within one of the processes, the COHERENT option actually gets used, so I understand not wanting it to be EXCLUSIVE.

Note that independent of this, as far as I understand (but the spec is not really clear on that this is a requirement), the app still needs to do  control transfer via barriers from/to VK_QUEUE_FAMILY_EXTERNAL_KHR, which is where I suspect the exclusive control for sharing comes in.

**Comment by danginsburg** [comment]
>  Perhaps the spec should relax the requirement for matching parameters there. It seems unreasonable to require both devices sharing an image have the same queue families enabled. If that causes conflicts for a given vendor's layout selections, the "external" flag should take precedence and force a compatible mode. 

The spec would need to also relax the requirement to have more than one queueFamilyIndex for VK_SHARING_MODE_CONCURRENT when the image is external, because for example in this case the device in the other process is created with only one queue.  Should I file a spec bug and we resolve it that way?

**Comment by BNieuwenhuizen** [comment]
Well, the validation layer diverges from the spec right now? The behavior described in the OP is valid per my reading of the spec, it is just that the validation layer is stricter than the spec which this bug is about.

TBH, not sure why we are talking about changing the spec in an incompatible way, since the way it is specified now is able to handle this case?

**Comment by danginsburg** [comment]
I do agree with @BNieuwenhuizen that the validation check here does not seem to conform to a VU in the spec so until/unless there is a spec change it seems validation should be fixed to the spec as is?  One reason this check is troublesome is that it will be visible to all SteamVR client applications.  If it was in the compositor it would be less bothersome since it is only visible internally.

**Comment by jzulauf-lunarg** [comment]
"must be unique and must be less than pQueueFamilyPropertyCount returned by either vkGetPhysicalDeviceQueueFamilyProperties or vkGetPhysicalDeviceQueueFamilyProperties2 for the physicalDevice that was used to create device" -- that is looser than the check we are using.

Notes from triage -- the queue family validation (in the parameter validation layer) is using a common utility that is overly strict in this instance *and* we currently aren't obtaining the needed state for the correct test at CreateDevice time, nor copying it at vkGetPhysicalDeviceQueueFamilyProperties[2 ]call time.

**Comment by cubanismo** [comment]
> Should I file a spec bug and we resolve it that way?

Yes, regardless of resolution, it's wroth filing a spec bug so the group can weigh in on the solution.

**Comment by mark-lunarg** [comment]
@danginsburg, looking at this again -- in the above comment, did you intend "...when the image is external."?

**Comment by jzulauf-lunarg** [comment]
@mark-lunarg -- I think my email of last night misled you.  I was just reviewing [VkDeviceQueueCreateInfo](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkDeviceQueueCreateInfo.html).

It's possible to create a device that doesn't include all the queue families available.  It think we are validating against the queue families the device was created with as opposed to the queue families the *physical device* supports. That would create a false error, and that's what needs correcting.

**Comment by mark-lunarg** [comment]
@jzulauf-lunarg, thank you very much for setting me straight!  Will try to get to this shortly.
