### ISSUE TITLE
Make "ExpectSuccess" default testing behavior

### ISSUE THREAD

**Issue by ncesario-lunarg** [KhronosGroup/Vulkan-ValidationLayers#3177]
#3154 highlights that a test can "succeed" despite previous failures (e.g., failures "ignored" during test setup). Update the testing framework to "expect success" by default. Ideally this would only involve changing `ErrorMonitor` and not having to refactor a large number of tests.

**Comment by spencer-lunarg** [comment]
@ncesario-lunarg to my knowledge the `default` has been successfully changed and this can be closed, right?

**Comment by ncesario-lunarg** [comment]
Yes, I think this was left open as there were still some "test gremlins" left behind, but I agree this should be closed now.
