### ISSUE TITLE
request: more detailed error messages for image layout validation

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#32]
**Issue by [TiemoJung](https://github.com/TiemoJung) (MIGRATED)**
_Monday Jun 12, 2017 at 17:28 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1860_

----

Hi,

while i was debugging our changes to our image state tracking system, i had a hard time figuring out which image mipmap level and/or array layer was not it the expected state, as the error message only lists the image aspect (as number, the name of that flag instead would be nice and consistent with the rest) and the current layout and the source layout of the barrier.
It would be helpful to add which mip levels and array layers are affected and may be the index of the barrier array passed to the barrier call.

**Comment by mark-lunarg** [comment]
Bundling this in with issue #466.
