### ISSUE TITLE
Mixed-up version numbers in API version error

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-ValidationLayers#3205]
**Describe the Issue**
I'm calling `vkGetPhysicalDeviceFeatures2` on a physical device that supports only Vulkan 1.0. It produces this error, which as such seems correct, but the version numbers in the message are mixed up. `pApplicationInfo.apiVersion` is set to 1.1 in the application, not 1.0.2, which is the physical device version. As it reads now, the message makes no sense.

**Valid Usage ID**
> UNASSIGNED-API-Version-Violation(ERROR / SPEC): msgNum: -996803404 - Validation Error: [ UNASSIGNED-API-Version-Violation ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xc495fcb4 | Attemped to call vkGetPhysicalDeviceFeatures2() with an effective API version of 1.1.0 (0x00401000), which is the minimum of version requested in pApplicationInfo (1.0.2 (0x00400002)) and supported by this physical device (1.0.2 (0x00400002)), but this API was not promoted until version 1.1.0 (0x00401000).
>    Objects: 1
>        [0] 0, type: 1, name: NULL

**Environment:**
 - OS: Linux Mint 20.2
 - GPU: llvmpipe
 - SDK or header version if building from repo: 1.2.182.0~rc2-1lunarg20.04-1
 - Options enabled (synchronization, best practices, etc.): Core, stateless parameter

**Comment by ncesario-lunarg** [comment]
Thanks for finding this!
