### ISSUE TITLE
Should VUID-vkBindBufferMemory-memory-01035 be skipped for host alloc-backed mem allocations?

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-ValidationLayers#3207]
Let B be a Vulkan buffer. When B is created, its create info struct chained has a VkExternalMemoryBufferCreateInfo 
 structure chained, whose handleTypes member is set to VK_EXTERNAL_MEMORY_HANDLE_TYPE_HOST_ALLOCATION_BIT_EXT.

Let M be a Vulkan memory allocation. At creation time, the corresponding VkMemoryAllocateInfo struct has VkExternalMemoryBufferCreateInfo struct chained as per spec requirements.

Now, when we bind M to B using vkBindBufferMemory(), validation layers generate the following error:

```
Validation Error: [ VUID-vkBindBufferMemory-memory-01035 ]
Object 0: handle = 0x4a0533000000002f,
type = VK_OBJECT_TYPE_DEVICE_MEMORY;
MessageID = 0x1dc7f8e6

vkBindBufferMemory()(): MemoryRequirements->memoryTypeBits (0x0) for this object type
are not compatible with the memory type (0x1) of VkDeviceMemory 0x4a0533000000002f[].
The Vulkan spec states: memory must have been allocated using one of the memory types
allowed in the memoryTypeBits member of the VkMemoryRequirements structure returned
from a call to vkGetBufferMemoryRequirements with buffer 

(https://vulkan.lunarg.com/doc/view/1.2.176.1/windows/1.2-extensions/vkspec.html#VUID-vkBindBufferMemory-memory-01035)
```

I believe this check should be skipped for host alloc-backed memory allocations, because the concept of memory types is not applicable in this context.

**Comment by sfricke-samsung** [comment]
regardless if we all agree that host alloc memory don't have a memory type to check, there will need to be a spec fix as well for that VUID

**Comment by ncesario-lunarg** [comment]
Is there a gitlab and/or Vulkan-Docs issue filed to track fixing the spec?

**Comment by DominikWitczakAMD** [comment]
> Is there a gitlab and/or Vulkan-Docs issue filed to track fixing the spec?

No, sorry, I haven't had time to look into this

**Comment by DominikWitczakAMD** [comment]
Looks like we have a driver bug that caused our internal test framework to do "stuff" it technically shouldn't be doing as per spec language, which led to VL error reports. No need for the VL change. @ncesario-lunarg : thanks for your hard work on this!

**Comment by ncesario-lunarg** [comment]
👍 @DominikWitczakAMD 

To be clear, #3321 should be closed, and the existing behavior is correct?

**Comment by DominikWitczakAMD** [comment]
Apologies if I had been unclear. We can safely close #3321.
