### ISSUE TITLE
Possible wrong format compatibility class for `R12X4G12X4_UNORM_2PACK16`

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-ValidationLayers#3220]
Looking at the source code of vk_format_utils.cpp I noticed that, in `kVkFormatTable`, the entry for `VK_FORMAT_R12X4G12X4_UNORM_2PACK16` marks it being in the 16-bit compatibility class. But this is a 32-bit format, as indicated by the size member, which is 4. So this may be an error?

**Comment by ncesario-lunarg** [comment]
Looks like this is related to https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2361.
