### ISSUE TITLE
Unreasonably slow GPU-Assisted validation

### ISSUE THREAD

**Issue by batcholi** [KhronosGroup/Vulkan-ValidationLayers#3223]
I am experiencing very low framerates while using GPU-Assisted validation. 
I understand that it's normal that it would slow down the execution of shaders, but I'm not sure that what I am experiencing is normal. 
In normal circumstances, GPU-Assisted features disabled, I am easily getting a stable 200 FPS. 
With GPU-Assisted features enabled, I am getting a steady 2 FPS. 
I don't think a reduction of 100x in performance is reasonable. 
It makes these features useless for me, even when only using it for debugging specific issues once in a while. 
Is a 100x performance reduction normal?

 - OS: Windows 10 and Manjaro Linux
 - GPU: Nvidia RTX 2080 and AMD RX 6900 XT
All systems experiencing the same issues

I am extensively using buffer_reference in most of my shaders... could this be the source of the problem?

**Comment by ncesario-lunarg** [comment]
Just to clarify, you are getting 200 FPS _with all features_ from `VK_LAYER_KHRONOS_validation` enabled _except_ GPU-AV, and it is only when enabling GPU-AV along with all other features from `VK_LAYER_KHRONOS_validation` you're seeing the slow down?

Aside from the "additional validation work" (which probably doesn't slow things down too much), it is my understanding that GPU-AV may (or perhaps always does) introduce some serialization into the rendering pipeline out of necessity, and that can have a pretty adverse affect on performance, so this may be expected.

FYI @Tony-LunarG for additional insight.

**Comment by Tony-LunarG** [comment]
@batcholi it is not just your application that can show massive slowdowns with GPU-AV enabled.  A few of the game traces that we use to measure validation performance also show drops to single digit FPS with GPU-AV enabled.  GPU-AV validation does a QueueWaitIdle for every QueueSubmit the application submits, which can certainly slow things down, and which I believe is probably even more of a drain on performance than the shader instrumentation code.

One thing you might try is to disable all validation aside from GPU-AV (khronos_validation.disables = VK_VALIDATION_FEATURE_DISABLE_ALL_EXT in a vk_layer_settings.txt file or VK_LAYER_DISABLES=VK_VALIDATION_FEATURE_DISABLE_ALL_EXT as an environment variable).  Neither of those will disable GPU-AV despite their name.  If you aren't worried about buffer out of bounds checking, you can probably get a small gain in performance by turning off buffer out of bounds checking (khronos_validation.gpuav_buffer_oob to false in vk_layer_settings).  You can also use the vkconfig utility to enable / disable these settings (which is probably the easiest route).

I started looking at GPU-AV performance some yesterday and saw some things that I found unexpected. I will keep looking, but it's coming up on LunarG SDK release time and it may take some time for me to get back to this.

**Comment by Tony-LunarG** [comment]
Between #4091 #4126  and #4419, performance is greatly improved, and not as unreasonably slow.  Closing this, but feel free to submit another issue if you have a workload that shows unreasonable performance
