### ISSUE TITLE
False negative for dynamic state VU's

### ISSUE THREAD

**Issue by jzulauf-lunarg** [KhronosGroup/Vulkan-ValidationLayers#326]
There are several places in the spec, for example VUID-vkCmdSetViewport-None-01221

>The bound graphics pipeline must have been created with the VK_DYNAMIC_STATE_VIEWPORT dynamic state enabled

where the dynamic state enable bits of the current pipeline must be bound.  However, due to how the command buffer is tracking the enable bits (in GLOBAL_CB_NODE::static_state) core validation will currently not produce an error when no pipeline is bound.  (which seems to be an implication of the VU).

**Comment by chrisforbes** [comment]
IIRC this was messy because the dynamic state could be set before the pipeline. If that has been reworked, then we might be able to tighten this requirement up.

**Comment by jzulauf-lunarg** [comment]
@chrisforbes  -- is there a spot where the spec allows for dynamic state to be set prior to binding a pipeline... or am I reading that snippet wrong?  Do you read that as:

"If a graphics pipeline is bound then it must have been created with the VK_DYNAMIC_STATE_VIEWPORT dynamic state enabled"

or 

"a graphics pipeline must be bound that was created with the VK_DYNAMIC_STATE_VIEWPORT dynamic state enabled"

**Comment by tobine** [comment]
@jzulauf-lunarg the second option is correct:

"a graphics pipeline must be bound that was created with the VK_DYNAMIC_STATE_VIEWPORT dynamic state enabled"

And I believe this has been tightened up from the early days when dynamic state validation was initially implemented. Key text from the Dynamic State [section](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#pipelines-dynamic-state) of the spec:

Dynamic state setting commands must not be issued for state that is not specified as dynamic in the bound pipeline object.

So, if any of the dynamic state setting commands are called w/o a pipeline being bound validation should issue an error. Also, if a pipeline is bound but it does not indicate that the dynamic state being set is dynamic, that's an error.

**Comment by mark-lunarg** [comment]
This coverage has been provided in early 2020, including tests.
