### ISSUE TITLE
Cube built for XLIB gets seg fault at exit

### ISSUE THREAD

**Issue by kvark** [KhronosGroup/Vulkan-ValidationLayers#3262]
This is a follow-up to https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1894#issuecomment-309832783

If it's invalid for an application to destroy an instance under specific circumstances, can we have a validation error for this?

More specifically, if a driver registers a callback with XLib, why can't it unregister the call back at `vkDestroySurfaceKHR`? This seems like the most natural and straightforward way to do this kind of cleanup, as opposed to assuming the whole Xlib is de-initialized before Vulkan driver is done.

**Comment by ncesario-lunarg** [comment]
> If it's invalid for an application to destroy an instance under specific circumstances

Giving the WSI section of the spec a quick look, I'm not seeing anything that addresses this. I'm not sure what/how the VVL can do anything here. e.g., I'm not familiar with the callbacks mentioned in the original issue, nor how we would determine when a driver implementation/ICD registers/un-registers a function with a WSI implementation.

@charles-lunarg are you familiar with these callbacks at all?

**Comment by ncesario-lunarg** [comment]
After a discussion with Charles (who maintains the Vulkan-Loader code), I'm fairly confident there is no way for us to detect this scenario in VVL. We can (and I believe we do with the `ObjectLifetimes` code) detect if all vulkan objects are destroyed at `vkDestroyInstance` time. Detecting whether or not a driver implementation has unregistered a callback with a WSI implementation (which happens outside of the Vulkan API AFAICT) we cannot do to the best of my knowledge.

Maybe this is something that should be brought up in Vulkan-Docs for a possible spec change w.r.t. WSI?

**Comment by kvark** [comment]
@ncesario-lunarg your examples demonstrate the use of Vulkan. By making this change, the workaround, you are giving a signal to other users that this is how they should be doing this. But I'm not seeing the actual process of determining that this is the right usage of Vulkan. Are you sure this isn't a driver bug? Did you try to report it upstream, or talk to Vulkan WG about this? I.e. if there are callbacks to unregister, why doesn't the driver unregister them at `vkDestroySurfaceKHR`.

**Comment by ncesario-lunarg** [comment]
>  By making this change

Sorry, I'm not sure what you are referring to. What change did I make?

>  But I'm not seeing the actual process of determining that this is the right usage of Vulkan.

I agree! That's why I mentioned this might be better suited for Vulkan-Docs or perhaps the khronos gitlab repo :) This is not something the VVL can validate. Moreover, we don't know _what_ the correct thing to validate would be, as the spec seems to be lacking in this area.

> Are you sure this isn't a driver bug?

I'm not. In fact, based on the information in the previous issues you referenced, I'd say that seems likely.

> Did you try to report it upstream, or talk to Vulkan WG about this?

AFAIK, this issue has not been raised with the WG in the past, but the previous issues pre-date my involvement in VVL, so I can't say that for sure. I started an issue for discussion over on Vulkan-Docs: https://github.com/KhronosGroup/Vulkan-Docs/issues/1634

**Comment by kvark** [comment]
Thank you for filing this! It's a great way to proceed.
>  By making this change

Sorry, I was referring to https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/commit/0017308648b6bf8eef10ef0ffb9470576c0c2e9e, which is done by @karl-lunarg

**Comment by ncesario-lunarg** [comment]
You're welcome :)
