### ISSUE TITLE
Confirm attachment indexing in vkCmdDraw-blendEnable-04727

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/Vulkan-ValidationLayers#3270]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/452a5f93b99f628da7eec950a451a203990cc844/layers/core_validation.cpp#L853-L871

In this code, `i` is the index of the _subpass attachment_, while `attachment` is the index of the corresponding _render pass attachment_.

On the line 862, `attachment` is used to index into `pColorBlendState->pAttachments`. The spec defines `pAttachments` as:
>  a pointer to an array of per target attachment states.

Although "target" is not a strictly-defined term in Vulkan, should this line use _subpass attachment_ index (i.e. `i`) instead?

In either case, the spec language should be clarified.

/cc @ziga-lunarg

**Comment by ziga-lunarg** [comment]
I think you are correct, subpass attachment index makes more sense with:

> corresponding element

than attachment does.

**Comment by lexaknyazev** [comment]
I asked for the spec clarification in https://gitlab.khronos.org/vulkan/vulkan/-/issues/2814.

FWIW, the older `VkGraphicsPipelineCreateInfo-blendEnable-04717` validation seems to use subpass-aligned index here:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/81a0c6b6d2e7cf21e1024c16e56e226939f5968a/layers/core_validation.cpp#L1226

**Comment by ziga-lunarg** [comment]
Thanks! I'll wait for the answer.
