### ISSUE TITLE
Validation for undereferenceable pointers

### ISSUE THREAD

**Issue by martty** [KhronosGroup/Vulkan-ValidationLayers#3278]
Currently, there is no validation for undereferenceable pointers - if the validation layer does dereference them, there is a crash inside the validation layer. This is often unhelpful (example found in the Vulkan discord):

![image](https://user-images.githubusercontent.com/395730/132990204-f4d2db8c-0748-4c64-aa64-f79ab4f901f4.png)
Although there are debug symbols (on Windows), there is no source packaged in the SDK, so one would have to obtain the correct commit and debug to find out that the `pNext` field was uninitialized, and `current` refers to that `pNext` and was the cause of that crash. I think that an uninitialized `pNext` is an extremely common mistake, and the layers are not very helpful in diagnosing this.

If the validation layer does not dereference the pointer in question, then it will crash inside the driver, which is even more troublesome to diagnose.

It could be possible to validate pointers for readability and writability, which would turns these crashes into diagnosis. For example, it is possible to attempt the read or write, then recover from the associated fault in a platform-specific manner and then report this to the user, possibly crashing afterwards still. Of course there is some associated cost of doing so, but it might be worth it (perhaps behind a flag).

cc @nanokatze

**Comment by ncesario-lunarg** [comment]
Thank you for the issue @martty. This is now tracked under https://github.com/KhronosGroup/Vulkan-ValidationLayers/projects/4#card-68681483.

While this sort of thing would be great to have, it will take a significant amount of time to investigate and then implement a solution, which unfortunately will likely not get finished in the short term.
