### ISSUE TITLE
CoreValidation-Shader-InterfaceTypeMismatch failures with structs

### ISSUE THREAD

**Issue by cnorthrop** [KhronosGroup/Vulkan-ValidationLayers#3279]
We're rolling in the latest validation layers for the ANGLE project.  A number of tests are triggering validation errors like the following:
> [ UNASSIGNED-CoreValidation-Shader-InterfaceTypeMismatch ] Validation Error: [ UNASSIGNED-CoreValidation-Shader-InterfaceTypeMismatch ] Object 0: handle = 0x470000000047, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0xb6cf33fe | Type mismatch on location 1.0: 'ptr to output struct of (vec4 of float32)' vs 'ptr to input struct of (vec4 of float32)'

From the output, it looks like the types match.

You can see the list of tests failing over here:
https://bugs.chromium.org/p/angleproject/issues/detail?id=6382

They are all struct related.  It might be that https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/8346fe841e59fce7f39f46cff81011be6d969933 does not handle structs correctly?

I can confirm that reverting that commit clears up the validation error.

@ziga-lunarg Would it be possible to revert this CL so we can continue to roll the validation layers?

If you need an example to work through, you can run ANGLE's end2end tests.  Let me know if you need help getting them running.  Example GLSL shader combination here:
https://source.chromium.org/chromium/chromium/src/+/main:third_party/angle/src/tests/gl_tests/GLSLTest.cpp;l=6292

**Comment by ziga-lunarg** [comment]
I already have a PR for this here #3264 

Can you verify if it fixes all your false errors?

**Comment by cnorthrop** [comment]
Yeah, those tests are cleared up with your fixes.

**Comment by ziga-lunarg** [comment]
Thanks for confirming @cnorthrop !
