### ISSUE TITLE
Lable runtime SPIR-V validation

### ISSUE THREAD

**Issue by sfricke-samsung** [KhronosGroup/Vulkan-ValidationLayers#3288]
**Describe the situation in which you encountered the missing validation**
Issue description:

Tracking issue to label first, then add any Runtime SPIR-V validation VUIDs that were added in the 1.2.192 headers

I plan to do the initial pass of labeling and will list all the missing VUIDs here after

**Valid Usage IDs requested**
Please include the valid usage IDs for the checks you are requesting:

`VUID-RuntimeSpirv-*`

**UPDATE:** The following are left to add

- [ ] VUID-RuntimeSpirv-NonUniform-06274
- [ ] VUID-RuntimeSpirv-DescriptorSet-06323

**Additional Context**
Any additional information:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3287/files?file-filters%5B%5D=.cpp&file-filters%5B%5D=.h&file-filters%5B%5D=.json#r709542472

**Comment by ncesario-lunarg** [comment]
@sfricke-samsung I'll go ahead and assign this to you for now if you're doing the initial work. If that changes, just let me know and we'll re-shuffle.

**Comment by sfricke-samsung** [comment]
After going through the following VUIDs are still not labeled

----

Redundant and getting removed from spec:

- VK_KHR_16bit_storage
  - VUID-RuntimeSpirv-uniformAndStorageBuffer16BitAccess-06332
  - VUID-RuntimeSpirv-storageBuffer16BitAccess-06331
  - VUID-RuntimeSpirv-storageInputOutput16-06334
  - VUID-RuntimeSpirv-storagePushConstant16-06333
- VK_KHR_8bit_storage
  - VUID-RuntimeSpirv-uniformAndStorageBuffer8BitAccess-06329
  - VUID-RuntimeSpirv-storageBuffer8BitAccess-06328
  - VUID-RuntimeSpirv-storagePushConstant8-06330
- VK_KHR_workgroup_memory_explicit_layout
  - VUID-RuntimeSpirv-workgroupMemoryExplicitLayout16BitAccess-06375
  - VUID-RuntimeSpirv-workgroupMemoryExplicitLayout8BitAccess-06374
- Capability checker should catch all of these
  - VUID-RuntimeSpirv-BuiltIn-06271

----

[Being discussed in WG](https://gitlab.khronos.org/vulkan/vulkan/-/issues/2408)

- VUID-RuntimeSpirv-OpTypeRuntimeArray-06273
- VUID-RuntimeSpirv-NonUniform-06274

----

Still looking into which checks we have are part of this VUID

- VUID-RuntimeSpirv-DescriptorSet-06323

**Comment by spencer-lunarg** [comment]
The remain two VUs need spec clarification
-  VUID-RuntimeSpirv-DescriptorSet-06323 (about to try and break this VU up more)
-  VUID-RuntimeSpirv-NonUniform-06274 (https://gitlab.khronos.org/vulkan/vulkan/-/issues/3291)
