### ISSUE TITLE
Validation layers don't catch deleted image views in framebuffer

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-ValidationLayers#329]
If a framebuffer references some image views which are deleted, the validation layers crash. For me at least in this code because `view_state == NULL`, but other places will maybe fail if that is fixed:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/fc819201d66625159a66f128abbe3be772e46cb0/layers/buffer_validation.cpp#L329-L337

I ran into this because I cached a framebuffer pointing at the backbuffer, but recreated the underlying image views upon resize.

**Comment by karl-lunarg** [comment]
I think that @baldurk is correct.  We can replace the assert in the code snippet with a log_msg, but the layer crashes later in CmdBeginRenderPass when it tries to track the binding of the deleted image view.
