### ISSUE TITLE
SC: correctly assign locations in complex cases

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#33]
**Issue by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Tuesday Jun 13, 2017 at 21:59 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1871_

----

Spec says:

>The layout of a structure type used as an Input or Output depends on whether it is also a Block (i.e. has a Block decoration).
>
>If it is a not a Block, then the structure type must have a Location decoration. Its members are assigned consecutive locations in their declaration order, with the first member assigned to the location specified for the structure type. The members, and their nested types, must not themselves have Location decorations.
>
>If the structure type is a Block but without a Location, then each of its members must have a Location decoration. If it is a Block with a Location decoration, then its members are assigned consecutive locations in declaration order, starting from the first member which is initially assigned the location specified for the Block. Any member with its own Location decoration is assigned that location. Each remaining member is assigned the location after the immediately preceding member in declaration order.
>
>The locations consumed by block and structure members are determined by applying the rules above in a depth-first traversal of the instantiated members as though the structure or block member were declared as an input or output variable of the same type.

We're not quite doing this -- glslang doesn't generate all of these cases.

**Comment by mark-lunarg** [comment]
@jeremy-lunarg, 3 years on, it's my impression that we are handling this correctly -- is there still work to do here?
