### ISSUE TITLE
Weird VUID vkCmdBindDescriptorSets-pDescriptorSets-01979

### ISSUE THREAD

**Issue by Cvostr** [KhronosGroup/Vulkan-ValidationLayers#3302]
**Describe the Issue**
Issue description.
Hello everyone, after upgrading SDK to 1.2.182 i noticed new validation errors in my project, that i handn't seen before. 
this VUID (01979) explains me, that buffer size must be greater than buffer's range, bound to VkDescriptorSet plus my dynamic offset. So if I bound the whole uniform buffer (65535 bytes, typically), I can't use dynamic offsets with this descriptor anymore?
The second form of VUID-01979 says that, if i bound buffer with range (VK_WHOLE_BUFFER) I can't use pDynamicOffsets. It should be set to zero. Im totally confused. New version of validation layers forbids me using dynamic offsets with whole bound buffer? I should avoid using dynamic uniforms and create a lot of descriptor sets instead? I think, thats an issue and this new restriction is useless and weird. Two typically forms of VUID-01979 presented below.

**Valid Usage ID**
 [ VUID-vkCmdBindDescriptorSets-pDescriptorSets-01979 ] Object 0: handle = 0x28905de8df8, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0x5607140000000354, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; Object 2: handle = 0x95a125000000001a, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0xa159a763 | vkCmdBindDescriptorSets(): pDynamicOffsets[0] is 0x6800 which when added to the buffer descriptor's range (0x6a00) is greater than the size of the buffer (0x6a00) in descriptorSet #0 binding #1 descriptor[0]. The Vulkan spec states: For each dynamic uniform or storage buffer binding in pDescriptorSets, the sum of the effective offset, as defined above, and the range of the binding must be less than or equal to the size of the buffer (https://vulkan.lunarg.com/doc/view/1.2.189.0/windows/1.2-extensions/vkspec.html#VUID-vkCmdBindDescriptorSets-pDescriptorSets-01979)

Validation Error: [ VUID-vkCmdBindDescriptorSets-pDescriptorSets-01979 ] Object 0: handle = 0x7ffe368a1ea8, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0x2e237000001b59c, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; Object 2: handle = 0x1285ab0000012cb2, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0xa159a763 | vkCmdBindDescriptorSets(): pDynamicOffsets[0] is 0x5700, but must be zero since the buffer descriptor's range is VK_WHOLE_SIZE in descriptorSet #0 binding #0 descriptor[0]. The Vulkan spec states: For each dynamic uniform or storage buffer binding in pDescriptorSets, the sum of the effective offset, as defined above, and the range of the binding must be less than or equal to the size of the buffer

**Environment:**
 - OS: Windows 10
 - GPU: GTX 1050
 - SDK or header version if building from repo: 1.2.182 - 189

**Additional context**

**Comment by ncesario-lunarg** [comment]
If understand correctly, you want to use a dynamic offset while using VK_WHOLE_SIZE for the bound range of the buffer?

From my understanding (which could very well be incorrect), the portion of a buffer that gets bound with dynamic offsets is:
```
[base_offset + dynamic_offset, base_offset + dynamic_offset + range)
```
and this implies
```
(base_offset + dynamic_offset + range) <= buffer_size
```
If you're using `VK_WHOLE_SIZE` as the range, then the bound portion would be:
```
[base_offset + dynamic_offset,  base_offset + dynamic_offset + (buffer_size - base_offset))
```
which boils down to `(buffer_size + dynamic_offset) <= buffer_size`, which implies `dynamic_offset` must be 0 (since it is unsigned).

Tagging @sfricke-samsung as I think he added some fixes for this in #2609.

**Comment by sfricke-samsung** [comment]
This issue seems a duplication of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2846

> if i bound buffer with range (VK_WHOLE_BUFFER) I can't use pDynamicOffsets. It should be set to zero. Im totally confused.

Yes, I explain in [the issue](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2846#issuecomment-851744837) how `VK_WHOLE_SIZE` is not a dynamic size that gets adjusted with the `pDynamicOffsets`

**Comment by Cvostr** [comment]
> If understand correctly, you want to use a dynamic offset while using VK_WHOLE_SIZE for the bound range of the buffer?
> 
> From my understanding (which could very well be incorrect), the portion of a buffer that gets bound with dynamic offsets is:
> 
> ```
> [base_offset + dynamic_offset, base_offset + dynamic_offset + range)
> ```
> 
> and this implies
> 
> ```
> (base_offset + dynamic_offset + range) <= buffer_size
> ```
> 
> If you're using `VK_WHOLE_SIZE` as the range, then the bound portion would be:
> 
> ```
> [base_offset + dynamic_offset,  base_offset + dynamic_offset + (buffer_size - base_offset))
> ```
> 
> which boils down to `(buffer_size + dynamic_offset) <= buffer_size`, which implies `dynamic_offset` must be 0 (since it is unsigned).
> 
> Tagging @sfricke-samsung as I think he added some fixes for this in #2609.



> This issue seems a duplication of #2846
> 
> > if i bound buffer with range (VK_WHOLE_BUFFER) I can't use pDynamicOffsets. It should be set to zero. Im totally confused.
> 
> Yes, I explain in [the issue](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2846#issuecomment-851744837) how `VK_WHOLE_SIZE` is not a dynamic size that gets adjusted with the `pDynamicOffsets`
> 
> edit: I also have a tracking issue to make this more clear in the Spec as well as writing a Vulkan Guide entry
> [KhronosGroup/Vulkan-Docs#1546](https://github.com/KhronosGroup/Vulkan-Docs/issues/1546)

So, is there any issue, or that VUID working good and devs have no plans to make changes?

**Comment by Cvostr** [comment]
So, is there any issue, or that VUID working good and devs have no plans to make changes?

**Comment by sfricke-samsung** [comment]
There seems to be no issue, again it might be working on most implementations, but it is still undefined behavior and can blow up in an expected situation.

To get the spec changed it would require a change in https://github.com/KhronosGroup/Vulkan-Docs as the Validation Layers are just following the wording of `VUID-vkCmdBindDescriptorSets-pDescriptorSets-01979`

**Comment by Cvostr** [comment]
Oh. But what i have to do now? to stop using dynamic offsets on whole bound buffers. 
In https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2846#issuecomment-852176902 i read that now good way to index data in buffers is push constants usage.

**Comment by ncesario-lunarg** [comment]
Thanks for the clarification @sfricke-samsung!

I'm going to close this as the VVL are operating correctly from what I can tell.

@Cvostr as for "what next," the comments in #2846 probably contain the relevant information for getting things working "within the spec" right now. And if you feel there should be a spec change, the Vulkan-Docs repo would be the place to raise an issue as @sfricke-samsung mentioned.
