### ISSUE TITLE
Vulkan-ValidationLayers uses shared_mutex when compiled as C++14

### ISSUE THREAD

**Issue by null77** [KhronosGroup/Vulkan-ValidationLayers#3323]
**Describe the Issue**
Same as #1921 reported by @randomascii 

The condition now is

```
#if _MSC_FULL_VER >= 190023918 && NTDDI_VERSION > NTDDI_WIN10_RS2
```

Defined in `vk_layer_utils.h`. Right now in Chromium / Clang / Windows / C++14 this condition is true, and `std::shared_mutex` is enabled even though it's not available.

**Comment by null77** [comment]
@jeremy-lunarg can you help fix?

**Comment by null77** [comment]
@jonahryandavis fyi

**Comment by null77** [comment]
A fix would be better I think, as long as it's in the next couple days. When you authored that CL above, what were you fixing? I don't see from the commit message what the problem was with the previous check.

**Comment by jeremyg-lunarg** [comment]
> A fix would be better I think, as long as it's in the next couple days. When you authored that CL above, what were you fixing? I don't see from the commit message what the problem was with the previous check.

At least for me it wasn't actually enabling shared_mutex on linux with -std=c++17

**Comment by null77** [comment]
Note: this is with Clang for Windows, which probably emulates the `_MSC_FULL_VER` variable, and is why you might not see this issue in your local Windows build. Presumably you'd be using the MSVC compiler.

Probably needs to be amended for that.

**Comment by jeremyg-lunarg** [comment]
Yes we're still supporting MSVC 2015 on windows and [prior to 2017 it doesn't do __cplusplus correctly](https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/). I should be able to fix the check in the next few hours.

**Comment by null77** [comment]
Sounds great! I'll test it out when you have a patch.
