### ISSUE TITLE
VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT VU not checked

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-ValidationLayers#333]
I was informed earlier today the following condition is not checked by Validation Layers:

``
“If flags contains VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT, imageType must be VK_IMAGE_TYPE_3D”.
``

Not following this requirement may have severe implications for our implementation. Can we have a check added for this VU?

**Comment by mark-lunarg** [comment]
WIP, MarkL.

**Comment by DominikWitczakAMD** [comment]
Excellent turn-over, hank you very much!
