### ISSUE TITLE
Question regarding VUID-vkCmdPipelineBarrier-pDependencies-02285 (pipeline barriers during render call)

### ISSUE THREAD

**Issue by Desperado17** [KhronosGroup/Vulkan-ValidationLayers#3341]
I have a question regarding  VUID-vkCmdPipelineBarrier-pDependencies-02285 aka "Barriers cannot be set during subpass 0 of VkRenderPass 0x61bb1e000000007b[] with no self-dependency specified."

Do I understand right that _any_ call to a vkCmdPipelineBarrier between vkCmdBeginRenderPass and vkCmdEndRenderPass will trigger this error? Or only those that affect resources already bound as attachments for the current render pass?

I have a situation where it may be necessary to load & transition new images while the render pass is composed and this would be problematic for me.

Regards

**Comment by ziga-lunarg** [comment]
The VUID 02285 says:

> If vkCmdPipelineBarrier is called within a render pass instance, the render pass must have been created with at least one VkSubpassDependency instance in VkRenderPassCreateInfo::pDependencies that expresses a dependency from the current subpass to itself, with synchronization scopes and access scopes that are all supersets of the scopes defined in this command

It's pretty clear that any `vkCmdPipelineBarrier` call will trigger the VUID.

**Comment by Desperado17** [comment]
So...can you imagine an elegant solution to solve this probiem? Currently, only the following solution comes to my mind:

Previously, I'd create a separate command buffer during image creation and submit this to the queue on its own but I assumed this would mean that I'd have to wait for the queue to finish all previous commands every time I transition an image which would cause lags, right?
My GPU offers a second queue, I could use this for all resource related commands and be independent from rendering commands.

**Comment by ziga-lunarg** [comment]
Why do you not create a VkSubpassDependency from the subpass to itself?

**Comment by Desperado17** [comment]
Is there any disadvantage in that, say, performance wise? Or for render passes / subpasses that have existing dependencies?
Do you know a link to an example?

**Comment by Desperado17** [comment]
Also, do I see right that oldLayout has to be newLayout according to 01181? Then I cannot transition at all!

**Comment by ziga-lunarg** [comment]
Looks like it. You would have to change the layout before or after render pass is active.

I do not have a link to an example, but a self-dependency just means srcSubpass is equal to dstSubpass, and the index is the subpass you will call `vkCmdPipelineBarrier()` in.

You can read more about it here: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#synchronization-pipeline-barriers-subpass-self-dependencies

**Comment by Desperado17** [comment]
Oh no I got everything sorted out. Thank you!
