### ISSUE TITLE
Validation fails incorrectly for DeviceCreate with unsupported features

### ISSUE THREAD

**Issue by gnl21** [KhronosGroup/Vulkan-ValidationLayers#335]
Trying to create a vkDevice using unsupported features is valid (if not very useful) usage, but it currently fails validation. This is triggering a significant number of validation failures when running the CTS.

**Comment by daveh-lunarg** [comment]
Agreed. The spec says that the driver will reply with VK_ERROR_FEATURE_NOT_PRESENT in this case, and there's no need for the validation layer to also complain.  PR shortly.
