### ISSUE TITLE
VUID-vkMapMemory-memory-00683 being incorrectly reported for multiple apps

### ISSUE THREAD

**Issue by Tobski** [KhronosGroup/Vulkan-ValidationLayers#3350]
**Describe the Issue**
Support for VUID-vkMapMemory-memory-00683 was added in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2084, but the conditions for the error are incorrect.

The error check in code only tests if the VK_MEMORY_HEAP_MULTI_INSTANCE_BIT flag was present on the memory type of the memory being allocated; this is allowed to be true for any memory types, even when a device group is not created - as this query is from a physical device, not a logical device (so has no knowledge of current device groups).

The error check should not be testing for this - instead it should be testing whether multiple instances are _actually_ allocated, as indicated by multiple unique values in `VkBindBufferMemoryDeviceGroupInfo::pDeviceIndices`. The bit flag is completely allowed in the memory type as long as only one instance is actually allocated.

This is causing at least some applications to suddenly start failing validation with the latest SDK due to this one issue.

**Valid Usage ID**
VUID-vkMapMemory-memory-00683

**Environment:**
 - OS: Linux
 - GPU: AMD Radeon 570 (Using AMDVLK)
 - SDK or header version if building from repo: Latest SDK
 - Options enabled (synchronization, best practices, etc.): Core Validation

**Comment by Tobski** [comment]
One of the original reports is from here: https://github.com/Traverse-Research/gpu-allocator/issues/71

**Comment by pmathia0** [comment]
I'm experiencing the same issue
**Environment:**

- OS: Windows 10 Home 21H1 19043.1237
- GPU: AMD Radeon RX5600XT, AMD Radeon SW 21.9.2
- Latest Vulkan SDK (1.2.189.2) downloaded from website
- Core Validation enabled
