### ISSUE TITLE
textureCompression* features do not need to be enabled to create images

### ISSUE THREAD

**Issue by gnl21** [KhronosGroup/Vulkan-ValidationLayers#336]
The textureCompression{ETC2,ASTC_LDR,BC} features are only informative, they don't need to be enabled to create images of those types but validation currently produces errors in this case.

(If the features are not supported on a device then individual formats may still be supported according to their FormatProperties and image creation should be allowed without the features enabled).

**Comment by daveh-lunarg** [comment]
The spec language in w.r.t. device features says (emphasis theirs) _"Features describe
functionality which is **optional** and which **must** be explicitly enabled before use."_, which certainly sounds imperative. I don't find any language related to vkCreateImage or vkCreateSwapchainKHR (the two places where validation consults the compressed feature bits) that would relax that. 

Can you provide a pointer to some language as to why these features checks should not be done?

**Comment by gnl21** [comment]
These features are slightly strange ones. The spec says, for example:
> textureCompressionETC2 specifies whether all of the ETC2 and EAC compressed texture formats
are supported. If this feature is enabled, then [features] must be supported in optimalTilingFeatures for the following formats:
> [...]
> vkGetPhysicalDeviceFormatProperties and vkGetPhysicalDeviceImageFormatProperties can be
used to check for additional supported properties of individual formats.

The point being that if the feature is not enabled (or supported) some properties may still be valid, and they can be found using the image format properties functions in the same way as for other, non-compressed formats.

Reading the last sentence of that quotation now it's not quite as clear as I thought it was, and perhaps it could be clarified. This issue arises from the CTS which is checking the properties of the compressed formats individually and successfully creating images from them, but it fails validation because these features are not enabled. (And the features can't be enabled because they're not supported, because not *all* of the relevant formats are supported).

**Comment by daveh-lunarg** [comment]
It comes down to what is meant by "all of the * formats are supported", which says nothing about having _some_ of the formats supported. I agree the last sentence is somewhat ambiguous. We've interpreted it to mean that the device feature bit indicates at least minimal support for all of the compressed formats, and that vkGetPhysicalDevice*FormatProperties() can then be used to discover any _additional_ features available for a specific compressed format. I see where this would paint you into a corner if you have some compressed support, but not enough to set the feature bit.

OTOH, if vkGetPhysicalDevice*FormatProperties() may be used to determine support for specific formats that aren't enabled/supported (in aggregate) via the corresponding feature bit, it raises the question of what is the purpose of the feature bit?

I'd like to hear some kind of definitive interpretation from the working group before changing the existing validation logic. Filtering that particular error message in the CTS test might be the best option, in the mean time?

**Comment by gnl21** [comment]
Sure, thanks. There was a clarification on this about a year ago but this seems to have been missed. I've requested a further clarification on this specific point.

Regarding the purpose of the feature bits: It's compulsory to support one whole set of texture formats (ETC2, ASTC or BC) and these features give a way of seeing which set it is without having to query a whole lot of different formats to ensure support individually.

**Comment by gnl21** [comment]
The clarification on this should be in the new spec version.

**Comment by gnl21** [comment]
I was going to upload a fix for this, but I can't trigger the errors anymore. Are the parameter validation checks for CreateImage not triggered as part of standard_validation anymore? Looking at the code I can't find any way that they would be called.

**Comment by gnl21** [comment]
My setup had got messed up and I've fixed it now. Thanks for the pointer.
