### ISSUE TITLE
Unexpected UNASSIGNED-CoreValidation-Shader-PointSizeMissing when emitting no points

### ISSUE THREAD

**Issue by rg3igalia** [KhronosGroup/Vulkan-ValidationLayers#3363]
**Describe the Issue**
In mesh shaders with the NVIDIA extension, the number of primitives that a given work group emits is controlled by the gl_PrimitiveCountNV variable. It's legal to emit no primitives at all by assigning 0 to it. When assigning 0, the shader should be allowed to not write anything to any output array, but doing so triggers UNASSIGNED-CoreValidation-Shader-PointSizeMissing if  the output primitive is points. Maybe the VUID could be changed to a warning for mesh shaders?

Note: for the future multi-vendor extension this will be even more important, as the mesh shader code is not **allowed** to write to any output array position beyond the limit specified by the dynamic count.

Example triggering the issue:
```
#version 450 
#extension GL_NV_mesh_shader : enable

layout (local_size_x=1) in; 
layout (points) out;
layout (max_vertices=1, max_primitives=1) out;

void main () {
    gl_PrimitiveCountNV = 0u; 
}
```

**Valid Usage ID**
UNASSIGNED-CoreValidation-Shader-PointSizeMissing

**Environment:**
 - OS: Linux
 - GPU: RTX 2060
 - SDK or header version if building from repo: cd72d751a1c9602b61132001e1ac147157187a8d
 - Options enabled (synchronization, best practices, etc.):

**Additional context**

**Comment by spencer-lunarg** [comment]
raised [internal issue](https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5502), I would want a spec clarification for the `PointSize` builtin

**Comment by spencer-lunarg** [comment]
@rg3igalia the Vulkan 1.3.235 spec now says

> VUID-StandaloneSpirv-MeshEXT-07728
>
> In mesh shaders using the MeshEXT or MeshNV Execution Model and the OutputPoints Execution Mode, a PointSize decorated variable must be written to

So this shader is invalid as it does need to write to a `PointSize` if using `layout (points) out;`

**Comment by rg3igalia** [comment]
Thanks for the update @spencer-lunarg.  The VK_NV_mesh_shader test can be fixed like you suggest, but the new VUID affects both MeshNV and MeshEXT. In the case of MeshEXT we can't do that. For example, see the equivalent `dEQP-VK.mesh_shader.ext.misc.no_points` test:

https://github.com/KhronosGroup/VK-GL-CTS/blob/c4fe10a0c86dc96647e9a94336150c3d7a8c656f/external/vulkancts/modules/vulkan/mesh_shader/vktMeshShaderMiscTestsEXT.cpp#L1356

In MeshEXT it's illegal to write to the output arrays in positions that go beyond the limits set by the SetMeshOutputsEXT call, so adding

```
gl_MeshVerticesEXT[0].gl_PointSize = 1.0;
```

would be illegal. I'll raise a spec issue about this.

**Comment by spencer-lunarg** [comment]
So `VUID-StandaloneSpirv-MeshEXT-07728` is something that will be implemented in `spirv-val` (which I will wait until the internal MR change is decided on), but for now, the new change in #4782 will prevent the false positive you were hitting with this issue.
