### ISSUE TITLE
Validation for VK_KHR_format_features2

### ISSUE THREAD

**Issue by llandwerlin-intel** [KhronosGroup/Vulkan-ValidationLayers#3400]
**Describe the situation in which you encountered the missing validation**
Issue description:

We need validation for the new bits of format features added in VK_KHR_format_features2

**Valid Usage IDs requested**
Please include the valid usage IDs for the checks you are requesting:

There are the following new VUs that need validation :
  * [ ] `VUID-*-OpTypeImage-06423`
  * [ ] `VUID-*-OpTypeImage-06424`
  * [ ] [Image View Format Features](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#resources-image-view-format-features) also adds valid usages for the `VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_DEPTH_COMPARISON_BIT_KHR` format feature flag.

To be updated (as pointed by @sfricke-samsung below) :
  * [ ] VUID-RuntimeSpirv-OpTypeImage-06269
  * [ ] VUID-RuntimeSpirv-OpTypeImage-06270

One tricky bit about this validation is that the validation needs to be adapted depending on whether VK_KHR_format_features2 is available on the implementation.
If it's not, the current validation code applies : https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/shader_validation.cpp
But if it's available, we need to turn that off and instead use the VkFormat of the corresponding descriptor to verify whether image load/store operations can be used without format.

**Additional Context**
Any additional information:

Some useful pointers into the spec : 
  * [Formats without shader storage format](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#formats-without-shader-storage-format)

**Comment by sfricke-samsung** [comment]
> One tricky bit about this validation is that the validation needs to be adapted depending on whether VK_KHR_format_features2 is available on the implementation.

Agree, so my opinion for this is that we already have

```cpp
enum ExtEnabled : unsigned char {
    kNotEnabled,
    kEnabledByCreateinfo,
    kEnabledByApiLevel,
};
```

and I recently (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3303) made sure everyone is calling `IsExtEnabled` so if we add a 

`kEnabledByImplementationSupport` (or something close to that name)

it would be the best way in the long run (in the case this extension would get promoted in a feature Vulkan version)

I **think** some logic would only need to be added to `InitFromDeviceCreateInfo` in `vk_extension_helper.h` to apply the change

from here, the code can just use `if (IsExtEnabled(device_extensions.vk_khr_format_feature2)) { }` like expected

**Comment by llandwerlin-intel** [comment]
Hey @sigexp : do you have any update to share on the validation support?

**Comment by ncesario-lunarg** [comment]
If it's possible to add @sigexp to the [Vulkan](https://github.com/orgs/KhronosGroup/teams/vulkan/members) group/team, I should be able to assign this properly.
