### ISSUE TITLE
Validation for `VK_DYNAMIC_STATE_COLOR_WRITE_ENABLE_EXT` on draw

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-ValidationLayers#3406]
**Describe the situation in which you encountered the missing validation**
Issue description: When a draw command is issued, there is no check to ensure that the `COLOR_WRITE_ENABLE_EXT` state has been previously set, if the pipeline requires this state. Presumably, the validity of the state (especially regarding the `attachmentCount`) is also not checked at draw time.

**Valid Usage IDs requested**
Please include the valid usage IDs for the checks you are requesting: There is no VUID for this, but the documentation of `VkDynamicState` says: "`VK_DYNAMIC_STATE_COLOR_WRITE_ENABLE_EXT` specifies that the `pColorWriteEnables` state in VkPipelineColorWriteCreateInfoEXT will be ignored and **must** be set dynamically with vkCmdSetColorWriteEnableEXT before any draw call."

**Comment by ncesario-lunarg** [comment]
This was one of my questions as well. I was going to ping Piers, but it looked someone else was the champion for that EXT?

**Comment by pdaniell-nv** [comment]
I agree it sounds like the spec is missing draw time VU for this.
