### ISSUE TITLE
Wrong validation of dstAccessMask = VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR with stageMask = VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT

### ISSUE THREAD

**Issue by httpdigest** [KhronosGroup/Vulkan-ValidationLayers#3420]
**Describe the Issue**
Issuing the following pipeline barrier results in the below error message:
```java
// insert barrier to let tracing wait for the TLAS build
vkCmdPipelineBarrier(cmdBuf,
        VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR,
        VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
        0, // <- no dependency flags
        VkMemoryBarrier
            .calloc(1, stack)
            .sType(VK_STRUCTURE_TYPE_MEMORY_BARRIER)
            .srcAccessMask(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR)
            .dstAccessMask(VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR),
        null,
        null);
```

**Valid Usage ID**
```
Validation Error: [ VUID-vkCmdPipelineBarrier-dstAccessMask-02816 ] Object 0: handle = 0x2baa4d632d8, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x69c8467d | vkCmdPipelineBarrier(): .pMemoryBarriers[0].dstAccessMask bit VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR is not supported by stage mask (VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT). The Vulkan spec states: The dstAccessMask member of each element of pMemoryBarriers must only include access flags that are supported by one or more of the pipeline stages in dstStageMask, as specified in the table of supported access types (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkCmdPipelineBarrier-dstAccessMask-02816)
```

**Environment:**
 - OS: Windows 10 x64 21H1
 - GPU: Nvidia GeForce RTX 2080 Ti
 - SDK or header version if building from repo: 1.2.189.2
 - Options enabled (synchronization, best practices, etc.): none (default after installation)

**Additional context**

According to the table https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#synchronization-access-types-supported the combination of stage `VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT` with destination access `VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR` **is supported** and with VK_KHR_ray_query this is a valid use-case.

**Comment by ziga-lunarg** [comment]
Looks like this was already fixed by:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/b4d9045703878d17f0deca6ad42f8588804aa59f#diff-ff6265e16106f281beca571129c8ba7142ddc561e0cc48584caa2e4533cd2ad8R1212

Any chance you could build from master and verify?

**Comment by ziga-lunarg** [comment]
@httpdigest You don't have to build an .msi, you can set the VK_LAYER_PATH environment variable.
But I ran a test with that barrier and it did give an error before that commit, but works after it.

**Comment by httpdigest** [comment]
Hey @ziga-lunarg I've now built the validation layers locally, and can also confirm that this validation is now issued anymore. Thanks!

**Comment by ziga-lunarg** [comment]
@httpdigest Thanks for confirming!
