### ISSUE TITLE
Validation problems with YCbCr copy compatibility

### ISSUE THREAD

**Issue by gnl21** [KhronosGroup/Vulkan-ValidationLayers#343]
Vulkan allows copying into individual planes of multiplane YCbCr image but the validation layer code is not checking for size matching correctly. It looks like the code at buffer_validation.cpp line 2262 needs to take the aspect masks into account.

Currently, the CTS attempts to copy 16 bit values into the chroma plane of a G8_B8R8 image but a validation error is produced that the formats are of different sizes (16 and 0).

**Comment by Tony-LunarG** [comment]
@gnl21 which CTS tests are getting the validation errors?

**Comment by gnl21** [comment]
I think that I was debugging dEQP-VK.ycbcr.copy.r4g4b4a4_unorm_pack16.g8_b8r8_2plane_420_unorm.linear_linear but you should be able to see it in any multi-plane copying test.

**Comment by Tony-LunarG** [comment]
Addressed in PR #362
