### ISSUE TITLE
Spurious validation for missing PointSize?

### ISSUE THREAD

**Issue by FilippoLeon** [KhronosGroup/Vulkan-ValidationLayers#3432]
**Describe the Issue**
I have a problem where a pipeline with POINT_LIST topology is writing to gl_PointSize, and despite that the validation layers are complaining that it is not written to. This appeared just after I updated the LunarG sdk to 1.2.189.2.

**Valid Usage ID**
UNASSIGNED-CoreValidation-Shader-PointSizeMissing(ERROR / SPEC): msgNum: -211210120 - Validation Error: [ UNASSIGNED-CoreValidation-Shader-PointSizeMissing ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_PIPELINE; | MessageID = 0xf3693078 | Pipeline topology is set to POINT_LIST, but PointSize is not written to in the shader corresponding to VK_SHADER_STAGE_VERTEX_BIT

**Environment:**
 - OS: Windows
 - GPU: Nvidia 2080
 - SDK or header version if building from repo: 1.2.189.2
 - Options enabled (synchronization, best practices, etc.): core validation

**Additional context**
The shaders are working as intended, so I'm pretty sure PointSize is written to.

Shader is pretty simple and not out of the ordinary.

I attach the vertex stage spv, just in case:
[shader.zip](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/7343125/shader.zip)

**Comment by ncesario-lunarg** [comment]
Yep, as @sfricke-samsung suspected the problem is with that change, specifically with https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/58fc22823a7e82768e9ccf05b8694f959f7b158d#diff-9b243a7433e4e75bae275e5e8e41d9a3c4857911c231b1a63ff42aafcffeb7bdR1159.

I should have a fix up later today.
