### ISSUE TITLE
Best practices layer is above validation layers.

### ISSUE THREAD

**Issue by spnda** [KhronosGroup/Vulkan-ValidationLayers#3438]
**Describe the Issue**
The best practices layer trigger above the validation layers. I incorrectly set `VkSubmitInfo::pWaitDstStageMask` to `nullptr`. With only the validation layers enabled, I get the expected message from the expected checks: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/f25baf33a51323d0c9f0a11dbce7c53b4c51136b/layers/stateless_validation.h#L218-L220

However, if I enable the best practices layer, it seems to trigger first. And as `pWaitDstStageMask` is a `nullptr`, this code snippet (and the one below for `vkSubmitQueue2KHR`) will result in a read access violation:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/f25baf33a51323d0c9f0a11dbce7c53b4c51136b/layers/best_practices_utils.cpp#L1277-L1279

Now, even if the core checks triggered before, I'd personally have nothing really against the crash, as the validation layers would have already told me that I incorrectly specified a parameter as null. However that is not the case, which is why I wonder if the core checks should *always* be the first validation object to exist, unless they are disabled through the config. Otherwise, the best practices layer should maybe instead be more strict about its pointer validation instead of just assuming everything is more-or-less valid.

**Valid Usage ID**
VUID-VkSubmitInfo-pWaitDstStageMask-parameter
^-- That's the VUID this specific issue triggers on, however this could theoretically happen on any nullptr restriction by the spec.

**Environment:**
 - OS: Windows 11 (10.0.22478)
 - GPU: RTX 2080 (496.13)
 - SDK or header version if building from repo: SDK 1.2.189.2
 - Options enabled (synchronization, best practices, etc.): Core, Thread Safety, Handle Wrapping, Object Lifetime, Stateless Parameter, Synchronization, Best Practices

**Comment by spnda** [comment]
@mark-lunarg I'm using vkconfig at the moment to override layers on my application.
![image](https://user-images.githubusercontent.com/43609023/137529338-301602cc-0fe2-43c6-8612-069951517acb.png)

**Comment by ncesario-lunarg** [comment]
Each validation check assumes that no prior validation errors have occurred. As soon as the vulkan spec has been violated and (hopefully) an error has been logged, everything is "invalid" as far as the validation layers are concerned; also, error messages that follow the initial error message could be misleading as they are based on invalid data.

_That said_, we would, of course, prefer _not_ to crash. In this case--and many others--to ensure we don't crash there are quite a few conditions that need to be added to the best practices code which would be redundant from the core checks that have already run (and make best practices _even slower_ than it already is), so I'm not sure it makes sense to make any changes.

Curious if @jeremyg-lunarg has any thoughts on this?

**Comment by spencer-lunarg** [comment]
@spnda I am not able to reproduce this, if you are please reopen and happy to take another look at this, otherwise not sure what the next action on this issue is
