### ISSUE TITLE
Image layout tracking problem for YCbCr images

### ISSUE THREAD

**Issue by gnl21** [KhronosGroup/Vulkan-ValidationLayers#344]
Image layout tracking seems broken when mixing transitions of `COLOR` and `PLANE_n` aspects. The spec says that transitions of `COLOR` should affect all of the `PLANE_n` aspects as well.

In the case that I'm seeing, an image barrier first transitions the `COLOR` aspect from `UNDEFINED` to `TRANSFER_DST_OPTIMAL`. After this, data is copied into each plane of the image using vkCopyBufferToImage. The SetLayout function sees no previous layout for these aspects and so updates the initial layout to `TRANSFER_DST_OPTIMAL`. When the command buffer is submitted it produces validation errors because the actual layout of the image is `UNDEFINED`.

**Comment by Tony-LunarG** [comment]
Fixed with PR #380
