### ISSUE TITLE
Bindless + Sync Validation

### ISSUE THREAD

**Issue by Eichenherz** [KhronosGroup/Vulkan-ValidationLayers#3450]
Sync Validation incorrectly reports hazards for bound, but not used resources.

>>> VK_ERROR <<<
SYNC-HAZARD-READ_AFTER_WRITE
Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = 0xcc25c90000000082, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x4cb75b2d | vkCmdDispatch: Hazard READ_AFTER_WRITE for VkImageView 0xcc25c90000000082[], in VkCommandBuffer 0x2c31d47aef0[], and VkPipeline 0x59ffe0000000003d[Pipeline_Comp_DrawCull], VkDescriptorSet 0x980b0000000002e[], type: VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE, imageLayout: VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL_KHR, binding #2, index 0. Access info (usage: SYNC_COMPUTE_SHADER_SHADER_STORAGE_READ, prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION, write_barriers: SYNC_EARLY_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_READ|SYNC_EARLY_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE|SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_READ|SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE, command: vkCmdPipelineBarrier2KHR, seq_no: 52, reset_no: 1).

>>> VK_ERROR <<<
SYNC-HAZARD-READ_AFTER_WRITE
Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = 0xd68cbb0000000091, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x4cb75b2d | vkCmdDispatch: Hazard READ_AFTER_WRITE for VkImageView 0xd68cbb0000000091[], in VkCommandBuffer 0x2c31d47aef0[], and VkPipeline 0x59ffe0000000003d[Pipeline_Comp_DrawCull], VkDescriptorSet 0x980b0000000002e[], type: VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE, imageLayout: VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL_KHR, binding #2, index 2. Access info (usage: SYNC_COMPUTE_SHADER_SHADER_STORAGE_READ, prior_usage: SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_WRITE, write_barriers: 0, command: vkCmdEndRenderPass, seq_no: 32, reset_no: 1).

 - OS: Win10
 - GPU: GTX1050 laptop
 - SDK 1.2.189.2
 - Options enabled: Sync Validation

I have a "bindless" layout:
......
layout( set = VK_GLOBAL_DESC_SET, binding = VK_GLOBAL_SLOT_SAMPLED_IMAGE ) uniform texture2D sampledImages[];
......

In this slot I have bound ( in this order ): 
- 0 depthBuffer
- 1 HiZ buffer
- color target

I'm accessing the HiZ buffer in a compute shader ( descriptor index via push const ) in a uniform manner.
But the sync validation complains about the other 2 images as seen above.
https://github.com/Eichenherz/HellTech-Engine/blob/remote_master/Shaders/c_draw_cull.comp.glsl#L140

**Comment by Ipotrick** [comment]
I encountered the same issue as @Eichenherz.
The validation complains about a RAW of my depth image wich is bound in a giga set that holds all images. I dont actually access the corresponding descriptor ofc but i still get the validation error.

On a side note i also get a validation error when i destory a ressource wich is bound to the mega set but not accessed on the gpu (aside from beeing bound in the mega set). In this case i leave a "dangling" descriptor to the ressource in the mega set, but i dont actually use it. The validation layers should at most give a warning but not an error imo as its fine to do that (having dangling descriptors wich are unused) after all i could read about this in the spec.
I meantion this on this issue as it seemed like a similar problem to the original issue.
Are there any updates on a potential improvement of the validation layers that would eliminate these false positives?
(btw i quadruple checked to be absolutely sure that this is what is happening and not some other sync error i have in my object destruction, i also tried to defer the destruction by something like 10 frames after its not used anymore, wich gave me the same error).

> Validation Error: [ VUID-vkDestroyBuffer-buffer-00922 ] Object 0: handle = 0x4868e6000000005a, name = primitiveInfoBuffer, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0xe4549c11 | Cannot free VkBuffer 0x4868e6000000005a[primitiveInfoBuffer] that is in use by a command buffer. The Vulkan spec states: All submitted commands that refer to buffer, either directly or via a VkBufferView, must have completed execution (https://vulkan.lunarg.com/doc/view/1.2.198.1/windows/1.2-extensions/vkspec.html#VUID-vkDestroyBuffer-buffer-00922)

**Comment by Ipotrick** [comment]
i read throu other issues and found out that both of my issues appear to be fixed now:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3719
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3717

**Comment by Ipotrick** [comment]
> i read throu other issues and found out that both of my issues appear to be fixed now: #3719 #3717

After testing a bit i found out that my issues are indeed not fixed, and the linked may have fixed a crash but not the faulty validation message.

**Comment by ncesario-lunarg** [comment]
Assigning to @jeremyg-lunarg for now, but with the expectation that it may be a while before he has a chance to do further investigation.

**Comment by martin-ejdestig** [comment]
Is there some way to disable validation for bindless descriptor sets? Would be nice to not have to disable `VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT` completely.

**Comment by martin-ejdestig** [comment]
As far as I can tell, only options at the moment is to:

* Disable VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT.
* Search through error message in `VkDebugUtilsMessengerCreateInfoEXT::pfnUserCallback` debug callback for e.g. the descriptor set with bindless array and filter it out.

I do not like either of those but think I will try the latter for now.

I found a TODO comment in code about adding programmatic suppression control: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/9fe2f727998ccac7b107b5d62edc3a71b2867240/layers/sync/sync_validation.cpp#L4943

Since solving this is a hard problem requiring instrumenting shader code etc. Is maybe adding a way to suppress the warnings something that could be done as an interim solution? I do not know how much work that entails though, so maybe also not feasible in near future.

**Comment by jzulauf-lunarg** [comment]
I think a narrower approach would be to identify if the arrays are only "indexed only by constant integral expressions when aggregated into arrays in shader code" and if so capture the indices used.  Then we can (for now) fully validate non-dynamic arrays (which is the default Vulkan behaviour), and skip any (again for now) the dynamically indexed ones.

**Comment by artem-lunarg** [comment]
The issue with accesses that are under conditions. Even with identifying the resources that are *statically used* by the shader this still does not prevent from false-positives.

**Comment by artem-lunarg** [comment]
@martin-ejdestig do you have opportunity to check that https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6605 change makes the error go away?

**Comment by martin-ejdestig** [comment]
Fetched #6632 and built. Can verify that I get no RAW warnings by setting `VK_LAYER_PATH` and `LD_LIBRARY_PATH` to absolute path of `Vulkan-ValidationLayers/build/layers`. (Also verified that unsetting env variables give warnings again.)

**Comment by artem-lunarg** [comment]
Thanks for checking. We are still deciding what's the proper way to workaround this, but it's helpful to know this works.

**Comment by martin-ejdestig** [comment]
fbd17ead907c6f25c814e140576beeea13620d5a works as well. No warnings.

**Comment by danginsburg** [comment]
I'm hitting this issue as well in Counter Strike 2.  Although it only happens when not using VK_EXT_graphics_pipeline_library, dynamic rendering, and extended dynamic state extensions (run cs2 with `-vulkan_disable_graphics_pipeline_library`).  I presume it doesn't trigger with GPL + extensions just because that path isn't implementing sync validation.  We have a big bindless descriptor array with many unreferenced and this fires all over the place because it thinkgs we are reading from descriptors.

**Comment by artem-lunarg** [comment]
> I presume it doesn't trigger with GPL + extensions just because that path isn't implementing sync validation

Yes, that's correct (checked that with cs2).
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6605 and https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6743 workaround error messages for descriptor arrays.

**Comment by artem-lunarg** [comment]
@nikitablack The fix did not get into 1.3.268 release and will be available in the next SDK.
