### ISSUE TITLE
Properly validate nested built-in types

### ISSUE THREAD

**Issue by ncesario-lunarg** [KhronosGroup/Vulkan-ValidationLayers#3453]
Add support for arbitrarily nested, built-in structures in shader runtime validation. Currently, only the top level of a struct or an array of structures are supported.

See https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3434#discussion_r729289031 in #3434 for more details.

**Comment by spencer-lunarg** [comment]
Since the original issue, we have added better coverage and have many examples of nested structs in tests, so marking close until another explicit edge case is found
