### ISSUE TITLE
missing 64bit vertex attribute validation

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-ValidationLayers#3476]
The Vulkan specification states:

`The input variable in the shader must be declared as a 64-bit data type if and only if format is a 64-bit data type.`

This is not a VU (that I can see), but it is a restrictive statement that has no accompanying validation, e.g., binding an attribute of format `VK_FORMAT_R64_SFLOAT` and then using a vertex shader that loads a `vec4` from it is illegal but does not trigger errors.

I think there should be validation for this, but probably that needs a new VU? I'm happy to file spec bugs to get a new VU if needed, but I thought I'd post here first to see if there were any other opinions.

**Comment by spencer-lunarg** [comment]
I have https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5869 now, also have a local PR ready with tests, just waiting to confirm that all 4 ways to mix-and-match 64-bit vertex input are invalid

**Comment by spencer-lunarg** [comment]
@zmike this was a long issue finally closed, the VUID are still being added, but if you hit issues with the 64-bit vertex input let us know here
