### ISSUE TITLE
Current master doesn't build, thread WRAPPER macro problems

### ISSUE THREAD

**Issue by Lucretia** [KhronosGroup/Vulkan-ValidationLayers#349]
[build log](https://paste.pound-python.org/show/jDHWrBKRq0sITH6UfI3Q/)

**Comment by jzulauf-lunarg** [comment]
Cannot reproduce.  This may indicate that master requires updates to the dependent projects. 

- rerun update_deps (or manually update and build to the "known good" configurations) Note that update_deps must be run for *each* config you want to build against
- remove CMakeCache.txt
- rerun cmake

**Comment by jzulauf-lunarg** [comment]
@mikes-lunarg , @shannon-lunarg  I imagine your already working though this to get to a new known good, yes?

**Comment by lenny-lunarg** [comment]
The update for this just got merged, from #346, so I'm closing this issue.
