### ISSUE TITLE
Add Mention of Vendor-Specific Best Practice Flags to Example Settings

### ISSUE THREAD

**Issue by samwalls-arm** [KhronosGroup/Vulkan-ValidationLayers#3495]
In this file https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/vk_layer_settings.txt it would be helpful to also have some mention of flags for vendor-specific best practice checks.

What would be the most appropriate way to include these, another section after `<LayerIdentifier>.enables`? Are there any other settings which are missing from the example?

**Comment by mark-lunarg** [comment]
@samwalls-arm, sure, that's a fine spot to add the missing mentions. There may be some other missing enables -- please feel free to add any that you notice, or push them back to us!

**Comment by juan-lunarg** [comment]
Better late than never. I'll try and get this documentation into the upcoming SDK release.
