### ISSUE TITLE
Support KHR_storage_buffer_storage_class in SC

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#35]
**Issue by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Tuesday Jul 18, 2017 at 18:22 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1947_

----

- `descriptor_type_match` needs to consider storage class of the declared variable, not just aspects of the type.
- `mark_accessible_ids` needs to consider the new `StorageBuffer` storage class.
- check VK extension is enabled if SPV extension is declared by the module (first case of this)
- intra-module validation that new storage class and new semantics are only used if the SPV extension is declared to be done by SPIRV-Tools (probably already complete)

**Comment by chrisforbes** [comment]
This is done.
