### ISSUE TITLE
Warn when allocating too much from a pool

### ISSUE THREAD

**Issue by FilippoLeon** [KhronosGroup/Vulkan-ValidationLayers#3510]
When allocating too much of a given type from a descriptor pool, it is possible for the allocation to succeed or to fail, and this is totally depending on the implementation. I stumbled across a bug in the Samples https://github.com/KhronosGroup/Vulkan-Samples/issues/389 where this happens.

According to the source code: since maintenance 1, after which there is an appropriate return code,  the check is skipped: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/2ab8c47ee56227650422dcd42475888bdc7215a4/layers/descriptor_sets.cpp#L3294

Not sure if such a warning is in the scope of validation layers, since it is perfectly valid behaviour. However, I'd rather be warned than not. Could this maybe be a "Portability" warning or a "Best practices" warning?

**Comment by sfricke-samsung** [comment]
So just to get a better idea of the issue, was the driver returning `VK_SUCCESS` (instead of one of the `VK_ERROR_*`) while going past the limit? To my knowledge, what `VK_KHR_maintenance1 ` was suppose to add was forcing the driver to check allocation requests for exceeding a pool's global limits and apps to detect the error message dynamically

(internal link for future quick references https://gitlab.khronos.org/vulkan/vulkan/-/issues/686)

**Comment by cforfang** [comment]
`VK_SUCCESS` is returned and the sample works fine (i.e. driver allocates a usable set even if the pool is technically too small). The thing is, some drivers do not use the pool sizes and will allow you to allocate past the creation limits, which is what we see here.

**Comment by ncesario-lunarg** [comment]
Thanks for the issue @FilippoLeon. Unfortunately, if I understand the issue correctly, I don't think there's much else the validation layers can do here.

The app/client code is expected to check the result of `vkAllocateDescriptorSets`. If platform X decides it's ok to allocate "beyond the allowed amount," but platform Y cannot allocate beyond the allowed amount, then platform X is expected to return VK_SUCCESS, and platform Y should return `VK_ERROR_*`, and the app needs to handle the result of `vkAllocateDescriptorSets` accordingly (and if the app forgets to check the return code, then best practices validation will catch that).

While it may be arguably "strange" that platform X does this, "driver X" is declaring it's ok via the return code. And if it's not ok--i.e., the "platform Y scenario"--then "driver Y" will also need to communicate that via the return code. So, while it may be _nice_ for the validation layers to emit _some_ sort of message to the user in the "platform X scenario," it doesn't seem to be adding any real value for the duplicated checks that would need to be put into VVL.

Hopefully that made some sort of sense. If not, please let me know; it's quite possible I'm just misunderstanding the issue.
