### ISSUE TITLE
VUID-vkQueueSubmit-pCommandBuffers-00072

### ISSUE THREAD

**Issue by Desperado17** [KhronosGroup/Vulkan-ValidationLayers#3515]
Greetings,

I get a VUID-vkQueueSubmit-pCommandBuffers-00072 error:

VUID-vkQueueSubmit-pCommandBuffers-00072(ERROR / SPEC): msgNum: 1999407236 - Validation Error: [ VUID-vkQueueSubmit-pCommandBuffers-00072 ] Object 0: handle = 0x7fffc0580058, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x772c8884 | VkCommandBuffer 0x7fffc0580058[] used in the call to vkQueueSubmit() is unrecorded and contains no commands. The Vulkan spec states: Any secondary command buffers recorded into any element of the pCommandBuffers member of any element of pSubmits must be in the pending or executable state (https://vulkan.lunarg.com/doc/view/1.2.154.0/linux/1.2-extensions/vkspec.html#VUID-vkQueueSubmit-pCommandBuffers-00072)
Objects: 1
[0] 0x7fffc0580058, type: 6, name: NULL

Questions:
1 )However, the second buffer is not set up as a secondary buffer, it's just a second buffer that is submitted to the queue after a first one. Will it produce the same error message regardless?

2) Is there an easy way to initialize a potentially empty command buffer so the error is not thrown?

Regards

**Comment by ncesario-lunarg** [comment]
@Desperado17 are you calling `vkBeginCommandBuffer`/`vkBeginCommandBuffer` on the command buffer that is triggering this error? It should be valid to submit an "empty" command buffer, but the begin/end calls _must_ have been made (it's fine if no `vkCmd*` calls were made to record any commands).

**Comment by ziga-lunarg** [comment]
@ncesario-lunarg Does #4048 also resolve this?

**Comment by jeremyg-lunarg** [comment]
Closing this. If it isn't resolved by the issue and PR mentioned above, please reopen and provide more details.
