### ISSUE TITLE
Is this validation layer error's sentence wrong?

### ISSUE THREAD

**Issue by IAmNotHanni** [KhronosGroup/Vulkan-ValidationLayers#3516]
**Describe the Issue**
I did some image layout transition incorrectly and received the following message:

**Valid Usage ID**
> 2021-11-08 18:54:11.153180 error  9904 [vulkan-renderer] Validation Error: [ VUID-VkImageMemoryBarrier-oldLayout-01197 ] Object 0: handle = 0x86390d0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x124ffb34 | For VkImage 0xa9ea89000000004c[] you cannot
transition the layout of aspect=1 level=0 layer=0 from VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL when the previous known layout is VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL. The Vulkan spec states: oldLayout must be VK_IMAGE_LAYOUT_UNDEFINED or the current layout of
 the image subresources affected by the barrier (https://vulkan.lunarg.com/doc/view/1.2.141.0/windows/1.2-extensions/vkspec.html#VUID-VkImageMemoryBarrier-oldLayout-01197)

**Environment:**
 - OS: Ubuntu 20.04 LTS
 - GPU: Intel Core i7-361QM CPU @ 2.30 GHz
 - SDK or header version if building from repo: -
 - Options enabled (synchronization, best practices, etc.): none

**Additional context**
Isn't the sentence in this message incorrect? Because we are transitioning from `VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL` to `VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL`. The word "from" must be replaced with the word "to"? So it should be:

> 2021-11-08 18:54:11.153180 error  9904 [vulkan-renderer] Validation Error: [ VUID-VkImageMemoryBarrier-oldLayout-01197 ] Object 0: handle = 0x86390d0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x124ffb34 | For VkImage 0xa9ea89000000004c[] you cannot
transition the layout of aspect=1 level=0 layer=0 **to** VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL when the previous known layout is VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL. The Vulkan spec states: oldLayout must be VK_IMAGE_LAYOUT_UNDEFINED or the current layout of
 the image subresources affected by the barrier (https://vulkan.lunarg.com/doc/view/1.2.141.0/windows/1.2-extensions/vkspec.html#VUID-VkImageMemoryBarrier-oldLayout-01197)

**Comment by IAmNotHanni** [comment]
Oh now I understand it! It is the old layout which was incorrect indeed. Sorry.

**Comment by ncesario-lunarg** [comment]
Glad it's working for you now :)
