### ISSUE TITLE
Gpu validation doesn't record device address in BUFFER_STATE in PostCallRecordGetBufferDeviceAddress

### ISSUE THREAD

**Issue by rhuff-lucasfilm** [KhronosGroup/Vulkan-ValidationLayers#3519]
Without the device address recorded in BUFFER_STATE PreCallRecordDestroyBuffer is not able to erase entries from buffer_map.  This means that as buffers (with usage including VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT) are created and destroyed the buffer_map grows and eventually contains many stale entries.  These stale entries end up triggering spurious "Device address access out of bounds" validation errors.

**Comment by rhuff-lucasfilm** [comment]
#3522 pull request

**Comment by rhuff-lucasfilm** [comment]
To reproduce this issue create and destroy lots of buffers with alternating large and small sizes.  Eventually the buffer_map will contain overlapping entries and validation will start reporting "out of bounds" errors.

**Comment by ncesario-lunarg** [comment]
Is this issue still valid after #3522 merged?

**Comment by Tony-LunarG** [comment]
No.  Closing.
