### ISSUE TITLE
Validate that "reference" parameter to vkCmdSetStencilReference is in range

### ISSUE THREAD

**Issue by jeffbolznv** [KhronosGroup/Vulkan-ValidationLayers#352]
The spec says this:

```
The reference value used by stencil comparison must be within the range
[eq]#[0,2^s^-1]# , where [eq]#s# is the number of bits in the stencil
framebuffer attachment, otherwise the reference value is considered
undefined.
```

Apparently NVIDIA has different implementation-dependent behavior than other vendors here, and we had this difference reported to us as a bug. Would be nice for the validation layers to catch this.

**Comment by jzulauf-lunarg** [comment]
Should be a VU statement, though would have to be correctly validated at draw time (when the bound stencil depth would be known) -- so a command level VU wouldn't be sensible.  

Interestingly there is no similar statement for VkStencilOpState, which could also only be validated at draw time.  While this could allow common validation code, the missing language w.r.t. the dynamic state leaves some ambiguity about the nature of the restriction.

Is the spec assuming that implementations will mask to significant bits before usage, or that different references would have to be set for differing numbers of bits?

**Comment by jeffbolznv** [comment]
For better or worse, it is not considered invalid usage, the spec essentially just says the behavior is implementation-dependent. The spec used to be more strict, but was relaxed for stencil-writes-via-fragment-shader where it is not as cheap to coerce out of bounds values. I guess it made sense to have the CPU command behave similarly.

**Comment by jeffbolznv** [comment]
FWIW, given that Vulkan only has S8 stencil formats, I think it would be totally reasonable to just implement this check in parameter_validation.

**Comment by jzulauf-lunarg** [comment]
We've been trying to cutting down on these non-VU "warning" type messages.  Adding it for an implementation dependent behavior seems like a hard sell

@mark-lunarg -- thoughts ... Is this a won't fix, or reasonable to add?

**Comment by mark-lunarg** [comment]
We can put it in the Assistant Layer, see issue #24.
