### ISSUE TITLE
VK_KHR_dynamic_rendering: missing VUIDs

### ISSUE THREAD

**Issue by jeremyg-lunarg** [KhronosGroup/Vulkan-ValidationLayers#3527]
Validation for this extension is incomplete. For example there is a TODO in CoreChecks::ValidatePipelineDrawtimeState() for missing checks.

I don't have a list of the missing VUIDs @AaronHaganAMD or @Tobski if you have one it would be great to add it here. Also I cannot assign @AaronHaganAMD to this bug yet, not sure why.

**Comment by jeremyg-lunarg** [comment]
Also, I am disabling Best Practices checks in vkCreateGraphicsPipeline() to avoid crashes, see https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3530

**Comment by ncesario-lunarg** [comment]
@AaronHaganAMD is it possible for you to join the [Vulkan](https://github.com/orgs/KhronosGroup/teams/vulkan/members) group/team? That's probably the easiest way to get the issue assigned to you.

**Comment by AaronHaganAMD** [comment]
> @AaronHaganAMD is it possible for you to join the [Vulkan](https://github.com/orgs/KhronosGroup/teams/vulkan/members) group/team? That's probably the easiest way to get the issue assigned to you.

Can you try assigning it to me now. Thanks !

**Comment by ncesario-lunarg** [comment]
👍 yep, that worked @AaronHaganAMD :)

**Comment by farnoy** [comment]
@AaronHaganAMD I believe this code should be made aware of dynamic rendering:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/f8601f995fa29df95d981483a9ac256f67740997/layers/buffer_validation.cpp#L3357

`CmdBeginRendering` does not update this source of data like [`BeginRenderPass` does](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/f8601f995fa29df95d981483a9ac256f67740997/layers/cmd_buffer_state.cpp#L623).

Perhaps this snippet should be used conditionally: `cb_node->activeRenderPass->dynamic_rendering_begin_rendering_info.renderArea`.

I didn't want to create a new issue because I'm on 1.2.198 and thus not 100% sure this is an issue. It looks like it would be, though.

**Comment by ncesario-lunarg** [comment]
@AaronHaganAMD Looks like if `VkLayerTest.CmdClearAttachmentTests` were adapted to use dynamic rendering, it would fail based on what @farnoy is pointing out. There are probably other cases where "old VUs" will fail when using dynamic rendering as well; though, these might have already been considered (I'm sure there are more dynamic rendering discussions I missed while I was out).

**Comment by spencer-lunarg** [comment]
Here are the remaining VUs I see

// generic
- [ ] VUID-VkGraphicsPipelineCreateInfo-renderPass-06056
- [ ] VUID-VkRenderingInfo-layerCount-07817
- [ ] VUID-vkCmdDraw-colorAttachmentCount-07616

// multiview
- [ ] VUID-VkGraphicsPipelineCreateInfo-renderPass-07718
- [ ] VUID-VkGraphicsPipelineCreateInfo-renderPass-07719
- [ ] VUID-VkGraphicsPipelineCreateInfo-renderPass-07720

// VK_KHR_device_group
- [ ] VUID-VkRenderingInfo-pNext-07815
- [ ] VUID-VkRenderingInfo-pNext-07816

// draw
- [ ] VUID-vkCmdDraw-imageView-06172
- [ ] VUID-vkCmdDraw-imageView-06173
- [ ] VUID-vkCmdDraw-pDepthAttachment-07617
- [ ] VUID-vkCmdDraw-pStencilAttachment-07618

// VK_KHR_maintenance2
- [ ] VUID-vkCmdDraw-imageView-06174
- [ ] VUID-vkCmdDraw-imageView-06175

// VK_KHR_separate_depth_stencil_layouts
- [ ] VUID-vkCmdDraw-imageView-06176
- [ ] VUID-vkCmdDraw-imageView-06177

**Comment by Tobski** [comment]
@sfricke-samsung FWIW, any VUIDs beyond 6200 were added after the initial release. I believe 6172-6177 are all unverifiable at present, as GPU-AV doesn't cover fixed function pipeline behavior (I'm also noting there should probably be equivalent VUs for Render pass objects...). 6056 looks like we just missed it.

**Comment by spencer-lunarg** [comment]
Ok, well @arno-lunarg is signed up to help with the new VUs, (can just take `06056` while at it). I updated the list to bring mention the GPU-AV issue and those can be moved to another issue later

**Comment by arno-lunarg** [comment]
Closed in favor of a split with:
- https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5798 
- https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5797
- https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5796
