### ISSUE TITLE
Validation error for Coverage Reduction

### ISSUE THREAD

**Issue by llyzs** [KhronosGroup/Vulkan-ValidationLayers#353]
In section "Coverage Reduction" of the spec, Vulkan allows using rasterizationSamples greater than VkAttachmentDescription::samples. This allows the fragment shader to have access to SampleMask and write some computational result into a 1-sample-count output. The usage is similar to ForcedSampleCount in Direct3D 11.1.

Currently the validation is treating this as an error and reports: Num samples mismatch! At draw-time in Pipeline (x) with 16 samples while current RenderPass (x) w/ 1 samples!

**Comment by jzulauf-lunarg** [comment]
Given the coverage reduction text, this looks like a bug. However there is also this VU statement... VUID-VkGraphicsPipelineCreateInfo-subpass-01505

> If subpass uses color and/or depth/stencil attachments, then the rasterizationSamples member of pMultisampleState must equal the maximum of the sample counts of those subpass attachments

which appears to contradict the text. (Unless I'm reading this wrong.) This looks like a documentation potentially in addition to the validation issue.

The contradiction needs to be resolved by the working group -- I'll open an issue.

**Comment by jeffbolznv** [comment]
In the spec source, that VU is actually inside an VK_AMD_mixed_attachment_samples ifdef, which has different requirements than VK_NV_framebuffer_mixed_samples. This is a spec bug and we'll figure out how to fix the spec.

On the original question, NVIDIA has an internal tracking issue that we need to implement validation layer support for this extension. I'm trying to figure out if that's going to happen soon.

**Comment by jzulauf-lunarg** [comment]
@jeffbolznv  -- assigning this to you then but ping back if you need/want support.

**Comment by mark-lunarg** [comment]
This issue looks to be fixed in the current codebase, by change 25181f004ca12511.
