### ISSUE TITLE
CMake: Follow best practice of discovery/injection of external dependencies

### ISSUE THREAD

**Issue by SpaceIm** [KhronosGroup/Vulkan-ValidationLayers#3558]
CMakeLists files of `Vulkan-ValidationLayers` don't follow best pratice regarding discovery and injection of dependencies. Currently, they rely on source code layout of dependencies, instead of install layout.

For example, let's take `robin-hood-hashing`:

```cmake
if (USE_ROBIN_HOOD_HASHING)
    if(NOT ROBIN_HOOD_HASHING_INSTALL_DIR)
	set(ROBIN_HOOD_HASHING_INSTALL_DIR $ENV{ROBIN_HOOD_HASHING_INSTALL_DIR} PATH "Path to robin-hood-hashing repository")
    endif()
    set(ROBIN_HOOD_HASHING_INCLUDE_DIR "${ROBIN_HOOD_HASHING_INSTALL_DIR}/src/include" PATH "Path to robin-hood-hashing/src/include")
endif()
```

Then you add `ROBIN_HOOD_HASHING_INCLUDE_DIR` to include properties of all targets.

There is no way for a package manager to inject an already installed `robin-hood-hashing`, without patching this CMakeLists (which is not a situation package managers want to keep forever). This way of injecting dependencies is not recommended.
`robin-hood-hashing` provides a CMake config files in its installation folder.

Therefore, injection of this lib should be done with:

```cmake
if (USE_ROBIN_HOOD_HASHING)
    find_package(robin_hood REQUIRED CONFIG)
endif()
```

then:

```cmake
if (USE_ROBIN_HOOD_HASHING)
    target_link_libraries(VkLayer_utils PUBLIC robin_hood::robin_hood)
    target_compile_definitions(VkLayer_utils PUBLIC USE_ROBIN_HOOD_HASHING)
endif()
```

And that's all, no need to inject robin-hood-hashing include dir to layers, it's a public dependency of `VkLayer_utils` only (it's a transitive dependency of khronos validation layer). By using targets, CMake takes care to propagate relevant properties to downstream targets.

Now you just have to populate `CMAKE_PREFIX_PATH` with install locations of dependencies while calling CMake (so that `find_package()` can find CMake config files), it's the proper usage of CMake.
Obviously, all your dependencies must be properly installed, not just built without calling install target.

Same comment for `SPIRV-Tools`, they provide config files and imported targets, which are far more robust.

**Comment by jeremyg-lunarg** [comment]
@SpaceIm Thank you for the very detailed suggestion!  The code in PR #3562 is an attempt to implement it. I still need to get a bunch of feedback on it and update part of our internal CI. But if you have any specific suggestions on if this PR will solve your problem or not, that would be helpful. Thanks!

**Comment by SpaceIm** [comment]
Thanks, it looks quite good, I've left a minor review. I'll also check on my side if it works well.
