### ISSUE TITLE
Validation Error when using input/color attachment in multiple subpasses

### ISSUE THREAD

**Issue by imrodriguezro** [KhronosGroup/Vulkan-ValidationLayers#3569]
**Issue description**
Hi! I get a validation error when creating a render pass that contains several subpasses. 
Subpass 0 has an input attachment that is used as:
color attachment in Subpass 1, again
input attachment in Subpass 2,
input attachment in Subpass 3, then
color attachment in Subpass 4, and finally
input attachment in Subpass 5.
In the attachment references I use the layout `eShaderReadOnlyOptimal` for input and `eColorAttachmentOptimal` for color attachments. 
From subpass 1 to 2 and 4 to 5 there subpass dependencies to avoid a RAW hazard. Now, the error I'm getting is:

**Validation error**
`Validation Error: [ VUID-VkSubpassDescription-None-04437 ] Object 0: handle = 0x1f887b68118, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x438c2f01 | vkCreateRenderPass(): pSubpasses[4].pColorAttachments[0] is also an input attachment so the layout (VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL) must not be VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL. The Vulkan spec states: Each attachment must follow the image layout requirements specified for its attachment type (https://vulkan.lunarg.com/doc/view/1.2.162.1/windows/1.2-extensions/vkspec.html#VUID-VkSubpassDescription-None-04437)`

**Environment:**
OS: Windows 10
GPU: NVIDIA GeForce GTX 1070 driver 471.164.0 api 1.2.175
SDK or header version if building from repo: Vulkan 1.2.162-1
Options enabled (synchronization, best practices, etc.): only validation layers are enabled

**Additional context**
To me, the error doesn't make sense since subpass 4 doesn't use it the attachment as input attachment.  If I ignore the validation error, the output looks fine. My question is: is it safe to ignore this error? if not, do you have any idea how can it possible be solved? thanks in advance!

**Comment by TNBCORPSGG** [comment]
- - [ ] ## - [x] ~~~~~~~~~~`~~~~~~````
- - - [ ] #### ~~~~````

````~~~~
````~~~~~~`~~~~~~~~~~55 I need to be the same thing that I have all your hard work and my 35《All Rise (抖音热播版)》
歌手：东泽润
专辑：Faded Pinbo

via @haoyybot《All Rise (抖音热播版)》
歌手：东泽润
专辑：Faded Pinbo

via @haoyybot《All Rise (抖音热播版)》
歌手：东泽润
专辑：Faded Pinbo

via @haoyybot

**Comment by TNBCORPSGG** [comment]
Touch and hold a clip to pin it. Unpinned clips will be deleted after 1 hour.Tap on a clip to paste it in the text box.Welcome to Gboard clipboard, any text that you copy will be saved here.Welcome to Gboard clipboard, any text that you copy will be saved here.《All Rise (抖音热播版)》
歌手：东泽润
专辑：Faded Pinbo

via @haoyybot《All Rise (抖音热播版)》
歌手：东泽润
专辑：Faded Pinbo

via @haoyybot《All Rise (抖音热播版)》
歌手：东泽润
专辑：Faded Pinbo

via @haoyybot《All Rise (抖音热播版)》
歌手：东泽润
专辑：Faded Pinbo

via @haoyybotTap on a clip to paste it in the text box.Welcome to Gboard clipboard, any text that you copy will be saved here.

**Comment by TNBCORPSGG** [comment]
# - ## ~~@[]()_@richard-lunarg - [ ] _@ci-tester-lunarg __~~
