### ISSUE TITLE
VkCuLaunchInfoNVX - Valid usage

### ISSUE THREAD

**Issue by sultim-t** [KhronosGroup/Vulkan-ValidationLayers#3576]
**Describe the Issue**
Should it be considered to be the incorrect validation message along with incorrect specification ([VkCuLaunchInfoNVX](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkCuLaunchInfoNVX.html))? 
Specifically, `paramCount` and `extraCount`, I guess, they should be able to be equal 0?

Example usage:
* DLSS SDK 2.3.1 (https://github.com/NVIDIA/DLSS) uses interanally `paramCount = 0`. ValidationLayers report several messages about it each frame.
* Nvidia developers use this value `=0` in Proton too: https://github.com/HansKristian-Work/vkd3d-proton/blame/0828aec4f68ba8bc359d7f6b7b53f1f5e43d5fdc/libs/vkd3d/command_list_vkd3d_ext.c#L95

**Valid Usage ID**
<>

**Environment:**
 - OS: Windows 11
 - GPU: Nvidia RTX 3070
 - SDK or header version if building from repo: 1.2.189.2
 - Options enabled (synchronization, best practices, etc.): default

**Additional context**
<>

**Comment by jeremyg-lunarg** [comment]
The validation for these fields is auto-generated from the spec.  It looks like paramCount, pParams, extraCount, and pExtras all need to be marked as optional.  Please file this as a [Vulkan-Docs](https://github.com/KhronosGroup/Vulkan-Docs/)  issue.

**Comment by ncesario-lunarg** [comment]
Keeping this open for now until the Vulkan-Docs issue gets resolved.

**Comment by sultim-t** [comment]
> This should be fixed in the 1.2.203 spec update.

From Vulkan-Docs issue thread

**Comment by ncesario-lunarg** [comment]
:+1: thanks for the heads up @sultim-t; I'll keep this open until we pick up the 1.2.203 header.
