### ISSUE TITLE
Beta extensions build broken due to Vulkan-Headers changes

### ISSUE THREAD

**Issue by kainino0x** [KhronosGroup/Vulkan-ValidationLayers#3585]
**Describe the Issue**
Building the vulkan validation layers with `VK_ENABLE_BETA_EXTENSIONS` doesn't work because Vulkan-headers removed VK_VIDEO_ENCODE_RATE_CONTROL_RESET_BIT_KHR and added VK_VIDEO_ENCODE_RATE_CONTROL_RESERVED_0_BIT_KHR in https://github.com/KhronosGroup/Vulkan-Headers/pull/247.

**Environment:**
 - OS: Any (Windows/Mac/Linux/Android)
 - GPU: N/A
 - SDK or header version if building from repo: https://github.com/KhronosGroup/Vulkan-Headers/commit/ea61f32f24d2ce28b358e154910fb4eb410ffd79
 - Options enabled (synchronization, best practices, etc.): `-DVK_ENABLE_BETA_EXTENSIONS`

**Additional context**
Example build log:
https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket/8829049900737553297/+/u/compile__with_patch_/raw_io.output_text_failure_summary_
From this change:
https://chromium-review.googlesource.com/c/chromium/src/+/3310131/3

**Comment by jeremyg-lunarg** [comment]
@mikes-lunarg, looks like this should get fixed by updated generated code once we roll to 201, right?

**Comment by mikes-lunarg** [comment]
@jeremyg-lunarg correct, fix is incoming
