### ISSUE TITLE
Add info to output for indicating if validation layer change input parameter of Vulkan command

### ISSUE THREAD

**Issue by mizhen** [KhronosGroup/Vulkan-ValidationLayers#3591]
The validation layer output should include the info that indicate if the layer changed any Vulkan command input parameter, and such info should be prepend a common string, so user can search and locate it easily.

The change is helpful because of the following:

GFXR capturing a title with or without validation layer, if the title behavior is different for capturing with validation layer compared with without validation layer, user may need to know what change made by validation layer caused such difference. So it would be helpful if validation layer output includes info indicating such change.

**Comment by jeremyg-lunarg** [comment]
Unless you enable GPUAV or DebugPrintf, I don't think the validation layer should be changing vulkan commands. There could be 2 other possible causes of what you're seeing:

1. The validation layer adds CPU overhead and locking to almost all vulkan functions. This could hide or expose race conditions in an application by changing the order of execution of different threads.
2. Invalid vulkan function calls detected by the validation will not be passed to any lower layers or the driver.

Either of these could cause GFXR to record differently depending on if validation is enabled or not.

**Comment by ncesario-lunarg** [comment]
+1 for @jeremyg-lunarg's comment.

@mizhen are there specific calls that do _not_ result in any validation errors, but you see (or suspect) "changing data"?

**Comment by mizhen** [comment]
Hi @ncesario-lunarg and @jeremyg-lunarg, thank you for your reply.

I haven’t found any specific calls which change input parameters, but I suspect there might be some.

Regarding the second case (“Invalid vulkan function calls detected by the validation will not be passed to any lower layers or the driver.”), is there a way to see these invalid function calls that are detected by validation layer?

**Comment by ncesario-lunarg** [comment]
> Regarding the second case (“Invalid vulkan function calls detected by the validation will not be passed to any lower layers or the driver.”), is there a way to see these invalid function calls that are detected by validation layer?

A function that fails a `PreCallValidate*` check (e.g., parameter validation), then `VK_ERROR_VALIDATION_FAILED_EXT` will be returned as the result for that function.

**Comment by mizhen** [comment]
Hi @ncesario-lunarg and @jeremyg-lunarg,

Thank you for your help.

I found validation layer changed some pointers of original VkGraphicsPipelineCreateInfo to NULL. These changes might be caused by the following source code:  

safe_VkGraphicsPipelineCreateInfo::safe_VkGraphicsPipelineCreateInfo(const VkGraphicsPipelineCreateInfo* in_struct, const bool uses_color_attachment, const bool uses_depthstencil_attachment) :
.........................................
    if (in_struct->pRasterizationState)
        pRasterizationState = new safe_VkPipelineRasterizationStateCreateInfo(in_struct->pRasterizationState);
    else
        pRasterizationState = NULL;
    if (in_struct->pMultisampleState && has_rasterization)
        pMultisampleState = new safe_VkPipelineMultisampleStateCreateInfo(in_struct->pMultisampleState);
    else
        pMultisampleState = NULL; // original pMultisampleState pointer ignored
    // needs a tracked subpass state uses_depthstencil_attachment
    if (in_struct->pDepthStencilState && has_rasterization && uses_depthstencil_attachment)
        pDepthStencilState = new safe_VkPipelineDepthStencilStateCreateInfo(in_struct->pDepthStencilState);
    else
        pDepthStencilState = NULL; // original pDepthStencilState pointer ignored
    // needs a tracked subpass state usesColorAttachment
    if (in_struct->pColorBlendState && has_rasterization && uses_color_attachment)
        pColorBlendState = new safe_VkPipelineColorBlendStateCreateInfo(in_struct->pColorBlendState);
    else
        pColorBlendState = NULL; // original pColorBlendState pointer ignored
    if (in_struct->pDynamicState)
        pDynamicState = new safe_VkPipelineDynamicStateCreateInfo(in_struct->pDynamicState);
    else
        pDynamicState = NULL;
...............................................................................................
vkCreateDevice also has such case for ppEnabledLayerNames of VkDeviceCreateInfo.

For this case, running target title to the location where I needed, the output file size of validation layer is over 100M, and dump file size over 1G, it would be very helpful if there are some messages with specific marker string can be added to indicate these pointers of VkGraphicsPipelineCreateInfo that have been changed. Since the file sizes are very large, adding this would allow me to search the marker string in output file to locate the message.

**Comment by Tony-LunarG** [comment]
GPU-AV will make a copy of the CreateInfo but it should only change anything in the rare case when the app is using all of the available descriptor set slots and then it replaces the instrumented shaders with the non-instrumented shaders since the GPU-AV descriptor set cannot be bound.

**Comment by spencer-lunarg** [comment]
update - this is related to https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7659

the issue is actually nothing to do with GPU-AV / DebugPrintf, but instead is an issue how we are currently trying to handled "ignored" struct members

The change I am working towards is to not modify the Pipeline Creation struct at all, but instead pass down what is ignored so the layer knows and we don't accidentally change what code is being sent to the driver

**Comment by spencer-lunarg** [comment]
So the safe struct stuff from https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3591#issuecomment-994907531 has been moved out of VVL, for now, the VVL should not be adjusting any values (outside shader instrumentation for GPU-AV)
