### ISSUE TITLE
VkCreateGraphicsPipeline segfault in validation layers

### ISSUE THREAD

**Issue by SovjetSpy** [KhronosGroup/Vulkan-ValidationLayers#3593]
**Description:**
Recently I encountered a scenario where the validation layers generate a segmentation fault. it happend when calling VkCreateGraphicsPipeline. I found out it happens somewhere in the function ValidatePipelineUnlocked on line 1543 in core_validation.cpp, after that I am clueless about what is happening. I added the output of the api params validation output of the input I am giving to the VkCreateGraphicsPipeline function.

I am not sertant whether this is a bug or not, but I do not think that generating a segfault is intended behavior.

**Valid Usage ID**
None generated.

**Environment:**
 - OS: Ubuntu 20.04.3 LTS x86_64
 - GPU: NVIDIA RTX 3060 laptop gpu with proprietary drivers and INTEL intergrated graphics whith mesa drivers
 - SDK or header version if building from repo: did not build from the repo
 - Options enabled (synchronization, best practices, etc.): only the standaard layout

**Additional context**
[api_dump.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/7671067/api_dump.txt)

**Comment by sfricke-samsung** [comment]
Do you know which version of the validation layers you are using... is line 1543 referencing the following for you? 

```cpp
            if (pPipeline->attachments.size() > 1) {
                const VkPipelineColorBlendAttachmentState *const attachments = &pPipeline->attachments[0];
```

**Comment by SovjetSpy** [comment]
Yes, that is the exact line that I am referencing. I am using the layers from the package manager. The version listed by apt is: 1.2.198.0~rc1-1lunarg20.04-1.

**Comment by sfricke-samsung** [comment]
I see from your dump

```
            pColorBlendState:               const VkPipelineColorBlendStateCreateInfo* = 0x7ffe11d53530:
                attachmentCount:                uint32_t = 1
                pAttachments:                   const VkPipelineColorBlendAttachmentState* = 0x7ffe11d53158
                    pAttachments[0]:                const VkPipelineColorBlendAttachmentState = 0x7ffe11d53158:
 ```
 
 so that seems like `pPipeline->attachments.size()` should be `1` and never reach to the next line
 
 Here is where `pPipeline->attachments` is appended, so not sure how it would possibly be adding more
 
 ```cpp
 static PIPELINE_STATE::AttachmentVector GetAttachments(const safe_VkGraphicsPipelineCreateInfo &create_info) {
    PIPELINE_STATE::AttachmentVector result;
    if (create_info.pColorBlendState) {
        const auto cbci = create_info.pColorBlendState;
        if (cbci->attachmentCount) {
            result.reserve(cbci->attachmentCount);
            std::copy(cbci->pAttachments, cbci->pAttachments + cbci->attachmentCount, std::back_inserter(result));
        }
    }
    return result;
}
```

**Comment by SovjetSpy** [comment]
That is weerd indeed. I will try bugging that peas of code tomorrow to see if I can find anything suspicious.

**Comment by SovjetSpy** [comment]
So I have tried to find out the problem, but failed. I have found out something interesting about the adding of the atachments to the array in the PIPELINE_STATE objects:
![Screenshot_20211208_192658](https://user-images.githubusercontent.com/48281028/145264953-41894411-5de8-4345-8787-dc9dee984114.png)

as you can see the pColorblendstate varable is a nullptr, but when I looked back in the stack trace I found that is wass still filed in:
![adding of atachments back in the stack trace](https://user-images.githubusercontent.com/48281028/145265307-0671b0a3-4910-4f76-8f8c-906726932baf.png)

also i found the real location of the segmentation fault. It is in shader_validation.cpp on line 299:
![segfault](https://user-images.githubusercontent.com/48281028/145265604-87933cda-7a9c-4c57-bf35-58e26b69282d.png)

I think it is also important to note that this is with the git repo debug build from about 3 days ago.

**Comment by sfricke-samsung** [comment]
So the segfault (from the 3rd image) is in a different spot than originally posted.

This spot makes more sense, since you already have a build working, could you try

```patch
- if (!output && pipeline->attachments[location].colorWriteMask != 0) {
+ if (!output && location < pipeline->attachments.size() && pipeline->attachments[location].colorWriteMask != 0) {
```

and see if that fixes your problem, from there I can create a more elegant fix and a test to prevent regressions

**Comment by SovjetSpy** [comment]
So the proposed fix did not work, because the initialization of the attatchment array is broken in some way and gave me segfaults when calling any function from it. I have managed to make my application working with the validation layers enabled by setting **piplinecreateinfo.rasterizationstate.rasterizerDiscardEnable** to VK_FALSE (it wass VK_TRUE). this changed the **has_rasterization** flag on line 4008 in the **safe_VkGraphicsPipelineCreateInfo::initialize** function in file vk_safe_struct.cpp. this in turn trigered the assignment if the **pColorBlendState** on line 4038 in the same function. This has the effect of changing the behavior of the **GetAttachments** function in the PIPELINE_STATE constructor. No validation errors are generated when creating the pipeline.

**Comment by ncesario-lunarg** [comment]
Thanks for the issue @SovjetSpy! Is there any chance you could provide a code snippet that reproduces this? If that is not possible, could you provide a gfxreconstruct capture?

**Comment by sfricke-samsung** [comment]
@SovjetSpy gave the `vkCreateGraphicsPipelines` API Dump, but I think what I am missing from putting all the pieces together is the `VkGraphicsPipelineCreateInfo::renderPass` api dump tied to the pipeline. If you could get me all the `VkRenderPassCreateInfo` info I should be able to just build a simple test and **hopefully** be able to reproduce it from just that

**Comment by SovjetSpy** [comment]
I am sorry about that. I did not think of the importance of the renderpass and I will send the structs and API dump later tonight.

**Comment by ncesario-lunarg** [comment]
👍 thanks!

**Comment by SovjetSpy** [comment]
I have made the dump and added it to this comment:
[api_dump.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/7688094/api_dump.txt)

And here is my renderpass creation code:
```cpp
    VkAttachmentDescription swapchain_trarget;
    swapchain_trarget.flags = 0;
    swapchain_trarget.format = swapchain_format;
    swapchain_trarget.samples = VK_SAMPLE_COUNT_1_BIT;
    swapchain_trarget.loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
    swapchain_trarget.storeOp = VK_ATTACHMENT_STORE_OP_STORE;
    swapchain_trarget.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
    swapchain_trarget.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
    swapchain_trarget.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    swapchain_trarget.finalLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;

    VkAttachmentReference color_ref;
    color_ref.attachment = 0;
    color_ref.layout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;

    VkSubpassDescription render_subpass_description;
    render_subpass_description.flags = 0;
    render_subpass_description.pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS;
    render_subpass_description.inputAttachmentCount = 0;
    render_subpass_description.pInputAttachments = nullptr;
    render_subpass_description.colorAttachmentCount = 1;
    render_subpass_description.pColorAttachments = &color_ref;
    render_subpass_description.pResolveAttachments = 0;
    render_subpass_description.pDepthStencilAttachment = nullptr;
    render_subpass_description.preserveAttachmentCount = 0;
    render_subpass_description.pPreserveAttachments = nullptr;

    VkRenderPassCreateInfo CreateInfo;
    CreateInfo.sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO;
    CreateInfo.pNext = nullptr;
    CreateInfo.flags = 0;
    CreateInfo.attachmentCount = 1;
    CreateInfo.pAttachments = &swapchain_trarget;
    CreateInfo.subpassCount = 1;
    CreateInfo.pSubpasses = &render_subpass_description;
    CreateInfo.dependencyCount = 0;
    CreateInfo.pDependencies = nullptr;

    VK_CHECK(vkCreateRenderPass(gp.get_device(), &CreateInfo, nullptr, &renderpass));
```
I think this code explains itself.

Adding my pipeline creation code is difficult, because I have made a lot of systems around the creation that have a influence on the  actual creation, but i can see wat I can do if it is realy nessasery.

**Comment by sfricke-samsung** [comment]
So tried to recreate the issue from the api_dump but a not sure why you have

```
dstColorBlendFactor:            VkBlendFactor = UNKNOWN (-1)
alphaBlendOp:                   VkBlendOp = UNKNOWN (-1)
```

as you should be hitting errors that these are not valid enum values

-----

I have tried everything I can but can't seem to reproduce the issue... my guess is it might be something special due to the fact it is a swapchain image.

The next best thing is go to the VulkanSDK `path_to_sdk/x86_64/bin/gfxrecon-capture.py` and get us a `.gfxr` file to have a chance to reproduce the issue with `gfxrecon-replay`

**Comment by SovjetSpy** [comment]
The reason for those values is that I did not zero out the struct. I figured that is was not important, because I disables blending. I have zeroed it out since and id had no effect. 

Also I have retried your origional proposed fix and it seems to work. I think I did something wrong when trying the first time.

I will try to make the gfxr capture later today.
