### ISSUE TITLE
Should `ppEnabledExtensions` in validation error reports be `ppEnabledExtensionNames`?

### ISSUE THREAD

**Issue by helenginn** [KhronosGroup/Vulkan-ValidationLayers#3599]
This comes with the caveat that I am entirely new to Vulkan as of today.

In handling a validation error,
```
VUID-VkDeviceCreateInfo-pProperties-04451(ERROR / SPEC): msgNum: 976972960 - Validation Error: [ VUID-VkDeviceCreateInfo-pProperties-04451 ] Object 0: handle = 0x7f8260e54900, type = VK_OBJECT_TYPE_PHYSICAL_DEVICE; | MessageID = 0x3a3b6ca0 | vkCreateDevice: VK_KHR_portability_subset must be enabled because physical device VkPhysicalDevice 0x7f8260e54900[] supports it The Vulkan spec states: If the VK_KHR_portability_subset extension is included in pProperties of vkEnumerateDeviceExtensionProperties, ppEnabledExtensions must include "VK_KHR_portability_subset" (https://vulkan.lunarg.com/doc/view/1.2.198.1/mac/1.2-extensions/vkspec.html#VUID-VkDeviceCreateInfo-pProperties-04451)
```

I notice a reference to `ppEnabledExtensions` that, through context, I would have expected to be `ppEnabledExtensionNames`, and I cannot find `ppEnabledExtensions` mentioned anywhere on khronos.org. I am wondering if this is a typo in the validation error. Feel free to close if I missed something obvious.

**Comment by ziga-lunarg** [comment]
That does look like a bug to me and I believe you're right that it should be probably be `ppEnabledExtensionNames` instead of `ppEnabledExtensions`. But this line does not come from validations layers, it is from the vulkan spec, so maybe an issue should be opened in https://github.com/KhronosGroup/Vulkan-Docs

**Comment by helenginn** [comment]
Thanks, I've passed it onto the Docs repository!
