### ISSUE TITLE
VU checks for vkGetQueryPoolResults() in CV are incorrect (and slow)

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#36]
**Issue by [cdwfs](https://github.com/cdwfs) (MIGRATED)**
_Wednesday Jul 26, 2017 at 00:11 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1971_

----

The checks in core_validation for vkGetQueryPoolResults():
- are too overzealous (reporting errors for usages not marked as invalid in the spec, such as retrieving the results of an unissued query with the WITH_AVAILABILITY flag set and the WAIT flag cleared)
- have ambiguous/duplicated report messages (same message for unavailable-and-unissued and unavailable-and-in-flight)
- have no VUIDs
- are, by their own admission, "insanely wasteful" (as reported in #829)

We should clean up the checks, and potentially clarify the spec regarding what is & isn't valid usage if we find something useful the layers aren't currently checking for.

**Comment by mark-lunarg** [comment]
We believe these issues were primarily addressed in three recent PRs bulking up query validation, increasing performance, and implementing a disable for all query validation.
