### ISSUE TITLE
ValidateDrawVertexIndex is using UINT32_MAX

### ISSUE THREAD

**Issue by cclao** [KhronosGroup/Vulkan-ValidationLayers#3604]
**Describe the Issue**
ValidateDrawVertexIndex is using UINT32_MAX

**Valid Usage ID**
This is discovered while working on ANGLE. ANGLE just implemented buffer sub-allocation, that we are sub-allocating from VkBuffer now. With that, we are seeing some synchronization validation errors. One such error is due to the TODO item listed in the code, see bellow for the detail.

**Environment:**
 - OS: 
 - GPU:
 - SDK or header version if building from repo:
 - Options enabled (synchronization, best practices, etc.):

**Additional context**

bool CommandBufferAccessContext::ValidateDrawVertexIndex(uint32_t indexCount, uint32_t firstIndex, const char *func_name) const {
    bool skip = false;
    if (cb_state_->index_buffer_binding.buffer_state == nullptr || cb_state_->index_buffer_binding.buffer_state->Destroyed()) {
        return skip;
    }

    auto *index_buf_state = cb_state_->index_buffer_binding.buffer_state.get();
    const auto index_size = GetIndexAlignment(cb_state_->index_buffer_binding.index_type);
    const ResourceAccessRange range = GetBufferRange(cb_state_->index_buffer_binding.offset, index_buf_state->createInfo.size,
                                                     firstIndex, indexCount, index_size);
    auto hazard = current_context_->DetectHazard(*index_buf_state, SYNC_INDEX_INPUT_INDEX_READ, range);
    if (hazard.hazard) {
        skip |= sync_state_->LogError(
            index_buf_state->buffer(), string_SyncHazardVUID(hazard.hazard), "%s: Hazard %s for index %s in %s. Access info %s.",
            func_name, string_SyncHazard(hazard.hazard), sync_state_->report_data->FormatHandle(index_buf_state->buffer()).c_str(),
            sync_state_->report_data->FormatHandle(cb_state_->commandBuffer()).c_str(), FormatUsage(hazard).c_str());
    }

    // TODO: For now, we detect the whole vertex buffer. Index buffer could be changed until SubmitQueue.
    //       We will detect more accurate range in the future.
    skip |= ValidateDrawVertex(UINT32_MAX, 0, func_name);
    return skip;
}

There is a TODO in the above code. This is causing sync validation error when sub-allocation is used. Because we are sending down UINT32_MAX here, the validation code does not know exact range of vertex array ranges been accessed and causing syncval error.

**Comment by jzulauf-lunarg** [comment]
Fixed @ https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5567
