### ISSUE TITLE
Vulkan Validation Layers fails to report invalid VkWin32SurfaceCreateInfoKHR window handle.

### ISSUE THREAD

**Issue by ZOulhadj** [KhronosGroup/Vulkan-ValidationLayers#3628]
**Issue description:** 

I made a mistake by forgetting to set the **VkWin32SurfaceCreateInfoKHR** HWND property to a valid window handle. A subsequent 
call to the **vkGetPhysicalDeviceSurfaceCapabilitiesKHR** returned **VK_UNKNOWN_ERROR(-13)**. The validation layer failed to pick this up.

Below is a forum post in which a person also got this error and the validation layer did not indicate that there was an issue.
[Post](https://community.khronos.org/t/vkgetphysicaldevice-surfacecapabilitieskhr-returns-vk-error-unknown-13/106718/4)

**Comment by ziga-lunarg** [comment]
Was VkWin32SurfaceCreateInfoKHR::hwnd `NULL` or something else?

**Comment by ZOulhadj** [comment]
Yes, hwnd was set to NULL.
