### ISSUE TITLE
Can't create cube app with VK_IMAGE_VIEW_TYPE_CUBE 

### ISSUE THREAD

**Issue by probug12** [KhronosGroup/Vulkan-ValidationLayers#3629]
**Issue description**
Can't create cube app using Vulkan SDK 1.2.189.0 & 1.2.198.1 for OSX & Linux. vkCreateImageView creates view "successfully" but always shows warning/error below which is too long and not helpful.

**Validation messages**
VkImageCreateInfo imageInfo {};
	imageInfo.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
	imageInfo.imageType = VK_IMAGE_TYPE_2D;
	imageInfo.extent.width = width;
	imageInfo.extent.height = height;
	imageInfo.extent.depth = 1;
	imageInfo.mipLevels = 1;
	imageInfo.arrayLayers = 1;
	imageInfo.flags = VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT;
	imageInfo.format = VK_FORMAT_R8G8B8A8_SRGB;
	imageInfo.tiling = VK_IMAGE_TILING_OPTIMAL;
	imageInfo.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
	imageInfo.usage = VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_SAMPLED_BIT;
	imageInfo.samples = VK_SAMPLE_COUNT_1_BIT;
	imageInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;

VkImageViewCreateInfo view_info {};
	view_info.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
	view_info.image = image;
	view_info.viewType = VK_IMAGE_VIEW_TYPE_CUBE;
	view_info.format = VK_FORMAT_B8G8R8A8_SRGB;
	view_info.components = {
		VK_COMPONENT_SWIZZLE_IDENTITY,
		VK_COMPONENT_SWIZZLE_IDENTITY,
		VK_COMPONENT_SWIZZLE_IDENTITY,
		VK_COMPONENT_SWIZZLE_IDENTITY
	};
	view_info.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
	view_info.subresourceRange.baseMipLevel = 0;
	view_info.subresourceRange.levelCount = 1;
	view_info.subresourceRange.baseArrayLayer = 0;
	view_info.subresourceRange.layerCount = 6;

VkImageView image_view;
>>>>>    if (vkCreateImageView(device, &view_info, nullptr, &image_view) == VK_SUCCESS) {}   <<<<<

Validation Error: [ VUID-VkImageViewCreateInfo-subresourceRange-01483 ] Object 0: handle = 0xf56c9b0000000004, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x6bf1590a | vkCreateImageView: pCreateInfo->subresourceRange.baseArrayLayer + .layerCount (= 0 + 6 = 6) is greater than the arrayLayers of the image when it was created (i.e. greater than 1). The Vulkan spec states: If subresourceRange.layerCount is not VK_REMAINING_ARRAY_LAYERS, image is not a 3D image created with VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT set, or viewType is not VK_IMAGE_VIEW_TYPE_2D or VK_IMAGE_VIEW_TYPE_2D_ARRAY, subresourceRange.layerCount must be non-zero and subresourceRange.baseArrayLayer + subresourceRange.layerCount must be less than or equal to the arrayLayers specified in VkImageCreateInfo when image was created (https://vulkan.lunarg.com/doc/view/1.2.198.1/mac/1.2-extensions/vkspec.html#VUID-VkImageViewCreateInfo-subresourceRange-01483)

Validation Error: [ VUID-VkImageViewCreateInfo-image-01003 ] Object 0: handle = 0xf56c9b0000000004, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x13c91c20 | vkCreateImageView(): pCreateInfo->viewType VK_IMAGE_VIEW_TYPE_CUBE is not compatible with image type VK_IMAGE_TYPE_2D. The Vulkan spec states: If image was not created with VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT then viewType must not be VK_IMAGE_VIEW_TYPE_CUBE or VK_IMAGE_VIEW_TYPE_CUBE_ARRAY (https://vulkan.lunarg.com/doc/view/1.2.198.1/mac/1.2-extensions/vkspec.html#VUID-VkImageViewCreateInfo-image-01003)

**Environment:**
 - OS: OSX 11.6.2 & Linux
 - GPU: Intel Iris Plus Graphics 650
 - SDK or header version if building from repo: 1.2.189.0 & 1.2.198.1
 - Options enabled (synchronization, best practices, etc.): VK_EXT_DEBUG_UTILS_EXTENSION_NAME, VK_LAYER_KHRONOS_validation

**Additional context**
Is there a working example of cube app using VK_IMAGE_VIEW_TYPE_CUBE?
[cube error.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/7791237/cube.error.txt)

**Comment by sfricke-samsung** [comment]
1. ` VUID-VkImageViewCreateInfo-subresourceRange-01483`

You have `imageInfo.arrayLayers = 1` and `view_info.subresourceRange.layerCount = 6` which is invalid because the image needs to be created with enough layers for the imageView to use. This seems like a proper validation error to me and you should be using  `imageInfo.arrayLayers = 6` 

2. `VUID-VkImageViewCreateInfo-image-01003`

You have

```
imageInfo.imageType = VK_IMAGE_TYPE_2D;
imageInfo.flags = VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT;
```

but if you want to cube image you will want to be using `VK_IMAGE_VIEW_TYPE_CUBE` so this also seems like a proper validation error to me

**Comment by probug12** [comment]
> 1. ` VUID-VkImageViewCreateInfo-subresourceRange-01483`
> 
> 
> You have `imageInfo.arrayLayers = 1` and `view_info.subresourceRange.layerCount = 6` which is invalid because the image needs to be created with enough layers for the imageView to use. This seems like a proper validation error to me and you should be using `imageInfo.arrayLayers = 6`
> 
>     2. `VUID-VkImageViewCreateInfo-image-01003`
> 
> 
> You have
> 
> ```
> imageInfo.imageType = VK_IMAGE_TYPE_2D;
> imageInfo.flags = VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT;
> ```
> 
> but if you want to cube image you will want to be using `VK_IMAGE_VIEW_TYPE_CUBE` so this also seems like a proper validation error to me

I changed imageInfo.arrayLayers = 6  but 

typedef enum VkImageType {
    VK_IMAGE_TYPE_1D = 0,
    VK_IMAGE_TYPE_2D = 1,
    VK_IMAGE_TYPE_3D = 2,
} VkImageType;

I have "view_info.viewType = VK_IMAGE_VIEW_TYPE_CUBE". Where do you suggest I use "VK_IMAGE_VIEW_TYPE_CUBE" ?

**Comment by probug12** [comment]
@sfricke-samsung   I changed imageInfo.arrayLayers = 6 but

typedef enum VkImageType {
VK_IMAGE_TYPE_1D = 0,
VK_IMAGE_TYPE_2D = 1,
VK_IMAGE_TYPE_3D = 2,
} VkImageType;

I have "view_info.viewType = VK_IMAGE_VIEW_TYPE_CUBE". Where do you suggest I use "VK_IMAGE_VIEW_TYPE_CUBE" ?

**Comment by ziga-lunarg** [comment]
`imageInfo.imageType` shoud be `VK_IMAGE_TYPE_2D` and `view_info.viewType` should be `VK_IMAGE_VIEW_TYPE_CUBE`

**Comment by probug12** [comment]
@ziga-lunarg Thats exactly what I have but getting all the same errors. Nothing changed a bit. Is there a working example of cube app using vulkan 1.2?

**Comment by sfricke-samsung** [comment]
> If image was not created with VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT then viewType must not be VK_IMAGE_VIEW_TYPE_CUBE or VK_IMAGE_VIEW_TYPE_CUBE_ARRAY

So if you have a `VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT` in your image and a `VK_IMAGE_VIEW_TYPE_CUBE` in your imageView then there should be no error (for VUID-VkImageViewCreateInfo-image-01003)

**Comment by probug12** [comment]
@sfricke-samsung I have “ imageInfo.flags = VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT;” , so I assume there is a bug in validation layers.  vkCreateImageView returns success 🤷🏻‍♂️

**Comment by ziga-lunarg** [comment]
The following works for me:

```
    VkImageCreateInfo imageInfo{};
    imageInfo.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
    imageInfo.imageType = VK_IMAGE_TYPE_2D;
    imageInfo.extent.width = 32;
    imageInfo.extent.height = 32;
    imageInfo.extent.depth = 1;
    imageInfo.mipLevels = 1;
    imageInfo.arrayLayers = 6;
    imageInfo.flags = VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT;
    imageInfo.format = VK_FORMAT_R8G8B8A8_SRGB;
    imageInfo.tiling = VK_IMAGE_TILING_OPTIMAL;
    imageInfo.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    imageInfo.usage = VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_SAMPLED_BIT;
    imageInfo.samples = VK_SAMPLE_COUNT_1_BIT;
    imageInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;

    VkImageViewCreateInfo view_info{};
    view_info.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
    view_info.image = image.handle();
    view_info.viewType = VK_IMAGE_VIEW_TYPE_CUBE;
    view_info.format = VK_FORMAT_R8G8B8A8_SRGB;
    view_info.components = {VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY,
                            VK_COMPONENT_SWIZZLE_IDENTITY};
    view_info.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
    view_info.subresourceRange.baseMipLevel = 0;
    view_info.subresourceRange.levelCount = 1;
    view_info.subresourceRange.baseArrayLayer = 0;
    view_info.subresourceRange.layerCount = 6;
```

**Comment by probug12** [comment]
Still not working for me https://pastebin.com/8gR4s0AJ

**Comment by ncesario-lunarg** [comment]
Are you attempting to create a cube map view from a swapchain image? It looks like the intent is to create a cube map view of `texture_image`, but I run into these errors here:
```cpp
void create_image_views() {
		swapchain_image_views.resize(swapchain_images.size());

		for (uint32_t i = 0; i < swapchain_images.size(); i += 1) {
			swapchain_image_views[i] = create_image_view(swapchain_images[i], swapchain_image_format, VK_IMAGE_ASPECT_COLOR_BIT);
		}
	}
```
before `texture_image` is created  (I think before any non-swapchain image is created), and this error looks valid to me.

Also possibly worth noting is that the pasted sample code did not run for me as-is due to VK_KHR_portability_subset assumptions. I also ran into an error w.r.t. to swapchain image count, so there might be some other problems happening before this error.

> Is there a working example of cube app using VK_IMAGE_VIEW_TYPE_CUBE?

I'm not sure if [Sascha Willems'](https://github.com/SaschaWillems/Vulkan/tree/a5022d6d5fc3118726e1df4bbe3a33e8784f50cf/examples/texturecubemap) demos are working with `VK_KHR_portability_subset`, but it might be good to get that working on your system first if possible.

**Comment by ncesario-lunarg** [comment]
@probug12 do you think there is still an issue here, or should this be closed?

**Comment by probug12** [comment]
@ncesario-lunarg Hi. I'm slowly rewriting everything from scratch to make sure I'm doing everything correctly. Not closing yet. Can I reopen it if there is an issue?

**Comment by ncesario-lunarg** [comment]
@probug12 yep, you can re-open (there should be a "re-open" button at the bottom of this issue page) if it turns out there is an issue. Or worst case you can always open a new issue :)

Closing for now.

**Comment by probug12** [comment]
Working on my own version of vulkan cube ( https://gitlab.com/ndbits/vulkan-cube ) and getting a black screen without any error. Renderdoc didn't work for me at all. Wondering if someone could suggest other debugging tools or find a bug. Thank you:)

**Comment by KarenGhavam-lunarG** [comment]
Another good source of debugging assistance is Discord or Reddit. There are many Vulkan developers out there that will look at your code and provide useful suggestions.
