### ISSUE TITLE
Validation layers in SDK 1.2.198.1 not correctly reporting incorrect object destruction order

### ISSUE THREAD

**Issue by Diamond-D0gs** [KhronosGroup/Vulkan-ValidationLayers#3642]
**Describe the Issue**
The validation layers are only reporting that a semaphore is being incorrectly destroyed, but incorrectly setting the destruction order of the device, instance, and swapchain reports no error.

**Valid Usage ID**
[ERROR: Validation]
Validation Error: [ VUID-vkDestroyDevice-device-00378 ]

**Environment:**
 - OS: Windows 11
 - GPU: Geforce GTX 1080
 - SDK: 1.2.198.1
 - Options enabled (synchronization, best practices, etc.):
 Standard Preset w/ Best Practices

**Additional context**
![Screenshot 2022-01-02 124554](https://user-images.githubusercontent.com/32776854/147889034-e556fe12-b48f-4438-a508-480ff65f1997.png)

![Screenshot 2022-01-02 124152](https://user-images.githubusercontent.com/32776854/147888948-9fd571d2-c1fc-4ac7-80e6-03f51e7f956d.png)

**Comment by mark-lunarg** [comment]
@Diamond-D0gs, thank you for the report.  The validation layers report leaked objects at `DestroyDevice()-` and `DestroyInstance()-`time. If `vkDestroyInstance()` is never called there remains no opportunity to report undestroyed child objects belonging to that instance.  However, as relates to this issue, not calling `vkDestroyInstance()` on the `VkInstance` object itself _is_ valid usage -- there's no error for the layers to report.

**Comment by mark-lunarg** [comment]
Closing this for now, if there are any other issues that were incompletely addressed, please reopen this issue or file another -- thanks!
