### ISSUE TITLE
Raytracing CTS test crashes with validation

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-ValidationLayers#3645]
**Describe the Issue**
dEQP-VK.ray_tracing_pipeline.pipeline_library.configurations.multithreaded_compilation_dho.s0_l1 crashes with validation starting at #3592 scripts: Store and delete mem for deferred ops 

Crash is in the Nvidia driver in CreateRayTracingPipelinesKHR

**Environment:**
 - OS: Windows 10
 - GPU: GeForce GTX 2080
 - SDK or header version if building from repo: f16f149 or today's master
 - Options enabled (synchronization, best practices, etc.): None

**Additional context**

**Comment by ncesario-lunarg** [comment]
@larsivarsimonsen-arm, any chance you'd be able to look into this?

**Comment by larsivarsimonsen-arm** [comment]
Hi @ncesario-lunarg,
Unfortunately, I do not have a way to run this setup so I'm not able to debug this.
I'll follow this thread and try to be of assistance to anyone that can run this, but I will not be able to drive the debug effort.
