### ISSUE TITLE
Use of DRM format modifier extension structs when not enabled

### ISSUE THREAD

**Issue by Kangz** [KhronosGroup/Vulkan-ValidationLayers#3673]
**Describe the Issue**
This [commit](https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/d0f84e4de9fb0a6dd48a8e3c48d3c829467fd9db) is causing an ASSERT in Swiftshader:

> third_party/swiftshader/src/Vulkan/libVulkan.cpp:3357 ABORT: UNSUPPORTED: pFormatProperties->pNext sType = DrmFormatModifierPropertiesList2EXT

The [Vulkan spec states that it is invalid to chain extension structs that aren't defined for the core version or enabled via an extension](https://www.khronos.org/registry/vulkan/specs/1.2/html/vkspec.html#:~:text=Each%20structure%20included%20in%20the%20pNext%20chain%20must%20be%20defined%20at%20runtime%20by%20either%3A). But the commit referenced seems to add `DrmFormatModifierPropertiesList2EXT` unconditionally.

Tagging @llandwerlin-intel and @ncesario-lunarg directly.

**Valid Usage ID**
If applicable, please include the validation messages encountered leading up to the issue

**Environment:**
 - OS: Linux
 - GPU: Swiftshader
 - SDK or header version if building from repo: VVL commit ad20b9766ba507b95e1dec5b687ddcd448237108
 - Options enabled (synchronization, best practices, etc.): core + synchronization

**Additional context**

**Comment by Kangz** [comment]
FYI @c0d1f1ed

**Comment by spencer-lunarg** [comment]
@Kangz did https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3674 fix this for you?

**Comment by Kangz** [comment]
It did, thanks!
