### ISSUE TITLE
Improve missing features/extensions messages

### ISSUE THREAD

**Issue by sfricke-samsung** [KhronosGroup/Vulkan-ValidationLayers#3699]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3688 shows that the error messages don't do a good enough job explaining what is happening. The whole feature stuff in Vulkan (especially with promoted features) is not for the faint of heart and if a future dev gets these errors, I would rather them not need to create a duplicate issue

**Comment by spencer-lunarg** [comment]
These have since been improved and we now print out the missing info better!
