### ISSUE TITLE
Core validation: Value assigned to the location decoration is not checked against (physical device::maxVertexOutputComponents / 4)

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#37]
**Issue by [DominikWitczakAMD](https://github.com/DominikWitczakAMD) (MIGRATED)**
_Thursday Jul 27, 2017 at 07:39 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1973_

----

We recently received a bug report from ISV, which - after closer inspection - revealed that validation layers apparently do not check if the location decoration value specified in a SPIR-V blob exceeds the maximum number of output components in the VS shader stage reported as supported for a physical device that the shader module is used against.

In specific, let's consider the following:

```
OpDecorate %2680 Location 64
```

Our driver reports a value of (32*4) for _maxVertexOutputComponents_. Ignoring this restriction causes our vkCreateGraphicsPipeline() to crash.

The ISV claims they have been using validation layers and this condition has not been reported. Could you check if this use case is covered, please?

**Comment by karl-lunarg** [comment]
<a href="https://github.com/chrisforbes"><img src="https://avatars1.githubusercontent.com/u/128877?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Thursday Jul 27, 2017 at 17:36 GMT_

----

This check is not yet implemented. The spec is slightly vague on how this restriction works -- is it a restriction on the number of distinct locations that may be used on an interface (but leaving the choice of which integers to use arbitrary), or is the intent that all location values used must be below the limit?

**Comment by karl-lunarg** [comment]
<a href="https://github.com/DominikWitczakAMD"><img src="https://avatars0.githubusercontent.com/u/17761066?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [DominikWitczakAMD](https://github.com/DominikWitczakAMD) (MIGRATED)**
_Friday Jul 28, 2017 at 05:54 GMT_

----

In our case it's the latter. Not sure about the others.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/chrisforbes"><img src="https://avatars1.githubusercontent.com/u/128877?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Monday Jul 31, 2017 at 18:24 GMT_

----

@DominikWitczakAMD I think that interpretation is reasonable, and I will use it when implementing the validation check, but we should get a spec wording tweak to make it absolutely clear.

**Comment by mark-lunarg** [comment]
A recent PR implemented checks against these input/output limits.
