### ISSUE TITLE
VkImageViewUsageCreateInfo errors

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-ValidationLayers#3701]
I have an image of format R16G16_FLOAT with usage including VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT, and then I'm creating a E5B9G9R9 imageview and using VkImageViewUsageCreateInfo to remove that bit, but I still get validation errors:

```
VUID-VkImageViewCreateInfo-usage-02652(ERROR / SPEC): msgNum: -946497048 - Validation Error: [ VUID-VkImageViewCreateInfo-usage-02652 ] Object 0: handle = 0x756aa0000000858, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0xc79599e8 | vkCreateImageView(): pCreateInfo->format VK_FORMAT_E5B9G9R9_UFLOAT_PACK32 with tiling VK_IMAGE_TILING_OPTIMAL does not support usage that includes VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT or VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT. The Vulkan spec states: If usage contains VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT, then the image view's format features must contain at least one of VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT or VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkImageViewCreateInfo-usage-02652)
```

**Valid Usage ID**
VUID-VkImageViewCreateInfo-usage-02652

**Environment:**
 - OS: linux
 - GPU: any
 - SDK or header version if building from repo: recent git checkout
 - Options enabled (synchronization, best practices, etc.): default

**Comment by sfricke-samsung** [comment]
I'm confused what the issue is, it seems you are mixing up `VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT` and `VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT`?

This VUID error is because you must have `VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT` set but your device doesn't support the optimal format feature bits for `VK_FORMAT_E5B9G9R9_UFLOAT_PACK32`

**Comment by zmike** [comment]
Ergh okay it's gonna be one of those weeks. Thanks!
