### ISSUE TITLE
VK_QCOM_fragment_density_map_offset: Add VUIDs

### ISSUE THREAD

**Issue by arpiagarwal** [KhronosGroup/Vulkan-ValidationLayers#3715]
Issue description:
Add validation layer support for VK_QCOM_fragment_density_map_offset extension.

Please include the valid usage IDs for the checks you are requesting:
VUID-VkFramebufferCreateInfo-renderPass-06502
VUID-VkSubpassFragmentDensityMapOffsetEndInfoQCOM-fragmentDensityMapOffsets-06503
VUID-VkSubpassFragmentDensityMapOffsetEndInfoQCOM-fragmentDensityMapAttachment-06504
VUID-VkSubpassFragmentDensityMapOffsetEndInfoQCOM-pDepthStencilAttachment-06505
VUID-VkSubpassFragmentDensityMapOffsetEndInfoQCOM-pInputAttachments-06506
VUID-VkSubpassFragmentDensityMapOffsetEndInfoQCOM-pColorAttachments-06507
VUID-VkSubpassFragmentDensityMapOffsetEndInfoQCOM-pResolveAttachments-06508
VUID-VkSubpassFragmentDensityMapOffsetEndInfoQCOM-pPreserveAttachments-06509
VUID-VkSubpassFragmentDensityMapOffsetEndInfoQCOM-fragmentDensityOffsetCount-06510
VUID-VkSubpassFragmentDensityMapOffsetEndInfoQCOM-fragmentDensityOffsetCount-06511
VUID-VkSubpassFragmentDensityMapOffsetEndInfoQCOM-x-06512
VUID-VkSubpassFragmentDensityMapOffsetEndInfoQCOM-y-06513
VUID-VkImageCreateInfo-fragmentDensityMapOffset-06514
VUID-VkImageCreateInfo-fragmentDensityMapOffset-06515

Any additional information:

**Comment by arpiagarwal** [comment]
I need to assign this to myself but can't figure it out. Can someone help? Thanks.

**Comment by spencer-lunarg** [comment]
all were added in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3716 - closing
