### ISSUE TITLE
Cannot build VVL with latest Vulkan-Headers

### ISSUE THREAD

**Issue by ianelliottus** [KhronosGroup/Vulkan-ValidationLayers#3734]
The Chromium autoroll of Vulkan components broke last Friday, because of Jon Leech's change from that day.

- Link to first Chromium change to break: https://chromium-review.googlesource.com/c/chromium/src/+/3439034
- Link to example of build failures: https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket/8823155286294776001/+/u/compile__with_patch_/stdout

**Comment by oddhack** [comment]
> This is a separate validation build issue caused by the video extension renaming a struct, I'll move it to the VVL repo where it will be addressed

OK. That sounds like just a consequence of the provisional extension changing its interfaces as they're allowed to.

**Comment by amaiorano** [comment]
> This is a separate validation build issue caused by the video extension renaming a struct, I'll move it to the VVL repo where it will be addressed

Hi @mikes-lunarg, I work on WebGPU at Google, and would like to know if you think this issue will be addressed fairly soon? As an interim solution, would it be possible to add an alias to the new struct name with the old name?

**Comment by oddhack** [comment]
> Hi @mikes-lunarg, I work on WebGPU at Google, and would like to know if you think this issue will be addressed fairly soon? As an interim solution, would it be possible to add an alias to the new struct name with the old name?

It sounds like you're running into the fact that these are provisional extensions which do not promise interface stability. You could ask the Vulkan Video TSG (who ultimately owns the definition of the video extensions) on the KhronosGroup/Vulkan-Docs repository if they're willing to support such a backwards-compatibility alias. But until the extensions are finalized, API changes can continue to happen.

**Comment by mikes-lunarg** [comment]
@amaiorano I have a fix running through CI now, it should be merged shortly.

Regarding the API instability, Vulkan-ValidationLayers builds with `VK_ENABLE_BETA_EXTENSIONS` to enable some features related to VK_KHR_portability_subset as well as to provide correct behavior for applications using other provisional extensions. We mitigate potential CI and build breakages internally by maintaining a pointer to the current compatible revision of Vulkan-Headers in [scripts/known_good.json](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/738a438c6a4a910ad57abc6a17e901a27b7b520d/scripts/known_good.json#L21). Such breakages are infrequent and typically only last a few days as we integrate a new header.

**Comment by amaiorano** [comment]
Thanks @mikes-lunarg, much appreciated.
