### ISSUE TITLE
Crash validating shader that uses OpConvertUToPtr with atomic operations

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-ValidationLayers#3735]
**Describe the Issue**
When validating an application that uses a shader module containing `OpConvertUToPtr` to generate a pointer later used with `OpAtomicUMax` the validation crashes inside `SHADER_MODULE_STATE::SpirvStaticData::SpirvStaticData`.

Specifically in the `default:` case when an atomic operation is encountered `module_state.get_def()` is called to get the pointer itself by ID, but that function doesn't find an entry in `def_index` and returns a pointer off the end of the array. The invalid iterator is then dereferenced leading to asserts and a crash in debug. It runs in release but likely only by coincidence as it's accessing off into undefined memory.

A shader that generates this issue is here in SPIR-V assembly form: [shader.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/8023369/shader.txt), it validates cleanly with the latest SPIR-V tools spirv-val, so I don't think the shader is in error. The shader will likely not run in any testbed that uses it, since it has a hardcoded GPU address (the shader is generated on the fly in application).

**Valid Usage ID**
N/A, no validation issues (the shader is fine itself, and validates correctly when this crash is avoided - see below).

**Environment:**
 - OS: Windows 10
 - GPU: nVidia RTX 2080 Ti
 - SDK or header version if building from repo: 1.3.204 (layers built from 738a438c6a4a910ad57abc6a17e901a27b7b520d)
 - Options enabled (synchronization, best practices, etc.): No extra options, only `VK_LAYER_KHRONOS_validation` layer enabled.

**Additional context**

Not fully understanding the code my guess is that the issue is that the `def_index` needs to be filled out with every result ID that is then later looked up, but there's no case for the result of `OpConvertUToPtr`. I added a simple `case spv::OpConvertUToPtr:` to the collection of `OpVariable` and `OpAccessChain` etc which store their result ID directly, and that seems to fix the issue for me. However without knowing the intention I don't know if that's the right solution, it's only a workaround I found that worked.

Bisecting, the problem seems to have started on 58b843521 but I don't know if that's the root cause or a coincidence due to code motion.

**Comment by sfricke-samsung** [comment]
So the `BuildDefIndex` function is a spot for improvement as it is manually just has instructions added. I tried to add what I thought was everything I would see in an atomic for https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/58b843521813d864d1900a3e1b1ed2ae296482be but I do think this is as simple as adding `OpConvertUToPtr` 

I also would try looking harder in the SPIR-V spec for what else can point to an atomic SSA chain and add tests for those as well

Happy to take this @ziga-lunarg btw
