### ISSUE TITLE
Image format feature checks applied to underlying image format, not view format

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-ValidationLayers#3736]
**Describe the Issue**
The application creates an image with `VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT` to allow view format casting and the base image format `VK_FORMAT_B8G8R8A8_SRGB`. I don't think the base format matters, only that it does _not_ support storage writes.

The application then creates an image view and performs a cast using the mutable format to the compatible format `VK_FORMAT_R32_UINT`. It then uses this view within a compute shader for formatless stores using `shaderStorageImageWriteWithoutFormat`. This is guaranteed to be supported for the `R32_UINT` format.

I get a validation message that the use is invalid because the format doesn't support the `VK_FORMAT_FEATURE_2_STORAGE_WRITE_WITHOUT_FORMAT_BIT` flag, however the driver _does_ report that flag for the view format R32_UINT as it is required to by the spec.

Since this requires going through a shader with writes to trigger I don't have a clean isolated sample demonstrating only this issue. If you do want to reproduce, you'd need the latest build of RenderDoc and also compile [this demos project](https://github.com/baldurk/renderdoc/blob/v1.x/util/test/demos.sln). It will require `glslc` in your path to run, so it's enough to have a version of the vulkan SDK installed.

If you run `demos_x64.exe VK_Overlay_Test` and capture it in RenderDoc, then save the capture and use 'File -> open capture with options' to enable API validation on replay, you should see this message. There are other validation issues which I'm looking into and in the process of fixing. If necessary I can make a clean test not using RenderDoc, but it can't be easily extracted.

**Valid Usage ID**
This fires on VUID-vkCmdDispatch-OpTypeImage-06423, as below:

> `[VUID-vkCmdDispatch-OpTypeImage-06423] Validation Error: [ VUID-vkCmdDispatch-OpTypeImage-06423 ] Object 0: handle = 0x6871490000000055, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; Object 1: handle = 0x1e6cc0000000220, name = Array -> MS destView, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x81c59101 | Descriptor set VkDescriptorSet 0x6871490000000055[] encountered the following validation error at vkCmdDispatch time: Descriptor in binding #2 index 0, VkImageView 0x1e6cc0000000220[Array -> MS destView], format VK_FORMAT_R32_UINT, doesn't contain VK_FORMAT_FEATURE_2_STORAGE_WRITE_WITHOUT_FORMAT_BIT_KHR The Vulkan spec states: Any VkImageView or VkBufferView being written as a storage image or storage texel buffer where the image format field of the OpTypeImage is Unknown must have image format features that support VK_FORMAT_FEATURE_2_STORAGE_WRITE_WITHOUT_FORMAT_BIT (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdDispatch-OpTypeImage-06423)`

**Environment:**
 - OS: Windows 10
 - GPU: nVidia RTX 2080 Ti (driver version 511.65)
 - SDK or header version if building from repo: 1.3.204 (layers built from 738a438c6a4a910ad57abc6a17e901a27b7b520d)
 - Options enabled (synchronization, best practices, etc.): No extra options, only `VK_LAYER_KHRONOS_validation` layer enabled.

**Additional context**

From what I can tell the issue here stems from the fact that in descriptor_sets.cpp the code loads the available feature bits from the underlying image state, which thus follow the underlying image's format: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/738a438c6a4a910ad57abc6a17e901a27b7b520d/layers/descriptor_sets.cpp#L1264

However the feature bits should be queried using the view's format, which is the one used effectively (as long as the cast is valid, and the image is mutable, etc). Changing the line to:

```
            const VkFormatFeatureFlags2KHR img_format_feats = image_view_state->format_features;
```

seems to fix the issue for me, though I'm only saying that because validation no longer complains :).

**Comment by sfricke-samsung** [comment]
So I think you are write and should just use the `VkImageView` format feature, but the spec says say "image format features" and curious if that was just an oversight in the spec VU not accounting for mutable formats

Will raise a Spec issue to double check

**Comment by llandwerlin-intel** [comment]
Looks like the write fix indeed, we meant the format to be what's in the view.

**Comment by sfricke-samsung** [comment]
Perfect thanks for the confirmation @llandwerlin-intel, I will add the fix then (in spec and VVL) and write a test to prevent regression!
