### ISSUE TITLE
Invalid error reported when sampling an isampler2D binding, to which a stencil-only image view created off a DS image is bound

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-ValidationLayers#374]
Consider the following shader:

```
#version 420

      (..stuff..)

layout(set = 0, binding = 0) uniform isampler2D stencil_sampler;

      (..stuff..)

void main()
{
    int stencil_value = textureLod(stencil_sampler, uv, 0.0).x;

    (..stuff..)
}
```

Let image X be a 320x240 2D image which uses D16_UNORM_S8_UINT format.
Let image view Ix be a 2Dimage view created from image X, encapsulating STENCIL aspect of X.

Image view is then bound to "stencil_sampler". At draw call time I get:

![image](https://user-images.githubusercontent.com/17761066/46608015-769ad880-cb03-11e8-9b3c-01592d97de2c.png)

..which is not valid since the IV I bound to the slot using a combined image sampler binding only encapsulates the stencil part which is SINT.

**Comment by tobine** [comment]
Hi @DominikWitczakAMD , I think there's an inconsistency in your description which I suspect it just a typo.  You wrote:

> since the IV I bound to the slot using a combined image sampler binding only encapsulates the stencil part which is SINT.

I'm guessing you meant to say that the stencil part is **UINT**, right?

**Comment by DominikWitczakAMD** [comment]
Fair point, will need to re-check. Will be back with you on this tomorrow the latest.

**Comment by DominikWitczakAMD** [comment]
Confirmed, app-side issue. Thanks :-)
