### ISSUE TITLE
Missing check for undefined pipeline when using multiview

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/Vulkan-ValidationLayers#3745]
**Describe the situation in which you encountered the missing validation**
Issue description:
If you are using multiview rendering, then the current pipeline binding is invalidated when you begin your RenderPass. This doensn't happen during a regular BeginRenderPass.
The validation layers fail to throw an error if you then try to render without binding a pipeline.

**Valid Usage IDs requested**
Please include the valid usage IDs for the checks you are requesting:

**Additional Context**
Any additional information:

**Comment by Tony-LunarG** [comment]
Triage
The spec says:
When multiview is enabled, at the beginning of each subpass all non-render pass state is undefined. In particular, each time vkCmdBeginRenderPass or vkCmdNextSubpass is called the graphics pipeline must be bound, any relevant descriptor sets or vertex/index buffers must be bound, and any relevant dynamic state or push constants must be set before they are used.

But I found no specific VUIDs regarding multiview and vkCmdBeginRenderPass or vkCmdNextSubpass unbinding all pipeline resources.

Playing with vklayertests_command.cpp: VkLayerTest.VerifyMaxMultiviewInstanceIndex, moving the vkCmdBindPipeline to before the BeginRenderPass does not elicit an additional validation error, whereas not binding the pipeline at all gets an expected 02700,  so state tracking does not unbind pipeline resources when BRP or NS are called with multiview enabled.

**Comment by aitor-lunarg** [comment]
Reopening until all resources are correctly tested.
