### ISSUE TITLE
Attachmentless renderpasses generate an invalid validation error at vkCreateGraphicsPipelines() call time if AMD_mixed_attachment_samples is enabled

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-ValidationLayers#375]
I don't have the infrastructure set up to propose a PR but the necessary fix seems to be trivial:

![image](https://user-images.githubusercontent.com/17761066/46609062-fe361680-cb06-11e8-8853-44fa60246fd4.png)

ANDing the check with (max_sample_count != 0) revokes the error.

**Comment by jzulauf-lunarg** [comment]
Triage Notes: max_sample_sample != 0 effectively implements the leading clause "If the subpass uses color and/or depth/stencil attachments" that needs to guard this test.   (see the for and if clauses just prior)

Adjacent to this in the spec are several related, but incomplete checks -- (that additional information gathering in the for and if clauses could allow implementation of, though factored out of the amd_... block)

* VUID-VkGraphicsPipelineCreateInfo-subpass-01411  (VK_NV_framebuffer_mixed_samples)
>  If subpass has a depth/stencil attachment and depth test, stencil test, or depth bounds test are enabled, then the rasterizationSamples member of pMultisampleState must be the same as the sample count of the depth/stencil attachment
* VUID-VkGraphicsPipelineCreateInfo-subpass-01412 (VK_NV_framebuffer_mixed_samples)
> If subpass has any color attachments, then the rasterizationSamples member of pMultisampleState must be greater than or equal to the sample count for those subpass attachments
* VUID-VkGraphicsPipelineCreateInfo-subpass-00757 (Core, i.e. neither AMD nor NV)
> If subpass uses color and/or depth/stencil attachments, then the rasterizationSamples member of pMultisampleState **must** be the same as the sample count for those subpass attachments

**Comment by jeffbolznv** [comment]
I think somebody at NVIDIA is implementing some of these checks. Might want to wait before spending time on this, to avoid duplicating effort.

**Comment by jzulauf-lunarg** [comment]
@jeffbolznv meaning 411 and 412, yes?

**Comment by jzulauf-lunarg** [comment]
@jeffbolznv  -- status update on the effort?

**Comment by mark-lunarg** [comment]
These checks have been implemented.
