### ISSUE TITLE
missing ASAN stack traces in vk_layer_validation_tests

### ISSUE THREAD

**Issue by jeremyg-lunarg** [KhronosGroup/Vulkan-ValidationLayers#3755]
**Describe the Issue**
ASAN is unable to report stack traces for leaks in the validation layer code. This is because the loader dlcloses() all layers (and probably icds as well) before ASAN has a chance to translate stack traces for all the leaks. 

**Valid Usage ID**
None

**Environment:**
 - OS:  Linux
 - GPU: any
 - SDK or header version if building from repo:
 - Options enabled (synchronization, best practices, etc.):

**Additional context**

**Comment by nisse-work** [comment]
I think it would make sense to have that dlopen call in the main() function (which appears to be in tests/tests/layer_validation_tests.cpp). Either unconditionally, or conditioned on some sanitizer preprocessor define, or a command line flag. Could also check for failure, and display a helpful message explaining how to use VK_LAYER_PATH or point to docs in case dlopen fails.

**Comment by juan-lunarg** [comment]
See latest asan work done by @charles-lunarg 

Thanks @charles-lunarg
