### ISSUE TITLE
Conditional jump or move depends on uninitialised value, in ObjectLifetimes::PreCallValidateQueueSubmit

### ISSUE THREAD

**Issue by nisse-work** [KhronosGroup/Vulkan-ValidationLayers#3760]
To detect problem, run 

`VK_LAYER_PATH=layers valgrind --leak-check=full ./tests/vk_layer_validation_tests --gtest_filter='VkPositiveLayerTest.QueueSubmitSemaphoresAndLayoutTracking'

Problem is this code in object_tracker.cpp, https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/9a307c998ff03fc4e3bfd10da8d30bd16624685e/layers/generated/object_tracker.cpp#L236:

```
            if (pSubmits[index0].pWaitSemaphores) {
                for (uint32_t index1 = 0; index1 < pSubmits[index0].waitSemaphoreCount; ++index1) {
                    skip |= ValidateObject(pSubmits[index0].pWaitSemaphores[index1], kVulkanObjectTypeSemaphore, false, "VUID-VkSubmitInfo-pWaitSemaphores-parameter", "VUID-VkSubmitInfo-commonparent");
                }
            }
```
I don't think pWaitSemaphores should be accessed at all if waitSemaphoreCount == 0. I would suggest deleting the if statement and just keep the loop, like

```
            for (uint32_t index1 = 0; index1 < pSubmits[index0].waitSemaphoreCount; ++index1) {
                skip |= ValidateObject(pSubmits[index0].pWaitSemaphores[index1], kVulkanObjectTypeSemaphore, false, "VUID-VkSubmitInfo-pWaitSemaphores-parameter", "VUID-VkSubmitInfo-commonparent");
            }
```

and similarly for pCommandBuffers and pSignalSemaphores pointers used in a similar fashion just after this block. I've had a quick look at object_tracker_generator.py, but I couldn't figure out how this code block is generated.

The valgrind error looks like this:

```
==1846733== Conditional jump or move depends on uninitialised value(s)
==1846733==    at 0x16ABA6FA: ObjectLifetimes::PreCallValidateQueueSubmit(VkQueue_T*, unsigned int, VkSubmitInfo const*, VkFence_T*) const (object_tracker.cpp:236)
==1846733==    by 0x16497E64: vulkan_layer_chassis::QueueSubmit(VkQueue_T*, unsigned int, VkSubmitInfo const*, VkFence_T*) (chassis.cpp:1147)
==1846733==    by 0x1FE3328: VkPositiveLayerTest_QueueSubmitSemaphoresAndLayoutTracking_Test::TestBody() (sync.cpp:368)
```

In sync.cpp, the first submitinfo entry is initialized as

```
    submit_info[0].sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    submit_info[0].pNext = nullptr;
    submit_info[0].commandBufferCount = 1;
    submit_info[0].pCommandBuffers = &cmd_bufs[0];
    submit_info[0].signalSemaphoreCount = 1;
    submit_info[0].pSignalSemaphores = &semaphore1;
    submit_info[0].waitSemaphoreCount = 0;
    submit_info[0].pWaitDstStageMask = nullptr;
    submit_info[0].pWaitDstStageMask = flags;
```

I.e., waitSemaphoreCount = 0, and pWaitSemaphores left uninitialized. I'm not really sure what the vulkan spec says, but I would really expect that value of pWaitSemaphores is completely ignored when waitSemaphoreCount = 0, and hence, this code in sync.cpp is correct.

**Comment by Tony-LunarG** [comment]
Fixed via #3791
