### ISSUE TITLE
Object tracking validation incorrect when using direct-to-display

### ISSUE THREAD

**Issue by gary-sweet** [KhronosGroup/Vulkan-ValidationLayers#377]
Applications using Direct-to-Display are asserting when unique object tracking validation is enabled due to bugs handling the `VkDisplayKHR` handles.

There is no single point of creation for the display handle when running direct-to-display; a number of
APIs return the same display handles. The existing code ends up wrapping the same `VkDisplayKHR` in multiple new unique_ids. The assert occurs because `GetDisplayPlaneSupportedDisplaysKHR()` tries to lookup a handle in the map that doesn't exist. There is a TODO in that function that says 
> What's going on here?

**Comment by gary-sweet** [comment]
Pull request with one possible fix here:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/379

**Comment by gary-sweet** [comment]
My PR to fix this wasn't doing the right thing, so I'll leave it to someone who knows the code better.

**Comment by Tony-LunarG** [comment]
Fixed with PR #439
