### ISSUE TITLE
Confusing best practices warning for API version mismatch

### ISSUE THREAD

**Issue by Ldash4** [KhronosGroup/Vulkan-ValidationLayers#3771]
**Describe the Issue**
When setting the `apiVersion` of `vkApplicationInfo` to `VK_MAKE_VERSION(1, 3, 0)`, with instance version `1.2.189` and device version `1.2.194`, I get the following warning:
`vkCreateDevice(): API Version of current instance, 1.3.0 (0x00403000) is higher than API Version on device, 1.2.194 (0x004020c2)`
([validation source](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/cb6d0ef7880c971644b53282735f3f398191231f/layers/best_practices_utils.cpp#L229))

Reading the [spec for VkApplicationInfo](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkApplicationInfo.html), it says the following:

> 
> The Khronos validation layers will treat apiVersion as the highest API version the application targets, and will validate API usage against the minimum of that version and the implementation version (instance or device, depending on context). If an application tries to use functionality from a greater version than this, a validation error will be triggered.
> 
> For example, if the instance supports Vulkan 1.1 and three physical devices support Vulkan 1.0, Vulkan 1.1, and Vulkan 1.2, respectively, and if the application sets apiVersion to 1.2, the application can use the following versions of Vulkan:
> 
>     Vulkan 1.0 can be used with the instance and with all physical devices.
> 
>     Vulkan 1.1 can be used with the instance and with the physical devices that support Vulkan 1.1 and Vulkan 1.2.
> 
>     Vulkan 1.2 can be used with the physical device that supports Vulkan 1.2.
> 
> If we modify the above example so that the application sets apiVersion to 1.1, then the application must not use Vulkan 1.2 functionality on the physical device that supports Vulkan 1.2.

This implies to me that it is valid to use `apiVersion = 1.3` despite not running a driver with 1.3 support. Why do I get this validation error?

**Environment:**
 - OS: Windows 10
 - GPU: GTX 1070
 - SDK or header version if building from repo: 1.3.204.0
 - Options enabled (synchronization, best practices, etc.): `VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT`

**Comment by Tony-LunarG** [comment]
From the Best Practices description:
When enabled, the Best Practices Object is intended to highlight potential performance issues, questionable usage patterns, common mistakes, and items **not specifically prohibited by the Vulkan specification** but that may lead to application problems.

You aren't getting a validation error, you are getting a best practices warning, presumably under the "questionable usage pattern" aspect.  Querying the device for the api level supported and using that is probably a better best practice.  As you said, you are not violating the spec, and you are not getting a validation error.

**Comment by Ldash4** [comment]
Alright, that makes sense. But the way I read it (again from the same spec page)
> apiVersion must be the highest version of Vulkan that the application is designed to use

Doesn't this imply that the best practice is actually to use a constant apiVersion, and handle the cases where the eventual instance/device version are lower?

**Comment by Tony-LunarG** [comment]
Yes, use the api version your application desires with fallback code for when it isn't available.

**Comment by charles-lunarg** [comment]
Unfortunately, I think this is actually a 'bug' in best practices. The API version is set at instance creation time, not at device creation. The application has to set the instance version well before they could have queried the device version.

**Comment by charles-lunarg** [comment]
Upon further discussion, I believe this should instead be downgraded to INFO level, not warning. 
It *is* useful to know that the created instance has a higher instance version than what the device supports. When debugging 'what version does my app have' is not always straightforward, especially to developers who don't realize that the apiVersion set in instance creation isn't the *device* version used, just the highest level that the app supports. I will create a PR to change this.
