### ISSUE TITLE
Invalid dynamic rendering validation...

### ISSUE THREAD

**Issue by unit-a-user** [KhronosGroup/Vulkan-ValidationLayers#3805]
**Describe the Issue**
Despite of error, `pDepthStencilState` and `pColorBlendState` has and valid, or there is no additional validation details... 

**Valid Usage ID**
Look to log...

**Environment:**
 - OS: Windows 11
 - GPU: NVIDIA RTX 2070 
 - SDK or header version if building from repo: 1.3.204.1
 - Options enabled (synchronization, best practices, etc.):

**Additional context**
```
Vulkan Debug Error: Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-renderPass-06053 ] Object 0: handle = 0x1b736479ed0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x247dedb2 | vkCreateGraphicsPipelines(): Pipeline 0 has fragment state and a depth format (VK_FORMAT_D32_SFLOAT_S8_UINT) or stencil format (VK_FORMAT_D32_SFLOAT_S8_UINT) and an invalid pDepthStencilState structure The Vulkan spec states: If renderPass is VK_NULL_HANDLE, the pipeline is being created with fragment shader state, and either of VkPipelineRenderingCreateInfo::depthAttachmentFormat or VkPipelineRenderingCreateInfo::stencilAttachmentFormat are not VK_FORMAT_UNDEFINED, pDepthStencilState must be a valid pointer to a valid VkPipelineDepthStencilStateCreateInfo structure (https://vulkan.lunarg.com/doc/view/1.3.204.1/windows/1.3-extensions/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-renderPass-06053)
Vulkan Debug Error: Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-renderPass-06054 ] Object 0: handle = 0x1b736479ed0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6882ec30 | vkCreateGraphicsPipelines(): Pipeline 0 has VkPipelineRenderingCreateInfoKHR::colorAttachmentCount (2) and an invalid pColorBlendState structure The Vulkan spec states: If renderPass is VK_NULL_HANDLE, the pipeline is being created with fragment output interface state, and VkPipelineRenderingCreateInfo::colorAttachmentCount is not equal to 0, pColorBlendState must be a valid pointer to a valid VkPipelineColorBlendStateCreateInfo structure (https://vulkan.lunarg.com/doc/view/1.3.204.1/windows/1.3-extensions/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-renderPass-06054)
```

**Comment by ziga-lunarg** [comment]
Thanks for reporting the issue @unit-a-user. I wrote a test to try and replicate it here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3806
But I do not receive the error messages. Can you provide more details, are `pColorBlendState` and `pDepthStencilState` in your `VkGraphicsPipelineCreateInfo` valid pointers? What are the values in them?

**Comment by krOoze** [comment]
I can replicate based on https://stackoverflow.com/questions/71331173/why-is-this-color-blend-state-invalid-vulkan.

**Comment by krOoze** [comment]
@unit-a-user Do you also use `rasterizerDiscardEnable`?

**Comment by ziga-lunarg** [comment]
@krOoze Thanks for pointing that out, setting `rasterizerDiscardEnable` does also cause my test to report those error messages.

**Comment by krOoze** [comment]
The layers seem relatively liberal with the spec, or perhaps the spec is too vague.

Spec says:

> and the pipeline is being created with fragment output interface state

where "fragment output interface state" is defined as `VkPipelineColorBlendStateCreateInfo` + `alphaToCoverageEnable` + `alphaToOneEnable` + `VkRenderPass` + subpass.

That does seem like a circular logic in the VU statement.

Meanwhile the layers liberally interpret this as:

```
(pPipeline->active_shaders & VK_SHADER_STAGE_FRAGMENT_BIT)
```

**Comment by ziga-lunarg** [comment]
Thanks, I'll wait for clarification.

**Comment by spencer-lunarg** [comment]
I think #5102 closed this, if not let me know and we can reopen
