### ISSUE TITLE
2 crashes, 49 failures on AMD Radeon 6800 XT

### ISSUE THREAD

**Issue by lunarpapillo** [KhronosGroup/Vulkan-ValidationLayers#3820]
**Describe the Issue**
We want to add the **AMD Radeon 6800 XT** on Windows to CI validation tests.  2 tests currently crash with `STATUS_ACCESS_VIOLATION`:
- `VkLayerTest.CreatePipelineCheckFragmentShaderBarycentricEnabled`
- `VkLayerTest.CopyInvalidImageMemory`

and 49 tests fail:
- `VkLayerTest.InvalidPipelineDepthClipControlFeatureDisable`
- `VkLayerTest.GraphicsPipelineStageCreationFeedbackCount`
- `VkLayerTest.ComputePipelineStageCreationFeedbackCount`
- `VkLayerTest.ComputeSharedMemoryOverLimit`
- `VkLayerTest.TestShaderZeroInitializeWorkgroupMemory`
- `VkLayerTest.CreateGraphicsPipelineNullRenderPass`
- `VkLayerTest.BufferExtents`
- `VkLayerTest.InvalidUsageBits`
- `VkLayerTest.BlitImageFormatTypes`
- `VkLayerTest.InvalidBarriers`
- `VkLayerTest.Sync2InvalidBarriers`
- `VkLayerTest.Sync2InvalidBarrierQueueFamily`
- `VkLayerTest.InvalidImageLayout`
- `VkLayerTest.UnnormalizedCoordinatesSeparateSampler`
- `VkLayerTest.CreateImageViewMissingYcbcrConversion`
- `VkLayerTest.BlockTexelViewInvalidFormat`
- `VkLayerTest.ImageViewMinLodFeature`
- `VkLayerTest.PrivateDataFeature`
- `VkLayerTest.SpecLinks`
- `VkLayerTest.RequiredPromotedFeaturesExtensions`
- `VkLayerTest.ValidateCmdBuildAccelerationStructuresKHR`
- `VkLayerTest.ObjInUseCmdBuildAccelerationStructureKHR`
- `VkLayerTest.ValidateExtendedDynamicStateDisabled`
- `VkLayerTest.ValidateExtendedDynamicStateEnabledNoMultiview`
- `VkLayerTest.ValidateExtendedDynamicState2Disabled`
- `VkLayerTest.WriteTimeStampInvalidQuery`
- `VkLayerTest.QueueSubmit2KHRUsedButSynchronizaion2Disabled`
- `VkLayerTest.ValidateCreateSamplerWithBorderColorSwizzle`
- `VkLayerTest.RenderPassCreateInvalidSubpassDependencies`
- `VkLayerTest.InvalidCmdBufferDescriptorSetImageSamplerDestroyed`
- `VkLayerTest.DepthStencilResolveMode`
- `VkLayerTest.InvalidDeviceGroupRenderArea`
- `VkLayerTest.Sync2SecondaryCommandbufferAsPrimary`
- `VkLayerTest.CompressedImageMipCopyTests`
- `VkLayerTest.CopyImageTypeExtentMismatch`
- `VkLayerTest.MeshShaderDisabledNV`
- `VkLayerTest.DrawWithoutUpdatePushConstants`
- `VkLayerTest.BadRenderPassContentsWhenCallingCmdExecuteCommandsWithBeginRenderPass`
- `VkLayerTest.BadExecuteCommandsSubpassIndices`
- `VkLayerTest.IncompatibleRenderPassesInExecuteCommands`
- `VkLayerTest.TransferImageToSwapchainWithInvalidLayoutDeviceGroup`
- `VkLayerTest.TestCreatingWin32Surface`
- `VkLayerTest.CmdWaitEvents2KHRUsedButSynchronizaion2Disabled`
- `VkLayerTest.Sync2FeatureDisabled`
- `VkGpuAssistedLayerTest.GpuBufferDeviceAddressOOB`
- `VkPositiveLayerTest.ClearRectWith2DArray`
- `VkPositiveLayerTest.WriteTimestampNoneAndAll`
- `VkPositiveLayerTest.RenderPassSingleMipTransition`
- `VkPositiveLayerTest.QueueSubmitTimelineSemaphore2Queue`

These tests are being disabled in CI; but they should all be evaluated to determine whether each one is an issue in validation code, an issue in a validation test, or a driver issue (which would mean that VVL should change test code to skip the affected test if being run on the broken device).  When all the failing tests have been repaired, the CI list of disabled tests can be emptied and this issue resolved.

**Environment:**
 - OS: **Windows 10** (`tcwinamd2`)
 - GPU: **AMD Radeon 6800 XT**

**Comment by lunarpapillo** [comment]
This text result file shows all the messages produced by the test failures and crashes above:
[blacklist.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/8210534/blacklist.txt)

**Comment by ziga-lunarg** [comment]
Which driver is used? Those 2 tests that crash work fine on my 6700 XT

**Comment by lunarpapillo** [comment]
> Which driver is used? Those 2 tests that crash work fine on my 6700 XT

What's your driver, for comparison purposes?
```
	"VkPhysicalDeviceProperties": {
		"apiVersion": 4202684,
		"driverVersion": 8388806,
		"vendorID": 4098,
		"deviceID": 29631,
		"deviceType": 2,
		"deviceName": "AMD Radeon RX 6800 XT",
```
**Device Manager** says:
- Driver Date: 10/18/2021
- Driver Version: 30.0.13023.1012

if either of those are helpful.  We can update the driver if that will fix some or all of the issues.

**Comment by ziga-lunarg** [comment]
```GPU0:
VkPhysicalDeviceProperties:
---------------------------
        apiVersion        = 4206795 (1.3.203)
        driverVersion     = 8388821 (0x8000d5)
        vendorID          = 0x1002
        deviceID          = 0x73df
        deviceType        = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
        deviceName        = AMD Radeon RX 6700 XT
        pipelineCacheUUID = 77983319-f03c-5b84-a53e-e8f9a26f2b50```
        
Driver Date: 22/01/2022
Driver Version: 30.0.14023.4005

**Comment by ziga-lunarg** [comment]
I installed an older driver and it crashes now, so I'll take a look

**Comment by ziga-lunarg** [comment]
The test `VkLayerTest.CreatePipelineCheckFragmentShaderBarycentricEnabled` crashes with an older driver, but it does look like a driver bug. The other tests all pass for me, even with 3 different older drivers.

**Comment by ncesario-lunarg** [comment]
@lunarpapillo is it possible to use a newer driver and generate a new list of failures? Does the driver you're currently using support dynamic rendering?

**Comment by lunarpapillo** [comment]
@ncesario-lunarg 
> is it possible to use a newer driver and generate a new list of failures?
Yes, of course.  I'll install the one @ziga-lunarg mentioned unless you suggest otherwise.

> Does the driver you're currently using support dynamic rendering?
That's `VK_KHR_dynamic_rendering`, right?  I don't think so, but you can see the device's `vulkaninfo` here: http://erusea:8080/view/Manual/job/manual-Vulkan-ValidationLayers/805/artifact/vulkantest-results/vulkaninfo.json

**Comment by ncesario-lunarg** [comment]
> That's VK_KHR_dynamic_rendering, right?

Correct.

I'd say let's move to the latest driver version (assuming that's the one Ziga was using?). Sounds like that will get rid of most of the failures, and effectively double our coverage for dynamic rendering tests.

**Comment by lunarpapillo** [comment]
The latest seems to be after Ziga's:
- Driver Date: 2/23/2022
- Driver Version: 30.0.14029.5006

I'll start a new blacklist exercise and see what's changed.

Note that changing the driver can break old traces; @johnzupin and I will verify whether traces are broken later (as the machine is not quite yet ready for trace testing, though John has already captured a few traces).

**Comment by lunarpapillo** [comment]
With the new driver (newer than Ziga's), I see 5 crashes (!!!) and 23 failures.  The results of the exercise (a list of all tests that failed, and their output) is attached:
[blacklist.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/8228116/blacklist.txt)

**Comment by ziga-lunarg** [comment]
@lunarpapillo The first test in the blacklist says `Unexpected: Validation Error: [ UNASSIGNED-CoreValidation-Shader-MaxComputeSharedMemorySize ]`, but this message is not active in the latest validation layers, it's commented out. 

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/core_validation_error_enums.h#L174

**Comment by lunarpapillo** [comment]
> @lunarpapillo The first test in the blacklist says `Unexpected: Validation Error: [ UNASSIGNED-CoreValidation-Shader-MaxComputeSharedMemorySize ]`, but this message is not active in the latest validation layers, it's commented out.

I don't think it matters...?  Just let me know when you think all the project and test fixes are in (including skipping tests that are believed to exhibit driver issues), and I'll remove the external blacklist and try again.

**Comment by ziga-lunarg** [comment]
How are you able to get the message? Is it not running latest master code?

And out of these test only VkGpuAssistedLayerTest.GpuBufferDeviceAddressOOB crashes for me, as discussed with @Tony-LunarG this one should remain black listed. 

The rest of the tests pass for me now.

**Comment by lunarpapillo** [comment]
I was running `master` on all my test runs.  We could do a full investigation of why the exact runs I saw provoked that message, but I don't think it would be terribly useful.

> VkGpuAssistedLayerTest.GpuBufferDeviceAddressOOB ... should remain black listed.

Usually tests that are known to fail on a particular device are blacklisted internally with the `IsPlatform()` VVL function, yes?  Has this test been internally blacklisted, or is there a reason not to do so?

**Comment by ziga-lunarg** [comment]
It probably is a waste of time to try to figure that out, I just don't see how it's possible. 

You are correct, I will update it.

**Comment by lunarpapillo** [comment]
I tried a run with the external blacklist off.  I saw the GPU OOB failure, but also one other: http://erusea:8080/view/Manual/job/manual-Vulkan-ValidationLayers/808/console
```
...
[ RUN      ] VkLayerTest.DynamicRenderingGraphicsPipelineCreateInfo
C:\j\m0\Vulkan-ValidationLayers\tests\vkrenderframework.cpp(196): error: Failed
Did not receive expected error 'VUID-VkGraphicsPipelineCreateInfo-renderPass-06062'
[  FAILED  ] VkLayerTest.DynamicRenderingGraphicsPipelineCreateInfo (91 ms)
...
[  PASSED  ] 1239 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] VkLayerTest.DynamicRenderingGraphicsPipelineCreateInfo
[  FAILED  ] VkGpuAssistedLayerTest.GpuBufferDeviceAddressOOB
```
I presume you're not seeing that failure?

**Comment by ziga-lunarg** [comment]
No, it passes fine for me.

**Comment by ziga-lunarg** [comment]
Can you try if #3846 fixes this test for you?

**Comment by lunarpapillo** [comment]
WTF... You're using a slightly different driver, 30.0.14023.4005, right?  Or did you update to the same one CI is using: 30.0.14029.5006 ?

**Comment by ziga-lunarg** [comment]
30.0.14029.5006 is what I have now.

**Comment by lunarpapillo** [comment]
I tried with `ziga-fix-06062-test`, but I still show the same failure:
```
tcwinamd2> cd work\KhronosGroup\Vulkan-ValidationLayers
> git log -n 1
commit 682e861de77f0ff148d80ed7bad7f7e57208506a (HEAD -> ziga-fix-06062-test,
ziga-lunarg/ziga-fix-06062-test)
Author: ziga-lunarg <ziga@lunarg.com>
Date:   Wed Mar 16 00:31:45 2022 +0100

    tests: Fix dynamic rendering color attachment test
> build\tests\Release\vk_layer_validation_tests.exe --gtest_filter=VkLayerTest.DynamicRenderingGraphicsPipelineCreateInfo
Note: Google Test filter = VkLayerTest.DynamicRenderingGraphicsPipelineCreateInfo
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from VkLayerTest
[ RUN      ] VkLayerTest.DynamicRenderingGraphicsPipelineCreateInfo
C:\Users\lunarg\work\KhronosGroup\Vulkan-ValidationLayers\tests\vkrenderframework.cpp(196): error: Failed
Did not receive expected error
'VUID-VkGraphicsPipelineCreateInfo-renderPass-06062'
C:\Users\lunarg\work\KhronosGroup\Vulkan-ValidationLayers\tests\vkrenderframework.cpp(196): error: Failed
Did not receive expected error 'VUID-VkGraphicsPipelineCreateInfo-flags-06482'
C:\Users\lunarg\work\KhronosGroup\Vulkan-ValidationLayers\tests\vkrenderframework.cpp(196): error: Failed
Did not receive expected error 'VUID-VkGraphicsPipelineCreateInfo-flags-06483'
[  FAILED  ] VkLayerTest.DynamicRenderingGraphicsPipelineCreateInfo (390 ms) 
[----------] 1 test from VkLayerTest (394 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (408 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] VkLayerTest.DynamicRenderingGraphicsPipelineCreateInfo

 1 FAILED TEST
 ```

**Comment by lunarpapillo** [comment]
Do you think there may be some other change in your developer build that I don't have?  It's possible there is a device difference between your 6700 XT and the 6800 XT in CI, but I think that's unlikely...

If you want to investigate directly on the CI machine, use the KVM https://kvm to get to `tcwinamd2`.  There's already a work window up that you can use.

**Comment by lunarpapillo** [comment]
@ziga-lunarg and I investigated differing results between Release and Debug builds; he figured out one more fix that was needed: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3857

**Comment by lunarpapillo** [comment]
This Release run on Ziga's fix branch with the **VulkanTests** blacklist deliberately disabled: http://erusea:8080/view/Manual/job/manual-Vulkan-ValidationLayers/809/console
```
INFO: set VK_LAYER_PATH=C:\j\m0\Vulkan-ValidationLayers\build\layers\Release
INFO: cd C:\j\m0\Vulkan-ValidationLayers
INFO: executing #8: C:\j\m0\Vulkan-ValidationLayers\build\tests\Release\vk_layer_validation_tests.exe --gtest_catch_exceptions=0
INFO: testing validation tests (VK_LAYER_FINE_GRAINED_LOCKING=1)...
INFO: set VK_LAYER_PATH=C:\j\m0\Vulkan-ValidationLayers\build\layers\Release
INFO: executing #9: C:\j\m0\Vulkan-ValidationLayers\build\tests\Release\vk_layer_validation_tests.exe --gtest_catch_exceptions=0 --gtest_filter=*Thread*
INFO: Tests PASS
INFO: -- Finished test after 3.09 minutes (185.19 seconds)
INFO: Test run complete after 9.45 minutes (567.21 seconds)
```
and this Debug run on the same branch: http://erusea:8080/view/Manual/job/manual-Vulkan-ValidationLayers/810/console
```
INFO: set VK_LAYER_PATH=C:\j\m0\Vulkan-ValidationLayers\dbuild\layers\Debug
INFO: cd C:\j\m0\Vulkan-ValidationLayers
INFO: executing #8: C:\j\m0\Vulkan-ValidationLayers\dbuild\tests\Debug\vk_layer_validation_tests.exe --gtest_catch_exceptions=0
INFO: testing validation tests (VK_LAYER_FINE_GRAINED_LOCKING=1)...
INFO: set VK_LAYER_PATH=C:\j\m0\Vulkan-ValidationLayers\dbuild\layers\Debug
INFO: executing #9: C:\j\m0\Vulkan-ValidationLayers\dbuild\tests\Debug\vk_layer_validation_tests.exe --gtest_catch_exceptions=0 --gtest_filter=*Thread*
INFO: Tests PASS
INFO: -- Finished test after 8.94 minutes (536.62 seconds)
INFO: Test run complete after 14.42 minutes (865.06 seconds)
```
show that this issue has been fixed.  As soon as that PR merges, **VulkanTests** can remove its blacklist entries for the Radeon 6800 XT device and allow **Vulkan-ValidationLayers** to run all tests on the device.
