### ISSUE TITLE
segfault dynamic rendering best practices 

### ISSUE THREAD

**Issue by ynnuW** [KhronosGroup/Vulkan-ValidationLayers#3829]
**Describe the Issue**
Vulkan app segfaults while enabling best practices validation when using dynamic rendering. https://github.com/SaschaWillems/Vulkan dynamic rendering example as test case. Does not segfault when best practices layer isn't enabled

**Environment:**
 - OS: Gentoo linux
 - GPU: AMD Fury
 - SDK or header version if building from repo: 1.3.204
 - Options enabled (synchronization, best practices, etc.): `VK_LAYER_ENABLES=VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT:VALIDATION_CHECK_ENABLE_VENDOR_SPECIFIC_AMD` `VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation`

**Additional context**
Output of my own code using valgrind  (SaschaWillems/Vulkan dynamic rendering example takes to long in valgrind).
```
==16827== Conditional jump or move depends on uninitialised value(s)
==16827==    at 0x14331BFF: BestPractices::ValidateCmdDrawType(VkCommandBuffer_T*, char const*) const (best_practices_utils.cpp:2031)

==16827== Invalid read of size 8
==16827==    at 0x14331C12: BestPractices::ValidateCmdDrawType(VkCommandBuffer_T*, char const*) const (best_practices_utils.cpp:2035)
==16827==    by 0x14331E6E: BestPractices::PreCallValidateCmdDraw(VkCommandBuffer_T*, unsigned int, unsigned int, unsigned int, unsigned int) const (best_practices_utils.cpp:2080)

==16827== Process terminating with default action of signal 11 (SIGSEGV)
==16827==  Access not within mapped region at address 0x40
==16827==    at 0x14331C12: BestPractices::ValidateCmdDrawType(VkCommandBuffer_T*, char const*) const (best_practices_utils.cpp:2035)
==16827==    by 0x14331E6E: BestPractices::PreCallValidateCmdDraw(VkCommandBuffer_T*, unsigned int, unsigned int, unsigned int, unsigned int) const (best_practices_utils.cpp:2080)
```

**Comment by ynnuW** [comment]
This doesn't happen anymore with latest commit

**Comment by ziga-lunarg** [comment]
Just tested myself, #3815 fixes this.
