### ISSUE TITLE
Descriptor set matching errors for (image, sampler) / combined-image-sampler mismatches

### ISSUE THREAD

**Issue by gnl21** [KhronosGroup/Vulkan-ValidationLayers#385]
The CTS (`dEQP-VK.spirv_assembly.instruction.graphics.image_sampler.imagefetch.combined_image_sampler_separate_descriptors.pass_sampler_to_function.shader_frag`) uses both an image and a sampler variable pointed to the same combined-image-sampler descriptor. This seems to be allowed but produces validation errors of the form:
> Descriptor set 0x12a2394 bound as set #0 encountered the following validation error at vkCmdDraw() time: Descriptor in binding #0 at global descriptor index 0 requires (none) component type, but bound descriptor format is VK_FORMAT_R32G32B32A32_SFLOAT.

The code is getting `req = 0` (presumably because the image part of the binding is unused?) but this generates the format mismatch with the image that is actually bound.

**Comment by chrisforbes** [comment]
This is going to require some work in shader validation to get the edge cases right. @mark-lunarg do you want it, or shall I take it?

**Comment by locke-lunarg** [comment]
fixed in [PR #1148 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1148)
