### ISSUE TITLE
ValidateCmdCopyBufferBounds additional checks

### ISSUE THREAD

**Issue by Eearslya** [KhronosGroup/Vulkan-ValidationLayers#3853]
**Describe the Issue**
When validating the copy regions within `vkCmdCopyBuffer`, the validation layer has a few gotchas that will slip through the cracks and fail to raise the alarm.

1) All of the checks performed by `ValidateCmdCopyBufferBounds` use `>` or `<` with no equality checks, so any copy regions that exactly line up with one another will not trigger.
Example: `srcOffset = 0, dstOffset = 0, size = 32` - Overlapping region 0-31.

2) All of the checks validate between source and destination only. This means it's possible to have overlapping destinations without raising an alarm.
Example: `srcOffset = 0, dstOffset = 64, size = 32` and `srcOffset = 32, dstOffset = 80, size = 32` - Overlapping region 80-95.

**Valid Usage ID**
VUID-vkCmdCopyBuffer-pRegions-00117

**Environment:**
 - OS: Windows 10 Pro 64-bit
 - GPU: Intel UHD Graphics 630
 - SDK or header version if building from repo: 1.3.206
 - Options enabled (synchronization, best practices, etc.): Best practices

**Additional context**

**Comment by ziga-lunarg** [comment]
For your second point, the VUID says:

> The union of the source regions, and the union of the destination regions, specified by the elements of pRegions, must not overlap in memory

So it does not say destination regions must not overlap.

**Comment by Eearslya** [comment]
I suppose that's fair. I feel it's possible to interpret that wording either way. That said, I can't see how two overlapping destinations would produce well-defined behavior, if the implementation chose to do them in parallel. Maybe a failure on the VUID's part.

Thanks for the fix, in any case!

**Comment by ziga-lunarg** [comment]
I believe it would say "The union of source and destinations regions" in that case. Thanks for bringing up the issue!
