### ISSUE TITLE
Add support for CMake toolchain file in update_deps.py to ease cross compilation

### ISSUE THREAD

**Issue by oliver-sc** [KhronosGroup/Vulkan-ValidationLayers#3866]
Hi,

I need to cross compile the Vulkan validation layers for a ARM64 Linux target system. Therefore, I need to set the  -DCMAKE_TOOLCHAIN_FILE command line option when invoking cmake.
The script **update_deps.py** doesn't support to set this cmake command line option.
Can you please add support for this.

You can find my modified **update_deps.py** in the linked pull request.

Regards,
Oliver

**Comment by oliver-sc** [comment]
Related pull request: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3865

**Comment by juan-lunarg** [comment]
@oliver-sc as a temporary measure to handle this issue you can also now set CMAKE_TOOLCHAIN_FILE as an environment variable and this will propagate to update_deps.py

**Comment by juan-lunarg** [comment]
It does requires 3.21 however:
https://cmake.org/cmake/help/latest/envvar/CMAKE_TOOLCHAIN_FILE.html
