### ISSUE TITLE
Core validation: Crash if AMD_mixed_attachment_samples is enabled and app attempts to create a GFX pipeline with disabled rasterization

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-ValidationLayers#387]
Crash originates from here:

![image](https://user-images.githubusercontent.com/17761066/46681941-a245bd80-cbec-11e8-894a-aa8625ab7277.png)

**Comment by jzulauf-lunarg** [comment]
Looks like the need for defensive coding on the log_msg path.  Needs a test case to ensure that there isn't another failure masked behind that crash.

@DominikWitczakAMD -- anything you could share suitable for a test case?

**Comment by jzulauf-lunarg** [comment]
@Tony-LunarG

**Comment by Tony-LunarG** [comment]
Fixed with PR #394
