### ISSUE TITLE
Documentation not available for vulkan 1.3

### ISSUE THREAD

**Issue by Razordor** [KhronosGroup/Vulkan-ValidationLayers#3875]
**Describe the Issue**
Validation layers are appended with links that lead to sites that say the following:
"Documentation not available for Windows version 1.3.204.1"

**Valid Usage ID**
VUID-VkImageCreateInfo-imageType-00957(ERROR / SPEC): msgNum: -1376796787 - Validation Error: [ VUID-VkImageCreateInfo-imageType-00957 ] Object 0: handle = 0x1e9bfef51c0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xadefbf8d | vkCreateImage(): if pCreateInfo->imageType is VK_IMAGE_TYPE_2D, pCreateInfo->extent.depth must be 1. The Vulkan spec states: If imageType is VK_IMAGE_TYPE_2D, extent.depth must be 1 (https://vulkan.lunarg.com/doc/view/1.3.204.1/windows/1.3-extensions/vkspec.html#VUID-VkImageCreateInfo-imageType-00957)
    Objects: 1
       [0]  0x1e9bfef51c0, type: 3, name: NULL

**Environment:**
 - OS: Windows 10
 - GPU: GTX 980
 - SDK or header version if building from repo: 1.3.204.1
 - Options enabled (synchronization, best practices, etc.): General, Validation, Performance

**Additional context**
N/A

**Comment by Eearslya** [comment]
Changing `1.3-extensions` to `1.2-extensions` makes the URL work. Looks like the webserver didn't get set up with the new directory.
