### ISSUE TITLE
Dynamic Rendering: Not checking layerCount when viewMask is 0

### ISSUE THREAD

**Issue by JerNeth** [KhronosGroup/Vulkan-ValidationLayers#3887]
**Describe the situation in which you encountered the missing validation**
Issue description:
Calling vkCmdBeginRendering with a VkRenderingInfo where the layerCount is 0 and the viewmask is 0 is not caught by the validation layers.

**Valid Usage IDs requested**
Please include the valid usage IDs for the checks you are requesting:
VUID-VkRenderingInfo-viewMask-06069

**Environment:**
OS: Windows
GPU: RTX 3080
SDK or header version if building from repo: 1.3.204.1
Options enabled (synchronization, best practices, etc.): default

**Additional Context**
Any additional information:

**Comment by ziga-lunarg** [comment]
This has already been fixed in #3868
