### ISSUE TITLE
crash in "VkLayer_khronos_validation.dll"  [assert.(hazard.tag < access_log_.size())]

### ISSUE THREAD

**Issue by firesgc** [KhronosGroup/Vulkan-ValidationLayers#3892]
**Describe the Issue**

Hello!

when I enable synchronization validation in my project, I get a crash in "VkLayer_khronos_validation.dll".  For this reason I downloaded and compiled the source code of "Vulkan-ValidationLayer binaries for 1.3.204.1 SDK release".

This is the corresponding assertion:
Assertion failed: tag < access_log_.size(), file D:\GitHub\Vulkan-ValidationLayers-sdk-1.3.204.1\layers\synchronization_validation.cpp, line 267. 
The hazard. tag has the value -1 (0xffffffffffff) and the message in out is "(usage: SYNC_IMAGE_LAYOUT_TRANSITION, prior_usage: SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE, write_barriers: 0" before it stops working.

Thank you for your help!

**Valid Usage ID**
none

**Environment:**
 - OS: Windows 11
 - GPU: 1080 TI
 - SDK or header version if building from repo: Vulkan-ValidationLayer 1.3.204.1
 - Options enabled (synchronization, best practices, etc.): Validation -> Sychronization Preset

**Comment by ziga-lunarg** [comment]
Thanks for reporting the issue, is it possible to get the full stack trace? And what is your application doing at the time of the crash?

**Comment by firesgc** [comment]
Hello!
I'm just rendering a depth prepass to fill the zbuffer before I render the color with a more expensive shader.

Callstack:
`VkLayer_khronos_validation.dll!CommandBufferAccessContext::FormatUsage(const HazardResult & hazard) Line 267	C++
 	VkLayer_khronos_validation.dll!RenderPassAccessContext::ValidateFinalSubpassLayoutTransitions(const CommandExecutionContext & ex_context, const char * func_name) Line 2553	C++
 	VkLayer_khronos_validation.dll!RenderPassAccessContext::ValidateEndRenderPass(const CommandExecutionContext & ex_context, const char * func_name) Line 2514	C++
 	VkLayer_khronos_validation.dll!SyncOpEndRenderPass::Validate(const CommandBufferAccessContext & cb_context) Line 6434	C++
 	VkLayer_khronos_validation.dll!SyncValidator::ValidateCmdEndRenderPass(VkCommandBuffer_T * commandBuffer, const VkSubpassEndInfo * pSubpassEndInfo, CMD_TYPE cmd) Line 3904	C++
 	VkLayer_khronos_validation.dll!SyncValidator::PreCallValidateCmdEndRenderPass(VkCommandBuffer_T * commandBuffer) Line 3910	C++
 	VkLayer_khronos_validation.dll!vulkan_layer_chassis::CmdEndRenderPass(VkCommandBuffer_T * commandBuffer) Line 3732	C++
 	care.launcher.exe!vk::CommandBuffer::endRenderPass<vk::DispatchLoaderStatic>(const vk::DispatchLoaderStatic & d) Line 5462	C++
 	care.launcher.exe!ModuleBackendVK::CommandBufferVK::CmdGraphicsEndPipeline(ModuleBackendVK::CommandBufferVK::FrameState & aState, void * aData) Line 326	C++
`

I saw that I have a probably added an incorrect (I need to read the docs again :)) VkSubpassDependency to my RenderPass. I am only rendering one pass and when I remove the VkSubpassDependency I no longer get a validation error.

I hope this helps!
