### ISSUE TITLE
vulkan 1.1: Incorrect core_validation error when using mixed color/depth sample count

### ISSUE THREAD

**Issue by quadgod420** [KhronosGroup/Vulkan-ValidationLayers#390]
I think I'm hitting a validation error, or spec is wrong.

Trying to create a renderpass w/ Vulkan 1.1, where color attachment is VK_SAMPLE_COUNT_1_BIT, and depth stencil is VK_SAMPLE_COUNT_4_BIT.

I am getting the error:
[ VUID-VkAttachmentDescription-samples-parameter ] Object: VK_NULL_HANDLE (Type = 0) | vkCreateRenderPass():  Subpass 0 attempts to render to attachments with inconsistent sample counts. The Vulkan spec states: samples must be a valid VkSampleCountFlagBits value (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkAttachmentDescription-samples-parameter)

However, based on the vulkan 1.1 spec, I think this should be legal:

> All attachments in pColorAttachments that are not VK_ATTACHMENT_UNUSED must have a sample count that is **smaller than or equal** to the sample count of pDepthStencilAttachment if it is not VK_ATTACHMENT_UNUSED

This contrasts from the Vulkan 1.0 spec, that states:

> If pDepthStencilAttachment is not VK_ATTACHMENT_UNUSED and any attachments in pColorAttachments are not VK_ATTACHMENT_UNUSED, they must have the **same** sample count

.. which in this case for 1.0, the validation error would be correct.

Thanks

**Comment by chrisforbes** [comment]
This is still the same in unextended 1.1 (https://www.khronos.org/registry/vulkan/specs/1.1/html/vkspec.html). The spec you were looking at has the AMD mixed sample counts rules folded in.

**Comment by quadgod420** [comment]
I see.. Confusing since the validation layers linked me to the extended spec. Closing.

**Comment by chrisforbes** [comment]
I agree that's kindof awful. Very hard to see from the extended spec where anything came from, too :(
