### ISSUE TITLE
Checks for vkCmdDraw-None-06538 don't consider whether an attachment is readonly

### ISSUE THREAD

**Issue by austinEng** [KhronosGroup/Vulkan-ValidationLayers#3932]
**Describe the Issue**
With an update to the vulkan validation layers, we recently started seeing VVL failures that appear to be incorrect. Getting errors like:
> Warning: Validation Error: [ VUID-vkCmdDraw-None-06538 ] Object 0: handle = 0x93aa30000093aa3, name = Dawn_BindGroup, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; Object 1: handle = 0x939990000093999, name = Dawn_InternalTextureView, type = VK_OBJECT_TYPE_IMAGE_VIEW; Object 2: handle = 0x93aa70000093aa7, type = VK_OBJECT_TYPE_FRAMEBUFFER; Object 3: handle = 0x939980000093998, name = Dawn_InternalTextureView, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0xebe11aa0 | Descriptor set VkDescriptorSet 0x93aa30000093aa3[Dawn_BindGroup] encountered the following validation error at vkCmdDraw time: Image subresources of VkImageView 0x939990000093999[Dawn_InternalTextureView] is being read from in Descriptor in binding #1 index 0 and will be written to as VkImageView 0x939980000093998[Dawn_InternalTextureView] in VkFramebuffer 0x93aa70000093aa7[] attachment # 1 overlap. The Vulkan spec states: If any recorded command in the current subpass will write to an image subresource as an attachment, this command must not read from the memory backing that image subresource in any other way than as an attachment (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdDraw-None-06538)

In the test that hit the error, I did some debugging and found the test uses two render passes. the first one writes to the texture view, then in a separate render pass, it reads from it as a readonly attachment and samples from it simultaneously.

I checked that the second render pass is indeed using VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL. So there should not be a read+write conflict.

Validation is coming from this commit.

https://chromium.googlesource.com/external/github.com/KhronosGroup/Vulkan-ValidationLayers.git/+/498b7e7971c37b54709bcf8ccfa847cfb054aee5%5E%21/

```
+                bool write_attachment =
+                    (subpass.usage & (VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT)) > 0;
+                if (write_attachment && readable) {
```

I would think that write_attachment should include a check for whether the layout of the attachment is readonly.

**Valid Usage ID**
[vkCmdDraw-None-06538](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdDraw-None-06538)

**Environment:**
 - OS: Linux
 - GPU: GTX 1660 + Intel HD Graphics 630
 - SDK or header version if building from repo: VVL commit 755d34faa108fa385a4f59e1b942e8ca9f56bdef
 - Options enabled (synchronization, best practices, etc.):

**Additional context**
https://bugs.chromium.org/p/chromium/issues/detail?id=1310052#c3

**Comment by ziga-lunarg** [comment]
Your error message says that `VkImageView` is being read from a descriptor and written to as an attachment at the same time, is that the case?

**Comment by austinEng** [comment]
It is used as an attachment with layout `VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL`, and it's being sampled from. It is not written to as an attachment since the layout is readonly.

**Comment by ziga-lunarg** [comment]
Thanks, I will take a look.
