### ISSUE TITLE
Possible false positive for dual source blending

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/Vulkan-ValidationLayers#3973]
**Describe the Issue**
I started getting the following error with our game that uses dual source blending:

VK ERROR : VALIDATION - Message Id Number: -2141630828 | Message Id Name: VUID-RuntimeSpirv-Fragment-06427
	Validation Error: [ VUID-RuntimeSpirv-Fragment-06427 ] Object 0: handle = 0xecf38c000000c23f, type = VK_OBJECT_TYPE_PIPELINE; | MessageID = 0x80594e94 | vkCmdDrawIndexed: Dual source blend mode is used, but the number of written fragment shader output attachment (2) is greater than maxFragmentDualSrcAttachments (1) The Vulkan spec states: When blending is enabled and one of the dual source blend modes is in use, the maximum number of output attachments written to in the Fragment {ExecutionModel} must be less than or equal to maxFragmentDualSrcAttachments (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-RuntimeSpirv-Fragment-06427)

It appears this started with commit ce62ca5dec7e07e359dac6f37a285db65db167a8

On NVIDIA, the value of maxFragmentDualSrcAttachments is one.  What the code is doing is checking on the number of fragment shader output variables and comparing it against maxFragmentDualSrcAttachments.

This would effectively disable dual source blending because the fragment shader has to write to a second output for example for SRC1_COLOR.  I'm not sure how to interpret the spec language "the maximum number of output attachments written to in the Fragment Execution Model must be less than or equal to [maxFragmentDualSrcAttachments](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#limits-maxFragmentDualSrcAttachments)" but my suspicion is that this is intented to check against the number of bound colorAttachments in the renderPass and not the number of outputs in the shader?

**Valid Usage ID**
VUID-RuntimeSpirv-Fragment-06427 

**Environment:**
 - OS:  Windows
 - GPU: NVIDIA
 - SDK or header version if building from repo: 208
 - Options enabled (synchronization, best practices, etc.): VK_LAYER_khronos_validation

**Additional context**

**Comment by sjfricke** [comment]
I added that VU a while ago to the spec (with the related ones next to it), looking into if I messed that up and needs spec fix, sorry for the churn :disappointed:

**Comment by ziga-lunarg** [comment]
The language under 29.1.2 is a lot more clear:

> The maximum number of color attachments that can be used in a subpass when using dual-source blending functions is implementation-dependent and is reported as the maxFragmentDualSrcAttachments member of VkPhysicalDeviceLimits.
