### ISSUE TITLE
Need to correctly check memory overlap

### ISSUE THREAD

**Issue by aitor-lunarg** [KhronosGroup/Vulkan-ValidationLayers#3993]
**Describe the Issue**
We currently don't correctly check memory overlap for the mentioned VUIDs.

**Valid Usage ID**

- [x] VUID-vkCmdCopyBuffer-pRegions-00117
- [x] VUID-VkCopyBufferInfo2-pRegions-00117
- [x] VUID-vkCmdCopyImage-pRegions-00124
- [x] VUID-VkCopyImageInfo2-pRegions-00124
- [x] VUID-vkCmdBlitImage-pRegions-00217
- [x] VUID-VkBlitImageInfo2-pRegions-00217
- [ ] VUID-vkCmdResolveImage-pRegions-00255 (Not yet implemented)
- [x] VUID-vkCmdCopyBufferToImage-pRegions-00173 (Not yet implemented)
- [x] VUID-vkCmdCopyImageToBuffer-pRegions-00184 (Not yet implemented)
- [ ] VUID-VkSparseImageMemoryBind-memory-01104 (covered in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4047)

**Environment:**
 - OS: Any
 - GPU: Any
 - SDK or header version if building from repo: Any
 - Options enabled (synchronization, best practices, etc.): None

**Additional context**
If there's any missing VUIDs, please edit the issue to add them

**Comment by aitor-lunarg** [comment]
I'll copy my thoughts on the issue that I mentioned on a PR regarding this:

```
My main concern is that for non-linear images, there's no way to get how they are stored in memory due to being implementation specific, and vulkan cannot provide that information (or at least that's how I understand it). I've used these parts of the specification to reach the conclusion:
https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSubresourceLayout.html
https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#glossary-linear-resource

The good thing about the VUID we are trying to cover (VUID-vkCmdCopyBuffer-pRegions-00117 and similars) is how they are described The union of all destination regions, specified by the elements of pRegions, must not overlap in memory with any texel that may be sampled during the blit operation. The interesting part is the may. Which allow us to be conservative and say: well since we don't know how non-linear textures are stored in memory due to being implementation specific, we assume the whole texture as potentially sampled. Allowing us to use the description to our advantage. (We may also drop the VUID from error to warning if we take the mentioned approach?)
```

**Comment by Rua** [comment]
The synchronization validation has to deal with this too, and I believe it tries to be specific if it can, and falls back to courser checks when it doesn't have enough information. Some of the techniques used there could probably be used here too.

**Comment by spencer-lunarg** [comment]
all VUs have  been added and the 2 that aren't are tracked in other more related issues
