### ISSUE TITLE
Add validation for VK_EXT_primitives_generated_query

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-ValidationLayers#3994]
**Describe the situation in which you encountered the missing validation**
Issue description: New extension

**Valid Usage IDs requested**
06687 and 06689 are in #3950
06708 is in #3944 
06688 is in #3951 
06709 is in #3966
06694 and 06695 is in #4010
#4016 = 06690, 06691, 06692, 06693, 06696

**Comment by spencer-lunarg** [comment]
These are all in now - closing
