### ISSUE TITLE
Note disturbed descriptors when unbound set used

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#40]
**Issue by [tobine](https://github.com/tobine) (MIGRATED)**
_Tuesday Aug 22, 2017 at 20:15 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2022_

----

We had a previous perf warning for disturbed descriptors, along with associate test. Developers didn't like this perf warning (See #2020 ) so we removed it. As an enhancement, track disturbed descriptors and if a disturbed descriptor is used while unbound, note that it's unbound due to previously being disturbed.

**Comment by tobine** [comment]
Migrated to #24 tracking issue.
