### ISSUE TITLE
Core Validation: Image to buffer copies don't handle texel block size for single plane "_422" image formats

### ISSUE THREAD

**Issue by TomCoo** [KhronosGroup/Vulkan-ValidationLayers#400]
When checking buffer bounds in image to buffer copies, the required buffer size must account for the texel block size for compressed or single plane "_422" image formats.

**Comment by TomCoo** [comment]
Fix is in https://github.com/TomCoo/Vulkan-ValidationLayers/commit/98f149665946a4295084851d57b3cbbef9bc9923

**Comment by jzulauf-lunarg** [comment]
Fix merged https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/401
