### ISSUE TITLE
`ValidateRenderPassCompatibility` is incorrect/incomplete

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-ValidationLayers#4029]
In the spec section "Render Pass Compatibility", it says:
> Two render passes are compatible if their corresponding color, input, resolve, and depth/stencil attachment references are compatible and if they are otherwise identical except for:
> - Initial and final image layout in attachment descriptions
> - Load and store operations in attachment descriptions
> - Image layout in attachment references

The `ValidateRenderPassCompatibility` function in the code checks if the flags are identical, and if the attachment references in subpasses are compatible. But it does not check that the attachment descriptions themselves are compatible (same length, identical other than the mentioned items), and it does not check that subpass dependencies or correlated view masks are identical at all.

**Comment by ziga-lunarg** [comment]
I cannot find where the spec says that subpass dependencies and correlated view masks must be identical.

Also attachment descriptions do seem to be validated in `CoreChecks::ValidateAttachmentCompatibility`, where all members that do not fall under exceptions are validated. 

And `UNASSIGNED-CoreValidation-DrawState-InvalidRenderpass` catches the case where the are different number of attachments.

**Comment by Rua** [comment]
The section I quoted says "if they are otherwise identical". So that includes all parts of the render pass configuration other than those mentioned.

**Comment by ziga-lunarg** [comment]
You're right, thanks! I'll take a look.
