### ISSUE TITLE
incorrect validation for sampler unnormalized coordinates

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-ValidationLayers#4042]
The descriptor validation VUID 02702 (e.g., `VUID-vkCmdDispatch-None-02702`) is incorrectly validating normalized coordinates in samplers.

According to the spec:

```
If the VkPipeline object bound to the pipeline bind point used by this command accesses a
VkSampler object that uses unnormalized coordinates, that sampler must not be used to
sample from any VkImage with a VkImageView of the type VK_IMAGE_VIEW_TYPE_3D,
VK_IMAGE_VIEW_TYPE_CUBE, VK_IMAGE_VIEW_TYPE_1D_ARRAY, VK_IMAGE_VIEW_TYPE_2D_ARRAY or
VK_IMAGE_VIEW_TYPE_CUBE_ARRAY, in any shader stage
```

However, it's possible for an app to use a combined sampler with unnormalized coordinates for texelFetch operations with all of these image view types, and the sampler will never be accessed, which should be considered valid usage. Thus, for such cases, I believe VVL should be checking with the shader to determine whether the sampler is truly being accessed.

**Comment by sjfricke** [comment]
I agree with you 100% that doing a texelFetch operation should not be touching the sampler object and therefore be valid, I guess my next fun question would be "is there CTS for this" to guarantee no driver will blow up if given this situation

**Comment by zmike** [comment]
Definitely a good q. I'd assume not? I'm told LunarG has documented all existing validation errors in CTS, so if there's documented cases of this error, then that could be a start in determining the existence of such tests.

**Comment by ncesario-lunarg** [comment]
@Tony-LunarG have you happened upon 02702 when running CTS?

**Comment by Tony-LunarG** [comment]
I see no 02702 errors in my latest logfile

**Comment by zmike** [comment]
So then I guess there is no CTS for this. Does there need to be? It seems like that's unrelated given the sampler shouldn't even be used.

**Comment by ncesario-lunarg** [comment]
Having a CTS test for this might be good, but seems orthogonal. This just looks like a shader validation deficiency in VVL. Looks like we need to add something along the lines of "IsSamplerAccessed" (or siimlar query) to `SHADER_MODULE_STATE` and add that check to https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/567a5be7485ffd5e2d1b33fb8eab9bc6ab5b3531/layers/descriptor_validation.cpp#L1365.
