### ISSUE TITLE
VUID-VkMemoryAllocateInfo-allocationSize-00638(ERROR / SPEC): when using VkImportMemoryWin32HandleInfoKHR

### ISSUE THREAD

**Issue by BeastLe9enD** [KhronosGroup/Vulkan-ValidationLayers#4060]
**Describe the Issue**
I'm importing a ```ID3D12Resource``` into Vulkan, and for that I'm using a ```VkImportMemoryWin32HandleInfoKHR```, I get a validation message:
```
VUID-VkMemoryAllocateInfo-allocationSize-00638(ERROR / SPEC): msgNum: 830614613 - Validation Error: [ VUID-VkMemoryAlloc
ateInfo-allocationSize-00638 ] Object 0: handle = 0x165cdd30040, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x31822c55
| vkAllocateMemory: allocationSize is 0. The Vulkan spec states: allocationSize must be greater than 0 (https://vulkan.l
unarg.com/doc/view/1.3.211.0/windows/1.3-extensions/vkspec.html#VUID-VkMemoryAllocateInfo-allocationSize-00638)
    Objects: 1
        [0] 0x165cdd30040, type: 3, name: NULL
```

**The spec says:**
If the parameters define an import operation and the external handle type is ```VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_BIT```, ```VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_KMT_BIT```, or ```VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_RESOURCE_BIT```, ```allocationSize``` is ignored. The implementation must query the size of these allocations from the OS.

So in my opinion it must be valid to let ```allocationSize``` be 0.

My code example:
```CPP
VkImportMemoryWin32HandleInfoKHR import_memory_win32_handle_info = {
    .sType = VK_STRUCTURE_TYPE_IMPORT_MEMORY_WIN32_HANDLE_INFO_KHR,
    .handleType = VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_RESOURCE_BIT,
    .handle = handle
};
VkMemoryAllocateInfo memory_allocate_info = {
    .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
    .pNext = &import_memory_win32_handle_info
};

VkDeviceMemory memory;
throw_if_failed(vkAllocateMemory(device, &memory_allocate_info, nullptr, &memory), "vkAllocateMemory");
```

**Environment:**
 - OS: Windows 10
 - GPU: NVIDIA GeForce RTX 3090
 - SDK or header version if building from repo: 1.3.204.0
 - Options enabled (synchronization, best practices, etc.): /

**Comment by ziga-lunarg** [comment]
I think this requires a spec clarification, because the VUID does not mention this exception.

**Comment by ncesario-lunarg** [comment]
I think there is precedence for ignoring such fields in the `VkGraphicsPipelineCreateInfo` struct (e.g., see the constructor for `safe_VkGraphicsPipelineCreateInfo`), and the spec is pretty clear this should be ignored in this particular case, so it seems like we _should_ be ignoring this particular field. That said, this isn't a pointer we can just "ignore if it's null;" I think the assumption that `allocationSize > 0` is baked into a lot of other code that we have, so this may not be a simple fix.

**Comment by sjfricke** [comment]
so ` VUID-VkMemoryAllocateInfo-pNext-01874` (and I think ` VUID-VkMemoryAllocateInfo-allocationSize-04750`) are used to allow non-zero `allocationSize` for Android and Fuchsia platforms doing external format imports. I don't think the Fuchsia code is added, but we do skip over this VUID for AHB

```cpp
 if (IsExtEnabled(device_extensions.vk_android_external_memory_android_hardware_buffer)) {
        skip |= ValidateAllocateMemoryANDROID(pAllocateInfo);
    } else {
        if (0 == pAllocateInfo->allocationSize) {
            skip |= LogError(device, "VUID-VkMemoryAllocateInfo-allocationSize-00638", "vkAllocateMemory: allocationSize is 0.");
        };
    }
```

so I imagine if this is the correct behavior desired in Windows (not sure, but if it is) then we can replace `IsExtEnabled(device_extensions.vk_android_external_memory_android_hardware_buffer)` with some `zeroAllocationSizeAllowed` variable in the state tracking (since one day Fuchsia will probably want it too)

**Comment by ncesario-lunarg** [comment]
That sounds like a good idea @sjfricke. 

@ziga-lunarg if that's something you're interested in taking on, please go ahead and assign it to yourself, otherwise I'll grab this.
