### ISSUE TITLE
`khronos_validation.printf_to_stdout` seems not work

### ISSUE THREAD

**Issue by Inori** [KhronosGroup/Vulkan-ValidationLayers#4074]
`khronos_validation.printf_to_stdout` seems not work on my machine.

The validation messages shows that I'm using the correct settings file and other options works right (like `khronos_validation.enables`).

Only the `printf_to_stdout` seems doesn't make sense.
Whether I set it to `true` or `false`, I got debug messages from both debug callback and stdout.

Vulkan SDK version: 1.3.211.0

`printf_to_stdout = true`:
![QQ截图20220503095617](https://user-images.githubusercontent.com/6732524/166394197-bf48b80d-13d0-4ced-9008-ae9af959037e.jpg)

`printf_to_stdout = false`:
![QQ截图20220503095328](https://user-images.githubusercontent.com/6732524/166394200-c8177abc-4dc3-4f2f-bb2c-2983a0200fee.jpg)

I've already commented out `std::cerr` line in my debug callback (and yes I've registered it and it is getting called), I should expect no output, right?

_Originally posted by @Inori in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2464#issuecomment-1115533818_

**Comment by Inori** [comment]
OK, I figured it out.
I should remove 'VK_DBG_LAYER_ACTION_LOG_MSG' from `khronos_validation.debug_action ` and this way I can control the stdout.
But a new problem occurs, when I removed `VK_DBG_LAYER_ACTION_LOG_MSG`, debug printf seems only work when `printf_to_stdout` is `true`. 
When I set it to `false`, I got message saying `buffer size that was too small`, even I set `printf_buffer_size = 65535`

**Comment by Tony-LunarG** [comment]
I'm not quite sure what you are seeing.

With everything set to default, you should see debug printf messages, among other messages, going to the Debug Utils callback. This looks like your second screenshot above - notice that the extra debug information when the printfs go through the callback.

With everything set to default, except for khronos_validation.printf_to_stdout = true you should see all but the debug printf messages going to the callback, and debug printf messages going to stdout  This looks like your first screenshot where only the debug printf text is sent and no debug info is attached.

You shouldn't need to change khronos_validation.debug_action from it's default to see debug printf messages on stdout or in the callback.

I do see that some of your shaders are failing validation. Debug printf will not instrument shaders that fail validation, and you won't get any debug printf messages from them when they run.

The value of printf_to_stdout should have no effect on the buffer size required to receive debug printf messages.

Aside from validation messages being printed from your callback with your cerr line commented out, which I can't explain, it looks like everything is working as expected.

**Comment by Inori** [comment]
Ok, I see, thanks for your reply.

**Comment by Tony-LunarG** [comment]
@Inori I'm on break this week but I should be able to more closely consider your first issue early next week.
One suggestion I have for now is that maybe you can limit the number of messages by conditionally using invocation ID to decide whether to print or not. 
Also, you can increase memory available for debug printf using vkconfig or a layers settings file.  The printf_buffer_size variable sets the size in bytes for each debug printf buffer (per draw / dispatch).

As for not receiving subsequent messages, there is only one debug printf buffer per draw, so if previous messages exhaust the available memory, subsequent messages will not appear - could that be what's happening?
Alternatively, are you sure that the subsequent messages are in a path executed by the shader invocation?

**Comment by Inori** [comment]
Limit message count using invocation ID together with a very big `printf_buffer_size` (over 65535) solves the problem.
Previously I though there must be something wrong, but it is really just `not enough buffer size.`
Thanks very much!
