### ISSUE TITLE
Should it check VUID-vkCmdPipelineBarrier2-synchronization2-03848 for VK_KHR_synchronization2?

### ISSUE THREAD

**Issue by locke-lunarg** [KhronosGroup/Vulkan-ValidationLayers#4080]
When I enable VK_KHR_synchronization2, instead of using Vk 1.3, and then run vkCmdPipelineBarrier2KHR, should it also check `VUID-vkCmdPipelineBarrier2-synchronization2-03848:The synchronization2 feature must be enabled`?

**Comment by ncesario-lunarg** [comment]
@jeremyg-lunarg @jzulauf-lunarg?

**Comment by locke-lunarg** [comment]
Now. it checks. But I think it shouldn't.

**Comment by jeremyg-lunarg** [comment]
With 1.2 + VK_KHR_synchronization2 you are supposed to set that value in VkPhysicalDeviceSynchronization2Features and include that structure in the pNext change of your vkCreateDevice() call.

**Comment by locke-lunarg** [comment]
@jeremyg-lunarg  You're right. Thanks.
