### ISSUE TITLE
vkCmdDrawIndirectCount is not allowed when using dynamic rendering but it should be

### ISSUE THREAD

**Issue by danielmaciel** [KhronosGroup/Vulkan-ValidationLayers#4085]
Calling vkCmdDrawIndirectCount when using dynamic rendering causes the following validation error:

VUID-vkCmdDrawIndirectCount-renderpass(ERROR / SPEC): msgNum: -1348211859 - Validation Error: [ VUID-vkCmdDrawIndirectCount-renderpass ] Object 0: handle = 0x3b20350, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xafa3eb6d | vkCmdDrawIndirectCount: This call must be issued inside an active render pass. The Vulkan spec states: This command must only be called inside of a render pass instance (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdDrawIndirectCount-renderpass)
    Objects: 1
        [0] 0x3b20350, type: 6, name: NULL

The spec has several references to vkCmdBeginRendering so it allows it to be used with dynamic rendering. It seems to be both a spec and validation bug.

 - OS: Ubuntu 22.04
 - GPU: Radeon 6800 XT
 - Building from sources, GIT SHA 33d806c64ee86f556048e3ecf289f8557b6c582f

**Comment by danielmaciel** [comment]
Sorry I realized I made a mistake, there is no bug.

**Comment by ncesario-lunarg** [comment]
👍 those are the best kind of issues :)
