### ISSUE TITLE
Core Validation: No error reported for a missing subpass->external dependency

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#41]
**Issue by [DominikWitczakAMD](https://github.com/DominikWitczakAMD) (MIGRATED)**
_Tuesday Aug 29, 2017 at 08:12 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2038_

----

Let X be an universal queue (ie. a queue coming from a queue family that supports both compute and graphics ops).

Now, let's consider two command buffers:

1) Command buffer A which uses a renderpass with a single subpass. Within the subpass, a draw call is issued which triggers fragment shader invocations. The invocations use image store ops to write data to an image. The last command recorded to cmd buffer A sets event 1.
2) Command buffer B uses a compute shader which reads data via image load ops from the image as above. Before the dispatch call is made, the cmd buffer waits on event 1.

Both command buffers are submitted to the same universal queue.

For these cmd buffers to work as expected, an explicit subpass->external dependency is needed, because a) the implicit subpass->external dep does not include shader_write access mask, b) the modified image needs not be defined as a RP attachment.

Core Validation does not inform about this omission.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/mark-lunarg"><img src="https://avatars2.githubusercontent.com/u/7252958?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mark-lunarg](https://github.com/mark-lunarg) (MIGRATED)**
_Tuesday Aug 29, 2017 at 19:03 GMT_

----

@tobine, if this doesn't kinda fall under your sync changes, just assign back to me.

**Comment by mark-lunarg** [comment]
Moved to the Synchronization tracking issue, #72.

**Comment by mark-lunarg** [comment]
Moved wrong issue!
