### ISSUE TITLE
depth stencil read only attachment validation errors

### ISSUE THREAD

**Issue by HuYuxin** [KhronosGroup/Vulkan-ValidationLayers#4137]
We are seeing these two validation errors in ANGLE tests after merging this CL: [e23f82fc84c891b3a34e6e8787913b335cbe3934](https://chromium.googlesource.com/external/github.com/KhronosGroup/Vulkan-ValidationLayers.git/+/e23f82fc84c891b3a34e6e8787913b335cbe3934). 
VUID-VkGraphicsPipelineCreateInfo-renderPass-06039
VUID-VkGraphicsPipelineCreateInfo-renderPass-06040 

Example:
Test: dEQP.GLES31/functional_primitive_bounding_box_depth_builtin_depth_global_state_bbox_equal

VVL error: 
[ VUID-VkGraphicsPipelineCreateInfo-renderPass-06039 ] Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-renderPass-06039 ] Object 0: handle = 0x563646551d90, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7054092e | Invalid Pipeline CreateInfo[0] State: VkPipelineDepthStencilStateCreateInfo::depthWriteEnable is VK_TRUE, while the layout of the depth aspect of the depth/stencil attachment in the render pass is VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL. The Vulkan spec states: If renderPass is not VK_NULL_HANDLE, the pipeline is being created with fragment shader state, and subpass uses a depth/stencil attachment in renderPass with a read-only layout for the depth aspect in the VkAttachmentReference defined by subpass, the depthWriteEnable member of pDepthStencilState must be VK_FALSE (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-renderPass-06039)

Would you please help us determine if there is a bug in the validation layer change? We believe the validation error thrown here is not matching with what the test does: the depth stencil attachment used in the test is not read-only.

**Comment by ShabbyX** [comment]
In particular, the issue seems to be that VVL is validating the pipeline state against the render pass the pipeline is _created_ with, instead of the render pass it is _used_ with. They don't have to be the same as long as they are compatible, and the attachment layouts used in the render pass are not part of the render pass compatibility.

**Comment by sjfricke** [comment]
> the pipeline state against the render pass the pipeline is **created** with, instead of the render pass it is **used** with. 

Well this VU is at pipeline creation time, so if you think it should be a render pass compatibility thing, then the VU will need to be moved to a draw time VU

**Comment by ncesario-lunarg** [comment]
I second @sjfricke's comment. We can revert if this is blocking and it can be confirmed that the spec is incorrect, but it looks like the validation is implemented to spec currently. We can also move the check to draw time (or maybe bind pipeline time?) if it makes sense, but it would be good to at least get a request for the spec change first.

**Comment by ShabbyX** [comment]
Let's follow up once https://gitlab.khronos.org/vulkan/vulkan/-/issues/3110 is resolved.

**Comment by spencer-lunarg** [comment]
update, this is now `VUID-vkCmdDraw-None-06886` and `VUID-vkCmdDraw-None-06887` and now just missing the Validation layer change
