### ISSUE TITLE
Using perprimitiveNV in fragment shader produces a validation error requiring SPV_NV_mesh_shader

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/Vulkan-ValidationLayers#414]
The following fragment shader:

```
#version 450

#extension GL_NV_mesh_shader: require 

layout(location = 0) out vec4 outputColor;

layout(location = 0) perprimitiveNV in vec3 triangleNormal;

void main()
{
	outputColor = vec4(triangleNormal * 0.5 + 0.5, 1.0);
}
```

Produces the following validation error when creating the shader module:

```
ERROR:  [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object: VK_NULL_HANDLE (Type = 0) | SPIR-V module not valid: 2nd operand of Decorate: operand 5271 requires one of these extensions: SPV_NV_mesh_shader
  OpDecorate %triangleNormal PerPrimitiveNV
```

Mesh shaders are enabled using the VK_NV_mesh_shader extension and VkPhysicalDeviceMeshShaderFeaturesNV::meshShader is set to true in the vkCreateDevice chain.

**Comment by jzulauf-lunarg** [comment]
@jeffbolznv  @chrisforbes -- look like like something in your intersection.

**Comment by chrisforbes** [comment]
This sounds like a GLSL compiler bug. The compiler should be emitting OpExtension SPV_NV_mesh_shader in this case, and appears not to be.

**Comment by zeux** [comment]
Yes - I think you're right. I didn't look at this closely enough, I've hit issues before where validation layers didn't communicate extension status to validator but in this case it looks like the SPIRV just doesn't have the correct extension declared, only source extension. I'll open a bug in glslang. Thanks!

**Comment by zeux** [comment]
It looks like it might have been fixed in glslang master, just not with the version that ships with latest Vulkan SDK.

**Comment by sparmarNV** [comment]
https://github.com/KhronosGroup/glslang/pull/1507 incorrectly error out use of NV_mesh_shader in fragment shaders.
@zeux can you file a glslang issue for this and assign me? It should be a simple fix.

**Comment by zeux** [comment]
@sparmarNV Filed https://github.com/KhronosGroup/glslang/issues/1541 - thanks! I'm closing this issue in favor of the glslang issue.
