### ISSUE TITLE
Validation issue with vktWsiSurfaceTests.cpp:querySurfaceCounterTest

### ISSUE THREAD

**Issue by math4origami** [KhronosGroup/Vulkan-ValidationLayers#4145]
**Describe the Issue**
This is a test in Vulkan CTS, https://github.com/KhronosGroup/VK-GL-CTS/blob/main/external/vulkancts/modules/vulkan/wsi/vktWsiSurfaceTests.cpp#L234.

It first creates a surface.  For example, for XLIB, it calls `createXlibSurfaceKHR()`, https://github.com/KhronosGroup/VK-GL-CTS/blob/main/external/vulkancts/framework/vulkan/vkWsiUtil.cpp#L197
This starts here in Validation:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/generated/chassis.cpp#L6019
```
CreateXlibSurfaceKHR() {
  auto layer_data = GetLayerDataPtr(get_dispatch_key(instance), layer_data_map);
```

Then, it tries to get some properties for the surface using `getPhysicalDeviceSurfaceCapabilities2EXT()`:
https://github.com/KhronosGroup/VK-GL-CTS/blob/main/external/vulkancts/framework/vulkan/vkWsiUtil.cpp#L402
Which is here in Validation:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/generated/chassis.cpp#L9632
```
GetPhysicalDeviceSurfaceCapabilities2EXT() {
  auto layer_data = GetLayerDataPtr(get_dispatch_key(physicalDevice), layer_data_map);
```

These API's layer_data are keyed to different instances. This results in two distinct instances of ThreadSafety, with distinct counter<VkSurface>. One stores the new surface:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/generated/thread_safety.cpp#L4535
```
ThreadSafety::PostCallRecordCreateXlibSurfaceKHR() {
  CreateObjectParentInstance(*pSurface);
```
while the other tries to look it up:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/generated/thread_safety.cpp#L6639
```
ThreadSafety::PreCallRecordGetPhysicalDeviceSurfaceCapabilities2EXT() {
  StartReadObjectParentInstance(surface, "vkGetPhysicalDeviceSurfaceCapabilities2EXT");
```
and fails at:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/generated/thread_safety.h#L143
```
class counter {
  std::shared_ptr<ObjectUseData> FindObject(T object) {
    assert(object_table.contains(object));
```

I noticed this issue when I was trying to create new tests for another wsi, https://gitlab.khronos.org/Tracker/vk-gl-cts/-/issues/3685, which used CreateDisplayPlaneSurface(), but it has the same issue.  I am not sure how to reconcile this issue.

**Environment:**
 - OS: Linux, Ubuntu gdm
 - GPU: Nvidia RTX 3080
 - SDK or header version if building from repo: Built from repo
 - Options enabled (synchronization, best practices, etc.):
 After building both Validation and CTS, I ran:
```
VK_LAYER_PATH=<path-to-validation>/build/layers  ./deqp-vk --deqp-validation=enable --deqp-print-validation-errors --deqp-log-images=disable --deqp-log-shader-sources=disable -n=dEQP-VK.wsi.xlib.surface.query_surface_counters
```

**Additional context**
n/a

**Comment by ziga-lunarg** [comment]
This was a bug in CTS, I have a fix here: https://gitlab.khronos.org/Tracker/vk-gl-cts/-/issues/4761
