### ISSUE TITLE
Maintenance4's interface matching doesn't make any difference

### ISSUE THREAD

**Issue by stedob02** [KhronosGroup/Vulkan-ValidationLayers#4148]
After enabling VK_KHR_maintenance4 or even using Vulkan 1.3 I am still getting the same Performance Error:
> vertex shader writes to output location 0.2 which is not consumed by fragment shader

**Comment by sjfricke** [comment]
can this be closed @stedob02 ?

**Comment by ncesario-lunarg** [comment]
Going to close this out, but please re-open if you're still encountering issues.
