### ISSUE TITLE
VkPipelineColorBlendAdvancedStateCreateInfoEXT fails validation

### ISSUE THREAD

**Issue by brett19** [KhronosGroup/Vulkan-ValidationLayers#415]
Trying to use `VkPipelineColorBlendAdvancedStateCreateInfoEXT` as the pNext on a `VkPipelineColorBlendStateCreateInfo` fails due to pNext checks not being updated with this structure here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/bf0a85c69a20b91257250a85f4fa7999121b5192/layers/parameter_validation_utils.cpp#L2135-L2139

**Comment by jzulauf-lunarg** [comment]
Triage notes: Looks like a small fix replacing 0, NULL  (allowed_type_count, allowed_types) 1,  and an array with the type allowed in https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkPipelineColorBlendStateCreateInfo-pNext-pNext

**Comment by brett19** [comment]
Will also need to update the structure names (parameter 4) to include the new structure I believe?
