### ISSUE TITLE
Validation layer seems to slow generating commands from multiple threads

### ISSUE THREAD

**Issue by alecazam** [KhronosGroup/Vulkan-ValidationLayers#4155]
**Describe the Issue**
One of the advertised features of Vulkan is the ability to generate commands from multiple threads.   I can't tell if the futex is contending or not, but it seems like with the validation layer enabled, all function calls including cpuTiming end up going through repeated system mutex lock (__futex_wait_ex) calls on Android.  These syscall's stacks can be seen in the Android profiler.  Calls like requesting a new command buffer can make 4 validations/locks.

This layer needs to have a mutex per command buffer/pool possibly as one solution.  And just avoid mutex lock altogether.  if these are all the same mutex, then the contention is even worse.   Multithreaded code with 3 cores was 13ms slower than using main core, but there are complex assymetric cores on Android where big is 1x, medium is 2x, and little is 4x slower.

**Valid Usage ID**
N/A

**Environment:**
 - OS:  Android 12 (but all versions)
 - GPU: Mali and Adreno
 - SDK or header version if building from repo: N/A
 - Options enabled (synchronization, best practices, etc.): N/A

**Additional context**
N/A

**Comment by alecazam** [comment]
We’re just using what shipped with Android 12, and seeing a ton of locks. Probably have to wait until this lands in newer drivers, and just not leave validation on during perf tests.

**Comment by ncesario-lunarg** [comment]
> not leave validation on during perf tests

I think it would be bad to leave validation on for performance testing even _with_ @jeremyg-lunarg's fixes/improvements.

**Comment by jeremyg-lunarg** [comment]
Definitely agree with not trying to measure driver or app perf with validation enabled!

Closing this for now, please reopen or file a new issue once you've had a chance to try the latest validation code.
