### ISSUE TITLE
Using spirv CapabilityTransformFeedback fails validation.

### ISSUE THREAD

**Issue by brett19** [KhronosGroup/Vulkan-ValidationLayers#418]
See PR #419

**Comment by jzulauf-lunarg** [comment]
@chrisforbes -- spirv validation related?

**Comment by chrisforbes** [comment]
I'm OK with the changes to shader validation itself. We might end up needing some more bits, but wiring the capabilities onto the features is a solid start.

**Comment by brett19** [comment]
Note that there is a related PR for SPIRV-Tools.  Both changes are necessary for XFB usage to validate correctly in the validation layer (as the validator invokes the spirv-tools validator).
https://github.com/KhronosGroup/SPIRV-Tools/pull/2011

**Comment by jzulauf-lunarg** [comment]
@chrisforbes -- can you review and coordinate (for example so we pick up the correct known good with the prerequisite changes all with the SPIRV validation changes)?

**Comment by mark-lunarg** [comment]
@brett19 submitted a PR for this issue and it was merged.  Closing as fixed.
