### ISSUE TITLE
Core Validation: CmdPushDescriptorSetWithTemplateKHR not tracked properly

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#42]
**Issue by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Friday Sep 01, 2017 at 23:28 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2045_

----

We're now more or less correct for CmdPushDescriptorSet, but not for the template variant.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/mark-lunarg"><img src="https://avatars2.githubusercontent.com/u/7252958?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mark-lunarg](https://github.com/mark-lunarg) (MIGRATED)**
_Thursday Mar 01, 2018 at 22:28 GMT_

----

In work.

**Comment by jzulauf-lunarg** [comment]
Fixed with https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/460
