### ISSUE TITLE
Transform feedback counter buffer barrier validation fail

### ISSUE THREAD

**Issue by llyzs** [KhronosGroup/Vulkan-ValidationLayers#420]
When I tried to call a buffer memory barrier with VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT and VK_PIPELINE_STAGE_TRANSFORM_FEEDBACK_BIT_EXT the validation layer reports the following error:

[ VUID-vkCmdPipelineBarrier-pMemoryBarriers-01185 ] Object: 0x56247ad179f0 (Type = 6) | vkCmdPipelineBarrier(): pBufferMemBarriers[0].dstAccessMask (0x8000000) is not supported by dstStageMask (0x1000000). The Vulkan spec states: Each element of pMemoryBarriers, pBufferMemoryBarriers and pImageMemoryBarriers must not have any access flag included in its dstAccessMask member if that bit is not supported by any of the pipeline stages in dstStageMask, as specified in the table of supported access types. (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdPipelineBarrier-pMemoryBarriers-01185)

The above combination is listed in the spec.

**Comment by tobine** [comment]
Looks like missing support for XForm Feedback EXT in [AccessMaskToPipeStage](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/core_validation.cpp#L8351)

**Comment by pdaniell-nv** [comment]
There is no validation support for VK_EXT_transform_feedback yet. We should do the basic minimum to avoid errors like this done soon.

**Comment by pdaniell-nv** [comment]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/447 should fix this.

**Comment by llyzs** [comment]
Thanks, works perfectly.
