### ISSUE TITLE
Add validation for VK_EXT_metal_objects

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-ValidationLayers#4215]
VUIDs to add:
VUID-VkInstanceCreateInfo-pNext-06779
VUID-VkMemoryAllocateInfo-pNext-06780
VkBufferViewCreateInfo-pNext-06782
VUID-VkImageCreateInfo-pNext-06783
VUID-VkImageCreateInfo-pNext-06784
VUID-VkImageCreateInfo-pNext-06785
VUID-VkImageCreateInfo-pNext-06786
VUID-VkImageViewCreateInfo-pNext-06787
VUID-VkSemaphoreCreateInfo-pNext-06789
VUID-VkEventCreateInfo-pNext-06790
VUID-VkExportMetalObjectsInfoEXT-pNext-06791
VUID-VkExportMetalObjectsInfoEXT-pNext-06792
VUID-VkExportMetalObjectsInfoEXT-pNext-06793
VUID-VkExportMetalObjectsInfoEXT-pNext-06794
VUID-VkExportMetalObjectsInfoEXT-pNext-06795
VUID-VkExportMetalObjectsInfoEXT-pNext-06796
VUID-VkExportMetalObjectsInfoEXT-pNext-06797
VUID-VkExportMetalObjectsInfoEXT-pNext-06798
VUID-VkExportMetalObjectsInfoEXT-pNext-06799
VUID-VkExportMetalObjectsInfoEXT-pNext-06800
VUID-VkExportMetalObjectsInfoEXT-pNext-06801
VUID-VkExportMetalObjectsInfoEXT-pNext-06802
VUID-VkExportMetalObjectsInfoEXT-pNext-06803
VUID-VkExportMetalObjectsInfoEXT-pNext-06804
VUID-VkExportMetalObjectsInfoEXT-pNext-06805
VUID-VkExportMetalObjectsInfoEXT-pNext-06806
VUID-VkExportMetalObjectsInfoEXT-pNext-pNext
VUID-VkExportMetalObjectsInfoEXT-sType-unique
VUID-VkExportMetalCommandQueueInfoEXT-queue-parameter
VUID-VkExportMetalBufferInfoEXT-memory-parameter
VUID-VkExportMetalTextureInfoEXT-image-parameter
VUID-VkExportMetalTextureInfoEXT-imageView-parameter
VUID-VkExportMetalTextureInfoEXT-bufferView-parameter
VUID-VkExportMetalTextureInfoEXT-plane-parameter
VUID-VkExportMetalTextureInfoEXT-commonparent
VUID-VkExportMetalIOSurfaceInfoEXT-image-parameter
VUID-VkExportMetalSharedEventInfoEXT-semaphore-parameter
VUID-VkExportMetalSharedEventInfoEXT-event-parameter
VUID-VkExportMetalSharedEventInfoEXT-commonparent

VUIDs verified in (future) 1.3.217 code gen:
VUID-VkExportMetalObjectCreateInfoEXT-sType-sType
VUID-vkExportMetalObjectsEXT-device-parameter
VUID-VkExportMetalObjectCreateInfoEXT-exportObjectType-parameter
VUID-vkExportMetalObjectsEXT-pMetalObjectsInfo-parameter
VUID-VkExportMetalObjectsInfoEXT-sType-sType
VUID-VkExportMetalDeviceInfoEXT-sType-sType
VUID-VkExportMetalCommandQueueInfoEXT-sType-sType
VUID-VkExportMetalBufferInfoEXT-sType-sType
VUID-VkExportMetalTextureInfoEXT-sType-sType
VUID-VkExportMetalIOSurfaceInfoEXT-sType-sType
VUID-VkExportMetalSharedEventInfoEXT-sType-sType
VUID-VkImportMetalBufferInfoEXT-sType-sType
VUID-VkImportMetalTextureInfoEXT-sType-sType
VUID-VkImportMetalTextureInfoEXT-plane-parameter
VUID-VkImportMetalIOSurfaceInfoEXT-sType-sType
VUID-VkImportMetalSharedEventInfoEXT-sType-sType

**Comment by ar-visions** [comment]
VK_EXT_metal_objects does not work.  Theres very little talk in here of use-case.  As a user, I followed the docs clearly on a metal texture that works in a pipeline that works, and very simply attached the pNext to the VkCreateImage's info struct. All of the struct info was correct and it did not work.  No validation errors.  A manual copy by transfer works, but not by directly accessing the Metal texture of which I have regionally outputted to verify its there.  Doesn't work.

**Comment by ar-visions** [comment]
Doesn't work for me.  Do we have a test case of it working that you use as validation for testing support for the extension?  That would be the first place to start for anyone, including the people maintaining extensions. 

```

VkhImage _vkh_image_create (VkhDevice vkh, VkImageType imageType,
				  VkFormat format, uint32_t width, uint32_t height,
				  VkhMemoryUsage memprops, VkImageUsageFlags usage,
				  VkSampleCountFlagBits samples, VkImageTiling tiling,
				  uint32_t mipLevels, uint32_t arrayLayers, void *import = nullptr){

	VkhImage img = (VkhImage)calloc(1,sizeof(vkh_image_t));

	img->vkh = vkh_device_grab(vkh);

	VkImageCreateInfo* pInfo = &img->infos;
	pInfo->sType			= VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
	pInfo->imageType		= imageType;
	pInfo->tiling			= tiling;
	pInfo->initialLayout	= (tiling == VK_IMAGE_TILING_OPTIMAL) ? VK_IMAGE_LAYOUT_UNDEFINED : VK_IMAGE_LAYOUT_PREINITIALIZED;
	pInfo->sharingMode		= VK_SHARING_MODE_EXCLUSIVE;
	pInfo->usage			= usage;
	pInfo->format			= format;
	pInfo->extent.width		= width;
	pInfo->extent.height	= height;
	pInfo->extent.depth		= 1;
	pInfo->mipLevels		= mipLevels;
	pInfo->arrayLayers		= arrayLayers;
	pInfo->samples			= samples;

	/// support different forms of platform imports (dx on windows, metal on macos, hopefully nothing on linux)
    if (import) {
        /// this stuff was added mid 2022
#ifdef __APPLE__
        struct MTLTexture;
        struct VkImportMetalTextureInfoEXT {
            VkStructureType sType;
            const void* pNext;
            VkImageAspectFlags plane;
            MTLTexture* mtlTexture;
        };
        #define VK_STRUCTURE_TYPE_IMPORT_METAL_TEXTURE_INFO_EXT (VkStructureType)1000311007
        VkImportMetalTextureInfoEXT metal_import = {
            .sType 		= VK_STRUCTURE_TYPE_IMPORT_METAL_TEXTURE_INFO_EXT,
            .plane 		= VK_IMAGE_ASPECT_COLOR_BIT,
            .mtlTexture = (MTLTexture*)import
        };

        pInfo->pNext = &metal_import;
#endif
    }
```

**Comment by ar-visions** [comment]
VkImportMetalTextureInfoEXT <- I've tried this one and I cant seem to get a result unfortunately.  I'm using Molten 1.2.3

Not sure where to post this

**Comment by Tony-LunarG** [comment]
@ar-visions it looks like you're having trouble with the implementation of the extension, rather than the validation of the extension.  I'd suggest opening an issue in the MoltenVK project : https://github.com/KhronosGroup/MoltenVK
