### ISSUE TITLE
Missing VUIDs for VK_BUFFER_USAGE_SHADER_BINDING_TABLE_BIT_KHR included in usage flags for buffers used as Shader Binding Tables

### ISSUE THREAD

**Issue by rumblehhh** [KhronosGroup/Vulkan-ValidationLayers#4224]
**Describe the situation in which you encountered the missing validation**
Applications not including VK_BUFFER_USAGE_SHADER_BINDING_TABLE_BIT_KHR as part of the buffer usage flags for buffers used as shader binding tables for example:
https://github.com/GPSnoopy/RayTracingInVulkan/pull/57
https://github.com/nvpro-samples/nvpro_core/pull/38 (used by https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR)

**Valid Usage IDs requested**
Please include the valid usage IDs for the checks you are requesting:
VUID-vkCmdTraceRaysKHR-pRayGenShaderBindingTable-03681
VUID-VkTraceRaysIndirectCommand2KHR-pRayGenShaderBindingTable-03681
VUID-vkCmdTraceRaysKHR-pMissShaderBindingTable-03684
VUID-VkTraceRaysIndirectCommand2KHR-pMissShaderBindingTable-03684
VUID-vkCmdTraceRaysKHR-pHitShaderBindingTable-03688
VUID-VkTraceRaysIndirectCommand2KHR-pHitShaderBindingTable-03688
VUID-vkCmdTraceRaysKHR-pCallableShaderBindingTable-03692
VUID-VkTraceRaysIndirectCommand2KHR-pCallableShaderBindingTable-03692

**Additional Context**
Any additional information:
Some api recording/playback tools like [PVRCarbon](https://developer.imaginationtech.com/pvrcarbon/) use buffer usage flags such as VK_BUFFER_USAGE_SHADER_BINDING_TABLE_BIT_KHR to control playback behaviour. 
I imagine missing VUIDs (and lenient implementations) contribute to some applications not properly setting buffer usage flags for shader binding tables.

**Comment by arno-lunarg** [comment]
The `VkCmdTraceRaysKHR` VUIDs are implemented. Opened https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5724 for the `VkTraceRaysIndirectCommand2KHR` VUIDs, validation needs to go through GPU assisted validation.
