### ISSUE TITLE
Investigate VkSyncValTest.SyncQSBufferCopyVsIdle crash in CI

### ISSUE THREAD

**Issue by ncesario-lunarg** [KhronosGroup/Vulkan-ValidationLayers#4225]
`VkSyncValTest.SyncQSBufferCopyVsIdle` is causing a sporadic crash on 32b release in CI.

**Comment by spencer-lunarg** [comment]
@ncesario-lunarg Trying to figure out what happened here, I see you disabled it, but also seems like https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4447 fixed it? But the diff doesn't show the change in #4226

**Comment by ncesario-lunarg** [comment]
Pretty sure this can be closed, and I think this was resolved as a wider test cleanup/fixup from @jzulauf-lunarg and @paul-lunarg.
