### ISSUE TITLE
spurious VUID-vkCmdBindPipeline-pipeline-06197 errors

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-ValidationLayers#4235]
I'm getting this

`VUID-vkCmdBindPipeline-pipeline-06197(ERROR / SPEC): msgNum: 296975921 - Validation Error: [ VUID-vkCmdBindPipeline-pipeline-06197 ] Object 0: handle = 0x74ea280000000054, type = VK_OBJECT_TYPE_PIPELINE; | MessageID = 0x11b37e31 | vkCmdBindPipeline(): Binding pipeline with VkPipelineRenderingCreateInfo::depthAttachmentFormat VK_FORMAT_UNDEFINED, but previously bound pipeline VkPipelineRenderingCreateInfo::depthAttachmentFormat was VK_FORMAT_X8_D24_UNORM_PACK32. The Vulkan spec states: If pipeline is a graphics pipeline, this command has been called inside a render pass instance started with vkCmdBeginRendering, and commands using the previously bound graphics pipeline have been recorded within the render pass instance, then the value of VkPipelineRenderingCreateInfo::depthAttachmentFormat specified by this pipeline must match that set in the previous pipeline (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdBindPipeline-pipeline-06197)`

from the following sequence:
* BeginRendering
* BindPipeline
* EndRendreing
* BeginRendering
* BindPipeline <--error here
* EndRendering

Should be easily reproducible with zink on a [piglit](https://gitlab.freedesktop.org/mesa/piglit/) test:

`MESA_LOADER_DRIVER_OVERRIDE=zink bin/arb_texture_multisample-sample-depth -auto -fbo`

**Comment by ASerandourAMD** [comment]
I have also observed the following errors with the same setup:
- VUID-vkCmdBindPipeline-pipeline-06194
- VUID-vkCmdBindPipeline-pipeline-06195
- VUID-vkCmdBindPipeline-pipeline-06196
- VUID-vkCmdBindPipeline-pipeline-06197

There is no command between `vkCmdBeginRenderingKHR` and `vkCmdBindPipeline`.

**Comment by jsguay-legion** [comment]
Same here on vulkan-SDK 1.3.216, Did not trigger on 1.3.211 with the same code. Error on my side is:
`
Validation Error: [ VUID-vkCmdBindPipeline-pipeline-06197 ] Object 0: handle = 0xc4bec900000000b0, type = VK_OBJECT_TYPE_PIPELINE; | MessageID = 0x11b37e31 | vkCmdBindPipeline(): Binding pipeline with VkPipelineRenderingCreateInfo::depthAttachmentFormat VK_FORMAT_UNDEFINED, but previously bound pipeline VkPipelineRenderingCreateInfo::depthAttachmentFormat was VK_FORMAT_D32_SFLOAT. The Vulkan spec states: If pipeline is a graphics pipeline, this command has been called inside a render pass instance started with vkCmdBeginRendering, and commands using the previously bound graphics pipeline have been recorded within the render pass instance, then the value of VkPipelineRenderingCreateInfo::depthAttachmentFormat specified by this pipeline must match that set in the previous pipeline (https://vulkan.lunarg.com/doc/view/1.3.216.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdBindPipeline-pipeline-06197)`

Like the OP, my sequence of calls is:

-     BeginRendering
-     BindPipeline (using D32_SFLOAT format for depth stencil attachment)
-     EndRendreing
-     BeginRendering
-     BindPipeline <--error here, pass uses no depth stencil attachment
-     EndRendering

**Comment by GPUCode** [comment]
Facing this issue too on my application. The only workaround currently is switching command buffers between rendering instances but that is very expensive. Any plans to fix this?

**Comment by sagaceilo** [comment]
Having exactly the same issue as ones described before. SDK 1.3.216

**Comment by zmike** [comment]
This still isn't fixed.

Running `dEQP-GLES31.functional.fbo.color.texcubearray.rg32ui` with zink triggers another spurious error.

**Comment by nikitablack** [comment]
I have the same issue with SDK 1.3.224.

**Comment by greg-churchillnavigation** [comment]
I'm still seeing this in SDK 1.3.224.1
I have a unique pipeline used in a set of post process rendering phases.
I've verified the rendering phases are configured correctly as is the pipeline.
The validation layer appears to be confusing pipelines outside these rendering phases for some reason.
I see errors VUID-vkCmdBindPipeline-pipeline-06195, VUID-vkCmdBindPipeline-pipeline-06196, VUID-vkCmdBindPipeline-pipeline-06197 for my usage sequence.

**Comment by daniilvinn** [comment]
1.3.216.0 - issue still exist.
I have same layout as OP:
`vkCmdBeginRendering()`
`vkCmdBindPipeline()`
`Draw stuff...`
`vkCmdEndRendering`

then I begin rendering again, draw my UI and on second pipeline binding I run into this issue as well.
Hope this is gonna be fixed soon.

**Comment by spencer-lunarg** [comment]
The Vulkan 1.3.232 spec updated `VUID-vkCmdBindPipeline-pipeline-06197` (and other related VUs)  to `VUID-vkCmdDraw-pDepthAttachment-07617` (which still needs to be added to validation)

Closing as this issue in itself is resolved via a spec update

[internal change](https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5487)

**Comment by spencer-lunarg** [comment]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5064
