### ISSUE TITLE
Incorrect version reported for VK_LAYER_KHRONOS_validation on Android

### ISSUE THREAD

**Issue by TheMostDiligent** [KhronosGroup/Vulkan-ValidationLayers#4240]
**Describe the Issue**
The `specVersion` member of `VkLayerProperties` struct reported for `VK_LAYER_KHRONOS_validation` layer on Android does not contain the minor version. For 1.3.216 SDK version, the value is `0x4000d8`, which translates to `1.0.216`

**Valid Usage ID**
The value of the `specVersion` member is `0x4030d8`, which translates to `1.3.216`

**Environment:**
 - OS: Android
 - GPU: Adreno (TM) 530, API version 1.1.87, Driver version 0.384.0.
 - Vulkan SDK version: 1.3.216
 - Options enabled (synchronization, best practices, etc.): n/a

**Additional context**
`VK_API_VERSION_MAJOR`, `VK_API_VERSION_MINOR`, and `VK_API_VERSION_PATCH` macros are used to extract the version components.

The `specVersion` value is correctly reported on Windows in the same SDK version.

**Comment by sjfricke** [comment]
> The specVersion value is correctly reported on Windows in the same SDK version.

[set the same for Windows and Android](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/6e8fb40b3b364391095e40f894cd3922854a0317/layers/vk_layer_utils.h#L309)
`#define VK_LAYER_API_VERSION VK_MAKE_VERSION(1, 0, VK_HEADER_VERSION)`

I agree the minor version should be adjusted, but curious how it is correct on Windows

**Comment by TheMostDiligent** [comment]
> but curious how it is correct on Windows

For the same sdk version it returns 1.3.216.

**Comment by mark-lunarg** [comment]
Just a guess, but maybe Windows/Linux is getting this info from the layer json file.  Android relies solely on the layer property enumeration APIs to get layer info.
