### ISSUE TITLE
Add Submit Time Synchronization Validation -- tracking/progress issue

### ISSUE THREAD

**Issue by jzulauf-lunarg** [KhronosGroup/Vulkan-ValidationLayers#4241]
**Describe the Issue**
Current Synchronization only occurs at command buffer record (include the recording of CmdExecuteCommandBuffers), but does not track data hazards between command buffers or across queue.

This issue tracks the known task list to get the functionality to an alpha release state.

**Current Status**

Implementation is in a alpha condition, with limited functionality committed to master, defaulted off and intentional undocumented means to enable (including the absences of VkConfig support)

**Functionality Supported**
* Supporting state data:
  * Implemented "QueueBatchAccessContext"
    * Access/Event/Signal state as of the end of a queue submit batch
    * Analog to the CommandBufferAccessContext for single command buffers
    * See updated documentation for full details
  * Tagging is global with ranges assigned at queuesubmit time
* Queue submit order hazard detection (single queue) functional
* PipelineBarrier now correctly scopes for access outside queue submit order
* Binary Semaphore examples function
* Device and Queue Wait Idle 
* Improvements to SetEvent scope capture
* Cmd*Event support with corrected Wait time synchronization chaining

**Missing/Incomplete**
* PipelineBarrier "BarrierHazard" detection is not mutli-queue aware (false negative)
* Correct handling of RenderPass barriers/accesses in QueueSubmit
* Other submit types/operations need support (including submit2)
 * Fence support is missing (though QueueWaitIdle model changes should be sufficient)
* Access Log cleanup.  Currently the access logs simply leak
  * There will need to be some garbage collection for unreferenced resource usage tags
* AccessContext cleanup -- EndRecord/"End of batch" cleanup/consolidation of RangeMaps needed.

** Issues found **
(either fix these as part of this issue, or transfer to independent issue)
* Missing test for finding hazards in non-begin() sections of scope.

**Comment by mokafolio** [comment]
What is the recommended way of reporting bugs for this specific feature? I am pretty sure this wrongly emits a `SYNC-HAZARD-WRITE-AFTER-WRITE` for my swapchain sub pass dependency setup.

**Comment by jzulauf-lunarg** [comment]
Implemented
