### ISSUE TITLE
VK_EXT_debug_report extension is reported instead of VK_EXT_debug_utils on Android

### ISSUE THREAD

**Issue by TheMostDiligent** [KhronosGroup/Vulkan-ValidationLayers#4242]
**Describe the Issue**
On Android, `VK_EXT_debug_utils` name is missing in the list of supported instance extensions, but `VK_EXT_debug_report` is reported. However, the `VK_EXT_debug_utils` extension can still be successfully enabled and works just fine.

**Valid Usage ID**
`VK_EXT_debug_utils` extension name is reported by `vkEnumerateInstanceLayerProperties`

**Environment:**
 - OS: Android
 - GPU: Adreno (TM) 530, API version 1.1.87, Driver version 0.384.0.
 - Vulkan SDK version: 1.3.216
 - Options enabled (synchronization, best practices, etc.): n/a

**Additional context**

Everything works properly on Windows in the same SDK version.

**Comment by sjfricke** [comment]
To my knowledge, Android does not support `VK_EXT_debug_utils` as the loader doesn't have support for it https://cs.android.com/android/platform/superproject/+/master:frameworks/native/vulkan/libvulkan/driver_gen.cpp;l=561

**Comment by TheMostDiligent** [comment]
Somehow it works though... Wasn't the report version deprecated in favor of utils?

**Comment by sjfricke** [comment]
It was, but idk if Android ever got around to updating it

**Comment by TheMostDiligent** [comment]
Since it works it appears that it supports it but doesn't report it. 
Anyway this seems to be not an SDK issue. Thanks!
