### ISSUE TITLE
Add validation for VK_EXT_shader_module_identifier

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-ValidationLayers#4268]
**Valid Usage IDs requested**
VUID-VkPipelineShaderStageCreateInfo-stage-06844
VUID-VkPipelineShaderStageCreateInfo-stage-06845
VUID-VkPipelineShaderStageCreateInfo-stage-06846
VUID-VkPipelineShaderStageCreateInfo-stage-06847
VUID-VkPipelineShaderStageCreateInfo-stage-06848
VUID-VkPipelineShaderStageCreateInfo-pSpecializationInfo-06849
VUID-VkPipelineShaderStageModuleIdentifierCreateInfoEXT-pNext-06850
VUID-VkPipelineShaderStageModuleIdentifierCreateInfoEXT-pNext-06851
VUID-VkPipelineShaderStageModuleIdentifierCreateInfoEXT-identifierSize-06852
VUID-VkPipelineLibraryCreateInfoKHR-pLibraries-06855
VUID-vkGetShaderModuleIdentifierEXT-shaderModuleIdentifier-06884
VUID-vkGetShaderModuleCreateInfoIdentifierEXT-shaderModuleIdentifier-06885

**Comment by spencer-lunarg** [comment]
I see them all in, closing
