### ISSUE TITLE
Investigate remaining test failures

### ISSUE THREAD

**Issue by ncesario-lunarg** [KhronosGroup/Vulkan-ValidationLayers#4273]
This a followup issue to #3177, mainly to track the investigation of disabled tests resulting from #4253 along with change 57b56bb0 in VulkanTests.

The following tests have been disabled for Android CI. Most (if not all) of these have likely been fixed by @sjfricke's changes, and this is here to ensure that these tests get re-enabled in local CI.
- VkLayerTest.SamplerImageViewFormatUnsupportedFilter
- VkLayerTest.TransformFeedbackCmdBindTransformFeedbackBuffersEXT
- VkLayerTest.TransformFeedbackCmdBeginTransformFeedbackEXT
- VkLayerTest.TransformFeedbackCmdEndTransformFeedbackEXT
- VkLayerTest.AndroidHardwareBufferExporttBuffer
- VkLayerTest.AndroidHardwareBufferDepthStencil
- VkLayerTest.AttachmentShouldNotBeTransient
- VkLayerTest.NotSupportProvokingVertexModePerPipeline
- VkLayerTest.PipelineInvalidAdvancedBlend
- VkLayerTest.InvalidFragmentDensityMapLayerCount
- VkLayerTest.FramebufferCreateErrors
- VkLayerTest.InvalidMixingProtectedResources
- VkLayerTest.SwapchainAcquireImageNoSync
- VkLayerTest.SwapchainAcquireImageNoSync2KHR
- VkLayerTest.SwapchainAcquireTooManyImages
- VkLayerTest.GetSwapchainImageAndTryDestroy
- VkLayerTest.SwapchainAcquireTooManyImages2KHR
- VkLayerTest.WarningSwapchainCreateInfoPreTransform
- VkLayerTest.SwapchainAcquireImageWithSignaledSemaphore
- VkLayerTest.GetSwapchainImagesCountButNotImages
- VkLayerTest.InvalidMemoryMapping
- VkBestPracticesLayerTest.AttachmentShouldNotBeTransient
- VkPositiveLayerTest.AndroidHardwareBufferDepthStencil

The following tests crash on Windows + AMD CI without any validation errors triggered:
- VkLayerTest.InvalidFragmentShadingRateFramebufferDimensions
- VkLayerTest.TestBeginRenderingInvalidFragmentShadingRateImage
- VkLayerTest.TestBeginRenderingFragmentShadingRateImageView
- VkLayerTest.TestBeginRenderingFragmentShadingRateAttachmentSize
- VkLayerTest.TestBeginRenderingFragmentShadingRateAttachmentSizeWithDeviceGroupExt

The following test appear to be driver bugs where the `descriptorSetLayout` handle passed to `vkCreateDescriptorUpdateTemplateKHR` is not ignored as expected and results in a crash:
- VkLayerTest.CreateDescriptorUpdateTemplate

The following tests crash on recent versions of the Mesa RADV driver and require further investigation:
- VkLayerTest.TransformFeedbackCmdBindTransformFeedbackBuffersEXT
- VkLayerTest.TransformFeedbackCmdBeginTransformFeedbackEXT
- VkLayerTest.TransformFeedbackCmdEndTransformFeedbackEXT
- VkGpuAssistedLayerTest.GpuDrawIndirectCountDeviceLimit

**Comment by sjfricke** [comment]
Ran these locally on my Android device, here is what I see failing/crashing still, will try to see if I can fix some

- VkLayerTest.AndroidHardwareBufferExporttBuffer
- VkPositiveLayerTest.AndroidHardwareBufferDepthStencil
- VkBestPracticesLayerTest.AttachmentShouldNotBeTransient
- VkLayerTest.NotSupportProvokingVertexModePerPipeline
- VkLayerTest.PipelineInvalidAdvancedBlend
- VkLayerTest.InvalidFragmentDensityMapLayerCount
- VkLayerTest.FramebufferCreateErrors
- VkLayerTest.InvalidMixingProtectedResources
- VkLayerTest.InvalidMemoryMapping

**Comment by spencer-lunarg** [comment]
This issue got stale - many of these tests are renamed and/or been worked on

I am currently trying to reduce which tests are "still" failing, from there will make the proper issues to looking into why

**Comment by artem-lunarg** [comment]
`NegativeFragmentShadingRate.DISABLED_Framebuffer`

```
  ivs[0] = m_renderTargets[0]->targetView(VK_FORMAT_B8G8R8A8_UNORM);
  ivs[1] = m_renderTargets[0]->targetView(VK_FORMAT_B8G8R8A8_UNORM);
```
`taretView` the second call returns cached image view value, so `ivs` will have two identical image view. Not sure if that's causes the problem, but it's better to mention about this.
