### ISSUE TITLE
VkSwapchainCreateInfoKHR flags unchecked

### ISSUE THREAD

**Issue by danilw** [KhronosGroup/Vulkan-ValidationLayers#4274]
**Issue description:**
As I saw - `VkSwapchainCreateInfoKHR.flags` ignored by Validation layers. (**Vulkan SDK 1.3.216.0** tested today)

**Valid Usage IDs requested**
VUID-VkSwapchainCreateInfoKHR-physicalDeviceCount-01429
VUID-VkSwapchainCreateInfoKHR-flags-03168
VUID-VkSwapchainCreateInfoKHR-flags-04100
VUID-VkSwapchainCreateInfoKHR-flags-03187

**Additional Context**
When `VkSwapchainCreateInfoKHR.flags` is not `0` it results in "very weird behavior" - I had to debug my application line by line for many hours, just to find that I set flag on incorrect value.
When `flags` is 1 - broken UV on small resolution, when `flags` is >1 application crash, when `flags` negative driver crash.

**Visual it looks like this**: (screenshots from Nvidia)

Vulkan samples
![1](https://user-images.githubusercontent.com/24825887/177331285-7718c106-b81e-40f3-b93a-d290b79720a0.png)

My test application in RenderDoc, as you can see "screenshot" of swapchain in RenderDoc not broken, this also made me very confused about source of this bug
![2](https://user-images.githubusercontent.com/24825887/177331546-77e9b2d9-a4c6-4212-9c9a-55f0917b4afc.png)

**Produced bug** (when flags incorrect) - when window resized to "small" UV of swapchain become broken, on every GPU (every OS), on Nvidia its "black vertical lines", on Intel and AMD it "broken UV"(random UV shifts).

It is hard to find reason of bugs like this when Validation layers completely silent, visual result can make you think this is because "wrong memory flags" or some wrong not initialized structure... and checking all of used Vulkan parameters require way too much time.

Test of this - just add to any VkSwapchainCreateInfoKHR parameters `.flags = 1;` and resize window to 85 height or less.

This `VkSwapchainCreateInfoKHR.flags` look completely unchecked by ValidationLayers and result when `flags` is wrong very much ruin whole application, so I think it should be checked by ValidationLayers.

**Comment by ncesario-lunarg** [comment]
Thank you for the issue @danilw. Looks like we are indeed missing validation for 03187, but we should be checking the other 3 VUIDs. Are you saying the other VUIDs (01429, 03168, and 04100) are not being triggered when you think they should (or perhaps being triggered when they shouldn't)? If so, can you provide a more complete example? I wasn't able to build the vulkan-shadertoy-launch project.

**Comment by danilw** [comment]
> Are you saying the other VUIDs (01429, 03168, and 04100) are not being triggered when you think they should (or perhaps being triggered when they shouldn't)?

**My bug/case is** only when `VkSwapchainCreateInfoKHR.flags = 1` when it supposed to be `0`. 
I list all other VUID because I saw `.flags` not being checked with any other value.

> If so, can you provide a more complete example? I wasn't able to build the vulkan-shadertoy-launch project.

I know only reproduction for "my bug" is:

go to https://github.com/KhronosGroup/Vulkan-Samples/blob/master/samples/api/hello_triangle/hello_triangle.cpp#L531

where `VkSwapchainCreateInfoKHR info{VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR};` defined and add:
`info.flags = 1;`
(or anything not 0, with 1 will be triggered my case I showed on screenshots)

Im sorry if I added wrong VUID, I hope my description of "my bug" shows what I talk about.

**Comment by arno-lunarg** [comment]
Do you trigger `VUID-VkSwapchainCreateInfoKHR-flags-parameter` when `.flags` is not a combination of `VK_SWAPCHAIN_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT_KHR`, `VK_SWAPCHAIN_CREATE_PROTECTED_BIT_KHR` and `VK_SWAPCHAIN_CREATE_MUTABLE_FORMAT_BIT_KHR` ?

**Comment by danilw** [comment]
to test I used hello_triangle.cpp as described above
`build/linux/app/bin/Release/x86_64/vulkan_samples sample hello_triangle`

**Vulkan SDK** 1.3.224.1
Linux Nvidia driver 515.57

when ` info.flags` == `VK_SWAPCHAIN_CREATE_MUTABLE_FORMAT_BIT_KHR` validation layers output:
```
UNASSIGNED-GeneralParameterError-ExtensionNotEnabled(ERROR / SPEC): msgNum: -383040211 - Validation Error: [ UNASSIGNED-GeneralParameterError-ExtensionNotEnabled ] Object 0: handle = 0x1cb3820, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xe92b452d | vkCreateSwapchainKHR(): pCreateInfo->flags contains VK_SWAPCHAIN_CREATE_MUTABLE_FORMAT_BIT_KHR which requires the VK_KHR_swapchain_mutable_format extension, which has not been enabled.
    Objects: 1
        [0] 0x1cb3820, type: 3, name: NULL
```

with `VK_SWAPCHAIN_CREATE_PROTECTED_BIT_KHR` - silent crash(segfault), **no validation output**.

with `VK_SWAPCHAIN_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT_KHR` - same visual artifacts (after resize to small resolution like on my screenshots in first message above), **no validation output**.

> when .flags is not a combination of

`info.flags = ` 5 or 6 or 7

```
UNASSIGNED-GeneralParameterError-ExtensionNotEnabled(ERROR / SPEC): msgNum: -383040211 - Validation Error: [ UNASSIGNED-GeneralParameterError-ExtensionNotEnabled ] Object 0: handle = 0x33e1f80, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xe92b452d | vkCreateSwapchainKHR(): pCreateInfo->flags contains VK_SWAPCHAIN_CREATE_MUTABLE_FORMAT_BIT_KHR which requires the VK_KHR_swapchain_mutable_format extension, which has not been enabled.
    Objects: 1
        [0] 0x33e1f80, type: 3, name: NULL

```

`info.flags = ` >=8

```
VUID-VkSwapchainCreateInfoKHR-flags-parameter(ERROR / SPEC): msgNum: -1531306541 - Validation Error: [ VUID-VkSwapchainCreateInfoKHR-flags-parameter ] Object 0: handle = 0x2867a20, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xa4ba1dd3 | vkCreateSwapchainKHR: value of pCreateInfo->flags contains flag bits that are not recognized members of VkSwapchainCreateFlagBitsKHR The Vulkan spec states: flags must be a valid combination of VkSwapchainCreateFlagBitsKHR values (https://vulkan.lunarg.com/doc/view/1.3.224.1/linux/1.3-extensions/vkspec.html#VUID-VkSwapchainCreateInfoKHR-flags-parameter)
    Objects: 1
        [0] 0x2867a20, type: 3, name: NULL
```

**Comment by arno-lunarg** [comment]
For VK_SWAPCHAIN_CREATE_PROTECTED_BIT_KHR, it seems that support can be checked using this extension: [VK_KHR_surface_protected_capabilities](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VK_KHR_surface_protected_capabilities)
But as you say, there is no VUID telling that it needs to be checked. Still, we could probably add this to the validation, if this extension is supported. According to https://vulkan.gpuinfo.org/listinstanceextensions.php, at least in your Nvidia case it should be. I need to get back to my team to talk about that.

For VK_SWAPCHAIN_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT_KHR, again, valid usage has some conditions not covered by any VUID it seems. From the spec:
> VK_SWAPCHAIN_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT_KHR specifies that images created from the swapchain (i.e. with the swapchain member of VkImageSwapchainCreateInfoKHR set to this swapchain’s handle) must use VK_IMAGE_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT.

But the `hello_triangle` exemple does not seem to dot that... As of writing I have no idea about what is wrong with this flag. Will check that with my team too.

**Comment by jeremyg-lunarg** [comment]
We have code to check all of the VUIDs requested, but the checks for 01429 and 03187 have bugs.
