### ISSUE TITLE
`RayTraversalPrimitiveCullingKHR` capability not allowed in ray _query_ shaders

### ISSUE THREAD

**Issue by MarijnS95** [KhronosGroup/Vulkan-ValidationLayers#4278]
### Describe the Issue
When using a shader with ray queries, that have [`SkipAABBsKHR`](https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/KHR/ray_common/rt_primitive_culling_capability.txt) set (`RAY_FLAG_SKIP_PROCEDURAL_PRIMITIVES` in HLSL) and its `RayTraversalPrimitiveCullingKHR` emitted in SPIR-V, the following error appears:

```
Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-01091 ] Object 0: handle = 0xb400007394d724d0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xa7bb8db6 | vkCreateShaderModule(): The SPIR-V Capability (RayTraversalPrimitiveCullingKHR) was declared, but none of the requirements were met to use it. The Vulkan spec states: If pCode declares any of the capabilities listed in the SPIR-V Environment appendix, one of the corresponding requirements must be satisfied (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-01091)
```

Note that this appears when _exclusively_ using `VK_KHR_ray_query` and _not_ enabling/having `VK_KHR_ray_tracing_pipeline` - hence not enabling the flag in `VkPhysicalDeviceRayTracingPipelineFeaturesKHR`.

It appears [the spec](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#spirvenv-capabilities-table-RayTraversalPrimitiveCullingKHR) and [this validation layer](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/a83fbb95949cd6315a0096bdc0c6c07675342fab/layers/generated/spirv_validation_helper.cpp#L217) only have a Vulkan feature for _Ray Tracing pipelines_, but not for _Ray Query shaders_?

A possible workaround is passing `VkPhysicalDeviceRayTracingPipelineFeaturesKHR` regardless of the `VK_KHR_ray_tracing_pipeline` feature, but that seems wrong and I'm surprised the validation layer doesn't complain about feature structs being used without the appropriate extension being enabled.

### Valid Usage ID
`VUID-VkShaderModuleCreateInfo-pCode-01091`

### Environment
 - OS: Any
 - GPU: Any with Ray Query support
 - SDK or header version if building from repo: 1.3.216.0
 - Options enabled (synchronization, best practices, etc.): None.

### Additional context

- https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_KHR_ray_query.html#_new_spir_v_capabilities Indicates that this capability is allowed within RayQuery shaders.
- https://microsoft.github.io/DirectX-Specs/d3d/Raytracing.html#rayquery The HLSL docs use this flag in a RayQuery example.
- Minimal example shader:
  ```hlsl
  RaytracingAccelerationStructure as;
  float4 main(float4 input : SV_POSITION) : SV_Target0 {
      RayQuery<RAY_FLAG_SKIP_PROCEDURAL_PRIMITIVES> q;
      RayDesc ray;
      q.TraceRayInline(as, 0, 0xff, ray);
      q.Proceed();
      if (q.CommittedStatus() == COMMITTED_TRIANGLE_HIT) {
          return 1.0;
      } else {
          return 0.0;
      }
  }
  ```

**Comment by sjfricke** [comment]
This is a spec bug (Vulkan-Docs) because all the validation layers stuff (and the table in the spec) are generated from the `vk.xml` file

```xml
        <spirvcapability name="RayTraversalPrimitiveCullingKHR">
            <enable struct="VkPhysicalDeviceRayTracingPipelineFeaturesKHR" feature="rayTraversalPrimitiveCulling" requires="VK_KHR_ray_tracing_pipeline"/>
        </spirvcapability>
```

I do agree looking at this now, it seems to be a mistake that there is no way to enable `RayTraversalPrimitiveCullingKHR` with only `VK_KHR_ray_query`

**Comment by MarijnS95** [comment]
@sjfricke Thanks for confirming that it should indeed be usable on `SPV_KHR_ray_query`; I should have clarified that I was also on the verge of punting this on a spec bug as well.

Will file this upstream :)

**Comment by dgkoch** [comment]
RayTraversalPrimitiveCullingKHR is optional for VK_KHR_ray_tracing_pipeline, but required for VK_KHR_ray_query, which is why there is no feature flag in VK_KHR_ray_query.  I think this bug came about when we tried to represent all the capabilities in the XML.

**Comment by dgkoch** [comment]
>       <spirvcapability name="RayTraversalPrimitiveCullingKHR">
>            <enable struct="VkPhysicalDeviceRayTracingPipelineFeaturesKHR" feature="rayTraversalPrimitiveCulling" requires="VK_KHR_ray_tracing_pipeline"/>
>            <enable extension="VK_KHR_ray_query"/>
>         </spirvcapability>

@sjfricke Actually we need the rayQuery feature to be enabled as well, right?

**Comment by MarijnS95** [comment]
@dgkoch Isn't the same implied for `VkPhysicalDeviceRayTracingPipelineFeaturesKHR`'s `rayTracingPipeline` boolean?

**Comment by sjfricke** [comment]
> Actually we need the rayQuery feature to be enabled as well, right?

yes so it would be

```patch
        <spirvcapability name="RayTraversalPrimitiveCullingKHR">
            <enable struct="VkPhysicalDeviceRayTracingPipelineFeaturesKHR" feature="rayTraversalPrimitiveCulling" requires="VK_KHR_ray_tracing_pipeline"/>
+           <enable struct="VkPhysicalDeviceRayQueryFeaturesKHR" feature="rayQuery" requires="VK_KHR_ray_query"/>
        </spirvcapability>
```

**Comment by MarijnS95** [comment]
Just wondering, if `VkPhysicalDeviceRayTracingPipelineFeaturesKHR::rayTraversalPrimitiveCulling` is enabled does that require `VkPhysicalDeviceRayTracingPipelineFeaturesKHR::rayTracingPipeline` to be enabled accordingly?

**Comment by dgkoch** [comment]
Spec fix released in VK 1.3.221

**Comment by sjfricke** [comment]
Pulled in and should be good now https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4314/files#diff-7d48a2b188a782c63658a6716d3b99ded72d38c774bbc647272646552d4e198e

@ncesario-lunarg we can close this issue now

**Comment by MarijnS95** [comment]
Thanks a lot! I'll test this out in the coming days.
