### ISSUE TITLE
Validation:  image layouts are not validated in pushed descriptor sets

### ISSUE THREAD

**Issue by scyganINTEL** [KhronosGroup/Vulkan-ValidationLayers#428]
When using `vkCmdPushDescriptorSetKHR` to push image view to STORAGE_IMAGE-typed descriptor, the image layout is not validated (according to spec, only GENERAL layout is allowed). 

At least following check from '_updated_' descriptors should be ported to '_pushed_' descriptors: 

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/9b9532b4c9fc97236169029f42a8ffeafdbb9185/layers/descriptor_sets.cpp#L1447-L1454

**Comment by jzulauf-lunarg** [comment]
All descriptor validation is deferred until vkDraw* or vkDispatch* time, and only for descriptors statically used by shaders active in those calls.

The state tracking needed to enable validating push descriptor is missing from CmdPushDescriptorSet, and the validation code present is deleting and reconstructing the push descriptor set for each Push (incorrectly) -- thus the bug and incomplete tags.

**Comment by scyganINTEL** [comment]
@jzulauf-lunarg check I am mentioning does not need to be deferred until vkDraw / vkDispatch, as both layout and descriptor type are given in push call.  

The push call can fail immediately, if non-GENERAL layout is used with STORAGE_IMAGE. 

Other checks (descriptor layout vs. subresource layout, etc..) indeed need deferring.

**Comment by jzulauf-lunarg** [comment]
Yes.  You are correct.  This is currently an Update time check and Should be a Push time check when implemented.  Thank you.

**Comment by jzulauf-lunarg** [comment]
PR addressing this issue under review https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/460

**Comment by jzulauf-lunarg** [comment]
PR merged
