### ISSUE TITLE
Missing unwrapping in DispatchBuildAccelerationStructuresKHR

### ISSUE THREAD

**Issue by KonstantinSeurer** [KhronosGroup/Vulkan-ValidationLayers#4292]
**Describe the Issue**
`VkAccelerationStructureInstanceKHR::accelerationStructureReference` does not get unwrapped which breaks host builds since it no longer is a valid `VkAccelerationStructureKHR` handle.

**Additional context**
For reference: https://gitlab.freedesktop.org/mesa/mesa/-/issues/6076#note_1457821

**Comment by jeremyg-lunarg** [comment]
This was fixed by https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3559
