### ISSUE TITLE
Best practices layer warns about deprecated extension based on instance version

### ISSUE THREAD

**Issue by spnda** [KhronosGroup/Vulkan-ValidationLayers#4293]
**Describe the Issue**
When creating an instance with (in my case) 1.3.216 and then calling vkCreateDevice for a device that supports 1.1.217, I get the following warning from the best practices layer:
> CreateDevice(): Attempting to enable deprecated extension VK_KHR_timeline_semaphore, but this extension has been promoted to VK_VERSION_1_2.

This is nonsense, as determining the proper extensions for device creation is device specific and depends on the api version of the device, not the instance. The device does not know of `KHR_timeline_semaphore` being deprecated as it doesn't know about 1.2. Currently, the message is absolutely useless. Although, simply by checking by physical device's apiVersion, the message makes sense again and is actually something a developer should consider. (Also there's a `vk` prefix missing on the CreateDevice() at the start of the string.)

**Comment by ncesario-lunarg** [comment]
Yep, that indeed does not look right. Looks like we need to do something like store _type_ (device or instance) information in [DeprecationData](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/73388b3fb9b7de3cd4266a6dc6ab59d115f86a23/layers/best_practices_validation.h#L109) and check against that before calling into `BestPractices::ValidateDeprecatedExtensions`.

**Comment by spnda** [comment]
Yes there's obviously a validation error about the instance version being higher than the device version:
```
vkCreateDevice(): API Version of current instance, 1.3.0 (0x00403000) is higher than API Version on device, 1.1.217
```

This was talked about in the discussion on Discord and there has been a comment on https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3771#issuecomment-1179595777 regarding this.

**Comment by ncesario-lunarg** [comment]
I'm not sure I completely agree with @charles-lunarg's comment in 3771, but that's somewhat suggestive :) ; warning if you request version A.B, but your device only supports X.Y seems like a perfectly good _warning_ (i.e., **not** an _error_) to me, but that is a different warning and issue than what's going on here.

I'm pretty sure the problem here is that we are checking device extensions against the _instance version_, rather than the _device version_, which needs to be fixed.
