### ISSUE TITLE
Detect required API version for tests using extensions with api version requirements

### ISSUE THREAD

**Issue by sjfricke** [KhronosGroup/Vulkan-ValidationLayers#4299]
```c++
// SetTargetApiVersion(VK_API_VERSION_1_1);
AddOptionalExtensions(VK_KHR_MAINTENANCE_4_EXTENSION_NAME);
ASSERT_NO_FATAL_FAILURE(Init());
```

Will crash on a 1.3 device because in [the spec for VK_KHR_maintenance4](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VK_KHR_maintenance4) it says 

> Requires support for Vulkan 1.1

I don't think the test framework has to be super smart and try setting the target API when an extension like `VK_KHR_maintenance4` is used, but for the future test writers out there we should have a better message than `Assertion: 'vk::CreateDevice(phy_.handle(), &info, __null, &dev) == VK_SUCCESS'` when this happens

in `AddRequestedInstanceExtensions` in `info.requirements` it can detect the `VK_VERSION_1_1_NAME` from `vk_extension_helper.h` and use that to give a useful error message to the test writer.

**Comment by spencer-lunarg** [comment]
We now produce the error

> Validation Error: [ VUID-vkCreateDevice-ppEnabledExtensionNames-01387 ] Object 0: handle = 0x558f22657c10, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x12537a2c | Missing extension required by the device extension VK_KHR_maintenance4: VK_VERSION_1_1. The Vulkan spec states: All required device extensions for each extension in the VkDeviceCreateInfo::ppEnabledExtensionNames list must also be present in that list (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCreateDevice-ppEnabledExtensionNames-01387)

Which is perfect and what I was hoping, as it tells me `VK_VERSION_1_1` is missing
