### ISSUE TITLE
Validation of VUID-VkImageViewCreateInfo-image-01586 is too strict

### ISSUE THREAD

**Issue by JoergArm** [KhronosGroup/Vulkan-ValidationLayers#4305]
**Describe the Issue**
While we have Conformance tests which rely on view-format-compatibility of aspects of mutable multi-planar images the VL is only allowing the usage of view formats which are precisely enumerated in the referenced table. Transitive compatibility (using the table's entry as an exemplary format for all covered by the MUTABLE property) is not permitted by the VL.

**Valid Usage ID**
Example:
Test case 'dEQP-VK.ycbcr.plane_view.image_view.g8_b8r8_2plane_420_unorm_disjoint_plane_0_compatible_format_r8_sint'..
VUID-VkImageViewCreateInfo-image-01586(ERROR / SPEC): msgNum: -52293694 - Validation Error: [ VUID-VkImageViewCreateInfo-image-01586 ] Object 0: handle = 0xfd5b260000000001, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0xfce20fc2 | vkCreateImageView(): ImageView format VK_FORMAT_R8_SINT is not compatible with plane 0 of underlying image format VK_FORMAT_G8_B8R8_2PLANE_420_UNORM, must be VK_FORMAT_R8_UNORM. The Vulkan spec states: If image was created with the VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT flag, if the format of the image is a multi-planar format, and if subresourceRange.aspectMask is one of VK_IMAGE_ASPECT_PLANE_0_BIT, VK_IMAGE_ASPECT_PLANE_1_BIT, or VK_IMAGE_ASPECT_PLANE_2_BIT, then format must be compatible with the VkFormat for the plane of the image format indicated by subresourceRange.aspectMask, as defined in Compatible formats of planes of multi-planar formats (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkImageViewCreateInfo-image-01586)
    Objects: 1
        [0] 0xfd5b260000000001, type: 10, name: NULL

**Environment:**
 - OS: Linux
 - GPU: Mali
 - SDK or header version if building from repo: v1.3.217
 - Options enabled (synchronization, best practices, etc.): none.

**Additional context**
The Spec explains how to read this table in more detail outside of the VU description, most importantly:
"[...] and any format compatible with the listed single-plane format according to Format Compatibility Classes."

**Comment by sjfricke** [comment]
> VK_FORMAT_R8_SINT is not compatible ... must be VK_FORMAT_R8_UNORM.

So I think the simple fix here is

```patch
    VkFormat compat_format = FindMultiplaneCompatibleFormat(image_format, aspect_mask);
-    if (view_format != compat_format) {
+    auto image_class = FormatCompatibilityClass(compat_format);
+    auto view_class = FormatCompatibilityClass(view_format);
+    // Need to only check if one is NONE to handle edge case both are NONE
+    if ((image_class != view_class) || (image_class == FORMAT_COMPATIBILITY_CLASS::NONE)) {
```

Re-re-re-reading the VUID, I see it does talk about how it needs to be "Compatible" with the format returned from the Table mapping

(will also need to fix `MultiplaneIncompatibleViewFormat` test as well

**Comment by JoergArm** [comment]
Thanks - this fixes the problem with the CTS.
