### ISSUE TITLE
False positives after concurrently waiting for a timeline semaphore

### ISSUE THREAD

**Issue by glebov-andrey** [KhronosGroup/Vulkan-ValidationLayers#4308]
Sometimes, after multiple threads wait for (or check the value of) a timeline semaphore, one of the threads gets false positive errors, e.g. `VUID-vkDestroyBuffer-buffer-00922` (*All submitted commands that refer to buffer, either directly or via a `VkBufferView`, **must** have completed execution*).

This issue seems similar to #4271, but this case does not involve a fence, #4281 does not fix it, and it is more about command buffer use counts.

After some debugging, I'm pretty sure this is what's happening.
Let there be a command buffer `CB`, a buffer `Buffer` and a timeline semaphore `Sema`.
Some thread submits work:
- `vkCmdDoSomething(CB, Buffer, ...)`
- `vkQueueSubmit(CB, signalSemaphore=Sema, signalSemaphoreValue=10)`

Then two threads observe the semaphore's value and act on it (I might be wrong about the exact order of internal operations and locking):

| T0 | T1 |
|-|-|
| `vkGetSemaphoreCounterValue(Sema) == 10` | `vkGetSemaphoreCounterValue(Sema) == 10` |
| > `SEMAPHORE_STATE::RetireTimeline(Sema, 10)` | > `SEMAPHORE_STATE::RetireTimeline(Sema, 10)` |
| > > `SEMAPHORE_STATE::Retire` (locks `SEMAPHORE_STATE` first) | |
| > > > remove and return operations to retire | |
| | > > `SEMAPHORE_STATE::Retire` (locks `SEMAPHORE_STATE` second) |
| | > > > remove and return nothing |
| | > (return from `vkGetSemaphoreCounterValue`) |
| | `vkDestroyBuffer(Buffer)` |
| | > check `BUFFER_STATE::InUse()` |
| | > > check `CMD_BUFFER_STATE::InUse() == true` |
| | > **ERROR** `VUID-vkDestroyBuffer-buffer-00922` |
| > > (without the lock) actually retire the returned operations | |
| > > > `CMD_BUFFER_STATE::Retire()` and `CMD_BUFFER_STATE::EndUse()` | |

I haven't checked this, but judging by the code, the same error could occur if two threads wait for the same fence or for a fence and semaphore signalled by the same operation.

I attempted to fix the issue by locking `SEMAPHORE_STATE`'s lock for the entire duration of `RetireTimeline()`. But even after replacing the `shared_mutex` with a `recursive_mutex`, deadlocks still occurred between threads locking `SEMAPHORE_STATE` and `QUEUE_STATE` in different orders (at least that's what it looked like).

**Environment:**
 - OS: Windows 10
 - GPU: NVIDIA RTX 2080
 - Checked with SDK 1.3.216.0, the current `master` @ adf933c0, and with #4281 applied
 - Checked with and without `GPU_ASSISTED` and `SYNCHRONIZATION_VALIDATION` enabled

**Comment by jeremyg-lunarg** [comment]
Thanks for the detailed report. I should be able to recreate the problem from what you've provided.

**Comment by jeremyg-lunarg** [comment]
@glebov-andrey I haven't yet been able to reproduce this problem. Does the test in #4328 look like what your application does or am I missing something? I do agree that this is almost certainly a bug but I don't want to fix it without having a regression test in place. Thanks!

**Comment by glebov-andrey** [comment]
@jeremyg-lunarg It looks close enough, but as far as I can tell, #4328 never actually submits the command buffer - it only ever fills  the semaphore to signal in `submit_info`.

**Comment by jeremyg-lunarg** [comment]
> @jeremyg-lunarg It looks close enough, but as far as I can tell, #4328 never actually submits the command buffer - it only ever fills the semaphore to signal in `submit_info`.

Doh! I bet that is why it doesn't reproduce the problem.  This test is based on the other test, and I didn't completely update it. Thank you for reviewing!
