### ISSUE TITLE
Check for VUID 00017 should use the render pass instance layercount

### ISSUE THREAD

**Issue by janharaldfredriksen-arm** [KhronosGroup/Vulkan-ValidationLayers#4322]
**Describe the Issue**
The VU says:

```
VUID-vkCmdClearAttachments-pRects-00017
The layers specified by each element of pRects must be contained within every attachment that pAttachments refers to
```

The "contained within" statement here is intended to refer to the number of layers in the _attachment_ (i.e. the render pass instance). Currently, the validation layers check against the number of layers in the attachment's _image view_.

The Vulkan WG will clarify this (internal issue 3157).

**Valid Usage ID**
00017 (potentially it gets a new number after spec clarification)

**Environment:**
 - Any

**Additional context**

[internal MR](https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5296/diffs)
[PR VUID updated](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4595)

**Comment by mikes-lunarg** [comment]
New VUID is `VUID-vkCmdClearAttachments-pRects-06937` in #4341
