### ISSUE TITLE
Image view with multiple layers validation Error 

### ISSUE THREAD

**Issue by Simoncl** [KhronosGroup/Vulkan-ValidationLayers#4345]
Building an image view with multiple layers. Setting the view to VK_IMAGE_VIEW_TYPE_2D_ARRAY and also tried imageViewCI.subresourceRange.layerCount = VK_REMAINING_ARRAY_LAYERS but still getting a validation error. This was not the case with Vulkan  1.2.170.0

validation layer: Validation Error: [ VUID-VkImageViewCreateInfo-imageViewType-04973 ] Object 0: handle = 0xd10d270000000018, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x8ab1932c | vkCreateImageView(): subresourceRange.layerCount (2) must be 1 when using viewType VK_IMAGE_VIEW_TYPE_2D (try looking into VK_IMAGE_VIEW_TYPE_*_ARRAY). The Vulkan spec states: If viewType is VK_IMAGE_VIEW_TYPE_1D, VK_IMAGE_VIEW_TYPE_2D, or VK_IMAGE_VIEW_TYPE_3D; and subresourceRange.layerCount is not VK_REMAINING_ARRAY_LAYERS, then subresourceRange.layerCount must be 1 

**Valid Usage ID**
[VUID-VkImageViewCreateInfo-imageViewType-04973 ] 

**Environment:**
Windows 10
Nvidia 2080 TI
1.3.216.0/windows/1.3-extensions
Info, Warning, Performance, Error

**Additional context**

**Comment by sjfricke** [comment]
>  Setting the view to VK_IMAGE_VIEW_TYPE_2D_ARRAY

The error says 

> when using viewType VK_IMAGE_VIEW_TYPE_2D

So it seems like you might not have actually been setting it to `VK_IMAGE_VIEW_TYPE_2D_ARRAY` like you think

**Comment by Simoncl** [comment]
I can replicate this validation error with a very simple set up too

**Comment by sjfricke** [comment]
here is [where it is checked](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/bbff1dc59468540736f2535cdfbad3ff436e26ec/layers/buffer_validation.cpp#L6085) and `string_VkImageViewType(view_type)` [is correct](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/bbff1dc59468540736f2535cdfbad3ff436e26ec/layers/generated/vk_enum_string_helper.h#L3493) so the fact it says `VK_IMAGE_VIEW_TYPE_2D` is still concerning

We have many tests this VU in [CreateImageViewInvalidSubresourceRange](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/bbff1dc59468540736f2535cdfbad3ff436e26ec/tests/vklayertests_buffer_image_memory_sampler.cpp#L8708)

I am not dismissing there might be a bug, but from the information given, I can't see it. A way to replicate the bug would be best way to help

**Comment by sjfricke** [comment]
> In Render Doc the attachment with multiple layers works even though I get the validation error

When a validation error is broken it is `undefined behavior` so yes there is a chance it might "still work" but also a chance it might crash on another GPU

**Comment by Simoncl** [comment]
So shall I upload a code example that exhibits this issue?

**Comment by sjfricke** [comment]
If you have an [API dump](https://vulkan.lunarg.com/doc/view/1.2.148.1/windows/api_dump_layer.html)  of the VkImage and VkImageView creation that would be enough for me to write an internal test in the VVL code for you

**Comment by Simoncl** [comment]
[apiDump.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/9173018/apiDump.txt)

**Comment by Simoncl** [comment]
I have uploaded the api dump around the  VkImage and VkImageView creation

**Comment by Simoncl** [comment]
Apologies for wasting your time.  I have found MY bug:(((

**Comment by sjfricke** [comment]
The `VkImage` that is the issue is not in this API dump, not the validation warning says `Object 0: handle = 0xd10d270000000018` but the VkImage handle is `0x00000175041C7070`

Also the error also says 

> subresourceRange.layerCount (2)

But the `VkImageView` here is `VK_REMAINING_ARRAY_LAYERS`

Also not sure why it is printing the error after `vkGetPhysicalDeviceFormatProperties2`

**Comment by Simoncl** [comment]
Yeah apologies again. The attachment I thought was the issue gets passed to a render pass node in my build graph that optionally adds a depth attachment,  it's this attachment that had the wrong image view type . Interestingly Vulkan 1.2.170.0  was not giving me an error. So that's cool 1.3 has picked it up:))

**Comment by sjfricke** [comment]
Happy to help, and glad the new updates to the layer caught a new bug!

**Comment by ncesario-lunarg** [comment]
Sounds like this issue can be closed @Simoncl?

**Comment by Simoncl** [comment]
yep Thank you again for our time.
