### ISSUE TITLE
VUID-vkCreatePrivateDataSlot-privateData-04564 check is present, but not trigger

### ISSUE THREAD

**Issue by archimedus** [KhronosGroup/Vulkan-ValidationLayers#4351]
**Describe the situation in which you encountered the missing validation**
Issue description:

For the extension VK_EXT_private_data additional validation is desirable.
Following extension functions should produce a validation error:

    vkCreatePrivateDataSlotEXT
    vkDestroyPrivateDataSlotEXT
    vkGetPrivateDataEXT
    vkSetPrivateDataEXT

if private data feature is not enabled during VkDevice creation.
According to extension VkDevice should be created with feature enabled:
i.e. either VkPhysicalDevicePrivateDataFeatures.privateData=true
or VkPhysicalDeviceVulkan13Features.privateData=true and one of these
structure must be included into VkDeviceCreateInfo.

**Valid Usage IDs requested**
VUID-vkCreatePrivateDataSlot-privateData-04564

**Though the code is present in the validation layer code (I used 1.3.216.0) provided VUID has not appeared in the output.**

I am sure the layers configured correctly as in the output I observe another error, to be exact:
Validation Error: [ VUID-VkInstanceCreateInfo-pNext-pNext ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xb04aea2d | vkCreateInstance: pCreateInfo->pNext chain includes a structure with unknown VkStructureType (1100000001);

Thus I would expect at least vkCreatePrivateDataSlotEXT should trigger the VUID in the output.

**Additional Context**
VkDeviceCreationInfo did not contain neither VkPhysicalDevicePrivateDataFeatures, nor VkPhysicalDeviceVulkan13Features.

**Comment by Tony-LunarG** [comment]
There's a test in tests\vklayertests_others.cpp for that VUID.  It's called PrivateDataFeature and you can run it (after building tests) by exporting VK_LAYER_PATH to your layers build directory and running 
vk_layer_validation_tests.exe --gtest_filter=VkLayerTest.PrivateDataFeature

Does that test pass for you?  If so, what could you be doing or not doing that the test is doing or not doing.  If not, could your layers be misconfigured - running the test with VK_LOADER_DEBUG=all exported could shed light there.

**Comment by Tony-LunarG** [comment]
Without knowing how this use case is different from VkLayerTest.PrivateDataFeature this issue cannot be addressed.  Feel free to re-open or file a new issue with more information
