### ISSUE TITLE
VUID_Core_Shader_OutputNotConsumed incorrectly reported as error?

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/Vulkan-ValidationLayers#4352]
**Describe the Issue**
Starting with 43c84ca0466d21c9fb21d8364275dffe6095336e if VK_KHR_maintenance4 is not enabled, outputs not being consumed by a shader stage was changed from a performance warning into an error.  I'm not sure what the basis of this change was according to the specification.  

Since at least Vulkan 1.0.22 the specification has had language in section 15.1.3 Interface matching that says

```Shaders can declare and write to output variables that are not declared or read by the subsequent stage.```

The spirv-opt inline exhaustive pass that is run as part of HLSL legalization for glslang and DXC will produce shaders that do this.  For example:

```
struct PS_INPUT 
{ 
    float4 vTex : TEXCOORD0 ; 
    float4 vColor : TEXCOORD1 ; 
    
    
} ; 
struct PS_OUTPUT 
{ 
    float4 vColor : SV_Target0 ; 
} ; 


PS_OUTPUT MainPs ( PS_INPUT i ) 
{ 
    PS_OUTPUT o ; 
  
    o . vColor = i . vColor ; 
    
    
    return o ; 
} 
```
glslangvalidator -D -e MainPs -S frag -V test.hlsl will produce this SPIR-V.  Notice that the i.vTex is eliminated:

```
; SPIR-V
; Version: 1.0
; Generator: Khronos Glslang Reference Front End; 10
; Bound: 37
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %MainPs "MainPs" %i_vColor %_entryPointOutput_vColor
               OpExecutionMode %MainPs OriginUpperLeft
               OpSource HLSL 500
               OpName %MainPs "MainPs"
               OpName %i_vColor "i.vColor"
               OpName %_entryPointOutput_vColor "@entryPointOutput.vColor"
               OpDecorate %i_vColor Location 1
               OpDecorate %_entryPointOutput_vColor Location 0
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
%_ptr_Input_v4float = OpTypePointer Input %v4float
   %i_vColor = OpVariable %_ptr_Input_v4float Input
%_ptr_Output_v4float = OpTypePointer Output %v4float
%_entryPointOutput_vColor = OpVariable %_ptr_Output_v4float Output
     %MainPs = OpFunction %void None %3
          %5 = OpLabel
         %33 = OpLoad %v4float %i_vColor
               OpStore %_entryPointOutput_vColor %33
               OpReturn
               OpFunctionEnd
````

I think this should remain a performance warning and not be an error, regardless of whether VK_KHR_maintenance4 is enabled.  I don't understand the reasoning behind turning this into an error.

**Comment by ncesario-lunarg** [comment]
I vaguely recall some confusion when this was turned into an error, and thought part of that stemmed from https://github.com/KhronosGroup/Vulkan-Docs/pull/1860, but can't recall the details. In any case, this this looks valid and the spec seems pretty clear. I'm guessing our current check catches both the case where
1. an output variable has more components than an input variable (which _is_ a validation error based on the VUID @sjfricke added) and
2. the case where an output variable is not consumed, which should remain a perf warning

We probably just need to distinguish between these 2 cases.

**Comment by sjfricke** [comment]
> Starting with https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/43c84ca0466d21c9fb21d8364275dffe6095336e

The warning --to--> error was added by @stedob02 in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4163

>  I don't understand the reasoning behind turning this into an error.

So **to my knowledge** (might need someone internally with Gitlab access to research/remind why it was added to `VK_KHR_maintenance4`), the idea of the change in `VK_KHR_maintenance4` was because a vendor was not able to properly handle the interface mismatch and by supporting `VK_KHR_maintenance4` it was a way to guarantee the updated driver would be able to handle it. 

> thought part of that stemmed from https://github.com/KhronosGroup/Vulkan-Docs/pull/1860

https://github.com/KhronosGroup/Vulkan-Docs/pull/1860 was just there to added the explicit VUID (which never got labeled and still using the old `VUID_Core_Shader_OutputNotConsumed`)
https://registry.khronos.org/vulkan/specs/1.0/html/vkspec.html#VUID-RuntimeSpirv-OpTypeVector-06816
and
https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-RuntimeSpirv-maintenance4-06817

**Comment by danginsburg** [comment]
According to @Tobski in this comment the scenario I mention above (fragment shader having only user-defined input with location 1 while VS outputs 0/1) is allowed: https://github.com/KhronosGroup/Vulkan-Docs/issues/666#issuecomment-869491481

That issue was linked to from Khronos internal gitlab on the MR that was part of VK_KHR_maintenance4 that rewrote the interface matching section.  I think it should remain a performance warning, but maybe @Tobski can help shed some light here because I don't have the whole history.

**Comment by zmike** [comment]
The other (related) issue is that this error still prints if `VK_KHR_maintenance4` (the extension) is enabled.

**Comment by ncesario-lunarg** [comment]
@Tobski's comment would seem to confirm my assumption, though I've yet to look at that check in more detail.

@zmike the error printing when maintenance4 is enabled sounds like a straight up bug in validation, but I think we're testing that case. Is the maintenance4 feature enabled?

**Comment by zmike** [comment]
@ncesario-lunarg ignore me, I forgot there was a feature bit for this one :grimacing:
