### ISSUE TITLE
vkEnumeratePhysicalDevices get incorrect device info on win10

### ISSUE THREAD

**Issue by lxrui** [KhronosGroup/Vulkan-ValidationLayers#4354]
**Describe the Issue**
vkEnumeratePhysicalDevices() get 5 physical device(intel630 + 1080x2 + 3090x2) on Alienware laptop with intel630 + 1080 (embedded) + 3090(Alienware Graphic AmPlifier) actually.
Whether I create vkDevice on 1080 or 3090, the program will crash on glActiveTexture().
Only if I disable the 3090 in the Device Manager, vkEnumeratePhysicalDevices() can get correct result and the program also will function normally.

Crash reason:  EXCEPTION_ACCESS_VIOLATION_READ
Crash address: 0x40
Process uptime: 8 seconds

Thread 0 (crashed)
 0  nvoglv64.dll + 0x976107
    rax = 0x00007fff1b2b4f60   rdx = 0x0000000000000000
    rcx = 0x0000000000000000   rbx = 0x0000000000000000
    rsi = 0x0000000000000000   rdi = 0x0000000000000a00
    rbp = 0x0000000000000000   rsp = 0x0000000f230ca1b0
     r8 = 0x0000000000000a00    r9 = 0x00000000000005a0
    r10 = 0x0000000f22a62000   r11 = 0x0000000000000000
    r12 = 0x0000000000000000   r13 = 0x00007fff6c3f82f8
    r14 = 0x0000013e3c9908e0   r15 = 0x0000013e3c989ed0
    rip = 0x00007fff18df6107
    Found by: given as instruction pointer in context

**Environment:**
 - OS: Windows 10
 - GPU: Intel HD630 + GTX1080 + RTX3090

**Additional context**
[vk_debug.log](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/9195948/vk_debug.log)

**Comment by jeremyg-lunarg** [comment]
Are you running the validation layer when this happens? If not this should probably be a [Vulkan-Loader](https://github.com/KhronosGroup/Vulkan-Loader) issue.

**Comment by lxrui** [comment]
> Are you running the validation layer when this happens? If not this should probably be a [Vulkan-Loader](https://github.com/KhronosGroup/Vulkan-Loader) issue.

Thank for your hint, I will move it to Vulkan-Loader. And do you have any ideal about this issue?

**Comment by lxrui** [comment]
move to vulkan-loader: https://github.com/KhronosGroup/Vulkan-Loader/issues/986
