### ISSUE TITLE
Build error while running update_deps.py

### ISSUE THREAD

**Issue by NorbertGarnysAMD** [KhronosGroup/Vulkan-ValidationLayers#436]
See attached log, 
expected: Known-Good Revisions should build without errors from validation layers
[log.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/2529252/log.txt)

**Comment by karl-lunarg** [comment]
@NorbertGarnysAMD The linked issue (KhronosGroup/Vulkan-Loader#90) explains the problem.  The CMake changes in the loader repo required a very recent version of CMake, which of course made the build success depend on the CMake version.  The loader repo is being changed to not require the newer CMake version, and I suspect that the known-good revisions in this repo would be updated by @jeremy-lunarg  when the loader repo is fixed.

**Comment by jeremy-lunarg** [comment]
Fixed by #443
