### ISSUE TITLE
Missing validation for simultaneous use of parameters for vkQueuePresentKHR

### ISSUE THREAD

**Issue by martty** [KhronosGroup/Vulkan-ValidationLayers#4388]
**Describe the situation in which you encountered the missing validation**
Issue description: vkQueuePresentKHR has some externally synchronized parameters, most importantly the swapchain, which is not validated.

**Valid Usage IDs requested**
Please include the valid usage IDs for the checks you are requesting: external synchronization

**Additional Context**
Any additional information:

**Comment by sjfricke** [comment]
all the externally synchronized parameters should be done in `layers/generated/thread_safty.cpp` but looking at the spec there are a few parameters that are arrays (`pWaitSemaphores` and `pSwapchains` for `vkQueuePresentKHR`)

`vkResetFences`, `vkFreeDescriptorSets`, `vkFreeCommandBuffers`, and `vkCreateSharedSwapchainsKHR` seem to be doing it correctly for their array parameters, but there is nothing for `vkQueuePresentKHR` at all as you pointed out... instresting...

So the fix will be to add a special case for `vkQueuePresentKHR` into `thread_safty_generator.py`

----

Spec language for reference

> Each element of the pWaitSemaphores member of the pPresentInfo parameter in vkQueuePresentKHR
> 
> Each element of the pSwapchains member of the pPresentInfo parameter in vkQueuePresentKHR

**Comment by artem-lunarg** [comment]
Fixed in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6400
