### ISSUE TITLE
No checks during `vkAllocateDescriptorSets` for push-descriptor descriptor layouts

### ISSUE THREAD

**Issue by PixelyIon** [KhronosGroup/Vulkan-ValidationLayers#4400]
**Describe the situation in which you encountered the missing validation**
There's no validation error when a `VkDescriptorSetLayout` that was created with the `VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT_KHR` flag is passed into `vkAllocateDescriptorSets`.

**Valid Usage IDs requested**
[`VUID-VkDescriptorSetAllocateInfo-pSetLayouts-00308`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDescriptorSetAllocateInfo.html#VUID-VkDescriptorSetAllocateInfo-pSetLayouts-00308)

**Comment by sjfricke** [comment]
This is being validated
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/5bd80db8bd3f06d20e6aac389f841742839f8cfc/layers/descriptor_validation.cpp#L2855

1. What version of the Validation layers (or SDK) are you using?
2. You have an [API dump](https://vulkan.lunarg.com/doc/view/latest/windows/api_dump_layer.html) of the section or another way to reproduce this as there already is a test (`VkLayerTest.AllocatePushDescriptorSet`) and it seems this VU is working as expected

**Comment by PixelyIon** [comment]
Sorry for the extremely late reply, I somehow didn't get the notification. It's likely that my validation layer was out of date as this check is covered in code. In any case, I'll close this issue since it's already covered, my bad for not double checking prior.

**Comment by sjfricke** [comment]
No problem! If you find this issue coming up again, please reopen, but with the information I suggested to give above
