### ISSUE TITLE
Potential race for sync fd fence export and retire

### ISSUE THREAD

**Issue by zhangyiwei** [KhronosGroup/Vulkan-ValidationLayers#4402]
**Describe the Issue**
sync_fd external fence export implies a fence reset operation, which has been reflected by `PostCallRecordGetFenceFdKHR`. However, it misses to remove this exported sync_fd fence from the associated submission. If there's another fence been waited, the prior submissions will be processed and the associated fence will be set to retired. Then the below VU violation shows up upon the next submission using the sync_fd fence.

**Valid Usage ID**
Validation Error: [ VUID-vkQueueSubmit-fence-00063 ] Object 0: handle = 0xe7e6d0000000000f, type = VK_OBJECT_TYPE_UNKNOWN; | MessageID = 0x6f35a2b3 | vkQueueSubmit(): VkNonDispatchableHandle 0xe7e6d0000000000f[] submitted in SIGNALED state.  Fences must be reset before being submitted The Vulkan spec states: If fence is not VK_NULL_HANDLE, fence must be unsignaled (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkQueueSubmit-fence-00063)

**Environment:**
 - OS: linux

**Comment by zhangyiwei** [comment]
Hmmm, https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4281 might have just fixed this external sync_fd fence issue as well with the additional condition of `state_ == FENCE_INFLIGHT` before retiring the fence. Let me build the tot to check.

**Comment by zhangyiwei** [comment]
No matter this gets luckily fixed by #4281 or not, I still encourage an explicit path for sync_fd specialty to avoid future regressions ; )

ps: sorry i haven't gotten time to test against tot yet

**Comment by jeremyg-lunarg** [comment]
Can you provide any code or just a list of API calls that would be a good starting point for a test case for this?

**Comment by zhangyiwei** [comment]
Setup
- 1 queue
- 2 native fences created with signaled states
- 1 sync_fd external fence

A sequence would be:
- reset native fence 1
- submit native fence 1
- wait native fence 2
- submit sync_fd fence
- export sync_fd fence
- reset native fence 2
- submit native fence 2
- wait native fence 1
- submit sync_fd fence <= seeing `VUID-vkQueueSubmit-fence-00063` violation
- export sync_fd fence
- keep looping and see such violation on each later sync_fd fence submission

Above is without #4281
