### ISSUE TITLE
Does VVL use the XML 'extension' attribute on <requires> tags?

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-ValidationLayers#4411]
We need to make a schema update to allow greater flexibility in describing extension dependencies of APIs, but I don't know if that change would have downstream impacts - checking here as a first step. See internal issue 2922 in the vulkan repo for more context.

**Comment by ncesario-lunarg** [comment]
I would say yes: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/20f4a87be1735a6aa6506388e51f3e1b5f07d0c5/scripts/parameter_validation_generator.py#L655

I'm pretty sure this is used to generate code for making sure dependent extensions are enabled, but there are probably other purposes. @mikes-lunarg may have some additional context.

**Comment by mikes-lunarg** [comment]
@ncesario-lunarg That's really all we use it for. Currently, this extension check is only done for entry points so the proposed change from internal MR 5355 won't cause any problems right away (though it would still be a good idea to implement the expanded schema). Supporting logical ORs in the list of extension dependencies will take some rework as well.

**Comment by oddhack** [comment]
OK, the internal MR is ready now - I pinged @mikes-lunarg there to ask if VVL could check out the XML change and see if it causes issues. If not, your signoff on the MR would be welcome.

**Comment by mikes-lunarg** [comment]
I gave a thumbs up on the internal MR, will close this now
