### ISSUE TITLE
Validation error regarding VkPipelineLayout lifetime

### ISSUE THREAD

**Issue by Cyphall** [KhronosGroup/Vulkan-ValidationLayers#4414]
**Describe the Issue**
The Vulkan specification says :
> A VkRenderPass or VkPipelineLayout object passed as a parameter to create another object is not further accessed by that object after the duration of the command it is passed into.

If I understand this correctly, it means that when I create a `VkPipeline` using a `VkPipelineLayout`, once the call to `vkCreateGraphicsPipelines()` returns, the `VkPipelineLayout` can be safely destroyed.
However, the validation message I recieved tells me that I am supposed to keep the `VkPipelineLayout` object alive for the lifetime of the `VkPipeline`.

**Valid Usage ID**
```
ERROR (UNASSIGNED-GPU-Assisted-Validation): Validation Error: [ UNASSIGNED-GPU-Assisted-Validation ] Object 0: handle = 0x1765c3483b0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xea8d5c05 | Setup Error. Detail: (Pipeline layout has been destroyed, aborting GPU-AV)
```

**Environment:**
 - OS: Windows 10 21H2
 - GPU: RTX 3070 (driver version 512.95)
 - SDK version: 1.3.216.0
 - Options enabled:
     - `vk::ValidationFeatureEnableEXT::eGpuAssisted`
     - `vk::ValidationFeatureEnableEXT::eSynchronizationValidation`

**Comment by Tony-LunarG** [comment]
Addressed in #4922
