### ISSUE TITLE
Pixel 6 crashes and failures

### ISSUE THREAD

**Issue by lunarpapillo** [KhronosGroup/Vulkan-ValidationLayers#4425]
We're preparing to add the Goole **Pixel_6** to CI.  Running VVL on a **Pixel_6** with the July 15, 2022 Google system update:
```
[ro.build.description]: [oriole-user 12 SQ3A.220705.004 8836240 release-keys]
```
provokes 13 crashes and 16 failures.  These are being removed from CI testing until VVL engineers have opportunity to address them.  When the issues have all been addressed, please assign this back to the originator, to remove the CI blacklist.

#### 13 crashing tests
- `VkLayerTest.AndroidHardwareBufferMemoryAllocation`
- `VkLayerTest.AndroidHardwareBufferImportBuffer`
- `VkLayerTest.AndroidHardwareBufferExporttBuffer` (should fix spelling on this too)
- `VkLayerTest.AndroidHardwareBufferImportBufferHandleType`
- `VkLayerTest.InlineUniformBlockEXT`
- `VkLayerTest.TransformFeedbackCmdBindTransformFeedbackBuffersEXT`
- `VkLayerTest.TransformFeedbackCmdBeginTransformFeedbackEXT`
- `VkLayerTest.TransformFeedbackCmdEndTransformFeedbackEXT`
- `VkGpuAssistedLayerTest.GpuValidationInlineUniformBlockAndMiscGpu`
- `VkPositiveLayerTest.AndroidHardwareBufferDepthStencil`
- `VkPositiveLayerTest.AndroidHardwareBufferBindBufferMemory`
- `VkPositiveLayerTest.OpCopyObjectSampler`
- `VkPositiveLayerTest.TestShaderInputAndOutputStructComponents`

#### 16 failing tests
- `VkLayerTest.CreatePipelineLayoutExcessPerStageDescriptors`
- `VkLayerTest.CreatePipelineLayoutExcessDescriptorsOverall`
- `VkLayerTest.CreateImageMaxLimitsViolation`
- `VkLayerTest.AndroidHardwareBufferInvalidBindBufferMemory`
- `VkLayerTest.ImageDrmFormatModifer`
- `VkLayerTest.FramebufferCreateErrors`
- `VkLayerTest.DrawIndirectByteCountEXT`
- `VkLayerTest.InvalidMixingProtectedResources`
- `VkLayerTest.BindImageMemorySwapchain`
- `VkGpuAssistedLayerTest.DrawTimeShaderUniformBufferTooSmall`
- `VkGpuAssistedLayerTest.DrawTimeShaderStorageBufferTooSmall`
- `VkGpuAssistedLayerTest.DrawTimeShaderUniformBufferTooSmallArray`
- `VkGpuAssistedLayerTest.DrawTimeShaderUniformBufferTooSmallNestedStruct`
- `VkGpuAssistedLayerTest.GpuDrawIndirectFirstInstance`
- `VkPositiveLayerTest.AndroidHardwareBufferMemoryRequirements`
- `VkPositiveLayerTest.PhysicalStorageBuffer`

**Comment by lunarpapillo** [comment]
This output might help provide more information about the failures (but not about the crashes):
[blacklist.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/9354476/blacklist.txt)

**Comment by sjfricke** [comment]
- `CreatePipelineLayoutExcessPerStageDescriptors`
- `CreatePipelineLayoutExcessDescriptorsOverall`
- `DrawIndirectByteCountEXT`
- `ImageDrmFormatModifer`

 are failing from the 

> Attempted to call vkGetPhysicalDevice*2() with an effective API version of 1.0.0 

error that we have seen before. The fix is to either make sure to call `SetTargetApiVersion(VK_API_VERSION_1_1);` or use the new `VkLayerTest::GetPhysicalDevice(Features|Properties)2` Nate added which I purpose doing (and just made the PR)

**Comment by sjfricke** [comment]
also related issue (might be some overlap) https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4273

**Comment by sjfricke** [comment]
The `VkGpuAssistedLayerTest` tests seem to be failing because you must have a [Mali GPU Pixel 6](https://vulkan.gpuinfo.org/displayreport.php?id=15551#features) which doesn't support `vertexPipelineStoresAndAtomics` like the [Adreno GPU Pixel 6](https://vulkan.gpuinfo.org/displayreport.php?id=15189#features)... the fix would to properly check for the required features needed for all the `VkGpuAssistedLayerTest` tests

**Comment by lunarpapillo** [comment]
> you must have a [Mali GPU Pixel 6](https://vulkan.gpuinfo.org/displayreport.php?id=15551#features)

Correct - this one is a Mali-G78, but I think its proper gpuinfo link is: https://vulkan.gpuinfo.org/displayreport.php?id=12851

Hmmm, I wasn't even aware there were flavors of **Pixel 6**...

**Comment by lunarpapillo** [comment]
There have been significant changes in the failing tests (undoubtedly due to the efforts of all those participating in this issue).  The current list of failing/blacklisted tests is here:

#### 11 crashing tests
- `VkLayerTest.AndroidHardwareBufferMemoryAllocation`
- `VkLayerTest.AndroidHardwareBufferExportBuffer`
- `VkLayerTest.InlineUniformBlockEXT`
- `VkLayerTest.TransformFeedbackCmdBindTransformFeedbackBuffersEXT`
- `VkLayerTest.TransformFeedbackCmdBeginTransformFeedbackEXT`
- `VkLayerTest.TransformFeedbackCmdEndTransformFeedbackEXT`
- `VkGpuAssistedLayerTest.GpuValidationInlineUniformBlockAndMiscGpu`
- `VkArmBestPracticesLayerTest.RedundantRenderPassStore`
- `VkPositiveLayerTest.AndroidHardwareBufferDepthStencil`
- `VkPositiveLayerTest.OpCopyObjectSampler`
- `VkPositiveLayerTest.TestShaderInputAndOutputStructComponents`

#### 11 failing tests
- `VkLayerTest.CreateImageMaxLimitsViolation`
- `VkLayerTest.AndroidHardwareBufferImportBuffer`
- `VkLayerTest.AndroidHardwareBufferImportBufferHandleType`
- `VkLayerTest.FramebufferCreateErrors`
- `VkLayerTest.InvalidMixingProtectedResources`
- `VkLayerTest.BindImageMemorySwapchain`
- `VkGpuAssistedLayerTest.DrawTimeShaderUniformBufferTooSmall`
- `VkGpuAssistedLayerTest.DrawTimeShaderStorageBufferTooSmall`
- `VkGpuAssistedLayerTest.DrawTimeShaderUniformBufferTooSmallArray`
- `VkGpuAssistedLayerTest.DrawTimeShaderUniformBufferTooSmallNestedStruct`
- `VkGpuAssistedLayerTest.GpuDrawIndirectFirstInstance`

#### 1 test blacklisted due to test issue #4490 
- `VkLayerTest.InvalidStructPNext`

As usual, when the test failures have been addressed, CI will remove them from the external blacklist.

**Comment by lunarpapillo** [comment]
The blacklist exercise output file is attached.  It might be helpful in determining why a test failed or crashed.
[blacklist.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/9464551/blacklist.txt)

**Comment by lunarpapillo** [comment]
Several of the tests have been fixed and now appear to be working, and will be removed from the blacklist:
- `VkGpuAssistedLayerTest.GpuValidationInlineUniformBlockAndMiscGpu`
- `VkPositiveLayerTest.OpCopyObjectSampler`
- `VkLayerTest.BindImageMemorySwapchain`
- `VkGpuAssistedLayerTest.DrawTimeShaderUniformBufferTooSmall`
-  `VkGpuAssistedLayerTest.DrawTimeShaderStorageBufferTooSmall`
-  `VkGpuAssistedLayerTest.DrawTimeShaderUniformBufferTooSmallArray`
- `VkGpuAssistedLayerTest.DrawTimeShaderUniformBufferTooSmallNestedStruct`
- `VkGpuAssistedLayerTest.GpuDrawIndirectFirstInstance`

The remaining failing tests are listed below.
#### 9 crashing tests
- `VkLayerTest.AndroidHardwareBufferMemoryAllocation`
- `VkLayerTest.AndroidHardwareBufferExportBuffer`
- `VkLayerTest.InlineUniformBlockEXT`
- `VkLayerTest.TransformFeedbackCmdBindTransformFeedbackBuffersEXT`
- `VkLayerTest.TransformFeedbackCmdBeginTransformFeedbackEXT`
- `VkLayerTest.TransformFeedbackCmdEndTransformFeedbackEXT`
- `VkArmBestPracticesLayerTest.RedundantRenderPassStore`
- `VkPositiveLayerTest.AndroidHardwareBufferDepthStencil`
- `VkPositiveLayerTest.TestShaderInputAndOutputStructComponents`

#### 5 failing tests
- `VkLayerTest.CreateImageMaxLimitsViolation`
- `VkLayerTest.AndroidHardwareBufferImportBuffer`
- `VkLayerTest.AndroidHardwareBufferImportBufferHandleType`
- `VkLayerTest.FramebufferCreateErrors`
- `VkLayerTest.InvalidMixingProtectedResources`

#### 1 blacklisted due to test issue #4490 
- `VkLayerTest.InvalidStructPNext`

**Comment by juan-lunarg** [comment]
The following 4 tests were added to the blacklist:
- `VkPositiveLayerTest.AndroidHardwareBufferDepthStencil`
- `VkLayerTest.CreateImageMiscErrors`
- `VkLayerTest.AndroidHardwareBufferDedicatedUsageDS`
- `VkBestPracticesLayerTest.UseDeprecatedInstanceExtensions`

**Comment by spencer-lunarg** [comment]
This issue got stale - many of these tests are renamed and/or been worked on

I am currently trying to reduce which tests are "still" failing, from there will make the proper issues to looking into why
