### ISSUE TITLE
spurious VUID-vkDestroySemaphore-semaphore-01137?

### ISSUE THREAD

**Issue by drewcrawford** [KhronosGroup/Vulkan-ValidationLayers#4428]
**Describe the Issue**
I am attempting to track down a (spurious?) VUID-vkDestroySemaphore-semaphore-01137 in my application.

I have tracked it down to [this reproducer](https://github.com/drewcrawford/semaphore-repro), on my system this reproduces in a few seconds on 3 out of 5 attempts.

```
$ cargo run
[... output trimmed ...]
vulkan_debug_callback VERBOSE_EXT GENERAL_EXT "Device Extension: VK_EXT_image_2d_view_of_3d (C:\\Windows\\System32\\DriverStore\\FileRepository\\iigd_dch.inf_amd64_66738090704aeb53\\.\\igvk64.dll) version 0.0.1"
vulkan_debug_callback INFO_EXT GENERAL_EXT "loader_add_implicit_layer: Disabling implicit layer VK_LAYER_OBS_HOOK for using an old API version 1.2 versus application requested 131.0"
vulkan_debug_callback INFO_EXT GENERAL_EXT "loader_add_implicit_layer: Disabling implicit layer VK_LAYER_LUNARG_override for using an old API version 1.3 versus application requested 131.0"
301
VUID-vkDestroySemaphore-semaphore-01137(ERROR / SPEC): msgNum: -1588160456 - Validation Error: [ VUID-vkDestroySemaphore-semaphore-01137 ] Object 0: handle = 0x25fd9185bd8, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xa1569838 | Cannot call vkDestroySemaphore on VkSemaphore 0xcb3ee80000000007[] that is currently in use by a command buffer. The Vulkan spec states: All submitted batches that refer to semaphore must have completed execution (https://vulkan.lunarg.com/doc/view/1.3.216.0/windows/1.3-extensions/vkspec.html#VUID-vkDestroySemaphore-semaphore-01137)
    Objects: 1
        [0] 0x25fd9185bd8, type: 3, name: NULL
vulkan_debug_callback ERROR_EXT VALIDATION_EXT "Validation Error: [ VUID-vkDestroySemaphore-semaphore-01137 ] Object 0: handle = 0x25fd9185bd8, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xa1569838 | Cannot call vkDestroySemaphore on VkSemaphore 0xcb3ee80000000007[] that is currently in use by a command buffer. The Vulkan spec states: All submitted batches that refer to semaphore must have completed execution (https://vulkan.lunarg.com/doc/view/1.3.216.0/windows/1.3-extensions/vkspec.html#VUID-vkDestroySemaphore-semaphore-01137)"
```

I will briefly summarize the access pattern in the reproducer:
1.  In a frame-paced loop, empty command buffers are submitted to the queue.  Each `VkCommandBufferBeginInfo` will signal a (new/unique) timeline semaphore.
2. In another thread, the semaphores are aggressively polled with `vkGetSemaphoreCounterValue`.  
3. As soon as a semaphore is polled with a raised value, which can only be from the corresponding command buffer completing, I call `vkDestroySemaphore`
4. Intermittently these destroys will trigger the validation message.

My understanding of the `vkQueueSubmit` documentation is that the semaphores are "signaled once the commands specified in pCommandBuffers have completed execution."  Therefore this VUID is a bit puzzling to me.

**Environment:**
 - OS:  Windows 11 10.0.22000 Build 22000
 - GPU:  Intel UHD Graphics 770, driver 0.404.3222
 - SDK or header version if building from repo: 1.3.216.0
 - Options enabled (synchronization, best practices, etc.): Core, ThreadSafety, Handle Wrapping, Object Lifetime, Stateless Parameter

**Additional context**

I have occasionally seen access violations inside the GPU driver when making minor timing changes to the reproducer.  I'm a little uncertain whether this is my bug, the vendor's bug, or if it somehow relates to this VUID.

**Comment by jeremyg-lunarg** [comment]
This should be resolved now that the fix for #4308 has merged. Please reopen if you're still seeing problems with the latest VVL code.
