### ISSUE TITLE
Crashes and failures on Linux AMD Radeon RX 6800 XT (RADV NAVI21)

### ISSUE THREAD

**Issue by lunarpapillo** [KhronosGroup/Vulkan-ValidationLayers#4433]
We've updated our **Ubuntu Mesa RADV** to a **Radeon RX 6800 XT**.
#### Crashes: 7
- `VkLayerTest.TransformFeedbackCmdBindTransformFeedbackBuffersEXT`
- `VkLayerTest.TransformFeedbackCmdBeginTransformFeedbackEXT`
- `VkLayerTest.TransformFeedbackCmdEndTransformFeedbackEXT`
- `VkLayerTest.BindImageMemorySwapchain`
- `VkPositiveLayerTest.CmdClearAttachmentTestsDynamicRendering`
- `VkPositiveLayerTest.CmdCopySwapchainImage`
- `VkPositiveLayerTest.DestroySwapchainWithBoundImages`
#### Failures: 15
- `VkLayerTest.TestBindBufferMemoryDeviceGroup`
- `VkLayerTest.DuplicatePhysicalDevices`
- `VkLayerTest.InvalidImageCreateFlagWithPhysicalDeviceCount`
- `VkLayerTest.CmdCopyUnboundAccelerationStructure`
- `VkLayerTest.BuildAccelerationStructureKHR`
- `VkLayerTest.TestWriteAccelerationStructureMemory`
- `VkLayerTest.TestBeginRenderingInvalidFragmentShadingRateImage`
- `VkLayerTest.TestBeginRenderingFragmentShadingRateImageView`
- `VkLayerTest.TestBeginRenderingFragmentShadingRateAttachmentSize`
- `VkLayerTest.TestBeginRenderingFragmentShadingRateAttachmentSizeWithDeviceGroupExt`
- `VkLayerTest.TransferImageToSwapchainWithInvalidLayoutDeviceGroup`
- `VkLayerTest.InvalidDeviceMask`
- `VkGpuAssistedLayerTest.GpuBufferDeviceAddressOOB`
- `VkPositiveLayerTest.TransferImageToSwapchainDeviceGroup`
- `VkPositiveLayerTest.ImagelessLayoutTracking`

**Comment by spencer-lunarg** [comment]
This issue got stale - many of these tests are renamed and/or been worked on

I am currently trying to reduce which tests are "still" failing, from there will make the proper issues to looking into why
