### ISSUE TITLE
Code-generate allowed DRM modifier structs in VkImageCreateInfo for 02251 validation

### ISSUE THREAD

**Issue by ncesario-lunarg** [KhronosGroup/Vulkan-ValidationLayers#4435]
When checking the formats in a `VkImageDrmFormatModifierListCreateInfoEXT` at image creation time, we need to ensure that all structs that extend from `VkPhysicalDeviceImageFormatInfo2` and `VkImageCreateInfo` are added to the `VkPhysicalDeviceImageFormatInfo2` at https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/21624bdccce73eee8680bd9fe7892e9128b3ce85/layers/buffer_validation.cpp#L1820.

FYI @zmike.

**Comment by spencer-lunarg** [comment]
closing as duplicate of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6256 which Arno is working on
