### ISSUE TITLE
`assert(VendorCheckEnabled(kBPVendorNVIDIA));` getting hit in Debug

### ISSUE THREAD

**Issue by sugoi1** [KhronosGroup/Vulkan-ValidationLayers#4440]
We're seeing asserts in Debug builds on all platforms in "BestPractices::RecordResetZcullDirection" when not using the NVidia driver here:
[Vulkan-ValidationLayers/layers/best_practices_utils.cpp](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/27f1e075c41daf1b3c229b48f913eb5649b28530/layers/best_practices_utils.cpp#L2055)

`assert(VendorCheckEnabled(kBPVendorNVIDIA));` is getting hit.

 - OS: All
 - GPU: Any non NVidia
 - SDK or header version if building from repo: ToT
 - Options enabled (synchronization, best practices, etc.): Debug

**Comment by sugoi1** [comment]
@rlocatti-nv @ncesario-lunarg PTAL

**Comment by rlocatti-nv** [comment]
`PreCallRecordCmdClearDepthStencilImage` doesn't have a vendor check guard. Working on a fix.
