### ISSUE TITLE
tests: SetTargetApiVersion() should return void

### ISSUE THREAD

**Issue by jeremyg-lunarg** [KhronosGroup/Vulkan-ValidationLayers#4449]
This function returns the minimum of the requested version and the version supported by the instance. Sometimes it is used to skip tests that require a version. But this is incorrect.  We also need the physical device version to meet the requirement.

So... this function should return void and DeviceValidationVersion() should be checked instead. 

For even more fun, can we make InitState() return a BAD_VERSION or MISSING_EXTENSION error to make it easier to skip?

**Comment by arno-lunarg** [comment]
So I modified SetTargetApiVersion() like you said, and replaced every call where the return value was used with a subsequent call do DeviceValidationVersion() after the init step (except when that call was already done).

I am not sure about changing InitState(), because in at least one test, `VkPositiveLayerTest.MultiplaneImageTests`, the test just proceed to other steps if the API version is not 1.1, so should not be skipped?

**Comment by jeremyg-lunarg** [comment]
> I am not sure about changing InitState(), because in at least one test, `VkPositiveLayerTest.MultiplaneImageTests`, the test just proceeds to other steps if the API version is not 1.1, so should not be skipped? :

Yes, trying to change InitState() is probably too tricky and would have consequences in many tests.

**Comment by ncesario-lunarg** [comment]
I'd like to eventually change `InitFramework` to accept a list of extensions to enable and return either success or failure + an error message. The `Add(Required|Optional)Extensions` must occur _before_ `InitFramework` for it to work properly, so it is one more thing that _can_ be called in an incorrect order and therefore must be checked at code review time. So something like:
```cpp
struct TestRequirements { // <- or a better name
    std::vector<const char*> required_extensions; // <- will effectively just call AddRequiredExtensions on each element
    std::vector<const char*> optional_extensions; // <- will effectively just call AddOptionalExtensions on each element
    uint32_t requested_version = VK_API_VERSION_1_0;
    void* p_next = nullptr;
    // perhaps a lambda or some other means of checking features and properties?
    ...
    std::string error_msg; // <- non-empty on failure. Would include the RequiredExtensionsNotSupported() << " not supported." string
};
```
Then a test would look like
```cpp
TestRequirements reqs;
reqs.required_extensions = { VK_KHR_8BIT_STORAGE_EXTENSION_NAME, ... };
...
InitFramework(reqs);

// Ideally would want some way to streamline the following as well
if (!reqs.error_msg.empty()) {
    GTEST_SKIP() << reqs.error_msg;
}
```

**Comment by arno-lunarg** [comment]
Yes my first impressions of the test suites was that the order things need to be done can be tricky to understand and error prone. I imagine that modifying existing test would be unfeasible, but maybe a new test suite base class could be introduced for new tests onward?

**Comment by arno-lunarg** [comment]
The PR fixes the issue.

**Comment by ncesario-lunarg** [comment]
> Yes my first impressions of the test suites was that the order things need to be done can be tricky to understand and error prone. I imagine that modifying existing test would be unfeasible, but maybe a new test suite base class could be introduced for new tests onward?

Right, we would effectively have to touch _every_ test. A new base class could make sense, but I think just adding an additional override of `InitFramework` should be sufficient and then tests can be converted gradually over time, eventually removing the "deprecated" overloads.
