### ISSUE TITLE
Access violation with NVIDIA Best Practices enabled

### ISSUE THREAD

**Issue by laurelkeys** [KhronosGroup/Vulkan-ValidationLayers#4456]
**Describe the Issue**
When testing the new NVIDIA Best Practices validation, an "**access violation writing location**" exception is thrown at `tree.GetState(layer, level)`:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/ac04e812d469b459358675a7249f10094591f915/layers/best_practices_utils.cpp#L2099-L2107

This happens because the `subresource_range` is using the following two [special values](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkImageSubresourceRange.html#_description):
- `subresource_range.levelCount` = `VK_REMAINING_MIP_LEVELS`
- `subresource_range.layerCount` = `VK_REMAINING_ARRAY_LAYERS`

which are not being handled, and lead the values of `i` and `j` to "blow up" since they are defined as `(~0U)`.

**Environment:**
 - OS: Windows 10
 - GPU: NVIDIA GTX 1060
 - SDK: 1.3.224.0
 - Options enabled: Validation's **Best Practices Preset**, with **NVIDIA-specific best practices** checked.
```
Current Enables: VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXT, VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_RESERVE_BINDING_SLOT_EXT, VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT, VALIDATION_CHECK_ENABLE_VENDOR_SPECIFIC_NVIDIA, VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION.

Current Disables: VK_VALIDATION_FEATURE_DISABLE_OBJECT_LIFETIMES_EXT, VK_VALIDATION_FEATURE_DISABLE_CORE_CHECKS_EXT, VK_VALIDATION_FEATURE_DISABLE_THREAD_SAFETY_EXT, VK_VALIDATION_FEATURE_DISABLE_API_PARAMETERS_EXT, VK_VALIDATION_FEATURE_DISABLE_UNIQUE_HANDLES_EXT.
```

**Comment by laurelkeys** [comment]
Side note: besides `RecordSetZcullDirection()` from the snippet above, [NVIDIA Best Practices](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4353) also added `RecordResetZcullDirection()` and `ValidateZcull()` and both have for-loops over `.layerCount` and `.levelCount` without checking for `~0U`.

**Comment by jeremyg-lunarg** [comment]
@rlocatti-nv can you take a look at this?

**Comment by jeremyg-lunarg** [comment]
It looks like creating and then iterating over a subresource_adapter::SubresourceGenerator with the IMAGE_STATE::subresource_encoder and the subresouce argument to the method should handle the special values correctly.

**Comment by rlocatti-nv** [comment]
Looking into it.
