### ISSUE TITLE
Incorrect ONE_TIME_SUBMIT warning with NVIDIA Best Practices enabled

### ISSUE THREAD

**Issue by laurelkeys** [KhronosGroup/Vulkan-ValidationLayers#4457]
**Describe the Issue**
Enabling the new NVIDIA Best Practices validation incorrectly reports the following **Validation Performance Warning** (line 1514):
`[NVIDIA] vkBeginCommandBuffer(): VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT was not set and the command buffer has only been submitted once. For best performance on NVIDIA GPUs, use ONE_TIME_SUBMIT.` even though `pBeginInfo->flags` = `VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT` (as verified using Visual Studio's debugger).
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/ac04e812d469b459358675a7249f10094591f915/layers/best_practices_utils.cpp#L1494-L1523

**Valid Usage ID**
`UNASSIGNED-BestPractices-vkBeginCommandBuffer-one-time-submit`

**Environment:**
 - OS: Windows 10
 - GPU: NVIDIA GTX 1060
 - SDK: 1.3.224.0
 - Options enabled: Validation's Best Practices Preset, with NVIDIA-specific best practices checked.
```
Current Enables: VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXT, VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_RESERVE_BINDING_SLOT_EXT, VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT, VALIDATION_CHECK_ENABLE_VENDOR_SPECIFIC_NVIDIA, VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION.

Current Disables: VK_VALIDATION_FEATURE_DISABLE_OBJECT_LIFETIMES_EXT, VK_VALIDATION_FEATURE_DISABLE_CORE_CHECKS_EXT, VK_VALIDATION_FEATURE_DISABLE_THREAD_SAFETY_EXT, VK_VALIDATION_FEATURE_DISABLE_API_PARAMETERS_EXT, VK_VALIDATION_FEATURE_DISABLE_UNIQUE_HANDLES_EXT.
```

**Additional context**
From a quick inspection of the code that sets `cb->is_one_time_submit`, it seems to me like the `if (cb) return;` should be replaced with `if (!cb) return;` (line 1488):
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/ac04e812d469b459358675a7249f10094591f915/layers/best_practices_utils.cpp#L1483-L1492

Alternatively, `PreCallRecordBeginCommandBuffer()` (the function that sets `cb->is_one_time_submit`, 2nd snippet) is only called **after** `PreCallValidateBeginCommandBuffer()` (the function that logs the warning, 1st snippet). Swapping the two could also fix the issue:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/55f77c5de1f76866e03da60bb1b76a8f3242b632/layers/generated/chassis.cpp#L2661-L2681

**Comment by jeremyg-lunarg** [comment]
@rlocatti-nv can you please take a look at this?

**Comment by paul-lunarg** [comment]
I've already written a test for this issue so I will try fixing it.

**Comment by paul-lunarg** [comment]
@laurelkeys Thanks for the detailed issue. It was, in fact, the "if (cb) return;" that was wrong. After adding a positive test it seems it is fixed.
