### ISSUE TITLE
NVIDIA: Driver confusion between buffer view size and buffer view elements

### ISSUE THREAD

**Issue by mbouchard2** [KhronosGroup/Vulkan-ValidationLayers#446]
Vulkan spec states that:

"If range is not equal to VK_WHOLE_SIZE, range divided by the element size of format must be less than or equal to VkPhysicalDeviceLimits::maxTexelBufferElements"

Unfortunately, the driver does not divide range by element size before checking.

Refer to this forum post:
https://devtalk.nvidia.com/default/topic/972407/vulkan/driver-confusion-between-buffer-view-size-and-buffer-view-elements/
@nsubtil

**Comment by pdaniell-nv** [comment]
Since this is probably specific to NVIDIA I made comment in the original forum post.

**Comment by jzulauf-lunarg** [comment]
The validation message for VUID-VkBufferViewCreateInfo-range-00930 in core_validation (the VU cited above) generated by core_validation doesn't emit the error message shown in the forum post, and does do the division required by the specification.

This is likely not a validation layer issue.
