### ISSUE TITLE
Missing essential information in Validation Error.

### ISSUE THREAD

**Issue by CarloWood** [KhronosGroup/Vulkan-ValidationLayers#4478]
I am currently running into the following validation error:

```
$4 = {sType = VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CALLBACK_DATA_EXT, pNext = 0x0, flags = 0, 
  pMessageIdName = 0x7fffec046a20 "VUID-VkGraphicsPipelineCreateInfo-layout-00756", messageIdNumber = 1165064310, 
  pMessage = 0x7fffec046c70 "Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-layout-00756 ] Object 0: handle = 0x7fffe4113eb0, name = LogicalDevice, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x45717876 | Shader uses descriptor slot 0.1 (expected `VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER`) but not declared in pipeline layout The Vulkan spec states: layout must be consistent with all shaders specified in pStages (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-layout-00756)", queueLabelCount = 0, 
  pQueueLabels = 0x0, cmdBufLabelCount = 0, pCmdBufLabels = 0x0, objectCount = 1, pObjects = 0x7fffec088bc0}
```

Aka,

```Shader uses descriptor slot 0.1 (expected `VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER`) but not declared in pipeline layout The Vulkan spec states: layout must be consistent with all shaders specified in pStages```

Where `pObjects` contains just

```
1: {objectType:Device, objectHandle:7fffe4113eb0, pObjectName:"LogicalDevice"}
```

What is missing here is: which shader? Which pipeline layout? Even if only -say- hexadecimal values are available, they are still better than nothing.

**Comment by sjfricke** [comment]
agree this is lacking the useful information you want from the validation error.

So a while ago a nice new `LogObjectList` struct was added so we could go

```cpp
LogObjectList objlist(module_state.vk_shader_module());
objlist.add(pipeline_layout->layout());
skip |= LogError(objlist, ....
```

but not every error message has been updated yet, but just pushed a PR up to address the shader validation to print out better object handle information

**Comment by CarloWood** [comment]
Thanks! When catching the validation error with a debug break point, it is of course possible to go up the stack and find that way which shader handle and pipeline layout handle were used (although that still doesn't give me the neat debug names that I coupled to those). But it is sure easier if all vulkan objects involved are printing (including their debug name).
