### ISSUE TITLE
check VUID-VkImageMemoryBarrier-image-04072 seems to be incorrect

### ISSUE THREAD

**Issue by xytovl** [KhronosGroup/Vulkan-ValidationLayers#4487]
**Describe the Issue**
When using validation layer on ffmpeg 4.4.2 it complained about incorrect usage of image memory barrier in
https://git.ffmpeg.org/gitweb/ffmpeg.git/blob/d61977cbe453869cec28d32b71fe25c2cd965dcf:/libavutil/hwcontext_vulkan.c#l1531

We have srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED
dstQueueFamilyIndex = VK_QUEUE_FAMILY_EXTERNAL_KHR

Message says "Destination queue family must be valid, ignored, or special", but check is
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/67b79bcb00a5f56cb6403b4c2546bbca08da9818/layers/buffer_validation.cpp#L5403
And this does not include the ignored case.

**Valid Usage ID**
VUID-VkImageMemoryBarrier-image-04072(ERROR / SPEC): msgNum: -456693645 - Validation Error: [ VUID-VkImageMemoryBarrier-image-04072 ] Object 0: handle = 0x7f8ea00fdaf0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xe4c76873 | vkCmdPipelineBarrier(): .pImageMemoryBarriers[0].image Barrier using VkImage VkImage 0xba7514000000002a[] created with sharingMode VK_SHARING_MODE_EXCLUSIVE, has srcQueueFamilyIndex 4294967295 (VK_QUEUE_FAMILY_IGNORED). Destination queue family must be valid, ignored, or special. The Vulkan spec states: If image was created with a sharing mode of VK_SHARING_MODE_EXCLUSIVE, and srcQueueFamilyIndex and dstQueueFamilyIndex are not equal, srcQueueFamilyIndex and dstQueueFamilyIndex must both be valid queue families, or one of the special queue family values reserved for external memory transfers, as described in Queue Family Ownership Transfer (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkImageMemoryBarrier-image-04072)
**Environment:**
 - OS: 
 - GPU:
 - SDK or header version if building from repo:
 - Options enabled (synchronization, best practices, etc.):

**Additional context**

**Comment by sjfricke** [comment]
So something I noticed is the error message says both

> sharingMode VK_SHARING_MODE_EXCLUSIVE, has **srcQueueFamilyIndex** 4294967295 (VK_QUEUE_FAMILY_IGNORED)

and

> Destination queue family must be valid, ignored, or special.

looking at the source, `kQueueErrorSummary[QueueError::kSrcAndDstValidOrSpecial]` is wrong and only says "Destination" and should say "Source and Destination"... can fix that quick

...but this means your error is your `srcQueueFamilyIndex` then (in case you were looking at the wrong spot)

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/67b79bcb00a5f56cb6403b4c2546bbca08da9818/layers/buffer_validation.cpp#L5406

Which I think `VK_QUEUE_FAMILY_IGNORED` is valid from re-reading the spec

**Comment by arno-lunarg** [comment]
VUID-VkImageMemoryBarrier-image-04072 states:

>If image was created with a sharing mode of VK_SHARING_MODE_EXCLUSIVE, and srcQueueFamilyIndex and dstQueueFamilyIndex are not equal, srcQueueFamilyIndex and dstQueueFamilyIndex must both be valid queue families, or one of the special queue family values reserved for external memory transfers, as described in Queue Family Ownership Transfer

So I think the VVL error message part you mentioned is just wrong, and should be:
> Source or destination queue family must be valid or special.

So @sjfricke's fix + remove _ignored_

**Comment by arno-lunarg** [comment]
So using
srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED
dstQueueFamilyIndex = VK_QUEUE_FAMILY_EXTERNAL_KHR

should indeed trigger validation

**Comment by ncesario-lunarg** [comment]
Based on the language in the spec, I think `VK_QUEUE_FAMILY_IGNORED` _is_ special...at least that's the way I was interpreting it. If that's the case, I was thinking the fix was as simple as adding `|| (queue_family == VK_QUEUE_FAMILY_IGNORED)` to https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/e5ac2812699382a399fef4bfc6d930ad45466ee3/layers/buffer_validation.cpp#L5398
but maybe I'm missing something.

**Comment by arno-lunarg** [comment]
Looking at [VUID-VkBufferMemoryBarrier2-buffer-04088](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkBufferMemoryBarrier2-buffer-04088) and [VUID-VkImageMemoryBarrier2-image-04071](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkImageMemoryBarrier2-image-04071), it seems my assumption was indeed wrong. Will put up the PR for the fix.
