### ISSUE TITLE
VUID-vkCmdDraw-None-02686 validation missing

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-ValidationLayers#4494]
**Describe the situation in which you encountered the missing validation**
The layers do not currently validate this VUID at all.

When using input attachments in a render pass, if the input attachment binding is used in the shader, then a validation error will result if nothing is bound to that binding at draw time. This is the same as any other binding that is used by the shader but not bound at draw time.

But according to the VUID, an input attachment must be bound if it's used by the subpass, regardless of whether it's used in the shader. Thus, there should be a validation error if no image is bound to an input attachment via a descriptor set, even if the shader never uses it.

**Valid Usage IDs requested**
VUID-vkCmdDraw-None-02686
> Every input attachment used by the current subpass **must** be bound to the pipeline via a descriptor set

**Comment by sjfricke** [comment]
seems like the VUID is there, but never actually checked anywhere as you mentioned... this seems the be where it was pulled out https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2244
