### ISSUE TITLE
Remove VVL coverage for removed VUID-VkImageViewCreateInfo-image-04739

### ISSUE THREAD

**Issue by pdaniell-nv** [KhronosGroup/Vulkan-ValidationLayers#4502]
The old VUID-VkImageViewCreateInfo-image-04739 has been removed from the latest Vulkan specification revision 226, so we should remove coverage from VVL.

See https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5362

**Comment by sjfricke** [comment]
fyi, where it was added
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3092/files
