### ISSUE TITLE
Replace VUID-VkImageViewCreateInfo-image-01584 with VUID-VkImageViewCreateInfo-image-07072

### ISSUE THREAD

**Issue by pdaniell-nv** [KhronosGroup/Vulkan-ValidationLayers#4503]
The old VUID-VkImageViewCreateInfo-image-01584 has been removed from the latest Vulkan specification revision 226 and should be replaced with coverage for [VUID-VkImageViewCreateInfo-image-07072](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkImageViewCreateInfo-image-07072).

This is a minor modification of the old VUID. See: https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5149

**Comment by paul-lunarg** [comment]
@pdaniell-nv To be clear, the only change to the VUID is this "and format is a non-compressed format", right ?

**Comment by paul-lunarg** [comment]
We also have validation for VUID-VkImageViewCreateInfo-image-04739 which seems to also have been removed and I can't seem to find a trace of it on google. The validation layers state it as this :
> "If image was created with the VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT flag and format is a non-compressed format, viewType must not be VK_IMAGE_VIEW_TYPE_3D"
Which is quite similar to 07072.
Should I also remove this VUID ?

**Comment by pdaniell-nv** [comment]
> To be clear, the only change to the VUID is this "and format is a non-compressed format", right ?

That's right.

> We also have validation for VUID-VkImageViewCreateInfo-image-04739 which seems to also have been removed and I can't seem to find a trace of it on google.

That's the subject of this issue: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4502
