### ISSUE TITLE
`gl_MeshPrimitivesEXT` corruption

### ISSUE THREAD

**Issue by unit-a-user** [KhronosGroup/Vulkan-ValidationLayers#4515]
**Describe the Issue**

ANY case of `gl_MeshPrimitivesEXT` isn't passing any validation. Application always crash with vector error and invalid op code. 

(In my case is `gl_MeshPrimitivesEXT[localPrimitive].gl_PrimitiveID = int(primitiveId);`)

**Valid Usage ID**

```
Vulkan Debug Error: Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x21b6bf34b10, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Invalid capability operand: 5283
Vulkan Debug Error: Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x21b6bf34b10, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Invalid capability operand: 5283
```

**Environment:**
 - OS: Windows 11
 - GPU: NVIDIA RTX 2070
 - SDK or header version if building from repo: 1.3.226
 - Options enabled (synchronization, best practices, etc.): unknown

**Additional context**

```
Debug Assertion Failed!

Program: ...dationLayers\build\install\lib\VkLayer_khronos_validation.dll
File: C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.34.31721\include\vector
Line: 50

Expression: can't dereference out of range vector iterator

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.
```

**Comment by unit-a-user** [comment]
(In my case is `gl_MeshPrimitivesEXT[localPrimitive].gl_PrimitiveID = int(primitiveId);`)

**Comment by unit-a-user** [comment]
Also, https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4516

**Comment by sjfricke** [comment]
`CapabilityMeshShadingEXT = 5283` was just added in the latest SPIR-V Headers for and the SPIR-V tooling seemed to not be ready as @mikes-lunarg pointed out in https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/d6dfc9959b650a2a24e7d6d2697f12cac7ab7e65

> Disable spv::CapabilityMeshShadingEXT in spirv_validation_generator.py
  until shader toolchain is updated
  
  So this will be fixed with the new SPIR-V headers which I assume will be pulled in very soon
