### ISSUE TITLE
 VUID-vkCmdTraceRaysKHR-pRayGenShaderBindingTable-03680 validation missing

### ISSUE THREAD

**Issue by chriku** [KhronosGroup/Vulkan-ValidationLayers#4517]
**Describe the situation in which you encountered the missing validation**
Setting the `deviceAddress` of `pRayGenShaderBindingTable` to `0` does not result in validation error

Can be simply tested by adding the line `m_rgenRegion.deviceAddress=0;` into https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR/blob/389f8e58ed1f8f5930c9fe57c3ba483f0bb71c32/ray_tracing__simple/hello_vulkan.cpp#L931 

**Valid Usage IDs requested**
VUID-vkCmdTraceRaysKHR-pRayGenShaderBindingTable-03680

**Comment by arno-lunarg** [comment]
Closed in favor of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4556
