### ISSUE TITLE
Unsupported extension VK_EXT_image_drm_format_modifier 

### ISSUE THREAD

**Issue by szihs** [KhronosGroup/Vulkan-ValidationLayers#452]
Hello, 
I have took the latest Validation Layer (1.1.90 revision)  and try to run on my sample.

However i get the below error.

VUID_Undefined(ERROR / SPEC): msgNum: 0 - Device Extension VK_EXT_image_drm_format_modifier is not supported by this layer.  Using this extension may adversely affect validation results and/or produce undefined behavior.

Could you please let me know why this error comes ? 
As per my reading, vk.xml says this extension is supported from 1.1.87 version

Kindly let me know.

Regards,
Harsh

**Comment by mark-lunarg** [comment]
Verified here.  Looks like it might be an issue in the extension_helper codegen.

**Comment by jzulauf-lunarg** [comment]
The error is in the vk.xml -- the name strings are using the name string placeholders "EXTENSION_159". I've submitted a PR to fix the xml.

If this is time critical we can merge a work-around in the codegen, or wait until the xml fix propagates to Vulkan-Headers

@szihs -- is it a critical fix?

**Comment by szihs** [comment]
Hi @jzulauf-lunarg 
Thanks for reply. It's not critical.
Please update once fix available upstream

**Comment by jzulauf-lunarg** [comment]
Close when known-good includes the xml fix.

**Comment by szihs** [comment]
Between can you share your PR so that I can locally proceed with validation

**Comment by jzulauf-lunarg** [comment]
@szihs  -- It looks like the needed registry change has been committed and picked up by Vulkan-ValidationLayers on master.
