### ISSUE TITLE
Validation is assuming we have readers

### ISSUE THREAD

**Issue by MathieuGirard** [KhronosGroup/Vulkan-ValidationLayers#4529]
When doing validation in release I had the threading validation message. Inserted a break at the moment of the trace callback shows that one thread is indeed in Vulkan while the second thread wasn't.

This shows that the validation fails to reset the use_data->thread in that first thread.

We are assymetrical when it come to the PreRead and PreWrite (one check if the count is greater than zero):

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/dd32ac341e8e775e3e95fc1380be4494b47925c4/scripts/thread_safety_generator.py#L332-L334

Suggested change:
```
                // There are readers.  This writer collided with them.
                if (prevCount.GetReadCount() > 0 && use_data->thread != tid) {
```

Reference code (symetry):
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/dd32ac341e8e775e3e95fc1380be4494b47925c4/scripts/thread_safety_generator.py#L382-L384

**Comment by ncesario-lunarg** [comment]
@MathieuGirard I'm not sure I understand what the problem is here nor the proposed solution (which doesn't seem to make sense given the condition on line 310). Any chance you could provide a way for us to reproduce this error?

**Comment by MathieuGirard** [comment]
Hi,

StartWrite will fail completly at line 333 and produce a error message if GetReadCount is zero and GetWriteCount isn't (306 is false, 310 is false, 333 is taken).

Comment at line 332 denote there are readers which would be incorrect in this case.

**Comment by MathieuGirard** [comment]
I aggree that the proposed change is incorrect, but the validation isn't correct either...

**Comment by ncesario-lunarg** [comment]
Unfortunately, there's not much we can do if we can't reproduce this behavior. Can you give more information as to why you think `use_data->thread` is not getting (re)set properly?

**Comment by MathieuGirard** [comment]
@ncesario-lunarg:
The issue is more about getting the multithread error while using a mutex protection.

The error suggests the vkFence is used simultaneously in two thread, debugger break on the tracwe itself shows that the check is incorrect the mutex is doing it's protection properly.

As for the reset thread id that was a suggestion.

Did you read the line 332 comment which sugegst there are no readers and my example scenario where it is not the case ?

If GetReaderCount return zeros and GetWriteCount return a value greater than zero line 332 will be taken: the comment conflicts with code.

If the comment is correct than the code is incorrect.

**Comment by MathieuGirard** [comment]
1. Basically from 310 if reader count is zero, write count must be non-zero.
2. If 310 condition is false (reader count is zero) and the else block is taken
3. The else block seems to assume reader count is non-zero **which is incorrect** (see 1).

This casue the validation layer to incorrectly complain about thread safety.
