### ISSUE TITLE
Validation incompatible with VK_EXT_image_2d_view_of_3d

### ISSUE THREAD

**Issue by gnl21** [KhronosGroup/Vulkan-ValidationLayers#4536]
The validation layer is not compatible with VK_EXT_image_2d_view_of_3d, which allows creating 2d depth-sliced views of 3D images under some circumstances. If these are accessed via descriptor then the validation layer asserts:
```
synchronization_validation.cpp:2065: bool CommandBufferAccessContext::ValidateDispatchDrawDescriptorSet(VkPipelineBindPoint, CMD_TYPE) const: Assertion `!img_view_state->IsDepthSliced()' failed.
```
The comment preceding the assert in the code says:
```
// NOTE: 2D ImageViews of VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT Images are not allowed in
// Descriptors, so we do not have to worry about depth slicing here.
// See: VUID 00343
assert(!img_view_state->IsDepthSliced());
```
so this needs updating to deal with the extension.

There are no validation messages encountered before the assert, and I believe that the code is valid vulkan.

The assert looks like it can be triggered by any code using the extension, but the CTS test `dEQP-VK.image.image_size.3d.readonly_writeonly_2d_view_7x1x1` shows the issue.

**Comment by gnl21** [comment]
ping @zmike

**Comment by zmike** [comment]
This is the wrong bit. `VK_IMAGE_CREATE_2D_VIEW_COMPATIBLE_BIT_EXT` is the bit from `VK_EXT_image_2d_view_of_3d`. The other one is for framebuffer attachments.

**Comment by gnl21** [comment]
Yes, so I think the comment was correct when it was written. It actually doesn't have to deal with the `2D_ARRAY_COMPATIBLE` bit but it does have to deal with `VK_IMAGE_CREATE_2D_VIEW_COMPATIBLE_BIT_EXT`, so with the extension the assert is incorrect.

**Comment by zmike** [comment]
Could be? I didn't write the validation for this, so I can only speak to the specification.

**Comment by ncesario-lunarg** [comment]
It looks like `IsDepthSliced` was intentionally updated with `VK_IMAGE_CREATE_2D_VIEW_COMPATIBLE_BIT_EXT` in https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/7fad0dbc3b, but the extension description does seem to directly contradict that comment. Does that sound correct @jeremyg-lunarg?

**Comment by jeremyg-lunarg** [comment]
> It looks like `IsDepthSliced` was intentionally updated with `VK_IMAGE_CREATE_2D_VIEW_COMPATIBLE_BIT_EXT` in [7fad0dbc3b](https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/7fad0dbc3b), but the extension description does seem to directly contradict that comment. Does that sound correct @jeremyg-lunarg?

We (@Tony-LunarG and myself) did this to fix a crash in core validation with CTS. https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4371 

Sync validation does get run through CTS periodically but it is possible a different problem is preventing us from hitting this assert.  It is possible that the code below the assert will need changes to handle VK_IMAGE_CREATE_2D_VIEW_COMPATIBLE_BIT_EXT as well.
