### ISSUE TITLE
TID value on Linux is not optimal

### ISSUE THREAD

**Issue by PixelyIon** [KhronosGroup/Vulkan-ValidationLayers#4552]
While attempting to debug an issue with an Android application and running into `UNASSIGNED-Threading-MultipleThreads`, we realized that the value returned by `loader_platform_get_thread_id()` on Linux is a pointer as returned by `pthread_self()` which isn't particularly useful as debuggers don't use this value as the TID and you'd need to evaluate `pthread_self()` on every single thread to determine the faulty threads.

The real TID should be obtained by `gettid` syscall which should likely be implemented in a similar manner as [Bionic's `gettid` wrapper](https://android.googlesource.com/platform/bionic/+/a4edf7a57cf818d19546c86b74146335468ea53f/libc/bionic/gettid.cpp#33) to avoid constant syscall overhead here by storing it in TLS.

**Comment by PixelyIon** [comment]
It seems like libcxx has a [pretty extensive implementation](https://github.com/llvm/llvm-project/blob/057fb8153ad61533d00939b77ea1c22edd2716c7/llvm/lib/Support/Unix/Threading.inc#L111-L132) of [`std::this_thread::get_id()`](https://en.cppreference.com/w/cpp/thread/get_id), it doesn't cache the TID but that could be added and it should be fairly easy with a `static thread_local` variable.

**Comment by jeremyg-lunarg** [comment]
@PixelyIon, please give the attached PR a try. Given that gettid() is already cached on Android I'm not sure if it is worthwhile to cache it again at our level. It should be a very fast system call and it is most likely in the noise compared to the rest of the work done in validation.

**Comment by PixelyIon** [comment]
Thanks for the quick resolution, I haven't tested the PR as I don't have a setup to build the layer and use prebuilt releases for Android but the code looks sound and should fix the issue.
