### ISSUE TITLE
alpha_to_coverage check failing when shader output is an array

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/Vulkan-ValidationLayers#4553]
**Describe the Issue**
I think the validation check for alpha_to_coverage being enabled and the fragment shader output including a alpha output is incorrect, if the fragment shader output is defined as an array. I have a vec4[2] as my array size, and I'm erroneously getting this validation error.
I think the issue is that 
`module_state.GetComponentsConsumedByType(output_zero->type_id, false) == 4;`
Should have it's 2nd argument as true, to strip the array, maybe?

**Valid Usage ID**
ERROR : VALIDATION - Message Id Number: 621927094 | Message Id Name: UNASSIGNED-CoreValidation-Shader-NoAlphaAtLocation0WithAlphaToCoverage
        Validation Error: [ UNASSIGNED-CoreValidation-Shader-NoAlphaAtLocation0WithAlphaToCoverage ] Object 0: handle = 0x4f67330000001267, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x2511dab6 | fragment shader doesn't declare alpha output at location 0 even though alpha to coverage is enabled.

**Environment:**
 - OS: Windows 10
 - GPU: RTX 5000
 - SDK or header version if building from repo: 1.3.224.0
 - Options enabled (synchronization, best practices, etc.): validation

**Additional context**

**Comment by spencer-lunarg** [comment]
sorry, I realize this was already handled, https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6140 fixes this

**Comment by spencer-lunarg** [comment]
happy to reopen if find still an issue

**Comment by mbechard** [comment]
i'll check, thanks!
