### ISSUE TITLE
Check that image usage bits are supported by format (or potential image view format)

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-ValidationLayers#4557]
In the documentation for `VkImageCreateInfo` there is a "note" section that details when bits of `usage` are valid. This is not a VUID, but the word "valid" is used, which gives a strong indication that this has the same kind of force as an actual VUID. So the validity of `usage` should probably be checked against the format too? This is not currently done as far as I can tell.

Note also https://github.com/KhronosGroup/Vulkan-Docs/issues/1949 where I requested a VUID for this.

**Comment by spencer-lunarg** [comment]
@Rua So if I am reading https://github.com/KhronosGroup/Vulkan-Docs/issues/1949#issuecomment-1268485447 correctly there is nothing to do here, correct?

**Comment by Rua** [comment]
I think so.
