### ISSUE TITLE
vkGetSemaphoreCounterValue return 0xffffffffffffffff

### ISSUE THREAD

**Issue by johnson3d** [KhronosGroup/Vulkan-ValidationLayers#4566]
**Describe the Issue**
Validation didn't output anything,But vkGetSemaphoreCounterValue will get UINT64_MAX suddenly
Issue description.The code like this:
        UINT64 VKFence::GetCompletedValue()
	{
		UINT64 count = 0;
		auto device = mDeviceRef.GetPtr();
		if (device == nullptr)
		{
			ASSERT(false);
			return 0;
		}
		auto hr = vkGetSemaphoreCounterValue(device->mDevice, mSemaphore, &count);
		if (count == UINT64_MAX)
		{
			ASSERT(false);
		}
		ASSERT(hr == VK_SUCCESS);
		return count;
	}

**Valid Usage ID**
If applicable, please include the validation messages encountered leading up to the issue

**Environment:**
 - OS: Window 10
 - GPU:GTX2080 Super
 - SDK or header version if building from repo:vual 1.3.216.0
 - Options enabled (synchronization, best practices, etc.):

VkValidationFeatureEnableEXT enableFeatures[] = { VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXT,
			VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_RESERVE_BINDING_SLOT_EXT ,
			//VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT ,
			VK_VALIDATION_FEATURE_ENABLE_DEBUG_PRINTF_EXT ,
			VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT };
validation output nothing
**Additional context**
https://github.com/johnson3d/titan3d/tree/ImGuiEditor_johnson
1open engineall.sln
2compile core.window
3compile MainEditor and run 
4open Contentbrowser utest/box_wite & utest/ddd,  do them sometimes, ASSERT(false) will be triggered

**Comment by johnson3d** [comment]
I find some information about return UINT64_MAX, Dx12 will removal device and get this error, if compute sth long time in queue.
TDR(Timeout detection and recovery) is triggered, And the hardware crashed/hung, 
I guess this problem did it for me. Can i get more info about queue execution state by validation?

**Comment by johnson3d** [comment]
vkGetSemaphoreCounterValue still return VK_SUCCESS, Validation settings is default always,And no messages was outputted,This problem is triggeded in that complex case, And we must do those actions many times, A simple demo is difficult to reproduce!_!

**Comment by jeremyg-lunarg** [comment]
I tried downloading and building your application but if failed due to errors because PhysX and possible some other dependencies weren't installed. I couldn't find any english language instructions on how to build. Without an efficient way to reproduce  your problem I'm not sure what else can be done for this Issue.

**Comment by johnson3d** [comment]
> I tried downloading and building your application but if failed due to errors because PhysX and possible some other dependencies weren't installed. I couldn't find any english language instructions on how to build. Without an efficient way to reproduce your problem I'm not sure what else can be done for this Issue.

I pushed some new files that include the readme.txt, So sorry, My english is very bad !_!

**Comment by jeremyg-lunarg** [comment]
We aren't going to be able to investigate this issue unless you can provide a simpler way to reproduce the problem.  It is unclear if this a bug in the application, driver or validation layers.

**Comment by cliche9** [comment]
@johnson3d Is there any solutions for this problem? I encountered this situation when submitting recently, and no more useful information from the validation layer than something like this:

[VUID-VkSubmitInfo2-semaphore-03883]:
		 Validation Error: [ VUID-VkSubmitInfo2-semaphore-03883 ] Object 0: handle = 0x4d0b8c0000009138, name = Global timeline rt, type = VK_OBJECT_TYPE_SEMAPHORE; Object 1: handle = 0x261695d4720, name = GraphicsQueue, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0x73d01e2c | vkQueueSubmit2(): pSubmits[0].pSignalSemaphoreInfos[1].semaphore value (7) exceeds limit regarding pending wait semaphore VkSemaphore 0x4d0b8c0000009138[Global timeline rt] value (**18446744073709551615**). The Vulkan spec states: If the semaphore member of any element of pSignalSemaphoreInfos is a timeline semaphore, the value member of that element must have a value which does not differ from the current value of the semaphore or the value of any outstanding semaphore wait or signal operation on that semaphore by more than maxTimelineSemaphoreValueDifference (https://vulkan.lunarg.com/doc/view/1.3.290.0/windows/1.3-extensions/vkspec.html#VUID-VkSubmitInfo2-semaphore-03883)
