### ISSUE TITLE
physical devices from vkEnumeratePhysicalDeviceGroups() are not tracked properly

### ISSUE THREAD

**Issue by ziga-lunarg** [KhronosGroup/Vulkan-ValidationLayers#4567]
Calling `vkEnumeratePhysicalDeviceGroups()` and using the physical devices found will give validation errors saying the physical device is not valid. Inserting a call to `vkEnumeratePhysicalDevices()` before the function reporting the errors will get rid of them. 

One example of this is the test dEQP-VK.compute.device_group.dispatch_base

**Comment by ncesario-lunarg** [comment]
Is this the same as or (related to) #4526?
