### ISSUE TITLE
possible spurious layout errors with compute presentation

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-ValidationLayers#4572]
**Describe the Issue**
I'm experimenting with doing QueuePresentKHR from a compute (non-graphics) queue. As near as I can tell, I'm doing everything I should be with queue/layout transitions, but no matter what I try, I get validation errors about the layout being wrong at present time. I'm not 100% sure that this is a VVL bug, but it sure seems like one. Specifically, it seems like queue submissions are using the layout from the wrong queue.

**Valid Usage ID**
`VUID-VkPresentInfoKHR-pImageIndices-01296`

**Environment:**
 - OS:  linux
 - GPU: AMD RX5700
 - SDK or header version if building from repo: e5afd16e31388ade3585a44af19388f4a7c18d10
 - Options enabled (synchronization, best practices, etc.): default

**Additional context**
Should be easily reproducible on a setup that has a separate compute queue with:
* build mesa+zink from https://gitlab.freedesktop.org/zmike/mesa/-/commits/vvl-bug
* run glxgears like `ZINK_DEBUG=validation MESA_LOADER_DRIVER_OVERRIDE=zink glxgears`

**Comment by jeremyg-lunarg** [comment]
This is probably related to https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2441. Layouts are validated and recorded at submit time, not execution time like they should be. If you're using multiple queues and semaphores, especially timeline semaphores, it is very easy to confuse the image layout tracking code.    Fixing this requires https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4328 + additional work on top of it to move all the validate and record work to run a the correct time.

**Comment by jeremyg-lunarg** [comment]
Closing this as a duplicate of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4422. It has a gfxrecontruct trace attached that shows the problem and I wrote a much clearer explanation of what is going wrong over there.

**Comment by artem-lunarg** [comment]
Fixed either by https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/10316 or by recent image layout fixes.
