### ISSUE TITLE
Chaining VkPhysicalDeviceConservativeRasterizationPropertiesEXT when using GPDP2 triggers incorrect validation layers

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-ValidationLayers#458]
If an app:

1) Fills out VkPhysicalDeviceConservativeRasterizationPropertiesEXT struct's pNext and sType fields accordingly but leaves the rest intact (= glitched)
2) Chains the struct to VkPhysicalDeviceProperties2KHR
3) Passes struct described in 2) to vkGetPhysicalDeviceProperties2KHR() 

a number of validation error triggers, saying untouched struct 1)'s fields are invalid. That's totally expected though, GPDP2 is supposed to fill these fields with actual contents. Definitely not an error.

**Comment by Tony-LunarG** [comment]
Fixed with PR #463
