### ISSUE TITLE
Cmake: Possible missing location for SPIRV-Headers

### ISSUE THREAD

**Issue by rendoir** [KhronosGroup/Vulkan-ValidationLayers#4581]
**Describe the Issue**
When building Vulkan-ValidationLayers with SPIRV-Headers (and SPIRV-Tools) in-tree, `SPIRV_HEADERS_INCLUDE_DIR` might end up being empty which will prevent the validation layers from compiling: 
```bash
<PathTo>\Vulkan-ValidationLayers\layers\generated\vk_format_utils.cpp(33,10): fatal error C1083: Cannot open include file: 'spirv/unified1/spirv.hpp': No such file or directory
```

**Environment:**
- SPIRV-Headers: commit 87d5b782bec60822aa878941e6b13c0a9a954c9b
- SPIRV-Tools: commit 11d0d162279b7cd19f82dac3934149dd97a3a42c
- Neither are installed.

**Further Investigation**
I started looking into Vulkan-ValidationLayers' CMakeLists.txt and I noticed that:
- `if(SPIRV-Headers_FOUND)` and `elseif(SPIRV_HEADERS_INSTALL_DIR)` are false for me: no surprises here as I didn't install SPIRV-Headers in either way.
- `elseif(SPIRV_HEADERS_INCLUDE_DIR)` is also false: this is kind of surprising since I build both SPIRV-Headers and SPIRV-Tools in-tree before the validation layers.

**Possible Fix**
I'm still not completely sure this is a problem in Vulkan-ValidationLayers itself or for one of the SPIRV projects.  
Regardless I found something that works:
```cmake
# Add this at the end of those if/elseif statements
elseif(SPIRV-Headers_SOURCE_DIR)
    if (NOT EXISTS "${SPIRV-Headers_SOURCE_DIR}/include/spirv/unified1/spirv.h")
	message(FATAL_ERROR "Cannot find SPIRV-Headers from SPIRV-Headers_SOURCE_DIR: ${SPIRV-Headers_SOURCE_DIR}")
    endif()
    set(SPIRV_HEADERS_INCLUDE_DIR "${SPIRV-Headers_SOURCE_DIR}/include")
```

**Comment by sjfricke** [comment]
> I'm still not completely sure this is a problem in Vulkan-ValidationLayers itself or for one of the SPIRV projects.

This is the Validation layers issue as I recent in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4540 needed to add `spirv.hpp` to `vk_format_utils.cpp`.

I guess not 100% sure what is going on with your cmake build, but at least for me on Linux in `external/helper.cmake` I have
`set(SPIRV_HEADERS_INSTALL_DIR "/path/to/Vulkan-ValidationLayers/external/SPIRV-Headers/build/install" CACHE STRING "" FORCE)`

@rendoir what OS and CMake version are you using?

**Comment by rendoir** [comment]
I'm on Windows 10, CMake 3.23.
I'll explore what value I get from that line this evening. I can also test on Linux.

**Comment by rendoir** [comment]
@sjfricke I'm not sure what you mean as there's no `external/helper.cmake` in the Vulkan-ValidationLayers repo (or SPIRV-Headers/Tools for that matter).
The issue also happens to me on Linux, so it's definitely some incompatibility between the way I build and the validation layers' cmake.
Here's (an outdated version of) my CMakeLists.txt: https://github.com/rendoir/vulkan/blob/master/CMakeLists.txt
I'm in the process of refactoring the code and updating submodules.
In my root directory I do:
`cmake -S . -B .build` and then `cmake --build .build`.
I hope this helps!

**Comment by sjfricke** [comment]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/BUILD.md#building

when calling `update_deps.py` it will generate the `helper.cmake` which can be used then can be used in the `cmake` call with `-C path/to/helper.cmake`

My personal fresh build sequence is the same one found at the link

**Comment by ncesario-lunarg** [comment]
Ideally we would link the `SPIRV-Headers::SPIRV-Headers` target to `VKLayer_utils` (which appears to be the target that is missing the appropriate include directory as @sjfricke pointed out), but I think I tried that when looking at #4540 and it didn't work; I will revisit that when (if) we get around to refactoring the cmake in the validation layer repo. It might be worth trying that again though. i.e., linking to `SPIRV-Headers::SPIRV-Headers` at https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/db7cc3d338e3a5a8c274dfd59e89c48e26218c75/CMakeLists.txt#L346

Seems like that _should_ work given your current setup. If it does, then I think that would be a good change to make to VVL. If it doesn't, it would be interesting to know why it doesn't.

**Comment by rendoir** [comment]
@sjfricke That seems to work, sorry. I should've read those docs.
@ncesario-lunarg I tried `target_link_libraries(VkLayer_utils PUBLIC SPIRV-Headers)` after L346 and it works but based on the above information it might not be needed.
Also, if someone stumbles upon this, there's a third solution that doesn't require pulling the dependencies or modifying the vulkan validation layers' cmake. In my CMake I added this:
```cmake
set(SPIRV_HEADERS_INCLUDE_DIR "${SPIRV-Headers_SOURCE_DIR}/include")
add_subdirectory(${EXTERNAL_PATH}/Vulkan-ValidationLayers)
```
From my side, I think we can close the issue but feel free to discuss. Thank you both!

**Comment by sjfricke** [comment]
I will let @ncesario-lunarg finalize this, but glad the `helper.cmake` file works, but as @ncesario-lunarg said, there is still a refactoring of the CMake that is desired, but for now, doesn't seem to be a need for an urgent hotfix

**Comment by ncesario-lunarg** [comment]
Glad you're unblocked for now, and thank you @sjfricke for helping to solve this :)

I think from a cmake perspective the "correct" thing would be to use the target in VVL, then you shouldn't have to worry about setting any additional variables (nor having to dig through VVL's cmake to know what those variables are). However, the VVL changes will be done when/if we get around to refactoring the cmake.
