### ISSUE TITLE
GalaxyS22 crashes and failures

### ISSUE THREAD

**Issue by lunarpapillo** [KhronosGroup/Vulkan-ValidationLayers#4587]
We're preparing to add **Samsung Galaxy S22** with the **Exynos** GPU to CI.  Running with the latest update:
```
r0sxxx-user 12 SP1A.210812.016 S901BXXS2AVHD release-keys
```
provoked 4 crashes and 9 failures.  The full log file from the blacklist exercise is included here, as the messages within can help with debugging:

[blacklist.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/9629913/blacklist.txt)

#### 4 crashing tests
- `VkLayerTest.TestShaderZeroInitializeWorkgroupMemory`
- `VkLayerTest.AndroidHardwareBufferMemoryAllocation`
- `VkPositiveLayerTest.ValidateGetAccelerationStructureBuildSizes`
- `VkPositiveLayerTest.AndroidHardwareBufferDepthStencil`

#### 9 failing tests
- `VkLayerTest.RayTracingPipelineShaderGroupsKHR`
- `VkLayerTest.RayTracingLibraryFlags`
- `VkLayerTest.InvalidRayTracingPipelineFlags`
- `VkLayerTest.BindImageInvalidMemoryType`
- `VkLayerTest.BindInvalidMemory`
- `VkLayerTest.BindInvalidMemory2Disjoint`
- `VkLayerTest.DeviceCoherentMemoryDisabledAMD`
- `VkLayerTest.InvalidMixingProtectedResources`
- `VkPositiveLayerTest.RayTracingPipelineShaderGroupsKHR`

In addition, this device also seems to be affected by #4490 .

**Comment by lunarpapillo** [comment]
I guess we should close this one?  Or is there still interesting information here?

**Comment by spencer-lunarg** [comment]
This seems to be a super set (the ones gone looking make sense why they are gone) so I think safe to close, it is linked to the new issue in case someone needs to look
