### ISSUE TITLE
Android: CheckAndroidVersion spawns subprocesses when it doesn't have to

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/Vulkan-ValidationLayers#4605]
**Describe the Issue**
On Android, GetEnvironment helper function forks extra processes/threads, which confuses developers.
It uses popen to fork a thread to run "getprop".  But GetEnvironment could have used the getenv C library call instead.

**Valid Usage ID**
n/a

**Environment:**
 - OS: Android
 - GPU: n/a
 - SDK or header version if building from repo: 
 - Options enabled (synchronization, best practices, etc.):

**Additional context**

A developer was debugging an Android Vulkan application and was confused when they threads being spawned.

The CheckAndroidVersion call at https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/e81f04ef6b6ad186bd771aca2d761a92d2277069/layers/vk_layer_config.cpp#L426 is called during dlopen.
That in turn calls GetEnvironment:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/e81f04ef6b6ad186bd771aca2d761a92d2277069/layers/vk_layer_config.cpp#L87 

That spawns a subprocess to run 'getprop'. It could have used getenv instead.

**Comment by ncesario-lunarg** [comment]
@dneto0 are you saying we could use the `getenv` C API to query Android properties? I did not think this was possible. @jeremyg-lunarg pointed to https://android.googlesource.com/platform/system/core.git/+/refs/heads/master/toolbox/getprop.cpp, which looks like we could use this to query Android properties rather than spawning a process to launch `getprop`, but is obviously a lot more involved than just using `getenv` (if that "just worked," that would be great :)).

**Comment by sjfricke** [comment]
So I [added this](https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/98acb880967dae494e05c4502b59e6618d929ec7#diff-1346ff8e79351fec4cce77afc861141f80c54fa0a56b5c1d1673b95db0a77c06R88) awhile ago. This was one of those things were looking around the ecosystem this was the "go to way" to check

whatever we do, someone should make sure it **builds** with Android 24/25 ndk libs as that is who this check is even for

**Comment by sjfricke** [comment]
So looked into this

We are not able to use `getenv` as that is an AOSP library and an NDK built library can't properly use it.

I looked into [sys/system_properties.h](https://cs.android.com/android/platform/superproject/+/master:bionic/libc/include/sys/system_properties.h) in the NDK and seems

```c++
char version[8];
found = __system_property_get("ro.build.version.sdk", version);
```

would work, **but** seems `__system_property_get` is now deprecated in Android O for `__system_property_read_callback` but that is not available for [Android 24 system_properties.h](https://cs.android.com/android/platform/superproject/+/android-7.0.0_r1:bionic/libc/include/sys/system_properties.h)

I have a PR that should fix this, but more of a "buying use time" as not sure when `__system_property_get` will disappear, but we do need a solution that will run on an Android 24 device to check the Android version
