### ISSUE TITLE
Warnings from macOS build "built for newer macOS version (11.7) than being linked (10.12)"

### ISSUE THREAD

**Issue by juan-lunarg** [KhronosGroup/Vulkan-ValidationLayers#4614]
MacOs builds on CI are seeing multiple linker warnings. Here is an example:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/actions/runs/3160572537/jobs/5145179242
```
ld: warning: object file (/Users/runner/work/Vulkan-ValidationLayers/Vulkan-ValidationLayers/external/glslang/build/install/lib/libSPVRemapper.a(SPVRemapper.cpp.o)) was built for newer macOS version (11.7) than being linked (10.12)
ld: warning: object file (/Users/runner/work/Vulkan-ValidationLayers/Vulkan-ValidationLayers/external/glslang/build/install/lib/libSPIRV.a(GlslangToSpv.cpp.o)) was built for newer macOS version (11.7) than being linked (10.12)
ld: warning: object file (/Users/runner/work/Vulkan-ValidationLayers/Vulkan-ValidationLayers/external/glslang/build/install/lib/libMachineIndependent.a(ShaderLang.cpp.o)) was built for newer macOS version (11.7) than being linked (10.12)
ld: warning: object file (/Users/runner/work/Vulkan-ValidationLayers/Vulkan-ValidationLayers/external/googletest/build/install/lib/libgtest.a(gtest-all.cc.o)) was built for newer macOS version (11.7) than being linked (10.12)
ld: warning: object file (/Users/runner/work/Vulkan-ValidationLayers/Vulkan-ValidationLayers/external/SPIRV-Tools/build/install/lib/libSPIRV-Tools.a(binary.cpp.o)) was built for newer macOS version (11.7) than being linked (10.12)
ld: warning: object file (/Users/runner/work/Vulkan-ValidationLayers/Vulkan-ValidationLayers/external/SPIRV-Tools/build/install/lib/libSPIRV-Tools.a(table.cpp.o)) was built for newer macOS version (11.7) than being linked (10.12)
```

**Environment:**
 - OS:  MacOS

This is occurring due to `CMAKE_OSX_DEPLOYMENT_TARGET` not being properly propagated. Unsure of severity of warning.

**Comment by juan-lunarg** [comment]
Also worth pointing out that if this is fixed to make linker warnings as errors to prevent this issue in the future.

**Comment by ncesario-lunarg** [comment]
FYI @richard-lunarg.

**Comment by juan-lunarg** [comment]
Also worth pointing out that the debug builds are getting this warning:

```
ld: warning: direct access in function 'VkImageObj::InitNoLayout(VkImageCreateInfo const&, unsigned int, bool)' from file 'CMakeFiles/vk_layer_validation_tests.dir/vkrenderframework.cpp.o' to global weak symbol 'std::__1::hex(std::__1::ios_base&)' from file '/Users/runner/work/Vulkan-ValidationLayers/Vulkan-ValidationLayers/external/glslang/build/install/lib/libSPIRV.a(GlslangToSpv.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```

IE the visibility setting isn't [consistent](https://stackoverflow.com/questions/8685045/xcode-with-boost-linkerid-warning-about-visibility-settings/11879361#11879361) across the project. And seems to be an Apple specific issue.

**Comment by juan-lunarg** [comment]
Solving this issue properly would also address this: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3866

**Comment by richard-lunarg** [comment]
An interesting situation. Generally speaking most developers do not target only the current version of macOS. Setting the CMAKE_OSX_DEPLOYMENT_TARGET environment variable to an older OS is as far as I know standard practice so the end product an run on an older OS. For CI purposes it makes no difference, but do we really want developers to have to know to change this themselves if they build from source? Maybe the answer to that is yes though. If so, it's a trivial change to CMakeLists.txt

**Comment by juan-lunarg** [comment]
[MACOSX_DEPLOYMENT_TARGET](https://cmake.org/cmake/help/latest/envvar/MACOSX_DEPLOYMENT_TARGET.html) is what developers should set.

Currently `CMAKE_OSX_DEPLOYMENT_TARGET` as a regular/cache variable doesn't propagate to project fetch with update_deps.py

And I believe setting `CMAKE_OSX_DEPLOYMENT_TARGET` in the code directly like we do, takes precedence over the environment variable. Since environment variables have less priority than cache/regular variables.
