### ISSUE TITLE
Bug in implementation of VUID-vkCmdDraw-None-02686

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-ValidationLayers#4628]
To reproduce, you can run the following ANGLE tests:

```
$ ./angle_end2end_tests --gtest_filter=MultisampledRenderToTexture*Vulkan
$ ./angle_end2end_tests --gtest_filter=FramebufferFetchES31*Vulkan
$ ./angle_deqp_gles31_tests --deqp-case=dEQP-GLES31.functional.shaders.framebuffer_fetch.*
```

After disabling the suppression of this VU (and equivalents) in [`RendererVk.cpp`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/angle/src/libANGLE/renderer/vulkan/RendererVk.cpp;l=221;drc=34977cc5ae8bb63e4c27fe30675b0ba9de722dce)

What ANGLE does in these tests is that it uses input attachments to emulate things (such as framebuffer fetch). However, for simplicity ANGLE always creates its descriptor set layouts with 8 input attachments (corresponding to maximum 8 color attachments), but at draw time only fills in as many input (== color) attachments there are.

In other words:

- `VkDescriptorSetLayoutCreateInfo` has 8x `VkDescriptorSetLayoutBinding`s, for bindings 0 through 7, all input attachments.
- `vkUpdateDescriptorSets` is called with only one `VkWriteDescriptorSet`, writing an image view to binding 0
- The render pass uses one color attachment and one input attachment at binding 0

The VU being validated says:

> Every input attachment used by the current subpass must be bound to the pipeline via a descriptor set

However, VVL fails in this code:

```
const auto descriptor = set->GetDescriptorFromBinding(binding.binding, i);
if (!descriptor) continue;

const auto image_descriptor = static_cast<const cvdescriptorset::ImageDescriptor *>(descriptor);
VkImageView image_view = image_descriptor->GetImageView();
if (subpass_input_views.count(image_view) == 0) {
    // Image view isn't used by subpass as an input attachment with this framebuffer
    result |=
        LogError(image_view, kVUID_Core_InputDescriptorInvalid,
                 "Input attachment descriptor image view is not a subpass input attachment");
} else {
    subpass_input_views.erase(image_view);
}
```

where `binding.binding` is 1. In that case `image_view` is also null. In other words, it's failing validation for input attachments that are _not_ used by the current subpass. The VU doesn't require those input attachments to be validated.

**Comment by spencer-lunarg** [comment]
There was a spec update to fix this and now moved over to`VUID-vkCmdDraw-None-07748`

https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4891 is tracking this, closing this issue, but when adding the fix will make sure it passes the test above
