### ISSUE TITLE
WriteDescriptorSet validation

### ISSUE THREAD

**Issue by shrinktofit** [KhronosGroup/Vulkan-ValidationLayers#464]
https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkWriteDescriptorSet.html

If descriptorType is VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER or VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC, the offset member of each element of pBufferInfo must be a multiple of VkPhysicalDeviceLimits::minUniformBufferOffsetAlignment

**Comment by jzulauf-lunarg** [comment]
@shrinktofit  -- The test for this VU is present, as is a unit test for it.  VUID-VkWriteDescriptorSet-descriptorType-00327 -- validated in the VK_LAYER_LUNARG_parameter_validation (which is also included in VK_LAYER_LUNARG_standard_validation)

Do you have a test case? What validation layers were enabled?

**Comment by shrinktofit** [comment]
> Do you have a test case? What validation layers were enabled?

I enabled the `VK_LAYER_LUNARG_standard_validation` layer.

**Comment by jzulauf-lunarg** [comment]
Looking at the code...  https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/parameter_validation_utils.cpp#L2642

By inspection this seems to be the needed logic.  Can you dump VkPhysicalDeviceLimits::minUniformBufferOffsetAlignment and pBufferInfo you're using that fails to trigger this error?

A simple test case would also be welcome.

**Comment by jzulauf-lunarg** [comment]
@shrinktofit  -- Is this issue still present for you?  Do you have any additional information to help reproduce the issue?

**Comment by shrinktofit** [comment]
No, thx.
