### ISSUE TITLE
Timeout in validation layers after updating past pull #4328

### ISSUE THREAD

**Issue by dj2** [KhronosGroup/Vulkan-ValidationLayers#4649]
When attempting to update our internal code to use the validation layers after 
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4328 we have started to see timeouts in our test files. Looking at the tests, we have test cases which previously took 5s and now take > 90s.

There are a number of errors of the form:

```
[ UNASSIGNED-VkSemaphore-state-timeout ] Object 0: handle = 0x111, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x222 | Timeout waiting for timeline semaphore state to update. completed_.payload=164 wait_payload=165
```

In each case I'm seeing a `completed_.payload` value of one less then the `wait_payload` value. The timeout values are disjoint though, so I see the (completed, wait) pairs of (14, 15), (29, 30), (52, 53), (85, 86), (112, 113), (157, 158), (164, 165). The test timeout kicks in and we  terminate the test process.

Looking at the various threads that are running when the process is terminated I'm seeing the following three threads that maybe of interest:

## Thread 1
```
ValidationObject::WriteLock()
vulkan_layer_chassis::SignalSemaphoreKHR()
```

## Thread 2
```
ValidationObject::ReadLock()
vulkan_layer_chassis::AllocateDescriptorSets()
```

## Thread 3
```
SEMAPHORE_STATE::NotifyAndWait()
ValidationStateTracker::PostCallRecordWaitSemaphoresKHR()
vulkan_layer_chassis::WaitSemaphoresKHR()
```

**Comment by jeremyg-lunarg** [comment]
@dj2 is there any way to share code, a gfxrecon capture or an api dump of one or more of these tests?

**Comment by dj2** [comment]
Sadly, no. I don't have permission to share. I can try to do some experiments if there are things I can try and report back on.

**Comment by jeremyg-lunarg** [comment]
I'll try to think of some experiments to try.  There's a similar error happening very sporadically in CTS, but this seems much more consistent.  Even having logging of when and which threads are making queue and semaphore related vulkan calls  would be helpful.

**Comment by dj2** [comment]
I can try to take a look when I'm back in the office on Thursday to see if I can add any extra logging into the the code.

**Comment by jeremyg-lunarg** [comment]
I think I'm close to having a fix for this (at least for the versions of it I can reproduce). I'll put up a PR for you to try later today.

**Comment by dj2** [comment]
Awesome, thanks. I did some poking around and it seems like on our side we're seeing this with timeline ops. It ends up calling the wait code over and over (but there is no queue so the function essentially does nothing).

**Comment by jeremyg-lunarg** [comment]
@dj2 Please give the linked PR a try when you have a chance. I still have more testing to do here but so far it seems to make the intermittent problems we were seeing much better.

**Comment by dj2** [comment]
I patched in the relevant bits of that CL locally (we're at the revision prior to the addition of #4328) and am still seeing the timeouts as before.

**Comment by jeremyg-lunarg** [comment]
You might also want to try  https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4665 . Or you might need both PRs. I'm in the process of merging both of them. Then we'll have to wait for more CI runs to see if the intermittent failures are gone.

**Comment by dj2** [comment]
This does not appear to be fixed for me. I sync'd to the tip-of-tree and retried and I'm getting the same timeout with the error stating 'This is most likely a validation bug'. Same sort of pattern as discussed above.

**Comment by jeremyg-lunarg** [comment]
We're pretty much stuck then unless you can get me some more information about these tests.    Even an outline like I was given in [this comment](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4402#issuecomment-1213594299) would be helpful.

**Comment by jeremyg-lunarg** [comment]
@dj2  Can you please try https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4683 when you have a chance? I think you'll start seeing new VUID-VkSubmitInfo-pSignalSemaphores-03242 errors from your test application with this PR.

**Comment by jeremyg-lunarg** [comment]
@dj2 https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4739 just merged, which should be able to detect the 'double submit of the same timeline value' problem your internal test app has (had?). If you're still having troubles running validation with this app, please repopen this or file a new issue or contact me privately. Thanks! 
 
(#4683 has a much more extensive check on incorrect signal order, but it still needs more work)
