### ISSUE TITLE
erroneous UNASSIGNED-CoreValidation-Shader-PointSizeMissing

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-ValidationLayers#4657]
**Describe the Issue**
When running `KHR-GL46.shader_image_load_store.multiple-uniforms` with zink, I get this error from a geometry shader . The shader never emits any vertices, however, so it's pointless to be throwing an error.

**Valid Usage ID**
`UNASSIGNED-CoreValidation-Shader-PointSizeMissing(ERROR / SPEC): msgNum: -211210120 - Validation Error: [ UNASSIGNED-CoreValidation-Shader-PointSizeMissing ] Object 0: handle = 0xcc25c90000000082, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0xf3693078 | Pipeline topology is set to POINT_LIST, but PointSize is not written to in the shader corresponding to VK_SHADER_STAGE_GEOMETRY_BIT.`

**Environment:**
 - OS: Linux
 - GPU: N/A
 - SDK or header version if building from repo: e5afd16e31388ade3585a44af19388f4a7c18d10

**Additional context**
I think validation for this should verify that the GS emits vertices before triggering the error.

**Comment by ziga-lunarg** [comment]
I believe the same applies for `dEQP-VK.geometry.emit.points_emit_0_end_0`

**Comment by spencer-lunarg** [comment]
being `unassigned` this was probably added from early days. Can look "why" it was added, maybe get a proper VUID added to spec, and most important add the "are we emitting vertices" check

**Comment by spencer-lunarg** [comment]
@zmike so as discussed in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5502#note_385816 it seems that for this (assuming you can't just disable `shaderTessellationAndGeometryPointSize`) this is still an invalid usage and either need

1. convincing to relax the VUID more
2. fix the CTS test to write something to pointsize
3. having Zink inject the `PointSize` write

**Comment by spencer-lunarg** [comment]
closing as stated above that the CTS is now invalid with regards to the new VUIDs
