### ISSUE TITLE
Validation error messages should be more specific when reporting invalid image layouts

### ISSUE THREAD

**Issue by shannon-lunarg** [KhronosGroup/Vulkan-ValidationLayers#466]
For clarity, validation error messages should be more specific when reporting invalid image layouts. It is suggested the layer code track in which way these subresource image layouts are first used (e.g.- image memory barriers, render pass attachment descriptions and references, image creation and clear, copy, and resolve commands) so this information can be used to create more helpful error messages.

> `[ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object: 0x600003504f30
(Type = 6) | Attempt to `**`execute a clear color image command`**` using image 0x26 (sub-resource: aspectMask 0x1 array layer 0, mip level 0) which is expected to be in layout VK_IMAGE_LAYOUT_GENERAL--instead, image 0x26's current layout is VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL."`

**Comment by jzulauf-lunarg** [comment]
Notes: This will require plumbing information regarding the image_layout usages down into `SetLayout` and storing that additional info along with `IMAGE_CMD_BUF_LAYOUT_NODE::initialLayout`

**Comment by shannon-lunarg** [comment]
Further comments from LunarXchange:
> "The new message is definitely an improvement. I'm not sure that tracking first use will help. In the case I had, the mismatch was between the layout specified in the descriptor and the layout of the image. The image was set up first and the descriptor second. Will first use tracking really help here?"
> Mark Callow - Indie Group

> "If I might add, this gets more complicated to track down as the descriptor operates on an ImageView vs an Image; some engines (ie UE4) generate a lot of ImageViews for a single Image (eg A cubemap with 10 mips will have 6*10=60 views) which makes tracking this down especially painful. Can the message maybe also describe which is the current ImageView this came from?"
> Rolando Caloca Olivares - Indie Group

**Comment by krOoze** [comment]
It would also be useful if the layers could detect ambiguous\overlapping layout transitions, and report it as such. I think it would be clearer than "expected layout is X, but current layout is Y". I mean, the "current layout" is bit of a lie if the sync is wrong in the first place.

**Comment by DethRaid** [comment]
I've run into the same validation message that was reported in closed issue #1102 . I'd really like to know _which_ part of my command buffer expected my image to be in that layout, not just that the command buffer as a whole somewhere expected the image to be in a layout at some point

**Comment by mark-lunarg** [comment]
Tracking in the error message improvements issue, #679.
