### ISSUE TITLE
LAYER_CONFIGURATION.md is entirely useless and provides no info

### ISSUE THREAD

**Issue by Joshua-Ashton** [KhronosGroup/Vulkan-ValidationLayers#4667]
This has been bugging me for a while.
This file has *a lot* of text that tells me *absolutely nothing*.

I want to find the env var/property to filter some warnings/errors, its not here.

The actual layer configuration information is at https://vulkan.lunarg.com/doc/view/latest/linux/khronos_validation_layer.html or in the `VkLayer_khronos_validation.json` which is not referenced by this file or the README.md at all.

So what is this file for? It provides no information whatsoever to me as a user of the validation layers aside from wasting my time thinking that what I want is here, and not pointing me to the right places...

It would be better to just have a link to https://vulkan.lunarg.com/doc/view/latest/linux/khronos_validation_layer.html in the README.md

**Comment by chloekek** [comment]
I disagree that this document is completely useless. I frequently visit the document to copy the name of the `VK_INSTANCE_LAYERS` environment variable and the name of the `VK_LAYER_KHRONOS_validation` layer to my clipboard. The documents you linked do not tell my the name of the environment variables.
