### ISSUE TITLE
Core validation layer crashes in buffer_validation::PostCallRecordCreateImageView

### ISSUE THREAD

**Issue by Cry-Mory** [KhronosGroup/Vulkan-ValidationLayers#467]
What's the problem?
=========================

We have a crash in core validation layer on Adreno 540 GPU in buffer_validation::PostCallRecordCreateImageView(...). The problem is GetImageState function call is returning null pointer which causes a crashes in the validation layer, when it de-references the pointer in next line:

image_state->createInfo.mipLevels

What's the scenario?
================================

We call vkCreateSwapchainKHR two times in row. The second call to vkCreateSwapchainKHR uses the first swapchain as the old swapchain.

The first call to vkCreateSwapchainKHR in our case creates a swapchain with the following vkImage handles:

0x0000007f097ed220
0x0000007f097ecea0
0x0000007f097ecb20

After calling vkCreateSwapchainKHR with the same information, driver decides to return the same vkImage handles:

0x0000007f097ecb20
0x0000007f097ecea0
0x0000007f097ed220

After creating the second swapchain, we acquire swapchain images for the second swap chain VkImage handles and try to delete the old swapchain. As Vulkan standard documentation mentions, at this point the application is allowed to destroy the swapchain:

> Upon calling vkCreateSwapchainKHR with an oldSwapchain that is not VK_NULL_HANDLE, any images from oldSwapchain that are not acquired by the application may be freed by the implementation, which may occur even if creation of the new swapchain fails. The application can destroy oldSwapchain to free all memory associated with oldSwapchain.

Call to vkDestroySwapchainKHR causes a call to core_validation::DestroySwapchainKHR(...) function in validation layer and internally this function calls PreCallRecordDestroySwapchainKHR which erases the VkImage handles from dev_data->imageLayoutMap map. Note that the erased VkImage handles are the same as the ones the new swapchain has.

Later, when we want to create VkImageView for our newly created swapchain's VkImage handles, the validation layer crashes. Since the new swap chain image handles does not exist in dev_data->imageMap.

Briefly: 
================================

VkCreateSwapChainKHR(1)  -> dev_data->imageMap = {}
vkAcquireNextImageKHR(1) -> dev_data->imageMap = { 0x0000007f097ecb20, 0x0000007f097ecea0, 0x0000007f097ed220}
VkCreateSwapChainKHR(2)  -> dev_data->imageMap = { 0x0000007f097ecb20, 0x0000007f097ecea0, 0x0000007f097ed220}
vkAcquireNextImageKHR(2) -> dev_data->imageMap = { 0x0000007f097ecb20, 0x0000007f097ecea0, 0x0000007f097ed220}
vkDestroySwapChainKHR(1) -> dev_data->imageMap = {}
vkCreateImageView(2)     -> crash!

**Comment by jzulauf-lunarg** [comment]
@Cry-Mory -- This looks like an example of the reason unique_layers was created.

Does this crash exist with VK_LAYER_GOOGLE_unique_objects after VK_LAYER_LUNARG_core_validation? Is there a reason VK_LAYER_LUNARG_standard_validation isn't being used for validation?

**Comment by tobine** [comment]
Since @Cry-Mory refers to Adreno I suspect that this is Android and VK_LAYER_LUNARG_standard_validation isn't available.

@Cry-Mory note that full recommended layer stack for validation on Android is given on [this](https://developer.android.com/ndk/guides/graphics/validation-layer) page as:

> // Make sure the desired validation layers are available
> // NOTE:  These are not listed in an arbitrary order.  Threading must be
> //        first, and unique_objects must be last.  This is the order they
> //        will be inserted by the loader.
> const char *instance_layers[] = {
>     "VK_LAYER_GOOGLE_threading",
>     "VK_LAYER_LUNARG_parameter_validation",
>     "VK_LAYER_LUNARG_object_tracker",
>     "VK_LAYER_LUNARG_core_validation",
>     "VK_LAYER_GOOGLE_unique_objects"
> };

There is an effort underway to unify the layers so that a single common layer name can be used between desktop and Android but for now these layers must be explicitly enabled on Android. Please try that and verify that it fixes the crash you're seeing.

**Comment by Cry-Mory** [comment]
@jzulauf-lunarg @tobine Thanks for your replies. As @tobine  mentioned the VK_LAYER_LUNARG_standard_validation does not exist on the android. 

@tobine thanks. I just tried the order you mentioned and it worked fine.

**Comment by jesusdz** [comment]
I had a similar issue when recreating the swapchain upon a resize flag. The crash was at the same point within the validation layers, also when calling vlCreateImageView, and also the second time I recreate the swapchain,  as explained in this thread. The only difference is that it only happened whenever the synchronization validation layer was enabled. My solution was not recreating the swapchain upon that resize flag setting (maybe the OS had not processed the window resize yet?), but instead recreating the swapchain whenever vkAcquireNextImage/vkQueuePresent returned codes requiring so.

**Comment by mark-lunarg** [comment]
@jzulauf-lunarg, @jeremyg-lunarg, FYI JIC.

**Comment by jzulauf-lunarg** [comment]
@mark-lunarg / @ncesario-lunarg -- looks like a bookkeeping error in DestroySwapchain.  It's assuming that the image handles are unique w.r.t. the swap chain, and they aren't.
