### ISSUE TITLE
Validation error of VUID-vkCmdPushConstants-offset-01796

### ISSUE THREAD

**Issue by maksym-pasichnyk** [KhronosGroup/Vulkan-ValidationLayers#4670]
I have two push_constant in fragment and vertex shader.

```
// fragment.glsl
layout(push_constant) uniform FragmentGlobals {
    vec4 GlobalLight;
};
```

```
// vertex.glsl
layout(push_constant) uniform VertexGlobals {
	mat4 ViewProjectionMatrix;
};
```

After pushing constants I get a validation error

```
cmd.pushConstants(cubePipelineLayout, vk::ShaderStageFlagBits::eVertex, 0, sizeof(VertexGlobals), &vertexGlobals);
cmd.pushConstants(cubePipelineLayout, vk::ShaderStageFlagBits::eFragment, 0, sizeof(FragmentGlobals), &fragmentGlobals);
```
> Validation Error: [ VUID-vkCmdPushConstants-offset-01796 ] Object 0: handle = 0x152f45b78, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x6a367c89 | vkCmdPushConstants(): stageFlags (VK_SHADER_STAGE_FRAGMENT_BIT, offset (0), and size (16),  must contain all stages in overlapping VkPushConstantRange stageFlags (VK_SHADER_STAGE_VERTEX_BIT)

If I push vertex data first and then push fragment data with vk::ShaderStageFlagBits::eVertex enabled, ViewProjectionMatrix will be partially overwritten.
If I push fragment data first with vk::ShaderStageFlagBits::eVertex enabled and then push vertex data, everything is fine.

**Comment by spencer-lunarg** [comment]
So the push constants are shared among the pipeline, I think you want to do something like

```glsl
layout(push_constant) uniform VertexGlobals {
	layout(offset = 16) mat4 ViewProjectionMatrix; // offset vec4 GlobalLight
};
```

These is a nice guide explaining Push Constants https://github.com/KhronosGroup/Vulkan-Guide/blob/master/chapters/push_constants.adoc , but sorry I am not able to see what is wrong with the validation error here

**Comment by maksym-pasichnyk** [comment]
@spencer-lunarg 
I don't want to adjust the offset manually, I can have different combination of shaders with different push constants.
The push constants are different across stages, so it's strange that the validation layer requires vk::ShaderStageFlagBits::eVertex for fragment data. 
I think the validation layer should not check all possible ranges.
The validation layer should check all vk::PushConstantRange from vk::PipelineLayout that contains vk::ShaderStageFlags in pushConstants.

**Comment by spencer-lunarg** [comment]
So the Validation Layers are just following the Vulkan Spec

> VUID-vkCmdPushConstants-offset-01795
For each byte in the range specified by offset and size and for each shader stage in stageFlags, there must be a push constant range in layout that includes that byte and that stage
>
> VUID-vkCmdPushConstants-offset-01796
For each byte in the range specified by offset and size and for each push constant range that overlaps that byte, stageFlags must include all stages in that push constant range’s [VkPushConstantRange](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VkPushConstantRange)::stageFlags

So I guess I am still trying to understand if you think

1. The Vulkan Spec shouldn't require this check
2. The Validation Layers are reading the spec language incorrectly

**Comment by maksym-pasichnyk** [comment]
@spencer-lunarg 
Maybe I'm not understanding the spec correctly or more likely the Vulkan Spec shouldn't require this check.

**Comment by spencer-lunarg** [comment]
So you are welcome to make the request https://github.com/KhronosGroup/Vulkan-Docs/issues to change the spec. I am going to close this, but **please** feel free to open this if you think this is still a validation layer issue! (as the code here is not checking what the spec says correctly)

**Comment by maksym-pasichnyk** [comment]
@spencer-lunarg Ok, thanks!
