### ISSUE TITLE
"simultaneously used " validation does not have enough information.

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#47]
**Issue by [Berserker66](https://github.com/Berserker66) (MIGRATED)**
_Thursday Sep 28, 2017 at 21:54 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2093_

----

In my case I have something like this:

https://pastebin.com/Z7UHMFny

Which unfortunately only tells me that something is wrong but does not actually help me in finding this issue. I logged the thread idents and slowly figured out that it must be my main thread and a thread that syncs the chromium embedded framework texture data. I'm still not sure what is actually happening and I'll need to invest some more time digging.

However, back to this issue - would it be possible to give a bit more information in these threading errors? Such as which command pool and which operations are happening at this time? Spec says, recording, freeing, resetting [...] - telling me which of these it is would already help.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/mark-lunarg"><img src="https://avatars2.githubusercontent.com/u/7252958?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mark-lunarg](https://github.com/mark-lunarg) (MIGRATED)**
_Thursday Sep 28, 2017 at 22:15 GMT_

----

Yeah, it shouldn't be hard to plumb the extra info through, and it's a great idea.  Thanks!

**Comment by jzulauf-lunarg** [comment]
Triage notes: What is needed is for the logging functionality to also to capture API entry point information potentially along with thread id (c.f. `std::this_thread::get_id` ),  in the access records, and then include that information in the log_msg in the case of conflict.

The bulk of this change will need to be done in the code generation of the thread layer entry points.

**Comment by mark-lunarg** [comment]
Hopefully addressed by #1557.
