### ISSUE TITLE
Subresource extent error message from copy operation with multi-planar format

### ISSUE THREAD

**Issue by ktomiharAMD** [KhronosGroup/Vulkan-ValidationLayers#472]
Hi,

I was trying to do copy operation using transfer queue for multi-planar image format (e.g. VK_FORMAT_G8_B8R8_2PLANE_420_UNORM). 

I created the image with extent of {w=8, h=8, d=1}, and set the imageExtent in copy region (VkBufferImageCopy) to be {w=8, h=8, d=1} and {w=4, h=4, d=1} respectively for each plane according to spec.

As I tried to copy for the image subresource of AspectMask = PLANE_1_BIT, I got the error message of following:

> "Error reported by layer [Validation] for [Command buffer]:  [ VUID-vkCmdCopyBufferToImage-imageOffset-01793 ] Object: 0x1d107de2640 (Type = 6) | vkCmdCopyBufferToImage(): pRegion[0].imageExtent (w=4, h=4, d=1) dimensions must be even integer multiples of this command buffer's queue family image transfer granularity (w=8, h=8, d=8) or offset (x=0, y=0, z=0) + extent (w=4, h=4, d=1) must match the image subresource extents (w=8, h=8, d=1). The Vulkan spec states: The imageOffset and imageExtent members of each element of pRegions must respect the image transfer granularity requirements of commandBuffer's command pool's queue family, as described in VkQueueFamilyProperties (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdCopyBufferToImage-imageOffset-01793)"

Shouldn't the image subresource extent for PLANE_1 be half of the width and half of the height with respect to the largest dimension (i.e. (w=4, h=4, d=1) in this case)?

**Comment by daveh-lunarg** [comment]
I agree, the plane_1 extent should be (4,4,1).  Looks like some validation code from the good 'ol days when images had just one plane, and one extent. PR incoming.
