### ISSUE TITLE
New dynamic rendering draw call VUs

### ISSUE THREAD

**Issue by mikes-lunarg** [KhronosGroup/Vulkan-ValidationLayers#4724]
#4723 removes VUIDs 06194, 06195, 06196, 06197. The following new VUIDs are their replacements:

**Valid Usage IDs requested**
  * VUID-{draw call}-colorAttachmentCount-07616
If the current render pass instance was begun with vkCmdBeginRendering and VkRenderingInfo::colorAttachmentCount greater than 0, then each element of the VkRenderingInfo::pColorAttachments array with a imageView equal to VK_NULL_HANDLE must have the corresponding element of VkPipelineRenderingCreateInfo::pColorAttachmentFormats used to create the currently bound pipeline equal to VK_FORMAT_UNDEFINED
  * VUID-{draw call}-pDepthAttachment-07617
If the current render pass instance was begun with vkCmdBeginRendering and VkRenderingInfo::pDepthAttachment->imageView was VK_NULL_HANDLE, the value of VkPipelineRenderingCreateInfo::depthAttachmentFormat used to create the currently bound graphics pipeline must be equal to VK_FORMAT_UNDEFINED
  * VUID-{draw call}-pStencilAttachment-07618
If the current render pass instance was begun with vkCmdBeginRendering and VkRenderingInfo::pStencilAttachment->imageView was VK_NULL_HANDLE, the value of VkPipelineRenderingCreateInfo::stencilAttachmentFormat used to create the currently bound graphics pipeline must be equal to VK_FORMAT_UNDEFINED
  * VUID-vkCmdExecuteCommands-imageView-07606
If vkCmdExecuteCommands is being called within a render pass instance begun with vkCmdBeginRendering, if the imageView member of an element of the VkRenderingInfo::pColorAttachments parameter to vkCmdBeginRendering is VK_NULL_HANDLE, the corresponding element of the pColorAttachmentFormats member of the VkCommandBufferInheritanceRenderingInfo structure included in the pNext chain of VkCommandBufferBeginInfo::pInheritanceInfo used to begin recording each element of pCommandBuffers must be VK_FORMAT_UNDEFINED

**Additional Info**
Spec MR: https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5487

**Comment by spencer-lunarg** [comment]
closing for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5064 instead (duplicate)
