### ISSUE TITLE
Compatible format of planes for multi-planar format

### ISSUE THREAD

**Issue by ktomiharAMD** [KhronosGroup/Vulkan-ValidationLayers#473]
Hi,

I created image with multi-planar format VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16 with VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT.

And I created image view of format VK_FORMAT_R16_UNORM for plane 0 (AspectMask = PLANE_0_BIT).

However, I got the error message of following:

> Error reported by layer [Validation] for [Image]:  [ VUID-VkImageViewCreateInfo-image-01586 ] Object: 0xab (Type = 10) | vkCreateImageView(): ImageView format VK_FORMAT_R16_UNORM is not compatible with plane 0 of underlying image format VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16, must be VK_FORMAT_R10X6_UNORM_PACK16. The Vulkan spec states: If image was created with the VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT flag, if the format of the image is a multi-planar format, and if subresourceRange.aspectMask is one of VK_IMAGE_ASPECT_PLANE_0_BIT, VK_IMAGE_ASPECT_PLANE_1_BIT, or VK_IMAGE_ASPECT_PLANE_2_BIT, then format must be compatible with the VkFormat for the plane of the image format indicated by subresourceRange.aspectMask, as defined in Compatible formats of planes of multi-planar formats (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkImageViewCreateInfo-image-01586)

As R16_UNORM is in the same compatibility class with R10X6_UNORM_PACK16 in the spec, shouldn't R16_UNORM also be acceptable?

**Comment by daveh-lunarg** [comment]
I agree the spec language on multi- / single-plane format compatibility is a little vague. The text says "the same number of bits per texel block", without distinguishing between _used_ bits or just _occupied_ bits.  OTOH the `Plane Format Compatibility Table` does distinguish between `16-bit` and `10-bit in a 16-bit field` formats, and that's what the validation logic adheres to.

It's possible that format compatibility was _intended_ to be transitive, but I don't find any language to that effect in the spec. I don't think we should consider changing the current table-specific interpretation in validation without some specific spec language supporting it.

Closing this issue as its not a validation bug, and any validation changes to be done will IMO first require a change to the spec language.

**Comment by gnl21** [comment]
This seems to have been fixed by #4307 so I've closed my PR #2879. I think this issue can be resolved now.
