### ISSUE TITLE
`ValidateDescriptor` applies per-index requirements to all indices in the binding

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-ValidationLayers#4749]
In the validation layer source code, there are various properties in the `interface_var` type indicating operations that are performed on an image, like `is_sampler_implicitLod_dref_proj`, `is_atomic_operation` and `is_dref_operation`, that the validation code gathers by analysing the shader. Now let's say, I have an array of two sampled image descriptors in one binding:
- The shader uses a dref operation with the image at index 0, and the image bound to index 0 has the required `SAMPLED_IMAGE_DEPTH_COMPARISON` format feature.
- The shader doesn't use a dref operation with the image at index 1, and the image bound to index 1 doesn't have this format feature.

This situation should be fine.

The problem is that one `interface_var` is stored per binding, and not per descriptor index. This means that in the `ValidateDescriptor` function that validates the currently bound image against the pipeline/shader, the requirements of `interface_var` are applied to all the images bound to that binding. In the example above, it ends up applying the `is_dref_operation` property to all bound images, thus requiring that the image bound to index 1 *also* has the `SAMPLED_IMAGE_DEPTH_COMPARISON` format feature, even though the image isn't actually used in any way to require that.

I think that solving this problem would require retrieving the accessed index in the binding when analysing the shader code. But I realise that this is only possible when the index is statically available in the shader, i.e. when it's a constant and doesn't depend on an external variable.

**Comment by jeremyg-lunarg** [comment]
I'm working on a solution to the general case of this problem, but it is a long term project.

**Comment by jeremyg-lunarg** [comment]
This should be fixed by https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6883
