### ISSUE TITLE
Should pipeline state queries for certain stages return a warning if the stage is disabled?

### ISSUE THREAD

**Issue by alexander-a-kharlamov** [KhronosGroup/Vulkan-ValidationLayers#476]
It's unclear from the spec if querying  VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_* or VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_* bits in a pipeline query is illegal when VkPhysicalDeviceFeatures.geometryShader or VkPhysicalDeviceFeatures.tessellationShader respectively are disabled.

If it's legal, I think it would still be beneficial to see a warning from validation layers. If it's illegal it should be reported as an error.

**Comment by jzulauf-lunarg** [comment]
This appears to be fully legal... adding to #24 and closing wontfix (at least not directly)
