### ISSUE TITLE
Building a static library for Android

### ISSUE THREAD

**Issue by themistocles-0** [KhronosGroup/Vulkan-ValidationLayers#4772]
At the moment, I compile all the third party libraries into my shared library statically, is the a way to build Vulkan-ValidationLayers into a static library, I've been trying the past two days, I've already seen the advice to use the prebuilt shared libraries, but as I noted, I currently prefer to statically link

**Comment by spencer-lunarg** [comment]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/build-android/jni/Android.mk#L96

```patch
- include $(BUILD_SHARED_LIBRARY)
+ include $(BUILD_STATIC_LIBRARY)
```

is all that should be needed

Assuming you don't need the test files you can always just delete those modules or go

```patch
- LOCAL_STATIC_LIBRARIES := googletest_main layer_utils shaderc
+ LOCAL_STATIC_LIBRARIES := googletest_main layer_utils shaderc VkLayer_khronos_validation
```

**Comment by themistocles-0** [comment]
I did the above and got the error "could not locate symbol layer_debug_messenger_actions", I removed the tests though, must the tests be compiled

**Comment by spencer-lunarg** [comment]
> must the tests be compiled

Only if you plan to run the tests, but if you just want the Layer itself, safe to remove!

Sorry, we have were working on refactoring the Android build system, but currently no convenient way to just build the layers without the test APK as well (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3088)

**Comment by themistocles-0** [comment]
How soon to a working Android.mk for static lib build

**Comment by themistocles-0** [comment]
> https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/build-android/jni/Android.mk#L96
> 
> ```diff
> - include $(BUILD_SHARED_LIBRARY)
> + include $(BUILD_STATIC_LIBRARY)
> ```
> 
> is all that should be needed
> 
> Assuming you don't need the test files you can always just delete those modules or go
> 
> ```diff
> - LOCAL_STATIC_LIBRARIES := googletest_main layer_utils shaderc
> + LOCAL_STATIC_LIBRARIES := googletest_main layer_utils shaderc VkLayer_khronos_validation
> ```

When I tried this, I got the error "could not locate symbol layer_debug_messenger_actions"

**Comment by themistocles-0** [comment]
> > How soon to a working Android.mk for static lib build
> 
> There are many other things to fix, so not going to be able to help for a while. I guess why are you not able to use the shared libraries?

@ the moment a matter of preference, I just build every other library I need into a static library and link it in statically, will try using the distributed shared libraries

**Comment by themistocles-0** [comment]
![Screenshot_20221109-190017](https://user-images.githubusercontent.com/74494183/200879686-d72fc13b-b4a5-477a-bc18-005a5d088e2c.jpg)
I'm starting to get the feeling the problem is I'd ignored the order of static library inclusion, causing symbol resolution errors, but the compiled libs via script above👆🏾👆🏾👆🏾is fine

**Comment by themistocles-0** [comment]
Figured it out, now there's a hang when I call vk::enumerateInstanceExtensionProperties()

**Comment by themistocles-0** [comment]
> Again, looking at the Android Loader code I linked above, I don't static Vulkan Layers are possible on Android

Guess so, @ my wit's end

> Is there any useful logged information from `adb logcat`?

None, have looked through it, mostly SDL2 logs, android's logs

**Comment by themistocles-0** [comment]
I guess it's just a quirk owing to the way vulkan is implemented as an API i.e: loader + ICD + layers, and how it's implemented on the android platform in particular
