### ISSUE TITLE
Clean up descriptor copy update validation

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#48]
**Issue by [tobine](https://github.com/tobine) (MIGRATED)**
_Friday Sep 29, 2017 at 18:49 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2094_

----

Src probably shouldn't need to be updated. Need some more spec language and potentially new VUIDs around copy update cases, currently primarily copy/reuse write update VUIDs. Add more copy update testing as well.

**Comment by tobine** [comment]
Checking this the VUs for copy updates have been improved and implemented.
