### ISSUE TITLE
Use fallthrough and remove unfinished switch cases

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/Vulkan-ValidationLayers#4809]
with C++ 17 the `[[fallthrough]]` syntax can be used to ensure the code is suppose to be missing the `break`

Also some `switch` cases have `TODO` to add the rest of the statements in `default`

**Comment by juan-lunarg** [comment]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/fc1c6286054e5772a506e95d67503dfc9bb2182b/CMakeLists.txt#L192-L196

To enforce this we just need to remove the following CMake. The main problem is the warnings produce by VMA.
