### ISSUE TITLE
error: 'class spvtools::ValidatorOptions' has no member named 'SetFriendlyNames'

### ISSUE THREAD

**Issue by brechtsanders** [KhronosGroup/Vulkan-ValidationLayers#4826]
When building with `-DBUILD_LAYERS:BOOL=ON` I get the following error:
```
R:/winlibs64-11.3.0msvcrt/Vulkan-ValidationLayers-1.3.235/layers/shader_validation.cpp:3960:13: error: 'class spvtools::ValidatorOptions' has no member named 'SetFriendlyNames'
 3960 |     options.SetFriendlyNames(false);
      |             ^~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
```

When I remove the following line from `layers/shader_validation.cpp` the error is gone and building succeeds:
```c
options.SetFriendlyNames(false);
```

OS: Windows 11
Compiler: MinGW-w64 (standalone version from https://winlibs.com/)
Version: 1.3.235
All the dependencies are up to date, built by myself from source using their latest release (glslang,vulkan-headers,vulkan-loader,spirv-headers,robin-hood-hashing).

**Comment by brechtsanders** [comment]
I just noticed `SetFriendlyNames` was recently added to SPIRV-Tools (https://github.com/KhronosGroup/SPIRV-Tools/pull/4951) but did not yet make it into the latest release version.

**Comment by spencer-lunarg** [comment]
The current [spirv-tools version](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/scripts/known_good.json#L39) is `eb0a366` which is newer than `07d361b` it was added

For your build environment please make sure you have the latest dependencies ([more info](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/BUILD.md)) 

```cpp
cd build
python3 ../scripts/update_deps.py --dir ../external --arch x64 --config debug
```

As I think you might not have the newest `SPIRV-Tools` files

**Comment by brechtsanders** [comment]
My goal is to build all my libraries from latest release versions, you seem to be using recent repositories.

My scenario would work if there is some kind of `#if`/`#endif` we can use around `options.SetFriendlyNames(false);`.

**Comment by jeremyg-lunarg** [comment]
> My goal is to build all my libraries from latest release versions, you seem to be using recent repositories.
> 
> My scenario would work if there is some kind of `#if`/`#endif` we can use around `options.SetFriendlyNames(false);`.

You might be better off sticking to only use the  sdk-* tags then.  Those are the versions that qualify as real releases, with coordination between dependent package maintainers and integration testing.

**Comment by brechtsanders** [comment]
Ok, I will stick to the sdk-* release versions.

**Comment by jeremyg-lunarg** [comment]
> > I'm okay will sticking to the sdk-* release versions, but version sdk-1.3.231.1 also has a line with `options.SetFriendlyNames(false);`
> 
> That's not good!

What version of SPIRV-Tools do you consider to be the latest release?  sdk-1.3.231.1 was built against their v2022.4 release as shown below.

There are tags in SPIRV-Tools for that SDK:
```
commit eb0a36633d2acf4de82588504f951ad0f2cecacb (HEAD, tag: v2022.4, tag: sdk-1.3.231.1, tag: sdk-1.3.231.0, origin/sdk-1.3.231, origin/canary)
Author: Diego Novillo <dnovillo@google.com>
Date:   Wed Oct 12 12:15:28 2022 -0400

    Finalize SPIRV-Tools v2022.4

```
And we used that commit (we should really use one of their tags for clarity)
```
Vulkan-ValidationLayers>git blame sdk-1.3.231.1 scripts/known_good.json

7418c9be68 (Nathaniel Cesario 2022-09-29 23:55:49 -0600 30)         {
7418c9be68 (Nathaniel Cesario 2022-09-29 23:55:49 -0600 31)             "name": "SPIRV-Tools",
7418c9be68 (Nathaniel Cesario 2022-09-29 23:55:49 -0600 32)             "url": "https://github.com/KhronosGroup/SPIRV-Tools.git",
7418c9be68 (Nathaniel Cesario 2022-09-29 23:55:49 -0600 33)             "sub_dir": "SPIRV-Tools",
7418c9be68 (Nathaniel Cesario 2022-09-29 23:55:49 -0600 34)             "build_dir": "SPIRV-Tools/build",
7418c9be68 (Nathaniel Cesario 2022-09-29 23:55:49 -0600 35)             "install_dir": "SPIRV-Tools/build/install",
7418c9be68 (Nathaniel Cesario 2022-09-29 23:55:49 -0600 36)             "cmake_options": [
7418c9be68 (Nathaniel Cesario 2022-09-29 23:55:49 -0600 37)                 "-DSPIRV-Headers_SOURCE_DIR={repo_dir}/../SPIRV-Headers"
7418c9be68 (Nathaniel Cesario 2022-09-29 23:55:49 -0600 38)             ],
78ce46e479 (Mike Schuchardt   2022-10-13 09:06:59 -0700 39)             "commit": "eb0a36633d2acf4de82588504f951ad0f2cecacb"
7418c9be68 (Nathaniel Cesario 2022-09-29 23:55:49 -0600 40)         },

```

SetFriendlyNames() was added by this SPIRV-Tools commit 07d361b6755c00922b30e6e20e8ae3797e78dd58
```
SPIRV-Tools>git tag --contains 07d361b6755c00922b30e6e20e8ae3797e78dd58
sdk-1.3.231.0
sdk-1.3.231.1
v2022.4
```

**Comment by jeremyg-lunarg** [comment]
@brechtsanders the SPIRV-Tools team has added release info on github in response to the issue I raised.

**Comment by jeremyg-lunarg** [comment]
You're still mixing things up. v1.3.236 isn't a release tag and definitely will not work with SPRIV-Tools at sdk-1.3.231.1
If you want to build v1.3.236 you will need the versions in https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/v1.3.236/scripts/known_good.json  which are NOT yet released tags from our dependencies.

There will soon be a new set of sdk-* tags (and presumably releases if the maintainers remember this time) across all these repositories.
