### ISSUE TITLE
Crash in vkCreateComputePipelines when using validation layer instrumented compute shader

### ISSUE THREAD

**Issue by rumblehhh** [KhronosGroup/Vulkan-ValidationLayers#4827]
**Describe the Issue**
We're hitting a crash inside vkCreateComputePipelines inside the driver when using a shader module created using the attached compute shader (`acceleration_structure_handle_remap.csh`).
We compile and optimise the glsl compute shader to spv using:
1. glslangValidator -V acceleration_structure_handle_remap.csh -o acceleration_structure_handle_remap_csh-unoptimised.spv -S comp
2. spirv-opt -O acceleration_structure_handle_remap_csh-unoptimised.spv -o acceleration_structure_handle_remap_csh-optimised.spv

I can workaround the crash either by:
a. Disabling validation layers completely
b. Using validation layers and using `acceleration_structure_handle_remap_csh-unoptimised.spv` directly i.e. skipping the spirv-opt step
c. Using validation layers and using `VK_EXT_validation_features` to disable shader validation (VkValidationFeatureDisableEXT-VK_VALIDATION_FEATURE_DISABLE_SHADERS_EXT). I was surprised by this as I hadn't realised the validation layers were instrumenting shader modules by default

We're using glslangValidator, spirv-opt and the validation layers from Vulkan SDK 1.3.231.2.
I've also tried using:
 - spirv-opt from spirv-tools package on Ubuntu jammy (Version: 2022.1+1.3.204.0-2)
 - glslangValidator Glslang Version: 10:11.8.0
 - Vulkan-ValidationLayers from e14ae34206c7f1fff73356c279904f19af95217f.

I've attached the following files:
 - `acceleration_structure_handle_remap.csh` - original glsl compute shader
 - `acceleration_structure_handle_remap_csh-unoptimised.spv` - output of step 1 above.
 - `acceleration_structure_handle_remap_csh-optimised.spv` - output of step 2 above.
 - `spirv-cross_acceleration_structure_handle_remap_csh-unoptimised.csh` - spirv-cross output for `acceleration_structure_handle_remap_csh-unoptimised.spv`
 - `spirv-cross_acceleration_structure_handle_remap_csh-optimised.csh` - spirv-cross output for `acceleration_structure_handle_remap_csh-optimised.spv`
 - `spirv_dis_acceleration_structure_handle_remap_csh-optimised.spv.txt` - spirv-dis output of the spirv used when creating the shader module when using c above (disabling shader validation)
 -  `instrumented_acceleration_structure_handle_remap_csh-optimised.spv` - the spirv used when creating the shader module which causes the crash when used with vkCreateComputePipelines. Side note spirv-cross crashes when trying to produce glsl for this spirv.
 - `spirv_dis_instrumented_acceleration_structure_handle_remap_csh-optimised.spv.txt` - spirv-dis output of the spirv used when creating the shader module which causes the crash when used with vkCreateComputePipelines.

**Environment:**
 - OS: Ubuntu 22.04
 - GPU:
AMD Radeon RX 6700 XT (RADV NAVI22)
VkPhysicalDeviceDriverProperties:
	driverID           = DRIVER_ID_MESA_RADV
	driverName         = radv
	driverInfo         = Mesa 23.0.0-devel (git-4030837 2022-11-18 jammy-oibaf-ppa)
	conformanceVersion = 1.3.0.0
 - SDK or header version if building from repo:

**Additional context**
[compute_shader_crash.zip](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/10040084/compute_shader_crash.zip)
A reproducer could also be sent confidentially if its required.

**Comment by spencer-lunarg** [comment]
> I was surprised by this as I hadn't realised the validation layers were instrumenting shader modules by default

To be clear, the only time we instrument the shader in the normal shader validation is

1. To flatten `OpGroupDecorate`
2. Set any `OpSpecConstant`

which neither of these are being used, what you are doing is really just avoid any validation on the `VkShaderModule` which is where the crash is occuring

> compute_shader_crash.zip

Thanks, this is super useful, about to take a look what is different between `acceleration_structure_handle_remap_csh-unoptimised.spv` and `acceleration_structure_handle_remap_csh-optimised.spv` and see where the issue is

**Comment by spencer-lunarg** [comment]
>  -  `instrumented_acceleration_structure_handle_remap_csh-optimised.spv` - the spirv used when creating the shader module which causes the crash when used with vkCreateComputePipelines.

I guess I am not sure where this was from

**Comment by rumblehhh** [comment]
> I guess I am not sure where this was from

Ah sorry to be clear this was retrieved by modifying the validation layers to write out to file the spirv bytes around the code here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/12033a3d242059e356e48ef294905e4a8bb320e0/layers/generated/layer_chassis_dispatch.cpp#L2551

acceleration_structure_handle_remap_csh-optimised.spv contains the spirv bytes our app passes to the validation layers
