### ISSUE TITLE
Unexpectedly receiving VUID-VkGraphicsPipelineCreateInfo-pStages-00731

### ISSUE THREAD

**Issue by rg3igalia** [KhronosGroup/Vulkan-ValidationLayers#4830]
**Describe the Issue**
I'm creating a new set of CTS tests that try to verify implementations correctly ignore pStages at graphics pipeline creation time when they are not needed. This is in the spirit of the current VkGraphicsPipelineCreateInfo VUs, which have some requirements about situations in which pStages has to meet certain conditions, but does not make it mandatory to be null when they are not used.

For example, when creating a graphics pipeline library with only the vertex input state, pStages should be ignored. However, if I try to do exactly that and include a tessellation shader in pStages, that should be ignored, I hit VUID-VkGraphicsPipelineCreateInfo-pStages-00731, which reads:

> If the pipeline is being created with [pre-rasterization shader state](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#pipelines-graphics-subsets-pre-rasterization) and pStages includes a tessellation control shader stage and a tessellation evaluation shader stage, pTessellationState must be a valid pointer to a valid [VkPipelineTessellationStateCreateInfo](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VkPipelineTessellationStateCreateInfo) structure

Which shouldn't apply to my case as I'm not creating a pipeline with pre-rasterization shader state.

**Valid Usage ID**
VUID-VkGraphicsPipelineCreateInfo-pStages-00731

**Environment:**
 - OS: Linux
 - GPU: NVIDIA.
 - SDK or header version if building from repo: 0f839617e939b5cf2c406fb00b1ed4533f695d71
 - Options enabled (synchronization, best practices, etc.): Default ones plus synchronization and debug printf.

**Additional context**

**Comment by rg3igalia** [comment]
Sorry, I forgot to mention that, to indicate the pipeline should only contain vertex input state, I'm chaining in a `VkGraphicsPipelineLibraryCreateInfoEXT` with `VK_GRAPHICS_PIPELINE_LIBRARY_VERTEX_INPUT_INTERFACE_BIT_EXT` in  the flags.

**Comment by spencer-lunarg** [comment]
So this is simply just a bug from what I can see (and exposed some other issue as well!) The spec now has the whole pre-rasterization shader state" section and the layers just need to be updated to better encapsulate it

**Comment by spencer-lunarg** [comment]
@rg3igalia ok so trying to untangle the spec here

>  I'm not creating a pipeline with pre-rasterization shader state.

But I see in the spec

> Pre-rasterization shader state is defined by:
    [VkPipelineShaderStageCreateInfo](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VkPipelineShaderStageCreateInfo) entries for:
        Vertex shaders
        Tessellation control shaders
        Tessellation evaluation shaders
        Geometry shaders
        Task shaders
        Mesh shaders
        
> when creating a graphics pipeline library with only the vertex input state, pStages should be ignored

So I don't see where in the spec that having `VK_GRAPHICS_PIPELINE_LIBRARY_VERTEX_INPUT_INTERFACE_BIT_EXT` should make the `VkGraphicsPipelineCreateInfo::pStages` ignored

**Comment by rg3igalia** [comment]
In the spec this is specified by combining two sections. One is the section you quoted above, which explains which parts of the VkGraphicsPipelineCreateInfo structure information should be taken into account for each piece of state. For example, for vertex input state only VkPipelineVertexInputStateCreateInfo and VkPipelineInputAssemblyStateCreateInfo are taken into account.

The other section explains how to decide which pieces of state you're providing at creation time, and that's the description of VkGraphicsPipelineLibraryCreateInfoEXT. It states the following:

> If a VkGraphicsPipelineLibraryCreateInfoEXT structure is included in the pNext chain of [VkGraphicsPipelineCreateInfo](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VkGraphicsPipelineCreateInfo), it specifies the [subsets of the graphics pipeline](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#pipelines-graphics-subsets) being created, excluding any subsets from linked pipeline libraries. If the pipeline is created with pipeline libraries, state from those libraries is aggregated with said subset.

And it also goes into details about what happens if we don't include the structure like in the traditional creation case. Together with the previous paragraph, this explains what you must do if you want to provide only part of the state while taking the rest from some included pipeline libraries while you link a final bindable pipeline.

> If this structure is omitted, and either [VkGraphicsPipelineCreateInfo](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VkGraphicsPipelineCreateInfo)::flags includes VK_PIPELINE_CREATE_LIBRARY_BIT_KHR or the [VkGraphicsPipelineCreateInfo](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VkGraphicsPipelineCreateInfo)::pNext chain includes a [VkPipelineLibraryCreateInfoKHR](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VkPipelineLibraryCreateInfoKHR) structure with a libraryCount greater than 0, it is as if flags is 0. Otherwise if this structure is omitted, it is as if flags includes all possible subsets of the graphics pipeline (i.e. a [complete graphics pipeline](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#pipelines-graphics-subsets-complete)).

The VUs from VkGraphicsPipelineCreateInfo then specify certain restrictions about the contents of pStages, but only for the cases where they are relevant because we're including that part of the state. Usually in the form of "If the pipeline is being created with [some state], then [restriction about valid behavior]". It follows that if the state is not being included, the contents of those members are irrelevant.

This also matches VUID-VkGraphicsPipelineCreateInfo-flags-06640:

> If [VkGraphicsPipelineLibraryCreateInfoEXT](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VkGraphicsPipelineLibraryCreateInfoEXT)::flags includes VK_GRAPHICS_PIPELINE_LIBRARY_PRE_RASTERIZATION_SHADERS_BIT_EXT or VK_GRAPHICS_PIPELINE_LIBRARY_FRAGMENT_SHADER_BIT_EXT, pStages must be a valid pointer to an array of stageCount valid [VkPipelineShaderStageCreateInfo](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VkPipelineShaderStageCreateInfo) structures

Otherwise there are no implicit or explicit rules about what pStages must be.

**Comment by spencer-lunarg** [comment]
> In the spec this is specified by combining two sections

everyone's favorite :tada: 

Ok, I do think this issue is related to the internal issue you raised https://gitlab.khronos.org/vulkan/vulkan/-/issues/3240 and https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4366#issuecomment-1296587415

I just built mesa with the current `VK_EXT_graphics_pipeline_library` extension prototype so that should allow me to also create some validation layers test to help with this. Doesn't seem necessarily hard, just a lot of structs and subsets need to re-re-read the spec to make sure it all lines up. Thanks for the help and pointing this issue out

**Comment by rg3igalia** [comment]
> Ok, I do think this issue is related to the internal issue you raised https://gitlab.khronos.org/vulkan/vulkan/-/issues/3240 and [#4366 (comment)](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4366#issuecomment-1296587415)

And also to https://gitlab.khronos.org/vulkan/vulkan/-/issues/3300, which is another VU I'm hitting with the new tests.

**Comment by ziga-lunarg** [comment]
Seems to me that this issue has already been fixed and there is a test for it `PositiveGraphicsLibrary.TessellationWithoutPreRasterization`
