### ISSUE TITLE
Adding missing Ray Tracing Access Mask VUs

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/Vulkan-ValidationLayers#4859]
**Describe the situation in which you encountered the missing validation**
Missing Ray Tracing access mask VUs

**Valid Usage IDs requested**
// related 06254 06255 06257

- [ ]  VUID-VkMemoryBarrier2-srcAccessMask-06256
- [ ]  VUID-VkMemoryBarrier2-dstAccessMask-06256
- [ ]  VUID-VkBufferMemoryBarrier2-srcAccessMask-06256
- [ ]  VUID-VkBufferMemoryBarrier2-dstAccessMask-06256
- [ ]  VUID-VkImageMemoryBarrier2-srcAccessMask-06256
- [ ]  VUID-VkImageMemoryBarrier2-dstAccessMask-06256

The same 6 permutation for

- VUID-VkMemoryBarrier2-srcAccessMask-06254
- VUID-VkMemoryBarrier2-srcAccessMask-06255
- VUID-VkMemoryBarrier2-srcAccessMask-06257 

**Additional Context**

These are all related, just depending on the extensions enabled (search for the VUID in https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/f4eb3e9a7acdef9ab62ac9af954a50409895ac6d/chapters/commonvalidity/access_mask_2_common.adoc)

A simple logic view is

```
if not VK_KHR_ray_query
if (VK_KHR_ray_tracing_pipelin OR VK_NV_ray_tracing)
  * VUID-VkMemoryBarrier2-srcAccessMask-06254

if not VK_KHR_ray_query
if not (VK_KHR_ray_tracing_pipelin OR VK_NV_ray_tracing)
* VUID-VkMemoryBarrier2-srcAccessMask-06255

if not VK_KHR_ray_query
if (VK_KHR_ray_tracing_pipelin OR VK_NV_ray_tracing)
* VUID-VkMemoryBarrier2-srcAccessMask-06256

if not VK_KHR_ray_query
if not (VK_KHR_ray_tracing_pipelin OR VK_NV_ray_tracing)
* VUID-VkMemoryBarrier2-srcAccessMask-06257
```

A related VUID to look at for how to implement is `VUID-VkMemoryBarrier2-dstAccessMask-03927`

**Comment by arno-lunarg** [comment]
- VUID-VkMemoryBarrier2-srcAccessMask-06254
- VUID-VkMemoryBarrier2-srcAccessMask-06255
- VUID-VkMemoryBarrier2-srcAccessMask-06257 

were removed, it should simplify things
