### ISSUE TITLE
Missing validation of signal-before-wait for binary semaphores

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-ValidationLayers#4869]
One of the conditions for waiting on a binary semaphore is:

> A binary semaphore must be signaled, or have an associated semaphore signal operation that is pending execution.

I just noticed when trying to reproduce a bug that this is not validated, at least when the wait operation is `vkQueuePresentKHR`. In short, if the application does this:

- First call vkQueuePresentKHR wait on semaphore S
- Then call vkQueueSubmit signalling semaphore S

There is no validation error.

**Comment by spencer-lunarg** [comment]
@ShabbyX Is there a VUID you see this suppose to be tied too? (I haven't looked yet)

**Comment by jeremyg-lunarg** [comment]
This seems like VUID-vkQueuePresentKHR-pWaitSemaphores-01295 to me.

**Comment by jeremyg-lunarg** [comment]
@ShabbyX I'm reopening this because we don't have code to emit 01295 or test it, and we should and fairly easily could.  There's several other vkQueuePresentKHR that are equivalent to other VUIDs in vkQueueSubmit which can be added too.
