### ISSUE TITLE
Improve system for calling GetInstanceProcAddr in tests 

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/Vulkan-ValidationLayers#4877]
Currently we are having to manually add each extensions' new functions using `vkGetInstanceProcAddr` (and device proc addr)

Two possible options to fix this is make a useful macro

```c++
 #define GET_INSTANCE_PROC_ADDR(function) \
 const PFN_##function function = GetInstanceProcAddr<PFN_##function>(#function);

GET_INSTANCE_PROC_ADDR(vkGetAccelerationStructureBuildSizesKHR)
```

or use the already generated logic to automatically add any added extension functions to the dispatch table for tests

**Comment by jeremyg-lunarg** [comment]
I would prefer the approach of improving lvt_function_pointers.{h, cpp} to automatically add function pointers for any enabled 
 extensions, unless it proves impractical.  There is a ton of boilerplate in the tests that could then be removed:
```
~/src/Vulkan-ValidationLayers/tests>git grep GetDeviceProcAddr | wc -l
433
~/src/Vulkan-ValidationLayers/tests>git grep GetInstanceProcAddr | wc -l
198
```

**Comment by spencer-lunarg** [comment]
This was solved from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5621
