### ISSUE TITLE
Global variables might be used when invalid in some cases.

### ISSUE THREAD

**Issue by Keenuts** [KhronosGroup/Vulkan-ValidationLayers#4884]
Hi!

This issue was found when running validation layers with ubsan on our internal CI. We have a multi-threaded application and build validation layers differently (bazel, custom rules), but cannot share logs. (I know, horrible bug report :upside_down_face: )
What we observe is failure when creating vulkan instance because of some SIGILL during what I believe is global variable initialization by the dynamic linker.

After some debugging, I noticed global variables were declared in the generated files, and those globals were not trivially constructible, like `std::map`. This issue could be "solved" by changing the compilation order and some other magic incantations, but never fixed all cases.

However, changing:
```
const std::map<> something = { [...] }
```
to:
```
const std::map<>& getSomething() {
     static const std::map<> map = { [...] };
     return map;
}
```

Fixed it in all cases (we found other issues, but don't have concrete solution/more context yet).
This is not a perfect fix either, just masked the problem since at least this function-local static initialization order is defined.
An alternative would be to follow this: https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables and only have constexpr globals for those cases.

**Environment:**
 - OS: linux
 - GPU: n/a
 - seen at commit af45e1ee442f5071521f0fdf4dc33a866a383e75

**Comment by Keenuts** [comment]
Looked into that a bit today, and I don't see a straightforward way to make it all constexpr right now:
 -> having those maps converted to constexpr arrays requires the contained items to be constexpr.
 -> base type can be std::bitset<128>, which allow some constexpr operation, but not enough to set high bits.
 -> extended constexpr support is coming, but cpp23, which is a bit too modern...

So in the meantime, I'd suggest the following:
 - convert map/unoderered_maps to arrays, which are trivially destructible
 - wrap those as function-local static, to make sure initialization is thread-safe.
 - since they are read-only consts, no need to lock on read.

**Comment by Keenuts** [comment]
@juan-lunarg I see you mentioned working on the code generation more broadly on other issues. Do you plan on changing the actual code, or just tooling/generation process?
(to know if I should work on the more long-term solution, or stop after the band-aid PR in flight)

**Comment by juan-lunarg** [comment]
I don't really have big plans for the current code generation. The only thing on my roadmap is currently the code generation is causing a bug for `vkExportMetalObjectsExt` when handle wrapping is enabled. Which I'm currently working on.

**Comment by juan-lunarg** [comment]
I've assigned the issue to you. Thanks for contributing @Keenuts :+1: , there is a lot of work to go around and the help is appreciated.

**Comment by Keenuts** [comment]
Oh no sorry, completely missed it! Feel free to take it!

**Comment by juan-lunarg** [comment]
@Keenuts is this issue still occurring?

> We have a multi-threaded application and build validation layers differently (bazel, custom rules), but cannot share logs. (I know, horrible bug report upside_down_face )

In order to tackle this issue effectively we will want to add something to CI to prevent a regression. Without more information on how to prevent a regression there isn't much tackling the issue.

I'll re-open if more information is given on how to repro.

**Comment by Keenuts** [comment]
@juan-lunarg 
No the issue was solved by https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4905 IIRC.
But I cannot even remember on what CI we saw this issue....
Fine with closing this until it resurfaces. If it does, having a repro on the public side is a good idea yes..

Thanks!
