### ISSUE TITLE
Problems building the vaildation layers using Cmake

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-ValidationLayers#4894]
I've been having troubles building recent versions of the layers at the CMake step. It all worked fine in the past, but I can't get it to work anymore. Even though I followed the  build instructions, it always fails with :

```
CMake Error at CMakeLists.txt:116 (find_package):
  Could not find a package configuration file provided by "VulkanHeaders"
  with any of the following names:

    VulkanHeadersConfig.cmake
    vulkanheaders-config.cmake

  Add the installation prefix of "VulkanHeaders" to CMAKE_PREFIX_PATH or set
  "VulkanHeaders_DIR" to a directory containing one of the above files.  If
  "VulkanHeaders" provides a separate development package or SDK, be sure it
  has been installed.
```

I ran the update_deps.py script multiple times, and ran the install target for the Vulkan headers manually. But still, it always fails with above error.

What's very odd, and maybe a bug in how CMake is used for the validation layers, is that if I set `VulkanHeaders_DIR` manually, every time I re-run cmake that variable get's cleared. So I can't even manually override the error.

Any clues on how I can resolve this?

Btw. it would great if the build artifacts from the CI could be uploaded somewhere. So people could just download nightly builds instead of having to build the layers themself.

**Environment:**
 - OS: Windows 10
 - IDE: Visual Studio 2019
 - CMAKE: 3.32.1

**Comment by SaschaWillems** [comment]
I found this issue: https://github.com/KhronosGroup/Vulkan-Loader/issues/140

It sounds similar to my problem, but I'm not sure how to proceed.

**Comment by mark-lunarg** [comment]
@juan-lunarg, @charles-lunarg, can y'all help out here?

**Comment by SaschaWillems** [comment]
Actually build instructions for Window won't work at all for me. After removing the build directory to get a clean start, I can't even generate any CMake file using the Windows build instructions:

```
python3 ..\scripts\update_deps.py --dir ..\external --arch x64 --config debug
```

Works fine, but

```
cmake -A x64 -C ..\external\helper.cmake -DCMAKE_BUILD_TYPE=Debug ..
```

I get the following error:

```
CMake Error: Error: generator platform: x64
Does not match the platform used previously:
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
``` 

If I remove the `-A x64` argument, the command succeeds.

**Comment by juan-lunarg** [comment]
> CMake Error: Error: generator platform: x64
> Does not match the platform used previously:
> Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.

This is a known issue with update_deps.py which is why I want to use a standard approach like vcpkg.

You need to delete the external directory. Those dependencies were built incompatible with your current vvl build.

**Comment by juan-lunarg** [comment]
update_deps.py doesn't handle
- changing the compilers
- changing the generator
- changing the target architecture
- changing the build type

you have to delete the external directory on any of these changes...

**Comment by mark-lunarg** [comment]
Can this information be added to the instructions in `BUILD.md` in the interim?

**Comment by juan-lunarg** [comment]
Yes they can.

**Comment by juan-lunarg** [comment]
I'll have CMake generate a clearer error message instead. Just requires generating a hash based on the above items and checking if the hash changes.

**Comment by juan-lunarg** [comment]
> Thanks everyone. Removing the external directory didn't do the trick for me. I just removed the whole repository and cloned it into a fresh directory. Everything then worked as noted in the build.md.

Sorry for the inconvenience.
