### ISSUE TITLE
Performance is extremely poor with validation layers

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#49]
**Issue by [Novum](https://github.com/Novum) (MIGRATED)**
_Tuesday Oct 03, 2017 at 21:45 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2100_

----

I understand that some performance degradation is expected, but with a lot of API calls the performance even with only core validation is unworkable. We are talking <1FPS where we would easily manage >200FPS on CPU side otherwise.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/mark-lunarg"><img src="https://avatars2.githubusercontent.com/u/7252958?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mark-lunarg](https://github.com/mark-lunarg) (MIGRATED)**
_Tuesday Oct 03, 2017 at 22:15 GMT_

----

Getting a sample workload showing the issue, or at least some areas to focus on would be helpful.  In the complex workloads we do have, the performance impact is much less than you are experiencing.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/Novum"><img src="https://avatars1.githubusercontent.com/u/112222?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Novum](https://github.com/Novum) (MIGRATED)**
_Tuesday Oct 03, 2017 at 22:39 GMT_

----

You should ship PDBs for the release validation layers. That way I could do performance profiling without having to recompile anything & it would help debugging in general.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/mark-lunarg"><img src="https://avatars2.githubusercontent.com/u/7252958?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mark-lunarg](https://github.com/mark-lunarg) (MIGRATED)**
_Tuesday Oct 03, 2017 at 22:40 GMT_

----

We'll look into doing so.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/Novum"><img src="https://avatars1.githubusercontent.com/u/112222?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Novum](https://github.com/Novum) (MIGRATED)**
_Tuesday Oct 03, 2017 at 22:41 GMT_

----

Thank you, I appreciate it.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/RCalocaO"><img src="https://avatars2.githubusercontent.com/u/6879188?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [RCalocaO](https://github.com/RCalocaO) (MIGRATED)**
_Wednesday Oct 04, 2017 at 17:48 GMT_

----

We have the same issue on UE4; I'll try to get a Very Sleepy capture and upload it.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/chrisforbes"><img src="https://avatars1.githubusercontent.com/u/128877?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Friday Oct 20, 2017 at 21:03 GMT_

----

@RCalocaO any update?

**Comment by karl-lunarg** [comment]
<a href="https://github.com/RCalocaO"><img src="https://avatars2.githubusercontent.com/u/6879188?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [RCalocaO](https://github.com/RCalocaO) (MIGRATED)**
_Friday Oct 20, 2017 at 21:59 GMT_

----

@chrisforbes  Here they are, with and without validation.

[Sleepy_Vulkan_SunTemple.zip](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/files/1403439/Sleepy_Vulkan_SunTemple.zip)

**Comment by KarenGhavam-lunarG** [comment]
This original issue was opened in May of 2017. @RCalocao I know that your recent performance issue you had in late January has been resolved. Was that issue the same issue you are referring to here with the Sleepy_Vulkan_SunTemple zip?

**Comment by mark-lunarg** [comment]
Performance issues are being tracked in issue #846.
