### ISSUE TITLE
sync_val_gen.py output apparently is incorrect again

### ISSUE THREAD

**Issue by jeremyg-lunarg** [KhronosGroup/Vulkan-ValidationLayers#4904]
I noticed that the changes from this PR were removed again in 825dd8a8902b1005434016951f636f759d4bdcfb. Why?

_Originally posted by @Rua in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4395#issuecomment-1335072124_

**Comment by jeremyg-lunarg** [comment]
@Rua some parts of the access mask <-> pipeline stage validity are generated from VUID text in valid_usage.json. It looks like that might have happened in the 1.3.227 header update.  It looks like you figured that out already and filed https://github.com/KhronosGroup/Vulkan-Docs/pull/1997

BTW I have a long standing issue open in the Khronos working group to give us a more directly machine readable way to get this information but there unfortunately hasn't been any progress yet.

**Comment by jeremyg-lunarg** [comment]
@arno-lunarg I think your recent PR took care of this and much more.

**Comment by arno-lunarg** [comment]
I am not sure of that? I only added validation concerning `VK_ACCESS_2_ACCELERATION_STRUCTURE_READ_BIT`, and from my understanding, my changes will not have any effect on this issue here... I did not change anything in the current validation code.

**Comment by jeremyg-lunarg** [comment]
this script is getting replaced, so this issue is irrelevant.
