### ISSUE TITLE
Chrome builds are failing on "layers: Modernize generated code"

### ISSUE THREAD

**Issue by SenorBlanco** [KhronosGroup/Vulkan-ValidationLayers#4924]
After commit b4539c542c35d1643bdf73b426fc951ea035b65e, Chrome builds seem to be failing with:

Step _compile (with patch)_ failed. Error logs are shown below:
[2131/24370] CXX obj/third_party/vulkan-deps/vulkan-validation-layers/src/VkLayer_khronos_validation/parameter_validation.o
FAILED: obj/third_party/vulkan-deps/vulkan-validation-layers/src/VkLayer_khronos_validation/parameter_validation.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
../../third_party/vulkan-deps/vulkan-validation-layers/src/layers/generated/parameter_validation.cpp:5336:376: error: integer value 3000300003 is outside the valid range of values [0, 2147483647] for this enumeration type [-Wenum-constexpr-conversion]

**Comment by SenorBlanco** [comment]
Context: https://chromium-review.googlesource.com/c/chromium/src/+/4083098?tab=checks

**Comment by juan-lunarg** [comment]
I found the culprit.

```
constexpr std::array allowed_structs_VkInstanceCreateInfo = { VK_STRUCTURE_TYPE_DEBUG_REPORT_CALLBACK_CREATE_INFO_EXT, VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT, VK_STRUCTURE_TYPE_DIRECT_DRIVER_LOADING_LIST_LUNARG, VK_STRUCTURE_TYPE_EXPORT_METAL_OBJECT_CREATE_INFO_EXT, VK_STRUCTURE_TYPE_VALIDATION_FEATURES_EXT, VK_STRUCTURE_TYPE_VALIDATION_FLAGS_EXT, static_cast<VkStructureType>(VK_STRUCTURE_TYPE_INSTANCE_LAYER_SETTINGS_EXT) };
```

That static_cast at the end is generating an invalid value.

VK_STRUCTURE_TYPE_INSTANCE_LAYER_SETTINGS_EXT is set to `3000300003` in our code. But that isn't a valid given the range of VkStructureType.

Looks like this was an issue before. Making the array constexpr just exposed the issue.

**Comment by SenorBlanco** [comment]
Thanks for the quick diagnosis and fix!
