### ISSUE TITLE
Image object names not included in image layout validation errors

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/Vulkan-ValidationLayers#4928]
**Describe the Issue**
I was debugging an image layout validation error and noticed I was not getting my debug object name for the VkImage.  It is because this code passes only the command buffer into the LogError and not the VkImage:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/5f77f7c00a0ebfcb3be0fcc11af76d28b4ccd247/layers/buffer_validation.cpp#L4848

So the error does not give me the name:

``` UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object 0: handle = 0x30f822990, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x4dae5635 | vkQueueSubmit(): pSubmits[0].pCommandBuffers[0] command buffer VkCommandBuffer 0x30f822990[] expects VkImage 0xcc150200000605c8[] (subresource: aspectMask 0x1 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL--instead, current layout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL.```

In general, it would good to audit these and make sure any place where an image layout is involved that the image name is also there.  These can be very hard to track down!

**Valid Usage ID**
UNASSIGNED-CoreValidation-DrawState-InvalidImageLayou

**Environment:**
 - OS: Win10
 - GPU: GTX 2080
 - SDK or header version if building from repo: master
 - Options enabled (synchronization, best practices, etc.):

**Additional context**

**Comment by spencer-lunarg** [comment]
Assigning myself to get this a proper VUID in the spec

**Comment by ncesario-lunarg** [comment]
I'm going to do a quick pass of the `buffer_validation.cpp` file and add any missing object handles I find. We should probably do this will all files incrementally.
