### ISSUE TITLE
Transform Feedback memory barriers don't validate

### ISSUE THREAD

**Issue by brett19** [KhronosGroup/Vulkan-ValidationLayers#493]
When doing a pipeline buffer memory barrier and passing in Transform Feedback related access flags, the validation layer will complain that stage mask and access flags do not match.  I believe this is an error related to the validation layers not being updated with the newest transform feedback specification changes.

**Comment by tobine** [comment]
Just wanted to check if you're running with latest code from master or from a previous SDK release? There's a chance that #420 from @pdaniell-nv that landed on master Nov 2nd addresses this issue.

**Comment by brett19** [comment]
Your right.  I'm running something newer than the latest SDK, but it does not include this PR.  Looks like this would fix it
