### ISSUE TITLE
`vkCmdClearAttachments` is missing from sync validation

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-ValidationLayers#4946]
I noticed that the `vkCmdClearAttachments` command is completely missing from the sync validation code. Neither the validation nor the recording of the command are processed at all. I don't know if it was missed, or if it's particularly hard to implement.

**Comment by spencer-lunarg** [comment]
cc @jzulauf-lunarg @jeremyg-lunarg - either of you  know the answer to this?

**Comment by jeremyg-lunarg** [comment]
> cc @jzulauf-lunarg @jeremyg-lunarg - either of you know the answer to this?

This is almost certainly an oversight.

**Comment by jzulauf-lunarg** [comment]
@spencer-lunarg  -- should be straightforward.  Like clear, but with ordering rules.  The resources to clear will be looked up through the current renderpass.  There is a pre-baked range generator for each attachment.  You can look at other operations that affect attachments for examples.
