### ISSUE TITLE
Add support for VUID-vkCmdExecuteCommands-commandBuffer-00103

### ISSUE THREAD

**Issue by juan-lunarg** [KhronosGroup/Vulkan-ValidationLayers#4952]
**Valid Usage IDs requested**
VUID-vkCmdExecuteCommands-commandBuffer-00103

**Additional Context**
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3170

**Comment by spencer-lunarg** [comment]
was added in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6250
