### ISSUE TITLE
Please consider validating lifetime of pipeline libraries

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-ValidationLayers#4955]
The spec requires pipeline libraries to stay alive while the linked pipeline is. This is not validated, but it would be nice if it did. I recently hit a crash in VVL because I was destroying pipeline libraries too early, and it took a bit before I found out I should have kept them alive.

**Comment by spencer-lunarg** [comment]
Agree with adding a lifetime check

> The spec requires pipeline libraries to stay alive while the linked pipeline is

You have a specific line? I want to find proper VUID to tag it with (or create a new one if missing)

**Comment by ShabbyX** [comment]
First paragraph of https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap10.html#pipelines-library:

> A pipeline library is .... The application must maintain the lifetime of a pipeline library based on the pipelines that link with it.

**Comment by spencer-lunarg** [comment]
so I realized this was fixed already in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6472

created a test in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6959 to confirm
