### ISSUE TITLE
crashes and failures with GalaxyS22 (Exynos)

### ISSUE THREAD

**Issue by lunarpapillo** [KhronosGroup/Vulkan-ValidationLayers#4961]
This device has been updated to the latest OS currently available:
- GPU Samsung Xclipse 920
- `apiVersion` 1.1.179
- `driverVersion` 0x800000
- build fingerprint `samsung/r0sxxx/r0s:12/SP1A.210812.016/S901BXXU2BVKB:user/release-keys`

A blacklist exercise (running one test case at a time) shows the following two crashes:
- `VkLayerTest.TestShaderZeroInitializeWorkgroupMemory`
- `VkPositiveLayerTest.RayTracingValidateGetAccelerationStructureBuildSizes`

and the following six failures:
- `VkLayerTest.BindImageInvalidMemoryType`
- `VkLayerTest.BindInvalidMemory`
- `VkLayerTest.BindInvalidMemory2Disjoint`
- `VkLayerTest.InitSwapchainPotentiallyIncompatibleFlag`
- `VkLayerTest.RayTracingLibraryFlags`
- `VkPositiveLayerTest.RayTracingPipelineShaderGroupsKHR`

All of the above are currently blacklisted in **VulkanTests**.  They will be cleared from the **VulkanTests** blacklist when they have been processed in VVL (either the project code fixed, the test code fixed, or the test cases blacklisted internally to VVL).

**Comment by lunarpapillo** [comment]
The full text of the blacklist exercise may be helpful in identifying why particular tests failed: 
[blacklist.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/10225807/blacklist.txt)

**Comment by spencer-lunarg** [comment]
the error in `AndroidHardwareBufferImportBufferHandleType`/`AndroidHardwareBufferMemoryRequirements` are strange, curious what is happening

`RayTracingPipelineCreateInfoKHR` and `RayTracingInvalidPipelineFlags` seems to be an issue not generating a SPIR-V binary from the GLSL

**Comment by juan-lunarg** [comment]
The following tests have been added to the blacklist:

- VkPositiveLayerTest.RayTracingPipelineShaderGroupsKHR
- VkLayerTest.InvalidProtectedQueue
- VkLayerTest.AndroidHardwareBufferDedicatedUsageDS
- VkLayerTest.AndroidHardwareBufferImportBufferHandleType
- VkLayerTest.RayTracingPipelineCreateInfoKHR
- VkLayerTest.RayTracingPipelineShaderGroupsKHR
- VkLayerTest.RayTracingInvalidPipelineFlags
- VkBestPracticesLayerTest.UseDeprecatedInstanceExtensions
- VkPositiveLayerTest.AndroidHardwareBufferMemoryRequirements
- VkPositiveLayerTest.AndroidHardwareBufferDepthStencil

**Comment by spencer-lunarg** [comment]
This issue got stale - many of these tests are renamed and/or been worked on

I am currently trying to reduce which tests are "still" failing, from there will make the proper issues to looking into why
