### ISSUE TITLE
Failures with Windows NVIDIA driver 527.77

### ISSUE THREAD

**Issue by lunarpapillo** [KhronosGroup/Vulkan-ValidationLayers#4966]
These tests failed on driver 527.77:
- `VkLayerTest.InvalidDescriptorSetLayoutBinding`
- `VkLayerTest.CopyMutableDescriptors`
- `VkLayerTest.ValidateUpdatingMutableDescriptors`
- `VkLayerTest.MutableDescriptorPoolsWithPartialOverlap`
- `VkLayerTest.InvalidWriteMutableDescriptorSet`
- `VkLayerTest.MutableDescriptors`
- `VkLayerTest.DescriptorUpdateTemplate`
- `VkLayerTest.MutableDescriptorSetLayout`
- `VkLayerTest.DescriptorBufferSetLayout`
- `VkLayerTest.DescriptorBufferNotEnabled`
- `VkLayerTest.DescriptorBufferDescriptorGetInfo`
- `VkPositiveLayerTest.CopyMutableDescriptors`

No test crashes were observed.

The blacklist exercise output may be helpful to developers trying to figure out why these tests failed: 
[blacklist527.77.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/10233003/blacklist527.77.txt)

**Comment by lunarpapillo** [comment]
The same blacklist shows up in a blacklist exercise for 527.97.

**Comment by Tony-LunarG** [comment]
Fixed via #5104

**Comment by Tony-LunarG** [comment]
Removed from CI blacklist
