### ISSUE TITLE
Invalid `api_version` in manifest file

### ISSUE THREAD

**Issue by SpaceIm** [KhronosGroup/Vulkan-ValidationLayers#4973]
**Describe the Issue**
Vulkan-Loader doesn't like `api_version` found in manifest file of Vulkan-ValidationLayers 1.3.236.0, so it skips this manifest file. `api_version` value in this file is `1.3.236.0`, but it should be `1.3.236` to satisfy Vulkan-Loader.

**Environment:**
 - OS: macOS Monterey
 - GPU: AMD Radeon Pro 5300M
 - SDK or header version if building from repo: 1.3.236.0
 - Options enabled (synchronization, best practices, etc.):

**Additional context**

Vulkan-Loader logs with `VK_LOADER_DEBUG=all`:

```
INFO:             Found manifest file /Users/spaceim/.conan/data/vulkan-validationlayers/1.3.236.0/_/_/package/30dd3403c0633649d778eca68bdac648f29555e4/res/vulkan/explicit_layer.d/VkLayer_khronos_validation.json (file version "1.2.0")
INFO | LAYER:     Layer "VK_LAYER_KHRONOS_validation" has an 'api_version' field which contains a non-zero variant value of 1.  Skipping Layer.
```

**Comment by SpaceIm** [comment]
Well, actually I understand, in conan config file is generated automatically but it doesn't know that version passed to config file should be 1.3.236 instead of 1.3.236.0, so it breaks because CMakeLists of Vulkan-ValidationLayers relies on this version in config file of Vulkan-Headers in order to populate its manifest file.

**Comment by juan-lunarg** [comment]
Why doesn't Conan use the `*.cmake` files produced by Vulkan-Headers?

I understand in the past it wasn't implemented, but now that it is shouldn't it be preferred?

**Comment by SpaceIm** [comment]
It's not really conan itself, but conan-center which enforces removal of CMake config & pkgconfig files. I agree it's not always ideal, and specially for vulkan-headers, but there is a rational: https://github.com/conan-io/conan-center-index/blob/7e1a4345ffc7e151ab3e053642e3c38726cdc804/docs/faqs.md#why-are-cmake-findconfig-files-and-pkg-config-files-not-packaged

Anyway, it's not a bug in Vulkan-ValidationLayers, I'll try to find a way to fix version in CMake config file generated by conan for vulkan-headers (or eventually keep config file generated during installation vulkean-headers, it's allowed by conan, but something must be changed in vulkan-headers recipe to prevent conan to generate its own CMake config file for vulkan-headers).

**Comment by juan-lunarg** [comment]
VVL should mimic what the loader does.
https://github.com/KhronosGroup/Vulkan-Loader/pull/1104

The version of the manifest should not depend on the version of Vulkan-Headers available.

**Comment by juan-lunarg** [comment]
@SpaceIm as of https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/ac7c75bb519ede9ee65e43778da2274002c525b0 the `api_version` will not cause issues for the `Conan` package manager

**Comment by SpaceIm** [comment]
thanks
