### ISSUE TITLE
vkResetFences causes a crash on macOS when using VulkanSDK 1.3.231.1+ 

### ISSUE THREAD

**Issue by theunwisewolf** [KhronosGroup/Vulkan-ValidationLayers#4974]
**Describe the Issue**
Simply calling vkResetFences() causes a crash in the validation layers. Example Code - 

```
    CreateVulkanSurface(&s_Context);
    VulkanSelectPhysicalDevice(&s_Context, requirements);
    VulkanCreateLogicalDevice(&s_Context, requirements);

    // Test code
    {
        VkFenceCreateInfo info = {};
        info.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO;
        info.flags = VK_FENCE_CREATE_SIGNALED_BIT;
        info.pNext = NULL;
        VkFence handle;
        vkCreateFence(s_Context.LogicalDevice.Handle, & info, 0, &handle);
        assert(handle);

        vkResetFences(s_Context.LogicalDevice.Handle, 1, &handle);  // <---- Crashes
    }
```

I tried creating a signalled as well as unsignalled fence (which shouldn't matter). Same issue.

**Valid Usage ID**
No message. It just crashes with the following trace - 
```
__cxa_throw (@__cxa_throw:3)
std::exception_ptr std::make_exception_ptr<std::__1::future_error>(std::__1::future_error) (@std::exception_ptr std::make_exception_ptr<std::__1::future_error>(std::__1::future_error):29)
std::__1::promise<void>::~promise() (@std::__1::promise<void>::~promise():31)
FENCE_STATE::Reset() (@FENCE_STATE::Reset():28)
ValidationStateTracker::PostCallRecordResetFences(VkDevice_T*, unsigned int, VkFence_T* const*, VkResult) (@ValidationStateTracker::PostCallRecordResetFences(VkDevice_T*, unsigned int, VkFence_T* const*, VkResult):46)
vulkan_layer_chassis::ResetFences(VkDevice_T*, unsigned int, VkFence_T* const*) (@vulkan_layer_chassis::ResetFences(VkDevice_T*, unsigned int, VkFence_T* const*):105)
----- Application Code -----
```

**Environment:**
 - OS: macOS Monterey
 - GPU: Integrated
 - SDK or header version if building from repo: 1.3.231.1, 1.3.236.0
 - Options enabled (synchronization, best practices, etc.): 

**Additional context**
Everything works fine with SDK 1.3.204.1.

Also, to make sure I wasn't doing something wrong, right after creating a logical device, I create a fence and reset it and it crashes right. The same code is working fine on my windows machine. 

I am quite new to vulkan, so it is entirely possible that I am doing something wrong!

**Comment by juan-lunarg** [comment]
Looks like we have a test case that covers this scenario:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/081dc9e60fb4dad6adc63a438789f8f7f4d85d2e/tests/positive/sync.cpp#L342-L352

Could you try running this test? It runs fine on my machine. If not we might not need more information for a repro / test case to prevent this in the future.

FYI @jeremy-lunarg looks like the exception is coming from `FENCE_STATE::Reset()`

```
__cxa_throw (@__cxa_throw:3)
std::exception_ptr std::make_exception_ptr<std::__1::future_error>(std::__1::future_error) (@std::exception_ptr std::make_exception_ptr<std::__1::future_error>(std::__1::future_error):29)
std::__1::promise<void>::~promise() (@std::__1::promise<void>::~promise():31)
FENCE_STATE::Reset() (@FENCE_STATE::Reset():28)
```

**Comment by in0x** [comment]
I believe I'm running into the same issue, getting a crash on the same callstack as the theunwisewolf after upgrading my SDK.
**OS**: macOS Ventura 13.1
**GPU**: M1 Pro (ARM M1 Mac 14-inch)
**SDK version**: 1.3.236.0

I only get the crash with validation layers enabled. I've also isolated it to something specific, I only get the crash on the first `vkResetFences` if I create the fence in signaled state. If I don't create the fence signaled, everything behaves as expected. For what I'm referencing specifically please see: https://github.com/in0x/editor/blob/master/src/main.cpp#L782. The linked repo should be cloneable and buildable on mac if you would like to try a repro. `make` && `./editor.app/Contents/MacOS/editor` should do it, though no promises as I've never tried to run this on another machine. As a final data point, I've attached a save from the caps viewer.

**Comment by in0x** [comment]
Also if I get a chance I'll try running the test you linked. Should I just set up the minimal vulkan state and then replicate the test's code, or is there a mechanism to actually run this test locally on my machine?

**Comment by juan-lunarg** [comment]
> Also if I get a chance I'll try running the test you linked. Should I just set up the minimal vulkan state and then replicate the test's code, or is there a mechanism to actually run this test locally on my machine?

First you'll need to build the validation layers:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/BUILD.md

Should be as simple as
```
cmake -B build --preset dev
cmake --build build/
```

Then you should be able to run the tests:
```
./build/tests/vk_layer_validation_tests --gtest_filter=VkPositiveLayerTest.ResetUnsignaledFence
```

**Comment by in0x** [comment]
Following your instructions I get the following output from the test. Interesting as I had to enable the portability extension as well when upgrading to the version that now crashes:
`philwelsch@phils-macbook-pro Vulkan-ValidationLayers % ./build/tests/vk_layer_validation_tests --gtest_filter=VkPositiveLayerTest.ResetUnsignaledFence
Note: Google Test filter = VkPositiveLayerTest.ResetUnsignaledFence
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from VkPositiveLayerTest
[ RUN      ] VkPositiveLayerTest.ResetUnsignaledFence
/Users/philwelsch/Code/Vulkan-ValidationLayers/tests/vkerrormonitor.cpp:106: Failure
Failed
Validation Error: [ VUID-VkDeviceCreateInfo-pProperties-04451 ] Object 0: handle = 0x600003e660e0, type = VK_OBJECT_TYPE_PHYSICAL_DEVICE; | MessageID = 0x3a3b6ca0 | vkCreateDevice: VK_KHR_portability_subset must be enabled because physical device VkPhysicalDevice 0x600003e660e0[] supports it The Vulkan spec states: If the VK_KHR_portability_subset extension is included in pProperties of vkEnumerateDeviceExtensionProperties, ppEnabledExtensionNames must include "VK_KHR_portability_subset" (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkDeviceCreateInfo-pProperties-04451)
/Users/philwelsch/Code/Vulkan-ValidationLayers/tests/vktestbinding.cpp:299: Failure
Failed
Assertion: `vk::CreateDevice(phy_.handle(), &info, __null, &dev) == VK_SUCCESS'
zsh: abort      ./build/tests/vk_layer_validation_tests`

**Comment by in0x** [comment]
Following your instructions I get the following output from the test. Interesting as I had to enable the portability extension as well when upgrading to the version that now crashes:
```
Vulkan-ValidationLayers % ./build/tests/vk_layer_validation_tests --gtest_filter=VkPositiveLayerTest.ResetUnsignaledFence 
Note: Google Test filter = VkPositiveLayerTest.ResetUnsignaledFence 
[==========] Running 1 test from 1 test suite. 
[----------] Global test environment set-up. 
[----------] 1 test from VkPositiveLayerTest 
[ RUN      ] VkPositiveLayerTest.ResetUnsignaledFence 
/Users/philwelsch/Code/Vulkan-ValidationLayers/tests/vkerrormonitor.cpp:106: Failure 
Failed 
Validation Error: [ VUID-VkDeviceCreateInfo-pProperties-04451 ] Object 0: handle = 0x600003e660e0, type = VK_OBJECT_TYPE_PHYSICAL_DEVICE; | MessageID = 0x3a3b6ca0 | vkCreateDevice: VK_KHR_portability_subset must be enabled because physical device VkPhysicalDevice 0x600003e660e0[] supports it The Vulkan spec states: If the VK_KHR_portability_subset extension is included in pProperties of vkEnumerateDeviceExtensionProperties, ppEnabledExtensionNames must include "VK_KHR_portability_subset" (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkDeviceCreateInfo-pProperties-04451) 
/Users/philwelsch/Code/Vulkan-ValidationLayers/tests/vktestbinding.cpp:299: Failure 
Failed Assertion: vk::CreateDevice(phy_.handle(), &info, __null, &dev) == VK_SUCCESS'
zsh: abort ./build/tests/vk_layer_validation_tests
```

**Comment by juan-lunarg** [comment]
Device creation is failing. You'll need to modify the test to go further. See `TEST_F(VkPositiveLayerTest, ExportMetalObjects)` as an example for adding the appropriate extensions.

**Comment by in0x** [comment]
Sure I'll try that. I didn't initially as I assumed that the test suite would do so if needed, does that mean that not all of your tests get run on all platforms by default?

**Comment by in0x** [comment]
Modified the particular test to include the portability extension and it passes now. Though considering what I found about the crash seemingly being related to reseting fences that get created signaled, and this test is about reseting on unsignaled ones I'm not sure that's saying too much

**Comment by ncesario-lunarg** [comment]
Looks like the exception is triggered at https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/cb16c644dee18b4fb124d45f4efcea64837f728b/layers/queue_state.cpp#L300.

This would seem to indicate that the result of the promise is in a "pending" or "not ready" state. I'm not sure why this would be, but we should probably be making some sort of assert that the result of the promise is not in any sort of pending state (@jeremyg-lunarg)?

**Comment by theunwisewolf** [comment]
Apologies for the late reply. I was not able to run the Validation layers test code out of the box, had to make some changes to the code. Anyways, I got the fence test running and it passed. 

I tried using the same extensions (at all levels) as used in the validation tests.

**Comment by theunwisewolf** [comment]
I am closing this issue as this does not seem to be related to anything in the Validation Layers.
