### ISSUE TITLE
Validation layer crashes in vkCmdEndDebugUtilsLabelEXT when labels are split across command buffers

### ISSUE THREAD

**Issue by JordanLogan-AMD** [KhronosGroup/Vulkan-ValidationLayers#498]
When a label is split across command buffers with the start label being in a different command buffer then the end label, the validation layer will crash when calling vkCmdEndDebugUtilsLabelEXT. The crash is due to popping an empty queue in EndCmdDebugUtilsLabel.

**Comment by jzulauf-lunarg** [comment]
Should absolutely be supported:

> An application may open a debug label region in one command buffer and close it in another, or otherwise split debug label regions across multiple command buffers or multiple queue submissions.

**Comment by jzulauf-lunarg** [comment]
There's a narrowly scoped fix to avoid the crash and provide reasonable support within a given command buffer.  The CB spanning behavior is a tougher nut by far, and should be opened/tracked as a separate issue.

**Comment by jzulauf-lunarg** [comment]
Crash should be be fixed in above PR.
