### ISSUE TITLE
#4923 seems to introduce a false positive in cmd_buffer_state.cpp

### ISSUE THREAD

**Issue by Kangz** [KhronosGroup/Vulkan-ValidationLayers#4981]
CC @jeremy-lunarg explicitly for #4923

**Describe the Issue**
We started to see flaky failure on Dawn's continuous testing that look weird because the regression range looks like it doesn't contain any commit changing the validation, and Dawn is pretty conservative in how it reuses descriptor sets. See https://bugs.chromium.org/p/dawn/issues/detail?id=1615

Reproducing locally, it seems that reverting the commit in #4923 fixes the flaky behavior, however I can't make sense of the logic there so I'm not able to root cause the issue further. Given the issue is very flaky, could it be that somehow maps store pointers that get reallocated somehow?

Any pointers on how to help debug this further?

**Valid Usage ID**
If applicable, please include the validation messages encountered leading up to the issue
> Validation Error: [ VUID-vkUpdateDescriptorSets-None-03047 ] Object 0: handle = 0x62440000006244, name = DawnDbg=3;Dawn_BindGroup, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0x35d7ea98 | vkUpdateDescriptorSets() pDescriptorWrites[0] failed write update validation for VkDescriptorSet 0x62440000006244[DawnDbg=3;Dawn_BindGroup] with error: Cannot call vkUpdateDescriptorSets() to perform write update on VkDescriptorSet 0x62440000006244[DawnDbg=3;Dawn_BindGroup] allocated with VkDescriptorSetLayout 0x61950000006195[DawnDbg=3;Dawn_BindGroupLayout] that is in use by a command buffer. The Vulkan spec states: Descriptor bindings updated by this command which were created without the VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT or VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT bits set must not be used by any command that was recorded to a command buffer which is in the pending state (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkUpdateDescriptorSets-None-03047)

**Environment:**
 - OS: Linux but also reproduces on Windows
 - GPU: Nvidia (couldn't repro with Switshader)
 - SDK or header version if building from repo: ToT (df33af3b2276fce856e74950d4bd1ed93a92c962)
 - Options enabled (synchronization, best practices, etc.): Only the default.

**Additional context**

**Comment by jeremyg-lunarg** [comment]
Thanks, I can reproduce this problem locally. I've been investigating a similar problem with a massive game trace and this test should be much easier to figure out.
