### ISSUE TITLE
VkGpuAssistedLayerTest.GpuBufferDeviceAddressOOB hangs on VK_ERROR_DEVICE_LOST

### ISSUE THREAD

**Issue by lunarpapillo** [KhronosGroup/Vulkan-ValidationLayers#4983]
Sometimes the `VkGpuAssistedLayerTest.GpuBufferDeviceAddressOOB` provokes an error:
```
[ RUN      ] VkGpuAssistedLayerTest.GpuBufferDeviceAddressOOB
C:\j\vz3\Release32\Vulkan-ValidationLayers\tests\vklayertests_gpu.cpp(1151): error: Expected equality of these values:
  VK_SUCCESS
    Which is: 0
  resolved_err
    Which is: -4
VK_ERROR_DEVICE_LOST
```
I have only seen this error appear on suspect drivers, but I believe that the driver can throw `VK_ERROR_DEVICE_LOST` at any time and the test should be able to manage it gracefully.

At a minimum, the test should fail gracefully when the error is returned; this would be far better than hanging forever.

Ideally, the test case should attempt to recover, re-initializing the device and attempting the test again, a limited number of times before giving up and failing gracefully.

**Comment by spencer-lunarg** [comment]
How was this different than https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4967 ?

**Comment by lunarpapillo** [comment]
#4967 is a driver issue.  This issue is intended to be a test enhancement issue.

**Comment by jeremyg-lunarg** [comment]
It looks like we're ready consider this fixed and reenable the test in CI.

**Comment by lunarpapillo** [comment]
It's not fixed.

**Comment by lunarpapillo** [comment]
Out of 16 runs since the blacklist was "fixed", four of the `Release32` runs aborted on `VkGpuAssistedLayerTest.GpuBufferDeviceAddressOOB`, e.g.: http://erusea:8080/job/Vulkan-ValidationLayers/10668/BITS=32,BUILD_MODE=Release,USE_ROBIN_HOOD_HASHING=OFF,label=tcwinnvi2/artifact/vulkantest-results/execution-logs/008-vk_layer_validation_tests-stdout.txt
```
        [ RUN      ] VkGpuAssistedLayerTest.GpuBufferDeviceAddressOOB
C:\j\vz2\Release32\Vulkan-ValidationLayers\tests\vklayertests_gpu.cpp(1136): error: Expected equality of these values:
          VK_SUCCESS
            Which is: 0
          resolved_err
            Which is: -4
        VK_ERROR_DEVICE_LOST
```

**Comment by lunarpapillo** [comment]
The same issue appears with `PositiveGpuAssistedLayer.GpuBufferDeviceAddress` on recent runs (I'm not sure whether it was a test name change or a different test):  http://erusea:8080/job/Vulkan-ValidationLayers/12543/BITS=32,BUILD_MODE=Release,label=tcwinnvi2/console
```
INFO: executing #6: C:\j\vz5\Release32\Vulkan-ValidationLayers\build32\tests\Release\vk_layer_validation_tests.exe --gtest_catch_exceptions=0 --gtest_filter=-PositiveCommand.ThreadedCommandBuffersWithLabels:VkPositiveLayerTest.QueueThreading:NegativeCommand.SecondaryCommandBufferRerecordedExplicitReset:NegativeCommand.SecondaryCommandBufferRerecordedNoReset:NegativeSyncVal.CopyOptimalImageHazards:NegativeViewportInheritance.BasicUsage:NegativeViewportInheritance.MultiViewport:PositiveSyncObject.WaitTimelineSemThreadRace:VkPositiveGraphicsLibraryLayerTest.NotAttachmentDynamicBlendEnable:PositiveGraphicsLibrary.NotAttachmentDynamicBlendEnable:VkGpuAssistedLayerTest.GpuBufferDeviceAddressOOB:VkVideoLayerTest.*:VkPositiveVideoLayerTest.*
Build timed out (after 60 minutes). Marking the build as aborted.
Build was aborted
Archiving artifacts
Finished: ABORTED
```
http://erusea:8080/job/Vulkan-ValidationLayers/12543/BITS=32,BUILD_MODE=Release,label=tcwinnvi2/artifact/vulkantest-results/execution-logs/006-vk_layer_validation_tests-stdout.txt
```
[ RUN      ] PositiveGpuAssistedLayer.GpuBufferDeviceAddress
C:\j\vz5\Release32\Vulkan-ValidationLayers\tests\unit\gpu_av_positive.cpp(354): error: Expected equality of these values:
  VK_SUCCESS
    Which is: 0
  resolved_err
    Which is: -4
VK_ERROR_DEVICE_LOST
```
As before, when this occurs, the test should exit with a non-zero exit code.  What's happening instead is that the test hangs forever, which causes Jenkins to eventually abort the test, and then causes subsequent runs in the same workspace to fail with:
```
ERROR: Cannot delete workspace: remote file operation failed: C:\j\vz5\Release32 at hudson.remoting.Channel@1017569:tcwinnvi2: java.io.IOException: Unable to delete 'C:\j\vz5\Release32\Vulkan-ValidationLayers\build32\layers\Release\VkLayer_device_profile_api.dll'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
```
until someone recognizes the problem and goes and manually cleans up the machine.

**Comment by Tony-LunarG** [comment]
PositiveGpuAssistedLayer.GpuBufferDeviceAddress is a new test.  It does a QueueWaitIdle as the last call of the test, and asserts when it gets DEVICE_LOST.  It doesn't do anything else but teardown and Vulkan object destroys, so maybe something is happening there.
