### ISSUE TITLE
Update swapchain VUs changed from VK_EXT_swapchain_maintenance1

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/Vulkan-ValidationLayers#4985]
With `VK_EXT_swapchain_maintenance1` added in the 1.3.237 headers the `VUID-vkAcquireNextImage2KHR-swapchain-01803` / `VUID-vkAcquireNextImageKHR-swapchain-01802` were slightly altered to `VUID-vkAcquireNextImage2KHR-surface-07784` / `VUID-vkAcquireNextImageKHR-surface-07783` with the new [swapchain forward progress](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#swapchain-acquire-forward-progress) language

This VU checked should be updated correctly

**Comment by mark-lunarg** [comment]
PR #5000.

**Comment by juan-lunarg** [comment]
FWIW a follow up creating positive tests would be great to have as well. Since that can help catch issues otherwise not found

EX:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4906

A separate issue for that can be made though.
