### ISSUE TITLE
VUID-VkGraphicsPipelineCreateInfo-renderPass-06061 firing when pipeline libraries are enabled

### ISSUE THREAD

**Issue by charlie-ht** [KhronosGroup/Vulkan-ValidationLayers#4989]
**Describe the Issue**

While running `dEQP-VK.pipeline.pipeline_library.multisample.shader_fragment_mask.samples_8.subpass_input.r32_uint`, I recieve the following validation error,

```
Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-renderPass-06061 ] Object 0: handle = 0x1426c490, type = VK_OBJECT_TYPE_DEVICE; | Me
ssageID = 0x399b0a5e | vkCreateGraphicsPipelines(): pCreateInfos[0] is being created with fragment shader state and renderPass = VK_NULL_HANDLE, but fragme
nt shader includes InputAttachment capability. The Vulkan spec states: If the pipeline is being created with fragment shader state and renderPass is VK_NUL
L_HANDLE, fragment shaders in pStages must not include the InputAttachment capability (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vk
spec.html#VUID-VkGraphicsPipelineCreateInfo-renderPass-06061)
```

However, the branch reporting this does not seem to be taking into account the fact pipeline libraries are enabled in this test. I suspect it can simply be flagged out in that case, since the create info doesn't contain a render pass for this case.

**Valid Usage ID**
VUID-VkGraphicsPipelineCreateInfo-renderPass-06061

**Environment:**
 - OS:  Linux
 - GPU: AMD Radeon RX 6700 XT
 - SDK or header version if building from repo:
   - Validation layers SHA: `a54a9aaab3da831ff692193d30cc90f272714b57`
 - Options enabled (synchronization, best practices, etc.):  VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT

**Additional context**

**Comment by spencer-lunarg** [comment]
sorry for delay on this... so yes, can reproduce it, seems a few other VUs in the `VkGraphicsPipelineCreateInfo` rely on "shaders in `pStages`" but we are currently at the linking pipeline, using the  accumulation of stages which is wrong
