### ISSUE TITLE
Add check for memory object backing bufferView & Image descriptor updates

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#50]
**Issue by [tobine](https://github.com/tobine) (MIGRATED)**
_Wednesday Oct 11, 2017 at 15:30 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2126_

----

In VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER and VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER cases we need to make sure that if the memory backing the buffer is destroyed, that we flag an error. Definitely need to check at Draw time (which we already do for other buffer updates) but could also check this at update time.
It also appears that we don't verify backing memory for image updates. Need all of these checks.

**Comment by tobine** [comment]
triage notes:For the TEXEL_BUFFER cases I believe these checks are still missing. They could be added to cvdescriptorset::DescriptorSet::ValidateDrawState() function in descriptor_sets.cpp. Backing image memory check for image descriptors used in draw also appears to still be missing and could be added in that same function.

**Comment by locke-lunarg** [comment]
[pull #847 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/847)
