### ISSUE TITLE
Missing validation for structs in pNext chains whose device extensions aren't supported by the device

### ISSUE THREAD

**Issue by charles-lunarg** [KhronosGroup/Vulkan-ValidationLayers#5012]
**Describe the situation in which you encountered the missing validation**
The current validation for pNext chains only verifies that they do not contain structs which never go in the chain. For example, a properties struct in a features chain (ex: VUID-VkDeviceCreateInfo-pNext-pNext). But what they don't check is whether the structs corresponding extension is supported by the implementation.

Real world use-case: If an application adds `VkPhysicalDevicePortabilitySubsetFeaturesKHR` to the pNext chain of vkGetPhysicalDeviceFeatures2 on a device that doesn't support the portability subset extension, the implementation is required to skip the struct. However, the application uses the feature flags in that struct to determine what is or isn't supported, and since it was skipped, every field will be false. (assuming the user default initialized the struct).

**Valid Usage IDs requested**
This doesn't have specific VUID's, rather it is generic spec language. New VUID's may be required, though best practices checks may be better fit.

**Additional Context**
[Vulkan Spec 3.7.2](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap3.html#fundamentals-implicit-validity)
> Any component of the implementation (the loader, any enabled layers, and drivers) must skip over, without processing (other than reading the sType and pNext members) any extending structures in the chain not defined by core versions or extensions supported by that component.

This bit of the spec states that unsupported structs should simply be skipped by layers/drivers. The language is imprecise (many discussion have been had about what 'supported' means and more specific VUID's like VUID-VkDeviceCreateInfo-pNext-pNext actually go against that rule. I think changing this bit of the spec or adding conditions to the 'skip over it' would be beneficial. 

I should say it makes sense to have this bit in the spec, as when a layer or driver gets a struct in a pnext chain that it doesn't know about, the component should ignore it. This happens quite a bit with older components not updated to the latest version.

**Comment by billhollings** [comment]
> I think changing this bit of the spec or adding conditions to the 'skip over it' would be beneficial.

Agreed. I think in the final spec for the `VK_KHR_portability_subset` extension, we could modify the spec text to add something like:

> An exception to this is the `VkPhysicalDevicePortabilitySubsetFeaturesKHR` structure, which must not be submitted in the `pNext` chain of `VkPhysicalDeviceFeatures2` if the `VK_KHR_portability_subset` extension is not supported by the physical device.

along with an appropriate VUID defined in the description of `VkPhysicalDeviceFeatures2`.
