### ISSUE TITLE
Getting "Invalid SurfaceKHR" when creating swapchain

### ISSUE THREAD

**Issue by stanlo** [KhronosGroup/Vulkan-ValidationLayers#502]
When trying to create a swapchain I get the following message: 
`INFO: Invalid SurfaceKHR Object 0x2. The Vulkan spec states: surface must be a valid VkSurfaceKHR handle (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkSwapchainCreateInfoKHR-surface-parameter)`

It starts occuring in this change: https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/c3ff7a9ae3f4119fc86aee08f4c8ecf4aed874f4

It is probably due to the code here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/c3ff7a9ae3f4119fc86aee08f4c8ecf4aed874f4#diff-3f3de3036469dc2c34e6ecd25ca43011R759

It appears that it uses the wrong validation function for pCreateInfo->surface. The surface would have been created by a VkInstance, however, create swapchain is a device function. Thus it looks in the wrong set of objects for surface, and thinks it was never created.

**Comment by mark-lunarg** [comment]
This will be fixed by #500.

**Comment by mark-lunarg** [comment]
Pushed to Master.  @stanlo, good catch, please let us know if you see other issues with this layer.  Thanks!
