### ISSUE TITLE
Enhance layers validation in Dynamic Rendering suspend and resume for secondary command buffers.

### ISSUE THREAD

**Issue by marfre02-ARM** [KhronosGroup/Vulkan-ValidationLayers#5033]
An enhancement is required to the layers checking for Dynamic Rendering scenarios as the current implementation does not take into account the use of secondary command buffers.

VUIDs affected are,

VUID-VkSubmitInfo-pCommandBuffers-06014
VUID-VkSubmitInfo-pCommandBuffers-06016
VUID-VkSubmitInfo-pCommandBuffers-06193

This pull request proposes an appropriate code change 9b9a0aef
A supporting set of tests that show the issue can be found in this pull request 28cdb58f

**Comment by spencer-lunarg** [comment]
@marfre02-ARM were you planning to make an actual PR with the code changes and 2 tests? (or did you want me to take the commits and make the change on your behalf?)

**Comment by marfre02-ARM** [comment]
Forgive me @spencer-lunarg I wasn't sure I had permission to create a pull-request on the main base code from my fork.
Please find proposed PRs for code #5048 and tests #5049.

**Comment by marfre02-ARM** [comment]
Have merged #5049 into #5048 to create a single PR with both code and tests.

**Comment by marfre02-ARM** [comment]
#5048 is merged now.
Thanks @spencer-lunarg @ncesario-lunarg for the help!
