### ISSUE TITLE
Layers fail to recognize enums from VK_EXT_conditional_rendering 

### ISSUE THREAD

**Issue by scyganINTEL** [KhronosGroup/Vulkan-ValidationLayers#507]
It seems layers fails to recognize `VK_PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT` as valid pipeline stage. 

Consider an application with following subpass self-dependency in renderpass:

```
VkSubpassDependency                      dependency =
       {
              0,                                                            //deUint32                  srcSubpass;
              0,                                                            //deUint32                  dstSubpass;
              VK_PIPELINE_STAGE_VERTEX_SHADER_BIT,                          //VkPipelineStageFlags       srcStageMask;
              VK_PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT,              //VkPipelineStageFlags       dstStageMask;
              VK_ACCESS_SHADER_WRITE_BIT,                                   //VkAccessFlags             srcAccessMask;
              VK_ACCESS_CONDITIONAL_RENDERING_READ_BIT_EXT,                 //VkAccessFlags             dstAccessMask;
              (VkDependencyFlags)0                                          //VkDependencyFlags         dependencyFlags;
       };

```

When barriers are executed from such subpass, layers spuriously emit following errors:

> VUID-VkRenderPassCreateInfo-pDependencies-00838(ERROR / SPEC): msgNum: 0 - Dependency 0 specifies a destination stage mask that contains stages not in the GRAPHICS pipeline as used by the destination subpass 0. The Vulkan spec states: For any element of pDependencies, if the dstSubpass is not VK_SUBPASS_EXTERNAL, all stage flags included in the dstStageMask member of that dependency must be a pipeline stage supported by the pipeline identified by the pipelineBindPoint member of the source subpass. (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkRenderPassCreateInfo-pDependencies-00838)

> VUID-vkCmdPipelineBarrier-pDependencies-02285(ERROR / SPEC): msgNum: 0 - vkCmdPipelineBarrier(): Barriers cannot be set during subpass 0 of renderPass 0xb with no self-dependency specified. The Vulkan spec states: If vkCmdPipelineBarrier is called within a render pass instance, the render pass must have been created with at least one VkSubpassDependency instance in VkRenderPassCreateInfo::pDependencies that expresses a dependency from the current subpass to itself, and for which srcStageMask contains a subset of the bit values in VkSubpassDependency::srcStageMask, dstStageMask contains a subset of the bit values in VkSubpassDependency::dstStageMask, dependencyFlags is equal to VkSubpassDependency::dependencyFlags, srcAccessMask member of each element of pMemoryBarriers and pImageMemoryBarriers contains a subset of the bit values in VkSubpassDependency::srcAccessMask, and dstAccessMask member of each element of pMemoryBarriers and pImageMemoryBarriers contains a subset of the bit values in VkSubpassDependency::dstAccessMask (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdPipelineBarrier-pDependencies-02285)

The problem seems to be in following code snippet, not recognizing `VK_PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT` as pipeline stage: 

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/sdk-1.1.92/layers/core_validation.cpp#L8914
```
// Note that we only check bits that HAVE required queueflags -- don't care entries are skipped
static std::unordered_map<VkPipelineStageFlags, VkQueueFlags> supported_pipeline_stages_table = {
    {VK_PIPELINE_STAGE_COMMAND_PROCESS_BIT_NVX, VK_QUEUE_GRAPHICS_BIT | VK_QUEUE_COMPUTE_BIT},
    {VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT, VK_QUEUE_GRAPHICS_BIT | VK_QUEUE_COMPUTE_BIT},
    {VK_PIPELINE_STAGE_VERTEX_INPUT_BIT, VK_QUEUE_GRAPHICS_BIT},
    {VK_PIPELINE_STAGE_VERTEX_SHADER_BIT, VK_QUEUE_GRAPHICS_BIT},
    {VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT, VK_QUEUE_GRAPHICS_BIT},
    {VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT, VK_QUEUE_GRAPHICS_BIT},
    {VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT, VK_QUEUE_GRAPHICS_BIT},
    {VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT, VK_QUEUE_GRAPHICS_BIT},
    {VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT, VK_QUEUE_GRAPHICS_BIT},
    {VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT, VK_QUEUE_GRAPHICS_BIT},
    {VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT, VK_QUEUE_GRAPHICS_BIT},
    {VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, VK_QUEUE_COMPUTE_BIT},
    {VK_PIPELINE_STAGE_TRANSFER_BIT, VK_QUEUE_GRAPHICS_BIT | VK_QUEUE_COMPUTE_BIT | VK_QUEUE_TRANSFER_BIT},
    {VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT, VK_QUEUE_GRAPHICS_BIT}};

```

**Comment by jzulauf-lunarg** [comment]
Triage notes:  A targeted narrow fix could be done by updating (or automating) the valid bits table.  That's probably desirable. 

Note that outside of code-generated validation, there appears to be no support for `VK_EXT_conditional_rendering` within the layers, noting the limited `DeviceExtensions::vk_ext_conditional_rendering` uses, and the lack of "interceptors" for CmdBeginConditionalRendering et. al. within the layers subdir, so this is the tip of a large incomplete iceberg.

@scyganINTEL -- is there a prioritized set of validation coverage that your application needs for ConditionalRendering, or is the priority simply silencing the false positive?

**Comment by scyganINTEL** [comment]
This is from Vulkan CTS, caught in review of new test. Probably silencing it for now is enough.

**Comment by locke-lunarg** [comment]
I ran `dEQP-VK.conditional_rendering.* in vulkan-cts-1.1.5 and Vulkan SDK 1.1.121`. I don't see those two error messages.

`VUID-VkRenderPassCreateInfo-pDependencies-00838` should be solved because `VK_PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT `is checked in `ValidateSubpassGraphicsFlags() of stateless_validation.h`.

`VUID-vkCmdPipelineBarrier-pDependencies-02285` message says `no self-dependency specified` but both of your `srcSubpass and dstSubpass` are 0 in `VkSubpassDependency`. It should be fine, and the validation isn't related to `VK_PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT `. The issue should be some other reasons, but it looks solved.
