### ISSUE TITLE
Make VkLayer_utils API separate and publicly available.

### ISSUE THREAD

**Issue by tomilov** [KhronosGroup/Vulkan-ValidationLayers#5073]
**Describe the Issue**
It is often needed to get pixel size for specific `VkFormat`.
There are projects which need to build validation layers to get `vk_format_utils.h` and `VkLayer_utils` library only for just `FormatElementSize` function.

**Additional context**
Examples:
 - [SPIRV-Reflect](https://github.com/KhronosGroup/SPIRV-Reflect/blob/de6e7cc2408122eca0a2af230e0ce60b1a257d02/examples/main_io_variables.cpp#L11)
 - [Sascha Willems](https://github.com/SaschaWillems/Vulkan/blob/a2a604be473c829763854ffb34f7978bc0358afb/external/ktx/lib/vk_format.h#L850)
 - [nvpro](https://github.com/nvpro-samples/vk_video_samples/blob/de54a1df626828c47e265c65d6676a3f083809a1/vk_video_decoder/libs/VkCodecUtils/pattern.cpp#L155)
 -  [glTF-IBL-Sampler](https://github.com/KhronosGroup/glTF-IBL-Sampler/blob/27f58c6839b20ce3974967e17a94cf7373c7c82f/lib/source/format.cpp#L5)
 - [testing suite](https://github.com/KhronosGroup/VK-GL-CTS/blob/071bfca11aa9fdad2643437667b5d1d615919854/external/vulkancts/modules/vulkan/pipeline/vktPipelineVertexUtil.cpp#L37)
 - etc
 
Almost every project contains such a code.
We need to solve the problem

**Comment by spencer-lunarg** [comment]
`vk_format_utils` is all generated from the XML and in theory anyone could do it themselves.

**Comment by spencer-lunarg** [comment]
The validation layers use `FormatElementSize` for what we need, but other repos might want something slightly different, I think it might be of better use to have a nice "how to make your own format utils from the header" document instead

**Comment by tomilov** [comment]
> it might be of better use to have a nice "how to make your own format utils from the header" document
I totally agree. I tried to figure out the codegen, but failed.

**Comment by spencer-lunarg** [comment]
> I tried to figure out the codegen, but failed.

I think that is how everyone feels about the state of the codegen code right now 😆

It is on my todo list(towards the top!)  to both cleanup the codegen logic and also write up a "how to do your own" blog/post somewhere.

**Comment by tomilov** [comment]
> a "how to do your own" blog/post

I will be one of the first grateful users.
To be specific, I stucked on `GeneratorOptions`. Where is its origin?

**Comment by juan-lunarg** [comment]
closing in favor of:
https://github.com/KhronosGroup/Vulkan-Docs/issues/2059

**Comment by juan-lunarg** [comment]
FYI @tomilov vk_format_utils.h is now a proper deliverable.

See https://github.com/KhronosGroup/Vulkan-Utility-Libraries

If you see anything else you want from VVL in the utility libraries let us know.

**Comment by tomilov** [comment]
@juan-lunarg Thank you!
