### ISSUE TITLE
Crash in CoreChecks::ValidateAllocateDescriptorSets when allocating mixed descriptor sets with and without variable descriptor count.

### ISSUE THREAD

**Issue by CarloWood** [KhronosGroup/Vulkan-ValidationLayers#5074]
When allocating descriptor sets with `vkAllocateDescriptorSets` passing a `VkDescriptorSetAllocateInfo` that has a `VkDescriptorSetVariableDescriptorCountAllocateInfo` in its `.pNext` chain, the function `CoreChecks::ValidateAllocateDescriptorSets` calls `layout->GetMaxBinding()` on every layout that is being allocated. If one such layouts does not have any binding at all, then causes a crash because `GetMaxBinding()` accesses `bindings_[bindings_.size() - 1].binding`, aka index -1 of an empty vector.

Of course, a layout that has a variable descriptor count will have at least one binding, but I believe that the spec allows allocating both, descriptor sets with and without variable descriptor count in one call; hence there can be a layout with `VkDescriptorSetLayoutCreateInfo::bindingCount` set to zero (which is allowed by the spec).

In the description of `VkDescriptorSetAllocateInfo`, the spec (1.3) says:

    "If descriptorSetCount is zero or this structure is not included in the pNext chain, then the variable lengths are considered to be zero."

from which I conclude that it is allowed to have non-zero `descriptorSetCount` and set the variable lengths to zero oneself.
More important, the spec then continuous with:

    "If VkDescriptorSetAllocateInfo::pSetLayouts[i] does not include a variable-sized descriptor binding, then pDescriptorCounts[i] is ignored."

where `i` is supposedly to iterate over all/any descriptor set being allocated. If there is a set layout with no bindings, and therefore no variable length descriptors, then crashing on a value of zero in `pDescriptorCounts[i]` is not what I'd call ignoring it ;)

**Comment by CarloWood** [comment]
Hi @spencer-lunarg  - please note that I'm not totally convinced anymore that the specs say this should be supported. That is, I'd think so (see above) but when I changed the mentioned code in the validation layers to not crash (not access index -1), the result was a crash in the libnvidia; of course I don't know WHY it crashed, but it is possible that they simply don't support it. Whether that is a bug in their library (or driver) I don't know, but it might be a good idea to double check with others what the consensus is on the correct behavior in this case (aka, what the spec REALLY says about this case).

**Comment by spencer-lunarg** [comment]
@CarloWood thanks for the follow up/concern! If this is actually a Validation Layer bug we still want to fix it, but if it is a driver/spec issue we will move it to the correct repo instead.

**Comment by CarloWood** [comment]
Something will have to be changed in the Validation Layer either way. Either you allow non-variable descriptor count descriptors with zero bindings during an allocation mixed with  variable descriptor count descriptors, i.e. avoid the access of index -1 in that case. Or you figure this is not supported by the specs and then also avoid the crash due to index -1 access, but instead print some validation error that this is not allowed.

**Comment by spencer-lunarg** [comment]
So **FINALLY** got back to look at this

This issue is very related to https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8065

and the issue is we were not checking for zero binding when calling `GetMaxBinding()` as pointed out

but it was discussed in https://gitlab.khronos.org/vulkan/vulkan/-/issues/3890 recently that `vkAllocateDescriptorSets` should not be allowed on zero-binding sets, so there is going to be a new VU checking this (but added https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8178 as extra good measures)
