### ISSUE TITLE
`AttachmentTracker::subpass_attachment_layout` never gets updated

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-ValidationLayers#5080]
In render_pass_state.cpp, in `AttachmentTracker::Update`, the variable `subpass_attachment_layout` is used to determine whether to insert a layout transition from a previous subpass to the current one, but only if the stored layout is not `kInvalidLayout`. In the constructor, this variable is initialised to contain `kInvalidLayout` for every subpass+attachment combination. But the stored value is then never updated, so the value stays at `kInvalidLayout`, which means that no layout transition ever gets added between the subpasses.

**Comment by arno-lunarg** [comment]
Hi @Rua, thank you for spotting this! To potentially have some more details, did you notice something break because of this bug?
