### ISSUE TITLE
Incorrect VUID-vkUpdateDescriptorSets-None-03047 validator error when using vkUpdateDescriptorSets before calling vkResetCommandBuffer

### ISSUE THREAD

**Issue by thatcosmonaut** [KhronosGroup/Vulkan-ValidationLayers#5090]
**Describe the Issue**
In my application, when we bind descriptor sets we attach them to some internal tracking so those descriptor sets can be reused after the command buffer has finished executing. When submitting new command buffers, we check the fences of pending command buffers to see if our tracking state can be cleaned up and the command buffers reused. At this time, we return the descriptor sets to our internal cache for reuse. However, we were not calling vkResetCommandBuffer until we acquired the command buffer for reuse. This caused the validator layer to give us VUID-vkUpdateDescriptorSets-None-03047 errors if a descriptor set was reused before vkResetCommandBuffer was called, even though the command buffer had already finished executing. 

The spec states: 

> The contents of a descriptor set binding must not be altered (overwritten by an update command, or freed) between the first point in time that it may be consumed, and when the command completes executing on the queue... Once all pending uses have completed, it is legal to update and reuse a descriptor set.

Thus, updating a descriptor set that was bound in a command buffer appears to be valid usage as long as the command buffer has finished executing, it shouldn't matter if the command buffer was reset or not. I changed the behavior in my application because the reset timing didn't matter much for us anyway, but I don't think this error is in line with the spec. 

**Valid Usage ID**
VUID-vkUpdateDescriptorSets-None-03047

**Environment:**
 - OS: Windows 10
 - GPU: Radeon RX5600XT
 - SDK or header version if building from repo: 1.3.236.0
 - Options enabled (synchronization, best practices, etc.): Standard validation

**Additional context**

**Comment by jeremyg-lunarg** [comment]
Can you please try the latest code, I [fixed a problem with this VUID](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4994) a few weeks ago.

**Comment by thatcosmonaut** [comment]
Wasn't able to build the SDK myself but I just tried 1.3.239.0 and the issue is fixed on my end.
