### ISSUE TITLE
Handle mask validation for multiple subpass self-dependencies

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#51]
**Issue by [tobine](https://github.com/tobine) (MIGRATED)**
_Thursday Oct 12, 2017 at 19:23 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2130_

----

Spin-off of #2123. We are not correctly handling validation of barrier self-dependency. An initial fix should take care of the issue from that bug, but a secondary consideration is if there are multiple subpass self-dependencies. In that case, the barrier [src|dst][Stage|Access]Masks must be subsets of their respective masks for a single instance of VkSubpassDependency.

**Comment by jzulauf-lunarg** [comment]
Added BUG tag, because this is something we're handling wrong and will create false positive from.

**Comment by tobine** [comment]
@jzulauf-lunarg I believe #183 fixed this, yes?

**Comment by jzulauf-lunarg** [comment]
yes
