### ISSUE TITLE
Multiples const std::vector could be converted to constexpr std::array

### ISSUE THREAD

**Issue by arno-lunarg** [KhronosGroup/Vulkan-ValidationLayers#5105]
Using the Find in Files tool of my IDE with input regex `const std::vector[\s\S]*=`, I saw multiple `const std::vector` definitions that are not needed and could be converted to use `constexpr std::array` instead.

**Comment by ncesario-lunarg** [comment]
Are you up for making the change? 😁

**Comment by arno-lunarg** [comment]
Yes sir!
