### ISSUE TITLE
`void*` data with a known size is not copied in the safe structs

### ISSUE THREAD

**Issue by LDeakin** [KhronosGroup/Vulkan-ValidationLayers#5112]
**Describe the Issue**
In the `safe_` structs, the data pointed to by `void*`/`const void*` members with a known size is not copied on initialisation. Maybe this is the intended behavior, especially since the data in such members is probably not checked during validation. However, it is inconsistent with how the `safe_` structs handle other members. I expected they would make a copy of all data (except data of unknown size, like `pUserData` in `VkDebugReportCallbackCreateInfoEXT`).

I don't know if this issue affects the validation layers themselves, but it could be valuable to fix it for external libraries that use the `safe_` structs. Here is an example of unsafe code related to this issue:
```cpp
safe_VkSpecializationInfo spec_info;
{
  uint32_t spec_constant = 123;
  VkSpecializationMapEntry entry = {.constantID = 0, .offset = 0, .size = sizeof(spec_constant)};
  VkSpecializationInfo spec_info_tmp = {
    .mapEntryCount = 1,
    .pMapEntries = &entry,
    .dataSize = sizeof(spec_constant),
    .pData = &spec_constant,
  };
  spec_info.initialize(&spec_info_tmp);
}
// accessing spec_info.pMapEntries[0] is valid
// accessing spec_info.pData is undefined behaviour
```

**Comment by juan-lunarg** [comment]
Sorry for the delay. I spotted multiple places this is problematic. I should have a fix soon.

- `safe_VkSpecializationInfo`
- `safe_VkWriteDescriptorSetInlineUniformBlock`
- `safe_VkPipelineExecutableInternalRepresentationKHR`
- `safe_VkCuModuleCreateInfoNVX`

**Comment by juan-lunarg** [comment]
Thanks @LDeakin for pointing out this problem :+1: 

Testing has been added to prevent this type of problem from happening again.
