### ISSUE TITLE
"Ensure object handle is not null" fails on vkCreateDebugUtilsMessengerEXT returning null

### ISSUE THREAD

**Issue by romanl-g** [KhronosGroup/Vulkan-ValidationLayers#5115]
**Describe the Issue**
This commit causing assertion fail
https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/e4d0a215586dcc42fba6ce54e51b2cc5d507849a

in ANGLE with VVL enabled:
```
target_os = "android"
target_cpu = "arm64"
is_component_build = false
is_debug = true
```

Driver doesn't expose `VK_EXT_debug_utils`, VVL adds it so ANGLE calls `vkCreateDebugUtilsMessengerEXT`

`third_party/vulkan-deps/vulkan-validation-layers/src/layers/generated/layer_chassis_dispatch.cpp`
calls driver's `vkCreateDebugUtilsMessengerEXT`
`VkResult result = layer_data->instance_dispatch_table.CreateDebugUtilsMessengerEXT(instance, pCreateInfo, pAllocator, pMessenger);`

which rightfully returns VK_NULL_HANDLE and assertion fails

**Environment:**
 - OS: Android
 - GPU:
 - SDK or header version if building from repo:
 - Options enabled (synchronization, best practices, etc.):

**Additional context**

**Comment by romanl-g** [comment]
@artem-lunarg

**Comment by artem-lunarg** [comment]
@romanl-g I'm working on the solution.

In addition to assert fix one more change in behavior can happen. In the previous implementation, when VK_NULL_HANDLE was returned from `CreateDebugUtilsMessengerEXT`, it was wrapped with `WrapNew`. `CreateDebugUtilsMessengerEXT` was returning non-null value even if the object was not created. I'm going to change that behavior, so `*pMessenger` will stay VK_NULL_HANDLE. If there's evidence that ANGLE relied on `*pMessenger` being not null, please let us know.

**Comment by romanl-g** [comment]
Driver doesn't have VK_EXT_debug_utils. Wouldn't that mean that VVL shouldn't be calling CreateDebugUtilsMessengerEXT at all regardless of whether that would fail or return null?

**Comment by romanl-g** [comment]
Despite driver not having VK_EXT_debug_utils, isn't VK_EXT_debug_utils provided by VVL itself? We're expecting this to keep working the same way as it was working before the assert was added.

**Comment by artem-lunarg** [comment]
> Driver doesn't have VK_EXT_debug_utils. Wouldn't that mean that VVL shouldn't be calling CreateDebugUtilsMessengerEXT at all regardless of whether that would fail or return null?

We are discussing this internally. 

> Driver doesn't expose VK_EXT_debug_utils

Does it mean that `VK_EXT_debug_utils` is not reported as supported instance extension?

**Comment by romanl-g** [comment]
`ExtensionFound(VK_EXT_DEBUG_UTILS_EXTENSION_NAME, instanceExtensionNames)` here returns true with VVL on and false with VVL off

https://crsrc.org/c/third_party/angle/src/libANGLE/renderer/vulkan/RendererVk.cpp;drc=598b4824eeb30c5d7ed57b2c69c7b67d84b96a23;l=1557

I also logged the values and saw that enabling VVL was adding a few entries to that list, `VK_EXT_debug_utils` being one of them.

If my understanding is correct, from ANGLE perspective `vkEnumerateInstanceExtensionProperties` includes `VK_EXT_debug_utils` when calling into VVL and doesn't include it when calling into the driver. It is possible that I am misunderstanding something though.

**Comment by artem-lunarg** [comment]
Yes, that's correct. VVL implements VK_EXT_debug_utils.

Still it's allowed for an instance extension to call a driver function. For example, on the desktop, `CreateDebugUtilsMessengerEXT` call ends up in the driver.

**Comment by romanl-g** [comment]
Ok great. So I'm not sure I'm getting this part right:

> I'm going to change that behavior, so *pMessenger will stay VK_NULL_HANDLE when a messenger object can not be created

Even if driver returned VK_NULL_HANDLE we'd still be expecting CreateDebugUtilsMessengerEXT call into VVL to return a non-null object because VVL itself does implement VK_EXT_debug_utils. Is that correct? Then I'm not sure if *pMessenger is supposed to be VK_NULL_HANDLE, wouldn't that misleadingly suggest that CreateDebugUtilsMessengerEXT didn't work as expected?

**Comment by artem-lunarg** [comment]
> Even if driver returned VK_NULL_HANDLE we'd still be expecting CreateDebugUtilsMessengerEXT call into VVL to return a non-null object because VVL itself does implement VK_EXT_debug_utils

We also discussing internally if the driver should be called. Right now the driver returns VK_SUCCESS (which means successful call) and also returns VK_NULL_HANDLE. According to specification, section 3.7.2, successful call of `vkCreate` functions should not result in VK_NULL_HANDLE objects.

**Comment by romanl-g** [comment]
Yup I too suspected that this wasn't according to the specs but if that's the current Android behavior I suppose we'll need some kind of a patch for this in VVL anyways. I'm seeing exactly this in some Android (emulator?) implementation of this method
```
    *pMessenger = VK_NULL_HANDLE;
    return VK_SUCCESS;
```

**Comment by artem-lunarg** [comment]
@romanl-g Do you have opportunity to try the above fix (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5127) while it's not merged yet ?

**Comment by romanl-g** [comment]
Yes that seems to work. ANGLE doesn't actually get VK_NULL_HANDLE with this change. In chassis.cpp, `DispatchCreateDebugUtilsMessengerEXT` returs VK_NULL_HANDLE but then `LayerCreateMessengerCallback` changes it to a valid handle.

**Comment by romanl-g** [comment]
That happens here I suppose:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/78cb04e1e6b5eae6dc755d6e20fbb3c978363604/layers/vk_layer_logging.cpp#L243

**Comment by artem-lunarg** [comment]
> Yes that seems to work. ANGLE doesn't actually get VK_NULL_HANDLE with this change. In chassis.cpp, `DispatchCreateDebugUtilsMessengerEXT` returs VK_NULL_HANDLE but then `LayerCreateMessengerCallback` changes it to a valid handle.

Yes,  when working on this issue I learned that VVL provides stub functions when driver/loader does not implement the extension, and it's the stub functions return null, so we need to handle this.

The fix is merged in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5127, please close this issue if the fix works on your side.

**Comment by artem-lunarg** [comment]
Closing this based on pre-merge confirmation that it works. Please re-open if there are any issues with the final version.
