### ISSUE TITLE
need unit test(s) for "VUID-vkUpdateDescriptorSets-None-03047

### ISSUE THREAD

**Issue by jeremyg-lunarg** [KhronosGroup/Vulkan-ValidationLayers#5121]
We need a unit test for this VUID, which makes sure that the descriptorset isn't in use by a command buffer when vkUpdateDescriptorSets() is called.  It should include a positive sub-test which replicates what happened in #4981, which is roughly:

1. Make 2 descriptorsets from the same pool, `a` and `b`
2. Bind `a` to a command buffer
3. submit command buffer
4. wait for idle
5. Bind `b` to a command buffer
6. submit command buffer
7. call vkUpdateDescriptorSets on `a`  - This should not cause 03047 but at one point it did.

**Comment by spencer-lunarg** [comment]
Related https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5090

**Comment by artem-lunarg** [comment]
The negative test is provided in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3708
