### ISSUE TITLE
Crashes and errors on macOS Apple M1

### ISSUE THREAD

**Issue by lunarpapillo** [KhronosGroup/Vulkan-ValidationLayers#5143]
After VVL changes made to add the portability subset, the tests can be run on macOS.  These are being run on an Apple M1 macMini through MoltenVK, `apiVersion` 1.2.236 and `driverVersion` 0.2.20098.  With these changes, most tests (1570) run and pass.

### 21 crashes (negative return codes)
- [ ] `VkPositiveLayerTest.FramebufferWithAttachmentsTo3DImageMultipleSubpasses`
- [ ] `VkPositiveLayerTest.UseFirstQueueUnqueried`
- [ ] `VkPositiveLayerTest.GetDevProcAddrExtensions`
- [ ] `VkPositiveLayerTest.QueueThreading`
- [ ] `VkPositiveLayerTest.PSOPolygonModeValid`
- [ ] `VkPositiveLayerTest.CreateGraphicsPipelineWithIgnoredPointers`
- [ ] `VkAmdBestPracticesLayerTest.NumberOfSubmissions`
- [ ] `VkLayerTest.ImagelessFramebufferWith3DImage`
- [ ] `VkLayerTest.DynamicRenderingCreateGraphicsPipelineNoInfo`
- [ ] `VkLayerTest.StageMaskGsTsEnabled`
- [ ] `VkLayerTest.MixedTimelineAndBinarySemaphores`
- [ ] `VkLayerTest.ExportMetalObjects`
- [ ] `VkLayerTest.PipelineRenderpassCompatibility`
- [ ] `VkLayerTest.CreatePipelineCheckFragmentShaderInterlockEnabled`
- [ ] `VkLayerTest.ValidateVariableSampleLocations`
- [ ] `VkLayerTest.CreateGraphicsPipelineNullRenderPass`
- [ ] `VkLayerTest.TestMaxFragmentDualSrcAttachments`
- [ ] `VkGpuAssistedLayerTest.GpuValidationInlineUniformBlockAndMiscGpu`
- [ ] `VkGraphicsLibraryLayerTest.ImplicitVUIDs`
- [ ] `VkPortabilitySubsetTest.CreateGraphicsPipelinesRasterizationState`
- [ ] `VkSyncValTest.SyncCopyOptimalMultiPlanarHazards`

### 95 failures (positive return codes)
- [ ] `VkPositiveLayerTest.ClearRectWith2DArray`
- [ ] `VkPositiveLayerTest.EventStageMaskSecondaryCommandBuffer`
- [ ] `VkPositiveLayerTest.TestCreatingFramebufferFrom3DImage`
- [ ] `VkPositiveLayerTest.TwoInstances`
- [ ] `VkPositiveLayerTest.StatelessValidationDisable`
- [ ] `VkPositiveLayerTest.ParameterLayerFeatures2Capture`
- [ ] `VkPositiveLayerTest.EnumeratePhysicalDeviceGroups`
- [ ] `VkPositiveLayerTest.CreatePipelineAttribMatrixType`
- [ ] `VkPositiveLayerTest.CreatePipelineAttribArrayType`
- [ ] `VkPositiveLayerTest.CreatePipelineAttribComponents`
- [ ] `VkPositiveLayerTest.AllowedDuplicateStype`
- [ ] `VkPositiveLayerTest.ImageDescriptor3D2DSubresourceLayout`
- [ ] `VkPositiveLayerTest.TopologyAtRasterizer`
- [ ] `VkPositiveLayerTest.TestPervertexNVShaderAttributes`
- [ ] `VkPositiveLayerTest.TestShaderInputOutputMatch`
- [ ] `VkPositiveLayerTest.LoosePointSizeWrite`
- [ ] `VkPositiveLayerTest.TestShaderInputAndOutputComponents`
- [ ] `VkPositiveLayerTest.OpTypeArraySpecConstant`
- [ ] `VkPositiveLayerTest.WaitEventThenSet`
- [ ] `VkArmBestPracticesLayerTest.RedundantRenderPassStore`
- [ ] `VkLayerTest.ImageBarrierWithBadRange`
- [ ] `VkLayerTest.CreateImageViewFormatMismatchUnrelated`
- [ ] `VkLayerTest.CreateImageViewDifferentClass`
- [ ] `VkLayerTest.MultiplaneIncompatibleViewFormat`
- [ ] `VkLayerTest.CreateImageViewInvalidSubresourceRange`
- [ ] `VkLayerTest.CreateImageMiscErrors`
- [ ] `VkLayerTest.CreateImageViewIncompatibleFormat`
- [ ] `VkLayerTest.CreateImageViewIncompatibleDepthFormat`
- [ ] `VkLayerTest.InvalidImageFormatList`
- [ ] `VkLayerTest.InvalidImageFormatListSizeCompatible`
- [ ] `VkLayerTest.BlockTexelViewInvalidLevelOrLayerCount`
- [ ] `VkLayerTest.BlockTexelViewInvalidType`
- [ ] `VkLayerTest.BlockTexelViewInvalidFormat`
- [ ] `VkLayerTest.CascadedInvalidation`
- [ ] `VkLayerTest.InvalidVertexAttributeAlignment`
- [ ] `VkLayerTest.ResolveImageImageType`
- [ ] `VkLayerTest.WriteDescriptorSetIdentitySwizzle`
- [ ] `VkLayerTest.Maint1BindingSliceOf3DImage`
- [ ] `VkLayerTest.InlineUniformBlockEXT`
- [ ] `VkLayerTest.SwapchainAcquireImageRetired`
- [ ] `VkLayerTest.DynamicRenderingInSecondaryCommandBuffers`
- [ ] `VkLayerTest.ImagelessFramebufferRenderPassBeginImageViewMismatchTests`
- [ ] `VkLayerTest.InstanceExtensionDependencies`
- [ ] `VkLayerTest.InstanceBadStype`
- [ ] `VkLayerTest.InstanceDuplicatePnextStype`
- [ ] `VkLayerTest.InstanceAppInfoBadStype`
- [ ] `VkLayerTest.InstanceValidationFeaturesBadFlags`
- [ ] `VkLayerTest.DestroyInstanceAllocationCallbacksCompatibility`
- [ ] `VkLayerTest.VersionCheckPromotedAPIs`
- [ ] `VkLayerTest.LayerInfoMessages`
- [ ] `VkLayerTest.UseObjectWithWrongDevice`
- [ ] `VkLayerTest.InvalidCmdBufferEventDestroyed`
- [ ] `VkLayerTest.DeviceFeature2AndVertexAttributeDivisorExtensionUnenabled`
- [ ] `VkLayerTest.Features12Features13AndpNext`
- [ ] `VkLayerTest.RequiredPromotedFeaturesExtensions`
- [ ] `VkLayerTest.FeaturesVariablePointer`
- [ ] `VkLayerTest.InvalidQueryPoolCreate`
- [ ] `VkLayerTest.StageMaskHost`
- [ ] `VkLayerTest.EventInUseDestroyedSignaled`
- [ ] `VkLayerTest.InUseDestroyedSignaled`
- [ ] `VkLayerTest.EventStageMaskOneCommandBufferPass`
- [ ] `VkLayerTest.EventStageMaskOneCommandBufferFail`
- [ ] `VkLayerTest.EventStageMaskTwoCommandBufferPass`
- [ ] `VkLayerTest.EventStageMaskTwoCommandBufferFail`
- [ ] `VkLayerTest.ThreadCommandBufferCollision`
- [ ] `VkLayerTest.Maintenance1AndNegativeViewport`
- [ ] `VkLayerTest.ApiVersion1_1AndNegativeViewport`
- [ ] `VkLayerTest.ResetEventThenSet`
- [ ] `VkLayerTest.InvalidGetDeviceQueue`
- [ ] `VkLayerTest.ValidateArrayLength`
- [ ] `VkLayerTest.InvalidCombinationOfDeviceFeatures`
- [ ] `VkLayerTest.Features12AndppEnabledExtensionNames`
- [ ] `VkLayerTest.InstanceCreateEnumeratePortability`
- [ ] `VkLayerTest.CreatePipelineBadVertexAttributeFormat`
- [ ] `VkLayerTest.CreatePipelineLayoutExcessDescriptorsOverall`
- [ ] `VkLayerTest.CreatePipelineAttribNotConsumed`
- [ ] `VkLayerTest.CreatePipelineAttribLocationMismatch`
- [ ] `VkLayerTest.CreatePipelineAttribTypeMismatch`
- [ ] `VkLayerTest.SwapchainAcquireImageNoSync`
- [ ] `VkLayerTest.SwapchainAcquireImageNoSync2KHR`
- [ ] `VkLayerTest.SwapchainAcquireImageNoBinarySemaphore`
- [ ] `VkLayerTest.SwapchainAcquireImageNoBinarySemaphore2KHR`
- [ ] `VkLayerTest.SwapchainAcquireTooManyImages`
- [ ] `VkLayerTest.GetSwapchainImageAndTryDestroy`
- [ ] `VkLayerTest.SwapchainAcquireTooManyImages2KHR`
- [ ] `VkLayerTest.WarningSwapchainCreateInfoPreTransform`
- [ ] `VkLayerTest.SwapchainAcquireImageWithSignaledSemaphore`
- [ ] `VkLayerTest.GetSwapchainImagesCountButNotImages`
- [ ] `VkGpuAssistedLayerTest.GpuBufferDeviceAddressOOB`
- [ ] `VkGpuAssistedLayerTest.ValidationFeatures`
- [ ] `VkPortabilitySubsetTest.CreateImageView`
- [ ] `VkPortabilitySubsetTest.CreateGraphicsPipelinesColorBlendAttachmentState`
- [ ] `VkPortabilitySubsetTest.UpdateDescriptorSets`
- [ ] `VkPortabilitySubsetTest.ShaderValidation`
- [ ] `VkSyncValTest.SyncQSPresentAcquire`

**Comment by lunarpapillo** [comment]
The full output from the failure exercise may be helpful: 
[failures.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/10470963/failures.txt)

**Comment by lunarpapillo** [comment]
In addition, the `VkPositiveLayerTest.QueueThreading` test (which is not caught during normal failure exercises) also crashes with a `SIGSEGV`:
```
INFO: executing #3: /Users/lunarg/work/KhronosGroup/Vulkan-ValidationLayers/build/tests/vk_layer_validation_tests --gtest_catch_exceptions=0 --gtest_filter=*Thread*
ERROR: execution return code -11: attempting to get a stack trace
ERROR: execute() call failed after 0.03 seconds (0.03 seconds): returncode=-11 (-0xb=SIGSEGV); execution log index: 3, working directory: /Users/lunarg/work/KhronosGroup/Vulkan-ValidationLayers
ERROR: ----stdout---------------------------------------------------
Note: Google Test filter = *Thread*
[==========] Running 13 tests from 4 test suites.
[----------] Global test environment set-up.
[----------] 7 tests from VkPositiveLayerTest
[ RUN      ] VkPositiveLayerTest.MultipleThreadsUsingHostOnlyDescriptorSet
/Users/lunarg/work/KhronosGroup/Vulkan-ValidationLayers/tests/positive/descriptors.cpp:1266: Skipped
VK_EXT_mutable_descriptor_type not supported
[  SKIPPED ] VkPositiveLayerTest.MultipleThreadsUsingHostOnlyDescriptorSet (15 ms) 
[ RUN      ] VkPositiveLayerTest.QueueThreading
ERROR: -------------------------------------------------------------
ERROR: FAIL during test after 29.42 seconds (29.42 seconds) with execute(/Users/lunarg/work/KhronosGroup/Vulkan-ValidationLayers/build/tests/vk_layer_validation_tests --gtest_catch_exceptions=0 --gtest_filter=*Thread*) failed after 0.03 seconds (0.03 seconds) with returncode=-11 (-0xb=SIGSEGV)
```
So it should be added to the list of crashes above:
- `VkPositiveLayerTest.QueueThreading`

**Comment by juan-lunarg** [comment]
> VkLayerTest.ExportMetalObjects

Works fine locally... strange.

**Comment by lunarpapillo** [comment]
A new test failure appeared as we were deploying (likely a new test was introduced between the time the blacklist was generated and when the Mac was deployed).
```
[ RUN      ] VkLayerTest.InvalidExportExternalImageHandleType
/Users/lunarg/.jenkins/vz0/Release64/Vulkan-ValidationLayers/tests/vkerrormonitor.cpp:106: Failure
Failed
VK_ERROR_FEATURE_NOT_PRESENT: vkCreateImage(): Only external memory handle type VK_EXTERNAL_MEMORY_HANDLE_TYPE_MTLTEXTURE_BIT_KHR is supported.
/Users/lunarg/.jenkins/vz0/Release64/Vulkan-ValidationLayers/tests/vklayertests_buffer_image_memory_sampler.cpp:12394: Skipped
Unable to create a valid external image
[  FAILED  ] VkLayerTest.InvalidExportExternalImageHandleType (6 ms) 
```
Blacklisting this too.

**Comment by richard-lunarg** [comment]
@lunarpapillo are you building on macOS with -DVK_USE_PLATFORM_METAL_EXT=ON ?

e.g. cmake -C helper.cmake -DBUILD_TESTS=ON -DVK_USE_PLATFORM_METAL_EXT=ON ..

**Comment by artem-lunarg** [comment]
> A new test failure appeared as we were deploying (likely a new test was introduced between the time the blacklist was generated and when the Mac was deployed).
> 
> ```
> [ RUN      ] VkLayerTest.InvalidExportExternalImageHandleType
> /Users/lunarg/.jenkins/vz0/Release64/Vulkan-ValidationLayers/tests/vkerrormonitor.cpp:106: Failure
> Failed
> VK_ERROR_FEATURE_NOT_PRESENT: vkCreateImage(): Only external memory handle type VK_EXTERNAL_MEMORY_HANDLE_TYPE_MTLTEXTURE_BIT_KHR is supported.
> /Users/lunarg/.jenkins/vz0/Release64/Vulkan-ValidationLayers/tests/vklayertests_buffer_image_memory_sampler.cpp:12394: Skipped
> Unable to create a valid external image
> [  FAILED  ] VkLayerTest.InvalidExportExternalImageHandleType (6 ms) 
> ```
> 
> Blacklisting this too.

This test was fixed here:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/d5cd69ecf0410885ee71b2e5c7fdfb97af43b0a3

**Comment by spencer-lunarg** [comment]
closing for favor of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7003
