### ISSUE TITLE
Vector subscript out of range running CTS with synchronization validation

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-ValidationLayers#5157]
**Describe the Issue**
These tests assert Vector subscript out of range when running them with synchronization validation enabled
       dEQP-VK.pipeline.monolithic.multisample.mixed_count.1_2
       dEQP-VK.api.granularity.in_render_pass.r5g6b5_unorm_pack16
       dEQP-VK.pipeline.monolithic.multisample.variable_rate.1_2_fb_1
       dEQP-VK.renderpass.dedicated_allocation.attachment_allocation.input_output.10
The commit that provokes the assert is "layers: Apply render pass final transitions always" from #5054 

The code in question is synchronization_validation.cpp 2916 
const auto &trackback = subpass_contexts_[transition.prev_pass].GetDstExternalTrackBack();
transition.prev_pass = 0xffffffff

**Valid Usage ID**
If applicable, please include the validation messages encountered leading up to the issue

**Environment:**
 - OS: WIndows 10
 - GPU: RTX 2060
 - Options enabled : synchronization

**Additional context**
CTS commit 5b7bf2e

**Comment by jzulauf-lunarg** [comment]
The simplest fix at this time is to revert the triggering change as it doesn't achieve its goal.  Correct address of the original issue will be in a separate PR.
