### ISSUE TITLE
Layer logging without app level callback doesn't work on Android

### ISSUE THREAD

**Issue by cnorthrop** [KhronosGroup/Vulkan-ValidationLayers#516]
At some point it looks like layer logging was rewritten to use a number of desktop loader features, like json files and environment variables.  That means on Android, layers can no longer log failures without an app level callback.  We didn't catch this change because our validation tests use an app level callback.

Can Android support be returned to validation layers that want to log output, or log to a file?

**Comment by mark-lunarg** [comment]
@cnorthrop, if no callback is registered, a default callback should be constructed and used by default.  This should send output to stdout. I'm guessing this is not sufficient for the information to end up in logcat?

**Comment by cnorthrop** [comment]
Right, stdout and stderr go to /dev/null on Android.

**Comment by mark-lunarg** [comment]
Ah.  Then this is nothing new -- I think the answer is to add some conditionally compiled-in Android-specific logic to `report_log_callback()` and `messenger_log_callback()` in vk_layer_logging.h.

**Comment by mark-lunarg** [comment]
If you can get @tobine to add this issue to the priority list, I can take care of it...

**Comment by mark-lunarg** [comment]
Fixed by PR #520.
