### ISSUE TITLE
Remove `-fno-strict-aliasing` and `-fno-builtin-memcmp`

### ISSUE THREAD

**Issue by juan-lunarg** [KhronosGroup/Vulkan-ValidationLayers#5161]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/a02d0adc2d8eae5a65ddd6178d218a69fe222426/CMakeLists.txt#L114-L115

Talking to @Tony-LunarG these are most likely safe to remove from VVL.

[-fstrict-aliasing](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#Optimize-Options)
[-fno-builtin-function](https://gcc.gnu.org/onlinedocs/gcc/C-Dialect-Options.html#C-Dialect-Options)

**Comment by Tony-LunarG** [comment]
From what I can tell, adding these options prevented a crash in link_shaders, presumably in the Ilo driver which is long gone at this point.
