### ISSUE TITLE
Validation error when using promoted VkPhysicalDeviceTexelBufferAlignmentProperties struct in Vulkan 1.3

### ISSUE THREAD

**Issue by jmccarthy634** [KhronosGroup/Vulkan-ValidationLayers#5163]
**Environment:**
 - OS: Windows 10
 - GPU: RTX 3080
 - SDK or header version if building from repo: 1.3.231
 - Options enabled (synchronization, best practices, etc.):

**Describe the Issue**

On drivers supporting API level 1.3.194 when attempting to create a buffer view with a valid alignment according to VkPhysicalDeviceTexelBufferAlignmentProperties I get a validation error shown below.

The only way to get around this is to enable the extension, and then pass the VkPhysicalDeviceTexelBufferAlignmentFeaturesEXT structure to VkDeviceCreateInfo when creating the device.

**Expected behavior**

According to the page for VK_EXT_texel_buffer_alignment:

> Functionality in this extension is included in core Vulkan 1.3, with the EXT suffix omitted. However, only the properties structure is promoted. The feature structure is not promoted. The original type name is still available as an alias of the core functionality.

I guess I'm asking if this is the expected behaviour, or if there isn't some other non-extension way to properly get around this, and if so then what was the point of promoting the properties struct if the features struct and therefore the extension is required to actually use information in the properties struct anyway. Or if this is just a bug with the validation layers.

**Valid Usage ID**
If applicable, please include the validation messages encountered leading up to the issue

**Additional context**

<details>
<summary>code or terminal output</summary>

Validation error in question:

```sh
Validation Error: [ VUID-VkBufferViewCreateInfo-offset-02749 ] Object 0: handle = 0x94780b0000002adb, name = buffer StructuredBuffer, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0xc253fd9b | vkCreateBufferView(): VkBufferViewCreateInfo offset (8) must be a multiple of VkPhysicalDeviceLimits::minTexelBufferOffsetAlignment (16). The Vulkan spec states: If the texelBufferAlignment feature is not enabled, offset must be a multiple of VkPhysicalDeviceLimits::minTexelBufferOffsetAlignment (https://vulkan.lunarg.com/doc/view/1.3.216.0/windows/1.3-extensions/vkspec.html#VUID-VkBufferViewCreateInfo-offset-02749)
```

</details>

**Comment by spencer-lunarg** [comment]
1. You always need to enable the feature bit, some features, such as `robustBufferAccess` can make your app slower so they are not always assumed to be on

2. So the issue here is I would expect `VkPhysicalDeviceVulkan13Features` to have ` texelBufferAlignment`, but looking back, there was some internal discussion and that is why it says

> However, only the properties structure is promoted. The feature structure is not promoted

So the actions here are

1. I will fix the Validation Layers to "enable" `texelBufferAlignment` when Vulkan 1.3 is used
2. Probably add some more spec clarification that this is the desired behavior as it is not 100% clear without read internal discussions about this

**Comment by spencer-lunarg** [comment]
spec change made, and PR up
