### ISSUE TITLE
VVL to check descriptor set allocation requesting types missed from pool creation

### ISSUE THREAD

**Issue by zhangyiwei** [KhronosGroup/Vulkan-ValidationLayers#5167]
The context is in https://gitlab.khronos.org/vulkan/vulkan/-/issues/3347. I wonder if we can do something better than best practice, since this is indeed causing app bailing on MESA Virtio-GPU Venus implementation.

**Comment by spencer-lunarg** [comment]
Reopen to look into making this part of normal validation if `VK_ERROR_OUT_OF_POOL_MEMORY` is returned

**Comment by spencer-lunarg** [comment]
@zhangyiwei sorry this got lost for so long, but finally fixed this so now by default it will give a warning if we detect `VK_ERROR_OUT_OF_POOL_MEMORY` was returned **and** the user used a type that wasn't in the pool
