### ISSUE TITLE
VK_KHR_shared_presentable_image layout transitions should be treated in a special way

### ISSUE THREAD

**Issue by SergeySol84** [KhronosGroup/Vulkan-ValidationLayers#5200]
**Environment:**
 - OS:  Android
 - GPU: Adreno
 - SDK or header version if building from repo:   1.3.239 binary
 - Options enabled (synchronization, best practices, etc.): VK_LAYER_KHRONOS_validation

From the spec of 
(https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_shared_presentable_image.html)
it is clear that layout transition should be done once into PRESENT_SRC_KHR and the following transitions should not be required. However validation layers are not happy about that and report an error that I need to transition image into GENERAL layout before I render into it.

**Expected behavior**

After transitioning image into PRESENT_SRC_KHR and presenting it via vkQueuePresentKHR  the validation layers should not require me to do any further layout transitions.

**Valid Usage ID**

<details>
<summary>code or terminal output</summary>

```sh
  E  Validation   Validation Error: [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object 0: handle = 0xxxx, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xxxx | vkQueueSubmit(): pSubmits[0].pCommandBuffers[0] command buffer VkCommandBuffer 0xxxx[] expects VkImage 0xxxx[] (subresource: aspectMask 0x1 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_GENERAL--instead, current layout is VK_IMAGE_LAYOUT_PRESENT_SRC_KHR.
```

</details>

**Comment by SergeySol84** [comment]
This is my issue, I sould have used the right layout in descriptor set update  inside the structure
VkDescriptorImageInfo

**Comment by spencer-lunarg** [comment]
> This is my issue

Sorry, did you find an issue on your end, or you think this is still a Validation Layer bug?

**Comment by SergeySol84** [comment]
This was the issue on my side, I have fixed it now.
