### ISSUE TITLE
Invalid VkSwapchainKHR Object

### ISSUE THREAD

**Issue by JophiMa** [KhronosGroup/Vulkan-ValidationLayers#5203]
**Environment:**
 - OS: Stock Arch Linux, updated today
 - GPU: GTX 750ti
 - SDK or header version if building from repo: vulkan-devel package from the official arch repository
 - Options: 
VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT, VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT, VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT; 

**Describe the Issue**
The program draws a rainbow triangle without issue, the first swapChain creation is always successful. Resizing the GLFWwindow  causes the old swapChain to be deleted and then overwritten by the same function that created the first one. However the second creation causes a **segFault at *vkQueuePresentKHR(presentQueue, &presentInfo)**. The weird thing is that **vkCreateSwapchainKHR(device, &createInfo, nullptr, &swapChain) returns VK_SUCCESS on both creations**. No changes are made to the function responsible for drawing frames inbetween creations. 

**Expected behavior**
I would expect a != VK_SUCCESS on creation, as the object is invalid.

**Valid Usage ID**
No other validation error except the one below is shown to me.

**Additional context**
I'm following the vulkan tutorial on vulkan-tutorial.com . My code is almost a complete copy of the code in the tutorial.
Calling vkAcquireNextImageKHR on the second swap chain results in VK_SUCCESS without  VK_ERROR_OUT_OF_DATE_KHR or VK_SUBOPTIMAL_KHR. The same goes for vkQueueSubmit. I can provide additional info if needed.
<details>
<summary>The validation error prior to segfault</summary>

```sh
[WARN] | (Validation layer) : Validation Error: [ VUID-VkPresentInfoKHR-pSwapchains-parameter ] Object 0: handle = 0x5555556b1da0, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x1f4c4154 | Invalid VkSwapchainKHR Object 0xfab64d0000000002. The Vulkan spec states: pSwapchains must be a valid pointer to an array of swapchainCount valid VkSwapchainKHR handles (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkPresentInfoKHR-pSwapchains-parameter)
```

</details>

I'm sorry if this is not a bug, it just seemed like it to me. Thanks in advance for helping out.

**Comment by spencer-lunarg** [comment]
@JophiMa it is hard to fix these issues without a way to try and reproduce it (or start to examine it more)

if possible could you give something like an [api dump](https://vulkan.lunarg.com/doc/view/latest/windows/api_dump_layer.html) of the area this happens as it will allow us to look into this faster

but most likely 

- you are passing the deleted swapchain into the `oldSwapchain` parameter of `SwapchainCreateInfo`
- you didn't actually delete the old swapchain, and because there are 2 swapchains associated with the same window handle it causes issues
