### ISSUE TITLE
"Descriptor in binding #X at global descriptor index Y is being used in draw but has not been updated." error when using VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT

### ISSUE THREAD

**Issue by flisgd** [KhronosGroup/Vulkan-ValidationLayers#521]
"Descriptor in binding #X at global descriptor index Y is being used in draw but has not been updated." error when using VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT in VkDescriptorBindingFlagsEXT.

Full message:

> UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotUpdated(WARN / SPEC): msgNum: 0 - Descriptor Set 0x4 bound but it was never updated. You may want to either update it or not bind it.
>     Objects: 1
>        [0] 0x4, type: 23, name: (null)
> Validation(WARN): msg_code: 0:  [ UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotUpdated ]  [ UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotUpdated ] Object: 0x4 (Type = 23) | Descriptor Set 0x4 bound but it was never updated. You may want to either update it or not bind it.
> UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotUpdated(ERROR / SPEC): msgNum: 0 - Descriptor set 0x4 bound as set #0 encountered the following validation error at vkCmdDraw() time: Descriptor in binding #0 at global descriptor index 0 is being used in draw but has not been updated.
>     Objects: 1
>        [0] 0x4, type: 23, name: (null)
> Validation(ERROR): msg_code: 0:  [ UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotUpdated ]  [ UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotUpdated ] Object: 0x4 (Type = 23) | Descriptor set 0x4 bound as set #0 encountered the following validation error at vkCmdDraw() time: Descriptor in binding #0 at global descriptor index 0 is being used in draw but has not been updated.

The problem seems to be in following code snippet:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/sdk-1.1.92/layers/descriptor_sets.cpp#L716

```
        for (uint32_t i = index_range.start; i < index_range.end; ++i, ++array_idx) {
            if ((p_layout_->GetDescriptorBindingFlagsFromBinding(binding) & VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT_EXT) ||
                descriptors_[i]->GetClass() == InlineUniform) {
                // Can't validate the descriptor because it may not have been updated,
                // or the view could have been destroyed
                continue;
            } else if (!descriptors_[i]->updated) {
```

VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT flag allows updating descriptor later:
```
VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT indicates that if descriptors in this binding are
updated between when the descriptor set is bound in a command buffer and when that
command buffer is submitted to a queue, then the submission will use the most recently set
descriptors for this binding and the updates do not invalidate the command buffer. 
```
> 
so I believe it should be also included in the code.

**Comment by tobine** [comment]
I created #523 to prevent the false positive. I'll open a separate issue track proper validation when VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT is present.
