### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [KhronosGroup/Vulkan-ValidationLayers#5224]
Would you like to wrap any pointers with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [CreateInstance](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/2e33730279b62844f39008ea7edc3d9baf9cc6a4/scripts/layer_chassis_generator.py#L830)
- [Test case](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/976daa66b653b5e05dccfb640a78838843efecba/tests/vklayertests_gpu.cpp#L417)

**Comment by juan-lunarg** [comment]
Closing in favor of planned clang-tidy integration into CI:
https://github.com/orgs/KhronosGroup/projects/10/views/1

**Comment by elfring** [comment]
:eyes: The GitHub interface presented the error code “404” for the referenced “project view”.

:thinking: I hope that further improvements will become possible (also for issues which I pointed out so far).
