### ISSUE TITLE
Improve clarity of Best Practices 'ImageBarrierAccessLayout' validation message

### ISSUE THREAD

**Issue by theakman2** [KhronosGroup/Vulkan-ValidationLayers#5226]
**Environment:**
 - OS: Xubuntu 22.10
 - GPU: Nvidia 3070 ti
 - SDK or header version if building from repo: 1.3.239
 - Options enabled (synchronization, best practices, etc.): Validation, synchronization, best practices. See screenshot below.

![image](https://user-images.githubusercontent.com/5579954/216773747-af941889-91a9-440f-87ad-7df51787a089.png)

**Describe the Issue**

'UNASSIGNED-BestPractices-ImageBarrierAccessLayout(WARN / SPEC): msgNum: -2069901625' validation warning messaging is confusing.

Currently, the error message is:

```
{{provided access mask}}: accessMask is {{command}}, but for layout {{provided layout}} expected accessMask are {{expected access mask}}
```

**Expected behavior**

I'd expect the error message to be something like:

```
{{provided access mask}} passed in {{command}}, but for layout {{provided layout}} expected accessMask are {{expected access mask}}
```

When I encountered the current error message, I thought my application had undefined behaviour that was causing the validation layers to generate the wrong string representation of the access mask.

Granted this may be an embarrassingly silly interpretation, but hopefully a minor formatting change will make the message clearer.

**Valid Usage ID**

UNASSIGNED-BestPractices-ImageBarrierAccessLayout(WARN / SPEC): msgNum: -2069901625

**Comment by ziga-lunarg** [comment]
This appears to have been fixed in 3b87a5ade78b5e8f584a552caed1411e64ac6e8d
