### ISSUE TITLE
broken primitive topology detection with GPL

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-ValidationLayers#5235]
I'm getting `VUID-vkCmdDrawMultiEXT-primitiveTopology-03420` emitted:

```
vkCmdDrawMultiEXT: the last primitive topology VK_PRIMITIVE_TOPOLOGY_LINE_LIST state set by vkCmdSetPrimitiveTopologyEXT is not compatible with the pipeline topology VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN. The Vulkan spec states: If the bound graphics pipeline state was created with the VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY_EXT dynamic state enabled then vkCmdSetPrimitiveTopology must have been called in the current command buffer prior to this drawing command, and the primitiveTopology parameter of vkCmdSetPrimitiveTopology must be of the same topology class as the pipeline VkPipelineInputAssemblyStateCreateInfo::topology state
```

The twist is that I've *exhaustively* verified that the pipeline I'm using is, in fact, created using a GPL vertex input with LINE_LIST. I'm not sure how/where exactly this state is propagated across GPL links, but something is broken here.

VVL 96f49d713eeb33cf87d8e56d1a8f3e05948002ed

**Comment by spencer-lunarg** [comment]
Can you give me an [API dump](https://vulkan.lunarg.com/doc/view/latest/windows/api_dump_layer.html) or a way to reproduce this, I guess trying to recreate a test for this, but not successful

**Comment by zmike** [comment]
I unfortunately encountered this in some experimental code and don't have a portable way to repro. I'd say if this can't be found by simple inspection/analysis then it can be closed for now until/unless I can come up with something to share.
