### ISSUE TITLE
Prevent Recording of update-after-bind descriptor and image_layout information

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-ValidationLayers#524]
Previously #523 prevented false positives for update-after-bind descriptors, however record time validation was still treating them as known (and valid) at record time, potentially crashing the validation layer.

--- Orignal description ---
Descriptor validation does not properly account for VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT bit. There's a number of VU statements affected by this bit that need to have checks implemented/updated, as well as new/updated tests.
#523 prevents false positives for descriptors with this bit that have not yet been updated at the time a Draw command goes into a cmd buffer. However, some action should be taken at that point to indicate that the draw-time descriptor validation should instead take place at submit time in this case.
Hopefully the draw-time descriptor validation code can be re-used at submit time to do any checking that had to be delayed due to this bit.

**Comment by karl-lunarg** [comment]
> Hopefully the draw-time descriptor validation code can be re-used at submit time 

Are you thinking that this check can/should be done at submit time on the CPU, or is it better handled by an on-GPU validation check?

I do agree that some of the existing descriptor checks need to be relaxed when bits like these are turned on to avoid the false positive. We do have a direction to perform some of these on the GPU, which is effectively at submit time.  So do you think that this one _can_ or should be implemented on the CPU, or is it a good candidate for a GPU-validation function?

**Comment by tobine** [comment]
I'm thinking on the CPU. Primarily b/c we already have all the CPU-side code that I'm thinking can be re-used so I know the work _can_ be done there and I'm thinking that's the path of least resistance.
I don't know how GPU-side checks are implemented, though, so if the process of porting checks from CPU to GPU is not very difficult, these checks are certainly a possibility for GPU validation, that's just not how I would do it personally.

**Comment by jzulauf-lunarg** [comment]
Triage notes: at draw time the needed layout check for VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT bindings needs to be added to the command buffers node's collection of QueueSubmit time actions.  This could either be in the form of a lambda added to the existing list, or a list of descriptor v. layout checks to be done.  Note interaction with "first use" (i.e. potentially neither the descriptor nor layout states will be known at record time), and that command buffer and global layout states are different.  Also possible refactor of record time validation code to avoid duplication of checks.

**Comment by jzulauf-lunarg** [comment]
@tobine limiting issue scope to ensuring that the record time validation and record are skipped for UPDATE_AFTER_BIND.  Queue-time validation will require creating a timeline of image layout update and descriptor validation events, as the command buffer only stores first and last state for image layout.  Will add as separate issue.
