### ISSUE TITLE
Image Layout errors for unused descriptor set bindings.

### ISSUE THREAD

**Issue by brett19** [KhronosGroup/Vulkan-ValidationLayers#526]
Validation fails against a descriptor set due to image layout mismatch when a descriptor set has a binding set to an image has the wrong layout but for which the binding is not actually used by the shader.

The use-case is that we have a singular pipeline layout that covers our whole application.  We have 48 bindings in this descriptor set and we pool our allocated descriptor sets to avoid the allocation/initialization cost.  When using a descriptor set which was allocated from the pool and had been previously used, sometimes we receive a descriptor set which has (for example) binding 8 set, but that binding is not used by the shader for the current draw.  Since its not used, we do not write a new value to that binding for the particular draw we are performing.  When the draw is performed, the validation layer complains about a mismatched image layout for whatever was bound to binding 8, in spite of the fact that that image is not actually being used.

**Comment by jzulauf-lunarg** [comment]
@brett19  -- The logic to limit image layout checks to based on static analysis of the shader set/binding declarations for currently bound shader exists, which means this is a bug in that logic, or in the application.

Is there an testcase or trace that reproduces this condition.

**Comment by brett19** [comment]
Hey @jzulauf-lunarg ,
Its definitely non-trivial to build a small test-case for this, since I don't quite understand the behaviour which causes it.  I incorrectly indicated above that the validation failure occurs when we did a vkDraw, but in fact it was actually occurring when we do the vkQueueSubmit for the command buffer.  I'm going to close this for now as I don't have a working reproduction since I rewrote part of my descriptor handling in order to avoid this issue (at a performance cost).  If you have any thoughts on where we might look for the error, please let me know.
Cheers, Brett

**Comment by jzulauf-lunarg** [comment]
@brett19 -- wasn't trying to scare you off.  A RenderDoc capture of the original issue would help potentially to evaluate if this is an application or layers issue.
