### ISSUE TITLE
vkCreateGraphicsPipelines validation doesn't return a meaningful object reference

### ISSUE THREAD

**Issue by mikes-lunarg** [KhronosGroup/Vulkan-ValidationLayers#527]
Nearly all of the `log_msg` calls in `PreCallValidateCreateGraphicsPipelines` send `PIPELINE_STATE.pipeline` to the debug callback, but that field isn't populated until `PostCallRecordCreateGraphicsPipelines` so it will always be 0.  The best we can probably do when there is a validation error in `vkCreateGraphicsPipelines` is return `device` as the source object.

**Comment by locke-lunarg** [comment]
[pull request #758](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/758)
