### ISSUE TITLE
Stop running all shader modules through spirv-opt

### ISSUE THREAD

**Issue by jeffbolznv** [KhronosGroup/Vulkan-ValidationLayers#528]
shader_module::PreprocessShaderBinary unconditionally runs shader modules through spirv-opt. From what I can tell, this was just meant as a shortcut to supporting OpGroupDecorate. But as I found in #515, this means spirv-opt bugs become validation layer bugs. It also means the layers aren't validating the original SPIR-V source that was passed in, but rather some modified version of it, which makes it harder to debug and probably obscures error messages. It doesn't seem like a good tradeoff to me.

Supporting group decorations directly is probably not that hard, but there are a handful of places that look at decorations and would need to be updated. While looking at this part of the code, I realized that each of these places loops over ALL instructions in the module even though decorations are required to be very early in the module, so there's some wasted time here. It would probably make sense to have a dedicated pass early on to gather up all the decorations into some more useful representation, which could handle group decorations as well, and then code that validates the decorations need not loop over any instructions.

**Comment by chrisforbes** [comment]
@jzulauf-lunarg I've just done decoration group support for SwiftShader; my SPIRV analysis in that project is heavily based on things learned in the VL work; perhaps we can bring those ideas back to VL?

The new decoration collector is a single forward pass, which we could combine with some other early pass, or could constrain to the correct part of the module if we wanted to do a standalone pass.

Here's the Swiftshader change: https://swiftshader-review.googlesource.com/c/SwiftShader/+/23174

**Comment by JasperNV** [comment]
spirv-opt should now be more vocal about unknown opcodes and properly report a failure in that case; see https://github.com/KhronosGroup/SPIRV-Tools/pull/2487

**Comment by chrisforbes** [comment]
Triage notes: not too difficult. 1-2d to build this if somebody knows SPIRV. I don't have the spare cycles to do the work at the moment.

**Comment by greg-lunarg** [comment]
I am going to try to help out on VL shader checker issues going forward. I won't be able to get to this for the next 2-3 weeks, but if its still around when I get freed up, I will go for it.

**Comment by mark-lunarg** [comment]
The source has been modified to only process shader binaries containing group decorations.  The flattened binary is only used for validation, and is not passed down to other layers or the display driver.
