### ISSUE TITLE
syncval: Add support for cmdBindVertexBuffers2 to syncval

### ISSUE THREAD

**Issue by jzulauf-lunarg** [KhronosGroup/Vulkan-ValidationLayers#5281]
Bind Vertex Buffers2 allows for restricting the scope of the buffer bound which provides a workaround for false positives where the whole of the buffer is considered used.

**Comment by jzulauf-lunarg** [comment]
Added @ https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5567 -- missing ULT

**Comment by spencer-lunarg** [comment]
update on this

the issue of "which stride" (https://gitlab.khronos.org/vulkan/vulkan/-/issues/3381) has been resolved

in this change (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7553) I moved things so now Sync Val can just check `cb_state.current_vertex_buffer_binding_info` to get the "correct" `stride` value (from pipeline or from dynamic state) at draw time
