### ISSUE TITLE
No check that YCbCr conversion sampler is specified on image view

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-ValidationLayers#529]
The spec requires that when using a YCbCr conversion sampler that it's passed identically on the immutable sampler in a combined image/sampler as well as the image view:

> VU on `VkWriteDescriptorSet`:
> If `descriptorType` is `VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER`, and `dstSet` was allocated with a layout that included immutable samplers for `dstBinding`, then the `imageView` member of each element of `pImageInfo` which corresponds to an immutable sampler that enables sampler Y’CBCR conversion must have been created with a `VkSamplerYcbcrConversionInfo` structure in its `pNext` chain with an _identically defined_ `VkSamplerYcbcrConversionInfo` to the corresponding immutable sampler

Tested on SDK 1.1.92.1.

**Comment by jzulauf-lunarg** [comment]
By 

> with an identically defined VkSamplerYcbcrConversionInfo

we take it to mean with the same value of the `VkSamplerYcbcrConversionInfo::conversion` handles, not with `VkSamplerYcbcrConversionInfo::conversion` handles created with identical
`VkSamplerYcbcrConversionCreateInfo`

**Comment by Tony-LunarG** [comment]
Fixed in PR #555
