### ISSUE TITLE
Warn if no VkPipelineRenderingCreateInfo for VkGraphicsPipelineCreateInfo 

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/Vulkan-ValidationLayers#5292]
from https://github.com/KhronosGroup/Vulkan-Docs/issues/2056

There are few cases in `VkGraphicsPipelineCreateInfo` where leaving things is valid, but could give a proper warning in best practices

**Comment by jube** [comment]
In the MESA llvmpipe driver, if `VkPipelineRenderingCreateInfo` is not added in the `pNext` chain of `VkGraphicsPipelineCreateInfo`, then no rendering occurs at all. IMO, it should be more than a best practice because, as stated in the related issue, it can lead to obscure bugs.
