### ISSUE TITLE
Scrub implementation of primary/secondary rules wrt renderpass edges, inheritance, etc

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#53]
**Issue by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Wednesday Nov 01, 2017 at 00:30 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2171_

----

This seems really messy at the moment. Some of the validation code for these features predates us having a clear picture of the constraints

**Comment by mark-lunarg** [comment]
Closing for now, most of this has been refactored during the last two years.
