### ISSUE TITLE
Layers complain about layout of ycbcr multi-plane image

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-ValidationLayers#530]
This seems related to #344 and #380.

I have a multiplane `VK_FORMAT_G8_B8R8_2PLANE_420_UNORM` image, which I layout transition with `VK_IMAGE_ASPECT_COLOR_BIT`. When creating a view of `VK_IMAGE_ASPECT_COLOR_BIT` with a ycbcr conversion sampler, the layers complain that its currently layout is `UNDEFINED`.

They don't complain when making views of the individual plane aspects suggesting that the tracking is accurate just not accounting for this case.

**Comment by daveh-lunarg** [comment]
Hi, @baldurk.  What is the specific VUID that's thrown in error?

**Comment by baldurk** [comment]
Sorry, that wasn't a good report!

The image is created and transitioned eventually into `VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL` after being populated. When a view is created of each `IMAGE_ASPECT_PLANE` and then read in a shader, there are no errors. When I create a ycbcr conversion view of `IMAGE_ASPECT_COLOR` then reading from that in the shader produces this error:

> [Validation]  [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object: 0x135aab96eb0 (Type = 6) | Submitted command buffer expects image 0x3d (subresource: aspectMask 0x1 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL--instead, image 0x3d's current layout is VK_IMAGE_LAYOUT_UNDEFINED.

I can get a repro to you soon, I'm in the middle of finishing my code so at the moment it might be broken in other ways.

**Comment by baldurk** [comment]
OK I think it's stable & error free apart from this message. If you build [my demo test program](https://github.com/baldurk/renderdoc/tree/v1.x/util/test) - either with CMake in the `demos/` folder or with the .sln there - you should be able to run the `VK_Video_Textures` demo and see the problem. You can pass it as a command line parameter to run it directly, or pick it from the menu that pops up. You can also pass `--validate` to load the validation layers if you're not forcing them on externally.

**Comment by Tony-LunarG** [comment]
Fixed in #536
