### ISSUE TITLE
Strange synchronization validation error when uploading initial data to an image

### ISSUE THREAD

**Issue by Pilzschaf** [KhronosGroup/Vulkan-ValidationLayers#5318]
**Environment:**
 - OS: Manjaro
 - GPU: AMD RX 7900XT
 - Options enabled: Validation, Best Practices, GPU assisted, GPU reserved binding slot and synchronization validation

**Describe the Issue**

Synchronization validation reports a write after write hazard for my initial data upload to an image. I simply create a new image, and a new scratch buffer. Fill the scratch buffer with the image data and try to copy the buffer to the image with vkCmdCopyBufferToImage. I have an image barrier before the copy to ensure the image is in the correct layout.

**Expected behavior**

I would not expect a sync validation error for the image as the layout is transitioned and there is no prior write to the image

**Valid Usage ID**
Vulkan Error: Validation Error: [ SYNC-HAZARD-WRITE-AFTER-WRITE ] Object 0: handle = 0xe7f79a0000000005, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x5c0ec5d6 | vkCmdCopyBufferToImage: Hazard WRITE_AFTER_WRITE for dstImage VkImage 0xe7f79a0000000005[], region 0. Access info (usage: SYNC_COPY_TRANSFER_WRITE, prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION, write_barriers: 0, command: vkCmdPipelineBarrier2, seq_no: 1, reset_no: 2).
Thread 0, Frame 0:

**Additional context**

I have included two files with the API dump of my repro case. One contains all calls. The other is reduced to the parts which I think are relevant

<details>

This is the code I use for the copy of the buffer to the image
```c
VkImageMemoryBarrier2 imageBarrier = {VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2};
imageBarrier.srcStageMask = VK_PIPELINE_STAGE_TRANSFER_BIT;
imageBarrier.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
imageBarrier.dstStageMask = VK_PIPELINE_STAGE_TRANSFER_BIT;
imageBarrier.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
imageBarrier.oldLayout = VK_IMAGE_LAYOUT_UNDEFINED;
imageBarrier.newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
imageBarrier.image = image->image;
imageBarrier.subresourceRange = (VkImageSubresourceRange){
	.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
	.baseMipLevel = 0,
	.levelCount = 1,
	.baseArrayLayer = 0,
	.layerCount = 1,
};
VkDependencyInfo dependencyInfo = {VK_STRUCTURE_TYPE_DEPENDENCY_INFO};
dependencyInfo.imageMemoryBarrierCount = 1;
dependencyInfo.pImageMemoryBarriers = &imageBarrier;
vkCmdPipelineBarrier2(commandBuffer, &dependencyInfo);

VkBufferImageCopy region = {0};
region.bufferOffset = scratchOffset;
region.imageSubresource.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
region.imageSubresource.layerCount = 1;
region.imageExtent = (VkExtent3D){image->width, image->height, image->depth};
vkCmdCopyBufferToImage(commandBuffer, uploadContext->scratch->buffer, image->image, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &region);

```

</details>
[api_dump_sync_issue_stripped.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/10791921/api_dump_sync_issue_stripped.txt)
[api_dump_sync_issue.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/10791922/api_dump_sync_issue.txt)

**Comment by artem-lunarg** [comment]
@Pilzschaf, which version of the Vulkan SDK is used here? If you built validation layers from the source code, which commit is it? Thanks for providing API dump files. That's very helpful.

**Comment by Pilzschaf** [comment]
The validation layers are the current system package version which is 1.3.236.0-1.
The vulkan version installed on the system is 1.3.240-1
I am using volk for loading vulkan into my application

**Comment by Pilzschaf** [comment]
I just replaced the system installed validation layers with a self-compiled version from the main branch and the validation sync error has gone. So it seems the issue has already been fixed on latest main.

**Comment by artem-lunarg** [comment]
I’m not sure which specific change fixed this, but I also run few tests that implement this scenario and they all pass so far.

**Comment by artem-lunarg** [comment]
Summary to conclude the work on this item. I tried the latest code and also tested the `sdk-1.3.236.0` release (https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/e2ea0836629a9229fa1650e33da8b78885e5de3f). I can't reproduce the issue both on windows and linux. Below is a test I used to verify this item. It does not reproduce the issue, so it was not added as a regression test.
```
TEST_F(VkSyncValTest, CopyBufferToImage) {
    TEST_DESCRIPTION("Positive test of copy buffer to image");

    SetTargetApiVersion(VK_API_VERSION_1_3);
    VkValidationFeatureEnableEXT enables[] = {
        VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT, VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT,
        VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXT, VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_RESERVE_BINDING_SLOT_EXT};
    VkValidationFeaturesEXT validation_features = {
        VK_STRUCTURE_TYPE_VALIDATION_FEATURES_EXT, nullptr, (uint32_t)std::size(enables), enables, 0, nullptr};
    InitFramework(nullptr, &validation_features);
    if (DeviceValidationVersion() < VK_API_VERSION_1_3) {
        GTEST_SKIP() << "At least Vulkan version 1.3 is required";
    }

    auto synchronization2 = LvlInitStruct<VkPhysicalDeviceSynchronization2Features>();
    auto features2 = GetPhysicalDeviceFeatures2(synchronization2);
    if (synchronization2.synchronization2 == VK_FALSE) {
        GTEST_SKIP() << "synchronization2 feature is not available";
    }
    ASSERT_NO_FATAL_FAILURE(InitState(nullptr, &features2));

    auto ci = LvlInitStruct<VkImageCreateInfo>();
    ci.imageType = VK_IMAGE_TYPE_2D;
    ci.format = VK_FORMAT_R8_UINT;
    ci.extent = {32, 32, 1};
    ci.mipLevels = 1;
    ci.arrayLayers = 1;
    ci.samples = VK_SAMPLE_COUNT_1_BIT;
    ci.tiling = VK_IMAGE_TILING_OPTIMAL;
    ci.usage =
        VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_STORAGE_BIT;
    ci.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    ci.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;

    VkImageObj image(m_device);
    image.init_no_mem(*DeviceObj(), ci);
    vk_testing::DeviceMemory mem;
    auto alloc_info = LvlInitStruct<VkMemoryAllocateInfo>();
    alloc_info.allocationSize = 32 * 1024 * 1024;
    m_device->phy().set_memory_type(image.memory_requirements().memoryTypeBits, &alloc_info, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    mem.init(*DeviceObj(), alloc_info);
    image.bind_memory(mem, 0);

    VkImageMemoryBarrier2 imageBarrier = {VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2};
    imageBarrier.srcStageMask = VK_PIPELINE_STAGE_TRANSFER_BIT;
    imageBarrier.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
    imageBarrier.dstStageMask = VK_PIPELINE_STAGE_TRANSFER_BIT;
    imageBarrier.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
    imageBarrier.oldLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    imageBarrier.newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
    imageBarrier.image = image.handle();
    imageBarrier.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
    VkDependencyInfo dependencyInfo = {VK_STRUCTURE_TYPE_DEPENDENCY_INFO};
    dependencyInfo.imageMemoryBarrierCount = 1;
    dependencyInfo.pImageMemoryBarriers = &imageBarrier;

    VkBufferImageCopy copy = {};
    copy.imageSubresource.layerCount = 1;
    copy.imageSubresource.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
    copy.imageExtent.depth = 1;
    copy.imageExtent.height = 32;
    copy.imageExtent.width = 32;

    VkMemoryPropertyFlags reqs =
        VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT | VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT;

    m_commandBuffer->begin();
    VkBufferObj buffer;
    buffer.init_as_src(*m_device, 4 * 1024 * 1024, reqs);
    void* buffer_ptr = buffer.memory().map();
    *reinterpret_cast<uint8_t*>(buffer_ptr) = 123;
    vk::CmdPipelineBarrier2(m_commandBuffer->handle(), &dependencyInfo);
    vk::CmdCopyBufferToImage(m_commandBuffer->handle(), buffer.handle(), image.handle(), VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &copy);
    m_commandBuffer->end();
}
```

**Comment by jagoly** [comment]
I'm still getting this same issue after updating to the latest release of the SDK (29th march), on arch.

For my sanity, I enabled sync validation on Sascha Willems' demo project, and the texture example hits the exact same issue as my and the OP's code.

I haven't tried building the SDK myself, but the OP believes that this fixed the issue, so unless that change didn't make it to the release I'm not sure what's going on. Maybe an issue with arch/manjaro packaging?

**Comment by artem-lunarg** [comment]
@jagoly, can you please confirm that the issue was reproduced on this sample app:
https://github.com/SaschaWillems/Vulkan/blob/master/examples/texture/texture.cpp

**Comment by jagoly** [comment]
Yes, that's the sample I was talking about. I just tested with the latest [commit](https://github.com/SaschaWillems/Vulkan/commit/fa0e3485d00c73b0637b914e6510d142ee2e5fdf) and the issue persists. The only changes I have made are a couple of lines in vulkanexamplebase.cpp to enable sync validation.

The first error is actually triggered by https://github.com/SaschaWillems/Vulkan/blob/fa0e3485d00c73b0637b914e6510d142ee2e5fdf/base/VulkanUIOverlay.cpp#L157, so I expect that this actually affects most of the samples.

There are a bunch of WRITE_AFTER_WRITE errors after calls to vkCmdPipelineBarrier and vkCmdBeginRenderPass, but I suspect they are the same issue. These errors occur in both the sample and my project.

**Comment by artem-lunarg** [comment]
I tested texture sample with the latest Ubuntu packages and it works without synchronization validation errors. I can't comment on other distributions since they are not officially supported and I also don't have access to arch, but it still should be possible to use the latest validation layers there.

It looks the issue might be with a version of the validation layer. One suggestion is to check that sdk installation indeed has proper version of the validation layer.
For example, `/usr/share/vulkan/explicit_layer.d/VkLayer_khronos_validation.json` (that's location on Ubuntu) should specify version 1.3.243 for the latest sdk:
```
{
    "file_format_version": "1.2.0",
    "layer": {
        "name": "VK_LAYER_KHRONOS_validation",
        "type": "GLOBAL",
        "library_path": "libVkLayer_khronos_validation.so",
        "api_version": "1.3.243",
        "implementation_version": "1",
```

If there is an issue with the packages then probably the simplest way is to build the validation layer from source (https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/BUILD.md#building-overview). And then set `VK_LAYER_PATH` environment variable to specify directory path where `VkLayer_khronos_validation.json` is located in the source tree.

**Comment by artem-lunarg** [comment]
@Pilzschaf there was indeed a bug and it was fixed in the above PR.
It's a shame I did not manage to reproduce it the first time 😉
