### ISSUE TITLE
ValidateAccessMaskPipelineStage in core_validation.cpp has wrong masks for raytracing

### ISSUE THREAD

**Issue by jzulauf-lunarg** [KhronosGroup/Vulkan-ValidationLayers#532]
From [LunarXChange #819 - ValidateAccessMaskPipelineStage in core_validation.cpp has wrong masks for raytracing](https://vulkan.lunarg.com/issue/view/5c172b6ce46ffe4fab562274)

> The function ValidateAccessMaskPipelineStage() in core_validation.cpp has the wrong masks in AccessMaskToPipeStage for the new NVIDIA raytracing. The enrtry for VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_NV only contains VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_NV, but according to spec should also contain VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD _BIT_NV. This happens in my code when i want to make a barrier between vertex data uploaded to a buffer and building an acceleration structure referencing that vertex data.

**Comment by jeffbolznv** [comment]
@pdaniell-nv offered to take this one.

**Comment by jzulauf-lunarg** [comment]
I see it.
