### ISSUE TITLE
Multiview validation incorrectly triggered when VK_KHR_multiview is used with old VkRenderPassCreateInfo

### ISSUE THREAD

**Issue by annop-np** [KhronosGroup/Vulkan-ValidationLayers#5334]
**Environment:**
 - OS: Oculus Quest 2
 - GPU: Adreno (TM) 650
 - SDK or header version if building from repo:
 - Options enabled (synchronization, best practices, etc.):

**Describe the Issue**

Various validation errors related to multiview features triggered, seemingly erroneously and incorrectly, when VkRenderPassMultiviewCreateInfo (VK_KHR_multiview) is used to implement Multiview with VkRenderPassCreateInfo via pNext structure.

The feature appears to be activated correctly despite the error messages, both during normal runtime and while being investigated in RenderDoc, and no graphical issue is seen.

According to the error message (VUID-VkSubpassDescription2-multiview-06558), the "viewMask" is set to non-zero while multiview feature is not enabled. However, the feature is enabled, via the extension, and query to VkPhysicalDeviceMultiviewFeatures indicate it is supported.

Additionally, please noted that the returned error ID suggest the issue is in VkSubpassDescription2, which I DO NOT use. The feature is enabled and implemented via extension and the original version of VkSubpassDescription and VkRenderPassCreateInfo, which has no "viewMask".

Possibly related to Issue# 4061 (https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4061)?

**Expected behavior**

No error message is triggered if there is no actual error, or a correct message used.

**Valid Usage ID**
VUID-VkSubpassDescription2-multiview-06558
VUID-VkShaderModuleCreateInfo-pCode-01091

**Additional context**

<details>
<summary>code or terminal output</summary>

```
>|error|validation Id = VUID-VkSubpassDescription2-multiview-06558 (1150517470):
 |Objects: unnamed (type: device, handle: 517066375616)
 |Validation Error: [ VUID-VkSubpassDescription2-multiview-06558 ] Object 0: handle = 0x78638ec1c0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x449380de | vkCreateRenderPass(): pCreateInfo->pSubpasses[0].viewMask is 3, but multiview feature is not enabled. The Vulkan spec states: If the multiview feature is not enabled, viewMask must be 0 (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkSubpassDescription2-multiview-06558)
```
```
>|error|validation Id = VUID-VkShaderModuleCreateInfo-pCode-01091 (-1480880714):
 |Objects: unnamed (type: device, handle: 517066375616)
 |Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-01091 ] Object 0: handle = 0x78638ec1c0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xa7bb8db6 | vkCreateShaderModule(): The SPIR-V Capability (MultiView) was declared, but none of the requirements were met to use it. The Vulkan spec states: If pCode declares any of the capabilities listed in the SPIR-V Environment appendix, one of the corresponding requirements must be satisfied (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-01091)
```

</details>

**Comment by ncesario-lunarg** [comment]
@annop-np is the `VkPhysicalDeviceMultiviewFeaturesKHR` struct with `multiview` set to true getting passed in at `vkCreateDevice` time? There are some features that are "special" and are implicitly enabled by enabling the extension, but I did not think this was one of them.

**Comment by spencer-lunarg** [comment]
agree with @ncesario-lunarg that this most likely is just not having the `multiview` feature not [being enabled](https://github.com/KhronosGroup/Vulkan-Guide/blob/main/chapters/enabling_features.adoc) at `vkCreateDevice` time

There is `VkPhysicalDeviceVulkan11Features::multiview` or `VkPhysicalDeviceMultiviewFeaturesKHR::multiview` that can be used (both work)

**Comment by spencer-lunarg** [comment]
so not all feature are "free" to enable, for example, if you enable ` robustBufferAccess` on some device, it will make performance worse... sometime a device will have the features enabled automatically, but the features allow this to be toggled if needed

> The use of "can" instead of "must" seem to imply it is default to enable to all device, unless the feature struct is added?

So it is backward, nothing is enabled by "default" in Vulkan (unless explicitly stated) and you need to enable it

I am going to close this issue as there is nothing left to do in the Validation Layers, if you feel the Spec needs improvement that belongs in the https://github.com/KhronosGroup/Vulkan-Docs/ repo
