### ISSUE TITLE
Ignoring VUID-VkSubmitInfo-pNext-04120 error when no VkProtectedSubmitInfo structure

### ISSUE THREAD

**Issue by IgorNazarovSamsungElectronics** [KhronosGroup/Vulkan-ValidationLayers#5363]
**Describe the situation in which you encountered the missing validation**

Submitting command buffer **without** `VkProtectedSubmitInfo` structure in the `VkSubmitInfo::pNext` **skips validation check**.
As the result, it allows submitting **protected** command buffer with the **unprotected** submission.

Vulkan spec:
```
    protectedSubmit specifies whether the batch is protected.
    If protectedSubmit is VK_TRUE, the batch is protected.
    If protectedSubmit is VK_FALSE, the batch is unprotected.
    If the VkSubmitInfo::pNext chain does not include this structure, the batch is unprotected.
```

**Valid Usage IDs requested**

VUID-VkSubmitInfo-pNext-04120

**Comment by juan-lunarg** [comment]
Thanks for the fix @IgorNazarovSamsungElectronics :+1:

**Comment by i-nazarov-samsung** [comment]
@juan-lunarg Glad to help.
