### ISSUE TITLE
vkCreateShaderModule error when Int64ImageEXT was declared and properly supported

### ISSUE THREAD

**Issue by mboucha1** [KhronosGroup/Vulkan-ValidationLayers#5379]
**Environment:**
 - OS: Windows 10
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - SDK or header version if building from repo: 1.3.239.0 (with runtime version 1.3.239)

**Describe the Issue**

Getting a vkCreateShaderModule validation error when trying to create a shader module with the following shader code:

void Atomic64Max(RWTexture2D<uint64_t> uav, uint2 position, uint64_t value)
{
    uint64_t originalValue = 0;
    InterlockedMax(uav[position], value, originalValue);
}

**Expected behavior**

Not expecting validation errors.

Based on documentation here:
https://vulkan.lunarg.com/doc/view/1.3.224.1/windows/1.3-extensions/vkspec.html#spirvenv-capabilities-table
https://github.com/KhronosGroup/Vulkan-Guide/blob/main/chapters/atomics.adoc

For 'Int64Atomics', following flags should be enabled (those are enabled on my PC):
[VkPhysicalDeviceVulkan12Features::shaderBufferInt64Atomics]
[VkPhysicalDeviceVulkan12Features::shaderSharedInt64Atomics]
[VkPhysicalDeviceShaderImageAtomicInt64FeaturesEXT::shaderImageInt64Atomics]

**Valid Usage ID**

Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-01091 ] Object 0: handle = 0x5b19fa0, name = Device, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xa7bb8db6 | vkCreateShaderModule(): The SPIR-V Capability (Int64ImageEXT) was declared, but none of the requirements were met to use it. The Vulkan spec states: If pCode declares any of the capabilities listed in the SPIR-V Environment appendix, one of the corresponding requirements must be satisfied (https://vulkan.lunarg.com/doc/view/1.3.239.0/windows/1.3-extensions/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-01091)

**Comment by juan-lunarg** [comment]
We have testing that covers this extension and is currently passing:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/1ca987ba3c2f623f8ba6172de23f39d1830766bd/tests/positive/shaderval.cpp#L1153

Are you sure you have properly enabled the feature?

**Comment by juan-lunarg** [comment]
Closing for now since this appears to be a user error.

If more assistance is needed please visit the vulkan discord.

**Comment by mboucha1** [comment]
I did confirmed that my shader did worked as expected when used with the above ShaderImageAtomicInt64 test.

I revisited my user code and founded out that the VkPhysicalDeviceFeatures2::pNext which was pointing to VkPhysicalDeviceShaderImageAtomicInt64FeaturesEXT was overriten later on by something else preventing proper setup.

Thanks for pointing me out the test, it was very useful.
