### ISSUE TITLE
QueueSubmit Time Validation of Update After Bind Descriptors

### ISSUE THREAD

**Issue by jzulauf-lunarg** [KhronosGroup/Vulkan-ValidationLayers#539]
VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT binding cannot be validated at command buffer record time as the binding contents are subject to change.  Validation thus must be done at QueueSubmit time.

**Comment by jzulauf-lunarg** [comment]
Triage notes:  As only "first" and "last" image layout states are tracked by the command buffer meta-data in core_validation, there is currently insufficient information for validating descriptor layout vs. image layout at queue submit time.  Image layout changing events will need to be tracked within the command buffer, and descriptor validations *skipped* at record time need to be tracked with a reference to the then current state of the image layout transition operations in order to determine the reconstruct the image layout at the time of the call referencing the descriptor.

@tobine -- look correct? (I have a somewhat length example of why tracking could be needed if you think it could be useful)

**Comment by tobine** [comment]
Yes, this looks right-on @jzulauf-lunarg
