### ISSUE TITLE
Could validate stageFlags for INPUT_ATTACHMENT?

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#54]
**Issue by [toten](https://github.com/toten) (MIGRATED)**
_Friday Nov 03, 2017 at 07:03 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2178_

----

My case is: 

When creating VkDescriptorSetLayoutBinding structure, the descriptorType is VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT; from the spec, the stageFlags must be VK_SHADER_STAGE_FRAGMENT_BIT. However I forgot setting the stageFlags (partially due to the code is originally copied from others), so the input_attachment reading in fragment shader returns black. It took me one or two hours to finally figure out where the problem is.

Just curious if the core-validation layer or parameter-validation layer could check this, and help to locate the problem quickly. 

Thanks a lot.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/tobine"><img src="https://avatars0.githubusercontent.com/u/7526739?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tobine](https://github.com/tobine) (MIGRATED)**
_Friday Nov 03, 2017 at 17:31 GMT_

----

This is missing check VALIDATION_ERROR_04e00bcc.

@toten note from [spec](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkDescriptorSetLayoutBinding-descriptorType-01510) that stageFlags can be 0 or *FRAGMENT_BIT:

`If descriptorType is VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT and descriptorCount is not 0, then stageFlags must be 0 or VK_SHADER_STAGE_FRAGMENT_BIT`

Not sure what your stageFlags was, but if it was 0, the new validation check won't catch that case.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/chrisforbes"><img src="https://avatars1.githubusercontent.com/u/128877?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Thursday Nov 09, 2017 at 22:03 GMT_

----

@tobine can we justify emitting a warning for stageFlags=0? We already have the option of descriptorCount=0 for making unusable placeholder bindings.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/tobine"><img src="https://avatars0.githubusercontent.com/u/7526739?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tobine](https://github.com/tobine) (MIGRATED)**
_Friday Nov 10, 2017 at 16:37 GMT_

----

Well, if @toten had stageFlags=0, then I'd say the fact that the warning would have been a help in that case justifies it. At least until/unless someone else complains about the warning with a reasonable use case that requires stageFlags=0. I can't think of a good case offhand as the descriptorCount=0 option is already there as you said for unusable bindings.
@toten please confirm if your stageFlags was 0 and we can put in a warning for that case to assist other users in the future.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/toten"><img src="https://avatars1.githubusercontent.com/u/14150200?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [toten](https://github.com/toten) (MIGRATED)**
_Monday Nov 13, 2017 at 02:20 GMT_

----

I used the api-dump layer (also debug) and could confirm the stageFlags was 0. The input-attachment loading returns black color when stageFlags was 0. 

When I explicitly set to VK_SHADER_STAGE_FRAGMENT_BIT, input-attachment loading works as expected. BTW, the api-dump layer returns:
stageFlags:                     VkShaderStageFlags = 16 (VK_SHADER_STAGE_FRAGMENT_BIT | VK_SHADER_STAGE_ALL_GRAPHICS | VK_SHADER_STAGE_ALL)
It looks a little strange that | VK_SHADER_STAGE_ALL_GRAPHICS | VK_SHADER_STAGE_ALL ??

Thanks all the help!

**Comment by mark-lunarg** [comment]
Moving this warning issue to best practices tracking issue, #24.
