### ISSUE TITLE
vkCreateSampler issue when it is not called

### ISSUE THREAD

**Issue by motangish** [KhronosGroup/Vulkan-ValidationLayers#543]
Validation layer outputs vkCreateSampler issue but vkCreateSampler is not called anywhere in the [code](https://vulkan-tutorial.com/code/16_swap_chain_recreation.cpp).

`validation layer: vkCreateSampler(): Anisotropic sampling feature is not enabled, pCreateInfo->anisotropyEnable must be VK_FALSE. The Vulkan spec states: If the anisotropic sampling feature is not enabled, anisotropyEnable must be VK_FALSE (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkSamplerCreateInfo-anisotropyEnable-01070)`

VulkanSDK 1.1.92.1

**Comment by daveh-lunarg** [comment]
@motangish, please verify that you have no overlay processes running. We've seen similar errors on Win10 with Steam overlay enabled, when the Steam runtime had not been updated recently. Some older versions of overlays can cause this, and the validation layers cannot differentiate between your app and the overlay activity.
