### ISSUE TITLE
Format not matching data, but validation layers not responding.

### ISSUE THREAD

**Issue by milosrs** [KhronosGroup/Vulkan-ValidationLayers#544]
People on KhronosDevs Slack told me to post an issue about this. Validation layers didn't report that I had used a wrong format for attributeDescriptions.format. More on this in my stack question.

https://stackoverflow.com/questions/53915722/what-causes-textures-to-be-rendered-on-each-triangle-of-a-polygon/53918801#53918801

**Comment by jzulauf-lunarg** [comment]
@milosrs  -- From my reading of the spec, your error (though frustrating) isn't a violation of the spec.  

One can certainly define a 4 component location VkVertexInputAttributeDescription and fetch only 2 components of them in a given shader. The rules for this are given in Table 30 in the [Vertex Attributes](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#fxvertex-attrib) section of the Vulkan spec.  One can imagine uses for this (for example two differ shaders which select different sub-portions of the same input attribute).

Even if one specifies a vec4 location with a `VkVertexInputAttributeDescription ` with only 2 components, the spec indicates that default values are used for the missing components.

Closing as "works as designed" but feel free to re-open if you think I'm in error here.
