### ISSUE TITLE
Validation layer doesn't check an ability of copy commands for given image format

### ISSUE THREAD

**Issue by Andreyogld3d** [KhronosGroup/Vulkan-ValidationLayers#545]
Hello!
According Vulkan specification:

19.4. Copying Data Between Buffers and Images
The format features of dstImage must contain VK_FORMAT_FEATURE_TRANSFER_DST_BIT.

But Mali GPU G71 with format VK_FORMAT_ETC2_*_BLOCK  has no support of VK_FORMAT_FEATURE_TRANSFER_DST_BIT flag:

`(VkFormatProperties::optimalTilingFeatures & VK_FORMAT_FEATURE_TRANSFER_DST_BIT) == 0`

I have no any error message from Validation Layer.

Best Regards, Andrey.

**Comment by jzulauf-lunarg** [comment]
@Andreyogld3d -- the spec source document [chapters/copies.txt](https://github.com/KhronosGroup/Vulkan-Docs/blob/master/chapters/copies.txt#L883) restricts this VU only to Vulkan 1.1 api level or newer or if `VK_KHR_maintenance1` is enabled.  

Can you verify that either `VkApplicationInfo::apiVersion` or  `VK_KHR_maintenance1` in your test case?

**Comment by Andreyogld3d** [comment]
Hi @jzulauf-lunarg, VK_KHR_maintenance1 is not enabled and Vulkan Version is 1.0.

**Comment by Andreyogld3d** [comment]
Hi @jzulauf-lunarg, Mali G71 GPU doesn't support VK_KHR_maintenance1 extension and Vulkan 1.1
