### ISSUE TITLE
Video encode extension issues

### ISSUE THREAD

**Issue by neurotok** [KhronosGroup/Vulkan-ValidationLayers#5459]
Hello @aqnuep execution of getPhysicalDeviceVideoFormatPropertiesKHR with single VK_VIDEO_CODEC_OPERATION_ENCODE_H264_BIT_EXT profile ends up with VK_ERROR_VALIDATION_FAILED_EXT result

Problem first discovered while working on CTS encode test suite, but i can be easily replicated on the vk_video_encode nvidia sample.

To run the program im using:
`-i ./clip-a.yuv --width 176 --height 144 --startFrame 0 --numFrames 30`

which attached clip:
[clip-a.zip](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/11001143/clip-a.zip)

**Comment by aqnuep** [comment]
Thank you for your feedback, but this is expected, as currently there is no support for video encode in the validation layers yet.

Validation layer support for video encode will be available only after the corresponding extensions are finalized, as currently all the video encode extension specifications are provisional and are subject to change.
