### ISSUE TITLE
API dump layer: Can object names be included alongside handles in API traces?

### ISSUE THREAD

**Issue by kbiElude** [KhronosGroup/Vulkan-ValidationLayers#548]
Here's an example excerpt from the API dump:

Thread 1, Frame 1:
vkBindBufferMemory(device, buffer, memory, memoryOffset) returns VkResult VK_SUCCESS (0):
    device:                         VkDevice = 000002713BF2D870
    buffer:                         VkBuffer = 0000000000000029
    memory:                         VkDeviceMemory = 0000000000000021
    memoryOffset:                   VkDeviceSize = 4419584

It would be tremendously useful if object handles were followed by names assigned to the corresponding objects via EXT_debug_utils or the other deprecated extension.

**Comment by karl-lunarg** [comment]
I've reposted this to LunarG/VulkanTools since that's where the API Dump layer is currently hosted.
