### ISSUE TITLE
Updated spec language related to graphics pipeline sub-state

### ISSUE THREAD

**Issue by ncesario-lunarg** [KhronosGroup/Vulkan-ValidationLayers#5490]
Spec changes in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5573 will potentially require several VUIDs to be updated (see VUIDs referenced in WG MR).

**Comment by spencer-lunarg** [comment]
after countless spec questions, issues raised, and PRs... I'm claiming this "done" until someone points out which parts are still left (some missing parts are being tracked in other issues as well)
