### ISSUE TITLE
Android builds switching to use libc++_shared.so breaks some workflows

### ISSUE THREAD

**Issue by solidpixel** [KhronosGroup/Vulkan-ValidationLayers#5491]
**Environment:**
 - OS: Android

**Describe the Issue**

Android allows layers to be injected into an application from outside of the APK, which used to work on older binary releases where the C++ library was statically linked with the layer. The recent move for binary releases on GitHub  to use a separate `libc++_shared.so` breaks this workflow as the Android dynamic linker cannot resolve the extra library even though the Vulkan loader finds the layer itself.

This workflow is particularly important for developer tools where we want to inject the layer at runtime without modifying the application APK, and for IHV/ODM workflows where we are often working with pre-existing APKs that cannot be rebuilt. 

**Expected behavior**

The Android workflow for installing and enabling a global layer is:

```
adb push /host/path/to/libVkLayer_khronos_validation.so /data/local/tmp
adb shell run-as <com.example.app> cp /data/local/tmp/libVkLayer_khronos_validation.so .
adb shell settings put global enable_gpu_debug_layers 1
adb shell settings put global gpu_debug_app <com.example.app>
adb shell settings put global gpu_debug_layers VK_LAYER_KHRONOS_validation
```

This works fine with the older statically linked layers from earlier releases. I've tried pushing `libc++_shared.so` to `/data/data/<com.example.app>/`, `/data/data/<com.example.app/lib/`, and `/data/data/<com.example.app/lib/arm64-v8a/` and none of them seem to resolve the library so the layer load fails. Error is:

```
failed to load layer library '/data/user/0/com.example.app/libVkLayer_khronos_validation.so': dlopen failed: library "libc++_shared.so" not found: 
```

Please can Android prebuilts revert back to statically linked C++ libraries, or at least provide both variants?

**Comment by mark-lunarg** [comment]
@jeremyg-lunarg.  We'll discuss reverting to static C++ libs, but for the moment there are simple instructions in [BUILD.md](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/BUILD.md#android-build) for modifying the android build to use statically linked C++ libraries.

**Comment by solidpixel** [comment]
Thanks for the quick response folks.

**Comment by mark-lunarg** [comment]
Using the `build-android\build_all.sh` script will now result in binaries built with the static C++ standard library.  Internal and Github CI do not use this script and will continue to use the shared library for testing.  Beginning with the next SDK and going forward, the Android Release Binaries will also be built with the static version of the library.

**Comment by jmccarthy634** [comment]
It looks like the change to make the release binaries use the static C++ libs didn't take? I've grabbed the 1.3.250.0 release and it was still compiled with shared C++ libs, which causes our application to crash as soon as it tries to load the layers. I needed to rebuild myself forcing `ANDROID_STL_TYPE=STATIC`.

**Comment by juan-lunarg** [comment]
FYI @mark-lunarg and @johnzupin

**Comment by johnzupin** [comment]
New binaries to statically include lib c++ libs have been attached to the release.
