### ISSUE TITLE
Missing check when dynamic rendering's `vkCmdEndRendering` is called without beginning with `vkCmdBeginRendering`.

### ISSUE THREAD

**Issue by nikitablack** [KhronosGroup/Vulkan-ValidationLayers#5492]
**Describe the situation in which you encountered the missing validation**

- Begin first rendering with `vkCmdBeginRendering()`.
- Begin second rendering with `vkCmdBeginRendering()`.
- End second rendering with `vkCmdEndRendering()`.
- End first rendering with `vkCmdEndRendering()`. <- Segmentation fault happens here.

I accidentally started a rendering while already in a rendering. Instead of a warning/error, I'm receiving a frustrating segfault.

**Valid Usage IDs requested**

I believe `VUID-vkCmdEndRendering-None-06161` is the valid usage in this situation.

**Comment by spencer-lunarg** [comment]
Asking the Working Group, the spec doesn't seem to cover a case if you call `vkCmdBeginRendering` twice

Once a clarification is made, will fix the Validation Layers accordingly (and write tests)

**Comment by spencer-lunarg** [comment]
ok, so I realize ` VUID-vkCmdBeginRendering-renderpass` ( or normally`VUID-vkCmdBeginRenderPass-renderpass`) should have caught the 2nd `vkCmdBeginRendering` 

So my question is did you not get that error? (or ` VUID-vkCmdEndRendering-renderpass` on the 2nd ending?)

**Comment by nikitablack** [comment]
No, the only thing I get is a segfault on the 2nd ending.

**Comment by spencer-lunarg** [comment]
opened a PR, we were missing the check, wrote some regression tests

Thanks for raising the issue!
