### ISSUE TITLE
Extended dynamic state crashes with validation layers enabled (de-referenced null pointer).

### ISSUE THREAD

**Issue by crud89** [KhronosGroup/Vulkan-ValidationLayers#5497]
**Environment:**
 - OS: Windows 10 x64
 - GPU: NVidia 1080 Ti (up-to-date driver, i.e., 531.41)
 - SDK or header version if building from repo: 1.3.239.0

**Describe the Issue**

When using extended dynamic state to set viewports and/or scissors with validation enabled, there is a crash due to a de-referenced null-pointer. This can be reproduced in [Sascha Willems' vulkan examples](https://github.com/SaschaWillems/Vulkan). [This slightly altered](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/11055725/triangle.zip) triangle example source should be able to reproduce the issue. The source file needs to be dropped it into `./examples/triangle/` (replacing the existing source).

This error occurs (at least) for `vkCmdSetViewportWithCount` and `vkCmdSetScissorWithCount`.

**Expected behavior**

No crash.

**Additional context**

<details>
<summary>Disassembly of call to `vkCmdSetViewportWithCount`</summary>

```asm
00007FFDACD744A0  test        rcx,rcx
00007FFDACD744A3  je          vkCmdSetViewportWithCount+1Ch (07FFDACD744BCh)
00007FFDACD744A5  mov         rax,qword ptr [rcx]  
00007FFDACD744A8  test        rax,rax  
00007FFDACD744AB  je          vkCmdSetViewportWithCount+1Ch (07FFDACD744BCh)
00007FFDACD744AD  mov         r9,10ADED040410ADEDh 
00007FFDACD744B7  cmp         qword ptr [rax],r9 
00007FFDACD744BA  je          vkCmdSetViewportWithCount+1Eh (07FFDACD744BEh)
00007FFDACD744BC  xor         eax,eax  
00007FFDACD744BE  mov         rax,qword ptr [rax+560h]  
...
00007FFDACE107A0  jmp         rax   
```

The last `mov` will cause rax to be set to null, which is later attempted to be jumped to.
</details>

**Comment by spencer-lunarg** [comment]
So from what I can see, you never enabled just set`VkPhysicalDeviceExtendedDynamicStateFeaturesEXT::extendedDynamicState` to `true`, I assume you made sure it was supported?

If you are not using Vulkan 1.3 you need to call `vkGetDeviceProcAddr(device, "vkCmdSetViewportWithCountEXT")` to get a pointer to this function

**Comment by crud89** [comment]
The extension is enabled in the constructor (`VulkanExample`), from where it is passed to the pNext-Chain:

```cxx
extendedDynamicStateFeatures.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTENDED_DYNAMIC_STATE_FEATURES_EXT;
extendedDynamicStateFeatures.pNext = nullptr;
extendedDynamicStateFeatures.extendedDynamicState = true;
```

If it is not enabled, the validation layer warn about this (which is expected), though the crash still occurs.

**Comment by spencer-lunarg** [comment]
>  I am using the latest SDK release (as of yesterday), so Vulkan 1.3.

Does your Driver/GPU support Vulkan 1.3? You need a Device version of 1.3, if not, the driver won't know about the `vkCmdSetViewportWithCount` (without `EXT`) function pointer

**Comment by crud89** [comment]
Yes, I've updated to the latest NVidia driver before opening this issue and the calls succeed without the validation layers enabled.

**Comment by spencer-lunarg** [comment]
Ok, so I grabbed down the ToT examples and applied your `triangle.cpp` diff and tried running (Intel Xe - Vulkan 1.3)

I was first getting error creating the Pipeline because it wasn't `VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT` with the extension not enabled

I then went

```patch
	VulkanExample() : VulkanExampleBase(ENABLE_VALIDATION)
	{
		extendedDynamicStateFeatures.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTENDED_DYNAMIC_STATE_FEATURES_EXT;
		extendedDynamicStateFeatures.pNext = nullptr;
		extendedDynamicStateFeatures.extendedDynamicState = true;

		this->deviceCreatepNextChain = &extendedDynamicStateFeatures;

+		apiVersion = VK_API_VERSION_1_3;
```

and I was able to run the example with the Validation Layers

**Comment by crud89** [comment]
That fixed it. Darn, I actually did not remember that you have to set the API version explicitly, because I did this only once before. Sorry for the inconvenience and thanks a lot! 🎉

**Comment by spencer-lunarg** [comment]
No problem, glad to know it is just "Vulkan being `fun`" and not a VVL bug :smile:
