### ISSUE TITLE
Enhancement: vkCmdBindDescriptorSets : validate if pipelineBindPoint matches layout targets

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#55]
**Issue by [TiemoJung](https://github.com/TiemoJung) (MIGRATED)**
_Monday Nov 13, 2017 at 19:57 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2204_

----

Hi,

i just slipped over a subtle error, passing accidentally VK_PIPELINE_BIND_POINT_COMPUTE as bind point for descriptors that where meant for VK_PIPELINE_BIND_POINT_GRAPHICS.
It should be possible to check pipelineBindPoint  against the targets of the supplied pipeline layout to report a use error.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/chrisforbes"><img src="https://avatars1.githubusercontent.com/u/128877?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Tuesday Nov 14, 2017 at 18:19 GMT_

----

We don't really know which bind point a pipeline layout (or descriptor set layout) is intended for-- it's possible to use the same across both graphics and compute.

How would this work-- are you suggesting that we look at the stage flags of each `VkDescriptorSetLayoutBinding` and determine whether which bind points the layout is /at all/ useful for?

**Comment by karl-lunarg** [comment]
<a href="https://github.com/TiemoJung"><img src="https://avatars2.githubusercontent.com/u/11774679?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [TiemoJung](https://github.com/TiemoJung) (MIGRATED)**
_Saturday Nov 18, 2017 at 05:48 GMT_

----

> How would this work-- are you suggesting that we look at the stage flags of each VkDescriptorSetLayoutBinding and determine whether which bind points the layout is /at all/ useful for?

Yes

**Comment by karl-lunarg** [comment]
<a href="https://github.com/mark-lunarg"><img src="https://avatars2.githubusercontent.com/u/7252958?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mark-lunarg](https://github.com/mark-lunarg) (MIGRATED)**
_Tuesday Nov 21, 2017 at 15:10 GMT_

----

This seems like a good candidate for the assistant layer -- any objections to adding it to that worklist?

**Comment by jzulauf-lunarg** [comment]
@TiemoJung is there a repro case for this.

The compatibility of the stage flags with the shader usage is validated (vs. the pipeline layout) at pipeline creation time. 

We check compatibility of the bound descriptor set with the pipeline layout at bind time and draw/dispatch time.

If this is failing, there's a bug in that validation.

**Comment by jzulauf-lunarg** [comment]
@TiemoJung -- pinging.  Is this still an open issue? Is there a reproduction case where an error is failing to be produced?

**Comment by TiemoJung** [comment]
Hi,
at the time it was just a idea of a check that could be done by the debug layers and if it was there when it was needed it had saved me a day of siffing through render logs.
The bug has been fixed since then and i have no other repo case for this.

**Comment by jzulauf-lunarg** [comment]
Triage notes:  This is a plain incomplete.  

VUID-VkGraphicsPipelineCreateInfo-layout-00756
> (pipeline) layout must be consistent with all shaders specified in pStages

VUID-VkComputePipelineCreateInfo-layout-00703
> (pipeline) layout must be consistent with the layout of the compute shader specified in stage

Given that VkDescriptorSetLayoutBinding::stageFlags  describe the valid stage usage for each binding, the valid stages for each binding used based on the static analysis of each shader can be compared for consistency with the binding stageFlags found in the descriptor set layout meta data stored by the validation layers -- by looking up the descriptor set layout from the pipeline layout binding definition .

**Comment by mark-lunarg** [comment]
Both of these VUIDs are implemented in shader validation.
