### ISSUE TITLE
VK_NV_raytracing: Acceleration structure descriptor set type mismatch

### ISSUE THREAD

**Issue by georgeouzou** [KhronosGroup/Vulkan-ValidationLayers#550]
Whenever a descriptor set layout is created with an acceleration structure layout binding, the validation layer output this message:

> Type mismatch on descriptor slot 0.0 (expected ``) but descriptor of type VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV

**Comment by jeffbolznv** [comment]
I think this should have been fixed by https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/515. @georgeouzou can you retry it?

**Comment by georgeouzou** [comment]
@jeffbolznv yes it is fixed now thanks, this problem does not happen with the latest build.
