### ISSUE TITLE
VK_LAYER_KHRONOS_validation can't be loaded due to undefined symbol

### ISSUE THREAD

**Issue by jansol** [KhronosGroup/Vulkan-ValidationLayers#5519]
**Environment:**
 - OS: Ubuntu 23.04
 - GPU: Intel Arc 770, AMD Radeon 7900XTX (separate machines, both using mesa 22.3 drivers)
 - SDK or header version if building from repo: 1.3.239.0-1
 - Options enabled (synchronization, best practices, etc.):

**Describe the Issue**

```console
$ vkcube --validate
ERROR : GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	/lib/x86_64-linux-gnu/libVkLayer_utils.so: undefined symbol: custom_stype_info

	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 0x55b3ffd18b80

ERROR : GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	Requested layer "VK_LAYER_KHRONOS_validation" failed to load!

	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 0x55b3ffd18b80

vkCreateInstance failed.

Do you have a compatible Vulkan installable client driver (ICD) installed?
Please look at the Getting Started guide for additional information.
```

**Expected behavior**

Vkcube runs with validation layers enabled.

**Comment by juan-lunarg** [comment]
Does this repro with tip of main?

**Comment by juan-lunarg** [comment]
`libVkLayer_utils` is not supported being built as a `.so`

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/9124f788b7de42a4b2589b7ede812dd887447f0c/layers/CMakeLists.txt#L17

`VkLayer_utils` is only to be used as a static library.

[This bug has been fixed in Debian's packaging](https://salsa.debian.org/xorg-team/vulkan/vulkan-validationlayers/-/commit/9a0d2a66b658367369202ba8ad552b7aff213515)

**Comment by juan-lunarg** [comment]
Apologies for any confusion this caused @jansol 

Essentially there are 2 Ubuntu packages. The ones managed by Debian and the ones managed by LunarG. We do our best to make sure everything is working everywhere. But sometimes stuff like this slips through the cracks.

FWIW using the packages from LunarG would address this:
https://vulkan.lunarg.com/sdk/home

**Comment by jansol** [comment]
Thanks for the pointer! I'll just wait for Ubuntu to pick up the fix then.

Unfortunately just using the LunarG packages is not an option for me since the shaderc from the vulkan sdk does not work with [Tauray](https://github.com/vga-group/tauray) due to missing some build options. Mixing and matching packages from both sources on the other hand is a royal pain to manage (if even possible, I'm not sure how strict the dependency definitions between packages are there) and I really don't have time to resolve issues with that every time someone on my team wants to update their system.
