### ISSUE TITLE
Array output causing UNASSIGNED-CoreValidation-Shader-NoAlphaAtLocation0WithAlphaToCoverage

### ISSUE THREAD

**Issue by romanl-g** [KhronosGroup/Vulkan-ValidationLayers#5520]
Hi,

We hit an issue in ANGLE where `glEnable(GL_SAMPLE_ALPHA_TO_COVERAGE);` together with `gl_FragData[0]` results in a validation failure:

```
UNASSIGNED-CoreValidation-Shader-NoAlphaAtLocation0WithAlphaToCoverage(ERROR / SPEC): msgNum: 621927094 - Validation Error: [ UNASSIGNED-CoreValidation-Shader-NoAlphaAtLocation0WithAlphaToCoverage ] Object 0: handle = 0x8190000000819, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x2511dab6 | fragment shader doesn't declare alpha output at location 0 even though alpha to coverage is enabled.
```

ANGLE repro: https://chromium-review.googlesource.com/c/angle/angle/+/4374098

The relevant part of the SPIR-V:
```
%5 = OpTypeFloat 32
%10 = OpTypeVector %5 4
%11 = OpConstant %2 8
%12 = OpTypeArray %10 %11
%13 = OpTypePointer Output %12
%14 = OpVariable %13 Output
```

The "== 4" check here is probably checking for the alpha channel:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/9124f788b7de42a4b2589b7ede812dd887447f0c/layers/core_checks/shader_validation.cpp#L408

But we're actually getting 8*4=32 components there because gl_FragData is an array[8]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/9124f788b7de42a4b2589b7ede812dd887447f0c/layers/state_tracker/shader_module.cpp#L799

Unsure if it's just `strip_array_level=false` that should be `true` or something else

**Comment by spencer-lunarg** [comment]
Side note: Currently trying to fix this VU so it has a proper VU in the spec as not sure what it is suppose to be https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5811

The `GetComponentsConsumedByType` has some issue which I am trying to work on/fix in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5481

I would be happy removing this check for now until it is properly added in the spec AND the `GetComponentsConsumedByType` logic is correctly implemented

**Comment by spencer-lunarg** [comment]
@romanl-g (cc @ShabbyX ) I for the time being removed the VU check for reason described above, keeping this issue open as I plan to correctly add this soon (and want to make sure it works for ANGLE correctly then too!)

**Comment by romanl-g** [comment]
Thanks!

**Comment by spencer-lunarg** [comment]
Update: The 1.3.251 spec has added these as proper VUs now

- `VUID-VkGraphicsPipelineCreateInfo-alphaToCoverageEnable-08891`
- `VUID-vkCmdDraw-alphaToCoverageEnable-08919`
- `VUID-vkCmdDraw-alphaToCoverageEnable-08920`
