### ISSUE TITLE
Failure behaviour for vkBindBufferMemory2 and vkBindImageMemory2

### ISSUE THREAD

**Issue by r-potter** [KhronosGroup/Vulkan-ValidationLayers#5527]
**Describe the Issue**

vkBindImageMemory2 and vkBindBufferMemory2 accept an array of buffers/images, and don't clearly specify what state objects are left in following a failure. In cases where buffer/image count > 1, shipping drivers leave these buffers in an indeterminate state, such that it's impossible for applications to know whether objects are bound or not. 

ValidationStateTracker::PostCallRecordBindImageMemory2KHR only updates the memory binding state on a successful call (i.e. it treats a failure as leaving all buffers/images unbound). Consequently, it views the following sequence as valid:

```
vkBindImageMemory2 - failure
vkBindImageMemory
```

**Expected behavior**

Validation layers should treat images/buffers used as arguments to vkBindImageMemory2 and vkBindBufferMemory2 as being in an indeterminate (possibly bound) state if the call fails, and the buffer/image count > 1

**Valid Usage ID**

"VUID-VkBindBufferMemoryInfo-buffer-07459", "buffer must not have been bound to a memory object"
"VUID-VkBindImageMemoryInfo-image-07460", "image must not have been bound to a memory object"
"VUID-vkBindBufferMemory-buffer-07459", "buffer must not have been bound to a memory object"
"VUID-vkBindImageMemory-image-07460", "image must not have been bound to a memory object"

**Additional context**

See below for more context:

https://github.com/KhronosGroup/Vulkan-Docs/issues/2086
https://gitlab.khronos.org/vulkan/vulkan/-/issues/3427
https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5818

**Comment by spencer-lunarg** [comment]
Update: `VK_KHR_maintenance6` now added a `VkBindMemoryStatusKHR` struct that can be used to get the real actual information from the driver
