### ISSUE TITLE
Add missing Video Query type VUs

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/Vulkan-ValidationLayers#5534]
missing 

-  VUID-vkCmdBeginQuery-queryType-04862
-  VUID-vkCmdBeginQueryIndexedEXT-queryType-04862

The work is mostly done in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4072

cc @aqnuep

**Comment by aqnuep** [comment]
These VUs are specific to video encode, which is still provisional.

As mentioned in other issues raised about video encode validation, it will only come together with the final specifications of the video encode extensions.

#4072 already targets completely out-of-date APIs, as `VK_QUERY_TYPE_VIDEO_ENCODE_BITSTREAM_BUFFER_RANGE_KHR` was removed and replaced with a more generic query type.

Please refrain from implementing video encode related validation, as the API and the specification is still work-in-progress, subject to change, and will be completed together with the specifications.

**Comment by spencer-lunarg** [comment]
Ok sounds good, thanks for the information and agree with with not spending time with it in provisional state
