### ISSUE TITLE
Validate non-acquired swapchain image use

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/Vulkan-ValidationLayers#5540]
History behind this

- original issue https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3426
- "fixed" https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3890
- ANGLE found issue https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3915
  - was reverted https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3928
- Attempted to fix again but PR got stale - https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4004

This should also get a proper VUID as well

**Comment by ziga-lunarg** [comment]
The original issue is #365
