### ISSUE TITLE
Issue with CoreChecks::TransitionSubpassLayouts when working with 3D or 2D array images

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/Vulkan-ValidationLayers#5552]
**Environment:**
 - OS: Windows 10
 - GPU: RTX 6000 Ada
 - SDK or header version if building from repo: 1.3.243.0 (downloaded from Web)
 - Options enabled (synchronization, best practices, etc.): 

**Describe the Issue**

When doing a renderpass with an attachment for 3D or 2D array image with an imageview created using a SubresourceRange of a subset of the image's layers (say, only 1 layer), the layout transition tracking in CoreChecks::TransitionSubpassLayouts is only applied to the layers listed by the SubresourceRange. But, the Vulkan spec states:

`When the VkImageSubresourceRange structure is used to select a subset of the slices of a 3D image’s mip level in order to create a 2D or 2D array image view of a 3D image created with VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT, baseArrayLayer and layerCount specify the first slice index and the number of slices to include in the created image view. Such an image view can be used as a framebuffer attachment that refers only to the specified range of slices of the selected mip level. However, any layout transitions performed on such an attachment view during a render pass instance still apply to the entire subresource referenced which includes all the slices of the selected mip level.`

**Expected behavior**

All of the layers of the image should be treated as transitioned, even if they aren't part of the SubresourceRange.

**Valid Usage ID**

UNASSIGNED-CoreValidation-DrawState-InvalidRenderpass

**Comment by spencer-lunarg** [comment]
@mbechard do you have the full error message the validation layers printed out?

**Comment by mbechard** [comment]
The error message is a step later, with:
`Validation Error: [ UNASSIGNED-CoreValidation-DrawState-InvalidRenderpass ] Object 0: handle = 0x2184a27d0d0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xa1662b9 | You cannot start a render pass using attachment 0 where the render pass initial layout is VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL and the previous known layout of the attachment is VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL. The layouts must match, or the render pass initial layout for the attachment must be VK_IMAGE_LAYOUT_UNDEFINED`

The incorrect tracking ends up with this errant error. The previous renderpass on layer 0 would have transitioned all slices to COLOR_ATTACHMENT_OPTIMAL, but when trying to start a renderpass targeting layer 1, it ends up with this error, thinking the other slices are still on SHADER_READ_OPTIMAL.

**Comment by mbechard** [comment]
This is still an issue with the latest SDK. Does the SpecChange tag mean the validation is correct, and the spec will change so that transitions only apply to the subresourceRange specified by the image view?

**Comment by spencer-lunarg** [comment]
> This is still an issue with the latest SDK.

Sorry, unfortunately we have not got around to fixing this yet

> Does the SpecChange tag mean the validation is correct

We are trying to get rid of all these "UNASSIGNED" VUs and have a proper VU in the spec that we can reference.

In the process of doing this, sometimes we find that the way we were validating it was slightly wrong. That is more up to the working group to help decide

**Comment by arno-lunarg** [comment]
I wrote a positive test in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6198 and I could not reproduce this issue. @mbechard maybe this new test does not match what you are doing?

**Comment by mbechard** [comment]
My apologies, it seems like this was a false positive on my testing side, as well as a mis-reading of the spec on my side. I thought the rule applied to 2d texture arrays as well, but I see now it only applied to 3d texture.
I thought I had also tested with 3d textures and had the incorrect error, but I'm unable to reproduce that now.
I'm very sorry about that.

**Comment by arno-lunarg** [comment]
No problem, on the contrary this issue allowed to add more coverage to our tests, something that is always appreciated!
