### ISSUE TITLE
False positive VUIDs reported when pipeline libraries are used and unused state is provided

### ISSUE THREAD

**Issue by ziga-lunarg** [KhronosGroup/Vulkan-ValidationLayers#5553]
The CTS test
dEQP-VK.pipeline.pipeline_library.misc.unused_shader_stages_include_tess
is an example of this. 

The tests creates a graphics pipeline library with only VK_GRAPHICS_PIPELINE_LIBRARY_VERTEX_INPUT_INTERFACE_BIT_EXT, and because VK_GRAPHICS_PIPELINE_LIBRARY_PRE_RASTERIZATION_SHADERS_BIT_EXT is not set, in parameter_validation_utils.cpp:2324 `pTessellationState` is set to `nullptr`. But the problem is that the shader stages include tessellation stages, which are not set to null and ignored so `VUID-VkGraphicsPipelineCreateInfo-pStages-00731` is being falsely reported.

**Comment by spencer-lunarg** [comment]
Yep, the issue is this VU has the statement which part needs to be included

I also realized looking at it that `VUID-VkGraphicsPipelineCreateInfo-rasterizerDiscardEnable-00750` and most of `VUID-VkGraphicsPipelineCreateInfo-pDynamicStates-*` will run into the same issue there as well
