### ISSUE TITLE
vkCreateSampler issue when it is not set up

### ISSUE THREAD

**Issue by MrGuardian** [KhronosGroup/Vulkan-ValidationLayers#5566]
**Environment:**
 - OS: `Windows 10 Pro 21H2 (build 19044.2728) x64`
 - GPU: `NVIDIA GeForce RTX 3080 (driver version 31.0.15.3141)`
 - SDK or header version if building from repo: `Vulkan SDK 1.3.239.00`
 - Options enabled (synchronization, best practices, etc.): not sure

**Describe the Issue**

I was following a tutorial on creating [my first triangle using Vulkan SDK](https://vulkan-tutorial.com/). When I get to the [swapchain recreation chapter](https://vulkan-tutorial.com/Drawing_a_triangle/Swap_chain_recreation) and wrote the code then launched the window and started to resize it, I got a spam of errors telling me to set `pCreateInfo->anisotropyEnable` to `VK_FALSE` during the creation of the sampler `vkCreateSampler()`. However in this tutorial we didn't use any textures (an by extension any samplers). Certainly there are no calls to `vkCreateSampler()` anywhere in my code and in this tutorial up to this stage. Maybe there are implicit samplers Vulkan creates but I imagine that would be against the main idea of Vulkan API to be as explicit as possible with the pipeline creation setup.

I encountered [a similar issue in the issue tracker](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/543) however what is proposed in that issue is not really applicable to my situation since my Steam is turned off completely and no services are running related to it.

I'm very new to Vulkan API and validation layer concepts so sorry if I ask too much. I only have an experience creating my own DX11 renderer several years ago so maybe I miss something important.

**Expected behavior**

No errors in a validation layer. Or a workaround to turn them off (without actually turning off the whole validation layer or severity levels) or a proposition for where can I look up the proper setup.

**Valid Usage ID**
`VUID-VkSamplerCreateInfo-anisotropyEnable-01070`
Not sure what to provide here, sorry, if this is incorrect. The validation layer output and surrounding messages included below.

**Additional context**

<details>
<summary>code or terminal output</summary>

```sh
available extensions:
        VK_KHR_surface
        VK_KHR_win32_surface
        VK_KHR_external_memory_capabilities
        VK_KHR_external_semaphore_capabilities
        VK_KHR_external_fence_capabilities
        VK_KHR_get_physical_device_properties2
        VK_KHR_get_surface_capabilities2
        VK_KHR_device_group_creation
        VK_EXT_swapchain_colorspace
        VK_KHR_surface_protected_capabilities
        VK_EXT_debug_report
        VK_EXT_debug_utils
        VK_NV_external_memory_capabilities
        VK_KHR_portability_enumeration
validation layer: windows_get_device_registry_files: GUID for 33 is not SoftwareComponent skipping
validation layer: Searching for ICD drivers named .\igvk64.dll
validation layer: Searching for ICD drivers named .\nvoglv64.dll
validation layer: Loading layer library C:\Libraries\VulkanSDK\1.3.239.0\Bin\.\VkLayer_khronos_validation.dll
validation layer: Loading layer library C:\Program Files (x86)\FPS Monitor\tools\.\fpsmonvk64.dll
validation layer: Loading layer library C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_50916785244854f2\.\nvoglv64.dll
GPU name selected: NVIDIA GeForce RTX 3080
validation layer: Validation Error: [ VUID-VkSamplerCreateInfo-anisotropyEnable-01070 ] Object 0: handle = 0x1b5548de8b0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x56f192bc | vkCreateSampler(): Anisotropic sampling feature is not enabled, pCreateInfo->anisotropyEnable must be VK_FALSE. The Vulkan spec states: If the samplerAnisotropy feature is not enabled, anisotropyEnable must be VK_FALSE (https://vulkan.lunarg.com/doc/view/1.3.239.0/windows/1.3-extensions/vkspec.html#VUID-VkSamplerCreateInfo-anisotropyEnable-01070)
validation layer: Validation Error: [ VUID-VkSamplerCreateInfo-anisotropyEnable-01070 ] Object 0: handle = 0x1b5548de8b0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x56f192bc | vkCreateSampler(): Anisotropic sampling feature is not enabled, pCreateInfo->anisotropyEnable must be VK_FALSE. The Vulkan spec states: If the samplerAnisotropy feature is not enabled, anisotropyEnable must be VK_FALSE (https://vulkan.lunarg.com/doc/view/1.3.239.0/windows/1.3-extensions/vkspec.html#VUID-VkSamplerCreateInfo-anisotropyEnable-01070)
validation layer: Validation Error: [ VUID-VkSamplerCreateInfo-anisotropyEnable-01070 ] Object 0: handle = 0x1b5548de8b0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x56f192bc | vkCreateSampler(): Anisotropic sampling feature is not enabled, pCreateInfo->anisotropyEnable must be VK_FALSE. The Vulkan spec states: If the samplerAnisotropy feature is not enabled, anisotropyEnable must be VK_FALSE (https://vulkan.lunarg.com/doc/view/1.3.239.0/windows/1.3-extensions/vkspec.html#VUID-VkSamplerCreateInfo-anisotropyEnable-01070)
...
```

I enable validation layers as follows:
```cpp
...

// Basic array of validation layers we want to enable
const std::vector<const char*> validationLayers = {
    "VK_LAYER_KHRONOS_validation"
};

...

void createLogicalDevice() {
  ...
  
  VkDeviceCreateInfo createInfo{};
  
  ...
  
  // enable validation layers for our device
  if (enableValidationLayers) {
      createInfo.enabledLayerCount = static_cast<uint32_t>(validationLayers.size());
      createInfo.ppEnabledLayerNames = validationLayers.data();
  }
  else {
      createInfo.enabledLayerCount = 0;
  }
  
  ...
}

void createInstance() {
  ...
  
  VkInstanceCreateInfo createInfo{};
  
  ...
  
  // enable validation layers if the are enabled
  VkDebugUtilsMessengerCreateInfoEXT debugCreateInfo{};
  
  if (enableValidationLayers) {
      createInfo.enabledLayerCount = static_cast<uint32_t>(validationLayers.size());
      createInfo.ppEnabledLayerNames = validationLayers.data();
  
      populateDebugMessengerCreateInfo(debugCreateInfo);
      createInfo.pNext = (VkDebugUtilsMessengerCreateInfoEXT*) &debugCreateInfo;
  }
  else {
      createInfo.enabledLayerCount = 0;
      createInfo.pNext = nullptr;
  }
  
  ...
}
```

</details>

**Comment by MrGuardian** [comment]
> So the issue seems there is a `vkCreateSampler` called but you think it is being called from your program

Not sure if I understood your wording correctly, but I'm sure there are no expicit calls to `vkCreateSampler` by me. I assume there might be some implicit internal calls to it in the Vulkan API, since I am very new to it and just started learning it.

> I would suggest swapping the Validation Layers for the [api dump layer](https://vulkan.lunarg.com/doc/view/latest/windows/api_dump_layer.html) (also in the SDK) and see what it dumps out

Thank you for pointing this out! Definitely helps not only in potentially finding the bug but also for me to learn a bit more about different types of validation layers available out of the box.

So I switched to this layer and the output I see is very strange. It does indeed contain a call to `vkCreateSampler` like follow:

```bash
Thread 0, Frame 0:
vkCreateSampler(device, pCreateInfo, pAllocator, pSampler) returns VkResult VK_SUCCESS (0):
    device:                 VkDevice = 000001BA7704CD20
    pCreateInfo: const VkSamplerCreateInfo* = 000000514FD9EF40:
        sType:           VkStructureType = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO (31)
        pNext:               const void* = NULL
        flags:      VkSamplerCreateFlags = 0
        magFilter:              VkFilter = VK_FILTER_LINEAR (1)
        minFilter:              VkFilter = VK_FILTER_LINEAR (1)
        mipmapMode:  VkSamplerMipmapMode = VK_SAMPLER_MIPMAP_MODE_LINEAR (1)
        addressModeU: VkSamplerAddressMode = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE (2)
        addressModeV: VkSamplerAddressMode = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE (2)
        addressModeW: VkSamplerAddressMode = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE (2)
        mipLodBias:                float = 0
        anisotropyEnable:       VkBool32 = 1
        maxAnisotropy:             float = 16
        compareEnable:          VkBool32 = 0
        compareOp:           VkCompareOp = VK_COMPARE_OP_ALWAYS (7)
        minLod:                    float = 0
        maxLod:                    float = 0
        borderColor:       VkBorderColor = VK_BORDER_COLOR_INT_TRANSPARENT_BLACK (1)
        unnormalizedCoordinates: VkBool32 = 0
    pAllocator: const VkAllocationCallbacks* = NULL
    pSampler:             VkSampler* = 000001BA799B41A0
```

Here is the full output of the `VK_LAYER_LUNARG_api_dump` layer: https://gist.github.com/MrGuardian/616963c35b95d087ac0bada9916d9540

However I am 100% sure _I didn't call it explicitly_. In fact, here is a full source code I have for this project (it is a single file project): https://gist.github.com/MrGuardian/b4806fb7f5bc9b2f4138c64849c5be89

Judging by the output I suspect it is called after the pipeline binding happened in the drawFrame function since there is a bunch of memory allocation going on before the `vkCreateSampler` in the log and judging roughly by the position of this function relative to the other functions I actually called from my code.

I follow [the tutorial](https://vulkan-tutorial.com/Drawing_a_triangle/Swap_chain_recreation) at my own pace and with my programming style, but the [raw source code from the tutorial author](https://vulkan-tutorial.com/code/17_swap_chain_recreation.cpp) also produces the same error.

I also saw a discussion in the comments where author of the tutorial advises to make an issue in this repository since some people also have this problem and apparently he doesn't. But then again, he used 1.1.77.0 version of the Vulkan SDK when he created this tutorial so maybe all was good back then.

Hopefully the information provided can shed a bit more light on what is going on. I am definitely inexperienced with the Vulkan SDK yet to understand why it behaves in this way and why validation layer behaves in this way.

**Comment by MrGuardian** [comment]
I just found what it was, hovewer the mechanics behind it are unclear to me. It turns out the popular application ["FPS Monitor"](https://fpsmon.com/en/) was behind this. I uninstalled it and now I don't have this error message anymore printed out.

The suspection was arisen when I saw it in the list of libraries providing the validation layers:

```bash
validation layer: Loading layer library C:\Program Files (x86)\FPS Monitor\tools\.\fpsmonvk64.dll
```

However it is still not clear to me if this library was somehow overriding the standard `VK_LAYER_KHRONOS_validation` layer or if this program could somehow bind into my Vulkan API calls and mix in some of its instructions. Not sure how this is possible if the program was not running anyway. Can you explain how could this app mix in `vkCreateSampler` code into my code?

**Comment by spencer-lunarg** [comment]
Ok, I see what is going on here

> I assume there might be some implicit internal calls to it in the Vulkan API

The API is not software, it is just a spec ( [more info](https://github.com/KhronosGroup/Vulkan-Guide/blob/main/chapters/what_is_vulkan.adoc#vulkan-at-its-core) )

>  this library was somehow overriding the standard VK_LAYER_KHRONOS_validation layer

So Vulkan goes

**app** -> **[Loader](https://github.com/KhronosGroup/Vulkan-Guide/blob/main/chapters/loader.adoc)** -> **[Layer 0](https://github.com/KhronosGroup/Vulkan-Guide/blob/main/chapters/layers.adoc)** -> **Layer 1** -> **Layer N** -> **Driver**

What is happening is between the `App` and the `Validation Layer` was the `FPS Monitor Layer`

It was calling `vKCreateSampler` and the Validation layers were seeing it from there. There is no way for the 2nd layer to know where the function call was coming from

![image](https://user-images.githubusercontent.com/115671160/229952193-18257582-c34f-456c-bb92-9b0f39965ef9.png)

I am closing this issue because it is not an issue with the Validation Layer repo, but happy to answer any more questions here

**Comment by MrGuardian** [comment]
@spencer-lunarg thank you so much for explaining this!
I didn't know that the validation layers can stack (even tho we explicitly selected a specific one to be active in our application) & add their own Vulkan API calls, that was illuminating, indeed. I have so much to learn about Vulkan API. Thank you again!
