### ISSUE TITLE
Fix BUILD.gn to allow files with same names

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/Vulkan-ValidationLayers#5571]
currently we can't have a `layers/stateless/cmd_buffer_validation.cpp` and `layers/core_checks/cmd_buffer_validation.cpp` file because BUILD.gn will produce this error

```
The target //:VkLayer_khronos_validation
generates two object files with the same name:
  obj/VkLayer_khronos_validation/cmd_buffer_dynamic_validation.o

It could be you accidentally have a file listed twice in the
sources. Or, depending on how your toolchain maps sources to
object files, two source files with the same name in different
directories could map to the same object file.

In the latter case, either rename one of the files or move one of
the sources to a separate source_set to avoid them both being in
the same target.
Updating Repo Dependencies and GN Toolchain
```

I tried separating it, but met with various build/linking errors and there is no good documentation/examples of BUILD.gn outside chromium

**Comment by juan-lunarg** [comment]
Is this something that can be fixed? This looks like a style choice enforced by the GN build system.

**Comment by mark-lunarg** [comment]
> Is this something that can be fixed? This looks like a style choice enforced by the GN build system.

Not at all positive about this but in the ANGLE project (uses Ninja) it looks like they namespace all the files within a compilation unit so maybe it's more than a style choice? Regardless, it is helpful in a number of ways. Just sayin'.

**Comment by juan-lunarg** [comment]
closing per last meeting discussion
