### ISSUE TITLE
VALIDATION_CHECK_ENABLE_VENDOR_SPECIFIC_ALL

### ISSUE THREAD

**Issue by kanashimia** [KhronosGroup/Vulkan-ValidationLayers#5573]
Adding VALIDATION_CHECK_ENABLE_VENDOR_SPECIFIC_ALL to khronos_validation.enables currently works, was able to find this by looking at the source code.
https://vulkan.lunarg.com/doc/sdk/1.3.243.0/linux/khronos_validation_layer.html doesn't mention this flag, as the json it is generated from.
Should this flag be documented or should it not work?

EDIT: Actually it was documented here in the old documentation: https://vulkan.lunarg.com/doc/view/1.2.189.0/linux/best_practices.html but somehow it was forgotten.

This ALL option is useful because my vk_layer_settings.txt already looks like this:

> khronos_validation.enables = VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_RESERVE_BINDING_SLOT_EXT,VALIDATION_CHECK_ENABLE_SYNCHRONIZATION_VALIDATION_QUEUE_SUBMIT,VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXT,VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT,VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT,VALIDATION_CHECK_ENABLE_VENDOR_SPECIFIC_ALL

Not very readable if you try to modify it by hand, if it was a json file would be much better.

**system details:**
OS: NixOS 23.05.20230330.e608c90
vulkan-validation-layers: 1.3.239.0

**Comment by juan-lunarg** [comment]
Thanks for pointing this out. It looks like a simple mistake.

**Comment by juan-lunarg** [comment]
The fix has been merged in now. Apologies for the confusion.
