### ISSUE TITLE
CoreChecks::ValidateCmdDrawIndexedBufferSize is double-counting the offset

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-ValidationLayers#5575]
Seeing failures in ANGLE, I took a look and this code is double-counting the index offset:

```
        VkDeviceSize end_offset = static_cast<VkDeviceSize>(index_size * (firstIndex + indexCount)) + index_buffer_binding.offset;
        if (end_offset > index_buffer_binding.size) {
```

I see that `index_buffer_binding.size + index_buffer_binding.offset` is the create info size, so clearly `index_buffer_binding.size` has already taken offset into account. `end_offset` can just drop `+ index_buffer_binding.offset`.

**Comment by jzulauf-lunarg** [comment]
That's right.  I corrected the RecordCmdBindIndex code to restrict the size to the *bound* size, but didn't note this code depended on the incorrect setting.  Note, the once this is fixed accesses outside the *bound* range, (not the buffer creation WHOLE_SIZE) will start producing errors.

I'll push a one-liner.
