### ISSUE TITLE
Fix code generation after breaking vulkan registry xml changes

### ISSUE THREAD

**Issue by ncesario-lunarg** [KhronosGroup/Vulkan-ValidationLayers#5579]
VVL needs to be updated to handle the use of boolean expressions to describe extension dependencies (introduced in https://github.com/KhronosGroup/Vulkan-Docs/commit/1b1c4dd43a35341c8c8e82ad985ed66d8beff5ba).

Many of the necessary update to code generation have already been made, but the current reliance on lists of dependencies-as opposed to boolean expressions--still needs to be addressed.

**Comment by spencer-lunarg** [comment]
Update, https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6004 was added to help fix this in tooling, on my todo today to try it out (cc @ziga-lunarg)

**Comment by spencer-lunarg** [comment]
there is nothing really left to do here, other issues are tracking the use case problems

**Comment by spencer-lunarg** [comment]
issue - https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2787
