### ISSUE TITLE
Implement support for VK_EXT_memory_priority

### ISSUE THREAD

**Issue by jeffbolznv** [KhronosGroup/Vulkan-ValidationLayers#558]
I will do this after the 1.1.97 headers are merged into the layers. There is only one explicit VU and it should be simple.

**Comment by sfricke-samsung** [comment]
seems like #568 covered this already as `VUID-VkMemoryPriorityAllocateInfoEXT-priority-02602` is already done

**Comment by mark-lunarg** [comment]
@sfricke-samsung, thanks!  I love it when this happens.
