### ISSUE TITLE
VUID-vkCmdDecodeVideoKHR-None-07011 issued when the video session has been correctly initialized

### ISSUE THREAD

**Issue by charlie-ht** [KhronosGroup/Vulkan-ValidationLayers#5586]
**Environment:**
 - OS: Ubuntu 20.10
 - GPU: Intel
 - SDK or header version if building from repo: Built from `20e85d7f2bbaca9222cb226dc5168aef3ed3f2e9`
 - Options enabled (synchronization, best practices, etc.): `VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT,VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXT`

**Describe the Issue**

Validation error reported while running `dEQP-VK.video.decode.h264_interleaved`. From an inspection of the test code, the `ControlVideoCoding` is being called at the right moment to initialize the video session before issuing decode commands. This test in particular interleaves command buffers from two different sessions, and it looks like the validation layer is mixing up state, although I wasn't able to get to the bottom of exactly how that might be happening.

**Expected behavior**

No validation error.

**Valid Usage ID**

`VUID-vkCmdDecodeVideoKHR-None-07011`

**Additional context**

This test manages two streams. It creates two decoders (and hence two sessions), records commands to decode the first stream's cached pictures, and the records commands to decode the second stream's cached pictures. It combines the full set of commands into one queue submission using the first decoders queue. While the test code is pretty difficult to follow, I didn't see it doing anything wrong per the spec.

<details>
<summary>code or terminal output</summary>

```sh
VUID-vkCmdDecodeVideoKHR-None-07011(ERROR / SPEC): msgNum: -1451100675 - Validation Error: [ VUID-vkCmdDecodeVideoKHR-None-07011 ] Object 0: handle = 0xead9370000000008, type = VK_OBJECT_TYPE_VIDEO_SESSION_KHR; | MessageID = 0xa981f5fd | VkVideoSessionKHR 0xead9370000000008[] is uninitialized The Vulkan spec states: The bound video session must not be in uninitialized state at the time the command is executed on the device (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdDecodeVideoKHR-None-07011)
    Objects: 1
        [0] 0xead9370000000008, type: 1000023000, name: NULL
```

</details>

**Comment by ncesario-lunarg** [comment]
FYI @aqnuep.

**Comment by aqnuep** [comment]
@charlie-ht, could you please point me to the CTS commit I can use to reproduce this issue?

Also, are you sure that you actually reset **both** sessions before recording decode commands against them?

Looking at the validation code for this I don't see how this VU could be checked against the wrong video session, but, of course, there could be some issue there nonetheless.

If you could provide an API dump that could help too, but I'm happy to run the CTS test to reproduce it locally if you can point me to the revision I should use.

**Comment by charlie-ht** [comment]
Hi @aqnuep, a CTS commit you can reproduce with is `6cb33ad38024ae3d133c304da7dd28f2dbd9ea15`. Note that you will see, in addition to `VUID-vkCmdDecodeVideoKHR-None-07011` the errors  `VUID-vkCmdDecodeVideoKHR-pDecodeInfo-07261` and `VUID-vkCmdDecodeVideoKHR-pDecodeInfo-07149`. `07149` has a pending fix, and `07261` is related to the issues regarding the flaging of top/bottom fields that are under discussion, they can be ignored for this issue.

> Also, are you sure that you actually reset both sessions before recording decode commands against them?

I wouldn't bet my life on it, but it sure looks like that's what the interleaving test is doing. It activates the right session before recording the commands for the respective parts of the interleaving test using code like,

```
		vkd.cmdBeginVideoCodingKHR(commandBuffer, &decodeBeginInfo);

		if (picNdx == 0)
			vkd.cmdControlVideoCodingKHR(commandBuffer, &videoCodingControlInfoKHR);
```

Where the `decodeBeginInfo` is pointing at the right session in the two parts of the interleaving test.

I noticed the validation layers are maintaining their own notion of the device state and the active session, which is why I thought perhaps the problem is there, but I also didn't notice anything obviously wrong.

I'm attaching an API dump too, it doesn't make it clear to what session the control command is being applied (to me anyway), but hopefully it might give a further clue.

[trace.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/11178517/trace.txt)
