### ISSUE TITLE
Non supported texture sampling method used as function parameter.

### ISSUE THREAD

**Issue by Paltoquet** [KhronosGroup/Vulkan-ValidationLayers#5614]
**Environment:**
 - OS:  Android
 - GPU: Adreno (TM) 630
 - Vulkan Version: 1.1
 - Options enabled (synchronization, best practices, etc.):

**Describe the Issue**

Using a nonsupported texture sampling method will not raise a validation error if texture and sampler are passed through function parameters.

```
#define SampleLvlTex2D(NAME, SAMPLER, COORD, LEVEL) \
textureLod(sampler2D(NAME, SAMPLER), COORD, LEVEL)

vec4 SampleLvlTex2DFunc( texture2D NAME, sampler SAMPLER, vec2 COORD, float LEVEL )
{ return textureLod(sampler2D(NAME, SAMPLER), COORD, LEVEL); }

float3 EnvironmentBRDF(float3 N, float3 V, float3 albedo, float roughness, float metalness)
{
	// this throws the validation error
	float3 specular = SampleLvlTex2D(myTexture, mySampler, uv, roughness);
	// this do not throw :)
	float3 specular = SampleLvlTex2DFunc(myTexture, mySampler, uv, roughness);
}
```
The texture format: VK_FORMAT_R32G32_SFLOAT, VK_FORMAT_D32_SFLOAT or VK_FORMAT_R32G32B32A32_SFLOAT

**Expected behavior**
throws validation error:
_alidation Error: [ VUID-vkCmdDraw-mipmapMode-04770 ] Object 0: handle = 0xe7250000000001cf, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; Object 1: handle = 0xf6fbc1000000009b, type = VK_OBJECT_TYPE_SAMPLER; Object 2: handle = 0x564fdd0000000069, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0xb507fc79 | vkCmdDraw: Descriptor set VkDescriptorSet 0xe7250000000001cf[] Sampler (VkSampler 0xf6fbc1000000009b[]) is set to use VK_SAMPLER_MIPMAP_MODE_LINEAR with compareEnable is set to VK_FALSE, but image view's (VkImageView 0x564fdd0000000069[]) format (VK_FORMAT_R32G32B32A32_SFLOAT) does not contain VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT in its format features. The Vulkan spec states: If a VkSampler created with mipmapMode equal to VK_SAMPLER_MIPMAP_MODE_LINEAR and compareEnable equal to VK_FALSE is used to sample a VkImageView as a result of this command, then the image view's format features must..._

I think a similar issue cause a crash on steam deck.

**Comment by spencer-lunarg** [comment]
@Paltoquet I will take a look at this (hopefully this week) but do you have the SPIR-V of both cases? 

The issue is most likely the way the GLSL/HLSL is generated into SPIR-V that we are not detecting correctly

**Comment by spencer-lunarg** [comment]
ok, so the difference is the Macro is using `OpLoad` directly while the function uses `OpFunctionCall`

The issue now is we use the shader to walk through and map which Sampler and ImageView are being used together... I guess we aren't handling function jumping correctly

Thanks for the SPIR-V and all the info so far, should be able to reproduce it really easily now in a local test and get a fix going
