### ISSUE TITLE
`DEBUG_PRINTF_EXT` doesn't work with `VK_EXT_shader_object`

### ISSUE THREAD

**Issue by phoekz** [KhronosGroup/Vulkan-ValidationLayers#5617]
**Environment:**
 - OS: Ubuntu 22
 - GPU: RTX 2060
 - SDK or header version if building from repo: 1.3.246 `ef7c246`
 - Options enabled (synchronization, best practices, etc.): best practices, debug printf, synchronization

**Describe the Issue**

1. Enable `VK_VALIDATION_FEATURE_ENABLE_DEBUG_PRINTF_EXT`
2. Issue a draw call using `VK_EXT_shader_object` instead of graphics pipelines.
3. Call `debugPrintfEXT` in any shader, but nothing happens.

Example error:
```
type=VALIDATION
message_id_name=UNASSIGNED-DEBUG-PRINTF
message=Validation Error: [ UNASSIGNED-DEBUG-PRINTF ] Object 0: handle = 0x55c15e07aac0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x92394c89 | Setup Error. Detail: (Unable to find pipeline state)
```

**Expected behavior**

Calling `debugPrintfEXT` should work without pipelines.

**Comment by spencer-lunarg** [comment]
These is already a tracker for adding validation for `VK_EXT_shader_object`
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5580

This will be part of it

**Comment by ncesario-lunarg** [comment]
Closing this as it is already covered by an existing issue.
