### ISSUE TITLE
`GPU_ASSISTED_EXT` segfaults with `VK_EXT_shader_object`

### ISSUE THREAD

**Issue by phoekz** [KhronosGroup/Vulkan-ValidationLayers#5619]
**Environment:**
 - OS: Ubuntu 22
 - GPU: RTX 2060
 - SDK or header version if building from repo: 1.3.246 `ef7c246`
 - Options enabled (synchronization, best practices, etc.): best practices, GPU assisted, synchronization

**Describe the Issue**

1. Enable `VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXT`
2. Issue a draw call using `VK_EXT_shader_object` instead of graphics pipelines.
3. Segfault in `Vulkan-ValidationLayers/layers/gpu_validation/gpu_validation.cpp:2028`. `pipeline_state=0x0`.

**Expected behavior**

`GPU_ASSISTED_EXT` shouldn't segfault the validation layers.

**Comment by juan-lunarg** [comment]
FYI @daniel-story
