### ISSUE TITLE
Support `VK_KHR_map_memory2`

### ISSUE THREAD

**Issue by phoekz** [KhronosGroup/Vulkan-ValidationLayers#5625]
**Environment:**

- OS: Ubuntu 22
- GPU: RTX 2060
- SDK or header version if building from repo: 1.3.246 ef7c246
- Options enabled (synchronization, best practices, etc.): best practices, debug printf, synchronization

**Describe the Issue**

Warning: ```Device Extension VK_KHR_map_memory2 is not supported by this layer.  Using this extension may adversely affect validation results and/or produce undefined behavior.```

The program crashes inside NVIDIA drivers as soon as you call `vkMapMemory2KHR`. Works fine without validation layers.

**Comment by ncesario-lunarg** [comment]
@phoekz can you please provide which version of the validation layers you are using in addition to the platform you are running on?

**Comment by phoekz** [comment]
> @phoekz can you please provide which version of the validation layers you are using in addition to the platform you are running on?

Sure, I updated the issue.

**Comment by ncesario-lunarg** [comment]
Tagging @gfxstrand, as I thought https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5475 added support for this extension. I'm especially confused about the "extension not supported" warning.

**Comment by gfxstrand** [comment]
It should have. I may have missed something, though.  The tests pass both in CI and on Intel/Mesa so I don't know what would be missing. Maybe it's interacting badly with best practices or synchronization?

**Comment by juan-lunarg** [comment]
I just double checked and `VkPositiveLayerTest.MapMemory2` and `VkLayerTest.MapMemory2` are passing CI right now.

**Comment by phoekz** [comment]
My bad, I just realized what I did wrong 🤦. My new project incorrectly used an older version of the validation layer build. I forgot to set `VK_LAYER_PATH` to point to my custom-built Vulkan validation layers.

**Comment by phoekz** [comment]
Can the validation layer report its header version / build ID? Maybe in an `UNASSIGNED-CreateInstance-status-message`? That could have saved some confusion on my part when dealing with multiple Vulkan projects🙂.

**Comment by phoekz** [comment]
Looks like the chosen layer manifest file is reported as part of `message_id_name="Loader Message"` logs at the start.
