### ISSUE TITLE
Add subpass self dependency VUs

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/Vulkan-ValidationLayers#5631]
[Internal spec change](https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5687/diffs)
[Released in  1.3.242](https://github.com/KhronosGroup/Vulkan-Docs/commit/f3e686fc22251102713a2a1a1cd071f60ab6efd8#diff-c0f9e36aa254a211f561ac0f4b0027c7ce5fdaa0da3fc0ffbf95ffa7bf5c802c)

- [x] VUID-vkCmdPipelineBarrier2-None-07890 (https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6649)
- [x] VUID-vkCmdPipelineBarrier2-dependencyFlags-07891
- [x] VUID-vkCmdPipelineBarrier2-None-07892
- [x] VUID-vkCmdPipelineBarrier-None-07889

related:

`VUID-vkCmdPipelineBarrier2-pDependencies-02285` is similar, but it missing the `VUID-vkCmdPipelineBarrier2-None-07889` variation

```
ifndef::VK_KHR_multiview,VK_VERSION_1_1[]
  * [[VUID-{refpage}-pDependencies-02285]]
endif::VK_KHR_multiview,VK_VERSION_1_1[]
ifdef::VK_KHR_multiview,VK_VERSION_1_1[]
  * [[VUID-{refpage}-None-07889]]
endif::VK_KHR_multiview,VK_VERSION_1_1[]
```

**Comment by ziga-lunarg** [comment]
It seems to me that these VUIDs are impossible to hit without hitting similar VUIDs on render pass create, for example to hit 07890 you will hit `VUID-VkSubpassDependency-srcSubpass-06809` when you create the required render pass.

**Comment by spencer-lunarg** [comment]
what if you use dynamic rendering and have no subpasses?

**Comment by ziga-lunarg** [comment]
You can't call `vkCmdPipelineBarrier()` inside a dynamic render pass.

**Comment by spencer-lunarg** [comment]
awww, ok, will take a double look Monday and make a spec MR to remove them

**Comment by spencer-lunarg** [comment]
update, so I think I realize this original spec change was for the `VK_KHR_dynamic_rendering_local_read` that came out and were
