### ISSUE TITLE
Build error, update_deps.py end with error

### ISSUE THREAD

**Issue by tonisimakov99** [KhronosGroup/Vulkan-ValidationLayers#5639]
**Environment:**
 - OS: Linux
 - GPU:
 - SDK or header version if building from repo:
 - Options enabled (synchronization, best practices, etc.):

![изображение](https://user-images.githubusercontent.com/31796662/231738481-58b94928-ff2e-4e01-b634-d69a098fa44d.png)

**Comment by juan-lunarg** [comment]
Essentially warnings are being treated as errors when compiling `spirv-tools`.

Thankfully the answer is simple. We set `SPIRV_WERROR` to `OFF` in our `known_good.json`

**Comment by juan-lunarg** [comment]
> thanks, it solved my problem, but I got new:

Try the following commands.

```
cmake -E rm -rf build
cmake -E rm -rf external
cmake -S . -B build --preset dev
```

If that doesn't work feel free to open another issue. However, please post the text instead of a picture. Pictures aren't very friendly to searching and another user might have your issue.
