### ISSUE TITLE
vkCmdClearColorImage layout validation too restrictive

### ISSUE THREAD

**Issue by Nadrin** [KhronosGroup/Vulkan-ValidationLayers#564]
When calling `vkCmdClearColorImage` with a VkImage in `VK_IMAGE_LAYOUT_GENERAL` I got this validation error:

`[ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object: 0x28 (Type = 10) | vkCmdClearColorImage(): Layout for cleared image should be TRANSFER_DST_OPTIMAL instead of GENERAL.`

The Vulkan specification says however:

> `imageLayout` specifies the current layout of the image subresource ranges to be cleared, and must be `VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR`, `VK_IMAGE_LAYOUT_GENERAL` or `VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL`.

Haven't tested `vkCmdClearDepthStencilImage` but it's worth checking whether the same bug happens there.

**Comment by tobine** [comment]
This is a performance warning, not an error: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/buffer_validation.cpp#L1597

If you don't want perf warnings, disable or ignore the VK_DEBUG_REPORT_PERFORMANCE_WARNING_BIT_EXT bit in your callback.

**Comment by Nadrin** [comment]
Ah, that makes sense then. Thanks!
