### ISSUE TITLE
Not setting state with shader objects is not diagnosed

### ISSUE THREAD

**Issue by nanokatze** [KhronosGroup/Vulkan-ValidationLayers#5655]
The VUIDs `VUID-vkCmdDraw*-None-{08617..08683}` that make statements about state you need to set when using shader objects are not currently diagnosed by VVL, which makes programming with shader objects very error-prone: it's easy to forget to set state that's currently unspecified as in practice that state will leak from the preceding command buffer or call to vkCmdBindPipeline.

**Comment by spencer-lunarg** [comment]
This is because we are stilling trying add support for `VK_EXT_shader_object`

I am closing this as this is being tracked already in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5580
