### ISSUE TITLE
VUIDs not checked if pipeline libraries aren't enabled

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-ValidationLayers#5656]
These two VUIDs apply regardless of whether the `VK_EXT_graphics_pipeline_library` extension is enabled, but in the source code they are only checked if it is enabled, and skipped otherwise.
- VUID-VkGraphicsPipelineCreateInfo-pStages-06894
- VUID-VkGraphicsPipelineCreateInfo-pStages-06895

I'm not sure in which situation 06895 can apply when pipeline libraries aren't being used, since pre-rasterization state must always be included, per 06573. But 06894 can definitely occur in a complete pipeline, if `rasterizerDiscardEnable` is set.

**Comment by spencer-lunarg** [comment]
Sorry, I recently moved this in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5628

For `VUID-VkGraphicsPipelineCreateInfo-pStages-06894`

> If the pipeline is being created with pre-rasterization shader state but not **fragment shader state**, elements of pStages must not have stage set to **VK_SHADER_STAGE_FRAGMENT_BIT**


fragment shader state is defined as

> A [VkPipelineShaderStageCreateInfo](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VkPipelineShaderStageCreateInfo) entry for the fragment shader

so without `VK_EXT_graphics_pipeline_library` how does one both have a `VK_SHADER_STAGE_FRAGMENT_BIT` but not  have a `fragment shader state`

**Comment by Rua** [comment]
By setting `rasterizerDiscardEnable`. The spec says:
> If the value of VkPipelineRasterizationStateCreateInfo::`rasterizerDiscardEnable` in the pre-rasterization shader state is `VK_FALSE` or the `VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE` dynamic state is enabled fragment shader state and fragment output interface state is included in a complete graphics pipeline.

So if `rasterizerDiscardEnable` is true, and `VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE` is not enabled, then the pipeline has no fragment shader state but is complete.

**Comment by ziga-lunarg** [comment]
This seems to have already been fixed, and `NegativePipeline.RasterizerDiscardWithFragmentShader` covers it
