### ISSUE TITLE
Potential bug in depthWriteEnabled traccking with dynamicState?

### ISSUE THREAD

**Issue by changanlao** [KhronosGroup/Vulkan-ValidationLayers#5677]
I am working on ANGLE, and seeing a strange VVL error that might possibly a VVL bug. 
Steps to reproduce:
1) Setup ANGLE and able to run end2end tests
2) Revert this CL which I try to workaround the VVL error
     https://chromium-review.googlesource.com/c/angle/angle/+/4442446
3) Run ClearTestES3.RepeatedStencilClearWithBlitInBetween/ES3_Vulkan on windows intel GPU, and it some times report this VVL error:
[ RUN      ] ClearTestES3.RepeatedStencilClearWithBlitInBetween/ES3_Vulkan
..\..\src\tests\test_utils\ANGLETest.cpp(65): error: RendererVk.cpp:777 (DebugUtilsMessenger): [ VUID-vkCmdDraw-None-06886 ] Validation Error: [ VUID-vkCmdDraw-None-06886 ] Object 0: handle = 0x2660000000266, type = VK_OBJECT_TYPE_PIPELINE; Object 1: handle = 0x26b000000026b, type = VK_OBJECT_TYPE_RENDER_PASS; Object 2: handle = 0x27654d828a8, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xf157442b | vkCmdDraw: depthWriteEnable is VK_TRUE, while the layout (VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL) of the depth aspect of the depth/stencil attachment in the render pass is read only. The Vulkan spec states: If the current render pass instance uses a depth/stencil attachment with a read-only layout for the depth aspect, depth writes must be disabled (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdDraw-None-06886)
                            Object: 0x2660000000266 (type = Pipeline(19))
                            Object: 0x26b000000026b (type = Render Pass(18))
                            Object: 0x27654d828a8 (type = Command Buffer(6))

One example can be seen in the ANGLE bots (if you have access):  
      https://chromium-swarm.appspot.com/task?id=61aa817c7663ef10

I have debugged this a bit and here is what I have found so far:

intel GPU has vulkan dynamic state feature enabled:
    supportsExtendedDynamicState is true 
    supportsExtendedDynamicState2 is true.

The test has only stencil attachment, no depth attachment. Intel GPU does not support stencil8 format, so it picked D24S8 format.

ANGLE is calling VkCmdSetDepthTestEnable(false). In my log, I never see it call  VkCmdSetDepthTestEnable with `true`argument and every renderpass is setting depth write to false.

But VVL complains depthWriteEnable is VK_TRUE, which made me suspect it is VVL tracking bug.

**Comment by spencer-lunarg** [comment]
sorry, I know there are some issue with dynamic state yet, with `VK_EXT_shader_object` some of it got put on backburner, but I can probably reproduce this easily locally

(and at least we will have regression tests for it then!)

**Comment by spencer-lunarg** [comment]
Ok, so looking at it more, I think this is the same issue we were having in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5551 now

**Comment by changanlao** [comment]
Thanks for quick action!

**Comment by spencer-lunarg** [comment]
@changanlao I think this is now fixed, between #5811 and https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5790 

If you still see the problem please reopen the issue!
