### ISSUE TITLE
VUID exist, but validation not happening for Pipeline dynamic state "CullMode"

### ISSUE THREAD

**Issue by gamagan** [KhronosGroup/Vulkan-ValidationLayers#5764]
**Environment:**
 - OS: Windows 10
 - GPU: GTX 1080ti
 - SDK or header version if building from repo: SDK 1.3.243
 - Options enabled (synchronization, best practices, etc.): KhronosValidation, LunargMonitor

**Describe the Issue**

I create some pipelines with dynamic cullMode enabled. I don't use the vkCmdSetCullMode() to set the dynamic value. When I run the application (with validation layers enabled), I don't get any validation errors. The cullMode just seems to default to double-sided. The docs say that, when dynamic cullMode is enabled, that the vkCmdSetCullMode() must be called to set value.

**Expected behavior**

Expected this validation error:
VUID-vkCmdDrawIndexed-None-07840

https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap21.html#VUID-vkCmdDrawIndexed-None-07840

**Valid Usage ID**
VUID-vkCmdDrawIndexed-None-07840

**Additional context**
None

**Comment by spencer-lunarg** [comment]
There are a lot of these

> If created with the VK_DYNAMIC_STATE_* then vkCmdSet* must have been called prior

VUs and seems we missed a few, including `VK_DYNAMIC_STATE_CULL_MODE`/`vkCmdSetCullMode` - I will quickly get this added
