### ISSUE TITLE
False positive on using multiple references to the same attachment

### ISSUE THREAD

**Issue by asuonpaa** [KhronosGroup/Vulkan-ValidationLayers#578]
While developing a test for descriptor copies I found validation layers giving the following error:

> vkCreateRenderPass(): subpass 0 already uses attachment 1 as a input attachment.

I'm having multiple input attachment descriptors and some are copied over in vkUpdateDescriptorSets. The result is that several bindings refer to the same attachment. The input attachment indices are also updated based on the copies, and the result is a list of VkAttachmentReferences where the same attachment is referenced more than once. An that's allowed as long as the layout is the same for all. Here's a quote from the [spec](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkSubpassDescription.html):

> If any attachment is used by more than one VkAttachmentReference member, then each use must use the same layout

**Comment by jzulauf-lunarg** [comment]
Triage notes: This is a bug in AddAttachmentUse ... needs to track the layout of the usage and, if differing, emit VUID-VkSubpassDescription-layout-02519.  Care should be taken to assure that this policy is valid for all callers of AddAttachmentUse, and if not controlled for.

Other logic in AddAttachmentUse should be reviewed to assure no additional false positives are embedded.

**Comment by asuonpaa** [comment]
I can try contributing to this task. Is there a way to assign this to me?

**Comment by asuonpaa** [comment]
Is it ok to return a warning instead of an error if there are several references to the same attachment? In most cases, it's not what was intended, and a warning could be useful.

**Comment by mark-lunarg** [comment]
@asuonpaa -- happily assigned!  As to a warning, If it is called out in the specification it is valid. Otherwise, the preferred place to implement warnings is in the Assistant Layer -- items can be added to the to-do list tracked in issue #24.

**Comment by jzulauf-lunarg** [comment]
Resolved.
