### ISSUE TITLE
False positive with read-only layout validation with dynamic state that is ineffective

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-ValidationLayers#5783]
Take the following scenario:

- Render pass uses DEPTH_STENCIL_READ_ONLY_OPTIMAL
- It starts and sets `vkCmdSetDepthTestEnable(false)`. Depth test and write are dynamic state
- It does _not_ set `vkCmdSetDepthWriteEnable`
- Draw
- End render pass

In the above, VVL complains that:

> vkCmdDraw: depthWriteEnable is VK_TRUE, while the layout (VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL) of the depth aspect of the depth/stencil attachment in the render pass is read only. The Vulkan spec states: If the current render pass instance uses a depth/stencil attachment with a read-only layout for the depth aspect, depth writes must be disabled (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdDraw-None-06886)

It seems that VVL sees depth write enabled because of a previous render pass which set it enabled. Vulkan says:

> Dynamic state that does not affect the result of operations can be left undefined.

In the above, since depth-test is disabled, depth-write doesn't matter and so it doesn't have to be set (as I understand it).

**Comment by ShabbyX** [comment]
This is very similar to https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4921 actually. That issue is closed, but the false positive still happens in ANGLE (last I tried after it was closed): https://chromium-review.googlesource.com/c/angle/angle/+/4103721

**Comment by spencer-lunarg** [comment]
Agree, I can easily fix this case, but it annoying we don't have a good way to see which state effect other state as a dependency (`depthWriteEnable` depends on `depthTestEnable`)

**Comment by ShabbyX** [comment]
> edit: I went through spec, built a table

In the xml I hope?

**Comment by spencer-lunarg** [comment]
> In the xml I hope?

For now, just manually did it to get the job done, when I get done with the Sync XML, can look into these tables
