### ISSUE TITLE
Layer crashes in vkCmdPushDescriptorSetWithTemplateKHR

### ISSUE THREAD

**Issue by zakarumych** [KhronosGroup/Vulkan-ValidationLayers#5784]
**Environment:**
 - OS: Windows
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - SDK : 1.3.243.0
 - Options enabled (synchronization, best practices, etc.): -

**Describe the Issue**

After creating [VkPipelineLayout](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPipelineLayout.html) with single [VkDescriptorSetLayout](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDescriptorSetLayout.html) with single uniform buffer I accidentally deleted [VkDescriptorSetLayout](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDescriptorSetLayout.html) object.
Later when I try to push descriptor with [vkCmdPushDescriptorSetWithTemplateKHR](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdPushDescriptorSetWithTemplateKHR.html) the validation layer causes app to crash.

**Expected behavior**

If I use [vkCmdPushDescriptorSetKHR](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdPushDescriptorSetKHR.html) the validation layer reports the issue - [VkDescriptorSetLayout](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDescriptorSetLayout.html) was destroyed.
I expect [vkCmdPushDescriptorSetWithTemplateKHR](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdPushDescriptorSetWithTemplateKHR.html) to do the same.

**Additional context**

<details>
<summary>code or terminal output</summary>

```sh
<sound of app crashes without any output>
```

</details>

**Comment by spencer-lunarg** [comment]
added a PR, the issue was ` VUID-vkCmdPushDescriptorSetWithTemplateKHR-pData-01686` was not implemented and the layers didn't make sure `pData` was still pointing to a valid `DescriptorSetLayout`

Thanks for bringing this up to our attention
