### ISSUE TITLE
Valgrind: Use of uninitialized value (`StatelessValidation::api_version`)

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-ValidationLayers#580]
From `valgrind` (non-validation-layer part of stack trace is removed):

```
==27942== Conditional jump or move depends on uninitialised value(s)
==27942==    at 0x107835F1: StatelessValidation::validate_api_version(unsigned int, unsigned int) (parameter_validation_utils.cpp:101)
==27942==    by 0x107839CF: StatelessValidation::manual_PreCallValidateCreateInstance(VkInstanceCreateInfo const*, VkAllocationCallbacks const*, VkInstance_T**) (parameter_validation_utils.cpp:146)
==27942==    by 0x106F9436: StatelessValidation::PreCallValidateCreateInstance(VkInstanceCreateInfo const*, VkAllocationCallbacks const*, VkInstance_T**) (parameter_validation.cpp:1337)
==27942==    by 0x107B2461: vulkan_layer_chassis::CreateInstance(VkInstanceCreateInfo const*, VkAllocationCallbacks const*, VkInstance_T**) (chassis.cpp:194)
==27942==    by 0x10AFC10E: vulkan_layer_chassis::CreateInstance(VkInstanceCreateInfo const*, VkAllocationCallbacks const*, VkInstance_T**) (chassis.cpp:200)
==27942==    by 0x41383CE: loader_create_instance_chain (loader.c:5287)
==27942==    by 0x4145BA9: vkCreateInstance (trampoline.c:501)
==27942==  Uninitialised value was created by a heap allocation
==27942==    at 0x4C3017F: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27942==    by 0x107B23B9: vulkan_layer_chassis::CreateInstance(VkInstanceCreateInfo const*, VkAllocationCallbacks const*, VkInstance_T**) (chassis.cpp:186)
==27942==    by 0x10AFC10E: vulkan_layer_chassis::CreateInstance(VkInstanceCreateInfo const*, VkAllocationCallbacks const*, VkInstance_T**) (chassis.cpp:200)
==27942==    by 0x41383CE: loader_create_instance_chain (loader.c:5287)
==27942==    by 0x4145BA9: vkCreateInstance (trampoline.c:501)
```

A quick investigation shows that:

1. `StatelessValidation::api_version` is not initialized at construction
2. In `chassis.cpp` (`CreateInstance()`), between the allocation of the `StatelessValidation` object and the `PreCallValidateCreateInstance`, `api_version` is not set.
3. A few lines after that call, the `api_version` is set to `framework->api_version`.

This would have created a debug error in `StatelessValidation::validate_api_version`, except the first parameter of `log_msg` is `NULL`.

**Comment by mark-lunarg** [comment]
@ShabbyX, thanks for the valgrinding.  I'm sure there'll be other things that pop up (this is all new stuff) -- please let me know and I'll respond as quickly as I can.

**Comment by ShabbyX** [comment]
There are indeed a few different issues popping up (I'm investigating and reporting them individually). What prompted me to do this was the fact that after the upgrade I see a random crash, so some of these are going to be more important to address.

**Comment by ShabbyX** [comment]
FYI, the other issue is KhronosGroup/Vulkan-Loader#132. Not sure if you are active on that repo as well.
