### ISSUE TITLE
vulkan-validationlayers 1.3.250 build failure

### ISSUE THREAD

**Issue by chenrui333** [KhronosGroup/Vulkan-ValidationLayers#5812]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  /tmp/vulkan-validationlayers-20230505-7593-j0ooez/Vulkan-ValidationLayers-1.3.250/layers/gpu_validation/gpu_validation.cpp:1338:38: error: no member named 'kDebugInputBindlessMaxDescSets' in namespace 'spvtools'; did you mean 'kDebugInputBindlessInitOffset'?
          buffer_info.size = spvtools::kDebugInputBindlessMaxDescSets * 8; // 64 bit addresses
                             ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                       kDebugInputBindlessInitOffset
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/4897416533/jobs/8745513632?pr=130298
relates to Homebrew/homebrew-core#130298

**Comment by jeremyg-lunarg** [comment]
You need to update SPIRV-Tools to commit d4c0abdcad60325a2ab3c00a81847e2dbdc927a2 / https://github.com/KhronosGroup/SPIRV-Tools/pull/5178

Be warned that this is about to happen again in PR https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5643

The file scripts/known_good.json indicates which commits of each dependency are required.

**Comment by spencer-lunarg** [comment]
@chenrui333 hope the info about the `scripts/known_good.json` is enough

The two common ways are

- `-D UPDATE_DEPS=ON` in the cmake
- `python3 scripts/update_deps.py --dir external --arch x64 --config release` if you want to do it manually

More info here https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/BUILD.md#dependencies

If this resolves the issue please close

**Comment by juan-lunarg** [comment]
Also @chenrui333 be aware of the versioning strategy for Vulkan repositories:
https://github.com/KhronosGroup/Vulkan-ValidationLayers#version-tagging-scheme

**Comment by chenrui333** [comment]
Should be good with [this PR](https://github.com/Homebrew/homebrew-core/pull/131028).

Do you mind for me adding a new workflow for regression testing build on macos?

**Comment by juan-lunarg** [comment]
We do test our builds on MacOS. Both on GitHub actions and on internal Jenkins.
