### ISSUE TITLE
PreCallValidateGetDescriptorEXT crashes on (illegally) null descriptors

### ISSUE THREAD

**Issue by kspagnoli-nv** [KhronosGroup/Vulkan-ValidationLayers#5826]
**Describe the situation in which you encountered the missing validation**

For vkGetDescriptorEXT, the VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER & VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT do not check to make sure the descriptor is non-null and instead deference a nullptr in the validation layer (causing a crash).

**Valid Usage IDs requested**

- VUID-VkDescriptorGetInfoEXT-type-08019
- VUID-VkDescriptorGetInfoEXT-type-08021

**Additional Context**

This is an easy mistake to make because null is allowed for all the other descriptor types. Maybe instead of...

`if (Get<SAMPLER_STATE>(pDescriptorInfo->data.pCombinedImageSampler->sampler).get() == nullptr) {`

The check should be...

`if (pDescriptorInfo->data.pCombinedImageSampler->sampler == VK_NULL_HANDLE || Get<SAMPLER_STATE>(pDescriptorInfo->data.pCombinedImageSampler->sampler).get() == nullptr) {`

And for VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT as well.

**Comment by spencer-lunarg** [comment]
So I wrote a test

```c++
TEST_F(NegativeDescriptorBuffer, NullHandle) {
    TEST_DESCRIPTION("Descriptor buffer various tests.");
    SetTargetApiVersion(VK_API_VERSION_1_2);
    AddRequiredExtensions(VK_EXT_DESCRIPTOR_BUFFER_EXTENSION_NAME);
    ASSERT_NO_FATAL_FAILURE(InitFramework());
    if (!AreRequiredExtensionsEnabled()) {
        GTEST_SKIP() << RequiredExtensionsNotSupported() << " not supported";
    }
    if (DeviceValidationVersion() < VK_API_VERSION_1_2) {
        GTEST_SKIP() << "At least Vulkan version 1.2 is required";
    }

    auto descriptor_buffer_features = LvlInitStruct<VkPhysicalDeviceDescriptorBufferFeaturesEXT>();
    GetPhysicalDeviceFeatures2(descriptor_buffer_features);
    ASSERT_NO_FATAL_FAILURE(InitState(nullptr, &descriptor_buffer_features));

    auto descriptor_buffer_properties = LvlInitStruct<VkPhysicalDeviceDescriptorBufferPropertiesEXT>();
    GetPhysicalDeviceProperties2(descriptor_buffer_properties);

    VkSampler invalid_sampler = CastToHandle<VkSampler, uintptr_t>(0x0);
    VkImageView invalid_imageview = CastToHandle<VkImageView, uintptr_t>(0x0);

    uint8_t buffer[128];
    auto dgi = LvlInitStruct<VkDescriptorGetInfoEXT>();

    const VkDescriptorImageInfo dii = {invalid_sampler, invalid_imageview, VK_IMAGE_LAYOUT_GENERAL};

    dgi.type = VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT;
    dgi.data.pInputAttachmentImage = &dii;
    m_errorMonitor->SetDesiredFailureMsg(kErrorBit, "VUID-VkDescriptorGetInfoEXT-type-08021");
    vk::GetDescriptorEXT(m_device->device(), &dgi, descriptor_buffer_properties.inputAttachmentDescriptorSize, &buffer);
    m_errorMonitor->VerifyFound();
}
```

and I don't see any crash, which version of the Validation Layers are you using, might have been fixed how we do the `Get` call since
