### ISSUE TITLE
False positive error when creating disjoint image memory binding

### ISSUE THREAD

**Issue by ilkkasaa** [KhronosGroup/Vulkan-ValidationLayers#583]
This problem was discovered while running the Vulkan CTS YCbCr format tests for multi-planar formats (dEQP-VK.ycbcr.format.*_disjoint). If an image is created with the `VK_IMAGE_CREATE_DISJOINT_BIT` flag, each plane has to be bound to memory separately and therefore the function `bindImageMemory2()` must be called multiple times or called once with multiple `VkBindImageMemoryInfo` objects. In any case all of the `VkBindImageMemoryInfo` objects contains the same `VkImage` object and that causes the following false positive validation error:

`ERROR:  [ VUID-vkBindImageMemory-image-01044 ] Object: 0x60d (Type = 8) | In vkBindImageMemory2() pBindInfos[0], attempting to bind memory (0x60d) to object (0x60b) which has already been bound to mem object 0x60c. The Vulkan spec states: image must not already be backed by a memory object (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkBindImageMemory-image-01044) (code 0x00000000 from Validation at DeviceMemory:0)`

**Comment by ilkkasaa** [comment]
Hi,
I agree that the spec is a bit misleading by saying "image must not already be backed by a memory object", but in the other hand the specification of the VK_IMAGE_CREATE_DISJOINT_BIT flag states: 

> VK_IMAGE_CREATE_DISJOINT_BIT specifies that an image with a multi-planar format must have each plane separately bound to memory, rather than having a single memory binding for the whole image; the presence of this bit distinguishes a disjoint image from an image without this bit set."

What do you think @daveh-lunarg is that clear enough or should the spec still be updated?

**Comment by daveh-lunarg** [comment]
Yeah, it's clear that the intent of the disjoint bit is to allow (actually, require) multiple per-plane memory binding operations on a single image, but that conflicts with the spec's valid usage statement for `VUID-vkBindImageMemory-image-01044` that you quote above. This issue points out an oversight of the multi-plane extension, which should have modified the memory binding valid usage statement to explicitly mention per-plane binding and/or partially-bound images. 

IMO we do need to have the spec language corrected before modifying the validation code. We try to be very careful to make the validation code match the spec's valid usage statements exactly, and in my experience trying to finesse it into _what they meant to say_ can easily cause more problems than it solves.

I think this also suggests some other AFAIK-unaddressed questions that should be discussed in the spec, like is it okay to bind only a subset of the planes if that's all you intend to access - i.e. is a partially-bound image considered bound or unbound at draw time? It would be good to get these type of questions in front of the extension authors, to improve overall spec quality.

**Comment by daveh-lunarg** [comment]
On further review, I think the spec is fine. I was confused by the implications of vkBindImageMemory2() called multiple times on a disjoint image, potentially creating partially-bound images. That's not allowed based on the "all or none" valid usage statement just above, so images are always not-bound or entirely-bound, and therefore the -01044 VUID language is fine as-is.

@ilkkasaa, if you're calling bindImageMemory2() just once to bind all planes, then you should not receive the -01044 error.  I will try to repro that case and fix it if so. If OTOH you're calling bIM2 multiple times, you should receive a _different_ error, which as I look at the validation status table I see is Not Yet Implemented. :(

**Comment by ilkkasaa** [comment]
>(Deleted final comment - with only a little more reading I find that partially-bound images are addressed by this VU statement: "A single call to vkBindImageMemory2 must bind all or none of the planes of an image".)

Well, I missed that part while reading the spec.

You are right about that calling bindImageMemory2() once to bind all planes does not generate any errors. I guess I messed up something earlier when I got the error message by calling it once. Now I'm not able to reproduce the error anymore. It was my mistake.

**Comment by daveh-lunarg** [comment]
Well, the spec itself is not terribly user-friendly. :)  I was convinced the language was broken for the first couple passes, as well.
