### ISSUE TITLE
No validation errors for drawIndirectFirstInstance and multiDrawIndirect on new SDK

### ISSUE THREAD

**Issue by pc-john** [KhronosGroup/Vulkan-ValidationLayers#5838]
**The problem**

No validation errors on new Vulkan SDK although older SDK produced correct errors.

I call vkCmdDrawIndexedIndirect() with VkDrawIndirectCommand::firstInstance greater than 1 while I did not enabled drawIndirectFirstInstance. This leads to validation error on old SDK, but nothing happens on the new one. Unless I am missing something it seems like a regression.

The same for multiDrawIndirect feature. If I call vkCmdDrawIndexedIndirect() with drawCount parameter greater than 1, I get validation error on old SDK but not on the new one. 

**Environment**

Old SDK: 1.2.198.1, running on machine with Quadro K1000M, Vulkan device version: 1.2.175
New SDK: 1.3.246.0, running on Quadro RTX 3000, Vulkan device version: 1.3.205

**Validation errors**

Correctly reported validation errors from the old SDK that are missing when using the new SDK:

<pre>
VUID-vkCmdDrawIndexedIndirect-drawCount-02718(ERROR / SPEC): msgNum: 1646706667 - Validation Error: [ VUID-vkCmdDrawIndexedIndirect-drawCount-02718 ] Object 0: handle = 0x5560569a20b8, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6226bfeb | CmdDrawIndexedIndirect(): Device feature multiDrawIndirect disabled: count must be 0 or 1 but is 100000 The Vulkan spec states: If the multi-draw indirect feature is not enabled, drawCount must be 0 or 1 (https://vulkan.lunarg.com/doc/view/1.2.198.0/linux/1.2-extensions/vkspec.html#VUID-vkCmdDrawIndexedIndirect-drawCount-02718)
    Objects: 1
        [0] 0x5560569a20b8, type: 3, name: NULL
VUID-vkCmdDrawIndexedIndirect-firstInstance-00530(ERROR / SPEC): msgNum: -2060933307 - Validation Error: [ VUID-vkCmdDrawIndexedIndirect-firstInstance-00530 ] Object 0: handle = 0x5560563ce108, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0x8528a745 | The drawIndirectFirstInstance feature is not enabled, but the firstInstance member of the VkDrawIndirectCommand structure at index 1 is not zero The Vulkan spec states: If the drawIndirectFirstInstance feature is not enabled, all the firstInstance members of the VkDrawIndexedIndirectCommand structures accessed by this command must be 0 (https://vulkan.lunarg.com/doc/view/1.2.198.0/linux/1.2-extensions/vkspec.html#VUID-vkCmdDrawIndexedIndirect-firstInstance-00530)
    Objects: 1
        [0] 0x5560563ce108, type: 4, name: NULL
</pre>

**Comment by spencer-lunarg** [comment]
hmm, let me write a test and make sure we are doing this still

**Comment by spencer-lunarg** [comment]
> VUID-vkCmdDrawIndexedIndirect-drawCount-02718

I added https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5845 and seems this is correct in latest ToT (Also seems to work for me in the SDK version as well)

> VUID-vkCmdDrawIndexedIndirect-firstInstance-00530

This was removed in favor of `VUID-VkDrawIndexedIndirectCommand-firstInstance-00554` https://github.com/KhronosGroup/Vulkan-Docs/pull/1913

**Comment by spencer-lunarg** [comment]
it is failing on the one device with `maxDrawIndirectCount` limit of 1, will fix the test

**Comment by pc-john** [comment]
Thanks again for the test. I see the test is ok now. I made another investigation on my side, and unfortunately, I cannot reproduce the problem today. Whatever I am doing, the problem is gone. It might be some hidden mistake on my side, or if it is related to Validation Layers, it would be probably more general configuration issue. I am going to close this issue today.

Just for the case the problem reappears, would you advice me how to run an application with particular version of Vulkan Validation layers if that is possible? Even the hint would be very helpful.

**Comment by spencer-lunarg** [comment]
Either the SDK or ToT version is ok

Also either an API dump or an GFXReconstruct trace (can dump the API calls from it) is helpful so I can see exactly what is going on

Thanks again for raising these issues, we are always trying to add more tests to improve edge cases like these
