### ISSUE TITLE
Missing Negative Tests

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/Vulkan-ValidationLayers#5842]
I went through all the validation we are checking but missing a test to see how bad it really was

a LOT of "missing tests" are really just because we have things like `vkCmdDraw` or `VK_KHR_copy_commands2` that would require writing the same test, but with/without extensions (which I think is not high priority at all)

I also removed some sections such as RTX, Vendor EXT, and WSI, and things where it depended on NOT having an extension enabled from the list

There is about 100 tests here that I feel should be added as they are not that hard (might be wrong) and are worth to catch future changes to the layers

- [x] `VUID-VkAttachmentDescription-format-06243` | core 
- [x] `VUID-VkAttachmentDescription-format-06242` | core 
- [x] `VUID-VkAttachmentDescription-format-06487` | (VK_VERSION_1_1,VK_KHR_maintenance2) 
- [x] `VUID-VkAttachmentDescription-format-06488` | (VK_VERSION_1_1,VK_KHR_maintenance2) 
- [x] `VUID-VkBufferCreateInfo-flags-00915`   | core 
- [x] `VUID-VkBufferCreateInfo-flags-00916`   | core 
- [x] `VUID-VkBufferCreateInfo-flags-00917`   | core 
- [x] `VUID-VkBufferCreateInfo-size-06409`    | (VK_VERSION_1_3,VK_KHR_maintenance4) 
- [x] `VUID-VkBufferCreateInfo-usage-08103`   | (VK_EXT_descriptor_buffer) 
- [x] `VUID-VkClearDepthStencilValue-depth-00022` | (VK_EXT_depth_range_unrestricted) 
- [x] `VUID-VkColorBlendEquationEXT-constantAlphaColorBlendFactors-07362` | (VK_EXT_extended_dynamic_state3,VK_EXT_shader_object)+(VK_KHR_portability_subset) 
- [x] `VUID-VkColorBlendEquationEXT-constantAlphaColorBlendFactors-07363` | (VK_EXT_extended_dynamic_state3,VK_EXT_shader_object)+(VK_KHR_portability_subset) 
- [x] `VUID-VkCommandBufferBeginInfo-flags-00055` | core 
- [x] `VUID-VkCopyDescriptorSet-dstArrayElement-00348`    | core 
- [x] `VUID-VkCopyDescriptorSet-dstBinding-00347` | core 
- [x] `VUID-VkCopyDescriptorSet-dstBinding-02632` | core 
- [x] `VUID-VkCopyDescriptorSet-srcArrayElement-00346`    | core 
- [x] `VUID-VkCopyDescriptorSet-srcBinding-00345` | core 
- [ ] `VUID-VkCopyDescriptorSet-srcSet-00349` | core 
- [x] `VUID-VkCopyDescriptorSet-srcSet-01918` | (VK_VERSION_1_2,VK_EXT_descriptor_indexing) 
- [x] `VUID-VkCopyDescriptorSet-srcSet-01920` | (VK_VERSION_1_2,VK_EXT_descriptor_indexing) 
- [x] `VUID-VkDescriptorImageInfo-imageView-07795`    | (VK_VERSION_1_1,VK_KHR_maintenance1)+(VK_EXT_image_2d_view_of_3d) 
- [ ] `VUID-VkDescriptorImageInfo-sampler-01564`  | (VK_VERSION_1_1,VK_KHR_sampler_ycbcr_conversion) 
- [x] `VUID-VkDescriptorSetLayoutBinding-descriptorCount-00283`   | core 
- [x] `VUID-VkDescriptorSetLayoutBinding-descriptorType-00282`    | core 
- [x] `VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-None-03011`   | (VK_VERSION_1_2,VK_EXT_descriptor_indexing) 
- [x] `VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-descriptorBindingInlineUniformBlockUpdateAfterBind-02211` | (VK_VERSION_1_2,VK_EXT_descriptor_indexing)+(VK_VERSION_1_3,VK_EXT_inline_uniform_block) 
- [x] `VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-descriptorBindingPartiallyBound-03013`    | (VK_VERSION_1_2,VK_EXT_descriptor_indexing) 
- [x] `VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-descriptorBindingSampledImageUpdateAfterBind-03006`   | (VK_VERSION_1_2,VK_EXT_descriptor_indexing) 
- [x] `VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-descriptorBindingStorageBufferUpdateAfterBind-03008`  | (VK_VERSION_1_2,VK_EXT_descriptor_indexing) 
- [x] `VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-descriptorBindingStorageImageUpdateAfterBind-03007`   | (VK_VERSION_1_2,VK_EXT_descriptor_indexing) 
- [x] `VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-descriptorBindingStorageTexelBufferUpdateAfterBind-03010` | (VK_VERSION_1_2,VK_EXT_descriptor_indexing) 
- [x] `VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-descriptorBindingUniformTexelBufferUpdateAfterBind-03009` | (VK_VERSION_1_2,VK_EXT_descriptor_indexing) 
- [x] `VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-descriptorBindingUpdateUnusedWhilePending-03012`  | (VK_VERSION_1_2,VK_EXT_descriptor_indexing) 
- [x] `VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-descriptorBindingVariableDescriptorCount-03014`   | (VK_VERSION_1_2,VK_EXT_descriptor_indexing) 
- [x] `VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-flags-03003`  | (VK_VERSION_1_2,VK_EXT_descriptor_indexing)+(VK_KHR_push_descriptor) 
- [x] `VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-pBindingFlags-03004`  | (VK_VERSION_1_2,VK_EXT_descriptor_indexing) 
- [x] `VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-pBindingFlags-03015`  | (VK_VERSION_1_2,VK_EXT_descriptor_indexing) 
- [ ] `VUID-VkDescriptorSetLayoutCreateInfo-flags-02208`  | (VK_KHR_push_descriptor)+(VK_VERSION_1_3,VK_EXT_inline_uniform_block) 
- [x] `VUID-VkDescriptorSetVariableDescriptorCountAllocateInfo-descriptorSetCount-03045`  | (VK_VERSION_1_2,VK_EXT_descriptor_indexing) 
- [x] `VUID-VkDeviceQueueCreateInfo-pQueuePriorities-00383`   | core 
- [x] `VUID-VkDeviceQueueCreateInfo-queueCount-00382` | core 
- [x] `VUID-VkFramebufferCreateInfo-flags-02778`  | core 
- [x] `VUID-VkFramebufferCreateInfo-pAttachments-00877`   | core 
- [x] `VUID-VkFramebufferCreateInfo-pAttachments-00879`   | core 
- [x] `VUID-VkGraphicsPipelineCreateInfo-TessellationEvaluation-07723`    | core 
- [x] `VUID-VkGraphicsPipelineCreateInfo-TessellationEvaluation-07724`    | core 
- [x] `VUID-VkGraphicsPipelineCreateInfo-pDynamicStates-00754`    | core 
- [x] `VUID-VkGraphicsPipelineCreateInfo-renderPass-06043`    | core 
- [x] `VUID-VkGraphicsPipelineCreateInfo-renderPass-06046`    | core 
- [x] `VUID-VkGraphicsPipelineCreateInfo-renderPass-06575`    | (VK_VERSION_1_3,VK_KHR_dynamic_rendering) 
- [x] `VUID-VkGraphicsPipelineCreateInfo-renderPass-06583`    | (VK_VERSION_1_3,VK_KHR_dynamic_rendering) 
- [x] `VUID-VkGraphicsPipelineCreateInfo-renderPass-06584`    | (VK_VERSION_1_3,VK_KHR_dynamic_rendering) 
- [x] `VUID-VkGraphicsPipelineCreateInfo-renderPass-06585`    | (VK_VERSION_1_3,VK_KHR_dynamic_rendering) 
- [x] `VUID-VkGraphicsPipelineCreateInfo-renderPass-06586`    | (VK_VERSION_1_3,VK_KHR_dynamic_rendering) 
- [x] `VUID-VkImageBlit-aspectMask-00238` | core 
- [x] `VUID-VkImageCreateInfo-flags-01572`    | (VK_VERSION_1_1,VK_KHR_maintenance2) 
- [x] `VUID-VkImageCreateInfo-flags-01573`    | (VK_VERSION_1_1,VK_KHR_maintenance2) 
- [x] `VUID-VkImageCreateInfo-flags-01924`    | core 
- [x] `VUID-VkImageCreateInfo-format-01577`   | (VK_VERSION_1_1,VK_KHR_sampler_ycbcr_conversion) 
- [x] `VUID-VkImageCreateInfo-tiling-04121`   | core 
- [x] `VUID-VkImageMemoryRequirementsInfo2-image-02279`   | (VK_VERSION_1_1,VK_KHR_get_memory_requirements2)+(VK_VERSION_1_1,VK_KHR_sampler_ycbcr_conversion)+(VK_EXT_image_drm_format_modifier) 
- [x] `VUID-VkImageResolve-aspectMask-00266`  | core 
- [x] `VUID-VkMemoryMapInfoKHR-memory-07962`  | (VK_KHR_map_memory2) 
- [x] `VUID-VkMemoryPriorityAllocateInfoEXT-priority-02602`   | (VK_EXT_memory_priority) 
- [x] `VUID-VkPhysicalDeviceRobustness2FeaturesEXT-robustBufferAccess2-04000` | (VK_EXT_robustness2) 
- [x] `VUID-VkPipelineColorWriteCreateInfoEXT-attachmentCount-06655`  | (VK_EXT_color_write_enable) 
- [x] `VUID-VkPipelineDepthStencilStateCreateInfo-depthBoundsTestEnable-00598`    | core 
- [x] `VUID-VkPipelineMultisampleStateCreateInfo-alphaToOneEnable-00785`  | core 
- [x] `VUID-VkPipelineRasterizationStateCreateInfo-depthClampEnable-00782`    | core 
- [x] `VUID-VkRenderingInfo-imageView-06107`  | (VK_VERSION_1_3,VK_KHR_dynamic_rendering)+(VK_EXT_fragment_density_map) 
- [x] `VUID-VkRenderingInfo-pNext-06121`  | (VK_VERSION_1_3,VK_KHR_dynamic_rendering)+(VK_KHR_fragment_shading_rate)+(VK_VERSION_1_1,VK_KHR_device_group) 
- [x] `VUID-VkSamplerCreateInfo-addressModeU-01078`   | core 
- [x] `VUID-VkSamplerCreateInfo-compareEnable-01080`  | core 
- [x] `VUID-VkSamplerCreateInfo-customBorderColors-04085` | (VK_EXT_custom_border_color) 
- [x] `VUID-VkSubpassDescription-layout-02519`    | core 
- [x] `VUID-VkWriteDescriptorSet-descriptorType-04150`    | core 
- [x] `VUID-VkWriteDescriptorSet-descriptorType-04151`    | core 
- [x] `VUID-VkWriteDescriptorSetInlineUniformBlock-dataSize-02222`    | (VK_VERSION_1_3,VK_EXT_inline_uniform_block) 
- [x] `VUID-vkBeginCommandBuffer-commandBuffer-00051` | core 
- [x] `VUID-vkBeginCommandBuffer-commandBuffer-00052` | core 
- [ ] `VUID-vkCmdBeginRenderPass-dstStageMask-06452`  | core 
- [ ] `VUID-vkCmdBeginRenderPass-srcStageMask-06451`  | core 
- [ ] `VUID-vkCmdBindDescriptorSets-pDescriptorSets-08010`    | (VK_EXT_descriptor_buffer) 
- [x] `VUID-vkCmdBindDescriptorSets-pDynamicOffsets-01972`    | core 
- [x] `VUID-vkCmdBindIndexBuffer-buffer-00433`    | core 
- [x] `VUID-vkCmdBindPipeline-pipelineBindPoint-00777`    | core 
- [x] `VUID-vkCmdBindPipeline-pipelineBindPoint-00778`    | core 
- [x] `VUID-vkCmdBindVertexBuffers-pBuffers-00627`    | core 
- [x] `VUID-vkCmdClearAttachments-aspectMask-07884`   | (VK_VERSION_1_3,VK_KHR_dynamic_rendering) 
- [x] `VUID-vkCmdClearAttachments-aspectMask-07885`   | (VK_VERSION_1_3,VK_KHR_dynamic_rendering) 
- [x] `VUID-vkCmdClearColorImage-aspectMask-02498`    | core 
- [x] `VUID-vkCmdClearColorImage-image-01993` | (VK_VERSION_1_1,VK_KHR_maintenance1) 
- [x] `VUID-vkCmdClearDepthStencilImage-aspectMask-02824` | core 
- [x] `VUID-vkCmdSetDepthBias-depthBiasClamp-00790`   | core 
- [x] `VUID-vkCreateCommandPool-queueFamilyIndex-01937`   | core 
- [x] `VUID-vkResetEvent-event-03823` | (VK_VERSION_1_3,VK_KHR_synchronization2) 
- [x] `VUID-vkSetEvent-event-03941`   | (VK_VERSION_1_3,VK_KHR_synchronization2) 
- [x] `VUID-vkUpdateDescriptorSets-pDescriptorWrites-06493`   | core

**Comment by ziga-lunarg** [comment]
I believe the remaining VUIDs can't be hit without hitting another VUID as well.
