### ISSUE TITLE
vkUpdateDescriptorSets mismatch with the specification

### ISSUE THREAD

**Issue by vkaytsanov** [KhronosGroup/Vulkan-ValidationLayers#5880]
**Environment:**
 - OS: Windows 11
 - GPU: NVIDIA GeForce RTX 3070 Ti
 - SDK or header version if building from repo: Vulkan 1.3.236
 - Options enabled (synchronization, best practices, etc.):

**Describe the Issue**
`vkUpdateDescriptorSets` fails with the validatior error below, while in the specification it says that the layout `VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL` is possible choice.
https://vulkan.lunarg.com/doc/view/1.3.204.1/windows/1.3-extensions/vkspec.html#descriptorsets-combinedimagesampler

```sh
# callstacks, crashes, etc.
# EX:
[ VUID-VkWriteDescriptorSet-descriptorType-04150 ] Object 0: handle = 0x5581c500000000d5, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0xf72a82b8 | vkUpdateDescriptorSets() pDescriptorWrites[4] failed write update validation for VkDescriptorSet 0x5581c500000000d5[] with error: Write update to VkDescriptorSet 0x5581c500000000d5[] allocated with VkDescriptorSetLayout 0xad092800000000d0[] binding #10 failed with error message: Attempted write update to combined image sampler descriptor failed due to: Descriptor update with descriptorType VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER is being updated with invalid imageLayout VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL for image VkImage 0x9fde6b0000000014[] in imageView VkImageView 0xd897d90000000016[]. Allowed layouts are: VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, VK_IMAGE_LAYOUT_GENERAL, VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL, VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL. The Vulkan spec states: If descriptorType is VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER the imageLayout member of each element of pImageInfo must be a member of the list given in Combined Image Sampler (https://vulkan.lunarg.com/doc/view/1.3.204.1/windows/1.3-extensions/vkspec.html#VUID-VkWriteDescriptorSet-descriptorType-04150)
```

</details>

**Comment by juan-lunarg** [comment]
Yeah I can see the bug in the validation layer code in `cc_descriptor.cpp`. Thankfully there is a helpful comment pointing out the problem exactly.

`The following works as currently all 3 descriptor types share the same set of valid layouts`

This is no longer the case.

**Comment by spencer-lunarg** [comment]
wait, I don't see the bug

we have the code 

```c++
const static std::array<ExtensionLayout, 8> extended_layouts{{
    // ..
    {VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL, &DeviceExtensions::vk_khr_separate_depth_stencil_layouts},
}};
```

My guess is your app is either a Vulkan 1.0/1.1 at Instance Creation time and `VK_KHR_separate_depth_stencil_layouts` wasn't enabled

**Comment by vkaytsanov** [comment]
Nice catch, @spencer-lunarg. Seems that when creating the instance, I have been using a wrong macro to specify the `engineVersion` and `apiVersion`. Excuse me for the false accusation @spencer-lunarg, @juan-lunarg

**Comment by spencer-lunarg** [comment]
awesome! Don't worry, happy to know this is not an issue

I am going to close the issue (as I see nothing left) but @ncesario-lunarg it seems we are not hitting `std::vector<VkImageLayout> ValidationObject::ValidParamValues()`? I would assume this would have printed out the error that the enum was not allowed to be used

**Comment by juan-lunarg** [comment]
My bad for the confusion. I jumped the gun based on my cursory reading of the code/spec and lack of test for `VUID-VkWriteDescriptorSet-descriptorType-04150`
