### ISSUE TITLE
layer_configuration.md does not describe programmatic configuration of layers

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [KhronosGroup/Vulkan-ValidationLayers#5895]
The file https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/LAYER_CONFIGURATION.md does not explain how to enable layers programmatically. I think it should. This file is used by the SDK and referenced by all other layers in the SDK as the general guide on how to configure layers.

I know we are working on defining an API for programmatically configuring layers, should we wait to update this referenced documentation until that API is defined and made public? @christophe-lunarg

**Comment by mark-lunarg** [comment]
The existing `vk_layer_settings_ext.h` allows setting layer options programmatically.  When the updated version arrives with the rework the method will be very similar with the exception of having to include the header file.

**Comment by KarenGhavam-lunarG** [comment]
See [#5895](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5895). layer_configuration.md describes how to configure layers and is used in the SDK documentation and referenced by all SDK layers. I believe this document should be updated with how to configure layers programmatically.

**Comment by christophe-lunarg** [comment]
Unless there is an explicit request from a user, I think we should way until the updated extenion is ready as this will be relatively soon.

**Comment by juan-lunarg** [comment]
Assigning @christophe-lunarg due to their recent work in VVL.

**Comment by christophe-lunarg** [comment]
This issue is resolved by https://github.com/KhronosGroup/Vulkan-Utility-Libraries/pull/85

**Comment by spencer-lunarg** [comment]
as @christophe-lunarg said, this seems resolved and actually just missing someone closing the issue
