### ISSUE TITLE
Improve Object Tracker error messages

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-ValidationLayers#5898]
I updated today and now I'm getting a bunch of these errors:

```
VUID-vkCmdBindPipeline-commonparent(ERROR / SPEC): msgNum: -1497306210 - Validation Error: [ VUID-vkCmdBindPipeline-commonparent ] Object 0: handle = 0x5e50a50, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xa6c0eb9e | Object 0xba7514000000002a of type VkPipeline was not created, allocated or retrieved from the correct device. The Vulkan spec states: Both of commandBuffer, and pipeline must have been created, allocated, or retrieved from the same VkDevice (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdBindPipeline-commonparent)
```

**Environment:**
 - OS: linux
 - GPU: any
 - SDK or header version if building from repo: 8f4fc4c98acf7a6a2c77524a389969a651b7a8c9
 - Options enabled (synchronization, best practices, etc.):

Reproduce with `ZINK_DEBUG=validation MESA_LOADER_DRIVER_OVERRIDE=zink ./glcts -n KHR-GLES31.core.compute_shader.simple-compute-shared_context`

**Comment by zmike** [comment]
I also get a bonus VVL crash if I add this VUID to my ignore list.

**Comment by spencer-lunarg** [comment]
The issue is `vkCreateComputePipelines` used `VkDevice = 0x55cbf7f4c4d0` to create the `VkPipeline`

The `VkCommandBuffer = 0x55cbf93f0040` in `vkCmdBindPipeline` used a `vkAllocateCommandBuffers` with  `VkDevice = 0x55cbf9721ef0`
     
So the issue is the `VkDevice` are not the same for the Pipeline and CommandBuffer in this bind

**Comment by zmike** [comment]
Ohh okay, that error message is a bit misleading. It'd be great if it could be improved to:
* explicitly state that the cmdbuf and pipeline were allocated from different devices
* print the pointers of the cmdbuf, pipeline, device(s)

**Comment by spencer-lunarg** [comment]
This is a generated error check (and message)

I agree the error message is not great. I will alter this issue to fix the error message (assuming it was actually catching the error)
