### ISSUE TITLE
Usage flags requirement not enforced for indirect buffers

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#59]
**Issue by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Wednesday Jan 10, 2018 at 15:35 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2333_

----

Similar to the validation we do for vertex buffers & index buffers today. As of 1.0.60 or so we have VUs in the spec for these cases.

Will add the checks for this so we can force CTS to get this right.

**Comment by mark-lunarg** [comment]
Validation for buffer usage flags is present in corechecks:
```
• VUID-vkCmdDrawIndirect-buffer-02709
• VUID-vkCmdDrawIndirectCount-buffer-02709
• VUID-vkCmdDrawIndirectCount-countBuffer-02715
• VUID-vkCmdDrawIndexedIndirect-buffer-02709
• VUID-vkCmdDrawIndexedIndirectCount-buffer-02709
• VUID-vkCmdDrawIndexedIndirectCount-countBuffer-02715
• VUID-vkCmdDrawMeshTasksIndirectNV-buffer-02709
• VUID-vkCmdDrawMeshTasksIndirectCountNV-buffer-02709
• VUID-vkCmdDrawMeshTasksIndirectCountNV-countBuffer-02715
• VUID-vkCmdDispatchIndirect-buffer-02709
```
