### ISSUE TITLE
Pipeline creation should ignore VkPipelineMultisampleStateCreateInfo with rasterization disabled

### ISSUE THREAD

**Issue by aitor-lunarg** [KhronosGroup/Vulkan-ValidationLayers#5931]
**Environment:**
 - OS: Any
 - GPU: Any
 - SDK or header version if building from repo: ToT
 - Options enabled (synchronization, best practices, etc.): None

**Describe the Issue**

While looking at a CTS crash with VVL enabled, I noticed VVL tries to copy an invalid `VkPipelineMultisampleStateCreateInfo` pointer from pipeline creation with rasterization disabled. The CTS test is: `dEQP-VK.api.pipeline.pipeline_invalid_pointers_unused_structs.graphics`

The spec states the following:
`pMultisampleState is a pointer to a VkPipelineMultisampleStateCreateInfo structure defining multisample state used when rasterization is enabled.`

**Expected behavior**

CTS forces drivers to ignore `VkPipelineMultisampleStateCreateInfo` if no rasterization happens. VVL shouldn't crash either.

**Comment by juan-lunarg** [comment]
Re-opening based on message from @aitor-lunarg

**Comment by aitor-lunarg** [comment]
Reverting #5932 since it does not correctly detect when pMultisampleState is required. Need to take into account dynamic state and pipeline libraries correctly.

Some failures from CTS provided by @Tony-LunarG:
```
Test case 'dEQP-VK.pipeline.monolithic.extended_dynamic_state.before_draw.null_rasterization_state'..
Test case 'dEQP-VK.pipeline.monolithic.extended_dynamic_state.two_draws_dynamic.null_rasterization_state'..
Test case 'dEQP-VK.pipeline.monolithic.extended_dynamic_state.mesh_shader.between_pipelines.null_rasterization_state'..
Test case 'dEQP-VK.pipeline.monolithic.extended_dynamic_state.mesh_shader.two_draws_static.null_rasterization_state'..
Test case 'dEQP-VK.pipeline.monolithic.extended_dynamic_state.between_pipelines.null_rasterization_state'..
Test case 'dEQP-VK.pipeline.monolithic.extended_dynamic_state.two_draws_static.null_rasterization_state'..
Test case 'dEQP-VK.pipeline.monolithic.extended_dynamic_state.mesh_shader.after_pipelines.null_rasterizaton_state'..
Test case 'dEQP-VK.pipeline.monolithic.extended_dynamic_state.after_pipelines.null_rasterization_state'..
Test case 'dEQP-VK.pipeline.monolithic.extended_dynamic_state.mesh_shader.cmd_buffer_start.null_rasterization_state'..
Test case 'dEQP-VK.pipeline.monolithic.extended_dynamic_state.mesh_shader.before_good_static.null_rasterization_state'..
Test case 'dEQP-VK.pipeline.monolithic.extended_dynamic_state.cmd_buffer_start.null_rasterization_state'..
Test case 'dEQP-VK.pipeline.monolithic.extended_dynamic_state.before_good_static.null_rasterization_state'..
Test case 'dEQP-VK.pipeline.monolithic.extended_dynamic_state.mesh_shader.before_draw.null_rasterization_state'..
Test case 'dEQP-VK.pipeline.monolithic.extended_dynamic_state.mesh_shader.two_draws_dynamic.null_rasterization_state'..
```

#6012 is another issue due to the change

**Comment by Eearslya** [comment]
I just assisted a user with this issue, and though the validation layers didn't *crash*, they did emit a confusing error that stated `pMultisampleState` must not be NULL, despite the fact that a valid multisample state was provided. (Relevant check [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/layers/core_checks/cc_pipeline_graphics.cpp#L1948))

Similar situation, valid pipeline creation info, but the user simply forgot to specify `pRasterizationState`, leaving it at NULL. They were also using dynamic rendering.
