### ISSUE TITLE
Yocto cross-compile build issues when base_libdir 'lib64'

### ISSUE THREAD

**Issue by EasyIP2023** [KhronosGroup/Vulkan-ValidationLayers#5964]
**Environment:**
 - OS: Linux
 - GPU: N/A
 - SDK Version: **Branch:** 1.3.243, **tag:** sdk-1.3.243.0

**Describe the Issue**
```
error: '<absolute path>/vulkan-validation-layers/1.3.243.0-r0/recipe-sysroot/usr/lib', needed by 'layers/libVkLayer_khronos_validation.so', missing and no known rule to make it
```

In Yocto if base lib directory is `lib64`, `/usr/lib` would be `/usr/lib64`. Thus, `/usr/lib` doesn't exists leading to above build issue. After debugging one can see that in `build/build.ninja`

```
LINK_LIBRARIES = \
    layers/libVkLayer_utils.a
    <absolute path>/vulkan-validation-layers/1.3.243.0-r0/recipe-sysroot/usr/lib64/libSPIRV-Tools-opt.so
    <absolute path>/vulkan-validation-layers/1.3.243.0-r0/recipe-sysroot/usr/lib64/libSPIRV-Tools.so
    <absolute path>/vulkan-validation-layers/1.3.243.0-r0/recipe-sysroot/usr/lib
```

After looking into [main/CMakeLists.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/CMakeLists.txt) and [layers/CMakeLists.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/layers/CMakeLists.txt). I'm unable to
determine where `<absolute path>/usr/lib` could potentially be set. The question I have is, how after the cmake configure/generate step would `<absolute path>/usr/lib` potentially be added to cmake `LINK_LIBRARIES` list. From the CMakeLists.txt files and Yocto project [cmake.bbclass](https://github.com/openembedded/openembedded-core/blob/master/meta/classes-recipe/cmake.bbclass) there doesn't seem to be anything enabling this behavior.

**NOTE:** Removing `<absolute path>/usr/lib` manually from `build/build.ninja` leads to successful builds.

**Expected behavior**

Be able to build regardless of what base_libdir is set to.
Potential Options
* `/usr/lib`
* `/usr/lib32`
* `/usr/lib64`

**Comment by EasyIP2023** [comment]
Link to OE PR with proposed solution.

https://lists.openembedded.org/g/openembedded-core/topic/99300453#182345

**Comment by juan-lunarg** [comment]
Is this at all similar to the vulkan tools issue?
https://github.com/KhronosGroup/Vulkan-Tools/pull/808

Because I just integrated a similar fix for the validation layers.
https://github.com/KhronosGroup/Vulkan-Tools/pull/808

**Comment by EasyIP2023** [comment]
@juan-lunarg Thank you for the quick response. Think it may be something else.

After digging with  `cmake --trace-expand <other flags>` the perpetrator may be the cmake property `INTERFACE_LINK_LIBRARIES`. Believe it may is being set somewhere not in repo.

I assumed it was in `SPRIV-toolsTarget.cmake`, Manually changing bellow doesn't change above behavior.

```
/../../../../recipe-sysroot/usr/lib64/cmake/SPIRV-Tools/SPIRV-ToolsTarget.cmake

set_target_properties(SPIRV-Tools-shared PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SPIRV_TOOLS_SHAREDLIB"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "${_IMPORT_PREFIX}/lib"
)
```

**Comment by EasyIP2023** [comment]
Issue is actually in OE-core

https://github.com/openembedded/openembedded-core/blob/master/meta/recipes-graphics/spir/spirv-tools_1.3.243.0.bb#L31
