### ISSUE TITLE
validation should check whether a vkCmdPipelineBarrier is called between vkCmdUpdateBuffer and vkCmdDrawIndirect

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#6]
**Issue by [mathiasschott](https://github.com/mathiasschott) (MIGRATED)**
_Friday Aug 26, 2016 at 08:31 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/892_

----

The application is constructing a VkDrawIndexedIndirectCommand buffer on host and then updating the device buffer with the data from host. This buffer is then used as the argument for an indirect draw.  Missing a memory/buffer barrier in between those caused "issues"...

vkCmdUpdateBuffer 
vkCmdPipelineBarrier // validation layer should report the lack of this call
vkCmdDrawIndirect

**Comment by mark-lunarg** [comment]
Moved to the sync tracking issue, #72.
