### ISSUE TITLE
Validate correct topology based on GS feature

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#60]
**Issue by [tobine](https://github.com/tobine) (MIGRATED)**
_Tuesday Jan 16, 2018 at 17:31 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2344_

----

This is VALIDATION_ERROR_0fc0035a which is not yet validated. Spec states:

> If the geometry shaders feature is not enabled, topology must not be any of VK_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY, VK_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY, VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY or VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY

**Comment by mark-lunarg** [comment]
This vuid "VUID-VkPipelineInputAssemblyStateCreateInfo-topology-00429" is implemented in corechecks.
