### ISSUE TITLE
Feature Request: Selective shader check in GPU-AV

### ISSUE THREAD

**Issue by dorian-apanel-intel** [KhronosGroup/Vulkan-ValidationLayers#6009]
In current app that I'm debugging, enabling GPU-AV causes drivers to use much more RAM at shader compilation, and total pipelines compile time is increased from 2 minutes to 2 hours.

I know the shader where issue occurs and would like to enable GPU-AV only to a selected shaders.
Ability to specify list in file which shaders are to be validated would help here a lot.

List could be a file of VK_EXT_shader_module_identifier in hex ascii. Alternatively it could it be a DebugUtilsLabel/DebugMarkerObjectName (but those can be set after module creation).

**Comment by spencer-lunarg** [comment]
I agree with this, the biggest question is "how" to select

I think the "cleanest" way would have some `pNext` struct passed down that lets you opt-in/out... but maybe not

**Comment by dorian-apanel-intel** [comment]
For app/game developers pNext would be enough. For driver developers a file or list that could be selected from vkconfig.

**Comment by jeremyg-lunarg** [comment]
@Tony-LunarG is also going to be looking at caching the instrumented shaders, which will help when doing repeated runs and only changing a few shaders. But I agree that this is a good feature to investigate.

@dorian-apanel-intel in the meantime you should make sure you have mimalloc enabled, it should improve the speed of the instrumentation code. For windows you can enable it with the `USE_MIMALLOC` cmake option (it should be on by default), but for Linux you need to use `LD_PRELOAD` as describe [here](https://github.com/microsoft/mimalloc).

**Comment by Tony-LunarG** [comment]
Feature implemented in #6711
