### ISSUE TITLE
VK_EXT_transform_feedback: Specifying 0 as vertexStride for vkCmdDrawIndirectByteCountEXT() does not trigger a validation error

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-ValidationLayers#601]
If a zero vertex stride is specified for the command, some pretty bad stuff happens on our implementation. However, no validation error is reported for this use case.

From VK_EXT_transform_feedback ext spec, vertexCount is calculated as floor(max(0, (*counterBufferPtr - counterOffset)) / vertexStride), so that explains the behavior of our driver.

At the time of writing, there's no VU defined for this corner case. I'm going to chase this issue separately.

**Comment by DominikWitczakAMD** [comment]
@jzulauf-lunarg : Yeah, thanks for your help on this! As usual, I got side-tracked at some point and never got around to actually raising a MR that would solve the missing VU issue..

**Comment by jzulauf-lunarg** [comment]
New VU language for VUID-vkCmdDrawIndirectByteCountEXT-vertexStride-02289 will be (approximately)

> `vertexStride` must be greater than 0 and less than or equal to `VkPhysicalDeviceLimits::maxTransformFeedbackBufferDataStride`

Add range check for this VU.

**Comment by mark-lunarg** [comment]
Running through CI.

**Comment by mark-lunarg** [comment]
This was fixed in mid-December.  Thanks!
