### ISSUE TITLE
Bug detecting when multisample-state is needed

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-ValidationLayers#6012]
Since ccf7e6f84cebd5651ece34c64d1545dcde91a996, ANGLE over SwiftShader is crashing where SwiftShader is handling libraries created with `VK_GRAPHICS_PIPELINE_LIBRARY_FRAGMENT_OUTPUT_INTERFACE_BIT_EXT`.

That commit decides that multisample state is not used if there is no fragment shader. However, that state is used by both the fragment and fragment output stages. VVL is setting multisample state to nullptr, causing a crash.

@spencer-lunarg

**Comment by aitor-lunarg** [comment]
Currently taking a look at it. I'll first revert the change and reintroduce a correct change later down the road. There are also some failures in CTS (provided by @Tony-LunarG), so I should have enough information to tackle the issue. PR #6013

**Comment by Tony-LunarG** [comment]
Fixed in #6013
