### ISSUE TITLE
Validation layer does not report errors if too many output components / locations are used in a shader

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-ValidationLayers#602]
No errors are reported if too many output variables or components are defined in a vertex shader (possibly other shader stages are also affected).

Since it doesn't take much for an app to miss these requirements, having these covered by validation layers would be very useful.

**Comment by jzulauf-lunarg** [comment]
@greg-lunarg  @chrisforbes -- is this something the current static analysis already counts up for us, and thus could be simply checked against the device limits?  Or is this something new to track?  c.f. https://www.khronos.org/registry/vulkan/specs/1.1-khr-extensions/html/vkspec.html#interfaces-iointerfaces-limits

**Comment by DominikWitczakAMD** [comment]
@chrisforbes : Last time I checked, which was with core validation layer build coming from sometime last week, XFB tests I've been working on, which really put these limits to a great use :-), did not trigger any errors (whereas the driver code would cringe in terror). I'd be more than happy to test any candidate PRs containg a fix.

**Comment by DominikWitczakAMD** [comment]
And yeah, I only mentioned vertex shader stage not being covered, but I should be able to run the tests for GFX pipelines covering other vertex processing stages as well.

**Comment by chrisforbes** [comment]
I'm still unclear on what we're doing wrong.

There was a spec clarification recently that builtins consume components against these limits. Is that possibly in play here?

**Comment by DominikWitczakAMD** [comment]
Most certainly, yes.

**Comment by greg-lunarg** [comment]
Do you have a shader that demonstrates the problem?

**Comment by mark-lunarg** [comment]
Was this perhaps addressed as part of #862?

**Comment by DominikWitczakAMD** [comment]
I've been swamped with other stuff for the last couple of months and unlikely to find time to reinvestigate this for some time from now. I'm happy to close the ticket for now and raise a new one when I get to rerunning our entire internal test coverage with validation layers at some point in the future.

Appreciate your eyes on this :-)
