### ISSUE TITLE
rt::ComputeScratchSize crashing CTS (Disable 03703 03704 03705)

### ISSUE THREAD

**Issue by arno-lunarg** [KhronosGroup/Vulkan-ValidationLayers#6040]
`rt::ComputeScratchSize` is causing a crash in the driver in CTS. 
Validation for `VUID-vkCmdBuildAccelerationStructuresKHR-dstAccelerationStructure-03703`, `VUID-vkCmdBuildAccelerationStructuresKHR-scratchData-03704` and `VUID-vkCmdBuildAccelerationStructuresKHR-scratchData-03705` will be disabled for now and re-enabled when a fix is found.

**Comment by dorian-apanel-intel** [comment]
I bumped onto it yesterday. I think at least one issue is here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/886d29ee27e1aaf359ddc55e9b97353a97563842/layers/core_checks/cc_ray_tracing.cpp#L473

In following code:
```
if (scratch == other_scratch) {
    return false;
}
```

If two scratch spaces with the same buffer are passed, but without overlapping ranges, it treats it as an error.

**Comment by arno-lunarg** [comment]
You are right, thank you for spotting this!

**Comment by arno-lunarg** [comment]
Still crashing in CTS. 2 tests can be used to try to reproduce, `dEQP-VK.ray_tracing_pipeline.opacity_micromap.disable_opacity_micromap_instance.map_value.2.level_9` and `dEQP-VK.ray_query.builtin.flow.vert.triangles`
When only `dEQP-VK.ray_tracing_pipeline.opacity_micromap.disable_opacity_micromap_instance.map_value.2.level_9` is ran, the test fails.
if only `dEQP-VK.ray_query.builtin.flow.vert.triangles` is ran, the test passes.
If both are ran in a row, the second test fails with `VUID-vkDestroyFence-fence-01120` and `VUID-vkFreeCommandBuffers-pCommandBuffers-00047`, and hangs in `layer_chassis_dispatch_manual.cpp 1143 auto lock = dispatch_cb_write_lock();`. Since CTS does not skip invalid (per the validation layer) vulkan calls, and since per 00047 the command buffer is still in flight, a hang in `vkFreeCommandBuffers` is "normal". But it started with commit https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/3bb7b3cbff4e6422118dd0a837f7a978a0138bbb and there is no obvious link between this hang and this commit

**Comment by spencer-lunarg** [comment]
@arno-lunarg with all these fixes, if you could run these on your NVIDIA machine with the latest CTS and confirm they don't crash now

- `deqp-vk.exe -n dEQP-VK.ray_tracing_pipeline.opacity_micromap.*` 
- `deqp-vk.exe -n dEQP-VK.ray_query.*`

then I think we are good to close this

**Comment by arno-lunarg** [comment]
Finally took the time to run those tests, no crash, closing
