### ISSUE TITLE
`VK_EXT_descriptor_buffer`: NVidia driver crash w/out validation error when `VK_DESCRIPTOR_SET_LAYOUT_CREATE_DESCRIPTOR_BUFFER_BIT_EXT` omitted

### ISSUE THREAD

**Issue by goulash32** [KhronosGroup/Vulkan-ValidationLayers#6050]
Issue description:
I had an embarrassingly long debugging session trying to figure out why my app was crashing upon calling `vkCmdSetDescriptorBufferOffsetsEXT()` after binding my descriptor buffers. This was on the latest Vulkan SDK (1.3.250.0) on the latest Windows 10 update, with the current release drivers (536.23) for my GeForce RTX 2070 Max-Q.

I did many back-and-forth comparisons with Sascha Willem's example (which ran fine on my machine), but ultimately it turns out I had neglected to include the `VK_DESCRIPTOR_SET_LAYOUT_CREATE_DESCRIPTOR_BUFFER_BIT_EXT` flag when creating my descriptor set layouts. Mea culpa, but it would have been great to have an informative validation error message in such a scenario.

Please include the valid usage IDs for the checks you are requesting:
I cannot find an extant VUID that corresponds to this issue.

**Comment by spencer-lunarg** [comment]
Thanks for debugging and reporting this info

I see there is no VU for `vkCmdSetDescriptorBufferOffsetsEXT` to check the `VK_DESCRIPTOR_SET_LAYOUT_CREATE_DESCRIPTOR_BUFFER_BIT_EXT` flag... but I think there are other places that would need something similar

I realized you already posted this in the `Vulkan-Docs` to move it here, but first thing I will do is purpose a spec change to make sure every HW vendor agrees of the limitations (differentiates if this is a driver bug or validaiton missing coverage), then will come back and add the VUs missing!

**Comment by spencer-lunarg** [comment]
(sorry took a bit longer then wanted) but this is now in the 1.3.258 spec as `VUID-vkCmdSetDescriptorBufferOffsetsEXT-firstSet-09006` and just need to add
