### ISSUE TITLE
debugPrintfEXT print only one

### ISSUE THREAD

**Issue by magicse** [KhronosGroup/Vulkan-ValidationLayers#6063]
**Environment:**
 - OS:  Windows
 - GPU: NVIDIA 1050 Ti
 - SDK last
 - Options enabled (synchronization, best practices, etc.): VALIDATION + Debug Ptrintf

I create shdaer for ncnn library, and for debug use debugPrintfEXT and vkconfig.
But debugPrintfEXT print message only from frist debugPrintfEXT()

shader example
```
#version 450

#if NCNN_fp16_storage
#extension GL_EXT_shader_16bit_storage: require
#endif
#if NCNN_fp16_arithmetic
#extension GL_EXT_shader_explicit_arithmetic_types_float16: require
#endif

#extension GL_EXT_debug_printf : enable
#extension GL_GOOGLE_include_directive: enable
#include "vulkan_activation.comp"
void main()
{
	debugPrintfEXT("*** Hello 1");
	debugPrintfEXT("*** Hello 2");
}
```
print only 
*** Hello 1
*** Hello 1
*** Hello 1
*** Hello 1

if  I change shader
```
void main()
{
	//debugPrintfEXT("*** Hello 1");
	debugPrintfEXT("*** Hello 2");
}
```

print only 
*** Hello 2
*** Hello 2
*** Hello 2
*** Hello 2

**Comment by filnet** [comment]
Multiple invocations of the shader are run in parallel so what you are seeing is the expected behavior.
Many calls to `debugPrintfEXT("*** Hello 1");` will be issued before `debugPrintfEXT("*** Hello 2");` is called.
You then hit the maximum message size limit and the `debugPrintfEXT("*** Hello 2");` are not shown.

This makes using debugPrintfEXT() interesting :)

Some tricks that can help are:
* combine the two `debugPrintfEXT()`  calls into one : ``debugPrintfEXT("*** Hello 1 Hello 2");`` 
* find some way to call `debugPrintfEXT()` under some condition.
````
if (<first invocation>) {
        debugPrintfEXT("*** Hello 1");
	debugPrintfEXT("*** Hello 2");
}
````

**Comment by filnet** [comment]
If the message buffer was big enough you would see:
```
*** Hello 1
*** Hello 1
*** Hello 1
*** Hello 1
...
*** Hello 2
*** Hello 2
*** Hello 2
*** Hello 2
```

**Comment by magicse** [comment]
It look like this
```
*** Hello 1
*** Hello 1
*** Hello 1
*** Hello 1
*** Hello 1
*** Hello 1
*** Hello 1
*** Hello 1
*** Hello 1
*** Hello 1
*** Hello 1
*** Hello 1
*** Hello 1
*** Hello 1
*** Hello 1
*** Hello 1

UNASSIGNED-DEBUG-PRINTF(WARN / SPEC): msgNum: -1841738615 - Validation Warning: [ UNASSIGNED-DEBUG-PRINTF ] Object 0: handle = 0x38f52d0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x92394c89 | WARNING - Debug Printf message was truncated, likely due to a buffer size that was too small for the message
    Objects: 1
        [0] 0x38f52d0, type: 3, name: NULL

Process terminated
```

**Comment by magicse** [comment]
> If the message buffer was big enough you would see:
> 
> ```
> *** Hello 1
> *** Hello 1
> *** Hello 1
> *** Hello 1
> [...]
> *** Hello 2
> *** Hello 2
> *** Hello 2
> *** Hello 2
> ```

Why like this ?
> ```
> *** Hello 1
> *** Hello 1
> *** Hello 1
> *** Hello 1
> [...]
> *** Hello 2
> *** Hello 2
> *** Hello 2
> *** Hello 2
> ```
and not like this 
> ```
> *** Hello 1
> *** Hello 2
> *** Hello 1
> *** Hello 2
> [...]
> *** Hello 1
> *** Hello 2
> *** Hello 1
> *** Hello 2
> ```

**Comment by Tony-LunarG** [comment]
You can also increase the size of the printf buffer by setting khronos_validation.printf_buffer_size in your layer settings file or you can use vkconfig and under Validation / GPU Base (pick debug printf) / Printf buffer size (bytes) and set it to something larger than the 1024 default.

**Comment by magicse** [comment]
@Tony-LunarG  @filnet  Thank You for helpimg.
I found another strange thing with debugPrintfEXT().
For example if my variable is int and I want formating it as float for print or backward, I always got zeros.

```
    int gx = int(gl_GlobalInvocationID.x) * 2;
    int gy = int(gl_GlobalInvocationID.y) * 2;
    int gz = int(gl_GlobalInvocationID.z) * 2;
    debugPrintfEXT("**** Shader psc(outw) gx gy (%i, %i, %f)\n", psc(outw), gx, gy);
```
Output 
	
**** Shader psc(outw) gx gy (72, 16, 0.000000)
**** Shader psc(outw) gx gy (72, 18, 0.000000)
**** Shader psc(outw) gx gy (72, 20, 0.000000)
**** Shader psc(outw) gx gy (72, 22, 0.000000)
**** Shader psc(outw) gx gy (72, 24, 0.000000)
**** Shader psc(outw) gx gy (72, 26, 0.000000)
**** Shader psc(outw) gx gy (72, 28, 0.000000)
**** Shader psc(outw) gx gy (72, 30, 0.000000)
**** Shader psc(outw) gx gy (72, 16, 0.000000)
**** Shader psc(outw) gx gy (72, 18, 0.000000)
**** Shader psc(outw) gx gy (72, 20, 0.000000)

```
    int gx = int(gl_GlobalInvocationID.x) * 2;
    int gy = int(gl_GlobalInvocationID.y) * 2;
    int gz = int(gl_GlobalInvocationID.z) * 2;
    debugPrintfEXT("**** Shader psc(outw) gx gy (%i, %i, %i)\n", psc(outw), gx, gy);
```
Output 

**** Shader psc(outw) gx gy (72, 16, 24)
**** Shader psc(outw) gx gy (72, 18, 24)
**** Shader psc(outw) gx gy (72, 20, 24)
**** Shader psc(outw) gx gy (72, 22, 24)
**** Shader psc(outw) gx gy (72, 24, 24)
**** Shader psc(outw) gx gy (72, 26, 24)
**** Shader psc(outw) gx gy (72, 28, 24)
**** Shader psc(outw) gx gy (72, 30, 24)
**** Shader psc(outw) gx gy (72, 16, 26)
**** Shader psc(outw) gx gy (72, 18, 26)
**** Shader psc(outw) gx gy (72, 20, 26)
**** Shader psc(outw) gx gy (72, 22, 26)
**** Shader psc(outw) gx gy (72, 24, 26)
**** Shader psc(outw) gx gy (72, 26, 26)
**** Shader psc(outw) gx gy (72, 28, 26)

**Comment by Tony-LunarG** [comment]
I get the same thing in C:
```
int hork = 24;
printf("Hork = %f", hork);
```
Hork = 0.000000

debugPrintf uses sprintf to format variable values, so whatever it does, debugPrintf will do.

**Comment by magicse** [comment]
Thank you very much for your patience and help.
I have one more last question.

In shaders i saw this "afp v0" , "psc(c) ", "afpvec4"
I didn't understand what this the types ... afp, psc , afpvec4? I couldn't find any information about this.

GLSL data type C data type Description
bool int A conditional type, taking on values of true or false.
int int Signed integer.
float float Single floating-point scalar.
vec2 float [2] Two component floating-point vector.
vect3 float [3] Three component floating-point vector.
vec4 float [4] Four component floating-point vector.
bvec2 int [2] Two component Boolean vector.
bvec3 int [3] Three component Boolean vector.
bvec4 int [4] Four component Boolean vector.
ivec2 int [2] Two component signed integer vector.
ivec3 int [3] Three component signed integer vector.
ivec4 int [4] Four component signed integer vector.
mat2 float [4] 2×2 floating-point matrix.
mat3 float [9] 3×3 floating-point matrix.
mat4 float [16] 4×4 floating-point matrix.
sampler1D int Handle for accessing a 1D texture.
sampler2D int Handle for accessing a 2D texture.
sampler3D int Handle for accessing a 3D texture.
samplerCube int Handle for accessing a cubemap texture.
sampler1DShadow int A handle for accessing a 1D depth texture with comparison.
Sampler2DShadow int A handle for accessing a 2D depth texture with comparison.

**Comment by magicse** [comment]
I found this here [gpu.cpp](https://github.com/FeiGeChuanShu/ncnn/blob/6209448f9b5354d56f8da4a1a2215fe5251c3be6/src/gpu.cpp#L3291)
