### ISSUE TITLE
Test crashes/failures for Radeon RX 6800 XT (RADV NAVI21) on Ubuntu 22.04

### ISSUE THREAD

**Issue by johnzupin** [KhronosGroup/Vulkan-ValidationLayers#6076]
This machine has been upgraded to Ubuntu 22.04, so the radv driver was updated but the GPU is the same.

Crashes: 
- `VkAmdBestPracticesLayerTest.NumberOfSubmissions`
- `VkBestPracticesLayerTest.SwapchainCreationTest`
- `VkGpuAssistedLayerTest.GpuDrawIndirectCountDeviceLimit`
- `NegativeRayTracing.CmdCopyUnboundAccelerationStructure`
- `NegativeWsi.InitSwapchainPotentiallyIncompatibleFlag`
- `NegativeWsi.SwapchainImageParams`
- `NegativeWsi.SwapchainNotSupported`
- `NegativeWsi.SwapchainMinImageCountNonShared`
- `PositiveWsi.SwapchainExclusiveModeQueueFamilyPropertiesReferences`

Failures:
- `VkArmBestPracticesLayerTest.PresentModeTest`
- `VkGpuAssistedLayerTest.GpuBufferDeviceAddressOOB`
- `NegativeImage.Image2DViewOf3D`
- `NegativeRayTracing.BuildAccelerationStructureKHR`
- `NegativeSyncVal.QSPresentAcquire`
- `NegativeWsi.SwapchainAcquireImageNoSync`
- `NegativeWsi.SwapchainAcquireImageNoSync2KHR`
- `NegativeWsi.SwapchainAcquireImageNoBinarySemaphore`
- `NegativeWsi.SwapchainAcquireImageNoBinarySemaphore2KHR`
- `NegativeWsi.SwapchainAcquireTooManyImages`
- `NegativeWsi.GetSwapchainImageAndTryDestroy`
- `NegativeWsi.SwapchainAcquireTooManyImages2KHR`
- `NegativeWsi.SwapchainImageFormatList`
- `NegativeWsi.SwapchainUsageNonShared`
- `NegativeWsi.WarningSwapchainCreateInfoPreTransform`
- `NegativeWsi.SwapchainAcquireImageWithSignaledSemaphore`
- `NegativeWsi.SurfaceSupportByPhysicalDevice`
- `NegativeWsi.CreatingSwapchainWithExtent`
- `NegativeWsi.SwapchainAcquireImageRetired`

These two tests also needed to be excluded for the test to pass as they seem to crash as well, they are not in the attached blacklist.txt:
- `VkPositiveLayerTest.DestroySwapchainWithBoundImages`
- `NegativeWsi.BindImageMemorySwapchain`

[blacklist.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/11887003/blacklist.txt)
[vulkaninfo.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/11887026/vulkaninfo.txt)

**Comment by spencer-lunarg** [comment]
spent last week on https://github.com/LunarG/VulkanTests/pull/483 and this should be reset now
