### ISSUE TITLE
broken vkCmdSetAttachmentFeedbackLoopEnableEXT handling

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-ValidationLayers#6092]
Using latest git from today, this seems broken. The cmdbuf state is never recorded (no state tracker handling), so VU 08877 is printed for every cmdbuf submission.

**Comment by spencer-lunarg** [comment]
Thanks for the fast fix @ncesario-lunarg ... the rework for `VK_EXT_shader_object` will help with all the random places we need to touch for every random dynamic state to prevent this stuff
