### ISSUE TITLE
icd: Add support for vkGetPhysicalDeviceFeatures2KHR pNext extension queries

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#61]
**Issue by [jzulauf-lunarg](https://github.com/jzulauf-lunarg) (MIGRATED)**
_Friday Jan 26, 2018 at 22:40 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2374_

----

The mock_icd needs to report valid limit/feature information for all extensions it reported as supported.  Currently mock_icd ignores the pNext chain for vkGetPhysicalDeviceFeatures2KHR where the extension features are queried.  

However, when validation support is added for an extension, the features and limits need to be reported back with valid (for example guaranteed minimums given in the spec) values in order for validation to have proper bounds/feature checks and for validation testing to function correctly.

**Comment by mark-lunarg** [comment]
This issue should be migrated to Vulkan-Tools.
