### ISSUE TITLE
Descriptor buffer CTS tests crash running with synchronization validation

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-ValidationLayers#6112]
**Environment:**
 - OS:  Windows 10
 - GPU: RTX 2080
 - SDK or header version if building from repo:  1.3.253
 - Options enabled (synchronization, best practices, etc.): synchronization

With synchronization validation enabled, and all other validation disabled, these tests crash:
dEQP-VK.binding_model.descriptor_buffer.push_template.graphics_vert_sets2_push_set0
dEQP-VK.binding_model.descriptor_buffer.push_descriptor.graphics_vert_sets2_push_set0

The crash is vector subscript out of range in sync_validation.cpp line 2048:
```const auto *descriptor_set = (*per_sets)[variable.decorations.set].bound_descriptor_set.get();```
per_sets is size of 1, variable.decorations.set is 1

**Expected behavior:**

The tests should not crash

**Comment by artem-lunarg** [comment]
This started happening after https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5420
It's not clear if that change is the root cause but it enabled this behavior

**Comment by artem-lunarg** [comment]
@Tony-LunarG, the latest code has fix for this crash

**Comment by Tony-LunarG** [comment]
Verified fixed - Thanks!
