### ISSUE TITLE
build is broken with 32bit and 64bit in same tree

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-ValidationLayers#6121]
If I clone VVL and configure both a 32bit and 64bit build in the same tree (with the same config but different build dirs), the second one will fail because all the deps are built into "Debug" and "Release" directories without specifying arch, which leads to trying to link the wrong arch's intermediate objects into the final library.

**Comment by juan-lunarg** [comment]
This is a known issue with our `UPDATE_DEPS` workflow. I'll look into fixing it.

As an immediate workaround you can set `UPDATE_DEPS_DIR`.

**Comment by juan-lunarg** [comment]
I have a fix for this now. This will be fixed by end of day.

**Comment by juan-lunarg** [comment]
Sorry this took a while. The actual fix was easy. The hard part was fixing up the scripts cleanly.

**Comment by juan-lunarg** [comment]
This should work now @zmike apologies for the delay

**Comment by zmike** [comment]
Awesome, thanks!
