### ISSUE TITLE
Detect that no query has been sent with BeginQuery/EndQuery before when calling GetQueryPoolResults

### ISSUE THREAD

**Issue by dabrain34** [KhronosGroup/Vulkan-ValidationLayers#6129]
**Describe the situation in which you encountered the missing validation**
When implementing a video encoder, I encountered a dead lock in the driver when querying the encoding result without calling Begin/End combo before.
I see that there is a check in the [EndQuery](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/2ce44f7f1928edb981adc587d8d3e2fb0f41e975/layers/core_checks/cc_query.cpp#L761), could we add this check in [GstQueryPoolResult](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/2ce44f7f1928edb981adc587d8d3e2fb0f41e975/layers/core_checks/cc_query.cpp#L113) ?

**Valid Usage IDs requested**
Check that a query has been sent in GstQueryPoolResult

**Additional Context**

**Comment by dabrain34** [comment]
@ncesario-lunarg ping

**Comment by ncesario-lunarg** [comment]
Should there be a VUID for `GetQueryPoolResults` that is similar to, e.g., 01923?

**Comment by aqnuep** [comment]
I don't think there should be anything video specific here, other than a potential driver bug in the way queries are implemented for the video queues on the implementation in question.

I believe calling `vkGetQueryPoolResults` on a query index that was never actually executed (i.e. no begin/end query was executed for it) is legal and should return that the query result is unavailable, except in one important case, per the following spec language:

```
After query pool creation, each query must: be reset before it is used.
Queries must: also be reset between uses.
```

As I believe per the current spec it is undefined to use any query in a pool if it wasn't reset before, hence a crash may be actually okay and expected if the application did not at least reset the query after creating the pool.

**Comment by aqnuep** [comment]
Btw, I believe there are no VUs for requiring queries to be reset before use, but maybe I just missed where they are. If, however, there aren't, maybe there should be per the spec excerpt above.

**Comment by artem-lunarg** [comment]
@dabrain34 does `vkGetQueryPoolResults` specify `VK_QUERY_RESULT_WAIT_BIT`?
According to the specification the wait is indefinite if query is not made available with with {Begin/End}Query.

**Comment by artem-lunarg** [comment]
Added some Best Practices suggestions:
https://github.com/orgs/KhronosGroup/projects/20/views/1?pane=issue&itemId=33287299
