### ISSUE TITLE
VUID-VkImageCreateInfo-imageCreateMaxMipLevels-02251 could be more detailed

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-ValidationLayers#6134]
If I get this error, e.g.,

```
Validation Error: [ VUID-VkImageCreateInfo-imageCreateMaxMipLevels-02251 ] Object 0: handle = 0x28df55bb2000, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xbebcae79 | vkCreateImage(): Format VK_FORMAT_B8G8R8A8_UNORM is not supported for this combination of parameters and VkGetPhysicalDeviceImageFormatProperties returned back VK_ERROR_FORMAT_NOT_SUPPORTED. The Vulkan spec states: Each of the following values (as described in Image Creation Limits) must not be undefined : imageCreateMaxMipLevels, imageCreateMaxArrayLayers, imageCreateMaxExtent, and imageCreateSampleCounts (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkImageCreateInfo-imageCreateMaxMipLevels-02251)
```

it would be nice if VVL could be more detailed if it knows which params are broken, or in the case where it isn't, just print all the params.

**Comment by spencer-lunarg** [comment]
agree... this VU (because of DMR format modifier and Android External formats) is easily one of the nastiest VUs... I agree the message is less than desirable

**Comment by spencer-lunarg** [comment]
actually looking more into this, the whole way we are checking this seems strange and lacks any real test, thanks for bringing this up, happy (kinda :upside_down_face: ) to get this quickly fixed
