### ISSUE TITLE
VK_ERROR_INITIALIZATION_FAILED

### ISSUE THREAD

**Issue by fwgreuter** [KhronosGroup/Vulkan-ValidationLayers#615]
Hi,
I am a video newby but I program c++ for several years.
My first assignment in the investigate if a new AMD GPU works faster than intel GPU.
So everything seems in place, all sample programs build.
GPU is detected by vulkan sdk (although it say unknown AMD GPU) and it looks a lot like the closed issue:
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2152

Attached is the vkvia.html output (changed the extension)
[vkvia.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/2782432/vkvia.txt)

**Comment by fwgreuter** [comment]
When I run the example the output is:

./vkcubepp
vkcubepp: /home/wmt/vulkan/1.1.92.1/examples/cube.cpp:1757: void Demo::prepare_depth(): Assertion `result == vk::Result::eSuccess' failed.
Aborted (core dumped)

**Comment by jeremy-lunarg** [comment]
How did you install the SDK? It appears that you have artifacts from both the Ubuntu packages and the tar-ball.

**Comment by jzulauf-lunarg** [comment]
@fwgreuter -- this looks to be packaging or configuration issue.  @jeremy-lunarg

**Comment by jeremy-lunarg** [comment]
Would you mind logging this issue on [lunarxchange](https://vulkan.lunarg.com/)? We can follow up over there. I don't believe this is a layers issue.

**Comment by fwgreuter** [comment]
as request moved to https://vulkan.lunarg.com/issue (issue 832)
