### ISSUE TITLE
spirv_tools_commit_id.h missing from BUILD

### ISSUE THREAD

**Issue by aabdolrashidi** [KhronosGroup/Vulkan-ValidationLayers#6167]
In the commit 0aa649cb7db151421e2737dc1b34f7421b59b8d1, the following change has been made in the renamed `layers/utils/shader_utils.h`:
```
-#include <generated/spirv_tools_commit_id.h>
+#include "generated/spirv_tools_commit_id.h"
```
However, `spirv_tools_commit_id.h` is missing from `core_validation_sources` in `BUILD.gn`. This causes errors in presubmit testing when rolling into ANGLE.
CC: @spencer-lunarg

**Comment by juan-lunarg** [comment]
> However, `spirv_tools_commit_id.h` is missing from `core_validation_sources` in `BUILD.gn`. This causes errors in presubmit testing when rolling into ANGLE.

We test the chromium build as part of CI. Why didn't that catch the build error?

**Comment by juan-lunarg** [comment]
Should be fixed now @aabdolrashidi

I'm confused how this issue emerged though.

**Comment by aabdolrashidi** [comment]
Thank you! The test now passes.
I am also not sure. The presubmit for ANGLE checks that all the header files not ignored are listed in the GN target.

**Comment by juan-lunarg** [comment]
>  I am also not sure. The presubmit for ANGLE checks that all the header files not ignored are listed in the GN target.

How does ANGLE check for this?

This is the script we use to test our GN build:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/971615e6d890a362af0f764de8e95895aa18a9a6/scripts/github_ci_gn.py#L22

**Comment by aabdolrashidi** [comment]
It uses the the function `has_all_includes()` in [this script](https://chromium.googlesource.com/angle/angle/+/refs/heads/main/scripts/export_targets.py#286).

**Comment by juan-lunarg** [comment]
Ok well I see how this issue emerged. Our GN script we use in CI doesn't run this script at all.

I'm not sure how to prevent this issue in the future.
