### ISSUE TITLE
Validation layers crash due to VUID being null while logging an error during synchronization checks

### ISSUE THREAD

**Issue by yuphin** [KhronosGroup/Vulkan-ValidationLayers#6195]
**Environment:**
 - **SDK or header version if building from repo**: Encountered in 1.3.250, persists in the main branch
 - **Options enabled (synchronization, best practices, etc.)**: default

**Describe the Issue**
In the `CoreChecks::ValidateAccessMask` function in `cc_syncronization.cpp`, illegal pipeline stages are checked when the access mask is `VK_PIPELINE_STAGE_2_RAY_TRACING_SHADER_BIT_KHR`. If there is an illegal stage, a `vuid` is selected but the `vuid` retrieved via `sync_vuid_maps::GetAccessMaskRayQueryVUIDSelector` gets the mapping from `GetLocation2VUIDMap()` function, which is a mapping between various `VK_KHR_synchronization2` structs and strings. So when the underlying application is not using `VK_KHR_synchronization2`, and is instead using core Vulkan structs, this causes crashes in the `skip |= LogError(objlist, vuid, "%s", msg.str().c_str());` line in `CoreChecks::ValidateAccessMask` function due to `vuid` being nullptr.

In summary, it looks like the assumption that the application is using `VK_KHR_synchronization2` here causes crashes in the validation layers while logging errors.

**How to reproduce**
1 - In a memory barrier, when the access  flags contain `VK_ACCESS_2_ACCELERATION_STRUCTURE_READ_BIT_KHR`
2- Stage flags contain a stage other than `VK_PIPELINE_STAGE_2_RAY_TRACING_SHADER_BIT_KHR`. For example when the stage is `VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_BUILD_BIT_KHR`
3- The application is not using `VK_KHR_synchronization2` structs
An example scenario would be creating a barrier after the acceleration structure is built.
**Point of interest**
````
bool CoreChecks::ValidateAccessMask(const LogObjectList &objlist, const Location &loc, VkQueueFlags queue_flags,
                                    VkAccessFlags2KHR access_mask, VkPipelineStageFlags2KHR stage_mask) const {
...
 if (!enabled_features.ray_query_features.rayQuery && (access_mask & VK_ACCESS_2_ACCELERATION_STRUCTURE_READ_BIT_KHR)) {
        const auto illegal_pipeline_stages = allVkPipelineShaderStageBits2 & ~VK_PIPELINE_STAGE_2_RAY_TRACING_SHADER_BIT_KHR;
        if (stage_mask & illegal_pipeline_stages) {
            // Select right vuid based on enabled extensions
            const char *vuid = sync_vuid_maps::GetAccessMaskRayQueryVUIDSelector(loc, device_extensions);
            const auto stages_string = sync_utils::StringPipelineStageFlags(stage_mask);
            std::stringstream msg;
            msg << loc.Message() << " contains pipeline stages " << stages_string << '.';
            skip |= LogError(objlist, vuid, "%s", msg.str().c_str()); // <- causes the crash when vuid is nullptr
        }
  }
...
}

**Comment by artem-lunarg** [comment]
@yuphin Current validation logic has unified checks for original synchronization API and `VK_KHR_synchronization2` (which is now also part of core in Vulkan 1.3). My best explanation that it's because original stage/access enums are compatible with subset of corresponding enums from `VK_KHR_synchronization2`, so behavior defined in Sync2 should make sense for Sync1. Of course, there should be no crashes!

**Comment by artem-lunarg** [comment]
Also, we will suggest a change to the specification to introduce missing Sync1 VUIDs. Hopefully, that will make this part of validation less confusing.
