### ISSUE TITLE
Crash in vkCmdBindDescriptorSets() validation with NULL pipeline layout

### ISSUE THREAD

**Issue by llandwerlin-intel** [KhronosGroup/Vulkan-ValidationLayers#6213]
**Environment:**
 - OS: Linux
 - GPU: Intel
 - SDK or header version if building from repo: 1.3.250.0
 - Options enabled (synchronization, best practices, etc.):

**Describe the Issue**

Users are running into a validation layer crash when the application calls `vkCmdBindDescriptorSets()` with a NULL pipeline layout.

The issue appears to be in CoreChecks::PreCallValidateCmdBindDescriptorSets : https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/layers/core_checks/cc_descriptor.cpp#L193

The layout state is accessed without checking if the layout parameter is NULL.

**Expected behavior**

No crash

**Valid Usage ID**
None

**Additional context**
Reporting on the Intel Mesa driver : https://gitlab.freedesktop.org/mesa/mesa/-/issues/9412

**Comment by spencer-lunarg** [comment]
We have a test for ` VUID-vkCmdBindDescriptorSets-layout-parameter` which should be catching this

just to sanity check, you haven't turned off Stateless Validation from the config settings have you?

**Comment by spencer-lunarg** [comment]
> I know there is a test, but it seems to test an invalid pointer. Which is not quite the same as null. I don't know if that makes a difference.

The other test we had was using a garbage handle

Recently we have been making tests to check for these null checks, so could be an old version of VVL (will get info from Mesa issue)

**Comment by spencer-lunarg** [comment]
This should for sure be fixed in the latest 261 SDK, if issue persists happy to have issue reopened
