### ISSUE TITLE
Non SPIR-V dependent validation no longer executed when SPIR-V module data is not available since recent refactoring

### ISSUE THREAD

**Issue by aqnuep** [KhronosGroup/Vulkan-ValidationLayers#6224]
**Environment:**
 - OS: All
 - GPU: All
 - SDK or header version if building from repo: latest main
 - Options enabled (synchronization, best practices, etc.):

**Describe the Issue**

SPIR-V module data has been moved to a new `SPIRV_MODULE_STATE` object, but that object is not created for cases when a SPIR-V module is not available, e.g. if shader module identifier is used (see `PIPELINE_STATE::GetStageStates()` code creating placeholder module state for this case).

Also, validation code previously accepting `SHADER_MODULE_STATE` objects now take `SPRIV_MODULE_STATE` objects, even when they don't rely on any SPIR-V state (e.g. `ValidateSpecializations` or `ValidateShaderSubgroupSizeControl`).

As a result, `ValidatePipelineShaderStage` will not run certain validation for cases that could previously be validated due to the reliance on the existence of a `SPIRV_MODULE_STATE` object:

```c++
    if (pipeline.uses_shader_module_id || !stage_state.module_state->spirv) {
        return skip;  // these edge cases should be validated already
    }
```

Thus validation coverage has been lost in cases where SPIR-V data is unavailable (like in case of the use of shader module indentifiers), and non-SPIR-V validation code was made SPIR-V dependent.

**Expected behavior**

Validation that does not require SPIR-V data should execute even when such data is not present, like it happened before the recent refactoring. Thus technically this is a regression that isn't caught by any test case.

**Valid Usage ID**

The following VUIDs (not a complete list) which do not depend on SPIR-V data are no longer generated when SPIR-V data is not available:

  * `VUID-VkSpecializationInfo-offset-00773`
  * `VUID-VkSpecializationInfo-pMapEntries-00774`
  * `VUID-VkSpecializationInfo-constantID-04911`
  * `VUID-VkPipelineShaderStageCreateInfo-flags-02784`
  * `VUID-VkPipelineShaderStageCreateInfo-flags-02785`
  * `VUID-VkPipelineShaderStageCreateInfo-flags-08988`

There could be more.

**Comment by spencer-lunarg** [comment]
>  Thus technically this is a regression that isn't caught by any test case.

... that's unfortunate, did you hit this from a real world app or just from reviewing the code

I will get some tests together and fix this (since I made the change so we can get `VK_EXT_shader_object` hooked up)

**Comment by aqnuep** [comment]
> > Thus technically this is a regression that isn't caught by any test case.
> 
> ... that's unfortunate, did you hit this from a real world app or just from reviewing the code
> 
> I will get some tests together and fix this (since I made the change so we can get `VK_EXT_shader_object` hooked up)

I noticed this on the Vulkan SC side, where SPIR-V data is similarly usually unavailable, just like in case when shader module identifiers are used in Vulkan. So I thought that I file an issue about as it's a VUID coverage regression that also affects Vulkan, not just Vulkan SC. I didn't look into how many other VUIDs may be now similarly artificially conditioned on the presence of SPIR-V data, while the VUIDs themselves are SPIR-V independent, I just listed the ones I know certainly did.

**Comment by aqnuep** [comment]
Btw, I would note that this is a good example where VVL development can actually benefit from the additional coverage SC VVL adds downstream.

**Comment by spencer-lunarg** [comment]
Ok, so my goal is to separate the logic from being "everything shader related" in a single check to things that are dependent on the SPIR-V and those dependent on the Pipeline (to both help with `VK_EXT_shader_object` and issues like https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2835

I realize there are things like `ValidateShaderSubgroupSizeControl`, where the SPIR-V doesn't matter and just the pipeline creation information, but since it had been all blended together from before, there is no way to tell

I know that `VK_EXT_shader_module_identifier` was always kinda hacked into the way we did validation, my upcoming fix should fix this, but will add some extra tests of course as well

**Comment by aqnuep** [comment]
@spencer-lunarg, that all makes sense, but I think that in order to apply all VUID checks in all cases where they apply (even when SPIR-V data is not available but the VUID does not depend on SPIR-V) there is a need for one of the following fixes:

1. Revert validation interfaces not depending on SPIR-V data to accept `SHADER_MODULE_STATE` objects (like they did before) instead of `SPIRV_MODULE_STATE`, as the former should be available in all cases, unlike the latter
2. Change the implementation so that empty `SPIRV_MODULE_STATE` objects are created even when SPIR-V data is not available

I'd say (1) is the cleaner approach and thus probably should be preferred, but I'd leave it to your judgement what you believe is the correct solution.

**Comment by spencer-lunarg** [comment]
the reason I am going to hold back reverting is because I expect this week there will be changes for `VK_EXT_shader_object` that need to split the difference between a `SPIRV_MODULE_STATE` and `SHADER_MODULE_STATE` so we need to get #2 right... I plan to keep adding tests this week to help really lock down these edge cases

**Comment by aqnuep** [comment]
Sure. I wrote my response before seeing your PR. I think what's in PR #6226 is a good first step toward a long-term solution for the split.
