### ISSUE TITLE
Compile broken by SPIRV-Headers commit

### ISSUE THREAD

**Issue by romanl-g** [KhronosGroup/Vulkan-ValidationLayers#6225]
https://github.com/KhronosGroup/SPIRV-Headers/issues/365

**Comment by romanl-g** [comment]
CooperativeMatrixOperandsMatrixASignedComponentsMask no longer a valid constant

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/c320ff46b5a914dafe7e0512a6395ecd643de457/layers/core_checks/cc_spirv.cpp#L1000

**Comment by spencer-lunarg** [comment]
cc @HuYuxin

Ok, so I was confused before when I saw this issue, I didn't realize there was a random change to the Header to change the names. I updated to ToT `SPIRV-Headers` and `SPIRV-Tools`/`SPIRV-Reflect` for completeness and seems to be good now

**Comment by HuYuxin** [comment]
Thank you @spencer-lunarg for taking care of the fix!

**Comment by spencer-lunarg** [comment]
Should be fixed now with https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6235
