### ISSUE TITLE
vkCreateSwapChainKHR validation error on out-of-date surface capabilities

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-ValidationLayers#624]
Imagine the following scenario:

1. Create xcb window with size WxH.
2. Get surface capabilities (whose currentExtent shows WxH)
3. Create a swapchain with size WxH
4. Resize the window
5. Get new window size with `xcb_get_geometry`: AxB.
6. Recreate swapchain with size AxB.

This results in the following validation error:

```
vkCreateSwapChainKHR() called with imageExtent = (A,B), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (W,H), minImageExtent = (W,H), maxImageExtent = (W,H). The Vulkan spec states: imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01274)
```

If I add a call to get the surface capabilities (and not use it) between steps 5 and 6, the validation error goes away. My guess is that the capabilities are cached from the last call and are out of date.

Is this expected behavior? Is it not allowed to create a swapchain using sizes that are obtained through other means (which are identical to `currentExtent`) without having queried the surface capabilities?

**Comment by mark-lunarg** [comment]
Ping!

**Comment by cubanismo** [comment]
It should be fine to create a surface with a size queried elsewhere, e.g., gleaned from a window system event the app received.  The validation layers should probably insert a fresh get surface capabilities call themselves within the create swapchain call if they want to avoid this race to the extent possible. Note there is always a race though: The window system can resize the native surface at any time between when the size is queried and when the swapchain is effectively created.  Having the validation layers query the current size inside the create swapchain function would actually probably help uncover errors in apps not handling this well, though no app can handle it perfectly (this is a flaw in the current WSI APIs).
