### ISSUE TITLE
Move to ../layers/vulkan/generated/ broke includes.

### ISSUE THREAD

**Issue by CarloWood** [KhronosGroup/Vulkan-ValidationLayers#6246]
As you know an #include ".." with double quotes, as opposed to using angle brackets, first searches relative to the directory that the file, that has the `#include`, resides in.

When `vk_format_utils.cpp` was still in `.../layers/vulkan/vk_format_utils.cpp` its `#include "utils/vk_layer_utils.h"` worked as intended because `utils` is in `.../layers/vulkan/`.

However, now that this file was moved into `.../layers/vulkan/generated/` this no longer works.
To correct this, the include should now read: ` #include "../utils/vk_layer_utils.h"` (note the prepended `../`).

See
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/layers/vulkan/generated/vk_format_utils.cpp

Note that this file is "generated", so something else needs to be changed somewhere. Also, this might not be the only place where this change needs to be made (in theory every include using double quotes and some subdirectory that wasn't moved into generated/ as well needs to have added `../` in front of it).

I realize it will still compile if an include path is added to the compilation of projects that use `generated/vk_format_utils.cpp` to where `utils/` sits (aka, where `generated` sits), which is likely something like `/usr/include/vulkan/`, but it would be HARMFUL to demand vulkan users to add that include path. The idea is that one uses `#include <vulkan/....>` in the source code for namespace reasons, and having to add that `vulkan/` path as include directory might break other things.

**Comment by CarloWood** [comment]
Hmmpf. I just edited the file in `/usr/include/vulkan/generated` and then it turns out that `utils/vk_layer_utils.h` itself has:
```
#include "generated/vk_extension_helper.h"
#include "generated/vk_format_utils.h"
```
which also can't be found ... 
I guess more discussion is needed.  Is it (now?) required to have `/usr/include/vulkan` in my search path? That feels like a really bad idea and wasn't necessary before this move into generated :/

**Comment by spencer-lunarg** [comment]
this change was added in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5860 to allow for a `layers/vulkansc/generated` folder for Vulkan-SC to make use of (cc @aqnuep)

As for the includes not working, it should be... I guess are you having issues with this from cloning and building the Validation Layers, or do you have a setup to use just the utils files?

**Comment by aqnuep** [comment]
> this change was added in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5860 to allow for a layers/vulkansc/generated folder for Vulkan-SC to make use of (cc @aqnuep)

Minor correction. This directory structure was requested by VVL reviewers, as previously Vulkan SC simply used an alternative generated folder name (generated-vksc), but the generated subdirectory name has been added explicitly to every #include directive in the source files, hence this directory structure.

I guess this is related to the `BUILD_LAYER_SUPPORT_FILES` target which is expected to be soon subsumed by the Vulkan-Utility-Libraries and the fact that the generated files are installed under `{install_path}/include/vulkan/generated` while the utilities are installed under `{install_path}/include/vulkan/utils`.

**Comment by spencer-lunarg** [comment]
> Minor correction. 

i apologize, I was unaware that was the reason, makes sense

> soon subsumed by the Vulkan-Utility-Libraries 

I guess I am still not sure why and where the issue occurs, we have `target_include_directories(VkLayer_utils PUBLIC . ${API_TYPE})` which allows us to go `#include "generated/vk_extension_helper.h"`, still not sure where there becomes a namespace conflict or why this would require people to include/care about `/usr/include/vulkan` (I never use those headers when compiling, always the ones we grab from the `scripts/known_good.json`

**Comment by CarloWood** [comment]
In my application (a Vulkan Engine) I need the Format utilities for debug purposes; therefore I have a .cpp file with the following content:
```cpp
// The header file <vulkan/vk_object_types.h> was generated with this define defined.
// Therefore we must include vulkan/vulkan_core.h while the same macro is defined, or
// we end up with undefined enums.
#define VK_ENABLE_BETA_EXTENSIONS
#include <vulkan/vulkan_core.h>
// Afterwards we have to undefine the macro again because otherwise other compiler
// errors turn up!
#undef VK_ENABLE_BETA_EXTENSIONS
#include <vulkan/generated/vk_format_utils.cpp>
```
This looks like, and therefore is, a hack -- but I don't know of another way to get the functions defined in vk_format_utils.cpp into my application; and I thought: there must be a reason that they are distributed like that, together with the headers.

The above compiled for a long time while using:
```cpp
#include <vulkan/vk_format_utils.cpp>
```
without the `generated` part thus; I stopped working on my vulkan engine for several months, and when I continued vk_format_utils.cpp was clearly moved into vulkan/generated/ (as per the package that Arch linux distributes); so I changed the above file to include the `generated/` part. However, then the code didn't compile anymore because vk_format_utils.cpp contains `#include "utils/..."` and utils sits in the same directory as `generated`.

When using the correct relative path for the double-quote include then it should compile again, and that can impossibly break something for other people.

**Comment by CarloWood** [comment]
That is... when using `"../utils/..."` the included file is indeed found again, but it turns out to still not compile because the headers in `utils/` also include stuff that is in `vulkan/`.  Hence my question: do you really want people to have `vulkan/` in their include path? Again, that seems a bad idea.

**Comment by CarloWood** [comment]
For clarity, I am talking about #include-ing these files after they were installed (in my case in `/usr/include/vulkan/{generated,utils}`.

**Comment by juan-lunarg** [comment]
@CarloWood as was mentioned previously the Vulkan-Utility-Libraries will address this situation.

https://github.com/KhronosGroup/Vulkan-Utility-Libraries/issues/18

In the future the validation layers will no longer install any header/source files. The validation layer repo authors make no promises of anything outside the BUILD.md (https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/BUILD.md#cmake-installed-files).

The reason for the current way things are done is largely historical.

In the future instead of consuming these files via VVL (via an unintended deliverable) you and other users will be able to consume them via a proper dependency.

**Comment by juan-lunarg** [comment]
Please see https://github.com/KhronosGroup/Vulkan-Utility-Libraries

VVL no longer installs header / source file deliverables
