### ISSUE TITLE
Compilation broken by Vulken-Header updates to 1.3.261

### ISSUE THREAD

**Issue by HuYuxin** [KhronosGroup/Vulkan-ValidationLayers#6263]
Similar to https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6225, the VVL compilation in chromium broke due to it is not catching up with the latest vulkan-header update 1.3.261 change: https://github.com/KhronosGroup/Vulkan-Headers/commit/450ead13e1064584da027d91192bd7bfb724640f.

Would you help us update the `vulkan-headers` in VVL to the latest version? Thank you.

**Comment by spencer-lunarg** [comment]
we have a PR readay here https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6264

I will find time later today to confirm it and we will merge it in

**Comment by spencer-lunarg** [comment]
ok, so this happened because there was an emergency  backward compatibility breaking change for the `VK_KHR_maintenance5` extension having the wrong suffixes, once #6264 finishes CI, I will merge it and should unblock you

**Comment by HuYuxin** [comment]
Thank you @spencer-lunarg so much for the quick fix!
