### ISSUE TITLE
 Tests failures for Nvidia RTX 2080 TI on Windows 10 with 532.34 beta driver

### ISSUE THREAD

**Issue by johnzupin** [KhronosGroup/Vulkan-ValidationLayers#6272]
On Windows 10 with a Nvidia RTX 2080 TI GPU and using the 532.34 beta driver the following tests will fail

- `NegativeDynamicState.DiscardRectanglesVersion`
- `NegativeViewportInheritance.BasicUsage`
- `NegativeViewportInheritance.MultiViewport`

[blacklist.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/12284025/blacklist.txt)

**Comment by spencer-lunarg** [comment]
should be fixed once both https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6273 and https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6275 are in

**Comment by johnzupin** [comment]
Looks like both of these merged, closing.
