### ISSUE TITLE
Issues with post-build step in tests/layers/CMakeLists.txt

### ISSUE THREAD

**Issue by nsubtil** [KhronosGroup/Vulkan-ValidationLayers#628]
In tests/layers/CMakeLists.txt there's a post-build step declared around line 120:

```
    add_custom_command(TARGET ${TEST_LAYER_NAME} POST_BUILD
                       COMMAND xcopy /Y /I ${SRC_LAYER} ${DST_LAYER}
                       COMMAND xcopy /Y /I ${SRC_JSON} ${DST_LAYER})
```

* SRC_LAYER is generated by the TEST_LAYER_NAME target, but it looks like SRC_JSON is not, which could cause dependency tracking issues on parallel builds
* The custom command target does not track outputs, which means these files will not be cleaned, causing issues with clean / rebuild targets
* SRC_LAYER is set to a glob pattern (`*device_profile_api.*`) that appears to match other files generated by different targets

**Comment by nsubtil** [comment]
Assigning myself, since I'd like to contribute a fix for this --- but I'm not sure I fully understand the intent of this post-build step.

@karl-lunarg / @mark-lunarg, are you familiar with this bit of code? Can you shed some light on what the purpose of this step is?

**Comment by mark-lunarg** [comment]
@nsubtil, @mikew-lunarg might know best, but I *think* this bit of source is to copy the device profile layer files (from the layers directory) into the tests part of the tree, as the purpose of this layer is to support the layer validation tests.  There are other spots where these convenience copies are made, for instance the gtest DLLs and the loader are copied into the build\tests\<config> dir (on Windows) to simplify executing the tests in the MSVC project.

**Comment by nsubtil** [comment]
Is there a list of files that this step should copy? The glob pattern seems problematic here, I'd like to see if we can do something different.

**Comment by mikew-lunarg** [comment]
@nsubtil I agree w @mark-lunarg remark about the rationale and the comment at line 110; i.e.: a local convenience copy.  Per the log, the comment and those globs were introduced quite some time ago (commit 417776eca)

Agree that globs are brittle and should be discouraged.  I'd also prefer CMake's file(copy) over the platform-specific xcopy.
