### ISSUE TITLE
Android NDK 25 breaks ShieldTV SecondaryCmdBuffer, Pixel3 SecondaryCommandBufferIncompatibleSubpass

### ISSUE THREAD

**Issue by lunarpapillo** [KhronosGroup/Vulkan-ValidationLayers#6283]
While updating the **Android NDK** to version 25.2.9519653 (a new requirement for **SPIRV-Tools**), I noted that the Android blacklist had to be changed due to two new failures appearing, identified by their appearance as the last line output before the crash:
```
vulkantest-results/ShieldTV-1322020015983/out.txt:

    [ RUN      ] VkAmdBestPracticesLayerTest.SecondaryCmdBuffer

vulkantest-results/Pixel3-89RX0E68Y/out.txt:

    [ RUN      ] NegativeDynamicRendering.SecondaryCommandBufferIncompatibleSubpass
```
Both failures presented similarly, as a `SIGSEGV`:
```
...
ERROR: Pixel3-89RX0E68Y: CRASH in package com.example.VulkanLayerValidationTests
ERROR: Pixel3-89RX0E68Y: signal 11 (SIGSEGV) code 1 (SEGV_MAPERR) fault_addr 0x68
ERROR: Pixel3-89RX0E68Y: cause null pointer dereference
...
20230804-022155|ERROR  |androidtestos:99|ShieldTV-1322020015983: CRASH in package com.example.VulkanLayerValidationTests
20230804-022155|ERROR  |androidtestos:104|ShieldTV-1322020015983: signal 11 (SIGSEGV) code 1 (SEGV_MAPERR) fault_addr 0x70
20230804-022155|ERROR  |androidtestos:109|ShieldTV-1322020015983: cause null pointer dereference
...
```
These were the only two tests affected.  Blacklisting these two allowed tests to pass.

Unusual observations:
- As far as I can tell historically, `NegativeDynamicRendering.SecondaryCommandBufferIncompatibleSubpass` is _not_ routinely executed on the **Pixel 3** (nor are _any_ `NegativeDynamicRendering` tests).  I'm not sure why it's first being exercised with NDK 25.
- Similarly, neither `VkAmdBestPracticesLayerTest.SecondaryCmdBuffer` nor any other `VkAmdBestPracticesLayerTest` appear to have ever been executed on the **ShieldTV**.  Again, I'm not sure why it's being exercised now.

**Comment by mikes-lunarg** [comment]
> Unusual observations:
> 
>    * As far as I can tell historically, `NegativeDynamicRendering.SecondaryCommandBufferIncompatibleSubpass` is _not_ routinely executed on the **Pixel 3** (nor are _any_ `NegativeDynamicRendering` tests).  I'm not sure why it's first being exercised with NDK 25.
> 
>    * Similarly, neither `VkAmdBestPracticesLayerTest.SecondaryCmdBuffer` nor any other `VkAmdBestPracticesLayerTest` appear to have ever been executed on the **ShieldTV**.  Again, I'm not sure why it's being exercised now.

Both `amd_best_practices.cpp` and `dynamic_rendering.cpp` are missing from [build-android/jni/Android.mk](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/build-android/jni/Android.mk). I suspect that the authors of each file simply forgot to add them to the Android build. Those tests got executed on Android for the first time when you switched to the new CMake-based build, as it uses the same build definition files as the desktop build.

**Comment by juan-lunarg** [comment]
> Both amd_best_practices.cpp and dynamic_rendering.cpp are missing from [build-android/jni/Android.mk](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/build-android/jni/Android.mk). I suspect that the authors of each file simply forgot to add them to the Android build. Those tests got executed on Android for the first time when you switched to the new CMake-based build, as it uses the same build definition files as the desktop build.

Yep. That's exactly what happened.

**Comment by spencer-lunarg** [comment]
closing because both devices are scheduled to be removed and aren't going to look into these in details
