### ISSUE TITLE
Unexpected validation errors with performance queries with multiple passes

### ISSUE THREAD

**Issue by rg3igalia** [KhronosGroup/Vulkan-ValidationLayers#6304]
**Environment:**
 - OS: Linux
 - GPU: RX 6700 XT (using the RADV Mesa driver)
 - SDK or header version if building from repo: d966a60f13e21ebb2bdd3112861d50c18f1e0620
 - Options enabled (synchronization, best practices, etc.): defaults + synchronization

**Describe the Issue**

When an app uses performance queries that need multiple passes, it's supposed to reset the query either on the host or a separate command buffer, and then submit a command buffer containing a `vkCmdBeginQuery` + stuff + `vkCmdEndQuery` sequence multiple times. In each submission, it has to include a `VkPerformanceQuerySubmitInfoKHR` indicating the pass index in the `pNext` chain of `VkSubmitInfo`. However, when doing that the layers generate `VUID-vkCmdBeginQuery-None-00807` erroneously.

I reproduced this problem with the performance query CTS tests in `dEQP-VK.query_pool.performance_query.*` tests. However, note that, before my changes for Khronos internal CTS issue 4615, the tests contain multiple validation errors. After my changes, `VUID-vkCmdBeginQuery-None-00807` appears to be the only remaining validation issue in those tests.

**Expected behavior**

No validation errors.

**Valid Usage ID**

`VUID-vkCmdBeginQuery-None-00807`

> VUID-vkCmdBeginQuery-None-00807(ERROR / SPEC): msgNum: 680962600 - Validation Error: [ VUID-vkCmdBeginQuery-None-00807 ] Object 0: handle = 0x55ac26bc6d90, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0x967dd1000000000e, type = VK_OBJECT_TYPE_QUERY_POOL; | MessageID = 0x2896aa28 | vkCmdBeginQuery: VkQueryPool 0x967dd1000000000e[] and query 0: query not reset. After query pool creation, each query must be reset before it is used. Queries must also be reset between uses. The Vulkan spec states: All queries used by the command must be unavailable (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdBeginQuery-None-00807)

**Additional context**

Possibly related to issue #1795, but I prefered to create a new one with more context.

**Comment by spencer-lunarg** [comment]
@rg3igalia should be fixed, if not please ping the issue again
