### ISSUE TITLE
Remaining validation for VK_EXT_host_image_copy

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-ValidationLayers#6317]
The following VUIDs were not implemented in PR #6290 and remain unvalidated:
VUID-VkCopyImageToImageInfoEXT-dstImage-09109
VUID-VkCopyImageToImageInfoEXT-srcImage-09109
VUID-VkCopyImageToMemoryInfoEXT-srcImage-09109
VUID-VkCopyMemoryToImageInfoEXT-dstImage-09109
VUID-VkImageToMemoryCopyEXT-pRegions-09067
VUID-VkMemoryToImageCopyEXT-pRegions-09062
VUID-VkMemoryToImageCopyEXT-pHostPointer-09061
VUID-VkImageToMemoryCopyEXT-pHostPointer-09066

**Comment by zmike** [comment]
While you're at it, `VUID-VkHostImageLayoutTransitionInfoEXT-subresourceRange-01488` doesn't correctly check `VK_REMAINING_ARRAY_LAYERS`, but it's unclear to me whether this is (also) a spec bug?

**Comment by zmike** [comment]
The issue I'm definitely seeing though is layout transitions using `vkTransitionImageLayoutEXT` don't seem to be tracked.

**Comment by Tony-LunarG** [comment]
There are some (light) tests that seem to work.  What flags a bad layout after transitioning?  For instance, the test uses vkTransitionImageLayoutEXT to transition from GENERAL to COLOR_ATTACHMENT_OPTIMAL, and then sends a barrier switching from COLOR_ATTACHMENT_OPTIMAL to GENERAL, and it doesn't get an error. What is your use case that is not getting tracked?

**Comment by zmike** [comment]
...Alright, I updated my VVL again today and everything is magically working. Great job, ignore me :+1:

**Comment by Tony-LunarG** [comment]
Addressed in #6483
