### ISSUE TITLE
Push descriptors error messages not clear

### ISSUE THREAD

**Issue by ziga-lunarg** [KhronosGroup/Vulkan-ValidationLayers#6324]
One message was fixed in #6319, but many more similar error messages remain, where using push descriptors the validation layers will emit an error saying "VkDescriptorSet 0x0[]". Most of these are cc_descriptor.cpp

**Comment by spencer-lunarg** [comment]
seems that my cleanup in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6399 fixed this, used https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6479 to confirm the error messages all now give proper messages like

> vkCmdPushDescriptorSetKHR(): pDescriptorWrites[0].dstSet (Push Descriptors defined with VkDescriptorSetLayout 0xe7f79a0000000005[]) has been destroyed.

instead of just `VkDescriptorSet 0x0[]`
