### ISSUE TITLE
Pixel 7 crashes and failures

### ISSUE THREAD

**Issue by johnzupin** [KhronosGroup/Vulkan-ValidationLayers#6338]
We're preparing to add the Google Pixel_7 to CI. Running VVL on a Pixel_7 with build version: ` 13.0.0 (TQ3A.230605.012, Jun 2023)`

There are 8 crashes and 13 failures. These are being removed from CI testing until VVL engineers have opportunity to address them. When the issues have all been addressed, please assign this back to the originator, to remove the CI blacklist.

Crashes:
- `PositiveCommand.ClearRectWith2DArray`
- `NegativeDescriptors.InlineUniformBlockEXT`
- `NegativeDescriptors.SampledImageDepthComparisonForFormat`
- `VkPositiveLayerTest.TestShaderInputAndOutputStructComponents`
- `NegativeRenderPass.Framebuffer`
- `PositiveShaderInterface.PhysicalStorageBuffer`
- `NegativeSyncVal.PresentDoesNotWaitForSubmit`
- `NegativeTransformFeedback.PipelineRasterizationStateStreamCreateInfoEXT`

Failures:
- `NegativeAndroidHardwareBuffer.DeviceImageMemoryReq`
- `VkBestPracticesLayerTest.UseDeprecatedInstanceExtensions`
- `NegativeDynamicRendering.RenderingFragmentDensityMapAttachment`
- `VkGpuAssistedLayerTest.DrawingWithUnboundUnusedSet`
- `PositiveGpuAssistedLayer.GetCounterFromSignaledSemaphoreAfterSubmit`
- `VkPositiveLayerTest.FormatProperties3FromProfiles`
- `NegativeQuery.CmdExecuteCommandsActiveQueries`
- `PositiveQuery.DestroyQueryPoolBasedOnQueryPoolResults`
- `NegativeSampler.UnnormalizedCoordinatesCombinedSampler`
- `NegativeSampler.UnnormalizedCoordinatesSeparateSampler`
- `PositiveShaderSpirv.UnnormalizedCoordinatesNotSampled`
- `NegativeShaderStorageImage.MissingFormatReadForFormat`
- `NegativeShaderStorageImage.MissingFormatWriteForFormat`

Hang:
- `PositiveSyncObject.WaitEventThenSet`

[blacklist.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/12479861/blacklist.txt)

**Comment by spencer-lunarg** [comment]
closing - these were cleaned up https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6603 and https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6633
