### ISSUE TITLE
spirv_grammar_generator.py fails with latest spirv-headers

### ISSUE THREAD

**Issue by amaiorano** [KhronosGroup/Vulkan-ValidationLayers#6350]
See my comment here: https://github.com/KhronosGroup/SPIRV-Headers/commit/c6e625d2c969dfc03965e9d80221ead48bb03795#r125406052

This line breaks VVL builds, specifically when spirv_grammar_generator.py runs, it will fail [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/scripts/generators/spirv_grammar_generator.py#L151).

The IdScope "name" field should be either Execution or Memory (or Scope, though that's a wrong name according to the comments).

Our internal google build failed with:
```
[40|47] Generating spirv_grammar_helper.h
ERROR: unknown operand OpInitializeNodePayloadsAMDX not handled correctly
```

I originally opened [the issue on SPIRV-Headers repo](https://github.com/KhronosGroup/SPIRV-Headers/issues/373), but after internal discussions, it seems the issue is that this script needs to be udpated to handle this `Visibility` IdScope type.

**Comment by spencer-lunarg** [comment]
fix is up
