### ISSUE TITLE
DebugPrintf validation layer not thread-safe during vkCreateShaderModule validation

### ISSUE THREAD

**Issue by jbarnoin** [KhronosGroup/Vulkan-ValidationLayers#6367]
**Environment:**
 - OS: Debian 12
 - GPU: NVIDIA GeForce RTX 3090 
 - SDK or header version if building from repo: SDK 1.3.250.1, git commit [3e748233c4f95d8ebd07fda616502624da7169e9](https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/3e748233c4f95d8ebd07fda616502624da7169e9)
 - Options enabled: Debug Printf, Fine-grained locking

**Describe the Issue**

When DebugPrintf validation layer is enabled while fine-grained locking is turned on, if vkCreateShaderModule is called from multiple threads in parallel, printf messages will likely return empty strings as they fail to find the correct associated shader module.

**Expected behavior**

Debug printf messages work after vkCreateShaderModule is called from multiple threads when fine-grained locking is enabled.

**Additional context**

When fine-grained locking is enabled, DebugPrintf::PreCallRecordCreateShaderModule may be called from multiple threads.
Within DebugPrintf::InstrumentShader here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/3e748233c4f95d8ebd07fda616502624da7169e9/layers/gpu_validation/debug_printf.cpp#L120-L125 unique_shader_module_id is being read and stored before a long operation (optimizer.Run), then incremented. This results in high likelyhood that the wrong shader id will be associated with the shader (multiple shaders will have the same id passed to CreateInstDebugPrintfPass).

unique_shader_module_id should be incremented atomically before calling optimizer.Run to avoid issues, which shouldn't cause much performance degradation.

**Comment by spencer-lunarg** [comment]
Should be fixed thanks to Tony's PR
