### ISSUE TITLE
`VUID-vkCmdDispatch-groupCountX-00386` Should contain shader pipeline name

### ISSUE THREAD

**Issue by Jasper-Bekkers** [KhronosGroup/Vulkan-ValidationLayers#6368]
Currently the error message for this validation layere message only outputs the handle to the command buffer which is relatively useless for pinpointing where this error is coming from. 

We annotate all of our PSOs with names, and to find where in our code this validation layer message triggers it would be extremely helpful to know the name of the PSO when it's available.

<hr>

I tried patching this myself but it seems rather involved: right now this check lives in `manual_PreCallValidateCmdDispatch` in the `StatelessValidation` object which presumably doesn't carry any state (and thus can't locate the PSO easily).

**Comment by spencer-lunarg** [comment]
Love this feedback, the last 2 weeks I have been working on improving the error messages, stuff like this is good to know

I can just move these draw commands to non-stateless and I agree, for draw/dispatch calls having the `VkPipeline` (or now `VkShaderEXT` too) would be helpful

**Comment by Jasper-Bekkers** [comment]
@spencer-lunarg Agreed; and thanks for picking this up. Having the right debugging tools is key!
