### ISSUE TITLE
Validation layers don't check SPIR-V version in vkCreateShaderModule

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#64]
**Issue by [baldurk](https://github.com/baldurk) (MIGRATED)**
_Monday Feb 19, 2018 at 21:20 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2419_

----

Uploading a SPIR-V module with version 1.1 or higher is not currently legal in Vulkan as far as I know (only 1.0 is supported), but the validation layers don't verify this and won't complain unless there's something else wrong with the SPIR-V.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/mark-lunarg"><img src="https://avatars2.githubusercontent.com/u/7252958?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mark-lunarg](https://github.com/mark-lunarg) (MIGRATED)**
_Monday Feb 19, 2018 at 22:03 GMT_

----

@baldurk, can you point to a reference?  The spec says "A Vulkan 1.0 implementation must support the 1.0 version of SPIR-V and the 1.0 version of the SPIR-V Extended Instructions for GLSL.", which would seem to leave the door open for newer versions.  Is it that the 1.1 and 1.2 SPIR-V features are OpenCL-only or something like that?

**Comment by karl-lunarg** [comment]
<a href="https://github.com/sheredom"><img src="https://avatars1.githubusercontent.com/u/611171?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sheredom](https://github.com/sheredom) (MIGRATED)**
_Tuesday Feb 20, 2018 at 08:43 GMT_

----

The point in the spec where we mandate SPIR-V 1.0 (https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/doc/specs/vulkan/appendices/spirvenv.txt#L17) was meant to mean 'Only the versions listed here are supported.'

I agree with @baldurk that it'd be a useful validation layer error if the Vulkan 1.0 API was passed a SPIR-V binary that had a version > 1.0!

**Comment by karl-lunarg** [comment]
<a href="https://github.com/mark-lunarg"><img src="https://avatars2.githubusercontent.com/u/7252958?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mark-lunarg](https://github.com/mark-lunarg) (MIGRATED)**
_Tuesday Feb 20, 2018 at 16:29 GMT_

----

@sheredom, @baldurk, thank you very much.  It's on the list.

**Comment by mark-lunarg** [comment]
It seems that the spirv-validator checks for this, assigning error code SPV_ERROR_WRONG_VERSION.  If this is still a problem, please reopen this issue.
