### ISSUE TITLE
Remove old VUID-VkDescriptorPoolCreateInfo-poolSizeCount-arraylength check

### ISSUE THREAD

**Issue by pdaniell-nv** [KhronosGroup/Vulkan-ValidationLayers#6401]
In https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5144 the `VUID-VkDescriptorPoolCreateInfo-poolSizeCount-arraylength` VU was removed from the Vulkan specification. The latest Vulkan SDK 1.3.261.0 VVL still have the following:
> Validation Error: [ VUID-VkDescriptorPoolCreateInfo-poolSizeCount-arraylength ] Object 0: handle = 0x127edb2f090, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x8e5726c | vkCreateDescriptorPool: parameter pCreateInfo->poolSizeCount must be greater than 0. The Vulkan spec states: poolSizeCount must be greater than 0 (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkDescriptorPoolCreateInfo-poolSizeCount-arraylength)

This should now be removed.

**Comment by spencer-lunarg** [comment]
So I looked, this was in [SDK 1.3.211](https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/54e93aef0af2b7c2eec7dcc2bd1d1894bb364cba) but not [SDK 1.3.216](https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/68e6bca3bf74423b97e63e2707400d70d588798a) which was over a year ago, so not sure how you are seeing this now unless while updating the SDK you didn't install correctly and pointing to a new spot

also will point out if you were using the SDK, it would print `https://vulkan.lunarg.com/doc/view/1.3.261.0/` as the URL, which this doesn't so makes me believe you aren't using the SDK like you think

Regradless, wrote a test to confirm `poolSizeCount` can be zero in ToT

**Comment by pdaniell-nv** [comment]
Ugh I'm sorry for the false bug report. I had 1.3.261.0 installed, but my ExplicitLayers registry entries were messed up and it was pointer to an old version of VVL. Reinstalling 1.3.261.0 fixed it. Sorry about that.

**Comment by spencer-lunarg** [comment]
no problem, we had no test for `poolSizeCount = 0` so now we have it!
