### ISSUE TITLE
tests: NegativeDynamicRendering::LibraryViewMask SIGSEGV

### ISSUE THREAD

**Issue by HildarTheDorf** [KhronosGroup/Vulkan-ValidationLayers#6403]
**Environment:**
 - OS: Linux (ubuntu 20.04 'focal') using Mesa 23.1.6 (https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa)
 - GPU: AMD Ryzen™ 7 5800U
 - SDK or header version if building from repo: Build from commit 637dd02e40c368d1e7677ef228bbdf9a4fb92403
 - Options enabled (synchronization, best practices, etc.): N/A

**Describe the Issue**

The test NegativeDynamicRendering::LibraryViewMask causes a segmentation fault on my machine on line 3514 `lib.CreateGraphicsPipeline();`. This causes the entire test run to end prematurely, not running any further tests.

**Expected behavior**
Test passes, is skipped, or at least fails gracefully

**Valid Usage ID**
N/A

**Additional context**

Not sure if this is incorrect usage by the VVL test or a bug in Mesa. The driver is always trying to access the pipeline topology in the Input Attachment state, but the IA state is null as the test is compiling a pipeline library without pre-raster state.

**Comment by spencer-lunarg** [comment]
I can reproduce the crash with my version of Mesa, will look more (thanks for bringing this up!)

**Comment by spencer-lunarg** [comment]
so the test is wrong, it tries to add an illegal `VkGraphicsPipelineLibraryCreateInfoEXT` onto `VkPipelineLibraryCreateInfoKHR`

(so the "real" but is a Spec bug is there is no `VUID-VkPipelineLibraryCreateInfoKHR-pNext-pNext` for the Validation to generate and catch this... but will fix that in the spec)
