### ISSUE TITLE
Add WSI support for tests on MacOS

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/Vulkan-ValidationLayers#6412]
(from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6407)

right now a lot of WSI tests are blacklisted for MacOS or are just going

```
    if (!InitSwapchain()) {
        GTEST_SKIP() << "Cannot create surface or swapchain";
    }
```

but really we just need to add proper fixes to the `AddSurfaceExtension`, `CreateSurface`, etc helpers

**Comment by juan-lunarg** [comment]
Got all the PositiveWsi tests passing on MoltenVK. Should have this fixed soon.
