### ISSUE TITLE
perf: chassis locks around nop function calls

### ISSUE THREAD

**Issue by jeffbolznv** [KhronosGroup/Vulkan-ValidationLayers#642]
The autogenerated chassis code (chassis.cpp) unconditionally locks around every call, even if the call goes to the nop implementation in the base class (ValidationObject). It's a shame C++ doesn't have a way to detect whether a method is overloaded. Instead, we need some way for the derived classes to opt in/out of locking, hopefully something that can be baked into the autogenerated code.

**Comment by mark-lunarg** [comment]
The derived classes can now opt in or out of locking by overriding the locking behavior in the base class, providing a way to avoid locking for default functions.
