### ISSUE TITLE
Investigate why swapchain uses instance-level registration in thread safety

### ISSUE THREAD

**Issue by artem-lunarg** [KhronosGroup/Vulkan-ValidationLayers#6429]
This was introduced in 6461871c2ac410df9f2ce821bb65b903670ead8d
The commit's description does not fully explain what's going on. This goal of this issue is to figure out the exact reason why `VkSwapchianKHR` should use instance-related `WRAPPER_PARENT_INSTANCE` instead of `WRAPPER` and to *comment this in the code*. If this reason is no longer valid then to *update the code to use WRAPPER and non-ParentInstance functions*.

**Comment by artem-lunarg** [comment]
@mark-lunarg it was some time ago, but if you remember some details feel free to comment.

**Comment by mark-lunarg** [comment]
@artem-lunarg, it was a long time ago!  Looking at the original commit (355b7ed5e73b), it says:
```
...two threads *reading* the same object will fight over a *write* lock for the same bucket. This change creates a tracking object (ObjectUseData) that persists for the lifetime of the object...
```
I think maybe Swapchains, like surfaces, get accessed by multiple threads and so need a parent reference for a place to manage the thread-safety lock to prevent the above-mentioned contention? Please watch out for the giant grains of salt you should be taking along with these comments.

**Comment by mark-lunarg** [comment]
Original issue [is here.](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2256)

**Comment by artem-lunarg** [comment]
Thanks, that’s good information.

**Comment by artem-lunarg** [comment]
We got a confirmation here [internal link](https://gitlab.khronos.org/vulkan/vulkan/-/issues/3622) that `oldSwapchain` can't originate from a different device. 

`VUID-VkSwapchainCreateInfoKHR-commonparent` has some issues (details here [another internal link](https://gitlab.khronos.org/vulkan/vulkan/-/issues/2983)), and one side effect of that it can lead to conclusion that swapchain can be used by a different device. 

The specification's section 3.3 Object model is a good reference for similar questions:
> All objects created or allocated from a VkDevice (i.e. with a VkDevice as the first parameter) are private to that device, and must not be used on other devices.

https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6567 updates related code.

As a side note about `VUID-VkSwapchainCreateInfoKHR-commonparent`, one option it to split it into two VUs (also that's how current form of VU can be understood): the first one is that swapchain parent should be the `device` (command's dispatchable parameter), and the second VU says that surface's parent should be `VkInstance` from the `device` parent chain.
