### ISSUE TITLE
perf: Parameter validation should only lock if log_msg is called

### ISSUE THREAD

**Issue by jeffbolznv** [KhronosGroup/Vulkan-ValidationLayers#643]
Parameter (stateless) validation unconditionally locks around each call (via the chassis). But since it only looks at parameters, most (all?) of the code is thread safe and doesn't need to lock. I think locking is only needed for logging (and I'm not really clear on whether it's even needed there).

It may be simple to fix this by just overloading StatelessValidation::write_lock and write_unlock to do nothing.

Enabling parameter_validation only in dota2 currently cuts perf in half. With the locking removed, it is closer to a 5-10% hit.

**Comment by mark-lunarg** [comment]
@jeffbolznv, super-cool -- we'll do some testing here and see if we can get this in shortly.
