### ISSUE TITLE
Utility Libraries Depend

### ISSUE THREAD

**Issue by hergljkds** [KhronosGroup/Vulkan-ValidationLayers#6456]
Adding a CMakeLists.txt dep for the new utility libraries may be premature.

**Comment by juan-lunarg** [comment]
This has been in the works for a while, and addresses code duplication issues, code deliverable issues, long standing asks/issues with the Vulkan SDK, and package manager issues.

We will have things ironed out for the next SDK release.

Given the lack of specificity I'm going to close this for now.
