### ISSUE TITLE
Provide symbols for validation.so for better debugging.

### ISSUE THREAD

**Issue by sindney** [KhronosGroup/Vulkan-ValidationLayers#6459]
We encountered some crash inside validation layer, we found the distributed package doesn't contain symbols.
It's nice if you can pack the symbols alongside the actual so in the future. So we don't have to built the whole project locally, thanks.

**Comment by sindney** [comment]
The latest version contains symbols,

**Comment by juan-lunarg** [comment]
For future reference specifying the platform would be helpful.

Because we don't strip debugging information on Unix like platforms for exactly this reason. And we ship PDBs for the validation layers.
