### ISSUE TITLE
Validation layer crash in vkCmdBuildAccelerationStructuresKHR

### ISSUE THREAD

**Issue by Onhi** [KhronosGroup/Vulkan-ValidationLayers#6461]
**Environment:**
 - OS: Windows 11 (21H2 - 22000.2295)
 - GPU: nVidia 2080 Super
 - SDK or header version if building from repo: 1.3.241
 - Options enabled (synchronization, best practices, etc.): VK_LAYER_KHRONOS_validation (default settings)

It looks like there is an issue related to the tracking of scratch data memory.
I mean this data specifically: `VkAccelerationStructureBuildGeometryInfoKHR::scratchData`.

To build acceleration structures I create vkbuffers to hold scratch data.
The buffers are temporary so I reuse the underliying memory for several of them.

Proper synchronization and resource life time management is respected yet, the validation layer triggers buffer lifetime errors and eventually crash on build acceleration structure call.

Typically it takes this form:

> frame 0:
> - wait fence -2
> - clean up frame -2
> - create buffer 0 at address A
> - build acceleration structure X (using buffer 0's device memroy address A)
> - a barrier ensuring acceleration structure X build is complete
> - ...
> - signal fence 0
> 
> frame 1:
> - wait fence -1
> - clean up frame -1
> - create buffer 1 at address A
> - build acceleration structure Y (using buffer 1's device memroy address A)
> - a barrier ensuring acceleration structure Y build is complete
> - ...
> - signal fence 1
> 
> frame 2:
> - wait fence 0
> - clean up frame 0
> - - release buffer 0 -> **This fires up the validation layer! Probaly because buffer 0 & 1 shares the same memory address A** (**message 1**)
> - create buffer 2 at address A
> - build acceleration structure Z (using buffer 1) -> **Validation layer crash here** (**message 2**) (**callstack**)

_Important note_: if I give all the buffers their own memory region, there is no validation message and no crash.

**Expected behavior**

Proper resource lifetime tracking and no validation layer crashes.

**Valid Usage ID**

_message 1_: `VUID-vkDestroyBuffer-buffer-00922(ERROR / SPEC): msgNum: -464217071 - Validation Error: [ VUID-vkDestroyBuffer-buffer-00922 ] Object 0: handle = 0x3067af08d10, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xe4549c11 | Cannot call vkDestroyBuffer on VkBuffer 0x48b6e900000001a9[bufTLASScratch] that is currently in use by a command buffer. The Vulkan spec states: All submitted commands that refer to buffer, either directly or via a VkBufferView, must have completed execution (https://vulkan.lunarg.com/doc/view/1.3.250.1/windows/1.3-extensions/vkspec.html#VUID-vkDestroyBuffer-buffer-00922)`

_message 2_: `Exception thrown at 0x00007FFDBBFEC38A (VkLayer_khronos_validation.dll) in Proton.exe: 0xC0000005: Access violation reading location 0x000001F700000020.`

**Additional context**

_callstack_: 
```
 [Inline Frame] VkLayer_khronos_validation.dll!CoreChecks::ValidateAccelerationBuffers::__l21::<lambda_f5bb0fbf4db95d51f61541879a23dcaa>::operator()(const std::shared_ptr<BUFFER_STATE> &) Line 331	C++
 [Inline Frame] VkLayer_khronos_validation.dll!std::none_of(const std::shared_ptr<BUFFER_STATE> * const _Last, const std::shared_ptr<BUFFER_STATE> * const) Line 1282	C++
 VkLayer_khronos_validation.dll!CoreChecks::ValidateAccelerationBuffers(unsigned int info_index, const VkAccelerationStructureBuildGeometryInfoKHR & info, const char *) Line 329	C++
 VkLayer_khronos_validation.dll!CoreChecks::PreCallValidateCmdBuildAccelerationStructuresKHR(VkCommandBuffer_T * commandBuffer, unsigned int infoCount, const VkAccelerationStructureBuildGeometryInfoKHR * pInfos, const VkAccelerationStructureBuildRangeInfoKHR * const * ppBuildRangeInfos) Line 251	C++
 VkLayer_khronos_validation.dll!vulkan_layer_chassis::CmdBuildAccelerationStructuresKHR(VkCommandBuffer_T * commandBuffer, unsigned int infoCount, const VkAccelerationStructureBuildGeometryInfoKHR * pInfos, const VkAccelerationStructureBuildRangeInfoKHR * const * ppBuildRangeInfos) Line 14811	C++
```

I included a rather large API dump text file. The message 1 fires up at line 54629 and the crash occurs at line 56068.
[api_dump.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/12566213/api_dump.txt)

**Comment by arno-lunarg** [comment]
Hello @Onhi, thank you for opening this issue with very good details. The frame operations you described allowed me to reproduce your issue in an isolated test.
It should be fixed now, though I never experienced any crash with my reproducing test, so if you still experiment one, feel free to reopen the issue!
