### ISSUE TITLE
Updated Blacklist for M1 Mac with MoltenVK 1.2.5

### ISSUE THREAD

**Issue by richard-lunarg** [KhronosGroup/Vulkan-ValidationLayers#6470]
20230911-211621|INFO   |gtest-blacklist:312|Passes (return code 0): 2260
20230911-211621|INFO   |gtest-blacklist:146|Crashes (negative return codes): 20
- `VkAmdBestPracticesLayerTest.NumberOfSubmissions`
- `PositiveCommand.ClearRectWith2DArray`
- `NegativeGeometryTessellation.StageMaskGsTsEnabled`
- `VkGpuAssistedLayerTest.GpuValidationInlineUniformBlockAndMiscGpu`
- `PositiveImage.FramebufferFrom3DImage`
- `VkPositiveLayerTest.UseFirstQueueUnqueried`
- `VkPositiveLayerTest.QueueThreading`
- `VkPositiveLayerTest.PSOPolygonModeValid`
- `VkLayerTest.CustomStypeStructString`
- `VkLayerTest.CustomStypeStructStringArray`
- `VkLayerTest.CustomStypeStructIntegerArray`
- `VkLayerTest.DuplicateMessageLimit`
- `VkLayerTest.VuidIdFilterString`
- `VkLayerTest.VuidFilterHexInt`
- `VkLayerTest.VuidFilterInt`
- `VkLayerTest.ExportMetalObjects`
- `PositiveRenderPass.FramebufferWithAttachmentsTo3DImageMultipleSubpasses`
- `NegativeShaderSpirv.FragmentShaderInterlockEnabled`
- `NegativeSyncObject.MixedTimelineAndBinarySemaphores`
- `NegativeSyncVal.CopyOptimalMultiPlanarHazards`
20230911-211621|INFO   |gtest-blacklist:146|Failures (positive return codes): 166
- `VkAmdBestPracticesLayerTest.UseMutableRT`
- `VkAmdBestPracticesLayerTest.UsageConcurentRT`
- `VkAmdBestPracticesLayerTest.UsageStorageRT`
- `VkAmdBestPracticesLayerTest.PrimitiveRestart`
- `VkAmdBestPracticesLayerTest.NumDynamicStates`
- `VkAmdBestPracticesLayerTest.KeepLayoutSmall`
- `VkAmdBestPracticesLayerTest.CopyingDescriptors`
- `VkAmdBestPracticesLayerTest.ClearImage`
- `VkAmdBestPracticesLayerTest.ImageToImageCopy`
- `VkAmdBestPracticesLayerTest.GeneralLayout`
- `VkAmdBestPracticesLayerTest.RobustAccessOn`
- `VkAmdBestPracticesLayerTest.Barriers`
- `VkAmdBestPracticesLayerTest.NumSyncPrimitives`
- `VkAmdBestPracticesLayerTest.SecondaryCmdBuffer`
- `VkAmdBestPracticesLayerTest.ComputeWorkgroupSize`
- `VkArmBestPracticesLayerTest.TooManySamples`
- `VkArmBestPracticesLayerTest.NonTransientMSImage`
- `VkArmBestPracticesLayerTest.SamplerCreation`
- `VkArmBestPracticesLayerTest.MultisampledBlending`
- `VkArmBestPracticesLayerTest.AttachmentNeedsReadback`
- `VkArmBestPracticesLayerTest.ManySmallIndexedDrawcalls`
- `VkArmBestPracticesLayerTest.SuboptimalDescriptorReuseTest`
- `VkArmBestPracticesLayerTest.SparseIndexBufferTest`
- `VkArmBestPracticesLayerTest.PostTransformVertexCacheThrashingIndicesTest`
- `VkArmBestPracticesLayerTest.PipelineDepthBiasZeroTest`
- `VkArmBestPracticesLayerTest.RobustBufferAccessTest`
- `VkArmBestPracticesLayerTest.DepthPrePassUsage`
- `VkArmBestPracticesLayerTest.ComputeShaderBadWorkGroupThreadAlignmentTest`
- `VkArmBestPracticesLayerTest.ComputeShaderBadWorkGroupThreadCountTest`
- `VkArmBestPracticesLayerTest.ComputeShaderBadSpatialLocalityTest`
- `VkArmBestPracticesLayerTest.RedundantRenderPassStore`
- `VkArmBestPracticesLayerTest.RedundantRenderPassClear`
- `VkArmBestPracticesLayerTest.InefficientRenderPassClear`
- `VkArmBestPracticesLayerTest.BlitImageLoadOpLoad`
- `VkArmBestPracticesLayerTest.RedundantAttachment`
- `PositiveAtomic.Float`
- `VkBestPracticesLayerTest.NonSimultaneousSecondaryMarksPrimary`
- `NegativeBuffer.BufferUsageFlagsUsage`
- `NegativeCommand.CascadedInvalidation`
- `NegativeCommand.CompressedImageMipCopy`
- `NegativeCommand.ImageBufferCopy`
- `NegativeCommand.CopyImageTypeExtentMismatch`
- `NegativeCommand.CopyImageTypeExtentMismatchMaintenance1`
- `NegativeCommand.ResolveImageImageType`
- `NegativeCommand.CopyImageRemainingLayers`
- `PositiveCommand.EventStageMaskSecondaryCommandBuffer`
- `NegativeDescriptors.WriteDescriptorSetIntegrity`
- `NegativeDescriptors.WriteDescriptorSetIdentitySwizzle`
- `NegativeDescriptors.DescriptorImageUpdateNoMemoryBound`
- `NegativeDescriptors.DescriptorBufferUpdateNoMemoryBound`
- `NegativeDescriptors.CopyDescriptorUpdate`
- `NegativeDescriptors.Maint1BindingSliceOf3DImage`
- `NegativeDescriptors.InlineUniformBlockEXT`
- `NegativeDynamicRendering.ZeroRenderArea`
- `NegativeDynamicRendering.InSecondaryCommandBuffers`
- `NegativeDynamicRendering.DeviceGroupRenderArea`
- `NegativeFragmentShadingRate.StageUsage`
- `VkGpuAssistedLayerTest.GpuBufferDeviceAddressOOB`
- `VkGpuAssistedLayerTest.ValidationFeatures`
- `PositiveGpuAssistedLayer.GpuBufferDeviceAddress`
- `NegativeImage.ImageViewDifferentClass`
- `NegativeImage.ImageViewInvalidSubresourceRange`
- `NegativeImage.ImageViewIncompatibleFormat`
- `NegativeImage.ImageViewIncompatibleDepthFormat`
- `NegativeImage.ImageFormatList`
- `NegativeImage.ImageFormatListSizeCompatible`
- `NegativeImage.BlockTexelViewLevelOrLayerCount`
- `NegativeImage.BlockTexelViewType`
- `NegativeImage.BlockTexelViewFormat`
- `VkPositiveLayerTest.ImageDescriptor3D2DSubresourceLayout`
- `VkPositiveLayerTest.StatelessValidationDisable`
- `VkPositiveLayerTest.ParameterLayerFeatures2Capture`
- `VkPositiveLayerTest.GetDevProcAddrExtensions`
- `VkPositiveLayerTest.EnumeratePhysicalDeviceGroups`
- `VkPositiveLayerTest.AllowedDuplicateStype`
- `VkPositiveLayerTest.TestPervertexNVShaderAttributes`
- `VkPositiveLayerTest.LoosePointSizeWrite`
- `VkPositiveLayerTest.TopologyAtRasterizer`
- `VkPositiveLayerTest.TestShaderInputAndOutputComponents`
- `VkPositiveLayerTest.TestShaderInputOutputMatch`
- `VkPositiveLayerTest.OpTypeArraySpecConstant`
- `NegativeImagelessFramebuffer.RenderPassBeginImageViewMismatch`
- `PositiveInstance.TwoInstances`
- `NegativeInstanceless.InstanceExtensionDependencies`
- `NegativeInstanceless.InstanceBadStype`
- `NegativeInstanceless.InstanceDuplicatePnextStype`
- `NegativeInstanceless.InstanceAppInfoBadStype`
- `NegativeInstanceless.InstanceValidationFeaturesBadFlags`
- `NegativeInstanceless.DestroyInstanceAllocationCallbacksCompatibility`
- `VkNvidiaBestPracticesLayerTest.TilingLinear`
- `VkNvidiaBestPracticesLayerTest.Depth32Format`
- `VkNvidiaBestPracticesLayerTest.AllocateMemory_SetPriority`
- `VkNvidiaBestPracticesLayerTest.AllocateMemory_ReuseAllocations`
- `VkNvidiaBestPracticesLayerTest.CreatePipelineLayout_SeparateSampler`
- `VkNvidiaBestPracticesLayerTest.CreatePipelineLayout_LargePipelineLayout`
- `VkNvidiaBestPracticesLayerTest.BeginCommandBuffer_OneTimeSubmit`
- `NegativeObjectLifetime.EventInUseDestroyedSignaled`
- `NegativeObjectLifetime.InUseDestroyedSignaled`
- `NegativeObjectLifetime.CmdBufferEventDestroyed`
- `VkLayerTest.VersionCheckPromotedAPIs`
- `VkLayerTest.LayerInfoMessages`
- `VkLayerTest.RequiredParameter`
- `VkLayerTest.SpecLinks`
- `VkLayerTest.UseObjectWithWrongDevice`
- `VkLayerTest.DeviceFeature2AndVertexAttributeDivisorExtensionUnenabled`
- `VkLayerTest.Features12Features13AndpNext`
- `VkLayerTest.RequiredPromotedFeaturesExtensions`
- `VkLayerTest.FeaturesVariablePointer`
- `VkLayerTest.StageMaskHost`
- `VkLayerTest.Maintenance1AndNegativeViewport`
- `VkLayerTest.ApiVersion1_1AndNegativeViewport`
- `VkLayerTest.ResetEventThenSet`
- `VkLayerTest.ValidateStride`
- `VkLayerTest.ValidateArrayLength`
- `VkLayerTest.InvalidSpirvExtension`
- `VkLayerTest.InvalidCombinationOfDeviceFeatures`
- `VkLayerTest.Features12AndppEnabledExtensionNames`
- `VkLayerTest.InstanceCreateEnumeratePortability`
- `VkLayerTest.CreatePipelineLayoutExcessDescriptorsOverall`
- `NegativePipelineTopology.PointSize`
- `NegativeProtectedMemory.GetDeviceQueue`
- `PositiveRayTracing.BarrierSync1NoCrash`
- `NegativeShaderCompute.WorkgroupMemoryExplicitLayout`
- `PositiveShaderInterface.VsFsTypeMismatchBlockNestedStructLastElementArray`
- `PositiveShaderInterface.VsFsTypeMismatchBlockNestedStructArray`
- `PositiveShaderInterface.MultidimensionalArray`
- `PositiveShaderInterface.MultidimensionalArrayVertex`
- `PositiveShaderInterface.MultidimensionalArrayDims`
- `PositiveShaderInterface.MultidimensionalArrayDims2`
- `PositiveShaderInterface.PhysicalStorageBuffer`
- `NegativeShaderSpirv.NoUniformBufferStandardLayout10`
- `NegativeShaderSpirv.NoUniformBufferStandardLayout12`
- `NegativeShaderSpirv.NoScalarBlockLayout10`
- `NegativeShaderSpirv.NoScalarBlockLayout12`
- `NegativeSyncObject.Barriers`
- `NegativeSyncObject.Sync2Barriers`
- `NegativeSyncObject.ImageBarrierWithBadRange`
- `NegativeSyncObject.EventStageMaskOneCommandBufferPass`
- `NegativeSyncObject.EventStageMaskOneCommandBufferFail`
- `NegativeSyncObject.EventStageMaskTwoCommandBufferPass`
- `NegativeSyncObject.EventStageMaskTwoCommandBufferFail`
- `PositiveSyncObject.WaitEventThenSet`
- `NegativeSyncVal.CmdWaitEvents2KHRUsedButSynchronizaion2Disabled`
- `NegativeSyncVal.Sync2FeatureDisabled`
- `NegativeSyncVal.QSBufferCopyHazards`
- `NegativeSyncVal.QSBufferCopyVsIdle`
- `NegativeSyncVal.QSBufferCopyVsFence`
- `NegativeSyncVal.QSRenderPass`
- `NegativeSyncVal.QSPresentAcquire`
- `NegativeThreading.CommandBufferCollision`
- `NegativeVertexInput.AttributeAlignment`
- `PositiveVertexInput.AttributeMatrixType`
- `PositiveVertexInput.AttributeArrayType`
- `PositiveVertexInput.AttributeComponents`
- `NegativeWsi.SwapchainAcquireImageNoSync`
- `NegativeWsi.SwapchainAcquireImageNoSync2KHR`
- `NegativeWsi.SwapchainAcquireImageNoBinarySemaphore`
- `NegativeWsi.SwapchainAcquireImageNoBinarySemaphore2KHR`
- `NegativeWsi.SwapchainAcquireTooManyImages`
- `NegativeWsi.GetSwapchainImageAndTryDestroy`
- `NegativeWsi.SwapchainAcquireTooManyImages2KHR`
- `NegativeWsi.WarningSwapchainCreateInfoPreTransform`
- `NegativeWsi.SwapchainAcquireImageWithSignaledSemaphore`
- `NegativeWsi.GetSwapchainImagesCountButNotImages`
- `NegativeWsi.SwapchainAcquireImageRetired`
- `NegativeYcbcr.MultiplaneIncompatibleViewFormat`
20230911-211621|INFO   |gtest-blacklist:146|Timeouts (hangs): 0
20230911-211621|INFO   |gtest-blacklist:146|Process errors: 0
20230911-211621|INFO   |gtest-blacklist:146|Interrupts: 0

**Comment by spencer-lunarg** [comment]
@richard-lunarg can this be closed for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7003 ?

**Comment by richard-lunarg** [comment]
Yes!
