### ISSUE TITLE
Missing check for VUID-VkGraphicsPipelineCreateInfo-renderPass-06055

### ISSUE THREAD

**Issue by lhiuming** [KhronosGroup/Vulkan-ValidationLayers#6473]
**Describe the situation in which you encountered the missing validation**
Issue description: VLL didn't report any error when create graphics pipeline with `pColorBlendState->attachmentCount` equal to 1 and `VkPipelineRenderingCreateInfo::colorAttachmentCount` equal to 0, while the spec say they must be equal. 

**Valid Usage IDs requested**
VUID-VkGraphicsPipelineCreateInfo-renderPass-06055

**Additional Context**
The result is that everything looks fine in the rendering except that color blending is not working. Environment:
Vulkan SDK: 1.3.261.1
nVIDIA driver: 537.13

**Comment by spencer-lunarg** [comment]
I just recently edited this code as I noticed it looked potentially wrong.

Let me write up some better tests to confirm, but this should be fixed as of now

(also seems related to https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4856)
