### ISSUE TITLE
Missing check VUID-vkCmdTraceRaysKHR-stride-03686 and VUID-vkCmdTraceRaysKHR-stride-03690

### ISSUE THREAD

**Issue by lhiuming** [KhronosGroup/Vulkan-ValidationLayers#6499]
**Describe the situation in which you encountered the missing validation**
VVL didn't report any error when `pMissShaderBindingTable->stride` is not a multiple of `VkPhysicalDeviceRayTracingPipelinePropertiesKHR::shaderGroupHandleAlignment` while the spec says the former number must be a multiple of the later. Same problem with `pHitShaderBindingTable->stride`.

**Valid Usage IDs requested**
VUID-vkCmdTraceRaysKHR-stride-03686, VUID-vkCmdTraceRaysKHR-stride-03690

**Additional Context**
The value I assign to `pMissShaderBindingTable->stride` and `pHitShaderBindingTable->stride` is `32`, and on my machine `VkPhysicalDeviceRayTracingPipelinePropertiesKHR::shaderGroupHandleAlignment` is `64`.
Environment:
Vulkan SDK: 1.3.261.1
nVIDIA driver: 537.13

**Comment by spencer-lunarg** [comment]
These VUs are checked and tested

Wrote a test and see the message

> Validation Error: [ VUID-vkCmdTraceRaysIndirectKHR-stride-03690 ] Object 0: handle = 0x559d446e4920, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xc562205e | vkCmdTraceRaysIndirectKHR(): pHitShaderBindingTable->stride (16) must be a multiple of VkPhysicalDeviceRayTracingPipelinePropertiesKHR::shaderGroupHandleAlignment (32).

So it is working as expected

do you have

**Comment by spencer-lunarg** [comment]
@lhiuming for sanity check, you can confirm the Validation layers are on correctly?

You by chance have a way to get an [api dump](https://vulkan.lunarg.com/doc/view/1.3.261.1/windows/api_dump_layer.html) or [gfxreconstruct capture](https://github.com/LunarG/gfxreconstruct/) so we can confirm this in deed is the values being passed in

**Comment by lhiuming** [comment]
Oh, sorry, I totally make a mistake. The value of `shaderGroupHandleAlignment` I think I am using is actually wrong. 😱

I can confirm the validation is working as expected. Sorry for the false report. Please close this issue. 😥

**Comment by spencer-lunarg** [comment]
No problem, I am glad to know everything is working!
