### ISSUE TITLE
Cryptic error at BeginRenderPass time

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#65]
**Issue by [nsubtil](https://github.com/nsubtil) (MIGRATED)**
_Thursday Feb 22, 2018 at 02:55 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2428_

----

I recently ran into a validation error message that looks like this:

`[Vulkan: location=377 code=15, layerPrefix='MEM'] vkCmdBeginRenderPass(): Cannot read invalid region of memory allocation 0xb4 for bound Image object 0xb3, please fill the memory before using.
`

The validation layers can tell that the region is invalid somehow, but the error message doesn't explain why. The objects also have debug labels attached to them, which would be very useful to have show up in the message. It's not clear what "fill the memory" means. In the end, there doesn't seem to be a lot of actionable information in this message.

Can we update the message to include more information on why the region is considered invalid, along with debug labels for the objects when available? And can we clarify the recommendation to "fill the memory"?

**Comment by mark-lunarg** [comment]
These confusing messages are no longer output by validation.
