### ISSUE TITLE
core_validation: subpass_to_node indexes out of range in RecordRenderPassDAG

### ISSUE THREAD

**Issue by MulattoKid** [KhronosGroup/Vulkan-ValidationLayers#650]
When creating a render pass with the following subpass dependency:
```
VkSubpassDependency dependency = {};
dependency.srcSubpass = VK_SUBPASS_EXTERNAL;
dependency.dstSubpass = 0;
dependency.srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
dependency.srcAccessMask = 0;
dependency.dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
dependency.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_READ_BIT | VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
```

the core validation layer segfaults. After some search, I found it to be line 8908 in core_validation.cpp.
The reason seems to be that as the srcSubpass is set to VK_SUBPASS_EXTERNAL, its value is 4294967295 which when accessing a vector with size 1 (the render pass has only one subpass) results in a segfault.

Commenting out all functionality except the return value in RecordRenderPassDag works as a temporary solution to avoid crashes.

**Comment by mark-lunarg** [comment]
I botched this during the refactoring to split the record/validate steps -- will get it fixed.
