### ISSUE TITLE
Synchronization - false positive on image layout transition with split barriers

### ISSUE THREAD

**Issue by vmilea** [KhronosGroup/Vulkan-ValidationLayers#6508]
**Describe the Issue**

The validation layer reports WAW hazard during an image layout transition, even if memory writes were made available prior to the transition through a dependency chain. This can happen for initial layout transitions during a render pass, if it assumes memory availability through some previous synchronization mechanism.

**Expected behavior**

No false positives.

**Additional context**

I'll start with a toy example involving buffers only:

```
// [1] copy from stagingBuffer to deviceBuffer
vkCmdCopyBuffer(commandBuffer, stagingBuffer, deviceBuffer, 1, &region);

VkBufferMemoryBarrier bufferMemoryBarrierA = {
    .srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT,
    .dstAccessMask = VK_ACCESS_NONE,
    .buffer = deviceBuffer,
    ...
};
// [2a] make writes available
vkCmdPipelineBarrier(commandBuffer,
    VK_PIPELINE_STAGE_TRANSFER_BIT,
    VK_PIPELINE_STAGE_TRANSFER_BIT,
    0,
    0, nullptr,
    1, &bufferMemoryBarrierA,
    0, nullptr);

VkBufferMemoryBarrier bufferMemoryBarrierB = {
    .srcAccessMask = VK_ACCESS_NONE, // already available
    .dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT,
    .buffer = deviceBuffer,
    ...
};
// [2b] make writes visible
vkCmdPipelineBarrier(commandBuffer,
    VK_PIPELINE_STAGE_TRANSFER_BIT,
    VK_PIPELINE_STAGE_TRANSFER_BIT,
    0,
    0, nullptr,
    1, &bufferMemoryBarrierB,
    0, nullptr);

// [3] copy again from stagingBuffer to deviceBuffer
vkCmdCopyBuffer(commandBuffer, stagingBuffer, deviceBuffer, 1, &region);
```

The contents of `stagingBuffer` are copied twice to `deviceBuffer`. I know it's silly, we just need some operations to reason about. Synchronization is required to prevent WAW hazard. Here I've opted to split the barrier in two. Barrier A makes the transfer writes available, while barrier B makes them visible. `srcAccessMask` for B is `VK_ACCESS_NONE`, but it shouldn't matter because the writes are already available. There is an execution dependency between them because the first `dstStageMask` and second `srcStageMask` are both `VK_PIPELINE_STAGE_TRANSFER_BIT`. The second copy won't start until the first copy has finished and the written data is available and visible.

So far so good, there are no validation errors. Now let's instead copy to an image. The image should transition from `VK_IMAGE_LAYOUT_UNDEFINED` to `VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL` before copying. Then after the copy has finished and writes are available, it should transition to `VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL`:

```
VkImageMemoryBarrier preTransferImageMemoryBarrier = {
    .srcAccessMask = VK_ACCESS_NONE,
    .dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT,
    .oldLayout = VK_IMAGE_LAYOUT_UNDEFINED,
    .newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
    .image = image,
    ...
};
// [1] transition image to VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL before copying
vkCmdPipelineBarrier(commandBuffer,
    VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
    VK_PIPELINE_STAGE_TRANSFER_BIT,
    0,
    0, nullptr,
    0, nullptr,
    1, &preTransferImageMemoryBarrier);

// [2] copy data from buffer to image
vkCmdCopyBufferToImage(commandBuffer, stagingBuffer, image, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &region);

VkImageMemoryBarrier postTransferImageMemoryBarrierA = {
    .srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT,
    .dstAccessMask = VK_ACCESS_NONE,
    .oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
    .newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
    .image = image,
    ...
};
// [3a] make writes available
vkCmdPipelineBarrier(commandBuffer,
    VK_PIPELINE_STAGE_TRANSFER_BIT,
    VK_PIPELINE_STAGE_TRANSFER_BIT,
    0,
    0, nullptr,
    0, nullptr,
    1, &postTransferImageMemoryBarrierA);

VkImageMemoryBarrier postTransferImageMemoryBarrierB = {
    .srcAccessMask = VK_ACCESS_NONE, // already available
    .dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_READ_BIT | VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT,
    .oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
    .newLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
    .image = image,
    ...
};
// [3b] transition to VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL and make result visible
vkCmdPipelineBarrier(commandBuffer,
    VK_PIPELINE_STAGE_TRANSFER_BIT,
    VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
    0,
    0, nullptr,
    0, nullptr,
    1, &postTransferImageMemoryBarrierB);
```

Again, I've opted to split the barrier after copy in two: barrier A makes the transfer writes available, while barrier B handles visibility for when the image will be used as color attachment. Because of the dependency chain, the final transition to `VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL` shouldn't start before the transfer writes have been made available. However, the following is reported:

> Validation Error: [ SYNC-HAZARD-WRITE-AFTER-WRITE ] Object 0: handle = 0xec4bec000000000b, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x5c0ec5d6 | vkCmdPipelineBarrier: Hazard WRITE_AFTER_WRITE for image barrier 0 VkImage 0xec4bec000000000b[]. Access info (usage: SYNC_IMAGE_LAYOUT_TRANSITION, prior_usage: SYNC_COPY_TRANSFER_WRITE, write_barriers: 0, command: vkCmdCopyBufferToImage, seq_no: 2, reset_no: 1).

This smells like a false positive. Intuitively, once a memory has been flushed, there's no need to flush again unless there are additional writes.

In terms of spec (section 7.1), **ScopedMemOps1** of barrier A includes the transfer writes, making them available. Barriers A and B form a **Sync** chain because their **Scopes** intersect, so **ScopedMemOps1** applies to the entire chain. A memory dependency results, which guarantees that "memory writes in **ScopedMemOps1** are made available". Finally, the layout transition happens-after availability operations, eliminating the hazard:

> When a layout transition is specified in a memory dependency, it happens-after the availability operations in the memory dependency, and happens-before the visibility operations. Image layout transitions may perform read and write accesses on all memory bound to the image subresource range, so applications must ensure that all memory writes have been made available before a layout transition is executed.

**Comment by artem-lunarg** [comment]
@vmilea thanks for this high quality report, I really enjoyed reading it.
I agree with the conclusions (before looking deeper into the spec). Going to check how we deal with availability status and whether we preserve it in the case visibility is defined by a separate barrier.

**Comment by artem-lunarg** [comment]
I can reproduce the issue. Added the above scenarios to our tests suite.
https://github.com/artem-lunarg/Vulkan-ValidationLayers/commit/8c32ba4d5f3f62333d609c211e3f9dc2923a4817
