### ISSUE TITLE
Samsung Galaxy S23 Ultra test crashes and failures

### ISSUE THREAD

**Issue by johnzupin** [KhronosGroup/Vulkan-ValidationLayers#6559]
We're preparing to add the Samsung Galaxy S23 Ultra to CI.

There are 11 crashes and 35 reported failures. These are being removed from CI testing until VVL engineers have opportunity to address them. When the issues have all been addressed, please assign this back to the originator, to remove the CI blacklist.

Crashes:
- `VkArmBestPracticesLayerTest.RedundantRenderPassStore`
- `NegativeDescriptors.SampledImageDepthComparisonForFormat`
- `NegativeProtectedMemory.MixingProtectedResources`
- `NegativeRayTracing.CmdCopyUnboundAccelerationStructure`
- `NegativeRenderPass.Framebuffer`
- `NegativeTransformFeedback.CmdBindTransformFeedbackBuffersEXT`
- `NegativeTransformFeedback.CmdBeginTransformFeedbackEXT`
- `NegativeTransformFeedback.CmdEndTransformFeedbackEXT`
- `NegativeTransformFeedback.BindPipeline`
- `NegativeTransformFeedback.EndRenderPass`
- `NegativeTransformFeedback.CmdNextSubpass`

Failures:
- `NegativeAndroidHardwareBuffer.DeviceImageMemoryReq`
- `VkBestPracticesLayerTest.UseDeprecatedInstanceExtensions`
- `NegativeBuffer.FillBufferCmdPoolUnsupported`
- `PositiveBuffer.OwnershipTranfers`
- `NegativeCommand.DepthStencilImageCopyNoGraphicsQueueFlags`
- `NegativeCommand.ImageCopyTransferQueueFlags`
- `PositiveCommand.FillBufferCmdPoolTransferQueue`
- `NegativeDynamicRendering.AttachmentInfo`
- `NegativeDynamicRendering.BeginRenderingFragmentShadingRateImage`
- `NegativeDynamicRendering.TestFragmentDensityMapRenderArea`
- `NegativeDynamicRendering.FragmentDensityMapRenderAreaWithoutDeviceGroupExt`
- `NegativeDynamicRendering.RenderingFragmentDensityMapAttachment`
- `NegativeDynamicRendering.FragmentDensityMapAttachmentCreateFlags`
- `NegativeDynamicRendering.FragmentDensityMapAttachmentLayerCount`
- `NegativeDynamicRendering.PNextImageView`
- `NegativeDynamicRendering.BeginRenderingFragmentShadingRateImageView`
- `NegativeDynamicRendering.BeginRenderingFragmentShadingRateAttachmentSize`
- `NegativeDynamicRendering.FragmentShadingRateAttachmentSizeWithDeviceGroupExt`
- `PositiveDynamicRendering.FragmentDensityMapSubsampledBit`
- `NegativeExternalMemorySync.ImportMemoryHandleType`
- `NegativeFragmentShadingRate.PrimitiveWriteMultiViewportLimit`
- `PositiveImage.OwnershipTranfersImage`
- `VkPositiveLayerTest.FormatProperties3FromProfiles`
- `NegativeRayTracing.BuildAccelerationStructureKHR`
- `NegativeSampler.UnnormalizedCoordinatesCombinedSampler`
- `NegativeSampler.UnnormalizedCoordinatesSeparateSampler`
- `PositiveShaderSpirv.SpecializationWordBoundryOffset`
- `PositiveShaderSpirv.UnnormalizedCoordinatesNotSampled`
- `PositiveShaderSpirv.Storage8and16bit`
- `NegativeShaderStorageImage.MissingFormatReadForFormat`
- `NegativeShaderStorageImage.MissingFormatWriteForFormat`
- `NegativeSyncObject.Barriers`
- `NegativeSyncObject.BarrierQueueFamily`
- `PositiveSyncObject.Sync2OwnershipTranfersImage`
- `PositiveSyncObject.Sync2OwnershipTranfersBuffer`

[blacklist.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/12719726/blacklist.txt)

[vkjson.json.zip](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/12719728/vkjson.json.zip)

**Comment by spencer-lunarg** [comment]
closing - these were cleaned up https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6603 and https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6633
