### ISSUE TITLE
VK_KHR_dynamic_rendering missing check - not checking that fragment output includes all color attachments?

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/Vulkan-ValidationLayers#6564]
**Describe the situation in which you encountered the missing validation**
Issue description:
We recently encountered a bug on RADV that does not give a validation error, but I believe it should.  The case is that there is a VkRenderingInfoKHR with 3 color attachments and then we render with a fragment shader that only outputs one value with Location 0 (built as a graphics pipeline library).  Additionally, in this case, the colorWriteMask state for each of the targets was set to RGBA.  

**Valid Usage IDs requested**
Please include the valid usage IDs for the checks you are requesting:
So I believe this issue has come up before, but I wasn't immediately able to locate the VUID (hoping someone can help!).  In section 15.3 of the spec it has the following language:

> When an active fragment shader invocation finishes, the values of all fragment shader outputs are copied out and used as blend inputs or color attachments writes. If the invocation does not set a value for them, the input values to those blending or color attachment writes are undefined.

**Additional Context**
I believe this is the root cause of https://github.com/ValveSoftware/csgo-osx-linux/issues/3258
Tested on Vulkan SDK 1.3.261.1

**Comment by HansKristian-Work** [comment]
Given that the input values are undefined, there probably is no VUID that would cover it, but there really should be a warning here at least.

**Comment by spencer-lunarg** [comment]
I think this might have been moved into the best practice layer here https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5711

so the issue is as @HansKristian-Work said were I saw this is "undefined values" and not "undefined behavior"

**Comment by spencer-lunarg** [comment]
This was discussed internally and realize this is a philosophical design issue

Awhile ago we decide to make anything not `undefined behavior` (which doesn't have a VU) outside of Core Checks and moved to Best Practice

It was pointed out that the optional Sync Val are also not `undefined behavior` but likely things you want to be detected.

Because Best Practice currently is a broad scope and would be non-performant, one idea was to create another option (like Sync Val) that would do additional checks for things of `undefined value` which would cover a case like this while not being too expensive to additionally validate

**Comment by danginsburg** [comment]
In this particular instance of undefined behavior, I would want to be warned about it, always.  I don't really know why this is UB in the spec instead of just invalid.

**Comment by spencer-lunarg** [comment]
More discussion, decided going to bring back into core check, and create a new logging, so instead of `LogError` or `LogWarning` going to be `LogUndefinedValue` which will be on by default, but can be filtered out as well if others desire.

**Comment by spencer-lunarg** [comment]
@danginsburg these checks are not back into core

they are still under the `warning` option (in case you only have `error` on)

in short, I created a way to justify having these in the "normal" core checks instead of the current large unbound bin of Best Practices
