### ISSUE TITLE
Null access when clearing attachment in secondary command buffer

### ISSUE THREAD

**Issue by asuonpaa** [KhronosGroup/Vulkan-ValidationLayers#657]
I'm having a secondary command buffer without framebuffer inheritance. There I do an attachment clear using vkCmdClearAttachments. At that point validation layers try to access an active framebuffer object which is null. The same doesn't happen with draws which probably defer the check until the secondary command buffer is executed.

**Comment by jzulauf-lunarg** [comment]
@asuonpaa  -- is there an error message that occurs prior to the null access? (if not that's an additional 'incomplete' element to this issue)

**Comment by asuonpaa** [comment]
No, there was no error message.

**Comment by jzulauf-lunarg** [comment]
@asuonpaa -- the secondary command buffer gives me the context I needed.

**Comment by jzulauf-lunarg** [comment]
@asuonpaa -- pushed a PR (above) that should address this issue and improves support for validation of secondary command buffers in vkCmdClearAttachments

**Comment by jzulauf-lunarg** [comment]
The earlier PR was abandoned as it has platform specific test failure.
