### ISSUE TITLE
build: CMake targets of dependencies are not respected

### ISSUE THREAD

**Issue by Accelero** [KhronosGroup/Vulkan-ValidationLayers#6587]
Available targets of dependencies in a CMake build are currently not respected. VVL only integrates them via find_package in config mode. 

See top level CMakeLists.txt @ line 39
```
 find_package(VulkanHeaders REQUIRED CONFIG QUIET)
```
This prevents building VVL in one CMake project together with the Loader and Headers in a  convenient way. If VVL would first check for available targets in the overarching project like so:

```
if(NOT TARGET Vulkan::Headers)
    find_package(VulkanHeaders REQUIRED CONFIG QUIET)
endif()
```
this could be possible. 
In fact that was the case in older versions e.g. v1.2.154. Currently one has to install the Vulkan-Headers and point CMake to the install directory before configuring the VVL CMake project so the package configs can be found by VVL. This is also the case for other dependencies like SPIRV-Headers and -Tools. 

Is there a reason this behavior got changed from older versions and no longer makes sense to support? And what is the current intended way of building parts of the Vulkan SDK from source?

edit:
A first step towards that functionality was made in 3bf912e

**Comment by juan-lunarg** [comment]
> Is there a reason this behavior got changed from older versions and no longer makes sense to support?

It wasn't tested in CI is the most likely answer. I can add it back in.

> And what is the current intended way of building parts of the Vulkan SDK from source?

VVL's build is geared toward package management. This is excellent for building the official Vulkan SDK. It's also great for system package managers and language package managers like vcpkg and conan.

So currently the intended way is to build and install each repo one at a time. Starting with repos like Vulkan-Headers which is practically required by everyone.

**Comment by juan-lunarg** [comment]
I have a PR up. Please check that it works for you.

**Comment by Accelero** [comment]
Works like a charm. Thanks for the quick reply and fix.

**Comment by Accelero** [comment]
Yeah, I already expected something like that, but since github let me close it I thought I might aswell do it. Absolutely makes sense to close it after the merge.

**Comment by juan-lunarg** [comment]
> Yeah, I already expected something like that, but since github let me close it I thought I might aswell do it. Absolutely makes sense to close it after the merge.

No worries. The change has been merged now.
