### ISSUE TITLE
Validation should warn if users enable extensions/layers without enumerating support

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#66]
**Issue by [baldurk](https://github.com/baldurk) (MIGRATED)**
_Sunday Feb 25, 2018 at 14:51 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2436_

----

The validation layers issue a warning if the application calls `vkBindImageMemory` or `vkBindBufferMemory` without first checking the memory requirements (see use of `memory_requirements_checked` in `core_validation.cpp`).

In a similar vein, the layers should also issue a warning if the application passes any extensions or layers to enable into `vkCreateInstance` or `vkCreateDevice` without first checking whether they are present through the enumeration functions.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/krOoze"><img src="https://avatars1.githubusercontent.com/u/3791331?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [krOoze](https://github.com/krOoze) (MIGRATED)**
_Wednesday Feb 28, 2018 at 16:48 GMT_

----

Those sound like different situations.

Passing unsupported extension name is perfectly valid, and the `vkCreate*` returns relatively informative return code.

But what about this:
log a warning if the `vkCreate*` actually fails because of it. The log would contain the name(s) of unsupported extension(s), which would be nice. (Technically it should be `INFO` category too, but I think this case warrants an exception.)

**Comment by mark-lunarg** [comment]
These types of warnings will be added to the Assistant Layer, see issue #24.

**Comment by camden-lunarg** [comment]
The assistant layer now logs a warning when VkResult is unsuccessful. Specifically, if vkCreate* fails because of an extension not present, the assistant layer warns you that VkResult returned with VK_ERROR_EXTENSION_NOT_PRESENT.

In addition, validation-layers will log a list of all unsupported extensions. 

Since the error code is now logged, this issue is now marked as complete in #24
