### ISSUE TITLE
Stuttering in windowed mode

### ISSUE THREAD

**Issue by motangish** [KhronosGroup/Vulkan-ValidationLayers#660]
When swapchain uses VK_PRESENT_MODE_FIFO_KHR mode and validation layers aren't enabled, application stutters in windowed mode. But if validation layers are enabled, stuttering does not occur.

What can cause such weird behavior?

**Comment by jzulauf-lunarg** [comment]
@motangish  Is there a specific aspect of this behavior you think might represent a bug in the validation layers?

The layers have a non-zero performance degradation which might be enough at as a governor, slowing the "fast" frames to be evenly paced with the slow.  Without knowing what synchronization operations the application is using, it would impossible to identify specific places where the validation done at present or synchronization could be affecting this.
