### ISSUE TITLE
BUILD_LAYER_SUPPORT_FILES flag in BUILD.md

### ISSUE THREAD

**Issue by mikew-lunarg** [KhronosGroup/Vulkan-ValidationLayers#661]
The role, documentation, and naming of the BUILD_LAYER_SUPPORT_FILES flag is not clear.

That flag seems to control code generation, which is not explained in the doc or its name "support files".

The [Build Options](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/BUILD.md#build-options) section of BUILD.md says that flag is OFF by default.  Is there a usecase for it to be anything other than ON?  Should it be exposed as a controllable flag?

**Comment by mark-lunarg** [comment]
Jeremy, as the BUILD_LAYER_SUPPORT_FILES-master, can you add an appropriate comment to the cmake file to take care of this issue as well?  If not, I'm happy to do it after you've fixed the other issue.

**Comment by jeremy-lunarg** [comment]
LunarG VulkanTools uses that flag. AFAIK it is the only consumer. It is a by product of the repository split some time back. That flag isn't particular alarming in my opinion as there appears to have been documentation added.
