### ISSUE TITLE
VUID-VkMemoryBarrier2-dstAccessMask-07454

### ISSUE THREAD

**Issue by shikui08** [KhronosGroup/Vulkan-ValidationLayers#6628]
Encountered with this validation error:
`
Debug utils callback with Id[-1377720901|VUID-VkMemoryBarrier2-dstAccessMask-07454] and Message[Validation Error: [ VUID-VkMemoryBarrier2-dstAccessMask-07454 ] Object 0: handle = 0x5593c237ed10, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xade1a5bb | vkCmdPipelineBarrier2KHR(): pDependencyInfo->pMemoryBarriers[0].dstAccessMask (VK_ACCESS_SHADER_READ_BIT) is not supported by stage mask (VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR). The Vulkan spec states: If dstAccessMask includes VK_ACCESS_2_SHADER_READ_BIT, dstStageMask must include VK_PIPELINE_STAGE_2_ALL_GRAPHICS_BIT, VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT, VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_BUILD_BIT_KHR, VK_PIPELINE_STAGE_2_MICROMAP_BUILD_BIT_EXT, or one of the VK_PIPELINE_STAGE_*_SHADER_BIT stages (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkMemoryBarrier2-dstAccessMask-07454)]`

Validation Error and Vulkan spec statement seems inconsistent, am I missing something?

**Comment by spencer-lunarg** [comment]
this clearly looks like a Validation Layer bug (so thanks for reporting it!)

looking at the `vk.xml`

```xml
<syncaccess name="VK_ACCESS_2_SHADER_READ_BIT" alias="VK_ACCESS_SHADER_READ_BIT">
            <syncsupport stage="VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_BUILD_BIT_KHR ... ">
```

**Comment by artem-lunarg** [comment]
Yes, that's a bug according to current version of spec. At first I'd like to clarify the spec [internal link](https://gitlab.khronos.org/vulkan/vulkan/-/issues/3640), never understood what does SHADER_ACCESS mean during ACCELERATION_STRUCTURE_BUILD.

**Comment by shikui08** [comment]
> this clearly looks like a Validation Layer bug (so thanks for reporting it!)
> 
> looking at the `vk.xml`
> 
> ```xml
> <syncaccess name="VK_ACCESS_2_SHADER_READ_BIT" alias="VK_ACCESS_SHADER_READ_BIT">
>             <syncsupport stage="VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_BUILD_BIT_KHR ... ">
> ```        
> 
> and seems we are not populating `syncDirectStageToAccessMask` correctly from this in the `sync_validation_generator.py` autogen

Thanks for the clarification! Glad to help!

**Comment by shikui08** [comment]
> Yes, that's a bug according to current version of spec. At first I'd like to clarify the spec ([internal link](https://gitlab.khronos.org/vulkan/vulkan/-/issues/3640)), never understood what does SHADER_READ mean during ACCELERATION_STRUCTURE_BUILD.

Thanks for the effort~

**Comment by artem-lunarg** [comment]
> At first I'd like to clarify the spec

The above PR is against the current version of the spec. I tend to think now the spec is correct. If something changes, we can adjust solution based on that.
