### ISSUE TITLE
gpu_inst_shader_hash.h missing from BUILD.gn

### ISSUE THREAD

**Issue by romanl-g** [KhronosGroup/Vulkan-ValidationLayers#6635]
Added in https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/ee3a5b2c7b3f29d3a71ac9513cbda429f65951a5
but not added to gn/cmake
@Tony-LunarG

**Comment by romanl-g** [comment]
(fwiw this breaks ANGLE's compile, we ran into this in the past and couldn't find an easy way to catch this on github's ci)

**Comment by romanl-g** [comment]
I don't think it matters for angle but isn't there a cmake list too?

**Comment by Tony-LunarG** [comment]
I don't think so. gpu_inst_shader_hash.h is analogous to spirv_tools_commit_id.h and now that it's been added to BUILD.gn, git grep shows it to be in all the same places that spirv_tools_commit_id.h is.
