### ISSUE TITLE
Vulkan-Headers update breaks compile QueueNotifyOutOfBandNV

### ISSUE THREAD

**Issue by romanl-g** [KhronosGroup/Vulkan-ValidationLayers#6644]
https://github.com/KhronosGroup/Vulkan-Headers/commit/bbe0f575ebd6098369f0ac6c6a43532732ed0ba6

```
[2419/9125] CXX obj/third_party/vulkan-deps/vulkan-validation-layers/src/VkLayer_khronos_validation/layer_chassis_dispatch.obj
FAILED: obj/third_party/vulkan-deps/vulkan-validation-layers/src/VkLayer_khronos_validation/layer_chassis_dispatch.obj 
... ../../third_party/vulkan-deps/vulkan-validation-layers/src/layers/vulkan/generated/layer_chassis_dispatch.cpp(8552,69): error: no viable conversion from 'VkOutOfBandQueueTypeInfoNV' to 'const VkOutOfBandQueueTypeInfoNV *'
 8552 |     layer_data->device_dispatch_table.QueueNotifyOutOfBandNV(queue, pQueueTypeInfo);
      |                                                                     ^~~~~~~~~~~~~~
1 error generated.
```

**Comment by spencer-lunarg** [comment]
This was a backward breaking XML change needing to add the `const` to that NV extension, so we need to re-run the code generation. @mikes-lunarg I assume will have a 1.3.267 header PR soon that will fix this

**Comment by romanl-g** [comment]
IIUC it's not just const, it's changing by-value to pointer

**Comment by AmericaPacific42** [comment]
Ditto error on Termux.
Github erases "*" from title, was changed from value to pointer.
https://github.com/KhronosGroup/Vulkan-Hpp/issues/1682

**Comment by spencer-lunarg** [comment]
should be fixed now that the new headers are in to `main`
