### ISSUE TITLE
VUID-VkImageCreateInfo-pNext-00990 incorrectly triggers for vkCreateImage with VkExternalFormatANDROID

### ISSUE THREAD

**Issue by chrvoss** [KhronosGroup/Vulkan-ValidationLayers#6646]
**Environment:**
 - OS: Android
 - GPU: Adreno 650
 - SDK: Validation Layer [1.3.261.1](https://github.com/KhronosGroup/Vulkan-ValidationLayers/releases/tag/sdk-1.3.261.1)

**Describe the Issue**

The issue occurs when creating a VkImage on Android representing a hardware buffer with a format that doesn't have a corresponding Vulkan format. The prototypical use case here is using the result of H.264 or H.265 video decoding on Qualcomm hardware, which should nominally decode to VK_FORMAT_G8_B8R8_2PLANE_420_UNORM (aka. NV12), but actually results in a vendor-defined external format with a somewhat different memory layout than user-created VK_FORMAT_G8_B8R8_2PLANE_420_UNORM images.

A full repro case is rather involved due to the large amount of setup code needed for creating a video decode session. Roughly, the Vulkan side of the code looks like this:

```
AHardwareBuffer hardwareBuffer = /* get hardware buffer from decoder */;

AHardwareBuffer_Desc bufferDesc{};
AHardwareBuffer_describe(hardwareBuffer, &bufferDesc);

// Query the buffer format
VkAndroidHardwareBufferFormatPropertiesANDROID bufferFormat{VK_STRUCTURE_TYPE_ANDROID_HARDWARE_BUFFER_FORMAT_PROPERTIES_ANDROID};
VkAndroidHardwareBufferPropertiesANDROID bufferProperties{VK_STRUCTURE_TYPE_ANDROID_HARDWARE_BUFFER_PROPERTIES_ANDROID};
bufferProperties.pNext = &bufferFormat;
vkGetAndroidHardwareBufferPropertiesANDROID(m_device, hardwareBuffer, &bufferProperties);

// Create a chain VkImageCreateInfo -> VkExternalMemoryImageCreateInfo -> VkExternalFormatANDROID
VkExternalFormatANDROID externalFormatAndroidInfo{VK_STRUCTURE_TYPE_EXTERNAL_FORMAT_ANDROID};
externalFormatAndroidInfo.externalFormat = bufferFormat.externalFormat; // This is 506 in our repro case

VkExternalMemoryImageCreateInfo externalMemoryInfo{VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO_KHR};
externalMemoryInfo.pNext = &externalFormatAndroidInfo;
externalMemoryInfo.handleTypes = VK_EXTERNAL_MEMORY_HANDLE_TYPE_ANDROID_HARDWARE_BUFFER_BIT_ANDROID;

VkImageCreateInfo imageCreateInfo = {VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO};
imageCreateInfo.pNext = &externalMemoryInfo;
imageCreateInfo.imageType = VK_IMAGE_TYPE_2D;
imageCreateInfo.extent.width = bufferDesc.width;
imageCreateInfo.extent.height = bufferDesc.height;
imageCreateInfo.extent.depth = 1;
imageCreateInfo.mipLevels = 1;
imageCreateInfo.arrayLayers = bufferDesc.layers;
imageCreateInfo.format = bufferFormat.format;	// This is VK_FORMAT_UNDEFINED in our repro case
imageCreateInfo.tiling = VK_IMAGE_TILING_OPTIMAL;
imageCreateInfo.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
imageCreateInfo.usage = VK_IMAGE_USAGE_SAMPLED_BIT;
imageCreateInfo.samples = VK_SAMPLE_COUNT_1_BIT;
imageCreateInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;

VkImage image;
vkCreateImage(m_device, &imageCreateInfo, nullptr, &image);
```

This triggers

> Validation Error: [ VUID-VkImageCreateInfo-pNext-00990 ] | MessageID = 0x466ca6a5 | vkCreateImage(): The handle type (VK_EXTERNAL_MEMORY_HANDLE_TYPE_ANDROID_HARDWARE_BUFFER_BIT_ANDROID), format (VK_FORMAT_UNDEFINED), type (VK_IMAGE_TYPE_2D), tiling (VK_IMAGE_TILING_OPTIMAL), usage (VK_IMAGE_USAGE_SAMPLED_BIT), flags (VkImageCreateFlags(0)) is not supported combination of parameters and vkGetPhysicalDeviceImageFormatProperties2 returned back VK_ERROR_FORMAT_NOT_SUPPORTED. (snip)

The issue here is that the validation layer queries vkGetPhysicalDeviceImageFormatProperties2 with VK_FORMAT_UNDEFINED, which of course fails.

In other places, the validation layer keeps track of external formats encountered so far via vkGetAndroidHardwareBufferPropertiesANDROID in ahb_ext_formats_map. I guess that external memory compatibility for a handle type of VK_EXTERNAL_MEMORY_HANDLE_TYPE_ANDROID_HARDWARE_BUFFER_BIT_ANDROID could be validated by checking that the externalFormat is present in that map, instead of querying vkGetPhysicalDeviceImageFormatProperties2.

**Expected behavior**

No validation error should be produced.

**Comment by spencer-lunarg** [comment]
thanks for raising this detailed issue, I personally just hit `VUID-VkImageCreateInfo-pNext-00990` myself today! The issue has been not being able to write a test as I never had a good way to work with a vendor format

Luckily I am about to add support for a way to "mock" the AHB implementation so I can **finally** write AHB tests like this and then will be able to fix the layers (and keep them fixed)

**Comment by spencer-lunarg** [comment]
details in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6856#issuecomment-1788548000 but got #6888 up to fix this
