### ISSUE TITLE
Missing feedback loop VU

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/Vulkan-ValidationLayers#6657]
https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5821/ change landed in 1.3.257 headers

it was VUID 08753 but is now  `VUID-vkCmdDraw-None-09000`

**Comment by spencer-lunarg** [comment]
can this be closed now @ziga-lunarg ?

**Comment by ziga-lunarg** [comment]
VUID 09003 is currently unimplemented.

**Comment by spencer-lunarg** [comment]
I guess the original issue was for `09000`, `09001`, and `09002`

I think `09003` needs spec clarification, pinged that in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5821#note_436725 and for now can close this and see what the WG says for that VU and go from there
