### ISSUE TITLE
FORMAT_TEXTURE2D_ATOMIC_64 and  VULAKN_ATOMIC64 and D3D12_FORMAT_R32G32

### ISSUE THREAD

**Issue by sd20134** [KhronosGroup/Vulkan-ValidationLayers#6670]
Hello, we want to do 64 atomic ops on a VK_FORMAT_R32G32_UINT targets.

Our tests show that this work quite well in Vulkan, however we are getting error in the validation layers
Here is the error message.

error : [unknown] assertion failure : false (Validation Error: [ VUID-vkCmdDispatch-None-02691 ] Object 0: handle = 0xb4ae2e000000007d, name = ShaderDescriptorTable, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; Object 1: handle = 0x51820000000007b, name = TextureRW, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x12a4e47d | vkCmdDispatch: Descriptor set VkDescriptorSet 0xb4ae2e000000007d[ShaderDescriptorTable] in binding #0 index 0, VkImageView 0x51820000000007b[TextureRW], format VK_FORMAT_R32G32_UINT, doesn't contain VK_FORMAT_FEATURE_STORAGE_IMAGE_ATOMIC_BIT. The Vulkan spec states: If a VkImageView is accessed using atomic operations as a result of this command, then the image view's format features must contain VK_FORMAT_FEATURE_STORAGE_IMAGE_ATOMIC_BIT

Can you share if there are specific issues with using VK_FORMAT_R32G32_UINT or the validation error is just bogus.

**Comment by spencer-lunarg** [comment]
Not all hardware supports `VK_FORMAT_FEATURE_STORAGE_IMAGE_ATOMIC_BIT` for `VK_FORMAT_R32G32_UINT`

In this case the device you are using doesn't fully support atomics, so trying to use on atomics "might" work, but it is [undefined behavior](https://raphlinus.github.io/programming/rust/2018/08/17/undefined-behavior.html)

I am not sure why this error message would be bogus

**Comment by sd20134** [comment]
thank you for your answer, is there a specific device that cannot do this ?

**Comment by sd20134** [comment]
i am asking because the tests were mostly on desktop gpus and it was fine there

**Comment by spencer-lunarg** [comment]
https://vulkan.gpuinfo.org/listdevicescoverage.php?optimaltilingformat=R32G32_UINT&featureflagbit=STORAGE_IMAGE_ATOMIC

Seems most devices do not support this

**Comment by spencer-lunarg** [comment]
@sd20134 there is nothing I see that can be done in the Validation Layers, we are just following what [the spec said](https://github.com/KhronosGroup/Vulkan-Docs) and reported that the format with the tiling used doesn't contain the required features

**Comment by sd20134** [comment]
thank you
