### ISSUE TITLE
Incorrect warning about using vkGetImageMemoryRequirements on imported Android hardware buffers

### ISSUE THREAD

**Issue by egdaniel** [KhronosGroup/Vulkan-ValidationLayers#669]
Currently when you try to bind memory that comes from an Android hardware buffer you will get a core validation warning that says:

"Binding memory to image 0xd but vkGetImageMemoryRequirements() has not been called on that image."

However, the Vulkan spec specifically says the following:

"The precise size of images that will be bound to external Android hardware buffer memory is unknown until the memory has been imported or allocated, so calling vkGetImageMemoryRequirements with such an image before it has been bound to memory will result in undefined behavior."

So the warning is not only incorrect but is also suggesting to do something is considered undefined behavior.

**Comment by locke-lunarg** [comment]
[PR #882 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/882)
Commits `layers: Validate AndroidHardwareBuffer`  & `tests: Validate vkGetImageMemoryRequirements`  for this issue.
