### ISSUE TITLE
Allow breaking on seq_no and reset_count

### ISSUE THREAD

**Issue by darksylinc** [KhronosGroup/Vulkan-ValidationLayers#6698]
**Environment:**
 - OS: Any
 - GPU and driver version: Any
 - SDK or header version if building from repo: It appears to apply to latest release.
 - Options enabled (synchronization, best practices, etc.): Any

**Describe the Issue**

Normally validation messages will look like this:

```
SYNC-HAZARD-WRITE_AFTER_WRITE(ERROR / SPEC): msgNum: -33950239 - Validation Error: [ SYNC-HAZARD-WRITE_AFTER_WRITE ] Object 0: handle = 0x277a4ff0, name = RID:541792944521253, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0xfdf9f5e1 | vkCmdCopyBuffer: Hazard WRITE_AFTER_WRITE for dstBuffer VkBuffer 0x277a4ff0[RID:541792944521253], region 0. Access info (usage: SYNC_COPY_TRANSFER_WRITE, prior_usage: SYNC_COPY_TRANSFER_WRITE, write_barriers: SYNC_VERTEX_SHADER_UNIFORM_READ|SYNC_TESSELLATION_CONTROL_SHADER_UNIFORM_READ|SYNC_TESSELLATION_EVALUATION_SHADER_UNIFORM_READ|SYNC_GEOMETRY_SHADER_UNIFORM_READ|SYNC_FRAGMENT_SHADER_UNIFORM_READ, command: vkCmdCopyBuffer, seq_no: 1347, reset_no: 5).
```

Very useful info there is that it reports the previous command, identified by `seq_no: 1347, reset_no: 5`.

However currently the layer has no way (either via vkconfig, environment variables, or via vkCmd call) to perform a breakpoint when those two conditions are hit. Right now I have to modify the source code and rebuild the layers:

```cpp
    ResourceCmdUsageRecord(vvl::Func command_, Count seq_num_, SubcommandType sub_type_, Count sub_command_,
                           const CMD_BUFFER_STATE *cb_state_, Count reset_count_)
        : command(command_),
          seq_num(seq_num_),
          sub_command_type(sub_type_),
          sub_command(sub_command_),
          cb_state(cb_state_),
          reset_count(reset_count_)
{
   if( unlikely( seq_num == 1347u && reset_count == 5u ) )
    {
        debug_break();
    }
}
```

You can see the implementation of [debug_break](https://github.com/OGRECave/ogre-next/blob/master/OgreMain/include/debugbreak/debugbreak.h) we use that works on all major platforms.

**Expected behavior**

It should be possible to easily break into the error when it happens on a second run (assuming the app guarantees deterministic behavior).

Suggestion:

Add `VK_BREAK_SEQ_NO` and `VK_BREAK_RESET_COUNT`. These are environment variables, and can be modified programmatically with `vkCmdSetDebugBreak( { VK_CMD_SET_DEBUG_BREAK, pNext = NULL, seq_no, reset_count } );`

**Valid Usage ID**

N/A

**Additional context**

N/A

**Comment by darksylinc** [comment]
Hi!

Conditional breakpoints will work with a debug build of the Validation Layers, yes; but it will likely not work (or be troublesome) with an out of the box build (which has optimizations turned on).

> Introducing new command is a bit complicated since it requires introduction of new extension. Environment variable + vkconfig might be more realistic option.

Sure, env variable + vkconfig sounds fine for me. I was merely throwing suggestions.

**Comment by artem-lunarg** [comment]
@darksylinc do you have opportunity to check if https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6904 works for you?
