### ISSUE TITLE
Refactor code reuse between 1.1 core and KHR entry points

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#67]
**Issue by [mikes-lunarg](https://github.com/mikes-lunarg) (MIGRATED)**
_Friday Mar 09, 2018 at 17:47 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2474_

----

Two issues here:
* At the very least, large amounts of duplicate code (eg unique_objects.cpp CreateDescriptorUpdateTemplate) should be refactored into a common function used by both KHR and core entry points
* Investigate if it is possible to remove some of the boilerplate that occurs even if KHR and core entry points share Pre/Post functions (eg core_validation.cpp EnumeratePhysicalDeviceGroupsKHR)

**Comment by mark-lunarg** [comment]
The second bullet should have been addressed by the chassis changes.

**Comment by mark-lunarg** [comment]
@mikes-lunarg, wanna keep this open?  Maybe you can take care of this during the codgen refactor?

**Comment by mark-lunarg** [comment]
This issue has been rolled into the [Validation Layer Enhancements Project Page](https://github.com/KhronosGroup/Vulkan-ValidationLayers/projects/4).
