### ISSUE TITLE
VUID-VkMemoryBarrier2-dstAccessMask-07454 incorrectly triggered for ACCELERATION_STRUCTURE_BUILD with SHADER_READ

### ISSUE THREAD

**Issue by MatejSakmary** [KhronosGroup/Vulkan-ValidationLayers#6712]
**Environment:**
 -  Windows 10
 -  GeForce GTX 1080 driver version 536.99
 -  SDK 1.3.261.1
 - Options enabled: Validation

After update from SDK version 1.3.250.1 to 1.3.261.1 Validation Layer error VUID-VkMemoryBarrier2-dstAccessMask-07454 triggered.

 There are two issues:
1) As can be seen from the API dump provided `VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR` and `VK_ACCESS_SHADER_READ_BIT` were not used, `VK_ACCESS_2_SHADER_READ_BIT` with `VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_BUILD_BIT_KHR` were used instead.

2) According to the validation message as well as online [documentation](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkAccessFlagBits.html) (Table 1. Supported access types) this combination of stage and access flag bits should be valid.

**Expected behavior**
No validation error triggered.

<details>

Full error message: 
```sh
[ VUID-VkMemoryBarrier2-dstAccessMask-07454 ] Object 0: handle = 0x2100c143b10, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xade1a5bb | vkCmdPipelineBarrier2(): pDependencyInfo.pMemoryBarriers[0].dstAccessMask bit VK_ACCESS_SHADER_READ_BIT is not supported by stage mask (VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR). The Vulkan spec states: If pname:dstAccessMask includes VK_ACCESS_2_SHADER_READ_BIT, pname:dstStageMask must include VK_PIPELINE_STAGE_2_ALL_GRAPHICS_BIT, VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT, VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_BUILD_BIT_KHR, VK_PIPELINE_STAGE_2_MICROMAP_BUILD_BIT_EXT, or one of the VK_PIPELINE_STAGE_*_SHADER_BIT stages (https://vulkan.lunarg.com/doc/view/1.3.261.1/windows/1.3-extensions/vkspec.html#VUID-VkMemoryBarrier2-dstAccessMask-07454)
```
API dump:
[dump.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/12922265/dump.1.txt)

</details>

**Comment by artem-lunarg** [comment]
This issues was fixed recently here https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6628. Should be available in the next SDK release or another option is to build the latest source code.
