### ISSUE TITLE
Not breaking on VK_DBG_LAYER_ACTION_BREAK for queue submission VUs

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/Vulkan-ValidationLayers#6716]
original issue from @zmike 

some VUs such as

> UNASSIGNED-Threading-MultipleThreads(ERROR / SPEC): msgNum: 337425955 - Validation Error: [ UNASSIGNED-Threading-MultipleThreads ] Object 0: handle = 0xf775d00000000144, type = VK_OBJECT_TYPE_SWAPCHAIN_KHR; | MessageID = 0x141cb623 | THREADING ERROR : vkQueuePresentKHR(): object of type VkSwapchainKHR is simultaneously used in current thread 140737110857408 and thread 140736829822656

don't trigger the `VK_DBG_LAYER_ACTION_BREAK` breakpoint

**Comment by arno-lunarg** [comment]
On windows, everything looks fine, for both GPU-AV and DebugPrintf.
Setting `VK_LAYER_DEBUG_ACTION=VK_DBG_LAYER_ACTION_BREAK` in debug environment settings, I get this when running `--gtest_filter=NegativeGpuAVDescriptorIndexing.ArrayOOBRuntime` with VS:
![unnamed](https://github.com/user-attachments/assets/8714fa8b-1dd5-4013-8aa5-e1a01a23823b)

**Comment by arno-lunarg** [comment]
Can also break on multi threading tests on Windows, `NegativeThreading.CommandBufferCollision` for instance

**Comment by spencer-lunarg** [comment]
As @arno-lunarg pointed out, the issue is less with `VK_DBG_LAYER_ACTION_BREAK` and more with the `raise(SIGTRAP)` in the Linux/Android code path... need to find something equivalent to [DebugBreak()](https://learn.microsoft.com/en-us/windows/win32/api/debugapi/nf-debugapi-debugbreak

**Comment by spencer-lunarg** [comment]
Ok, confirmed this also worked for me on Linux. Marking as complete for now, until have someway to reproduce
