### ISSUE TITLE
missing VK_EXT_fragment_density_map / VK_KHR_fragment_shading_rate (RenderPass/Framebuffer)

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/Vulkan-ValidationLayers#6730]
There are surely more missing, mostly dealing with SPIR-V and AHB, but here are some I found that are focused on the Renderpass/Framebuffer side

- [x] VUID-VkFramebufferCreateInfo-flags-03196 (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8230)
- [x] VUID-VkFramebufferCreateInfo-flags-03197 (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8230)
- [ ] VUID-VkFramebufferCreateInfo-flags-04587
- [x] VUID-VkFramebufferCreateInfo-pAttachments-02552 (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8227)
- [x] VUID-VkFramebufferCreateInfo-renderPass-02553
- [x] VUID-VkRenderPassCreateInfo2-pAttachments-09387
- [x] VUID-VkRenderPassFragmentDensityMapCreateInfoEXT-fragmentDensityMapAttachment-02548 (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8252)

**Comment by spencer-lunarg** [comment]
@r-potter note this issue was open, I marked off the few you added recently

**Comment by r-potter** [comment]
Thanks @spencer-lunarg. We have something for 02548 on the way. 04587 needed a spec change to the VUID, which was signed off but not published last week

**Comment by spencer-lunarg** [comment]
https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6766 will replace `VUID-VkFramebufferCreateInfo-renderPass-08921` with `VUID-VkFramebufferCreateInfo-flags-04587` so this is issue is done and closing
