### ISSUE TITLE
Misc VUs missing coverage

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/Vulkan-ValidationLayers#6738]
These are found during my searching for things not validated yet, these didn't match any group and making a single issue as they are all relatively simple to add

- [x] VUID-VkBindBufferMemoryInfo-bufferDeviceAddress-03339
- [x] VUID-VkCommandBufferBeginInfo-flags-09240
- [x] VUID-VkPipelineLayoutCreateInfo-descriptorType-06531 (related VUID-VkPipelineLayoutCreateInfo-descriptorType-02217)
- [x] VUID-VkRenderPassMultiviewCreateInfo-multiview-06555
- [x] VUID-vkCmdBindPipeline-pipelineBindPoint-06653 (Spencer to see why it is a duplicate)
- [x] VUID-vkCmdBindPipeline-pipelineBindPoint-06721

**Comment by ziga-lunarg** [comment]
Is `VUID-vkCmdBindPipeline-pipelineBindPoint-06653` also new? Seems like a copy of `VUID-vkCmdBindPipeline-pipeline-03382`

**Comment by spencer-lunarg** [comment]
aww, seems like it, will take care of that one
