### ISSUE TITLE
validation layers should validate VK_KHR_shader_float_controls

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/Vulkan-ValidationLayers#674]
Validation of VK_KHR_shader_float_controls was first proposed to be done in SPIRV-Tools : https://github.com/KhronosGroup/SPIRV-Tools/pull/2177 

There was a debate about whether the validation should be done in the layer or in SPIRV-Tools.  Discussion offline concluded this was better done in layers.

@mikes-lunarg suggested that there was already code looking at entry point execution modes, which is the key introspection required here.

(For my own reference, the extension spec is here:

https://github.com/KhronosGroup/Vulkan-Docs/blob/master/appendices/VK_KHR_shader_float_controls.txt

)

**Comment by AttilioProvenzano-ARM** [comment]
Hi @dneto0, thanks for following up on this, I'll look into completing the PR for the layers now.

**Comment by jzulauf-lunarg** [comment]
Pending PR https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/513

**Comment by jzulauf-lunarg** [comment]
@mikes-lunarg -- I can't assign @AttilioProvenzano-ARM  and you're both tagged on the PR
