### ISSUE TITLE
Feature Request: Add Ability to Programmatically Disable Specific Validation Layers in vk::InstanceCreateInfo

### ISSUE THREAD

**Issue by Koromire** [KhronosGroup/Vulkan-ValidationLayers#6789]
**Problem Statement:**
Vulkan currently offers control over which validation layers are enabled through the application via `vk::InstanceCreateInfo::ppEnabledLayerNames`. However, it lacks the ability to explicitly disable certain layers from within the application itself. This leads to challenges when incompatible or older API versions of layers are automatically loaded, resulting in warnings or issues.

**Use Case Example(s):**
When developing a Vulkan application with API version 1.3, I encountered warnings like:

```
Layer VK_LAYER_OW_OBS_HOOK uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
```
While Vulkan Configurator allows for an exclusion list, controlling this programmatically within the application is currently not feasible.

**Suggested Solution:**
Introduce a new member variable in `vk::InstanceCreateInfo`, such as `ppDisabledLayerNames` or `ppForceDisabledLayerNames`, to specify layers that should not be enabled.

Example:

```
vk::InstanceCreateInfo createInfo;
createInfo.ppEnabledLayerNames = enabledLayers;
createInfo.ppDisabledLayerNames = disabledLayers;
```

Best regards,
Koromire

**Comment by ziga-lunarg** [comment]
This is not something for validation layers, but for the loader. And you can do this through the `VK_LOADER_LAYERS_DISABLE` environment variable.

You can read more about it here: https://github.com/KhronosGroup/Vulkan-Loader/blob/main/docs/LoaderInterfaceArchitecture.md

You can also take a look at vkconfig: https://github.com/LunarG/VulkanTools/blob/main/vkconfig/README.md
It allows you to enable and disable the layers you want.
