### ISSUE TITLE
1.3.268.0: cmake fails

### ISSUE THREAD

**Issue by kloczek** [KhronosGroup/Vulkan-ValidationLayers#6830]
**Environment:**
 - OS: Linux x86/64
 - GPU and driver version: N/A
 - SDK or header version if building from repo: 1.3.268.0
 - Options enabled (synchronization, best practices, etc.): N/A

**Describe the Issue**
cmake fails with:
<details>

```console
+ /usr/bin/cmake -B x86_64-redhat-linux-gnu -D BUILD_SHARED_LIBS=ON -D CMAKE_AR=/usr/bin/gcc-ar -D CMAKE_BUILD_TYPE=RelWithDebInfo -D CMAKE_C_FLAGS_RELEASE=-DNDEBUG -D CMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -D CMAKE_Fortran_FLAGS_RELEASE=-DNDEBUG -D CMAKE_INSTALL_PREFIX=/usr -D CMAKE_NM=/usr/bin/gcc-nm -D CMAKE_RANLIB=/usr/bin/gcc-ranlib -D CMAKE_VERBOSE_MAKEFILE=ON -D INCLUDE_INSTALL_DIR=/usr/include -D LIB_INSTALL_DIR=/usr/lib64 -D LIB_SUFFIX=64 -D SHARE_INSTALL_PREFIX=/usr/share -D SYSCONF_INSTALL_DIR=/etc -S . -D BUILD_LAYER_SUPPORT_FILES=ON -D BUILD_TESTS=OFF -D CMAKE_INSTALL_INCLUDEDIR=/usr/include/vulkan -D GLSLANG_INSTALL_DIR=/usr/bin -D SPIRV_HEADERS_INSTALL_DIR=/usr -D USE_ROBIN_HOOD_HASHING=OFF -D VULKAN_HEADERS_INSTALL_DIR=/usr
-- The CXX compiler identification is GNU 13.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at CMakeLists.txt:162 (message):
  BUILD_LAYER_SUPPORT_FILES is deprecated! See
  https://github.com/KhronosGroup/Vulkan-Utility-Libraries/issues/18


-- Could NOT find robin_hood (missing: robin_hood_DIR)
-- Configuring done (0.7s)
CMake Error at layers/CMakeLists.txt:74 (target_link_libraries):
  Target "VkLayer_utils" links to:

    Vulkan::LayerSettings

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.



-- Generating done (0.0s)
```
</details>

**Comment by juan-lunarg** [comment]
The validation layers now has a dependency on the [Vulkan-Utility-Libraries](https://github.com/KhronosGroup/Vulkan-Utility-Libraries).

Install that repo first and point to the installation similar to the other dependencies.

**Comment by juan-lunarg** [comment]
Also remove the following from your configuration step:

```
-D BUILD_LAYER_SUPPORT_FILES=ON  # This does nothing now. And produces a warning.
```

May help to take a look at homebrew. Since they already fixed this issue a bit ago:
https://github.com/Homebrew/homebrew-core/pull/152290

Since they already have the utility libraries in their setup.

**Comment by kloczek** [comment]
I've been trying to package that with enabled tests and cannot find `magic_enum`
```
CMake Error at tests/CMakeLists.txt:8 (find_package):
  Could not find a package configuration file provided by "magic_enum" with
  any of the following names:

    magic_enumConfig.cmake
    magic_enum-config.cmake

  Add the installation prefix of "magic_enum" to CMAKE_PREFIX_PATH or set
  "magic_enum_DIR" to a directory containing one of the above files.  If
  "magic_enum" provides a separate development package or SDK, be sure it has
  been installed.
```

**Comment by juan-lunarg** [comment]
> I've been trying to package that with enabled tests and cannot find magic_enum

Why are you enabling testing? If your goal is to package libraries enabling testing makes your life harder.

**Comment by kloczek** [comment]
> Why are you enabling testing? If your goal is to package libraries enabling testing makes your life harder.

Testing each build package by execute included test suite is not only about testing just build software but about testing other components used in test procedure like compiler and other. More test suites -> higher probabilisty to catch something which shuld not happen.

**Comment by juan-lunarg** [comment]
The utility libraries uses magic_enum for testing.

https://github.com/Neargye/magic_enum

You'll need to install that similar to vulkan-headers and all the other dependencies if you want to run the utility library testing.

**Comment by juan-lunarg** [comment]
Were you able to get things working? Or do you need more information?

**Comment by kloczek** [comment]
I need more time to package `magic_enum` (I'm busy now with other thing and will back tho Vulkan-ValidationLayers probably tomorrow).
I'll close this ticket because missing package in my bolid env has nothing to do with Vulkan-ValidationLayers.
If something will be wrong on testing I'll open new ticket.

Thank you for your time 👍
