### ISSUE TITLE
vkAcquireNextImage2KHR causes false error messages in further submit and present calls

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#69]
**Issue by [ColAngel](https://github.com/ColAngel) (MIGRATED)**
_Wednesday Mar 21, 2018 at 06:28 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2502_

----

If this function is used then vkQueueSubmit throws false error that semaphore which was used in the vkAcquireNextImage2KHR has no way to be signalized and the queue is waiting on it. 
Further the vkQueuePresentKHR throws false error message that the image with the index X was not aquired. Tested it with MultiGPU (DeviceGroups) and for single Physical Device. Both have this issue.
However the actuall code seems to work just fine and all functions return vkSuccess

**Comment by karl-lunarg** [comment]
<a href="https://github.com/mark-lunarg"><img src="https://avatars2.githubusercontent.com/u/7252958?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mark-lunarg](https://github.com/mark-lunarg) (MIGRATED)**
_Wednesday Mar 21, 2018 at 18:13 GMT_

----

Compatible validation for this API has not yet been implemented.

**Comment by krOoze** [comment]
@mark-lunarg @ColAngel I have not tested, but this seems implemented. The state tracking is common for both classic and 2KHR function.

**Comment by mark-lunarg** [comment]
Sweet!  Thanks @krOoze, for all of your help.
