### ISSUE TITLE
`GroupOperation` missing instructions that aren't `NonUniform`?

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-ValidationLayers#6902]
The `GroupOperation` function in the validator is supposed to return whether the given opcode is a group operation. I gather that the list of opcodes is generated automatically via this code:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/7589ad3a94712d13285106d52e8fc541205ddbf0/scripts/generators/spirv_grammar_generator.py#L133-L134

This code seems to select specifically instructions of the `NonUniform` class, but there are [other group operations in SPIR-V](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#_group_operation) too. The validation checks that use this function do not say anything about applying only to `NonUniform` group instructions. They simply refer to "group operations":

> VUID-RuntimeSpirv-None-06343
> [Group operations](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#shaders-group-operations) with [subgroup scope](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#shaders-scope-subgroup) **must** not be used if the shader stage is not in [`subgroupSupportedStages`](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#limits-subgroupSupportedStages)

> VUID-RuntimeSpirv-None-06275
> [`shaderSubgroupExtendedTypes`](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#features-subgroup-extended-types) **must** be enabled for [group operations](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#shaders-group-operations) to use 8-bit integer, 16-bit integer, 64-bit integer, 16-bit floating-point, and vectors of these types

Therefore, I wonder if this is a mistake in the validator and this function should really be returning `true` for *all* group operations listed in the SPIR-V spec, not only the `NonUniform` ones.

**Comment by spencer-lunarg** [comment]
all the other Group Operations require `SPV_AMD_shader_ballot`/`VK_AMD_shader_ballot` (or `SPV_KHR_uniform_group_instructions` which isn't supported in Vulkan)

So agree this is an issue, but only for anyone using `VK_AMD_shader_ballot` at the moment

**Comment by Rua** [comment]
What about operations like `OpGroupIAdd` and `OpGroupBitwiseAndKHR`? Are they not supported by Vulkan?

**Comment by spencer-lunarg** [comment]
![image](https://github.com/KhronosGroup/Vulkan-ValidationLayers/assets/115671160/a6eb6aef-7e9f-44ae-b0cd-b108b9a79683)

and `Groups` is not in https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#spirvenv-capabilities

There is an internal spec PR to get it added for `VK_AMD_shader_ballot` but now with 1.1 subgroups, I feel that priority to fix this edge case is low

**Comment by spencer-lunarg** [comment]
I found the original issue https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3689

Closing this as a duplicate, but linking info
