### ISSUE TITLE
Validation for shader objects in regards to dynamic state mixing extension and non-extension function

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-ValidationLayers#6909]
**Environment:**
 - OS: Windows 11
 - GPU and driver version: NVIDIA RTX 4070 with latest driver
 - SDK or header version if building from repo: Packaged SDK 1.3.268.0 
 - Options enabled (synchronization, best practices, etc.): none

**Describe the Issue**

While trying to fix open validation issues for my shader object sample (see https://github.com/SaschaWillems/Vulkan/blob/master/examples/shaderobjects/shaderobjects.cpp) I noticed that the validation errors related to shader object and dymamic state are mixing extension function names with non-extension functions names. This sample uses Vulkan 1.0 and makes use of the `VK_EXT_shader_object`  and dynamic state extensions.

These are two of the messages I'm getting with the latest SDK:

```
ERROR: [-641312433][VUID-vkCmdDrawIndexed-None-08654] : Validation Error: [ VUID-vkCmdDrawIndexed-None-08654 ] Object 0: handle = 0x17c0b2effc0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xd9c6594f | vkCmdDrawIndexed():  VK_DYNAMIC_STATE_ALPHA_TO_COVERAGE_ENABLE_EXT state not set for this command buffer. The Vulkan spec states: If a shader object is bound to any graphics stage, and the most recent call to vkCmdSetRasterizerDiscardEnable in the current command buffer set rasterizerDiscardEnable to VK_FALSE, then vkCmdSetAlphaToCoverageEnableEXT must have been called in the current command buffer prior to this drawing command (https://vulkan.lunarg.com/doc/view/1.3.268.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdDrawIndexed-None-08654)
```

and

```
ERROR: [1562429016][VUID-vkCmdDrawIndexed-None-08640] : Validation Error: [ VUID-vkCmdDrawIndexed-None-08640 ] Object 0: handle = 0x17c0b2effc0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x5d20c658 | vkCmdDrawIndexed():  VK_DYNAMIC_STATE_DEPTH_BIAS_ENABLE state not set for this command buffer. The Vulkan spec states: If a shader object is bound to any graphics stage, and the most recent call to vkCmdSetRasterizerDiscardEnable in the current command buffer set rasterizerDiscardEnable to VK_FALSE, then vkCmdSetDepthBiasEnable must have been called in the current command buffer prior to this drawing command (https://vulkan.lunarg.com/doc/view/1.3.268.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdDrawIndexed-None-08640)
```

The first one mixes the non-extended `vkCmdSetRasterizerDiscardEnable` with the extended `vkCmdSetAlphaToCoverageEnableEXT `.

The second call only refers to non-extended functions.

Both can be misleading.

**Expected behavior**

When using the shader object and dynamic state extensions (and not the core versions that e.g. include a given dynamic state extension), the validation messages should always refer to the extension function names.

**Valid Usage ID**
* VUID-vkCmdDrawIndexed-None-08654
* VUID-vkCmdDrawIndexed-None-08640
* And probably more...

**Comment by ziga-lunarg** [comment]
Everything that comes after `The Vulkan spec states:` in these messages is copied directly from the spec.

**Comment by SaschaWillems** [comment]
And that's exactly the issue. The layer messages mix extension and core functions. So this probably is a spec issue instead of a layer issue then.

**Comment by spencer-lunarg** [comment]
I think this is a spec issue, looking, `08640` and `08654` should just be a single VU that says either `vkCmdSetAlphaToCoverageEnableEXT` (and/or?) `vkCmdSetDepthBiasEnable` is set

**Comment by spencer-lunarg** [comment]
so spending more time looking into this, I guess first thing is this is not a VVL issue, we are just reporting the spec VU text, nothing that can be done here

As for making a spec issue, I guess you could try, the issue is `VK_EXT_extended_dynamic_state2` was promoted to 1.3 but `VK_EXT_extended_dynamic_state3` wasn't

this means `vkCmdSetDepthBiasEnable` has a promoted name, which I feel in general the spec aims for, so might be more churn then it is worth to try and have it be the correct name depending on the logic of which extensions/versions are being used

----

![image](https://github.com/KhronosGroup/Vulkan-ValidationLayers/assets/115671160/c1bf7ffc-e9af-4c33-a99b-d721f715c4e7)
