### ISSUE TITLE
False positive from buffer bounds validation with multi-planar formats

### ISSUE THREAD

**Issue by ilkkasaa** [KhronosGroup/Vulkan-ValidationLayers#691]
I'm working on YCbCr tests in Vulkan CTS and I get the following validation error from vkCmdCopyBufferToImage() with multi-planar formats:
`ERROR:  [ VUID-vkCmdCopyBufferToImage-pRegions-00171 ] Object: VK_NULL_HANDLE (Type = 6) | vkCmdCopyBufferToImage(): pRegion[0] exceeds buffer size of 528 bytes.. The Vulkan spec states: srcBuffer must be large enough to contain all buffer locations that are accessed according to Buffer and Image Addressing, for each element of pRegions (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdCopyBufferToImage-pRegions-00171) (code 0x00000000 from Validation at CommandBuffer:0)`

The error seems to be caused by buffer validation function `ValidateBufferBounds()` that does not handle multi-planar formats correctly. The function computes incorrectly the required buffer size. It uses `FormatElementSize()` to get the element size (and uses the size to compute the minimum required buffer size), but this does not work for multi-planar formats. Multi-plane compatible formats should be used to compute the buffer size requirement for each plane individually.

I guess that similar problems may exist elsewhere `FormatElementSize()` is used. Atleast `ValidateBufferImageCopyData()` possibly causes false positive `VUID-VkBufferImageCopy-bufferOffset-00193` error with multi-planar formats (I haven't tested it).

**Comment by jzulauf-lunarg** [comment]
Triage notes: The reporter has it correct.  We need to test the image format for multiplane and use the accessMask bit (only one can be specified) and format calling `FindMultiplaneCompatibleFormat` to get the format for the plane in use, and use the element size for *that* format in the size computation for the current pRegion entry,

**Comment by locke-lunarg** [comment]
[Pull request #764 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/764)

**Comment by sasmaster** [comment]
Hi guys. Is this one fixed? I hit the same issue where I need to copy Luma and Chroma data from YUV buffer into multi-planar image and it reports stuff like this:

Severity: Error,Type:Validation,10:58:15 ERROR  Message:Vulkan API:Validation Error: [ VUID-vkCmdCopyBufferToImage-pRegions-00171 ] Object 0: handle = 0x1eed79d1168, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6f4d3c00 | vkCmdCopyBufferToImage(): pRegion[1] exceeds buffer size of 589824 bytes.. The Vulkan spec states: srcBuffer must be large enough to contain all buffer locations that are accessed according to Buffer and Image Addressing, for each element of pRegions (https://vulkan.lunarg.com/doc/view/1.2.148.0/windows/1.2-extensions/vkspec.html#VUID-vkCmdCopyBufferToImage-pRegions-00171)

Even though the buffer size and copy setup looks correct.
