### ISSUE TITLE
Version mistach error when getting VkPhysicalDeviceSubgroupProperties 

### ISSUE THREAD

**Issue by linw789** [KhronosGroup/Vulkan-ValidationLayers#6911]
**Environment:**
 - OS: Windows 10
 - GPU and driver version: AMD Radeon RX 6800 XT with the latest driver
 - SDK or header version if building from repo: 1.3.261.1

vkvia.exe shows:
```none
"Vulkan Driver Info": 
    API version: 1.3.246
```

**Describe the Issue**

```c++
VkPhysicalDeviceSubgroupProperties subgroup_properties {
    .sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_PROPERTIES,
    .pNext = NULL };
VkPhysicalDeviceProperties2 physical_device_properties {
    .sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2,
    .pNext = &subgroup_properties };

vkGetPhysicalDeviceProperties2(vkb_device.physical_device, &physical_device_properties);
```

Vulkan Validation Layer reports: 

Validation Error: [ VUID-VkPhysicalDeviceProperties2-pNext-pNext ] Object 0: handle = 0x1d537ec8540, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xdd73dbcf | vkGetPhysicalDeviceProperties2KHR: Includes a pNext pointer (pProperties->pNext) to a VkStructureType (VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_PROPERTIES) which was added in VK_API_VERSION_1_1 but the current __effective API version__ is 1.0.0 (0x00400000). The Vulkan spec states: Each pNext member of any structure (including this one) in the pNext chain must be either NULL or a pointer to a valid instance of VkPhysicalDeviceAccelerationStructurePropertiesKHR, ...

What is "effective API version" in this context?

**Expected behavior**

No error

**Comment by spencer-lunarg** [comment]
You might have a 1.3 Instance Version (since that is handled in the Loader), but if you created your `VkDevice` with 1.0 then it takes the minimum version

In this case, your driver supports version 1.3.246, but you most likely set `VkApplicationInfo::apiVersion` to be `VK_API_VERSION_1_0` and that is why you are getting the error

**Comment by linw789** [comment]
That was the issue. Thank you!
