### ISSUE TITLE
GPU Assisted validation ignores khronos_validation.gpuav_max_buffer_device_addresses setting in vkconfig

### ISSUE THREAD

**Issue by Ipotrick** [KhronosGroup/Vulkan-ValidationLayers#6912]
**Environment:**
 - OS: windows 10
 - GPU and driver version: RTX 4080 
 - SDK or header version if building from repo: 1.3.268.0
 - Options enabled (synchronization, best practices, etc.): GPU assisted + bounds checks

**Describe the Issue**

The validation layers ignore the setting `#khronos_validation.gpuav_max_buffer_device_addresses`.
I tried to set it via vkconfig and by placing a vk_layer_settings.txt in the working dir. It ignored it both times and continued to gave me the following message:
```
UNASSIGNED-GPU-Assisted-Validation(ERROR / SPEC): msgNum: -359834619 - Validation Error: [ UNASSIGNED-GPU-Assisted-Validation ] | MessageID = 0xea8d5c05 | Setup Error. Detail: (Number of buffer device addresses in use (10976) is greapter than khronos_validation.max_buffer_device_addresses (10000). Truncating BDA table which could result in invalid validation)
    Objects: 0
```

**Expected behavior**

The validation layers should respect the value set in vk config and or the value in the vk layer config txt.

</details>

**Comment by spencer-lunarg** [comment]
@Tony-LunarG I know you just touched the GPU-AV settings recently, can you take a quick look

**Comment by Tony-LunarG** [comment]
@Ipotrick, I've been able to reproduce the vkconfig problem and have a fix in #6921.
I wasn't able to reproduce the problem with a vk_layer_settings.txt file in the working directory.  When you saw that problem, was, perhaps, vkconfig still running?  I'm seeing vkconfig overriding a vk_layer_settings.txt file and wonder if that was what you were seeing.

**Comment by Ipotrick** [comment]
That could indeed be the case. I will retest when i am at my home pc.

**Comment by Tony-LunarG** [comment]
@Ipotrick can this be closed?

**Comment by Tony-LunarG** [comment]
Closing - Please submit another issue if there is still a problem

**Comment by Ipotrick** [comment]
vkconfig was running while i tested, i forgot about this thread, sorry. Closing is perfect if there is a fix :D.
