### ISSUE TITLE
VUID UNASSIGNED-CoreValidation-DrawState-InvalidImageAspect with image memory barrier is not invalid

### ISSUE THREAD

**Issue by ziga-lunarg** [KhronosGroup/Vulkan-ValidationLayers#6919]
Attempt to fix: #6906

The spec says nothing about image memory barriers needing to have the same aspect as the image.

**Comment by spencer-lunarg** [comment]
https://gitlab.khronos.org/vulkan/vulkan/-/issues/3814

**Comment by spencer-lunarg** [comment]
Working Group agreed this is invalid to have

```
format = VK_FORMAT_D16_UNORM
aspectMask = VK_IMAGE_ASPECT_DEPTH_BIT | VK_IMAGE_ASPECT_STENCIL_BIT
```

I will be creating a spec fix and then applying the VU after

**Comment by spencer-lunarg** [comment]
![image](https://github.com/KhronosGroup/Vulkan-ValidationLayers/assets/115671160/b740d5b2-9497-4201-b35f-c64e8803633c)

Here is the spec that states this as well
