### ISSUE TITLE
Enabling layers breaks rendering in MoltenVK?

### ISSUE THREAD

**Issue by kondrak** [KhronosGroup/Vulkan-ValidationLayers#693]
After a brief email discussion with LunarG and Valve I was asked to report this problem here:
When using MoltenVK, enabling validation layers causes some of the pipelines in the program to not render at all. The problem occurs no matter if VK_EXT_DEBUG_UTILS or VK_EXT_DEBUG_REPORT is used. The number of pipelines doesn't seem to play any role here, since I can reproduce the issue in my bigger applications and smaller test programs with 2-3 pipelines at max. When validation layers are disabled, everything renders perfectly. The application in question was tested on multiple Windows and Linux machines with Intel, Nvidia and AMD GPUs - no validation errors/warnings are being reported so I'm confident the code is ok. The layers seem to work fine when enabled in MoltenVK (errors/warning/info is being reported correctly), so it seems as if there's some broken transformation happening behind the scenes that impacts the final image?
It was suggested that due to specific way MoltenVK works, the problem could be related to this issue: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/528 - either way, one idea is that SPIR-V code is being malformed, so maybe it's a good starting point for investigation?

Testing using SDK 1.1.97.0 but the problem occurs also on 1.1.92.1

**Comment by jzulauf-lunarg** [comment]
@greg-lunarg @chrisforbes -- this could use some shader validation triage/assessment

**Comment by karl-lunarg** [comment]
Some of the email discussion included a guess that the transformations applied in #528 would affect the proper action of spirv-cross, which is an element in the MoltenVK chain that is not present in the other platforms.  Spirv-cross is used as part of the process to convert the shaders for Metal.   If this is the case, it isn't clear if the SPIR-V transformed by #528 is invalid, or if spirv-cross isn't handling the transforms correctly.

It might be useful to implement #528 (i.e., do what it says) and see if that fixes this problem.

**Comment by greg-lunarg** [comment]
While I believe that #528 is probably a better ultimate solution, building a V-VL with #683 might be a quick, short-term solution and/or a good experiment to see if spirv-opt is indeed the problem, IF the shaders involved do not contain group decorates. @kondrak is this something you could try?

**Comment by kondrak** [comment]
Sure, I'll check it out and report back soon!

**Comment by kondrak** [comment]
I've now build the validation layers using the branch from #683 and see no apparent difference. There are no MoltenVK errors reported in the background. 
I started suspecting this could be indeed a bug in my code but I this issue also appears in our custom game engine that we're developing independently, so it seems to be something hidden in MoltenVK/layers after all.
I launched the application with `VK_LOADER_DEBUG=all` but can't see anything out of ordinary just yet.

**Comment by karl-lunarg** [comment]
As @greg-lunarg pointed out, using the #683 fix would produce a different result only if there are group decorations in the shaders.  If there's any doubt about that, @kondrak would it be possible to set a breakpoint or change the code so that something noticeable happens at the place where the optimizer is called?  This could be someplace in the `if (has_group_decoration)` block around line 112 in the patch for shader_validation.h.   If the code here to call the optimizer never runs, we can rule out this optimizer pass.

Other ideas:

@billhollings: Is it possible to automatically save the shader sources after the spirv-cross step and before they are passed to the Metal shader compiler?  If so, then perhaps they can be saved with and without the validation enabled and then compared.  If they match, then that points us away from the shader stack.

About the only other thing I can think of that could be caused by the validation layers is a possible reordering of Vulkan commands as they reach the MoltenVK driver if the app is threaded.  The layers do a lot of locking/unlocking around accessing the state tracking data and it *may* be possible for this to affect when commands reach the driver.  If the application is perfectly correct in terms of synchronization, then this reordering should be harmless.  But synchronization validation is only partially implemented and it is possible for applications to seemingly work fine and pass validation but still have a hole in synchronization.  This reordering could have a subtle but unique effect in MoltenVK.  This is a bit of a longshot.  But @kondrak, if the app is multithreaded and there is an easy way to run it single threaded, can you try that?

@kondrak you also mentioned "smaller test programs".  Will it be possible for you to provide one of them as a repro test, in case it is needed?

**Comment by mark-lunarg** [comment]
Double-checked the source again, and the (non-GPU) shader validation does NOT change the shader binary that is ultimately sent down-chain to the subsequent layers or to the display driver.

**Comment by billhollings** [comment]
@karl-lunarg To answer your question about MSL shader source visibility...enabling the `MVK_DEBUG` runtime environment variable will cause MoltenVK to log all SPIR-V and MSL converted from it to the console.

**Comment by karl-lunarg** [comment]
Thanks, @billhollings.  But @mark-lunarg's note above implies that the layers are not modifying the SPIR-V.  So looking for differences in the SPIR-V and converted MSL with and without the layers should show no differences.  I don't know if it is still worth making sure that's the case or not.

**Comment by kondrak** [comment]
The application in question is single threaded but I also checked multithreading and there's no difference. SInce it's now confirmed that no shader code is being modified, I'll try to provide a minimum repro application soon and post it here.

**Comment by kondrak** [comment]
I've now published a sample application where the problem occurs: https://github.com/kondrak/mvk_validationbug
The program uses two simple pipelines - one renders a texture quad, the other handles rendering of a bitmap font, so both are fairly simple. With validation layers enabled, only the quad is rendered. With layers disabled, both quad and debug overlay text (framerate, frame length and a few other stats) are rendered. There's a preprocessor macro `VALIDATION_LAYERS_ON` passed to Debug build by default which controls whether the layers should be created or not. 

The project should build out of the box but it requires SDL2 framework to be present in the system - if that's a problem, let me know and I'll try and remove that dependency.

**Comment by mikes-lunarg** [comment]
I can reproduce the issue, looking now

**Comment by karl-lunarg** [comment]
@mikes-lunarg and I found the problem, and it is all related to synchronization, as I sort of speculated in this [comment](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/693#issuecomment-462807019), although it had nothing to do with threading.

I tried this on a MacBook Pro 2017 with a Radeon Pro 560 GPU.  I didn't even see the brick texture, with or without the validation layers enabled..  I fixed this by adding a global memory pipeline barrier to the `copyBuffer()` function in Buffers.cpp, just before the submit.  I suppose that a more constrained buffer barrier would be more appropriate for a final solution.  This made the brick texture appear.

The problem with the overlay not drawing is solved by adding `VK_MEMORY_PROPERTY_HOST_COHERENT` to line 48 in Buffers.cpp.  You were mapping and updating this memory, which is host visible, device local, and host cached.  The host writes were not made visible to the device.  The spec says:

> "Unmapping non-coherent memory does not implicitly flush the host mapped memory, and host writes that have not been flushed may not ever be visible to the device. However, implementations must ensure that writes that have not been flushed do not become visible to any other memory."

I suppose you could add a `vkFlushMappedMemoryRanges()` after the unmap in the font rendering path as another way to approach fixing this.  This could be more performant than turning on coherency.

It is also likely that you would need to add more memory barriers or other synchronization in order for things to be completely correct.  You may wish to review this [guide](https://github.com/KhronosGroup/Vulkan-Docs/wiki/Synchronization-Examples) or other information on synchronization.

This is an example of how things can work OK on some platforms and not on others, unless the proper synchronization is used.

I can't completely explain why the validation layers made this symptom appear.  My only suggestion is that it changed the timing enough to expose the problem.  Or the layers had some sort of impact on the host memory system.  The answer is probably deep in the details of about how MoltenVK implements or maps the various Vulkan memory types in the Metal environment.

Thanks for the reproduce case.  We probably would have had to punt without it.

**Comment by kondrak** [comment]
Thanks for the analysis! Are these kinds of problems something that validation layers could potentially catch in future releases?

**Comment by karl-lunarg** [comment]
> Are these kinds of problems something that validation layers could potentially catch in future releases?

Yes.  But the complete solution is a very difficult and large problem.  The solution is also probably expensive enough that it would need to be turned on explicitly via an option.  Some work has been started in this area and it is "on the list".  But the high volume of incoming issues has slowed the progress.

**Comment by kondrak** [comment]
Thanks Karl!
Also, I figured out why things are working on other platforms. As you may have noticed, I'm using VMA to handle memory allocations and it seems that both on Windows and Linux devices all memory blocks are host coherent - not sure how that is assigned yet (I haven't looked that deep into VMA) but the gist is that flushing memory ranges is completely skipped right now by the library. I'll investigate it a bit further.

**Comment by adam-sawicki-amd** [comment]
Hello. I'm the author of Vulkan Memory Allocator library. The choice of memory type can be made in different ways, as described on library documentation page "Choosing memory type". You can specify a high-level intended memory usage or a set of required and preferred flags. Specific memory type is then chosen according to the algorithm recommended by Vulkan spec, chapter "10.2. Device Memory", which is selecting the first type that meets the requirements. The memory type might have additional flags as well. (For example, on Windows Intel all memory is `HOST_VISIBLE`. On all 3 PC GPU vendors on Windows, all `HOST_VISIBLE` memory is also `HOST_COHERENT`.) There are no "negative" requirement flags in VMA. If you want to explicitly choose memory type that doesn't have specific flags, you can use `VmaAllocationCreateInfo::memoryTypeBits` to narrow the choice of memory types that can be selected for an allocation. That shouldn't be required in normal use cases though.

If you use a memory type which is, or at least may be, not `HOST_COHERENT`, you must flush it after CPU write and invalidate it before CPU read. VMA provides functions for that: `vmaFlushAllocation`, `vmaInvalidateAllocation`. When used with memory type that is `HOST_COHERENT`, these calls are ignored, which is correct according to Vulkan spec, chapter "10.2.1. Host Access to Device Memory Objects".

So if you use memory that is `HOST_VISIBLE` but not `HOST_COHERENT` and don't do flush and invalidate, this is a bug in your code. Please either do flush/invalidate, or request memory to be allocated from a type that is guaranteed to be `HOST_COHERENT`.

If, on the other hand, the Vulkan flush or invalidate call is required for a memory type that is `HOST_COHERENT` to make it working correctly, or unmapping the memory is required in any case (see https://github.com/KhronosGroup/MoltenVK/issues/175 - that might be related problem), then it's a bug in MoltenVK.
