### ISSUE TITLE
VK_EXT_transform_feedback: Specifying VK_PIPELINE_STAGE_TRANSFORM_FEEDBACK_BIT_EXT in global mem barriers raises invalid validation errors

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-ValidationLayers#695]
The error I'm seeing is:

```
Dependency 0 is a self-dependency, but specifies stage masks that contain stages not
in the GRAPHICS pipeline. The Vulkan spec states: If srcSubpass is equal to dstSubpass,
srcStageMask and dstStageMask must n ot set any bits that are neither 
VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT, nor one of the graphics pipeline stages (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-
VkSubpassDependency2KHR-srcSubpass-02244)
```

This is seen when defining a self-subpass dependency necessary to separate separate draw call
invocations which are wrapped in begin+end transform feedback calls that use counter buffers.

Analogous error is reported for XFB-specific access masks.

**Comment by jzulauf-lunarg** [comment]
Mask expansion hasn't been updated with spec .  Change under test.

**Comment by jzulauf-lunarg** [comment]
@DominikWitczakAMD  -- push a PR that should address this.

**Comment by jzulauf-lunarg** [comment]
@DominikWitczakAMD I believe I got the second issue you reported.  Please reopen if I didn't.

**Comment by DominikWitczakAMD** [comment]
Still seeing the issues I'm afraid. I've also spotted a similar problem, this time affecting create_renderpass2.

1. The following memory barrier, passed via vkCmdPipelineBarrier(), triggers an error:

![image](https://user-images.githubusercontent.com/17761066/52842357-23631300-30ff-11e9-97ec-f8adc83ed11e.png)

![image](https://user-images.githubusercontent.com/17761066/52842383-3aa20080-30ff-11e9-847b-a80992ed2693.png)

![image](https://user-images.githubusercontent.com/17761066/52842391-45f52c00-30ff-11e9-8ef9-c3b812390fdf.png)

2. The following subpass dependency passed via VkRenderPassCreateInfo2Khr::pDependencies, also triggers an error:

![image](https://user-images.githubusercontent.com/17761066/52842299-f4e53800-30fe-11e9-944d-20ac1d8a1d93.png)

![image](https://user-images.githubusercontent.com/17761066/52842315-fdd60980-30fe-11e9-9bfe-7159108f1bdc.png)

In both cases, access & pipeline stage masks hold bits related to XFB.

**Comment by jzulauf-lunarg** [comment]
@DominikWitczakAMD According to the spec `VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT = 0x04000000,` is only valid in `VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT`.  The `dstStageMask` is set to `VK_PIPELINE_STAGE_TRANSFORM_FEEDBACK_BIT_EXT`.

Unless the spec is wrong the error is correct AFAICT.
