### ISSUE TITLE
VUID-VkRenderingInfo-None-08994 given incorrectly

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/Vulkan-ValidationLayers#6973]
**Environment:**
 - OS: Windows 10
 - GPU and driver version: GTX 2080 546.01
 - SDK or header version if building from repo: 1.3.268.0
 - Options enabled (synchronization, best practices, etc.): validation

**Describe the Issue**

Starting with Vulkan SDK 1.3.268.0 some previously working code started giving this validation error:

> VK ERROR : VALIDATION - Message Id Number: 1299066336 | Message Id Name: VUID-VkRenderingInfo-None-08994
> 	Validation Error: [ VUID-VkRenderingInfo-None-08994 ] Object 0: handle = 0x9c636f20, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x4d6e2de0 | vkCmdBeginRenderingKHR(): pRenderingInfo->renderArea.extent.width is zero. The Vulkan spec states: If VkDeviceGroupRenderPassBeginInfo::deviceRenderAreaCount is 0, renderArea.extent.width must be greater than 0 (https://vulkan.lunarg.com/doc/view/1.3.268.0/windows/1.3-extensions/vkspec.html#VUID-VkRenderingInfo-None-08994)

In this case, I am not passing a `VkDeviceGroupRenderPassBeginInfo `into the pNext chain of `VkRenderingInfoKHR`.  It is the case that the width/height of the renderArea I'm providing is (0,0) but it's not clear to me why that would be a validation error if `VkDeviceGroupRenderPassBeginInfo  `is not provided.

**Expected behavior**

I think this should perhaps be valid?

**Valid Usage ID**
VUID-VkRenderingInfo-None-08994 (and others related to VkDeviceGroupRenderPassBeginInfo in that region)

**Comment by ziga-lunarg** [comment]
That is what the VUID says, if VkDeviceGroupRenderPassBeginInfo::deviceRenderAreaCount is 0, or also if VkDeviceGroupRenderPassBeginInfo is not provided, then renderArea.width and renderArea.height must be greater than 0

**Comment by ziga-lunarg** [comment]
I believe VkDeviceGroupRenderPassBeginInfo::deviceRenderAreaCount being 0 is equal to VkDeviceGroupRenderPassBeginInfo not being included in the pNext chain.

And from this part of the spec:

> If there is an instance of VkDeviceGroupRenderPassBeginInfo included in the pNext chain and its deviceRenderAreaCount member is not 0, then renderArea is ignored, and the render area is defined per-device by that structure.

I gather that the renderArea is ignored if VkDeviceGroupRenderPassBeginInfo  is included in pNext and its deviceRenderAreaCount  is greather than 0. If renderArea is not ignored then width and height must be positive.

**Comment by danginsburg** [comment]
OK, if you are confident it should be an error, then feel free to close the bug.  I was unsure because the code was previously passing validation in SDK 1.3.261.1 and the language in the linked VU is not consistent with for example:

> VUID-VkRenderingInfo-pNext-06077
> If the pNext chain does not contain [VkDeviceGroupRenderPassBeginInfo](https://vulkan.lunarg.com/doc/view/1.3.268.0/windows/1.3-extensions/vkspec.html#VkDeviceGroupRenderPassBeginInfo) or its deviceRenderAreaCount member is equal to 0, renderArea.offset.x must be greater than or equal to 0

Perhaps there should be a spec bug filed to change the language of the VU to include similar text regarding the behavior if VkDeviceGroupRenderPassBeginInfo is not provided.

**Comment by spencer-lunarg** [comment]
for background, this was added from CTS coverage
https://gitlab.khronos.org/vulkan/vulkan/-/issues/3535
https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5972

I think this is just a simple case of Mike didn't see that language when creating the spec PR... I will go back in the spec and unify these error message, but the intent was that the `renderArea` must not be zero, unless you are using Device Groups

**Comment by spencer-lunarg** [comment]
ok, so I realize what happen, mike added the language and then AFTER we had the PR to "consolidate VUs" and that is why the `VUID-VkRenderingInfo-pNext-06077` was made the "correct" way and no one saw the original ...... so just a spec cleanup (internal MR https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6288)
