### ISSUE TITLE
Compute shader local group size not checked.

### ISSUE THREAD

**Issue by nikitablack** [KhronosGroup/Vulkan-ValidationLayers#698]
Hello, I created a compute shader but put the wrong size in the local group size - the value, greater than supported `maxComputeWorkGroupInvocations`. The result is that the pipeline creation failed without validation layer reporting why.

**Comment by mark-lunarg** [comment]
VUID is "features-limits-maxComputeWorkGroupInvocations", pretty sure compute is much less well-developed than graphics all around.

**Comment by locke-lunarg** [comment]
[Pull request #833 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/833)
