### ISSUE TITLE
Questions about latest changes to VUID-vkCmdPipelineBarrier-src/dstAccessMask-06257

### ISSUE THREAD

**Issue by pablode** [KhronosGroup/Vulkan-ValidationLayers#6990]
Hi! Since updating to the latest Vulkan SDK 1.3.268, I'm getting following validation errors:

11-16 15:21:33.877 5b7c [ERROR] Validation Error: [ VUID-vkCmdPipelineBarrier-srcAccessMask-06257 ] Object 0: handle = 0x1ff026580c8, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x235b7e76 | vkCmdPipelineBarrier(): pMemoryBarriers[2].srcStageMask contains pipeline stages VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT|VK_PIPELINE_STAGE_VERTEX_SHADER_BIT|VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT|VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT|VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT|VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT|VK_PIPELINE_STAGE_TRANSFER_BIT|VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR. The Vulkan spec states: If the rayQuery feature is not enabled and a memory barrier srcAccessMask includes VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR, srcStageMask must not include any of the VK_PIPELINE_STAGE_*_SHADER_BIT stages except VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR (https://vulkan.lunarg.com/doc/view/1.3.268.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdPipelineBarrier-srcAccessMask-06257)

11-16 15:21:33.877 5b7c [ERROR] Validation Error: [ VUID-vkCmdPipelineBarrier-dstAccessMask-06257 ] Object 0: handle = 0x1ff026580c8, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xe5ce30b3 | vkCmdPipelineBarrier(): pMemoryBarriers[2].dstStageMask contains pipeline stages VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT|VK_PIPELINE_STAGE_VERTEX_SHADER_BIT|VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT|VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT|VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR. The Vulkan spec states: If the rayQuery feature is not enabled and a memory barrier dstAccessMask includes VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR, dstStageMask must not include any of the VK_PIPELINE_STAGE_*_SHADER_BIT stages except VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR (https://vulkan.lunarg.com/doc/view/1.3.268.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdPipelineBarrier-dstAccessMask-06257)

This leads me to two questions:

* The errors state that VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR is only allowed for the VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR pipeline stage, [backed by the spec](https://vulkan.lunarg.com/doc/view/1.3.268.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdPipelineBarrier-srcAccessMask-06257). However, the [VkAccessFlagBits documentation](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkAccessFlagBits.html#_description) states that the flag may also be used in the VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR pipeline stage. Additionally, table 1 for the synchronization2 access flags lists a bunch more pipeline stages.

* Is the intended solution in this case to split the different pipeline stages with their access masks over multiple pMemoryBarriers?

**Comment by arno-lunarg** [comment]
Hello @pablode 

If the rayQuery feature is disabled, the only types of shaders allowed to access acceleration structures are the ray tracing ones. Since you get `06257`, I assume that the `rayQuery` feature is disabled in your app (?)
Also as you mention `VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR` is allowed, because it is not considered a shader access, so `06257` does not forbid it.

Hope this helps!

**Comment by spencer-lunarg** [comment]
@pablode friendly ping - does the above information help? is `rayQuery` enabled?

**Comment by pablode** [comment]
Thanks for the answers, I now understand that I need a second pipeline barrier specifically for the ray tracing shader stage (with VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR accesses).
