### ISSUE TITLE
Results of accessing private data on a handle that has been deleted seemingly unvalidated?

### ISSUE THREAD

**Issue by ziga-lunarg** [KhronosGroup/Vulkan-ValidationLayers#6993]
We recently encountered a Vulkan application bug where the application was reading private data (`VK_EXT_private_data`) from a destroyed handle (VkDescriptorSetLayout in this case) which was crashing the driver with no validation error reported.

**Comment by spencer-lunarg** [comment]
update: Add PR to check for this, but seems like this is a missing VU, will add to spec
