### ISSUE TITLE
No debug call-back reported if two renderpasses which rasterize to the same attachment are not synchronized

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#7]
**Issue by [DominikWitczakAMD](https://github.com/DominikWitczakAMD) (MIGRATED)**
_Friday Sep 23, 2016 at 13:32 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/973_

----

Consider a command buffer A which does the following:
1. Start a renderpass X
2. Draw stuff.
3. End renderpass X
4. Start a renderpass Y
5. Draw even more stuff
6. End renderpass Y.

Renderpasses X and Y use the same attachment. For this command buffer to be correct, the renderpasses need to be synchronized via an event or external dependency. The problem is ignored by core validation layer.

**Comment by mark-lunarg** [comment]
Moved into tracking issue #72.
