### ISSUE TITLE
Image layout tracking for depth+stencil images at vkCmdEndRenderPass

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#70]
**Issue by [Qining](https://github.com/Qining) (MIGRATED)**
_Thursday Mar 22, 2018 at 02:03 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2506_

----

Looks like there is bug for the layout transition tracking at vkCmdEndRenderPass. The `finalLayout` is not included in the tracking, so that I keep getting error messages from validation layers like:
```
DS(ERROR / SPEC): object: 0x557ab9082cb0 type: 6 msgNum: 6 - Cannot submit cmd buffer using image (0xdc) [sub-resource: aspectMask 0x4 array layer 2, mip level 0], with layout VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL when first use is VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL.

```
I can get rid of the error by using pipeline barrier to switch the layout and change the `finalLayout` from `VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL` to `VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL`, (which is the same layout used in `VkAttachmentReference`) in the attachment description when creating the `VkRenderPass`.

Nothing else changed, so I think there is a problem with `vkCmdEndRenderPass + DepthStencil image layout transition`.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/chrisforbes"><img src="https://avatars1.githubusercontent.com/u/128877?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Friday Mar 23, 2018 at 03:45 GMT_

----

@Qining we do account for the final layout -- this is the (admittedly slightly misnamed) `TransitionFinalSubpassLayouts` call in `core_validation::CmdEndRenderPass.`

Do you have a test case which demonstrates this?

**Comment by karl-lunarg** [comment]
<a href="https://github.com/Qining"><img src="https://avatars0.githubusercontent.com/u/2983685?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Qining](https://github.com/Qining) (MIGRATED)**
_Tuesday Mar 27, 2018 at 15:02 GMT_

----

Thanks for reply, let me see if I can make a test case for this.

**Comment by karl-lunarg** [comment]
Qining seems to no longer be a member.

**Comment by Qining** [comment]
I'm still here. Maybe we can have this issue closed for now, until I have a piece of example code. Thanks

**Comment by karl-lunarg** [comment]
OK, thanks for responding!   I can't seem to assign the issue to you.  I think it is because of the issue migration, which required me to be the owner of all migrated issues.  We'll look forward to you making a new issue when you have that example.  Thanks!
