### ISSUE TITLE
Missing `VkImage` object info in QueueSubmit synchronization validation error

### ISSUE THREAD

**Issue by glebov-andrey** [KhronosGroup/Vulkan-ValidationLayers#7010]
**Environment:**
 - VVL revision: `7adefb0aeb9034bb791437afb7ad447e0cbe5931` (current `main`)
 - Options enabled: synchronization with `VALIDATION_CHECK_ENABLE_SYNCHRONIZATION_VALIDATION_QUEUE_SUBMIT`

**Describe the Issue**

When `VALIDATION_CHECK_ENABLE_SYNCHRONIZATION_VALIDATION_QUEUE_SUBMIT` is enabled I'm getting validation errors about WAW hazards between `SYNC_IMAGE_LAYOUT_TRANSITION` usages, but the error message doesn't include the `VkImage`'s handle or debug name.

Here is an example message:
`Validation Error: [ SYNC-HAZARD-WRITE-AFTER-WRITE ] Object 0: handle = 0x1f69f5feb00, name = Graphics queue, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0x5c0ec5d6 | vkQueueSubmit2():  Hazard WRITE_AFTER_WRITE for entry 0, VkCommandBuffer 0x1f6b5fb65b0[], Recorded access info (recorded_usage: SYNC_IMAGE_LAYOUT_TRANSITION, command: vkCmdPipelineBarrier2, seq_no: 1, reset_no: 1). Access info (prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION, write_barriers: 0, ).`

The `VkDebugUtilsMessengerCallbackDataEXT` also contains only one object - the `VkQueue`.

Also it looks like there's a formatting bug in `Access info` with the trailing `, `.

**Expected behavior**

The message (and callback data) contains the object info for the `VkImage` or `VkBuffer` which was specified in the pipeline barrier.

**Additional context**

<details>
<summary>Stack trace</summary>

```
[VkLayer_khronos_validation.dll] debug_log_msg(const _debug_report_data *, unsigned int, const LogObjectList &, const char *, const char *, const char *) logging.cpp:211
[VkLayer_khronos_validation.dll] LogMsg(const _debug_report_data *, unsigned int, const LogObjectList &, const Location *, basic_string_view<char, std::char_traits<char> >, const char *, char *) logging.cpp:466
[VkLayer_khronos_validation.dll] ValidationObject::LogError(basic_string_view<char,std::char_traits<char> >,const LogObjectList &,const Location &,const char *,...) chassis.h:2325
[VkLayer_khronos_validation.dll] ReplayState::DetectFirstUseHazard(const sparse_container::range<unsigned __int64> &) sync_validation.cpp:2765
[VkLayer_khronos_validation.dll] SyncOpPipelineBarrier::ReplayValidate(ReplayState &, unsigned long long) sync_validation.cpp:7142
[VkLayer_khronos_validation.dll] ReplayState::ValidateFirstUse() sync_validation.cpp:2787
[VkLayer_khronos_validation.dll] QueueBatchContext::DoQueueSubmitValidate(const SyncValidator &, QueueSubmitCmdState &, const VkSubmitInfo2 &) sync_validation.cpp:4571
[VkLayer_khronos_validation.dll] SyncValidator::ValidateQueueSubmit(VkQueue_T *, unsigned int, const VkSubmitInfo2 *, VkFence_T *, const ErrorObject &) sync_validation.cpp:8280
[VkLayer_khronos_validation.dll] SyncValidator::PreCallValidateQueueSubmit2(VkQueue_T *, unsigned int, const VkSubmitInfo2 *, VkFence_T *, const ErrorObject &) sync_validation.cpp:8340
[VkLayer_khronos_validation.dll] vulkan_layer_chassis::QueueSubmit2(VkQueue_T *, unsigned int, const VkSubmitInfo2 *, VkFence_T *) chassis.cpp:5087
```

</details>

**Comment by artem-lunarg** [comment]
@glebov-andrey In the example with a comma formatting, did recorded command buffer use secondary command buffer calls, like, `vkCmdExecuteCommands`?

**Comment by glebov-andrey** [comment]
@artem-lunarg No, this is actually the exact same case as #7024.

**Comment by artem-lunarg** [comment]
Added image/buffer handles from the pipeline barrier commands to the error message.

**Comment by glebov-andrey** [comment]
Thanks! This is a big improvement.
Except now pipeline barrier calls with more than 255 objects assert in debug builds and cause UB (probably) in release builds.
Here's a stack trace:
```
[VkLayer_khronos_validation.dll] small_vector<NamedHandle, 1, unsigned char>::emplace_back<const VulkanTypedHandle &>(const VulkanTypedHandle &) custom_containers.h:284
[VkLayer_khronos_validation.dll] ResourceCmdUsageRecord::AddHandle<const VulkanTypedHandle &>(const VulkanTypedHandle &) sync_commandbuffer.h:127
[VkLayer_khronos_validation.dll] CommandBufferAccessContext::AddHandle<const VulkanTypedHandle &>(unsigned long long, const VulkanTypedHandle &) sync_commandbuffer.h:331
[VkLayer_khronos_validation.dll] SyncOpPipelineBarrier::Record(CommandBufferAccessContext *) sync_op.cpp:342
[VkLayer_khronos_validation.dll] CommandBufferAccessContext::RecordSyncOp(std::shared_ptr<SyncOpBase> &&) sync_commandbuffer.cpp:883
[VkLayer_khronos_validation.dll] CommandBufferAccessContext::RecordSyncOp<SyncOpPipelineBarrier, const enum vvl::Func &, SyncValidator &, unsigned int, const VkDependencyInfo &>(const vvl::Func &, SyncValidator &, unsigned int &&, const VkDependencyInfo &) sync_commandbuffer.h:346
[VkLayer_khronos_validation.dll] SyncValidator::PreCallRecordCmdPipelineBarrier2(VkCommandBuffer_T *, const VkDependencyInfo *, const RecordObject &) sync_validation.cpp:524
[VkLayer_khronos_validation.dll] vulkan_layer_chassis::CmdPipelineBarrier2(VkCommandBuffer_T *, const VkDependencyInfo *) chassis.cpp:5049
```
The assertion in question is `assert(size_ < kMaxCapacity)`, and it looks like the solution is just to change `size_type` to something larger than `uint8_t` - I would guess `uint32_t` is enough.
For reference, over 255 image barriers comes up when uploading a lot of images in a batch and then transferring all of them from a transfer queue to a graphics queue.
