### ISSUE TITLE
Validate builtin interface block match

### ISSUE THREAD

**Issue by chrisforbes** [KhronosGroup/Vulkan-ValidationLayers#702]
CTS has accidentally had mismatches in builtin interface between VS output and GS input. Need to validate that the block declarations are equivalent.

**Comment by chrisforbes** [comment]
@asuonpaa any interest in doing this?

**Comment by asuonpaa** [comment]
@chrisforbes can you assign the task for me?

**Comment by chrisforbes** [comment]
@mark-lunarg can you add @asuonpaa to a team that allows bug assignment?

**Comment by mark-lunarg** [comment]
@chrisforbes, I added @asuonpaa as a collaborator and (I believe) an invite link was sent to him.  Once that clears I think we'll be able to assign issues to him.

**Comment by asuonpaa** [comment]
I've accepted the invitation. I wish I could just assign myself when needed :)

**Comment by chrisforbes** [comment]
@asuonpaa that *should* work now... I've assigned this batch of issues to you though.
