### ISSUE TITLE
possible false positives on multiple VUIDs when using VK_EXT_swapchain_maintenance1 

### ISSUE THREAD

**Issue by AlexRouSg** [KhronosGroup/Vulkan-ValidationLayers#7025]
**Environment:**
 - OS:  Windows 10
 - GPU and driver version: NVIDIA GeForce GTX 1080 Ti  driver: 546.01
 - SDK or header version if building from repo: 1.3.268.0
 - Options enabled (synchronization, best practices, etc.):

**Describe the Issue**

When using VK_EXT_swapchain_maintenance1 and waiting on the fence provided to VkSwapchainPresentFenceInfoEXT I'd expect that the fence would be in a latter point in time than a fence provided to VkQueeuSubmit/2.

However validation doesn't seem to take into account the fence provided to VkSwapchainPresentFenceInfoEXT for "in use" checks.
i.e. there were no fence provided to VkQueeuSubmit/2

**Expected behavior**

These and likely other similar validation messages doesn't trigger

**Valid Usage ID**
VUID-vkResetCommandPool-commandPool-00040
VUID-vkBeginCommandBuffer-commandBuffer-00049
VUID-vkQueueSubmit2-commandBuffer-03875

**Comment by artem-lunarg** [comment]
@AlexRouSg That's correct, currently we don't have synchronization logic for `VkSwapchainPresentFenceInfoEXT`'s fence.

I'd like to write a test to reproduce the issue. I have few questions:
a) Does `vkQueuePresent` wait for `vkQueueSubmit` using a semaphore?
b) Is the idea of the above scenario to use `VkSwapchainPresentFenceInfoEXT` fence instead of `vkQueueSubmit` fence to determine that submitted workload has completed?

**Comment by artem-lunarg** [comment]
I can reproduce the issue assuming the answers to the above questions are both yes.

Added repro case: https://github.com/artem-lunarg/Vulkan-ValidationLayers/commit/b2f3ffea90d6bc39b60463aae9a5722f148695aa

**Comment by AlexRouSg** [comment]
yup both are true, I also don't see how this could be correct without a semaphore between vkQueueSubmit and vkQueuePresent

**Comment by artem-lunarg** [comment]
@ShabbyX also reported this.

**Comment by ShabbyX** [comment]
Reproducible with https://github.com/KhronosGroup/Vulkan-Samples/pull/617 FYI

**Comment by artem-lunarg** [comment]
@AlexRouSg the latest code fixes our repro case and similar issue in Vulkan-Samples, but please re-open if it does not fix your use case. The fix won't be included in the next SDK (missed release deadline) but will be included in the SDK after that, and of course available in the latest code.
