### ISSUE TITLE
FS output interface validation should consider alphaToCoverage state

### ISSUE THREAD

**Issue by chrisforbes** [KhronosGroup/Vulkan-ValidationLayers#703]
Alpha to coverage uses location 0 alpha component.

- When using alpha to coverage, we should not warn on a "useless" declaration of this output.
- When using alpha to coverage, if location 0 alpha component is *not* declared, that should be an error.

**Comment by chrisforbes** [comment]
@asuonpaa any interest in doing this?

**Comment by asuonpaa** [comment]
Sure, can someone assign the task for me?
