### ISSUE TITLE
Compilation error due to vk_layer_settings_ext.h removed

### ISSUE THREAD

**Issue by aabdolrashidi** [KhronosGroup/Vulkan-ValidationLayers#7079]
The header `vk_layer_settings_ext.h` has been removed in the following commit: https://github.com/KhronosGroup/Vulkan-Utility-Libraries/commit/2feac587338c7e1b631b2ef9bd6e894d7ad7f56d

However, some files in `Vulkan-ValidationLayers` still use this header, such as:
* `layers/vulkan/generated/stateless_validation_helper.cpp`
* `tests/framework/layer_validation_tests.h`
* `scripts/generators/stateless_validation_helper_generator.py`

This can lead to compilation errors similar to the following:
```
.../stateless_validation_helper.cpp:30:10: fatal error: 'vulkan/layer/vk_layer_settings_ext.h' file not found
```
CC: @mikes-lunarg @christophe-lunarg

**Comment by mikes-lunarg** [comment]
This is fixed in #7075

**Comment by spencer-lunarg** [comment]
headers merged, should be fixed now

**Comment by aabdolrashidi** [comment]
Thanks for the fix! The error no longer appears after the merge.
