### ISSUE TITLE
False positive for image view type of dynamically unused descriptors

### ISSUE THREAD

**Issue by Cyphall** [KhronosGroup/Vulkan-ValidationLayers#7102]
**Environment:**
 - OS: Windows 11
 - GPU: RTX 3070
 - SDK version: 1.3.268.0, with validation layers manually built from commit 55a016893749388c61d1bd4359b6b4b661169917
 - Options enabled: eBestPractices, eSynchronizationValidation, eGpuAssistedReserveBindingSlot, eGpuAssisted

**Describe the Issue**

I use a large descriptor binding array with descriptor indexing to simulate bindless textures.
In this descriptor binding array, I store both cubemap images (for skyboxes) and regular 2D images (for materials).

My material lighting shader may or may not sample 2D textures from this descriptor binding, depending on a signed integer index passed via an uniform buffer (-1 means "use a predefined value instead of sampling a texture").

In my test scene, I have a skybox (cubemap image stored at index 0) and a rendered object which uses a textureless material (all texture indices at -1).
In this scene, no texture read actually happen in the material lighting shader.

However, I am getting the following validation error:

> Validation Error: [ VUID-vkCmdDraw-viewType-07752 ] Object 0: handle = 0xb9181f0000000029, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; Object 1: handle = 0xd22e030000001406, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x73ed4ff5 | vkCmdDraw():  the descriptor (VkDescriptorSet 0xb9181f0000000029[], binding 0, index 0) ImageView type is VK_IMAGE_VIEW_TYPE_CUBE but the OpTypeImage has (Dim = 2D) and (Arrayed = 0). The Vulkan spec states: If a VkImageView is accessed as a result of this command, then the image view's viewType must match the Dim operand of the OpTypeImage as described in Instruction/Sampler/Image View Validation (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdDraw-viewType-07752)

This validation error would be correct if I was actually sampling a texture from the descriptor set. However, this is not the case.

Note that this issue does **not** happen with the validation layers bundled with SDK 1.3.268.0.

**Expected behavior**

No validation error, since the cubemap at index 0 is not sampled from in the material lighting shader.

**Valid Usage ID**
VUID-vkCmdDraw-viewType-07752

**Comment by spencer-lunarg** [comment]
or at least seeing a SPIR-V file where this happens would be helpful to see why determined it was "accessed"

**Comment by Cyphall** [comment]
I will try to give you a gfxreconstruct trace this evening.
In the meantime, you can view the mentioned lighting shader [here](https://github.com/Cyphall/Cyph3D/blob/903e695ffad4e74f582dc6671782b5213dff8cb9/resources/shaders/internal/lighting/lighting.frag#L396C67-L396C67).

**Comment by spencer-lunarg** [comment]
> Note that this issue does not happen with the validation layers bundled with SDK 1.3.268.0.

I would assume this issue was the result of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6883

----

(for my records) the `vec3 albedo = u_objectUniforms.albedoIndex >= 0 ? texture(u_textures[u_objectUniforms.albedoIndex], texCoords).rgb : u_objectUniforms.albedoValue;` turns into the following SPIR-V

![image](https://github.com/KhronosGroup/Vulkan-ValidationLayers/assets/115671160/48dc6929-6fcb-4251-86ef-a90964d210b9)

----

I think the issue is before we ignored the `%1048 = OpAccessChain %101 %u_textures %1047` call before because we didn't know what it was indexing, but now the `GPU Assisted Validation` (GPU-AV) tracks that, but it still shouldn't be printing anything unless that path is being taken

**Comment by Cyphall** [comment]
Any news on this?
It would be nice to not have this bug in the next SDK release.

**Comment by jeremyg-lunarg** [comment]
This is back to the top of my stack. I was able to reproduce the error with your capture but couldn't find anything obvious on the first pass.

**Comment by jeremyg-lunarg** [comment]
@Cyphall a couple of questions:

1.  Is there anything special I need to do to reproduce the issue other than build Cyph3D.exe from your master branch and run it? I don't see any GPU-AV errors when I do this. However I'm on an RTX2080 and it looks like you have an RTX3070.
2. Do you still get the GPU-AV error if you turn off sync validation and best practices?

**Comment by Cyphall** [comment]
@jeremyg-lunarg 

1. No it should work with these steps.
Note that I do not enable validation in Release builds, so you either need to run in debug or override validation settings with the Vulkan Configurator.
2. Yes. I tested with the "GPU-Assisted" preset in the Vulkan Configurator and I still get these validation errors with the latest commit of the Validation Layers (fd2d689).

**Comment by Cyphall** [comment]
My `master` branch now has GPUAV disabled even in debug builds so you will have to use the Vulkan Configurator to enable it back

**Comment by Cyphall** [comment]
Thank you!
