### ISSUE TITLE
vkRegisterDisplayEventEXT reporting display was created, allocated or retrieved from VkPhysicalDevice 0x0

### ISSUE THREAD

**Issue by jparimaa** [KhronosGroup/Vulkan-ValidationLayers#7123]
**Environment:**
 - OS: Ubuntu 20.04.6 LTS aarch64
 - GPU and driver version: 
 - SDK or header version if building from repo: https://github.com/KhronosGroup/Vulkan-ValidationLayers/releases/tag/v1.3.267 and later
 - Options enabled (synchronization, best practices, etc.): See the attached source code
 - Source: [vkcube.zip](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/13633056/vkcube.zip)
 
**Describe the Issue**

Calling `vkRegisterDisplayEventEXT` prints a warning that says

> ERROR : VALIDATION - Message Id Number: -1462709463 | Message Id Name: VUID-vkRegisterDisplayEventEXT-commonparent
> 	Validation Error: [ VUID-vkRegisterDisplayEventEXT-commonparent ] Object 0: handle = 0xaaaaaaef5c30, type = VK_OBJECT_TYPE_INSTANCE; Object 1: handle = 0xaaaaac9771d0, type = VK_OBJECT_TYPE_PHYSICAL_DEVICE; | MessageID = 0xa8d0d329 | vkRegisterDisplayEventEXT(): display (VkDisplayKHR 0xfab64d0000000002) was created, allocated or retrieved from VkPhysicalDevice 0x0[], but command is using (or its dispatchable parameter is associated with) VkPhysicalDevice 0xaaaaac9771d0[]. The Vulkan spec states: Both of device, and display must have been created, allocated, or retrieved from the same VkPhysicalDevice (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkRegisterDisplayEventEXT-commonparent)
> 
> 	Objects - 2
> 		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 0xaaaaaaef5c30
> 		Object[1] - VK_OBJECT_TYPE_PHYSICAL_DEVICE, Handle 0xaaaaac9771d0

I think display (VkDisplayKHR 0xfab64d0000000002) was NOT created with VkPhysicalDevice 0x0

**Expected behavior**

I suspect this might be a false positive. I wasn't expecting an error message.

**Additional context**

Important part of the source code:
```
PFN_vkRegisterDisplayEventEXT vkRegisterDisplayEventEXT = (PFN_vkRegisterDisplayEventEXT)vkGetInstanceProcAddr(demo->inst, "vkRegisterDisplayEventEXT");
if (vkRegisterDisplayEventEXT == NULL) {
    printf("Could not get instance function pointer vkRegisterDisplayEventEXT\n");
    abort();
}

VkFence vsyncFence;
VkDisplayEventInfoEXT eventInfo;
eventInfo.sType = VK_STRUCTURE_TYPE_DISPLAY_EVENT_INFO_EXT;
eventInfo.pNext = NULL;
eventInfo.displayEvent = VK_DISPLAY_EVENT_TYPE_FIRST_PIXEL_OUT_EXT;
VkResult registerResult = vkRegisterDisplayEventEXT(demo->device, g_display, &eventInfo, NULL, &vsyncFence);
if (registerResult != VK_SUCCESS) {
    printf("Failed in vkRegisterDisplayEventEXT, result = %d\n", registerResult);
    abort();
}
vkDestroyFence(demo->device, vsyncFence, NULL);
```

Command line arguments used when executing the attached source
`--validate --present_mode VK_PRESENT_MODE_FIFO_KHR`

The system was Nvidia Orin AGX running in display mode (ie. no desktop manager).

The issue did not seem to happen in v1.3.266 but appeared in v1.3.267 and later.

**Comment by spencer-lunarg** [comment]
the issue is likely the fact `VkDisplayKHR` is not created, but rather "acquired" (like a `VkQueue`) and the state tracking logic is not capturing it correctly

> The issue did not seem to happen in v1.3.266 but appeared in v1.3.267 and later.

There was some recent re-working of the Object Tracker class (where this is checked) so likely the lack of `VK_KHR_displayVK_KHR_display` WSI  tests allowed for this regression

**Comment by spencer-lunarg** [comment]
awww, wow @artem-lunarg (since you helped in this area of the code)

so `VUID-vkRegisterDisplayEventEXT-commonparent` and ` VUID-vkDisplayPowerControlEXT-commonparent` are the only 2 functions where we use a PhysicalDevice-based handle (`VkDisplayKHR`) in a device function call

we have the code

```
// Anonymous object validation does not check parent, only that the object exists
    if (wrong_parent_vuid == kVUIDUndefined) {
        return skip;
    }
    ```
    
but in this case, we want to skip if its these 2 VUs too (if the objects match)
