### ISSUE TITLE
syncval: Set VALIDATION_CHECK_ENABLE_SYNCHRONIZATION_VALIDATION_QUEUE_SUBMIT to be on by default

### ISSUE THREAD

**Issue by jeremyg-lunarg** [KhronosGroup/Vulkan-ValidationLayers#7127]
Now that this feature has been implemented for several months and SDK releases, it seems like it should be on by default.

**Comment by jeremyg-lunarg** [comment]
FYI @danginsburg

**Comment by jzulauf-lunarg** [comment]
Should change to form `VALIDATION_CHECK_DISABLE_...` shouldn't it?

**Comment by jeremyg-lunarg** [comment]
> Should change to form `VALIDATION_CHECK_DISABLE_...` shouldn't it?

I suppose.
