### ISSUE TITLE
Windows-AMD 32-bit failures

### ISSUE THREAD

**Issue by lunarpapillo** [KhronosGroup/Vulkan-ValidationLayers#7144]
**LunarG CI** currently only tests the `Debug64` configuration for **Windows-AMD** machines, on the assumption that 32-bit was adequately tested on the **Windows-NVIDIA** platforms.  This appears to not be case, as we found 32-bit **Windows-AMD** failures on `main` (`v1.3.273-40-g4bd62a370`) during routine SDK integration loader testing.  `Release32` and `Debug32` fail identically (but, as they crash, it's possible there are deviations that we didn't test enough to discover).

`Release32` failure: http://tcubuser:8080/view/Manual/job/manual-Vulkan-ValidationLayers/75/console
```
ERROR: vvl: FAIl test NegativeGpuAVBufferDeviceAddress.StorageBufferOOB
------------------------------------------------------------
[ RUN      ] NegativeGpuAVBufferDeviceAddress.StorageBufferOOB
C:\j\mz3\Vulkan-ValidationLayers\tests\framework\error_monitor.cpp(239): error: Failed
Did not receive expected error 'VUID-vkCmdDispatch-None-08613'

[  FAILED  ] NegativeGpuAVBufferDeviceAddress.StorageBufferOOB (3764 ms)
------------------------------------------------------------
ERROR: vvl: CRASH - test PositiveGpuAVBufferDeviceAddress.Store never completed
------------------------------------------------------------
[ RUN      ] PositiveGpuAVBufferDeviceAddress.Store
C:\j\mz3\Vulkan-ValidationLayers\tests\unit\gpu_av_buffer_device_address_positive.cpp(152): error: Value of: output == 0xca7
  Actual: false
Expected: true

------------------------------------------------------------
```

`Debug32` failure: http://tcubuser:8080/view/Manual/job/manual-Vulkan-ValidationLayers/76/console
```
ERROR: vvl: FAIl test NegativeGpuAVBufferDeviceAddress.StorageBufferOOB
------------------------------------------------------------
[ RUN      ] NegativeGpuAVBufferDeviceAddress.StorageBufferOOB
C:\j\mz0\Vulkan-ValidationLayers\tests\framework\error_monitor.cpp(239): error: Failed
Did not receive expected error 'VUID-vkCmdDispatch-None-08613'

[  FAILED  ] NegativeGpuAVBufferDeviceAddress.StorageBufferOOB (3168 ms)
------------------------------------------------------------
ERROR: vvl: CRASH - test PositiveGpuAVBufferDeviceAddress.Store never completed
------------------------------------------------------------
[ RUN      ] PositiveGpuAVBufferDeviceAddress.Store
C:\j\mz0\Vulkan-ValidationLayers\tests\unit\gpu_av_buffer_device_address_positive.cpp(152): error: Value of: output == 0xca7
  Actual: false
Expected: true

------------------------------------------------------------
```

**Comment by lunarpapillo** [comment]
When 32-bit is running on **Windows-AMD**, we'll add the configuration to CI.  (We may want to do a full 32-bit blacklist exercise,  if fixing just these two tests doesn't allow testing to run and pass.)

**Comment by spencer-lunarg** [comment]
the `StorageBufferOOB` test was refactored awhile ago and seems we have decided that device buffer address on 32-bit is not something we expect to ever be used (the extension is designed for 64-bit system in mind, like rtx)
