### ISSUE TITLE
syncval: Better debug info for errors detected during vkQueueSubmit()

### ISSUE THREAD

**Issue by jeremyg-lunarg** [KhronosGroup/Vulkan-ValidationLayers#7159]
It is turning out to be difficult to find the source of synchronization errors that are detected during vkQueueSubmit(), especially in applications with very large command buffers with many barriers.

It would be helpful if either the call stack for the command or the [debug utilities command buffer debug regio](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdBeginDebugUtilsLabelEXT.html)n label was available for the command was saved in the tag info so that it was available at submission time. 

This sort of feature would also be useful for other parts of validation like GPU-AV, but right now it is primarily needed in syncval.

**Comment by jeremyg-lunarg** [comment]
FYI @danginsburg

**Comment by artem-lunarg** [comment]
@jeremyg-lunarg the feature is in. Let me know if any feedback. Feel free to close if it works for you.
FYI @danginsburg

**Comment by artem-lunarg** [comment]
@jzulauf-lunarg noticed that reporting debug regions from previous submissions is not implemented. Going to try to handle this use case too.
