### ISSUE TITLE
Question: Debug callback used to log all create/destroyed objects with their address, no longer does?

### ISSUE THREAD

**Issue by comeradealexi** [KhronosGroup/Vulkan-ValidationLayers#717]
I recently updated my Vulkan SDK on Windows to the latest version (1.1.97.0) and I notice this extra debug information is no longer provided through the callbacks and I can't figure out how to access it.

I found it useful when I got validation errors as I was able to match the image address from the validation error back to the log where it was created.

Is there a way to re-enable this feature or am I just missing something?

I've still got all the standard validation layers enabled etc, nothing has changed from my code point of view but I'm just getting far less information now through my debug callbacks.

I've just rolled back to 1.1.92.1 where it worked and I'm getting messages such as the following, which I no longer get in 1.1.97.0:
UNASSIGNED-ObjectTracker-Info
OBJ[0xff1] : CREATE VK_DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_SET_EXT object 0x1cba1dfbf60

Any help would be greatly appreciated.

**Comment by mark-lunarg** [comment]
@comeradealexi, looked at this and it seems like the messages *should* still be going out -- are you using the `VK_EXT_debug_report `extension or the `VK_EXT_debug_report `extension?

**Comment by comeradealexi** [comment]
I am using VK_EXT_debug_utils.
