### ISSUE TITLE
Debug report callback doesn't get destroyed from Vulkan Loader

### ISSUE THREAD

**Issue by ilkkasaa** [KhronosGroup/Vulkan-ValidationLayers#718]
There is an issue while destroying the debug report callback. The problem is that when a debug report callback is created in Vulkan Loader (in `terminator_CreateDebugReportCallbackEXT` function, file `debug_utils.c`) the Loader stores the address of the created callback, but once the callback is created the Validation Layers seems to somehow “wrap” the address and therefore change the value of the `pCallback` pointer (= address of the callback). When destroying the callback, the Loader fails to destroy it (in function `util_DestroyDebugReportCallback`) because it gets the “wrapped” address of the callback but expects to get the actual address to identify the callback to be destroyed.

Because the callback doesn’t get destroyed from the Loader, the Loader creates some debug messages even after the callback should be destroyed. This is a major problem in Vulkan CTS because it always crashes when shutting down if the Validation Layers are enabled.

Looks like this issue has existed since the commits from the pull request https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/505

**Comment by jzulauf-lunarg** [comment]
@mark-lunarg @lenny-lunarg -- looks like a loader-vvl interface disconnect.  Perhaps some change in how the chassis is handling this?

**Comment by mark-lunarg** [comment]
Some debugging seems to point to a dangling callback pointer in the Loader.  Created [Loader Issue #149](https://github.com/KhronosGroup/Vulkan-Loader/issues/149) to track this issue in that repo.  Thanks @ilkkasaa.
