### ISSUE TITLE
Unnecessary space in pCreateInfos reference

### ISSUE THREAD

**Issue by taniwha** [KhronosGroup/Vulkan-ValidationLayers#7180]
In the following message, the leading space before the 0 in `pCreateInfos[ 0]` is unnecessary and could case message parsers problems.

> validation layer: warning: Validation Warning: [ UNASSIGNED-BestPractices-SpirvDeprecated_WorkgroupSize ] Object 0: handle = 0x7fffed076150, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7bc61184 | vkCreateComputePipelines(): pCreateInfos[ 0] is using the Workgroup built-in which SPIR-V 1.6 deprecated. The VK_KHR_maintenance4 extension exposes a new LocalSizeId execution mode that should be used instead.

**Comment by spencer-lunarg** [comment]
confirmed was fixed from the 1.3.261 to 1.3.268 SDK
