### ISSUE TITLE
#7129 breaks dynamic rendering examples

### ISSUE THREAD

**Issue by RYDB3RG** [KhronosGroup/Vulkan-ValidationLayers#7193]
Enabling sync checks with #7129 or newer breaks [Vulkan-Samples/tree/main/samples/extensions/dynamic_rendering](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/samples/extensions/dynamic_rendering) or [examples/dynamicrendering](https://github.com/SaschaWillems/Vulkan/tree/master/examples/dynamicrendering) with `SYNC-HAZARD-WRITE-AFTER-READ` issues:

    [error] [framework\core\instance.cpp:50] 929810911 - SYNC-HAZARD-WRITE-AFTER-READ: Validation Error: 
    [ SYNC-HAZARD-WRITE-AFTER-READ ] Object 0: handle = 0x267e54b1f30, type = VK_OBJECT_TYPE_QUEUE; | 
    MessageID = 0x376bc9df | vkQueueSubmit():  Hazard WRITE_AFTER_READ for entry 0, VkCommandBuffer 
    0x267edcc47b0[], Submitted access info (submitted_usage: SYNC_IMAGE_LAYOUT_TRANSITION, command: 
    vkCmdPipelineBarrier, seq_no: 1, VkImage 0xec4bec000000000b[], reset_no: 1). Access info 
    (prior_usage: SYNC_PRESENT_ENGINE_SYNCVAL_PRESENT_ACQUIRE_READ_SYNCVAL, read_barriers: 
    VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT|VK_PIPELINE_STAGE_2_BOTTOM_OF_PIPE_BIT, , batch_tag: 
    15, vkAcquireNextImageKHR aquire_tag:15: VkSwapchainKHR 0xcfef35000000000a[], image_index: 0image: 
    VkImage 0xec4bec000000000b[]).

**Comment by SaschaWillems** [comment]
Thanks, will fix this. Also pinging @gpx1000 as Holochip did the Khronos sample.
