### ISSUE TITLE
PVRTC formats are treated as invalid on non PowerVr hardware

### ISSUE THREAD

**Issue by ilyachastikov** [KhronosGroup/Vulkan-ValidationLayers#7196]
**Environment:**
 - OS: windows 11 
 - GPU and driver version: GeForce RTX 4090, 546.33 
 - SDK or header version if building from repo: 1.3.268
 - Options enabled (synchronization, best practices, etc.): -

**Describe the Issue**

When invoke "vkGetPhysicalDeviceFormatProperties" formats from VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG (1000054000) to VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG(1000054007) are treated as invalid.

**Expected behavior**

These formats are unsupported on this hardware but must be valid for checking of its support.

**Valid Usage ID**
[VUID-vkGetPhysicalDeviceFormatProperties-format-parameter]

**Additional context**

<details>
<summary>code or terminal output</summary>

```sh
# callstacks, crashes, etc.
# EX:
[VUID-vkGetPhysicalDeviceFormatProperties-format-parameter] : Validation Error: [ VUID-vkGetPhysicalDeviceFormatProperties-format-parameter ] | MessageID = 0x4addcb92 | vkGetPhysicalDeviceFormatProperties(): format (1000054000) does not fall within the begin..end range of the core VkFormat enumeration tokens and is not an extension added token. The Vulkan spec states: format must be a valid VkFormat value (https://vulkan.lunarg.com/doc/view/1.3.268.0/windows/1.3-extensions/vkspec.html#VUID-vkGetPhysicalDeviceFormatProperties-format-parameter) (1256049554)..
```

</details>

**Comment by spencer-lunarg** [comment]
this error occurs because you don't have the `VK_IMG_format_pvrtc` enabled.

Without enabling an extensions, the use of extended enums (such as `VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG`) are invalid according the spec

**Comment by spencer-lunarg** [comment]
note, while most drivers will just handle `vkGetPhysicalDeviceFormatProperties` ok, some drivers (at least one older Android I am aware of)  will crash if given a `VkFormat` it doesn't know about

**Comment by spencer-lunarg** [comment]
> These formats are unsupported on this hardware but must be valid for checking of its support.

By not having the extension, it is already known they are not supported, same with other formats added from extensions

**Comment by ilyachastikov** [comment]
Thanks for answer.
