### ISSUE TITLE
`JSON_LIBRARY_PATH` doesn't match the path of the DLL when building on MSYS2

### ISSUE THREAD

**Issue by Martysh12** [KhronosGroup/Vulkan-ValidationLayers#7213]
## Environment
 - System: Windows, MSYS2
 - Toolchain: `mingw-w64-x86_64`

## Description
`library_path`'s value in `VkLayer_khronos_validation.json` does not match the actual path of the library:
 - `"library_path": ".\\VkLayer_khronos_validation.dll"`
 - The actual filename of the library: `libVkLayer_khronos_validation.dll`

This causes Vulkan to complain about `VK_ERROR_LAYER_NOT_PRESENT` when the layer is clearly there, its JSON just has the wrong library path.

## Possible causes
1. These lines tell CMake what to put in `library_path`. Perhaps it is possible to add a condition that tests for MSYS2?
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/98dea769721b40ed5402b35a84867f180d8955ef/layers/CMakeLists.txt#L390-L396

2. These lines change target properties based on the system. Perhaps it is possible to add a condition that removes the `lib` prefix on MSYS2?
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/98dea769721b40ed5402b35a84867f180d8955ef/layers/CMakeLists.txt#L313-L328

**Comment by spencer-lunarg** [comment]
Thanks for bringing this up, unfortunately I don't think anyone I know has a MINGW setup to test any chance,  I would be happy with a PR, otherwise I fear this issue will just sit and get stale

I believe loader removes `lib` from prefix, so it created `vulkan-1.dll` and maybe VVL should do the same

**Comment by spencer-lunarg** [comment]
update: @charles-lunarg will try and give a crack at a PR :pray:

**Comment by spencer-lunarg** [comment]
@Martysh12 could you confirm https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7220 fixes this problem
