### ISSUE TITLE
VK_EXT_shader_object and VK_EXT_descriptor_buffer are incompatible

### ISSUE THREAD

**Issue by evopen** [KhronosGroup/Vulkan-ValidationLayers#7233]
**Environment:**
 - OS: Linux
 - GPU and driver version: NVIDIA RTX 4080 545.29.06
 - SDK or header version if building from repo: validation layer 0e381678018f858395770d8ddd320af499006628, header 1.3.270
 - Options enabled (synchronization, best practices, etc.):

**Describe the Issue**

When using shader_object with descriptor_buffer extensions, descriptor is bounded by `vkCmdSetDescriptorBufferOffsetsEXT`. Validation reports `VkShaderEXT 0xd10d270000000018[fragment] uses set #0 but that set is not bound`.

**Expected behavior**

Validation layer will not report error.

**Valid Usage ID**
```
VUID-vkCmdDraw-None-08600(ERROR / SPEC): msgNum: 1198051129 - Validation Error: [ VUID-vkCmdDraw-None-08600 ] Object 0: handle = 0x8ec9ca0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0xd10d270000000018, name = fragment, type = VK_OBJECT_TYPE_SHADER_EXT; | MessageID = 0x4768cf39 | vkCmdDraw():  VkShaderEXT 0xd10d270000000018[fragment] uses set #0 but that set is not bound. The Vulkan spec states: For each set n that is statically used by a bound shader, a descriptor set must have been bound to n at the same pipeline bind point, with a VkPipelineLayout that is compatible for set n, with the VkPipelineLayout used to create the current VkPipeline or the VkDescriptorSetLayout array used to create the current VkShaderEXT , as described in Pipeline Layout Compatibility (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdDraw-None-08600)
    Objects: 2
        [0] 0x8ec9ca0, type: 6, name: NULL
        [1] 0xd10d270000000018, type: 1000482000, name: fragment
```

**Additional context**

It seems that validation code path for shader object did not take descriptor buffer into account, unlike the pipeline code path.

**Comment by spencer-lunarg** [comment]
was able to reproduce, the issue is `VkPipeline` objects are created with `VK_PIPELINE_CREATE_DESCRIPTOR_BUFFER_BIT_EXT` so we know not to check against what was set in `vkCmdBindDescriptorSets`... will have a temp fix up soon

**Comment by evopen** [comment]
Hi, thanks for the fix. May I ask is there a tracking issue for validating descriptor buffer bind? I couldn't find one.

**Comment by spencer-lunarg** [comment]
these is this one https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4832

those should the only two `vkCmdBindDescriptorBuffersEXT` VUs still missing
