### ISSUE TITLE
VUID-vkSetDebugUtilsObjectNameEXT-pNameInfo-07874 behaves incorrectly

### ISSUE THREAD

**Issue by kainino0x** [KhronosGroup/Vulkan-ValidationLayers#7241]
**Environment:**
 - OS: Linux
 - GPU and driver version: driver agnostic - seen on nvidia, intel, and `llvmpipe: Mesa 23.2.1-1+build1 (LLVM 16.0.6) 0.0.1 [Selected]` which is the one I debugged against. (Also for some reason it does not fire when run against SwiftShader. Maybe we are just not setting up the VVL correctly in that case.)
 - SDK or header version if building from repo: This started happening in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7204
    Please see the links in the commit summary of https://chromium-review.googlesource.com/c/chromium/src/+/5166194 for the exact versions of all of the Vulkan dependencies (the later ends of all of the commit ranges linked)
 - Options enabled (synchronization, best practices, etc.):

**Describe the Issue**

When calling vkSetDebugUtilsObjectNameEXT to set the name of a VkDevice, we get the following error:

`STDERR: Error: VUID-vkSetDebugUtilsObjectNameEXT-pNameInfo-07874: Validation Error: [ VUID-vkSetDebugUtilsObjectNameEXT-pNameInfo-07874 ] Object 0: handle = 0x3b84009b4000, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xbcf2c383 | vkSetDebugUtilsObjectNameEXT(): pNameInfo->objectHandle (VkDevice 0x3b8401e41c00) was created, allocated or retrieved from VkDevice 0x0[], but command is using (or its dispatchable parameter is associated with) VkDevice 0x3b8401e41c00[]. The Vulkan spec states: If pNameInfo->objectHandle is the valid handle of a device-level object, that object must be a descendent of the VkDevice identified by device (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkSetDebugUtilsObjectNameEXT-pNameInfo-07874)`

Note the message says the type is `VK_OBJECT_TYPE_INSTANCE` - but as far as I can tell from my debugger, this is wrong, and it is actually `VK_OBJECT_TYPE_DEVICE`.

**Expected behavior**

If this is indeed a VkDevice, then its "parent" VkDevice should be itself, not 0x0 as the error message says, which would make this call valid.

If this is actually a VkInstance, then this validation check should not be hit at all - the spec says this validation only applies if it's a device-level object, which VkInstance is not.

**Valid Usage ID**
VUID-vkSetDebugUtilsObjectNameEXT-pNameInfo-07874

**Additional context**

Dawn bug: https://crbug.com/dawn/2322

cc @spencer-lunarg since this appears to have regressed in #7204

**Comment by spencer-lunarg** [comment]
I thought I caught these edge cases when re-working the "device calls itself" logic, I see one slipped through... will take care of it right now

**Comment by spencer-lunarg** [comment]
@kainino0x please ping if this is still causing false positives

**Comment by kainino0x** [comment]
Thank you for the fix! Will do!

**Comment by kainino0x** [comment]
Things look fixed in Dawn/Chrome. Thanks again!
