### ISSUE TITLE
SYNC-HAZARD-WRITE-AFTER-WRITE when using multiple threads

### ISSUE THREAD

**Issue by RYDB3RG** [KhronosGroup/Vulkan-ValidationLayers#7250]
Hi,

Is `SYNC-HAZARD-WRITE-AFTER-WRITE`  expected when 2 threads submit with a mutex into the same queue?

repro:

    TEST_F(NegativeSyncVal, CopyPresentLoop) {
        AddSurfaceExtension();
        RETURN_IF_SKIP(InitSyncValFramework());
        RETURN_IF_SKIP(InitState());
        if (!InitSwapchain()) {
            GTEST_SKIP() << "Cannot create surface or swapchain";
        }

        std::mutex queue_mutex;
        const auto &queues = m_device->graphics_queues();
        auto &queue0 = queues[0];
        auto &queue1 = queues[0];

        VkCommandPoolCreateInfo pool_create_info = vku::InitStructHelper();
        pool_create_info.queueFamilyIndex = m_device->graphics_queue_node_index_;
        pool_create_info.flags = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
        vkt::CommandPool pool0(*m_device, pool_create_info);

        const vkt::Fence fence0(*m_device);
        vkt::CommandBuffer cmd0(m_device, &pool0);
        vkt::Buffer src(*m_device, 1024 * 128, VK_BUFFER_USAGE_TRANSFER_SRC_BIT);
        vkt::Buffer dst(*m_device, 1024 * 128, VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_INDEX_BUFFER_BIT);

        std::thread thread([&]
        {
            while(true)
            {
                VkBufferCopy copy_info{};
                copy_info.size = 1024 * 128;

                cmd0.begin();
                vk::CmdCopyBuffer(cmd0.handle(), src.handle(), dst.handle(), 1, &copy_info);
                cmd0.end();

                vk::ResetFences(m_device->device(), 1, &fence0.handle());

                VkSubmitInfo submit = vku::InitStructHelper();
                submit.commandBufferCount = 1;
                submit.pCommandBuffers = &cmd0.handle();

                {
                    std::unique_lock<std::mutex> lock(queue_mutex);
                    ASSERT_EQ(VK_SUCCESS, vk::QueueSubmit(queue1->handle(), 1, &submit, fence0.handle()));
                }

                vk::WaitForFences(m_device->device(), 1, &fence0.handle(), VK_TRUE, kWaitTimeout);
            }
        });

        {
            const auto swapchain_images = GetSwapchainImages(m_swapchain);
            const vkt::Semaphore acquire_semaphore(*m_device);
            const vkt::Semaphore submit_semaphore(*m_device);
            vkt::CommandPool pool1(*m_device, pool_create_info);
            vkt::CommandBuffer cmd1(m_device, &pool1);

            VkFenceCreateInfo fence_create_info{};
            fence_create_info.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO;
            fence_create_info.flags = VK_FENCE_CREATE_SIGNALED_BIT;
            vkt::Fence fence1(*m_device, fence_create_info);

            while(true)
            {
                ASSERT_EQ(VK_SUCCESS,vk::WaitForFences(m_device->device(), 1, &fence1.handle(), VK_TRUE, kWaitTimeout));
                vk::ResetFences(m_device->device(), 1, &fence1.handle());

                uint32_t image_index = 0;
                ASSERT_EQ(VK_SUCCESS,
                    vk::AcquireNextImageKHR(device(), m_swapchain, kWaitTimeout, acquire_semaphore, VK_NULL_HANDLE, &image_index));

                VkImageMemoryBarrier layout_transition = vku::InitStructHelper();
                layout_transition.srcAccessMask = 0;
                layout_transition.dstAccessMask = 0;

                layout_transition.oldLayout = VK_IMAGE_LAYOUT_UNDEFINED;
                layout_transition.newLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;
                layout_transition.image = swapchain_images[image_index];
                layout_transition.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
                layout_transition.subresourceRange.baseMipLevel = 0;
                layout_transition.subresourceRange.levelCount = 1;
                layout_transition.subresourceRange.baseArrayLayer = 0;
                layout_transition.subresourceRange.layerCount = 1;

                cmd1.begin();
                vk::CmdPipelineBarrier(cmd1, VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT,
                                    VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT, 0, 0, nullptr, 0, nullptr, 1, &layout_transition);
                cmd1.end();

                constexpr VkPipelineStageFlags semaphore_wait_stage = VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT;
                VkSubmitInfo submit = vku::InitStructHelper();
                submit.waitSemaphoreCount = 1;
                submit.pWaitSemaphores = &acquire_semaphore.handle();
                submit.pWaitDstStageMask = &semaphore_wait_stage;
                submit.commandBufferCount = 1;
                submit.pCommandBuffers = &cmd1.handle();
                submit.signalSemaphoreCount = 1;
                submit.pSignalSemaphores = &submit_semaphore.handle();

                VkPresentInfoKHR present = vku::InitStructHelper();
                present.waitSemaphoreCount = 1;
                present.pWaitSemaphores = &submit_semaphore.handle();
                present.swapchainCount = 1;
                present.pSwapchains = &m_swapchain;
                present.pImageIndices = &image_index;

                {
                    std::unique_lock<std::mutex> lock(queue_mutex);
                    ASSERT_EQ(VK_SUCCESS, vk::QueueSubmit(queue0->handle(), 1, &submit, fence1));
                }

                {
                    std::unique_lock<std::mutex> lock(queue_mutex);
                    vk::QueuePresentKHR(queue0->handle(), &present);
                }
            }
        }
    }

**Comment by artem-lunarg** [comment]
@RYDB3RG thanks for the attached test. It looks like a validation bug. Queue submission with a fence defines a fence signal operation and a memory dependency, so waiting on the fence should prevent `WRITE_AFTER_WRITE` hazards due to copying to a buffer in a different iterations of the thread loop.

Relevant parts of the spec (section 7.3):
> When a fence is submitted to a queue as part of a [queue submission](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#devsandqueues-submission) command, it defines a memory dependency on the batches that were submitted as part of that command, and defines a fence signal operation which sets the fence to the signaled state.

> The first [access scope](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#synchronization-dependencies-access-scopes) includes all memory access performed by the device.


Reported error message:
> [ RUN      ] NegativeSyncVal.CopyPresentLoop
Validation Error: [ SYNC-HAZARD-WRITE-AFTER-WRITE ] Object 0: handle = 0x1b5bdd44540, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0x5c0ec5d6 | vkQueueSubmit():  Hazard WRITE_AFTER_WRITE for entry 0, VkCommandBuffer 0x1b5cf06f950[], Submitted access info (submitted_usage: SYNC_COPY_TRANSFER_WRITE, command: vkCmdCopyBuffer, seq_no: 1, reset_no: 3). Access info (prior_usage: SYNC_COPY_TRANSFER_WRITE, write_barriers: 0, queue: VkQueue 0x1b5bdd44540[], submit: 0, batch: 0, batch_tag: 2, command: vkCmdCopyBuffer, command_buffer: VkCommandBuffer 0x1b5cf06f950[], seq_no: 1, reset_no: 1).


Thanks again for the test, that's a big deal.

**Comment by artem-lunarg** [comment]
Add repro case: https://github.com/artem-lunarg/Vulkan-ValidationLayers/commit/f67a708774c7e7d4be49e1ddb708523f20ed3115

**Comment by moset** [comment]
I'm also seeing SYNC-HAZARD-WRITE-AFTER-WRITE when using timeline semaphores to synchronize between GPU and CPU. I expect it's the same problem in the layer. Do you think a reproduction case is needed for this case as well?

**Comment by artem-lunarg** [comment]
@moset timeline semaphores are currently not supported for synchronization validation but that's something we are going to work on.

**Comment by artem-lunarg** [comment]
Added simplified repro case (does not require present): https://github.com/artem-lunarg/Vulkan-ValidationLayers/commit/fc5848f86f3771d069aae8681aca192c9bed6fa2
