### ISSUE TITLE
YUV Sampler validation

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-ValidationLayers#726]
From an issue that @egdaniel found.
The spec has a couple of statements about YUV sampling requirements that validation should be added for. First, from the intro statement in section [12.1. Sampler Y’CBCR conversion](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#samplers-YCbCr-conversion):

> To create a sampler with Y’CBCR conversion enabled, add a VkSamplerYcbcrConversionInfo to the pNext chain of the VkSamplerCreateInfo structure. To create a sampler Y’CBCR conversion, the samplerYcbcrConversion feature must be enabled. Conversion must be fixed at pipeline creation time, through use of a combined image sampler with an immutable sampler in VkDescriptorSetLayoutBinding.

Based on this text the primary check that we'd like added is to verify at draw time that, if any samplers in the descriptor set contain a YCBCR conversion, then those samplers MUST also exists as immutable samplers in the currently bound pipeline.

That is the draw-time check that I don't believe there's a specific VU for, but the requirement is clear from the quoted spec text.
Two other checks to add before draw are from VUs in [VkWriteDescriptorSet](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VkWriteDescriptorSet) section of spec.

1. If descriptorType is VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, and if any element of pImageInfo has a imageView member that was created with a VkSamplerYcbcrConversionInfo structure in its pNext chain, then dstSet must have been allocated with a layout that included immutable samplers for dstBinding
2. If descriptorType is VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, and dstSet was allocated with a layout that included immutable samplers for dstBinding, then the imageView member of each element of pImageInfo which corresponds to an immutable sampler that enables sampler Y’CBCR conversion must have been created with a VkSamplerYcbcrConversionInfo structure in its pNext chain with an identically defined VkSamplerYcbcrConversionInfo to the corresponding immutable sampler

**Comment by Tony-LunarG** [comment]
Is your second check addressed by the fix for #529?

**Comment by daveh-lunarg** [comment]
I think so.  It looks like these VUs are VUID-VkWriteDescriptorSet-descriptorType-01947 and -01948.  VUID database says 1948 is implemented.

**Comment by tobine** [comment]
Yes, #529 was same issue as item 2 in my description so that item can be disregarded. Thanks!

**Comment by locke-lunarg** [comment]
It has to pass VUID-VkWriteDescriptorSet-descriptorType-01947 & 01948, so it could update and bind the descriptor set.

But in the case, the error that a sampler in the descriptor set contain a YCBCR conversion, but it is not an immutable sampler at draw time will not happen.

**Comment by tobine** [comment]
This is now covered
