### ISSUE TITLE
Segfault when validating dynamic blend state 

### ISSUE THREAD

**Issue by gerddie** [KhronosGroup/Vulkan-ValidationLayers#7261]
**Environment:**
 - OS:  Linux
 - GPU and driver version: AMD, radv  (mesa-gita921a6901010)
 - SDK or header version if building from repo: 1.3.268 (but also tested with git head)  
 - Options enabled (synchronization, best practices, etc.): 
   * Core (all)
   * Handle wrapping
   * Stateless parameter 
   * Object lifetime  
   * Thread safety 
  
**Describe the Issue**

When running an apitrace of *Quern - undying thoughts* using *Mesa/Zink* the validation layer crashes in `CoreChecks::ValidateDrawDynamicStatePipeline`  on [line 524](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/02f1cb7d55aa808bbe1401cb0648f7057c98485a/layers/core_checks/cc_cmd_buffer_dynamic.cpp#L524) with a `nullptr`  dereference. (Below the backtrace is for version 1.3.268, so the line in question is 408)

**Expected behavior**

The validation layer should not crash, and possibly report an validation error if blending is enabled for non-allocated attachments (not sure about this). 

**Additional context**

The framebuffer has only one color attachment at this point, but because in `CMD_BUFFER_STATE::BeginRendering` the vector holding the attachments is allocated as `(pRenderingInfo->colorAttachmentCount + 2) * 2` and some attachments are initialized to `nullptr` in the loop that follows, because of that we end up with the `nullptr` deref. Working around this by checking for as  `nullptr` and skipping the attachment in this case results in a new validation error, because the DS surface that is also added to the vector of attachments  is checked for `VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT` and this check fails.

There are two problems here: On one hand if the dynamic blend state  is enabled for an attachment that is not available we get a crash. Here the format feature test should either be skipped for this attachment or a validation error should be reported (I haven't yet found the relevant part of the spec that  tells me which would be the right answer). 

The second problem is that the validation of the dynamic blend state iterates over the whole vector of attachments as created in 
`CMD_BUFFER_STATE::BeginRendering`, but it should probably only  iterate over the first `cb_state.GetDynamicColorAttachmentCount()` elements.  

<details>
<summary>code or terminal output</summary>

```sh
4581357: error: caught an unhandled exception
glretrace: _ZN2os20libbacktraceProvider13dumpBacktraceEv+0x383021: /home/gerddie/Collabora/apitrace/lib/os/os_backtrace.cpp:303
glretrace: _ZN2os14dump_backtraceEv+0x383174: /home/gerddie/Collabora/apitrace/lib/os/os_backtrace.cpp:314
glretrace: signalHandler+0x380e74: /home/gerddie/Collabora/apitrace/lib/os/os_posix.cpp:321
/lib64/libc.so.6+0x38a3f: /usr/src/debug/sys-libs/glibc-2.37-r7/glibc-2.37/signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
/usr/local/lib64/libVkLayer_khronos_validation.so: _ZNK10CoreChecks32ValidateDrawDynamicStatePipelineERK16LAST_BOUND_STATERK8Location+0x7be896: /home/gerddie/Collabora/Vulkan-ValidationLayers/layers/core_checks/cc_cmd_buffer_dynamic.cpp:408
/usr/local/lib64/libVkLayer_khronos_validation.so: _ZNK10CoreChecks24ValidateDrawDynamicStateERK16LAST_BOUND_STATERK8Location+0x7bd38e: /home/gerddie/Collabora/Vulkan-ValidationLayers/layers/core_checks/cc_cmd_buffer_dynamic.cpp:236
/usr/local/lib64/libVkLayer_khronos_validation.so: _ZNK10CoreChecks19ValidateActionStateERK16CMD_BUFFER_STATE19VkPipelineBindPointRK8Location+0x9ee503: /home/gerddie/Collabora/Vulkan-ValidationLayers/layers/core_checks/cc_drawdispatch.cpp:5668
/usr/local/lib64/libVkLayer_khronos_validation.so: _ZNK10CoreChecks37PreCallValidateCmdDrawMultiIndexedEXTEP17VkCommandBuffer_TjPK25VkMultiDrawIndexedInfoEXTjjjPKiRK11ErrorObject+0x9e3a56: /home/gerddie/Collabora/Vulkan-ValidationLayers/layers/core_checks/cc_drawdispatch.cpp:4447
/usr/local/lib64/libVkLayer_khronos_validation.so: _ZN20vulkan_layer_chassis22CmdDrawMultiIndexedEXTEP17VkCommandBuffer_TjPK25VkMultiDrawIndexedInfoEXTjjjPKi+0x1070170: /home/gerddie/Collabora/Vulkan-ValidationLayers/layers/vulkan/generated/chassis.cpp:13916
/home/gerddie/Testbed-debug/lib64/dri/zink_dri.so: draw_indexed<(zink_multidraw)1>+0x109a7e8: ../src/gallium/drivers/zink/zink_draw.cpp:317
/home/gerddie/Testbed-debug/lib64/dri/zink_dri.so: _Z9zink_drawIL14zink_multidraw1EL18zink_dynamic_state5ELb0ELb0EEvP12pipe_contextPK14pipe_draw_infojPK23pipe_draw_indirect_infoPK26pipe_draw_start_count_biasjP17pipe_vertex_statej+0x109a7e8: ../src/gallium/drivers/zink/zink_draw.cpp:1067
/home/gerddie/Testbed-debug/lib64/dri/zink_dri.so: zink_draw_vbo<(zink_multidraw)1, (zink_dynamic_state)5, false>+0xfc678d: ../src/gallium/drivers/zink/zink_draw.cpp:1140
/home/gerddie/Testbed-debug/lib64/dri/zink_dri.so: tc_call_draw_single+0xb28d34: ../src/gallium/auxiliary/util/u_threaded_context.c:3834
/home/gerddie/Testbed-debug/lib64/dri/zink_dri.so: batch_execute+0xb1f050: ../src/gallium/auxiliary/util/u_threaded_context.c:461
/home/gerddie/Testbed-debug/lib64/dri/zink_dri.so: tc_batch_execute+0xb1f050: ../src/gallium/auxiliary/util/u_threaded_context.c:512
/home/gerddie/Testbed-debug/lib64/dri/zink_dri.so: util_queue_thread_func+0xec84f: ../src/util/u_queue.c:309
/home/gerddie/Testbed-debug/lib64/dri/zink_dri.so: impl_thrd_routine+0x1126d3: ../src/c11/impl/threads_posix.c:67
/lib64/libc.so.6: start_thread+0x869a9: /usr/src/debug/sys-libs/glibc-2.37-r7/glibc-2.37/nptl/pthread_create.c:444
/lib64/libc.so.6: clone3+0x1086eb: ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

</details>

**Comment by spencer-lunarg** [comment]
@gerddie thanks for raising this, was able to write a test to quickly reproduce it, will investigate more to see what is going on here
