### ISSUE TITLE
Validation check when using struct VkPhysicalDeviceExtendedDynamicState3FeaturesEXT

### ISSUE THREAD

**Issue by tzdimi** [KhronosGroup/Vulkan-ValidationLayers#7262]
If  VkPhysicalDeviceExtendedDynamicState3FeaturesEXT struct is included at VkDeviceCreateInfo .pNext chain and  VK_EXT_extended_dynamic_state3 extension is not enabled there is no error message when trying to create the device that 
the extension isn't enabled.
Most probably related with #5012

**Comment by spencer-lunarg** [comment]
also related to https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7189

This has been a long todo to get the code gen working (with proper testing to catch the many nasty edge cases), unfortunately didn't make it for the upcoming SDK but my goal is to get this done for the following SDK release
