### ISSUE TITLE
Add support for Opacity Micro-Maps

### ISSUE THREAD

**Issue by jarvism-nv** [KhronosGroup/Vulkan-ValidationLayers#7265]
**Environment:**
 - OS: Windows 11
 - GPU and driver version: RTX 4080 (31.0.15.4617)

**Describe the Issue**

I currently get the following validaiton error when using micro maps:

```
Validation Error: [ VUID-VkBufferMemoryBarrier2-dstAccessMask-07454 ] Object 0: handle = 0x245a8d57aa0, type =
VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x5e6e827d | vkCmdPipelineBarrier2(): pDependencyInfo->pBufferMemoryBarriers[0].dstAccessMask (VK_ACCESS_SHADER_READ_BIT) is not supported by stage mask
(VK_PIPELINE_STAGE_2_MICROMAP_BUILD_BIT_EXT). The Vulkan spec states: If dstAccessMask includes
VK_ACCESS_2_SHADER_READ_BIT, dstStageMask must include VK_PIPELINE_STAGE_2_ALL_GRAPHICS_BIT,
VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT, VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_BUILD_BIT_KHR,
VK_PIPELINE_STAGE_2_MICROMAP_BUILD_BIT_EXT, or one of the VK_PIPELINE_STAGE_*_SHADER_BIT stages
(https://vulkan.lunarg.com/doc/view/1.3.268.0/windows/1.3-extensions/vkspec.html#VUID-VkBufferMemoryBarrier2-dstAccessMask-07454)
```

It says `VK_ACCESS_SHADER_READ_BIT` isn't supported with `VK_PIPELINE_STAGE_2_MICROMAP_BUILD_BIT_EXT`, but then lists it as being allowed.

**Expected behavior**

`VK_PIPELINE_STAGE_2_MICROMAP_BUILD_BIT_EXT` should be recognized and there shouldn't be a validation error.

**Comment by jarvism-nv** [comment]
@spencer-lunarg Do you know when these changes will make into the vulkan SDK?

**Comment by KarenGhavam-lunarG** [comment]
> @spencer-lunarg Do you know when these changes will make it into the vulkan SDK?

An SDK just released on January 17. There won't be another SDK for at least 8 weeks.

**Comment by spencer-lunarg** [comment]
@jarvism-nv It seems it just missed the release for https://github.com/KhronosGroup/Vulkan-ValidationLayers/releases/tag/vulkan-sdk-1.3.275.0
