### ISSUE TITLE
Validation for VkGraphicsPipelineLibraryCreateInfoEXT

### ISSUE THREAD

**Issue by AMD-dwang** [KhronosGroup/Vulkan-ValidationLayers#7266]
**Describe the situation in which you encountered the missing validation**
We created a pipeline that includes VK_GRAPHICS_PIPELINE_LIBRARY_FRAGMENT_SHADER_BIT_EXT in VkGraphicsPipelineLibraryCreateInfoEXT::flags, and in this pipeline we didn't pass any shaders, this violates the spec agreement, but validation layer didn't catch it. 

**Valid Usage IDs requested**
VUID-VkGraphicsPipelineCreateInfo-flags-06644

**Comment by spencer-lunarg** [comment]
this was recently added 2 weeks ago (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7192/files#diff-35ec146be4657f8821a010ede63e5a91c518ccda060f5cee145173d473b793a5R289) and will be in the next SDK release
