### ISSUE TITLE
gpuav: Fix `NegativeGpuAVRayTracing.CmdTraceRaysIndirectKHR`

### ISSUE THREAD

**Issue by arno-lunarg** [KhronosGroup/Vulkan-ValidationLayers#7279]
Linux-Mesa-6800, AMD is crashing on `NegativeGpuAVRayTracing.CmdTraceRaysIndirectKHR`
Issue is probably in validation code, I suspect incorrect device address handling

**Comment by spencer-lunarg** [comment]
verified this is now working on my MESA RAD machine
