### ISSUE TITLE
deviceMask is not validated in vkAcquireNextImage2KHR

### ISSUE THREAD

**Issue by scyganINTEL** [KhronosGroup/Vulkan-ValidationLayers#728]
The 'deviceMask' member of VkAcquireNextImageInfoKHR structure does not seem validated in vkAcquireNextImage2KHR call. Spec says: 

>  deviceMask must be a valid device mask

Where valid mask can be constructed only from bits pointing to valid device indices in device group. 

This can be reproduced using commit 65ebf85d of VK-GL-CTS, test `dEQP-VK.wsi.win32.swapchain.render.basic2`, which is buggy in this version.

The wrong deviceMask value (0xFFFFFFFF) is here: https://github.com/KhronosGroup/VK-GL-CTS/blob/65ebf85d/external/vulkancts/modules/vulkan/wsi/vktWsiSwapchainTests.cpp#L1373

**Comment by jzulauf-lunarg** [comment]
Triage notes:  This is one of several related incomplete VU checks regarding deviceMasks.  From the spec:

> A device mask value is valid if every bit that is set in the mask is at a bit position that is less than the number of physical devices in the logical device.

core_validation stores that count in layer_data::physical_device_count.

When implementing the fix, similar VU checks should be added as appropriate

**Comment by locke-lunarg** [comment]
[Pull request 785](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/785)

**Comment by locke-lunarg** [comment]
[Pull request #788](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/788)
