### ISSUE TITLE
No way to determine where headers files are installed on Linux

### ISSUE THREAD

**Issue by djdeath** [KhronosGroup/Vulkan-ValidationLayers#729]
Most libraries on Linux systems provide a `.pc` file to allow applications & libraries to find what path to include and what library to link against.
The validation layers do not provide such a file and so depending on the Linux distribution you're running on it's currently impossible to find what path to include : 
```
#include <vk_layer.h>
```
or
```
#include <vulkan/vk_layer.h>
```

On Debian/Fedora/Ubuntu, headers are installed in `/usr/include/vulkan/` while other distros have a mix of `/usr/` & `/usr/include/`

Could we add a .pc file for the validation layers?

**Comment by 1ace** [comment]
+1

This effectively means that it is currently impossible to use these headers as provided by the system, as currently the choices are:
- `#include <vk_layer.h>` and break the build on half the world
- `#include <vulkan/vk_layer.h>` and break the build on the other half of the world
- maintain a local copy of the files in your project

**Comment by jzulauf-lunarg** [comment]
@johnzupin @jeremy-lunarg -- do we want to track this here or at LunarXchange, as this appears to be an SDK issue?

**Comment by jeremy-lunarg** [comment]
AFAICT all of binaries in the SDK come from source repositories which refer to vk_layer.h in the vulkan subdirectory. i.e. vulkan/vk_layer.h. We expect the same from distro packages. If that's not the case, then I would follow up with package provider.

**Comment by djdeath** [comment]
I tend to agree with you, the vulkan subdirectory makes sense.
I'm just curious as to why the `vulkan/` subpath isn't baked into the CMakeFiles so that could help packagers avoid the mistake.

**Comment by mikew-lunarg** [comment]
@djdeath I cant address the historical part of how we got here.
But if you have improvements for the CMakeLists files, we'd welcome pull requests.

**Comment by mikew-lunarg** [comment]
@djdeath @1ace Thanks for raising this issue, it exposes shortcomings in the way the install is implemented in CMake.  I'm starting a new issue, see #743.  Your input there welcome.
