### ISSUE TITLE
NegativeGpuAVDescriptorIndexing.ArrayOOBTess and ArrayOOBVertex cases crash on Linux / RADV

### ISSUE THREAD

**Issue by jeremyg-lunarg** [KhronosGroup/Vulkan-ValidationLayers#7314]
**Environment:**
Internal CI 
Driver Name = radv
Driver Info = Mesa 22.2.5

**Describe the Issue**

tests: 
- `NegativeGpuAVDescriptorIndexing.ArrayOOBTess`
- `NegativeGpuAVDescriptorIndexing.ArrayOOBVertex`

The tessellation portion of this test often crashes internal CI runs.

Note: I'm splitting up the original test to make it easier to figure out problems like this.  See:  https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7312

**Comment by spencer-lunarg** [comment]
after running `--gtest_filter=NegativeGpuAVDescriptorIndexing* --gtest_repeat=20` on Mesa 24 RADV driver, I am now convinced this is just not an issue and just need an CI internal driver update

**Comment by spencer-lunarg** [comment]
did `--gtest_filter=NegativeGpuAVDescriptorIndexing* --gtest_repeat=20` again with ToT RADV... no issues, closing as if this is still an issue, its because CI has an old driver
