### ISSUE TITLE
Shared libraries end up with 100+ copies of `api_extension_map`

### ISSUE THREAD

**Issue by jimblandy** [KhronosGroup/Vulkan-ValidationLayers#7340]
Because `api_extension_map` is declared as a global in `layers/vulkan/generated/vk_dispatch_table_helper.h`, each compilation unit that \#includes that header ends up with its own copy of that somewhat large value. Experimentation (adding a similar `const` definition to that header of a global whose type's constructor does some logging) suggests that `libVkLayer_khronos_validation.so` ends up with around 110 copies of the hash table.

This doesn't cause any misbehavior (other than, I assume, slowness). I was just debugging an unrelated problem that occurs when running a shared library's global destructors is racing with the main program exiting, and noticed that there were a jillion entries in glibc's [`__exit_funcs`](https://github.com/bminor/glibc/blob/b86cb494f9a27a106c96c025c6d834334d85b80a/stdlib/cxa_atexit.c#L74) list for symbols named `api_extension_map` --- at different addresses.

**Comment by charles-lunarg** [comment]
I believe this is the same issue #7293 so in effect it’s been fixed already. It’d b great if you could confirm this by pulling main and building locally?

**Comment by spencer-lunarg** [comment]
I also think this got in the 1.3.275 SDK as well (@charles-lunarg can you confirm that)

**Comment by charles-lunarg** [comment]
It did not get into the 1.3.275 SDK. I believe I missed the cutoff by a good week.

**Comment by spencer-lunarg** [comment]
@jimblandy as Charles said, `api_extension_map` is now in `vk_dispatch_table_helper.cpp` (from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7293) and this issue should be fixed now in ToT

If any other concerns feel free to reopen the issue

**Comment by jimblandy** [comment]
Yes, c63fae9bc seems to remove around 100 entries from glibc's exit function table.
