### ISSUE TITLE
Unreported read-after-write conflict between UNIFORM_READ and TRANSFER_WRITE accesses, caused by an unrelated memory barrier

### ISSUE THREAD

**Issue by nicebyte** [KhronosGroup/Vulkan-ValidationLayers#7349]
**Environment:**
 - OS:  Windows 10 Home 22H2
 - GPU and driver version: GeForceRTX 2080 super, driver version 31.0.15.4617
 - SDK or header version if building from repo: SDK 1.3.275.0
 - Options enabled (synchronization, best practices, etc.): everything in Core, Synchronization, QueueSubmit Synchronization Validation, Handle Wrapping, Object Lifetime, Stateless Parameter, Fine Grained Locking, Thread Safety

**Describe the Issue**

The following commands are executed:

1. A transfer writing to buffer B;
2. A compute dispatch, reading from buffer B, using a `StructuredBuffer`;
3. Another compute dispatch, reading from buffer B, using a `ConstantBuffer`.

There is a memory barrier between 1 and 2 using the following stage/access masks:

```
srcStageMask = VK_PIPELINE_STAGE_2_ALL_TRANSFER_BIT
srcAccessMask = VK_ACCESS_2_TRANSFER_WRITE_BIT
dstStageMask = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT
dstAccessMask = VK_ACCESS_2_SHADER_READ_BIT
```

Note that `VK_ACCESS_2_UNIFORM_READ_BIT` is missing from the destination access mask!

**Expected behavior**

I expect validation layers to report a read-after-write hazard, because the above memory barrier does _not_ make the transfer stage's writes available/visible to the UNIFORM_READ accesses. SHADER_READ does not imply UNIFORM_READ. Quote from the spec:

> VK_ACCESS_SHADER_READ_BIT specifies read access to a uniform texel buffer, sampled image,
> storage buffer, physical storage buffer, shader binding table, storage texel buffer, or storage
> image in any shader pipeline stage

**Observed behavior**
VVL do not report any validation errors.

**Additional context**
To further check my own thinking, I have hacked the example above to use vertex attrib / index buffers instead of storage and uniform. In other words:

1. transfer writes to buffer B
2. draw call 1 uses B as vertex attribute buffer
3. draw call 2 uses B as index buffer

A memory barrier similar to the above is issued between (1) and (2) (note the missing INDEX_ATTRIBUTE_READ_BIT):
``` 
srcStageMask = VK_PIPELINE_STAGE_2_ALL_TRANSFER_BIT
srcAccessMask = VK_ACCESS_2_TRANSFER_WRITE_BIT
dstStageMask = VK_PIPELINE_STAGE_2_VERTEX_INPUT_BIT 
dstAccessMask = VK_ACCESS_2_VERTEX_ATTRIBUTE_READ_BIT
```

Under that scenario, VVL indeed issues an error: `vkQueueSubmit():  Hazard READ_AFTER_WRITE for entry 1, VkCommandBuffer 0x1d729e592d0[], Submitted access info (submitted_usage: SYNC_INDEX_INPUT_INDEX_READ, command: vkCmdDrawIndexed, seq_no: 2, reset_no: 1). Access info (prior_usage: SYNC_COPY_TRANSFER_WRITE, write_barriers: SYNC_VERTEX_ATTRIBUTE_INPUT_VERTEX_ATTRIBUTE_READ`

**Comment by artem-lunarg** [comment]
@nicebyte Thanks for the high-quality bug report. It should be fixed now.
