### ISSUE TITLE
VUID-VkDeviceCreateInfo-pNext-pNext: VkPhysicalDeviceRasterizationOrderAttachmentAccessFeaturesEXT requires ARM extension

### ISSUE THREAD

**Issue by romanl-g** [KhronosGroup/Vulkan-ValidationLayers#7350]
Getting this error:
```
vkCreateDevice(): pCreateInfo->pNext includes a pointer to a VkPhysicalDeviceRasterizationOrderAttachmentAccessFeaturesEXT, but when creating VkDevice, the parent extension (VK_ARM_rasterization_order_attachment_access) was not included in ppEnabledExtensionNames. 
```

https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/55932ddb23483d52e7280c717a4fa06dbcd3841d#diff-272b640c64b2b6038b99dbdd33841d520d5d595cd609171016925c39ea24f643R6243

            if (!IsExtEnabled(device_extensions.vk_arm_rasterization_order_attachment_access)) {
                skip |= LogError(pnext_vuid, instance, loc.dot(Field::pNext),
                                 "includes a pointer to a VkPhysicalDeviceRasterizationOrderAttachmentAccessFeaturesEXT, but when "
                                 "creating VkDevice, the parent extension "
                                 "(VK_ARM_rasterization_order_attachment_access) was not included in ppEnabledExtensionNames.");
            }

Per spec:
https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceRasterizationOrderAttachmentAccessFeaturesEXT.html

the extension can be `VK_ARM_rasterization_order_attachment_access` OR `VK_EXT_rasterization_order_attachment_access` (we add the latter but the check above only seems to check the former)

**Comment by romanl-g** [comment]
@spencer-lunarg

**Comment by spencer-lunarg** [comment]
sorry, this happened with another `vendor`-promoted-to-`EXT/KHR` extension as well... will get this fixed quick with my workaround (and then search for anymore like it)

thanks for raising this
