### ISSUE TITLE
Acceleration Structures missing in Device/Indirect call

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/Vulkan-ValidationLayers#7362]
These VUs we already have in `vkCmdBuildAccelerationStructuresKHR` and think they are just simply missing a case from the other 2 calls

- [x] VUID-vkBuildAccelerationStructuresKHR-pInfos-03675
- [x] VUID-vkBuildAccelerationStructuresKHR-pInfos-03668
- [x] VUID-vkBuildAccelerationStructuresKHR-pInfos-03761
- [x] VUID-vkBuildAccelerationStructuresKHR-pInfos-03762
- [x] VUID-vkBuildAccelerationStructuresKHR-pInfos-03763
- [x] VUID-vkBuildAccelerationStructuresKHR-pInfos-03764
- [x] VUID-vkBuildAccelerationStructuresKHR-pInfos-03765
- [x] VUID-vkBuildAccelerationStructuresKHR-pInfos-03766
- [x] VUID-vkBuildAccelerationStructuresKHR-pInfos-03767
- [x] VUID-vkBuildAccelerationStructuresKHR-ppBuildRangeInfos-03676
- [x] VUID-vkBuildAccelerationStructuresKHR-primitiveCount-03769
- [x] VUID-vkBuildAccelerationStructuresKHR-dstAccelerationStructure-03701
- [x] VUID-vkBuildAccelerationStructuresKHR-dstAccelerationStructure-03702
- [x] VUID-vkBuildAccelerationStructuresKHR-firstVertex-03770

(With the indirect, there might be some that are GPU-AV - please mark and ignore)

- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-pInfos-03671
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-pInfos-03672
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-geometry-03673
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-pInfos-03674
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-dstAccelerationStructure-03701
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-dstAccelerationStructure-03702
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-pInfos-03711
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-pInfos-03712
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-pInfos-03761
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-pInfos-03762
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-pInfos-03765
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-pInfos-03766
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-pInfos-03767
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-pInfos-03802
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-pInfos-03803
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-pInfos-03804
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-pInfos-03805
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-pInfos-03806
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-pInfos-03807
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-pInfos-03808
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-pInfos-03809
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-pInfos-03811
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-pInfos-03812
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-pInfos-03813
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-pInfos-03814

Those will be added back when https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6040 is solved

- [ ] VUID-vkBuildAccelerationStructuresKHR-dstAccelerationStructure-03703
- [x] VUID-vkBuildAccelerationStructuresKHR-scratchData-03704
- [ ] VUID-vkBuildAccelerationStructuresKHR-scratchData-03705
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-dstAccelerationStructure-03703
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-scratchData-03704
- [x] VUID-vkCmdBuildAccelerationStructuresIndirectKHR-scratchData-03705

**Comment by arno-lunarg** [comment]
VUID-vkBuildAccelerationStructuresKHR-scratchData-03704 and VUID-vkBuildAccelerationStructuresKHR-scratchData-03705 can only happen if the scratch host address comes from a mapped VkBuffer (unusual), and if the buffers backing acceleration structures are host visible. 
Adding validation would imply mapping the buffers backing the acceleration structures, something that can only be done if they are not already mapped.
With all of that in mind, adding validation for those 2 VUIDs is simply not worth it.
