### ISSUE TITLE
More things to move into `vk_dispatch_table_helper.cpp`

### ISSUE THREAD

**Issue by jimblandy** [KhronosGroup/Vulkan-ValidationLayers#7363]
#7293 moved `api_extension_map` into `vk_dispatch_table_helper.cpp`, fixing #7340. However, in the process of verifying that fix, I found a few other things that seem to need similar treatment:

- `kDeviceExtensionNames`
- `kInstanceExtensionNames`
- `UnsupportedStructureTypeString`

**Comment by spencer-lunarg** [comment]
going to do this right now, this is a relativity simple, yet real useful suggestion!

**Comment by spencer-lunarg** [comment]
Actually added another few from `vk_object_types.cpp`

I think I got all the ones I could find, but @jimblandy if you find anymore, always happy with these types of issues!
