### ISSUE TITLE
layer complain format (1000054006) not fall within the begin..end range  of the core VkFormat enumeration tokens and is not an extension added token

### ISSUE THREAD

**Issue by vkensou** [KhronosGroup/Vulkan-ValidationLayers#7369]
**Environment:**
 - OS: Windows
 - GPU and driver version: NVIDIA RTX 2060
 - SDK or header version if building from repo: 1.3.268 download from lunarg.com
 - Options enabled (synchronization, best practices, etc.): Validation

**Describe the Issue**

the validation layer complain format (1000054000) - format (1000054007) does not fall within the begin..end range of the core VkFormat enumeration tokens and is not an extension added token.

**Expected behavior**

1000054000 is a VkFormat VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG.
1000054007 is a VkFormat VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG

**Valid Usage ID**
VUID-vkGetPhysicalDeviceFormatProperties-format-parameter(ERROR / SPEC): msgNum: 1256049554 - Validation Error: [ VUID-vkGetPhysicalDeviceFormatProperties-format-parameter ] | MessageID = 0x4addcb92 | vkGetPhysicalDeviceFormatProperties()

**Additional context**

<details>
<summary>code or terminal output</summary>

```sh
VUID-vkGetPhysicalDeviceFormatProperties-format-parameter(ERROR / SPEC): msgNum: 1256049554 - Validation Error: [ VUID-vkGetPhysicalDeviceFormatProperties-format-parameter ] | MessageID = 0x4addcb92 | vkGetPhysicalDeviceFormatProperties(): format (1000054000) does not fall within the begin..end range of the core VkFormat enumeration tokens and is not an extension added token. The Vulkan spec states: format must be a valid VkFormat value (https://vulkan.lunarg.com/doc/view/1.3.268.0/windows/1.3-extensions/vkspec.html#VUID-vkGetPhysicalDeviceFormatProperties-format-parameter)
    Objects: 0

VUID-vkGetPhysicalDeviceFormatProperties-format-parameter(ERROR / SPEC): msgNum: 1256049554 - Validation Error: [ VUID-vkGetPhysicalDeviceFormatProperties-format-parameter ] | MessageID = 0x4addcb92 | vkGetPhysicalDeviceFormatProperties(): format (1000054001) does not fall within the begin..end range of the core VkFormat enumeration tokens and is not an extension added token. The Vulkan spec states: format must be a valid VkFormat value (https://vulkan.lunarg.com/doc/view/1.3.268.0/windows/1.3-extensions/vkspec.html#VUID-vkGetPhysicalDeviceFormatProperties-format-parameter)
    Objects: 0
VUID-vkGetPhysicalDeviceFormatProperties-format-parameter(ERROR / SPEC): msgNum: 1256049554 - Validation Error: [ VUID-vkGetPhysicalDeviceFormatProperties-format-parameter ] | MessageID = 0x4addcb92 | vkGetPhysicalDeviceFormatProperties(): format (1000054002) does not fall within the begin..end range of the core VkFormat enumeration tokens and is not an extension added token. The Vulkan spec states: format must be a valid VkFormat value (https://vulkan.lunarg.com/doc/view/1.3.268.0/windows/1.3-extensions/vkspec.html#VUID-vkGetPhysicalDeviceFormatProperties-format-parameter)
    Objects: 0
VUID-vkGetPhysicalDeviceFormatProperties-format-parameter(ERROR / SPEC): msgNum: 1256049554 - Validation Error: [ VUID-vkGetPhysicalDeviceFormatProperties-format-parameter ] | MessageID = 0x4addcb92 | vkGetPhysicalDeviceFormatProperties(): format (1000054003) does not fall within the begin..end range of the core VkFormat enumeration tokens and is not an extension added token. The Vulkan spec states: format must be a valid VkFormat value (https://vulkan.lunarg.com/doc/view/1.3.268.0/windows/1.3-extensions/vkspec.html#VUID-vkGetPhysicalDeviceFormatProperties-format-parameter)
    Objects: 0
VUID-vkGetPhysicalDeviceFormatProperties-format-parameter(ERROR / SPEC): msgNum: 1256049554 - Validation Error: [ VUID-vkGetPhysicalDeviceFormatProperties-format-parameter ] | MessageID = 0x4addcb92 | vkGetPhysicalDeviceFormatProperties(): format (1000054004) does not fall within the begin..end range of the core VkFormat enumeration tokens and is not an extension added token. The Vulkan spec states: format must be a valid VkFormat value (https://vulkan.lunarg.com/doc/view/1.3.268.0/windows/1.3-extensions/vkspec.html#VUID-vkGetPhysicalDeviceFormatProperties-format-parameter)
    Objects: 0
VUID-vkGetPhysicalDeviceFormatProperties-format-parameter(ERROR / SPEC): msgNum: 1256049554 - Validation Error: [ VUID-vkGetPhysicalDeviceFormatProperties-format-parameter ] | MessageID = 0x4addcb92 | vkGetPhysicalDeviceFormatProperties(): format (1000054005) does not fall within the begin..end range of the core VkFormat enumeration tokens and is not an extension added token. The Vulkan spec states: format must be a valid VkFormat value (https://vulkan.lunarg.com/doc/view/1.3.268.0/windows/1.3-extensions/vkspec.html#VUID-vkGetPhysicalDeviceFormatProperties-format-parameter)
    Objects: 0
VUID-vkGetPhysicalDeviceFormatProperties-format-parameter(ERROR / SPEC): msgNum: 1256049554 - Validation Error: [ VUID-vkGetPhysicalDeviceFormatProperties-format-parameter ] | MessageID = 0x4addcb92 | vkGetPhysicalDeviceFormatProperties(): format (1000054006) does not fall within the begin..end range of the core VkFormat enumeration tokens and is not an extension added token. The Vulkan spec states: format must be a valid VkFormat value (https://vulkan.lunarg.com/doc/view/1.3.268.0/windows/1.3-extensions/vkspec.html#VUID-vkGetPhysicalDeviceFormatProperties-format-parameter)
    Objects: 0
VUID-vkGetPhysicalDeviceFormatProperties-format-parameter(ERROR / SPEC): msgNum: 1256049554 - Validation Error: [ VUID-vkGetPhysicalDeviceFormatProperties-format-parameter ] | MessageID = 0x4addcb92 | vkGetPhysicalDeviceFormatProperties(): format (1000054007) does not fall within the begin..end range of the core VkFormat enumeration tokens and is not an extension added token. The Vulkan spec states: format must be a valid VkFormat value (https://vulkan.lunarg.com/doc/view/1.3.268.0/windows/1.3-extensions/vkspec.html#VUID-vkGetPhysicalDeviceFormatProperties-format-parameter)
    Objects: 0
```

</details>

**Comment by spencer-lunarg** [comment]
I have another todo to improve that error message, but the issue is you never enabled `VK_IMG_format_pvrtc` and so using those enum values for `VkFormat` are not valid

**Comment by vkensou** [comment]
> `VK_IMG_format_pvrtc`

I am using Windows, so I can't enable `VK_IMG_format_pvrtc`. 
In my understanding, if the VkFormat is not supported, it is appropriate that vkGetPhysicalDeviceFormatProperties return false instead of a Validation Error.

**Comment by spencer-lunarg** [comment]
`vkGetPhysicalDeviceFormatProperties` is a void function so not sure what it would return

If a driver was shipped with an old header that doesn't have `VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG` it is essentially a garbage enum value to it, so the VU is there to move the responsibility to the app to not call with an unknown format

**Comment by vkensou** [comment]
> `vkGetPhysicalDeviceFormatProperties` is a void function so not sure what it would return

Regarding the return value of vkGetPhysicalDeviceFormatProperties, what I mean is its third parameter pFormatProperties. 

I understand your concern about drivers using outdated header files. So, for VkFormat introduced in Vulkan 1.1 or later, such as VK_FORMAT_G8B8G8R8_422_UNORM and VK_FORMAT_G8_B8R8_2PLANE_444_UNORM, should app also ensure that they are not passed carelessly?

**Comment by spencer-lunarg** [comment]
To use `VK_FORMAT_G8B8G8R8_422_UNORM` the app must either

1. Create a 1.1 Vulkan instance
2. Use 1.0 and enable `VK_KHR_sampler_ycbcr_conversion`

This is not limited to `VkFormat`, the idea is there will always be new enum values added over time, so the corresponding Vulkan Version or Extension needs to be enabled to ensure the driver (or downstream layers) are aware it exists

In practices, for a call like `vkGetPhysicalDeviceFormatProperties`, I assume most (if not all) drivers would have a switch statement and just ignore anything if it didn't see the format, but it is still undefined behavior, therefor the validation layers need to produce an error here

**Comment by vkensou** [comment]
> To use `VK_FORMAT_G8B8G8R8_422_UNORM` the app must either
> 
> 1. Create a 1.1 Vulkan instance
> 2. Use 1.0 and enable `VK_KHR_sampler_ycbcr_conversion`
> 
> This is not limited to `VkFormat`, the idea is there will always be new enum values added over time, so the corresponding Vulkan Version or Extension needs to be enabled to ensure the driver (or downstream layers) are aware it exists
> 
> In practices, for a call like `vkGetPhysicalDeviceFormatProperties`, I assume most (if not all) drivers would have a switch statement and just ignore anything if it didn't see the format, but it is still undefined behavior, therefor the validation layers need to produce an error here

Thank you for your patient reply. I understand now.

**Comment by spencer-lunarg** [comment]
@vkensou you aren't the first to ask, it isn't obvious, but glad to help

again, I have a todo to have it where we (the Validation Layers) actually know which enum it is, we can display a better message of what you need to enable

**Comment by spencer-lunarg** [comment]
@vkensou thanks for raising this, gave me the energy to **finally** make this massive PR which next time will tell you nicely what extensions you are missing instead of the cryptic "out of range" error it was giving https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7420

**Comment by vkensou** [comment]
> @vkensou thanks for raising this, gave me the energy to **finally** make this massive PR which next time will tell you nicely what extensions you are missing instead of the cryptic "out of range" error it was giving #7420

I am very glad that I can also make a small contribution. 
I found another issue: ycbcr related formats.
I start a VkInstance with 1.0, and enable extension: VK_KHR_sampler_ycbcr_conversion. Then query format: VK_FORMAT_G16B16G16R16_422_UNORM, VK_FORMAT_B16G16R16G16_422_UNORM and etc. There are still these error:
```
VUID-vkGetPhysicalDeviceFormatProperties-format-parameter(ERROR / SPEC): msgNum: 1256049554 - Validation Error: [ VUID-vkGetPhysicalDeviceFormatProperties-format-parameter ] | MessageID = 0x4addcb92 | vkGetPhysicalDeviceFormatProperties(): format (1000156027) does not fall within the begin..end range of the core VkFormat enumeration tokens and is not an extension added token. The Vulkan spec states: format must be a valid VkFormat value (https://vulkan.lunarg.com/doc/view/1.3.268.0/windows/1.3-extensions/vkspec.html#VUID-vkGetPhysicalDeviceFormatProperties-format-parameter)
    Objects: 0
VUID-vkGetPhysicalDeviceFormatProperties-format-parameter(ERROR / SPEC): msgNum: 1256049554 - Validation Error: [ VUID-vkGetPhysicalDeviceFormatProperties-format-parameter ] | MessageID = 0x4addcb92 | vkGetPhysicalDeviceFormatProperties(): format (1000156028) does not fall within the begin..end range of the core VkFormat enumeration tokens and is not an extension added token. The Vulkan spec states: format must be a valid VkFormat value (https://vulkan.lunarg.com/doc/view/1.3.268.0/windows/1.3-extensions/vkspec.html#VUID-vkGetPhysicalDeviceFormatProperties-format-parameter)
    Objects: 0
...
```

**Comment by spencer-lunarg** [comment]
aww interesting, this is a good edge case, thanks for catching it!

The issue is the function is a instance function (it doesn't take a `vkDevice`, so you can query it before ever making a device, so you would't be able to know if it is valid or not yet
