### ISSUE TITLE
Pipeline barrier validation seems to classify vkCmdFillBuffer() as a copy command instead of a clear command

### ISSUE THREAD

**Issue by litherum** [KhronosGroup/Vulkan-ValidationLayers#7406]
**Environment:**
 - OS: Windows 11 Pro 23H2 22631.3085 Windows Feature Experience Pack 1000.22684.1000.0
 - GPU and driver version: NVIDIA GeForce RTX 2080 Ti 31.0.15.5123
 - SDK or header version if building from repo: 1.3.271 
 - Options enabled (synchronization, best practices, etc.): `VK_LAYER_KHRONOS_validation`, `VK_EXT_debug_utils`, `VK_EXT_validation_features`, `Synchronization2`

**Describe the Issue**

Create 2 buffers: a source buffer and a destination buffer. The goal is to use `vkCmdFillBuffer()` to fill the first buffer with 0s, and then use `vkCmdCopyBuffer2()` to copy the 0s from the first buffer to the second buffer. Pipeline barriers are needed before and between the two commands.

The spec [lists](https://registry.khronos.org/vulkan/specs/1.3/html/chap18.html#vkCmdFillBuffer) `vkCmdFillBuffer()` as a clear command, so the first pipeline barrier needs to transition the source buffer from `VK_PIPELINE_STAGE_2_NONE`/`VK_ACCESS_2_NONE` to `VK_PIPELINE_STAGE_2_CLEAR_BIT`/`VK_ACCESS_2_TRANSFER_WRITE_BIT`. Then `vkCmdFillBuffer()` can fill it.

Then, we need to transition the source buffer to `VK_PIPELINE_STAGE_2_COPY_BIT`/`VK_ACCESS_2_TRANSFER_READ_BIT` to get it ready to be the source of `vkCmdCopyBuffer2()`. (The destination buffer also needs to be transitioned from  `VK_PIPELINE_STAGE_2_NONE`/`VK_ACCESS_2_NONE` to `VK_PIPELINE_STAGE_2_COPY_BIT`/`VK_ACCESS_2_TRANSFER_WRITE_BIT`.) Then, we can `vkCmdCopyBuffer2()` the source buffer to the destination buffer.

However, at this point, the validation layers say there is a read-after-write hazard on the source buffer, indicating that its pipeline barrier between the two commands is incorrect.

If you change the program to replace all uses of `VK_PIPELINE_STAGE_2_CLEAR_BIT` with `VK_PIPELINE_STAGE_2_COPY_BIT`, the program passes validation by the validation layers. This indicates that the validation layers classify `vkCmdFillBuffer()` as a copy command instead of a clear command. This is incorrect, though - the spec [indicates](https://registry.khronos.org/vulkan/specs/1.3/html/chap18.html#vkCmdFillBuffer) `vkCmdFillBuffer()` is a clear command.

**Expected behavior**

The validation layers indicate the program passes validation.

**Additional context**

<details>
<summary>code</summary>

Sample program: [BlitTransferTest.zip](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/14094332/BlitTransferTest.zip)

</details>

<details>
<summary>validation message</summary>

```
SYNC-HAZARD-READ-AFTER-WRITE(ERROR / SPEC): msgNum: -455515022 - Validation Error: [ SYNC-HAZARD-READ-AFTER-WRITE ] Object 0: handle = 0x4c5b620000000007, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0xe4d96472 | vkCmdCopyBuffer2():  Hazard READ_AFTER_WRITE for srcBuffer VkBuffer 0x4c5b620000000007[], region 0. Access info (usage: SYNC_COPY_TRANSFER_READ, prior_usage: SYNC_COPY_TRANSFER_WRITE, write_barriers: 0, command: vkCmdFillBuffer, seq_no: 2, reset_no: 1).
    Objects: 1
        [0] 0x4c5b620000000007, type: 9, name: NULL
```

</details>

**Comment by artem-lunarg** [comment]
@litherum I agree that `vkCmdFillBuffer` accesses are defined on CLEAR stage and not on COPY stage. Thanks for noticing this.

Quotes from the spec for documentation purposes:
> VK_PIPELINE_STAGE_2_COPY_BIT specifies the execution of all [copy commands](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#copies)

> VK_PIPELINE_STAGE_2_CLEAR_BIT specifies the execution of [clear commands](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#clears)

**Comment by plasmacel** [comment]
Was it ever fixed? The issue still presents in Vulkan SDK 1.3.280.

**Comment by artem-lunarg** [comment]
@litherum Yes, it was fixed, we also have pretty good test coverage for that issue to detect regressions and they all pass. Why do you think the issue is still present?
