### ISSUE TITLE
No validation error on missing layout information in final pipeline library

### ISSUE THREAD

**Issue by madeeha** [KhronosGroup/Vulkan-ValidationLayers#7408]
**Environment:**
 - OS: Linux
 - GPU and driver version: AMD and RADV
 - SDK or header version if building from repo: a8a721e307323f4ceb056d074afca41c88799816
 - Options enabled (synchronization, best practices, etc.): defaults+synchronization

**Describe the Issue**

While writing a VK-GL-CTS test, mistakenly specified the pipeline layout to null in the final link step when creating a graphics pipeline using 4 graphics pipeline libraries, using VK_PIPELINE_LAYOUT_CREATE_INDEPENDENT_SETS_BIT_EXT for the pipeline layouts. This is related and somewhat similar to issue #7282.

This is illegal according to VUID-VkGraphicsPipelineCreateInfo-flags-06730, which [reads](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-flags-06730):

> If flags does not include VK_PIPELINE_CREATE_LINK_TIME_OPTIMIZATION_BIT_EXT, the pipeline includes a complete set of state specified entirely by libraries, and each library was created with a VkPipelineLayout created with VK_PIPELINE_LAYOUT_CREATE_INDEPENDENT_SETS_BIT_EXT, then layout must be compatible with the union of the libraries' pipeline layouts

However, the layers stay silent about this problem. 
It can be reproduced by applying the patch I give you below, and running the test dEQP-VK.pipeline.pipeline_library.graphics_library.misc.independent_pipeline_layout_sets.fast_linked

**Expected behavior**
Expected to see VUID-VkGraphicsPipelineCreateInfo-flags-06730 error.

**Valid Usage ID**
VUID-VkGraphicsPipelineCreateInfo-flags-06730

**Additional context**
Patch to trigger VUID-VkGraphicsPipelineCreateInfo-flags-06730 with dEQP-VK.pipeline.pipeline_library.graphics_library.misc.independent_pipeline_layout_sets.fast_linked
```
diff --git a/external/vulkancts/modules/vulkan/pipeline/vktPipelineLibraryTests.cpp b/external/vulkancts/modules/vulkan/pipeline/vktPipelineLibraryTests.cpp
index 11a429ea7..837c86fc3 100644
--- a/external/vulkancts/modules/vulkan/pipeline/vktPipelineLibraryTests.cpp
+++ b/external/vulkancts/modules/vulkan/pipeline/vktPipelineLibraryTests.cpp
@@ -1913,7 +1913,7 @@ tcu::TestStatus PipelineLibraryMiscTestInstance::runIndependentPipelineLayoutSet
        VkGraphicsPipelineCreateInfo    finalPipelineInfo       = initVulkanStructure();
 
        finalPipelineInfo.flags         = finalPipelineFlag;
-       finalPipelineInfo.layout        = *allLayouts;
+       finalPipelineInfo.layout        = VK_NULL_HANDLE; //*allLayouts;
 
        appendStructurePtrToVulkanChain(&finalPipelineInfo.pNext, &linkingInfo);
        Move<VkPipeline> pipeline = createGraphicsPipeline(vk, device, DE_NULL, &finalPipelineInfo);
```

**Comment by spencer-lunarg** [comment]
has been on my todo list, also ` VUID-VkGraphicsPipelineCreateInfo-flags-06729` since it is related. I have started getting GPL stuff done so can quickly get this in very soon

**Comment by madeeha** [comment]
thank you
