### ISSUE TITLE
machine-dependent behavior on NegativeGpuAVOOB.Vector on Linux-AMD 6800

### ISSUE THREAD

**Issue by lunarpapillo** [KhronosGroup/Vulkan-ValidationLayers#7431]
The `NegativeGpuAVOOB.Vector` test reliably crashes on one Ubuntu host `tcubumes4`, where a supposedly identical host `tcubumes` doesn't fail.  We need a VVl engineer to determine why the tests behave differently on the two machines.

The `NegativeGpuAVOOB.Vector` test will be blacklisted from the **AMD Radeon RX 6800 XT (RADV NAVI21)** test suite until this issue is resolved.

### Failing machine `tcubumes4`
The device and driver information on the failing machine `tcubumes4` are: http://tcubuser.lunarg.localdomain:8080/view/Administration/job/Vulkaninfo/BITS=64,label=tcubumes4/17/console
```
INFO: Vulkan loader version: 1.3.204
INFO: deviceName: AMD Radeon RX 6800 XT (RADV NAVI21)
INFO: deviceType: VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
INFO: vendorID: 4098 (0x1002)
INFO: deviceID: 29631 (0x73bf)
INFO: apiVersion: 4206816 (0x4030e0) (1.3.224)
INFO: driverVersion: 92282885 (0x5802005) (22.2.5)
INFO: driverID: VK_DRIVER_ID_MESA_RADV
INFO: driverName: radv
INFO: driverInfo: Mesa 22.2.5
```
A typical failure looks like: http://tcubuser.lunarg.localdomain:8080/job/Vulkan-ValidationLayers/15545/BITS=64,BUILD_MODE=Debug,label=Linux-Mesa-6800/console
```
INFO: export VK_LAYER_TESTS_PRINT_DRIVER="on"
INFO: export NODEVICE_SELECT="1"
INFO: export VK_LAYER_PATH="/home/lunarg/.jenkins/vz3/Debug64/Vulkan-ValidationLayers/dbuild/layers"
INFO: export LD_LIBRARY_PATH="/home/lunarg/.jenkins/vz3/Debug64/Vulkan-ValidationLayers/dbuild/layers"
INFO: executing #68: /home/lunarg/.jenkins/vz3/Debug64/Vulkan-ValidationLayers/dbuild/tests/vk_layer_validation_tests --gtest_catch_exceptions=0 --gtest_filter=NegativeGpuAVOOB.Vector
WARNING: no core file "core" found - no stack trace available
WARNING: return code -11 (-0xb=SIGSEGV) on attempt 1/2- details on failing tests follow
WARNING: vvl-isolated: CRASH - test NegativeGpuAVOOB.Vector never completed
------------------------------------------------------------
[ RUN      ] NegativeGpuAVOOB.Vector
------------------------------------------------------------
```

### Passing machine `tcubumes`
The device and driver information on the failing machine `tcubumes4` are: http://tcubuser.lunarg.localdomain:8080/view/Administration/job/Vulkaninfo/BITS=64,label=tcubumes/18/console
```
INFO: Vulkan loader version: 1.3.204
INFO: deviceName: AMD Radeon RX 6800 XT (RADV NAVI21)
INFO: deviceType: VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
INFO: vendorID: 4098 (0x1002)
INFO: deviceID: 29631 (0x73bf)
INFO: apiVersion: 4206816 (0x4030e0) (1.3.224)
INFO: driverVersion: 92282885 (0x5802005) (22.2.5)
INFO: driverID: VK_DRIVER_ID_MESA_RADV
INFO: driverName: radv
INFO: driverInfo: Mesa 22.2.5-0ubuntu0.1~22.04.3
```
Note that there is a slightly different `driverInfo`, but `driverVersion` is the same.

The tests on this machine, including `NegativeGpuAVOOB.Vector`, pass: http://tcubuser.lunarg.localdomain:8080/job/Vulkan-ValidationLayers/BITS=64,BUILD_MODE=Debug,label=Linux-Mesa-6800/15571/console
```
INFO: export NODEVICE_SELECT="1"
INFO: export VK_LAYER_PATH="/home/lunarg/.jenkins/vz2/Debug64/Vulkan-ValidationLayers/dbuild/layers"
INFO: export LD_LIBRARY_PATH="/home/lunarg/.jenkins/vz2/Debug64/Vulkan-ValidationLayers/dbuild/layers"
INFO: executing #68: /home/lunarg/.jenkins/vz2/Debug64/Vulkan-ValidationLayers/dbuild/tests/vk_layer_validation_tests --gtest_catch_exceptions=0 --gtest_filter=NegativeGpuAVOOB.Vector
...
INFO: PASS: 1813 tests pass, 1245 tests skipped, 0 tests fail
```

**Comment by jeremyg-lunarg** [comment]
INFO: driverInfo: Mesa 22.2.5
vs
INFO: driverInfo: Mesa 22.2.5-0ubuntu0.1~22.04.3

probably means the bad machine has a different driver binary on it.

**Comment by jeremyg-lunarg** [comment]
tcbumes4 has this package installed hi  mesa-vulkan-drivers:amd64                  22.2.5-0ubuntu0.1~22.04.1   so it should report the exact same driver info.

**Comment by jeremyg-lunarg** [comment]
lunarg@tcubumes4:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"

lunarg@tcubumes:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"

**Comment by spencer-lunarg** [comment]
Can confirm RADV Mesa 24 has no problem with this test on many re-runs

**Comment by spencer-lunarg** [comment]
this was taken off the blacklist and hasn't been crashing, assume my refactoring of things fixed this test implicitly
