### ISSUE TITLE
Expecting validation error for using `VkPhysicalDeviceVulkan11Features` on Vulkan 1.1 device

### ISSUE THREAD

**Issue by MarijnS95** [KhronosGroup/Vulkan-ValidationLayers#7433]
The `VkPhysicalDeviceVulkan11Features` struct was only introduced with `VK_VERSION_1_2`. Testing on an Android phone with instance version `0.1.3.0`, a Vulkan device of `1.1.x`, with [the latest `1.3.268` prebuilt layers](https://github.com/KhronosGroup/Vulkan-ValidationLayers/releases/tag/vulkan-sdk-1.3.268.0) no validation errors are shown when passing `VkPhysicalDeviceVulkan11Features` to this device. When manually downgrading `VkApplicationInfo::apiVersion` which [is said to affect what the VVL checks against](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkApplicationInfo.html#_description) to `1.1`, the error is properly shown.

I'd assume that the Vulkan driver/device might or should not accept `VkPhysicalDeviceVulkan11Features`. Is this thought correct, or is the ICD converting these to the individual feature structs for older devices/drivers? If the former, should a VUID be issues to catch this?

**Comment by spencer-lunarg** [comment]
this is a slightly longer-then-I-wish known issue (https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5012) I am currently [very close](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7420) to having the code gen done for the enums/flags and will then go right to checking for the struct next!

**Comment by MarijnS95** [comment]
@spencer-lunarg good stuff! I was indeed looking under the totally wrong search terms when trying to find a duplicate of this.

Do you want to close this as a duplicate?

Do you want me to test that the proposed case above indeed results in a validation layer error with #7420 merged in locally?

**Comment by MarijnS95** [comment]
And should the linked PR also have `closes #5012`?

**Comment by spencer-lunarg** [comment]
happy to keep this open and I plan to use this issue to write a test case for your issue

... hopefully by end of this week this will be done and I can go through and closes **all** the related issues lol (they are probably all slightly overlapping each other now)

**Comment by MarijnS95** [comment]
Thanks @spencer-lunarg! Your branch already helped me uncover some issues in our 1.1 fallback path (and stretching beyond that...). It doesn't yet seem to error out on having `VkPhysicalDeviceVulkan11Features` in `pNext` on a `1.1` device, but I'll gladly await your test-case for this :)
