### ISSUE TITLE
gpuav: Crash in image layout state running performance trace

### ISSUE THREAD

**Issue by jeremyg-lunarg** [KhronosGroup/Vulkan-ValidationLayers#7435]
**Environment:**
 - OS: Windows 
 - GPU and driver version: RTX 
 - SDK or header version if building from repo: you need a revert of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7183 to make it far enough to hit this.
 - Options enabled (synchronization, best practices, etc.): GPU-AV

**Describe the Issue**
thesurge2-1-10000 trace crashes with the following stack trace:

```
common_assert_to_message_box<wchar_t>(const wchar_t * const, const wchar_t * const, const unsigned int, void * const)
common_assert<wchar_t>(const wchar_t * const, const wchar_t * const, const unsigned int, void * const)
_wassert(const wchar_t *, const wchar_t *, unsigned int)
image_layout_map::ImageSubresourceLayoutMap::UpdateFrom(const image_layout_map::ImageSubresourceLayoutMap &)
vvl::CommandBuffer::ExecuteCommands(vvl::enumeration<VkCommandBuffer_T * const,VkCommandBuffer_T * const *>)
ValidationStateTracker::PreCallRecordCmdExecuteCommands(VkCommandBuffer_T *, unsigned int, VkCommandBuffer_T * const *, const RecordObject &)
vulkan_layer_chassis::CmdExecuteCommands(VkCommandBuffer_T *, unsigned int, VkCommandBuffer_T * const *)
```

in` image_layout_map::ImageSubresourceLayoutMap::UpdateFrom()`, the `const ImageSubresourceLayoutMap& other` argument is invalid memory. In `CommandBuffer::ExecuteCommands()`, the sub_cb_subres_map pointer is entirely invalid memory but the `image_state `pointer looks ok.

**Comment by arno-lunarg** [comment]
Did https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7444 also fixed this?

**Comment by jeremyg-lunarg** [comment]
> Did #7444 also fix this?

I won't be able to re-test until I get back to boulder on monday night

**Comment by jeremyg-lunarg** [comment]
> Did #7444 also fix this?

No, I'm still crashing with tip of main (1518a84bb) which includes the fix for #7444

**Comment by jeremyg-lunarg** [comment]
The crash occurs between frames 2000 - 2325 of the trace and appears to be at the end of a loading screen. It is preceded by several of these errors:
```
UNASSIGNED-Descriptor destroyed(ERROR / SPEC): msgNum: -1575303641 - Validation Error: [ UNASSIGNED-Descriptor destroyed ] Object 0: handle = 0x2596ef7a9e0, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0xa21ac627 | vkCmdDrawIndexedIndirect():  (set = 0, binding = 20) Descriptor index 0 references a resource that was destroyed. Command buffer (0x259afa25b90). Draw Index 0x133. Pipeline (0x2598cfba860). Shader Module (0x259a0996fa0). Shader Instruction Index = 862.  Stage = Fragment.  Fragment coord (x,y) = (528.5, 393.5).  Unable to find SPIR-V OpLine for source information.  Build shader with debug info to get source information.
    Objects: 1
```
So probably something in the descriptor in use feedback mechanism that feeds into ILT validation isn't skipping the bad descriptor correctly

**Comment by jeremyg-lunarg** [comment]
Enabling Handle Wrapping avoids the crash. It now seems like a handle reuse bug in the code that manages vvl::CommandBuffer::image_layout_map.
