### ISSUE TITLE
Missing Android Binaries for 1.3.275.0

### ISSUE THREAD

**Issue by juan-kitware** [KhronosGroup/Vulkan-ValidationLayers#7449]
Looks like the SDK android pipeline failed to build on x86. As a result no new Android binaries have been published on GitHub:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/actions/workflows/sdk_android_build.yml
https://github.com/KhronosGroup/Vulkan-ValidationLayers/actions/runs/7558017693/job/20578570059

To address the issue build the validation layers with x86 and figure out the build error:

> python scripts/android.py --config Release --app-abi x86 --app-stl c++_static

Not sure exactly what went wrong since the logs for this run have expired and are no longer available. Maybe just re-running the job will fix the issue? Not sure.

**Comment by spencer-lunarg** [comment]
@juan-kitware I am not sure how you were aware/caught this, but thanks for bringing this to our attention! I have re-ran the job and will continue to monitor it. If you ever noticed or find any other issue, please don't feel shy to raise future concerns

**Comment by juan-kitware** [comment]
I believe the problem is caused by an upgrade to [artifact@v4](https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/5fcc34d5e7a80a79eb5d2838792ab752d1815cf3)

The fix seems simple though:
https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#multiple-uploads-to-the-same-named-artifac

Running a job with artifact@v3 should tell you quickly if I am right though.

**Comment by spencer-lunarg** [comment]
I created https://github.com/KhronosGroup/Vulkan-ValidationLayers/tree/spencer-lunarg-patch-1

I just need to figure out how to kick off the action with it (cc @johnzupin)

**Comment by johnzupin** [comment]
You would need to create a tag in the form of `vulkan-sdk-*` on your forked repo. I have one going on my fork right now at https://github.com/johnzupin/Vulkan-ValidationLayers/actions/runs/7792879421.  If this works you should merge in your change, I can cherry pick it to the sdk branch, and then I can redo the tag so it publishes.

**Comment by johnzupin** [comment]
Reverting it back works as a fix for now. It created the release on my fork: https://github.com/johnzupin/Vulkan-ValidationLayers/releases/tag/vulkan-sdk-1.9.999.1

**Comment by juan-kitware** [comment]
Closing since new binaries have been posted:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/releases/tag/vulkan-sdk-1.3.275.0
