### ISSUE TITLE
Incorrect warning with VkPipelineTessellationDomainOriginStateCreateInfo

### ISSUE THREAD

**Issue by tmerilehti** [KhronosGroup/Vulkan-ValidationLayers#747]
It seems that `VkPipelineTessellationDomainOriginStateCreateInfo` is not recognized by the layers when included in the `pNext` chain of `VkPipelineTessellationStateCreateInfo.`

When `VkPipelineTessellationDomainOriginStateCreateInfo` is included, the following warning will show up:

`WARNING:  [ VUID-VkGraphicsPipelineCreateInfo-pNext-pNext ] Object: VK_NULL_HANDLE (Type = 0) | vkCreateGraphicsPipelines: value of pCreateInfos[0].pTessellationState->pNext must be NULL. This warning is based on the Valid Usage documentation for version 101 of the Vulkan header.  It is possible that you are using a struct from a private extension or an extension that was added to a later version of the Vulkan header, in which case your use of pCreateInfos[0].pTessellationState->pNext is perfectly valid but is not guaranteed to work correctly with validation enabled The Vulkan spec states: Each pNext member of any structure (including this one) in the pNext chain must be either NULL or a pointer to a valid instance of VkPipelineDiscardRectangleStateCreateInfoEXT or VkPipelineRepresentativeFragmentTestStateCreateInfoNV (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-pNext-pNext) (code 0x00000000 from Validation at Unknown:0)`

I assume the validation is done [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/9f30087b9d9b14cf6bd8780f71f60530034ad35b/layers/parameter_validation_utils.cpp#L1040) in the `validate_struct_pnext(),` where the `allowed_struct_names` is NULL and `allowed_type_count` is 0. 

This warning can be reproduced in Vulkan CTS, when running dEQP-VK.tessellation.winding.* tests.

**Comment by locke-lunarg** [comment]
[Pull request #765](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/765)
