### ISSUE TITLE
`SYNC_FRAGMENT_SHADER_INPUT_ATTACHMENT_READ` being considered outside of a render pass

### ISSUE THREAD

**Issue by glebov-andrey** [KhronosGroup/Vulkan-ValidationLayers#7486]
**Environment:**
 - OS: Linux
 - SDK or header version if building from repo: current `main` (4af85c346039fd01d6b389eaa1a36242240a549f)
 - Options enabled (synchronization, best practices, etc.): synchronization (with queue submit validation)

**Describe the Issue**

As far as I can tell from the spec., input attachment reads happen in the `COLOR_ATTACHMENT_OUTPUT`/`EARLY_FRAGMENT_TESTS` stage with `COLOR_ATTACHMENT_READ`/`DEPTH_STENCIL_ATTACHMENT_READ` access from the point of view of commands outside of the render pass in question. Despite this I'm getting some validation errors with either the submitted or prior usage reported as `SYNC_FRAGMENT_SHADER_INPUT_ATTACHMENT_READ`.

Here's an example error message:
```
Validation Error: [ SYNC-HAZARD-WRITE-AFTER-READ ] Object 0: handle = 0x55b83a4f5b10, name = Graphics queue, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0x376bc9df | vkQueueSubmit2():
Hazard WRITE_AFTER_READ for entry 21, VkCommandBuffer 0x7f9b380f2f40[Command Buffer | draw_water],
Submitted access info (submitted_usage: SYNC_IMAGE_LAYOUT_TRANSITION, command: vkCmdPipelineBarrier2, seq_no: 1, VkImage 0xca0b160000000085[graph_res#6/1_image] <...A BUNCH OF IMAGES...>, reset_no: 1).
Access info (prior_usage: SYNC_FRAGMENT_SHADER_INPUT_ATTACHMENT_READ, read_barriers: VK_PIPELINE_STAGE_2_BOTTOM_OF_PIPE_BIT, queue: VkQueue 0x55b83a4f5b10[Graphics queue], submit: 18, batch: 0, batch_tag: 572, command: vkCmdDraw, command_buffer: VkCommandBuffer 0x7f9a840a9600[Command Buffer | copy_gbuffer], seq_no: 3, reset_no: 1, | vkCmdDraw(3, 1, 0, 0)).
```
Given the list of images in the error it could be any of 3 images - two color images and one depth/stencil. It's most likely the depth/stencil image causing the error (see debugger output below) but all these images follow the same usage pattern:
- gbuffer pass uses them as color / depth-stencil attachments
- some passes use the depth aspect of the depth/stencil image as an input attachment
- `vkCmdPipelineBarrier2`
  for color:
    ```
    srcStageMask VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT
    srcAccessMask VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT
    dstStageMask VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT
    dstAccessMask VK_ACCESS_2_COLOR_ATTACHMENT_READ_BIT
    oldLayout   VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL
    newLayout   VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL
    ```
  for depth/stencil:
    ```
    srcStageMask VK_PIPELINE_STAGE_2_EARLY_FRAGMENT_TESTS_BIT | VK_PIPELINE_STAGE_2_LATE_FRAGMENT_TESTS_BIT
    srcAccessMask VK_ACCESS_2_NONE
    dstStageMask VK_PIPELINE_STAGE_2_EARLY_FRAGMENT_TESTS_BIT
    dstAccessMask VK_ACCESS_2_DEPTH_STENCIL_ATTACHMENT_READ_BIT
    oldLayout   VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL
    newLayout   VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL
    ```
    (the results of previous write access have been made available and visible to `*_FRAGMENT_TESTS` in a previous pass)
- `copy_gbuffer` uses these images as input attachments (`loadOP=LOAD`, `storeOp=NONE`) (only the depth aspect of the d/s image is used as an input attachment)
- `vkCmdPipelineBarrier2` (this is where the error occurs)
  for color:
    ```
    srcStageMask VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT
    srcAccessMask VK_ACCESS_2_NONE
    dstStageMask VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT
    dstAccessMask VK_ACCESS_2_COLOR_ATTACHMENT_READ_BIT | VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT
    oldLayout   VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL
    newLayout   VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL
    ```
  for depth/stencil:
    ```
    srcStageMask VK_PIPELINE_STAGE_2_EARLY_FRAGMENT_TESTS_BIT
    srcAccessMask VK_ACCESS_2_NONE
    dstStageMask VK_PIPELINE_STAGE_2_EARLY_FRAGMENT_TESTS_BIT | VK_PIPELINE_STAGE_2_LATE_FRAGMENT_TESTS_BIT
    dstAccessMask VK_ACCESS_2_DEPTH_STENCIL_ATTACHMENT_READ_BIT | VK_ACCESS_2_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT
    oldLayout   VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL
    newLayout   VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL
    ```

There are a few other similar cases. Some are `READ_AFTER_WRITE`, some are `WRITE_AFTER_READ`. In all these cases it seems that the pair of operations is `SYNC_FRAGMENT_SHADER_INPUT_ATTACHMENT_READ` and `SYNC_IMAGE_LAYOUT_TRANSITION` in some order.

**Additional context**

The odd thing is that I haven't yet been able to create a synthetic example which causes the error.
So I'm attaching the stack trace and the debugger output of the `HazardResult` which causes the error (this is for the depth/stencil image based on access flags).

As we can see from the debugger `last_reads` contains both a `SYNC_EARLY_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_READ` (bit `41`) entry, which is fine, and the problematic `SYNC_FRAGMENT_SHADER_INPUT_ATTACHMENT_READ` (bit `35`) entry.

<details>
<summary>Stack trace</summary>

```
[libVkLayer_khronos_validation.so] debug_log_msg logging.cpp:211
[libVkLayer_khronos_validation.so] LogMsg logging.cpp:465
[libVkLayer_khronos_validation.so] ValidationObject::LogError chassis.h:2355
[libVkLayer_khronos_validation.so] ReplayState::DetectFirstUseHazard sync_op.cpp:1234
[libVkLayer_khronos_validation.so] SyncOpPipelineBarrier::ReplayValidate sync_op.cpp:374
[libVkLayer_khronos_validation.so] ReplayState::ValidateFirstUse sync_op.cpp:1257
[libVkLayer_khronos_validation.so] QueueBatchContext::DoQueueSubmitValidate sync_submit.cpp:665
[libVkLayer_khronos_validation.so] SyncValidator::ValidateQueueSubmit sync_validation.cpp:2920
[libVkLayer_khronos_validation.so] SyncValidator::PreCallValidateQueueSubmit2 sync_validation.cpp:2982
[libVkLayer_khronos_validation.so] vulkan_layer_chassis::QueueSubmit2 chassis.cpp:5107
```

</details>

<details>
<summary>Debugger output</summary>

![Screenshot_20240209_125153](https://github.com/KhronosGroup/Vulkan-ValidationLayers/assets/5797263/2c55c318-268c-42b8-ac2c-950c687a42b0)

</details>

**Comment by artem-lunarg** [comment]
> As far as I can tell from the spec., input attachment reads happen in the COLOR_ATTACHMENT_OUTPUT/EARLY_FRAGMENT_TESTS stage with COLOR_ATTACHMENT_READ/DEPTH_STENCIL_ATTACHMENT_READ access from the point of view of commands outside of the render pass in question. Despite this I'm getting some validation errors with either the submitted or prior usage reported as SYNC_FRAGMENT_SHADER_INPUT_ATTACHMENT_READ.

@glebov-andrey I still have to check the entire scenario, but reading only the above quote I don't see this as an unexpected behavior.

Yes, the code that is *before* the render pass can synchronize with the input attachment load operation through accesses/stages you mentioned above (and don't need to consider accesses done by the commands inside the renderpass). But commands *after* the render pass have to synchronize directly with a draw command accesses if NONE store operation is used.

After the load operation,  the draw command will use `SYNC_FRAGMENT_SHADER_INPUT_ATTACHMENT_READ` access/stage. If store operation is NONE then that access will be the last one, and subsequent input attachment layout transition will see exactly that access.

**Comment by glebov-andrey** [comment]
> [...] But commands after the render pass have to synchronize directly with a draw command accesses if NONE store operation is used.
> After the load operation, the draw command will use SYNC_FRAGMENT_SHADER_INPUT_ATTACHMENT_READ access/stage. If store operation is NONE then that access will be the last one, and subsequent input attachment layout transition will see exactly that access.

Oh, that's interesting. I was under the impression that the render pass model made it so that _logically_ all attachment reads and writes were made by `loadOp`/`storeOp`, and not by the shaders (in other words the fragment shader's `subassLoad` gets its input from `COLOR_ATTACHMENT_OUTPUT-READ`/`EARLY_FRAGMENT_TESTS-READ` stages, and not directly from the framebuffer attachment).
But I suppose what you said makes more sense for non-tiled architectures where there might be no difference between an input attachment and a sampled image, and thus no actual `loadOp` for the attachment.
Maybe this is something which could be better described by the spec though?

**Comment by artem-lunarg** [comment]
>  I was under the impression that the render pass model made it so that logically all attachment reads and writes were made by loadOp/storeOp, and not by the shaders 

I agree, this sounds logical. I need to read more about this and maybe ask people on the team. I'm also learning this along the way.

**Comment by artem-lunarg** [comment]
@glebov-andrey Sorry for the confusion, I think you are right. The part of the spec that explains this is submission order (https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#synchronization-implicit), specifically the part related to the ordering of commands outside of render pass. Then `vkCmdPipelineBarreir`'s scopes are defined based on submission order and if a barrier command is recorded outside of render pass, then it cannot synchronize with commands/accesses from a subpass according to submission order definition.

**Comment by artem-lunarg** [comment]
Added repro case: https://github.com/artem-lunarg/Vulkan-ValidationLayers/commit/784f8e841083663a1694fb299c66fe0488548b4e

**Comment by artem-lunarg** [comment]
I think the reason it did not fail for COLOR attachment is mostly luck. last_reads contains loadOp accesses but also draw accesses. Synchronization outside of render passs should not take into account draw accesses (based on how pipeline barriers are defined with regard to submission order). But that's not what current code does - it tests transition against all last_reads, which includes draw accesses.

Why COLOR is lucky? Layout transition synchronizes with COLOR_ATTACHMENT_OUTPUT stage and that stage includes execution of FRAGMENT stage (according to stage order). So the test against draw command's FRAGMENT access (that shouldn't be done in the first place) is successful .

DEPTH is not lucky. Layout transition synchronizes with EARLY_FRAGMENT stage which does not include execution of FRAGMENT stage. The test against draw command's FRAGMENT access is unsuccessful. 

Idea to implement: being outside the render pass, we need to test only against the reads that are outside the render pass, according to the submission order definition of "outside render pass".

**Comment by artem-lunarg** [comment]
The ticket is opened to clarify the spec.

**Comment by glebov-andrey** [comment]
@artem-lunarg Thank you for clarifying all of this, and for opening the ticket!
I guess this can be closed then - the issue is on the app's side.
