### ISSUE TITLE
Incorrect error for image memory with VkBindImageMemorySwapchainInfoKHR

### ISSUE THREAD

**Issue by janetliuAMD** [KhronosGroup/Vulkan-ValidationLayers#749]
It seems the validation layer doesn't understand images with memory bound to swapchain memory using `VkBindImageMemorySwapchainInfoKHR` in the `pNext` chain of `VkBindImageMemoryInfo` through a `vkBindImageMemory2KHR()` call, and will generate error messages of "**no memory bound**" for such images. This might due to the `memory` field of `VkBindImageMemoryInfo` must be set to `VK_NULL_HANDLE` in this case.

For example, when such an image was used as `dstImage` in `vkCmdCopyImage()` call, the layer will report error messages like:
> Validation Error was reported: vkCmdCopyImage(): VkImage object 0x45 used with no memory bound. Memory should be bound by calling vkBindImageMemory(). The Vulkan spec states: If dstImage is non-sparse then it must be bound completely and contiguously to a single VkDeviceMemory object (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdCopyImage-dstImage-00132)

**Comment by locke-lunarg** [comment]
@janetliuAMD fix in [PR #994 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/994)
