### ISSUE TITLE
Option to remove the `seq_no` and `reset_no` from sync val output

### ISSUE THREAD

**Issue by DethRaid** [KhronosGroup/Vulkan-ValidationLayers#7491]
Sync validation tells you the sequence number and reset number of the command that generated the validation error. This is useful for some applications, but not all. I'd like to request an option in the Vulkan Configurator to remove those numbers from sync val output, reducing unnecessary information for applications that have too many commands to count or which don't re-use command buffers

**Comment by artem-lunarg** [comment]
I think this can be part of a more general feature that allows to configure sync error messages, for example, to specify formatting options, but also which components you need. I can imaging we can put there even more information so filtering can be increasingly more important. Not the goal for the very near future, but maybe something to figure out during the year.

**Comment by artem-lunarg** [comment]
@DethRaid `seq_no` \ `reset_no` won't be reported by default in the next SDK. Can be enabled manually if needed.

<img src="https://github.com/user-attachments/assets/7deb664c-7ed9-4e3d-ad17-9f038d8cb320" width=50% height=50%>
