### ISSUE TITLE
Dynamic rendering: missing validation for MSAA

### ISSUE THREAD

**Issue by QuantumDeveloper** [KhronosGroup/Vulkan-ValidationLayers#7495]
If MSAA is present and `ResolveImageView != null`, but `ResolveMode = None`, validation will not say anything. 
This will lead to situation when swapchain will not resolve render target and window will stays black.
Very hard to find root cause without validation error messages

Vulkan SDK: 1.3.275.0

**Comment by spencer-lunarg** [comment]
Thanks for raising the issue, but I want to clarify what API calls specifically are are talking about

> MSAA is present

Did you mean you had `VkPipelineMultisampleStateCreateInfo::rasterizationSamples` to something like `VK_SAMPLE_COUNT_4_BIT` ? 

If this is what you mean, then the issue would not be noticed until a `vkCmdDraw` when you match up the Rendering object with the bound pipeline

**Comment by QuantumDeveloper** [comment]
I mean this API: `VkRenderingAttachmentInfo`

![image](https://github.com/KhronosGroup/Vulkan-ValidationLayers/assets/6085009/5a850d39-f161-48c3-902b-956c400e754d)

**Comment by spencer-lunarg** [comment]
So I looked at the Spec, and if `resolveMode = None` the `resolveImageView` should be ignored

![image](https://github.com/KhronosGroup/Vulkan-ValidationLayers/assets/115671160/d6ae0e7e-9fc5-4852-911a-0c3d1a6a79f8)

So I guess was the issue that you value you passed into `resolveImageView` never got written too and that is why the image is black... if this is the case, there is nothing "invalid" about this, but would be a good thing to add to best practice layers to catch

**Comment by QuantumDeveloper** [comment]
Yep, at least just warn a user about this situation. This was working for nearly a year, but some time ago stopped. This issue took the whole day to find, so I thought someone could also be struggling from this issue

**Comment by spencer-lunarg** [comment]
Agree... there are many other subtle "is ignored" language in the spec that I feel would also be easy to not realize like this... Will get a warning in for this case, but then will look into maybe a larger way to catch the other hundreds of cases like this

Thanks for bringing this up, I appreciate being aware of these sharp edges of using Vulkan
