### ISSUE TITLE
Queue submit synchronization validation asserts/crashes in `GetDebugRegionName()`

### ISSUE THREAD

**Issue by glebov-andrey** [KhronosGroup/Vulkan-ValidationLayers#7502]
**Environment:**
 - OS: Linux
 - SDK or header version if building from repo: current `main` (9d00ae6c668895d3af97ad57e4f1771797cf3a16)
 - Options enabled (synchronization, best practices, etc.): synchronization (with queue submit validation enabled)

**Describe the Issue**

Synchronization validation crashes when queue submit validation is enabled with the assertion `record.label_command_index < label_commands.size()` in `GetDebugRegionName()` while formatting an error (called from `QueueBatchContext::FormatUsage()`).

There seem to be two cases this happens.

1. The first case is relatively simple - the value of `record.label_command_index` was `kU32Max`.
   I found another place where the `debug_name_provider` was set to `nullptr` in such a case, so I added
   ```c++
   const auto debug_name_provider = (record.label_command_index == vvl::kU32Max) ? nullptr : 
   access.debug_name_provider;
   ```
   to `FormatUsage()`, and it stopped crashing during the first frame.

2. In the second case `record.label_command_index` is `25` and `label_commands.size()` is `6`, which seems to be caused by the use of a timeline semaphore for device-to-host synchronization.
   I know timeline semaphores aren't properly supported by synchronization validation but it would be nice if it wouldn't crash :) Also I seem to recall that there is enough timeline semaphore state tracking for object lifetime checking, so maybe command buffer execution tracking is also possible.

   What appears to be happening is that VVL doesn't know that the command buffer's execution has been waited for by the host. As a result, when they get reused for different passes with a different amount of debug labels, this assertion is triggered. I'm pretty sure that this is due to command buffer reuse because the labels in `label_commands` are from a graphics pass while the command which triggers the error is a `vkCmdDispatch`.

   If I use an extra set of fences for device-to-host synchronization the error goes away (this doesn't affect the `kU32Max` case).

**Comment by artem-lunarg** [comment]
@glebov-andrey thanks for catching this. The first part should be fixed (assuming that the issue I found is the same issue you found).

**Comment by glebov-andrey** [comment]
@artem-lunarg I can confirm that #7503 fixes the first case

**Comment by artem-lunarg** [comment]
@glebov-andrey The second issue with timelines, is it the same application that also had the first issue? Wondering if in the application with timeline semaphores you still can get some benefits from debug labels (or sync validation in general), for example, from the fixed first case.

**Comment by glebov-andrey** [comment]
@artem-lunarg Yes, it is the same application.
Debug labels definitely help a lot, it's just that not everything has them.
Regarding the usefulness of sync. validation - generally it works fine, especially the non-queue-submit part. We've found multiple synchronization issues with it and it's pretty much essential for render graph development.

Queue submit is problematic though because even with async compute disabled we still have a transfer queue, which is synchronized with the graphics queue via the host with a timeline semaphore.
Even with all of that, if we ignore the transfer->graphics issues, I've still managed to find a couple bugs related to intra-queue synchronization between submits.

Ultimately, until timeline semaphores are properly supported in queue submit validation, we'll keep it disabled by default, and we can always use fences as a workaround for the second crash.

**Comment by artem-lunarg** [comment]
Thanks for the details! Submit validation was enabled recently and we are actively working to make it stable on the new use cases. Your reports are very appreciated, helps to fix submit validation faster. Talking about timeline semaphores, my intention to add support sooner than later, since it's a core feature and is actually used in practice. No specific dates yet, but ideally I'd like to start working on it after submit validation is stable, if nothing more important comes first.

**Comment by artem-lunarg** [comment]
@glebov-andrey The above PR mitigates the negative effects due to the usage of unsupported `vkWaitSemaphores`. If this does not help, because the wait is based on `vkGetSemaphoreCounterValue`, then that can be handled too, but for now trying to support only what is necessary.
