### ISSUE TITLE
Missing file (gpu_resources.cpp) referenced in BUILD.gn

### ISSUE THREAD

**Issue by toji** [KhronosGroup/Vulkan-ValidationLayers#7523]
[Recent attempts](https://dawn-review.googlesource.com/c/dawn/+/175213) to roll the validation layers into the Dawn project have failed because the [BUILD.gn](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/BUILD.gn#L172) file references the file `layers/gpu_validation/gpu_resources.cpp` which does not exist in the repo. The equivalent [CMakeLists.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/layers/CMakeLists.txt#L224) references `gpu_validation/gpu_resources.h` instead, so it appears that this is a typo.

Not having interacted with this repo much before now, I wanted to verify that was the case prior to making a pull request to fix it.

**Comment by jeremyg-lunarg** [comment]
@toji is there an easy way to make our gn BUILD, which runs as a github action, detect these errors?
