### ISSUE TITLE
Add validation for new extension VK_NV_shader_atomic_float16_vector

### ISSUE THREAD

**Issue by jeffbolznv** [KhronosGroup/Vulkan-ValidationLayers#7527]
VK_NV_shader_atomic_float16_vector was released in 1.3.278. I'll implement validation support for it.

**Comment by spencer-lunarg** [comment]
@jeffbolznv all the work should be isolated to `ValidateAtomicsTypes` where I capture all the atomic instructions an check types there

There is a `atomics_positive.cpp` and `atomics.cpp` 

I would look at `TEST_F(PositiveAtomic, ImageInt64)` for the simplest example to add a simple compute shader with the GLSL

**Comment by spencer-lunarg** [comment]
You will also need to update `GetAtomicInfo` to capture vector types as looking, it was really only setup for scalar
