### ISSUE TITLE
Missing validation checks when linking GPLs that contain multiple subsets

### ISSUE THREAD

**Issue by JonahT22** [KhronosGroup/Vulkan-ValidationLayers#7550]
**Environment:**
 - OS: Windows 11 x64
 - GPU and driver version: SwiftShader 

**Describe the Issue**

When the ANGLE OpenGL ES driver is using a backend Vulkan implementation that supports GPL, it will create [three pipeline libraries](https://cs.android.com/android/platform/superproject/main/+/main:external/angle/src/libANGLE/renderer/vulkan/vk_cache_utils.cpp;l=2870) that it will link into a complete pipeline:

1. Vertex Input GPL
2. Combined "Shaders" GPL (Containing both Pre-Rasterization and Fragment subsets)
3. Fragment Output GPL

I am investigating a case where I intentionally supply a different `pMultisampleState` to the Fragment and Fragment Output subsets, which should violate `VUID-VkGraphicsPipelineCreateInfo-pLibraries-06635` when these subsets are linked into a complete pipeline.

However, when linking a complete pipeline from these 3 libraries, some validation checks are skipped in `cc_pipeline_graphics.cpp`, such as `ComparePipelineMultisampleStateCreateInfo()`. If I decouple the "Shaders" GPL into separate Pre-Rasterization and Fragment libraries, I see the expected `VUID-VkGraphicsPipelineCreateInfo-pLibraries-06635` validation error.

I suspect that this is caused by how `CoreChecks::ValidateGraphicsPipelineLibrary()` gathers info for subsets within a complete linked pipeline, since [it checks each library](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/layers/core_checks/cc_pipeline_graphics.cpp#L636) for _equality_ with each subset bit, not whether the library _contains_ each subset bit.

**Expected behavior**

`VUID-VkGraphicsPipelineCreateInfo-pLibraries-06635` should be triggered for the case where `pMultisampleState` is different between the Fragment and Fragment Output subsets, and there are multiple subsets within a single GPL.

**Comment by spencer-lunarg** [comment]
thanks for bringing this up and doing some debugging on this

I figured out the simple fix was

```patch
- lib->graphics_lib_type == VK_GRAPHICS_PIPELINE_LIBRARY_FRAGMENT_SHADER_BIT_EXT
+ lib->graphics_lib_type & VK_GRAPHICS_PIPELINE_LIBRARY_FRAGMENT_SHADER_BIT_EXT
```

I was able to reproduce and writing more tests to help regressions
