### ISSUE TITLE
`ComparePipelineMultisampleStateCreateInfo()` only compares pointer addresses of pSampleMask

### ISSUE THREAD

**Issue by JonahT22** [KhronosGroup/Vulkan-ValidationLayers#7551]
**Environment:**
 - OS: Windows 10 x64
 - GPU and driver version: SwiftShader

**Describe the Issue**

I have a use case where I am linking a complete pipeline from 4 GPL subsets, and I am seeing the following validation error
```
[ VUID-VkGraphicsPipelineCreateInfo-pLibraries-06635 ] Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-pLibraries-06635 ] | MessageID = 0x9756e45a | vkCreateGraphicsPipelines(): pCreateInfos[0] Fragment Shader and Fragment Output Interface were created with different VkPipelineMultisampleStateCreateInfo.Fragment Shader pMultisampleState:
    pNext: 0x0
    rasterizationSamples: VK_SAMPLE_COUNT_1_BIT
    sampleShadingEnable: 0
    minSampleShading: 1.000000
    pSampleMask: 0x7b70834190
    alphaToCoverageEnable: 0
    alphaToOneEnable: 0
Fragment Output Interface pMultisampleState:
    pNext: 0x0
    rasterizationSamples: VK_SAMPLE_COUNT_1_BIT
    sampleShadingEnable: 0
    minSampleShading: 1.000000
    pSampleMask: 0x7b70834230
    alphaToCoverageEnable: 0
    alphaToOneEnable: 0
. The Vulkan spec states: If one element of VkPipelineLibraryCreateInfoKHR::pLibraries was created with VK_GRAPHICS_PIPELINE_LIBRARY_FRAGMENT_SHADER_BIT_EXT with a pMultisampleState that was not NULL, and if a different element of VkPipelineLibraryCreateInfoKHR::pLibraries was created with VK_GRAPHICS_PIPELINE_LIBRARY_FRAGMENT_OUTPUT_INTERFACE_BIT_EXT, the pMultisampleState used to create each library must be identically defined (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-pLibraries-06635)
```
The offending field is `pSampleMask` - in my use case, the Fragment and Fragment Output subsets were indeed created using pointers to two different VkSampleMask objects. However, I have verified that the values within both `pSampleMask` objects are identical. 

The [ComparePipelineMultisampleStateCreateInfo()](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/layers/core_checks/cc_pipeline_graphics.cpp#L449) check in `cc_pipeline_graphics.cpp` only compares the pointer address of the pSampleMasks, not the values contained within those pSampleMasks. 

Is this desired behavior? For the purpose of complete pipeline linking, it seems more useful to compare the values contained within the pSampleMask instead of the addresses.

**Comment by spencer-lunarg** [comment]
1. Thanks for reporting this
2. I agree it probably should be the values of `VkSampleMask` array and not the raw pointer instead

I will 

1. Fix this comparison and write a test
2. Create a spec issue to double check
