### ISSUE TITLE
VkPipelineSampleLocationsStateCreateInfoEXT validation

### ISSUE THREAD

**Issue by 44DA133A8B** [KhronosGroup/Vulkan-ValidationLayers#7585]
**Describe the situation in which you encountered the missing validation**

Validation layer does not verify correctness of linking of VkPipelineSampleLocationsStateCreateInfoEXT using pNext.
In the app it was linked to VkPipelineRasterizationStateCreateInfo instead of VkPipelineMultisampleStateCreateInfo.
vkCmdSetSampleLocationsEXT() had not effect because of that.

There's no VUID for vkCmdSetSampleLocationsEXT used with pipeline created without VkPipelineRasterizationStateCreateInfo.

**Valid Usage IDs requested**
VUID-VkPipelineRasterizationStateCreateInfo-pNext-pNext

**Additional Context**

No

**Comment by spencer-lunarg** [comment]
So this was an issue with the 1.3.275 SDK release, but was fixed in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7301

I just wrote a quick test I can confirm it prints the error

> Validation Error: [ VUID-VkPipelineRasterizationStateCreateInfo-pNext-pNext ] | MessageID = 0x1c82df49 | vkCreateGraphicsPipelines(): pCreateInfos[0].pRasterizationState->pNext chain includes a structure with unexpected VkStructureType VK_STRUCTURE_TYPE_PIPELINE_SAMPLE_LOCATIONS_STATE_CREATE_INFO_EXT. This error is based on the Valid Usage documentation for version 278 of the Vulkan header.

This will be in the next SDK release, sorry for the inconvenience this caused

**Comment by 44DA133A8B** [comment]
Thanks a lot!
