### ISSUE TITLE
`VUID-VkGraphicsPipelineCreateInfo-renderPass-06055` doesn't trigger

### ISSUE THREAD

**Issue by Swizzlefowl** [KhronosGroup/Vulkan-ValidationLayers#7586]
**Environment:**
 - OS: Microsoft Windows 11 Pro Version 10.0.22621 Build 22621
 - GPU and driver version: Nvidia Driver version 546.29
 - SDK or header version if building from repo: SDK version 1.3.275.0, VVL compiled from source commit-hash: `2b09a7fe46381cc842a5ee4948c482a15b5b4824`

**Describe the Issue**

If the pNext chain of `vkCreateGraphicsPipelines` doesn't contain `VkPipelineRenderingCreateInfo`, therefore the following clause applies:
> If this structure is not specified, and the pipeline does not include a [VkRenderPass](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkRenderPass.html), viewMask and colorAttachmentCount are 0, and depthAttachmentFormat and stencilAttachmentFormat are VK_FORMAT_UNDEFINED.

Specifying `VkPipelineColorBlendStateCreateInfo` with a non-zero `attachmentCount` in the same `VkGraphicsPipelineCreateInfo`, would result in an attachment count mismatch as it no longer matches the implicit `colorAttachmentCount = 0`. 

**Expected behavior**

[`VUID-VkGraphicsPipelineCreateInfo-renderPass-06055`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkGraphicsPipelineCreateInfo.html#VUID-VkGraphicsPipelineCreateInfo-renderPass-06055) should trigger.

**Additional context**

After commenting out `pipe.gp_ci_.pNext = &pipeline_rendering_info;` in `TEST_F(NegativeDynamicRendering, ColorAttachmentMismatch)` the unit test fails.

This issue was discovered with help from @PixelyIon.

**Comment by spencer-lunarg** [comment]
created PR, thanks for raising this! this was a nasty edge case I never knew about. I went through spec and this seems to be the only VU that has this edge case

**Comment by Swizzlefowl** [comment]
Just checked with the latest commit and it works as expected.
