### ISSUE TITLE
sync: False-positives in Granite samples when timeline semaphores are used

### ISSUE THREAD

**Issue by artem-lunarg** [KhronosGroup/Vulkan-ValidationLayers#7600]
The scope of this issue is restricted to two samples from the Granite renderer (https://github.com/Themaister/Granite):
`gltf-viewer-simple` and `latency-test`.

These samples are good examples of synchronization validation false positives due to missing timeline semaphore support. The above samples run error-free when binary semaphores are used.

`context.cpp`: `ext.vk12_features.timelineSemaphore = VK_FALSE` can be used to enable binary semaphores.

@HansKristian-Work for your visibility

**Comment by devshgraphicsprogramming** [comment]
Btw I have a pretty nice repro of latched submits [multithreaded_histogram.zip](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/15149875/multithreaded_histogram.zip)

**Comment by artem-lunarg** [comment]
thanks @devshgraphicsprogramming!

**Comment by devshgraphicsprogramming** [comment]
Source is here btw: https://github.com/Devsh-Graphics-Programming/Nabla-Examples-and-Tests/blob/master/07_StagingAndMultipleQueues/main.cpp

**Comment by devshgraphicsprogramming** [comment]
This code change silences the validation layer (if I treat every GPU as I'd treat Intel): https://github.com/Devsh-Graphics-Programming/Nabla-Examples-and-Tests/commit/4e48f0b27213fae6ce032bae4ff2ff0622921afc 

Basially my code is a repro for validation layers choking on timeline semaphores + out-of-order-submits to different queues

**Comment by devshgraphicsprogramming** [comment]
Funny thing, renderdoc chokes on this usage as well, but it actually freezes up completely.

I guess its because its not been coded to be able to defer a capture until later after a submission.

**Comment by imrodriguezro** [comment]
Hi!
out of curiosity, do you guys have a rough estimate of when these false-positives related to timeline semaphores will be fixed?

**Comment by artem-lunarg** [comment]
Hi @imrodriguezro, actually we have some estimates. Syncval timelines semaphores support won't be available in the next SDK (later this month) but it will be in the SDK after that. The implementation should land in the main branch somewhere in August, so it will be possible to test this before the autumn SDK too.

**Comment by imrodriguezro** [comment]
thanks for the info @artem-lunarg 👍
