### ISSUE TITLE
Vulkan SDK 1.1.97.0. Invalid message for transform feedback

### ISSUE THREAD

**Issue by archimedus** [KhronosGroup/Vulkan-ValidationLayers#762]
Running code for transform feedback I get message:

> VUID_Undefined(ERROR / SPEC): msgNum: 0 - vkCmdBeginTransformFeedbackEXT: parameter counterBufferCount must be greater than 0.

There is no requirement "counterBufferCount must be greater than 0." in the specification. Implicitly it is confirmed by following paragraphs:

> If counterBufferCount is not 0, and pCounterBuffers is not NULL, pCounterBuffers must be a
valid pointer to an array of counterBufferCount VkBuffer handles that are either valid or
VK_NULL_HANDLE

Also:

> pCounterBuffers is an **optional** array

> pCounterBufferOffsets is an **optional** array

**This counterBufferCount must be allowed to be zero.** Also please do not validate optional array pointers if it is zero.

**Comment by jeffbolznv** [comment]
I believe this was fixed in vk.xml about a month ago. Can you try the 101 SDK?

**Comment by archimedus** [comment]
You are right. Issue is fixed in SDK 1.1.101.0.

Thank you.
