### ISSUE TITLE
Full screen triangle VkPipeline issue

### ISSUE THREAD

**Issue by Goshido** [KhronosGroup/Vulkan-ValidationLayers#7636]
**Environment:**
 - OS: _Android 11_
 - GPU and driver version: _GPU_: _Mali G76_, driver: _26.0.0_
 - SDK or header version if building from repo: _SHA-1_ `831cedf792c4992d2e19dd7f6494aa971894cfd4`
 - Options enabled (synchronization, best practices, etc.): `VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT` and `VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT`

**Describe the Issue**

I've just updated to latest _VVL_ and got best practices validation warning which seems odd:

```txt
Validation Performance Warning: [ BestPractices-DrawState-VtxIndexOutOfBounds ] Object 0: handle = 0xb4000070684d2c68,
name = Frame in flight #0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x86a454d4 |
vkCmdDraw():  Vertex buffers are bound to VkCommandBuffer 0xb4000070684d2c68[Frame in flight #0]
but no vertex buffers are attached to VkPipeline 0x4a8566000001a31e[Reflection global]
```

Problem is that `Reflection global` pipeline is using full screen triangle and is not using vertex buffers at all. Ok then I tried to make stupid thing. I called `vkCmdBindVertexBuffers` and set all buffers to `VK_NULL_HANDLE`. But this is an error as well (understandable error).

Vertex buffer is in fact used elsewhere in the command buffer but that works. For example for filling `G-Buffer` pass before the lighting passes.

What I gonna do? I'm so confused. Would you kindly help?

**Expected behavior**

No validation warnings for `VkPipeline`'s which are not using vertex|index buffers.

**Valid Usage ID**
_N/A_

**Additional context**

Some _Vulkan_ discord folks suggested to look into [_PR #7553_](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7553).

Previous compatible version _SHA-1_ `82be16cb105068820a02962395fff3e81036254c`.

**Comment by spencer-lunarg** [comment]
So first understand this is a "warning" not an "error"

> Vertex buffer is in fact used elsewhere in the command buffer but that works. For example for filling G-Buffer pass before the lighting passes.

This warning in case you are accidentally calling `vkCmdBindVertexBuffers` but never needed to use it

> is using full screen triangle

I guess could you clarify exactly you mean by this in Vulkan terms (so we are on same page)... as if this is something that the VVL could detect

... thinking out loud, one idea could be improving this error message to only check at the end of the command buffer if ALL draw calls didn't need it

**Comment by Goshido** [comment]
> I guess could you clarify exactly you mean by this in Vulkan terms (so we are on same page)... as if this is something that the VVL could detect

I mean that my vertex shader uses vertex ID and build output vertex for rasterizer:

```hlsl
#include "full_screen_triangle.inc"


[[vk::binding ( BIND_TRANSFORM, SET_TRANSFORM )]]
cbuffer Transform:                              register ( b0 )
{
    float32_t2x2                g_transform;
};

static float32_t2 const g_vertices[ 3U ] =
{
    float32_t2 ( -1.0F, -3.0F ),
    float32_t2 ( 3.0F, 1.0F ),
    float32_t2 ( -1.0F, 1.0F )
};

static float32_t2 const g_uvs[ 3U ] =
{
    float32_t2 ( 0.0F, -1.0F ),
    float32_t2 ( 2.0F, 1.0F ),
    float32_t2 ( 0.0F, 1.0F )
};

struct OutputData
{
    linear float32_t4           _vertexH:       SV_Position;

    [[vk::location ( ATT_SLOT_UV )]]
    noperspective float32_t2    _uv:            UV;
};

//----------------------------------------------------------------------------------------------------------------------

OutputData VS ( in uint32_t vertexID: SV_VertexID )
{
    OutputData result;
    result._vertexH = float32_t4 ( mul ( g_transform, g_vertices[ vertexID ] ), 0.5F, 1.0F );
    result._uv = g_uvs[ vertexID ];
    return result;
}
```

**Comment by spencer-lunarg** [comment]
So I think this is an example of why this is a best practice "warning" ... clearly you have a reason here

I think this warning should be refactored to only warn if no draw uses the bound vertex buffer as that is really what it was ment to check

**Comment by Goshido** [comment]
Here is visual representation from _RenderDoc_. I think _VVL_ incorrect here.

![Issue](https://github.com/KhronosGroup/Vulkan-ValidationLayers/assets/6526711/321b03f6-3ee3-4b0d-9057-3437c0b4e56c)

Basically in current implementation _VVL_ will force me to end current command buffer, and start new command buffer without binding anything.

Emm. It can't be true.

**Comment by spencer-lunarg** [comment]
> I think VVL incorrect here

I agree, I created https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7638 which will track the entire command buffer instead of a single draw

**Comment by Goshido** [comment]
The issue has been fixed. Thank you 👍
