### ISSUE TITLE
BUG: Ownership transfer + layout trasition between queues

### ISSUE THREAD

**Issue by Eichenherz** [KhronosGroup/Vulkan-ValidationLayers#7642]
**Environment:**
 - OS: Win 10
 - GPU and driver version: Nvida 1050 mobile & driver 551.52
 - SDK or header version if building from repo: 1.3.275.0
 - Options enabled (synchronization, best practices, etc.): synchronization

**Describe the Issue**

There are 2 queues: transfer and compute. An upload is being done on the transfer + a release and layout transition. Then an acquire + (same) layout transition is being done on the compute queue for the same resource ( an image ). The validation error from below is being returned. 

**Expected behavior**

No error should be returned

**Valid Usage ID**
`[gfxrecon] ERROR - DEBUG MESSENGER: SYNC-HAZARD-WRITE-AFTER-WRITE: Validation Error: [ SYNC-HAZARD-WRITE-AFTER-WRITE ] Object 0: handle = 0x190015a9e80, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0x5c0ec5d6 | vkQueueSubmit2():  Hazard WRITE_AFTER_WRITE for entry 0, VkCommandBuffer 0x190017c1a30[], Submitted access info (submitted_usage: SYNC_IMAGE_LAYOUT_TRANSITION, command: vkCmdPipelineBarrier2, seq_no: 1, VkImage 0xcb3ee80000000007[InputImg], VkImage 0xcfef35000000000a[OutputImg], reset_no: 1). Access info (prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION, write_barriers: 0, queue: VkQueue 0x190013be230[], submit: 0, batch: 0, batch_tag: 1, command: vkCmdPipelineBarrier2, command_buffer: VkCommandBuffer 0x190017c1a30[] (destroyed), seq_no: 3, VkImage 0xcb3ee80000000007[InputImg], reset_no: 1).`

**Additional context**
https://github.com/Eichenherz/Nabla-Examples-and-Tests/blob/acc16a6baea0c75b06a76b069a49ba56591e2474/26_CentralLimitBoxBlur/main.cpp#L223

[gfxrecon_capture_20240305T172423.json](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/14498631/gfxrecon_capture_20240305T172423.json)

RELEASE:
```json
{
  "index": 267,
  "function": {
    "name": "vkCmdPipelineBarrier2",
    "thread": 1,
    "cmd_index": 3,
    "args": {
      "commandBuffer": 29,
      "pDependencyInfo": {
        "sType": "VK_STRUCTURE_TYPE_DEPENDENCY_INFO",
        "dependencyFlags": "0x00000000",
        "memoryBarrierCount": 0,
        "pMemoryBarriers": null,
        "bufferMemoryBarrierCount": 0,
        "pBufferMemoryBarriers": null,
        "imageMemoryBarrierCount": 1,
        "pImageMemoryBarriers": [
          {
            "sType": "VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2",
            "srcStageMask": "0x0000000100000000",
            "srcAccessMask": "0x0000000000001000",
            "dstStageMask": "0x0000000000000000", // is this wrong!?
            "dstAccessMask": "0x0000000000000000",
            "oldLayout": "VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL",
            "newLayout": "VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL",
            "srcQueueFamilyIndex": 1,
            "dstQueueFamilyIndex": 2,
            "image": 14,
            "subresourceRange": {
              "aspectMask": "0x00000001",
              "baseMipLevel": 0,
              "levelCount": 1,
              "baseArrayLayer": 0,
              "layerCount": 1
            },
            "pNext": null
          }
        ],
        "pNext": null
      }
    }
  }
},
```

ACQUIRE:
```json
{
  "index": 278,
  "function": {
    "name": "vkCmdPipelineBarrier2",
    "thread": 1,
    "cmd_index": 2,
    "args": {
      "commandBuffer": 39,
      "pDependencyInfo": {
        "sType": "VK_STRUCTURE_TYPE_DEPENDENCY_INFO",
        "dependencyFlags": "0x00000000",
        "memoryBarrierCount": 0,
        "pMemoryBarriers": null,
        "bufferMemoryBarrierCount": 0,
        "pBufferMemoryBarriers": null,
        "imageMemoryBarrierCount": 2,
        "pImageMemoryBarriers": [
          {
            "sType": "VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2",
            "srcStageMask": "0x0000000000000000",  // is this wrong!?
            "srcAccessMask": "0x0000000000000000",
            "dstStageMask": "0x0000000000000800",
            "dstAccessMask": "0x0000000100000000",
            "oldLayout": "VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL",
            "newLayout": "VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL",
            "srcQueueFamilyIndex": 1,
            "dstQueueFamilyIndex": 2,
            "image": 14,
            "subresourceRange": {
              "aspectMask": "0x00000001",
              "baseMipLevel": 0,
              "levelCount": 1,
              "baseArrayLayer": 0,
              "layerCount": 1
            },
            "pNext": null
          },
```

**Comment by artem-lunarg** [comment]
@Eichenherz that's a know issue, we have a ticket opened here https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7024 with a working repro case here https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7024#issuecomment-1830760272.  Will close this as duplicate, but will notify this ticket when it's fixed.

**Comment by artem-lunarg** [comment]
@Eichenherz this issue should be fixed by https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7552 which first appeared in the 1.3.280 SDK.
