### ISSUE TITLE
Layers make CTS test fail

### ISSUE THREAD

**Issue by rg3igalia** [KhronosGroup/Vulkan-ValidationLayers#7659]
**Environment:**
 - OS: Fedora Linux 39
 - GPU and driver version: Intel/Mesa (ANV)
 - SDK or header version if building from repo: 2c29b49c2c717c4ad50063e4bded444e9676254e
 - Options enabled (synchronization, best practices, etc.): defaults+synchronization

**Describe the Issue**

The CTS test `dEQP-VK.pipeline.monolithic.extended_dynamic_state.cmd_buffer_start.null_rasterization_state` fails when the layers are enabled, and passes with the layers disabled.

This is a test that makes `pRasterizationState` NULL on pipeline creation because it sets all the corresponding state as dynamic, which is allowed by the spec.

However, taking a look at what the test is doing with and without the layers, it seems the layers also remove `pViewportState`, `pDepthStencilState` and `pColorBlendState` when creating the pipeline, which prevents the test from working correctly.

**Expected behavior**

The test passes in both cases.

**Valid Usage ID**

None.

**Additional context**

N/A.

**Comment by spencer-lunarg** [comment]
I am currently trying to fix as we speak

the core issue is we need to ignore a lot of of these `VkGraphicsPipelineCreateInfo` fields, but the way it was done was by just removing them from the incoming struct, which causes bugs like this were are changing the output sent to the driver

Currently trying to undo that while still correctly ignoring things as they should be
