### ISSUE TITLE
"OutputNotConsumed" although attachement is VK_ATTACHMENT_UNUSED

### ISSUE THREAD

**Issue by xxxbxxx** [KhronosGroup/Vulkan-ValidationLayers#766]
hello,

This validation warning:
`[Validation] Code 0 :  [ UNASSIGNED-CoreValidation-Shader-OutputNotConsumed ] Object: 0x9d9 (Type = 15) | fragment shader writes to output location 1 with no matching attachment`

is triggered even though there is a matching VkAttachmentReference with VK_ATTACHMENT_UNUSED.

Which should be valid, if I understand correctly
 https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkSubpassDescription.html

**Comment by aejsmith** [comment]
I also think this warning should be removed. We hit it quite a bit but as far as I see the spec specifically says it's legal and the writes are just discarded.

**Comment by mark-lunarg** [comment]
Hey @jeremy-lunarg, this seems to be low-hanging fruit.  Maybe it could be moved to Best Practices and taken out of CoreChecks.
