### ISSUE TITLE
No validation error on vkGetDescriptorSetLayoutSupport

### ISSUE THREAD

**Issue by madeeha** [KhronosGroup/Vulkan-ValidationLayers#7665]
**Environment:**
 - OS: Linux
 - GPU and driver version: AMD and RADV
 - SDK or header version if building from repo: e76a83ffd0d955bbe52d7287c7977de42520c0e7
 - Options enabled (synchronization, best practices, etc.): defaults

**Describe the Issue**

A VkDescriptorSetLayoutCreateInfo is created with pBindings having a binding of type VK_DESCRIPTOR_TYPE_MUTABLE_EXT and pNext has the VkMutableDescriptorTypeCreateInfoEXT with mutableDescriptorTypeListCount set to 0.
When vkGetDescriptorSetLayoutSupport, no error is reported by the validation layers and only a driver crash is observed.

This is illegal according to VUID-VkDescriptorSetLayoutCreateInfo-pBindings-07303, which [reads](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDescriptorSetLayoutCreateInfo.html#VUID-VkDescriptorSetLayoutCreateInfo-pBindings-07303):

> If any element pBindings[i] has a descriptorType of VK_DESCRIPTOR_TYPE_MUTABLE_EXT, then a VkMutableDescriptorTypeCreateInfoEXT must be present in the pNext chain, and mutableDescriptorTypeListCount must be greater than i

It can be reproduced by applying the patch I give you below, and running the VKCTS test dEQP-VK.binding_model.mutable_descriptor.single.uniform_buffer.update_copy.mutable_source.host_only_source.pool_expand_types.pre_update.no_array.vert

**Expected behavior**
Expected to see VUID-VkDescriptorSetLayoutCreateInfo-pBindings-07303 error.

**Valid Usage ID**
VUID-VkDescriptorSetLayoutCreateInfo-pBindings-07303

**Additional context**
Patch to trigger VUID-VkDescriptorSetLayoutCreateInfo-pBindings-07303 in VKCTS with dEQP-VK.binding_model.mutable_descriptor.single.uniform_buffer.update_copy.mutable_source.host_only_source.pool_expand_types.pre_update.no_array.vert
```
diff --git a/external/vulkancts/modules/vulkan/binding_model/vktBindingMutableTests.cpp b/external/vulkancts/modules/vulkan/binding_model/vktBindingMutableTests.cpp
index 1ea40f1e7..b9f5520d3 100644
--- a/external/vulkancts/modules/vulkan/binding_model/vktBindingMutableTests.cpp
+++ b/external/vulkancts/modules/vulkan/binding_model/vktBindingMutableTests.cpp
@@ -1593,8 +1593,8 @@ public:
 
                if (strategy == PoolMutableStrategy::KEEP_TYPES || strategy == PoolMutableStrategy::EXPAND_TYPES)
                {
-                       mutableInfo.mutableDescriptorTypeListCount = static_cast<deUint32>(mutableTypeLists.size());
-                       mutableInfo.pMutableDescriptorTypeLists    = de::dataOrNull(mutableTypeLists);
+                       mutableInfo.mutableDescriptorTypeListCount = 0u; //static_cast<deUint32>(mutableTypeLists.size());
+                       mutableInfo.pMutableDescriptorTypeLists    = nullptr; //de::dataOrNull(mutableTypeLists);
                        poolCreateInfo.pNext                       = &mutableInfo;
                }
 
@@ -1709,8 +1709,8 @@ private:
                const VkMutableDescriptorTypeCreateInfoEXT createInfoMutable = {
                        VK_STRUCTURE_TYPE_MUTABLE_DESCRIPTOR_TYPE_CREATE_INFO_EXT,
                        flagsCreateInfo.get(),
-                       static_cast<deUint32>(mutableTypeLists.size()),
-                       de::dataOrNull(mutableTypeLists),
+                       0u, //static_cast<deUint32>(mutableTypeLists.size()),
+                       nullptr //de::dataOrNull(mutableTypeLists),
                };
 
                const VkDescriptorSetLayoutCreateInfo layoutCreateInfo = {
@@ -1727,6 +1727,7 @@ private:
                        vkd.getDescriptorSetLayoutSupport(device, &layoutCreateInfo, &support);
                        DescriptorSetLayoutResult result((support.supported == VK_TRUE) ? DescriptorSetLayoutResult::LayoutSupported::YES
                                                                                        : DescriptorSetLayoutResult::LayoutSupported::NO);
+
                        return result;
                }
                else
```

**Comment by spencer-lunarg** [comment]
this was fixed in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7726

`vkGetDescriptorSetLayoutSupport` now calls into the same logic `vkCreateDescriptorSetLayout` does
