### ISSUE TITLE
Crash while validating graphics pipeline due to invalid FS state

### ISSUE THREAD

**Issue by aabdolrashidi** [KhronosGroup/Vulkan-ValidationLayers#7697]
After commit 550d53799bf6a99c8f9ab7ff02c6e18ceb725c94, some tests crash when validating `vkCreateGraphicsPipelines()` due to invalid FS state.

In `core_checks/cc_pipeline_graphics.cpp` &rarr; `ValidateGraphicsPipelineLibrary()`:
`pre_raster_independent_set` is set using `fragment_shader_state` flags even if FS state is invalid.
If a check is added similar to `fs_independent_set` below it, the issue is fixed.

CC: @spencer-lunarg

**Comment by spencer-lunarg** [comment]
can I ask what kinda of test you had that crashed this? This logic is inside a `from_libraries_only` check and I want to add a regression test, but can't create a full completed pipeline with an invalid fragment shader state

**Comment by y-novikov** [comment]
Example bot with the failure: https://ci.chromium.org/ui/p/angle/builders/try/linux-test/19214/overview
Logs of sample dEQP GLES3 tests running on top of SwiftShader Vulkan implementation:
https://chromium-swarm.appspot.com/task?id=68583741bdeeaf10
[ RUN      ] dEQP-GLES3.functional.rasterizer_discard.basic.write_stencil_lines

Signal 11 [Segmentation fault]:
Writing test results to /b/s/w/ity_zrz6fl/.angle.1KgOld
Backtrace:
angle::PrintStackBacktrace() at crash_handler_posix.cpp:498
angle::Handler(int) at crash_handler_posix.cpp:659
__restore_rt at libc_sigaction.c:?
PipelineSubState::PipelineLayoutCreateFlags() const at pipeline_sub_state.cpp:23
CoreChecks::ValidateGraphicsPipelineLibrary(vvl::Pipeline const&, Location const&) const at cc_pipeline_graphics.cpp:622
CoreChecks::ValidateGraphicsPipeline(vvl::Pipeline const&, Location const&) const at cc_pipeline_graphics.cpp:85
CoreChecks::PreCallValidateCreateGraphicsPipelines(VkDevice_T*, VkPipelineCache_T*, unsigned int, VkGraphicsPipelineCreateInfo const*, VkAllocationCallbacks const*, VkPipeline_T**, ErrorObject const&, void*) const at cc_pipeline_graphics.cpp:?
vulkan_layer_chassis::CreateGraphicsPipelines(VkDevice_T*, VkPipelineCache_T*, unsigned int, VkGraphicsPipelineCreateInfo const*, VkAllocationCallbacks const*, VkPipeline_T**) at chassis.cpp:664
rx::vk::PipelineCacheAccess::createGraphicsPipeline(rx::vk::Context*, VkGraphicsPipelineCreateInfo const&, rx::vk::Pipeline*) at vk_wrapper.h:1793
rx::GraphicsPipelineCache<rx::GraphicsPipelineDescCompleteHash>::linkLibraries(rx::vk::Context*, rx::vk::PipelineCacheAccess*, rx::vk::GraphicsPipelineDesc const&, rx::vk::PipelineLayout const&, rx::vk::PipelineHelper*, rx::vk::PipelineHelper*, rx::vk::PipelineHelper*, rx::vk::GraphicsPipelineDesc const**, rx::vk::PipelineHelper**) at vk_cache_utils.cpp:2354
rx::ProgramExecutableVk::linkGraphicsPipelineLibraries(rx::ContextVk*, rx::vk::PipelineCacheAccess*, rx::vk::GraphicsPipelineDesc const&, rx::vk::PipelineHelper*, rx::vk::PipelineHelper*, rx::vk::PipelineHelper*, rx::vk::GraphicsPipelineDesc const**, rx::vk::PipelineHelper**) at ProgramExecutableVk.cpp:1198
rx::ContextVk::createGraphicsPipeline() at ContextVk.cpp:2249
rx::ContextVk::handleDirtyGraphicsPipelineDesc(angle::BitSetT<42ul, unsigned long, unsigned long>::Iterator*, angle::BitSetT<42ul, unsigned long, unsigned long>) at ContextVk.cpp:2297
rx::ContextVk::setupDraw(gl::Context const*, gl::PrimitiveMode, int, int, int, gl::DrawElementsType, void const*, angle::BitSetT<42ul, unsigned long, unsigned long>) at Error.h:181
rx::ContextVk::drawArrays(gl::Context const*, gl::PrimitiveMode, int, int) at ContextVk.cpp:4106
GL_DrawArrays at Error.h:181
deqp::gles3::Functional::RasterizerDiscardCase::iterate() at es3fRasterizerDiscardTests.cpp:?
deqp::gles3::TestCaseWrapper::iterate(tcu::TestCase*) at tes3TestPackage.cpp:98
tcu::RandomOrderExecutor::executeInner(tcu::TestCase*, std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > const&) at tcuRandomOrderExecutor.cpp:268
tcu::RandomOrderExecutor::execute(std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > const&) at tcuTestCase.hpp:207

**Comment by y-novikov** [comment]
Thanks for the fix, I didn't see these failures in the newer roll https://chromium-review.googlesource.com/c/angle/angle/+/5374168.
But I do see new crashes, I think from #7675.

**Comment by aabdolrashidi** [comment]
Thank you for the fix!
