### ISSUE TITLE
Test crashes/failures for llvmpipe on WSL Ubuntu 22.04

### ISSUE THREAD

**Issue by jeremyg-lunarg** [KhronosGroup/Vulkan-ValidationLayers#7731]
I'm bringing up a new laptop and here's the test problems for WSL llvmpipe with:
```
 ii  mesa-vulkan-drivers:amd64     23.2.1-1ubuntu3.1~22.04.2               amd64        Mesa Vulkan graphics drivers

GPU0:
VkPhysicalDeviceProperties:
---------------------------
        apiVersion        = 4206847 (1.3.255)
        driverVersion     = 1 (0x0001)
        vendorID          = 0x10005
        deviceID          = 0x0000
        deviceType        = PHYSICAL_DEVICE_TYPE_CPU
        deviceName        = llvmpipe (LLVM 15.0.7, 256 bits)
        pipelineCacheUUID = 32332e32-2e31-2d31-7562-756e7475332e

```
Crashes:

- [x] NegativeDynamicState.InvalidSampleMaskSamples (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7742)
- [x] NegativeGpuAV.UnnormalizedCoordinatesSeparateSamplerSharedSampler (has been fixed in 1.3.278)
- [ ] NegativeShaderObject.MissingCmdSetBlendConstantsEXT (crashes in lavapipe)
- [x] NegativeSyncObject.Sync2SignalSemaphoreValue (crashes in lavapipe, has been fixed in 1.3.278)

Fails:

- [x] NegativeCommand.ResolveUsage (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7742)
- [x] NegativeExternalMemorySync.ImportMemoryFromFdHandle (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7742)
- [x] VkLayerTest.SpecLinks (issue is with `ANNOTATED_SPEC_LINK`, not the driver)
- [x] PositiveWsi.CreateXcbSurface (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7734)

**Comment by spencer-lunarg** [comment]
I can help take a look at these, I have lavapipe on my machine and can reproduce / debug Mesa

> PositiveWsi.CreateXcbSurface

This one is something with your x-server setup, I had this locally, fixed it, but not sure what the test is suppose to do to fix it

**Comment by jeremyg-lunarg** [comment]
> I can help take a look at these, I have lavapipe on my machine and can reproduce / debug Mesa
> 
> > PositiveWsi.CreateXcbSurface
> 
> This one is something with your x-server setup, I had this locally, fixed it, but not sure what the test is suppose to do to fix it

It's likely my x-server not set up at all.  I don't mind looking at these when I get bored. Mostly I'm just testing out my new laptop (RTX 4060 and Intel integrated tests are still running).

**Comment by spencer-lunarg** [comment]
>  I don't mind looking at these when I get bored

That was my goal, I always am looking if tests work on Intel/AMD Mesa.. just can't believe I didn't think of doing it with Lavapipe as well

**Comment by jeremyg-lunarg** [comment]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7734

**Comment by spencer-lunarg** [comment]
`NegativeShaderObject.MissingCmdSetBlendConstantsEXT`  if you look at https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/vulkan/runtime/vk_graphics_state.c?ref_type=heads#L3004 it is

![image](https://github.com/KhronosGroup/Vulkan-ValidationLayers/assets/115671160/0ce762e0-6388-465d-990d-935b742afac4)

**Comment by spencer-lunarg** [comment]
With latest 1.3.278 driver all of these are now fixeed
