### ISSUE TITLE
Crash when creating pipeline with wrong shaders

### ISSUE THREAD

**Issue by rudolfheszele** [KhronosGroup/Vulkan-ValidationLayers#7751]
**Environment:**
 - OS: Windows 10
 - GPU and driver version: Nvidia Geforce RTX 2070, Geforce Game Ready driver version 551.23.
 - SDK or header version if building from repo: I am using the conan package with version 1.3.239.0
 - Options enabled (synchronization, best practices, etc.): I use the default settings.

**Describe the Issue**
I made a mistake when created a pipeline with two shader modules (vertex and fragment). The fragment shader was accidentally compiled to spir-v as a vertex shader (the compilation succeeded).
With this setup I got a crash somewhere in the layer's dll, complaining about an empty std::optional being dereferenced, when I tried to create a pipeline.

**Expected behavior**
No crash should happen, a warning message should be printed instead (or let the driver crash)

**Valid Usage ID**
NA

**Additional context**
NA

**Comment by spencer-lunarg** [comment]
@rudolfheszele thanks for the report, we have had MANY fixes for the Shader/Pipeline part of the code in the last year to help stop these types of sudden crashes

@arno-lunarg tried reproducing and could not

I see you are using a very old `1.3.239.0` version (Janurary 2023) - I assume the fix is to update or grab the latest version of the Validation Layers

**Comment by rudolfheszele** [comment]
Thanks for the info! I will investigate using a newer version of the validation layer. Unfortunately, the latest on conan center is the one I am using (1.3.239).

**Comment by spencer-lunarg** [comment]
I just looked into Conan (first time hearing about it) and I can't find a quick way to update the version of that package (or who even added it there)

My suggestion in general for Vulkan dev tools is to try and look to use the [Vulkan SDK](https://vulkan.lunarg.com/sdk/home) as we package all the latest version with testing there and with Vulkan it is just a matter of setting your `VK_LAYER_PATH` or even better is a lot of people use [VkConfig](https://vulkan.lunarg.com/doc/view/latest/windows/vkconfig.html) tool which makes things even simpler to grab the right version of a layer

**Comment by rudolfheszele** [comment]
Yes, I know about the Vulkan SDK, I am experimenting with a development environment setup without it. I want to be able to just clone a repo and start hacking :) Thanks for the quick reply and help!
