### ISSUE TITLE
Option to throw exceptions upon warnings

### ISSUE THREAD

**Issue by Lawrencemm** [KhronosGroup/Vulkan-ValidationLayers#778]
The option to raise exceptions upon warnings would make it easier for me to debug the source of the problem in my code.

I understant that exceptions across shared library boundaries can be tricky but if I understand it correctly it's possible at least if the host code uses the same exception handling structure as the shared code.

**Comment by jzulauf-lunarg** [comment]
Have you tried raising an exception in the function you registered with `VkDebugUtilsMessengerCreateInfoEXT`  AFAICT this would give you full control over the exception you use, and the conditions under which you raise it.

**Comment by Lawrencemm** [comment]
Seems like the obvious solution was staring me in the face. Thanks.

For Google:
Throw Vulkan validation exception VkDebugUtilsMessengerCreateInfoEXT
