### ISSUE TITLE
python chaos in the script dir

### ISSUE THREAD

**Issue by hergljkds** [KhronosGroup/Vulkan-ValidationLayers#7806]
Who exactly is developing this project?  

I have never seen worse.

Without running ./scripts/update_deps.py, is there a simple way to generate the source files (headers, etc.)?

Who switched the code base and replaced it with crap?  Sabotage.  People must love breaking code...

**Comment by artem-lunarg** [comment]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/BUILD.md#building-overview

**Comment by spencer-lunarg** [comment]
> Without running ./scripts/update_deps.py, is there a simple way to generate the source files (headers, etc.)?

The script I use

`python3 scripts/generate_source.py external/Vulkan-Headers/registry/ external/SPIRV-Headers/include/spirv/unified1/`

If you only want to need to build one file

`python3 scripts/generate_source.py external/Vulkan-Headers/registry/ external/SPIRV-Headers/include/spirv/unified1/ --target vk_safe_struct.h`

(This seems like the answer you wanted so going to close the issue)

> Who switched the code base and replaced it with crap

This has been like this for over a year now, sorry if this caused you time wasted when using the newer version, we try to keep things updated in the `BUILD.md` file as things change

We are also mainly working on the C++ part of the code and are not python/build-system experts so happy to take any advice!

**Comment by hergljkds** [comment]
strange things happen when using stuxnet... I mean git.  Changes, cryptic changes... seamless and wicked.  Jimmy Cracked corn and (I still have a soul so) I KKare.

dependency chaos.

https://github.com/KhronosGroup/Vulkan-Utilities-Libraries

solved the problem... a step towards being phein.
