### ISSUE TITLE
Descriptor not updated message with multiple textures

### ISSUE THREAD

**Issue by SuperflyJon** [KhronosGroup/Vulkan-ValidationLayers#781]
I've got a simple example which has 2 texture bindings (and a uniform buffer), I get the following validation message:

> Descriptor set 0x2a bound as set #0 encountered the following validation error at vkCmdDrawIndexed() time: Descriptor in binding #2 at global descriptor index 3 is being used in draw but has not been updated.

The textures render fine and the descriptor pool/layouts and descriptor look okay to me.  I'm not sure what I'm doing wrong...

**Comment by tobine** [comment]
Layer just telling you that vkUpdateDescriptorSets() hasn't been called to update that particular descriptor. It should either be updated or not used in the Draw.

**Comment by SuperflyJon** [comment]
I was calling vkUpdateDescriptorSets and that was not the problem.  Note that both textures were drawing correctly.

The problem was that for the 2nd texture I was accidentally setting the descriptorCount field of VkDescriptorSetLayoutBinding to 2.  I think this is the "global descriptor index 3" part of the error message.
