### ISSUE TITLE
Race in the NegativeSyncObject.Sync2SignalSemaphoreValue uinit test

### ISSUE THREAD

**Issue by tomek-brcm** [KhronosGroup/Vulkan-ValidationLayers#7885]
The unit test test attempts to verify the VUID-VkSemaphoreSignalInfo-value-03259 check by attempting to signal a timeline semaphore[0] = 25 while there's a pending signal semaphore[0] = 20 submitted to the queue. There's no guarantee that the submitted operation is actually pending.

The queue submission waits for semapthore[1] == 5 (already met at the semaphore creation time). This creates a race between the 2 signal operations: from the queue and from the API call. If the queue wins, the signal semaphore[0] = 25 becomes valid use rather then violation of VUID-VkSemaphoreSignalInfo-value-03259. Also the subsequent signal semaphore[0] = 15 from the API becomes invalid use.

There are 3 possible scenarios for semaphore[0] values that change what is valid and what is invalid use. The unit test code always assumes the 1st scenario:

* 5 (creation) --> 10 (API) --> 20 (queue pending) --> 25 (API, invalid) --> 15 (API, valid) --> _20 (queue completed)_
* 5 (creation) --> 10 (API) --> 20 (queue pending) --> 25 (API, invalid) --> _20 (queue completed)_ --> 15 (API, **invalid**)
* 5 (creation) --> 10 (API) --> 20 (queue pending) --> _20 (queue completed)_ --> 25 (API, **valid**) --> 15 (API, **invalid**)

I'll submit a tivial fix so that the assumption is always met. There might be a bigger issue of correctly tracking timeline semapthores between immediate and queued signal operations.

**Comment by artem-lunarg** [comment]
>  There might be a bigger issue of correctly tracking timeline semapthores between immediate and queued signal operations.

Coincidentally just this week I'm working on the use case when wait-before-signal does not work correctly in some scenarios for timeline semaphores. Just to let know that this has a chance to be fixed, hopefully, soon.

**Comment by artem-lunarg** [comment]
cc @jeremyg-lunarg for visibility (again)

**Comment by tomek-brcm** [comment]
Hi Artem,

Yes, I understand. My point is that there are 2 immediate signal operations (15 and 25) with a values on both sides of a queued signal (20) and both can potentially backfire but only 25 is flagged as (potentially) invalid use.

**Comment by artem-lunarg** [comment]
Hi Tomek, 

When the validation error happens then no state is updated for corresponding API call on the VVL side. Because in this code

```
semaphore_signal_info.value = 25;
m_errorMonitor->SetDesiredError("VUID-VkSemaphoreSignalInfo-value-03259");
vk::SignalSemaphore(device(), &semaphore_signal_info);
m_errorMonitor->VerifyFound();
```

we have a validation failure the 25 signal does not affect surrounding validation. For signals 20 and 15 it looks like there is no 25, from VVL state tracking point of view. It should be no issue here.

But one thing that we can do better (and hopefully we are moving in that  direction) is the simplification of such complex test, ideally it should be separate test for each scenario.

**Comment by artem-lunarg** [comment]
@tomek-brcm I can image that in some scenarios trying to continue after validation error might put driver in bad state but that's also a patern for validation code, we intentionally trying to provoke bad behavior. Did you experience some stability issue with this test?

**Comment by gnl21** [comment]
Hi Artem,

It's not the call that you point to that's causing the problem. Here's a slightly longer snippet copied from the test:
```
    semaphore_signal_info.value = 25;
    m_errorMonitor->SetDesiredError("VUID-VkSemaphoreSignalInfo-value-03259");
    vk::SignalSemaphore(device(), &semaphore_signal_info);
    m_errorMonitor->VerifyFound();
    semaphore_signal_info.value = 15;
    ASSERT_EQ(VK_SUCCESS, vk::SignalSemaphore(device(), &semaphore_signal_info));
    semaphore_signal_info.semaphore = semaphore[1].handle();
    ASSERT_EQ(VK_SUCCESS, vk::SignalSemaphore(device(), &semaphore_signal_info));
```
It's the second signal operation, with value 15, that is causing problems. The test considers it invalid and the validation layer is not blocking it, but the earlier queue submit may already have signaled the semaphore with the value 20.

**Comment by tomek-brcm** [comment]
Tithout my patch the unit test code for the 2nd signall operation proably should be this instead:
```
    semaphore_signal_info.value = 15;
    m_errorMonitor->SetDesiredError("VUID-VkSemaphoreSignalInfo-value-03258");
    vk::SignalSemaphore(device(), &semaphore_signal_info);
    m_errorMonitor->VerifyFound();
```

**Comment by artem-lunarg** [comment]
@gnl21 @tomek-brcm Thanks for explanation, it makes sense. I think that signal 25does not play much role here, was a bit confused  at first that it can cause any problem.
