### ISSUE TITLE
vkGetDisplayPlaneSupportedDisplaysKHR segmentation fault

### ISSUE THREAD

**Issue by Snektron** [KhronosGroup/Vulkan-ValidationLayers#789]
Hello,

calling `vkGetDisplayPlaneSupportedDisplaysKHR` with `pDisplays` a nullptr should return the total number of displays in `pDisplayCount`, where in that case `pDisplayCount` doesnt need to have a defined value.

When validation layers are enabled, `vulkan_layer_chassis::GetDisplayPlaneSupportedDisplaysKHR` intercepts this call. If the value of `*pDisplayCount` happens to be non-zero, an access violation is performed in `ThreadSafety::PreCallRecordGetDisplayPlaneSupportedDisplaysKHR`. Even if `*pDisplayCount` is zero, the call to `DispatchGetDisplayPlaneSupportedDisplaysKHR` may return a nonzero value in `pDisplayCount`, in which case a similar access violation occurs in `ThreadSafety::PostCallRecordGetDisplayPlaneSupportedDisplaysKHR`.

Im using the LunarG SDK version 1.1.101.0, and im unsure if similar problems might exist.

**Comment by mark-lunarg** [comment]
I believe this has been fixed either by commit 6d4956662d or 0320864eeac8.  Please reopen this issue if this API is still causing access violations.  Thanks!
