### ISSUE TITLE
Segmentation fault when calling vkCmdPipelineBarrier2

### ISSUE THREAD

**Issue by Ondrej-Richtr** [KhronosGroup/Vulkan-ValidationLayers#7905]
**Environment:**
 - OS: Win10 (MSYS2 environment)
 - GPU and driver version: NVIDIA GeForce GTX 1060, driver ver. 551.81
 - SDK or header version if building from repo: The msys2 package I use states "1.3.280.0-1"
 - Options enabled (synchronization, best practices, etc.): VK_KHR_synchronization2 device extension enabled

Each time I call vkCmdPipelineBarrier2 I get segfault no matter the input parameters. Used command buffer is in a recording state and other commands I use gets recorded correctly, so I have no idea what's causing it. There's also no message from validation layers or anything, just a crash.
First I thought it's because I badly initialized the function pointer, but I asserted that vkCmdPipelineBarrier2 != NULL. However when I dont enable the validation layers everything works just fine, no crash when calling vkCmdPipelineBarrier2 nor when submitting the queue with said command.

**Comment by spencer-lunarg** [comment]
@Ondrej-Richtr can you try `vkCmdPipelineBarrier2KHR` as I assume that works

`vkCmdPipelineBarrier2` == `VK_VERSION_1_3` (and not sure if you are using it)

It is possible you have a valid `vkCmdPipelineBarrier2` pointer, but it points into the Vulkan Loader and because you might not have 1.3, it won't pass it down to the layers (as an old 1.2 layer wouldn't know about that call yet)

**Comment by Ondrej-Richtr** [comment]
> @Ondrej-Richtr can you try `vkCmdPipelineBarrier2KHR` as I assume that works
> 
> `vkCmdPipelineBarrier2` == `VK_VERSION_1_3` (and not sure if you are using it)
> 
> It is possible you have a valid `vkCmdPipelineBarrier2` pointer, but it points into the Vulkan Loader and because you might not have 1.3, it won't pass it down to the layers (as an old 1.2 layer wouldn't know about that call yet)

Ok I tried `vkCmdPipelineBarrier2KHR` and that finally got me validation layers message:

> 'Validation Error: [ VUID-vkCmdPipelineBarrier2-synchronization2-03848 ] Object 0: handle = 0x143b3441e60, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xa060404 | vkCmdPipelineBarrier2KHR():  the synchronization2 feature was not enabled. The Vulkan spec states: The synchronization2 feature must be enabled (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdPipelineBarrier2-synchronization2-03848)'

So the issue was that I forgot to use `VK_API_VERSION_1_3` and also forgot to enable synchronization2 feature.
It works fine now, sorry for wasting your time.
