### ISSUE TITLE
pictureFormat (1000156003) does not fall within the of the core VkFormat enumeration tokens

### ISSUE THREAD

**Issue by elsampsa** [KhronosGroup/Vulkan-ValidationLayers#7910]
**Environment:**
 - OS:  Ubuntu 22.04.4
 - GPU and driver version: NVIDIA GeForce RTX 4070, driver version 535.171.04
 - SDK or header version if building from repo: **1.3.268**.  Ubuntu package: `1.3.268.0~rc1-1lunarg22.04-1` from lunarg repo.
 - Options enabled (synchronization, best practices, etc.): N/A

**Describe the Issue**

Validation layers complain that `VK_FORMAT_G8_B8R8_2PLANE_420_UNORM (1000156003)` is not available, although it *is* clearly in the vulkan header files (see in [here](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkFormat.html)).

Here is a scheme of the code to reproduce the issue:
```c++
...
VkVideoProfileInfoKHR &videoProfile = ... // a reference to a valid VkVideoProfileInfoKHR
VkVideoCapabilitiesKHR &videoCap = ... // a reference to a valid VkVideoCapabilitiesKHR
VkVideoFormatPropertiesKHR *vk_video_format_props // pointer to an array of VkVideoFormatPropertiesKHR(s)
...
VkVideoSessionCreateInfoKHR info = {};
info.sType = VK_STRUCTURE_TYPE_VIDEO_SESSION_CREATE_INFO_KHR;
info.pNext = nullptr; 
info.queueFamilyIndex = 1; // I have appropriate index here
info.flags = 0;
info.pVideoProfile = &videoProfile;
info.pictureFormat = vk_video_format_props[0].format; // VK_FORMAT_G8_B8R8_2PLANE_420_UNORM = 1000156003
info.maxCodedExtent = videoCap.maxCodedExtent;
info.referencePictureFormat = vk_video_format_props[0].format;
info.maxDpbSlots = videoCap.maxDpbSlots; 
info.maxActiveReferencePictures = videoCap.maxActiveReferencePictures;
info.pStdHeaderVersion = &(videoCap.stdHeaderVersion);
// the call that creates the error message
VkResult result = ex.vkCreateVideoSessionKHR(
      vk_device, // a valid device
      &info,
      nullptr,
      &video_session
);
```

I am using these device extensions:
```
VK_KHR_VIDEO_QUEUE_EXTENSION_NAME
VK_KHR_SYNCHRONIZATION_2_EXTENSION_NAME
VK_KHR_VIDEO_DECODE_QUEUE_EXTENSION_NAME
VK_KHR_VIDEO_DECODE_H264_EXTENSION_NAME
```
And this instance extension:
```
VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME
```

**Expected behavior**

There should be no error message, or at least, an error message that gives the correct reason for the fail.

**Valid Usage ID**
```bash
VUID-VkVideoSessionCreateInfoKHR-pictureFormat-parameter(ERROR / SPEC): msgNum: -1141110005 - Validation Error: 
[ VUID-VkVideoSessionCreateInfoKHR-pictureFormat-parameter ] | MessageID = 0xbbfc0b0b | vkCreateVideoSessionKHR():
pCreateInfo->pictureFormat (1000156003) does not fall within the begin..end range 
of the core VkFormat enumeration tokens and is not an extension added token. 
The Vulkan spec states: pictureFormat must be a valid VkFormat value 
(https://vulkan.lunarg.com/doc/view/1.3.268.0/linux/1.3-extensions/vkspec.html#VUID-VkVideoSessionCreateInfoKHR-pictureFormat-parameter)
```

If applicable, please include the validation messages encountered leading up to the issue:

Not sure if related:
```
VUID-vkCreateDevice-ppEnabledExtensionNames-01387(ERROR / SPEC): msgNum: 307460652 - Validation Error: [ VUID-vkCreateDevice-ppEnabledExtensionNames-01387 ] Object 0: handle = 0x5713a5281490, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x12537a2c | vkCreateDevice(): pCreateInfo->ppEnabledExtensionNames[0] Missing extension required by the device extension VK_KHR_video_queue: VK_VERSION_1_1. The Vulkan spec states: All required device extensions for each extension in the VkDeviceCreateInfo::ppEnabledExtensionNames list must also be present in that list (https://vulkan.lunarg.com/doc/view/1.3.268.0/linux/1.3-extensions/vkspec.html#VUID-vkCreateDevice-ppEnabledExtensionNames-01387)
    Objects: 1
        [0] 0x5713a5281490, type: 1, name: NULL
```
(as you can see from above I *have* loaded all necessary extensions)

**Additional context**

Related [issue?](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7369)

**Comment by elsampsa** [comment]
Hmm.. should I update my driver maybe..?
https://vulkan.gpuinfo.org/
Mine is 535.+ but in that list GeForce RTXs are using 552.+

**Comment by spencer-lunarg** [comment]
so in the latest SDK we **finally** improved the error message here

the issue is likely you are using Vulkan 1.0 without the `VK_KHR_sampler_ycbcr_conversion` extension enabled

If you update to the 1.3.275 or 1.3.280 SDK version it should say this in the error message

**Comment by elsampsa** [comment]
Thanks! 
..but as I mentioned above, I *am* using **1.3.268**
..or otherwise I am completely clueless (happens frequently) and I'm using 1.0 without realizing it?

**Comment by spencer-lunarg** [comment]
>  I am using 1.3.268, not 1.0

sorry, this was my fault

- `1.3.268` == `1.3.268 SDK` 
- `Vulkan 1.0` your app version `VkInstanceCreateInfo::pApplicationInfo::apiVersion`

**Comment by elsampsa** [comment]
Thanks for clarifying!  Seems that the distinction between API and SDK versions was not clear for me (lol).
Changed to this and now the error msg disappeared:
```
// Vulkan Application Info
VkApplicationInfo appInfo = {};
appInfo.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO;
appInfo.pApplicationName = "Vulkan Example";
appInfo.applicationVersion = VK_MAKE_VERSION(1, 1, 0);
appInfo.pEngineName = "No Engine";
appInfo.engineVersion = VK_MAKE_VERSION(1, 1, 0);
appInfo.apiVersion = VK_API_VERSION_1_1;
```

**Comment by spencer-lunarg** [comment]
glad it is working now!

The big difference is the patch number (`268`) which is tied to the Vulkan Spec / Vulkan Header version. This is used to help identify if new extensions were added or not, but for "which version of Vulkan are you using" it really is just `1.0`, `1.1`, `1.2` etc as those are where we will changes things like `vkCreateRenderPass2` vs `vkCreateRenderPass2KHR` being allowed
