### ISSUE TITLE
Core Validation makes RTX CTS tests fail

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/Vulkan-ValidationLayers#7956]
**Environment:**
 - OS: Ubuntu 22.04
 - GPU and driver version: AMD RADV
 - SDK or header version if building from repo: ToT May 3rd (00e2ef09f9d7b149690a0112e55a87dcd47ee83c)

**Describe the Issue**

`./deqp-vk -n dEQP-VK.ray_tracing*check_all_handles` fails all 72 tests (assume all fail for same reason) when VVL is turned on.

**Comment by arno-lunarg** [comment]
No issues with AMD windows driver

**Comment by spencer-lunarg** [comment]
just confirmed that using the latest Mesa Driver solves this, so clearly there is something VVL was doing (that was valid) that the old RADV driver didn't like
