### ISSUE TITLE
Application hangs when GPU-VA is enabled

### ISSUE THREAD

**Issue by f32by** [KhronosGroup/Vulkan-ValidationLayers#7994]
**Environment:**
 - OS: Windows 11
 - GPU and driver version: NVIDIA 552.44
 - SDK or header version if building from repo: build from source (commit e74bfc215bf985d5cb515dcbd972b7b33611ba63)
 - Options enabled (synchronization, best practices, etc.):

```
Core:
- Object in Use
- Shader (with Caching)
- Object Lifetime
- Stateless Parameter

GPU-VA with following settings:
- Reserve Descriptor Set Binding Slot
- Linear Memory Allocation Mode
- Descriptor and OOB Checks (with Generate warning on OOB accesses even if robustness is enabled)
- Validate RayQuery SPIR-V Instructions
```

**Describe the Issue**

Application hangs and found two threads are acquiring write lock on something.

![renderthread](https://github.com/KhronosGroup/Vulkan-ValidationLayers/assets/12209857/7edeffac-70fc-4610-8b41-34eca0f09ace)
![vvl_thread](https://github.com/KhronosGroup/Vulkan-ValidationLayers/assets/12209857/99a2b497-5f6f-44e1-9b6b-6c5a0ee4f582)

**Expected behavior**

**Valid Usage ID**
If applicable, please include the validation messages encountered leading up to the issue

**Additional context**

<details>
<summary>code or terminal output</summary>

```sh
# callstacks, crashes, etc.
# EX:
Validation Error: [ VUID-vkCmdDrawMultiEXT-colorAttachmentCount-06188 ] Object 0: handle = 0x3d47e60 ...
```

</details>

**Comment by spencer-lunarg** [comment]
@f32by is this something you can hit everytime, or is it hanging different each time?

**Comment by f32by** [comment]
> @f32by is this something you can hit everytime, or is it hanging different each time?

It always hangs at the same position with GPU-VA enabled.

**Comment by spencer-lunarg** [comment]
We want to figure out this, but without a way to reproduce it is not possible

we have made a lot of improvements in the last 2 months and not sure this still occurs in the 1.3.290 SDK

If problems persists, please open a new issue and we can try to take another look
