### ISSUE TITLE
Test failures for Nvidia RTX 4060TI on Windows 10 using Nvidia 552.22 driver

### ISSUE THREAD

**Issue by johnzupin** [KhronosGroup/Vulkan-ValidationLayers#7995]
On Windows 10 using the Nvidia 552.22 driver, and running on a Nvidia RTX 4060TI GPU, the following tests fail. This was seen on VVL at `snapshot-2024wk18-15-ga5f65dae0`.

Failures on a 64 bit build:

- PositiveGpuAVBufferDeviceAddress.StoreRelaxedBlockLayout
- PositiveGpuAV.InlineUniformBlockAndRecovery
- NegativeVideo.EncodeQualityLevelPropsUnsupportedProfile
- NegativeVideo.CreateSessionUnsupportedProfile

Failures on a 32 bit build:

- NegativeYcbcr.DrawConstOffset

**Comment by artem-lunarg** [comment]
Partially overlaps with https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7735

**Comment by spencer-lunarg** [comment]
moved comment over the #7735 because who ever gets the chance to look into this will likely hit same thing
