### ISSUE TITLE
Layers: (SC) check PointSize valid usage

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#8]
**Issue by [yavn](https://github.com/yavn) (MIGRATED)**
_Friday Sep 23, 2016 at 13:37 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/974_

----

This is a feature request.

It seems that Vulkan requires (similar to GLES) that `PointSize` is written in VS when the vertex pipeline is outputting points. It would be nice if layer could detect this situation and report an error if `PointSize` is not assigned to in the shader.

Please check the spec for details. From what I understood, this only applies if vertex shader is the only active vertex stage, and only if drawing points (`VK_PRIMITIVE_TOPOLOGY_POINT_LIST`). In other stages the point size is 1.0 by default and there are other rules (e.g. see `shaderTessellationAndGeometryPointSize` feature).

**Comment by karl-lunarg** [comment]
<a href="https://github.com/chrisforbes"><img src="https://avatars1.githubusercontent.com/u/128877?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Saturday Sep 24, 2016 at 02:40 GMT_

----

Seems like a reasonable thing to want, and shouldn't be a big deal to implement. I'm not convinced you've got the rules quite right, but I'll work from the spec.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/jekstrand"><img src="https://avatars3.githubusercontent.com/u/3218227?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jekstrand](https://github.com/jekstrand) (MIGRATED)**
_Friday Jan 13, 2017 at 16:35 GMT_

----

+1 I just hit this in a CTS test where they were using tessellation with point_mode but weren't setting `gl_PointSize` in their tessellation evaluation shader.  This comment serves as a note to the person working on this to remember tessellation!

The correct rules for this are fairly subtle.  If you only have a vertex shader, then you must write `gl_PointSize` in the shader when using points.  If you have a geometry or tessellation shader, then it depends on whether or not the `shaderGeometryAndTessellationPointSize` feature is enabled.  If enabled, then you must write `gl_PointSize` in the last geometry shader stage.  If disabled, then you must not write `gl_PointSize` and you get a default of 1.0.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/zeux"><img src="https://avatars2.githubusercontent.com/u/1106629?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zeux](https://github.com/zeux) (MIGRATED)**
_Saturday Oct 28, 2017 at 03:55 GMT_

----

We've hit this issue as well - on some Android devices neglecting to output gl_PointSize results in a random value getting fed to the rasterizer, which can be hard to track down without a graphics debugger if the result of rasterization isn't directly visible on the screen...

IOW +1 - this is easy to miss and needs to be validated.

**Comment by mark-lunarg** [comment]
Need to address @chrisforbes review findings in PR #261.
