### ISSUE TITLE
Including useful information in various messages

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#80]
**Issue by [gwihlidal](https://github.com/gwihlidal) (MIGRATED)**
_Friday Apr 20, 2018 at 16:53 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2598_

----

There are a number of messages which could (I think) easily include more information/context about what has occurred. Many messages will just print out verbatim spec, and leave finding out what values, etc.. were provided that caused an error up to the user (often requiring a lot of digging app-side).

As an example:
```
Object: 0x236 | Descriptor set 0x236 encountered the following validation error at vkCmdDispatch() time: Image layout specified at vkUpdateDescriptorSets() time doesn't match actual image layout at time descriptor is used. See previous error callback for specific details.
```
This check will have compared the image layouts in order to perform this validation, so why not print out the values (friendly names not ordinals) in the message?
```
Object: 0x236 | Descriptor set 0x236 encountered the following validation error at vkCmdDispatch() time: Image layout (SOME LAYOUT HERE # 1) specified at vkUpdateDescriptorSets() time doesn't match actual image layout (SOME LAYOUT HERE # 2)  at time descriptor is used. See previous error callback for specific details.
```

As a general request, just printing out the object IDs isn't super helpful (but better than not having them), as I have to create my own mapping from ID -> debug name to be used for interpreting these messages. I'm already specifying friendly debug names for all my Vulkan objects (for RenderDoc, nsight, etc..) - could the validation layers print out those values if they exist for the object ID that is being reported? That would make my debugging life (and I'm sure countless others) much better.

Thank you!
Graham

**Comment by mark-lunarg** [comment]
Folding this into the Validation debug message tracking issue, #679.
