### ISSUE TITLE
The messenger callback contains no name when using VK_EXT_debug_utils

### ISSUE THREAD

**Issue by Jelly3D** [KhronosGroup/Vulkan-ValidationLayers#802]
When using the VK_EXT_debug_utils extension, the messenger callback object.pObjectName holds an empty string even if the _debug_report_data::debugUtilsObjectNameMap contains it.

Upon investigation I found that in the call to debug_log_msg, the object name is temporary stored in **std::string label** whose raw pointer is then given to **object_name_info.pObjectName**.

Unfortunately, when reaching the end of the scope, the string is destroyed and its internal pointer points to at least one '\0', hence the empty object name subsequently passed in the messenger callback.

**Comment by mark-lunarg** [comment]
Thanks for the fantastically detailed report, @Jelly3D.  Keep 'em coming.
