### ISSUE TITLE
VK_DYNAMIC_STATE_VIEWPORT and ray tracing pipeline

### ISSUE THREAD

**Issue by Onhi** [KhronosGroup/Vulkan-ValidationLayers#8038]
**Environment:**
 - OS: Windows 11
 - GPU and driver version: AMD Radeon 7900XTX 24.5.1
 - SDK or header version if building from repo: 1.3.283.0
 - Options enabled (synchronization, best practices, etc.): Validation

**Describe the Issue**

Launching my app with validation enabled I get this message:

```
VUID-vkCmdTraceRaysKHR-None-08608(ERROR / SPEC): msgNum: 688222058 - Validation Error: [ VUID-vkCmdTraceRaysKHR-None-08608 ] Object 0: handle = 0x3811cd7bf90, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0xf8c81f0000000143, name = m_ray_tracing_pipeline, type = VK_OBJECT_TYPE_PIPELINE; | MessageID = 0x29056f6a | vkCmdTraceRaysKHR():  VkPipeline 0xf8c81f0000000143[m_ray_tracing_pipeline] doesn't set up VK_DYNAMIC_STATE_VIEWPORT|VK_DYNAMIC_STATE_SCISSOR, but it calls the related dynamic state setting commands. The Vulkan spec states: If a pipeline is bound to the pipeline bind point used by this command, there must not have been any calls to dynamic state setting commands for any state not specified as dynamic in the VkPipeline object bound to the pipeline bind point used by this command, since that pipeline was bound (https://vulkan.lunarg.com/doc/view/1.3.283.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdTraceRaysKHR-None-08608)
    Objects: 2
       [0]  0x3811cd7bf90, type: 6, name: NULL
       [1]  0xf8c81f0000000143, type: 19, name: m_ray_tracing_pipeline
```

Note, there are no calls to vkCmdSetViewport between calls to vkCmdBindPipeline and vkCmdTraceRaysKHR.
Attempting to set the dynamic states while creating the RT pipeline creates another validation error.

**Expected behavior**

No validation error.

**Valid Usage ID**

688222058

**Comment by spencer-lunarg** [comment]
yes, the only dynamic state allowed for Ray Tracing is `VK_DYNAMIC_STATE_RAY_TRACING_PIPELINE_STACK_SIZE_KHR`

I noticed this and this should have been fixed in https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/b5b7e5b0aa8e58670dff0dc4e5caa9572227ca39 

unfortunately, this change was added a few days after the 1.3.283 SDK branch

If you want to test with the latest version to confirm, we have built binaries at the bottom of https://github.com/KhronosGroup/Vulkan-ValidationLayers/actions/runs/9155344430

**Comment by Onhi** [comment]
Yes indeed, it's fixed with the new version.

**Comment by spencer-lunarg** [comment]
Thanks for the confirmation!

Marking closed from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8012
