### ISSUE TITLE
Prompt on device when trying to run tests on Android 14

### ISSUE THREAD

**Issue by johnzupin** [KhronosGroup/Vulkan-ValidationLayers#8045]
Running into this problem trying to run VVL tests on Android 14, I get a prompt trying to run tests that says: 

```
VulkanLayerValidtionTests

This app was built for an older version of Android. It might not work properly and doesn't include the latest security and privacy protections. Check for an update, or contact the app's developer
```

Nothing runs until "ok" is selected which is a problem for automation.

Changing the "targetSkdVersion" in `tests/android/AndroidManifest.xml` to 33 seems to fix the issue.

Is there a better way around this?

**Comment by spencer-lunarg** [comment]
https://github.com/LunarG/gfxreconstruct/pull/1079 is a good example of this

We should just update the `VulkanLayerValidtionTests` app, there is zero reason we need to keep it working on such an old Android version (The layers still support old Android, but for the tests we control the environment)
