### ISSUE TITLE
Something is up with vkGetDeviceProcAddr and vkGetPhysicalDeviceCalibrateableTimeDomainsKHR

### ISSUE THREAD

**Issue by Onhi** [KhronosGroup/Vulkan-ValidationLayers#8048]
**Environment:**
 - OS: Windows 11
 - GPU and driver version: AMD Radeon 7900XTX 24.5.1
 - SDK or header version if building from repo: 1.3.283.0
 - Options enabled (synchronization, best practices, etc.): Validation

**Describe the Issue**

Weird validation message on vkCreateDevice.

`WARNING-vkGetDeviceProcAddr-device(WARN / SPEC): msgNum: 582089644 - Validation Warning: [ WARNING-vkGetDeviceProcAddr-device ] | MessageID = 0x22b1fbac | vkGetDeviceProcAddr(): pName is trying to grab vkGetPhysicalDeviceCalibrateableTimeDomainsKHR which is an instance level function
    Objects: 0`

**Expected behavior**

No weird message...

**Valid Usage ID**
582089644

**Comment by spencer-lunarg** [comment]
sorry, I am not seeing what is wrong here

You are using vkGet**Device**ProcAddr and not vkGet**Instance**ProcAddr for an instance level function (`vkGetPhysicalDeviceCalibrateableTimeDomainsKHR`) so you will get `NULL` returned (but you will get the real function pointer if you use `vkGetInstanceProcAddr`)

![image](https://github.com/KhronosGroup/Vulkan-ValidationLayers/assets/115671160/34b757ec-082e-4e04-9890-c086f2359901)

**Comment by Onhi** [comment]
The thing is, I'm not calling either functions (vkGetDeviceProcAddr / vkGetDeviceProcAdd) it's just a message I get calling vkCreateDevice,

**Comment by Onhi** [comment]
Here's the text it produced:
(Sorry for the wall of text)

> LAYER:            Checking for Layer Manifest files in Registry at HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers
> INFO | LAYER:     Located json file "C:\Program Files\RenderDoc\renderdoc.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
> INFO | LAYER:     Located json file "C:\Program Files (x86)\Epic Games\Epic Online Services\managedArtifacts\98bc04bc842e4906993fd6d6644ffb8d\EOSOverlayVkLayer-Win64.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
> INFO | LAYER:     Located json file "C:\Program Files (x86)\Steam\SteamOverlayVulkanLayer64.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
> INFO | LAYER:     Located json file "C:\Program Files (x86)\Steam\SteamFossilizeVulkanLayer64.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
> INFO | LAYER:     Located json file "C:\Users\g_las\AppData\Local\LunarG\vkconfig\override\VkLayer_override.json" from registry "HKEY_CURRENT_USER\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
> INFO | LAYER:     Encountered meta-layer "VK_LAYER_LUNARG_override"
> INFO | LAYER:     Using the global override layer
> WARNING | LAYER:  Override layer has override paths set to C:\VulkanSDK\1.3.283.0\Bin
> LAYER:            Searching for layer manifest files
> LAYER:               In following locations:
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin
> LAYER:               Found the following files:
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_api_dump.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_gfxreconstruct.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_khronos_profiles.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_khronos_shader_object.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_khronos_synchronization2.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_khronos_validation.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_monitor.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_screenshot.json
> INFO | LAYER:     Meta-layer "VK_LAYER_LUNARG_override" all 1 component layers appear to be valid.
> LAYER:              [0] VK_LAYER_KHRONOS_validation
> LAYER:            Checking for Layer Manifest files in Registry at HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers
> INFO | LAYER:     Located json file "C:\Program Files\RenderDoc\renderdoc.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
> INFO | LAYER:     Located json file "C:\Program Files (x86)\Epic Games\Epic Online Services\managedArtifacts\98bc04bc842e4906993fd6d6644ffb8d\EOSOverlayVkLayer-Win64.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
> INFO | LAYER:     Located json file "C:\Program Files (x86)\Steam\SteamOverlayVulkanLayer64.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
> INFO | LAYER:     Located json file "C:\Program Files (x86)\Steam\SteamFossilizeVulkanLayer64.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
> INFO | LAYER:     Located json file "C:\Users\g_las\AppData\Local\LunarG\vkconfig\override\VkLayer_override.json" from registry "HKEY_CURRENT_USER\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
> INFO | LAYER:     Encountered meta-layer "VK_LAYER_LUNARG_override"
> INFO | LAYER:     Using the global override layer
> WARNING | LAYER:  Override layer has override paths set to C:\VulkanSDK\1.3.283.0\Bin
> LAYER:            Searching for layer manifest files
> LAYER:               In following locations:
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin
> LAYER:               Found the following files:
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_api_dump.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_gfxreconstruct.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_khronos_profiles.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_khronos_shader_object.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_khronos_synchronization2.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_khronos_validation.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_monitor.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_screenshot.json
> INFO | LAYER:     Meta-layer "VK_LAYER_LUNARG_override" all 1 component layers appear to be valid.
> LAYER:              [0] VK_LAYER_KHRONOS_validation
> LAYER:            Checking for Layer Manifest files in Registry at HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers
> INFO | LAYER:     Located json file "C:\Program Files\RenderDoc\renderdoc.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
> INFO | LAYER:     Located json file "C:\Program Files (x86)\Epic Games\Epic Online Services\managedArtifacts\98bc04bc842e4906993fd6d6644ffb8d\EOSOverlayVkLayer-Win64.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
> INFO | LAYER:     Located json file "C:\Program Files (x86)\Steam\SteamOverlayVulkanLayer64.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
> INFO | LAYER:     Located json file "C:\Program Files (x86)\Steam\SteamFossilizeVulkanLayer64.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
> INFO | LAYER:     Located json file "C:\Users\g_las\AppData\Local\LunarG\vkconfig\override\VkLayer_override.json" from registry "HKEY_CURRENT_USER\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
> INFO | LAYER:     Encountered meta-layer "VK_LAYER_LUNARG_override"
> INFO | LAYER:     Using the global override layer
> WARNING | LAYER:  Override layer has override paths set to C:\VulkanSDK\1.3.283.0\Bin
> LAYER:            Searching for layer manifest files
> LAYER:               In following locations:
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin
> LAYER:               Found the following files:
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_api_dump.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_gfxreconstruct.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_khronos_profiles.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_khronos_shader_object.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_khronos_synchronization2.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_khronos_validation.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_monitor.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_screenshot.json
> INFO | LAYER:     Meta-layer "VK_LAYER_LUNARG_override" all 1 component layers appear to be valid.
> LAYER:              [0] VK_LAYER_KHRONOS_validation
> LAYER:            Checking for Layer Manifest files in Registry at HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers
> INFO | LAYER:     Located json file "C:\Program Files\RenderDoc\renderdoc.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
> INFO | LAYER:     Located json file "C:\Program Files (x86)\Epic Games\Epic Online Services\managedArtifacts\98bc04bc842e4906993fd6d6644ffb8d\EOSOverlayVkLayer-Win64.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
> INFO | LAYER:     Located json file "C:\Program Files (x86)\Steam\SteamOverlayVulkanLayer64.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
> INFO | LAYER:     Located json file "C:\Program Files (x86)\Steam\SteamFossilizeVulkanLayer64.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
> INFO | LAYER:     Located json file "C:\Users\g_las\AppData\Local\LunarG\vkconfig\override\VkLayer_override.json" from registry "HKEY_CURRENT_USER\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
> INFO | LAYER:     Encountered meta-layer "VK_LAYER_LUNARG_override"
> INFO | LAYER:     Using the global override layer
> WARNING | LAYER:  Override layer has override paths set to C:\VulkanSDK\1.3.283.0\Bin
> LAYER:            Searching for layer manifest files
> LAYER:               In following locations:
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin
> LAYER:               Found the following files:
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_api_dump.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_gfxreconstruct.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_khronos_profiles.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_khronos_shader_object.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_khronos_synchronization2.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_khronos_validation.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_monitor.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_screenshot.json
> INFO | LAYER:     Meta-layer "VK_LAYER_LUNARG_override" all 1 component layers appear to be valid.
> LAYER:              [0] VK_LAYER_KHRONOS_validation
> LAYER:            Checking for Layer Manifest files in Registry at HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers
> INFO | LAYER:     Located json file "C:\Program Files\RenderDoc\renderdoc.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
> INFO | LAYER:     Located json file "C:\Program Files (x86)\Epic Games\Epic Online Services\managedArtifacts\98bc04bc842e4906993fd6d6644ffb8d\EOSOverlayVkLayer-Win64.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
> INFO | LAYER:     Located json file "C:\Program Files (x86)\Steam\SteamOverlayVulkanLayer64.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
> INFO | LAYER:     Located json file "C:\Program Files (x86)\Steam\SteamFossilizeVulkanLayer64.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
> INFO | LAYER:     Located json file "C:\Users\g_las\AppData\Local\LunarG\vkconfig\override\VkLayer_override.json" from registry "HKEY_CURRENT_USER\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
> INFO | LAYER:     Encountered meta-layer "VK_LAYER_LUNARG_override"
> INFO | LAYER:     Using the global override layer
> WARNING | LAYER:  Override layer has override paths set to C:\VulkanSDK\1.3.283.0\Bin
> LAYER:            Searching for layer manifest files
> LAYER:               In following locations:
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin
> LAYER:               Found the following files:
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_api_dump.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_gfxreconstruct.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_khronos_profiles.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_khronos_shader_object.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_khronos_synchronization2.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_khronos_validation.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_monitor.json
> LAYER:                  C:\VulkanSDK\1.3.283.0\Bin\VkLayer_screenshot.json
> INFO | LAYER:     Meta-layer "VK_LAYER_LUNARG_override" all 1 component layers appear to be valid.
> LAYER:              [0] VK_LAYER_KHRONOS_validation
> DEBUG | LAYER:    Loading layer library C:\VulkanSDK\1.3.283.0\Bin\.\VkLayer_khronos_validation.dll
> INFO | LAYER:     Insert instance layer "VK_LAYER_KHRONOS_validation" (C:\VulkanSDK\1.3.283.0\Bin\.\VkLayer_khronos_validation.dll)
> DEBUG | LAYER:    Loading layer library C:\WINDOWS\System32\DriverStore\FileRepository\u0402593.inf_amd64_66758692e35a2906\B402774\.\amdvlk64.dll
> INFO | LAYER:     Insert instance layer "VK_LAYER_AMD_switchable_graphics" (C:\WINDOWS\System32\DriverStore\FileRepository\u0402593.inf_amd64_66758692e35a2906\B402774\.\amdvlk64.dll)
> LAYER:            vkCreateInstance layer callstack setup to:
> LAYER:               <Application>
> LAYER:                 ||
> LAYER:               <Loader>
> LAYER:                 ||
> LAYER:               VK_LAYER_AMD_switchable_graphics
> LAYER:                       Type: Implicit
> LAYER:                           Disable Env Var:  DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1
> LAYER:                       Manifest: C:\WINDOWS\System32\DriverStore\FileRepository\u0402593.inf_amd64_66758692e35a2906\B402774\amd-vulkan64.json
> LAYER:                       Library:  C:\WINDOWS\System32\DriverStore\FileRepository\u0402593.inf_amd64_66758692e35a2906\B402774\.\amdvlk64.dll
> LAYER:                 ||
> LAYER:               VK_LAYER_KHRONOS_validation
> LAYER:                       Type: Explicit
> LAYER:                       Manifest: C:\VulkanSDK\1.3.283.0\Bin\VkLayer_khronos_validation.json
> LAYER:                       Library:  C:\VulkanSDK\1.3.283.0\Bin\.\VkLayer_khronos_validation.dll
> LAYER:                 ||
> LAYER:               <Drivers>
> INFO | LAYER:     Inserted device layer "VK_LAYER_KHRONOS_validation" (C:\VulkanSDK\1.3.283.0\Bin\.\VkLayer_khronos_validation.dll)
> INFO | LAYER:     Failed to find vkGetDeviceProcAddr in layer "C:\WINDOWS\System32\DriverStore\FileRepository\u0402593.inf_amd64_66758692e35a2906\B402774\.\amdvlk64.dll"
> DRIVER | LAYER:   vkCreateDevice layer callstack setup to:
> DRIVER | LAYER:      <Application>
> DRIVER | LAYER:        ||
> DRIVER | LAYER:      <Loader>
> DRIVER | LAYER:        ||
> LAYER:               VK_LAYER_KHRONOS_validation
> LAYER:                       Type: Explicit
> LAYER:                       Manifest: C:\VulkanSDK\1.3.283.0\Bin\VkLayer_khronos_validation.json
> LAYER:                       Library:  C:\VulkanSDK\1.3.283.0\Bin\.\VkLayer_khronos_validation.dll
> LAYER:                 ||
> DRIVER | LAYER:      <Device>
> DRIVER | LAYER:          Using "AMD Radeon RX 7900 XTX" with driver: "C:\WINDOWS\System32\DriverStore\FileRepository\u0402593.inf_amd64_66758692e35a2906\B402774\.\amdvlk64.dll"
> WARNING-vkGetDeviceProcAddr-device(WARN / SPEC): msgNum: 582089644 - Validation Warning: [ WARNING-vkGetDeviceProcAddr-device ] | MessageID = 0x22b1fbac | vkGetDeviceProcAddr(): pName is trying to grab vkGetPhysicalDeviceCalibrateableTimeDomainsKHR which is an instance level function
>     Objects: 0

**Comment by spencer-lunarg** [comment]
So I see

```
LAYER: VK_LAYER_AMD_switchable_graphics
LAYER: Type: Implicit
```

so since it is the only implicit layer if you could please try `set VK_LOADER_LAYERS_DISABLE=~implicit~` and it goes away, it means we need to report the bug to AMDVLK

**Comment by Onhi** [comment]
Yes, that worked. Will you report the issue to AMDVLK or should I do it?

**Comment by spencer-lunarg** [comment]
I'll report it, it might not actually be in AMDVLK, but will hunt down via AMD contacts who needs to make this change

Thanks for helping me narrow this down, in the meantime you can go `set VK_LAYER_MESSAGE_ID_FILTER=WARNING-vkGetDeviceProcAddr-device` to clear things out
