### ISSUE TITLE
Crash when VkDescriptorSetLayoutBinding structure defines 0 bindings, and vkUpdateDescriptorSets called with bindings specified

### ISSUE THREAD

**Issue by FireBanana** [KhronosGroup/Vulkan-ValidationLayers#8065]
**Environment:**
 - OS: Windows 11
 - GPU: Nvidia A1000/AMD 7600
 - Options enabled (synchronization, best practices, etc.): Default
 - SDK ver: 1.3.268

**Describe the Issue**
Crash occurs in CoreChecks::ValidateWriteUpdate when incorrect VkDescriptorLayoutBinding specified. You can see the usage here: https://github.com/FireBanana/MiniEngine/blob/9bd8d265a9ec404f32091d56f0a8be0cde28655d/src/backend/vulkan/VulkanDescriptorSet.cpp

In the build() method, vkCreateDescriptorSetLayout is called incorrectly, which causes vkUpdateDescriptorSets to crash without any warnings or errors.

**Expected behavior**
Don't crash, mention incorrect bindings as errors.

**Comment by spencer-lunarg** [comment]
Thanks @FireBanana for raising this! I just pushed a fix and actually it seem like you caught a gap in the Vulkan spec ([internal change](https://gitlab.khronos.org/vulkan/vulkan/-/issues/3890)) as  this was never banned anywhere (but clearly is not allowed)

**Comment by FireBanana** [comment]
Thanks for the quick update!
