### ISSUE TITLE
Error messages should not reference internal "global index", but instead the binding relative index.

### ISSUE THREAD

**Issue by edrickhong** [KhronosGroup/Vulkan-ValidationLayers#812]
**was: Validation layers reporting wrong message for unupdated descriptor set binding index**

I have a shader that uses 4 bindings in a desc set

binding 0 sampler
binding 1 sampler[16]
binding 2 sampler
binding 3 uniform

I've updated all the bindings except for binding1 indices 2 to 15

The error message generated was:
Descriptor in binding 1 at global descriptor index 3 is being used in draw but has not been updated

It should be index 2, no? 
Unless the global descriptor index describes the descriptor as a whole, starting from binding 0. 
Even so, I feel like this isn't clear since it first states it is at binding 1

**Comment by jzulauf-lunarg** [comment]
@edrickhong -- you have correctly deduced the meaning of the error message, but frankly, it's a terrible message.

Triage notes:  In this specific case `cvdescriptorset::DescriptorSet::ValidateDrawState` has the base offset for the binding stored in `index_range.start` -- so there is not excuse for reporting the meaningless (to the user) "global index" as that's an internal concept specific to how the validation layers store descriptor validation data.

All of the "at global index" messages should be modified to output the index *within* the binding.

(updating title)

**Comment by jzulauf-lunarg** [comment]
Triage note: searching `at global descriptor index ` was useful.

**Comment by locke-lunarg** [comment]
[Pull request #823](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/823)

**Comment by jzulauf-lunarg** [comment]
@edrickhong Should be fixed on master now.
