### ISSUE TITLE
Validation layers fail to build on Linux with Vulkan-Headers master

### ISSUE THREAD

**Issue by rg3igalia** [KhronosGroup/Vulkan-ValidationLayers#813]
After Vulkan-Headers was updated to version 1.1.105, the validation layers no longer build.

```
$ ninja -j1
[1/83] Generating vk_enum_string_helper.h
FAILED: vk_enum_string_helper.h 
cd /home/rgarcia/.cache/jhbuild/build/Vulkan-ValidationLayers && /usr/bin/python3 /home/rgarcia/devel/jh-source/Vulkan-ValidationLayers/scripts/lvl_genvk.py -registry /home/rgarcia/devel/jh-install/share/vulkan/registry/vk.xml -scripts /home/rgarcia/devel/jh-install/share/vulkan/registry vk_enum_string_helper.h
Traceback (most recent call last):
  File "/home/rgarcia/devel/jh-source/Vulkan-ValidationLayers/scripts/lvl_genvk.py", line 695, in <module>
    genTarget(args)
  File "/home/rgarcia/devel/jh-source/Vulkan-ValidationLayers/scripts/lvl_genvk.py", line 565, in genTarget
    reg.apiGen(options)
  File "/home/rgarcia/devel/jh-install/share/vulkan/registry/reg.py", line 943, in apiGen
    regEmitExtensions = re.compile(self.genOpts.emitExtensions)
  File "/usr/lib64/python3.7/re.py", line 234, in compile
    return _compile(pattern, flags)
  File "/usr/lib64/python3.7/re.py", line 285, in _compile
    raise TypeError("first argument must be string or compiled pattern")
TypeError: first argument must be string or compiled pattern
ninja: build stopped: subcommand failed.
```

NB: I also tried branch mikes-script-sync but it won't build either due to an enum to string conversion generated without ifdef guards for an enum that only exists in Win32.

**Comment by KarenGhavam-lunarG** [comment]
Although the Vulkan-headers has a new header, the validation layer repo has not yet moved forward to that new header. In the BUILD.md document see the following:

> There is a Python utility script, scripts/update_deps.py, that you can use to gather and build the dependent repositories mentioned above. This program also uses information stored in the scripts/known-good.json file to checkout dependent repository revisions that are known to be compatible with the revision of this repository that you currently have checked out.

**Comment by jzulauf-lunarg** [comment]
Vulkan-ValidationLayers are not guaranteed to function with the tip of master on *any* of the constituent branches.  Breakage and errors on the tip of those components aside, there may be incompatibilities, new features, or deprecations that affect compatibility.

**Comment by rg3igalia** [comment]
Thank you both! I somehow missed that section of BUILD.md. However, do you think having an issue like this one open can still be useful?

To give you some context: I'm working on validations for an extension that was published as part of 1.1.105 and would like to know when the validation layers can be built with that version of the headers, in order to submit the pull request. An issue like this one would allow me to get a notification when the validation layers are ready.

**Comment by jzulauf-lunarg** [comment]
@rg3igalia  -- there isn't an automated way built-in to github to receive notices when a file (for example known_good.json) changes, though there are apparently external tools YMMV.  

The best way to know the latest supported header is on the [releases page]( https://github.com/KhronosGroup/Vulkan-ValidationLayers/releases) -- the v1.x.y tags are the commits supporting the matching release of the header.

Adding a tag *does* *not* generate the "Releases Only" watcher notification (with additional manual steps).  Watching the project will get you notices of *all* changes, comments etc. -- which will get you the notice you want, but likely be too noisy to be useful.

**Comment by rg3igalia** [comment]
@jzulauf-lunarg Exactly, thanks. Those problems you mention are why I suggested having an open issue to track support for Vulkan-Headers 1.1.105 could be useful. For example, I cannot submit a pull request for VK_EXT_host_query_reset until the layers are updated. With an issue, I can subscribe to it here in Github and receive notifications about comments and status changes without other noisy traffic.

**Comment by jzulauf-lunarg** [comment]
@rg3igalia -- just so.  Given the lack of any better means to track this, I've added the issue.  https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/817 .

As a general process issue we won't be adding these issues for each header update, but for people needing access and notification to a specific update, a tracking issue assigned to the person doing the header update seems reasonable.
