### ISSUE TITLE
GPU-AV: Fix logic in RestorablePipelineState::Restore when using shader objects

### ISSUE THREAD

**Issue by arno-lunarg** [KhronosGroup/Vulkan-ValidationLayers#8136]
Descriptor sets and push constants ranges need to be rebound, using the proper pipeline layouts

Linked to https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8120

**Comment by spencer-lunarg** [comment]
changes added to https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8120 but still need to confirm for Shader Objects
