### ISSUE TITLE
No resource type and name in error message

### ISSUE THREAD

**Issue by Goshido** [KhronosGroup/Vulkan-ValidationLayers#8139]
**Environment:**
 - OS: _Android 11_
 - GPU and driver version: _GPU_: _Mali G76_, driver: _26.0.0_
 - SDK or header version if building from repo: _1.3.287_, _SHA-1_ `15ba84ba94ff2ed473474deba2b4f2af4705b1fb`
 - Options enabled (synchronization, best practices, etc.): `VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT` and `VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT`

**Describe the Issue**

Is it normal that sync validation does not provide description which kind of resource is not synchronized? I mean `VkImage` or `VkBuffer`. I gave meaningful names to each _Vulkan_ resource in the app. The typical message looks like this:

```txt
severity: Error
type: Validation
message ID name: SYNC-HAZARD-WRITE-AFTER-WRITE
message ID: 0x5C0EC5D6
queues: N/A
command buffers: N/A
objects: [nullptr]
message: Validation Error: [ SYNC-HAZARD-WRITE-AFTER-WRITE ] Object 0: handle = 0xb400007ed9519e68,
    type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0x5c0ec5d6 | vkQueueSubmit():  Hazard WRITE_AFTER_WRITE for entry 0,
    VkCommandBuffer 0xb400007e37fad308[Frame in flight #1], Submitted access info (submitted_usage:
    SYNC_COMPUTE_SHADER_SHADER_STORAGE_WRITE, command: vkCmdDispatch, seq_no: 277, reset_no: 2, debug_region: Exposure).
    Access info (prior_usage: SYNC_COMPUTE_SHADER_SHADER_STORAGE_WRITE, write_barriers: 0, queue: 
    VkQueue 0xb400007ed9519e68[], submit: 209, batch: 0, batch_tag: 2152, command: vkCmdDispatch,
    command_buffer: VkCommandBuffer 0xb400007e776cec68[Frame in flight #0], seq_no: 284, reset_no: 2,
    debug_region: Exposure).
```

**Expected behavior**

Validation warning contains resource type and name.

**Valid Usage ID**
_N/A_

**Comment by artem-lunarg** [comment]
@Goshido there is limitation to the amount of information that can be provided by `prior_usage` access, but it should be possible to provide resource information for `submitted_usage`.

**Comment by Goshido** [comment]
Quick investigation: It turns out that 3 `VkBuffer` do not have proper sync. Here is compute shader snippet for them:

```hlsl
[[vk::binding ( BIND_SYNC_MIP_5, SET_RESOURCE )]]
globallycoherent RWTexture2D<float32_t>             g_syncMip5:         register ( u0 );

[[vk::binding ( BIND_EXPOSURE, SET_RESOURCE )]]
RWStructuredBuffer<float32_t>                       g_exposure:         register ( u1 );

[[vk::binding ( BIND_GLOBAL_ATOMIC, SET_RESOURCE )]]
globallycoherent RWStructuredBuffer<uint32_t>       g_globalAtomic:     register ( u2 );

[[vk::binding ( BIND_TEMPORAL_LUMA, SET_RESOURCE )]]
RWStructuredBuffer<float32_t>                       g_temporalLuma:     register ( u3 );
```

**Comment by Goshido** [comment]
@artem-lunarg could I expect an improvement or it's super hard limitation for _VVL_ architecture?

**Comment by artem-lunarg** [comment]
I'll try to add resource information to `submitted_usage`, does not look hard except I missed something. Adding more information to `prior_usage ` is much harder, this requires to store a lot of information. We plan improvements, but there might be a tendency that *current access* information is more detailed compared to the *previous access*.

**Comment by Goshido** [comment]
Great. I gonna wait. Thx 👍

**Comment by artem-lunarg** [comment]
@Goshido Going to postpone the fix. Doable, but need to update memory allocation scheme first.

Implementation note: instead of allocating handle array per usage record, allocate single buffer per command buffer context and store only index/count in the usage record. This will avoid performance impact from large number of allocations. Memory wise single buffer solution is easy to manage (e.g. disable storing handles when memory is a concern) and easy to collect stats.

**Comment by artem-lunarg** [comment]
@Goshido Support is added here https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8222. Currently it's buffers only, images will be later after we test current solution for a bit.

**Comment by Goshido** [comment]
Awesome 👍
