### ISSUE TITLE
Implement support for VK_EXT_host_query_reset

### ISSUE THREAD

**Issue by rg3igalia** [KhronosGroup/Vulkan-ValidationLayers#816]
I have validations ready for the VK_EXT_host_query_reset extension, including tests. This extension was added in 1.1.104. As soon as the validation layers are updated to support Vulkan-Headers 1.1.105 (there's no 1.1.104 update in the commits), I will submit a pull request.

This issue is related to https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/813.

**Comment by jzulauf-lunarg** [comment]
See #817 for 1.1.105 notification

**Comment by rg3igalia** [comment]
This is solved since https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/858 was merged.
