### ISSUE TITLE
Need Support for Vulkan-Headers version 1.1.105 

### ISSUE THREAD

**Issue by jzulauf-lunarg** [KhronosGroup/Vulkan-ValidationLayers#817]
Please reference this issue in pull requests to integrate 1.1.105 support, or if a later version is supported instead.

**Comment by jzulauf-lunarg** [comment]
@rg3igalia  -- follow this one for the updates you're looking for.

**Comment by rg3igalia** [comment]
Subscribed. Thanks!

**Comment by shannon-lunarg** [comment]
Vulkan header version 1.1.106 is now supported in the Vulkan-ValidationLayers repo, Vulkan-Tools, and Vulkan-Loader. Known-good updates are still rolling out on the LunarG repositories (LuanrG-VulkanSamples and LunarG-VulkanTools).

I will close this issue once _all_ relevant repos have updated known-good files.

**Comment by rg3igalia** [comment]
Thanks, @shannon-lunarg !
