### ISSUE TITLE
ValidationLayers linker errors when building from source on Windows 11 on ARM64 / Snapdragon X Elite CPU

### ISSUE THREAD

**Issue by Amr-Gameel** [KhronosGroup/Vulkan-ValidationLayers#8184]
**Environment:**
 - OS: Windows 11 on ARM64
 - GPU and driver version: Snapdragon X-Elite / Adreno embedded GPU, not sure about the driver version, but it was only just launched this week
 - SDK or header version if building from repo: Building from source / downloaded via git, I suppose this is the latest version
 - Options enabled (synchronization, best practices, etc.): None

**Describe the Issue**
Is there a Vulkan SDK for Windows 11 ARM (Snapdragon X-Elite)? I suppose there isn't. I am trying to compile Vulkan from source for ARM64. I managed to compile Vulkan Loader, and got a sample compiling and running. However, I am running into a linking problem with Validation Layers. There are 514 unresolved externals.

Please see a log of the errors as attached.
Could anyone please guide me on what is missing?
[message.txt](https://github.com/user-attachments/files/15945595/message.txt)

**Comment by richard-lunarg** [comment]
As of about 15 minutes ago, there is an Alpha of the Windows SDK for ARM at vulkan.lunarg.com. From your log it looks like all of the dependencies were not building as ARM, thus the linker errors. All the layers in the new SDK are ARM64X and will work with both x86_64 and ARM64 binaries. The shader toolchain, etc. is all ARM64 too.

**Comment by spencer-lunarg** [comment]
closing for now, since there was everything build for the SDK, we know this should work, just a matter of making sure everything is ARM based

happy to open if finding more build issues related to this
