### ISSUE TITLE
Allow GPU-AV and DebugPrintF to be used at the same time

### ISSUE THREAD

**Issue by arno-lunarg** [KhronosGroup/Vulkan-ValidationLayers#8192]
Things to do:
- Remove `VUID-VkValidationFeaturesEXT-pEnabledValidationFeatures-02968` (no GPU AV and DebugPrintF at the same time)

**Comment by spencer-lunarg** [comment]
so yes, I think we will want to fully confirm we have it working with both, but then I will remove/update the VUs in the spec for `VUID-VkValidationFeaturesEXT-*`
