### ISSUE TITLE
ValidateShaderStageInputOutputLimits doesn't handle outermost array dimension special case

### ISSUE THREAD

**Issue by jeffbolznv** [KhronosGroup/Vulkan-ValidationLayers#820]
This came up here (i.e. an existing test hits it): https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/808#discussion_r269353157

Tessellation control input variables must have an array dimension that is at least the number of vertices in the patch, and that dimension should not be counted against the maxTessellationControlPerVertexInputComponents limit. But ValidateShaderStageInputOutputLimits doesn't handle this, and thus overcounts components by a factor of 32!

The shader in that example indeed has an input array of 32 elements:

```
%gl_PerVertex_0 = OpTypeStruct %v4float %float %_arr_float_uint_1 %_arr_float_uint_1
    %uint_32 = OpConstant %uint 32
%_arr_gl_PerVertex_0_uint_32 = OpTypeArray %gl_PerVertex_0 %uint_32
%_ptr_Input__arr_gl_PerVertex_0_uint_32 = OpTypePointer Input %_arr_gl_PerVertex_0_uint_32
      %gl_in = OpVariable %_ptr_Input__arr_gl_PerVertex_0_uint_32 Input
```

Some relevant spec language:

```
Tessellation control
ifdef::VK_NV_mesh_shader[]
and mesh
endif::VK_NV_mesh_shader[]
shader per-vertex output variables and blocks, and tessellation control,
tessellation evaluation, and geometry shader per-vertex input variables and
blocks are required to be declared as arrays, with each element representing
input or output values for a single vertex of a multi-vertex primitive.
For the purposes of interface matching, the outermost array dimension of
such variables and blocks is ignored.
```

(emphasis mine):
```
  * [[limits-maxTessellationControlPerVertexInputComponents]]
    pname:maxTessellationControl**PerVertex**InputComponents is the maximum
    number of components of input variables which can: be provided as
    **per-vertex** inputs to the tessellation control shader stage.
```

**Comment by mark-lunarg** [comment]
We were just talking about this strangeness yesterday -- thanks so much for finding the problem!

**Comment by jzulauf-lunarg** [comment]
@MulattoKid -- this looks like code you submitted from last August.  Would you be able to look at it?

**Comment by jzulauf-lunarg** [comment]
Triage Notes:  The error appears to be in how the number of input components is computed in `CoreChecks::ValidateShaderStageInputOutputLimits`

**Comment by jeffbolznv** [comment]
I have a change pending for this that I will push later today. I can't assign myself, but if somebody else wants to assign me that's fine.
