### ISSUE TITLE
O(n^2) algorithm in `CoreChecks::RecordCmdCopyBuffer`

### ISSUE THREAD

**Issue by Axel-Reactor** [KhronosGroup/Vulkan-ValidationLayers#8224]
**Environment:**
 - OS: doesn't matter
 - GPU and driver version: doesn't matter
 - SDK or header version if building from repo: 1.3.283.0
 - Options enabled (synchronization, best practices, etc.): just the defaults

**Describe the Issue**

The checks in `CoreChecks::RecordCmdCopyBuffer` effectively hang the validation layers when calling `vkCmdCopyBuffer` with ~100 of regions.

**Expected behavior**

`O(log(n))`

**Comment by spencer-lunarg** [comment]
@arno-lunarg has this been fixed in the refactor from last SDK?

**Comment by arno-lunarg** [comment]
not at all, I will take a look but for now it is not a priority

**Comment by Novum** [comment]
This was for buffer ranges, not texels.

**Comment by jeremyg-lunarg** [comment]
@arno-lunarg I think you can make this better by changing the inner loop of ` CoreChecks::RecordCmdCopyBuffer`

```
    for (uint32_t i = 0; i < regionCount; ++i) {
         const auto &src = src_ranges[i]; 
         for (uint32_t j = 0; j < regionCount; ++j) {  
```
Starting from j = i + 1 should give the same results.

Maybe it is possible to get to O(log(n)) as suggested but that would require more than 5 minutes of pondering, at least for me.

**Comment by arno-lunarg** [comment]
Ah wow I just confused myself, it is not gpu-av related at all.... Sorry, I will try to take a look this week!

**Comment by arno-lunarg** [comment]
Also since it is a perf problem in core validation, it now becomes a priority

**Comment by spencer-lunarg** [comment]
sorry, want to take blame, I labeled this as GPU-AV and that rightfully confused Arno... sorry, Arno has profiling setup now so should be able to get this improved!

**Comment by arno-lunarg** [comment]
I made some optimisations, hopefully things get better on your hand. If they don't, please feel free to re-open the issues. Again sorry for the brain fart I had, I should have worked on this earlier.
