### ISSUE TITLE
BUILD.gn "vulkan_clean_old_validation_layer_objects" removing files unrelated to VVL

### ISSUE THREAD

**Issue by romanl-g** [KhronosGroup/Vulkan-ValidationLayers#8238]
`action("vulkan_clean_old_validation_layer_objects") `

is nuking files by glob which can match files unrelated to VVL

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/e0f6324b75b14466dea699ba4979cfe2096ee5e9/BUILD.gn#L40-L42

This is creating a race condition between build rules resulting in flaky build failures in ANGLE: https://g-issues.angleproject.org/issues/350816748#comment5

@mark-lunarg

**Comment by romanl-g** [comment]
In our specific case, the files going missing are `libVkLayer_lunarg_api_dump.so` and `VkLayer_lunarg_api_dump.json` after their generation got enabled by https://crrev.com/c/5649937

But removing files by glob looks like a risky idea in general.. Seems like this is some old cleanup code - can it be removed altogether?

**Comment by mark-lunarg** [comment]
I too think it should be possible to remove it altogether, and will take a look tomorrow when this high-temperature national holiday is over.

**Comment by spencer-lunarg** [comment]
@romanl-g if things are still not working let us know!

**Comment by romanl-g** [comment]
thanks, this should resolve the issue!

**Comment by romanl-g** [comment]
Oops, this led to an issue due to now unused var:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8242/commits/12048d7d846e9020a11feb8650587f6898414d50#r1668658950

**Comment by romanl-g** [comment]
hmm looks like the link is not working
```
/b/s/w/ir/cache/builder/angle/buildtools/linux64/gn gen /b/s/w/ir/cache/builder/angle/out/Release --check
  -> returned 1
ERROR at //third_party/vulkan-validation-layers/src/BUILD.gn:23:19: Assignment had no effect.
vulkan_data_dir = "$root_out_dir/$vulkan_data_subdir"
                  ^----------------------------------
You set the variable "vulkan_data_dir" here and it was unused before it went
out of scope.
```
