### ISSUE TITLE
Incorrect validation errors for transform feedback queries

### ISSUE THREAD

**Issue by jozefkucia** [KhronosGroup/Vulkan-ValidationLayers#824]
Validation layers produce incorrect validation errors when transform feedback queries are used:

`UNASSIGNED-CoreValidation-DrawState-InvalidQuery(ERROR / SPEC): msgNum: 0 - Requesting a copy from query to buffer with invalid query: queryPool 0xd, index 1`

It appears that validation layers do not track `vkCmdBeginQueryIndexedEXT()` correctly.

**Comment by jzulauf-lunarg** [comment]
@jozefkucia  -- Added tracking in PR cited above. Does this resolve the issue?

**Comment by jozefkucia** [comment]
Yes, this PR resolves the issue. Thanks.
