### ISSUE TITLE
Buffer descriptor write update not all descriptors are marked as updated

### ISSUE THREAD

**Issue by Arzana** [KhronosGroup/Vulkan-ValidationLayers#825]
I'm updating a descriptor set with 3 descriptors in it, two 4x4 matrices and an combined image sampler (in that order). I'm currently updating this set using two vkUpdateDescriptorSets calls. One for the two uniforms (they are in the same block) and one for the combined image sampler.
The two uniforms are in the same buffer so I pass one buffer info object with the buffer handle an offset of 0 and a range of 128 (for both matrices). 
Here the validation layer concludes that I've only updated the first descriptor in my descriptor set and raises an error telling me that the descriptor at global index 1 hasn't been updated but is being using the a render command. 
The error is being raised by the cvdescriptorset::DescriptorSet::ValidateDrawState function when it checks if the underlying descriptors of the set have been updated. Here I find that "updated" has been set for my first matrix and the combined image sampler. 
The cvdescriptorset::BufferDescriptor::WriteUpdate function sets this to true only for the first descriptor. When the cvdescriptorset::DescriptorSet::PerformWriteUpdate is being called only the descriptor count, which I set to 1 as otherwise I get the error that my offsets are not aligned. 

The code I've written doesn't seem fully correct to me as I'm trying to update 2 descriptors in the set but I'm having to pass 1 as the descriptor count because they're in the same buffer. The render pass itself works perfectly fine, the matrix that isn't updated is a view matrix and I can see the changes when I update it in the way. 

Am I doing something wrong (as I expect) or should that validation layer check for this behavior as it does seem to work?

**Comment by tobine** [comment]
Hi @Arzana, my guess based on what you've said is that you're doing something wrong. It sounds like that your two uniforms are in a single descriptor **set**, but that they are two separate **descriptors** within that set linked to those uniform buffers. If this is the case, then you need to perform a vkUpdateDescriptorSets() call with VkWriteDescriptorSet struct that has a descriptorCount of "2". If they're using the same buffer, then you replicate that handle in the "buffer" field of the second VkDescriptorBufferInfo and you set the "offset" field of that second descriptor to account for the offset size of the first uniform.

Make sense?

I don't believe there's a validation bug here so I'm closing the bug. If you have further questions feel free to respond.

**Comment by Arzana** [comment]
I'm confused about why it's rendering correctly in the first place. If I use two VkDescriptorBufferInfo structures and set the offsets correctly I get the following validation error:

vkUpdateDescriptorSets(): pDescriptorWrites[0].pBufferInfo[1].offset (0x40) must be a multiple of device limit minUniformBufferOffsetAlignment 0x100. The Vulkan spec states: If descriptorType is VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER or VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC, the offset member of each element of pBufferInfo must be a multiple of VkPhysicalDeviceLimits::minUniformBufferOffsetAlignment (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkWriteDescriptorSet-descriptorType-00327)

The error states that my offsets need to be aligned to the minUniformBufferOffsetAlignment of my GPU. So if I update it using my previous method I get no device lost but, when I use the method with multiple offsets I do get a device lost. In both scenarios I get correct results but the official way results in more memory being used.
