### ISSUE TITLE
Duplicated debug utils messenger in layers

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-ValidationLayers#827]
This seems to be a recent change since 1.1.101 as far as I can tell.

Debug messengers get added twice: once from chassis.cpp in `CreateDebugUtilsMessengerEXT` -> `layer_create_messenger_callback` and then again in `CreateDebugUtilsMessengerEXT` -> `CoreChecks::PostCallRecordCreateDebugUtilsMessengerEXT` -> `layer_create_messenger_callback`.

**Comment by mark-lunarg** [comment]
I believe this issue was fixed by commit 358462ef.  Please reopen if evidence dictates otherwise -- thanks!
