### ISSUE TITLE
Add validation for VK_EXT_pipeline_creation_feedback

### ISSUE THREAD

**Issue by Tobski** [KhronosGroup/Vulkan-ValidationLayers#830]
There's no coverage for the new VUs in VK_EXT_pipeline_creation_feedback - only implicit VUs are supported. Adding support for the handful of explicit VUs should be fairly straightforward, but it would be good to get coverage.

CC @jfroy as the spec author in case this is something that he's able to help with (or find someone who can!)

**Comment by jfroy** [comment]
We're happy to help with this.

**Comment by jzulauf-lunarg** [comment]
@jfroy  -- do you have plans for submitting changes to implement any of these VU's?  Is there any way we can help enable you to do so?

**Comment by jfroy** [comment]
@jzulauf-lunarg We have a Stadia engineer working on them, and we'll send a MR soon.

**Comment by jzulauf-lunarg** [comment]
@jfroy -- excellent. thanks.  just wanted to make sure there was no duplication of effort.  Have your engineer review CONTRIBUTING to ensure the smoothest/best review/merge process.
