### ISSUE TITLE
TLAS vkCmdBuildAccelerationStructuresKHR with zero instance

### ISSUE THREAD

**Issue by Onhi** [KhronosGroup/Vulkan-ValidationLayers#8306]
**Environment:**
 - OS: Windows 11 23H2
 - GPU and driver version: nVidia RTX 4090, driver : 560.70
 - SDK or header version if building from repo: SDK 1.3.283.0
 - Options enabled (synchronization, best practices, etc.): Standard Validation

**Describe the Issue**

Creating a TLAS with no instances triggers a validation error during the build step.
The validator complains that `geometry.instances.data.deviceAddress` is not a valid device address (its null) even if `VkAccelerationStructureBuildRangeInfoKHR::primitiveCount` is zero.

**Expected behavior**

The validator should allow to build TLAS with no instance.

**Valid Usage ID**

```
VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03813(ERROR / SPEC): msgNum: -306746069 - Validation Error: [ VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03813 ] Object 0: handle = 0x318ab8da600, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xedb76d2b | vkCmdBuildAccelerationStructuresKHR(): pInfos[0].pGeometries[0].geometry.instances.data.deviceAddress (0) is not an address belonging to an existing buffer. The Vulkan spec states: For any element of pInfos[i].pGeometries or pInfos[i].ppGeometries with a geometryType of VK_GEOMETRY_TYPE_INSTANCES_KHR, geometry.instances.data.deviceAddress must be a valid device address obtained from vkGetBufferDeviceAddress (https://vulkan.lunarg.com/doc/view/1.3.283.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03813)
    Objects: 1
       [0]  0x318ab8da600, type: 6, name: NULL
```

**Comment by arno-lunarg** [comment]
Thank you for the report, indeed the driver will not access the device address in this case and there is no need to report an error
