### ISSUE TITLE
Avoid repeated output of the same message

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [KhronosGroup/Vulkan-ValidationLayers#831]
As a result of Ecosystem survey done by LunarG, a request was made for the following. Logging here so it isn't lost.

> It would be sweet to have an option where if the same message has been output more than a specific number of times, it can be omitted automatically by the validation layer to prevent a spew of messaged being sent to the callback.

**Comment by krOoze** [comment]
That is already perfectly possible to do in the application's callback.
Does this mean the `vk_layer_config.txt`?

**Comment by mark-lunarg** [comment]
Since this is at error-time, performance is not so much of a concern.  But it's not as simple as hashing the error message and eating the output -- it would probably have to be done per-VUID, having a count for each.
