### ISSUE TITLE
VUID-vkCmdDraw-dynamicPrimitiveTopologyUnrestricted-07500

### ISSUE THREAD

**Issue by RikiLee** [KhronosGroup/Vulkan-ValidationLayers#8319]
**Environment:**
 - OS: Windows 11
 - GPU and driver version: NVIDIA RTX4090
 - SDK or header version if building from the repo: 1.3.290.0
 - Options enabled (synchronization, best practices, etc.):

**Describe the Issue**

Unexcepted error message when I use a pipeline without the dynamic state VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY, I only enable the VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY for another pipeline.

**Expected behavior**

No VUID-vkCmdDraw-dynamicPrimitiveTopologyUnrestricted-07500 errors.

**Valid Usage ID**
VUID-vkCmdDraw-dynamicPrimitiveTopologyUnrestricted-07500

**Comment by spencer-lunarg** [comment]
@RikiLee can you please provide the error message that was given

**Comment by spencer-lunarg** [comment]
an [API Dump](https://vulkan.lunarg.com/doc/view/latest/windows/api_dump_layer.html) or GFXReconstruct capture would also help... we have tests for this VU and I see the ` if (pipeline.IsDynamic(CB_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY)` around it, so not sure how you go in this VU reported by accident

**Comment by RikiLee** [comment]
> @RikiLee can you please provide the error message that was given

debug: validation layer: Validation Error: [ VUID-vkCmdDraw-dynamicPrimitiveTopologyUnrestricted-07500 ] Object 0: handle = 0x1f543614d10, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0x301e6c0000000022, type = VK_OBJECT_TYPE_PIPELINE; | MessageID = 0xca492c88 | vkCmdDraw():  the last primitive topology VK_PRIMITIVE_TOPOLOGY_LINE_STRIP state set by vkCmdSetPrimitiveTopology is not compatible with the pipeline topology VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP. The Vulkan spec states: If the bound graphics pipeline state was created with the VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY dynamic state enabled and the dynamicPrimitiveTopologyUnrestricted is VK_FALSE, then the primitiveTopology parameter of vkCmdSetPrimitiveTopology must be of the same topology class as the pipeline VkPipelineInputAssemblyStateCreateInfo::topology state (https://vulkan.lunarg.com/doc/view/1.3.290.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdDraw-dynamicPrimitiveTopologyUnrestricted-07500)

**Comment by spencer-lunarg** [comment]
ugh... geometry shaders and topology have some very subtle spec wording... I need to re-re-re-read it :laughing: 

This is either going to be a "Yes, this is a bug in VVL" or it will be a "VVL is right, this is invalid, but the error message is awful in letting you know"

both are VVL bugs, so will take a look into this, but might be a while as busy fixing other things

**Comment by danginsburg** [comment]
I am running into this bug as well after updating to Vulkan SDK v1.3.290 with a pipeline that has a geometry shader.

> VK ERROR : VALIDATION - Message Id Number: -901174136 | Message Id Name: VUID-vkCmdDraw-dynamicPrimitiveTopologyUnrestricted-07500
> Validation Error: [ VUID-vkCmdDraw-dynamicPrimitiveTopologyUnrestricted-07500 ] Object 0: handle = 0x1c7c0a2b0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0x61e6d50000003d56, name = tools_sprite.vfx, type = VK_OBJECT_TYPE_PIPELINE; | MessageID = 0xca492c88 | vkCmdDraw(): the last primitive topology VK_PRIMITIVE_TOPOLOGY_POINT_LIST state set by vkCmdSetPrimitiveTopology is not compatible with the pipeline topology VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP. The Vulkan spec states: If the bound graphics pipeline state was created with the VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY dynamic state enabled and the dynamicPrimitiveTopologyUnrestricted is VK_FALSE, then the primitiveTopology parameter of vkCmdSetPrimitiveTopology must be of the same topology class as the pipeline VkPipelineInputAssemblyStateCreateInfo::topology state (https://vulkan.lunarg.com/doc/view/1.3.290.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdDraw-dynamicPrimitiveTopologyUnrestricted-07500)

The PSO and dynamic state are both VK_PRIMITIVE_TOPOLOGY_POINT_LIST.  The GS has input primitive of points and output primitive of triangle_strip.
