### ISSUE TITLE
Add Sparse VU 09491 09492

### ISSUE THREAD

**Issue by arno-lunarg** [KhronosGroup/Vulkan-ValidationLayers#8328]
`VUID-VkSparseMemoryBind-resourceOffset-09491`
If the resource being bound is a VkBuffer, resourceOffset, memoryOffset and size must be an integer multiple of the alignment of the [VkMemoryRequirements](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkMemoryRequirements.html) structure returned from a call to [vkGetBufferMemoryRequirements](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetBufferMemoryRequirements.html) with the buffer resource

`VUID-VkSparseMemoryBind-resourceOffset-09492`
If the resource being bound is a VkImage, resourceOffset and memoryOffset must be an integer multiple of the alignment of the [VkMemoryRequirements](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkMemoryRequirements.html) structure returned from a call to [vkGetImageMemoryRequirements](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetImageMemoryRequirements.html) with the image resource

**Comment by spencer-lunarg** [comment]
note this was added in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6323 and touched up a bit in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6555

These are the same idea as VUs such as `VUID-vkBindBufferMemory-memoryOffset-01036`

**Comment by arno-lunarg** [comment]
you should have the title of "VUID archeologist"
