### ISSUE TITLE
Layout transition validation broken if same image changes layout twice in same vkCmdPipelineBarrier

### ISSUE THREAD

**Issue by egdaniel** [KhronosGroup/Vulkan-ValidationLayers#836]
In ValidateBarriersToImage in buffer_validation.cpp, we first loop through all imageMemoryBarriers to make sure if we do multiple layout transitions to the same image that it all is done correctly. This part seems fine.

However, at then end of the function it loops over each layer and call ValidateImageAspectLayout. In this call it looks up the image to find what its current layout is and make sure this matches the oldLayout on the barrier. The problem is layout transitions for previous barriers in the same vkCmdPipelineBarrier have not been recorded on the image yet. Thus we are always comparing the layout before the vkCmdPipelineBarrier and not the layout that some previous imageMemoryBarrier may have set.

**Comment by jzulauf-lunarg** [comment]
It's not clear this is valid usage, as the spec doesn't specify order within the entries of the barriers.  There is an open issue in the working group to clarify the language w.r.t. barriers.
