### ISSUE TITLE
Timeline signaling validation breaks after win32 handle export.

### ISSUE THREAD

**Issue by rygo6** [KhronosGroup/Vulkan-ValidationLayers#8375]
**Environment:**
 - OS: Win11
 - GPU and driver version: 4090
 - SDK or header version if building from repo: 1.3.290.0
 - Options enabled (synchronization, best practices, etc.): Fine Grained Locking. Core.

**Describe the Issue**

Signaling a semaphore with:
```
  const VkSemaphoreSignalInfo semaphoreSignalInfo = {
      .sType = VK_STRUCTURE_TYPE_SEMAPHORE_SIGNAL_INFO,
      .semaphore = timeline,
      .value = signalValue,
  };
  MIDVK_REQUIRE(vkSignalSemaphore(device, &semaphoreSignalInfo));
```
Gives the following error:
```
MemorVUID-VkSemaphoreSignalInfo-value-03259(ERROR / SPEC): msgNum: 1227785937 - Validation Error: [ VUID-VkSemaphore
SignalInfo-value-03259 ] Object 0: handle = 0x28ff7d9a370, name = CompTimelineSemaphore, type = VK_OBJECT_TYPE_SEMAPHORE
; | MessageID = 0x492e86d1 | vkSignalSemaphore(): pSignalInfo->value (1) must be less than value of any pending signal o
peration (0) for semaphore VkSemaphore 0x28ff7d9a370[CompTimelineSemaphore]. The Vulkan spec states: value must be less
than the value of any pending semaphore signal operations (https://vulkan.lunarg.com/doc/view/1.3.290.0/windows/1.3-exte
nsions/vkspec.html#VUID-VkSemaphoreSignalInfo-value-03259)
    Objects: 1
        [0] 0x28ff7d9a370, type: 5, name: CompTimelineSemaphore
```
However, it ONLY has this issue if I create the semaphore as an exported win32 handle and then actually `Get` the handle via:
```
      const VkSemaphoreGetWin32HandleInfoKHR getWin32HandleInfo = {
          .sType = VK_STRUCTURE_TYPE_SEMAPHORE_GET_WIN32_HANDLE_INFO_KHR,
          .semaphore = *pSemaphore,
          .handleType = MIDVK_EXTERNAL_SEMAPHORE_HANDLE_TYPE,
      };
      MIDVK_INSTANCE_FUNC(GetSemaphoreWin32HandleKHR);
      MIDVK_REQUIRE(GetSemaphoreWin32HandleKHR(context.device, &getWin32HandleInfo, pExternalHandle));
```
It works just fine if I don't `Get` the handle. 

This is the exact code creating the timeline semaphore:
https://github.com/rygo6/moxaic/blob/79527edd33e0e5ce4cc793d568b8e6900fe56884/src/mid_vulkan.c#L1257

I think I remember some kind of issue like this existing around signaling from command buffer submission like a year ago. Which this is similiar to, except it's cause by trying to signal with vkSignalSemaphore.

**Expected behavior**
This shouldn't be a validation error. Seems like a bug.

**Valid Usage ID**
1227785937

**Comment by rygo6** [comment]
I believe this is related to #8212

I was just looking at the semaphore_state myself to see if I could fix but realized, can exported semaphores even be validated since another process could be changing their state?

Or would you internally to the validation dll have to start calling vkGetSemaphoreCounterValue to ensure timeline operations are correct?

**Comment by artem-lunarg** [comment]
> I was just looking at the semaphore_state myself to see if I could fix but realized, can exported semaphores even be validated since another process could be changing their state?

That's correct observation. The validation of external objects are limited, but the validation layer should not report errors when it does not have enough information.

> I believe this is related to https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8212

Yes, it should be the same issue.

**Comment by rygo6** [comment]
@artem-lunarg If you have any idea of the issue and how to solve it, could you please give a quick description? I spent some time looking through the semaphore validation code and have a vague sense of what needs to happen, once the semaphore gets exported it needs to start omitting other checks, but any other context you can provide might save me some time.

**Comment by artem-lunarg** [comment]
@rygo6 Sorry, I did not look at this issue yet. I’ll try to fix it tomorrow, if this can be done in one day.

**Comment by artem-lunarg** [comment]
@rygo6 the potential fix is merged

**Comment by artem-lunarg** [comment]
No difference in repro case with https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8212, I'm pretty sure it's the same issue. @rygo6 free to re-open if this does not help.
