### ISSUE TITLE
VkSwapchainPresentFenceInfoEXT does not allow null fences

### ISSUE THREAD

**Issue by artem-lunarg** [KhronosGroup/Vulkan-ValidationLayers#8399]
Specification about VkSwapchainPresentFenceInfoEXT:
> pFences is a list of fences with swapchainCount entries. Each entry must be [VK_NULL_HANDLE](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VK_NULL_HANDLE) or the handle of a fence to signal when the relevant operations on the associated swapchain have completed.

I get validation error for VK_NULL_HANDLE fence:
> Validation Error: [ UNASSIGNED-GeneralParameterError-RequiredHandleArray ] | MessageID = 0x3955e8fe | vkQueuePresentKHR(): pPresentInfo->pNext<VkSwapchainPresentFenceInfoEXT>.pFences[1] is VK_NULL_HANDLE.

`PositiveWsi.QueueWaitsForPresentFence2` can be used for testing, replace one of the fences in `present_fences` with VK_NULL_HANDLE.

**Comment by ziga-lunarg** [comment]
This has been fixed in the spec: https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6985
