### ISSUE TITLE
GPU-assisted validation fails due to "uniformAndStorageBuffer8BitAccess" feature

### ISSUE THREAD

**Issue by kvark** [KhronosGroup/Vulkan-ValidationLayers#8414]
**Environment:**
 - OS: NixOS (Linux 6.6.45)
 - GPU and driver version: AMD RADV 24.1.5
 - SDK or header version if building from repo:
 - Options enabled (synchronization, best practices, etc.): 1.3.283.0

**Describe the Issue**

When enabling GPU-assisted validation, it fails to activate:
> WARNING-GPU-Assisted-Validation(WARN / SPEC): msgNum: 615892639 - Validation Warning: [ WARNING-GPU-Assisted-Validation ] | MessageID = 0x24b5c69f | vkCreateDevice():  gpuav_validate_copies option was enabled, but uniformAndStorageBuffer8BitAccess feature is not available. Disabling option.

**Expected behavior**

The feature is supported on this platform. If VVL needs it, I'd expect it to silently enable/request it when I'm creating `VkDevice` instead of expecting me to request some features.

**Comment by spencer-lunarg** [comment]
We currently do this for some features, but thanks for pointing this out,  I realize some of the newer options (ex `gpuav_validate_copies`) didn't attempt to just enable it for you
