### ISSUE TITLE
VUID-VkGraphicsPipelineCreateInfo-renderPass-06038 message improvement

### ISSUE THREAD

**Issue by ziga-lunarg** [KhronosGroup/Vulkan-ValidationLayers#8419]
The VUID message is:
`SPIR-V consumes input attachment index 4 but that is greater than the pSubpasses[0].inputAttachmentCount (4).`

I think `greater` should be replaced with `not less than`

**Comment by spencer-lunarg** [comment]
... this is a common issue where we have something like

```
uint32_t something[4];

// accessing
something[4] = 0;
```

where it reads strange because the "index" was `4` and the size is `4`

but I think going `not less than` is a smart way to word it
