### ISSUE TITLE
Misc error message improvements

### ISSUE THREAD

**Issue by artem-lunarg** [KhronosGroup/Vulkan-ValidationLayers#8420]
1. Aspect mask is printed as a number instead of readable flag names. Search this pattern for places to fix: `aspectMask 0x%x`

2.  When I run validation through vkconfig in the end of the message I get the list of objects.  The suggestion is to replace type number with a readable name, assuming that it is VVL responsible for this part.
```
   Objects: 2
        [0] 0x242784aee70, type: 6, name: NULL
        [1] 0xf443490000000006, type: 9, name: NULL
```

**Comment by ziga-lunarg** [comment]
`VUID-VkMemoryAllocateFlagsInfo-flags-parameter` for example is similar, the message only says:

> vkAllocateMemory(): pAllocateInfo->pNext<VkMemoryAllocateFlagsInfo>.flags (0x2) has VkMemoryAllocateFlagBits values that requires the extensions VK_KHR_buffer_device_address.
