### ISSUE TITLE
Odd message formatting for some dynamic state VUIDs

### ISSUE THREAD

**Issue by ziga-lunarg** [KhronosGroup/Vulkan-ValidationLayers#8422]
In `CoreChecks::ValidateDynamicStateIsSet()` dynamic states are validated and part of the log message comes from `DescribeDynamicStateDependency()`. But not all dynamic states return something from this function, resulting in this being an empty string and the log message looking odd.

You can reproduce this by for example running `--gtest_filter=NegativeDynamicState.ExtendedDynamicState2InvalidateStaticPipeline --print-vu`

**Comment by spencer-lunarg** [comment]
I get

> vkCmdDraw():  VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE state is dynamic, but the command buffer never called vkCmdSetPrimitiveRestartEnable.

the `DescribeDynamicStateDependency` is there to list when there are extensions that do depend on things like `rasterizerDiscardEnable`

I guess is the issue that the null string at the end looks weird because it is after a newline with a period inbetween?

**Comment by ziga-lunarg** [comment]
That part is fine, the problem is between the vvl message and `The vulkan spec states`.

> Validation Error: [ VUID-vkCmdDraw-None-04879 ] Object 0: handle = 0x21fbba2d920, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0x980f360000000011, type = VK_OBJECT_TYPE_PIPELINE; | MessageID = 0x73760394 | vkCmdDraw():  VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE state is dynamic, but the command buffer never called vkCmdSetPrimitiveRestartEnable.
> . The Vulkan spec states: If there is a shader object bound to the VK_SHADER_STAGE_VERTEX_BIT stage or the bound graphics pipeline state was created with the VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE dynamic state enabled then vkCmdSetPrimitiveRestartEnable must have been called and not subsequently invalidated in the current command buffer prior to this drawing command (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdDraw-None-04879)
