### ISSUE TITLE
Error message formatting

### ISSUE THREAD

**Issue by ziga-lunarg** [KhronosGroup/Vulkan-ValidationLayers#8429]
I think somewhere in the `LogError` function there is a check if the messaged ends with a dot. And if it does not, it is added. But it seems that this is missing a check for new lines, because some of the messages have odd formatting on line breaks, where the line starts with a dot, like this:

```
Unable to find SPIR-V OpLine for source information.  Build shader with debug info to get source information.
. The Vulkan spec states: If any stage of the VkPipeline object bound to the pipeline bind point used
```

**Comment by spencer-lunarg** [comment]
checked and this is now fixed in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8520

PLEASE raise issue with example if you find anymore that are formatted strangly!
