### ISSUE TITLE
On android some messages are cut off as they are too long

### ISSUE THREAD

**Issue by ziga-lunarg** [KhronosGroup/Vulkan-ValidationLayers#8430]
One example is:

> 08-21 21:28:00.594 14727 14803 I VALIDATION: VUID-vkCmdDraw-None-06479(ERROR / SPEC): msgNum: 1268585879 - Validation Error: [ VUID-vkCmdDraw-None-06479 ] Object 0: handle = 0xba36e6000000079e, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; Object 1: handle = 0x7ddd740000000051, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x4b9d1597 | vkCmdDraw():  the descriptor VkDescriptorSet 0xba36e6000000079e[] [Set 0, Binding 9, Index 0] has VkImageView 0x7ddd740000000051[] with format of VK_FORMAT_R8G8B8A8_UNORM which doesn't support VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_DEPTH_COMPARISON_BIT.
> 08-21 21:28:00.594 14727 14803 I VALIDATION: (supported features: VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_BIT|VK_FORMAT_FEATURE_2_STORAGE_IMAGE_BIT|VK_FORMAT_FEATURE_2_COLOR_ATTACHMENT_BIT|VK_FORMAT_FEATURE_2_COLOR_ATTACHMENT_BLEND_BIT|VK_FORMAT_FEATURE_2_BLIT_SRC_BIT|VK_FORMAT_FEATURE_2_BLIT_DST_BIT|VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_FILTER_LINEAR_BIT|VK_FORMAT_FEATURE_2_TRANSFER_SRC_BIT|VK_FORMAT_FEATURE_2_TRANSFER_DST_BIT|VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_FILTER_MINMAX_BIT|VK_FORMAT_FEATURE_2_MIDPOINT_CHROMA_SAMPLES_BIT|VK_FOR

**Comment by spencer-lunarg** [comment]
One can change the size of logcat on Android (https://stackoverflow.com/questions/12397780/how-to-change-size-of-logcat-buffer-in-android)

but VVL could easily just detect the default length and in `MessengerLogCallback` breakup the `__android_log_print` such that is prints the whole message over a few lines
