### ISSUE TITLE
vkCmdSetVertexInputEXT is not validated correctly

### ISSUE THREAD

**Issue by ziga-lunarg** [KhronosGroup/Vulkan-ValidationLayers#8458]
There are many CTS tests hitting `VUID-vkCmdDraw-Input-07939` when I don't think they should, one example is `dEQP-VK.draw.renderpass.instanced.dynamic_state_draw_vk_primitive_topology_point_list`.

Here is a test to reproduce:

```
TEST_F(PositiveDynamicState, VertexInputMultiple) {
    TEST_DESCRIPTION("Test CmdSetVertexInputEXT with multiple bindings");
    SetTargetApiVersion(VK_API_VERSION_1_1);

    AddRequiredExtensions(VK_EXT_VERTEX_INPUT_DYNAMIC_STATE_EXTENSION_NAME);
    AddRequiredFeature(vkt::Feature::vertexInputDynamicState);
    RETURN_IF_SKIP(Init());
    InitRenderTarget();

    struct PerVertex {
        int a;
        float b;
    };

    struct PerInstance {
        uint32_t c;
        float d;
    };

    VkVertexInputBindingDescription2EXT bindings[2];
    bindings[0] = vku::InitStructHelper();
    bindings[0].binding = 0u;
    bindings[0].stride = sizeof(PerVertex);
    bindings[0].inputRate = VK_VERTEX_INPUT_RATE_VERTEX;
    bindings[0].divisor = 1u;
    bindings[1] = vku::InitStructHelper();
    bindings[1].binding = 1u;
    bindings[1].stride = 0u;
    bindings[1].inputRate = VK_VERTEX_INPUT_RATE_INSTANCE;
    bindings[1].divisor = 1u;

    VkVertexInputAttributeDescription2EXT attributes[4];
    attributes[0] = vku::InitStructHelper();
    attributes[0].location = 0u;
    attributes[0].binding = 0u;
    attributes[0].format = VK_FORMAT_R8_SINT;
    attributes[0].offset = offsetof(PerVertex, a);

    attributes[1] = vku::InitStructHelper();
    attributes[1].location = 1u;
    attributes[1].binding = 0u;
    attributes[1].format = VK_FORMAT_R32_SFLOAT;
    attributes[1].offset = offsetof(PerVertex, b);

    attributes[2] = vku::InitStructHelper();
    attributes[2].location = 2u;
    attributes[2].binding = 1u;
    attributes[2].format = VK_FORMAT_R8_UINT;
    attributes[2].offset = offsetof(PerInstance, c);

    attributes[3] = vku::InitStructHelper();
    attributes[3].location = 3u;
    attributes[3].binding = 1u;
    attributes[3].format = VK_FORMAT_R32_SFLOAT;
    attributes[3].offset = offsetof(PerInstance, d);

    char const *vsSource = R"glsl(
        #version 450
        layout(location = 0) in int a;
        layout(location = 1) in float b;
        layout(location = 2) in uint c;
        layout(location = 3) in float d;

        void main(){
            gl_Position = vec4(float(a), b, float(c), d);
        }
    )glsl";
    VkShaderObj vs(this, vsSource, VK_SHADER_STAGE_VERTEX_BIT);

    CreatePipelineHelper pipe(*this);
    pipe.AddDynamicState(VK_DYNAMIC_STATE_VERTEX_INPUT_EXT);
    pipe.shader_stages_ = {vs.GetStageCreateInfo() , pipe.fs_->GetStageCreateInfo()};
    pipe.CreateGraphicsPipeline();

    vkt::Buffer vertex_buffer(*m_device, 1024, VK_BUFFER_USAGE_VERTEX_BUFFER_BIT);
    vkt::Buffer instance_buffer(*m_device, 1024, VK_BUFFER_USAGE_VERTEX_BUFFER_BIT);

    VkBuffer buffers[2] = {vertex_buffer.handle(), instance_buffer.handle()};
    VkDeviceSize offsets[2] = {0u, 0u};

    m_commandBuffer->begin();
    m_commandBuffer->BeginRenderPass(m_renderPassBeginInfo);
    vk::CmdBindPipeline(m_commandBuffer->handle(), VK_PIPELINE_BIND_POINT_GRAPHICS, pipe.Handle());
    vk::CmdBindVertexBuffers(m_commandBuffer->handle(), 0, 2, buffers, offsets);
    vk::CmdSetVertexInputEXT(m_commandBuffer->handle(), 2, bindings, 4, attributes);
    vk::CmdDraw(m_commandBuffer->handle(), 3u, 3u, 0u, 0u);
    m_commandBuffer->EndRenderPass();
    m_commandBuffer->end();
}
```

**Comment by ShabbyX** [comment]
This was suppressed in ANGLE too, and I just came here to report it's a bug. The failure was bisected to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8391/commits/205fed036669844bcc3525b9d96da5bcc8577779

For example, the `SimpleStateChangeTestES31.MultipleVertexArrayObjectRendering/ES3_1_Vulkan` end2end test can reproduce it. What ANGLE does is create two bindings (0 and 1), one mapped to each location (0 and 1 respectively). Then it issues `vkCmdBindVertexBuffers` with 2 bindings starting at binding 0. That correctly covers both locations 0 and 1, but VVL complains with `VUID-vkCmdDraw-Input-07939`

**Comment by ShabbyX** [comment]
There seems to be another bug here too. We are hitting `VUID-vkCmdDraw-None-02721` in the `SimpleStateChangeTestES31.MultipleVertexArrayObjectRendering/ES3_1_Vulkan` end2end test. The test does this:

- `vkCmdSetVertexInputEXT` with two buffers that are R32G32B32_SSCALED and R32G32B32A32_SSCALED with strides 12 and 16 respectively. Then draw.
- `vkCmdSetVertexInputEXT` with two buffers that are R8G8B_SSCALED and R8G8B8A8_SSCALED with strides 3 and 4 respectively. Then draw.

The VVL error says:

> Format VK_FORMAT_R32G32B32_SFLOAT has an alignment of 4 but the alignment of attribAddress (515) is not aligned in pVertexAttributeDescriptions[0] (binding=0 location=0) where attribAddress = vertex buffer offset (512) + binding stride (3) + attribute offset (0)

which looks like a tracking bug, we didn't combine R32G32B32 with stride 3.

**Comment by spencer-lunarg** [comment]
> If I check out the parent of https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/205fed036669844bcc3525b9d96da5bcc8577779, the VVL error goes away.

awesome, I get to re-hack at the vertex input attribute code... well thanks for listing this, will make sure ANGLE is fixed when making the change

**Comment by spencer-lunarg** [comment]
@ShabbyX this should be fixed now
