### ISSUE TITLE
Bugs with CTS synchronization tests

### ISSUE THREAD

**Issue by ziga-lunarg** [KhronosGroup/Vulkan-ValidationLayers#8461]
Running timeline semaphore tests in CTS reports `UNASSIGNED-VkSemaphore-state-timeout` and the message says `This is most likely a validation bug`.

One such test for example is `dEQP-VK.synchronization.timeline_semaphore.device_host.write_copy_buffer_read_copy_buffer.buffer_16384`

And the full message is:

> UNASSIGNED-VkSemaphore-state-timeout(ERROR / SPEC): msgNum: 1474714163 - Validation Error: [ UNASSIGNED-VkSemaphore-state-timeout ] Object 0: handle = 0x40b43c0000000049, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x57e65a33 | vkWaitSemaphores(): pWaitInfo->pValues[0] Timeout waiting for timeline semaphore state to update. This is most likely a validation bug. completed_.payload=0 wait_payload=141
>     Objects: 1
>         [0] 0x40b43c0000000049, type: 5, name: NULL

There are other VUIDs that follow, but I assume they are caused by this first one.

**Comment by jeremyg-lunarg** [comment]
I think this might be a tests where many many semaphores a created and then it takes a very long time for them to be signaled.  Possibly the timer for this error needs to be made longer.

**Comment by artem-lunarg** [comment]
It's a regression after 882f09f1e8751a8738ae1c3dd6bf0e8ceb5898bc
