### ISSUE TITLE
VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT regression

### ISSUE THREAD

**Issue by Goshido** [KhronosGroup/Vulkan-ValidationLayers#8467]
**Environment:**
 - OS: _Android 11_
 - GPU and driver version: _GPU_: _Mali G76_, driver: _26.0.0_
 - SDK or header version if building from repo: _1.3.294_, _SHA-1_ `9c149610e4f776392993201be4ff820286215fd0`
 - Options enabled (synchronization, best practices, etc.): `VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT` and `VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT`

**Describe the Issue**

I've just detected **HUGE** regression in sync validation of _VVL_. Basically I tested scenario:

1. I took correct RenderPass and made intentional mistake by deleting huge subpass dependency to trigger some sync validation error:

```cpp
...

            AV_VK_FLAG ( VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT ) |
            AV_VK_FLAG ( VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT ) |
            AV_VK_FLAG ( VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT ),

        .dependencyFlags = VK_DEPENDENCY_BY_REGION_BIT
    }/*, <-----------------------
    {
        .srcSubpass = 1U,
        .dstSubpass = VK_SUBPASS_EXTERNAL,

        .srcStageMask = AV_VK_FLAG ( VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT ) |
            AV_VK_FLAG ( VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT ) |
            AV_VK_FLAG ( VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT ),

        .dstStageMask = AV_VK_FLAG ( VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT ) |
            AV_VK_FLAG ( VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT ) |
            AV_VK_FLAG ( VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT ) |
            AV_VK_FLAG ( VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT ),

        .srcAccessMask = AV_VK_FLAG ( VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT ) |
            AV_VK_FLAG ( VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT ),

        .dstAccessMask = AV_VK_FLAG ( VK_ACCESS_SHADER_READ_BIT ) |
            AV_VK_FLAG ( VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT ) |
            AV_VK_FLAG ( VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT ) |
            AV_VK_FLAG ( VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT ),

        .dependencyFlags = VK_DEPENDENCY_BY_REGION_BIT
    }*/ <-----------------------
};

VkRenderPassCreateInfo const renderPassInfo

...
```
2. I compiled the latest _VVL_ v1.3.294 from commit `9c149610e4f776392993201be4ff820286215fd0`

**Problem**

I run application and got nothing from _VVL_.

**Expected behavior**

_VVL_ must detect and report obviously incorrect _Vulkan_ usage as before.

**Valid Usage ID**

_N/A_

**Further investigation**

I decided to find first commit where _VVL_ started to fail because I knew last working commit:

Version | Commit | Status
--- | --- | ---
_1.3.294_ | `9c149610e4f776392993201be4ff820286215fd0` | ❌broken
_1.3.290_ | `58428b0c0e9cb818ee240857c5b4725df8c5183e` | ❌broken
_1.3.290_ | `569ead6ae5c87311a83aa54cef3b66c4ec68dbc7` | ❌broken
_1.3.290_ | `4966de11e0e1383bced099c3aa52153455beaacf` | ❌broken
_1.3.290_ | `97237f3f4226732c305284e3bf89bd2e66d623e8` | ❌broken
_1.3.290_ | `3ffe98fe2781166df58903c18a71af7b717365aa` | 👈👈👈 THIS GUY IS THE FIRST BROKEN COMMIT
_1.3.290_ | `b93cd0c87caa1d69346e9a1adb7b3e1c68b72423` | ✅fine, parent commit to first broken commit above
_1.3.289_ | `d03e2bca31b298fc911f7c89cfaf24d28904492d` | ✅fine
_1.3.288_ | `5295afa929b5517c1733f0e1c71efb48807f59a7` | ✅fine
_1.3.287_ | `15ba84ba94ff2ed473474deba2b4f2af4705b1fb` | ✅fine

Expected _VVL_ error is the following according to last working commit:

```txt
severity: Error
type: Validation
message ID name: SYNC-HAZARD-READ-AFTER-WRITE
message ID: 0xE4D96472
queues: N/A
command buffers: N/A
objects: HDR accumulator
message: Validation Error: [ SYNC-HAZARD-READ-AFTER-WRITE ] Object 0: handle = 0x46967500000016be,
    name = HDR accumulator, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0xe4d96472 | vkCmdDispatch():
    Hazard READ_AFTER_WRITE for VkImageView 0x46967500000016be[HDR accumulator],
    in VkCommandBuffer 0xb40000716ff7ec68[Frame in flight #0], and VkPipeline 0x12c6c0000002f48b[Exposure],
    VkDescriptorSet 0xee647e0000000009 [Exposure], type: VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE,
    imageLayout: VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, binding #0, index 0. Access
    info (usage: SYNC_COMPUTE_SHADER_SHADER_SAMPLED_READ, prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION,
    write_barriers: 0, command: vkCmdEndRenderPass, seq_no: 282, subcmd: 1,renderpass:
    VkRenderPass 0x41d49a00000016c1[Render session], reset_no: 2).
```

Would you kindly help?

**Comment by artem-lunarg** [comment]
Hi @Goshido ,

The commit you mentioned is: `3ffe98f - sync: Make shader_access_heuristic disabled by default`.

That's the expected behavior now. Shader accesses validation feature is not robust enough, it can produce correct results but also false positives. We decided to pursue a direction where default Synchronization Validation configuration does not produce false positives. Starting with SDK 1.3.290 the shader access validation feature is disabled by default, but it still exists (now under the umbrella of "heuristic") and can be enabled if it is helpful for specific use case.

In vkconfig:

![image](https://github.com/user-attachments/assets/15772bda-d893-4111-8f6d-fa39fa56aaf3)

or by setting environment variable: `VK_VALIDATION_SYNCVAL_SHADER_ACCESSES_HEURISTIC=1`

Please let me know if this solution works for you.

**Comment by Goshido** [comment]
HI @artem-lunarg. Is it possible to activate sync validation via pNext transport somehow? Environment variable sound like a HACK for me.

**Comment by artem-lunarg** [comment]
> Is it possible to activate sync validation via pNext transport somehow? 

Yes, by using `VK_EXT_layer_settings` extension.

An environment variable name is generated automatically based on corresponding validation layer setting: 
 `khronos_validation.syncval_shader_accesses_heuristic`, but you can set it programmatically. 

All settings and corresponding environment variables can be found here: 
https://vulkan.lunarg.com/doc/view/1.3.290.0/windows/layer_configuration.html#user-content-layer-details

The layer configuration documentation (provides example of programmable interface):
https://vulkan.lunarg.com/doc/view/1.3.290.0/windows/layer_configuration.html

The example of how we do this in VVL unit tests:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/13c0c4dc619d165b05061702a3c8eb604d21efa4/tests/unit/sync_val_positive.cpp#L51

**Comment by Goshido** [comment]
Damn. The problem is that extension is not supported by my shitty [Redmi Note 8 Pro](https://vulkan.gpuinfo.org/displayreport.php?id=12030#extensions). It's kinda disappointed. The only hacky environmental variable way exists (

**Comment by artem-lunarg** [comment]
@christophe-lunarg @spencer-lunarg do you know more details about `VK_EXT_layer_settings` support? That's an instance extension, which component do provides it, loader?

**Comment by spencer-lunarg** [comment]
`VK_EXT_layer_settings` is **not** implemented in driver, the various tools implement it (like validation layers) so you are still have to use it!

**Comment by Goshido** [comment]
@spencer-lunarg that's promising. I gonna try it.

**Comment by Goshido** [comment]
@artem-lunarg I've just tested `VK_EXT_layer_settings` and... It works like a charm on the most recent _VVL v1.3.294_ `c6dbf2c4d429151224dc6836db76c24309bc99a8`.

I got expected sync validation error at intentional mentioned mistake above.

Here is how my init code looks like:

```cpp
...

// [2024/08/28] Starting from VVL v1.3.290 3ffe98fe2781166df58903c18a71af7b717365aa
// it's needed to additionaly activate 'syncval_shader_accesses_heuristic' to use sync validation.
// See https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8467
constexpr static char const* const vvlLayerName = "VK_LAYER_KHRONOS_validation";
constexpr static VkBool32 activate = VK_TRUE;

constexpr static VkLayerSettingEXT vvlSync
{
    .pLayerName = vvlLayerName,
    .pSettingName = "syncval_shader_accesses_heuristic",
    .type = VK_LAYER_SETTING_TYPE_BOOL32_EXT,
    .valueCount = 1U,
    .pValues = &activate
};

constexpr static VkLayerSettingsCreateInfoEXT vvlSettings
{
    .sType = VK_STRUCTURE_TYPE_LAYER_SETTINGS_CREATE_INFO_EXT,
    .pNext = &g_debugUtilsMessengerCreateInfo,
    .settingCount = 1U,
    .pSettings = &vvlSync
};

// [2022/07/26] GPU assisted validation is impossible on MALI G76 (driver 26) due to lack of required
// feature - VkPhysicalDeviceFeatures::vertexPipelineStoresAndAtomics.
constexpr static VkValidationFeatureEnableEXT const validationFeatures[] =
{
    VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT,
    VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT
};

constexpr VkValidationFeaturesEXT validationInfo
{
    .sType = VK_STRUCTURE_TYPE_VALIDATION_FEATURES_EXT,
    .pNext = &vvlSettings,
    .enabledValidationFeatureCount = static_cast<uint32_t> ( std::size ( validationFeatures ) ),
    .pEnabledValidationFeatures = validationFeatures,
    .disabledValidationFeatureCount = 0U,
    .pDisabledValidationFeatures = nullptr
};

instanceCreateInfo.pNext = &validationInfo;
instanceCreateInfo.enabledLayerCount = 1U;
instanceCreateInfo.ppEnabledLayerNames = &vvlLayerName;

...
```

Thanks for the help! 👍
The issue could be closed.

**Comment by artem-lunarg** [comment]
@Goshido that's great! and the credits for all hard work to design `VK_EXT_layer_settings` API go to @christophe-lunarg 🎉
