### ISSUE TITLE
vkQueuePresentKHR crash on mac os without validation info

### ISSUE THREAD

**Issue by lsdh-fei** [KhronosGroup/Vulkan-ValidationLayers#8473]
- macos 14.6.1  macbook pro 16-inch, 2019
 - AMD Radeon Pro 5300M 4 GB
 - sdk version: 1.3.283.0
 - moltenvk version: 1.2.9
 - SDL2 version: 2.30.6
 - tool: vscode + clang

i wrote a demo, it runs well on m1 mac, and when i turned to intel x86,  it crashed when call vkQueuePresentKHR, there has no validation info when it crash, stack as below:

libsystem_platform.dylib!_platform_memmove$VARIANT$Haswell (未知源:0)
libVkLayer_khronos_validation.dylib!DispatchQueuePresentKHR(VkQueue_T*, VkPresentInfoKHR const*) (未知源:0)
libVkLayer_khronos_validation.dylib!vulkan_layer_chassis::QueuePresentKHR(VkQueue_T*, VkPresentInfoKHR const*) (未知源:0)

it should run well , the cube demo runs well on the x86 machine, i dont know if there is some error when i use the new sdl2 version, when i use the sdl2 in the sdk, it couldent compile. 

here is tasks.json:
{
	"label": "cppdebug compile",
	"type": "cppbuild",
	"command": "/usr/bin/clang++",
	"args": [
		"-Wno-nullability-completeness",
		"-std=c++17",
		"-stdlib=libc++",
		"-fcolor-diagnostics",
		"-fansi-escape-codes",
		"-I/usr/local/Cellar/sdl2/2.30.6/include",
		"-L/usr/local/Cellar/sdl2/2.30.6/lib",
		"-lSDL2",
		"-I${workspaceFolder}/include",
		"-I${VULKAN_SDK}/include",
		"-L${VULKAN_SDK}/lib",
		"-Wl,-rpath,${VULKAN_SDK}/lib",
		"-lvulkan.1",
		"-g",
		"${workspaceFolder}/*.cpp",
		"${workspaceFolder}/include/imgui/*.cpp",
		"${workspaceFolder}/source/*.cpp",
		"-o",
		"${workspaceFolder}/output/vulkan"
	],
	"options": {
		"cwd": "${workspaceFolder}"
	},
	"problemMatcher": [
		"$gcc"
	],
	"group": {
		"kind": "build",
		"isDefault": true
	},
	"detail": "vulkan with vscode c++ plugin"
}

**Comment by aitor-lunarg** [comment]
https://github.com/KhronosGroup/MoltenVK/issues/2295 could be related. It seems like the crash is when we do the driver call, so it may point to a MoltenVK crash. Did you test without validation? Does it also crash? Have you tested with latest MoltenVK?

As @spencer-lunarg mentioned having a repro case would help pin point the issue!

**Comment by lsdh-fei** [comment]
@aitor-lunarg after i remoded validation layer，It crashed in MoltenVK, stack as below:

libMoltenVK.dylib!MVKQueuePresentSurfaceSubmission::MVKQueuePresentSurfaceSubmission(MVKQueue*, VkPresentInfoKHR const*) (未知源:0)
libMoltenVK.dylib!MVKQueue::submit(VkPresentInfoKHR const*) (未知源:0)
libMoltenVK.dylib!vkQueuePresentKHR (未知源:0)

i will try the latest MoltenVK later

**Comment by lsdh-fei** [comment]
@spencer-lunarg the code works well with sdk 1.3.239.0 on m1 mac,but crashed with sdk 1.3.283.0 on intel cpu mac. the crash stack is shown in validation, so i post it here, but it seems a bug in MoltenVK.

**Comment by lsdh-fei** [comment]
@aitor-lunarg i tested with latest MoltenVK, it crashed with the same stack in MVKQueuePresentSurfaceSubmission.
latest MoltenVK log:

[mvk-info] GPU device:
	model: AMD Radeon Pro 5300M
	type: Discrete
	vendorID: 0x1002
	deviceID: 0x7340
	pipelineCacheUUID: 18F2B84E-0E06-0200-0000-000100000000
	GPU memory available: 4080 MB
	GPU memory used: 0 MB
	Metal Shading Language 3.1
	supports the following GPU Features:
		GPU Family Metal 3
		GPU Family Mac 2
		Read-Write Texture Tier 2
[mvk-info] GPU device:
	model: Intel(R) UHD Graphics 630
	type: Integrated
	vendorID: 0x8086
	deviceID: 0x3e9b
	pipelineCacheUUID: 18F2B84E-0E06-0200-0000-000100000000
	GPU memory available: 1536 MB
	GPU memory used: 8 MB
	Metal Shading Language 3.1
	supports the following GPU Features:
		GPU Family Metal 3
		GPU Family Mac 2
		Read-Write Texture Tier 1
[mvk-info] Created VkInstance for Vulkan version 1.2.290, as requested by app, with the following 3 Vulkan extensions enabled:
	VK_KHR_surface v25
	VK_EXT_debug_utils v2
	VK_EXT_metal_surface v1

[mvk-info] Vulkan semaphores using MTLEvent.
[mvk-info] Descriptor sets binding resources using Metal3 argument buffers.
[mvk-info] Created VkDevice to run on GPU AMD Radeon Pro 5300M with the following 2 Vulkan extensions enabled:
	VK_KHR_portability_subset v1
	VK_KHR_swapchain v70
[mvk-info] Created 3 swapchain images with size (1024, 768) and contents scale 1.0 in layer CAMetalLayer: SDL_cocoametalview (0x7fc500746810) on screen Built-in Retina Display.

**Comment by spencer-lunarg** [comment]
> the crash stack is shown in validation

@lsdh-fei all the stack traces you have show it is crashing after it leaves the validation layers

**Comment by aitor-lunarg** [comment]
I've created https://github.com/KhronosGroup/MoltenVK/issues/2321 with all relevant comments. We'll be closing this issue since this looks like a MoltenVK issue and not a validation issue. Main reason being that the crash is still present after removing the validation layers. Once MoltenVK no longer crashes, and enabling validation layers make it crash, feel free to reopen so we can take a look at it!
