### ISSUE TITLE
Setting report_flags through an env variable or VK_EXT_layer_settings doesn't work

### ISSUE THREAD

**Issue by kanashimia** [KhronosGroup/Vulkan-ValidationLayers#8477]
**Environment:**
 - OS: NixOS 24.11
 - SDK or header version: 1.3.283.0
 - Options enabled (synchronization, best practices, etc.): All of them

**Describe the Issue**

VVL docs list that you can use `VK_KHRONOS_VALIDATION_REPORT_FLAGS` env variable to set the report flags:
https://vulkan.lunarg.com/doc/sdk/1.3.283.0/windows/khronos_validation_layer.html

But you can't just enable report_flags for example like this:
```bash
export VK_LOADER_LAYERS_ENABLE=VK_LAYER_KHRONOS_validation
export VK_KHRONOS_VALIDATION_REPORT_FLAGS=perf
```

You will see nothing, as if that env variable doesn't exist.

It wont work if you set it through the VK_EXT_layer_settings API too, even though examples clearly show that you should be able to.
https://vulkan.lunarg.com/doc/sdk/1.3.283.0/windows/layer_configuration.html

```c
// I heard you like macros? I wrote some macros for you:

#define ARRAY_LEN(arr) (sizeof(arr) / sizeof(*arr))
#define VK_ARRAY(...) ARRAY_LEN((__VA_ARGS__)), (__VA_ARGS__)

#define VK_DBG_TYPE_MAP(val) _Generic((val), \
    VkBool32: VK_LAYER_SETTING_TYPE_BOOL32_EXT, \
    str: VK_LAYER_SETTING_TYPE_STRING_EXT )

#define VK_DBG_OPT(name, ...) { \
    .pLayerName = "VK_LAYER_KHRONOS_validation", \
    .pSettingName = name, \
    .type = VK_DBG_TYPE_MAP(*(__VA_ARGS__)), \
    .valueCount = ARRAY_LEN((__VA_ARGS__)), (__VA_ARGS__) }

auto layer_settings_info = (VkLayerSettingsCreateInfoEXT){
    .sType = VK_STRUCTURE_TYPE_LAYER_SETTINGS_CREATE_INFO_EXT,
    .settingCount = VK_ARRAY((VkLayerSettingEXT[]){
        VK_DBG_OPT("validate_core", (VkBool32[]){ true }),
        VK_DBG_OPT("validate_sync", (VkBool32[]){ true }),
        // VK_DBG_OPT("thread_safety", (VkBool32[]){ true }),
        VK_DBG_OPT("validate_best_practices", (VkBool32[]){ true }),
        VK_DBG_OPT("validate_best_practices_arm", (VkBool32[]){ true }),
        VK_DBG_OPT("validate_best_practices_nvidia", (VkBool32[]){ true }),
        VK_DBG_OPT("validate_best_practices_amd", (VkBool32[]){ true }),
        VK_DBG_OPT("validate_best_practices_img", (VkBool32[]){ true }),
        VK_DBG_OPT("debug_action", (str[]){ "VK_DBG_LAYER_ACTION_LOG_MSG" }),
        VK_DBG_OPT("report_flags", (str[]){ "info", "warn", "perf", "error", "debug" }),
        VK_DBG_OPT("enables", (str[]){ 
            "VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_RESERVE_BINDING_SLOT_EXT",
            "VALIDATION_CHECK_ENABLE_SYNCHRONIZATION_VALIDATION_QUEUE_SUBMIT",
            "VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXT",
            "VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT",
            "VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT",
            "VALIDATION_CHECK_ENABLE_VENDOR_SPECIFIC_ALL",
        }),
    }),
};
```
(tried to test the example too, I know you are SHOCKED by the sheer amount of macro awesomeness)

You won't see all of the perf warnings or whatever unless you also set in the `vk_layer_settings.txt`:
```
khronos_validation.report_flags = debug,error,perf,info,warn
```
OR you define your own messenger:
```c
VkDebugUtilsMessengerEXT messenger;
vkCreateDebugUtilsMessengerEXT(instance, &(VkDebugUtilsMessengerCreateInfoEXT){
    .sType = VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT,
    .pfnUserCallback = vk_dbg_callback,
    .messageSeverity =
        VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT | 
        VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT | 
        VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT | 
        VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT,
    .messageType =
        VK_DEBUG_UTILS_MESSAGE_TYPE_DEVICE_ADDRESS_BINDING_BIT_EXT | 
        VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT | 
        VK_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT | 
        VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT,
}, NULL, &messenger);
```

Other settings seems to work as expected.

Also https://vulkan.lunarg.com/doc/sdk/1.3.283.0/windows/layer_configuration.html shows the env variable without the vendor `KHRONOS` part, why?

> 
> Example Usage on Linux/macOS:
> ```
> $ export VK_VALIDATION_VALIDATE_CORE=true
> $ export VK_VALIDATION_VALIDATE_SYNC=true
> $ export VK_VALIDATION_THREAD_SAFETY=true
> $ export VK_VALIDATION_DEBUG_ACTION=VK_DBG_LAYER_ACTION_LOG_MSG
> $ export VK_VALIDATION_REPORT_FLAGS=debug:error:perf:info:warn
> $ export VK_VALIDATION_ENABLE_MESSAGE_LIMIT=true
> $ export VK_VALIDATION_DUPLICATE_MESSAGE_LIMIT=3
> ```

Tried it too, doesn't work.

**Additional context**

Environment variable for this setting didn't exist before, you could set it through the config, but not through the env variable.
I suspect when VK_EXT_layer_settings was introduced you added automatic generation of the docs and different forms of config parsers, but didn't actually verify that they actually work? Seems pretty weird.
It seems to had happened when SDK 1.3.275.0 was released, and if you view docs for 1.3.268.0 it will show `Environment Variable: N/A` there under the option.

Also maybe you should test this somehow for other options, at least you can find out which settings didn't have the appropriate env var before by looking at the previous versions of the docs.

**Comment by spencer-lunarg** [comment]
ya, this has been a todo of mine for a while

so you are right, this was all designed before the layer settings

we should be able to set `export VK_LAYER_REPORT_FLAGS=debug:error:perf:info:warn` like any other setting

I need to do a lot fixes to the setting, which is not the hard part, the hard part is writing good tests to make sure I don't break things under people
