### ISSUE TITLE
ERROR_DEVICE_LOST with "Descriptor indexing" enabled when using VK_EXT_descriptor_buffer

### ISSUE THREAD

**Issue by StefanPoelloth** [KhronosGroup/Vulkan-ValidationLayers#8492]
**Environment:**
 - OS: Windows 10 22H2 19045.4780
 - GPU and driver version: 560.94
 - SDK or header version if building from repo: af7b0a35d009b5ad6e0b280a5b81388608ebfe39
 - Options enabled (synchronization, best practices, etc.): Descriptor Indexing

**Describe the Issue**
When using VK_EXT_descriptor_buffer and VVL option "Descriptor indexing", the driver resets and the app errors with `ERROR_DEVICE_LOST`.
It happens in my production code and can be reproduced with the sample: [descriptor_buffer_basic.cpp](https://github.com/KhronosGroup/Vulkan-Samples/blob/main/samples/extensions/descriptor_buffer_basic/descriptor_buffer_basic.cpp )

**Expected behavior**

Either no crash and working or a message that descriptor indexing checks are not possible with descriptor buffers and disabling it internally to not crash.

**Comment by spencer-lunarg** [comment]
We currently don't support `VK_EXT_descriptor_buffer` at all on GPU-AV (aka Descriptor indexing)

it should be producing a warning, but I need to just write actual Descriptor Buffer GPU-AV tests and confirm it will "work as normal" and not just crash on you like this

Thanks for reporting, will get fixed

**Comment by StefanPoelloth** [comment]
@spencer-lunarg I can confirm that your PR fixes the crash for us.
