### ISSUE TITLE
debugPrintfEXT does not work on indirect draws

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-ValidationLayers#8503]
Tested with ToT VVL. Works fine on normal draws.

**Comment by spencer-lunarg** [comment]
@zmike so something else must have been going wrong, I wrote tests and confirmed that 

- DispatchIndirect
- DispatchBase
- DrawIndexed
- DrawIndexedIndirect
- DrawIndirectCount
- DrawIndexedIndirectCount

all work as expected

**Comment by zmike** [comment]
:thinking:  :thinking:  :thinking: 

I guess close for now?

**Comment by spencer-lunarg** [comment]
regardless I am glad we have more tests for DebugPrintf... I assume something else was completely wrong...

Were you trying to print in a fragment shader, but wasn't making it there (ex `rasterizerDiscardEnable`,  the vertex shader didn't create any triangles, etc)

**Comment by zmike** [comment]
I was printing from a vertex shader that was definitely producing triangles. I don't have a good explanation for why it wasn't working, and I don't have time to test again now.

**Comment by spencer-lunarg** [comment]
![image](https://github.com/user-attachments/assets/de623359-e5a3-4410-93e4-ef1ca3d76b42)

**Comment by zmike** [comment]
![crab](https://imgur.com/crab-threatening-cameraman-sjFQpzl)
