### ISSUE TITLE
vkGetPipelineKeyKHR is broken and crashes in drivers

### ISSUE THREAD

**Issue by HansKristian-Work** [KhronosGroup/Vulkan-ValidationLayers#8540]
**Environment:**
 - OS: Arch Linux
 - GPU and driver version: doesn't matter
 - SDK or header version if building from repo: main.
 - Options enabled (synchronization, best practices, etc.):

**Describe the Issue**

vkGetPipelineKeyKHR with non-null pCreateInfo seems to pass down the create info as-is, but I don't think that works since e.g. VkRenderPass objects are wrapped, and must be unwrapped, but the layer implementation doesn't seem to do this, leading to segfaults in driver.

**Comment by spencer-lunarg** [comment]
ya, the code generation for this seemed... not correct, but so far nothing was "breaking", this was on my radar to test more before the SDK drops very soon and already got my setup ready... but seems @HansKristian-Work is much faster than me to play with the new toys

**Comment by HansKristian-Work** [comment]
https://github.com/Themaister/Granite/pull/138 adds pipeline binary support for testing. Have to load the layer manually since I disable pipeline binary when VVL is used due to this breakage.
