### ISSUE TITLE
vkGetPipelineKHR crashes when given a NULL pCreateInfo

### ISSUE THREAD

**Issue by HansKristian-Work** [KhronosGroup/Vulkan-ValidationLayers#8544]
**Describe the Issue**

> If pPipelineCreateInfo is NULL, then the implementation must return the global key that applies to all pipelines.

This is ignored, leading to a segfault in `CoreChecks::PreCallValidateGetPipelineKeyKHR`.

**Comment by spencer-lunarg** [comment]
@HansKristian-Work hopfully this is the end of the VVL Pipeline Binary issue saga
