### ISSUE TITLE
The layers don't validate that `vertexAttributeInstanceRateDivisor` is available if the application requests

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-ValidationLayers#855]
See baldurk/renderdoc#1348 from [this comment](https://github.com/baldurk/renderdoc/issues/1348#issuecomment-481749138) on.

If the application unconditionally sets `vertexAttributeInstanceRateDivisor` but the driver doesn't support it, there are no validation errors, though there should be.

**Comment by locke-lunarg** [comment]
@ShabbyX  If you want to set `vertexAttributeInstanceRateDivisor`, you have to add a device extension, `VK_EXT_VERTEX_ATTRIBUTE_DIVISOR_EXTENSION_NAME` or `VK_EXT_vertex_attribute_divisor`.

If your driver doesn't support `VK_EXT_vertex_attribute_divisor`, you can see a log like 
`loader_validate_device_extensions: Device extension VK_EXT_vertex_attribute_divisor not supported by selected physical device or enabled layers.`, and then `vkCreateDevice` fail.

Is that you need? or you means something else?

**Comment by locke-lunarg** [comment]
[Pull #864](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/864)
Added a validation. When using VkPhysicalDeviceFeatures2 & VkPhysicalDeviceVertexAttributeDivisorFeaturesEXT without enabling the extensions, it prints logs

**Comment by ShabbyX** [comment]
@locke-lunarg Thanks for taking a look, but that's not exactly the issue I'm seeing. We do enable the extension. The issue is that even though the extension is present, `vertexAttributeInstanceRateDivisor` is not supported. Setting that doesn't cause a validation error.

**Comment by jzulauf-lunarg** [comment]
There isn't any valid usage that required features be supported for the command to be *valid*.  The language in the spec is that

> vkCreateDevice verifies that extensions and features requested in the ppEnabledExtensionNames and pEnabledFeatures members of pCreateInfo, respectively, are supported by the implementation. 

and...

> If any requested feature is not supported, vkCreateDevice must return VK_ERROR_FEATURE_NOT_PRESENT. 

Typically when the *driver* is required to return an error code, validation is silent unless there is a specific valid usage statement.

**Comment by locke-lunarg** [comment]
@ShabbyX [issue #24 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/24)
We have a future plan, `Add warnings for non-success driver return values`.
