### ISSUE TITLE
Missing CmdDrawIndirect stride checks

### ISSUE THREAD

**Issue by mark-lunarg** [KhronosGroup/Vulkan-ValidationLayers#857]
Parameter validation should be checking the class of stride checks for functins such as `CmdDrawIndirect` (**VUID-vkCmdDrawIndirect-drawCount-00476**).  Looks like there are over half-a-dozen of these, not sure if any of them are currently checked.

**Comment by locke-lunarg** [comment]
Fix in [PR #909 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/909)
