### ISSUE TITLE
Add missing subpass structure checks

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#86]
**Issue by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Friday May 04, 2018 at 02:33 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2638_

----

I've run into a bunch of issues recently where attachments are used in invalid combinations (same attachment multiple times in one subpass by accident...).

Most of these don't have VUs, but we should still have the checks.

**Comment by chrisforbes** [comment]
Fixed.
