### ISSUE TITLE
rbtree infinite loop/crash

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-ValidationLayers#8618]
As I pasted to @spencer-lunarg, running this this [piglit](https://gitlab.freedesktop.org/mesa/piglit) test with VVL causes an extended loop inside VVL on shutdown which eventually results in a crash:

 `ZINK_DEBUG=vvl MESA_LOADER_DRIVER_OVERRIDE=zink bin/object-namespace-pollution glBitmap framebuffer -auto -fbo`

**Comment by spencer-lunarg** [comment]
(notes) 

If I turn off everything but Core Checks ( `VK_LAYER_DISABLES=VK_VALIDATION_FEATURE_DISABLE_SHADERS_EXT,VK_VALIDATION_FEATURE_DISABLE_THREAD_SAFETY_EXT,VK_VALIDATION_FEATURE_DISABLE_OBJECT_LIFETIMES_EXT,VK_VALIDATION_FEATURE_DISABLE_UNIQUE_HANDLES_EXT,VK_VALIDATION_FEATURE_DISABLE_API_PARAMETERS_EXT`) it will still crash

If I turn off core checks (`VK_LAYER_DISABLES=VK_VALIDATION_FEATURE_DISABLE_CORE_CHECKS_EXT`) it works as expected... so seems to be isolated to just core checks

I noticed from API dump it goes

```
vkBindBufferMemory()
vkBindBufferMemory()
PIGLIT: {"result": "pass" }
vkCreateImageView()
vkGetPhysicalDeviceImageFormatProperties2KHR()
vkCreateImage()
vkGetImageMemoryRequirements2()
vkAllocateMemory()
vkBindImageMemory()
vkCmdPipelineBarrier2() <---- memory corruption noticed here
```

**Comment by spencer-lunarg** [comment]
seems all `static const std::map` are being corrupted, even in things in like `GetAccessMask2CommonMap()`, not sure yet when that corruption starts

**Comment by spencer-lunarg** [comment]
so Piglet is calling `exit(0)`

```
#0 __run_exit_handlers stdlib/exit.c:108
#1 __GI_exit stdlib/exit.c:138
#2 piglit_report_result piglit/tests/util/piglit-util.c:245-
```

but it is then handling it `piglit-framework-gl.c` via the `destory()` but our `std::map` are being destroyed as a library under us during that `exit(0)` call

**Comment by spencer-lunarg** [comment]
note: seems this might be a regression from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8320

**Comment by zmike** [comment]
I think that's good enough.
