### ISSUE TITLE
Arrays of combined image samplers with YCbCr samplers in a descriptor

### ISSUE THREAD

**Issue by pumexx** [KhronosGroup/Vulkan-ValidationLayers#863]
Suppose we have an array of combined image samplers defined in a shader :
layout(set=1, binding=0) uniform sampler2D u_sampler[4];
and each combined image sampler has image view and sampler pointing to the same VkSamplerYcbcrConversion object.

Validation fails with message : 
[ VUID-VkWriteDescriptorSet-descriptorType-01948 ] Object: 0x12 (Type = 23) | vkUpdateDescriptorSets() failed write update validation for Descriptor Set 0x12 with error: Write update to VkDescriptorSet 0x12 allocated with VkDescriptorSetLayout 0x10 binding #0 failed with error message: Attempted write update to combined image sampler and image view and sampler ycbcr conversions are not identical, sampler: 0x3 image view: 0xd.. 

Looks like validation layers have some issue in cvdescriptorset::DescriptorSet::VerifyWriteUpdateContents() : 
the i-th image view in the array of combined image samplers is always compared to the first sampler, not the i-th sampler 
( layers\descriptor_sets.cpp, lines 2194 to 2199 ). 

If you want to reproduce the issue and you have access to gerrit.khronos.org, then you can download the code from : https://gerrit.khronos.org/#/c/3756/

Parameters required to reproduce the issue: 
deqp-vk --deqp-vk-device-id=1 --deqp-case=dEQP-VK.ycbcr.conversion.r10x6g10x6b10x6a10x6_unorm_4pack16.sampler_array.nearest_tiling_optimal_binding_31

**Comment by locke-lunarg** [comment]
[pull #869](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/869)
Fixed it.
