### ISSUE TITLE
Push Constant memory leak

### ISSUE THREAD

**Issue by Eearslya** [KhronosGroup/Vulkan-ValidationLayers#8632]
**Environment:**
 - OS: Windows 10 x64
 - GPU and driver version: NVidia GTX 3080 
 - SDK or header version if building from repo: 789f86b
 - Options enabled (synchronization, best practices, etc.):

**Describe the Issue**

Command Buffer state tracking has a member variable, [`push_constant_data_chunks`](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/789f86b62b8bc15dcf427da5254e485c7cb69993/layers/state_tracker/cmd_buffer_state.h#L517) that tracks push constant data as it is pushed with `vkCmdPushConstants` calls. Every call adds to the end of this array with the data the user has pushed, [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/789f86b62b8bc15dcf427da5254e485c7cb69993/layers/state_tracker/state_tracker.cpp#L2944).

This array is cleared out whenever a multipass render pass begins or moves to the next subpass (via `UnbindResources()`). However, this array is NOT cleared out when the command buffer is reset, either with `vkResetCommandBuffer` or `vkResetCommandPool`. This results in a slow leak as every push constant slowly adds more data to the command buffer's state.

**Expected behavior**

[`vvl::CommandBuffer::ResetCBState()`](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/789f86b62b8bc15dcf427da5254e485c7cb69993/layers/state_tracker/cmd_buffer_state.cpp#L208) should clear the `push_constant_data_chunks` array.

**Additional context**

**Comment by arno-lunarg** [comment]
Thank you for reporting this! Should be a quick fix (TM)

**Comment by morrow-addref** [comment]
Hi there, I seemingly am still getting what looks to be a memory leak with push constants. My set up is multithreaded with secondary command buffers that get executed in a primary command buffer which is then passed to a graphics queue. The command pool for the second buffer then gets reset on the next frame it is used (the next frame it gets used being max frames in flight after it was previously used).

Should "ResetCBState" call "Clear()" on "push_constant_ranges_layout" like the other change in #8635?

Is there a way I can narrow down what may be leaking?

**Comment by arno-lunarg** [comment]
Looking at the code, the necessary clear to `push_constant_ranges_layout` is here, trying to write a simple test with secondary command buffers and push constants did not show an obvious leak.

Are you using the latest SDK? If so, would you be able to send a GFXR capture of your app showing the leak so I can have a look please? It can be sent privately through https://share.lunarg.com/home/welcome if needed
