### ISSUE TITLE
Unexplained validation error for SPIR-V Capability ClipDistance in call to vkCreateShaderModule

### ISSUE THREAD

**Issue by jcortell68** [KhronosGroup/Vulkan-ValidationLayers#8641]
**Environment:**
 - OS: Android
 - GPU and driver version: Samsung
 - Validation layer for Android 1.3.290.0

**Describe the Issue**
I'm getting the following validation error, but I've checked that `vkGetPhysicalDeviceFeatures()` returns `VK_TRUE` for `features.shaderClipDistance`. Is there something I'm not understanding about this error and/or the corresponding vulkan spec usage for `vkCreateShaderModule`?

```
[VUID-VkShaderModuleCreateInfo-pCode-08740] Code 115483881 : Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-08740 ]
| MessageID = 0x6e224e9 | vkCreateShaderModule():  SPIR-V Capability ClipDistance was declared, but one of the following 
equirements is required (VkPhysicalDeviceFeatures::shaderClipDistance). The Vulkan spec states: If pCode is a pointer to SPIR-V code, and
Code declares any of the capabilities listed in the SPIR-V Environment appendix, one of the corresponding requirements must be 
satisfied (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-08740)
```

**Additional context**

BTW, notice that the error message has a bad/stale/broken hyperlink. [Here](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkShaderModuleCreateInfo.html#VUID-VkShaderModuleCreateInfo-pCode-08740) is the correct link the spec Valid Usage item is this.

Ironically, the vulkan spec content at that link has, itself, a broken link. [Here](https://docs.vulkan.org/spec/latest/appendices/spirvenv.html#:~:text=Vulkan%20Environment%20for%20SPIR-V.%20Shaders
) is the correct SPIRV Environment link

**Comment by spencer-lunarg** [comment]
So there is a difference between a "feature being supported" and "enabling a feature"

The poster child for this is `robustBufferAccess`, while you "can" enable it, it does occur a performance penalty, so it is suggested to not enable it unless you need.... for most features, it is free to enable

So what is most likely happening is you checked for support, but didn't set it in `VkDeviceCreateInfo::pEnabledFeatures` and that is why you are getting this error message

More info about features can be found here https://github.com/KhronosGroup/Vulkan-Guide/blob/main/chapters/enabling_features.adoc

**Comment by jcortell68** [comment]
> So what is most likely happening is you checked for support, but didn't set it in VkDeviceCreateInfo::pEnabledFeatures and that is why you are getting this error message

That was it. This Vulkan rookie appreciates the assist.
