### ISSUE TITLE
Differentiate between NV and EXT DGC features

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-ValidationLayers#8678]
Context: https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6933

Like BDA, the EXT version of GDC uses the same feature names as the NV version, but changes the semantics.

VVL needs to differentiate between these features now. That starts with `scripts/generators/device_features_generator.py` needing this change:

```
        self.identical_but_different_features = {
            'VkPhysicalDeviceBufferDeviceAddressFeaturesEXT': 'EXT',
+           'VkPhysicalDeviceDeviceGeneratedCommandsFeaturesNV': 'NV',
        }
```

and autogenerate takes care of everything except the existing VVL checks for NV and EXT version of the extension. The NV ones would have to be changed to check the NV-specific feature.

**Comment by spencer-lunarg** [comment]
I am like 10000000% sure I added this to `device_features_generator.py` ... but seems we have 2 lists, I added it to `feature_requirements.py` only
