### ISSUE TITLE
Stop enabling all features in AddRequiredFeature

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/Vulkan-ValidationLayers#8684]
We have many tests that we have to go

```c++
AddRequiredFeature(vkt::Feature::meshShader);
AddDisabledFeature(vkt::Feature::multiviewMeshShader);
AddDisabledFeature(vkt::Feature::primitiveFragmentShadingRateMeshShader);
```

because when enable a single feature for `VkPhysicalDeviceMeshShaderFeaturesEXT` it will expose anything else supported... they should be defaulted to disabled

This makes it very easy for someone new to not realize features are being enabled from underneath them

**Comment by arno-lunarg** [comment]
I am all for this change, but my hunch is that many tests will break because of this

**Comment by spencer-lunarg** [comment]
>  but my hunch is that many tests will break because of this

The majority of feature structs have only 1 feature, some will break, but should be easy to catch/fix
