### ISSUE TITLE
incorrect value in error printf

### ISSUE THREAD

**Issue by airlied** [KhronosGroup/Vulkan-ValidationLayers#870]
layers/parameter_validation_utils.cpp:928

                if (vertex_input_state->vertexAttributeDescriptionCount > device_limits.maxVertexInputAttributes) {
                    skip |= log_msg(report_data, VK_DEBUG_REPORT_ERROR_BIT_EXT, VK_DEBUG_REPORT_OBJECT_TYPE_UNKNOWN_EXT, 0,
                                    "VUID-VkPipelineVertexInputStateCreateInfo-vertexAttributeDescriptionCount-00614",
                                    "vkCreateGraphicsPipelines: pararameter "
                                    "pCreateInfo[%d].pVertexInputState->vertexAttributeDescriptionCount (%u) is "
                                    "greater than VkPhysicalDeviceLimits::maxVertexInputAttributes (%u).",
                                    i, vertex_input_state->vertexBindingDescriptionCount, device_limits.maxVertexInputAttributes);
                }

the printf prints vertexBindingDescriptionCount where it should be vertexAttributeDescriptionCount.

**Comment by mark-lunarg** [comment]
@airlied, nice catch!
