### ISSUE TITLE
Question regarding vkCmdPipelineBarrier-image-09555

### ISSUE THREAD

**Issue by jmoguill** [KhronosGroup/Vulkan-ValidationLayers#8703]
**Environment:**
 - OS: Windows 11
 - GPU and driver version: RTX 4070 TI
 - SDK or header version if building from repo: 1.3.290
 - Options enabled (synchronization, best practices, etc.):

**Describe the Issue**

I have a question regarding image layout tracking for vkCmdPipelineBarrier....

I'm trying to use dynamic rendering local read extension, and get a validation error:

Validation Error: [ VUID-vkCmdPipelineBarrier-image-09555 ] Object 0: handle = 0xa336760000000093, name = test_fr_0, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x80387ecc | vkCmdPipelineBarrier(): pImageMemoryBarriers[0] image layout is VK_IMAGE_LAYOUT_UNDEFINED. The Vulkan spec states: If vkCmdPipelineBarrier is called within a render pass instance started with vkCmdBeginRendering, and the image member of any image memory barrier is used as an attachment in the current render pass instance, it must be in the VK_IMAGE_LAYOUT_RENDERING_LOCAL_READ_KHR or VK_IMAGE_LAYOUT_GENERAL layout (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdPipelineBarrier-image-09555)

I am recording a barrier to local read layout before this call to pipeline barrier ....
Here's the log output (I call pipeline barrier, then begin rendering, then draw, then pipeline barrier)

-  imageMemoryBarrier: image: A336760000000093 oldLayout: VK_IMAGE_LAYOUT_UNDEFINED newLayout: VK_IMAGE_LAYOUT_RENDERING_LOCAL_READ_KHR srcStageMask: VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT |  dstStageMask: VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT |  srcAccessMask:  dstAccessMask: VK_ACCESS_COLOR_ATTACHMENT_READ_BIT | VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT |

-  beginRendering
 - draw
-  imageMemoryBarrier: image: A336760000000093 oldLayout: VK_IMAGE_LAYOUT_RENDERING_LOCAL_READ_KHR newLayout: VK_IMAGE_LAYOUT_RENDERING_LOCAL_READ_KHR srcStageMask: VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT | VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT | VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT | VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT |  dstStageMask: VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT | VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT | VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT | VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT |  srcAccessMask: VK_ACCESS_COLOR_ATTACHMENT_READ_BIT | VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT |  dstAccessMask: VK_ACCESS_INPUT_ATTACHMENT_READ_BIT |

I dived into the validation layer code a bit, it seems that the layout state is tracked after submit is called, but not while commands are recorded?

Does the validation layer need to track layout changes while commands are recorded?
What if I call 
pipelineBarrier( imageMemoryBarrier: srcLayout: undefined, dstLayout: local_read, ...)
draw()
pipelineBarrier(imageMemoryBarrier: srcLayout: local_read, dstLayout: transfer_src, ...)

Please clarify: is this an app bug or a validation layer issue?  Should I update to latest vulkan sdk (296?)

**Expected behavior**

**Valid Usage ID**
If applicable, please include the validation messages encountered leading up to the issue

**Additional context**

<details>
<summary>code or terminal output</summary>

```sh
# callstacks, crashes, etc.
# EX:
Validation Error: [ VUID-vkCmdDrawMultiEXT-colorAttachmentCount-06188 ] Object 0: handle = 0x3d47e60 ...
```

</details>

**Comment by artem-lunarg** [comment]
@jmoguill this is a known issue https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7776
Unfortunately at the moment we are busy with other tasks, so there are several layout related issues unaddressed. I personally did not dig into the layout code yet. I'll try to find some time before the next SDK to investigate this.

**Comment by artem-lunarg** [comment]
Closing this as a duplicate. Will notify this ticket when https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7776 is fixed.

**Comment by artem-lunarg** [comment]
> I dived into the validation layer code a bit, it seems that the layout state is tracked after submit is called, but not while commands are recorded?

From what I remember yes, at least partially. During recording time there is no information about current layout (you don't know layout at the beginning of the command buffer), it is available only at submit time.

**Comment by jmoguill** [comment]
> Closing this as a duplicate. Will notify this ticket when #7776 is fixed.

Thanks Artem

**Comment by artem-lunarg** [comment]
The related issue https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7776 was fixed some time ago, also some other image layout functionality (submit time validation) was fixed too.
