### ISSUE TITLE
Vulkan-Headers CPP module causing build issues with clang

### ISSUE THREAD

**Issue by rg3igalia** [KhronosGroup/Vulkan-ValidationLayers#8732]
**Environment:**
 - OS: Linux (Fedora 40)
 - GPU and driver version: does not apply
 - SDK or header version if building from repo: main as of now (6dca9173407b7718e06e7461d551cdffa64be68b)
 - Options enabled (synchronization, best practices, etc.): does not apply

**Describe the Issue**

I'm building the layers using clang on Fedora 40 and I'm hitting build issues when configuring the layers from the tip of the main branch.

```
-- The CXX compiler identification is Clang 18.1.8
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib64/ccache/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
[1/5] Scanning /home/rgarcia/devel/Vulkan-ValidationLayers/external/RelWithDebInfo/64/Vulkan-Headers/include/vulkan/vulkan.cppm for CXX dependencies
FAILED: CMakeFiles/Vulkan-Module.dir/include/vulkan/vulkan.cppm.o.ddi 
"/usr/bin/clang-scan-deps" -format=p1689 -- /usr/lib64/ccache/clang++  -I/home/rgarcia/devel/Vulkan-ValidationLayers/external/RelWithDebInfo/64/Vulkan-Headers/include -Wall -g -O0 -O2 -g -DNDEBUG -std=gnu++20 -x c++ /home/rgarcia/devel/Vulkan-ValidationLayers/external/RelWithDebInfo/64/Vulkan-Headers/include/vulkan/vulkan.cppm -c -o CMakeFiles/Vulkan-Module.dir/include/vulkan/vulkan.cppm.o -MT CMakeFiles/Vulkan-Module.dir/include/vulkan/vulkan.cppm.o.ddi -MD -MF CMakeFiles/Vulkan-Module.dir/include/vulkan/vulkan.cppm.o.ddi.d > CMakeFiles/Vulkan-Module.dir/include/vulkan/vulkan.cppm.o.ddi.tmp && mv CMakeFiles/Vulkan-Module.dir/include/vulkan/vulkan.cppm.o.ddi.tmp CMakeFiles/Vulkan-Module.dir/include/vulkan/vulkan.cppm.o.ddi
Error while scanning dependencies for /home/rgarcia/devel/Vulkan-ValidationLayers/external/RelWithDebInfo/64/Vulkan-Headers/include/vulkan/vulkan.cppm:
In file included from /home/rgarcia/devel/Vulkan-ValidationLayers/external/RelWithDebInfo/64/Vulkan-Headers/include/vulkan/vulkan.cppm:19:
In file included from /home/rgarcia/devel/Vulkan-ValidationLayers/external/RelWithDebInfo/64/Vulkan-Headers/include/vulkan/vulkan.hpp:17:
In file included from /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/algorithm:61:
In file included from /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/stl_algo.h:71:
In file included from /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/cstdlib:79:
/usr/include/stdlib.h:32:10: fatal error: 'stddef.h' file not found
ninja: build stopped: subcommand failed.

Starting builds in /home/rgarcia/devel/Vulkan-ValidationLayers/external/RelWithDebInfo/64
CMake Error at scripts/CMakeLists.txt:123 (message):
  Could not run update_deps.py which is necessary to download dependencies.
```

At this moment I'm not sure if this is a bug in the module or in the compiler. It doesn't matter, though, since the Vulkan-Headers CPP module is not needed at all to compile the layers. We can disable it and build the layers without issues.

```diff
diff --git a/scripts/known_good.json b/scripts/known_good.json
index 5074a13bf..b76b081e0 100755
--- a/scripts/known_good.json
+++ b/scripts/known_good.json
@@ -7,7 +7,10 @@
             "sub_dir": "Vulkan-Headers",
             "build_dir": "Vulkan-Headers/build",
             "install_dir": "Vulkan-Headers/build/install",
-            "commit": "v1.3.299"
+            "commit": "v1.3.299",
+            "cmake_options": [
+                "-DVULKAN_HEADERS_ENABLE_MODULE=OFF"
+            ]
         },
         {
             "name": "Vulkan-Utility-Libraries",
```

**Expected behavior**

The layers build without issues.

**Valid Usage ID**

Does not apply.

**Additional context**

N/A

**Comment by spencer-lunarg** [comment]
Notes from 2 sidebar chats with @rg3igalia and @charles-lunarg 

- This is from a Fedora update
- GCC still works
- Charles spent lot of time working on this 
  - https://github.com/KhronosGroup/Vulkan-Headers/blob/b955ae0edb4f02074bfbf134ccc1980e83122d30/CMakeLists.txt#L45
- Some similar issue https://github.com/llvm/llvm-project/issues/60669
- I am out of my league here (sorry)

**Comment by rg3igalia** [comment]
Probably also related to this: https://github.com/llvm/llvm-project/issues/61006#issuecomment-2132010270

A bug that manifests when clang is invoked through the ccache symlink as is my case. Anyhow, I think it makes sense to skip building the CPP module in the layers if it's not used, knowing the current toolchains have this kind of issues.

**Comment by spencer-lunarg** [comment]
the 1.3.301 will have this change https://github.com/KhronosGroup/Vulkan-Headers/pull/509 to turn off Module by default, so after we pull them in, things will be fixed implicitly
