### ISSUE TITLE
VUID-vkDestroyFence-fence-01120 message

### ISSUE THREAD

**Issue by ziga-lunarg** [KhronosGroup/Vulkan-ValidationLayers#8745]
I'm running into `VUID-vkDestroyFence-fence-01120`, but the message doesn't make much sense. 

> Validation Error: [ VUID-vkDestroyFence-fence-01120 ] | MessageID = 0x5d296248 | vkDestroyFence(): fence can't be called on VkFence 0xf56c9b0000000004[] that is currently in use by VkFence 0xf56c9b0000000004[].

The word `fence` seems extra in that sentence, but more importantly the fence is in use by itself?

Test to reproduce:

```
TEST_F(PositiveSyncObject, DestroyFenceInUse) {
    RETURN_IF_SKIP(Init());

    VkFenceCreateInfo fci = vku::InitStructHelper();
    fci.flags = VK_FENCE_CREATE_SIGNALED_BIT;
    vkt::Fence fence(*m_device, fci);

    vk::WaitForFences(device(), 1, &fence.handle(), VK_TRUE, kWaitTimeout);
    vk::ResetFences(device(), 1u, &fence.handle());

    m_default_queue->Submit(vkt::no_cmd, fence);
}
```

**Comment by artem-lunarg** [comment]
It looks similar issues with other objects, saw the same in Semaphore messages.

**Comment by User21T** [comment]
Good day. The fence is possibly in state where it can't be destroyed. Maybe some process, e.g. submission command at the end of the test, is still using it. I think we could repeat `vk::WaitForFences` after `m_default_queue->Submit(vkt::no_cmd, fence)` to make sure this command has finished and no processes use the fence.
