### ISSUE TITLE
VkPipelineRasterizationStateCreateInfo.rasterizerDiscardEnable awareness

### ISSUE THREAD

**Issue by Agrael1** [KhronosGroup/Vulkan-ValidationLayers#8761]
Hello,

Today I have got in an interesting situation. I am supplying both Vertex and Fragment shader binding to the pipeline, setting up rendering, when suddenly I get this error on pipeline creation:

```
[Validation layer]: VUID-VkGraphicsPipelineCreateInfo-pStages-06894
 [Message]:Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-pStages-06894 ] | MessageID = 0xdfcd6d41 | vkCreateGraphicsPipelines(): pCreateInfos[0] does not have fragment shader state, but stages (VK_SHADER_STAGE_VERTEX_BIT|VK_SHADER_STAGE_FRAGMENT_BIT) contains VK_SHADER_STAGE_FRAGMENT_BIT. The Vulkan spec states: If the pipeline requires pre-rasterization shader state but not fragment shader state, elements of pStages must not have stage set to VK_SHADER_STAGE_FRAGMENT_BIT (https://vulkan.lunarg.com/doc/view/1.3.280.0/windows/1.3-extensions/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-pStages-06894)
```

After searching for couple of hours with Discord help we found that it is caused by `VkPipelineRasterizationStateCreateInfo.rasterizerDiscardEnable = true;` which was mistakenly treated as early depth stencil.

It would be nice to have that flag actually be present in validation as the possible cause of the error.

**Comment by spencer-lunarg** [comment]
Thanks for raising this  (I am always trying to provide better error messages)

So yes, the "tricky" part is someone might be using `VK_EXT_graphics_pipeline_library` extension where you are able to only create the various parts and `rasterizerDiscardEnable` is not the issue... but for the "normal" case (which I think you hit) I agree, the `rasterizerDiscardEnable` has personally tripped me up, and should just be in the error message

created https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8762
