### ISSUE TITLE
Providing stack trace in messages when validation is delayed

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#88]
**Issue by [fduranleau-gl](https://github.com/fduranleau-gl) (MIGRATED)**
_Friday May 04, 2018 at 14:36 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2641_

----

We know that some validation can not be done immediately when recording a command (e.g. tracking image layout). So some of them are deferred at submission time. However, if we hit an error (or a warning) there, then we lose the context from where the offending command comes.

So, a nice (and non-intrusive) feature that would be very practical is if, for such deferred validation, information about the call stack could be saved (at record time) and displayed along with messages. This should be possible to implement at least on some platforms.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/mark-lunarg"><img src="https://avatars2.githubusercontent.com/u/7252958?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mark-lunarg](https://github.com/mark-lunarg) (MIGRATED)**
_Friday May 04, 2018 at 15:53 GMT_

----

Thanks @fduranleau-gl!

**Comment by karl-lunarg** [comment]
<a href="https://github.com/chrisforbes"><img src="https://avatars1.githubusercontent.com/u/128877?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Tuesday May 08, 2018 at 22:21 GMT_

----

This is a really neat idea, but likely expensive to do... :+1:

**Comment by karl-lunarg** [comment]
<a href="https://github.com/fduranleau-gl"><img src="https://avatars2.githubusercontent.com/u/37842737?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fduranleau-gl](https://github.com/fduranleau-gl) (MIGRATED)**
_Wednesday May 09, 2018 at 11:56 GMT_

----

There certainly is a cost. Maybe it could be an opt-in feature?

**Comment by jzulauf-lunarg** [comment]
@fduranleau-gl   Trying to scope this.  By "information about the call stack" do you me:

1) The current vkCmdInsertDebugUtilsLabelEXT information current at the time the validation was deferred?

1) the call stack from the application down to the API in the sense of a debugger (which assumes sufficiently intact symbolic information that stack unwinding is possible)

2) information regarding (for example, with validation deferred to QueueSubmit time) command buffer the deferred validation was recorded into, and the API call (perhaps parameters thereof) that caused the deferred validation



3) Some other state reported? (please supply)

Would timestamps (from some global system high precision timer) be of use?

**Comment by mark-lunarg** [comment]
Will track this enhancement in the validation error tracking issue, #679.
