### ISSUE TITLE
Spurious VUID-vkCmdBindDescriptorBuffersEXT-maxResourceDescriptorBufferBindings-08049(ERROR / SPEC)

### ISSUE THREAD

**Issue by buzmeg** [KhronosGroup/Vulkan-ValidationLayers#8835]
**Environment:**
 -   OS: Ubuntu 24.04.1 LTS (Linux hostname 6.8.0-45-generic)
 -    GPU and driver version: Intel UHD Graphics 620 (WHL GT2)
 -    SDK or header version if building from repo: Vulkan Instance Version: 1.3.290
 -    Options enabled (synchronization, best practices, etc.): Validation

I received:

VUID-vkCmdBindDescriptorBuffersEXT-maxResourceDescriptorBufferBindings-08049(ERROR / SPEC): msgNum: -132400417 - Validation Error: [ VUID-vkCmdBindDescriptorBuffersEXT-maxResourceDescriptorBufferBindings-08049 ] Object 0: handle = 0x7fff88037490, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xf81bbadf | vkCmdBindDescriptorBuffersEXT():  Number of resource buffers is 2. There must be no more than maxResourceDescriptorBufferBindings (1) descriptor buffers containing resource descriptor data bound. List of resource buffers:
VkBuffer 0x2cfba2000000001c[]
VkBuffer 0x2cfba2000000001c[]

I'm pretty sure those are the same buffer.  :)

**Comment by spencer-lunarg** [comment]
There is a TODO in the code

> // TODO - Understand what "descriptor buffer" means toward the limit, does the same VkBuffer reused count twice

I need to raise a spec issue to clarify if "resource descriptor buffers" cares about the number of "things bound" or "unique handles bound"

**Comment by buzmeg** [comment]
Oddly, I have a different program that violates that limit significantly with completely different buffers, and yet works perfectly on my integrated Intel hardware.

Which, to a certain extent, sorta makes sense. Everything is indirected through VkBuffers allocated by the user and VkDeviceAddresses.  At bottom, it's just pointer chasing.  There is no inherent reason why everything has to come off of the same VkBuffer as long as the pointers and addresses all land in the memory that the card can use for descriptors.

In the mesa vulkan driver in anv_physical_device.c, for example, it's completely arbitrary:
```
      if (pdevice->uses_ex_bso) {
         props->maxDescriptorBufferBindings = MAX_SETS;
         props->maxResourceDescriptorBufferBindings = MAX_SETS;
         props->maxSamplerDescriptorBufferBindings = MAX_SETS;
         props->maxEmbeddedImmutableSamplerBindings = MAX_SETS;
      } else {
         props->maxDescriptorBufferBindings = 3; /* resources, samplers, push (we don't care about push) */
         props->maxResourceDescriptorBufferBindings = 1;
         props->maxSamplerDescriptorBufferBindings = 1;
         props->maxEmbeddedImmutableSamplerBindings = 1;
      }
```

Those numbers aren't used *anywhere* in the driver itself.  They don't feed any allocation limits as far as I can see, and they're never checked anywhere either. They only exist in the Intel driver, and appear to be completely arbitrary.

**Comment by buzmeg** [comment]
Bug filed with Mesa: https://gitlab.freedesktop.org/mesa/mesa/-/issues/12144

Unfortunately, I don't think this is going to help the validation layer very much.  Nothing inside the Mesa code uses these values, so there isn't going to be any "clarification of definition" coming from that direction.

Everything sane is just setting it to MAX_SETS which is 32 on most things.

**Comment by spencer-lunarg** [comment]
From some internal discussion, this VU is correct, if you go 

```c++
VkDescriptorBufferBindingInfoEXT descriptor_buffer_binding_info[2];
descriptor_buffer_binding_info[0].address = descriptor_buffer.Address();
descriptor_buffer_binding_info[0].usage = VK_BUFFER_USAGE_RESOURCE_DESCRIPTOR_BUFFER_BIT_EXT;
descriptor_buffer_binding_info[1].address = descriptor_buffer.Address() + alignment; // same VkBuffer
descriptor_buffer_binding_info[1].usage = VK_BUFFER_USAGE_RESOURCE_DESCRIPTOR_BUFFER_BIT_EXT;
vk::CmdBindDescriptorBuffersEXT(m_command_buffer.handle(), 2, descriptor_buffer_binding_info);
```

that counts as `2` towards `maxResourceDescriptorBufferBindings` ... the spec / VU is not clear and we are going to update that... but also, the Validation Error message could also notice this and report this as it is easy to get confused
