### ISSUE TITLE
gpuav_debug_disable_all is set to "ADVANCED" instead of "HIDDEN"

### ISSUE THREAD

**Issue by christophe-lunarg** [KhronosGroup/Vulkan-ValidationLayers#8907]
`gpuav_debug_disable_all` is set to `"view": "HIDDEN"`
And `gpuav_debug_settings` is set to `"view": "ADVANCED"`

Shouldn't `gpuav_debug_settings` be set to `HIDDEN` considering that all the setting within `gpuav_debug_disable_all` group is `HIDDEN`?

Spencer said yes, `gpuav_debug_settings` should be `HIDDEN`.

**Comment by spencer-lunarg** [comment]
@christophe-lunarg I mixed this up, currently it looks like

```json
{
"key": "gpuav_debug_settings",
"view": "ADVANCED",
"settings": [
    {
        "key": "gpuav_debug_disable_all",
        "view": "HIDDEN",
    },
    {
        "key": "gpuav_debug_validate_instrumented_shaders",
    },
    {
        "key": "gpuav_debug_dump_instrumented_shaders",
    },
    {
        "key": "gpuav_debug_max_instrumentations_count",
    },
    {
        "key": "gpuav_debug_print_instrumentation_info",
    }
]
```

I guess I still want the other settings, is the issue that I am missing `"view": "ADVANCED"` for the all the other settings, I thought they would inherit it from `gpuav_debug_settings`

`gpuav_debug_disable_all` is just a very specific one I don't want anyone who is not a VVL dev to accidentally set, the others I could care less if people want to poke at them
