### ISSUE TITLE
Vulkan Pipeline Barrier Synchronization Issue: Invalid Source Stage in vkCmdPipelineBarrier.

### ISSUE THREAD

**Issue by Mordentary** [KhronosGroup/Vulkan-ValidationLayers#8909]
Hi, so I found this trying to fix validation error
**Environment:**
- OS: Windows 11
- GPU and driver version: RTX 3050 TI mobile, 565.90
- Branch: docking (1.91.5)
- Options enabled: Synchronization validation enabled, SDL

**Describe the Issue**
When dragging an ImGui window outside of the main application window, a synchronization hazard occurs due to incorrect pipeline barrier stage flags. The Vulkan backend uses `VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT` as the source stage in `vkCmdPipelineBarrier`, which causes a read-write hazard during external window operations.

**Expected behavior**
The pipeline barrier should properly synchronize the image layout transition when dragging windows outside the main window, without triggering any validation errors. This should be achieved by using the correct source stage flag (`VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT`).

**Valid Usage ID**
Validation Error: [ SYNC-HAZARD-WRITE-AFTER-READ ]

<details>
<summary>Validation Error Details</summary>

```sh
[ERROR] Validation Error: [ SYNC-HAZARD-WRITE-AFTER-READ ]
Object 0: handle = 0x291d2876fa0, type = VK_OBJECT_TYPE_QUEUE;
MessageID = 0x376bc9df
vkQueueSubmit(): Hazard WRITE_AFTER_READ for entry 0, VkCommandBuffer 0x291efc487a0[]
Submitted access info (submitted_usage: SYNC_IMAGE_LAYOUT_TRANSITION, command: vkCmdPipelineBarrier, seq_no: 1, reset_no: 112)
Access info (prior_usage: SYNC_PRESENT_ENGINE_SYNCVAL_PRESENT_ACQUIRE_READ_SYNCVAL, 
read_barriers: VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT|VK_PIPELINE_STAGE_2_BOTTOM_OF_PIPE_BIT,
batch_tag: 3367, vkAcquireNextImageKHR aquire_tag:3367:
VkSwapchainKHR 0x1d4e2e0000000062[], image_index: 2image: VkImage 0x5dbcf90000000065[])
```

</details>

**Additional context**

Related discussion: [SYNC-HAZARD-WRITE-AFTER-READ error with swapchain acquisition and command buffer submission](https://stackoverflow.com/questions/77871832/sync-hazard-write-after-read-error-with-swapchain-acquisition-and-command-buffer)

**Current Code**

```cpp
// In imgui_impl_vulkan.cpp
vkCmdPipelineBarrier(fd->CommandBuffer,
    VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,                    // srcStageMask (incorrect)
    VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,        // dstStageMask
    0,
    0, nullptr,
    0, nullptr,
    1, &barrier);
```

**Reproduction Steps:**
1. Use ImGui docking branch with Vulkan backend
2. Enable synchronization validation
3. Create a window in the application
4. Drag the window outside the main application window
5. Observe validation error in debug output

**Proposed Fix:**
```cpp
vkCmdPipelineBarrier(fd->CommandBuffer,
    VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,        // srcStageMask (correct)
    VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,        // dstStageMask
    0,
    0, nullptr,
    0, nullptr,
    1, &barrier);
```

**Comment by artem-lunarg** [comment]
@Mordentary From what you described it sounds it’s  an ImGui issue and not a Vulkan Validation Layer issue. This issue tracker is the bugs in the validation layer.

**Comment by Mordentary** [comment]
Absolutely! I misread repo!
