### ISSUE TITLE
Increased CPU consumption over time

### ISSUE THREAD

**Issue by fridenmf** [KhronosGroup/Vulkan-ValidationLayers#8934]
**Environment:**
 - OS: Windows 11
 - GPU and driver version: NVIDIA GeForce RTX 2080 Ti (560.94)
 - SDK or header version if building from repo: 1.3.296.0
 - Options enabled (synchronization, best practices, etc.): synchronization, best practices

**Describe the Issue**

The validation layers consume more CPU time the longer an application runs if an application often create and destroys resources. The first seconds the validation layers take up less than 1 ms CPU time, but after about 40 seconds it takes about 8 ms, and it continues to increase the longer you run. An application starting on 200 FPS gets down to about 40 FPS after about 2 minutes.

There is a video under **Additional context** demonstrating this, as well as Visual Studio performance profile results showing the amount of time spent in the validation layers compared to a "dummy 4 ms function", where the dummy function takes up more time than the validation layers in the first seconds of the application, but only a fraction of the time of the validation layers 40 seconds later.

**Expected behavior**

The validation performance should not get worse over time if the total number of resources used in a frame does not increase over time.

**Additional context**

<details>

Video:\
![vvl_performance_loss](https://github.com/user-attachments/assets/4eb41ade-90eb-4b40-a432-8abe5b54c217)

Visual Studio performance profile after 8 seconds:\
![after_8_seconds](https://github.com/user-attachments/assets/b9257718-e859-4735-8575-65668a76661e)

Visual Studio performance profile after 40 seconds:\
![after_40_seconds](https://github.com/user-attachments/assets/5fafb363-d16c-49c0-8d83-d06ca490224f)

</details>

**Comment by spencer-lunarg** [comment]
Thanks to bringing this to our attentions, we will take a look into this locally and see if we can reproduce and then hopefully track down what is going on

**Comment by arno-lunarg** [comment]
Would you be able to provide an executable so we can have a proper look at how VVL behaves with your application please?

**Comment by artem-lunarg** [comment]
@fridenmf Is synchronization validation enabled? If yes, does it behave the same if only standard validation is enabled?

**Comment by fridenmf** [comment]
@arno-lunarg Sure! The following app has the ability to load the validation layers from the application if the "validate"-checkbox is ticked. Leave it unticked if you reproduce it vkconfig.exe instead\
[TODO.zip](https://github.com/user-attachments/files/17940333/TODO.zip)

@artem-lunarg Seems to only get the slowdown when "Synchronization -> Submit time validation" is on.

**Comment by artem-lunarg** [comment]
@fridenmf I guess the application uses timeline semaphores. If yes, does it only slow down the app or there is also significant increase of memory usage (as reported by the OS tools)?

One more question, are there synchronization validation errors? (this can increase resource usage if we made a mistake)

**Comment by fridenmf** [comment]
@artem-lunarg It does not use timeline semaphores, it's mostly Vulkan 1.0 except from using VK_KHR_get_physical_device_properties2 for displaying driver properties. I've measured memory and I don't see any signs of memory leaks. There is no validation errors or warnings except from a `BestPractices-vkCreateSwapchainKHR-suboptimal-swapchain-image-count` due to me using two swapchain images instead of the recommended three.

**Comment by fridenmf** [comment]
When implementing resource reusage for all resources created each frame I don't see the performance slowdown. Binary search lead me to the VkImage being created every frame with usage VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_SAMPLED_BIT, VK_SAMPLE_COUNT_1_BIT. When it's reused there is no slowdown in VVL, when it's re-created every frame there is slowdown in the VVL. It should narrow down the search.

**Comment by artem-lunarg** [comment]
The issues is reproducible and checking the older SDKs it seems we always had it (or at least for quite some time).
