### ISSUE TITLE
PositiveSyncObject.KhronosTimelineSemaphoreExample sporadically asserts

### ISSUE THREAD

**Issue by ziga-lunarg** [KhronosGroup/Vulkan-ValidationLayers#8942]
Running `PositiveSyncObject.KhronosTimelineSemaphoreExample` on nvidia 3070 with latest public beta driver will sporadically assert:

> [ RUN      ] PositiveSyncObject.KhronosTimelineSemaphoreExample
> Assertion failed: scope_ != kInternal, file C:\Projects\Vulkan-ValidationLayers\layers\state_tracker\semaphore_state.cpp, line 350

**Comment by artem-lunarg** [comment]
It's a known on nvidia, that's why this test was disabled on CI. It works properly on AMD. I don't think it should be an issue, but we can disable it all together. 

The above assert is related to mimalloc, sometimes everything go to hell at the end.

**Comment by ziga-lunarg** [comment]
Good to know, maybe there should be a comment above the test in case anyone else runs into this.

**Comment by artem-lunarg** [comment]
> Good to know, maybe there should be a comment above the test in case anyone else runs into this.

I feel it's a good case where vendor specific checks in the test are justifiable (not only CI blacklist). You usually want to run entire test suite without thinking if some test does not like your machine.
