### ISSUE TITLE
Missing validation for VK_KHR_swapchain_mutable_format

### ISSUE THREAD

**Issue by nickyc95** [KhronosGroup/Vulkan-ValidationLayers#896]
Hi,

When trying to use `VK_KHR_swapchain_mutable_format` it correctly checks for dependent extensions but still to throw a validation error when the view format doesn't match the swapchain format.

Had a look around and found (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/496) but that appears to never have been merged.

(https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/514) was merged but only check for dependent extensions and that formats match.

Thanks

**Comment by mark-lunarg** [comment]
Hey @mikes-lunarg, is this still lying around someplace, or should I just make a new commit from the stuff in Github?

**Comment by mikes-lunarg** [comment]
There isn't any outstanding code for this, #496 is additional validation at vkCreateSwapchainKHR time.

This issue looks like an interaction between VK_KHR_swapchain_mutable_format and existing format checks.  We probably need to flag presentable images as mutable in PostCallRecordGetSwapchainImagesKHR so they don't get incorrectly validated when a view is created from them.

**Comment by mark-lunarg** [comment]
The validation appears to have been corrected, probably during the statetracker implementation-time.  Modified cube to create alternate-format imageviews of presentable images and noticed no unwarranted validation messages.  Closing for now, please reopen or comment further should problems persist.  Thanks!
