### ISSUE TITLE
VK_DBG_LAYER_ACTION_BREAK is not working

### ISSUE THREAD

**Issue by neobrain** [KhronosGroup/Vulkan-ValidationLayers#897]
Setting e.g. `lunarg_core_validation.debug_action = VK_DBG_LAYER_ACTION_BREAK` in `vk_layer_settings.txt` does not have the desired effect of triggering breakpoints upon validation errors. Instead, it will just ignore them.

While `layer_debug_report_actions` in vk_layer_utils.cpp has code to implement this feature, it's marked as deprecated and never gets called for me in practice. Its replacement (`layer_debug_messenger_actions`) does get called but doesn't handle the `debug_action & VK_DBG_LAYER_ACTION_BREAK` case.

Presumably, all that's needed to fix this issue is port c9d8165e4a7c1ef8632fa5a43b63e59deefa0463 to `layer_debug_messenger_actions`.

**Comment by neobrain** [comment]
Any updates on this issue? All that's needed to fix this is to copy the `debug_action & VK_DBG_LAYER_ACTION_BREAK` block introduced in c9d8165 to the `layer_debug_messenger_actions` function.

I'd submit a patch myself, but I'd rather not sign and keep track of a CLA just for such trivial changes.

**Comment by neobrain** [comment]
Thanks, this will help me out a lot! :)

**Comment by mark-lunarg** [comment]
@neobrain, just FFR, can you describe how you use this feature, how you learned of it, and how it helps?  I was not a little surprised that *anybody* was using it!

**Comment by neobrain** [comment]
@mark-lunarg It's a straightforward way of producing a stacktrace upon encountering a validation error, which I needed since it sometimes can be difficult to figure out which API call site a validation layer message actually refers to otherwise. It's been a while, but IIRC `VK_DBG_LAYER_ACTION_BREAK` is the only way to actually do this (other than manually setting a breakpoint on the validation message printer, which I'd have to look up every time).

I don't remember how I found out about it, but both https://vulkan-tutorial.com/Drawing_a_triangle/Setup/Validation_layers and https://gpuopen.com/using-the-vulkan-validation-layers/ (two well-ranked search results for "vulkan validation breakpoint") mention `vk_layer_settings.txt` as a means to configure the layers, and presumably when looking for further information I ran into `https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/vk_layer_settings.txt`.

**Comment by mark-lunarg** [comment]
@neobrain, thanks for your response.  This is all good information -- we're in a push to improve the validation workflow, and to make features like this more visible and useful.  If you have any more suggestions or ideas for improvement, please let us know!

**Comment by neobrain** [comment]
@mark-lunarg Happy to help! I'll let you know if any more suggestions come to mind :+1:
