### ISSUE TITLE
VkRenderPass validation suspicious inconsistency

### ISSUE THREAD

**Issue by Goshido** [KhronosGroup/Vulkan-ValidationLayers#8970]
**Environment:**
 - OS: _Android 11_
 - GPU and driver version: _GPU_: _Mali G76_, driver: _26.0.0_
 - SDK or header version if building from repo: _1.3.302_, _SHA-1_ `736e979cbb2579384ee420dc349de4611bdee3ee`
 - Options enabled (synchronization, best practices, etc.): `VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT` and `VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT`

**Describe the Issue**

`VkRenderPass` with 2 subpasses. First subpass - GBuffer fill, second subpass - additive lighting. All render targets become input attachments except _HDR_ accumulator. This only happens when subpass `1` (counting from 0) does not have any drawcalls. For example when all scene materials are emissive.

```txt
[ SYNC-HAZARD-WRITE-AFTER-WRITE ]
    name = Render session,
    type = VK_OBJECT_TYPE_RENDER_PASS;

vkCmdEndRenderPass():
Hazard WRITE_AFTER_WRITE
    in subpass 1
    for attachment 4 depth aspect
    during store
    with storeOp VK_ATTACHMENT_STORE_OP_DONT_CARE.

Access info
    (usage: SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE,
    prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION,

write_barriers:
    SYNC_FRAGMENT_SHADER_COLOR_ATTACHMENT_READ|
    SYNC_FRAGMENT_SHADER_INPUT_ATTACHMENT_READ|
    SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_READ|
    SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_WRITE

command: vkCmdNextSubpass)
```

![issue](https://github.com/user-attachments/assets/f8b883e8-5849-4fa5-af12-cfbe523133d4)

Error happens on first command buffer recording.

Same time there is no _VVL_ errors when subpass `1` is not empty:

![working](https://github.com/user-attachments/assets/7571e2a4-1270-48ee-841d-a2e423e7b2b4)

That's strange. Would you kindly help?

The full `VkRenderPass` initialization:

```cpp
#define AV_VK_FLAG(x) ( static_cast<uint32_t> ( x ) )

VkAttachmentDescription const attachments[]
{
    // #0: albedo
    {
        .flags = 0U,
        .format = _gBuffer.GetAlbedo ().GetFormat (),
        .samples = VK_SAMPLE_COUNT_1_BIT,
        .loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR,
        .storeOp = VK_ATTACHMENT_STORE_OP_DONT_CARE,
        .stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE,
        .stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE,
        .initialLayout = VK_IMAGE_LAYOUT_UNDEFINED,
        .finalLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL
    },

    // #1: emission
    {
        .flags = 0U,
        .format = _gBuffer.GetHDRAccumulator ().GetFormat (),
        .samples = VK_SAMPLE_COUNT_1_BIT,
        .loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR,
        .storeOp = VK_ATTACHMENT_STORE_OP_STORE,
        .stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE,
        .stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE,
        .initialLayout = VK_IMAGE_LAYOUT_UNDEFINED,
        .finalLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL
    },

    // #2: normal
    {
        .flags = 0U,
        .format = _gBuffer.GetNormal ().GetFormat (),
        .samples = VK_SAMPLE_COUNT_1_BIT,
        .loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR,
        .storeOp = VK_ATTACHMENT_STORE_OP_DONT_CARE,
        .stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE,
        .stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE,
        .initialLayout = VK_IMAGE_LAYOUT_UNDEFINED,
        .finalLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL
    },

    // #3: params
    {
        .flags = 0U,
        .format = _gBuffer.GetParams ().GetFormat (),
        .samples = VK_SAMPLE_COUNT_1_BIT,
        .loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR,
        .storeOp = VK_ATTACHMENT_STORE_OP_DONT_CARE,
        .stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE,
        .stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE,
        .initialLayout = VK_IMAGE_LAYOUT_UNDEFINED,
        .finalLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL
    },

    // #4: depth|stencil
    {
        .flags = 0U,
        .format = _gBuffer.GetDepthStencil ().GetFormat (),
        .samples = VK_SAMPLE_COUNT_1_BIT,
        .loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR,
        .storeOp = VK_ATTACHMENT_STORE_OP_DONT_CARE,
        .stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE,
        .stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE,
        .initialLayout = VK_IMAGE_LAYOUT_UNDEFINED,
        .finalLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL
    }
};

constexpr static VkAttachmentReference const geometryColorReferences[] =
{
    // #0: albedo
    {
        .attachment = 0U,
        .layout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL
    },

    // #1: emission
    {
        .attachment = 1U,
        .layout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL
    },

    // #2: normal
    {
        .attachment = 2U,
        .layout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL
    },

    // #3: params
    {
        .attachment = 3U,
        .layout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL
    }
};

// depth|stencil
constexpr static VkAttachmentReference geometryDepthStencilReference
{
    .attachment = 4U,
    .layout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL
};

constexpr static VkAttachmentReference const lightColorReferences[] =
{
    // #1: HDR accumulator
    {
        .attachment = 1U,
        .layout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL
    }
};

constexpr static VkAttachmentReference const lightInputAttachments[] =
{
    // #0: albedo
    {
        .attachment = 0U,
        .layout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL
    },

    // #2: normal
    {
        .attachment = 2U,
        .layout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL
    },

    // #3: params
    {
        .attachment = 3U,
        .layout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL
    },

    // #4: depth
    {
        .attachment = 4U,
        .layout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL
    }
};

constexpr VkSubpassDescription const subpasses[] =
{
    {
        .flags = 0U,
        .pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS,
        .inputAttachmentCount = 0U,
        .pInputAttachments = nullptr,
        .colorAttachmentCount = static_cast<uint32_t> ( std::size ( geometryColorReferences ) ),
        .pColorAttachments = geometryColorReferences,
        .pResolveAttachments = nullptr,
        .pDepthStencilAttachment = &geometryDepthStencilReference,
        .preserveAttachmentCount = 0U,
        .pPreserveAttachments = nullptr
    },
    {
        .flags = 0U,
        .pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS,
        .inputAttachmentCount = static_cast<uint32_t> ( std::size ( lightInputAttachments ) ),
        .pInputAttachments = lightInputAttachments,
        .colorAttachmentCount = static_cast<uint32_t> ( std::size ( lightColorReferences ) ),
        .pColorAttachments = lightColorReferences,
        .pResolveAttachments = nullptr,
        .pDepthStencilAttachment = nullptr,
        .preserveAttachmentCount = 0U,
        .pPreserveAttachments = nullptr
    }
};

constexpr VkSubpassDependency const dependencies[] =
{
    {
        .srcSubpass = VK_SUBPASS_EXTERNAL,
        .dstSubpass = 0U,

        .srcStageMask = AV_VK_FLAG ( VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT ) |
            AV_VK_FLAG ( VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT ),

        .dstStageMask = AV_VK_FLAG ( VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT ) |
            AV_VK_FLAG ( VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT ),

        .srcAccessMask = AV_VK_FLAG ( VK_ACCESS_SHADER_READ_BIT ) |
            AV_VK_FLAG ( VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT ),

        .dstAccessMask = AV_VK_FLAG ( VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT ) |
            AV_VK_FLAG ( VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT ),

        .dependencyFlags = VK_DEPENDENCY_BY_REGION_BIT
    },
    {
        .srcSubpass = 0U,
        .dstSubpass = 1U,

        .srcStageMask = AV_VK_FLAG ( VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT ) |
            AV_VK_FLAG ( VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT ),

        .dstStageMask = AV_VK_FLAG ( VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT ) |
            AV_VK_FLAG ( VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT ),

        .srcAccessMask = AV_VK_FLAG ( VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT ) |
            AV_VK_FLAG ( VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT ),

        .dstAccessMask = AV_VK_FLAG ( VK_ACCESS_INPUT_ATTACHMENT_READ_BIT ) |
            AV_VK_FLAG ( VK_ACCESS_COLOR_ATTACHMENT_READ_BIT ) |
            AV_VK_FLAG ( VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT ),

        .dependencyFlags = VK_DEPENDENCY_BY_REGION_BIT
    },
    {
        .srcSubpass = 1U,
        .dstSubpass = VK_SUBPASS_EXTERNAL,
        .srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
        .dstStageMask = VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
        .srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT,
        .dstAccessMask = VK_ACCESS_SHADER_READ_BIT,
        .dependencyFlags = VK_DEPENDENCY_BY_REGION_BIT
    }
};

VkRenderPassCreateInfo const renderPassInfo
{
    .sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO,
    .pNext = nullptr,
    .flags = 0U,
    .attachmentCount = static_cast<uint32_t> ( std::size ( attachments ) ),
    .pAttachments = attachments,
    .subpassCount = static_cast<uint32_t> ( std::size ( subpasses ) ),
    .pSubpasses = subpasses,
    .dependencyCount = static_cast<uint32_t> ( std::size ( dependencies ) ),
    .pDependencies = dependencies
};

bool const result = android_vulkan::Renderer::CheckVkResult (
    vkCreateRenderPass ( device, &renderPassInfo, nullptr, &_renderPassInfo.renderPass ),
    "pbr::RenderSession::CreateRenderPass",
    "Can't create render pass"
);

if ( !result ) [[unlikely]]
    return false;

AV_SET_VULKAN_OBJECT_NAME ( device, _renderPassInfo.renderPass, VK_OBJECT_TYPE_RENDER_PASS, "Render session" )
```

**Expected behavior**

No inconsistency or fix of the potential _VVL_ bug.

**Valid Usage ID**
_N/A_

**Comment by artem-lunarg** [comment]
@Goshido The error message says that depth image write operations that happens at the end of the second subpass (storeOp LOAD_OP_DONT_CARE is a potential write) races with depth image layout transition at the begin of the first subpass.

The error message needs improvement but there is one suggestion. It looks like the first (0) subpass dependency does not properly barrier depth image layout transition. The specification defines that by default:
`VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT |VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT` is used to protect the first subpass from depth image layout transition to initialLayout. Could you try in the first (0) subpass dependency to use this mask for depth for `dstAccessMask`  instead of just `VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT`?

**Comment by Goshido** [comment]
> The error message says that depth image write operations that happens at the end of the second subpass (storeOp LOAD_OP_DONT_CARE is a potential write) races with depth image layout transition at the begin of the first subpass.

I think it's protected by VK_SUBPASS_EXTERNAL → 0 subpass dependency:

```cpp
constexpr VkSubpassDependency const dependencies[] =
{
    {
        .srcSubpass = VK_SUBPASS_EXTERNAL,
        .dstSubpass = 0U,

        .srcStageMask = AV_VK_FLAG ( VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT ) |
            AV_VK_FLAG ( VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT ),               <---------------------

        .dstStageMask = AV_VK_FLAG ( VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT ) | <---------------------
            AV_VK_FLAG ( VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT ),

        .srcAccessMask = AV_VK_FLAG ( VK_ACCESS_SHADER_READ_BIT ) |
            AV_VK_FLAG ( VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT ),            <---------------------

        .dstAccessMask = AV_VK_FLAG ( VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT ) |
                AV_VK_FLAG ( VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT ),        <---------------------

        .dependencyFlags = VK_DEPENDENCY_BY_REGION_BIT
    },
```

> storeOp LOAD_OP_DONT_CARE is a potential write
I did not know that it's potential write.

>  The specification defines that implicit subpass dependency uses:
VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT |VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT to protect the first subpass from the depth image layout transition to initialLayout.
Problem is that I do not rely on implicit barriers and specify both barriers explicitly:

- VK_SUBPASS_EXTERNAL → 0
- 1 → VK_SUBPASS_EXTERNAL

>  Could you try in the first (0) subpass dependency to use this mask for dstAccessMask depth part instead of just VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT?

If made modification in 0 → 1 subpass dependency which made _VVL_ happy for both cases:

![image](https://github.com/user-attachments/assets/ae87a269-f1ac-41e7-ac50-96e68a02a0b3)

My mistake was that thinking that transition from depth attachment to input attachment is enough to protect depth on writes will be visible for input attachment. Am I right?

---

And it still can not explain why _VVL_ see incorrect sync only is subpass `1` is empty.

**Comment by artem-lunarg** [comment]
@Goshido Please ignore my previous message. `VK_ATTACHMENT_LOAD_OP_CLEAR` is a WRITE operation and it should be enough `VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT` to synchronize depth loadOp with layout transition (as specified in the first subpass depedency).

**Comment by artem-lunarg** [comment]
> I did not know that it's potential write.

Yes, according to Vulkan specification it's a write operation (can modify image somehow). I used the word "potential" with regard to real implementations, where we don't know how it's implemented, but correct Vulkan code should assume it's a write.

**Comment by artem-lunarg** [comment]
> My mistake was that thinking that transition from depth attachment to input attachment is enough to protect depth data will be visible for input attachment. Am I right?

So I initially missed that subpass 1 actually uses depth image and there is image layout transition between subpass 0 and 1 (from `VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL` to `VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL`). 
I was thinking storeOp conflicts with the initial layout transition and could not understand how it can happen 🤦. 

Having a layout transition between 0 and 1 (write operation) it makes sense this should be properly synchronized with subsequent operations.

**Comment by artem-lunarg** [comment]
If subpass 1 is empty and subpass dependency 1 does not specify DEPTH WRITEs on the dst side, then storeOp write races with the previous layout transition write. As was in the original error message.

**Comment by Goshido** [comment]
In my understanding `vkCmdBeginRenderPass`, `vkCmdNextSubpass` and `vkCmdEndRenderPass` are sync points for render pass system. So _VVL_ should produce same error no matter of drawcalls between that commands. Don't you think? I want to point that in cases above all three API have been called.

**Comment by artem-lunarg** [comment]
In general it's possible to synchronize with commands inside subpass too in some cases. One such cases when STORE_OP_NONE/LOAD_OP_NONE is used, but it's not this case. It's not clear yes why commands inside subpass affect result.

What is the purposes of VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT as the source stage in the subpass dependency 1?

**Comment by Goshido** [comment]
> ~~What is the purposes of VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT as the source stage in the subpass dependency 1?~~

I made experiment 😊. Without it VVL produces:

```txt
[ SYNC-HAZARD-WRITE-AFTER-WRITE ]
    Object 0: handle = 0x9a41ed000000167b,
    name = Render session,
    type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x5c0ec5d6 |
    
vkCmdNextSubpass(): Hazard WRITE_AFTER_WRITE
    in subpass 1
    for attachment 4 image
    layout transition (
        old_layout: VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
        new_layout: VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL).
Access info (
    usage: SYNC_IMAGE_LAYOUT_TRANSITION,
    prior_usage: SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE,
write_barriers: 0, command: vkCmdDrawIndexed,
debug_region: Geometry pass::Stipple geometry).
```

**Comment by artem-lunarg** [comment]
Well, I think I understand why there is no error message when there are draw commands in the subpass 1. Sorry, did not work with this recently and it takes time to refresh memory.

So, loadOp/storeOp operations happen only at the beginning of the first subpass and at the end of the last subpass correspondingly. It means it's possible to synchronize with them only at those points. There is no loadOp/storeOp between subpass 0 and 1. If there are draw commands inside subpass 1 then original subpass dependency that defines COLOR_OUTPUT/FRAGMENT stages synchronizes with corresponding draw operations and protects from the previous layout transition. When there are no draw commands then COLOR_OUTPUT/FRAGMENT stages in subpass dependency 1 have no effect and layout transition follows immediately by storeOp write and subpass dependency can't synchronize them (according to original subpass dependency it can sync only with draw commands).

**Comment by Goshido** [comment]
Wow. just wow. Is it defined in the spec? Or it's safe to assume from _VVL_ side heuristics?

**Comment by artem-lunarg** [comment]
> Wow! Just wow! Is it defined in the spec?

Which part exactly? :) It should be all according to spec until I made mistake.

**Comment by Goshido** [comment]
I did not know that drawcalls affects layout transition because they actually **triggers** pipeline stage rotations.

**Comment by artem-lunarg** [comment]
> I did not know that drawcalls affects layout transition because they actually trigger pipeline stage rotations! Well I think VVL is absolutely correct and issue should be closed.

Probably one thing to remember that layout transition is a write operation. If it interfaces with loadOp/storeOp then we need to sync with accesses defined for these ops, otherwise we need to figure out which accesses are performed by subpass and sync with them.
