### ISSUE TITLE
Error if trying to use an access mask with pipeline stages that can't perform it

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#9]
**Issue by [ghost](https://github.com/ghost) (MIGRATED)**
_Monday Oct 03, 2016 at 10:25 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1006_

----

Certain pipeline stages can only perform a subset of the memory access operations that can be specified in the src/dstAccessMask of a Vk*MemoryBarrier structure. As an obvious example, "TOP_OF_PIPE" and "BOTTOM_OF_PIPE" do not perform _any_ memory accesses.

Specifying a type of access with a stage that can't perform it will result in a no-op. I've seen a couple of apps attempting to use TOP/BOTTOM with memory accesses, which will not work. It would be nice to warn users that this is a no-op, as there's a higher-than-zero chance they're doing something they didn't intend to (or they are doing nothing and expecting something).

All stages other than "ALL_COMMANDS" and "ALL_GRAPHICS_COMMANDS" are affected by this. For instance, "DRAW_INDIRECT_BIT" will only ever perform accesses of type "VK_ACCESS_INDIRECT_COMMAND_READ_BIT", and no other stage will perform accesses of that type.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/karl-lunarg"><img src="https://avatars2.githubusercontent.com/u/16430219?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [karl-lunarg](https://github.com/karl-lunarg) (MIGRATED)**
_Thursday Oct 06, 2016 at 17:38 GMT_

----

Michael, can you consider implementing this, since you judged it to be a P1?

**Comment by karl-lunarg** [comment]
<a href="https://github.com/lentinem"><img src="https://avatars3.githubusercontent.com/u/9709345?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lentinem](https://github.com/lentinem) (MIGRATED)**
_Thursday Oct 06, 2016 at 17:42 GMT_

----

Sure; I should be able to get to it in a few days.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/ghost"><img src="https://avatars3.githubusercontent.com/u/10137?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ghost](https://github.com/ghost) (MIGRATED)**
_Thursday Oct 13, 2016 at 10:31 GMT_

----

@lentinem Just a heads up, this _might_ actually be invalid behaviour (i.e. worthy of an error, rather than a warning). We're discussing this in the WG and should hopefully have an answer early next week. I'm hoping it's not hard to switch something from a warning to an error?

**Comment by karl-lunarg** [comment]
<a href="https://github.com/lentinem"><img src="https://avatars3.githubusercontent.com/u/9709345?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lentinem](https://github.com/lentinem) (MIGRATED)**
_Thursday Oct 13, 2016 at 16:13 GMT_

----

Yes; just a different define passed into the log function.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/ghost"><img src="https://avatars3.githubusercontent.com/u/10137?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ghost](https://github.com/ghost) (MIGRATED)**
_Tuesday Oct 18, 2016 at 10:15 GMT_

----

The WG decided to make this invalid behaviour. Spec hasn't been updated to reflect that yet though, and it'll take at least a couple of weeks until it is. Any preference for how to handle this process-wise? I'd be fine with just making it an error now if that's easier, but we then may have to fend off some issues asking why it's now invalid in the interim...

**Comment by karl-lunarg** [comment]
<a href="https://github.com/tobine"><img src="https://avatars0.githubusercontent.com/u/7526739?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tobine](https://github.com/tobine) (MIGRATED)**
_Tuesday Oct 18, 2016 at 14:08 GMT_

----

Should be fine to just make it an error now on master branch as most developers run from SDK version of layers and I suspect SDK won't be updated for at least a few weeks.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/ghost"><img src="https://avatars3.githubusercontent.com/u/10137?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ghost](https://github.com/ghost) (MIGRATED)**
_Tuesday Jan 24, 2017 at 19:22 GMT_

----

Apparently I forgot to ever update this bug; sorry about that! The spec change to make this an error did happen a while ago now - see the paragraph before Table 6.2 "supported access types" in the "Access Types" section of the Synchronization chapter.

**Comment by jzulauf-lunarg** [comment]
Triage notes:  The specific language in 6.1.3. Access Types (as of 1.1.95)
 
> An application must not specify an access flag in a synchronization command if it does not include a pipeline stage in the corresponding stage mask that is able to perform accesses of that type.

Table 4. does not exist in a machine readable for code generation.  A script that generates a map or access bit to stage mask is attached.

**Comment by jzulauf-lunarg** [comment]
[legal_access_map.py.gz](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/2678009/legal_access_map.py.gz)

**Comment by mark-lunarg** [comment]
This was implemented by @tobine in commit 6493f135497.
