### ISSUE TITLE
Code-Gen all implicit VUs

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#90]
**Issue by [mark-lunarg](https://github.com/mark-lunarg) (MIGRATED)**
_Friday May 04, 2018 at 18:26 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2646_

----

There are ~700 implicit VU checks that remain unimplemented or at least unidentified in the database.  These need to be covered by PV and OT codegen.

Many if not most of these look to consist of validating elements of extension structs that only exist in pNext chains.  

This is important since new extension validation requires COMPLETE-level validation, and these checks should all be performed automatically.

**Comment by mark-lunarg** [comment]
The main body of these messages has been covered, and the remaining messages are easily identifiable through the vk_validation_stats python script.
