### ISSUE TITLE
Divide by zero crash validating single-draw vkCmdDrawMeshTasksIndirectEXT

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-ValidationLayers#9014]
**Environment:**
 - OS: Windows 11
 - GPU and driver version: AMD 7900 XTX driver 24.10.1
 - SDK or header version if building from repo: Built from b10d21aa975d5cf4ecf4d8d3c7ba4610e151bce6
 - Options enabled (synchronization, best practices, etc.): GPU validation & synchronization

**Describe the Issue**

If calling `vkCmdDrawMeshTasksIndirectEXT` (possibly others, but this was where it crashed for me) with `drawCount == 1` the spec says `stride` is ignored, but on this line:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/07e3442eac85dc9a1984ba057c849d492fe8b974/layers/gpu/cmd_validation/gpuav_draw.cpp#L657

There's an unconditional divide by stride, I believe it's to clamp the draw count if he draws read out of bounds. In the event that stride is set to 0 this causes a crash.

**Expected behavior**

When calling an indirect draw with count of 1 stride is not required to be non-zero so this should be ignored.

**Valid Usage ID**
N/A

**Additional context**
Adding a simple `drawCount > 1` to the check worked for me, though I'm assuming there's earlier validation that stride is properly set when requried.

**Comment by spencer-lunarg** [comment]
Thanks for catching this (we literately just merged this change in this week)

We will get some mesh tests (and other things that use`drawCount`) in for this

**Comment by arno-lunarg** [comment]
Thank you for spotting that! Especially since the error spat at me when testing that was awful, and the debugger would not even break ...

**Comment by spencer-lunarg** [comment]
Keeping open until we add tests for `vkCmdDrawIndirect` and `vkCmdDrawIndexedIndirect` to confirm they aren't broken as well
