### ISSUE TITLE
Updating COMBINED_IMAGE_SAMPLER descriptors crashes; accesses invalid pNext chain

### ISSUE THREAD

**Issue by doitsujin** [KhronosGroup/Vulkan-ValidationLayers#905]
Hello,

as of 1.1.106, the validation layers crash for me when updating combined image-sampler descriptors if the participating image view was created with a `pNext` chain. The problem seems to be in the following code:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/ff7ebed5ab983c7019cddf0046261b9cd0f5017c/layers/descriptor_sets.cpp#L2227-L2229

Specifically, `iv_state->create_info.pNext` does not point to a valid `pNext` chain as it still contains the application-provided pointer from when `vkCreateImageView` was called.

Pinging @Joshua-Ashton who found this issue.

**Comment by Plagman** [comment]
@MarkY-LunarG Seems serious, can this be looked into soon?

**Comment by mark-lunarg** [comment]
Sure, I'll get on it first thing.  Thanks!

**Comment by locke-lunarg** [comment]
[PR #912 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/912)

**Comment by jzulauf-lunarg** [comment]
fixed by merged PR . Thanks to @Joshua-Ashton and @doitsujin  for such a clear, specific bug report.

**Comment by Joshua-Ashton** [comment]
Thanks for the fix! Much appreciated :)
