### ISSUE TITLE
Android, PowerVR Rogue GM9446:  Incorrect check VkPhysicalDeviceMultiviewProperties::maxMultiviewInstanceIndex for Vulkan 1.1.131 device

### ISSUE THREAD

**Issue by Andreyogld3d** [KhronosGroup/Vulkan-ValidationLayers#9090]
**Environment:**
 - OS: Android 13
 - GPU and driver version:PowerVR Rogue GM9446 driverVersion 1.386.1368
 - SDK or header version if building from repo: repo commit 2897317be9f49fbca8d1e14d87fb08b56023b5ed
 - Options enabled (synchronization, best practices, etc.): Android build, using default options

**Describe the Issue**

PowerVR Rogue has Vulkan 1.1.131 version, supports [VK_KHR_multiview](https://registry.khronos.org/vulkan/specs/latest/man/html/VK_KHR_multiview.html) extension, and has 
[VkPhysicalDeviceMultiviewProperties::maxMultiviewViewCount > 0](https://registry.khronos.org/vulkan/specs/latest/man/html/VkPhysicalDeviceMultiviewProperties.html), 
[VkPhysicalDeviceMultiviewProperties::maxMultiviewInstanceIndex > 0](https://registry.khronos.org/vulkan/specs/latest/man/html/VkPhysicalDeviceMultiviewProperties.html)

Steps to reproduce:

1. Use [VkPhysicalDeviceMultiviewFeatures ](https://registry.khronos.org/vulkan/specs/latest/man/html/VkPhysicalDeviceMultiviewFeatures.html) for [VkDeviceCreateInfo](https://registry.khronos.org/vulkan/specs/latest/man/html/VkDeviceCreateInfo.html).  
 VkPhysicalDeviceMultiviewFeatures::multiview == VK_TRUE, accrording specification:
[If the VkPhysicalDeviceMultiviewFeatures structure is included in the pNext chain of the VkPhysicalDeviceFeatures2 structure passed to vkGetPhysicalDeviceFeatures2, it is filled in to indicate whether each corresponding feature is supported. ](https://registry.khronos.org/vulkan/specs/latest/man/html/VkPhysicalDeviceMultiviewFeatures.html)
 2. Draw some geometry void vkCmdDrawIndexed(, ,1, 0, 0, 1);

 I have error:

[ VUID-vkCmdDrawIndexed-maxMultiviewInstanceIndex-02688 ] Object 0: handle = 0xb400007d7ebf2800, name = RT0_CommandBuffer_0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0xdd1b7300000003cf, name = ShadowMapAlphaPSO50, type = VK_OBJECT_TYPE_PIPELINE; Object 2: handle = 0x3b715500000000c5, name = RenderPass4, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0xcbc65162 | vkCmdDrawIndexed(): renderpass instance has multiview enabled, and maxMultiviewInstanceIndex: 0, but instanceCount: 1and firstInstance: 0.
The Vulkan spec states: If the draw is recorded in a render pass instance with multiview enabled, the maximum instance index must be less than or equal to VkPhysicalDeviceMultiviewProperties::maxMultiviewInstanceIndex (https://docs.vulkan.org/spec/latest/chapters/drawing.html#VUID-vkCmdDrawIndexed-maxMultiviewInstanceIndex-02688) Code -876195486

**Expected behavior**

No Validation error for Vulkan 1.1.xx with supports [VK_KHR_multiview](https://registry.khronos.org/vulkan/specs/latest/man/html/VK_KHR_multiview.html), enabled [VkPhysicalDeviceMultiviewFeatures::multiview](https://registry.khronos.org/vulkan/specs/latest/man/html/VkPhysicalDeviceMultiviewFeatures.html) and [VkPhysicalDeviceMultiviewProperties::maxMultiviewInstanceIndex > 0](https://registry.khronos.org/vulkan/specs/latest/man/html/VkPhysicalDeviceMultiviewProperties.html),
[VkPhysicalDeviceMultiviewProperties::maxMultiviewViewCount > 0](https://registry.khronos.org/vulkan/specs/latest/man/html/VkPhysicalDeviceMultiviewProperties.html)

**Valid Usage ID**
https://docs.vulkan.org/spec/latest/chapters/drawing.html#VUID-vkCmdDrawIndexed-maxMultiviewInstanceIndex-02688

**Additional context**

Accrording source code, this error happens [there](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/layers/core_checks/cc_drawdispatch.cpp#L54)

I think we have incorect setup of [phys_dev_props_core11](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/layers/state_tracker/state_tracker.h#L1794) in this [code](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/layers/state_tracker/state_tracker.cpp#L766-L780)

PowerVR Rogue GM4646 https://vulkan.gpuinfo.org/displayreport.php?id=21556

</details>

**Comment by ziga-lunarg** [comment]
Thanks for the detailed report, I tried loading a profile in the gpuinfo.org report you provided and it seems to work correctly for me. 

> I think we have incorect setup of [phys_dev_props_core11](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/layers/state_tracker/state_tracker.h#L1794) in this [code](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/layers/state_tracker/state_tracker.cpp#L766-L780)

In the state_tracker.cpp, in your case `maxMultiviewInstanceIndex` should be written in line 779, do you not get there?

**Comment by Andreyogld3d** [comment]
Hi @ziga-lunarg, thank for your answer

> I tried loading a profile in the gpuinfo.org report you provided and it seems to work correctly for me.

May be need to do debug on real Android device ? During Debuging using Android Studio, I have [VkPhysicalDeviceMultiviewProperties::maxMultiviewInstanceIndex  > 0](https://registry.khronos.org/vulkan/specs/latest/man/html/VkPhysicalDeviceMultiviewProperties.html)

>In the state_tracker.cpp, in your case maxMultiviewInstanceIndex should be written in line 779, do you not get there?

I have just researched VVL code, without debugging

**Comment by ziga-lunarg** [comment]
I ran a test on android and I'm still not seeing how those values would not be set. Can you confirm that you enable the VK_KHR_multiview extension or use VK_API_VERSION_1_1?

**Comment by Andreyogld3d** [comment]
I have result after debugging VVL. I use the following code:

```
    const std::array str_enabled = {
"kNotEnabled", "kEnabledByCreateinfo", "kEnabledByApiLevel", "kEnabledByInteraction"};
    __android_log_print(ANDROID_LOG_INFO, "VVL_DEBUG", 
"dev_ext.vk_feature_version_1_2: %s\n", str_enabled[dev_ext.vk_feature_version_1_2]);
...
    if (dev_ext.vk_feature_version_1_2) {
          GetPhysicalDeviceExtProperties(physical_device, dev_ext.vk_feature_version_1_2, &phys_dev_props_core11);
        GetPhysicalDeviceExtProperties(physical_device, dev_ext.vk_feature_version_1_2, &phys_dev_props_core12);
    } else {
  
        __android_log_print(ANDROID_LOG_INFO, "VVL_DEBUG", "dev_ext.vk_khr_multiview %s\n", 
dev_ext.vk_khr_multiview ? "true" : "false");

        if (dev_ext.vk_khr_multiview) {
            VkPhysicalDeviceMultiviewProperties multiview_props = vku::InitStructHelper();
            GetPhysicalDeviceExtProperties(physical_device, dev_ext.vk_khr_multiview, &multiview_props);
            __android_log_print(ANDROID_LOG_INFO, "VVL_DEBUG", "phys_dev_props_core11::maxMultiviewViewCount %d phys_dev_props_core11.maxMultiviewInstanceIndex %d\n", phys_dev_props_core11.maxMultiviewViewCount, phys_dev_props_core11.maxMultiviewInstanceIndex);
            phys_dev_props_core11.maxMultiviewViewCount = multiview_props.maxMultiviewViewCount;
            phys_dev_props_core11.maxMultiviewInstanceIndex = multiview_props.maxMultiviewInstanceIndex;
        }

```
Android Studio Debug output:

2024-12-26 21:25:54.709 20379-31449 VVL_DEBUG               androidvulkan.androidvulkan          I  **dev_ext.vk_feature_version_1_2: kEnabledByCreateinfo**

So, phys_dev_props_core11.maxMultiviewViewCount and  phys_dev_props_core11.maxMultiviewInstanceIndex has zero value.

**Comment by ziga-lunarg** [comment]
Thanks for debugging. But I am confused by `dev_ext.vk_feature_version_1_2: kEnabledByCreateinfo`.

Your device only supports 1.1 if I read that correctly. Do you use api version 1.1 or higher? 

And if `dev_ext.vk_feature_version_1_2` is indeed enabled, then the first if will be true and `GetPhysicalDeviceExtProperties(physical_device, dev_ext.vk_feature_version_1_2, &phys_dev_props_core11);` will be called, which should fill out `VkPhysicalDeviceVulkan11Properties::maxMultiviewInstanceIndex`.

**Comment by Andreyogld3d** [comment]
>But I am confused by dev_ext.vk_feature_version_1_2: kEnabledByCreateinfo.

Yes, it is very strange :(

>Your device only supports 1.1 if I read that correctly. Do you use api version 1.1 or higher?

Yes, Vulkan 1.1 and API 1.1, I can't use more than 1.1 :)

I suggest the following fix

This code 
```
    if (dev_ext.vk_khr_multiview || enabled_features.multiview) {
        phys_dev_props_core11.maxMultiviewViewCount = phys_dev_props->multiview_props.maxMultiviewViewCount;
        phys_dev_props_core11.maxMultiviewInstanceIndex = phys_dev_props->multiview_props.maxMultiviewInstanceIndex;
    }

```
insert [there ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/layers/state_tracker/state_tracker.cpp#L1118)

It fix problem, but what about  dev_ext.vk_feature_version_1_2 != kNotEnabled ?? ....

**Comment by Andreyogld3d** [comment]
>And if dev_ext.vk_feature_version_1_2 is indeed enabled, then the first if will be true and GetPhysicalDeviceExtProperties(physical_device, dev_ext.vk_feature_version_1_2, &phys_dev_props_core11); will be called, which should fill out VkPhysicalDeviceVulkan11Properties::maxMultiviewInstanceIndex.

incorrect   code
```
template <bool init = true, typename ExtProp>
void GetPhysicalDeviceExtProperties(VkPhysicalDevice gpu, ExtEnabled enabled, ExtProp* ext_prop) {

```
for ExtProp == VkPhysicalDeviceMultiviewProperties ?

**Comment by ziga-lunarg** [comment]
The fix you suggested should not be needed.

Currently if you api version is 1.2 or greater, then `dev_ext.vk_feature_version_1_2` should be `kEnabledByCreateinfo` and state_tracker.cpp:766 will be true and `phys_dev_props_core11` will be filled in, in line 768.

But in your case when api version is 1.1, the `dev_ext.vk_feature_version_1_2` should be `kNotEnabled` so you get to line 775, where `dev_ext.vk_khr_multiview` should be `kEnabledByApiLevel` and `phys_dev_props_core11.maxMultiviewInstanceIndex` will be written to in line 779

**Comment by Andreyogld3d** [comment]
Ok, I will debug, why ev_ext.vk_feature_version_1_2 != kNotEnabled 
Where dev_ext.vk_feature_version_1_2 will be initilized ?

**Comment by ziga-lunarg** [comment]
In vk_extension_helper.cpp:612, you should look at `this->vk_feature_version_1_2`

**Comment by Andreyogld3d** [comment]
Hi @ziga-lunarg,  
```
        if (api_version >= version_it.first) {
            const std::array str_enabled = {"kNotEnabled", "kEnabledByCreateinfo", "kEnabledByApiLevel", "kEnabledByInteraction"};
        	__android_log_print(ANDROID_LOG_INFO, "VVL_DEBUG", "this->vk_feature_version_1_2: %s requested_api_version %d\n", str_enabled[this->vk_feature_version_1_2], requested_api_version.Value());
            if (info.state) this->*(info.state) = kEnabledByCreateinfo;
...
}
```
this->vk_feature_version_1_2: kNotEnabled requested_api_version 4206592 api_version 4206592
this->vk_feature_version_1_2: kNotEnabled requested_api_version 4206592 api_version 4206592
this->vk_feature_version_1_2: kEnabledByCreateinfo requested_api_version 4206592 api_version 4206592
this->vk_feature_version_1_2: kNotEnabled requested_api_version 4198531 api_version 4198400
this->vk_feature_version_1_2: kNotEnabled requested_api_version 4206592 api_version 4206592
this->vk_feature_version_1_2: kNotEnabled requested_api_version 4206592 api_version 4206592
this->vk_feature_version_1_2: kEnabledByCreateinfo requested_api_version 4206592 api_version 4206592

4206592 - 1.3.0 for VkInstance, PowerVR Rogue support **1.3.0 for VkInstance**
4198531 - 1.1.131 for VkDevice == 4198400(VK_API_VERSION_1_1) , 

I think problem with different Versions for VkDevice and VkInstance, for example I have no problem with others Vulkan Devices:

Mali G57 - VkInstance 1.1.0 VkDevice 1.1.131
Adreno 660 VkInstance 1.1.0 VkDevice 1.1.128

**Comment by ziga-lunarg** [comment]
Thanks for looking into this. I think I finally understand what is going on.

In `layers/chassis/chassis_manual.cpp` line 332 is:
`&instance_dispatch->instance_extensions, instance_dispatch->api_version,`

If you replace `instance_dispatch->api_version` with `device_dispatch->api_version` does the error go away?

**Comment by Andreyogld3d** [comment]
Yes, It works, I see no any error message!

Also, other invalid message has been fixed:

[ VUID-VkPipelineLayoutCreateInfo-descriptorType-03024 ] | MessageID = 0xeb2bfadc | vkCreatePipelineLayout(): max per-stage storage buffer bindings count (4) exceeds device maxPerStageDescriptorUpdateAfterBindStorageBuffers limit (0).
                                                                                                    The Vulkan spec states: The total number of descriptors with a descriptorType of VK_DESCRIPTOR_TYPE_STORAGE_BUFFER and VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC accessible to any given shader stage across all elements of pSetLayouts must be less than or equal to VkPhysicalDeviceDescriptorIndexingProperties::maxPerStageDescriptorUpdateAfterBindStorageBuffers (https://docs.vulkan.org/spec/latest/chapters/descriptorsets.html#VUID-VkPipelineLayoutCreateInfo-descriptorType-03024) Code -349439268

I can't use VK_EXT_descriptor_indices - because I have no this extension or 1.2 and more VkDevice, I think we have the same problem VkInstance 1.3.0

Thank you!

**Comment by ziga-lunarg** [comment]
Thanks for verifying! I will try to push and merge a fix to the main branch
