### ISSUE TITLE
Add validation support for VK_ANDROID_external_memory_android_hardware_buffer

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#91]
**Issue by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Friday May 04, 2018 at 19:47 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2648_

----

**Comment by daveh-lunarg** [comment]
Done, PR #407 & #542
