### ISSUE TITLE
Improve some DescriptorSet validation messages

### ISSUE THREAD

**Issue by mark-lunarg** [KhronosGroup/Vulkan-ValidationLayers#922]
From [LunarXchange issue #855](https://vulkan.lunarg.com/issue/view/5cdae0d3670a051a7d6377e5#issue/assign/5cdae0d3670a051a7d6377e5/552f13ef7ef24d0001000008):

VkDebugUtilsMessengerCallbackDataEXT::pObjects could have a lot more information; in my case, I have this validation error:

[Error:Validation(VUID-VkWriteDescriptorSet-descriptorType-01403)] vkUpdateDescriptorSets() failed write update validation for Descriptor Set 0xa0c with error: Write update to VkDescriptorSet 0xa0c allocated with VkDescriptorSetLayout 0xa06 binding #3 failed with error message: Attempted write update to combined image sampler descriptor failed due to: Descriptor update with descriptorType VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER is being updated with invalid imageLayout VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL. Allowed layouts are: VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, VK_IMAGE_LAYOUT_GENERAL, VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL, VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL. The Vulkan spec states: If descriptorType is VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE or VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, the imageLayout member of each element of pImageInfo must be a member of the list given in Sampled Image or Combined Image Sampler, corresponding to its type (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkWriteDescriptorSet-descriptorType-01403)

It could show the image & imageview in the message, as well as I already have a VkDebugUtilsObjectNameInfoEXT for the specified image, that would greatly improve debugging (the validation code already has to find which image it's on the write descriptor set to find the layout).

**Comment by RCalocaO** [comment]
Pinging on this :) without it need to work with/find text on ~3,000,000 lines vk_apidump.txt file and most text editors are not great with those!

**Comment by mark-lunarg** [comment]
OK Rolando, it's your lucky day -- I believe we've plumbed through the objectnames, but I'll confirm that and see about getting the image and imageview into the message as well, right away,

**Comment by mark-lunarg** [comment]
@RCalocaO, updated this error message, and plumbed the new ObjectNameInfo outputs through to all objects output by the descriptor_sets.cpp file, which had been missing them (!).  If there are any other messages we can improve, please open a new issue.
