### ISSUE TITLE
ValidateComputeWorkGroupInvocations checks the total count of invocations 

### ISSUE THREAD

**Issue by Ealrann** [KhronosGroup/Vulkan-ValidationLayers#923]
Hello,

After an update of the vulkan validation layers  (1.1.107), a new error appears in my code:

```ERROR OCCURED:  [ UNASSIGNED-features-limits-maxComputeWorkGroupInvocations ] Object: 0x5 (Type = 15) | ShaderMdoule 0x5 invocations (486400) exceeds device limit maxComputeWorkGroupInvocations (896).```

I searched a bit from the spec and from the validation code, and if my understanding is correct, I think there is a problem in the validation code.
The [ValidateComputeWorkGroupInvocations function](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/4fee64083dc3c1f70d0c68d20c83abc590092e3b/layers/shader_validation.cpp#L2978) compare the `maxComputeWorkGroupInvocations` to the product:
`local_size_x * local_size_y * local_size_z * groupCountX * groupCountY * groupCountZ`

But the vulkan spec say that : 

> maxComputeWorkGroupInvocations is the maximum total number of compute shader **invocations in a single local workgroup**. The product of the X, Y, and Z sizes as specified by the LocalSize execution mode in shader modules and by the object decorated by the WorkgroupSize decoration must be less than or equal to this limit.

So the maxComputeWorkGroupInvocations should only be compared to:
`local_size_x * local_size_y * local_size_z`

There is too a minor typo mistake few times in this source file: "ShaderM**dou**le"

**Comment by jzulauf-lunarg** [comment]
I read the spec the same way you do.  But the text is confusing

> The product of the X, Y, and Z sizes as specified by the LocalSize execution mode in shader modules and by the object decorated by the WorkgroupSize decoration

makes it sound like a product of the two, but should probably read 

> The product of the X, Y, and Z sizes as specified by the LocalSize execution mode in shader modules *or* by the object decorated by the WorkgroupSize decoration

Mirroring earlier text:

> workgroups ... size ... can be set by assigning a value to the LocalSize execution mode or via an object decorated by the WorkgroupSize decoration.

I'll open a spec bug to clarify.

@mikes-lunarg ... yes?

**Comment by mark-lunarg** [comment]
Fixed by #927.
