### ISSUE TITLE
Valid Usage of pMultisampleState->rasterizationSamples when having rasterizerDiscardEnable = VK_TRUE

### ISSUE THREAD

**Issue by Destranix** [KhronosGroup/Vulkan-ValidationLayers#930]
Situation:
In one subpass, which uses several multisample attachments, I'm using several GraphicsPipelines. One having rasterizerDiscardEnable = VK_FALSE and one having rasterizerDiscardEnable = VK_TRUE.

For both createInfos of those pipelines the same MultisampleStateCreateInfo is passed with rasterizationSamples equal those of the attachments.

When creating the GraphicsPipelines the validation layer stats:
`vkCreateGraphicsPipelines: pCreateInfo[26].pMultisampleState->rasterizationSamples (1) does not match the number of samples of the RenderPass color and/or depth attachment. The Vulkan spec states: If neither the VK_AMD_mixed_attachment_samples nor the VK_NV_framebuffer_mixed_samples extensions are enabled, and if subpass uses color and/or depth/stencil attachments, then the rasterizationSamples member of pMultisampleState must be the same as the sample count for those subpass attachments (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-subpass-00757)`

for every of those pipelines with rasterizerDiscardEnable = VK_TRUE;

I could not find anything in the specification, that stats, that rasterizationSamples must be the same for pipelines with rasterizerDiscardEnabled = VK_TRUE (More concrete: Specification does not stat, that pMultisampleState must be a valid pointer when having rasterizerDiscardEnable = VK_TRUE) and even if, I passed it anyway.

Is there something I overlooked or is there possibly something wrong with the validationlayer?

**Comment by mark-lunarg** [comment]
@Destranix, I don't see in the spec where an exception is specifically called out for the mismatch, but the spec does say `pMultisampleState is a pointer to an instance of the VkPipelineMultisampleStateCreateInfo, and is ignored if the pipeline has rasterization disabled`. I supposed it then follows that if this createinfo is ignored when DiscardEnable = TRUE, we shouldn't be validating against its content.

**Comment by Destranix** [comment]
Thank you!

**Comment by locke-lunarg** [comment]
Fixed [`issue #1099 `](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1099)
