### ISSUE TITLE
Perf warning when preTransform doesn't match currentTransform

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-ValidationLayers#934]
Under vkCreateSwapchainKHR call, for the VkSwapchainCreateInfoKHR struct, the spec states:

> • preTransform is a VkSurfaceTransformFlagBitsKHR value describing the transform, relative to
the presentation engine’s natural orientation, applied to the image content prior to
presentation. If it does not match the currentTransform value returned by
vkGetPhysicalDeviceSurfaceCapabilitiesKHR, the presentation engine will transform the image
content as part of the presentation operation

For the case when preTransform does not match currentTransform, I would like to have a PERFORMANCE_WARNING flagged. The performance impact of having the presentation engine do the transform can be big on Android so it would be best for devs to get some indication of this issue from running standard validation.

**Comment by locke-lunarg** [comment]
Fixed in [PR #1019](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1019)
