### ISSUE TITLE
Suggest changing error message verbiage pertaining to "X before calling Y" when getting data

### ISSUE THREAD

**Issue by awr1** [KhronosGroup/Vulkan-ValidationLayers#936]
In Vulkan, you have the common idiom of getting multiple items via calling `vkGetXYZ()` with a count variable pointer, making a dynamic array based on the count, and then calling that same function pointing to your new array.

In the validation layers, you can get errors like this:

```
vkCreateSwapchainKHR() called before calling vkGetPhysicalDeviceSurfaceFormatsKHR()
```

but the meaning of *"called"* here is not technically correct. One can call ` vkGetPhysicalDeviceSurfaceFormatsKHR()` getting the count only, and claim to have "called" this function, which makes the error message confusing. I had come across this error when I had realized I was calling  `vkGetPhysicalDeviceSurfaceFormatsKHR()` twice with the same arguments and forgetting to fill the array I had allocated, and I found myself initially not understanding the message - clearly, I was "calling it" before in the code!

I think "acquiring data from" or "getting item(s) from" might be a better phrase than merely just "calling".

**Comment by tobine** [comment]
@awr1 Yes, I agree, a minor but helpful distinction. Are you up for creating the PR?

**Comment by awr1** [comment]
@tobine sure, I'll see if I can work it on it later today.
