### ISSUE TITLE
VK_EXT_debug_utils - missing object names in cases where they could be added

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#94]
**Issue by [danginsburg](https://github.com/danginsburg) (MIGRATED)**
_Tuesday May 08, 2018 at 16:41 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2654_

----

I've hooked up my engine to VK_EXT_debug_utils.  For a while I have been using debug_marker extension with Renderdoc to name resources including images, buffers, and shader modules.  I noticed after hooking up to VK_EXT_debug_utils that there are cases where object names could easily be provided for shader modules, but are not done.  For example:

```
VK WARNING : VALIDATION - Message Id Number: 2 | Message Id Name: none
	fragment shader writes to output location 0 with no matching attachment

	Objects - 1
		Object[0] - VK_OBJECT_TYPE_UNKNOWN, Handle 0000000000000000
```

Looking at where these messages originate in shader_validation.cpp, it is because it is doing log_msg with VK_DEBUG_REPORT_OBJECT_TYPE_UNKNOWN_EXT and null object even though it knows the VkShaderModule at the point of finding the error.

The request here is to provide the VkShaderModule object so the name gets passed through.  

In general, I would request that if it hasn't been done already that there is an audit of log_msg's to make sure they pass in the known object so the application can get the name.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/MarkY-LunarG"><img src="https://avatars2.githubusercontent.com/u/16328578?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MarkY-LunarG](https://github.com/MarkY-LunarG) (MIGRATED)**
_Tuesday May 08, 2018 at 16:50 GMT_

----

Since this is a validation layer item, I'm assigning it to @mark-lunarg, he can re-assign it as necessary.  Thanks @danginsburg for the suggestion.

**Comment by MarkY-LunarG** [comment]
Assign this to myself for now for a first run at this.

**Comment by mark-lunarg** [comment]
This issue has been subsumed by tracking issue #679
