### ISSUE TITLE
Incorrect subpass resolve error?

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-ValidationLayers#943]
I'm trying to get color resolve working with subpasses, and I get a validation error that doesn't make sense. What I have is:

    VkAttachmentReference colorRef = { 0, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL };

    subpassDesc.pColorAttachments = &colorRef;
    subpassDesc.pResolveAttachments = &colorRef;
    subpassDesc.pPreserveAttachments = nullptr;

This results in the following validation error:

> subpass 0 uses attachment 0 as both resolve and color attachment. The Vulkan spec states: Each element of pPreserveAttachments must not also be an element of any other member of the subpass description

The corresponding validation comes from this line:

    } else if (uses & ~ATTACHMENT_INPUT || (uses && (new_use == ATTACHMENT_RESOLVE || new_use == ATTACHMENT_PRESERVE))) {

and complains about preserve, but the code also includes resolve. This seems incorrect.

Nevertheless, following the validation code and using the following:

    VkAttachmentReference colorRef = { 0, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL };
    VkAttachmentReference unusedRef = { VK_ATTACHMENT_UNUSED, VK_IMAGE_LAYOUT_UNDEFINED };

    subpassDesc.pColorAttachments = &unusedRef;
    subpassDesc.pResolveAttachments = &colorRef;
    subpassDesc.pPreserveAttachments = nullptr;

instead gives this validation error (which makes more sense):

> Subpass 0 requests multisample resolve from attachment 4294967295 which has attachment=VK_ATTACHMENT_UNUSED. The Vulkan spec states: If pResolveAttachments is not NULL, for each resolve attachment that is not VK_ATTACHMENT_UNUSED, the corresponding color attachment must not be VK_ATTACHMENT_UNUSED

---

It's possible I'm not doing resolve correctly. What I'm trying to achieve is "do multisampled rendering, resolve into a singlesampled attachment and discard the multisampled result". This should at least be possible (as an optimization) on tiling GPUs.

**Comment by chrisforbes** [comment]
You're using it wrong. The color attachment should be the multisample attachment you want to render into; the resolve attachment should be the single-sampled attachment you want to resolve that into.

**Comment by mark-lunarg** [comment]
@ShabbyX, I'll defer closing this issue to you, if you are satisfied with @chrisforbes answer -- Thanks!

**Comment by ShabbyX** [comment]
Yes, sorry, I later realized I was misusing the API. I had been trying to use this as a more flexible `vkCmdResolveImage` (where a single-draw-call subpass would do something like flipping, and the subpass would resolve the image), in which I didn't need the actual multisampled result to be stored.
