### ISSUE TITLE
Incorrect template update decoding for inline uniform blocks

### ISSUE THREAD

**Issue by rg3igalia** [KhronosGroup/Vulkan-ValidationLayers#944]
When validating vkUpdateDescriptorSetWithTemplate, the templated update is converted to a normal update before being validated using cvdescriptorset::DecodedTemplateUpdate. This conversion fails to properly set descriptorCount for inline uniform blocks, which should match the value of dataSize inside the VkWriteDescriptorSetInlineUniformBlockEXT extension structure[1]. This is correctly validated later, resulting in code getting spurious validation errors with VUID VUID-VkWriteDescriptorSet-descriptorType-02220.

[1] https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VkWriteDescriptorSet

**Comment by mark-lunarg** [comment]
Fixed by PR #945.
