### ISSUE TITLE
2 subpass use same depth_stencil attachment as READ_ONLY

### ISSUE THREAD

**Issue by liufachen** [KhronosGroup/Vulkan-ValidationLayers#948]
My vulkan version is 1.1.106.0

The problem is : subpass “1” use color attachment A and subpass “2” use color attachment B, both use the same depth_stencil attachment as VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL.
The validation say:“A dependency between subpasses 1 and 2 must exist but one is not specified”, but Doc say:“If two subpasses use the same attachment in different layouts, and both layouts are read-only, no subpass dependency needs to be specified between those subpasses.”.

My problem is what mistake i made so i need provide a subpass-dependendcy.

I appreciate your time and help, i fought this problem almost 2 days, and hope someone could give me a help and thanks again.

and more information please refer: https://community.khronos.org/t/2-subpass-use-same-depth-stencil-attachment-as-read-only/104058/5

**Comment by tobine** [comment]
I believe there's a bug in the layers related to this. Specifically in subpass dependency [checking](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/core_validation.cpp#L8822) we definitely don't account for the case quoted from the spec:

> If two subpasses use the same attachment in different layouts, and both layouts are read-only, no subpass dependency needs to be specified between those subpasses.

For this specific bug the attachment is not "in different layouts" it's in the same layout. However, I think this may be a spec issue as I don't believe there should be a subpass dependency if both subpasses access the attachment in read-only layouts regardless of whether the layouts are the same or not.

**Comment by liufachen** [comment]
I appreciate for your help and hope this issue will be closed in the feature.

Thank you tobine.

**Comment by jzulauf-lunarg** [comment]
@tobine  -- did you open spec issue (or propose an MR) for the spec issue.  It always makes me nervous to get Validation ahead of the spec in this sense, without at least some grunts of affirmation out of the WG.  

@mikes-lunarg

**Comment by jzulauf-lunarg** [comment]
@tobine  -- does the following give enough cover to say that  read-only attachments (input or read only depth stencil) don't require subpass dependency  w.r.t. other read references to the same attachment. The "different layouts" section of the spec is then just further clarification that even image layout transitions between read only formats (and image layout transitions can *write*) don't require them *either*.

> Care should be taken to avoid a data race here; if any subpasses access attachments with overlapping memory locations, and one of those accesses is a write, a subpass dependency needs to be included between them.

**Comment by tobine** [comment]
@jzulauf-lunarg That helps but doesn't seem conclusive. I submitted a spec edit and tagged you on it to clarify that no subpass dependency is required between subpasses using the same attachment in any read-only layouts (regardless of if the layouts are the same or not)

**Comment by oddhack** [comment]
The spec part of this should be addressed in the 1.1.117 spec update. Please close if that's all that needs to be done for this issue.
