### ISSUE TITLE
Script to summarize CI test results across all device profiles

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#95]
**Issue by [tobine](https://github.com/tobine) (MIGRATED)**
_Tuesday May 08, 2018 at 22:22 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2657_

----

Currently there are a number of tests (10ish) that are skipped on all device profiles in CI. The current giant scrawl of results across 7 device profiles makes it difficult to recognize gaps like this.
To simplify test result analysis, I'm recommending adding a script that will parse the results across all device profiles and then print a summary for each test that tells how many times it passed and how many times that it had unexpected errors. If there are tests that don't run at all, this script should flag them.
Once all tests are running, any test that's added that doesn't hit any device profiles should cause a CI fail. Such tests should either be updated so that they correctly run on at least one profile, or a profile should be modified so that it will cause the test to be run.

**Comment by karl-lunarg** [comment]
Needs to be assigned to William Henning, after he's added to collaborator list.

**Comment by mark-lunarg** [comment]
Moved to CI repo/projects list.
