### ISSUE TITLE
vkQueuePresentKHR with invalid VkQueue doesn't trigger any validation layers warnings

### ISSUE THREAD

**Issue by Kadowns** [KhronosGroup/Vulkan-ValidationLayers#950]
Reopening this issue here, initially i've posted it on on Vulkan-Docs repo.

My application was crashing (without any exceptions or validation layers warnings) when calling vkQueuePresentKHR with an invalid VkQueue. Fixed it by properly calling vkGetDeviceQueue();

It would be nice if validation layers warned me about my mistake, just like when other calls are made with invalid handles.

SDK version is 1.1.106.0.

**Comment by mark-lunarg** [comment]
@Kadowns, thanks for the report.  Unfortunately, for a host of reasons, the current architecture does not allow validating dispatchable handles (instance, physicaldevice, device, commandbuffer, and queue).  While adding this support might be possible, it would be brittle and perhaps introduce unwelcome performance impacts.
