### ISSUE TITLE
GPU-assisted Validation for VK_EXT_buffer_device_address

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/Vulkan-ValidationLayers#963]
This issues announces intent to implement GPU-assisted validation layer of VK_EXT_buffer_device_address.

We are assuming familiarity with the general GPU-assisted validation mechanism.

The layer will instrument all shader references through PhysicalStorageBuffer pointers. The instrumentation will first check if the base pointer has been issued from vkGetBufferDeviceAddressEXT. It will then check that the offset does not exceed the length of the buffer. This will be accomplished with an auxiliary lookup buffer specially created and initialized by the layer.

Any question, concerns or additional suggestions are welcome.

**Comment by jeffbolznv** [comment]
What do you mean by "the base pointer and offset"? You'll just have a pointer, and need to check that it's inside the range of addresses of some buffer. I think that's what you mean, but the wording is weird.

**Comment by greg-lunarg** [comment]
By our reading of the spec, for shaders that are using the PhysicalStorageBuffer64EXT addressing model, for each load or store in the PhysicalStorageBuffer storage class, the "base pointer" of the pointer is recursively defined as: if the pointer is an OpAccessChain, return the "base pointer" of its base, else return the pointer.

As for offset, that is the difference between the "base pointer" of the load or store and the final pointer that is being referenced.

**Comment by jeffbolznv** [comment]
The app can pass in or construct (e.g. convert to int, do math, convert back) arbitrary pointers, the only rule is that the pointer value used in a memory access instruction must be inside some buffer.

**Comment by greg-lunarg** [comment]
So going to your Example in https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GLSL_EXT_buffer_reference.txt

you are saying that it is not necessarily true that a value of type blockType was returned by vkGetBufferDeviceAddressEXT. Instead, maybe the app took the address of a buffer using vkGetBufferDeviceAddressEXT and then manufactured  a bunch of blockType buffers by sub-dividing the original buffer using integer math, being careful to get the alignment right.

**Comment by jeffbolznv** [comment]
Yes, that's right.

**Comment by greg-lunarg** [comment]
OK. We can deal with that. Thanks!

**Comment by mark-lunarg** [comment]
@greg-lunarg, is there a need to keep this issue open?  Or maybe fold it into the [GPUAV tracking issue](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/852)?  Thanks!

**Comment by greg-lunarg** [comment]
@jeffbolznv What do you think will be the typical number of different buffers that will have vkGetBufferDeviceAddressEXT called on them during a game session?

**Comment by jeffbolznv** [comment]
I'd expect it to be a significant portion of the app's buffers, so could be anywhere from tens to hundreds or even more.

**Comment by greg-lunarg** [comment]
> is there a need to keep this issue open? Or maybe fold it into the GPUAV tracking issue?

@mark-lunarg While this is in active development, I think it makes sense for it to have its own issue. My very recent exchange with JeffB is a good example of its usefulness.

**Comment by greg-lunarg** [comment]
As currently planned, this validation will require the shaderInt64 member of VkPhysicalDeviceFeatures to be true since instrumentation is going to need to enable Int64 SPIR_V capability so that the instrumented shader can do the 64 bit arithmetic and comparisons required to make sure pointers are in range one of the queried buffers. The validation layer will have to check for this support early on.

**Comment by Tony-LunarG** [comment]
With the KHR version now accounted for, I'm closing this
