### ISSUE TITLE
Using VK_VALIDATION_FEATURE_DISABLE_CORE_CHECKS_EXT in vk_layer_settings causes hang.

### ISSUE THREAD

**Issue by mattruschnv** [KhronosGroup/Vulkan-ValidationLayers#964]
I'm able to disable other validation layer components in various combinations, but if I try to disable core validation, either in combination or in isolation, my applications will fail to load / never be responsive. This is seen both when I try to disable via vk_layer_settings.txt or when I hardcode the feature off by making modifications in chassis.cpp.

**Comment by mark-lunarg** [comment]
@mattruschnv, this is when using the Khronos layer, yes?  I'll take a look first-thing Monday.

**Comment by mattruschnv** [comment]
It can be reproduced by setting VK_INSTANCE_LAYERS to either VK_LAYER_LUNARG_standard_validation or VK_LAYER_KHRONOS_validation (which are the same thing, I think) in your env variables on windows.

**Comment by mark-lunarg** [comment]
Thanks @mattruschnv!
