### ISSUE TITLE
Bake codegen files into repo

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-ValidationLayers#965]
Currently many layer files are code-generated during the layer build. The proportion of build time spent on the codegen is high and can cause significant use of CPU cycles on build systems that pull and build VVL repo from scratch while doing large-scale testing.
As as common solution I'd like for the code-gen'd files to be committed into the repo so that the default build path can just use them without the code-gen step.
With this change, there should also be a new update to CI system to make sure that the files output by codegen match the code-gen'd files that are checked-in. The committed files should only need to be updated during the header roll process.

**Comment by mikes-lunarg** [comment]
Added in #1033
