### ISSUE TITLE
Releasing a fence, whose payload has been exported to an external handle using reference transference and later imported to >=1 fences, does not trigger any warning

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#97]
**Issue by [DominikWitczakAMD](https://github.com/DominikWitczakAMD) (MIGRATED)**
_Wednesday May 09, 2018 at 09:37 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2660_

----

Releasing such a "master" fence whose payload is being used by other active fence instances within a process renders remaining fences either hopelessly useless (in case of permanent import) or useless until reset (in case of temporary import). In case of the former, this probably deserves a warning.

**Comment by mark-lunarg** [comment]
Adding to the Assistant Layer tracking issue #24, as this is a warning.
