### ISSUE TITLE
Warn when vkQueuePresentKHR() returns VK_SUBOPTIMAL_KHR

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-ValidationLayers#979]
I know we removed many PERF WARNINGS in VVL, but there is one case that our team has identified as common and important enough that we believe it should be added.
In the case where vkQueuePresentKHR() returns VK_SUBOPTIMAL_KHR, we would like a perf warning to be issued to the app based on the spec text for this return code:

>  VK_SUBOPTIMAL_KHR - Presentation will still succeed, subject to the window resize behavior, but the swapchain is no longer configured optimally for the surface it targets. Applications should
query updated surface information and recreate their swapchain at the next convenient
opportunity

We see this on Android, often due to preTransform mis-matches and the perf hit can be significant so we'd like VVL to proactively notify apps so they can recreate their swapchain for optimal perf.

There's currently a spot in CoreChecks::PostCallRecordQueuePresentKHR() where VK_SUBOPTIMAL_KHR is treated in same fashion as VK_SUCCESS that can be modified to throw the perf warning:

`if (local_result != VK_SUCCESS && local_result != VK_SUBOPTIMAL_KHR) continue;  // this present didn't actually happen.`

**Comment by mark-lunarg** [comment]
This could probably go in stateless validation, right?  Maybe we should take all of these warnings that we don't want to put in the assistant layer, and stick them in a separate VO that would be disabled by default.  We're sliding back down the slippery slope.

**Comment by tobine** [comment]
Yes, can go in stateless for sure.

**Comment by locke-lunarg** [comment]
@tobine Only for `vkQueuePresentKHR()`? How about `vkAcquireNextImageKHR()`?

**Comment by tobine** [comment]
@locke-lunarg I had wondered the same thing initially but was told that just vkQueuePresentKHR() is the key concern here.

**Comment by locke-lunarg** [comment]
@tobine  Thanks.
