### ISSUE TITLE
Positive Test to validate vk_safe_struct.cpp GraphicsPipelineCreateInfo changes

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-ValidationLayers#981]
vk_safe_struct.cpp, which is code-generated, will make some modifications, starting [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/scripts/helper_file_generator.py#L976), to the state in the VkGraphicsPipelineCreateInfo struct based on whether or not rasterizerDiscardEnable is true.

According to the spec [VUs](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-rasterizerDiscardEnable-00750) for VkGraphicsPipelineCreateInfo, it *seems* like those modifications should have no effect on functionality. However in certain instances, such as [this](https://bugs.chromium.org/p/angleproject/issues/detail?id=3509), those modifications are causing issues.

I would like to see a positive test that validates these modifications on different devices by creating a GraphicsPipeline with rasterizerDiscardEnable set to true and set that includes VS & FS pipeline stages and sets pViewportState, pMultisampleState, pDepthStencilState, and pColorBlendState to NULL.

If/when the positive test reveals driver crashes, please follow-up with appropriate vendors to identify bug in their driver and/or issues with how validation is modifying the state.

Below is a debug cut-and-paste of validation-layer modified VkGraphicsPipelineCreateInfo state that's causing the driver crash on the issue above. The test can match this state and initially just copy some simple shaders used by other validation tests. Sorry the formats a little messy. This is just pull straight out of VS debugger.

`
-		local_pCreateInfos	0x000001d662836a48 {sType=VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO (28) pNext=0x0000000000000000 ...}	safe_VkGraphicsPipelineCreateInfo *
		sType	VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO (28)	VkStructureType
		pNext	0x0000000000000000	const void *
		flags	0	unsigned int
		stageCount	2	unsigned int
-		pStages	0x000001d661528058 {sType=VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO (18) pNext=0x0000000000000000 ...}	safe_VkPipelineShaderStageCreateInfo *
		sType	VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO (18)	VkStructureType
		pNext	0x0000000000000000	const void *
		flags	0	unsigned int
		stage	VK_SHADER_STAGE_VERTEX_BIT (1)	VkShaderStageFlagBits
		module	0x0000000000000049 {...}	VkShaderModule_T *
+		pName	0x00007ffe90fc8b78 "main"	const char *
+		pSpecializationInfo	0x0000000000000000 <NULL>	safe_VkSpecializationInfo *
-		pVertexInputState	0x000001d6627581d0 {sType=VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO (19) pNext=0x0000000000000000 ...}	safe_VkPipelineVertexInputStateCreateInfo *
		sType	VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO (19)	VkStructureType
		pNext	0x0000000000000000	const void *
		flags	0	unsigned int
		vertexBindingDescriptionCount	1	unsigned int
-		pVertexBindingDescriptions	0x000001d662228700 {binding=0 stride=16 inputRate=VK_VERTEX_INPUT_RATE_VERTEX (0) }	const VkVertexInputBindingDescription *
		binding	0	unsigned int
		stride	16	unsigned int
		inputRate	VK_VERTEX_INPUT_RATE_VERTEX (0)	VkVertexInputRate
		vertexAttributeDescriptionCount	1	unsigned int
-		pVertexAttributeDescriptions	0x000001d662228c50 {location=0 binding=0 format=VK_FORMAT_R32G32B32A32_SFLOAT (109) ...}	const VkVertexInputAttributeDescription *
		location	0	unsigned int
		binding	0	unsigned int
		format	VK_FORMAT_R32G32B32A32_SFLOAT (109)	VkFormat
		offset	0	unsigned int
-		pInputAssemblyState	0x000001d66282ee10 {sType=VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO (20) pNext=0x0000000000000000 ...}	safe_VkPipelineInputAssemblyStateCreateInfo *
		sType	VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO (20)	VkStructureType
		pNext	0x0000000000000000	const void *
		flags	0	unsigned int
		topology	VK_PRIMITIVE_TOPOLOGY_POINT_LIST (0)	VkPrimitiveTopology
		primitiveRestartEnable	0	unsigned int
+		pTessellationState	0x0000000000000000 <NULL>	safe_VkPipelineTessellationStateCreateInfo *
+		pViewportState	0x0000000000000000 <NULL>	safe_VkPipelineViewportStateCreateInfo *
-		pRasterizationState	0x000001d661116120 {sType=VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO (23) pNext=0x0000000000000000 ...}	safe_VkPipelineRasterizationStateCreateInfo *
		sType	VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO (23)	VkStructureType
		pNext	0x0000000000000000	const void *
		flags	0	unsigned int
		depthClampEnable	0	unsigned int
		rasterizerDiscardEnable	1	unsigned int
		polygonMode	VK_POLYGON_MODE_FILL (0)	VkPolygonMode
		cullMode	0	unsigned int
		frontFace	VK_FRONT_FACE_COUNTER_CLOCKWISE (0)	VkFrontFace
		depthBiasEnable	0	unsigned int
		depthBiasConstantFactor	0.000000000	float
		depthBiasClamp	0.000000000	float
		depthBiasSlopeFactor	0.000000000	float
		lineWidth	1.00000000	float
+		pMultisampleState	0x0000000000000000 <NULL>	safe_VkPipelineMultisampleStateCreateInfo *
+		pDepthStencilState	0x0000000000000000 <NULL>	safe_VkPipelineDepthStencilStateCreateInfo *
+		pColorBlendState	0x0000000000000000 <NULL>	safe_VkPipelineColorBlendStateCreateInfo *
+		pDynamicState	0x0000000000000000 <NULL>	safe_VkPipelineDynamicStateCreateInfo *
		layout	0x000000000000001c {...}	VkPipelineLayout_T *
		renderPass	0x0000000000000020 {...}	VkRenderPass_T *
		subpass	0	unsigned int
		basePipelineHandle	0x0000000000000000 <NULL>	VkPipeline_T *
		basePipelineIndex	0	int
`

**Comment by mark-lunarg** [comment]
Note that there may be some validation issues related to rasterizerDiscardEnable, see issue #930.

**Comment by tobine** [comment]
Ah, interesting, I hadn't seen #930 but agree with you comment there that validation should be ignoring validating pMultisampleState (and other states I recommend to be "NULL" in this issue) for Gfx Pipelines w/  rasterizerDiscardEnable == TRUE.
That issue may need some spec clarification as well as layer fixes.

**Comment by locke-lunarg** [comment]
Fixed [issue #1099 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1099)
