### ISSUE TITLE
Update FormatHandle to output final format

### ISSUE THREAD

**Issue by jzulauf-lunarg** [KhronosGroup/Vulkan-ValidationLayers#983]
See #679 --

Update the format handle to output agreed upon format

__handleTypeName__ 0x%l016llx [__definedName__]

The handle type name can be retrieved from from the type traits of the handle.

Note: Given the way the spec defines handles fo 32 bit compilations, __handleTypeName__ will be "NONDISPATCHABLE" (or similar) for all non-dispatchable handles. If there is no __definedName__ it will be replaced by the empty string

Tests will also need to be updated s.t. they recognize new messages -- note that any expected error that is looking for __handleTypeName__ will potentially see different messages on 32 and 64 bit, so should be converted to look for the VUID string if possible.

**Comment by mark-lunarg** [comment]
@locke-lunarg, is the work here now done?  If so, please close this issue.
