### ISSUE TITLE
libVKLayer_core_validation.so cannot be recognized in VulkanLoader (from even older codes)

### ISSUE THREAD

**Issue by byumjin** [KhronosGroup/Vulkan-ValidationLayers#987]
I'm sorry.
I opened new issue here because I couldn't re-open my previous issue (#985).

So, what I want to do is, I would like to test my codes with those pre-built layers built by myself.
It seems like my android app can't recognize 'VK_LAYER_KHRONOS_validation' at all.
This is why I tried the old layers, but 'VK_LAYER_LUNARG_core_validation' still cannot be loaded.

I guess my Vulkanloader (1.0 version) is not compatible with the latest codes in this repository, but I'm not sure.
Also, I tried older codes from version (8f93d488cf - Mar 11) which doesn't generated 'VK_LAYER_KHRONOS_validation'. But, still, my app can't recognize 'VK_LAYER_LUNARG_core_validation' when I use the pre-built libs from the codes.

Unfortunately, I can't wait for the new NDK until July.

Should I try much older codes?
Or do you have any other suggestions?

Thank you.

**Comment by mark-lunarg** [comment]
#985 was reopened, please reference that issue for updates or other further actions.
