### ISSUE TITLE
Validate non-attachment uses of attachment image memory

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#99]
**Issue by [cdwfs](https://github.com/cdwfs) (MIGRATED)**
_Thursday May 10, 2018 at 00:47 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2665_

----

The spec states in [section 7.3 Framebuffers](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#_framebuffers):

> Applications **must** ensure that all accesses to memory that backs image subresources used as attachments in a given renderpass instance either happen-before the [load operations](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#renderpass-load-store-ops) for those attachments, or happen-after the [store operations](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#renderpass-load-store-ops) for those attachments.

This requirement is not currently enforced by the validation layers, and the resulting bugs can be quite time consuming to track down.

A decent (but certainly non-exhaustive) start would be to add a check to ensure that none of the images bound as descriptors (and used by an active shader as defined in [section 8.12](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#shaders-staticuse)) are also attachments for the current render pass.

**Comment by ziga-lunarg** [comment]
@spencer-lunarg Would you agree that this is now covered by #6782

**Comment by spencer-lunarg** [comment]
yes, this is an old issue, but it are those VUs... agree, also we have now effort going to poke the WG and figure out what are the "invalid" accesses of a `VkImage` instead of us just guessing the limit
